### ISSUE TITLE
dry canals are displayed as blue dashes

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1003]
Pernamently dry derelict canal ( http://wiki.openstreetmap.org/wiki/Tag:waterway%3Dderelict_canal ) is currently displayed as blue, transparent dashes. I thing that it would be better to use some symbol that is not blue - but I have no good suggestions.

example of a current rendering: http://www.openstreetmap.org/?mlat=49.20021&mlon=16.22416#map=17/49.20021/16.22416

![selection_003](https://cloud.githubusercontent.com/assets/899988/4447896/8ebb0894-480e-11e4-8699-594e07fefa54.png)

**Comment by matkoniecz** [comment]
Or maybe just stop displaying this feature?

**Comment by imagico** [comment]
Yes, it seems this tag is primarily used in the UK and New England for older canals that still exist that were formerly used for transport of goods but today are either no more used at all or just for water sports etc.  For these the dashed rendering is inappropriate and misleading.

It could be considered to render it just like waterway=canal but the wiki description of the tag is vague and ambiguous - both in terms of use of the canal and if it is water filled or not.  So either the wiki should be clarified so it can be properly rendered or the features with that tag should be re-tagged.

**Comment by matkoniecz** [comment]
I posted request to improve documentation on OSM wiki.

**Comment by sommerluk** [comment]
Current rendering can be confused with intermittend waterways.

**Comment by sommerluk** [comment]
I would not mind to drop the rendering. Blue should be reserved for actual water. As we do not render valleys or similar things either, I think it might be more consistent to drop delerict_canal also.

**Comment by kocio-pl** [comment]
I think it should be rendered as https://wiki.openstreetmap.org/wiki/Tag%3Abarrier%3Dditch - this was not the intended usage, but in fact it is kind of barrier now.

**Comment by matkoniecz** [comment]
I still think that usage of this tag should not be encouraged and it should not be rendered at all (all mentioned problems are still present).

**Comment by kocio-pl** [comment]
Few questions: you wrote that it's "pernamently dry" in the original post, do you still think it's the case? Do you remember what was the outcome of discussion? What is the downside of rendering it as a ditch?

**Comment by matkoniecz** [comment]
> Do you remember what was the outcome of discussion?

Nobody bothered to fix documentation, I found thread at https://lists.openstreetmap.org/pipermail/tagging/2015-August/026101.html

From what I see it degenerated into discussion whatever disused:amenity=pub or amenity=pub + disused=yes is preferable.

>  you wrote that it's "pernamently dry" in the original post, do you still think it's the case?

I think that at least some derelict canals are permanently dry and that rendering is counterintuitive in such cases.

> What is the downside of rendering it as a ditch?

I think that given that it is not popular (2k uses worldwide), meaning is unclear, may be tagged with better tags, documentation is unclear, nobody bothered to improve the documentation - I think that rendering it at all is promoting broken tag.

Also, it is quite likely that it is not feature similar to ditch. It may be anything from canal closed for transport, through overgrown canal throug permanently dry canal to a place with faint traces of a canal that was there long time ago.

**Comment by lakedistrictOSM** [comment]
This is an example of a section of an old canal that I've tagged as `waterway=derelict_canal`
![](https://www.visitcumbria.com/wp-content/gallery/sedgwick/3-sedgwickaqueduct2.jpg)

The canal here is dry and is overgrown with thick vegetation. (left side of image)

It could also be mapped with a lifecycle prefix, eg `abandoned:waterway=canal`.
