### ISSUE TITLE
Eiffel tower dissappeared beneath highway=pedestrian

### ISSUE THREAD

**Issue by mboeringa** [gravitystorm/openstreetmap-carto#1004]
I just noticed the Eiffel tower no longer displays fully. Most of it seems hidden beneath a stretch of highway=pedestrian as area, _or something else prevents it from rendering_:

http://www.openstreetmap.org/#map=17/48.85740/2.29346

I also don't see a label for it, so something else in the tagging may prevent it from rendering...

**Comment by gorn** [comment]
Eifell tower still missing on Carto (two years later).

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 01 ago 2016, alle ore 13:16, Jakub Tesinsky <notifications@github.com> ha scritto:
> 
> Eifell tower still missing on Carto (two years later).
> 


are you missing a label for the tower? Because the footprint is clearly rendered and not "missing": http://www.openstreetmap.org/#map=17/48.85817/2.29488
The label is hard to achieve at reasonable zoom levels because of tower subtags not being available until hstore gets activated

**Comment by HolgerJeromin** [comment]
This is a duplicate of  #688 which is still open, that's why the current issue is still valid. 
Discussion is best placed on the open issue.

**Comment by gorn** [comment]
Eifell tower still missing on Carto (four years later).

**Comment by Adamant36** [comment]
Things can take a while sometimes ;)

(this opinion doesn't represent those of the maintainers)

**Comment by matkoniecz** [comment]
> Eifell tower still missing on Carto (four years later).

And #688 is still open and waiting for solution or decision that it will not be changed.

In general issues are fixed once someone makes code that is good enough to fix them properly.

See https://github.com/gravitystorm/openstreetmap-carto/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc for issues sorted from oldest.
