### ISSUE TITLE
ele with alpine_hut when mapped as a building

### ISSUE THREAD

**Issue by al--** [gravitystorm/openstreetmap-carto#101]
Wish: If a building is tagged as tourism=alpine_hut, it would be fine if the ele was shown (as is done if it is mapped as a node).

![91464 1](https://f.cloud.github.com/assets/1458456/916010/7fc54ae0-fe7f-11e2-8678-e2866fa3fcd5.png)
http://www.openstreetmap.org/browse/way/232521425
![91450 1](https://f.cloud.github.com/assets/1458456/916026/dd974196-fe7f-11e2-8116-0b266eec7599.png)
http://www.openstreetmap.org/browse/node/389786530

**Comment by pnorman** [comment]
Reopening, I think there's still some changes that need to be done to enable this.

**Comment by math1985** [comment]
After #2823 is merged, this will be the oldest open issue!

**Comment by kocio-pl** [comment]
@sommerluk I guess you could extend elevation rendering for polygons or help me with this? 

I've tried to copy this block:

https://github.com/gravitystorm/openstreetmap-carto/blob/8862ee40103ce9addd0b45c79dcfcd436c3dcd91/project.mml#L2020-L2024

and this one (without "natural" part):

https://github.com/gravitystorm/openstreetmap-carto/blob/8862ee40103ce9addd0b45c79dcfcd436c3dcd91/project.mml#L2085-L2092

to a `text-poly` layer, but then I get:
```
Postgis Plugin: ERROR:  column "elevation" does not exist
```

The `text-point` layer doesn't have this problem.

**Comment by sommerluk** [comment]
I’m not sure. Could you make the code available on Github?

Just raw guess: `text-point` is composed by a `SELECT` and a sub-`SELECT`. The code for the name-elevation-combination is part of the outer `SELECT` and needs the column `elevation` which does _not_ come from the database (the database only provides `ele`), but it created in the inner `SELECT`. `text-poly` does not have nested `SELECT`. If you haven’t created one, you cannot query `elevation` at this level.

**Comment by kocio-pl** [comment]
You were right probably, I didn't spot the SELECT is nested. Could you try to fix this issue?
