### ISSUE TITLE
Mention Kosmtik in documentation

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1015]
We're mentioning TileMill in the docs - we should also mention Kosmtik, particularly as it works out of the box with YAML MML files.

This would touch INSTALL.md and CONTRIBUTING.md

cc @yohanboniface

**Comment by math1985** [comment]
This has been done in the meanwhile.

**Comment by math1985** [comment]
By the way, for those using Kosmtik: I created a little tool for comparing the development version on your local machine with the version on openstreetmap.org. It can be found here:

http://bl.ocks.org/math1985/raw/7d2b0538a8b64b9d31e2

No install or set-up is necessary, just make sure that you have a (default) Kosmtik installation running and go the URL.

Note that Kosmtik uses Mapnik 3 by default and openstreetmap.org uses Mapnik 2, so this causes some differences in font rendering.

**Comment by math1985** [comment]
By the way, for those using Kosmtik: I created a little tool for comparing the development version on your local machine with the version on openstreetmap.org. It can be found here:

http://bl.ocks.org/math1985/raw/ceef79a7d2c45a02cf60f48869eec754

No install or set-up is necessary, just make sure that you have a (default) Kosmtik installation running and go the URL.

Note that Kosmtik uses Mapnik 3 by default and openstreetmap.org uses Mapnik 2, so this causes some differences in font rendering.

**Comment by yohanboniface** [comment]
> By the way, for those using Kosmtik: I created a little tool for comparing the development version on your local machine with the version on openstreetmap.org. It can be found here:

Just curious: why not using the kosmtik-map-compare plugin?

**Comment by math1985** [comment]
> Just curious: why not using the kosmtik-map-compare plugin?

 To be honest: I wasn't aware of its existence.

I also can't quite get it to work now I try it. I ran `node index.js plugins --install kosmtik-map-compare
` and I added `compareUrl: http://c.tile.openstreetmap.org/{z}/{x}/{y}.png` to the top of my yaml file, is there anything else I need to do?

I like the ability to slide left and right, it's really helpful for comparing. Is this also available in kosmtik-map-compare, or would it be possible to make it available?

**Comment by yohanboniface** [comment]
> I also can't quite get it to work now I try it. I ran node index.js plugins --install kosmtik-map-compare and I added compareUrl: http://c.tile.openstreetmap.org/{z}/{x}/{y}.png to the top of my yaml file, is there anything else I need to do?

Humm, what is not working specifically?

> I like the ability to slide left and right, it's really helpful for comparing. Is this also available in kosmtik-map-compare, or would it be possible to make it available?

Not available, but that's a good point. Should be added, yes.

**Comment by math1985** [comment]
> Humm, what is not working specifically?

Now it works - I might have overlooked the 'compare' button the first time I tried.

> Not available, but that's a good point. Should be added, yes.

That would be really cool!
