### ISSUE TITLE
amenity=hospital area should be labeled based on size

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#1019]
Non-building `amenity=hospital` areas are labeled with a red ⊕ at z15, and with an icon + name at z16 and above, but nothing at z14 or below ([example](http://www.openstreetmap.org/#map=14/39.2523/-84.3391)). The label should appear based on the area’s area (like #941), since some hospital campuses can be quite large.

![z14](https://cloud.githubusercontent.com/assets/1231218/4537624/8e38e904-4de0-11e4-9718-1747d0702d97.png)
![z15](https://cloud.githubusercontent.com/assets/1231218/4537656/0c0a58e0-4de1-11e4-87f3-896c78115059.png)

**Comment by Tomasz-W** [comment]
@kocio-pl Please close this ticket as duplicate.
Continue further discussion in https://github.com/gravitystorm/openstreetmap-carto/issues/3284
