### ISSUE TITLE
Secondary and trunk color too similar to landuse colors

### ISSUE THREAD

**Issue by joakimfors** [gravitystorm/openstreetmap-carto#102]
Secondary and trunk are rendered with a color that is way too similar to landuse=forest/meadow/farmland. Makes it quite difficult to see them at lower zooms.

One solution is to make landuse less saturated and even more pale. This would have the added benefit of making the difference between the basemap color and landuse less distinct which, IMHO, equals a prettier map.

![screen shot 2013-08-07 at 12 47 12](https://f.cloud.github.com/assets/1665340/923603/43b8de60-ff4f-11e2-97a9-e1ca79d6dd39.png)

Spot the secondaries and trunks. ;)

**Comment by matkoniecz** [comment]
I prepared preliminary version of road style that solves this problem.

https://github.com/gravitystorm/openstreetmap-carto/compare/master...matkoniecz:new-road-style-z16-with-purple-pedestrians (currently zlevels 16, 10, 11, 12 are done, other may be poorly displayed).

![malmo](https://cloud.githubusercontent.com/assets/899988/8487552/223d21a6-210d-11e5-855d-ba06224bc22c.png)

Links to bigger comparison images:

Malmo
https://cloud.githubusercontent.com/assets/899988/8487558/3109f326-210d-11e5-9cbf-b63f80d29739.png
https://cloud.githubusercontent.com/assets/899988/8487559/310a7e2c-210d-11e5-9a0c-fc9dc64f58c5.png

Bolzano
https://cloud.githubusercontent.com/assets/899988/8487560/310cbcb4-210d-11e5-9f67-d4f94e1d317e.png
https://cloud.githubusercontent.com/assets/899988/8487561/310cdab4-210d-11e5-89af-1faf0ab4a61e.png

**Comment by joakimfors** [comment]
Very nice! One nit-pick is that motorway could be a bit darker/redder than trunk.

I also like the new more defined rendering of cycleways and footways, but I suspect that belongs to another case.

**Comment by matkoniecz** [comment]
I am considering making trunk/motorway redder, on worse screens it looks like primary. It is also harder than currently to immediately recognise given road as primary.

@joakimfors 
I am trying to reduce number of differently displayed road classes and I think that unification of motorway/trunk is the best bet. Such unification allows to clearly differentiate road classes without using all hues from blue through green to red as it is currently done.

I posted about footways at https://github.com/gravitystorm/openstreetmap-carto/pull/1359#issuecomment-117320217 as my proposed change was inspire by that pull request and there is no relevant open issue.

**Comment by imagico** [comment]
The color scheme in general seems to work nicely but the details still need work i think.  What does not work so well IMO:

* The colors appear very strong at low zooms, in particular the primary/secondary (which seem even stronger than motorway)
* The lack of or very weak outlining at z=12 does not seem to work too well, in particular on dark background.  From the Malmo high zoom example it seems the color relation between outline and fill is somewhat off for tertiary roads - compared to both primary/secondary and to residential it is too saturated and too bright.
* The purple for pedestrians does not seem such a good idea since similar colors are traditionally used for boundaries and air transport features.
* You might want to think about changing the blue color for highway=motorway_junction labels.

**Comment by matkoniecz** [comment]
@imagico 

> the details still need work i think

Yes, I agree. I am happy enough to show how it may work but it is not ready for PR.

> The colors appear very strong at low zooms, in particular the primary/secondary (which seem even stronger than motorway)

At this moment it is result of making secondary yellow strong enough to make it clearly visible on farmland, also for people with worse eyesight and on worse screens. Primary and trunk/motorway are getting redder just strong enough to make it clearly distinguishable.

The easiest solution is to make farmland even paler or allow secondary to be less noticeable on farmland.

> The lack of or very weak outlining at z=12 does not seem to work too well

Good idea for experiment.

> The purple for pedestrians does not seem such a good idea since similar colors are traditionally used for boundaries and air transport features.

Is it tradition as "in UK", "in this style", "typical worldwide"?

> You might want to think about changing the blue color for highway=motorway_junction labels.
Maybe also arrows on oneways. 

Thanks for feedback!

**Comment by imagico** [comment]
> At this moment it is result of making secondary yellow strong enough to make it clearly visible on farmland, also for people with worse eyesight and on worse screens. Primary and trunk/motorway are getting redder just strong enough to make it clearly distinguishable.
> 
> The easiest solution is to make farmland even paler or allow secondary to be less noticeable on farmland.

Currently the casing helps a lot at z>=12, it might be a good idea to use a somewhat different color at low zooms than the fill color at high zooms.

Farmland paler would in principle work for me but it would immediately collide with the bare ground base color.

> Is it tradition as "in UK", "in this style", "typical worldwide"?

in this style.

**Comment by 1ec5** [comment]
> Is it tradition as "in UK", "in this style", "typical worldwide"?

Certainly in this style at least. Boundaries are all purple, and so are hangars. In any case, pedestrian streets are usually shown muted in OSM styles. Streets are only highlighted with color when they're moe significant than unclassified. The purple makes the pedestrian street look similarly important.

**Comment by matkoniecz** [comment]
> Currently the casing helps a lot at z>=12, it might be a good idea to use a somewhat different color at low zooms than the fill color at high zooms.

In proposed style fill on low zoom levels is the same color as casing on high (fill on high is paler). Low zoom levels have no casing, maybe adding it would be a good idea...

> The purple makes the pedestrian street look similarly important.

The intention was mainly to make it clearly different. Many styles show highway=pedestrian like highway=footway but I am not really happy about it.

**Comment by imagico** [comment]
I don't think casing would do any good at z<12.  But the colors that work good for the casing at high zooms probably are not equally suited for the full line at low zooms - for that purpose i'd probably try it somewhat less saturated and if necessary to be well visible darker.

By the way - have you considered doing something about the dominance of minor roads in urban areas and the noise resulting from it at z=10/11?

**Comment by matkoniecz** [comment]
> By the way - have you considered doing something about the dominance of minor roads in urban areas and the noise resulting from it at z=10/11?

Yes, see comparison in https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/34957

For now z16 is ready, but I also tested this issue to ensure that selected colors for major road will be visible on lower zoom levels. Ensuring that minor roads will not be too visible is planned.

**Comment by matkoniecz** [comment]
@imagico 

> Farmland paler would in principle work for me but it would immediately collide with the bare ground base color.

I think that there is still plenty of space for making it paler - see http://www.openstreetmap.org/#map=11/52.0111/-1.5003. landuse=farmland dominates nearly everything else (maybe except road shields).

**Comment by dieterdreist** [comment]
2015-07-03 19:15 GMT+02:00 Mateusz Konieczny <notifications@github.com>:

> see http://www.openstreetmap.org/#map=11/52.0111/-1.5003.
> landuse=farmland dominates nearly everything else (maybe except road
> shields).
>


because it is bad mapping style ;-) Basically they started asserting
farmland to everything and are now slowly catching up with removing it
where there isn't actually farmland. Horrible to maintain as well (requires
either boring and timeconsuming splitting or will mutate to a multipolygon
monster). You can see this style a lot, unfortunately, similar to
landuse=residential in villages instead of place polygons...

**Comment by imagico** [comment]
Sorry for being ambiguous - with 'bare ground base color' i meant @bare_ground (#eee5dc), not @land-color (#f2efe9).

**Comment by matkoniecz** [comment]
@imagico 

> You might want to think about changing the blue color for highway=motorway_junction labels.

I have two versions - one with black labels, one with red ones. Red one is my preferred version.

https://cloud.githubusercontent.com/assets/899988/8511593/9858fcd4-231f-11e5-84e8-63266da45217.png

https://github.com/matkoniecz/road-style-preview/blob/master/Malmo%20-%20secondary%20new-road-style-z16-with-purple-pedestrians-_red%2011..19%20800px%20new-road-style-z16-with-purple-pedestrians%20-%3E%20red.png

**Comment by nebulon42** [comment]
Just wanted to say that this already looks like a great improvement, I'm looking forward to the proposal.

**Comment by kocio-pl** [comment]
@nebulon42 +1 :+1:

**Comment by jojo4u** [comment]
The red motorway junctions looks better than the black.

**Comment by imagico** [comment]
Seeing that i realize changing the label color is not as easy as i thought.  Black labels are confusing since there are a lot of black labels for other stuff and likewise there are quite a few brownish/reddish label types.  Blue is also used for railway stations etc. so it is not necessarily a bad idea to use it for all travel/transport structure related labels.

And the oneway arrows seem much better in blue as well.

**Comment by jojo4u** [comment]
About motorway equaling trunk:
One of the goals of carto ist the support of the mapper feedback loop. I also check the the map after my edits. Thus we should show the different kinds of highways we have if they aren't too similar (e.g. unclassified<->residential).
Another reason is that motorways are always dual carriageways while trunks are not (http://wiki.openstreetmap.org/wiki/Template:Highway:International_equivalence). Judging by this list trunks are sometimes "cheap" motorways but often the backbone of the national grid. IMHO trunks are as comparable to motorway as they are to primary. So what does the map display? Importance or quality of travel?
German maps usually show motorway and trunk as dual carriageway (http://mc.bbbike.org/mc/?lon=13.259246&lat=55.508148&zoom=12&num=3&mt0=mapnik&mt1=mapnik-german&mt2=hike_bike&mt3=falk-osm) have you tried it with motorway?

**Comment by joakimfors** [comment]
I agree with jojo4u. The standard carto rendering is as much a debugging tool as a navigation tool. Harder to spot mapping errors if you have to load the data in an editor instead of just looking at the map.

**Comment by jojo4u** [comment]
Colors: I find the secondary "honey yellow" quite unusual, I cannot "look away" from it. It has quite the same prominence as motorway,trunk,primary. Also the very pale yellow of tertiary is a bit confusing: I always look twice at tertiary vs. residential since the difference is so slight.

**Comment by ftrebien** [comment]
@jojo4u "So what does the map display? Importance or quality of travel?" From the debate about unsealed roads (#110), I think the map displays importance more prominently, and is going to add subtle hints about quality of travel in some (perhaps very specific) situations. I would say that rendering styles of tracks for grade1 to grade5 also follow that idea. It seems to me that "motorway" is always both important and high quality, whereas "trunk" is always important but quality varies (sometimes as good as motorway, sometimes [much less](https://wiki.openstreetmap.org/wiki/User:Ftrebien/Drafts/Generic_highway_classification_principles#Core_ideas), it mostly depends on which country one is talking about). Motorways and trunks are probably not equally important on average, but sometimes trunks can be as important as other motorways. To me, this means they should rendered similar (more similar than primary and secondary, for example), but not exactly the same.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 05.07.2015 um 19:03 schrieb Christoph Hormann <notifications@github.com>:
> 
> Blue is also used for railway stations etc. so it is not necessarily a bad idea to use it for all travel/transport structure related labels.


I believe a clear distinction between rail and road related features is desirable

**Comment by RobJN** [comment]
Trunks and Motorways are currently very different in how things are mapped in the UK. Primary and secondary are more similar so if you were looking at which roads to render in a similar way then those would be prime candidates for me. See for example the mapsurfer.net style on openstreetmap.ru

**Comment by math1985** [comment]
@matkoniecz Have you seen the [new OsmAnd online rendering](http://bl.ocks.org/tyrasd/6164696)? I"m not sure if I sent it to you before.

Left is our rendering, right is OsmAnd (it is no longer 'old Mapnik', ignore the cation).

**Comment by math1985** [comment]
@matkoniecz That's a good start!

I know too much feedback can be overwhelming, but would it be possible to produce some side-by-side examples so we have some comparison of different options?

I think living_street and pedestrian look much better in the new rendering.

I agree with the points on mapper-feedback loop, and I think all highway types should be distinct at at least some zoomlevel.

Have you tried a German-like style with a thick casing for trunk/primary?

**Comment by daganzdaanda** [comment]
Agree with all, this is already great! Thank you @matkoniecz !
I like that there is more contrast on the map again, now that most landuses are much softer. 

I see the difficulty in rendering the extra road classes that OSM uses, compared to other maps that have one or two classes less. But I agree with the "Mappers Loop" argument, so +1 for making trunk and motorway a bit different again. Maybe a darker red for motorway is good? 

An idea I got from looking at Google's maps: could we use line width to differentiate streets more often? Maybe tertiary and unclassified / residential could all be white with grey casing, but tertiary is wider?

**Comment by Rovastar** [comment]
I think these look too similar.  It is really hard to tell the difference between the road classifications. I have no idea, for example, which is the best/major roads to get around a city.

The reasoning behind combining the motorway/trunk is confusing and I am unclear what you are trying to acheive. We have a clear heiracarcy of roads and although in OSM some countries standards my combine them, others do not. We should stick to a overall heiracarcy and they should be notably distinct.

Also if there are clashes with existing items when adding new rendering but there are always at least 2 ways of solving this by fixing either feature. I still think we need to fix the greens first.

**Comment by matkoniecz** [comment]
@imagico
> The lack of or very weak outlining at z=12 does not seem to work too well, in particular on dark background.

Since this comment rendering changed a bit, especially on z12. https://github.com/gravitystorm/openstreetmap-carto/issues/1387#issuecomment-120274565 has preview of latest version on the dark backround (forest). Outlining is still quite weak - is it still a problemn after changes?

@imagico
> Sorry for being ambiguous - with 'bare ground base color' i meant @bare_ground (#eee5dc), not @land-color (#f2efe9).

@math1985 

> @matkoniecz Have you seen the new OsmAnd online rendering? I"m not sure if I sent it to you before.

I was unaware about it, thanks! BTW, is there now a place to compare current style with the old mapnik?


@math1985

> but would it be possible to produce some side-by-side examples so we have some comparison of different options

I posted some in the diary entry ( http://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35351 ) and the next week I will post next batch. Are you interested in some specific location/variation?

@math1985 @everybody
> I also agree the tertiary colour in the proposed rendering does not work very well.

I reverted tertiary colour to one before changes - and it seems that everybody prefers it this way.

> I agree with the points on mapper-feedback loop, and I think all highway types should be distinct at at least some zoomlevel.

I will add some way to differentiate motorway and trunk.

@math1985

> Have you tried a German-like style with a thick casing for trunk/primary?

Is trunk/primary instead of trunk/motorway intentional?

> An idea I got from looking at Google's maps: could we use line width to differentiate streets more often? Maybe tertiary and unclassified / residential could all be white with grey casing, but tertiary is wider? 

@daganzdaanda
I will try this a bit more (doing this for living_street vs residential failed, but it may fit better to driveway-service-residential-tertiary progression).

@Rovastar

> I think these look too similar. It is really hard to tell the difference between the road classifications. I have no idea, for example, which is the best/major roads to get around a city.

I tweaked colour and increased difference between primary and trunk/motorway. See https://github.com/gravitystorm/openstreetmap-carto/issues/1387#issuecomment-120274565 for an example of latest rendering.

I will work in next days on differentiating motorway/trunk.

**Comment by imagico** [comment]
z12 looks much better now.  The casing color for tertiary still looks too saturated to me - thin lines like with this kind of casing usually work better if they are less saturated.  IIRC you said you use the same color for casing and for the lines at low zooms - but you don't really need to.

The red might be somewhat strong at the very low zooms (<=6) - but this is something that will be difficult to judge without the full view of course.

**Comment by matkoniecz** [comment]
@daganzdaanda 

> Maybe tertiary and unclassified / residential could all be white with grey casing, but tertiary is wider? 

Thanks for this idea, it turned out to work well (see one of examples in http://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35437 ).
