### ISSUE TITLE
tourism=camp_site area should be labeled based on size

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#1020]
`tourism=camp_site` areas are labeled with a tent icon at z16 and above, but nothing at z15 or below ([example](http://www.openstreetmap.org/#map=14/39.4017/-84.1046)). The label should appear based on the area’s area (like #941).

![z14](https://cloud.githubusercontent.com/assets/1231218/4537717/3ad21cb6-4de2-11e4-85ed-4c2f7d1d3439.png)
![z15](https://cloud.githubusercontent.com/assets/1231218/4537718/3e551a96-4de2-11e4-9178-61324a6b8702.png)
![z16](https://cloud.githubusercontent.com/assets/1231218/4537719/45fd3530-4de2-11e4-967b-639fa4b7cd7d.png)

**Comment by Tomasz-W** [comment]
@kocio-pl Please close this ticket as duplicate.
Continue further discussion in https://github.com/gravitystorm/openstreetmap-carto/issues/3284
