### ISSUE TITLE
amenity=prison area should be labeled based on size

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#1022]
Non-building `amenity=prison` areas are labeled with a brown jailbird icon and name at z17 and above, but nothing at z16 or below ([example](http://www.openstreetmap.org/#map=16/39.9096/-83.4688)). The label should appear based on the area’s area (like #941), since some prison complexes can be quite large.

![z15](https://cloud.githubusercontent.com/assets/1231218/4537872/382e0850-4de5-11e4-8b66-2c9b586aabe8.png)
![z16](https://cloud.githubusercontent.com/assets/1231218/4537874/3be0181c-4de5-11e4-96d5-533f37ebcabd.png)
![z17](https://cloud.githubusercontent.com/assets/1231218/4537875/3f2ab1b2-4de5-11e4-8344-a70415af12e8.png)

**Comment by Tomasz-W** [comment]
@kocio-pl Please close this ticket as duplicate.
Continue further discussion in https://github.com/gravitystorm/openstreetmap-carto/issues/3284
