### ISSUE TITLE
Render operator on amenity=post_box and amenity=post_office

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#1023]
According to the wiki, [`amenity=post_office`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_office) and [`amenity=post_box`](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_box) can be used for facilities operated by either (quasi-)government agencies or commercial parcel services (UPS, FedEx, DHL, etc.). But if you come across a brown ✉︎⃝ icon on the map, you’re going to assume initially that it’s a traditional post office rather than something like a UPS Store. To reduce confusion, the renderer should place a small label underneath the icon indicating the `operator`. (But only if there isn’t already a `name` on the feature, since the name would probably indicate the type of facility.)

According to taginfo, `operator` is used on [27,965 post offices](http://taginfo.openstreetmap.org/tags/amenity=post_office#combinations) and [75,760 postboxes](http://taginfo.openstreetmap.org/tags/amenity=post_box#combinations). (`brand` is used on 6,309 postboxes.)

_(This issue was inspired by [this talk-us thread](https://lists.openstreetmap.org/pipermail/talk-us/2014-October/013661.html).)_

**Comment by math1985** [comment]
Post box: there are hardly any postboxes in the database by an operator other than the national carrier. Rendering a few operators that are not the national carrier is not worth having to render the national carrier name under almost all mailboxes.

Post office: duplicate with #840.

**Comment by 1ec5** [comment]
@math1985 How should collection boxes for UPS, FedEx, DHL, and the like be tagged? They probably have more collection boxes than the national carrier in my city and probably many others.

**Comment by math1985** [comment]
@1ec5 I'm not sure. I suppose this is in the US? Perhaps ask on the US mailing list what the tagging standard is?

**Comment by 1ec5** [comment]
This issue grew out of a talk-us thread, actually:

https://lists.openstreetmap.org/pipermail/talk-us/2014-October/013661.html

**Comment by math1985** [comment]
I see, I missed that in your first post.

I can re-open this issue, but I'm still not sure of what the best solution would be.

**Comment by 1ec5** [comment]
Compounding the problem, many private carriers put their boxes right next to their competitors’ (maybe due to city ordinance; I’m not sure). It might be difficult to cram three carriers’ labels right next to each other.

**Comment by mboeringa** [comment]
The best solution to me, especially taking into account this last raised issue, is not rendering this on the standard style, but on a dedicated site with togglable overlays depicting per layer each carrier's boxes. E.g.: This site by Marc Zoutendijk is an excellent example, that can display multiple backgrounds for the overlays, including OSM Standard:

**Taglocator**
http://mijndev.openstreetmap.nl/~marczoutendijk/openpoimap/taglocator.html

**Comment by Tomasz-W** [comment]
Is anybody still interested in this? I think it would clutter the map with needless information. What about closing this ticket?

**Comment by matkoniecz** [comment]
I see no good reason to render this particular part of OSM data.
