### ISSUE TITLE
tourism=attraction not rendered when object also has unrendered amenity tag

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#1029]
[This area](http://www.openstreetmap.org/way/243426059) is tagged `amenity=casino` and `tourism=attraction`. Normally `tourism=attraction` gets a red label ([example](http://www.openstreetmap.org/way/37492969)), but `amenity=casino` seems to override that rule, removing the label at all zoom levels. (The fuschia-ish fill color remains.) A label should appear based on the area’s area (like #941).

**Comment by 1ec5** [comment]
With 714aff3fc966cfa00265ffc395a343a7ebc0bb82, this is a lot worse because `tourism=attraction` simply isn’t rendered at all when the area has an `amenity` tag.

**Comment by math1985** [comment]
Yes, this really needs a solution. It's not very clear how, though.

**Comment by pnorman** [comment]
Is this another one of those cases arising out of combinatorial explosion (mapbox/carto#20) workarounds?

**Comment by math1985** [comment]
Yes it is.

**Comment by malenki** [comment]
IMHO: when there are better explaining tags than `tourism=attraction` on the object – like in this case `amenity=casino` – the `tourism=attraction` should not be rendered.
If you want to render casinos: do so. But don't encourage people to stick the generic `tourism=attraction` on more objects then needed.
After all I don't think the OPs example is a good one since the casino tag explains that it is a casino. For my part I wouldn't consider a casino an attraction for tourists.

**Comment by 1ec5** [comment]
> For my part I wouldn't consider a casino an attraction for tourists.

It depends on the case. In the case I linked to above, it is considered a regional tourist attraction. Other casinos may not be. In the same vein, a landmark fountain may be worth `tourism=attraction` for various reasons, whereas the one across the street may not be. But perhaps I’m misunderstanding `tourism=attraction`? It seems open to interpretation.

**Comment by mkoniecz** [comment]
I noticed other cases of missing tourism=attraction labels:

https://www.openstreetmap.org/way/321318572
https://www.openstreetmap.org/node/2500686532

In the first case it is blocked by unrendered natural, in the second case I am not sure what is happening.

**Comment by davidgumberg** [comment]
Same issue with having for example amenity=pharmacy and shop= any unrendered shop type.
