### ISSUE TITLE
Semicolons are not correctly handled on aeroway=runway

### ISSUE THREAD

**Issue by sb12** [gravitystorm/openstreetmap-carto#1035]
![runway](https://cloud.githubusercontent.com/assets/5783139/4592744/6b583dc6-507f-11e4-8c2c-5c664ee9d05b.png)

http://www.openstreetmap.org/way/31724226

Probably introduced by #750

**Comment by pnorman** [comment]
The upstream bug with the unknown character is fixed
![image](https://user-images.githubusercontent.com/1190866/179342070-213b4dec-2bdc-4933-a858-f28d24cc9f1a.png)

I'd like to not apply the `;` newline logic to aeroways, but splitting that text rendering into its own layer is covered by #2169
