### ISSUE TITLE
Let some symbols not block text rendering

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#1046]
Some symbols, such as gates and electricity towers, should not block text rendering.

Solution #1007 was rejected.

An alternative solution would be to move the layers for towers and gates etc. above the text layers.

**Comment by HolgerJeromin** [comment]
This prevents rendering of this barrier node on zoom 17, so you think you can drive through... 8-/
http://www.openstreetmap.org/node/194410086#map=17/50.76606/6.07305

**Comment by math1985** [comment]
Could you open a separate issue for that?

**Comment by HolgerJeromin** [comment]
done #1542
