### ISSUE TITLE
Support rendering of "label" member of relation

### ISSUE THREAD

**Issue by joakimfors** [gravitystorm/openstreetmap-carto#105]
Administrative boundaries can have a "label" node member. It would be nice if the stylesheet rendered the name of the relation at the position of the label member node.

Related: #103 #104

**Comment by Dimitar5555** [comment]
@gravitystorm Mappers work with what Carto offers them. You can't expect them to not put `label` (or `admin_centre` which is practically the same) elements when the relation's name is not rendered. After all they want to create some relationship between the area and the label/place center (which is usually not the same point as the centroid). Of course it would be fine to render names on the centroid if no label/admin center nodes are available.

If the name of the relation were rendered ignoring `label` nodes, the name would be in seemingly random places and mappers would not create relations for those objects. Also, I think it's important to note that mappers currently determine the label location by placing `place=*` nodes, so I don't see how having the same node with `label` role and no tags is a problem.
