### ISSUE TITLE
amenity=place_of_worship area should be labeled based on size

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#1052]
Non-building `amenity=place_of_worship` areas are labeled with black square or religion-appropriate icon at z16, and with an icon + name at z17 and above, but nothing at z15 or below. The label should appear based on the area’s area (like #941). `amenity=place_of_worship` isn’t just used for indoor worship spaces; it’s also (for better or worse) used for places like monastery grounds, convent grounds, and [spiritual retreat centers](http://www.openstreetmap.org/way/52768907), like the one below:

![z14](https://cloud.githubusercontent.com/assets/1231218/4605687/9040f086-51f3-11e4-862e-84e75ec47240.png)
![z16](https://cloud.githubusercontent.com/assets/1231218/4605695/962bf93c-51f3-11e4-9de1-ec0093b43d67.png)
![z17](https://cloud.githubusercontent.com/assets/1231218/4605696/99f74206-51f3-11e4-9476-f5fa7da9c6ef.png)

Many [church grounds](http://www.openstreetmap.org/way/98372069) are above the scale of typical buildings anyways:

![z15](https://cloud.githubusercontent.com/assets/1231218/4605700/0685f4f8-51f4-11e4-8d04-3b7725e65ba0.png)

**Comment by Tomasz-W** [comment]
@kocio-pl Please close this ticket as duplicate.
Continue further discussion in https://github.com/gravitystorm/openstreetmap-carto/issues/3284
