### ISSUE TITLE
stop rendering building constructed as a railway station in a special way

### ISSUE THREAD

**Issue by mkoniecz** [gravitystorm/openstreetmap-carto#1062]
Currently building=station is displayed specially [1]. There are some easily fixable problems (it should be building=train_station #389 #204), it is rendered without borders what makes it ugly, rendered on railway=station area would be invisible etc.

But main problem is that value of building tag is not related to the current purpose - building=train_station will be usually still used as train station, but some will be completely unused, may be turned into shopping mall/warehouse/whatever else - therefore I see no reason to render it specially as it encourages tagging for renderer (changing correct building=train_station into incorrect values to avoid special rendering for buildings with a changed purpose).

[1] http://www.openstreetmap.org/#map=19/49.90007/18.46664

![selection_015](https://cloud.githubusercontent.com/assets/899988/4625182/47c4a30e-5372-11e4-8fb8-c5a67315de14.png)

**Comment by nebulon42** [comment]
There is a colour value "station" in landcover.mss. Is this still used? Otherwise it should be removed.

**Comment by mkoniecz** [comment]
Thanks, AFAIK it is unused.

**Comment by nebulon42** [comment]
Seems to be used here: https://github.com/gravitystorm/openstreetmap-carto/blob/master/landcover.mss#L494
