### ISSUE TITLE
natural=peak - poor display with ele tag displayed and name not displayed

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1065]
![91432 1](https://f.cloud.github.com/assets/1458456/915957/9d528930-fe7d-11e2-8daf-b193a7f7591c.png)

http://www.openstreetmap.org/browse/node/26863056

If the name is omitted for whatever reason, there should not be an empty line between the peak signature (triangle) and the elevation.

Possibly algorithm:
1) when label does not fit below icon, render label on top or side (#957) 
2) If 1 failed, try #957 with the name only, omitting the elevation.
3) If that failed too, try these steps again, with the elevation only, omitting the name. Don't leave an empty line for the omitted name.

extracted from #100

**Comment by math1985** [comment]
Did #1187 resolve this?

**Comment by matkoniecz** [comment]
Yes.
