### ISSUE TITLE
Bigger town's names occluded by clearly smaller town's names

### ISSUE THREAD

**Issue by yopaseopor** [gravitystorm/openstreetmap-carto#1083]
When I see Vilanova i la Geltrú (south of Barcelona) 
http://www.openstreetmap.org/#map=12/41.22392/1.72511
, a town with 65000 population, and all these tags 

addr:country_code	ES
addr:postcode	08800
admin_level	8
capital	8
ele	25
is_in:country	Spain
is_in:country_code	ES
is_in:municipality	Vilanova i la Geltrú
is_in:province_code	08
name	Vilanova i la Geltrú
name:ca	Vilanova i la Geltrú
name:es	Villanueva y Geltrú
place	town
population	66532
population:date	2009
ref:ine	08307000100
source	Instituto Geográfico Nacional
source:date	2011-06
source:ele	MDT5
source:file	http://centrodedescargas.cnig.es/CentroDescargas/equipamiento/BD_Municipios-Entidades.zip
source:name	Nomenclátor Geográfico de Municipios y Entidades de Población
wikipedia	ca:Vilanova i la Geltrú

It gets hidden by other smaller towns, with less priority like Sant Pere de Ribes

name	Sant Pere de Ribes
name:ca	Sant Pere de Ribes
name:es	San Pedro de Ribas
place	town
population	11904

and same priority but less population as Vilafranca del Penedès

admin_level	8
capital	8
designation	town
ele	229
is_in:country	Spain
is_in:country_code	ES
is_in:municipality	Vilafranca del Penedès
is_in:province_code	08
name	Vilafranca del Penedès
place	town
population	35864
ref:ine	08305000500
source	Institut Cartogràfic de Catalunya, IDESCAT
source:date	2011-06
source:ele	MDT5
source:file	http://www.idescat.cat/cat/idescat/publicacions/cataleg/pdfdocs/nomencat2010.pdf
source:name	Nomenclátor Geográfico de Municipios y Entidades de Población
website	http://www.vilafranca.cat/
wikipedia	ca:Vilafranca del Penedès

When I ask that to the catalan list they say me it happens in other towns like Mataró pop. 116698 vs. Argentona pop. 11544.
All these happens at lower levels than 11.These towns (Vilanova i la Geltrú and Mataró) should start to appear from level 9 http://www.openstreetmap.org/#map=9/41.7734/1.7413 and the smaller towns would start to appear from level 11 http://www.openstreetmap.org/#map=11/41.3552/1.9398 .

But also I notify other thing.As OSM standards tags a city starting from 100000 population http://wiki.openstreetmap.org/wiki/Tag:place%3Dcity (spanish OSM standards also http://wiki.openstreetmap.org/wiki/ES:Key:place )  , in Spain there are so many cities that also be with same tag (town) and same name's size but not the same population (from 10000 to 100000 there are more than 400,some near to others so it is important to make a difference).Is there anyway render would count population to make the name bigger than other towns with less population?

**Comment by matkoniecz** [comment]
Frankfurt is missing in z7 and z8, as reported in #1811

**Comment by yopaseopor** [comment]
Still happens http://c.tile.openstreetmap.org/9/258/191.png

**Comment by matkoniecz** [comment]
Note that tile.openstreetmap.org servers are old version of this style, without code introduced by #1461. 

https://github.com/openstreetmap/chef/issues/36 proposes updating to v2.35.0 that is also not containing code that fixes this problem.

This issue will no longer appear on OSM website once v2.36.0 (not released at this point) will be used.

To check how it works with latest version of the style it is necessary to render tiles on your own.
