### ISSUE TITLE
Potential missing labels in amenity-points

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1091]
Following objects are rendered as nodes on z20, but without labels for name tag

amenity=atm
amenity=bicycle_rental
highway=ford
tourism=information
lock=yes
man_made=mast
amenity=post_box
amenity=recycling
amenity=telephone
amenity=emergency_phone
amenity=toilets
amenity=drinking_water
man_made=water_tower
tourism=picnic_site
leisure=picnic_table
leisure=slipway
tourism=caravan_site

I think that man_made=mast and highway=ford may have labels, I am less sure about other positions.

In addition #459 is ticket for tourism=viewpoint, #840 amenity=post_office, #800 amenity=car_sharing

related to #710

**Comment by math1985** [comment]
The tag amenity=recycling in the database usually has 'real' a name tag, the name of the recycling centre. I agree values like 'glass', 'paper' etc should not be used as name tag.

Bicycle rental, mast, recycling, drinking_water, water_tower, picnic_site, picnic_table, and slipway often have real names in the database. For atm, we can render the operator.

Ford, post box, telephone, emergency_phone, and toilets usually don't have a name so I propose to not render a label for them.

Tourism=information need access to the information key.

**Comment by HolgerJeromin** [comment]
We will see if your pull request will make the mappers use fake names for recycling containers. 
Thanks btw for adding names for trees :-)
