### ISSUE TITLE
Please render natural=arete

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#1097]
approved and in use since some time,  "arete" means a very sharp ridge and is usually a very characteristic landform and notable obstacle

Could be rendered as two-way cliff.

Quick search over existing usage does not show any widespread abuse or other problems.
- http://wiki.openstreetmap.org/wiki/Tag:natural%3Darete
- http://wiki.openstreetmap.org/wiki/Proposed_features/arete

**Comment by jeisenbe** [comment]
Used over 2000 times, and `natural=ridge` rendering is under consideration

**Comment by pnorman** [comment]
Now rendered.
