### ISSUE TITLE
Render named cave_entrance on z14

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1102]
Currently all caves are rendered from z15. I expect that overall it will improve rendering (I know that it will improve map in Poland).

It can be considered to render just cave icon, without name or smaller icon than on higher zoom levels.

**Comment by math1985** [comment]
I think I would be against decreasing the zoom level. I don't think caves are that much more important than other POI. They often happen to be in less dense environments, so then rendering wouldn't be that bad, but in the Kraków case, the cave is probably not the most important POI on that zoomlevel.

**Comment by matkoniecz** [comment]
Maybe it is just my bias and fact that I like caves. It is not clear that it would be improvement.
