### ISSUE TITLE
inconsistent amenity / landuse/highway services name display

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#1118]
At this location the right POI (Chef Express) is shown in z17 hiding the name of the services area ("Magliana"): http://www.openstreetmap.org/#map=17/41.81916/12.40550
But at zoom 18 and 19 it is the contrary: http://www.openstreetmap.org/#map=18/41.81954/12.40551
(in z19 the other POI name is omitted in favor of "Magliana").
You can see by looking at the z17 for the other direction that the name of the services area would be displayed in z17 as well...

**Comment by math1985** [comment]
> works for me on mapnik 2.2.0, but I am not using Carto but XML styles, maybe that's the reason?

@dieterdreist Could you give me an XML style where this works? Carto generates XML styles, so in principle it shouldn't matter.

**Comment by pnorman** [comment]
@systemed, you know of a hacky way to get placements into CartoCSS, right?

**Comment by systemed** [comment]
I do, but I stole it off @gravitystorm: https://github.com/mapbox/carto/issues/238

**Comment by yohanboniface** [comment]
@math1985 Have you addd the dx/dy properties too?

Here is an example that works: https://github.com/yohanboniface/transilien-network-carto/blob/master/style.mss#L129 in case it helps

**Comment by dieterdreist** [comment]
2015-01-25 20:40 GMT+01:00 math1985 <notifications@github.com>:

> works for me on mapnik 2.2.0, but I am not using Carto but XML styles,
> maybe that's the reason?
>
> @dieterdreist <https://github.com/dieterdreist> Could you give me an XML
> style where this works? Carto generates XML styles, so in principle it
> shouldn't matter.
>


sorry for replying late, I had overlooked this issue. I really don't do
anything special, this is an example:

        <Rule>
            <Filter>([place]='town')</Filter>
            &minscale_zoom14;
            &maxscale_zoom14;
            <TextSymbolizer fontset-name="bold-fonts" size="13"
fill="rgb(240,241,241)" wrap-width="20" placement-type="simple"
placements="N,E,S,W,NE,SE,NW,SW">[name]</TextSymbolizer>
        </Rule>

**Comment by math1985** [comment]
Duplicate with #957 and #1069.
