### ISSUE TITLE
Decrease polygon-gamma for buildings

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#1122]
Buildings that are in reality next to each other sometimes appear to have a small gap in between them. We can prevent this by decreasing polygon-gamma, just like we do for landcover.

This happens on z15 and lower.

**Comment by matkoniecz** [comment]
Location http://www.openstreetmap.org/?mlat=52.49002&mlon=-1.89804#map=18/52.49002/-1.89804

![selection_003](https://cloud.githubusercontent.com/assets/899988/9074545/ed7a886a-3b0a-11e5-8713-cfe06e94948d.png)

**Comment by pnorman** [comment]
Given that this problem is fairly minor visually, I'd prefer not to adjust polygon-gamma.

**Comment by kocio-pl** [comment]
I think this ticket can be closed in a few days (if nobody complains).
