### ISSUE TITLE
Drop railways from z6/z7

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#1123]
Zoom level 6 and 7 are currently very crowded. Both railways and some types of roads are rendered with a gray line. It would probably improve the legibility of the map if we drop railroads from these zoomlevels.

**Comment by matkoniecz** [comment]
I am withdrawing my objection. I admit that my previous comment in this thread was based too much on naive "lets render everything or at least as much as possible".

It is not merely hard to distinguish roads and railways on z6/z7, it is completely impossible. And expecting that somebody new to the map style will be able to do this is ridiculous.

Google maps renders railways from z11, HERE map from z10, MapQuest and Humanitarian from z12, OSM mapnik de from z10, Stamen Toner from z14(!).

Railways are interesting but in that case placement of infrastructure is not the only important part - to get from point A to B using railway one anyway needs to check available connection.
