### ISSUE TITLE
admin_level=7 and admin_level=8 look identical

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#1137]
According to the OSM wiki’s [`admin_level` table](http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative), plenty of countries use adjacent `admin_level`s, both odd and even. This stylesheet appears to render `admin_level=7` and `admin_level=8` with exactly the same dashed line. Where a level 8 jurisdiction abuts the edge of its parent level 7 jurisdiction, there’s a T-junction between three identical lines and it’s difficult to make sense of the boundaries.

In some exceptional cases – unfortunately quite common where I map – an `admin_level=8` boundary might cross over an `admin_level=7` boundary, resulting in a misleading junction between _four_ identical lines. For example, the [City of Harrison](http://www.openstreetmap.org/relation/183454) (level 8) exists in both [Harrison Township](http://www.openstreetmap.org/relation/2723542) and [Crosby Township](http://www.openstreetmap.org/relation/2701691). The city limits [cross over the township line](http://www.openstreetmap.org/#map=16/39.2577/-84.7646) twice and [run along it](http://www.openstreetmap.org/#map=16/39.2727/-84.7643) in another spot. In the screenshots below, it looks like there are more boundaries than there really are:

![Highlighted](https://cloud.githubusercontent.com/assets/1231218/5178642/ed008fe0-7424-11e4-9b38-fc48e3a820f4.png) ![not highlighted](https://cloud.githubusercontent.com/assets/1231218/5178646/f135a1a4-7424-11e4-92aa-6397a70f0723.png)

_(Left: Nothing highlighted. Right: City of Harrison, level 8, highlighted.)_

It’s great to see boundaries vary by both width and dash pattern these days. If all the reasonable dash patterns are already in use, I think varying widths some more (with even thicker lines for lower `admin_level`s) would address this issue.

**Comment by jeisenbe** [comment]
This same problem is present for `admin_level=9` and `admin_level=10`, which makes it even harder to solve, unless we stop rendering `admin_level=9/10`.

**Comment by jeisenbe** [comment]
Fixed by #4100
