### ISSUE TITLE
building with leisure=stadium has a weird border

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1140]
https://www.openstreetmap.org/way/292867512#map=18/50.06765/19.99338

affects both current buildings and after #565 

http://bl.ocks.org/pnorman/raw/c61d6b11193081910866/#18.00/50.06767/19.99319

![selection_005](https://cloud.githubusercontent.com/assets/899988/5210106/6cd82ab8-75c7-11e4-83c1-53cf594af6dc.png)

http://bl.ocks.org/pnorman/raw/c61d6b11193081910866/#14.00/50.0698/20.0176

![selection_006](https://cloud.githubusercontent.com/assets/899988/5210121/9a6fec2c-75c7-11e4-9f57-d9594e313b3f.png)

**Comment by mkoniecz** [comment]
or
3) treat building=* with leisure=stadium different, but it would fail in cases like http://www.openstreetmap.org/way/130575966 http://www.openstreetmap.org/relation/2274125

**Comment by daganzdaanda** [comment]
(sorry for the duplicate, I did not find this again... probably was searching for "sports_centre")
I'd favour 1b) which is also proposed in #1205. 
Some tagging schemes may then look bad but these can be corrected quickly. 
And then we can ignore leisure=stadium and leisure=sports_centre on buildings, apart from the names, which may need another look.

**Comment by pnorman** [comment]
Solved.
