### ISSUE TITLE
Not rendered: ambulance_station

### ISSUE THREAD

**Issue by hajo4** [gravitystorm/openstreetmap-carto#1160]
I think it would be important, and increase the usefulness of OSM-maps
if such emergency-facilities would be shown on the map.

E.g. with tag "emergency:ambulance_station".

**Comment by math1985** [comment]
Should be emergency=ambulance_station, not emergency:ambulance_station obviously.

**Comment by marcobra** [comment]
+1 for this rendering request...  useful points 
 i've seen "hospital tricks" to get emergency points rendered...

Thanks

**Comment by HolgerJeromin** [comment]
rendering the name would be sufficient. IMO the outline and an icon is often not really needed.

**Comment by marcobra** [comment]
IMO: i hate names, especially the long intrusive rendering names... of private activity (icon + names): bar and restaurant and shop... they always overlap addr:housenumber info's

**Comment by HolgerJeromin** [comment]
For example 
http://www.openstreetmap.org/way/108967298
should render something. 
I have no preference if name or housenumber is rendered, but right now you think the housenumber is missing here...

**Comment by marcobra** [comment]
in my town http://osm.org/go/xX0MtwbVB?layers=N&m=

**Comment by kocio-pl** [comment]
Maybe we could reuse the garages area color for this?

**Comment by Tomasz-W** [comment]
I think special rendeing is not nessesary here, because this objects are not common-useful. Is anybody still interested in it?

**Comment by SomeoneElseOSM** [comment]
My 2p: In a different map style I chose not to give it a special icon because it's not somewhere you specifically go (see for e.g. http://map.atownsend.org.uk/maps/map/map.html#zoom=18&lat=53.048011&lon=-1.409169 ).

**Comment by kocio-pl** [comment]
I guess not, so i will close it now. If there will be any new ideas and arguments, it can be reopened.
