### ISSUE TITLE
Render access data for barrier=gate and barrier=lift_gate

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1161]
These barriers have dual role - it may mean that otherwise passable way is inacessible, or that barrier is passable in this point.

There are three types of access for barriers:
- public access (access=yes)
- no access or limited (access tag set to value other than yes)
- implied no access (no access tag set)

I propose to render on high zoom levels no access with red glow on barrier=gate and barrier=lift_gate symbols, and implied no access with pink glow (untested, this is jus an initial idea).

related to #323

**Comment by kocio-pl** [comment]
I guess access=yes could make it render lighter (with man made gray probably). Lack of information is a high risk that the access is limited.

**Comment by Tomasz-W** [comment]
related to: https://github.com/gravitystorm/openstreetmap-carto/issues/1012

**Comment by SomeoneElseOSM** [comment]
> I guess access=yes could make it render lighter 

While that idea works great for car parks, I don't think that it would work well here.  An amenity is a destination; a barrier is just something on your route that you might have to explicitly avoid.  A lighter barrier might not stand out enough to say to someone "you probably can't come through here".
