### ISSUE TITLE
Covered reservoirs

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#1167]
Hi
Covered reservoirs (covered=yes) mapped as areas are being rendered solid blue, the same as open ones. Could it be amended to just a dashed outline or maybe narrow band of blue shading similar to the new national parks boundaries render?

**Comment by matkoniecz** [comment]
I admit that I am not sure what is represented by [covered = yes landuse=reservoir].

Can somebody link to an example photos?

@DaveF63 Is https://commons.wikimedia.org/wiki/File:Covered_reservoir_seen_from_the_top_of_Primrose_Hill_-_geograph.org.uk_-_784303.jpg a photo of https://www.openstreetmap.org/way/43160349#map=18/51.39740/-2.38280 ?

**Comment by DaveF63** [comment]
I don't have photos, but generally it's any reservoir where the water isn't visible. 
In my area of the UK there are numerous water tanks, semi buried below ground level. The half above ground is landscaped, covered in earth & grass.

**Comment by Tomasz-W** [comment]
retaled to #2620

**Comment by jragusa** [comment]
I investigated these covered reservoirs and it seems there is a tagging mistake. Both examples proposed above (https://www.openstreetmap.org/way/43160349 and https://www.openstreetmap.org/node/2789983153) should be better described as `man_made=reservoir_covered` and it's the same for several equivalent "covered reservoirs".

A correct covered reservoir is for example https://www.openstreetmap.org/way/574995790 ([see the aerial photograph](https://www.geoportail.gouv.fr/carte?c=5.192751913660046,45.962857934988534&z=21&l0=ORTHOIMAGERY.ORTHOPHOTOS::GEOPORTAIL:OGC:WMTS(1)&l1=GEOGRAPHICALGRIDSYSTEMS.MAPS::GEOPORTAIL:OGC:WMTS(0)&l2=GEOLOGY.GEOLOGY::EXTERNAL:OGC:EXTERNALWMS(1;h)&permalink=yes) : a reservoir covered with a tarpaulin. Following this example, the rendering should not be changed.

So I propose to close this issue and recommend people to fix tag to `man_made=reservoir_covered` if they are semi-buried and covered by grass or add `building=*` if they are located in a building.

**Comment by Tomasz-W** [comment]
@kocio-pl https://github.com/gravitystorm/openstreetmap-carto/issues/1167#issuecomment-441454335

**Comment by kocio-pl** [comment]
The other tagging sounds sane, however we still don't know if/how to render them (see #2620):

https://wiki.openstreetmap.org/wiki/Tag%3Aman_made%3Dreservoir_covered
![taghistory 30](https://user-images.githubusercontent.com/5439713/48984695-73819900-f0ff-11e8-9256-39746e97e074.png)
