### ISSUE TITLE
Tunnel=culvert is rendered inside riverbank

### ISSUE THREAD

**Issue by Theodin** [gravitystorm/openstreetmap-carto#1192]
A smaller river which exits from a larger river in a tunnel is rendered strangely white:

http://www.openstreetmap.org/#map=19/32.74385/-114.46112

![culvert](https://cloud.githubusercontent.com/assets/8019309/5605513/d12eff18-93ff-11e4-90cd-11c6a69a5a70.png)

**Comment by Theodin** [comment]
![culvert](https://cloud.githubusercontent.com/assets/8019309/5605513/d12eff18-93ff-11e4-90cd-11c6a69a5a70.png)

**Comment by HolgerJeromin** [comment]
There is no tunnel from the riverbank to the "center" of the river. 
In my opinion a tagging error, even if the riverbank would not be mapped. 
Compare tagging of a street tunnel next to a crossing.

**Comment by mkoniecz** [comment]
Closing per @HolgerJeromin 

I edited this location to fix this tagging error.

**Comment by Theodin** [comment]
You are right. Thanks for fixing it.
