### ISSUE TITLE
amenity=place_of_worship without building=* is now not rendered as area

### ISSUE THREAD

**Issue by mkoniecz** [gravitystorm/openstreetmap-carto#1193]
![amenity place_of_worship closed_way](https://cloud.githubusercontent.com/assets/899988/5606347/a4e7b8ce-942b-11e4-8810-26b2e2827cd7.png)

**Comment by mkoniecz** [comment]
First problem: landcover layer that has code[a] to display PoW that is not on a building currently is not querying this amenity value

Currently it has[b] 

> CASE WHEN amenity IN ('parking', 'university', 'college', 'school', 'hospital', 'kindergarten', 'grave_yard') THEN amenity ELSE NULL END)) AS amenity,

[a] https://github.com/gravitystorm/openstreetmap-carto/blob/7cae5b06d842283454ef4c1b99fc8078f7a75f7c/landcover.mss#L146
[b] https://github.com/gravitystorm/openstreetmap-carto/blob/7cae5b06d842283454ef4c1b99fc8078f7a75f7c/project.yaml#L133

Second problem: fixing this issue is not fixing this bug - https://github.com/mkoniecz/openstreetmap-carto/commit/c66484abec526bf3a17295a530f937002cc0d3bb is not fix for this issue

**Comment by nirvn** [comment]
I was about to open a bug when TomH on IRC pointed me out to this recently opened issue.

For Southeast Asian buddhist country, the disappearance of a fill color for the amenity=place_of_worship polygons (without building=yes) is a significant regression. The buddhist temples, aka pagodas, are sizable walled areas with lots of empty space. They are landmarks everybody know and serve to identify settlement centers.

The filling should return to make southeast asia, and others, happy OSM users :) The previous styling might have been relying on a gray that was too dark, so if we take this opportunity to look at improving things, it might be better to use a more subtle color, like the light pink for tourism polygons.

**Comment by EdLoach** [comment]
mkoniecz - you've not added place_of_worship to the where clause: 

    OR amenity IN ('parking', 'university', 'college', 'school', 'hospital', 'kindergarten', 'grave_yard')

**Comment by mkoniecz** [comment]
@EdLoach - Thanks!
