### ISSUE TITLE
Living streets are hard to see

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1194]
After #1153, I think living streets are harder to see when there are lots of houses around. Example: http://www.openstreetmap.org/#map=17/48.36770/10.90188

Possibly a lighter grey would now look better? It would need testing on other backgrounds.

**Comment by mkoniecz** [comment]
I also would make them narrower.

**Comment by math1985** [comment]
Would there be way in which we can make highway=pedestrian visually more similar to highway=footway? If so, we can render highway=living_street as the current highway=pedestrian.

**Comment by dieterdreist** [comment]
> Am 05.01.2015 um 21:02 schrieb kocio-pl <notifications@github.com>:
> 
> I think highway=living_street and highway=pedestrian are too thick - if we need to show the actual area borders, we can use the area=yes tag, otherwise they should be rendered more like a service road.
> 


Living streets are usually a subclass of residential roads while pedestrian streets might be either quite important historic roads (eg main roads in historic city centers) or less important roads (eg parallels or cross streets to more important roads in aforementioned context).


In all these cases, they seem to merit more prominence than service roads=

**Comment by kocio-pl** [comment]
As a matter of fact we have in Warsaw very important historic road being now also a pedestrian street - and the area tag fits there much better than simply a thick line, because the shape is uneven and thicker than it: 

http://www.openstreetmap.org/way/137380704 

But when we have pedestrian streets as main avenues (like in the park, in cemetery or in allotments) the contrast between them and plain footways is stark (also be aware of how service road changes into it):

http://www.openstreetmap.org/way/116215396

So:
1) the standard pedestrian street is too thin (and too straight) for some cases and too thick for other ones, 
2) and because we can always make it thicker and even more precise, we may not care about this problem, but we can't make it thinner when needed,
3) that means we need thinner standard line rendering.

**Comment by kocio-pl** [comment]
"Living streets are usually a subclass of residential roads" - I agree, that may have more merit, but living streets can be also mixed with (thinner) service roads, especially with even more thinner road type highway=service+service=driveway:

http://www.openstreetmap.org/way/25655233

The colour of living streets also needs some tweaking now the buildings are pale (in some other osm-carto issue there was an example of the Old Town in Cracow given).

**Comment by math1985** [comment]
I agree this issue is important. Does anyone have a suggested colour?

**Comment by nebulon42** [comment]
This should go together with giving residential landuse a more brownish hue, maybe also living streets could get a brownish hue with a lighter overall colour.

**Comment by dieterdreist** [comment]
2015-01-05 23:25 GMT+01:00 kocio-pl <notifications@github.com>:

> As a matter of fact we have in Warsaw very important historic road being
> now also a pedestrian street - and the area tag fits there much better than
> simply a thick line, because the shape is uneven and thicker than it:
>
> http://www.openstreetmap.org/way/137380704
>


on a side note the tagging for this way doesn't seem right if this is
describing a pedestrian highway: http://www.openstreetmap.org/way/137020852
Also the current tagging can be reduced for simplicity without loosing any
information:
"access=designated" doesn't convey any information
psv=yes is default (might be important if you change the highway value to
pedestrian)
motor_vehicle=designated also doesn't seem to add more information here
(but is actually allowing the access for all motor vehicles, so it
contradicts the pedestrian context).

**Comment by kocio-pl** [comment]
@dieterdreist: It looks more or less like this:

https://commons.wikimedia.org/wiki/File:Widok_na_krakowskie_przedmiescie_po_remoncie.jpg

**Comment by dieterdreist** [comment]
2015-03-10 12:49 GMT+01:00 kocio-pl <notifications@github.com>:

> @dieterdreist <https://github.com/dieterdreist>: It looks more or less
> like this:
>
>
> https://commons.wikimedia.org/wiki/File:Widok_na_krakowskie_przedmiescie_po_remoncie.jpg
>


@kocio-pl: is it generally accessible by car, or is it a pedestrian area
with exceptions for psv? I can't see this in the photo.

**Comment by kocio-pl** [comment]
The car traffic is generally forbidden there, only taxi, public transport and cycling is allowed. The street is paved with brick stone and pedestrians can cross it freely. That's like a classical street with sidewalks, except the sidawalks are wide and the street is much less important part of this space.

**Comment by dieterdreist** [comment]
2015-03-10 14:11 GMT+01:00 kocio-pl <notifications@github.com>:

> The car traffic is generally forbidden there, only taxi, public transport
> and cycling is allowed. T



I think you should delete the "access=designated" (no content) and re-tag
motor_vehicle=designated to motor_vehicle=private then ("designated" is a
stronger "yes").
