### ISSUE TITLE
playground node icon should not block school label

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1195]
The icon of the playground node (its label was removed a few minutes ago) should not block the large school name:
http://www.openstreetmap.org/way/90133797#map=18/50.78145/6.08447

related to #1046

**Comment by mkoniecz** [comment]
Just moving playground to .amenity-low-priority layer is not a good idea, as it would cause gate to playground block playground icon.

Maybe add new layer, with icon less important and not as unimportant as gates and bollards?

**Comment by pnorman** [comment]
> Maybe add new layer

we shouldn't need to do this.

the painter's algorithm used should have the school labeled first, the problem is the playground is a point not a polygon

**Comment by javbw** [comment]
Is this the same kind of problem (point instead of  polygon) that would cause a helipad point to block a hospital area's label?

http://www.openstreetmap.org/#map=17/36.40779/139.06400

**Comment by math1985** [comment]
Duplicate with #964.
