### ISSUE TITLE
landuse=construction colour is too dominant

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1197]
This has been left out from the last round of recalibrating colours. Along with leisure=pitch / track (see #1190), construction sites now are pretty dominant on the map. 

Possible solution: desaturate and lighten a lot. 
If it gets too close to forests or similar, maybe move the chroma a bit (green -> red?). Or think about a broad diagonal hatching.

**Comment by math1985** [comment]
Agree, this does not look good now.

How do other maps render construction sites?

**Comment by mboeringa** [comment]
> How do other maps render construction sites?

See the red arrows for a couple of examples, very light yellow with random light coloured stipple. Berlin seems one huge construction site...

![landuse_construction](https://cloud.githubusercontent.com/assets/7635726/5616716/883acf22-9507-11e4-8e25-35c8129ad7db.jpg)

**Comment by math1985** [comment]
Is anyone willing to propose a colour? I think @mboeringa's rendering is not very clear.

**Comment by althio** [comment]
I like the proposal of diagonal hatching. Just like military landuse as it
bears the same idea of restricted access.
Color: yellow for works instead of red.

**Comment by gravitystorm** [comment]
I dislike the diagonal hatching, in general and certainly for construction sites. It's very eye catching (in 'real life' it's used for things like hazard warning tape, danger signs etc) and we should avoid using it here.

The main use of hatching, in military landuse, I also dislike. It should be reserved for things like military danger areas rather than things like ceremonial parade grounds.

**Comment by althio** [comment]
Hatching is indeed very eye-catching but hazard warning tape and danger signs are really well suited for a construction site so IMO the meaning is good and clear.

You could keep hatching but also make it as (in)visible as you wish if you adjust saturation and opacity. You could even render buildings or other features below the hatching as the tagging allow to define the intented use of the construction site.

However I do agree that hatching with added fill in the gaps as in military landuse is too proeminent.
A good combination could be:
* Hatching with muted color,
* no fill in the gaps,
* gaps bigger than stripes.
Yellow for construction, redish for military.

**Comment by gravitystorm** [comment]
Hazard warning might be good for the construction site itself, but not for a general-purpose map where construction sites are just one of hundreds of other features. There's no reason to make them the most eye-catching feature on the map.

**Comment by nebulon42** [comment]
As a side note I discovered that construction does not have an outline, unlike most other landuses.

**Comment by polarbearing** [comment]
Hatching was discussed as being reserved for strictly access-limited features, in the discussion of #772 prison areas, where vertical hatching is proposed, which just needs to be rebased.

**Comment by althio** [comment]
@polarbearing 
Construction site are temporary and quite access-limited, I think it is useful to use a different-looking rendering than usual buildings and landuses.

@gravitystorm 
Different-looking does not mean most eye-catching.
What I suggested in https://github.com/gravitystorm/openstreetmap-carto/issues/1197#issuecomment-68853334 is pretty low-profile, with muted color, no fill and discrete subdued low-key hatching. I want people to say it is almost useless because you cannot see it at once. See? I am not talking about ugly bars that leap at your eyes.

**Comment by mboeringa** [comment]
> What I suggested in #1197 (comment) is pretty low-profile, with muted color, no fill and discrete subdued low-key hatching. I want people to say it is almost useless because you cannot see it at once.

You mean more like the below cut from the larger image I posted, in this case representing a **landuse=greenfield**, so a planned development?

![greenfield](https://cloud.githubusercontent.com/assets/7635726/5632904/c9baf87a-95d2-11e4-8b00-1deb6e62f0f0.jpg)

Or this one (also a greenfield, but with structure of old buildings below it, so it is less obvious):

![greenfield_2](https://cloud.githubusercontent.com/assets/7635726/5633050/f3e89d72-95d3-11e4-9667-995adddd74d0.jpg)

Or this military base:

![military](https://cloud.githubusercontent.com/assets/7635726/5633054/0189c9a6-95d4-11e4-8d79-71d6591ab55d.jpg)

**Comment by kocio-pl** [comment]
This is really a discrete way of rendering landuse=construction - no matter how short-lived that landuse is (that's mainly a matter of surveying and judging if it isn't too small and temporary to tag). It's definitely restricted area, but still not eye-catching - at least much less visible than in current state of rendering. I really like this solution.

**Comment by math1985** [comment]
Whether landuse=construction is a more restricted area than for example landuse=farmland is probably very culture-dependent.

**Comment by kocio-pl** [comment]
That would be another discussion (how to tag farmlands), but I just say that construction area is always restricted by its nature, so for me the hatching on landuse=construction is justified (much more than on military parade square, of course). Plus Andy is worried about too much visibility and we would make it less visible, so I guess it's not a problem.

**Comment by polarbearing** [comment]
Construction is not more restricted than a locked private garden or an industrial site. You normally won't get shot when trying to leave or enter. Thus a hatching symbolizing heavy restriction is completely unjustified. 

As for the first example, the stippled yellow looks a lot like beach.

**Comment by mboeringa** [comment]
> As for the first example, the stippled yellow looks a lot like beach.

Yes, that maybe a possible misinterpretation. However, at some point, "context" starts to matter. Nobody will intuitively associate a "beach" with a location in the middle of a dense urban build up of city like Berlin or any other, so it should be relatively clear that this is no beach (and of course, I use a different symbol for beach...)

Anyway, these are just examples to help you all make up your own mind, and decide on some rendering for Carto, which by no means need to be exactly the ones I show.

**Comment by althio** [comment]
@mboeringa https://github.com/gravitystorm/openstreetmap-carto/issues/1197#issuecomment-68901779
> You mean more like the below cut from the larger image I posted, in this case representing a landuse=greenfield [...] or this military base?

Yes that is the general idea and direction. This representation of military base without fill is IMO better than the current one in carto.
But I would go for even less saturation and/or opacity.

Also after reading https://github.com/gravitystorm/openstreetmap-carto/pull/771#issuecomment-50338716
> I don't like the hashing of the prison. Generally I dislike this type of hashing as the thin lines could look like some type of way and frankly look ugly.

I would like to see thicker lines (maybe hatching with equal width for lines and gaps to start with?).
With reduced saturation and/or opacity it would look as if the thin lines were blurred or washed out to give wider stripes. If I make myself clear? I think I need a mockup...

**Comment by althio** [comment]
@polarbearing
> Hatching was discussed as being reserved for strictly access-limited features, in the discussion of #772 prison areas
+
> Construction is not more restricted than [...] Thus a hatching symbolizing heavy restriction is completely unjustified.

For now I feel this is your personal opinion and that we can still discuss whether hatching is for heavy restriction and whether restrictions apply to construction sites and what is suitable or completely unjustified.

**Temporary**
Construction sites are temporary (or is someone about to mention never-ending works somewhere?). IMO renderings like reduced opacity/saturation, dashes lines and hatched areas can give straightforward meaning about this temporary state.
**Access**
polarbearing wants hatching for features with strictly limited access.
But then all people disagree about what is limited access and if construction sites in the world are more or less permissive than farmland or a locked private garden.
**Danger**
gravitystorm dislikes the diagonal hatching in general, in particular for construction sites and generic military landuse. He wants hatching to be associated with warning and danger and reserved for things like military danger areas.
I think construction sites are dangerous enough for workers and that is why access is *'sometimes'* restricted to non-workers. From wikipedia:
> Construction is one of the most dangerous occupations in the world, incurring more occupational fatalities than any other sector in both the United States and in the European Union.


* Any of these three criteria [Temporary|Access|Danger] separately might not be enough to convince you all.
* Please combine all 3 and I think it sets a good case for construction site with discrete hatching (with no fill and stripes of reduced opacity and/or saturation).

Finally the area rendering as hatching could be used with an icon on the centroid. This icon could make things clear (icon for works, icon for danger_area, ...).

**Comment by althio** [comment]
Here is a crude mockup for proposed rendering of landuse=construction.
It is based on hatching (yellow + transparent) with reduced opacity. [Dalle Vitruve/Square Vitruve]
It certainly needs to be further tuned (no outline, it covers icons and labels, tentative color H/S/L and opacity) but I hope you get the general idea.

On the same area you can compare with current rendering of landuse=construction. [Square des Cardeurs]

It also includes a highway=construction [Rue des Balkans] and a small landuse=allotments [Le 56 Saint-Blaise].

![warning-yellow-light-30](https://cloud.githubusercontent.com/assets/9863567/5849264/70db3dc4-a1e3-11e4-81d9-cce2304ad3ba.png)

**Comment by mboeringa** [comment]
Looks like an improvement over the current rendering, it certainly gives more of a feel of the uncertain state of the feature, and the fact that a building is going to be raised here, none of which is obvious in the old rendering. I like the detail of the spade.

On the other hand, I guess the rendering only involves the hatching, so it might be wise to try it out on piece of landuse=residential or landuse=industrial, without building contours beneath it... Of course, there are construction sites that are not associated with raising a building a all, but maybe the creation of a square, or building a road. So how does the hatching work on other landuse, or potentially natural, types?

**Comment by dieterdreist** [comment]
> Am 06.01.2015 um 09:17 schrieb althio <notifications@github.com>:
> 
> I like the proposal of diagonal hatching. Just like military landuse as it
> bears the same idea of restricted access.


+1, like hatching too, IMHO this would symbolize incompleteness here, and not access.=

**Comment by dieterdreist** [comment]
> Am 06.01.2015 um 21:15 schrieb mboeringa <notifications@github.com>:
> 
> Nobody will intuitively associate a "beach" with a location in the middle of a dense urban build up of city like Berlin


as a side note there are and have been in the past years quite some beaches in Berlin, eg Beach Mitte, Strandbar, etc 
eg the most commercial and least "underground" one: http://www.artschoolvets.com/blog/djhype/files/2010/09/Strandbar-Mitte_08.jpg=

**Comment by javbw** [comment]
>Of course, there are construction sites that are not associated with raising a building at all, but maybe the creation of a square, or building a road. So how does the hatching work on other landuse, or potentially natural, types?

if it is going to let another land use show through (residential, industrial), wouldn't it also let the other landuse areas show through (park, sports grounds, grass) or let the road be rendered over the top (highway=construction)? if so then it would work well for those examples. The hatching seems to be a good solution.

**Comment by althio** [comment]
Good points @mboeringa.
I think most of the cases could be handled with:
* yellow stripes with muted color but full opacity
* and alternate fully transparent stripes

The worst case being yellow [construction] on yellow [sand]?
Maybe outline or icon could also help.

Construction roads are not in the scope. Or do you think people could tag
construction road as way and construction landuse as area?
I think the road will be easily visible with current rendering.

**Comment by math1985** [comment]
We still don't have a good rendering for landuse=construction, and I think the current rendering is still a major problem. Does anybody have any suggestions perhaps?

**Comment by mboeringa** [comment]
> Does anybody have any suggestions perhaps?

I think there have been enough suggestions here in the thread, and concrete proposals, e.g. see @althio's post (https://github.com/gravitystorm/openstreetmap-carto/issues/1197#issuecomment-70975675). Now make a choice and refine to a true proposal / pull request for carto.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 14 ago 2016, alle ore 23:49, Matthijs Melissen <notifications@github.com> ha scritto:
> 
> Does anybody have any suggestions perhaps?


I believe we could get rid of the fill and have instead an outline (extending towards the inside and not out of the actual limit), in the color of the current fill, with a notable width (similar to natural reserves).
The fill could be as if the construction was already finished (if this information is available, e.g. from a construction=* tag)

**Comment by kocio-pl** [comment]
Let's check the simplest solution (making it lighter) in comparison with buildings and special buildings (tagged as place of worship):

Current rendering
![dp7zxvik](https://cloud.githubusercontent.com/assets/5439713/17796679/ccd560c4-65c2-11e6-9d83-4e32cf954fec.png)

5% lighter
![7iyeio1t](https://cloud.githubusercontent.com/assets/5439713/17796685/dc739c76-65c2-11e6-9996-9781158ae2e3.png)

10% lighter
![dos5vcr_](https://cloud.githubusercontent.com/assets/5439713/17796689/e6e5c8aa-65c2-11e6-933d-dbdad6a351a7.png)

**Comment by jojo4u** [comment]
Both work for me. Mapping constructions sites is one of the points OSM is good at, and the 5% example still highlights this. The 10% example looks like another landuse. It depends on decission of the maintainers what the style should show.

**Comment by math1985** [comment]
Both are improvements to me, I think I would prefer 10%.
