### ISSUE TITLE
adjust landuse colours

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1198]
Landuse colours IMO are currently a bit too saturated. After #1153 built-up landuse could use some adjustment to work better with the lighter buildings colour (which I like a lot).

Other related issues have popped up recently, such as #1197 or #1190. I would first adjust built-up landuse and then look at other types. I'm now expanding on https://github.com/gravitystorm/openstreetmap-carto/issues/1190#issuecomment-68640322.

The problem is that there are a lot of different colours in use and there are a lot of interaction effects. To approach this in a systematic way I have created an SVG image that is meant to assist with colour changes: [color-compare.svg](https://github.com/nebulon42/openstreetmap-carto/blob/color-compare/color-compare.svg) (partly previewed below).

![color-compare](https://cloud.githubusercontent.com/assets/3531092/5612674/19b5bf40-94d9-11e4-9b33-689db994cf58.png)

It displays all landuse colours with streets, buildings and water features on top, please tell me if I missed something important. Some combinations are unlikely to occur, but I included them anyway. This enables to see quickly which combinations work/don't work so well. It also enables before/after comparisons of landuse if you adjust the right column landuse colour and stroke. If you adjust the stroke or fill of the topmost streets, buildings etc (in residential) then every similar feature in this column changes too. This enables to test e.g. street colour changes (as proposed e.g. in #1194).

Of course, this does not make previewing and testing on the actual map obsolete in any way.

**Comment by HolgerJeromin** [comment]
perhaps move the building element near the streets in the svg as these object are often a problem together. Especially buildings and living_street.
I am unsure if living street should be adjusted before the landuse.

**Comment by math1985** [comment]
They have been made lighter a lot already (right before changing the building colour): http://bl.ocks.org/tyrasd/raw/6164696/#16.00/52.4875/-1.8819

However, we could make them even lighter.

**Comment by math1985** [comment]
See also #599.

**Comment by pnorman** [comment]
> However, we could make them even lighter.

Not really - any lighter or less chroma and the different landuses would be too hard to distinguish.

**Comment by nebulon42** [comment]
Thanks for pointing me to that. I must have missed it.
> any lighter or less chroma and the different landuses would be too hard to distinguish.

That is a good argument, maybe it is possible to do it while keeping somewhat distinguishable landuses. The goals of having a map that supports mappers and a map that looks good for simply looking at it are clearly conflicting. I guess it will become more and more difficult to support both goals.

**Comment by pnorman** [comment]
> maybe it is possible to do it while keeping somewhat distinguishable landuses

I tried, but don't think so. As it is, I had to push industrial farther towards purple to make enough room between retail and commercial.

1b97c3f2414af60d5a4540c778d39fd0aea4e0d3 contains some colour distances

**Comment by nebulon42** [comment]
I think this issue is too broad and hence too complex. I'm closing it as there should be more specialised sub-issues.
