### ISSUE TITLE
building with leisure=sports_centre has some green visible

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1203]
Previously this combination of tags resulted in a grey building because of the transparency involved. Now the building is a solid colour, but look at the edges and you still see a bit of the green from the sports_centre, e.g. http://www.openstreetmap.org/way/86531926

Should we just render the building and not the leisure tag?

Also, the name of such a gym used to be rendered in green, and now it's the same as any building. 
But a node for a sports_centre still gets a green label, see http://www.openstreetmap.org/way/100481294 vs http://www.openstreetmap.org/node/3268045065
Should maybe the name of a building + sports_centre be rendered green again?

**Comment by nebulon42** [comment]
Is this the same as #1140?

**Comment by pnorman** [comment]
> Is this the same as #1140?

yes
