### ISSUE TITLE
Adjust size of placenames at z14

### ISSUE THREAD

**Issue by austi1996** [gravitystorm/openstreetmap-carto#1204]
The size of the placenames at z14 looks a little bit strange, because town (e.g. Horw) and suburb (e.g. Ennethorw) as well as village (e.g. Hergiswil) and isolated_dwelling (e.g. Halti) have similar sizes.

![placename size](https://cloud.githubusercontent.com/assets/8715795/5653887/8132ae1c-96be-11e4-96b2-44c838801b83.png)
http://www.openstreetmap.org/#map=14/47.0005/8.3137

I suggest to reduce the size of suburb names and to increase the size of village names. In fact, some suburbs have a higher population than towns, but suburbs can be part of towns (see the example) and I guess town names are more important than suburb names in most cases.

**Comment by Circeus** [comment]
The issue here is tagging that doesn't follow the recommended usage, not poor display choices. place=suburb and palce=village belong to *separate tagging schemes (urban/rural)*, and subplaces within a village are supposed to use place=neighbourhood. Suburb is intended for larger settlements (namely towns and cities) and uses that size specifically to allow smaller place=neighbourhood below.

**Comment by Rovastar** [comment]
I agree it looks like a tagging issue.

**Comment by pnorman** [comment]
for reference

[`place=town` Horw](http://www.openstreetmap.org/node/240037485)
[`place=suburb` Ennethorw](http://www.openstreetmap.org/node/1406978917)
[`place=isolated_dwelling` Halti](http://www.openstreetmap.org/node/2458246541)
[`place=village` Hergiswil](http://www.openstreetmap.org/node/240128251)

**Comment by Rovastar** [comment]
Thanks for posting what the OP should have done.

It does loo a little odd but I still would not change it for these reasons.
An review of how we do the sizes for all town, suburbs, cities, etc on all zoom levels is need though at some point though as there are some inconsistencies, etc.

**Comment by austi1996** [comment]
I agree that the suburb tagging seems wrong, but it was stated in the wiki (https://wiki.openstreetmap.org/wiki/Key:place) that a suburb can be a part of a town. Consequently, the size of the label should be smaller. Otherwise the town is not recognizable. It is not possible to identify the town name (Rheine) at http://www.openstreetmap.org/#map=14/52.2814/7.4466

More obvious is the small difference of the label sizes of village and isolated_dwelling at z14. If I understand placenames.mss right, village has a text-size of 10 and isolated_dwelling of 9. At z13, only the village name is visible and at z15, the village label has a size of 13 and the isolated_dwelling a size of 9.

**Comment by Rovastar** [comment]
It is difficult to look a one case like you have done here to define and cage all cases.

You will need to compare it to other areas like large cities with suburbs defined.
How often is this does your use case occur?

The other option is to see if there is scope for a change in OSM standards here. Should a small town have the tag suburb the same as a large mega city?

Also there are many other option here, large town text is an option for example.

**Comment by Rovastar** [comment]
For isolated dwelling, personally I would not display them until a really high zoom (they are a couple of houses) but I expect there are militant isolated dwelling fans that want to keep it as is.

**Comment by math1985** [comment]
Maybe rendering suburbs in gray and villages and towns in black would be an idea?

**Comment by Circeus** [comment]
> Maybe rendering suburbs in gray and villages and towns in black would be an idea?

We would have to do the same with cities, but that's not such a bad idea.

I was under the impression that horw was tagged as a village, not a town. My bad. Clearly place=suburb is not an option to tag below place=town, but I'm no clear that we need two levels under that place type anyway.

**Comment by mkoniecz** [comment]
> For isolated dwelling, personally I would not display them until a really high zoom (they are a couple of houses)

Yes, from wiki: "Isolated dwellings are the smallest kind of human settlement. (...) The whole settlement must not consist of more than 2 households.".

**Comment by Rovastar** [comment]
A simple reply with quotes

dieterdreist: "While it is true that they are small, they might still be of local interest / importance for orientation, and as their display is very likely not conflicting with other settlements I'd _not_ ban them to only "really high zoom levels"."

Rovastar: "I expect there are militant isolated dwelling fans that want to keep it as is."

**Comment by pnorman** [comment]
I would not restrict isolated dwellings to high zooms. They may not be particularly important, but by definition they are isolated so will appear in areas with few label conflicts and very few place=* labels.

**Comment by mkoniecz** [comment]
Maybe not restricting, but what about rendering the in a smaller size than village label? Currently difference is quite small at z14.
