### ISSUE TITLE
render building=stadium as a major building

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1205]
related to #1140

Stadiums are landmarks, used by public, widely recognisable.

Currently only building with amenity=place_of_worship are considered as major buildings

**Comment by Rovastar** [comment]
As I have mapped hundreds of stadiums as various project of mine often often I had been and a few of stadium mappers used building=grandstand for parts of the stadium when doing detailed mapping.

Building=stadium actually does not have that many tags 550 at current count so I am not sure for the direct need.

But if it is to go through I would also include building=grandstand.

**Comment by mboeringa** [comment]
In terms of the actual **buildings** of stadiums, there is actually at least three tagging schemes (including the two Rovastar pointed out and I wasn't yet aware of):

- Double tag with **leisure=stadium** and **building=x** (most likely "yes" or "stadium")
- Mono tag with **building=stadium**
- Mono tag with **building=grandstand**

I can imagine the latter is also sometimes, or often, applied to only part of the stadium complex, exactly to which part represent the grandstands. However, for many smaller stadiums, the grandstand is probably the only significant building structure part of the stadium complex. The last two actually need documentation in the Wiki, I don't see both of them listed.

- **leisure=stadium** as mono tag is supposed to include the entire ground, so including pitches etc. See the Wiki.

**Comment by mkoniecz** [comment]
> The last two actually need documentation in the Wiki, I don't see both of them listed.

Good point. I added building=stadium to http://wiki.openstreetmap.org/wiki/Template:Building_typology (I am not sure whatever a separate building=stadium page would be useful).

**Comment by mboeringa** [comment]
I now ran a new SQL render rule with all the three tagging options against my Berlin database. As you can see from the table in ArcGIS, all three options are indeed in regular use, including the **leisure=stadium** with **building=x** double tagging scheme:

![stadium_tagging](https://cloud.githubusercontent.com/assets/7635726/5676405/b5fa93c2-97d5-11e4-8f5d-89172b8e2194.jpg)

**Comment by kocio-pl** [comment]
Current uses:

building=stadium - 794 (+ has wiki page)
building=grandstand - 2 137
leisure=stadium + building=* - 3 810 (also documented on wiki)

Looks like it should be decided on Tagging list to know.

**Comment by Tomasz-W** [comment]
As stadiums are very different to each other - ones are bigger and other ones are smaller, ones are very well-cared for and other ones are abandoned, I don't think that classifying all of them as major building is the good idea. Comments above also proved that tagging of stadiums is not fully clear.
@kocio-pl There was no new comments for almost 2 years here, what about closing it?

**Comment by dieterdreist** [comment]
I am in favor of closing it, just because some stadiums are major buildings doesn’t mean we have to do anything about it to make it visible: it can already be seen by size, shape and urban position that it is a major building.

**Comment by kocio-pl** [comment]
Still even not decided what the stadium should be tagged like, so I will close it now. Can be reopened later if needed.
