### ISSUE TITLE
get-shapefiles.sh crashes on populated places ogr2ogr cleanup

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#121]
On a clean checkout, get-shapefiles.sh crashes on the ogr2ogr cleanup of populated places:

    FAILURE:
    Unable to open existing output datasource `data/ne_10m_populated_places/ne_10m_populated_places_fixed.shp'.

The error disappears when removing '-overwrite' in the following line, so that might be a solution.

    ogr2ogr -overwrite data/ne_10m_populated_places/ne_10m_populated_places_fixed.shp data/ne_10m_populated_places/ne_10m_populated_places.shp

**Comment by kocio-pl** [comment]
> Confirmed fixed. This can be closed.

Seems like forgotten ticket - please close if the problem is no longer an issue.
