### ISSUE TITLE
Rendering office=research?

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1219]
I think we should render office=research area, but I'm not sure how should it look like. R&D offices are something like public/scientific/industrial areas (and are sometimes quite large), but I guess it's not really one nor the other. Examples in Poland:

http://www.openstreetmap.org/way/297349775 (national weather forecast institute - http://www.imgw.pl/index.php?lang=en&option=com_content&view=article&id=147&Itemid=180)

http://www.openstreetmap.org/way/296064476 (building technology institute)

http://www.openstreetmap.org/way/35071468 (physics and organic chemistry institute)

For medical research institutes are quite common to be connected with a hospital, but I think it is a clear choice then.

**Comment by mkoniecz** [comment]
I think that for start http://wiki.openstreetmap.org/wiki/Tag:office%3Dresearch should be improved - before even considering rendering it.

Also, it is used less than 1000 times as an area.

**Comment by AnBuKu** [comment]
would be nice, if office at large would be rendered, as e.g. shop with a
small dot

Am 13.01.2015 um 12:54 schrieb Mateusz Konieczny:
> I think that for start
> http://wiki.openstreetmap.org/wiki/Tag:office%3Dresearch should be
> improved - before even considering rendering it.
> 
> Also, it is used less than 1000 times as an area.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1219#issuecomment-69733586>.
> 

-- 

Andreas Bürki

abuerki@anidor.com
S/MIME certificate - SHA1 fingerprint:
ED:A5:F3:60:70:8B:4C:16:44:18:96:AE:67:B9:CA:77:AE:DA:83:11
GnuPG - GPG fingerprint:
5DA7 5F48 25BD D2D7 E488 05DF 5A99 A321 7E42 0227

**Comment by Rovastar** [comment]
I am not sure I agree with how you are using this tag.
I would expect this tag to be used on the individual office buildings not for land use. 
Sure with the chaos of open tagging anything can be used but I do not think your practice should be incouraged. 
Why not tag the area with the most relevant landuse and do the individual buildings as office=
And personally I would not render these any differently.

**Comment by Rovastar** [comment]
Every office building rendered as a dot sounds a terrible idea.

**Comment by kocio-pl** [comment]
Well, this is exactly my point: I'm not sure what landuse is the most relevant =} , because R&D is intentionally a half way between academic world and practical application (like industry). It can be also a public institution as well (I guess in Poland this is a common case). Oh - and it's the office, of course... 

So we have 3-4 equally valid descritions and that's why I think about it as a separate category of institutions. For me rendering doesn't have to be anything new, but at least uniform (like university or industrial for example).

**Comment by AnBuKu** [comment]
Am 13.01.2015 um 13:42 schrieb Rovastar:
> Every office building rendered as a dot sounds a terrible idea.

Indeed. But this is not the intention! Sorry for modest explanation.

The intention is to render a POI office, as you render a POI shop. But
never a building. E.g. you might have a large building with several
shops and offices, thus the building is rendered separately and the
POI's business and shop are rendered each separately.

Anyhow, I always try to avoid to mix stuff together, but keep it
separated so future updates (businesses / shops come and go, but
buildings stand usually longer) are easier

-> http://wiki.openstreetmap.org/wiki/Key:office
-> http://taginfo.openstreetmap.org/keys/office

> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1219#issuecomment-69738695>.
> 

-- 

Andreas Bürki

abuerki@anidor.com
S/MIME certificate - SHA1 fingerprint:
ED:A5:F3:60:70:8B:4C:16:44:18:96:AE:67:B9:CA:77:AE:DA:83:11
GnuPG - GPG fingerprint:
5DA7 5F48 25BD D2D7 E488 05DF 5A99 A321 7E42 0227

**Comment by althio** [comment]
> it is used less than 1000 times as an area.

And it could be used more with proper wiki documentation as you suggested.
And it could be used more if rendered. This is not tagging erroneously for the renderer, this is better tagging for the renderer and thanks to it.

I think office=research could be rendered with an icon, for instance: ![image](https://cloud.githubusercontent.com/assets/9863567/5721101/a751083c-9b2d-11e4-9162-8b915a7143e9.png)

We have icons for a lot of POI/amenities from libraries and pubs to bakeries and drinking_water, but not for schools and universities and research centers?
Humanitarian-style is rendering schools and ![](https://raw.githubusercontent.com/hotosm/HDM-CartoCSS/master/icons/poi/university-18.png) universities with icons.

**Comment by kocio-pl** [comment]
I like this icon - it nicely blends both (science and experimental/technical) aspects. However could you show how does it look with a proper size? I fear that there may be too much details to recognize it on the map.

**Comment by kocio-pl** [comment]
I was curious how many R&D institutions may be there in Poland/world by name, to know the scale of such POIs not rendered as an area, but ["name"="Instytut*"] (I intended * globbing) did not work in Overpass-turbo.eu service. How to do it properly?

**Comment by althio** [comment]
[previous message EDITED to add smaller icons]
Please note I have no rights on this particular icon. It is just an exemple that I found interesting and I included it for illustration and discussion.
Also, this is a plain bitmap image and it was scaled down in a crude way. Both image and scaling might be improved.

**Comment by mkoniecz** [comment]
> but "name"="Instytut*" (I intended * globbing) did not work in Overpass-turbo.eu service. How to do it properly?

See http://overpass-turbo.eu/s/70e and http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Value_matches_regular_expression_.28.7E.2C_.21.7E.29

>  I would expect this tag to be used on the individual office buildings not for land use. 

It is necessary to define and document on wiki how tag is supposed to be used. Without that - it is hard to use it.
