### ISSUE TITLE
Masts are not always for communication

### ISSUE THREAD

**Issue by sanderd17** [gravitystorm/openstreetmap-carto#1225]
The tag man_made=mast only says something about the physical look of the structure, not it's function. See http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmast

Next to communications, it can also be used for lightening (of football stadions f.e.), or for sports like popinjay archery. 

Currently, the icon communications.p.20.png is used for all man_made=mast objects, that icon has a visualisation of "broadcasting" next to the mast view.

According to the wiki, it's advised to add tower:type=communication if the mast is used for communication purposes. 

So I propose to use a version without broadcasting for a simple man_made=mast, and a version with broadcasting when tower:type=communication is added.

I made a simple icon of a mast, based on the communications icon, but where I just coloured the broadcasting stuff away. I hope it's good enough.
![mast](https://cloud.githubusercontent.com/assets/562171/5740260/ffe27a4c-9c01-11e4-838f-7b5ccb664603.png)

**Comment by HolgerJeromin** [comment]
related to #339

**Comment by nebulon42** [comment]
I thought too that this needs upgrade, but it seems that `tower:type` is in the rendering database already ([openstreetmap-carto.style#L137](https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.style#L137)).
