### ISSUE TITLE
circular cliffs are not rendered

### ISSUE THREAD

**Issue by fkv1** [gravitystorm/openstreetmap-carto#1227]
Necessary work has been done in the wiki to reapproach issue #268. There is no reopen function, so I hereby open a new issue for the same thing. See original issue for details.

**Comment by math1985** [comment]
Relevant section from the wiki:

> Closed ways shall be rendered in the same style as open ways, unless the tag is accompanied by area=yes or set on a multipolygon relation. In those cases, applications are advised to treat natural=cliff as an obsolete synonym for the newer tag natural=bare_rock.

**Comment by kocio-pl** [comment]
The same for man_made=embankment.

**Comment by pnorman** [comment]
duplicate of #268 - issues can be re-opened by maintainers.
