### ISSUE TITLE
text rendering problem for Arabic script languages

### ISSUE THREAD

**Issue by aso-mehmudi** [gravitystorm/openstreetmap-carto#1230]
"Arial Unicode Ms" does not support Arabic script languages completely. for my language, Central Kurdish language (ckb) which is also using Arabic script, certain special Unicode characters are shown wrongly. please use these fonts instead:
1. "Tahoma" and "Tahoma Bold" (ver. 5+)
2. "Segoe UI" and "Segoe Bold" (ver. 5+)
3. "DejaVu Sans" family (Ver. 2.33+)
they are perfect for Arabic script languages in small sizes.

**Comment by pnorman** [comment]
> "Arial Unicode Ms" does not support Arabic script languages completely.

We are not using Arial Unicode - the [font list](https://github.com/gravitystorm/openstreetmap-carto/blob/master/style.mss#L5-L16) only has openly licensed fonts.

please use these fonts instead:
> 1. "Tahoma" and "Tahoma Bold" (ver. 5+)
> 2. "Segoe UI" and "Segoe Bold" (ver. 5+)
> 3. "DejaVu Sans" family (Ver. 2.33+)
> they are perfect for Arabic script languages in small sizes.

DejaVu Sans is the font used. The version is a deployment issue, but given that my Ubuntu 12.04 server has 2.33, the production rendering servers will have at least that.

> for my language, Central Kurdish language (ckb) which is also using Arabic script, certain special Unicode characters are shown wrongly. 

If you have examples of incorrectly rendered text, can you please provide a link to the object being mis-rendered, a screenshot of how it currently looks on the map, and a screenshot showing how the text is supposed to look.

**Comment by aso-mehmudi** [comment]
coordinates: 36.02061/45.81650
Kurdish Wikipedia article: http://ckb.wikipedia.org/wiki/%D8%B3%D9%88%DB%8E%D8%B1%D9%88%DB%8E

![osmkurdi](https://cloud.githubusercontent.com/assets/4657223/5773100/a21a9ec2-9d72-11e4-9f87-e3ec4551f217.jpg)

**Comment by pnorman** [comment]
http://www.openstreetmap.org/node/3275074925

**Comment by gravitystorm** [comment]
Can someone try this with mapnik master and see if the harfbuzz improvements fixes this?

**Comment by aso-mehmudi** [comment]
this problem really makes me reluctant to add names to features. please fix it before the amount of data in our region get increased. thanks.

**Comment by math1985** [comment]
> Can someone try this with mapnik master and see if the harfbuzz improvements fixes this?

I don't have mapnik master installed, does anyone of us?

**Comment by pnorman** [comment]
@springmeyer is there a way to get node-mapnik to build 3.0.0-RC1 with command line flags when installing something (i.e. kosmtik) which pulls it in? I'd prefer not to install a systemwide unreleased Mapnik, but probably have a machine somewhere I can do that on if all else fails.

**Comment by pnorman** [comment]
fixed by mapnik 3, so closing in favour of #2017
