### ISSUE TITLE
Hostel icon not rendered on recreation_ground

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#1232]
tourism=hostel + landuse=recreation ground is a typical combination for bungalow villages.
http://overpass-turbo.eu/s/73y

Usually the label is written in the landuse style, thus the hostel icon is not rendered. 
In the case the map is centred to, the playground node in the centre seems to block any label or icon. 

Shouldn't *-placement = interiour also look for positions that are not in the centre?

Edit by @math1985:
* [x]    Recreation ground names have higher priority than hostel names
* [x]    The playground icon blocks the rendering of the hostel name

**Comment by pnorman** [comment]
> Shouldn't *-placement = interiour also look for positions that are not in the centre?

No, I don't believe point symbolizers will try multiple locations without explicitly setting the other locations, which is not possible in CartoCSS without some hackish workarounds.

**Comment by polarbearing** [comment]
Should a tourism or amenity label be written with higher priority than the landuse (in particular as they have the same size)?

**Comment by math1985** [comment]
There are two issues here:
* Recreation ground names have higher priority than hostel names
* The playground icon blocks the rendering of the hostel name

**Comment by math1985** [comment]
>  The playground icon blocks the rendering of the hostel name

This is duplicate with #964.
