### ISSUE TITLE
Improvements for rendering of highway=motorway_link on bridges?

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#1236]
The rendering of highway=motorway_link is not as nice here if it is on bridges:

http://www.openstreetmap.org/#map=18/5.29604/-3.98160

![3](https://cloud.githubusercontent.com/assets/6830724/5788717/bb787e30-9e3e-11e4-9995-7a60392ed0df.png)
?

– The connection of the highway=motorway_link with the primary road?

– The connection of ghe highway=motorway_link ways with the highway=motorway way?

Or is this a problem of the tagging

**Comment by math1985** [comment]
– The connection of the highway=motorway_link with the primary road?

That's a tagging problem, probably the link is not yet a bridge at the point where it branches of the primary.

> – The connection of ghe highway=motorway_link ways with the highway=motorway way?

This needs investigating, but it might well be that there's nothing we can do about that.

**Comment by sommerluk** [comment]
> That's a tagging problem, probably the link is not yet a bridge at the point where it branches of the primary.

Yes, but the distance is really small – not much more than 5&nbsp;meters. Probably not enough to solve the rendering issue on zoom levels lower than z18.

However, it’s a rather rare case. Should I close this issue?

**Comment by math1985** [comment]
It doesn't look like we can solve this problem without creating problems in other situations. I will therefore close this issue.
