### ISSUE TITLE
Odd "corner" effect with leisure=nature_reserve

### ISSUE THREAD

**Issue by SomeoneElseOSM** [gravitystorm/openstreetmap-carto#1237]
Something very odd is happening in the corner here:

http://www.openstreetmap.org/#map=19/53.19758/-1.10464

Zoom out a bit and the effect is more pronounced:

http://www.openstreetmap.org/#map=11/53.1964/-1.1045

It seems that the first and last node of the way

http://www.openstreetmap.org/node/324376900

is treated differently from the others - it gets the "inside" bit of the nature reserve effect added around it as if it wasn't part of a closed way.

**Comment by floscher** [comment]
This is the same issue as in #481.

**Comment by SomeoneElseOSM** [comment]
So it is - thanks.
