### ISSUE TITLE
amenity=town hall only renders on the Humanitarian Layer

### ISSUE THREAD

**Issue by Drew-NL** [gravitystorm/openstreetmap-carto#1244]
When trying to add town hall to Petty Harbour I noticed it only renders on the Humanitarian layer and not on the Standard Layer.

Below are two examples
http://www.openstreetmap.org/edit#map=19/47.56156/-52.71255
The Town Hall is next to stadium.

http://www.openstreetmap.org/edit#map=19/47.46491/-52.70870
The Town Hall is at 35 Main Street

**Comment by math1985** [comment]
Duplicate with #77. Feel free to propose an icon - I think the Humanitarian icon is too similar to our museum icon.

**Comment by Drew-NL** [comment]
My bad, did a search and did not find the issue, missed the two tabs in the results for code/issues.
