### ISSUE TITLE
Render junction=yes on areas

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#1253]
Since #813 the name of junction=yes is rendered on points. This tagging is used for simple junctions. A tagging for complex junctions was in discussion when #813 was merged. In the meantime, discussion/voting has been terminated. So it would be nice to render the name of junction=yes also when it occurs on areas (same font/style like on points).

**Comment by sommerluk** [comment]
I suppose this means changing openstreetmap-carto.style?

**Comment by math1985** [comment]
No, we have the junction key in the database: https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.style

**Comment by sommerluk** [comment]
@math1985 Yes. I thought that it would be a problem for areas, because it’s only “linear”, not “polygon”? (I had tried to make a PR, but I failed due to a lack of knowledge about the import and a total lack of knowledge of SQL ;-)

**Comment by math1985** [comment]
Hmm, maybe you're right, I guess it should indeed be polygon.

**Comment by math1985** [comment]
Better done in pg2psql.

**Comment by sommerluk** [comment]
@math1985 Should I open a ticket at osm2psql for this?

**Comment by math1985** [comment]
@sommerluk No, I think we can solve it in our own osm2pgsql style/lua file.

**Comment by Codain** [comment]
I'm interested in this feature. Is there any progress so far? I don't think I can help since I don't know the project code and have no test bench.

I think that simply displaying the junction name at the center of the polygon (as if it was a node) is enought, no need to draw the outline at the moment.

**Comment by kocio-pl** [comment]
The milestone says it would need to change database layout - could someone confirm (or negate) it?

**Comment by pnorman** [comment]
> The milestone says it would need to change database layout - could someone confirm (or negate) it?

We need junction=yes as areas.

**Comment by dieterdreist** [comment]
sent from a phone

> On 3 Dec 2016, at 09:17, Paul Norman <notifications@github.com> wrote:
> 
> We need junction=yes as areas.


junction=yes seems to be a property of a feature, similar to bridge=yes or tunnel=yes or covered=yes or oneway=yes
For a feature I'd recommend a different tagging scheme, e.g. highway=junction

**Comment by sommerluk** [comment]
Can be resolved without database reload by #2484

**Comment by jojo4u** [comment]
> For a feature I'd recommend a different tagging scheme, e.g. highway=junction

Yes this is usually valid but here we have colliding [highway=traffic_signals and junction](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Named_traffic_signals.2Ftraffic_signal_systems_.28Japan..._.29). But further discussion about tagging should be done elsewhere.

**Comment by dieterdreist** [comment]
2016-12-05 10:20 GMT+01:00 jojo4u <notifications@github.com>:

> Yes this is usually valid but here we have colliding highway=traffic_signals
> and junction
> <https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals#Named_traffic_signals.2Ftraffic_signal_systems_.28Japan..._.29>.
> But further discussion about tagging should be done elsewhere.
>


IMHO these are different things, one is to tag traffic lights, the other to
tag a junction. There is no conflict, but if this is wanted the traffic
signals tag might eventually be incorporated as a property into the
junction object.

**Comment by kocio-pl** [comment]
Resolved by https://github.com/gravitystorm/openstreetmap-carto/pull/2510.
