### ISSUE TITLE
Rendering Wadi and Intermittent River/Stream

### ISSUE THREAD

**Issue by RAytoun** [gravitystorm/openstreetmap-carto#1255]
@mkoniecz , @math1985 
Hi, my name is Ralph (RAytoun) and I have been a cartographer all my working life. I was Senior Cartographer in Philip's School and World Reference Atlas section...responsible for the research and compilation of all new mapping, additions and amendments for the full range of Philip's World Atlas products. I am at present a member of HOT and a principal tutor for the Missing Maps Project, London.
I have raised a few points in this regard and have been pointed in your direction by Blake Girardot.
I see this issue was under discussion in September last year. Math1985 mentions intermittent should be different to wadi which is quite correct....mkoniecz said wadi is a term for a whole valley as well as dry stream which is also correct but may I add that in the parched and arid areas where wadis abound the sides of these "valleys" are sheer cliff walls and the floor of the valley is a dry flat flood plain. The sides of the flood plain would be added the same as for river banks but the outline would be a pecked line with no fill or is sometimes depicted with a light brown stipple fill.
My points are...
I would like to raise the issue of tags for waterway=river, waterway=stream and waterway=wadi.
The problem that exists with the existing tags is that there is no visual difference on the map for a stream (perennial) and a stream (intermittent) and the only other option is wadi which gives a blue pecked line.
Accepted mapping standards for this would be to show:-
 all perennial rivers and streams as a continuous solid blue line (indicating that there is flowing water all year round) or solid blue outline (river banks) with a light blue fill.
 all non-perennial rivers and streams as a continuous blue pecked line (indicating that there is flowing water during the wet season but not the whole year). River banks would be pecked blue line with light blue fill.
A wadi would be depicted with a continuous pecked brown line (indicating that it is dry watercourse and could be dry for years at a time...only flowing if there is a flash flood or unusually heavy rain). For wider wadis (valleys) a pecked brown outline with no fill or brown stipple fill.
This would then convey the correct meanings with symbols on the map and make reading the map a lot easier. The categories would still be searchable and distinguish between the three categories of water flow.
The proposed tags would then be
waterway=river ...... waterway= stream ...... continuous solid blue line
waterway=river_intermittent ...... waterway=stream_intermittent ..... continuous pecked blue line
waterway=wadi ..... continuous pecked brown line (a wadi can be so wide that another tag would be needed similar to the tag for river banks) waterway=wadi_bank which would still be a brown pecked line either with no fill or a brown stipple fill.
This would then ease the path for introducing the tags for perennial lakes with a solid blue outline and lighter blue fill, intermittent lakes with a blue pecked outline and a light blue fill and dry pans with a brown pecked outline with a brown stipple fill.
If it is deemed appropriate is there someone who could do this or help me?
Reference...... http://pubs.usgs.gov/gip/TopographicMapSymbols/topomapsymbols.pdf

**Comment by imagico** [comment]
This is the wrong place for discussing tagging ideas, this should be done on the wiki or the tagging mailing list.

Discussion here should focus on how to render tags currently in use and current consensus is that use of `waterway=wadi` is not very consistent and therefore it is not very productive to use this tag and it should not be rendered in any special way.  Special display of intermittent waterways is currently in work in #1000.  Use of additional tags for further differentiation might be considered but the `seasonal` key (see #805) is currently not available and other tags are not widely used.

**Comment by mkoniecz** [comment]
> Special display of intermittent waterways is currently in work in #1000

To be more exact - work is finished and it waits for other maintainer with time to review it.

**Comment by mkoniecz** [comment]
Closing per

> This is the wrong place for discussing tagging ideas, this should be done on the wiki or the tagging mailing list.

**Comment by RAytoun** [comment]
Hi Mateusz,
Sorry to confuse, my point here was not about the tagging, that was a
possible example.
My point here was about the rendering of waterways. As has been pointed out
to me...this is in hand at the moment. I sent math1985 a response
explaining my position in mapping more remote regions of the world that
would require these symbols and differentiation between wadi and
intermittent stream. I have also now been made aware that the base map
rendering is following that of Michelin Maps. A have worked with and am
familiar with their maps. It is a very successful series of maps. However
they are first and foremost Road Map orientated with less emphasis on the
rendering of specialist background geography, which is what we are dealing
with here.
I can see from the defensive responses that have ignored my points on the
rendering and prefer to attack me about "not the place for tagging" that I
appear to be not welcome. I an still offering my specialist knowledge with
regard to map symbols and their depiction if you are interested in making
use of it.
Thanks for your time in responding to my email. I shall await the outcome
of your amendments to the rendering to see whether it is suitable for the
requirements of other parts of the world.
Have a nice day
Ralph

**Comment by imagico** [comment]
> I can see from the defensive responses that have ignored my points on the rendering and prefer to attack me about "not the place for tagging" that I appear to be not welcome.

I am sorry if my reply appeared defensive but no one attacked you in any way.

If you think the representation of certain geographical features in OpenStreetMap is insufficient (which i agree wholeheartedly to) the usual way would be to:

1. develop a tagging scheme for those features based on [established](http://wiki.openstreetmap.org/wiki/Verifiability) [principles](http://wiki.openstreetmap.org/wiki/User:Joto/How_to_invent_tags)
2. use this tagging to map things
3. document your tags on the wiki
4. get others to map things this way as well
5. get the tagging to be rendered in this map style

From classical cartography work you are probably used to a different approach, i.e. first develop a classification scheme based on rendering considerations and then map things according to this scheme but the above is how it is done in OSM.  This forum only deals with the last point and this requires the first four things to be done already at least to some extent.  I merely tried to point you to this by summarizing the current state of these things wrt. wadi/intermittent waterway mapping.

**Comment by RAytoun** [comment]
Again thanks for the response. I am trying to find my way around and being
pointed to various sights where my only approach is to mention the problems
I am having in the hope that I could eventually reach some kind of
compromise that suits everyone. Just one request....please do not do away
with wadi just yet, it has many specific functions as a wadi, dry gulch,
arroyo, wash, etc. to name a few uses in various parts of the world. You
are spot on regarding the way I have been used to setting things up and
will try to adapt to the OSM pattern of approach. I look forward to seeing
the results of your rendering of intermittent rivers and streams.
Thanks for your help in pointing me in the right direction.
If you have any questions regarding symbols on a map please feel free to
ask. (Example..understanding what is meant by a wadi also being a valley)
Regards
Ralph

**Comment by math1985** [comment]
Welcome @RAytoun! I think your request is essentially the same as #805, so I think it's best to continue the discussion there. I have just merged #1000, which is meant to resolve #805. This will be visible on the main site within a couple of weeks.

Note that waterway=river_intermittent is in fact tagged as waterway=river, intermittent=yes.

With the new rendering, waterway=river, intermittent=yes will be rendered just like wadi, namely as a pecked blue line. We might consider distinguishing river=wadi and intermittent=yes in the future, but a pecked brown line is probably not the best option as we use this for tracks already. By the way, I haven't seen that many maps of wadis, but the ones I have seen all render wadis as a blue pecked line rather than a brown one.

**Comment by RAytoun** [comment]
Thanks for that. I made a comment regarding that before I received this.
You guys are doing a great job and it is appreciated. I and some of our
mappers will be appreciative of the new look of the intermittent waterway.
I can concur that a brown peck will clash with tracks, but as was said this
is something to be addressed at a later date when mapping of remote areas
picks up.
Thanks again for your time and responses.

**Comment by Rovastar** [comment]
RAytoun,

It could be that these are rendered at some point in the main map style but it sounds a more specific need for you (and is most useful) in humanitarian situations so you should focus on getting this rendered for the HOT/humanitarian style first.
This would be more relevant for that map style than the main one and you could then show a better vitalization first and then  it could be done here if suitable.
