### ISSUE TITLE
Add area render for tourism=attraction

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#1257]
@gravitystorm suggests [here](https://github.com/gravitystorm/openstreetmap-carto/pull/1063#issuecomment-67853592) about tourism=attraction:

> [..] we'll need to consider some sort of area rendering in the future otherwise we end up with floating labels with no indication what extent they refer to.

**Comment by mkoniecz** [comment]
Where it would be useful? in my experience tourism=attraction is applied to very small object where rendering area is not useful or objects that are rendered anyway.

The only use-case where it maybe would be useful is Speakers' Corner in Hyde Park.

**Comment by moliha** [comment]
Below are two examples of attractions that are areas, shown with:  
- The current grayish Mapnik-rendering  
- The current redish Cycle-rendering (and former Mapnik-rendering): 

"Den Fynske Landsby" in Odense, Denmark:  
- http://www.openstreetmap.org/#map=16/55.3647/10.3835  
- http://www.openstreetmap.org/#map=16/55.3647/10.3835&layers=C  

"Den Gamle By" in Aarhus, Denmark:  
- http://www.openstreetmap.org/#map=17/56.15878/10.19169  
- http://www.openstreetmap.org/#map=17/56.15878/10.19169&layers=C

The redish rendering makes it easy to see the extent of the attraction-area.

With the current grayish Mapnik-rendering it can be difficult to distinguish the attraction-area from some of the surrounding areas.

I think there are many such cases where a distinct coloring of atraction-areas is useful.

One additional point: the redish color used for attractions by Cycle and formerly by Mapnik is perhaps too close to the color used for retail and industrial areas. Some adjustnents of these colors could also be useful.

Note: In case the rendering is changed,images from the above links can be seen at  
http://mlha.dk/osm/attraction.htm

**Comment by mboeringa** [comment]
> The only use-case where it maybe would be useful is Speakers' Corner in Hyde Park.

That is an extremely bold statement that unfortunately doesn't hold up. Look at this image of Berlin city centre made with my OSM Renderer for ArcGIS. Just in this small section of the German capital alone, there are at least 7 different **non-**building features tagged with **tourism=attraction**, including really prominent ones like:

- Museuminsel
- Nikolaiviertel
- M. Heckmann hofe
- Hackeschermarkt

There are *many* of such non-building tourist marked features world wide...

Please click the image to see it properly enlarged.

![berlin_centre](https://cloud.githubusercontent.com/assets/7635726/5905832/58e8cf48-a593-11e4-9150-c4bf0c1ccda1.jpg)

**Comment by dieterdreist** [comment]
2015-01-26 19:43 GMT+01:00 mboeringa <notifications@github.com>:

> The only use-case where it maybe would be useful is Speakers' Corner in
> Hyde Park.
>
> That is an extremely bold statement that unfortunately doesn't hold up.
>

+1


> Look at this image of Berlin city centre made with my OSM Renderer for
> ArcGIS. Just in this small section of the German capital alone, there are
> at least 7 different *non-*building features tagged with
> *tourism=attraction*, including really prominent ones like:
>
>    - Museuminsel
>    - Nikolaiviertel
>    - M. Heckmann hofe
>    - Hackeschermarkt
>
> There are *many* of such non-building tourist marked features world
> wide...
>


yes, but just because they aren't buildings doesn't mean they can't be
mapped with tags that say what they are (series of close by museums
connected recently to become one big complex, disney land like
1987-socialist-reconstruction with precast concrete of a former historic
quarter in the heart of Berlin, series of connected backyards, central
neighbourhood filled up with tourist gyp).

A tourist attraction is nothing on its own, it is a feature that has the
attractiveness for tourists as an attribute.

**Comment by katpatuka** [comment]
I'm usually mapping a lot of area-style touristic attractions in Turkey and China - most of them are historically ruins or archaeological sites - so I feel the ___need___ for colored areas. Up to yesterday they where rendered pink which was ok for me... whoever decided to change that back again... :/

**Comment by matkoniecz** [comment]
I thought about rendering it like zoos/theme parks but with subtler border.

**Comment by polarbearing** [comment]
+1

**Comment by dieterdreist** [comment]
sent from a phone

> Am 26.08.2015 um 20:28 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> I thought about rendering it like zoos/theme parks but with subtler border.


I see this tag as a qualifier, it only makes sense in combination with a tag that says what it is, and when it is present it could raise the "importance level", e.g. it could be rendered/labeled earlier (in terms of rendering order and/or zoom level) than the same object without the tag (I acknowledge that this concept will lead to more complex rendering rules).

**Comment by daganzdaanda** [comment]
Just wanted to push this, because of the similar problems in #2700 and #2839. The difference seems to be that here we are already showing a label, but this label is not dependent on the way_area. Nevertheless, I believe rendering an outline like zoo/theme park as proposed above would be sensible.

**Comment by kocio-pl** [comment]
Could you prepare a PR resolving this issue?

**Comment by polarbearing** [comment]
related to #2704 (museum area)

**Comment by daganzdaanda** [comment]
> Could you prepare a PR resolving this issue?

Sorry, I haven't got the time to start to learn this... Though maybe sometime in the next year or two ;) I really want to try a Docker installation and see what comes out from it.

**Comment by Tomasz-W** [comment]
I'm against rendering this feature with special outline, because it's very rare case that object is mapped only as tourism=attraction area, without some other tag which give the object it's shape/ outline. As I check in Overpass turbo, most of cases where there is only tourism=attraction tag, is just indicative area (there is no fence/ wall etc., but it's just object aproach mapped), so with outline it would give a little bit false information.

**Comment by matkoniecz** [comment]
I think that we should not render it as area. Even rendering name is a bit dubious, but rendering it as an area would further discourage from adding also primary tags actually describing the feature.

Rendering `tourism=attraction` labels is barely acceptable as there are many, many different small objects where some instances of them are for some reason interesting. Rendering all of them as icons is not going to happen.

But for large areas where displaying area would be useful any object should have already a proper tah that should be used.

I will not go as far as to propose dropping rendering of `tourism=attraction` labels but adding area rendering will not help.

**Comment by kocio-pl** [comment]
I agree that current compromise is enough.

**Comment by matkoniecz** [comment]
In case that there are some large-scale objects that for some reason can not be tagged with anything except tourism=attraction (I expect that there are no such objects) then let us know in a comment.

**Comment by BertMule** [comment]
I support this request.

I just ran into the problem where an attraction area isn't rendered, neither is the name.
Which, as usual, is very frustrating.
The purpose was to indicate the fenced area of the attraction, containing buildings that belong to it.

Please give it some contrasting colour and display the name.
