### ISSUE TITLE
Render Admin_level=4 similar to level 3 in Japan

### ISSUE THREAD

**Issue by javbw** [gravitystorm/openstreetmap-carto#1258]
Currently, there is no admin level 3 in Japan.  There is no "state" system in japan, though it is being debated by the government. Currently, the highest admin boundary inside Japan are the prefectures (level 4), and regional names are historical nicknames.  A Russian mapper recently added Admin_level 3 to the previously mapped (but leveless) regions, though the Japanese wiki explicitly states that admin 3 is reserved for the future states (it has been since before I was a mapper). I just messaged him to revert his changes. 

http://wiki.openstreetmap.org/wiki/Japan_tagging#Boundary

I would like to request that since Japan's provinces are treated like states, that they be rendered with a border similar to admin level 3. I'm not sure if it is possible to render one countries level 4 as a level 3 boundary, but it is appropriate to do so in this case. It is very difficult to see the prefecture boundaries currently. In 10 years (or more) when states are formed from the existing provinces, then it can be reverted to a standard level 4 rendering. 

Although the region names (and areas covered) are popularly used to represent groups of prefectures, 
http://www.craftmap.box-i.net/japan_sozai/picture/0021/0021_5b.gif

it is not an *administrative* boundary - like "So-cal" or "the central valley" are commonly used region names in California, but have no administrative power. This is why admin_level=3 is reserved for the future states.

A purely political map of Japan it will not include the regions. 
http://rousai.kuronowish.com/nippon/japan.gif

Javbw

**Comment by Rovastar** [comment]
It is not possible to render different features based on location.

**Comment by javbw** [comment]
So the only way to have them render as admin 3  is to move the provinces up to admin 3 and back down to admin 4 when the states show up? 

Javbw

**Comment by Rovastar** [comment]
I am not sure what your community wants to do. Technically it is not possible, which is the question you asked.

Actually though I would question why you even want this?

http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative
US states are on admin level 4. As are countries in the UK.
Now other countries go the other way and tiny areas are assigned to level 3.

Inconsistent admin levels for me the biggest pain for low zoom carto in the openstreetmap community. Tagging standards for admin levels are all over the place country by country.

Having no global standard for admin levels sadly will never happen.Getting the community to thankless and time consuming task and that require real decision making.making and those things will never occur in OSM.

**Comment by pnorman** [comment]
> So the only way to have them render as admin 3  is to move the provinces up to admin 3 and back down to admin 4 when the states show up?

The only way to have something render as admin level 3 is for it to be admin level 3. You're approaching this from the idea of having a solution, not from having a problem.

**Comment by math1985** [comment]
In addition, it would be very confusing for mappers if admin_level=4 behavws different in Japan. I will therefore close this issue.

However, I'm planning to rework the way admin boundaries are currently rendered, so that might solve the problem of bad visibility of the borders.
