### ISSUE TITLE
Power lines too prominent at z14

### ISSUE THREAD

**Issue by javbw** [gravitystorm/openstreetmap-carto#1260]
I feel the power lines are too prominent with the current color, and appear at too low a zoom level (z14)

Please remove them (or at least lighten them) in the z14 and z15 render, as they are easily mistaken as a feature that can be ineracted with (a train line) or a barrier to travel (such as a river,wall, or some other kind of barrier or boundary.  I know that by looking at the key it's meaning is easily understood, but it is too prominently rendered for what little importance it has to people looking at a map at z16, especially in cities where high voltage lines come together and cross many road and train lines. 

Where I am mapping, many high voltage towers converge (or pass nearby) to supply Tokyo with electricity, coupled with the fact that in Japan, a solid black like is reserved only for private train lines (the striped lines are for national JR rail only) 

So there is a double whammy of not only the -carto not following regional mapping customs, plus the power lines are rendered in a manner that makes it very distracting. 

https://goo.gl/maps/qAnBR  (I’m not basing this on google’s stylesheet for the map - they are following Japan’s historical mapping tendencies)
Please note the upper train line is black. The lower train line is striped. 

http://www.openstreetmap.org/#map=14/36.3835/139.1072  (zoomed in a bit)
Wow - the private train lines now run north-south! how useful! 

Add: http://www.openstreetmap.org/#map=14/36.3525/139.0275  Takasaki City looks horrible too.

Since I cannot implement a change to the render of the train lines (giving mappers the ability to add a color tint or style to the line to match regional customs or local line colors), at least I can request that power lines be made less prominent on a map covered with softer colors and grays for truly useful objects.

**Comment by Rovastar** [comment]
First off I will repeat, technically we cannot do regional items so stop implying you are being oppressed here by not being allowed to do things.

Second oprnstreetmap carto is not meant to reflect historical local customs of the map design for every country on the planet. It is meant to be a general style.

We also cannot render different things based on sparse/dense areas so what we render for dense cities in Tokyo is the same for a rural area of France.

Now onto the specifics of pylons and their power lines.

Some will regard these as useful. If you are in rural setting they can be very useful for orientation given little else around. You can actually see them often very visibly - they can be huge power lines connected to huge pylons. 
Now I appreciate you are not likely a member of http://www.pylons.org/ but showing these is useful to many.

We could look at the colour of the lines maybe lighten them up a bit as everything else is lighter but if we do that (and keep doing it for others) we get into a set of greys are all things like trams lines, walls, power lines, etc.

Now about the confusion, yes I agree it can look like other things, trams, walls, etc.
Maybe would could actually make these electricity lines more visible (I know emergency/danger of death is popular things to be rendered) instead of or as well as lightening up.
Maybe with a electric lighting bolt zap symbol, or something
⚡ 
or
https://www.google.co.uk/search?q=electricity+lightning+bolt+logo&source=lnms&tbm=isch&sa=X
or
https://www.google.co.uk/search?q=electricity+symbol&biw=1366&bih=606&source=lnms&tbm=isch&sa=X
That would actually make more sense on the rendering maybe spaced out over the power line like the arrows are on the one way roads.
I presume that zap is fairly understandable globally for electricity?

**Comment by javbw** [comment]
> On Jan 27, 2015, at 10:55 AM, Rovastar <notifications@github.com> wrote:
> 
> First off I will repeat, technically we cannot do regional items so stop implying you are being oppressed here by not being allowed to do things
> 
When I was asking for a regional issue (the boundaries), I really have no idea what -carto is capable of, since I’m an basically an end user of -carto, not a contributor, if you don’t count my (apparently annoying) issues / comments on the issues.

This  (side) issue with the train is different, as it is a lack of flexibility in the interpretation of existing tags (colour=*). Adding the flexibility would give that ability to all users in all regions, not just myself in Japan. I use Japan as an example not only because it is where I’m living/mapping, but has regional issues that come up in all manner of tags, and (to me) is a good test of supporting things that may not be an issue when tagging Germany, but would come up with tagging other non-western countries - particularly religion, transport, and object labels. Rendering and tagging support is slowly being fleshed out for non-christian religions, and there are still font/rendering issues for character based languages (Japanese / Chinese, etc). 

figuring out a solution to show custom colors on a train line to reflect regional colorations of the train system that are common throughout the world is a good idea, and I feel its lack of support in -carto is an oversight that should be corrected sooner than later. creating a system to add and curate region specific symbols (if the differentiation is tag based - not region based) is something that would help as well. 

I feel no oppression, but I feel some frustration that rigidity causes regional issues that could otherwise be avoided. by not having a render for the colors/styles of the train system (or certain motorway applications) in -carto creates a much less useful map for places dependent on trains - or even in California - where the LA metro and San Diego trolley are heavily color-dependant on their train labeling.  

This rigidity is reflected in other frustrations below, as the point of my issue ticket is the power lines.

> Second oprnstreetmap carto is not meant to reflect historical local customs of the map design for every country on the planet. It is meant to be a general style
> 
Adaptability to regional customs, within reason (iconography, coloring) should be considered essential if we expect locals to use it. Otherwise it is a map for tourists. not only are you competing against Google and bing, but other local/regional mapping agencies for eyeballs. Google Japan and google US used to look totally different (and Tokyo is still the densest render I have ever seen on Google Maps), and a trip to Korea surprised me with how Google handled their train system differently than than japan or the US - as they were catering to the locals rather than the home office in Mountain View. 

Working with the tagging mailing list to make tags and -carto to render the tags together is the only way to accomplish something like that, which is what I am trying/hoping to do. 

In this case another rendered item (power lines) clashes with a local custom exacerbating an issue.  Don’t misunderstand me - I’m not saying we should change the power lines just because it conflicts with my region’s customs - but it does make a bad situation more noticeable, which is why I i am bringing it up here as an issue. And eventually I hope to solve other regional issues as well through adding additional flexibility/support into the tagging choices.

Now onto the purpose of this ticket. 
> We also cannot render different things based on sparse/dense areas so what we render for dense cities in Tokyo is the same for a rural area of France
> 
I know how they stick out in rural areas. here’s a pic I took https://www.flickr.com/photos/javbw/11091396333/in/set-72157638113676925

Even if they were rendered at 50% grey, if they were one of the few landmarks visible on the map ( I assume in a sea of green woods or brown farms) the line would stick out like a sore thumb, even though it wouldn’t jump out as it does now. and it could easily fit in with the softer OSM renders.

> Now onto the specifics of pylons and their power lines.
> 
> Some will regard these as useful. If you are in rural setting they can be very useful for orientation given little else around. You can actually see them often very visibly - they can be huge power lines connected to huge pylons. 
> 
I personally orient myself by mountains, so I understand how useful large items can be. (I wish mountain sizes/labels were somehow supported better in -carto as well). 

The tallest power towers I have ever seen are behind my house. they are about 15 stories tall. I can see them from 10-15km away. Others nearby have 6-8 strands per conductor, making them some of the thickest power lines in the world (as I understand it), as they are built to handle 1 million volts. I understand their scale and visibility. 

Whats the first man-made thing you notice in this picture?

https://www.flickr.com/photos/javbw/11091304694/in/set-72157638113676925
> Now I appreciate you are not likely a member of http://www.pylons.org/ <http://www.pylons.org/> but showing these is useful to many.
> 
I’m not a member, butI tagged several of the lines and substations visible in my previous post's example near Maebashi. I think it is proper to represent the system in OSM.
> We could look at the colour of the lines maybe lighten them up a bit as everything else is lighter but if we do that (and keep doing it for others) we get into a set of greys are all things like trams lines, walls, power lines, etc
> 
> 

If we’re gonna have something ~100% black render over softer colors, why don’t we make something useful, public, and transportation related stick out? How about (public transport related) train lines? And then make the power lines grey?  

I’m not saying that changing the power lines is dependent on changing the trains, I’m pointing out that it eventually came to be that trains (and a lot of other things) are grey and the power lines are very black, and hey, that isn’t very useful and something should be done about that, cause it’s annoying - particularly annoying where I live because it implies “train”.  So here I am. Asking for a remedy to the situation that will help *all mappers in all regions* - not just myself in my little corner of Japan. 

I do object to the prominent rendering of something that, overall, is not a major part of the road system with a strong showing at z14-16, which is probably the most useful zoom range for seeing a large city’s road system - so it is detriment to the map. I have never seen it rendered on any other map (google/bing/apple/ mapion/zenrin/mapple), though zenrin/google (same data) does map the towers at very high zoom (~z18+) 

They don’t show it not because they don’t have the data, they don’t show it because it is a distraction for a majority of users. 

This is the frustration that something so minor compared to the road or train system is given such contrast and prominence. It is a detriment that needs to be rectified. 

Please go look at the Takasaki example I linked to in my initial post. There are more power lines than train lines - and there is a Shinkansen station & line in there somewhere! The only one in my province. I think the amount of people, daily, that use an online map to locate Takasaki station probably outweigh the number of people (in my prefecture)  who look at any map whatsoever to orient themselves to a power line in a year. or two. or 10. It just isn’t that useful to be that prominent. 

Basically - it is just too strong a render for a interesting, but only mildly useful mapped object. The power towers, for all intents and purposes, are big trees. You don’t drive on them, you don’t go to them, and they don’t block your way as you drive. On a (somewhat) political map, they are just decoration, or in some areas, a landmark. 
> Now about the confusion, yes I agree it can look like other things, trams, walls, etc.
> 
it looks like train lines or ski lift lines - especially with all the squares - or a barrier or boundary. The only solid black lines in -carto I can think of are dams and walls (and bridge casings).

>  Maybe would could actually make these electricity lines more visible (I know emergency/danger of death is popular things to be rendered) instead of or as well as lightening up.
> Maybe with a electric lighting bolt zap symbol, or something
> ⚡ 
> or
> https://www.google.co.uk/search?q=electricity+lightning+bolt+logo&source=lnms&tbm=isch&sa=X <https://www.google.co.uk/search?q=electricity+lightning+bolt+logo&source=lnms&tbm=isch&sa=X>
> or
> https://www.google.co.uk/search?q=electricity+symbol&biw=1366&bih=606&source=lnms&tbm=isch&sa=X <https://www.google.co.uk/search?q=electricity+symbol&biw=1366&bih=606&source=lnms&tbm=isch&sa=X>
> That would actually make more sense on the rendering maybe spaced out over the power line like the arrows are on the one way roads.
> I presume that zap is fairly understandable globally for electricity?
> 
> 

a small bolt is a good idea.  Having it inserted into the line (and the same color as the line) with no shield  and a transparent stroke (so the line is 1-2px away from the bolt) would be a nice indicator that is an an electrical item. The towers can be lightened even further, as once your eye is on the line, it is easy to pick out any deviations. I put colour= tags on the towers that are red and white. perhaps a z18 it can render the building (or the outline) with red/white stripes if the tag exists, because, yea, a 15 story tall red/white striped object is a landmark. After checking a previously tower I mapped, I apparently I am tagging the tower area and with the power line node junction incorrectly, as it has changed (and looks awkward now ) since I tagged it a few months ago. 
http://www.openstreetmap.org/edit#map=18/36.40996/139.25080 <http://www.openstreetmap.org/edit#map=18/36.40996/139.25080>

(That might bring up a whole can of worms on the mailing lists because is red and white colour=red;white , =red_white , etc , etc.   ><) 

~~~

My frustrations are cause by incomplete tagging systems and rigid rendering. making it more flexible/open in what it renders  through a more flexible tagging system ( somehow, since I’m not a coder), will not just benefit me, but other users in other situations and places, and result in a more useful map for locals - even if that results in possible “mapping for the renderer” or vandalism -  but it will make a truly more useful map. 

Which is the goal we are all working towards, right? Otherwise why would I bother submitting issues? 


Javbw.



> —
> Reply to this email directly or view it on GitHub <https://github.com/gravitystorm/openstreetmap-carto/issues/1260#issuecomment-71576893>.
>

**Comment by SomeoneElseOSM** [comment]
@javbw Just checking in case you're not aware, but there are 5 different styles available by default on osm.org. You've logged this issue against the only one that displays power lines at the scales your examples use, which seems ... odd.

If someone was wanting to clearly see rail lines over everything else, wouldn't the Transport Map (https://www.openstreetmap.org/#map=14/36.3835/139.0857&layers=T) be more useful?  Other renderings are also available (e.g. http://www.openrailwaymap.org/).

**Comment by javbw** [comment]
@ someoneelseOSM - thanks for the suggestion - and if i was concerned just for the train lines, or interested in mapping just the trains - then it would be the best layer to use. Maybe if I lived in Tokyo, and I needed to mainly move by train, that would be the appropriate map. 

However, moving around here is in Japan is really weird compared to the US. Everything is relative.  There are no human parsable street addresses for any building, so everything is referenced to other  labeled points on the map. 
And I know that this sounds like I'm being picky or myopic, because relative directions are common everywhere, but the extent and dependence on relative directions is amazing. Everything is used for relative directions in printed materials and access maps on web sites, starting with stations, named or number of street lights, Large buildings, government buildings, and shops reference other (more famous) shops on their access maps.

Therefore, the most common render of OSM - the default layer -  includes all the pieces for proper relative navigation - train stations, street lights, buildings, parks, and all the other objects that are used for relative direction giving when not using a GPS/Navi here in Japan. Plus, outside of Tokyo, rural Japan has higher ownership of cars per capita than even southern California - so driving is also popular, but it uses the train stations and the like for major relative navigation references in supplied driving directions. 

So I'm very interested in making the default the most useful and polished version of -carto.

**Comment by matkoniecz** [comment]
> http://www.openstreetmap.org/#map=14/36.3835/139.1072 (zoomed in a bit)
> Wow - the private train lines now run north-south! how useful! 

Is it still a problem? Rail rendering was changed by #1736 and other PRs during road redesign, what make main railways more prominent.

Current rendering is 

![selection_001](https://cloud.githubusercontent.com/assets/899988/15942409/876416cc-2e84-11e6-9551-4b83f340e4b9.png)

unfortunately there are no captured images in the report.

**Comment by SomeoneElseOSM** [comment]
@matkoniecz  It wasn't very clear in the original report, but I believe the "rail lines" comment was supposed to be sarcasm.  I don't think that power line rendering has changed much and at z14 above they're arguably too prominent (though as I said in the comment above, other renderings are also available).

In https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/commits/ca2a7be2b5fe776ad04cc49c444d3f688ba8725a/power.mss I did reduce the prominence of power lines in an osm-carto fork, and I think the change was beneficial.

**Comment by matkoniecz** [comment]
Thanks! It is always nice to merge/copy code.

I am bit surprised that power lines in your fork were so strongly reduced without change to power towers/poles. Is my reading of code correct? I see no changes to symbols https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blame/ca2a7be2b5fe776ad04cc49c444d3f688ba8725a/power.mss or in symbols files.

**Comment by SomeoneElseOSM** [comment]
Re power towers/poles - that was deliberate, since I didn't think those were actually overprominent.  See for example:

![5334](https://cloud.githubusercontent.com/assets/5311740/15944363/24421e08-2e85-11e6-8d87-1b4783926374.png) and compare with ![osm-carto](http://c.tile.openstreetmap.org/14/8117/5334.png)

**Comment by matkoniecz** [comment]
Thanks! It looks interesting and may be more intuitive - after all in pyloned power lines cables are not so prominent...

But I wonder how it will work in area with more features (landuse etc), probably I will propose change in between fork and current code.

**Comment by math1985** [comment]
I also like the rendering of @SomeoneElseOSM .

**Comment by kocio-pl** [comment]
How would it look like on the residential area?

**Comment by SomeoneElseOSM** [comment]
Not particularly visible:
![5346](https://cloud.githubusercontent.com/assets/5311740/15945992/b9078a4e-2e8c-11e6-810b-4b9c3cadcf1e.png) (which is http://c.tile.openstreetmap.org/14/8123/5346.png ).

**Comment by kocio-pl** [comment]
Thanks! I thought that it may be like this, but power lines are more important navigational aid outside the residential areas, which can be overcrowded with details, so it may be still good solution for a general map.

Could you also show some rendering with bigger zoom to see how does it look on a plain grey area?
