### ISSUE TITLE
update screenshot

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#1261]
Our screenshot in the README is outdated - we've changed a bunch of colours recently, most noticeably the buildings. The replacement should cover the same area + zoom

**Comment by althio** [comment]
I don't know how to put the file in `https://raw.github.com/gravitystorm/openstreetmap-carto/master/preview.png`

If that helps here are the files:

before
![image](https://cloud.githubusercontent.com/assets/9863567/5922366/42e26304-a64b-11e4-9d47-fa37f46e96c8.png)

after
![preview](https://cloud.githubusercontent.com/assets/9863567/5922371/510b6408-a64b-11e4-8868-0cd96b212eef.png)

**Comment by pnorman** [comment]
I think you've got a different zoom on the one after - shield sizes have changed in your screenshot, but not in the stylesheet.

**Comment by math1985** [comment]
> I don't know how to put the file in https://raw.github.com/gravitystorm/openstreetmap-carto/master/preview.png

Best to create a pull request, this should explain how:
https://help.github.com/articles/fork-a-repo/
https://help.github.com/articles/using-pull-requests/

Let us know if anything is unclear.

**Comment by althio** [comment]
@pnorman
> I think you've got a different zoom on the one after

I will double check but zoom levels immediately above and under looked significantly different.

@math1985
> Let us know if anything is unclear.

What was unclear for me is how to access the folder and put a file in raw.github.com/gravitystorm/openstreetmap-carto/master
But master is the branch, not a folder and I guess 'raw' is not relevant.
I think I found the current file now.

**Comment by althio** [comment]
@pnorman
>> I think you've got a different zoom on the one after

> I will double check but zoom levels immediately above and under looked significantly different.

I was on the correct zoom (z15) but I used Share/Image/Download and it does look slighly different than direct screenshot. I am not sure if there is a difference in "quality" or sharpness also.

z14 - direct screenshot
![preview-chicago-z14](https://cloud.githubusercontent.com/assets/9863567/5935768/ceb52be4-a6de-11e4-8079-6a54cd54dc25.png)

z15 - direct screenshot
![preview-chicago-z15](https://cloud.githubusercontent.com/assets/9863567/5935771/d4a8d01e-a6de-11e4-9c76-3ab0c36580a4.png)
z15 - Share/Image/Download
![preview](https://cloud.githubusercontent.com/assets/9863567/5922371/510b6408-a64b-11e4-8868-0cd96b212eef.png)
current file in repo
![image](https://cloud.githubusercontent.com/assets/9863567/5922366/42e26304-a64b-11e4-9d47-fa37f46e96c8.png)

z16 - direct screenshot
![preview-chicago-z16](https://cloud.githubusercontent.com/assets/9863567/5935775/da4af83a-a6de-11e4-8d10-285fbd594cc7.png)

**Comment by pnorman** [comment]
share image/download generates a new image, and has nothing to do with the zoom on the website you were viewing at. A screenshot is always best for this kind of example

**Comment by althio** [comment]
Approximative area:
http://www.openstreetmap.org/#map=15/41.8729/-87.6323
+ zoom 15
+ direct screenshot, no share/download
+ crop, no resize
+ size px 852*300
+ file named preview.png
![preview](https://cloud.githubusercontent.com/assets/9863567/5965132/f26ed852-a7f9-11e4-9ea6-eb6d1125ac9b.png)
I will create a new PR when I have access to a computer with git installed. Otherwise feel free to take the file and create own PR.

**Comment by sommerluk** [comment]
@math1985 This issue can be closed with merge of #1279

**Comment by math1985** [comment]
Indeed. By the way, if you include the text 'resolves #1261' in your PR description, the issue gets closed automatically when the PR is merged.

**Comment by nebulon42** [comment]
Was this screenshot taken from TileMill? Otherwise there is #1208, which changes the building colour again slightly.

**Comment by althio** [comment]
@nebulon42
> Was this screenshot taken from TileMill?

No. It was a screenshot from plain map on public website.

**Comment by nebulon42** [comment]
Ok, so I guess we need to update the preview once again after the next release.
