### ISSUE TITLE
aeroway=runway too wide at z=14

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1263]
If a runway is tagged on a line, the width of it changes a lot from z=14 to z=15.
It looks OK on big airports with very long runways, but all the small airfields look quite strange.
Examples: 
http://www.openstreetmap.org/#map=14/48.0329/9.5092
http://www.openstreetmap.org/#map=14/48.4347/10.9223
http://www.openstreetmap.org/#map=14/48.3508/11.7726

I believe this is the line in roads.mss:
https://github.com/gravitystorm/openstreetmap-carto/blob/bc2eb949f28992a354b5ff04226780226b0f79df/roads.mss#L1560

The width goes 2 -> 4 -> 7 ->18 for z>=14
So 18 at z14 is much wider than 18 at z15??

**Comment by mrwojo** [comment]
The width should be 14 at z14 to maintain the relative scale.

A bad example of parallel runways overlapping at z14: http://www.openstreetmap.org/?mlat=47.5378&mlon=-122.3080#map=14/47.5378/-122.3080

**Comment by dieterdreist** [comment]
2015-01-28 1:03 GMT+01:00 daganzdaanda <notifications@github.com>:

> If a runway is tagged on a line, the width of it changes a lot from z=14
> to z=15.
> It looks OK on big airports with very long runways, but all the small
> airfields look quite strange.
>

many runways are mapped as areas which will always display in the right
dimensions. Some mappers question this way of mapping because they say that
finding the direction is easier with linear ways.

**Comment by mkoniecz** [comment]
Should be fixed by #1270
