### ISSUE TITLE
"standard layer" map key contains misleading entries

### ISSUE THREAD

**Issue by SomeoneElseOSM** [gravitystorm/openstreetmap-carto#1268]
I created https://github.com/openstreetmap/openstreetmap-website/issues/882 over at "openstreetmap-website" .  Per TomH's comment it does make sense for it to be fixed "from this end" (i.e. when a new openstreetmap-carto release is made an update is made to the map key that can be sent live at the same time as the new map style).

Currently https://github.com/openstreetmap/openstreetmap-website/blob/068471fc0e797428c48b8917d62fe7db0331cc65/config/key.yml does seem to contain incorrect entries for both "unsurfaced" and "byway" - and I suspect there will be a number of other differences too.

The original question about this was in the US forum at http://forum.openstreetmap.org/viewtopic.php?pid=481542#p481542 .

**Comment by math1985** [comment]
I know @gravitystorm is already working on this.

**Comment by gravitystorm** [comment]
Thanks @SomeoneElseOSM - it's been something I've been working on but we should have an issue to track it too.

**Comment by math1985** [comment]
I think the destination and private access dashes should also be included in the legend.

**Comment by SomeoneElseOSM** [comment]
(for the benefit of anyone stumbling across this issue) note that there's now a wiki page that covers many/most of the current style: 

http://wiki.openstreetmap.org/wiki/Standard_tile_layer

**Comment by matkoniecz** [comment]
@tomhughes (reply to https://github.com/openstreetmap/openstreetmap-website/issues/882#issuecomment-72201717)

> I just whatever the cartographers give me there

What is the preferred format for providing updated version? Making PR updating https://github.com/openstreetmap/openstreetmap-website/blob/835eff634651a98602897a1fbdaa4a6426beedb1/config/key.yml and these images seems to be a poor idea.

Maybe including in openstreetmap-carto key.yml file + script to generate images would be a good idea?

**Comment by matkoniecz** [comment]
Thanks to https://github.com/openstreetmap/openstreetmap-website/pull/1004/files I found these files in https://github.com/openstreetmap/openstreetmap-website/tree/master/app/assets/images/key/mapnik

**Comment by matkoniecz** [comment]
And now the most misleading entries are removed.

**Comment by matkoniecz** [comment]
There is  #1928 for Create legend, https://github.com/openstreetmap/openstreetmap-website/pull/1017 and https://github.com/openstreetmap/openstreetmap-website/pull/1070 fixed issue of completely misleading entries

**Comment by vincentdephily** [comment]
Still some misleading entries: http://www.openstreetmap.org/note/637566
