### ISSUE TITLE
alpine_hut should have precedence over restaurant

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1269]
Sometimes alpine huts are both tagged `tourism=alpine_hut` and `amenity=restaurant`, which is not wrong IMO. In those cases restaurant seems to have precedence over alpine_hut, which causes the icon to appear at z17 instead of z13. This is undesirable as huts are important POIs for hikers.

Examples: http://www.openstreetmap.org/way/176377262 or http://www.openstreetmap.org/node/3007429464

**Comment by nebulon42** [comment]
I have already tried to move alpine_hut after restaurant, but it didn't have any effect. How is it possible to control what rule takes precedence over the other if there is more than one match?

**Comment by math1985** [comment]
It's basically the order of the arguments of COALESCE in project.yaml.

This is not an optimal situation, and any (suggestion for a) rewrite of the code to make this more easy to control is more than welcome.

**Comment by nebulon42** [comment]
I see, thanks for clarification. From PostgreSQL documentation:

> The COALESCE function returns the first of its arguments that is not null.

**Comment by Rovastar** [comment]
Not sure I understand why alpine huts are restaurants.  Table service.?

**Comment by polarbearing** [comment]
Don't confuse an alpine hut with a shelter. As I understand, a hut is operated by a host, for whom serving meals is a significant part of her income, whether served at the table or picked at a counter. 

This is another case that the accommodation function is seen as more important that other use, see #1232.
