### ISSUE TITLE
Render barrier=toll_booth

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#1276]
Would it be possible to render barrier=toll_booth? The tag applies to nodes and areas and could simply be rendered with an icon – maybe something like a simplified version of http://wiki.openstreetmap.org/wiki/File:Zeichen_391_-_Mautpflichtige_Strecke,_StVO_2003.svg

That’s something that probably has less side effects than changing the rendering for roads with toll=* (#593). Nevertheless it can be usefull.

**Comment by math1985** [comment]
Duplicate with #958.

**Comment by sommerluk** [comment]
Sorry, I missed #958
