### ISSUE TITLE
admin level 10 boundaries are rendered on top of other admin levels

### ISSUE THREAD

**Issue by sb12** [gravitystorm/openstreetmap-carto#1277]
Rendering of admin level 10 boundary with lower admin levels leads to artefacts:
![screenshot from 2015-01-31 17 37 49](https://cloud.githubusercontent.com/assets/5783139/5988812/321f1f44-a970-11e4-8ce5-2417a8edadf3.png)

http://www.openstreetmap.org/#map=18/49.46213/8.45261

My guess: The ordering introduced in #1107 sorts the 10 between the 1 and the 2 which leads to admin level 10 being drawn over the other admin levels.

**Comment by math1985** [comment]
> My guess: The ordering introduced in #1107 sorts the 10 between the 1 and the 2 which leads to admin level 10 being drawn over the other admin levels.

Good guess, I would have never thought of that but I think you're right.

**Comment by sb12** [comment]
No idea when, but I think this has been fixed (see https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml#L1367).
