### ISSUE TITLE
tunnel= and cover= do not render on highway area

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#1278]
highway=footway + covered=yes and/or tunnel tag are rendered:
http://www.openstreetmap.org/way/177142916

However this tunneled footway:
http://www.openstreetmap.org/way/172093544
and this covered footway:
http://www.openstreetmap.org/way/232454585

are blocked by the pedestrian area.

#688 discusses buildings not rendered on highways, for which this roof is another example: 
https://www.openstreetmap.org/way/312103060 however it is not the roof preventing the footways to render, as can be seen at where the edge of the roof is wider than the pedestrian area.

Another example:
http://www.openstreetmap.org/#map=18/52.52179/13.41374
Some underground footway fragments that are visible, they tagged indoor=yes. Those with tunnel=yes do not render. 

Probably it is useful that a linear highway paints over a tunnel, however with a highway area this seems to be different.

**Comment by HolgerJeromin** [comment]
Another example 

http://www.openstreetmap.org/way/27578466#map=18/50.78067/6.07594

**Comment by daganzdaanda** [comment]
Another example: 
http://www.openstreetmap.org/note/new#map=19/52.52363/13.36882
The tunneled trunk highways (http://www.openstreetmap.org/way/48859719#map=19/52.52376/13.36934) are hidden by a pedestrian area, but the names and the label are shown.

**Comment by math1985** [comment]
Duplicate with #529.
