### ISSUE TITLE
Render support for highway=residential_link

### ISSUE THREAD

**Issue by aaronstar** [gravitystorm/openstreetmap-carto#1280]
As above I suggest rendering support for highway=residential_link, highway=service_link, which is currently supported by various routing software and a natural extension of support for Link Roads.

**Comment by mkoniecz** [comment]
http://taginfo.openstreetmap.org/tags/highway=residential_link - 57 instances worldwide
http://taginfo.openstreetmap.org//search?q=highway%3Dservice_link - 0 instances worldwide

Undocumented on wiki, very likely to be controversial.

It should be (a) documented (b) used to even consider rendering it.

**Comment by mboeringa** [comment]
I also wonder what the "various routing software" are that support a hardly used tag... I guess you may be the developer of the one solution that now does, but it might be helpful to state it as such, and explain your reasons.

I also don't understand the concept of a **residential_link** or **service_link**. In most cases, if anything, I can only think of ***lanes***, but these aren't the typical "links" of a motorway junction...

**Comment by aaronstar** [comment]
I am unsure if this can be reopened (quick decision) regardless,

Here is an example canidate of a road where highway=residential_link should be used.
https://www.openstreetmap.org/edit#map=19/-31.91795/115.86190

The intersecting road is two way with a turning segment bypass.

Link Roads may be mistaken for being motorway links. This has resulted in inconsistent usage. Link Roads are Slip Roads. Slip Roads include indeterminate and terminal ramps (I.e a T junction in cases) ingress and egress ramps and turning segments and intersection bypass segments (excluding those which turn unto themselves) I.e. U turns within the median.

Skobbler and Scout have native support for highway=residential_link and highway=service_link,
others including OsmAnd and OSRM support wildcards of highway values to accomodate link roads (Wherein they don't support highway=primary_link or the like at present as standalone values but rather they support link roads.).

**Comment by pnorman** [comment]
I thought we did render residential_link roads, did this maybe change since the XML?

> Undocumented on wiki

This is not particularly relevant - none of the links except for motorway_link have their own page

**Comment by pnorman** [comment]
Re-opening, residential_link is supported by MQ Open and Humanitarian so we shouldn't dismiss it out of hand.

**Comment by mkoniecz** [comment]
> This is not particularly relevant - none of the links except for motorway_link have their own page

Neither http://wiki.openstreetmap.org/wiki/Key:highway nor http://wiki.openstreetmap.org/wiki/Highway_link is even mentioning highway=residential_link.

**Comment by gravitystorm** [comment]
We render _link roads as far down as tertiary, and that's been a common convention for a long time. I think most other styles will follow the same pattern. Editors (e.g. iD) only go as far as tertiary_link too. T

I'd suggest in fact that it's a bug in both MQ Open and the Humanitarian styles that they are rendering unrecognised highway types - these mistagged roads would get fixed faster if they didn't show up anywhere.

**Comment by jeisenbe** [comment]
Update, December 2018:
http://taginfo.openstreetmap.org/tags/highway=unclassified_link - 5 instances worldwide
http://taginfo.openstreetmap.org/tags/highway=residential_link - 6 instances worldwide
http://taginfo.openstreetmap.org/tags/highway=service_link - 0 instances worldwide
http://taginfo.openstreetmap.org/tags/highway=road_link - 0 instances worldwide
