### ISSUE TITLE
Please render amenity=public_bookcase

### ISSUE THREAD

**Issue by DigitaleAllmende** [gravitystorm/openstreetmap-carto#1288]
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_bookcase

It would be nice to have a special icon for public bookcases, maybe a hand combined with a book to symbolize book sharing.

**Comment by pnorman** [comment]
With 29 usages, it hasn't gained enough traction among mappers to add yet another icon to the style for it.

**Comment by HolgerJeromin** [comment]
many are tagged as library or other tags.
http://de.wikipedia.org/wiki/Liste_öffentlicher_Bücherschränke
has a nice collection in several countries. So the resources are available to push the right tagging.

**Comment by DigitaleAllmende** [comment]
@HolgerJeromin "many are tagged as library or other tags" 
yes, and there are many to be tagged: http://openbookcase.org/ 

that's why I would like to have a special icon for them

**Comment by gravitystorm** [comment]
Even if they were widely tagged, we need to draw a line as to how many different features we render on a general-purpose style. Public_bookcases are great, but would be shown as a specialist rendering.

**Comment by Adamant36** [comment]
@kocio-pl, any chance of reopening this now that there are 3,074 uses of it? Id really like to see them rendered and I think @Tomasz-W could come up with a good icon for them.

**Comment by Tomasz-W** [comment]
Icon proposal:

![amenity public_bookcase](https://user-images.githubusercontent.com/25656654/45743365-231c2580-bbfc-11e8-960e-60d91c42144a.png)

**Comment by kocio-pl** [comment]
Well, I'm not sure where I took the indoor possibility, but OSM wiki defines it as "a type of street furniture containing books", which means strictly outdoor object. I would render it on z19+, given its size, and I like this icon proposition. @Tomasz-W could you publish the vector code?

**Comment by Adamant36** [comment]
I'll do the PR for it. I've been wanting them to show up in my area for a while now.
