### ISSUE TITLE
integer out of range

### ISSUE THREAD

**Issue by StyXman** [gravitystorm/openstreetmap-carto#1289]
Whlie trying to render zoom level 0 using v2.27.0, I get this error:

```RuntimeError: ERROR:  integer out of range```

On Postgres' logs I can see the failing query:

```sql
SELECT ST_AsBinary("way") AS geom,"feature" FROM (SELECT
    way, name, way_pixels,
    COALESCE(landuse, "natural") AS feature
  FROM (SELECT
      way, COALESCE(name, '') AS name,
      ('landuse_' || (CASE WHEN landuse IN ('forest') THEN landuse ELSE NULL END)) AS landuse,
      ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock') THEN "natural" ELSE NULL END)) AS "natural",
      way_area/(156543*156543) AS way_pixels
    FROM planet_osm_polygon
    WHERE (landuse IN ('forest')
      OR "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock'))
      AND way_area/(156543*156543) > 0.01
      AND building IS NULL
    ORDER BY z_order, way_area DESC
  ) AS features
) AS landcover_low_zoom WHERE "way" && ST_SetSRID('BOX3D(-20037508 -20037508,20037508 20037508)'::box3d, 900913)
```

The problem being that `156543*156543` (24505710849, ~23Gi) is too big for a PG integer. I'm still using PG 9.3, but I don  know if this is part of the problem.

**Comment by math1985** [comment]
I cannot reproduce this in psql 9.3. @pnorman?

**Comment by gravitystorm** [comment]
I get the error on both 9.1 and 9.3

```
psql (9.3.5)
Type "help" for help.

gis=# select 156543 * 156543;
ERROR:  integer out of range
gis=# 
```

```
psql (9.1.14)
Type "help" for help.

gis=# select 156543 * 156543;
ERROR:  integer out of range
```

**Comment by imagico** [comment]
The strange thing to me seems why this query is even evaluated at z=0 - to my (possibly naive) understanding mapnik should only invoke queries if the style actually renders something at the zoom level in question.  And nothing in landcover-low-zoom is currently rendered at z<8.

**Comment by math1985** [comment]
> `way_area/NULLIF(!pixel_width!::real*!pixel_height!::real)`

Small typo, it should be:

`way_area/NULLIF(!pixel_width!::real*!pixel_height!::real,0)`
