### ISSUE TITLE
Missing low-zoom land

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1294]
![image](https://cloud.githubusercontent.com/assets/1190866/6087656/2a02587a-ae03-11e4-8840-dc4838a3422d.png)
zoom 3 off of orm.openstreetmap.org, also impacting other low zooms, presumably anything fresh.

It might be an issue with the shapefiles on the server, or something in the recent update which was https://github.com/gravitystorm/openstreetmap-carto/compare/v2.27.0...v2.28.0

cc @tomhughes

**Comment by simonpoole** [comment]
Maybe related maybe not, but maritime boundaries are no longer rendered at zoom 10 and lower.

**Comment by pnorman** [comment]
some roads are missing
![image](https://cloud.githubusercontent.com/assets/1190866/6087878/8bd5fb54-ae05-11e4-894d-df02ee8a1765.png)

I asked for a roll back to v2.27.0

**Comment by simonpoole** [comment]
@pnorman the missing roads seem to manifest itself at zoom 10 and lower too, so likely related

**Comment by mkoniecz** [comment]
It appears to affect z9 and lower zoom levels. Roads are gone on z10.

**Comment by pnorman** [comment]
styles have been rolled back to v2.27.0, and re-rendering will take place over the next few hours.

We still need to figure out the cause, and why it's hitting tile.osm.org but not local tilemill testing.

**Comment by tomhughes** [comment]
The rollout had probably only got down to z9 which is why you only saw it below that - we update the style sheet and then render 0-12 with render_old before telling mod_tile about the change so that it starts doing high zoom tiles. As the update was rolled back before the low zoom render had finished that is where it will mainly have been visible.

**Comment by pierzen** [comment]
I see the flooed area presently east of Canada at zoom 8.
http://www.openstreetmap.org/#map=8/49.645/-60.617

Somme feedback could be provided to users adding a banner on openstreetmap.org explaining this temporary problem.

**Comment by math1985** [comment]
I can't reproduce the bug locally even using the command line (render_list).

**Comment by pnorman** [comment]
What mapnik version?

**Comment by math1985** [comment]
Seems like 2.2.0.

**Comment by pnorman** [comment]
tile.osm.org render servers are running 2.2.0 also. Perhaps a `carto` issue?

**Comment by math1985** [comment]
@jburgess has seen the Carto XML ouput, if he still has the file we could check if it's a Carto problem by comparing it with a locally generated XML file.

**Comment by pnorman** [comment]
> @jburgess has seen the Carto XML ouput, if he still has the file we could check if it's a Carto problem by comparing it with a locally generated XML file.

I'm not confident that we'd get the same Mapnik XML generated internally in TileMill as we would on the command line, but worth a shot.

**Comment by math1985** [comment]
See matthijsmelissen.nl/temp/osm.xml for the osm.xml as obtained by 
```
/opt/tilemill/node_modules/carto/bin/carto  ~/osm/project.mml
```
This is carto 0.9.6.

This version of the osm.xml does not contain the bug.

**Comment by tomhughes** [comment]
I just generated project.xml on orm and put it up at http://download.compton.nu/tmp/project.xml (carto 0.9.4).

**Comment by math1985** [comment]
Quite different:

-<Layer name="world"
-  maxzoom="9"
-  srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
+<Layer name="world" minzoom="750000" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">


Didn't @jburgess


https://github.com/mapbox/carto/commit/7deb1b86e060efee5ec358712683ec505542efa0

**Comment by math1985** [comment]
Quite different:
```
-<Layer name="world"
-  maxzoom="9"
-  srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
+<Layer name="world" minzoom="750000" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
```

I think our code requires this commit to carto: 
https://github.com/mapbox/carto/commit/7deb1b86e060efee5ec358712683ec505542efa0

So it seems the carto version need to be at least v0.9.5.

**Comment by tomhughes** [comment]
I've upgraded carto to 0.14.1 now and http://download.compton.nu/tmp/project2.xml is what I'm getting, but that seems to have crazy large minzoom/maxzoom values in it?

**Comment by poempelfox** [comment]
Those large values should be correct, as that is the same kind of values MaxScaleDenominator/MinScaleDenominator use in the mapnik XML.

**Comment by math1985** [comment]
> I've upgraded carto to 0.14.1 now and http://download.compton.nu/tmp/project2.xml is what I'm getting, but that seems to have crazy large minzoom/maxzoom values in it?

Minzoom/maxzoom values are fine. There are some differences between the 0.9.6 and 0.14.1 XML output, at least concerning the order of the rules, so the stylesheet would need some rigid testing on 0.14.1 before it can be rolled out to the server.

**Comment by tomhughes** [comment]
It was rolled out already...

**Comment by pnorman** [comment]
`node-carto` on ubuntu is 0.9.5.

My guess is the change that handles min/max zoom was part of the mapnik-reference changes in 0.96.0 (mapbox/carto@c6f787f761a6c3714ef9639accbc279889e88f85) but I'll check on 0.95.0

If it is 0.96.0, then I guess the question is, do we want to bump up the required version to past what Ubuntu 14.04 has?

**Comment by Vort** [comment]
z0 tile is still bugged
(filled with water)
or this is another issue?
http://a.tile.openstreetmap.org/0/0/0.png

**Comment by tomhughes** [comment]
@pnorman as far as I know Ubuntu doesn't have any particular version - carto isn't packaged is it?

**Comment by tomhughes** [comment]
Oh it is on 14.04 but we're on 12.04 still. It's 0.9.5 as you say, which should (just) be enough.

**Comment by poempelfox** [comment]
@Vort: status claims "Last rendered at Fri Feb 06 19:16:35 2015." - it simply hasn't been rerendered (yet).
@tomhughes: Ubuntu 14.04 does ship Carto "Version: 0.9.5-2" in "universe" (package "node-carto") and I can confirm that this version does generate the XML properly.
