### ISSUE TITLE
intermittent rivers at low zooms

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#1305]
The recent addition of special rendering of intermittent rivers (#1000) only uses the dashed rendering at z>=12, from 8 to 11 intermittent rivers are rendered like normal rivers as solid lines.  Not sure if this is intentional but it does not seem like a good idea.  An intermittent river is sort of a partial river, both in meaning and the way it is rendered as a dashed line.  First showing the river in full (at z>=8) and then showing it only partially (at z>=12) is irritating.

If the dashed rendering is considered unsuitable for the lower zooms i would suggest a lighter or semitransparent color.

**Comment by mkoniecz** [comment]
Is there some location where it would be relevant? I remember considering adding dashed line also for low zoom levels but I failed to find any locations where it would improve situation (I am not remembering exactly what was problem). Also, with dashes it would have the same problems as with borders (straight lines vs complicated shapes resulting in unexpected rendering of dashes),

**Comment by imagico** [comment]
No particular area where this is a special problem but i find it generally very irritating.  For example around here:

http://www.openstreetmap.org/#map=9/-22.0627/15.1611

and here:

http://www.openstreetmap.org/#map=9/-21.8029/141.3776

Overall i don't thing the lack of generalization would be a problem for dashed rendering of waterways at z>=10, in some cases it might be at z=8/9.

**Comment by imagico** [comment]
Better examples:

http://www.openstreetmap.org/#map=10/-24.3734/45.1772
http://www.openstreetmap.org/#map=11/30.1422/-7.9122

**Comment by math1985** [comment]
I agree rendering dashes earlier (or not rendering intermittent rivers at all on low zoom) would be an improvement.

**Comment by matkoniecz** [comment]
@imagico #1376 implements not rendering intermittent rivers on low zoom levels. Is it something that would work for such locations?

**Comment by imagico** [comment]
It would resolve the inconsistency but IMO it would not be a very good solution - see my comment on #1376 .

**Comment by sommerluk** [comment]
I’ve played a little bit with the dashed line, using the same code on low zoom levels like on high zoom levels. At z8 your example from Madagaskar looks like this (only intermittent rivers, no other objects in the database):

![screen](https://cloud.githubusercontent.com/assets/6830724/6655202/9272d880-caeb-11e4-8319-e1de8158868b.png)

The higher the zoom level, the better the representation of course …

**Comment by imagico** [comment]
Note that's only the *intermittent* rivers without the permanent ones.  But i agree this does not look ideal - a thinner solid line might be an option for z=8/9.

I don't think the dashed drawing will cause any serious troubles for z=10/11 though.

**Comment by matkoniecz** [comment]
Maybe dashes for 10/11 and no rendering for 8/9? Two different styles for intermittent rivers will be confusing.

**Comment by imagico** [comment]
As said i don't think starting to display intermittent rivers later than normal ones is a good idea since intermittency is not an indicator for importance.

It does not seem to me that styling differences between zoom levels are an issue - all water things are in the same color including areas (i.e. riverbank polygons) so there is a huge variety of structures in that color anyway.

This matter is of course strongly related to the question how intermittent water areas are going to be displayed at lower zoom levels.  The best option here would probably be a paler color - in that case it would make sense to me to use the same styling for the river lines since at z=8/9 water rendering essentially does not differenciate clearly between line and area features - except for the highest latitudes.

**Comment by sommerluk** [comment]
What about an intermediate solution? Rendering non-intermittent rivers from z=8 and intermittent rivers from z=10?

**Comment by imagico** [comment]
IMO the dashed rendering or a smaller line width would be a better intermediate solution than not rendering at all.

**Comment by sommerluk** [comment]
I would prefer the dashed line.

Having a continious line — even if this line is smaller — seems confusing to me when it changes to be dashed at z=13.

The screenshot looks also quite “busy” just only with the intermittent rivers. I like the idea of @matkoniecz to start rendering of intermittent rivers at z10 with a dashed line. Maybe lower zoom levels are also okay, but I would try to avoid 2 different rendering for intermittent rivers and therefor opt for dashed lines.

**Comment by math1985** [comment]
I would prefer dashed rendering on low zoom 8-12. Perhaps increase the dash length a bit.

**Comment by sommerluk** [comment]
> I would prefer dashed rendering on low zoom 8-12. Perhaps increase the dash length a bit.

Proposed in PR #1399
