### ISSUE TITLE
highway=steps are too prominent

### ISSUE THREAD

**Issue by bubalici** [gravitystorm/openstreetmap-carto#1307]
I suggest a change for the bright red color that the highway=steps has at the moment. Ever since the building color was changed, the steps look to strident, especially in areas where there are lots of such roads (example: https://www.openstreetmap.org/#map=18/37.44711/24.94306 ).
This kind of red is more fitted for restrictions (e.g. access=no tags) or important roads.
At z15 they look even more strange.

As to what color should they have... don't know, perhaps something near the color of pedestrian roads.

**Comment by HolgerJeromin** [comment]
i think step is logical linked to footway. changing both would be a major change. Making footway and pedestrian similar seems good, but footway has to be visible on forest and other landuses.

**Comment by matkoniecz** [comment]
Change of colour is a poor idea, but it is possible to reduce visibility of highway=steps (just a bit, this feature should be still noticeable).
