### ISSUE TITLE
translucent style for leisure=park

### ISSUE THREAD

**Issue by cm8** [gravitystorm/openstreetmap-carto#1309]
We had this in the default style, before it was switched to carto.

This was _very_helpful.  In reality a park can be a very large area with lots of different features within.  So, e.g. there may be multiple landuse=forest and landuse=meadow within a leisure=park

With the 'old' openstreetmap style this rendered fine, since the light green for a park was translucent and the features 'beneath' were viewable on the map.

Currently only a single solid color with absolutely no detail is shown.  And I fear that mappers will start to throw out 'leisure=park' data in favor for the micromap'd detail to be shown underneath.  I suggest to restore the behaviour we once had with mapnik default style..

(I think there is a similar/same issue with the zoo style)

**Comment by pnorman** [comment]
The move to not use translucent fills was not related to the switch to carto - it was an intentional change that happened much later.

https://github.com/gravitystorm/openstreetmap-carto/pull/590#issuecomment-44815238 provides some context.

**Comment by cm8** [comment]
Then use dots or whatever instead of filling the whole area.  The decision to hide any detail beneath was not thought through and there are lot's of people (if not most or all) regreting this decision.  I don't say translucency was good for buildings, but it clearly worked for parks.

**Comment by HolgerJeromin** [comment]
cm8: can you give an example?

**Comment by kocio-pl** [comment]
I was also thinking lately how to show that some parts of the park are in fact just a grass, in the other parts there are some trees and probably some flowers sectors here and there (water and pedestrian areas are shown OK, fountain and statues should be visible too, but that's a different case). 

I see the "(leisure) park" as an abstract entity having some boundaries, quite large in size and filled with many different physical objects - just like a "national park", so it could be rendered in a similar way.

**Comment by daganzdaanda** [comment]
IIRC the decision what gets rendered on top is now made by way-size?
The smaller ways do get rendered over the larger ones.
So it depends on what the situation is at your park, @cm8 

But I agree with @kocio-pl this is a bit of a landuse vs landcover issue. A park is a kind of use of some land, and it can contain lots of different things on the ground (landcover). So is landuse=residential.

We can use both the more abstract and the more detailed info in OSM. For most zooms, a simple green area to show the extent of a "park" is perfect. But for the close-ups, it's great to see the details of landcover. If way-size-sorting doesn't work well, maybe for those close-up zooms, drawing an outline and no fill (similar to national parks) would be a good idea.

**Comment by HolgerJeromin** [comment]
In heavy mapped western areas not rendering a green fill
could lead to a more detailed grass and tree landcover mapping.
But on low density areas we should be happy to know it is a park.

**Comment by kocio-pl** [comment]
@HolgerJeromin: As far as I know, we don't plan to distinguish such areas on the map, but I agree with @daganzdaanda that the scale matters and we do use it a lot. 

I think we need to use the highest zoom level (curently z=19) as a platform to test and develop real micromapping features rendering, like street area (https://github.com/gravitystorm/openstreetmap-carto/issues/110#issuecomment-73688071) - parks could be also shown in more detail then, while still being a general green space in z<19.

**Comment by daganzdaanda** [comment]
I found the older issue #1136 that concerns the rendering of parks. There, an example is given: http://www.openstreetmap.org/way/258003222 (meadow partially hidden by a smaller piece of park)

And it links to #888, with another example: http://www.openstreetmap.org/relation/3967553 (park on top of wood)
Also, @math1985 [points out](https://github.com/gravitystorm/openstreetmap-carto/issues/888#issuecomment-52538370) that we can't just decide that parks should render below forests or other landuses, because there could be a small park in a big forest just like the other way around. 
This holds true for all zoom levels. Using way-size to decide what gets rendered on top is a very reasonable choice, which works very well in the majority of cases.

The other options I can think of:
- always render parks below landcovers like forest, meadow,... 
   -> will turn parks like the 2nd example invisible
- always render parks on top of landcovers, but only the outline (like national parks) 
   -> will not look green when there are no additional landcovers mapped
- render parks twice, once as an area below, and once as an outline on top
   -> ???

**Comment by cm8** [comment]
> I see the "(leisure) park" as an abstract entity having some boundaries, quite large in size and filled 
> with many different physical objects - just like a "national park", so it could be rendered in a similar way.

+1
A good example is here: http://www.openstreetmap.org/#map=16/51.2832/12.3851

Note that this issue in principle also exists for larger industrial areas or residential ones.  For most of these it's either that or another, but as pointed out for many years now on talk-de:

landuse and landcover

are two distinct things that both deserve to show up "somehow" on the map.

**Comment by cm8** [comment]
This issue should be reopened.

The discussion shows that there is discomfort with current rendering of leisure=park on all sides - even more so when talking about high zoom levels.

I do not insist on a solution that reintroduces translucency, so the issue may be renamed to sth more expressive.

As long as translucency was used I did not find a single issue with it myself.  If a consensus to not use it has evolved around some specific incompatibility in the past, that's fine.  But then another solution has to be found to accomodate for the features that have been lost by taking this step.  This has been expressed by the previous comments as well.

E.g. it could be tried to achieve a similar translucent effect by using a dithering pattern - opaque dots or squares with fully transparent gaps in between.  I have seen this being used by a couple of other map providers out there.

**Comment by kocio-pl** [comment]
If we want to decide what is on top, we could just use layer=* tag. However it's hard for me to say what should be default (if layers are not set at all, meaning "0", or are the same).

**Comment by dieterdreist** [comment]
2015-02-16 16:12 GMT+01:00 kocio-pl <notifications@github.com>:

> If we want to decide what is on top, we could just use layer=* tag.
> However it's hard for me to say what should be default (if layers are not
> set at all, meaning "0", or are the same).



I'm not sure if I understood you right, but "layer" in OSM is not a tag to
manage the rendering order, it is a tag for the missing z-component (say
which object is above which, on a local level, not globally). In the
rendering it can often make sense to render stuff that is below above (i.e.
after) other stuff and code the stacking order in the signature (e.g.
dashed lines, dotted lines, transparency)

**Comment by kocio-pl** [comment]
That's what I meant. I think rendering should follow that information more closely than it is now.

**Comment by math1985** [comment]
> That's what I meant. I think rendering should follow that information more closely than it is now.

However that's not a solution for the problem in this issue, unless we're talking about floating parks.

**Comment by kocio-pl** [comment]
I agree, you're right.

**Comment by cm8** [comment]
landuse=military made it from the traditional openstreetmap to carto, using both, translucency and a pattern.  It's surprising that this style was not abolished in the same vein as leisure=park was.

http://www.openstreetmap.org/#map=15/51.3790/12.3553

So I really wonder - why can we have it for this feature, but for parks we can't?  ..
