### ISSUE TITLE
Add rendering for wayside_shrine

### ISSUE THREAD

**Issue by al--** [gravitystorm/openstreetmap-carto#131]
Wish: Please render historic=wayside_cross and wayside_shrine, they are landmarks.

wayside_cross could be rendered much like any christian place of worship:
![wayside_cross](https://f.cloud.github.com/assets/1458456/1014622/79128aa2-0bc0-11e3-916a-cb6e2ca4dae3.png)

wayside_shrine symbol could be something like ![wayside_shrine](https://f.cloud.github.com/assets/1458456/1014624/8c8bff28-0bc0-11e3-8961-1438beefe2c7.png)

**Comment by kocio-pl** [comment]
My proposition for shrine (also 9 px as cross made by @matkoniecz):
1) ![shrine-9-11](https://cloud.githubusercontent.com/assets/5439713/8932747/531a7ac6-353f-11e5-8e5f-d68eaea8a45b.png)

**Comment by matkoniecz** [comment]
@kocio-pl 
Shrines need also symbols for other religion values. At least for religion=* missing (over 80% of entries), religion values except 'christian' are quite rare.

**Comment by kocio-pl** [comment]
First has only vertical stick left, the second one is just a box with no stick on top:
2) ![shrine-9-12](https://cloud.githubusercontent.com/assets/5439713/8937027/29d10ac4-3556-11e5-81c9-0dfe702f4b9c.png)
3) ![shrine-9-13](https://cloud.githubusercontent.com/assets/5439713/8937029/2ef7cc54-3556-11e5-8e29-f39b844ce0f6.png)

**Comment by kocio-pl** [comment]
I guess 2 is better as a general shrine (with 1 for christian), so I'll try to make some mockups soon.

**Comment by Penegal** [comment]
If it helps, another possibility for wayside cross, widespread in France : ![wayside cross](https://cloud.githubusercontent.com/assets/13777824/9875618/c1a4e616-5baf-11e5-8ff5-040fbdae2fe1.png)

**Comment by matkoniecz** [comment]
> My proposition for shrine (also 9 px as cross made by @matkoniecz):

https://github.com/gravitystorm/openstreetmap-carto/issues/131#issuecomment-125615202 - can you upload a SVG file (or is it only a png mockup)?

**Comment by kocio-pl** [comment]
@matkoniecz [Here you are](https://github.com/kocio-pl/openstreetmap-carto/blob/icons/symbols/shrine-9.svg).

**Comment by matkoniecz** [comment]
Initial effects are promising, but I will try to tweak icon to make it less heavy. Below is an extreme example, but also single shrines are too prominent.

![selection_001](https://cloud.githubusercontent.com/assets/899988/10068205/bcc813f8-62a2-11e5-8b35-322edc9e8883.png)

**Comment by al--** [comment]
IMO wayside_cross/_shrine (and even chapel) icons should be smaller than a church cross icon.

**Comment by matkoniecz** [comment]
Yes, obviously here shrines are way too prominent. On topic of crosses - it is a good point. Either PoW symbols should have chance to appear earlier or crosses should appear later.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 24.09.2015 um 10:28 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Either PoW symbols should have chance to appear earlier or crosses should appear later.


the churches (and other PoW) could probably appear earlier, but regardless of that I share the point that wayside shrines and crosses should be less prominent in general compared to them. One way would be to reduce the cross size in the icon.

**Comment by al--** [comment]
Here's how the (official) BEV does ist: It's smaller, not only the cross, but especially what's underneath.

![marterl_karte](https://cloud.githubusercontent.com/assets/1458456/10075194/c1f4a74c-62d4-11e5-9c99-c727e9b92a02.png)

A cross with something underneath is typically always more prominent than just a cross.

**Comment by kocio-pl** [comment]
@matkoniecz Those objects are the perfect examples of https://github.com/gravitystorm/openstreetmap-carto/issues/1705 to me: in the outdoor they could be OK, but in the city they are just making noise on this zoom level.

**Comment by kocio-pl** [comment]
Do we think the problem of shrine rendering can be solved or no good enough solution is currently at the table and it's rather to be closed?

**Comment by matkoniecz** [comment]
I think that it can be solved, but recently I had no available time to do anything with it.

**Comment by kocio-pl** [comment]
Any new ideas?

**Comment by HolgerJeromin** [comment]
What about rendering (Christian?) shrines same as crosses?

**Comment by kocio-pl** [comment]
@HolgerJeromin It might make sense, at least [22% of shrines](http://taginfo.openstreetmap.org/tags/historic=wayside_shrine#combinations) would be visible and it may encourage people to add religion=christian for some others. 

@matkoniecz , what do you think about it?

**Comment by PontiacCZ** [comment]
Three years talking about rendering wayside_shrine? Where did it stick - with creating the graphics?
I often add wayside shrines to OSM and would love to see them on the main layer.

**Comment by matkoniecz** [comment]
> Where did it stick - with creating the graphics?

Yes, that is the main problem. It turns out to be quite hard to make a good icon even for simple religion=christian case.

**Comment by kocio-pl** [comment]
Since we have no solution for a long time, I guess we should close it now. If someone comes with an idea, this could be reopened.

**Comment by kocio-pl** [comment]
What if we start rendering them later (like z18+) with proposed design?

**Comment by Penegal** [comment]
Sounds good to me ; the icon seems OK and that really could help general users to have these landmarks.

**Comment by kocio-pl** [comment]
I will wait for additional comments, but that means it's worth to reopen this issue. Code should be rather easy to prepare if we reach agreement here.

**Comment by PontiacCZ** [comment]
You mean the proposed symbol in the original post? I agree.

**Comment by kocio-pl** [comment]
I mean both christian and non-christian icons:
1) ![shrine-9-11](https://cloud.githubusercontent.com/assets/5439713/8932747/531a7ac6-353f-11e5-8e5f-d68eaea8a45b.png)
2) ![shrine-9-12](https://cloud.githubusercontent.com/assets/5439713/8937027/29d10ac4-3556-11e5-81c9-0dfe702f4b9c.png)

**Comment by PontiacCZ** [comment]
Yep, I think both of them are fine, let's go for them.

**Comment by Tomasz-W** [comment]
For me, it's not representing common-known shrine shape enough. What about classic wayside shrines shape?

![historic wayside_shrine2](https://user-images.githubusercontent.com/25656654/34669768-a23295da-f473-11e7-819d-f657a33a66f5.png)

14x14: ![historic wayside_shrine](https://user-images.githubusercontent.com/25656654/34669772-a5ecd8ca-f473-11e7-92bc-cb0eca74716a.png)
14x14 (brown): ![historic wayside_shrine brown](https://user-images.githubusercontent.com/25656654/34669911-4f4658d8-f474-11e7-9141-73f2edef0e68.png)

**Comment by kocio-pl** [comment]
Do you plan to have one universal shape instead of christian+generic?

**Comment by matkoniecz** [comment]
> Do you plan to have one universal shape instead of Christian+generic?

I think that Christian + generic is preferable. For start, version with cross is much easier to recognize (I am not sure whatever generic ones are worth rendering) and strongly encourages adding religion tag at least some shrines.

**Comment by kocio-pl** [comment]
> I am not sure whatever generic ones are worth rendering

I think they are, because they are common orientation point in the outdoor. That's why I still try to render them, otherwise we could just render christian shrines the same as wayside crosses (which was proposed at some point).

**Comment by matkoniecz** [comment]
I agree that with good, recognizable icon rendering them would be a good idea. I have doubts about rendering them with icon that I tried or see here.

**Comment by kocio-pl** [comment]
@Tomasz-W Could you publish this shape as gist, so I could try it?

**Comment by Tomasz-W** [comment]
https://gist.github.com/Tomasz-W/e237875a860653546d553cacd4d8afbd

**Comment by kocio-pl** [comment]
@Tomasz-W Thanks again for your design, it was one of the oldest issues alive and I'm happy that it's done at last!... It looks like sometimes trying to make the icon smaller is worse than having full size icon but with a lighter color - good lesson.

**Comment by Tomasz-W** [comment]
Fun fact: 1642 days passed between opening this issue and merge the icon ;)

**Comment by kocio-pl** [comment]
The oldest (re)open(ed) issue ticket is from [11 Jun 2013](https://github.com/gravitystorm/openstreetmap-carto/issues/61), so only about 2 months older than this...

**Comment by kocio-pl** [comment]
@matkoniecz 
> Below is an extreme example, but also single shrines are too prominent.

BTW: are you sure that all these shrines should be tagged as `historic=wayside_shrine`? Maybe they should be retagged as `man_made=shrine`, just like we do with crosses?

**Comment by kocio-pl** [comment]
I know, it's just a thought related to the example you gave here.
