### ISSUE TITLE
Arabic and Hebrew POI names don't show

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1313]
I just noticed that there were many icons without names in the middle east. Then I checked, and the POIs do have names but they don't get rendered. Seems that Arabic and Hebrew are afflicted. I checked some other places with non-roman scripts, and did not find a problem.

**Comment by math1985** [comment]
@daganzdaanda Do you have an example?

@mkoniecz Might this be a text-dy problem? Are Arabic and Hebrew taller than É?

**Comment by mkoniecz** [comment]
@math1985 No idea, example would be helpful. It sounds like a RTL problem ( http://en.wikipedia.org/wiki/Right-to-left ).

**Comment by daganzdaanda** [comment]
Argh, I had a loooong post already, and then the browser crashed >:(

For Hebrew: Any town center in Israel, e.g. this area https://www.openstreetmap.org/#map=19/31.78109/35.21898
For Arabic: look in Teheran, e.g. https://www.openstreetmap.org/#map=18/35.68707/51.41875

The museums in Teheran make it look likely that it has to do with text-dy: some labels are there, some not, and it changes with zoom.
Hebrew seems to miss even more labels, maybe it needs even more text-dy.
Just found this: https://www.openstreetmap.org/#map=19/32.07437/34.80938 
Two pharmacies with hebrew names, one is labeled.

Some POIs seem to be (mostly?) OK though: bakery, bank, generic shop. But I wouldn't count on that...

**Comment by mkoniecz** [comment]
It seems to be text-dy issue with new icons. I am now running text-dy validator for v2.28.1.

**Comment by math1985** [comment]
> It seems to be text-dy issue with new icons. I am now running text-dy validator for v2.28.1.

No, I think it is a mapnik bug where RTL text is rendered too high.

**Comment by math1985** [comment]
Reported upstream at https://github.com/mapnik/mapnik/issues/2705.

**Comment by math1985** [comment]
Prefixing the string to be displayed with chr(8206) (LEFT-TO-RIGHT MARK) resolves the problem but reintroduces https://github.com/mapnik/mapnik/issues/189.

**Comment by pnorman** [comment]
I don't think there's anything we can do on our end until it's fixed in a released version of Mapnik

**Comment by math1985** [comment]
I agree.

Do we leave bugs that need to be fixed upstream open, or do we close them?

Did anyone check if Mapnik 3 solves this issue?

**Comment by mkoniecz** [comment]
> Do we leave bugs that need to be fixed upstream open, or do we close them?

I propose open, in a separate milestone. It makes possible to check every X months whatever issues are fixable by updating dependencies.

**Comment by gravitystorm** [comment]
> I propose open, in a separate milestone.

Agreed

**Comment by pnorman** [comment]
Confirming fixed in Mapnik 3

**Comment by math1985** [comment]
Mapnik 3 has now been rolled out, so this should be fixed now on openstreetmap.org as well.
