### ISSUE TITLE
Rendering standalone bridges

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#1320]
There are sometimes bridges that are not rendered on the map, because they are not part of an otherwise rendered feature. For example, there may be a bridge that is inaccessible and does not have path or road on top but is still a significant feature that would be expected to be shown on a map. Often these were built for a purpose (road, railway, path) that no longer applies but the structure is still present. Sometimes they are in use but for a purpose that we do not render. Often they are named.

The suggestion is to consider rendering ways with `bridge=yes` even when it is not part of a rendered linear feature.

**Comment by math1985** [comment]
Duplicate with #612?

See also #1320.

**Comment by gravitystorm** [comment]
(Please note that there have been previous issues around this topic which have been repeatedly driven off-topic. Unless you are a maintainer on this project, please do not mention or even hint at "abandoned railways" since that will lead to your comments being deleted and you being blocked from making future comments.

**Comment by althio** [comment]
I support this and I add a suggestion for rendering if this is in the scope of this issue.

left: current rendering for `bridge=yes` with rendered way
right: proposed rendering for `bridge=yes` standalone (supporting way not rendered).
![bridge-standalone](https://cloud.githubusercontent.com/assets/9863567/6247665/7ee85894-b777-11e4-8495-b6357a3d050f.png)

**Comment by kocio-pl** [comment]
What about bridge dimensions (I mean 2D)? For me it's kind of building - it can have different shapes and sizes.

**Comment by althio** [comment]
@kocio-pl 
> What about bridge dimensions (I mean 2D)? For me it's kind of building - it can have different shapes and sizes.

If I am not mistaken, `bridge=yes` is a 1D feature because it is only an attribute on a supporting way. It is linear, no width, no shape, only the length of the tagged way does matter.
I am OK with a constant rendered width, similar to a bridge with a rendered road.

I also think you can support `man_made=bridge` at https://github.com/gravitystorm/openstreetmap-carto/issues/436 to discuss more detailed rendering when more detailed tagging is available.

**Comment by kocio-pl** [comment]
Thanks for clarification, now I probably understand! 

I think 1D should be rendered as you have shown us, because 2D (with outline) doesn't care for railways/roads/paths at all and we don't have to look at special cases like this.

**Comment by math1985** [comment]
> left: current rendering for bridge=yes with rendered way

No, that's not the current rendering.

**Comment by brycenesbitt** [comment]
@kocio-pl there are ways to map in 2D.  A tag "width=x m" can be added to a "bridge=yes", to hint rendering as to the significance of the feature on the ground.   man_made=bridge is available for 2D bridge mapping.

**Comment by matkoniecz** [comment]
Maybe rendering man_made=bridge would be enough?

**Comment by dieterdreist** [comment]
sent from a phone

> Am 04.07.2015 um 19:21 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Maybe rendering man_made=bridge would be enough?


I agree, bridge_name is just a hint on which bridge a way runs on, adding the name to the bridge itself (name key on man_made bridge object) should be preferred

**Comment by jojo4u** [comment]
man_made=bridge ought to be enough. bridge=yes is a subtag which should not be evaluated if we don't render the object.

@dieterdreist you mention bridge_name, but I don't see it mentioned in this thread before. Also  bridge:name is more comon now.

**Comment by dieterdreist** [comment]
> @dieterdreist you mention bridge_name, but I don't see it mentioned in this thread before. Also bridge:name is more comon now.


it does not matter, both are odd ;-)
the name tag variations typically use the underscore (int_name, loc_name etc) while bridge subtags use the colon (bridge:structure....) so bridge:name seems logical for the attribute subtag

By using the key "name" on the right object we can avoid this altogether
