### ISSUE TITLE
natural=wood and landuse=forest completely camouflage streets (especially highway=trunk) in low zoom levels

### ISSUE THREAD

**Issue by IOOI-SqAR** [gravitystorm/openstreetmap-carto#1323]
natural=wood and landuse=forest completely camouflage streets (especially highway=trunk) in low zoom levels. Do you see the three rings of highway=trunk around Moscow in the attached screenshot? I don't.
![bildschirmfoto 2015-02-20 um 14 09 23](https://cloud.githubusercontent.com/assets/9305009/6286792/a2e17d62-b90b-11e4-8630-464595e9925d.png)

A solution wood be to lower the color saturation of both natural=wood and landuse=forest

**Comment by math1985** [comment]
Duplicate with #102.

**Comment by HolgerJeromin** [comment]
reported as #102
