### ISSUE TITLE
Make Travis CI build log less cryptic

### ISSUE THREAD

**Issue by mkoniecz** [gravitystorm/openstreetmap-carto#1329]
Currently it is rather hard to guess how 

> The command "scripts/yaml2mml.py < project.yaml > project.mml2 && diff project.mml project.mml2" exited with 1.

should be fixed. I think that mentioning https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#editing-layers would be a good idea.

Also, is it possible to eliminate wall of text (lines 142-156 in https://travis-ci.org/gravitystorm/openstreetmap-carto/builds/51634644)? Or is it useful for some purpose?

**Comment by pnorman** [comment]
> Also, is it possible to eliminate wall of text (lines 142-156 in https://travis-ci.org/gravitystorm/openstreetmap-carto/builds/51634644)? Or is it useful for some purpose

It outputs the diff so you can see where the issue was. If the yaml and mml correspond, then it won't output text.

**Comment by tvainika** [comment]
How about adding an explanation message after failure like this:

diff --git a/.travis.yml b/.travis.yml
index f2a2a94..580ece2 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,4 +20,4 @@ install:
 script:
   - jsonlint project.mml
   - ./node_modules/carto/bin/carto project.mml | xmllint - | wc -l
-  - scripts/yaml2mml.py < project.yaml > project.mml2 && diff project.mml project.mml2
+  - scripts/yaml2mml.py < project.yaml > project.mml_generated && diff project.mml project.mml_generated || (echo "FAIL: Please run script/yaml2mml.py if you modify project.yaml, see CONTRIBUTING.md for details"; false)
