### ISSUE TITLE
city wall inconsistencies

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1333]
Line thickness varies between `barrier=city_wall` and `historic=citywalls` with the latter being on its own layer.

Example: http://www.openstreetmap.org/#map=19/49.61542/6.13741
![citywall](https://cloud.githubusercontent.com/assets/3531092/6333519/fc9d18f0-bb8d-11e4-86a7-3c634c5b18b1.png)

The connecting line between the thicker line parts is tagged as `barrier=city_wall` while the other parts also have a `historic=citywalls` tag.

**Comment by mkoniecz** [comment]
I am not sure is it a good idea to display historic=citywalls. Maybe it is expecting too much, but city walls may be mapped as building=*.

Current historic=citywalls rendering is not intuitive, especially in places with building=* - see http://www.openstreetmap.org/#map=19/41.90367/12.45770

![selection_001](https://cloud.githubusercontent.com/assets/899988/6336522/721c2084-bba3-11e4-8c90-e5a986356aac.png)
