### ISSUE TITLE
highway=residential is rendered above primary_link roads at intersections

### ISSUE THREAD

**Issue by skorasaurus** [gravitystorm/openstreetmap-carto#1334]
As I understand, it's common practice in this stylesheet that when roads intersect, the road with a higher priority (i.e. primary and residential intersect, primary will be displayed over the residential road at the intersection). 

This practice is not followed when residential and primary_link roads intersect. As show in the example below, the residential road is displayed above the primary_link. 

![selection_035](https://cloud.githubusercontent.com/assets/955351/6356574/4bc45f9e-bc2c-11e4-8749-08e862e707e4.png)

[This road had been tagged incorrectly as highway=primary_link](https://www.openstreetmap.org/way/122085248) (and I've corrected the tag to primary), but in cases where it's correct tagging, primary_link should be rendered above residential.

**Comment by math1985** [comment]
Duplicate with #678 - in that issue it is also discussed why there is no trivial fix for this,
