### ISSUE TITLE
Rendering name with very close characters, hard to read

### ISSUE THREAD

**Issue by kerosin** [gravitystorm/openstreetmap-carto#1335]
Hello,

The characters of natural=water are very close so that you can not differentiate between "rn" or "m".
example Kernersee
![](http://i.imgur.com/8FGUtf0.png)
see live at http://osm.org/go/0MEnwKXYl

This seems to affect also other objects like streets, see
http://www.openstreetmap.org/#map=18/51.54463/6.84936

This is of course also depending on the zoom level. Hopefully this can be improved.

Thanks in advance!

**Comment by polarbearing** [comment]
I assume you mean you can _not_ differentiate between them?
The typographic term is kerning, is that adjustable in carto?
https://en.wikipedia.org/wiki/Kerning

**Comment by HolgerJeromin** [comment]
iirc kerning is about top-heavy chars with next char is bottom-heavy. This is the case between "Ke" but not between "rn".

**Comment by math1985** [comment]
Seems to be an issue already present in the font (DejaVu Sans Oblique).

![screenshot](https://cloud.githubusercontent.com/assets/5251909/6373811/0016dd04-bd05-11e4-9ad1-8bdb258721a2.png)

**Comment by daganzdaanda** [comment]
The "rn" combination is actually used in textbooks to show that sans-serifs are a bit less "stable" than serifs when it comes to close spacing.
Kerning is usually coded into a font, and optimized for a normal reading size (e.g. 9 or 10pt). Smaller sizes may not work as well. Also, at a small size the hinting and anti-aliasing on a screen interfere with what you get. And some programs just ignore the kerning tables. 

Here, the outline / halo fuses in some places, and makes the letters look even closer than they are. 
I'd just increase the letter-spacing (tracking) for all the letters a bit, maybe 2px. 

Optionally, we could space all the letters evenly over the whole lake (if that's possible).

**Comment by math1985** [comment]
>  I'd just increase the letter-spacing (tracking) for all the letters a bit, maybe 2px. 

This is possible, but would look bad for Arabic, see [here](https://www.mapbox.com/blog/multilingual-character-spacing/).

**Comment by math1985** [comment]
Other example in OpenOffice:
![screenshot from 2015-03-02 15 41 02](https://cloud.githubusercontent.com/assets/5251909/6444082/28edfa40-c0f3-11e4-999e-2f79e12e43fc.png)

**Comment by math1985** [comment]
Reported upstream, let's see what they think.

https://bugs.freedesktop.org/show_bug.cgi?id=89393

**Comment by fkv1** [comment]
> Also, at a small size the hinting and anti-aliasing on a screen interfere with what you get.

Anti-aliasing should be turned off for every kind of text altogether. It makes the text blur without delivering any real benefit. Additional examples at #2028.

**Comment by math1985** [comment]
This might be fixed in Mapnik3 as well.
