### ISSUE TITLE
Unrendered man_made overrules natural

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1336]
Opening a new issue after https://github.com/gravitystorm/openstreetmap-carto/issues/1060#issuecomment-75535146

Nodes with man_made=cross and natural=peak don't show up on the map.
Example: https://www.openstreetmap.org/node/26863070
More examples: http://overpass-turbo.eu/s/7OE

As @nebulon42 notes, *in the SQL  man_made  takes precedence over  natural , but since  man_made=cross  is not rendered nothing is rendered.*
Related to #1269 (amenity vs tourism)

Possible solutions I can think of: 

1 - reverse priority, render all natural over all man_made on the same node
   ...Likely to cause other issues?
1a - selectively render natural=peak over all man_made on the same node

2 - render something for man_made=cross
2a - render something special for man_made=cross and natural=peak combo

3 - more general: Have a list of things that get rendered for each key, and if the value is not on that list, look for another possible key to render. No idea if that is realistically possible, or if it would open other problems.

**Comment by math1985** [comment]
> 3 - more general: Have a list of things that get rendered for each key, and if the value is not on that list, look for another possible key to render. No idea if that is realistically possible, or if it would open other problems.

Yes, that's possible, and the way this should be solved.

**Comment by nebulon42** [comment]
While 3 is conceptually a good solution I have no clue how to implement that regarding SQL and Carto. @math1985 Maybe you can expand a bit on how you see this could be done?

**Comment by mkoniecz** [comment]
Its seems to be already done in some queries like https://github.com/gravitystorm/openstreetmap-carto/blob/a392b4560def43c2ce073daac0fd3dca41f7829d/project.yaml#L117

Note that values of landuse other than 'forest' are transformed into null, without that COALESCE on [landuse='trolololo'; natural='forest'] would produce 'trolololo'.

> CASE WHEN landuse IN ('forest') THEN landuse ELSE NULL END

transforms [landuse='trolololo'; natural='forest'] into [landuse=null; natural='forest'] - and coalesce returns 'forest'.

**Comment by math1985** [comment]
> Its seems to be already done in some queries like https://github.com/gravitystorm/openstreetmap-carto/blob/a392b4560def43c2ce073daac0fd3dca41f7829d/project.yaml#L117

Yes, that's the way to go.
