### ISSUE TITLE
Name of attraction, pedestrian area is changing with zoom

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1339]
http://www.openstreetmap.org/way/95334058#map=18/50.76381/6.11586
this petting zoo is mapped as:

    highway=pedestrian
    name=Zwergziegen-Streichel-Gehege
    tourism=attraction
    attraction=animal

and rendered >zoom 18 with a black name, but on zoom 17 it transforms into the attraction font color.
I am not sure if pedestrian is a good tag, but i think footway would render the same.
Perhaps it is not worth any fine tuning.

**Comment by dieterdreist** [comment]
2015-02-27 12:50 GMT+01:00 Holger Jeromin <notifications@github.com>:

> http://www.openstreetmap.org/way/95334058#map=18/50.76381/6.11586
> this petting zoo is mapped as:
>
> highway=pedestrian
> name=Zwergziegen-Streichel-Gehege
> tourism=attraction
> attraction=animal
>
> and rendered >zoom 18 with a black name, but on zoom 17 it transforms into
> the attraction font color.
> I am not sure if pedestrian is a good tag, but i think footway would
> render the same.
> Perhaps it is not worth any fine tuning.
>


tourism=attraction seems to be a complete exxageration for this feature,
I'd remove it. Rather there should be a tag to describe the kind of feature
(compound) and ideally also one to say which kind of animal is locked-in.

**Comment by HolgerJeromin** [comment]
attraction is the right tagging for this:
http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dzoo#Animal
But you are right, i missed the genus tag. Will add it (as i did already for all the animals in this zoo)

**Comment by dieterdreist** [comment]
2015-02-27 13:42 GMT+01:00 Holger Jeromin <notifications@github.com>:

> attraction is the right tagging for this:
> http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dzoo#Animal
> But you are right, i missed the genus tag. Will add it (as i did already
> for all the animals in this zoo)
>



I disagree, while attraction=animal looks fine to me, there is really no
need to add tourism=attraction to every compound. My suggestion is to
remove this from the page you linked.

Please also note that this is not settled tagging but something that was
put into the wiki just a few days ago:
http://wiki.openstreetmap.org/w/index.php?title=Tag%3Atourism%3Dzoo&diff=1117079&oldid=1089427

cheers,
Martin

**Comment by HolgerJeromin** [comment]
Other examples:
http://www.openstreetmap.org/way/111595742#map=18/51.78510/6.13896
http://www.openstreetmap.org/way/229646048#map=19/48.14877/8.23767

**Comment by mkoniecz** [comment]
It is possible to
- ignore this effect
- render names for highway areas (is it applicable also to linear features?) earlier for ones with tourism attraction
- render tourism attraction names on highways in a highway style

I am tempted to solve it by ignoring this effect.

**Comment by math1985** [comment]
It seems the reason for this bug is that road area names are rendered if they are over 3000 pixels, while attraction names are rendered either if they are over 3000 pixels, or from zoom 17. This area only reaches 3000 pixels on z18, so on z17 the attraction name is labelled and on z18 the road area name.

I think this should be solved by always rendering road area names from z17 independent of size.

**Comment by HolgerJeromin** [comment]
I like math1985 suggestion.
