### ISSUE TITLE
having issue getting to load in TIleMill

### ISSUE THREAD

**Issue by d3netxer** [gravitystorm/openstreetmap-carto#1340]
I cloned the repo, ran get-shapefiles inside the directory, the shapefiles downloaded successfully. I then copied the openstreetmap-carto folder inside my TileMill projects directory. When I open the project in TileMill all I see is blue. Any help?

In the past it worked for me and I could see all the layers.

**Comment by pnorman** [comment]
Is this zoom 0? There's a known issue there.

**Comment by d3netxer** [comment]
ok, I just opened TileMill and started zooming in more; the land appears at zoom level 10 or higher, but everything turns blue whenever I zoom out. Does anybody know why?

**Comment by pnorman** [comment]
It sounds like you're missing the low-zoom shapefile. What is the output of `ls -hal data/simplified-land-polygons-complete-3857/`?

simplified_land_polygons.shp should be about 31MB. If not, delete simplified-land-polygons-complete-3857 and re-run `./get-shapefiles.sh`

**Comment by d3netxer** [comment]
I found out what did it. I modified the shapefiles.mss file: https://github.com/gravitystorm/openstreetmap-carto/blob/master/shapefiles.mss

These lines display the coast only at zoom level 10 or more:

#coast-poly {
[zoom >= 10] {
polygon-fill: @land-color;
}
}

I changed 10 to 1. Now I can see the coasts when I open the project and know where I am.

**Comment by math1985** [comment]
Glad to see it's solved!

**Comment by pnorman** [comment]
> I found out what did it. I modified the shapefiles.mss file

Are you saying you had modified it, and when you reverted your changes it was fixed, or are you saying you made changes? If the latter, you haven't fixed it.

**Comment by math1985** [comment]
Oops, I was not paying attention. It should indeed work without changing the 10 to 1.

Likely something related to @d3netxer's setup. Feel free to discuss further, but I suspect the problem is not on our side, so I'll leave the status as closed.

**Comment by d3netxer** [comment]
@pnorman here is my output of ls -hal simplified-land-polygons-complete-3857/

vagrant@ubuntu1204-desktop:/home/openstreetmap-carto/data$ ls -hal simplified-land-polygons-complete-3857/
total 33M
drwxr-xr-x 2 root root 4.0K Feb 27 21:28 .
drwxr-xr-x 7 root root 4.0K Feb 27 21:24 ..
-rw-r--r-- 1 root root    6 Feb 22 07:06 simplified_land_polygons.cpg
-rw-rw-r-- 1 root root 743K Feb 22 07:06 simplified_land_polygons.dbf
-rw-r--r-- 1 root root 348K Feb 27 21:28 simplified_land_polygons.index
-rw-rw-r-- 1 root root  847 Feb 22 07:06 simplified_land_polygons.prj
-rw-rw-r-- 1 root root  31M Feb 22 07:06 simplified_land_polygons.shp
-rw-rw-r-- 1 root root 496K Feb 22 07:06 simplified_land_polygons.shx

**Comment by d3netxer** [comment]
@pnorman I had not modified the shapefiles.mss file originally.

I had modified it after I ran into the issue when trying to solve it. So I'm not sure I really fixed it
