### ISSUE TITLE
Rendering issues in Bengali

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#1346]
There are some problems with rendering in Bengali, first reported [here](http://forum.openstreetmap.org/viewtopic.php?id=30265).

For example, see [here](http://www.openstreetmap.org/node/317729205#map=14/22.6961/90.3929). Note the different order of the characters in the sidebar and in the labelled renderer. The order in the sidebar should be correct.

**Comment by math1985** [comment]
@pnorman Do you have any idea what might cause this?

**Comment by gravitystorm** [comment]
It's best to check this with mapnik3 before investigating much else. The harfbuzz rendering in mapnik3 changes so many aspects of non-european text rendering.

**Comment by AhmedShawon92** [comment]
Another example http://www.openstreetmap.org/node/1623159414

**Comment by pnorman** [comment]
Looks like a glyph placement problem, almost certainly solved in harfbuzz because chrome gets it right.

Nothing we can do until @springmeyer releases a new version of Mapnik which includes harfbuzz.

I was able to be fairly confident about the source of this error because I've seen it before with other scripts, but for script errors we really need pictures of both the wrong rendering and what the correct rendering is.

**Comment by pnorman** [comment]
I'm not sure if this is solved in harfbuzz or not, because I don't know what the correct placement is

**Comment by AhmedShawon92** [comment]
From the previous 2 example, right form is what you see in left panel. Wrong is what you see on map. In  1st example(http://www.openstreetmap.org/node/317729205#map=14/22.6961/90.3929) right form is "বরিশাল" but map shows "বরশিাল" which is wrong. In 2nd example(http://www.openstreetmap.org/node/1623159414) right form is "পিরোজপুর" but OSM shows "পর োজপুর".

**Comment by pnorman** [comment]
> From the previous 2 example, right form is what you see in left panel

The point is that in a script where we know there are rendering issues with some fonts, relying on anything other than a picture or screenshot may not work.

**Comment by AhmedShawon92** [comment]
It's hard to to make a English speaker understand about this. There is something in our language(along with many south asian language) called "Kar". They are the short form of vowels and also work as vowels as they do in English language. When one of these "kar"s sits in front of a letter than OSM can render them correctly. Imagine a 2 letter word "পাড়", where "প" and "ড়" is letter and "া" is a Kar which is sitting in front of the letter "প". It will be rendered correctly on OSM. But when one of those "Kars" sits behind a letter than the problem will start and OSM renderer wiil show it sitting in front of the letter(behind the next letter). Example: Imagine another 2 letter word "ডিম" where the Kar "ি" and is sited behind the letter "ড". But OSM will render this word as "ডমি" placing the car in front of the letter "ড", behind the next letter "ম".
Sorry for my bad English.

**Comment by AhmedShawon92** [comment]
Description of the problem: 
It's hard to to make a English speaker understand about this. There is something in our language(along with many south asian language) called "Kar". They are the short form of vowels and also work as vowels as they do in English language. When one of these "kar"s sits in front of a letter(or under a letter) than OSM can render them correctly. Imagine a 2 letter word "পাড়", where "প" and "ড়" is letter and "া" is a Kar which is sitting in front of the letter "প". It will be rendered correctly on OSM. But when one of those "Kars" sits behind a letter than the problem will start and OSM renderer wiil show it sitting in front of the letter(behind the next letter). Example: Imagine another 2 letter word "ডিম" where the Kar is "ি" and it is sited behind the letter "ড". But OSM will render this word as "ডমি" placing the Kar in front of the letter "ড", behind the next letter "ম". 
The language Bangla has 10 Kars: া, ি, ী, ু, ূ ৃ, ে, ৈ, ো and ৌ. OSM can render া, ী, ু, ূ and ৃ properly as they sit in front and under of letters. Can't render ি, ে, ৈ as they sit behind of letters. OSM also can't render ো and ৌ who has 2 parts one sitting behind and one part sitting in front of the letter at the same time. Many south Asian language use Kars.

**Comment by gravitystorm** [comment]
@AhmedShawon92 thanks for the detailed description of the problem.

**Comment by AhmedShawon92** [comment]
JOSM latest version started supporting Bangla but it also has 100% same problem. Sorry for may bad English. The last point is that OSM can't show the correct position of kars(which changed the whole word) if they sit other places than front of a letter.

**Comment by AhmedShawon92** [comment]
JOSM team have probably fixed their problem(https://josm.openstreetmap.de/changeset/8111/josm). This topic was discussed here(https://josm.openstreetmap.de/ticket/11194). When it will be fixed in OSM website?

**Comment by pnorman** [comment]
closing in favour of #2017 which is more general

**Comment by math1985** [comment]
As Mapnik 3 now has been rolled out, this should have been solved.
