### ISSUE TITLE
Add to contributing.md requesting pictures

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1347]
OSM is a constantly changing data source and frequently an area has changed after an issue has been reported, making it impossible to see what the problem is. CONTRIBUTING.md should request a screenshot of reported issues.

This also makes it easier to see what the issue is without having to hunt it down.

**Comment by mkoniecz** [comment]
Maybe it would be better to add guidelines for reporting issues directly to this box on https://github.com/gravitystorm/openstreetmap-carto/issues/new ?

I think that even people that followed link quickly stop reading - as currently this document is about pull requests, not about how issues should be reported.

**Comment by pnorman** [comment]
We can't change that box afaik.

**Comment by mboeringa** [comment]
It may be a crazy idea, but couldn't this in fact be automated? Each time a user posts a contribution with a link to one of the rails application's screens showing OSM data (e.g. http://www.openstreetmap.org/#map=8/52.154/5.295), a screenshot could be generated based on the link by some server, and then stored somewhere with a reference / link to the original post it relates to based on the issue comment reference number (e.g. https://github.com/gravitystorm/openstreetmap-carto/issues/1347#issue-59544856)... This way, there would be no reliance on user interaction, and the historic snapshot of the area would be retained safely for further reference.

**Comment by mkoniecz** [comment]
@mboeringa What is displayed for user depends on tile server - sometimes it results in different map for different people at the same time. Also, caches introduce differences.

**Comment by pnorman** [comment]
cropping a screenshot also means we know what is the issue - not a big screen full of map, most of which is probably not relevant to the problem.

**Comment by matkoniecz** [comment]
> Maybe it would be better to add guidelines for reporting issues directly to this box on https://github.com/gravitystorm/openstreetmap-carto/issues/new ?

It is now possible - see example in action on https://github.com/clementine-player/Clementine/issues/new

More info at https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by pnorman** [comment]
We now have the text

> As OpenStreetMap data is always changing, rendering bug reports should always contain a cropped screenshot of the problem, and a link to the area. Don't assume that we will see exactly what you see. If a particular OSM object is an issue, the issue should contain the tagging of the object.

Compliance isn't great, but a PR template in #2256 might help. Also, we can quote CONTRIBUTING.md if someone doesn't add a screenshot and we need one.
