### ISSUE TITLE
Match POI label colour to background or icon colour?

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#1355]
For some POI, it both makes sense to match the label colour to the background, and to match it to the icon.

Examples of such POI where this is currently an issue are camp site and playground. If we decide to render areas of hospitals etc., the same issue will arise for such POI.

What would be preferred? Here are a couple of examples for camp site. The first is the current rendering.

![screenshot from 2015-03-04 14 06 04](https://cloud.githubusercontent.com/assets/5251909/6484891/9c30aa4a-c277-11e4-8045-f07b8b86d421.png)

![screenshot from 2015-03-04 14 06 42](https://cloud.githubusercontent.com/assets/5251909/6484901/b13fe022-c277-11e4-8b82-9552d0c328fb.png)

![screenshot from 2015-03-04 14 03 30](https://cloud.githubusercontent.com/assets/5251909/6484847/3f75d000-c277-11e4-8b0b-903fa1bc79ab.png)

![screenshot from 2015-03-04 14 02 06](https://cloud.githubusercontent.com/assets/5251909/6484813/0d9ee184-c277-11e4-8821-6d972ece39ef.png)

**Comment by nebulon42** [comment]
For me different colours for icon and text always looked strange and my first thought was that of a mistake.

I think POIs should have a distinct colour so the last option has too low contrast for me. I'm not sure if changing the font size according to area size while the icon does not change has the desired effect, but I like the font more. But that's more a general dislike of the appearance of DejaVu Sans with a certain letter spacing.

Briefly: I like the first version best.

**Comment by mboeringa** [comment]
I personally find it most intuitive if the color of the icon and accompanying label match, like in examples 1, 3 and 4, as there can be little doubt the icon and label belong to each other, even with more labels and icons in the same location. Matching the color with background color, like in 4, may also be an option, however, you have to consider if you prefer icons with a similar function to have similar color, which may preclude matching with background, or give precedence to the background matching. So function versus consistency with background.

**Comment by math1985** [comment]
Good points above.

Another aspect is that if we keep the text color different from the icon color, the relation between the icon and the area is not clear. For example, in the first picture, it is not clear that the camp sites cover the entire green area. In the last picture, this is much clearer.

**Comment by sommerluk** [comment]
> In the last picture, it's much clearer that the camp site covers the whole area.

+1

**Comment by mkoniecz** [comment]
> In the last picture, it's much clearer that the camp site covers the whole area.

What may be misleading. Camp site may cover only part of meadow. Also, what about camp sites in different places where background will be different?

**Comment by math1985** [comment]
> What may be misleading. Camp site may cover only part of meadow. Also, what about camp sites in different places where background will be different?

Camp sites are always rendered green (with a darker green outline). There is no meadow or grassland in the picture above, the green comes from the camp site tag.

If the camp site only covers part of a meadow, and it's tagged as an area, then the outline of the camping is still visible. If it's tagged as a point, using the blue icon might be better.

**Comment by pnorman** [comment]
I don't like 2, it looks odd. 4 might look better with more contrast, but I find it hard to look past that.

**Comment by math1985** [comment]
Version with increased contrast:

![screenshot from 2015-03-12 19 20 00](https://cloud.githubusercontent.com/assets/5251909/6626182/cbd660a2-c8ec-11e4-91a9-23e21427ec7a.png)

**Comment by mboeringa** [comment]
I like the last version. Clear and sharp with the dark color, yet still recognizable green.

**Comment by mkoniecz** [comment]
> Camp sites are always rendered green (with a darker green outline). There is no meadow or grassland in the picture above, the green comes from the camp site tag.

In that case greenish icon is a good idea. The only problem is that it removes unification of colour for various accommodations.

I also like the last version.

**Comment by math1985** [comment]
> The only problem is that it removes unification of colour for various accommodations (hotels, hostels, motels etc).

I agree.

Another problem is that it's not clear how the label should be rendered on zoomlevels where the area is smaller. It probably doesn't look good if the label is larger than the area.

**Comment by math1985** [comment]
@imagico @RAytoun Do you have an opinion on this issue? How is this usually handled?

**Comment by imagico** [comment]
I don't really have a strong opinion here - a few thoughts though:

* This seems to be a matter of scale, at low zooms something like a campground is more a POI to be symbolized with icon and corresponding label - even if it is also rendered as an areas while at high zooms it is primarily a landuse, to be symbolized by an area color/pattern.
* Labeling in the same style as area labels with an icon and aligned to the icon seems wrong.  It also would add another variant to the already extremely confusing variety of point label styles demonstrated in #1354

**Comment by math1985** [comment]
@pnorman What is your opinion on the darker version?

**Comment by pnorman** [comment]
"Version with increased contrast" looks okay to me. I wouldn't go any lighter.

**Comment by kocio-pl** [comment]
Contrast version is better, but I don't get the whole issue. Blue is for all the "sleeping" amenities, why we want (misleading) green instead - just because it can usually be used on grass? 

I also don't understand the hospital case - we already display kind-of-reddish icon+label on the yellowish area.

**Comment by pnorman** [comment]
> Blue is for all the "sleeping" amenities, why we want (misleading) green instead - just because it can usually be used on grass?

There is no grass in the above images.

camping is both a sleeping amenity and a park amenity, which is a conflict between how we would colour it.

**Comment by Circeus** [comment]
> I also don't understand the hospital case - we already display kind-of-reddish icon+label on the yellowish area.

What they mean is that all scaling names currently have text color based on the matching area, and when the colors would differs, as they do here or with hospitals, a decision would have to be made in one direction or the other.

**Comment by Tomasz-W** [comment]
@matthijsmelissen @pnorman @kocio-pl @Circeus
Is it still an issue after https://github.com/gravitystorm/openstreetmap-carto/pull/1354 merge? There hasn't been any new comments for almost 2 years? What about closing it?

**Comment by kocio-pl** [comment]
If there's anything left, please reopen it.
