### ISSUE TITLE
Weird rendering of railway=station on building

### ISSUE THREAD

**Issue by diverpl** [gravitystorm/openstreetmap-carto#1356]
Navigate to [this place](http://osm.org/go/0M11MUS7x-?m=). There are three squares for one railway station (one full and two parts of square) and truncated railway station name.

![stobno](https://cloud.githubusercontent.com/assets/8281509/6514456/d5b3fdce-c382-11e4-856c-dadb66200849.png)

**Comment by math1985** [comment]
Probably because of missing `marker-clip: false;`.

**Comment by math1985** [comment]
@mkoniecz Have you loaded this area? Does it indeed fix the problem?

**Comment by mkoniecz** [comment]
@math1985 Yes, it works correctly.

![selection_001](https://cloud.githubusercontent.com/assets/899988/6522612/2303f9bc-c3e7-11e4-8c05-696f4a0673ed.png)

**Comment by mkoniecz** [comment]
BTW, thanks to @diverpl for reporting!
