### ISSUE TITLE
Railway station names should have higher priority than tram stops

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1358]
Side effect of #1357 is making it more likely that railway station name is completely blocked by a tram stop

![selection_001](https://cloud.githubusercontent.com/assets/899988/6522187/2f31095a-c3e2-11e4-984f-f58baa312274.png)

http://www.openstreetmap.org/#map=15/50.06735/19.94883

**Comment by math1985** [comment]
Why is that a side-effect of #1357? I  actually don't fully understand what marker-clip does.

**Comment by mkoniecz** [comment]
Labels now are properly checking for collision across tile borders. It may result in what just added image depicts - labels are no longer broken, but tram stops completely hide railway station label.

**Comment by math1985** [comment]
I see.

It's also a tagging error, I don't think 'osobowy' is officially part of the station name.

**Comment by mkoniecz** [comment]
@math1985 Good catch, I will fix it.

**Comment by gravitystorm** [comment]
> I actually don't fully understand what marker-clip does.

the `-clip` settings control whether or not the underlying geometry is "clipped" (edited) to be only the part within metatile when it's fetched from the datasource. By default in mapnik 2.x all geometries are clipped - a good speedup in many cases like drawing large complex forest polygons.

There are side effects of altering the geometries like this. e.g. for a labelling a polygon each metatile gets a smaller part of the polygon, and tries to label the centre of the clipped polygon instead of the centre of the original polygon. In mapnik 3.x geometry clipping is off by default, and so we'll change our rules so that only particular things (e.g. solid lines without text, polygons fills) have `-clip = true`

**Comment by pnorman** [comment]
> In mapnik 3.x geometry clipping is off by default, and so we'll change our rules so that only particular things (e.g. solid lines without text, polygons fills)

Can we use a wildcard to set a default to prepare for this?

**Comment by gravitystorm** [comment]
> Can we use a wildcard to set a default to prepare for this?

I'm not sure what you mean? In any case, I think the approach will be to make one big switch at whatever point we require mapnik3 (e.g. v4.x)

**Comment by pnorman** [comment]
> I'm not sure what you mean?

Instead of adding `-clip` settings hundreds of times can we use a selector such as

```mss
* {
  polygon-clip: true;
}
```

**Comment by kocio-pl** [comment]
This metro station:

http://www.openstreetmap.org/node/3416840991#map=19/52.25787/20.99429

has no visible label at any zoom level. I don't know what is exact reason, but I strongly suspect it's blocked by tram stops.

**Comment by kocio-pl** [comment]
Both examples work now, so we can close this issue as solved.

**Comment by math1985** [comment]
Has this been solved in the code too, or is it fixed by a change in the data?

**Comment by kocio-pl** [comment]
I don't remember anything I could do with data to avoid it, so my bet is that was something only in the code.

**Comment by pnorman** [comment]
We need to be explicitly sorting in the SQL if the labels are coming from the same layer.

**Comment by kocio-pl** [comment]
I'm inclined to close this issue in a few days if there will be no current examples on the map.

**Comment by matkoniecz** [comment]
I was unable to find anything, though I was not looking for very long.

**Comment by kocio-pl** [comment]
Closing, because our testing cases are resolved now and we couldn't find more of them. Reopening is possible if there will be some new examples of this problem.
