### ISSUE TITLE
failed display of closed way, unclosed way works (multiple affected tags)

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1362]
It affects:
historic=citywalls
man_made=breakwater
man_made=embankment (also #892)
man_made=groyne
natural=cliff (also #268)
natural=tree_row
waterway=derelict_canal
waterway=ditch

it affects also this tags, but in such cases closed way is tagging that makes no sense:
waterway=dam
waterway=drain
waterway=river
waterway=stream
waterway=wadi
waterway=weir
power=line
power=minor_line

This list should contain all affected primary tags, but it is possible that additionally also some tag combinations are affected. Already reported:

Administrative boundaries not being rendered for closed ways #713 

 The boundary=national_park tag is not rendered when tagged on a closed way (not a relation) #1141

**Comment by lest69** [comment]
A closed-way waterway=dam could make sense in some circumstances. One example that comes to mind is the dam around some tailings ponds, which are often completely man-made and enclose the pond in a closed loop. I'll see if I can find one that has been mapped in OSM.

**Comment by math1985** [comment]
power=line and power=minor_line might also make sense as closed loop, if there is redundancy built in the network. As opposed to rivers, power lines are not directional.

**Comment by math1985** [comment]
Example for power=line: www.openstreetmap.org/way/239134263

Waterway=dam is fixed by #991.

**Comment by SGroe** [comment]
Also closed ways tagged with highway=raceway & sport=motor are not shown...

https://www.openstreetmap.org/way/84416553

**Comment by math1985** [comment]
> Also closed ways tagged with highway=raceway & sport=motor are not shown...

@pnorman Would using hstore and dropping sport fro the tag list be a solution to that?

**Comment by math1985** [comment]
See also https://github.com/openstreetmap/osm2pgsql/pull/346#issuecomment-186944592.
