### ISSUE TITLE
drop rendering for waterway=wadi

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1365]
As discussed on tagging mailing list[a] and described on wiki[b] this tag is ambiguous. It may mean ephemeral river, valley, typical course of flash floods. What worse word wadi is used in multiple languages with multiple meanings. There are also additional problems.

It is recommended to use waterway=river/waterway=stream + intermittent=yes for waterways, natural=valley for valleys.

I am proposing to drop rendering of this tag.

[a] https://lists.openstreetmap.org/pipermail/tagging/2015-January/thread.html - thread "waterway=wadi problem"
[b] http://wiki.openstreetmap.org/wiki/Tag:waterway%3Dwadi

**Comment by dieterdreist** [comment]
> Am 11.03.2015 um 17:24 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> It may mean ephemeral river, valley, typical course of flash floods. What worse word wadi is used in multiple languages with multiple meanings. There are also additional problems.
> 
> It is recommended to use waterway=river/waterway=stream + intermittent=yes for waterways, natural=valley for valleys.
> 
> I am proposing to drop rendering of this tag.
> 

I agree that the tagging you propose is more generic and might be universally applicable for similar features, but I don't agree that the meaning in Arabic (valley) is a problem, there has been a definition in the wiki, and the key waterway does give enough context not to apply this tag to valleys

cheers,
Martin

**Comment by pnorman** [comment]
> As discussed on tagging mailing list[a] and described on wiki[b] this tag is ambiguous. It may mean ephemeral river, valley, typical course of flash floods. What worse word wadi is used in multiple languages with multiple meanings. There are also additional problems.
> 
> It is recommended to use waterway=river/waterway=stream + intermittent=yes for waterways, natural=valley for valleys.
> 
> I am proposing to drop rendering of this tag.

It sounds like the tagging change and rendering change are occurring in the wrong order

**Comment by math1985** [comment]
> It sounds like the tagging change and rendering change are occurring in the wrong order

I agree.

**Comment by mkoniecz** [comment]
S what would be a good point to drop rendering? Used than 1k times?

**Comment by sommerluk** [comment]
Now 11 170 ways with this tag.

**Comment by sommerluk** [comment]
Down to 6253 usages on ways now.

**Comment by imagico** [comment]
Reopening since:

* use is now about 1/3 of what it was when the issue was closed
* the tag has been deprecated for several years now
* there is very little active use of the tag, most remaining occurrences are from edits at least several years old, in particular three groups from individual mappers in Tunisia, Pakistan and southern Turkey from about 4 years ago account for nearly half of the data.

**Comment by polarbearing** [comment]
+1 for dropping. 
Maybe the PL wiki page could be changed to use the proper Deprecated template, instead of "description=Do not use, see the wiki page".

**Comment by sommerluk** [comment]
+1 for dropping

If the feature is ambiguous and can mean two different things, the rendering will always be bad for at least one the these two meaning.

**Comment by pnorman** [comment]
> in particular three groups from individual mappers in Tunisia, Pakistan and southern Turkey from about 4 years ago account for nearly half of the data.

This is the most compelling part for me.

**Comment by jeisenbe** [comment]
Usage chart:

![waterway-wadi-taghistory](https://user-images.githubusercontent.com/42757252/66732987-f38c2b00-ee98-11e9-91e7-06989d92b65f.png)

Compare to intermittent=yes used over 2 million times on waterway features, including 1.9 million intermittent streams alone.
