### ISSUE TITLE
highway=services is an area

### ISSUE THREAD

**Issue by al--** [gravitystorm/openstreetmap-carto#137]
highway=services implicitely defines an area.

Please render it as an area (but not pink, if possible...).

**Comment by math1985** [comment]
Best done with osm2pgsql on import.

**Comment by joakimfors** [comment]
Found this in #osm2pgsql/346 

Why should a closed highway=service automatically be treated as area when no other highway= is? I know of a lot of places where service is mapped as closed ways but aren't areas IRL.

**Comment by HolgerJeromin** [comment]
We talk about highway=services not highway=service here :-)

**Comment by math1985** [comment]
http://wiki.openstreetmap.org/wiki/Tag:highway%3Dservices

Very confusing, I admit.

**Comment by joakimfors** [comment]
Ah, sorry. I shouldn't comment on issues in the middle of the night. ;)

**Comment by jojo4u** [comment]
Please also treat highway=rest_area as area, it's the small cousin of services (http://wiki.openstreetmap.org/wiki/Tag:highway%3Drest_area).
