### ISSUE TITLE
tourism=attraction is selected too early in COALESCE

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1371]
After #1349 [landuse=\*; tourism=attraction; name=\*] label is rendered in tourism attraction style. Old rendering in that case was better. 

![landuse village_green tourism attraction name eeeeee eeeeee eeeeee ref 1 ele 8000 closed_way v2 28 1 - master](https://cloud.githubusercontent.com/assets/899988/6650788/b6f4f30e-ca24-11e4-8edd-c373ced8d3fd.png)
https://cloud.githubusercontent.com/assets/899988/6650786/b575c936-ca24-11e4-93fe-d3c470635102.png) - see z14 to z17
https://cloud.githubusercontent.com/assets/899988/6650789/b85cbcf4-ca24-11e4-80d2-9312f0e489f9.png - see z15+

It may be solved by splitting COALESCE for tourism key in two parts. Remove value attraction from the current one and add new at the end containing only value attraction. It would reduce priority of tourism=attraction.

>  'tourism_' || CASE WHEN tourism IN ('attraction')

tourism=attraction overrides also values of other keys COALESCE, except key aeroway.

**Comment by mkoniecz** [comment]
> tourism=attraction overrides also values of other keys COALESCE, except key aeroway.

And for features with icons it seems to result in disappearing labels, as tourism=attraction labels is lacking text-dy.

https://cloud.githubusercontent.com/assets/899988/6650842/78f029fa-ca26-11e4-94ea-467b5d4ed202.png
