### ISSUE TITLE
Label's position sometimes doesn't follow label node's position

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1386]
For admin_level=4 label seems to be always rendered in the center of the area:

http://www.openstreetmap.org/relation/130935

while I guess it should follow label node's position:

http://www.openstreetmap.org/node/504977488

**Comment by math1985** [comment]
This is a deliberate change, see #1134.

**Comment by math1985** [comment]
It's also duplicate with #105, so I will close it for the same reason.

**Comment by kocio-pl** [comment]
Thanks for the links! =} I guess it could be open (at least for now), because I have some further comments and questions. Maybe the subject will deserve renaming (if that's technically possible).

> It's entirely the wrong concept to put a "label" node in the database, and I'll not be using it for rendering.

Ok, I see - but we use them at some other levels. So why are we so inconsistent with such "entirely wrong concept"? With such a strong statement we definitely shouldn't.

> If the renderer isn't sufficiently advanced to place a label to your desire, then lets improve the renderer. 

That would be even better for me than manual labeling! 

The real problem for me is that sometimes admin_centre name is obscured by admin_level name, which I consider a serious bug for a general map. For example Warsaw is not visible up to z=7 (I think there are some other bugs at low zoom levels, but 6 and 7 seem like obvious cases of above).

IMO admin_level name should always try hard to allow admin_centre name to appear where it really is, because it is probably huge and we have more flexibility in choosing the place to render its name.

**Comment by matkoniecz** [comment]
> The real problem for me is that sometimes admin_centre name is obscured by admin_level name

I think that it would be better to open ticket for this one (assuming there is not one). Label nodes are resulting in optimization for the most common data consumers what is a rather poor solution.

**Comment by kocio-pl** [comment]
You're right. I will open new ticket for improving the renderer, but this ticket should be probably left open for discussion about the first issue - namely why sometimes use label nodes and whether we should drop using it entirely?

**Comment by math1985** [comment]
> why sometimes use label nodes and whether we should drop using it entirely?

Is this the same issue as #102/#546?

**Comment by kocio-pl** [comment]
I don't know - they are long and hairy... =/ Could you recap current state of things regarding label nodes (if you follow the topic, of course)?

**Comment by math1985** [comment]
Very briefly summarized:
* We only render labels for admin_level 2 and 4, not for higher levels
* We do render place=city, place=town etc. tags
* place=city etc. are often tagged both as node and as area (but sometimes as either of them)
* It is not clear whether it is better to render the node or the centroid of the area

**Comment by kocio-pl** [comment]
OK, so does it mean @gravitystorm changed his mind since #105 (softened it a little) - and also what was the reasons, in a nutshell?

**Comment by math1985** [comment]
I'm not sure if my opinion entirely corresponds to @gravitystorm's opinion, but my main problem is that a label is not a geographic feature and therefore should not be in the database. If the label should be rendered on the centroid, then the renderer is able to compute that without needing a label node. If the label should be rendered out of the way of other features and labels, a label node won't help because this depend on zoomlevel and rendering rules. And if the label should be rendered on the economic centre of a town, then the node should be called place=economic_centre or something like that.

**Comment by kocio-pl** [comment]
You're probably right - label node is cheating. =} But my question is why is not how it should be done, but why it's still used then?

**Comment by math1985** [comment]
> why it's still used then?

I don't think we use label nodes. We do use place=city nodes, which is also not very elegant, but slightly less hack-ish than label nodes.

**Comment by kocio-pl** [comment]
I see. So we can close that ticket now.
