### ISSUE TITLE
Add icon for shop=radiotechnics

### ISSUE THREAD

**Issue by RicoElectrico** [gravitystorm/openstreetmap-carto#139]
As per [the Wiki](http://wiki.openstreetmap.org/wiki/Key:shop):

> A shop selling electronic components, electrical products, radio measuring devices, supplies for radio and electronics

Here's an icon I made: ![radiotechnics](https://f.cloud.github.com/assets/1409116/1046253/4dd73174-1036-11e3-9c96-1cc95eb97249.png) ([SVG version here](http://www.safeupload.w8w.pl/haxor/radiotechnics.svg)). It represents a diode, which is a basic electronic part and also is essential in all radio devices, so I think it is going to be recognizable.

**Comment by kocio-pl** [comment]
The usage is still rising, currently it's 1506 and I agree some diode icon would work:

![taghistory 21](https://user-images.githubusercontent.com/5439713/47948330-77226580-df2f-11e8-8800-4a5d522d32c9.png)
