### ISSUE TITLE
Rendering man_made=gasometer

### ISSUE THREAD

**Issue by markobr** [gravitystorm/openstreetmap-carto#1392]
man_made=gasometer is not rendered at all. It probably should look like some type of building.

**Comment by matkoniecz** [comment]
I think that it should be tagged as [man_made=gasometer; building=gasometer]. According to http://taginfo.openstreetmap.org/tags/man_made=gasometer#combinations typical tagging is [man_made=gasometer; building=yes].

In either case there is no need for rendering change.
