### ISSUE TITLE
layer and roof

### ISSUE THREAD

**Issue by joker234** [gravitystorm/openstreetmap-carto#140]
on object with building=roof and layer=1 should be over highway=service. Often used at gas stations.

**Comment by pnorman** [comment]
We're handling this with `covered=yes`, and there were no concrete suggestions here aside from transparency, which is not an option.

**Comment by RicoZ-OSM** [comment]
I did update documentation of building=roof, imho technically the roof isn't  a  free-flying structure but an open-wall building so ways underneath it should be mapped just like ways through any other building. That means shared nodes, covered/tunnel and no layer in most cases.

See #1710 or wiki for more details.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 04.10.2015 um 13:39 schrieb RicoZ-OSM <notifications@github.com>:
> 
> technically the roof isn't a free-flying structure but an open-wall building


no, the roof is a structure that protects you from precipitation and or sun and or falling stuff and or wind etc, but it doesn't have to have walls (could have columns, could be hung from or attached to something else etc.). And you can't just add walls that aren't structure (walls would bring in additional loads)

**Comment by jojo4u** [comment]
Please discuss this on the wiki/mailing list. RicoZ, you should post only a  link to the discussion, and not your opinion in addition.
