### ISSUE TITLE
High-zoom weir rendering

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1403]
We should probably scale z18 and z19 weir icons up to the width of the river.

z18
![image](https://cloud.githubusercontent.com/assets/1190866/6716702/7a492fae-cd64-11e4-8715-f5a5fb290fdd.png)

z19
![image](https://cloud.githubusercontent.com/assets/1190866/6716689/6b300b00-cd64-11e4-9d33-220d921efdaa.png)

**Comment by kocio-pl** [comment]
Probably yes, but what to do with really wide rivers (waterway=riverbank)?

**Comment by pnorman** [comment]
The weir will need to be as a line there.

I suppose it's *possible* to approximate a point weir into a line going from shore to shore with some PostGIS wizardry, but that would not be my first choice for a mapper-oriented style.

**Comment by imagico** [comment]
> I suppose it's possible to approximate a point weir into a line going from shore to shore with some PostGIS wizardry, but that would not be my first choice for a mapper-oriented style.

I think this is a question with somewhat broader scope also relevant in other cases (like #1384, #244) - should rendering of node features on a way be potentially influenced by the direction of the way.

IMO it should - otherwise mappers feel unnecessarily inclined to tag the orientation in some form which is redundant.

**Comment by pnorman** [comment]
> I think this is a question with somewhat broader scope also relevant in other cases (like #1384, #244) - should rendering of node features on a way be potentially influenced by the direction of the way.

Not really. The issue I raised was about width, not direction. I'd have no objection to orienting the icon to the river (if it weren't a circle), but turning it into a line the width of the river is different. There, I would rather see the weir get mapped as a line, which is more information and, in the case of most weirs, more accurate as they are not precisely a line at 90 degrees to the river.

**Comment by imagico** [comment]
Well - mapping a weir as a line makes sense if the river is mapped with a riverbank polygon.  In your example however the river is mapped as a line and drawn in a style defined width and a weir mapped as a line may be longer or less long than the drawing width of the river at a certain zoom level so the appearance in the map will generally still be off.  If you have the weir direction however it is fairly easy to draw a weir line exactly the right length to match the river width based on just the node.

**Comment by dieterdreist** [comment]
> Am 19.03.2015 um 18:28 schrieb imagico <notifications@github.com>:
> 
> In your example however the river is mapped as a line and drawn in a style defined width and a weir mapped as a line may be longer or less long than the drawing width of the river at a certain zoom level so the appearance in the map will generally still be off.


tomorrow someone might come and draw the water area. If the weir is mapped as a way, the width of the waterway line might be off in renderings, but the weir will always be the correct length

**Comment by pnorman** [comment]
> Well - mapping a weir as a line makes sense if the river is mapped with a riverbank polygon.

I expect the number of weirs mapped as lines where the river they're in is not mapped as a polygon is vanishingly small. If someone cares enough about water features to map the weir in that detail, I'd expect them to care enough about the river area too.

> If you have the weir direction however it is fairly easy to draw a weir line exactly the right length to match the river width based on just the node

I wouldn't be opposed to rendering point weirs as a line normal to the river at that point and the length of the width of a river line, but that's not what this issue is about and is more involved. If you want to make that change, a new issue would be best to track it.
