### ISSUE TITLE
Add special rendering for shop=shoes

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1404]
We should start rendering shop=shoes, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/shoes.svg

[It was proposed in meta-issue https://github.com/gravitystorm/openstreetmap-carto/issues/1402]

**Comment by nebulon42** [comment]
This would be my proposal: ![shoes-18](https://cloud.githubusercontent.com/assets/3531092/6766805/83f951d8-d015-11e4-9b04-abd1ecd1b28d.png)
