### ISSUE TITLE
Add special rendering for shop=photo and shop=photo_studio

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1405]
We should start rendering shop=photo and shop=photo_studio, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/shopping_photo.svg

[It was proposed in meta-issue #1402]

**Comment by kocio-pl** [comment]
[My proposition](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-photo-icon/symbols/photo-14.svg): ![photo-14](https://cloud.githubusercontent.com/assets/5439713/7485361/b1b74a2e-f394-11e4-8e2d-c4483fa0c35b.png)

**Comment by daganzdaanda** [comment]
I like it!
