### ISSUE TITLE
Add special rendering for shop=optician

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1408]
We should start rendering shop=optician, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/optician.svg

[It was proposed in meta-issue #1402]

**Comment by matkoniecz** [comment]
shop=optician is already rendered, with generic shop icon (a purple dot). Is it intended as "render shop=optician with a special icon?" For list of rendered tag you may consult https://github.com/matkoniecz/CartoCSSHelper/blob/master/style_specific/default_osm_style.rb or search in code - https://github.com/gravitystorm/openstreetmap-carto/search?utf8=%E2%9C%93&q=optician

**Comment by matkoniecz** [comment]
The same applies to other clones of this ticket.

**Comment by kocio-pl** [comment]
I thought that is clearly written in the body of the issue - but of course I can also make title more clear too.

**Comment by nebulon42** [comment]
[optician-18.svg](https://github.com/nebulon42/osmic/blob/master/shop/optician-18.svg): ![optician-18](https://cloud.githubusercontent.com/assets/3531092/6778233/2822f156-d151-11e4-90b4-2c8e3dc5bb88.png)

**Comment by kocio-pl** [comment]
Good and recognizable.

**Comment by nebulon42** [comment]
Apparently closing with the commit in #1493 did not work. Should be closed.
