### ISSUE TITLE
Add special rendering for shop=travel_agency

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1409]
We should start rendering shop=travel_agency, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/travel_agency.svg

[It was proposed in meta-issue #1402]

**Comment by kocio-pl** [comment]
1) ![travel_agency-14-3](https://cloud.githubusercontent.com/assets/5439713/7614419/f7aa8bf6-f996-11e4-8c0b-8e2670c61d2f.png)
2) ![travel_agency-14-4](https://cloud.githubusercontent.com/assets/5439713/7614425/00c695ea-f997-11e4-8910-54f1fd40d9a3.png)

1) is basically French original, only slightly edited.

**Comment by AndiG88** [comment]
I'm againt rendering this until there is a clear agreement on the tagging. Currently **office=travel_agent** is also used.

http://wiki.openstreetmap.org/wiki/Proposed_features/office%3Dtravel_agent

**Comment by dieterdreist** [comment]
> Am 14.05.2015 um 07:02 schrieb AndiG88 <notifications@github.com>:
> 
> Currently office=travel_agent is also used.
> 


that is not a travel agency where the clients walk in to book a trip but a back office, or it is mistagging ;-)


I'm opposing the palm tree icon as this seems Europe-centered, won't work in countries where palms are part of the flora.

**Comment by AndiG88** [comment]
> *An office where you can arrange travel tickets, eg train and plane, and hotel and tour bookings.*

> *I propose this instead of the tag shop=travel_agency because you can not remove goods for sale from these premises, rather they sell services which you receive elsewhere.*

Sounds like that's exactly what it is.

**Comment by dieterdreist** [comment]
2015-05-14 11:06 GMT+02:00 AndiG88 <notifications@github.com>:

> *I propose this instead of the tag shop=travel_agency because you can not
> remove goods for sale from these premises, rather they sell services which
> you receive elsewhere.*
>
> Sounds like that's exactly what it is.
>

See shop: "A place selling retail products or services." (SERVICES)
I agree that the office tag description does not contain what I had thought
it did and what seemed to be consensus on various mailing lists (typically
appointment required, can be "backoffice-offices", access for clients not
required) but does rather create an overlap with shop (short definition: "A
place of business, similar to shops." -> no useful distinction, longer
description, 1st sentence: "A place predominantly selling services." ->
complete shop overlap).

Still, it doesn't make sense to have 2 tags for the same thing, and remain
with another feature not mappable (a back office without retail clients
where people work on managing / creating voyages / trips, doing accountancy
etc.). Well, maybe that would be office=tour_operator

**Comment by kocio-pl** [comment]
That's exactly why proposed 2) - a palm picture is nice, but I want OSM to be more universal whenever it's possible. Is it working or maybe different metaphore or visual details could be used instead?

Travel agency is not less a shop than ticket shop (shop=ticket): you also buy tickets, but they are just a convenient way for selling services (like concerts or other venues) really. I find it not a tagging issue (and if yes, it's rather compulsive categorizing, because we rather don't tag "travel_agent=yes"), it's just the twisted fact of life. =} I guess "shop" is a namespace including all the retail, so it should be as good as the office. 

I would render both then, since none of them is an error.
