### ISSUE TITLE
Add special rendering for shop=greengrocer

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1410]
We should start rendering shop=greengrocer, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/greengrocer.svg

[It was proposed in meta-issue #1402]

**Comment by kocio-pl** [comment]
I tried to port French icon (because it's just great: ![greengrocer-14](https://cloud.githubusercontent.com/assets/5439713/7429884/23fea75a-f00a-11e4-8e6e-0e0f21421a80.png)) to 14x14 px with limited success - in the Inkscape it looks OK, but [on the GitHub preview](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-greengrocer/symbols/greengrocer-14.svg) it's small. Could somebody more experienced - @nebulon42 ? - check if it's technically correct?

**Comment by nebulon42** [comment]
The file is basically ok, but I would use Plain SVG instead Inkscape SVG. IMO especially the leaves and the stem are not aligned enough. I would make the stem more wide and connect it to the fruit, maybe leaving out one of the leaves would be better, too.

**Comment by kocio-pl** [comment]
What about now? ![greengrocer-14](https://cloud.githubusercontent.com/assets/5439713/7439504/23e8f63e-f07e-11e4-9b28-7cadc974fc5c.png)

**Comment by nebulon42** [comment]
Looks better, yes. Maybe pure black for the fill would be better. Technically there are also some transforms left, which I would get rid of (by ungrouping and fresh positioning), but that's optional I think.

**Comment by kocio-pl** [comment]
I try to learn also those details, so I changed the color to black (I haven't noticed it's not pure black) and ungrouped the elements, but was not aware what to do next to get rid of transforms. You can explain me it if you want, but you can also work with this file yourself. 

Until I'm ready with development environment I will leave the icons as they are probably, because I already can edit and create them (more or less) correct, so it's time to learn testing and making correct PRs to close some of the issues.

**Comment by nebulon42** [comment]
I noticed that after ungrouping you just have to save and the main shape is fine then.

However, I noticed a few other things. If you look in the code (open the file with a text editor) you have an additional unnecessary rectangle of width/height 8px in it and also some empty group (<g>) after it. You can get rid of the group enclosing the two rectangles too. The canvas rectangle should have 14px width/height and be positioned at (0,0). Also it is important that this rectangle has `visibility:hidden` (your group was taking care of that by using `display: none`) in its style attribute, no need for stroke (`stroke: none`).

**Comment by kocio-pl** [comment]
Ok, that was too difficult for me, so I made a simple hack and took a clean canvas from a different icon. Looks like it was a clever move, because file is now smaller, more readable and the preview in GitHub is correct too. I was not sure if copy-paste would work here, but that ensures me it's legitimate trick when dealing with twisted code - I don't plan to become an expert on SVG XML! =}

Thanks a lot for your help! I feel pretty safe now about drawing vector pixel-aligned OSM icons, even if my design skills are just basic here.

**Comment by kocio-pl** [comment]
I guess this icon can be also used for [shop=farm](http://wiki.openstreetmap.org/wiki/Tag:shop=farm), since the difference is location rather than stock.

**Comment by kocio-pl** [comment]
@nebulon42 Your [Osmic version](https://github.com/nebulon42/osmic/blob/master/shop/greengrocer-14.svg) is not worse than this one (both are nice and readable for me) but it's more coherent with some other icons you've already committed to default map style, so maybe you want it to make a PR?

If you work with other shapes I try to design, just let us know. I don't like some of them and will try hard to make my version easier to recognize (visually all of them are interesting at least for me), but that's minority - I'd like to spend more time on drawing missing shapes than just on doubling your icons .

**Comment by nebulon42** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/pull/1569#issuecomment-105422844. Currently, I do not plan any new shapes, but I might start re-drawing shapes when I look at them in detail, can't help that. I will notify you if there's an alternative shape I did in the future.

**Comment by kocio-pl** [comment]
I see, that's the same feel of urgency I had with a kiosk icon, probably. =}}} 

Thanks, that will do - for me another shape to consider is a good thing.
