### ISSUE TITLE
Add special rendering for shop=mobile_phone

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1412]
We should start rendering shop=mobile_phone, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/mobile_phone.svg

[It was proposed in meta-issue #1402]

**Comment by nebulon42** [comment]
[mobile-phone-18.svg](https://github.com/nebulon42/osmic/blob/master/shop/mobile-phone-18.svg): ![mobile-phone-18](https://cloud.githubusercontent.com/assets/3531092/6778209/03c1ddb8-d151-11e4-87f2-6ca13513081c.png)

**Comment by kocio-pl** [comment]
New model with the bigger screen - great! ;-P

**Comment by HolgerJeromin** [comment]
phones does not have an antenna anymore, but it is useful. Its no iPod :-)

**Comment by nebulon42** [comment]
Apparently closing with the commit in #1493 did not work. Should be closed.
