### ISSUE TITLE
Add special rendering for shop=copyshop

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1413]
We should start rendering shop=copyshop, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/copyshop.svg

[It was proposed in meta-issue #1402]

**Comment by kocio-pl** [comment]
My simple proposition (again the original is too detailed to edit it):
1) ![copyshop-14-1](https://cloud.githubusercontent.com/assets/5439713/8070874/1f2573c0-0f05-11e5-97fd-1f5dda7d4837.png)

**Comment by daganzdaanda** [comment]
It does the job, I think.

**Comment by matkoniecz** [comment]
Rejected in #1615 (at least for now).
