### ISSUE TITLE
Add special rendering for shop=toys

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1414]
We should start rendering shop=toys, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/toys.svg

[It was proposed in meta-issue #1402]

**Comment by kocio-pl** [comment]
I had to edit the French version to be better pixel-aligned, but I start with this idea:
1) ![toys-14-2](https://cloud.githubusercontent.com/assets/5439713/7616148/a851a0b0-f9a2-11e4-903a-823d390b735e.png)

**Comment by kocio-pl** [comment]
Another take:
2) ![toys-14-3](https://cloud.githubusercontent.com/assets/5439713/7653361/8c0c0c46-fb15-11e4-96bc-325477a75cab.png)

**Comment by matkoniecz** [comment]
2 looks like a turnip, 1 seems OK.

**Comment by dieterdreist** [comment]
2015-05-13 19:04 GMT+02:00 kocio-pl <notifications@github.com>:

> I had to edit the French version to be better pixel-aligned, but I start
> with this idea:
> 1) [image: toys-14-2]
> <https://cloud.githubusercontent.com/assets/5439713/7616148/a851a0b0-f9a2-11e4-903a-823d390b735e.png>
>

this one looks great!
