### ISSUE TITLE
Add special rendering for shop=jewelry

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1415]
We should start rendering shop=jewelry, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/jewelry.svg

[It was proposed in meta-issue #1402]

**Comment by dieterdreist** [comment]
> Am 18.03.2015 um 23:09 schrieb kocio-pl <notifications@github.com>:
> 
> We should start rendering shop=jewelry, 
> 


this should be shop=jewellery because all tags are in British English 
>

**Comment by kocio-pl** [comment]
It's still stuck at the proposition level:

http://wiki.openstreetmap.org/wiki/Proposed_features/BE-Spelling_shop%3Djewelry

The usage is like 15996 vs 170, so
1. We can render both versions, since it's quite clear what are they and we're in state of transition.
2. We can render only BE version to accelerate this process.
3. We can render only current version, since it's approved and very popular.

I would pick 1 for now and maybe 2 when proposal is accepted.

**Comment by matkoniecz** [comment]
Or we can wait with prominent rendering until situation is fixed - promoting better tagging scheme is OK but not in situation when it is losing 1 to 100.

**Comment by kocio-pl** [comment]
Sure. I said what I like the most, but for me any option is acceptable, since all have their strengths and weaknesses.

**Comment by pnorman** [comment]
> this should be shop=jewellery because all tags are in British English

Yes - but what it should be is a tagging issue, while what it is is fairly clear.

**Comment by dieterdreist** [comment]
2015-03-20 0:20 GMT+01:00 Paul Norman <notifications@github.com>:

> Yes - but what it should be is a tagging issue, while what it is is fairly
> clear.



yes, but promoting an AE spelling variant by bringing it on the map will
a) set a precedent
b) carve this into stone
c) go against one of the fundamental, generic tagging rules, not just a
specific one

**Comment by math1985** [comment]
> a) set a precedent

We already do render railway=subway rather than UK English railway=metro or railway=underground. In UK English, a subway is a pedestrian underpass AFAIK.

Other common US English tags are highway=elevator (should be highway=lift), and sport=soccer (should be sport=football). I'm sure there will be more.

**Comment by nebulon42** [comment]
[jewellery-18.svg](https://github.com/nebulon42/osmic/blob/master/shop/jewellery-18.svg): ![jewellery-18](https://cloud.githubusercontent.com/assets/3531092/6778163/c0bd674e-d150-11e4-8aed-0b9fe42fb525.png)

**Comment by jongleur1983** [comment]
What's missing for this to be done? A style patch only?
I don't think extensive tests would be required as it's basically the same as other shop icons that already exist.

**Comment by nebulon42** [comment]
On my list. But as I wrote in https://github.com/gravitystorm/openstreetmap-carto/issues/1402#issuecomment-85010118 I'm waiting for maintainers approvement as I don't want to end up with a lot of PRs that have no chance of getting merged.
