### ISSUE TITLE
Add special rendering for shop=computer

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1416]
We should start rendering shop=computer, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/computer2.svg

[It was proposed in meta-issue #1402]

**Comment by kocio-pl** [comment]
Just a basically corrected version:
1) ![computer-14-2](https://cloud.githubusercontent.com/assets/5439713/8069586/c4219f98-0efb-11e5-99ca-8ab23a2e3c2e.png)

**Comment by math1985** [comment]
I'm very busy at the moment, sorry for my lack of comments. I will get back to the PRs as soon as possible.

**Comment by kocio-pl** [comment]
Thanks for the message.

**Comment by daganzdaanda** [comment]
I'd take 2) or 3), even if that leaves a big "hole" in the icon.
