### ISSUE TITLE
Add special rendering for shop=fishmonger and shop=seafood

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1417]
We should start rendering shop=fishmonger and shop=seafood, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/fish.svg

[It was proposed in meta-issue #1402]

**Comment by kocio-pl** [comment]
I guess French original is too small and complicated for our needs, so I made a simple fish image:
1) ![seafood-14-2](https://cloud.githubusercontent.com/assets/5439713/8070648/19cc5850-0f03-11e5-83e0-782a469dd288.png)

**Comment by daganzdaanda** [comment]
Yes, that should do it.
