### ISSUE TITLE
Add special rendering for shop=hifi

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1418]
We should start rendering shop=hifi, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/hifi.svg

[It was proposed in meta-issue #1402]

**Comment by pmailkeey** [comment]
I don't like "hifi" as it's a bit precise - would prefer a good equivalent of "multimedia entertainment" - covering TVs, hifi, even computery games electronics / consoles.

**Comment by kocio-pl** [comment]
Probably, but the tag is already used and we have [almost 6k uses](http://taginfo.openstreetmap.org/tags/?key=shop&value=hifi), so rendering of shop=hifi would be rational.

**Comment by math1985** [comment]
> I don't like "hifi" as it's a bit precise - would prefer a good equivalent of "multimedia entertainment" - covering TVs, hifi, even computery games electronics / consoles.

I agree.

Typical hifi shop: http://www.bang-olufsen.com/en

Unfortunately, this is not the right place to do something about it - try the tagging mailing list.

**Comment by dieterdreist** [comment]
> Am 30.04.2015 um 15:17 schrieb math1985 <notifications@github.com>:
> 
> I don't like "hifi" as it's a bit precise - would prefer a good equivalent of "multimedia entertainment" - covering TVs, hifi, even computery games electronics / consoles.
> 
> I agree.
> 


"hifi" is a different kind of shop, it doesn't include all kind of multimedia entertainment or computer games.

Cheers 
Martin

**Comment by kocio-pl** [comment]
My icon proposition for shop=hifi: ![hifi-14](https://cloud.githubusercontent.com/assets/5439713/7422433/19f048cc-ef8d-11e4-9fde-ebd977133376.png)

**Comment by pmailkeey** [comment]
I'll take your icon and raise you:

![image](https://cloud.githubusercontent.com/assets/11827386/7422532/8feb6500-ef85-11e4-8890-23d82222c695.png)

This icon can be used for a proper hifi shop - that has hifi TVs, DVD players and hifi computer games. Let's just call it an AV shop - that's simple and understandable.

This message, by the way, is in in HD with 5.1 surround sound.

**Comment by kocio-pl** [comment]
Funny. =} 

Maybe you mean shop=electronics? ([icon for it in Osmic](https://github.com/nebulon42/osmic/blob/master/shop/electronics-14.svg))

**Comment by pnorman** [comment]
Icons need to fit within 16x16 unless there's some exceptional reason.

**Comment by pmailkeey** [comment]
Sorry Paul, - looks like you've been caught out by my sense of humour ! 

The speaker icon is fine, it's just the 'hifi' tag I have issues with as it implies audio only and I strongly feel it should imply a wider aspect of the industry - using [Richer Sounds](http://www.richersounds.com/) as a good example.
![image](https://cloud.githubusercontent.com/assets/11827386/7428755/1ef938c2-efee-11e4-8943-881bee4104cd.png)

**Comment by matkoniecz** [comment]
> it's just the 'hifi' tag I have issues with

This should be discussed on wiki or tagging mailing list.

**Comment by pmailkeey** [comment]
Cheers, will do.

**Comment by kocio-pl** [comment]
@pmailkeey : I guess if it's mainly audio, it's hifi and this icon is adequate (we may also try headphones), but if it's more than this, it should be tagged as shop=electronics. It's purely tagging problem.

The problem with rendering multi-shops is we have to use something single and - well - iconic for such a variety of things. I guess loudspeakers for "hifi" are both representative and easy to recognize by the simple silhouette. In case of "electronics" I advised using some generic, old kind of it, like TV or radio, because we may need some other, like computer or phone, to show specialized shops.
