### ISSUE TITLE
Add special rendering for shop=musical_instrument

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1420]
We should start rendering shop=musical_instrument, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/musical_instrument.svg

[It was proposed in meta-issue #1402]

**Comment by nebulon42** [comment]
This icon is already in use for `amenity=nightclub`.

**Comment by kocio-pl** [comment]
I think it could be more specific - like guitar or piano. But wasn't it disco ball that we were trying to apply here or was it some other tag?

**Comment by kocio-pl** [comment]
My proposition:
[1)](https://github.com/kocio-pl/openstreetmap-carto/blob/icons/symbols/musical_instrument-14-4.svg) ![musical_instrument-14-4](https://cloud.githubusercontent.com/assets/5439713/8336080/1f62a080-1aa2-11e5-8314-2ebde9d24400.png)

**Comment by lest69** [comment]
I know what it's supposed to be, but I'm concerned it could be confused with other things (shoe, ice skate, cleats, etc.). Can you maybe try a guitar?

**Comment by kocio-pl** [comment]
That was what I started with, but the result was rather poor, so I'm still trying:
2) ![musical_instrument-14-1](https://cloud.githubusercontent.com/assets/5439713/8354360/dabfb426-1b47-11e5-8580-79739e026ff7.png)
3) ![musical_instrument-14-3](https://cloud.githubusercontent.com/assets/5439713/8354373/e47098b4-1b47-11e5-965e-ad462aad7c20.png)

**Comment by kocio-pl** [comment]
Another take:
4) ![musical_instrument-14-5](https://cloud.githubusercontent.com/assets/5439713/8360629/36a44a38-1b6e-11e5-93b2-d769d8204803.png)

**Comment by kocio-pl** [comment]
Hm, maybe saxophone would do...

@nebulon42 Do you have any ideas or actual drafts for this shop type?

**Comment by matkoniecz** [comment]
3) is the best from proposed ones

**Comment by nebulon42** [comment]
I have no special ideas. I think any musical instrument could work. 2 or 3 maybe, with some tweaking.

**Comment by daganzdaanda** [comment]
A trumpet is a good symbol, I think. Number 3) has no piston valves in the middle, maybe they could be added to reduce the "hole".

**Comment by kocio-pl** [comment]
So the popular opinion is clear - I will try to work with the trumpet.

**Comment by kocio-pl** [comment]
All about details, which are visible mostly at higher resolutions, and slightly better with current icon size: 
7) ![musical_instrument-14-24](https://cloud.githubusercontent.com/assets/5439713/9063689/071d1554-3ac9-11e5-99cf-9aec47f3b8f3.png)

**Comment by matkoniecz** [comment]
I think that 3) is still the best (7 started to look like scheme of electronics, with diode on the left and resistor on the bottom).

**Comment by kocio-pl** [comment]
Maybe I have tried too hard to make everything visible (piston valves left untouched):
8) ![musical_instrument-14-25](https://cloud.githubusercontent.com/assets/5439713/9074968/e98426e4-3b0f-11e5-9586-28f23d96c2df.png)
9) ![musical_instrument-14-26](https://cloud.githubusercontent.com/assets/5439713/9074974/f19224bc-3b0f-11e5-9abc-96487df65ee7.png)

**Comment by matkoniecz** [comment]
to keep also 3) visible:

3) ![musical_instrument-14-3](https://cloud.githubusercontent.com/assets/5439713/8354373/e47098b4-1b47-11e5-965e-ad462aad7c20.png)
8) ![musical_instrument-14-25](https://cloud.githubusercontent.com/assets/5439713/9074968/e98426e4-3b0f-11e5-9586-28f23d96c2df.png)
9) ![musical_instrument-14-26](https://cloud.githubusercontent.com/assets/5439713/9074974/f19224bc-3b0f-11e5-9abc-96487df65ee7.png)

**Comment by matkoniecz** [comment]
3) and 9) are the best.

**Comment by kocio-pl** [comment]
What about piston valves?
