### ISSUE TITLE
new trees are blocking icons and labels

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1425]
New trees are prettier but this unintended side-effect has some poor results.

Comparison of v2.28.1 and current master with fixed cave_entrance icon (#1424)
https://cloud.githubusercontent.com/assets/899988/6742797/11332f9e-ce93-11e4-9bbf-dfbc1f9c66c2.png - see disappearing cave_entrance in the center from z16.

**Comment by math1985** [comment]
Old trees also had the possibility of blocking labels, but with the new rendering this problem is more likely.

Moving the tree layer two layers down should fix this problem.

**Comment by pnorman** [comment]
[`marker-ignore-placement`](https://github.com/mapbox/carto/blob/master/docs/latest.md#marker-ignore-placement-boolean) should fix it.

**Comment by dieterdreist** [comment]
2015-03-20 3:03 GMT+01:00 math1985 <notifications@github.com>:

> Old trees also had the possibility of blocking labels, but with the new
> rendering this problem is more likely.
>
> Moving the tree layer two layers down should fix this problem.
>


IMHO "ordinary" trees are worth an exception: they should be rendered very
early but it should be possible to have all other stuff overlap them (i.e.
see them like a part of the "landcover" layer, render them soon after the
areas). Only particular trees (those that get a name rendered or have a
special icon) should be treated like a regular POI.
