### ISSUE TITLE
more attractive water color

### ISSUE THREAD

**Issue by jotpe** [gravitystorm/openstreetmap-carto#1427]
I don't like blue color of our water areas. It looks a kind of dirty. Maybe a slightly stronger color can improve this. I think that water color and water gradient style of Google Maps, is a good example for a nicer look.

What do you think?

**Comment by joakimfors** [comment]
I find Hike & Bike maps water style to be pretty nice: http://hikebikemap.org/

**Comment by jotpe** [comment]
I agree.

**Comment by matkoniecz** [comment]
See also #1781

**Comment by kocio-pl** [comment]
Should we close it as a duplicate, since most of the discussion is going on #1781 now?
