### ISSUE TITLE
render siren icons

### ISSUE THREAD

**Issue by jotpe** [gravitystorm/openstreetmap-carto#1428]
It would be beautiful to see emergency=siren icons on the openstreetmap.

Regards Johannes

**Comment by matkoniecz** [comment]
For start, it is used less than 1000 times and it is not a some type of special case where high usage is impossible.

**Comment by pnorman** [comment]
Pluses: Documented, not a tag primarily from a single user.

Minuses: Very low usage, no editor support.

Also, emergency isn't in the DB so this would have to wait regardless.

**Comment by jotpe** [comment]
now its > 1000

**Comment by jotpe** [comment]
now its > 1700

**Comment by HolgerJeromin** [comment]
It should be rendered in openfiremap but I am unsure if it is good here.

**Comment by kocio-pl** [comment]
I have also some doubts. It would need some icon (probably rather easy task), but still it is not something too visible and needed by people on the street. Hard to tell what should take precedence in this case. Probably AED rescue sets or surveillance cameras would be needed more directly. On the other hand it may be useful as a general feedback loop and on z19+ there are not many features on the screen, so this wouldn't make a visual mess anyway.

**Comment by HolgerJeromin** [comment]
In Aachen, Germany nearly all 42 (all mapped by me :-) ) are on roofs of public buildings (schools, University, town hall ) . So they are pretty likely to be not rendered due to collision. 
Another reason for a specialised overlay map.

**Comment by jotpe** [comment]
+1 for the feedback loop.

In Cologne a lot of siren masts are over 20 m high. They are good orientation points.

I think the collision can be neglect, in Aachen the ratio is ~ 0.1 %.

**Comment by HolgerJeromin** [comment]
can you explain what you mean of the 0.1% ratio in Aachen?  At least these Aachen sirens will probably not be rendered:
http://www.openstreetmap.org/node/3447146299
http://www.openstreetmap.org/node/3497243191
http://www.openstreetmap.org/node/3449230297
http://www.openstreetmap.org/node/3497243185

**Comment by kocio-pl** [comment]
@jotpe Masts are important orientation points indeed and they may be enough to be rendered.
