### ISSUE TITLE
Railway yard tracks suddenly stopped rendering

### ISSUE THREAD

**Issue by jc86035** [gravitystorm/openstreetmap-carto#1442]
See https://www.openstreetmap.org/way/219993787#map=19. There are supposed to be about 15 rail yard tracks there, but they stopped getting rendered for some reason. (Tags: <code>railway=rail</code>, <code>service=yard</code>.) However, tracks with <code>railway=subway</code>, <code>service=yard</code> are <a href=https://www.openstreetmap.org/way/207717060>still rendered</a>.

**Comment by pnorman** [comment]
confirming. possibly #1373 that regressed this?

**Comment by pnorman** [comment]
80a990a9e4706f09a04575165db4f076702ac613 from #1395
