### ISSUE TITLE
Add special rendering for shop=kiosk

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1459]
We should start rendering shop=kiosk (over 45k objects on taginfo), probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/kiosk.svg

[It was proposed in meta-issue #1402]

**Comment by nebulon42** [comment]
[kiosk-18.svg](https://github.com/nebulon42/osmic/blob/master/shop/kiosk-18.svg): ![kiosk-18](https://cloud.githubusercontent.com/assets/3531092/6779943/14884b68-d161-11e4-94c6-22a66aca0fd9.png)

**Comment by kocio-pl** [comment]
I could not recognize it probably (for me it looks now like an oven covered with with bananas... =} ). I'm not sure what to do, but maybe just removing the top bar could help? I can think also that the roof part can be made simpler (just those hanging elements?).

BTW: I'd like to start creating icons myself with Inkscape. What are the most important tips for making them pixel-aligned?

**Comment by nebulon42** [comment]
For a start you could take the kiosk icon and try to improve it. :) Pixel-aligned means that the nodes of the path are snapped to the grid. Bring up the grid in Inkscape by pressing '#' and compare where the nodes are located. See also #632.

**Comment by kocio-pl** [comment]
I may start with the clinic, since I'm not too familiar with vector graphics. =} 

I think basic guidelines regarding pixel-aligning could be added here:
https://github.com/nebulon42/osmic/blob/master/CONTRIBUTING.md#technical-aspects

**Comment by kocio-pl** [comment]
My proposition for kiosk: https://github.com/kocio-pl/openstreetmap-carto/blob/shop-kiosk-icon/symbols/kiosk-14.svg

**Comment by math1985** [comment]
I think @nebulon42's version is clearer.

**Comment by matkoniecz** [comment]
I prefer @kocio-pl version so it may be cultural thing (typical kiosk style in a given area). Note that I tested neither on a map, it is based just on looking at svgs.

**Comment by kocio-pl** [comment]
I was not fully satisfied with my take, it was just a first try to make something more simple than Osmic. @nebulon42 has a lot of creative ideas when drawing the icons, but sometimes it hurts recognizability too bad for my taste and kiosk was beyond my power to stay calm. ;-)

Here is my second try, I guess more distinct from the general building: https://github.com/kocio-pl/openstreetmap-carto/blob/shop-kiosk-icon-rectangle/symbols/kiosk-14.svg 
![kiosk-14](https://cloud.githubusercontent.com/assets/5439713/7369555/1d015e74-edb3-11e4-8029-6c69d8ee7af7.png)

**Comment by kocio-pl** [comment]
Some more sketches - this time inspired by French icon: 
1) ![kiosk-14-person](https://cloud.githubusercontent.com/assets/5439713/7375358/542105f6-edd8-11e4-9fe3-aec45f34edd9.png) 
2) ![kiosk-14-person-osmic](https://cloud.githubusercontent.com/assets/5439713/7375366/68326b02-edd8-11e4-80c1-9d8ab43fa74d.png) 
3) ![kiosk-14-person-osmic-2](https://cloud.githubusercontent.com/assets/5439713/7375374/7207cf3c-edd8-11e4-8b78-a1f0eb5d608a.png)

**Comment by pnorman** [comment]
I'd rather not render using any of those. They look very shelter-like to me.

**Comment by kocio-pl** [comment]
So next delivery is less shelter-like and use the window metaphor instead:
7) ![kiosk-14-person-window](https://cloud.githubusercontent.com/assets/5439713/7433058/e5283c48-f02d-11e4-94b8-a0ebdbb48e92.png)
8) ![kiosk-14-person-window-2](https://cloud.githubusercontent.com/assets/5439713/7433062/ecd19ac0-f02d-11e4-917a-89fe99090f6e.png)
9) ![kiosk-14-person-window-3](https://cloud.githubusercontent.com/assets/5439713/7433066/f3912506-f02d-11e4-83ea-4bc8cbd50f93.png)
10) ![kiosk-14-person-window-4](https://cloud.githubusercontent.com/assets/5439713/7433070/fa92fa5a-f02d-11e4-870a-6c5650518ce5.png)
11) ![kiosk-14-person-window-5](https://cloud.githubusercontent.com/assets/5439713/7433183/0eae38c8-f02f-11e4-9ca2-96859f5cb8c7.png)

What about them? I don't think they are ready for instant use, but maybe one of them is a reasonable base for modifications or there are some good elements that can be used?

For me 4) is still preferable, because we want to show it's a stand-alone building so it should look a bit like a shelte. 5) is good enough, but for me it's rather ticket window/box office (shop=ticket, 1 471 uses -> 30x less important =} ).

**Comment by kocio-pl** [comment]
Different metaphor now (should be suitable also for shop=newsagent which has another big number - 8 788 - of uses):
12) ![newspaper-14-2-12](https://cloud.githubusercontent.com/assets/5439713/7437574/c79fb482-f058-11e4-88d6-d9db2ce92f0e.png)
13) ![newspaper-14-3-13](https://cloud.githubusercontent.com/assets/5439713/7437578/cfb6f68a-f058-11e4-881a-77869eeb187f.png)
