### ISSUE TITLE
Displaying way and area locations

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#1464]
About a node, OSM.org displays   Location: 50...., 5....
How about displaying the ends of a way, in direction order
Location: 50...., 5.... (start)
Location: 50...., 5.... (end)
And BBOX for an area (increasing values)
Location: 50...., 5.... (bottom left)
Location: 50...., 5.... (top right)
Location: 50...., 5.... (???)
???: center(?) or admin_centre

Cheers!

**Comment by HolgerJeromin** [comment]
This is a website issue. Openstreetmap carto is the wrong repository for this request.

**Comment by matkoniecz** [comment]
Also, it is not clear what is expected here. 

This repository is about one map style, not about application powering http://www.openstreetmap.org 

Maybe https://github.com/openstreetmap/openstreetmap-website/ would be fitting for a feature request but I recommend making more understandable what is wanted.
