### ISSUE TITLE
Icon for amenity=ice_cream

### ISSUE THREAD

**Issue by seebk** [gravitystorm/openstreetmap-carto#1479]
amenity=ice_cream is curently not rendered in the map. Can this be changed?

**Comment by kocio-pl** [comment]
We should render it, since it's very popular ([4 880 uses on taginfo](http://taginfo.openstreetmap.org/tags/amenity=ice_cream)), but we don't have the icon for it now for a start.

I wonder however if we should also render shop=ice_cream? It's far less used, but still [almost thousand](http://taginfo.openstreetmap.org/tags/shop=ice_cream) such tags exist in our database.

**Comment by dieterdreist** [comment]
2015-04-13 11:19 GMT+02:00 kocio-pl <notifications@github.com>:

> We should render it, since it's very popular (4 880 uses on taginfo
> <http://taginfo.openstreetmap.org/tags/amenity=ice_cream>), but we don't
> have the icon for it now for a start.
>
> I wonder however if we should also render shop=ice_cream? It's far less
> used, but still almost thousand
> <http://taginfo.openstreetmap.org/tags/shop=ice_cream> such tags exist in
> our database.
>

similar to amenity=ice_cream there is also amenity=cafe (and maybe
amenity=fast_food) with cuisine=ice_cream (6836 uses currently:
http://taginfo.osm.org/tags/cuisine=ice_cream#overview ), but I am not sure
if we have the cuisine key currently. AFAIK this is not similar to
shop=ice_cream (which is AFAIK a take-away place and not a place with
seats).

**Comment by kocio-pl** [comment]
We could reuse the same icon with different standard color: brown for cafe, violet for shop/amenity. That would be simple and coherent for me.

Most probably we don't have cuisine key yet, but if we agree on that, it would be just a matter of time (i.e. database refresh).

**Comment by seebk** [comment]
I am no expert in icon design, but I wanted to give it a try:
https://cloud.sebastiankraft.net/index.php/s/9q1JQnpwzYSzCPS

If you like it feel free to use or modifiy it!

**Comment by seebk** [comment]
And here already is another one
http://osm-icons.org/wiki/File:12077.svg

**Comment by kocio-pl** [comment]
Could you try to rework it according to [this draft](https://github.com/nebulon42/osmic/blob/master/CONTRIBUTING.md#technical-aspects)? That would be more consistent with what we implement in OSM lately.

**Comment by sommerluk** [comment]
cuisine=* is currently not in the database.

I’m not sure if it’s a good idea to support three different taggings for (almost) the same thing. In any case, I think first of all the most common variant (cuisine=ice_cream) should get support – before maybe adding more variants later.

**Comment by dieterdreist** [comment]
2015-04-16 9:03 GMT+02:00 Lukas Sommer <notifications@github.com>:

> I’m not sure if it’s a good idea to support three different taggings for
> (almost) the same thing



at least shop=ice_cream (typically take away, no real seating possibility,
no table service) is different from amenity=cafe and cuisine=ice_cream
(table service, seating possibility)  in a way similar than shop=alcohol to
amenity=pub. We also distinguish between a pub and a restaurant and a cafe,
so why wouldn't we want to make this distinction also for ice cream? Not
sure about amenity=ice_cream, could be both.

See these pictures for reference:
http://media.holidaycheck.com/data/urlaubsbilder/images/82/1156947037.jpg
(not sure if amenity=ice_cream or shop=ice_cream, but for sure its not a
cafe)
http://upload.wikimedia.org/wikipedia/de/thumb/1/17/Barchfeld_eisdiele.JPG/800px-Barchfeld_eisdiele.JPG
(amenity=cafe)
http://foodieinternational.com/wp-content/uploads/2012/04/IMG_4571-1024x681.jpg
(shop=ice_cream if there is no table service).

**Comment by sommerluk** [comment]
> at least shop=ice_cream (typically take away, no real seating possibility,
> no table service) is different from amenity=cafe

I understand the difference between a restaurant-like thing with tables and a simple take-away.

But the question is if these keys are really used according to this difference. The wiki page of amenity=ice_cream presents the cuisine=ice_cream version as an alternitive tagging with the same meaning. shop=ice_cream hasn’t it’s own wiki page – and what you can read at the wiki page of amenity=ice_cream about shop=ice_cream also doesn’t make a clear difference. Furthermore, the text “over the counter“ isn’t part of all translations. So I doubt that in practice mappers make a meaningfull difference between these three tagging variants.

I think it would be nice to have a clear distinction in the database, but I doubt that today this distinction is in the database.

**Comment by kocio-pl** [comment]
Would it do any bad to have alternative takes (if both are valid, of course)? I'm not sure rendering should prefer any tagging scheme in such cases.

**Comment by dieterdreist** [comment]
2015-04-16 12:04 GMT+02:00 Lukas Sommer <notifications@github.com>:

> I understand the difference between a restaurant-like thing with tables
> and a simple take-away.
>
> But the question is if these keys are really used according to this
> difference.
>


you can question this for every tag :-)


> The wiki page of amenity=ice_cream presents the cuisine=ice_cream version
> as an alternitive tagging with the same meaning. shop=ice_cream hasn’t it’s
> own wiki page – and what you can read at the wiki page of amenity=ice_cream
> about shop=ice_cream also doesn’t make a clear difference.
>

it's a wiki, you can change it.


> Furthermore, the text “over the counter“ isn’t part of all translations.
>


"translations" are translations, the definition is on the English page.
Many translations for many tags are out of sync, I strongly encourage all
mappers to generally rely on the English version if possible (i.e. if they
understand it). The translations out of sync should be updated to the
content on the English page, but this is wishful thinking, I guess we are
lacking manpower.


> So I doubt that in practice mappers make a meaningfull difference between
> these three tagging variants.
>
> I think it would be nice to have a clear distinction in the database, but
> I doubt that today this distinction is in the database.
>

on which experience (country?) do you base this judgement? Maybe you can
write a message to their local mailing list and ask them to help cleaning
this up? Reducing what will get rendered will for sure not help to
differentiate the (in the real world existing) occurences.

FWIW, I have in a few occasions also used "sells:ice_cream=yes/industrial"
as an attribute for other places that also sell ice cream (like newspaper
agent, kiosk, convenience store, bar, ...)

**Comment by nebulon42** [comment]
I could not resist to give it a try: https://github.com/nebulon42/osmic/blob/master/shop/ice-cream-14.svg

**Comment by kocio-pl** [comment]
Looks good for me.

**Comment by seebk** [comment]
Yes, that probably better fits the style of the other symbols.  I would vote for using this icon for amenity=ice_cream as well as shop=ice_cream as described in the wiki.

**Comment by kocio-pl** [comment]
OK, so we have the icon and we have >5k such items in the database, so above any reasonable limit. I would also add shop=ice_cream (with shop color) which is currently only 931, because the difference is not clear for mappers and users. Should I prepare such PR?

**Comment by nebulon42** [comment]
That would be great.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 24.06.2015 um 15:09 schrieb kocio-pl <notifications@github.com>:
> 
> OK, so we have the icon and we have >5k such items in the database, so above any reasonable limit. I would also add shop=ice_cream (with shop color) which is currently only 931, because the difference is not clear for mappers and users. Should I prepare such PR?
> 

+1, when possible, cuisine=ice_cream (7185 objects) would be nice as well (rendered like amenity)

**Comment by nebulon42** [comment]
Cusine is not in the rendering database yet, and would have to be dealt with later.

**Comment by kocio-pl** [comment]
Cuisine tag should be added to [this issue](https://github.com/gravitystorm/openstreetmap-carto/issues/1504) probably to take effect. 

BTW: does anybody knows what is the current state of preparation to database re-import? I asked there but no answer was given.

**Comment by HolgerJeromin** [comment]
> Cuisine tag should be added

Not it should not
https://github.com/gravitystorm/openstreetmap-carto/issues/1504#issuecomment-97715323

**Comment by kocio-pl** [comment]
I still don't get the whole hstore thing, but that'd be nice. However I guess - this way or another - we still depend on database re-import and it's not clear when could it be and how far we are from this point, so cuisine=ice_cream rendering has to wait...
