### ISSUE TITLE
landuse=residential renders on top of amenity=parking

### ISSUE THREAD

**Issue by bubalici** [gravitystorm/openstreetmap-carto#1481]
Not sure if this is the proper place to ask about this... looks like a bug to me.
The landuse is rendered above the parking:
https://www.openstreetmap.org/#map=19/37.44165/24.94491

I guess it's a bug and not a style change because close by it shows the parking lots above landuse:
https://www.openstreetmap.org/#map=19/37.44101/24.93708

**Comment by HolgerJeromin** [comment]
The areas are sorted by size. There were similar issues with [parks](https://github.com/gravitystorm/openstreetmap-carto/issues/1136#issuecomment-64291374) which were closed as we can not do much against it.

**Comment by matkoniecz** [comment]
Also, in that case it is a tagging error. landuse=highway (or lack of landuse) would be a better tagging.

**Comment by dieterdreist** [comment]
2015-04-14 10:19 GMT+02:00 Mateusz Konieczny <notifications@github.com>:

> Also, in that case it is a tagging error. landuse=highway (or lack of
> landuse) would be a better tagging.


yes, this clearly isn't residential landuse, neither the roundabout nor the
parking in front of the commercial landuse. Either it is completely public
land or the parking is associated to the (and IMHO to be tagged as)
landuse=commercial.
