### ISSUE TITLE
Add rendering natural=spring on area

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#1482]
Currently springs are only rendered with an icon+name, even when they are mapped as an area.
Small example: http://www.openstreetmap.org/way/206317365
however springs of larger rivers often seep through the sand on a larger area, so this tagging is valid. 

It would probably be simple to fill the area with water colour, however it might need to be considered when changing the icon in #1384. 

Alternatively, the spring area could be filled with a pattern of spring icons, similar to wetland. 

Stats: Node: 58K, area+relation: 690

**Comment by matkoniecz** [comment]
> however springs of larger rivers often seep through the sand on a larger area

I would consider such area as wetland, and I would tag it this way - what would result in expected rendering (though it would require two areas, one for natural=spring, one for natural=wetland).

**Comment by kocio-pl** [comment]
Is this issue to be closed, as you have suggested, or maybe it's something to be considered in https://github.com/gravitystorm/openstreetmap-carto/issues/325?

**Comment by Tomasz-W** [comment]
@kocio-pl this should be closed for the reasons above.

**Comment by polarbearing** [comment]
Why is this being closed so suddenly?
I don't see reasons above. I see one argument from @matkoniecz  regarding one type of spacial spring, in wetland. There are other types of springs, such as the water coming up from the ground, already forming a body of water. You would not consider that as 'wetland'.

**Comment by kocio-pl** [comment]
Sorry, for me it's a problem about old discussions without reaching conclusions. There may be many valid arguments, but in the end it's decision what to do. Moreover it's hard for me to imagine such area - could you give an example?

**Comment by Tomasz-W** [comment]
As I know, we map water areas as natural=water (or natural=wetland). 'Natural=spring' tag should be added to the first node of a river/ stream way, not water area. 
I've checked some cases in Overpass turbo, and most of them it's just bad tagging.

**Comment by polarbearing** [comment]
Can you give examples and say why you consider the tagging wrong?

Springs can be quite large, have a look at https://en.wikipedia.org/wiki/Big_Spring_%28Missouri%29 for one that can spit out up to 57 cubical meters per second! Why does it not deserve an area? 

Whether natural=spring on an area should imply being a body of water, or needs an extra outline around, is subject to further discussion.

**Comment by kocio-pl** [comment]
This example sounds convincing for me. Since there's also a discussion, I reopen this ticket.

If we should render such area, how should we do it? Just like a node spring or maybe different?

**Comment by Tomasz-W** [comment]
Actually, it can be tagged in two ways - the one which I described above, and also as natural=spring area (anyway first node of stream/ river should be connected with spring node/ area)
If we are going to render it, I think it should be just blue water area with spring icon in the middle.

**Comment by imagico** [comment]
For the thousandth time: This is not the place to discuss tagging.

If a spring can be mapped as a polygon is not the issue here.  The issue here is if polygons tagged `natural=spring` should be rendered **differently** compared to a node with this tag.  This likely makes no sense because however you define the outline of a spring (which is hard to do in a verifiable way) this will either qualify as `natural=water` or `natural=wetland` or be part of a larger area that qualifies as such.

**Comment by polarbearing** [comment]
> For the thousandth time: This is not the place to discuss tagging.

Right, but as tagging and rendering are related, it is necessary to point out which things are well defined, and which need further discussion.

**Comment by polarbearing** [comment]
Example of spring tagged on area, after recent refurbishment:
<img width="258" alt="spring-on-area" src="https://user-images.githubusercontent.com/8266355/40691268-5ff0c3a2-63ab-11e8-983d-1c027943492d.png">

Due to #3253, the icon would be invisible if the spring area were mapped as a natural=water body.

**Comment by jeisenbe** [comment]
#3253 was fixed by #3738, so spring icons now render above water areas without problems.

I agree with the comments above https://github.com/gravitystorm/openstreetmap-carto/issues/1482#issuecomment-369214325 - a spring can be mapped as an area of water or a wetland. 

Closed.

**Comment by b-unicycling** [comment]
I don't agree with the solution of tagging them as water, because they lose their property of being a spring that way. People have now tried to solve this by using water=spring, but I thought we were told not to map for the renderer which the solution of tagging them as water bodies absolutely is doing.

**Comment by imagico** [comment]
> I don't agree with the solution of tagging them as water

I don't think anyone has suggested this here.

The problem that mappers need to apply several primary tags with the same key to the same geometry is a common one and not unique to springs - the common technique is to create two features representing the two different concepts (the spring as well as the water covered area/the area of water saturated ground a.k.a. wetland).  This also allows applying secondary tags in a semantically non-ambiguous way.
