### ISSUE TITLE
Add rendering for area:highway on z19(+)

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1483]
We should start rendering some notable microscale elements, such as area:highway. Taginfo says now we have 14.342 such objects worldwide - it's not as much as popular highway keys, but more than a raceway we already render and it's a visible number in itself. Rendering should start from z>=19 (or maybe z>=18?), because this zoom level really shows the problem with linear highway rendering.

**Comment by math1985** [comment]
Duplicate with #180.

**Comment by dieterdreist** [comment]
> Am 16.04.2015 um 01:04 schrieb kocio-pl <notifications@github.com>:
> 
> Rendering should start from z>=19 (or maybe z>=18?), because this zoom level really shows the problem with linear highway rendering.


I'm in favor of rendering them below (before) the key highway, from z17 and higher
