### ISSUE TITLE
Highway areas should be rendered above highway lines

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1484]
Areas for walking (highway=footway+area=yes, highway=pedestrian+area=yes) should be rendered above routing lines there (highway=footway+area=yes, highway=pedestrian+area=yes). Probably other areas (like highway=service) should also be on the top of lines (be it walking or not), because any other highway lines also belong to the routing dept., while on default map we should rather show the real shape if available.

Pedestrian lines are looking the same as pedestrian areas, so this is not a visual problem, but footway lines are red now (and we're not sure how would they look like in the future or when it could change - see https://github.com/gravitystorm/openstreetmap-carto/pull/1327) and make sense for rendering only when we have nothing better (like areas). Otherwise they are meant just for routing purposes, but are useful also for low zooms where we don't want too many computations and details.

**Comment by dieterdreist** [comment]
2015-04-16 12:41 GMT+02:00 kocio-pl <notifications@github.com>:

> Areas for walking (highway=footway+area=yes, highway=pedestrian+area=yes)
> should be rendered above routing lines there (highway=footway+area=yes,
> highway=pedestrian+area=yes). Probably other areas (like highway=service)
> should also be on the top of lines (be it walking or not), because any
> other highway lines also belong to the routing dept., while on default map
> we should rather show the real shape if its available.



can you be more clear what you intent by "routing lines"? IMHO
highway=<road type> should render above and not below
highway=pedestrian/footway + area=yes (i.e. like it is today, I'm fine with
the casing not being above the area).

**Comment by kocio-pl** [comment]
All the highways are areas, of course - treating them as lines is inaccurate and works as a hint for machines how to route or how to make things simple when we want to get rid of details (that's why we use predefined width on lines). However until we start rendering streets areas and crossing areas we have to make compromises when needed and that's why I wrote "probably". The sure thing for me is footway lines should be covered by footway areas, the rest needs to be checked and discussed.

**Comment by dieterdreist** [comment]
2015-04-16 13:30 GMT+02:00 kocio-pl <notifications@github.com>:

> The sure thing for me is footway lines should be covered by footway areas,


I see (was not sure if you were refering to roads crossing squares or in
pedestrian areas, because those do make sense and are needed to be
visible). For those "virtual footways" above pedestrian areas I suggest to
remove them from the data, they do not exist and you do not need them if
you connect the footway areas to the highway network (the worst that can
happen is that you will have small detours, because you will be routed at
the borders instead of crossing the area).

**Comment by kocio-pl** [comment]
I guess that would be too far for now. Highway areas (even pedestrian/footway) are not that popular so we would loose all the pedestrian ways around and they're still better than no trace at all. So I prefer just covering (rough) lines with (detailed) areas when they're available.

**Comment by math1985** [comment]
If we render highway areas above highway lines, the casings of the road terminating on an area will be visible as dents in the area. That's worse than the current situation, so we don't really have a way to solve this.
