### ISSUE TITLE
footpaths shown, but service roads not. zoom 15

### ISSUE THREAD

**Issue by harry-wood** [gravitystorm/openstreetmap-carto#1486]
At zoom level 15 footpaths are shown but service roads are not. Looks a bit weird here for example: 
http://osm.org/go/evsGtbDt?m Zoom out to 15 and there's just a gap

**Comment by math1985** [comment]
What solution do you propose?

**Comment by math1985** [comment]
This was in fact earlier reported as #561, but we couldn't find a solution there. Feel free to suggest an improvement in the older issue.

**Comment by Rovastar** [comment]
561 is about driveway not service roads proper. Service roads should be rendered.

**Comment by math1985** [comment]
Regular service ways are rendered from the same level as footways, the example given by @harry-wood is tagged as driveway.

**Comment by Rovastar** [comment]
Oops my mistake

**Comment by harry-wood** [comment]
Aha service=driveway renders at less zoom levels. Didn't even know that tag
