### ISSUE TITLE
Reconsider binary mode for project.mml

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#1487]
In #1480 the project.mml file was changed to being treated as binary. I know find that running yaml2mml.py on my copy changes the project.mml file, but I don't know what's changed since `git diff` just says binary file changed.

Is there an easy way to find out what the differences are?

**Comment by pnorman** [comment]
> Is there an easy way to find out what the differences are?

Checking the gitattributions options.

I'm curious, as project.mml is a generated file, what are the reasons for looking at it instead of project.yaml?

**Comment by gravitystorm** [comment]
It's an important file, so I like to check that it's as intended.

For example, it turns out that my editor was stripping whitespace from the yaml file without me realising. So the project.mml file was being shown as changed, and I didn't know why, and I couldn't find out either.

Secondly, it means that I can't `git add -p` if I make two changes that I want to commit separately. The workaround is to `git add -p`, then `git stash`, then run the python script, then commit, then git stash apply, then run the python script again, etc. Worse will happen when I get this wrong, and commit some changes to the mml file by mistake (e.g. `git add -p`, then `git commit`) - it'll be picked up by travis, but that's a bit cumbersome.

Anyway, if other people find it an advantage then fair enough, but I'd like to hear from everyone what they think so that it's considered properly.

**Comment by math1985** [comment]
I have no strong opinion either way. I don't use `git add -p`. I appreciate the cleaner `diff`s, but I'm not sure if avoiding the issues mentioned by @gravitystorm is not more important.

As a matter of principle, treating compiled files as binary makes sense, I guess, so not treating it as binary seems a bit of a hack.

**Comment by pnorman** [comment]
I find it an advantage because the diff noise was making it harder to see what changed in a commit.

I've tried `git add -p` a few times for adding some changes but not all, and I never found it worked well since frequently I couldn't split the changes in the JSON the same way I wanted to in the YAML. I still use git add -p, but just to review my changes as I add them.

If we want to revert #1480, I could add the definitions to `.git/info/attributes` locally

The "right" way to handle project.mml is probably with git smudge filters.

Of course, the real right way is to get YAML support upstream in carto and stop distributing a compiled file.

**Comment by matkoniecz** [comment]
.mml diffs were for me a pure noise, I never verified contents of this file (of course, I am always checking whatever rendering works).

> Secondly, it means that I can't git add -p if I make two changes that I want to commit separately.

I never used this functionality during developing style, so I never had problem with this.

**Comment by pnorman** [comment]
`echo '*.mml diff' > .git/info/attributes` will override the project settings with your own local setting to show diffs for mml files.

**Comment by math1985** [comment]
With a workaround available and no strong support for reconsidering this option, I think we can close the issue.
