### ISSUE TITLE
Water parks areas should be rendered

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1490]
Issue #370 was closed by pull #725, where leisure=water_park got an icon. I think it should also get a fill. 
Possible colours:
- like landuse=meadow (since there are often meadows along the pools)
- something like sports_centre (maybe rethink that strong green at the same time...)

**Comment by mboeringa** [comment]
I don't think this should have a fill, but some kind of outline only. It is a kind of "administrative" border, not a visible feature on the ground (In my personal ArcGIS Renderer, I render it as such: with just an outline). And yes, this is similar for sports_centres and many other OSM features...

**Comment by matkoniecz** [comment]
Can you give an example of location where fill would be useful?

**Comment by mboeringa** [comment]
@matkoniecz: Here is an example rendering of waterpark in Paris to show you why I think using an outline may be more appropriate. As you can see, there is other stuff being tagged within the outline of the waterpark. Setting a fill could only be done if it is one of the "lower" layers, drawn below most other stuff, but I think an outline is probably best, like with **leisure = marina** or **tourism = theme_park**. These features can be quite big as well.

![waterpark](https://cloud.githubusercontent.com/assets/7635726/7490108/cf9b9f38-f3dd-11e4-8635-dd960868c161.png)

**Comment by daganzdaanda** [comment]
> Can you give an example of location where fill would be useful?

https://www.openstreetmap.org/way/70234702 used to be a leisure=water_park, and someone turned it into leisure=park, probably because it makes the area visible (as someone speculated in a note about it).
Here http://www.openstreetmap.org/way/127430479 there's also "surface=grass" tagged, which doesn't  help to make the area green (anymore?), and is actually wrong since the area also contains buildings and the pools...
Checking overpass for water_parks shows a lot of them that look "wrong" because there is nothing to show the extent of them. 

But I do agree with @mboeringa that an outline could do the same as a fill, or even more since then people might start to fill the outline with micromapped meadows and trees and so on.

**Comment by KaiRo-at** [comment]
I've seen water parks getting a landuse=recreation_ground just so that it gets rendered as green on the map (given that most of the surface is usually grass and recreational stuff is mostly green in our scheme, that color sounds right anyhow).
Examples are http://www.openstreetmap.org/way/24443459 or http://www.openstreetmap.org/way/24444267 around my home town.

**Comment by kocio-pl** [comment]
+1 for the outline.

( Another +1 for lighter shade of green in sports_centre - new issue probably? )

**Comment by polarbearing** [comment]
A water park is a theme park which theme is water, thus treating it the same as a theme park seems logical. Either with the same colour, or more blueish like the marina.

**Comment by Tomasz-W** [comment]
Related to #3045

**Comment by johsin18** [comment]
I vote for a greenish fill, or at least for supporting additional tags like surface=grass. I have the impression that many water parks are tagged as regular parks, so tagging for the renderer.

**Comment by polarbearing** [comment]
Still prefer an outline over a fill.

**Comment by kocio-pl** [comment]
I think theme park rendering would be OK. Anybody like to create the PR?

**Comment by geozeisig** [comment]
An outline is good and a fill too, but water park got an misleading icon. It shows a swimmer although water parks are not suitable for swimming. So delete the icon or replace it with a better one. The icon should be used for sport facilities [#2018](https://github.com/gravitystorm/openstreetmap-carto/issues/2018).

**Comment by johsin18** [comment]
Thanks to your comments, I came to the conclusion that for my use case, I should rather use leisure=sports_centre, which has a fill already.  So please ignore my comment, sorry (I will remove it).

**Comment by jeisenbe** [comment]
In #3748, we tried rendering with the tourism (zoo, theme park) outline, but this showed problems: the tag `leisure=water_park` is often used for swimming pool areas that are not very similar to theme parks. So now the option is to try a fill color, perhaps similar to recreation ground or sports_centre
