### ISSUE TITLE
tram_stop and bus_stop on one node leads to doubled label

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1491]
http://www.openstreetmap.org/node/703415187
This is a railway=tram_stop and a highway=bus_stop at once. In some zoom levels, the name of the stop gets rendered twice. I think this has been introduced recently, at least I did not notice it a few months ago. 
It looks a bit silly, but on the other hand it is good feedback for the mappers. Before, you would not see any hint that buses stop there, too. 

Should we change anything about that behaviour?

**Comment by pnorman** [comment]
We should probably consistent about if we're rendering the tram stop and bus stop labels above/below the point, which will eliminate this

**Comment by jojo4u** [comment]
This is wrong tagging. Bus_stop belongs beside the road, tram_stop on rails. The tagging got fixed a year ago. I guess this issue is so minor it should get closed.

**Comment by matkoniecz** [comment]
> This is wrong tagging. Bus_stop belongs beside the road, tram_stop on rails. The tagging got fixed a year ago. I guess this issue is so minor it should get closed.

It is not clearly documented on wiki (for example http://wiki.openstreetmap.org/wiki/Tag:railway=tram%20stop?uselang=en-US).

**Comment by jojo4u** [comment]
The wording is a bit convoluted but its clear:
> Insert a node in a way tagged with railway=tram at the position where the stop is located and tag this node with railway=tram_stop and name=*

**Comment by matkoniecz** [comment]
lets continue at http://wiki.openstreetmap.org/wiki/Talk:Tag:railway%3Dtram_stop#meaning_of_.22where_the_stop_is_located.22
