### ISSUE TITLE
leisure=marina outline doesn't cover man_made=pier at z18 and z19

### ISSUE THREAD

**Issue by bubalici** [gravitystorm/openstreetmap-carto#1492]
The marina's blue outline stops at the edge of the pier for zooms 18 and 19 (lower than that it appears ok from what I can tell). 
![1](https://cloud.githubusercontent.com/assets/10978358/7218448/f3746500-e66f-11e4-9372-daae4c8c9f7a.jpg)

https://www.openstreetmap.org/#map=19/37.43629/24.93703

**Comment by gravitystorm** [comment]
As a side note, the water should be included in the marina too, rather than running up and down the side of each pier.

**Comment by math1985** [comment]
That's not a side node, I think that's the cause of this issue. Marinas should include the water areas as well, and doing that should solve this issue.
