### ISSUE TITLE
Add rendering for power=sub_station/substation + building=*

### ISSUE THREAD

**Issue by al--** [gravitystorm/openstreetmap-carto#150]
Currently an area tagged

* power=sub_station
* building=yes

to indicate that it's an indoor substation is rendered as if it was a "regular" building
![power building](https://f.cloud.github.com/assets/1458456/1097390/a295a200-1710-11e3-9d03-16ddcadbf4ce.png) 
[Umspannwerk Michelbeuern](http://www.openstreetmap.org/browse/way/23709119)

Shouldn't it be rendered much like an outdoor substation?

And/or maybe you could add a flash icon to such substations? &nbsp; ![lightning](https://f.cloud.github.com/assets/1458456/1097404/012fe118-1711-11e3-8f8c-39b37da3dc49.png)  &nbsp; [SVG](http://www.openstreetmap.at/files/lightning.svg)

**Comment by matkoniecz** [comment]
I am not convinced that it is a good idea - it seems to be not information that would be generally useful and recognisable.

Also - it seems that most of substations fully enclosed in buildings are nearly always quite minor - and therefore probably less important (I may be mistaken, I am basing this on my local observation and searching with overpass).

Also - such combination is typical for cities with many other objects already displayed.

I would recommend rejecting this proposal.

**Comment by pnorman** [comment]
> Also - it seems that most of substations fully enclosed in buildings are nearly always quite minor - and therefore probably less important (I may be mistaken, I am basing this on my local observation and searching with overpass).

They can be fairly large (e.g. [way 51185776](http://www.openstreetmap.org/way/51185776)) but economics dictate that unless a large area is quite dense, large substations are not in buildings.

That being said, most people wouldn't realize it was one without the big "Substation" on the outer wall. Given the conflict between rendering it like a substation and rendering it like a building, I consider the latter more important to render, and the combination of the two not significant or important enough have its own style.

**Comment by al--** [comment]
"Trafohäuschen" (as they are called in German) are quite common in AT ([photos](https://www.google.at/search?q=trafohäuschen&sa=X&tbm=isch)) and they are good landmarks! And the map in my OP shows a rather big one (common in dense urban areas). 

The problem was (at time of OP, don't know current status): If you tag both building and power, it is treated like any building (the power tag is ignored)! It would be ok to treat it the same as with power= only (i.e. ignore the building tag).

And an additional wish was to map electrical power infrastructure (POIs and areas, including buildings) with a lightning icon (
![lightning](https://cloud.githubusercontent.com/assets/1458456/9517739/53bd212e-4cb2-11e5-8251-39c56e00384f.png) [SVG](https://www.openstreetmap.at/files/lightning.svg) to make it easier to recognize.

**Comment by al--** [comment]
They even have [their own website](http://www.trafoturm.eu/)... ;) ;)

**Comment by al--** [comment]
[Here](http://overpass-turbo.eu/s/b9b) you can find quite a few examples.

**Comment by kocio-pl** [comment]
This kind of icon may be enough to differentiate power buildings/areas from general industrial.

**Comment by matkoniecz** [comment]
>  It would be ok to treat it the same as with power= only (i.e. ignore the building tag).

For most people it is not really important that substation is in the building - building itself is far more importart.

**Comment by pnorman** [comment]
Given our current power rendering, I don't think this makes sense. Our entire power rendering could probably use re-doing, and if that happened this might then become an option.
