### ISSUE TITLE
Brown color flooding Europe / Germany at Z19

### ISSUE THREAD

**Issue by mboeringa** [gravitystorm/openstreetmap-carto#1502]
I see no one else yet raised this issue here, but in the Germany (and to some extent outside), there is currently a dark brown color flooding Z19.

It doesn't seem to match problems / color appearing with coastline issues?...

See discussion here in the German OpenStreetMap subforum with links to affected extent:
**Europa wird braun**
http://forum.openstreetmap.org/viewtopic.php?id=30938

I wonder if it has something to do with a huge "land_area" multipolygon created for Germany 12 days ago with **type=land_area**?:

(please note your browser may have a hard time opening this link)
http://www.openstreetmap.org/relation/62781

Although the extent of the brown area seems to be going beyond this...

**Comment by pnorman** [comment]
No reason to suspect any kind of OpenStreetMap issue here

**Comment by mboeringa** [comment]
That may be so, but it would be helpful to trace back this particular color in the style, so as to know what needs fixing. One of the last posts in that thread on the German forum speculates the color might be related to building (outlines) colors...

**Comment by mboeringa** [comment]
Well, user woodpeck may have fixed it, see:
http://forum.openstreetmap.org/viewtopic.php?pid=499950#p499950

and especially:
https://www.openstreetmap.org/node/2082813401/history

**Comment by mboeringa** [comment]
This issue does slightly raise the question though, if the render databases should accept just any geometry thrown at them... While I appreciate the coastline difficulties, couldn't this issue have been prevented by doing some basic geometric check in PostGIS before inserting the feature? (excuses for my ignorance, but I know to little of the exact updating process going on behind the scene between the main and render databases)

**Comment by gravitystorm** [comment]
> if the render databases should accept just any geometry thrown at them

That's a discussion that's way out of scope for this repository.
