### ISSUE TITLE
More fine grained capital ordering

### ISSUE THREAD

**Issue by joakimfors** [gravitystorm/openstreetmap-carto#1505]
Perhaps there should be one more "level" of capital rendering. Currently capital=yes and =4 are treated the same way (#1247 and f02d12c3a66bb1e6c011a4d0faaea01b1f29d86a) which leads to priority conflicts between national capitals and regional capitals. Maybe capital=yes and capital=2 should be placed in placenames-capital and a new category, placenames-medium++ ;), should be created where ≈4 and would reside.

Example of Malmö clobbering Copenhagen: http://www.openstreetmap.org/#map=6/55.260/12.722

**Comment by math1985** [comment]
#1461 should implement this.
