### ISSUE TITLE
Office=government not rendered

### ISSUE THREAD

**Issue by Stalfur** [gravitystorm/openstreetmap-carto#1506]
An issue we are having in various places in Botswana is the absence of government offices, [on this little spot](http://www.openstreetmap.org/#map=17/-24.86406/25.85663) here we have at least 5 government offices (landboard, AIDS prevention, health administration, council etc) which are not rendered currently.

**Comment by HolgerJeromin** [comment]
exactly the same as #271
related to the meta issue #108

**Comment by Stalfur** [comment]
Thanks, did not find these despite searching repository
