### ISSUE TITLE
Request to add rendering for motorhome tank disposal stations (Elsan points, Dump Stations) 

### ISSUE THREAD

**Issue by brycenesbitt** [gravitystorm/openstreetmap-carto#1507]
OSM has good rendering coverage for campgrounds. This is a request to render the toilet holding tank dump stations as well.

There are tens of thousands of these worldwide, with hundreds mapped in OpenStreetMap.
It's also the type of feature that could attract new mappers (especially since nearly
every caravan site has wifi).

The tag is **amenity=sanitary_dump_station**, it often but not always is found in a camp_site.
A set of three icons in different sizes are at: https://github.com/gravitystorm/openstreetmap-carto/pull/1466

There's a similar tag used and rendered by OpenSeaMap, except for marine users.

**Comment by matkoniecz** [comment]
http://taginfo.openstreetmap.org/tags/amenity=sanitary_dump_station - used only 431 times, not a special case like capital=yes ("there are tens of thousands of these worldwide").

**Comment by brycenesbitt** [comment]
Capitals represent the past of mapping.
Unmapped features represent the future.

But really: the dump stations are a useful easy to render feature that's common on other maps.  Google maps has capitals: OSM can stick out by rendering in greater depth.

**Comment by pnorman** [comment]
430 node usages, of which 385 by the same user ID.

Not an established tag.

**Comment by brycenesbitt** [comment]
> 430 node usages, of which 385 by the same user ID.

@pnorman check the first revision of each node: those are far more diverse.  You are seeing the result of a tagging consolidation, not a single user feature.

**Comment by BalooUriza** [comment]
I'm nominating that we re-open the issue.  This is a thing that needs to exist.  

I know we all live by the mantra "don't tag for the renderer", but reality is, people tag things they recognize and know are supported by at least the renderers and routing engines available on the homepage.  And if you've just spent a week off the grid and have a black tank on the verge of belching sewage all over the interior and the highway, emptying that (and, for longer journeys, refilling the freshwater tank) is as critical as getting fuel to drive/tow it.

This isn't necessarily only a luxury feature, either.  In humanitarian situations, dump stations can often be temporarily fitted to handle composting toilets or as a collection point for dumping portable toilets in the vicinity, and as equally valuable as the opposite amenity: Drinking water, which I believe is already rendered.

**Comment by Barrocas** [comment]
Agree with BalooUriza, it would help in locating these spots, I though I don't use them (have no caravan), but I see the need and understand it.

**Comment by brycenesbitt** [comment]
This feature is now a preset in iD and JOSM.

**Comment by kocio-pl** [comment]
What visual representation (icon probably) should it have? Anything already used or maybe something new?

**Comment by Barrocas** [comment]
There is a link to the proposed image, in a previous post..

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by kocio-pl** [comment]
It was hard to find, however I made a [quick rework of this icon](https://github.com/kocio-pl/openstreetmap-carto/blob/toilet_dump_station/symbols/toilet-dump-station-14-big.svg) to stick to our current standards: ![toilet-dump-station-14-big](https://cloud.githubusercontent.com/assets/5439713/7899350/0f4ad3e2-0720-11e5-88c3-0877844520d6.png)

**Comment by matkoniecz** [comment]
I would never guess meaning of that icon.

**Comment by brycenesbitt** [comment]
Would the intended users understand the symbol?  Those with a motorhome or boat?

----------------------------------------
Here are the icons I created:
https://github.com/gravitystorm/openstreetmap-carto/pull/1466/files

As well, there's a standard USA traffic sign for this feature: sign number D9-12.
 But it depicts the USA style of this feature, which involves a connection like this:
http://i.ytimg.com/vi/Uuz3Y9jRRNM/maxresdefault.jpg
http://www.trafficsign.us/650/guide/d9-12.gif
And that's not a worldwide view.

----------------------------------------
There are four styles of holding tank toilet station that seem common worldwide. The context usually makes the type clear:

1) USA style round gravity drains: the drain point must be at ground level.
2) Cartridge style, where the waste is in a portable tank carried or rolled to the dump point.   The dump point is some sort of basin, often raised above the ground to ease emptying.
3) Marine pumpout stations, which suck the waste out.
4) Aircraft pumpout stations (about which I know little).

While it's rare: a given pump station might support more than one style.  There seem to be combined #1 and #2 available. 


See also 
http://www.sanidumps.com/sanidumps_belgium.php
