### ISSUE TITLE
Render flush toilets slightly differently from pit or chemical toilets

### ISSUE THREAD

**Issue by brycenesbitt** [gravitystorm/openstreetmap-carto#1508]
Tag **toilets:disposal** is available to determine the toilet type. **toilets:type** has the same data. There are 10,000 uses between them.

**Comment by HolgerJeromin** [comment]
Do you have any idea for rendering different? The toilet icon was pretty hard to design in the 14x14 pixel space. 
The logic should be to render 
toilets:disposal=pitlatrine || toilets:disposal=chemical
different, as toilets:disposal has many bogus data and most toilets are not tagged.
I am unsure to support the obsolete toilets:type but it has a high count for toilets:type=pit (other values were cleaned up by me).
This tags have to be added in a reimport (see #1504 )

**Comment by brycenesbitt** [comment]
One idea is to use the common crescent moon "outhouse" symbol for the pit toilets.
Or, the centre bar between the man and woman could be dashed for pit/chemical toilets (but few people would figure that out without a map key).

**Comment by HolgerJeromin** [comment]
I have never seen a crescent moon on an outhouse and I think this would be misinterpreted as a symbol for muslim thing, as a muslim place of worship has such a symbol.
A dashed line would work, but i think this would probably interpreted as a lack of separation for men and women. :)

**Comment by brycenesbitt** [comment]
Color or background could also be used.  The 14x14 space is terribly tiny.

The "outhouse" map symbol is not something I invented:
![symb_outhouse](https://cloud.githubusercontent.com/assets/1294423/7421911/581129b4-ef3d-11e4-8478-afd4137c7cb8.jpg)
For some historic analysis see http://missourifolkloresociety.truman.edu/outhouses.html

**Comment by gravitystorm** [comment]
I think this level of detail is well beyond a general-purpose map.

**Comment by math1985** [comment]
> I think this level of detail is well beyond a general-purpose map.

+1, closing this.

**Comment by brycenesbitt** [comment]
I think you have a lot of people who won't use a pit toilet, who are simply unable to derive value from a single icon.  For example: one might be willing to walk to a farther toilet, if the nearby one is a pit, and a nearby flush unit can be seen on the map.

**Comment by gravitystorm** [comment]
Sure, I understand why you might be interested in whether it's a pit toilet or not. But people might be interested in whether a supermarket is selling cornflakes, or a hairdressers does dying as well as cutting, or if a telephone box has wifi available, or if a museum has audioguides in Japanese, or.... 

For every feature in OSM, there will be some additional - and useful - level of detail that we need to choose not to render on this style.

**Comment by matthiasfeist** [comment]
I don't necessarily want to open up this discussion again, but it seems that the iD editor has chosen to support the mapping of these kinds of toilets by providing a template for tagging and also renders it with a special icon.
Example here: https://www.openstreetmap.org/node/3666208448
