### ISSUE TITLE
One for the interface engineers

### ISSUE THREAD

**Issue by pmailkeey** [gravitystorm/openstreetmap-carto#1510]
Hi,

If the OSM interface engineers live here...

Can we have it so that hovering over an object reveals the object type and name - and then if clicked on, opens up full data disclosure like currently selecting ? and clicking on/near an object ?

**Comment by kocio-pl** [comment]
I guess you should [try here](https://github.com/openstreetmap/openstreetmap-website/issues).

**Comment by pmailkeey** [comment]
Cheers.
