### ISSUE TITLE
render area:highway=primary,secondary,tertiary the same colour as highway=pri,sec,tert.

### ISSUE THREAD

**Issue by pmailkeey** [gravitystorm/openstreetmap-carto#1514]
Currently area highways (e.g. residential and service) are rendered the same colour as their respective highways ('white'). Area Highways primary, secondary and tertiary are also rendered white while the highways are red orange and yellow. Can we have the areas rendered the same colours as the respective highways please.

image Sample: residential, primary, tertiary.

![image](https://cloud.githubusercontent.com/assets/11827386/7438864/a7bb1b60-f063-11e4-8ef3-c6201e756c67.png)

**Comment by pnorman** [comment]
We don't render area:highway, and that is already covered by #180

**Comment by matkoniecz** [comment]
And that particular cases seems to be a tagging for renderer - somebody used [highway=service+area=yes] instead of [highway:area=primary].

**Comment by pmailkeey** [comment]
I show you an image of rendered area:highway and you say you don't render it. Ok, so who does then ? Whoever it is, can you make the colours match please - as per my original request ! :((((

**Comment by pmailkeey** [comment]
Area highway primary and tertiary (and presumably secondary) aren't rendered - so they need to be. Highway residential is - and so has been used - after all, the roads are residential toooooo

**Comment by matkoniecz** [comment]
> rendered area:highway

Have you checked it (using editor and looking at tags?). Anyway, please link this location.

**Comment by pmailkeey** [comment]
https://www.openstreetmap.org/#map=19/54.21137/-3.27538

**Comment by matkoniecz** [comment]
Yes, it is tagging for render. Instead of area:highway=* somebody incorrectly used highway=residential+area=yes.

**Comment by gravitystorm** [comment]
> I show you an image of rendered area:highway and you say you don't render it. Ok, so who does then ?

Less of the bad attitude please. If you'd like a more detailed explanation, then ask nicely, but please don't argue with us when you don't know what you're talking about.

**Comment by pmailkeey** [comment]
Tagging as 'residential' isn't incorrect as it is a residential road. Whether it's a tertiary road is somewhat more subjective. It still needs the rendering sorting out for areas of primary, sec and tertiary though.

I only have a 'bad attitude' when dealing with idiots.
