### ISSUE TITLE
Render barrier= kerb over areas

### ISSUE THREAD

**Issue by pmailkeey** [gravitystorm/openstreetmap-carto#1515]
Rendering the sidewalk area as a footway and area highway as a road is hiding barrier=kerb. This in turn is hiding dropped kerbs (disabled) etc.

**Comment by matkoniecz** [comment]
duplicate of #528 (found by searching [barrier area](https://github.com/gravitystorm/openstreetmap-carto/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+barrier+area+))
