### ISSUE TITLE
Same level boundary names should face each other

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#1516]
The way to render [the boundaries in this place] (http://www.openstreetmap.org/?mlat=50.39884&mlon=5.53053#map=17/50.39884/5.53053) is a wonderful improvement.
But "Liège" can be a Province, an Arrondissement, a City, a Municipality or a Part-municipality.
And, facing Durbuy, it looks like the municipality.
Here, it's the Province and it would be nice if it were facing Province Luxembourg to show that.
Same for 8=municipality, 6=arrondissement and 4=province probably in that order.
That is:

     Durbuy    Marche-en-Famenne  Luxembourg
    - - - - - - - - - - - - - - - - - - - - -
    Ferrières         Huy            Liège

instead of the top line being the other way round.

Thanks!

**Comment by math1985** [comment]
Makes sense.

Do we have any way to accomplish this?

**Comment by math1985** [comment]
Now I think of it, this is not possible. Within one polygon, the order should be the same everywhere. That means that at a tripoint, at least one of the border labels will be the wrong way around. Example:

```
     C|C
     B|B
     A|A CBA
     .------
   C/C   ABC
 B/B    
A/A      
```

**Comment by a-pirard** [comment]
Please do not close issues before waiting for a reply.
Please reopen.
I'm afraid your answer is unfortunately incorrect.
No two sides of a border can, of course, have the same names.
Assuming municipalities, arrondissements, provinces (in that order):
ABC
DEF
GHI
The marking is as follows:
````
     A|I   G
 A   B|H
     C|G IHG
     .------
   A/F   DEF
 B/E    
C/D      D
````
Being understood that any of BEH may be the same name, same for CFI.
Should the names be written when they're the same?
Yes, I think, for consistency of making this scheme understood.
And if the space is short, they could both be stacked, municipality nearest.

**Comment by math1985** [comment]
I think you might be misunderstanding the problem. Could you create an example of an tripoint with expected output in ASCII art? I think you'll see this is impossible.

**Comment by a-pirard** [comment]
Thanks for replying, but I think you are mistaken.
What I have replied contains your own ASCII art with the letters corrected.
You have drawn 3 boundaries between municipality A, municipality A and municipality A.
We cannot have the same municipality on both sides of the same municipality boundary, can we?
I changed it to 3 boundaries between municipality A, municipality D and municipality G.
Same for the arrondissements and provinces, (which can be the same across a municipality boundary).
Please reread my text carefully.
And, once again, please reopen this issue.
Thanks.

**Comment by daganzdaanda** [comment]
@a-pirard , I think A means the category "municipality" and not a certain name of a municipality in @math1985 's example. Does it make sense then?

**Comment by a-pirard** [comment]
Sorry, I received no e-mail notification of your answer.
The corrected version of your drawing is this.
````
     C|C
     B|B
     A|A ABC
     .------
   C/C   ABC
 B/B    
A/A      
````
Note that the vertical and oblique boundaries must be looked at at sideways (tilt your head to the left).
These two names are written alongside the boundary.
The way you have drawn them, the bottom of their letters are to the right.
And if you look at names from within the upper right area are, the horizontal one is bottom up.
The names are supposed to start with the lower level (A, highest number) as you read them.  If, turning round a boundary the names flip over bottom up / head down, it's normal that your drawing shows them in opposite order because you read them in opposite order.
But note that names facing each other must of course **never** be flipped.

I hope that this clarifies my suggestion and that you will reopen the case (as you think it "makes sense").

**Comment by math1985** [comment]
The problem with the proposed picture is that the area in the upper right is labelled ABC on one border, and CBA (different order) on the order. I don't think we have a way to accomplish that, do we?

Do we currently label borders (the line between two tripoints), or border relations (the entire polygon)?

**Comment by pnorman** [comment]
Polygons are the objects rendered afaik - otherwise we couldn't offset the labels to the appropriate side.

**Comment by a-pirard** [comment]
On 2015-05-10 13:59, math1985 wrote :
>
> The problem with the proposed picture is that the area in the upper
> right is labelled ABC on one border, and CBA (different order) on the
> order. I don't think we have a way to accomplish that, do we?
>
> Do we currently label borders (the line between two tripoints), or
> border relations (the entire polygon)?
>
I stop commenting that misleading drawing because it does not show on
which side the bottoms of the letters are (in which direction the names
are read) and hence it's impossible to prove anything with it.
Let's use this closed boundary from the map
<http://www.openstreetmap.org/relation/2792257> instead.
If you follow its border clockwise from West to East and if you read the
inside names *as you do*, that is in the order you meet the words and
the letters, you will read   xuerbmeloD ...  Sprimont ... xuerbmeloD
...  xuerbmeloD Sprimont ... Sprimont Dolembreux ... Dolembreux
Sprimont  ... Dolembreux ... xuerbmeloD ... xuerbmeloD ...
Hence, the current map already exhibits what you call a problem: "the
area is labeled ABC somewhere and CBA (different order) elsewhere.  But
that's quite normal because, as I said before, it happens when the names
are flipped upside down: you must  bend your head or turn the map to see
the bottom of the letters towards you to tell which word is on the
left.  But as the names are flipped the same way either side, their left
sides are facing each other.

The best way to prove that there is no problem with my suggestion is to
forget it all about that drawing and to notice that all it takes is
sliding the names alongside the border both sides and make name groups
so that "Same level boundary names face other".  The *only* gotcha is
that a name group should not extend across a point where you flip the
names, in which case the parts of the group would be flipped different ways.

Keep doing exactly what you do now except that you slide the names.
And make groups like I have shown in the first message.

*And please reopen this case.

*

**Comment by a-pirard** [comment]
On 2015-05-10 13:59, math1985 wrote :
    
    
      The problem with the proposed picture is that the area in the
        upper right is labelled ABC on one border, and CBA (different
        order) on the order. I don't think we have a way to accomplish
        that, do we?
      Do we currently label borders (the line between two tripoints),
        or border relations (the entire polygon)?
      
    
    I stop commenting that misleading drawing because it does not show
    on which side the bottoms of the letters are (in which direction the
    names are read) and hence it's impossible to prove anything with it.
    Let's use this

      closed boundary from the map instead.
    If you follow its border clockwise from West to East and if you read
    the inside names as you do, that is in the order you meet
    the words and the letters, you will read   xuerbmeloD ...  Sprimont
    ... xuerbmeloD ...  xuerbmeloD Sprimont ... Sprimont Dolembreux ...
    Dolembreux Sprimont  ... Dolembreux ... xuerbmeloD ... xuerbmeloD
    ...
    Hence, the current map already exhibits what you call a problem:
    "the area is labeled ABC somewhere and CBA (different order)
    elsewhere.  But that's quite normal because, as I said before, it
    happens when the names are flipped upside down: you must  bend your
    head or turn the map to see the bottom of the letters towards you to
    tell which word is on the left.  But as the names are flipped the
    same way either side, their left sides are facing each other.
    
    The best way to prove that there is no problem with my suggestion is
    to forget it all about that drawing and to notice that all it takes
    is sliding the names alongside the border both sides and make name
    groups so that "Same level boundary names face other".  The only
    gotcha is that a name group should not extend across a point where
    you flip the names, in which case the parts of the group would be
    flipped different ways.
    
    Keep doing exactly what you do now except that you slide the names.
    And make groups like I have shown in the first message.
    
    And please reopen this case.

**Comment by a-pirard** [comment]
Explaining this to a friend, I realize that the problem comes down to writing the well formated string "Durbuy    Marche-en-Famenne  Luxembourg" instead of "Durbuy" and "Marche-en-Famenne" and "Luxembourg" separately and the just as well formated (to be facing) other string exactly aligned to the other side.  Hoping that can be easily done.  Thanks.
