### ISSUE TITLE
render label for historic=city_gate

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#152]
City gates are mostly quite important features for orientation. Even if the citywalls or the city gate doesn't exist (or act as barriers) any more, they are usually still important for the local people as toponyms in way descriptions and the like. Please render historic=city_gate (not necessarily with an icon, but maybe like place=locality?).
http://taginfo.openstreetmap.org/tags/historic=city_gate

**Comment by matkoniecz** [comment]
see also #790 proposing doing this for barrier=gate

**Comment by dieterdreist** [comment]
Yes, while gates should also have their name rendered (in the few cases where a name tag is present), it's worth to point out that historic=city_gate might also be applied to places without actual gates (still the name will typically be preserved, and in a lot of cases there will be traces, e.g. an opening in the city wall).

**Comment by kocio-pl** [comment]
Are we still interested in this? How should it be rendered then?

**Comment by dieterdreist** [comment]
I’d render just a label, these are typically well known toponyms even in absence of the actual gate / structure

**Comment by kocio-pl** [comment]
There is also icon in Osmic - one should test if and when (probably z18+/z19+) to render it:

https://github.com/gmgeo/osmic/blob/master/tourism/city-gate-14.svg

**Comment by matthijsmelissen** [comment]
This is one of the oldest issues, and relatively simple to implement. Is anyone willing to work on this?

**Comment by matthijsmelissen** [comment]
Is this something for @andrzej-r perhaps?

**Comment by jragusa** [comment]
with the Osmic icon:

on building:
https://www.openstreetmap.org/way/317181351
![city_gate_yvoire](https://user-images.githubusercontent.com/9897203/39967932-c45b5db4-56c4-11e8-9351-549ef974d1dd.png)

on node:
https://www.openstreetmap.org/node/5092502909
![city_gate_larochesurforon](https://user-images.githubusercontent.com/9897203/39967940-e2e6e3ac-56c4-11e8-8f18-7426a9747b9c.png)

**Comment by jragusa** [comment]
with man_made colour on same locations:
![city_gate_yvoire_manmade](https://user-images.githubusercontent.com/9897203/39971273-81b7142e-56f8-11e8-9103-9562ec59621e.png)

![city_gate_larochesurforon_manmade](https://user-images.githubusercontent.com/9897203/39971301-f5cf4e44-56f8-11e8-85f0-554199bd8bfd.png)

with label alone:
![city_gate_yvoire_label](https://user-images.githubusercontent.com/9897203/39971171-33fdaf1e-56f7-11e8-995c-0c4156047a0d.png)

label is not displayed for the previous one (priority of street name ?). Adjacent gate:
https://www.openstreetmap.org/node/5092502910
![city_gate_larochesurforon_label](https://user-images.githubusercontent.com/9897203/39971173-3b34ec98-56f7-11e8-8221-07a96f533b82.png)

I'm in favour for man_made colour which is also consistent with defensive towers

**Comment by kocio-pl** [comment]
Man made black is consistent with all the towers and city walls, so I vote for this color too. @jragusa Could you prepare a PR?

**Comment by Tomasz-W** [comment]
I have got 2 more ideas:
- render also city gates tagged as relations (some of them are ruins with a few separated parts, example below)
- render historic=city_gate + ruins=yes with lighter icon (like private parkings)

Example gates:
![20161015_133518](https://lh5.googleusercontent.com/p/AF1QipPhOGZXI2oRWaGjqsU1xl4CmFM0FDDBDDgMsykf=rp)
![20161015_133518](http://gdansk.fotopolska.eu/foto/341/341296.jpg)

What do you think about it?

**Comment by kocio-pl** [comment]
Lighter icon might also work for castles/palaces/stately/manors etc. - but somebody has to test it. There's also a question how the `historic=ruins` should look like then (see #331).

Relations might not work because currently import using osm2pgsql does not move relation properties to their members.

**Comment by matkoniecz** [comment]
> render also city gates tagged as relations

these gates are tagged as multipolygons, right? In that case no special handling is needed.
