### ISSUE TITLE
Add special rendering for shop=garden_centre

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1523]
My propositions: ![garden_centre-14](https://cloud.githubusercontent.com/assets/5439713/7452238/48246e32-f25b-11e4-9bbe-988c7810cdd8.png) ![garden_centre-14-3](https://cloud.githubusercontent.com/assets/5439713/7452232/24acbb12-f25b-11e4-854d-4a67741f4c1a.png) ![garden_centre-14-6](https://cloud.githubusercontent.com/assets/5439713/7452529/cdb49cfe-f25e-11e4-96bb-10f13caf2bfe.png) (and [this one](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-garden_centre/symbols/garden_centre-14.svg) ![garden_centre-14](https://cloud.githubusercontent.com/assets/5439713/7455304/2eb13f6e-f27b-11e4-96f0-4e4aa8bfb1a0.png) is probably the best of them).

[Proposed and talked about in https://github.com/gravitystorm/openstreetmap-carto/pull/1520, mentioned on meta-issue https://github.com/gravitystorm/openstreetmap-carto/issues/1460]

**Comment by matkoniecz** [comment]
This seems a good icon, also for me the last one is my favorite.

**Comment by daganzdaanda** [comment]
Agree, a good idea, and the last icon is probably the best execution.
