### ISSUE TITLE
Add special rendering for shop=beauty

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1525]
1) [My proposition](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-beauty-icon/symbols/beauty-14.svg) for this type of shop is this: ![beauty-14](https://cloud.githubusercontent.com/assets/5439713/7471882/a07ed78a-f32c-11e4-9bcd-05cbaf8357e8.png)
2) [Slightly modified version](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-beauty-icon/symbols/beauty-14-2.svg): ![beauty-14-2](https://cloud.githubusercontent.com/assets/5439713/7508101/6caa7cb2-f47a-11e4-9be9-af27660da577.png)

[Mentioned on meta-issue #1460]

**Comment by matkoniecz** [comment]
This icon is not really working for me. Maybe lipstick would be more recognizable?

**Comment by kocio-pl** [comment]
3) ![beauty-14-3](https://cloud.githubusercontent.com/assets/5439713/7527230/828d76e8-f519-11e4-8d88-5a86d302839b.png)

Rules are hard when dealing with small square matrix: the shapes have to be rather uniform in both directions to be really visible. It's not possible to have true proportions here, because its already very tall (like 4-5 pixels wide) and we're left with too much of a plain geometry, which is much less recognizable.

**Comment by marcgemis** [comment]
what about an eye + eye brush ? something like the right most icon on the second row of : http://www.gettyimages.fi/detail/illustration/black-cosmetics-icons-royalty-free-illustration/166078626 (I know they are not free, but I cannot draw something to illustrate my idea)

**Comment by kocio-pl** [comment]
Eye metaphor:
7) ![beauty-14-7](https://cloud.githubusercontent.com/assets/5439713/7724846/6b574edc-fef5-11e4-9c79-dc01183313a8.png)
8) ![beauty-14-10](https://cloud.githubusercontent.com/assets/5439713/7724850/724f536a-fef5-11e4-8723-9e05df1096e7.png)

**Comment by marcgemis** [comment]
prefer 8 above 7

**Comment by kocio-pl** [comment]
I added also 9) in the meantime. =} Is 7) (or 9) readable enough for you as a symbol?

**Comment by marcgemis** [comment]
it's probably better that someone who doesn't know what you try to present is the judge for that.

**Comment by kocio-pl** [comment]
We can't avoid kind of prejudice here, since everybody looking at the icons on GitHub probably read the title of the issue first ;-) , but that is just a hint and the shape itself may suggest something entirely different - and that would be a bad thing. But if it's not that bad, it's still very interesting for me what do people think about it in general, because I may find another idea or touch some details to make it better. It's also nice to know someone is just happy with a proposed shape.

The best test is probably asking friends, family and other not involved persons showing them just the images, and that happens sometimes, however we don't need to be so strict and use only their input.

**Comment by HolgerJeromin** [comment]
I opened a lot of tabs with issues here and did no see the title when coming back to this tab. So i had no idea what its about and thought: Oh, this is rather a icon for beauty stuff than chemist (which i had opened, too).

**Comment by kocio-pl** [comment]
Field test:
![beauty-after-z19-full](https://cloud.githubusercontent.com/assets/5439713/7784178/a6659934-015c-11e5-8364-b5255cd1b394.png)
![beauty-after-z19-small](https://cloud.githubusercontent.com/assets/5439713/7784179/ac0cf8a0-015c-11e5-939a-419cee6af42d.png)
![beauty-after-z19-rough](https://cloud.githubusercontent.com/assets/5439713/7784180/afc04cea-015c-11e5-9645-09b57769ba94.png)

I like 3) the most, because it's crisp and with that soft color it doesn't look too sketchy.
