### ISSUE TITLE
 Add special rendering for shop=chemist

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1528]
[My proposition](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-chemist-icon/symbols/chemist-14.svg) for this type of shop is this: ![chemist-14](https://cloud.githubusercontent.com/assets/5439713/7478217/64681ce8-f359-11e4-9d87-42e431d88d47.png)

[Mentioned on meta-issue #1460]

**Comment by neiljp** [comment]
From the scale of the image that I can see, this is really quite unidentifiable. Zoomed in, I guess it's a toothpaste/brush pair?

**Comment by kocio-pl** [comment]
Yes, I was looking for something identifiable by the shape and thought about this pair. Maybe you have other ideas?

**Comment by daganzdaanda** [comment]
FWIW, I understood it as toothpaste and brush before I read the first comment. But that may be because I new that it was to signify a chemist.
On the map, the labels will help tell people what the icon means, until they have "learned" it. So it's probably fine. Anyhow, I can't think of a better way to signify a chemist, they sell all kinds of small things in tubes and boxes, not very iconifiable (is that a word?)

**Comment by kocio-pl** [comment]
You may be right, but any criticism makes me think what could be done different, so I just come up with another idea, so we could at least compare which try is better:

2) ![chemist-14-4](https://cloud.githubusercontent.com/assets/5439713/7499206/5623fba2-f426-11e4-9a2c-73f984ce4d25.png)

**Comment by daganzdaanda** [comment]
Is that a roll of toilet paper? cool ;)
...but actually, its not what I would think of first with a chemist. And, @nebulon42 tries to keep perspective in the new icons to a minimum, and I think we should try to follow that guideline.

**Comment by kocio-pl** [comment]
Perspective - sure, but toilet paper clearly belongs to "A shop selling articles of personal hygiene, cosmetics, and household cleaning products." Meanwhile:
 
3) ![chemist-14-5](https://cloud.githubusercontent.com/assets/5439713/7499439/efcd7336-f427-11e4-9084-d909e4ebc1c6.png)

**Comment by kocio-pl** [comment]
4) ![chemist-14-5](https://cloud.githubusercontent.com/assets/5439713/7505904/93d8ae98-f458-11e4-9788-d7828d873810.png)

I still feel 1) is the best, but 4) is a close second for me. I try to mimic current [department store icon](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/department_store.p.16.png), which contains many (4!) more or less recognizable elements.

**Comment by nebulon42** [comment]
Two items is okay, but four (like department store) is way too much.

**Comment by polarbearing** [comment]
> iconifiable (is that a word?)

English allows you to create new words, and in particular using the typical prefixes and suffixes. Thus, it is a word :-)

And back on topic, I like the toothbrush/paste proposal.

**Comment by kocio-pl** [comment]
Maybe. =} However that was impressive for me.

One-man survey I conducted indicates 1) was instantly recognized, so I will probably stay with it.

**Comment by AndiG88** [comment]
What about a Bottle of Soap?

**Comment by kocio-pl** [comment]
Another random tester recognized 1) instantly, so I have no doubt now. Here is my try with your idea, but for me it doesn't work:

5) ![chemist-14-7](https://cloud.githubusercontent.com/assets/5439713/7643567/d116fe02-fa9a-11e4-83dc-f2ce40671552.png)

**Comment by dieterdreist** [comment]
2015-05-15 0:39 GMT+02:00 kocio-pl <notifications@github.com>:

> Another random tester recognized 1) instantly, so I have no doubt now.
> Here is my try with your idea, but for me it doesn't work:
>
> 5) [image: chemist-14-7]
> <https://cloud.githubusercontent.com/assets/5439713/7643567/d116fe02-fa9a-11e4-83dc-f2ce40671552.png>
>
>
>
>
this one isn't recognizable. A handgrenade? I like the very first one
(toothbrush)

**Comment by kocio-pl** [comment]
Yeah, a hand grenade or something with university. =} I could have drawn it differently, but that would still be not as clear as 1).

**Comment by kocio-pl** [comment]
Just "after" image with 1) - I'm experimenting a lot, my computer is rather slow and after all the shop dot is known:

![chemist-after](https://cloud.githubusercontent.com/assets/5439713/7730794/9a4c3a8c-ff1c-11e4-9038-88f904d40082.png)
