### ISSUE TITLE
Allow customisation of pattern files

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1529]
Currently patterns are PNG and are hard to customise/re-create. Since most symbols will now be SVG (see #1165) and easy customisation is a goal of this style this should also include pattern files.

As there might be problems with SVG versions of patterns (see https://github.com/imagico/jsdotpattern/issues/3) pattern files will probably stay in PNG format also after Mapnik 3 has been released. One solution could be to store the used symbols and the jsdotpattern configuration separately from the PNG file.

**Comment by imagico** [comment]
See also imagico/jsdotpattern#4 and the specific remarks regarding the wetland patterns in https://github.com/gravitystorm/openstreetmap-carto/pull/1497#issuecomment-96428501

**Comment by math1985** [comment]
I would suggest, for the time being, to at least include the source images and (a link to) the script with which they are generated.

I ran into this while trying to solve #1158. I found [this tool](http://www.imagico.de/map/jsdotpattern.php), but it took me too long to find out how to use the tool to generate the required image.

**Comment by matkoniecz** [comment]
> jsdotpattern configuration

It may be a good idea to store also jsdotpattern itself ( https://github.com/imagico/jsdotpattern ). It will ensure that there are no problems with a disappearing project.

**Comment by math1985** [comment]
Note that the licenses are currently not compatible.

**Comment by matkoniecz** [comment]
Yes, it would require either complicating license description (CC0 except X folder that is licensed as...) or somehow saving it separately (what would be quite fragile).

**Comment by imagico** [comment]
Come on guys - everyone is free to fork jsdotpattern or to host a copy for use, it does not make any difference if it is on gravitystorm's or my account.  It is just a tool like others you use during style development (text editor, tilemill, inkscape, gimp, whatever).

And of course (just in case there is any doubt) SVGs generated with jsdotpattern can have any license - this is the free decision of the user.  I did not specify anything about the symbols included but right now i would not consider most of them eligible for copyright anyway.

And yes, generating patterns with jsdotpattern is not really easy, especially with anisotropic patterns like the wetland dash pattern and often requires complicated sequences of relaxation with different settings.  Anyone is welcome to improve usability and algorithms.  But ultimately good design is hard work and only a certain amount of it can be hidden in clever software.

**Comment by math1985** [comment]
> And yes, generating patterns with jsdotpattern is not really easy, especially with anisotropic patterns like the wetland dash pattern and often requires complicated sequences of relaxation with different settings. 

I'm not blaming the software at all, but would it be possible to document somewhere the exact steps or input to jsdotpattern that is necessary to obtain the patterns we are using?

**Comment by imagico** [comment]
I suppose so - it would however be a bit like recording the exact sequence of pen strokes in Gimp  used to draw a sketch...

And at least while using the standard javascript RNG it would still not be exactly reproducible.

**Comment by imagico** [comment]
The wetland/rock/scree symbols are now available and you can record processing steps and save/share them as links.  I have no exact recordings of the patterns used here but the two last examples [on my blog post](http://blog.imagico.de/new-features-in-jsdotpattern-pattern-generator/) are somewhat similar to what is used for the wetland patterns.

**Comment by pnorman** [comment]
I think what would be reasonable is to add 2x (or higher) resolution PNGs for use with "retina" tiles. It's not ideal, but I think the best option to avoid jaggedness at higher DPI.

**Comment by matkoniecz** [comment]
At least svg files should be added. symbols/rock_overlay.png is really hard to modify (tweaking colour etc). SVG file that was used to generate this file would be probably easier to work with.

**Comment by matkoniecz** [comment]
Also, instructions to recreate svgs probably also should be added in a separate tracked file - not hidden as commit comments like https://github.com/gravitystorm/openstreetmap-carto/commit/05462b49a581823d196e31d936a3c0f5ec816243

**Comment by pnorman** [comment]
> Also, instructions to recreate svgs probably also should be added in a separate tracked file

The patterns aren't simply mechanically generated, I've ended up adjusting based on how the pattern looked, and trying the same sequence of operations a couple different times to find the result I liked the best.

**Comment by kocio-pl** [comment]
@matkoniecz +1! If they are complicated, it's even more important to describe them somehow.

[I was asking how we should deal with such documentation](https://github.com/gravitystorm/openstreetmap-carto/pull/1696#issuecomment-131618637) in general, but with no answer to this moment.

**Comment by matkoniecz** [comment]
> The patterns aren't simply mechanically generated, I've ended up adjusting based on how the pattern looked, and trying the same sequence of operations a couple different times to find the result I liked the best.

Imagico added permalinks (see for example http://www.imagico.de/map/jsdotpattern.php#x,512,jdp6894;g,30,32,32;s,jdp33742;s,jdp81637;rx,250,2,32,32;s,jdp28824;s,jdp59702;s,jdp91550;s,jdp27774;rx,250,2,64,64;rd,1,0,0,tree%20pair,1,5,5,0,jdp48960 ).

**Comment by kocio-pl** [comment]
I've just created PR for documenting quarry pattern (https://github.com/gravitystorm/openstreetmap-carto/pull/1859). Is there any other missing pattern documentation or we can close this issue?
