### ISSUE TITLE
use service tag during rendering railway=tram

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1531]
railway=rail with service=yard/siding/spur is rendered as less prominent. The same may be done with railway=tram, currently tram depots with many tracks are rendered as black areas - see http://www.openstreetmap.org/#map=15/50.0327/19.9334 for an example

![selection_002](https://cloud.githubusercontent.com/assets/899988/7489357/1f6093d2-f3d6-11e4-8352-79aa054f1261.png)

**Comment by nebulon42** [comment]
+1
Maybe also the overall colour could be lightened a bit as black is really strong.

**Comment by kocio-pl** [comment]
We have [something like this](http://www.openstreetmap.org/#map=15/52.2976/20.9291) in Warsaw too. I think we can go lighter up to z15 - on higher zoom levels spacing is more visible and we can easily distinguish it from nearby power line, which is good.

**Comment by mboeringa** [comment]
> We have something like this in Warsaw too. I think we can go lighter up to z15 - on higher zoom levels spacing is more visible and we can easily distinguish it from nearby power line, which is good.

@kocio-pl : none of those tram yard lines in your example are tagged with **service=yard/siding/spur**, so unless you fix this, any changes won't have affect on this paricular Warsaw example...

Additionally, I would probably replace **tunnel=yes** with **covered=yes** for those parts of the line inside depots, as these aren't real tunnels (although I don't know if the current carto rendering handles these the same in terms of rendering, I do in my ArcGIS renderer).

**Comment by kocio-pl** [comment]
I can do this, of course (somebody else was working there, so maybe I will let him/her know). I was not talking about the same tagging, but the same situation with rendering artifacts and my intention was to probably not change rendering above z15.
