### ISSUE TITLE
Add special rendering for shop=confectionery

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1534]
My propositions for this icon are: 
1) ![confectionery-14-1](https://cloud.githubusercontent.com/assets/5439713/7497942/bcc7e55c-f41d-11e4-9bef-cf8532b80f28.png)
2) ![confectionery-14-3](https://cloud.githubusercontent.com/assets/5439713/7497945/c039dbe6-f41d-11e4-8d84-a4f7d79e2587.png)

2) is probably better, because it's more readable.

[Mentioned on meta-issue #1460]

**Comment by math1985** [comment]
2) looks like a pretzel to me, which is usually not sweet and thus not confectionery.

**Comment by daganzdaanda** [comment]
Yep, we had the pretzel for bakery up to a few months ago! 
I like the sweet, but it might look a bit small compared to other icons. Also, if you put it in the middle of the 14px box, it will have some extra distance from the label. 
Maybe rotate the sweet by 45° to use more of the space?

**Comment by kocio-pl** [comment]
IMO rotation doesn't help too much - it even does not give us more space: ![confectionery-14](https://cloud.githubusercontent.com/assets/5439713/7506707/aef1bd72-f463-11e4-99e8-139b7ace23fb.png)

**Comment by HolgerJeromin** [comment]
I like the 45° sweet. 
Perhaps a 0° sweet would be better if it would have a round core, too.

**Comment by Stalfur** [comment]
The sweet is nice and something like that is the best bet. The pretzel and the cake remind me more of a bakery.

**Comment by matkoniecz** [comment]
> I like the 45° sweet.
> Perhaps a 0° sweet would be better if it would have a round core, too.

I have the same opinion.

**Comment by kocio-pl** [comment]
OK, so 5) ![confectionery-14-5](https://cloud.githubusercontent.com/assets/5439713/7527581/23e40d06-f51d-11e4-8869-962fb6186553.png) or 3) ![confectionery-14-1](https://cloud.githubusercontent.com/assets/5439713/7506937/c80f7822-f467-11e4-807d-49ea06280a87.png) then?
6) Or maybe this: ![confectionery-14-6](https://cloud.githubusercontent.com/assets/5439713/7527657/175b73b6-f51e-11e4-80d9-22422ea22693.png)?

**Comment by Stalfur** [comment]
5 or 6, 3 looks like a Star Wars tie fighter!

**Comment by kocio-pl** [comment]
Probably the last round then and we're done with it - everybody: 5) 0° sweet or 6) 45° sweet?

**Comment by marcgemis** [comment]
6 for me

**Comment by matkoniecz** [comment]
6 for me

**Comment by imagico** [comment]
I think this whole 'new shop icons' thing is going somewhat in the wrong direction.  The map is widely used by mappers as a substitute for reading the wiki, they see what tagging results in a suitable rendering and tag accordingly.  This is widely known, this is not nice but this is the way it is and it is our task as style designers to take care to minimize the negative side effects of this.

In this example having a sweet used as an icon for confectionery will likely lead people using this tag mostly for candy stores while the term confectionery (and likely the intention of the tag) is more on hand crafted sugary foods - which applies only to a small subset of candy stores.  The wiki also suggests a more specific shop=sweets for such stores.

So when you design icons or create pull requests for adding them please study the wiki and actual use of the tag and make sure the icon is sufficiently selective to the core meaning of the tag.  If this is not possible you should keep the generic icon for this kind of shop.

Using a cake icon would have the same effect w.r.t. shop=pastry.

**Comment by matkoniecz** [comment]
@imagico That is (unfortunately) a good point. Though effects of icons in JOSM are probably even more significant.

**Comment by kocio-pl** [comment]
@imagico 

1) If we took it dead serious, this would invalidate all generic icons or make them overcrowded with elements. What is a "(generic) confectionery item" for you? I guess there's no such single thing - they are all specific.

[I try to avoid mixing generic and specific cases](https://github.com/gravitystorm/openstreetmap-carto/issues/1530#issuecomment-100184221) when possible, but sometimes [reuse is a reasonable approach](https://github.com/gravitystorm/openstreetmap-carto/pull/1522) to take (even if they are just similar objects, not in "general/specific" relation). 

2) Also we're not going to resolve some root problems just like that:

>  The map is widely used by mappers as a substitute for reading the wiki, they see what tagging results in a suitable rendering and tag accordingly. This is widely known, this is not nice but this is the way it is and it is our task as style designers to take care to minimize the negative side effects of this.

In my opinion Wiki in turn is used by mappers as a good old "phone book" substitute for more clear/lightweight/navigable tagging system and I find this problem as important as "mapping for renderer", but much less recognized. And we have to live with them here and now. 

I don't get "minimizing the side effects" as avoiding rendering dubious elements at all costs - because the cost will be unwanted data loss (data not being tagged) or tagging with much less reasonable scheme just to make it show. In many cases we will just not know about that, because this cost is typically hidden. We try to warn users not to blindly follow rendering, and it's good, but we don't talk at all that rendering something people really want to see can actually reduce wrong tagging! Of course it is understandable that developers tend to cut too high expectations of the users, but ultimately our task is also rendering things when needed.

Our database is precious, but so is the motivation for the people to see what they enter, let's not forget about it. Going to extreme - if we would like to avoid all the tagging/rendering risks and really tell "OSM is the data", we should remove the maps from the website and make a big red button "download us!"... =}

3) Designing/drawing/discussing icons takes me so much time, that I forgot to check Wiki for potential clash with other, not popular kinds of shops (that is clearly not the result of tagging for render, because confectionery is highly popular, while sweets is almost not existent, but they are rendered the same). However I like to get the idea first and check/refine/change it later, because first sketch is probably wrong anyway. =}

**Comment by imagico** [comment]
I don't really want to get into an elaborate argument here.  It is fine with me that you like to brainstorm ideas about possible icons for various shops before doing detailed analysis of tag use and wiki.  But if an icon is to make it into the style it should be expected that it passes basic scrutiny in the aspects i mentioned.

Please also keep in mind what @gravitystorm wrote in https://github.com/gravitystorm/openstreetmap-carto/pull/1522#issuecomment-99899938 - a generic shop icon is better than a specific but not well matching one.

Also don't get me wrong, i realize that creating an icon for something like a confectionery within the constraints of a 14x14 pixel image that is recognizable as what shop=confectionery means for people from all over the world is very hard, maybe impossible.  There are tons of things that would be good to change in the style to encourage people to do better mapping but many of them are currently not feasible due to technical or other constraints.  We need to concentrate on things that can be done and that includes not introducing misleading icons.

**Comment by math1985** [comment]
> In this example having a sweet used as an icon for confectionery will likely lead people using this tag mostly for candy stores while the term confectionery (and likely the intention of the tag) is more on hand crafted sugary foods

The tag shop=confectionery is the most used tag for candy shops such as Mr Simms Olde Sweet Shoppe in the UK and Jamin in the Netherlands. I agree the tag needs some discussion on usage, but for now I think a candy is fine.

**Comment by kocio-pl** [comment]
@imagico 

Thanks a lot for bringing up Wiki! You're right, sooner or later I should at least have a look at it, not only at Taginfo.

> Please also keep in mind what @gravitystorm wrote in #1522 (comment) - a generic shop icon is better than a specific but not well matching one.

I wouldn't agree with such rule - there are much more things deserving our attention and nobody tries to warn about them:
1. It may be better, but has anybody realized it may be worse as well? A dot with a "FooBar" name is rather useless, so I prefer something giving me a hint of what kind of shop is it. I would be taking the risk that somebody may not understand exact meaning from the icon, but rendering just the dot (with name) is also not risk free - it is the risk of annoying users by not giving them enough relevant information we already have.
2. I find rendering housenumbers of different POIs instead of their name/icon/dot as misleading as it gets, since it looks like tagging/rendering/tile refreshing artifact (how one could know if it's POI or two buildings drawn in one place?), but that was not generally perceived this way, so "misleading" is a matter of personal taste to some degree. 
3. Not rendering something is also risky, as I wrote in the previous comment. The fact that we probably wouldn't be aware of bad consequences doesn't mean they are smaller and this choice is "safe" - it's just a choice or lack of the resources (which is a common case).

There is also the practical side of decision making. As we have no policy on what and how should be rendered, I try to judge it myself case by case using the brainstorm, but the final say goes to the persons in charge of merging PRs.

> There are tons of things that would be good to change in the style to encourage people to do better mapping but many of them are currently not feasible due to technical or other constraints. We need to concentrate on things that can be done and that includes not introducing misleading icons.

It's not about the things that can't be done - they surely can be done, it's just that no hard 1:1 mapping is possible. Lack of details or taking one element for a symbol of a broader category shouldn't be a base for calling the icon misleading in my opinion, at least not by itself. The problem of generic/specific categories is not the question of technical constraints. Every map is just a highly symbolic and scaled down depiction of reality and so are the icons. They are just the symbols and all of them are arbitrary. But we probably don't want to have the photos instead, not because we can't show them on the map, but they're too detailed, not uniform enough and they would take too much space.

The question "What is a (generic) confectionery item?" is valid even if we have 128x128 matrix or bigger. If there's no such thing, we have to look for a workaround - and we do it already:
1. For convenience store we have something not associated with food or drink, but you can easily say it's misleading, because the baskets are used regardless of shop type (for example in consumer electronics store).
2. For department store we currently use different strategy - a mix of things, which are more or less representative and can also be misleading if the store does not have all the items from the icon.
3. Fire station icon (the strategy of taking one important element, as with candy in this issue) can be misleading - one could think it's a firecamp. And so on.

So even the most popular icons are not that safe and can mean other things. We just learned what given symbol means here and use it accordingly. OSM is growing and the downside is some nice generic things may be divided into more specific categories - let's say for example current airport icon one day will be needed for aircraft hangar or the aircraft works, and what would be the alternative for the airport then?

Just the fact that Wiki or Taginfo says about sweets shop is only a hint that we should think if the difference for users is big enough to consider splitting; once the sweet shops are more used, of course - if ever.

...Sorry for such a long reply, but looking for a good enough icon is one thing, while understanding the rules for that process is quite different beast and I think about it from a point of view, which was probably not fully expressed before.

**Comment by Stalfur** [comment]
Fully agree with @kocio-pl

**Comment by kocio-pl** [comment]
Different idea - not so candy this time ;-) :
7) ![confectionery-14-3](https://cloud.githubusercontent.com/assets/5439713/7557604/057c1866-f795-11e4-8543-b0fb422eefe5.png)
8) ![confectionery-14-10](https://cloud.githubusercontent.com/assets/5439713/7557637/90f06712-f795-11e4-8708-874969358da4.png)
9) ![confectionery-14-5](https://cloud.githubusercontent.com/assets/5439713/7557606/0ba9b2d4-f795-11e4-954a-ec5d203cb456.png)
10) ![confectionery-14-7](https://cloud.githubusercontent.com/assets/5439713/7557609/132c8522-f795-11e4-94cf-aa915ce2678c.png)

I like 10) the most. Comments?

**Comment by dieterdreist** [comment]
2015-05-11 4:26 GMT+02:00 kocio-pl <notifications@github.com>:

> Different idea - not so candy this time ;-) :
> 7) [image: confectionery-14-3]
> <https://cloud.githubusercontent.com/assets/5439713/7557604/057c1866-f795-11e4-8543-b0fb422eefe5.png>
> 8) [image: confectionery-14-10]
> <https://cloud.githubusercontent.com/assets/5439713/7557637/90f06712-f795-11e4-8708-874969358da4.png>
> 9) [image: confectionery-14-5]
> <https://cloud.githubusercontent.com/assets/5439713/7557606/0ba9b2d4-f795-11e4-954a-ec5d203cb456.png>
> 10) [image: confectionery-14-7]
> <https://cloud.githubusercontent.com/assets/5439713/7557609/132c8522-f795-11e4-94cf-aa915ce2678c.png>
>
> I like 10) the most. Comments?
>



from the above I also like 10) the most.
Maybe we should distinguish between baker's confections and sugar
confections, as they typically are different kind of shops, and also for
the clients it matters which kind it is (if you want to buy pastry a candy
store will not do it, and vice versa). The first is probably a synonym for
shop=pastry (a tag I had introduced some years ago because confectionery
seemed to be exclusively about candy, a notion that gets contradicted by
the current en wikipedia article: http://en.wikipedia.org/wiki/Confectionery
and sugar confections are likely a synonym for shop=candy.

**Comment by kocio-pl** [comment]
[The discussion now is on Tagging list](https://lists.openstreetmap.org/pipermail/tagging/2015-May/024374.html) (and rightly so! =} ).

**Comment by kocio-pl** [comment]
I guess there will be no conclusion, but at the same time we could start discussing also removing bakery icon, because they can (and sometimes do) overlap. For me it's better to have generic sweets icon, because it's very popular kind of shop and this icon (10) is not misguiding with relation to this tag, it's just that there may be a lot of localities.
