### ISSUE TITLE
Add special rendering for shop=variety_store

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1536]
1) [My proposition](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-variety_store-icon/symbols/variety_store-14-1.svg) for this kind of shop: ![variety_store-14-1](https://cloud.githubusercontent.com/assets/5439713/7507930/0f03ed02-f478-11e4-9929-92bc450fb223.png)

[Mentioned on meta-issue #1460]

**Comment by HolgerJeromin** [comment]
I read it as a smart phone in landscape mode with a % on the display.

**Comment by kocio-pl** [comment]
I'm quite happy with this icon, given the circumstances, but any other metaphor to test (like typical products found there) or maybe other means of showing "low price"?

**Comment by math1985** [comment]
To me the proposed symbol is not recognizable (but I also don't have an alternative).

**Comment by kocio-pl** [comment]
Other ideas:

2) ![variety_store-14-2](https://cloud.githubusercontent.com/assets/5439713/7518607/50ed2666-f4dc-11e4-9049-27bc74eca0ba.png)

3) ![variety_store-14-3](https://cloud.githubusercontent.com/assets/5439713/7518613/572686d0-f4dc-11e4-89d0-1b8ffe4bbed0.png)

**Comment by pnorman** [comment]
I don't know that we're going to get a suitable icon for this store.

**Comment by kocio-pl** [comment]
It's always the best if you can recognize the item just looking at its icon, but that's not the hard requirement. For example archaeological site icon [was misinterpreted by some of us](https://github.com/gravitystorm/openstreetmap-carto/pull/1518), but that doesn't mean it was useless to have that icon for such an important/popular item. "Suitable" for me means "good enough", not "perfect".

**Comment by matkoniecz** [comment]
In that case none of proposed icon works and I doubt that that there will be good enough to replace generic shop icon.

**Comment by kocio-pl** [comment]
You don't know till you try. =} 

I like the first one and, as I said in [different comment](https://github.com/gravitystorm/openstreetmap-carto/issues/1534#issuecomment-100280638) more or less, I do believe that generic dot is better just from terrible housenumbers for POIs, but much worse than visual hint, even if not recognizable just from the shape. So for me that is a fine (although not great) solution and clearly better than current state.

However I still let the idea grow in my head, so maybe something more relevant for general public can be found. After all, more people tend to discuss tagging schemes, so I'd like more comments to know what works for most users and what not. Maybe some kind of beauty contest is needed to draw enough people attention?

**Comment by Rovastar** [comment]
I too don't think there really is a suitable icon for this. By all means try if you like find one.
True we don't have to get perfect icons just good enough but it needs to be understood by a (the very) least by say 50% of map viewing public and not easily confused with other potential things. I think many of us agree it is not understood clearly enough here.
About the closest in my opinion could be the icon 2 but not all these shops are dollar/pound/euro stores and having numbers looks wrong and should be discouraged.

**Comment by daganzdaanda** [comment]
[The wiki] (http://wiki.openstreetmap.org/wiki/Tag:shop%3Dvariety_store) actually says these are "dollar stores": 
> A variety store or price-point retailer is a retail store that sells inexpensive items, usually with a single price point for all items in the store. Typical merchandise includes cleaning supplies, toys, and confectionery.

In that case, I like the % sign on a tag, but the icon is too busy. Would a transparent % on a filled tag work?
![dollarstore](https://cloud.githubusercontent.com/assets/7693297/7556195/6db2296c-f767-11e4-9caf-cdc1f7908ed1.png) (this is just a quickly pixeled image)

**Comment by math1985** [comment]
As a metaphor for 'discount' % might work. On the other hand, it's a bit ironic that variety_store's are one of the type of stores where you'll never see %-signs in shop, as the prices are fixed (1,00 or 0,99) anyway.

What about the text .99?

**Comment by kocio-pl** [comment]
@daganzdaanda Thanks a lot!

4) ![variety_store-14-4](https://cloud.githubusercontent.com/assets/5439713/7556310/0b671434-f76c-11e4-9136-38aca4392bee.png)
5) ![variety_store-14-5](https://cloud.githubusercontent.com/assets/5439713/7556362/8485d08e-f76d-11e4-8ebc-13f9f3743620.png)
6) ![variety_store-14-8](https://cloud.githubusercontent.com/assets/5439713/7556471/74a728b2-f771-11e4-9a6b-9c64674fe5bb.png)
7) ![variety_store-14-7](https://cloud.githubusercontent.com/assets/5439713/7556432/c56a17f2-f76f-11e4-9570-988c6ee17ad5.png)

For me it's good, especially 6) - 4) was just a test based on 1) and I don't like its proportions now. 

Maybe I should closer resemble your simpler approach to % sign, but this is the moment I'd like to make a real test on the map to know how it all really works, because I don't want it to be too prominent and black on white can look very far from violet on light brown.

**Comment by daganzdaanda** [comment]
Yes, I was thinking the same about there never being a % in a dollar-store. But it does bring across the idea of cheap stuff for me. A transparent -.99 inside a filled tag would work for me, too. 
Agree about testing the ideas on a map. If it's not too much trouble I'd like to see how 6) works, and maybe a -,99 version.

**Comment by kocio-pl** [comment]
Both are acceptable for me - at least until proven otherwise in the field test =} :
8) ![variety_store-14-9](https://cloud.githubusercontent.com/assets/5439713/7565045/eb08553c-f7ec-11e4-9e86-b811f9bcf072.png)
9) ![variety_store-14-10](https://cloud.githubusercontent.com/assets/5439713/7565048/effaaa5e-f7ec-11e4-9caa-9a557d3d1f38.png)

**Comment by kocio-pl** [comment]
Test:

![variety_store-after-z19](https://cloud.githubusercontent.com/assets/5439713/7753814/23db429a-ffe8-11e4-8b53-56a0a86ab849.png)
![variety_store-after-z19-dark](https://cloud.githubusercontent.com/assets/5439713/7753816/27ef5092-ffe8-11e4-9d89-a2db928679b4.png)

I guess darker version is better.

**Comment by HolgerJeromin** [comment]
I like the second one, too. Thanks

**Comment by dieterdreist** [comment]
> Am 21.05.2015 um 18:37 schrieb kocio-pl <notifications@github.com>:
> 
> I guess darker version is better.


+1, but it is not working particularly well

**Comment by daganzdaanda** [comment]
+1 4 2nd, but maybe turn the 99 into right-angled pixel-aligned digital numbers to make them less blurry?

**Comment by matkoniecz** [comment]
It looks like shop for batteries.

**Comment by kocio-pl** [comment]
![variety_store-after-z19-empty](https://cloud.githubusercontent.com/assets/5439713/7797380/8455200e-02eb-11e5-84c5-071e3d39ad18.png)
![variety_store-after-z19-digital](https://cloud.githubusercontent.com/assets/5439713/7797381/89445fee-02eb-11e5-8475-f4328d39ed72.png)

Still like 2nd, but 3rd may be better and 4th are also good for me.
