### ISSUE TITLE
Add special rendering for shop=car_parts

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1537]
1) [My proposition](https://github.com/kocio-pl/openstreetmap-carto/blob/shop-car_parts-icon/symbols/car_parts-14.svg) for this kind of shop: ![car_parts-14](https://cloud.githubusercontent.com/assets/5439713/7517925/2e9c8a2e-f4d8-11e4-92ea-62c30629fc5c.png)

[Mentioned on meta-issue #1460]

**Comment by matkoniecz** [comment]
This icon is not really working for me.

**Comment by kocio-pl** [comment]
One-man survey indicated it would be a scrap, however it's [far in the queue for adoption](http://wiki.openstreetmap.org/wiki/Tag:industrial%3Dauto_wrecker) (about 0,1k...). I was expecting that may be too distant association, so - back to reality:

2) ![car_parts-14-2](https://cloud.githubusercontent.com/assets/5439713/7527867/c3cf9c88-f520-11e4-8c12-5679b7b46291.png)
3) ![car_parts-14-3](https://cloud.githubusercontent.com/assets/5439713/7527962/c26fe04a-f521-11e4-9270-7d0e99958a13.png)
4) ![car_parts-14-4](https://cloud.githubusercontent.com/assets/5439713/7527964/dd702d1e-f521-11e4-9b5f-afdfde230638.png)

**Comment by marcgemis** [comment]
what about a car exhaust or shock absorber ? would that be doable on such a small space ?
I wonder whether I would recognize 2 as a wheel on a map.
and 3 is pretty close to the icon of Mercedes , not ?

**Comment by kocio-pl** [comment]
I doubt car exhaust or shock absorber would work - maybe some photos/icons showing their shape could help here? Another idea is to use spark plug or headlamp, but the first one will be probably too geometric, and lamps have many shapes, not always easy to recognize. 

Maybe old car horn ([like this](https://commons.wikimedia.org/wiki/File:Znak_B-29.svg) or [this](http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/yellow-road-sign-icons-media/001791-yellow-road-sign-icon-media-horn-sc48.png)) would do, because the shape is great, but I have to try if it fits so small matrix well enough.

**Comment by marcgemis** [comment]
http://www.gettyimages.com/detail/illustration/car-parts-performance-icons-royalty-free-illustration/166007126  second on the first row, first on the second row 

fourth on the second row : http://www.gettyimages.com/detail/illustration/car-icon-set-royalty-free-illustration/481131735

**Comment by brycenesbitt** [comment]
I like the car door.

But really: there are many features that should come first.

**Comment by yohanboniface** [comment]
Just in case, the one we made for HDM: ![car parts](https://raw.githubusercontent.com/hotosm/HDM-CartoCSS/master/icons/poi/car_parts-18.png)

https://github.com/hotosm/HDM-CartoCSS/blob/master/icons/poi/car_parts-18.png

**Comment by kocio-pl** [comment]
@yohanboniface Wow, that was great, thanks a lot! =} How did you get this brilliant idea?

So - shameless copy with bold, thin or medium sized signs?:
5) ![car_parts-14-5](https://cloud.githubusercontent.com/assets/5439713/7549386/ae1c5b52-f632-11e4-8c48-59e9bad936ae.png)
6) ![car_parts-14-6](https://cloud.githubusercontent.com/assets/5439713/7549388/b457e158-f632-11e4-9faa-381610e6f4ff.png)
7) ![car_parts-14-7](https://cloud.githubusercontent.com/assets/5439713/7549389/bb899106-f632-11e4-87cb-b9823562b118.png)

I guess I have to test it with real style to know. 6) looks too prominent now, but with different color and among other symbols on the map it may be actually very good!

**Comment by kocio-pl** [comment]
@brycenesbitt 

> But really: there are many features that should come first.

What do you mean exactly? 

I don't have any particular order for designing icons, I just made a list of [the most popular tags with no icon yet](https://github.com/gravitystorm/openstreetmap-carto/issues/1460) (plus one [with possible icons from French style](https://github.com/gravitystorm/openstreetmap-carto/issues/1402)) and try a lot, especially when the comments are mostly negative, until it works or I get stuck. But after that I plan to also draw sketches for other easy/important items ("important objects" not always mean "big quantities"). Do you have any candidates?

**Comment by daganzdaanda** [comment]
The door looked nice, but a car battery really makes more sense for this kind of shop.
I'd go with No. 6.

**Comment by AndiG88** [comment]
With electric cars becoming more popular I'm not sure a battery is the best solution.

http://www.greencarreports.com/news/1096570_about-that-one-tesla-battery-swapping-station-an-update

**Comment by daganzdaanda** [comment]
Hm, yeah, these might become popular in a few years (the example from the link is not open to the public yet). But should we really reserve this icon for future use? Would you then prefer the car door for "car_parts"?

Btw, for idea 2) there is also http://wiki.openstreetmap.org/wiki/Tag:shop%3Dtyres with 5000+ objects.

**Comment by kocio-pl** [comment]
Thanks - so I would definitely reserve kind of 2) for tyres, but don't know what objects would we need for electric cars. Maybe they can be better depicted the other way?

**Comment by kocio-pl** [comment]
The proposition for electric cars charging station is [here](https://github.com/gravitystorm/openstreetmap-carto/issues/989) and looks like a fuel station, so battery is still the best for car parts, I think.

**Comment by kocio-pl** [comment]
Real life test:

![car_parts-large-after-z19](https://cloud.githubusercontent.com/assets/5439713/7749322/ea001d86-ffcc-11e4-9800-5928738d2b42.png)

![car_parts-small-after-z19](https://cloud.githubusercontent.com/assets/5439713/7749330/fe30d7e6-ffcc-11e4-99c8-72df36e3ede9.png)

I prefer the first one, because it's a bit lighter and more crisp, but the second one is not as dark (solid) as I was afraid.

**Comment by daganzdaanda** [comment]
I'm fine with both.
