### ISSUE TITLE
amenity=place_of_worship covering landuse

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#154]
![place_of_worship_area](https://f.cloud.github.com/assets/1190866/1102475/2f5f470a-1823-11e3-98db-518e89a7be0a.png)
http://www.openstreetmap.org/#map=18/49.14/-123.09&layers=D

There are landuse=grass that used to render, but no longer do.

There's also a highway=footway area=yes multipolygon with the same issue, that I'd probably retag, but have left because it's also not rendering.

Cross-referencing #151 for place_of_worship non-building rendering.

**Comment by mkoniecz** [comment]
PoW no longer looks like a building. Is it still a problem?

**Comment by pnorman** [comment]
Fixed - rendering order is now suitable.
