### ISSUE TITLE
Update for DejaVu nearing

### ISSUE THREAD

**Issue by mboeringa** [gravitystorm/openstreetmap-carto#1543]
Hi all,

Not an issue, but to notify you, I noticed on the DejaVu mailing list archive, that there is an update with fixes planned for the DejaVu font next sunday (v2.35):

http://sourceforge.net/p/dejavu/mailman/dejavu-fonts/

Since it seems to be the main font of the style, and DejaVu hasn't been updated since 25-8-2013, it may be worth checking out perhaps once it is released.

**Comment by math1985** [comment]
Thanks for pointing that out!

**Comment by mboeringa** [comment]
I now also found this site I hadn't seen before, of an organization involved in language projects related to developing countries. They have fonts as well, probably for lesser known scripts:
http://scripts.sil.org
May have something interesting for particular cases...

**Comment by pnorman** [comment]
We're not packaging DejaVu with the style, so I don't see that any action is needed here. It will be nice if the new version has better coverage.

If Ubuntu picks up the update in 14.04, then tile.openstreetmap.org servers should pick it up. If they don't pick up the update for 14.04 then it's up to sysadmins if they want to include a more recent DejaVu manually.

When there is a Ubuntu LTS release out with the font, it might be worth taking a look to see if we can drop any of the fallback fonts.
