### ISSUE TITLE
Multiple layers above eachother

### ISSUE THREAD

**Issue by M1dgard** [gravitystorm/openstreetmap-carto#1544]
Complex situations with multiple layers of the public road are not readable on the map.

https://www.openstreetmap.org/#map=19/51.03680/3.70911
This place has 3 layers. A way goes under the building to give access to the public underground bicycle parking of the train station. On street level there is a bus station and tram stop. Above all that is a bridge that gives access to the Virginie Loveling building.

From what I recall, Google Maps solves these kind of problems by providing a layer chooser.

I've attached a quick mockup of multiple layer renderings (composited screenshots from JOSM with the "Mapnik (true)" paint style). Adjacent layers show through with 7.5% opacity.

Layer -1
![1_layer_-1](https://cloud.githubusercontent.com/assets/4283376/7622158/17865b7c-f9cd-11e4-9ed0-9b3243dfc758.png)

Layer 0
![2_layer_0](https://cloud.githubusercontent.com/assets/4283376/7622159/17a654cc-f9cd-11e4-98ba-315553e61b5f.png)

Layer 1
![3_layer_1](https://cloud.githubusercontent.com/assets/4283376/7622160/17a698f6-f9cd-11e4-9e1b-2683c245121c.png)

This may be difficult to implement in the current setup. These situations are becoming increasingly frequent though. Multi-layer renders might be the most straight-forward approach to make such situations understandable from a map.

**Comment by math1985** [comment]
I absolutely agree with the problem described. I'm not sure if it's within the scope of this project, though. Maps generated by this style are not only used on the website, but also in apps, in JOSM, and even in print, so I doubt multi-layer maps would work for all users of our rendering.

**Comment by M1dgard** [comment]
I see, this is a problem for every renderer and maps can be printed. But the restrictions of paper should not stop us from improving digital maps IMHO.

And in JOSM at least you can turn off layers with filters.

**Comment by pnorman** [comment]
A layer chooser is really out of scope for this repo.

One approach if we had a vector tile rendering stack would be to render multiple tile sets on the fly, or re-style in browser on the fly, but that would be more than a year off and still might be out of scope for here.

If you really want to see mapping for complex multi-level scenarios, look at some of the Asia-specific maps.
