### ISSUE TITLE
Drop rendering ref=* on highway=residential

### ISSUE THREAD

**Issue by yarl** [gravitystorm/openstreetmap-carto#1550]
I came up on this when I was browsing map [near Lubartów](http://www.openstreetmap.org/#map=16/51.4628/22.6090). Because of `ref=*` tags, most of `name=*` tags are not rendered.

![screen](http://i.imgur.com/3OFgS8p.png)

In my opinion we sould consider drop rendering of `ref=*` on `highway=residential`. According to [taginfo](http://taginfo.openstreetmap.org/tags/highway=residential#combinations) we have 49345 `highway=residential` + `ref=*` combinations (0.16%).

**Comment by kocio-pl** [comment]
Good idea!

**Comment by math1985** [comment]
Duplicate with #285 - feel free to discuss further overthere.
