### ISSUE TITLE
Support for indoor-level Tag

### ISSUE THREAD

**Issue by saerdnaer** [gravitystorm/openstreetmap-carto#1551]
With more and more people tagging indoor features and using the [level](http://taginfo.openstreetmap.org/keys/level)-Tag the main map database should also import this key to at least be able to hide the complexity and reduce duplicated tagging together with the layer Tag. Compare http://www.openstreetmap.org/#map=18/48.14033/11.55965 as example area with heavy indoor tagging.

Im not sure if a own issue or an comment in #1504 is the right way, but now decided for an own issue.

**Comment by dieterdreist** [comment]
2015-05-15 14:05 GMT+02:00 Andreas Hubel <notifications@github.com>:

> With more and more people tagging indoor features and using the level
> <http://taginfo.openstreetmap.org/keys/level>-Tag the main map database
> should also import this key to at least be able to hide the complexity,
> compare http://www.openstreetmap.org/#map=18/48.14033/11.55965
>
>
there's also the (synonymous) key building:level (used less, but still more
than 10K times): http://taginfo.openstreetmap.org/keys/building%3Alevel

**Comment by HolgerJeromin** [comment]
i am pretty sure most building:level tags are typos and should be building:levels. 
95.39% have a building=* tag

**Comment by HolgerJeromin** [comment]
This whole issue should be closed. 
https://github.com/gravitystorm/openstreetmap-carto/issues/1504#issuecomment-97715323
"the discussion of which tags to "add" is unnecessary, so lets not spend time on it."

**Comment by saerdnaer** [comment]
@HolgerJeromin Thanks for that pointer. The relevant part is "All features will appear when we use --hstore and all keys will be available". This means the level Tag (and all other) willl be in the geo database when #1504 is done. Sorry for the noise.
