### ISSUE TITLE
highway=turning_circle at highway=track way too prominent in z15/z16

### ISSUE THREAD

**Issue by Dusche** [gravitystorm/openstreetmap-carto#1554]
Hey!
Turning circles at the end of highway=track at zoom levels 15/16 look like having a big brown marker on the map. For example look at: http://www.openstreetmap.org/export#map=15/53.1800/8.1988

I would suggest one of these:
a) Use a smaller circle at these zoom levels.
b) Use a lighter brown for the filling.
b) Use a small dashed circle according to the tracktype.

**Comment by math1985** [comment]
Thanks, you're right. I only tested it in rural environments.

**Comment by HolgerJeromin** [comment]
Even in rural areas this is far too big: http://www.openstreetmap.org/#map=15/44.0291/15.2422

**Comment by ximex** [comment]
:+1: 
here an other example: https://www.openstreetmap.org/#map=15/47.9264/16.1542

**Comment by HolgerJeromin** [comment]
On the long run perhaps something for the road reconsidering. @matkoniecz 
A quick fix could reduce the circle.

**Comment by tilmanb** [comment]
I don't know if it is a good idea to even render turning circles on tracks in this fashion. Roads have a displayed width, whereas tracks are linear features in the style.
So if you want to render it at all, I suggest using a linear marker without fill for track turning circles, like
```node[highway=turning_circle] {
  symbol-size:4;
  color: brown;
}```, or whatever is the track color.

**Comment by HolgerJeromin** [comment]
a circle with no fill could be confused with mini-roundabouts. 
But the circle size compared to the line width should be the same proportion as the other road features.

**Comment by math1985** [comment]
Thanks for fixing this!
