### ISSUE TITLE
Render turn restrictions

### ISSUE THREAD

**Issue by socketpair** [gravitystorm/openstreetmap-carto#1556]
Just like http://map.comlu.com

![2015-05-19 03 14 42](https://cloud.githubusercontent.com/assets/1157412/7691608/50ddd024-fdd5-11e4-880b-a7587905931f.png)

**Comment by ximex** [comment]
What if there are more restrictions at one crossing?

And i don't think that it would look pretty in the mapnik style. The strong red and blue color of the signs wouldn't fit to the soft colors oft the streets,...

**Comment by socketpair** [comment]
I don't mean exactly the same as in picture, but to illustrate what I mean.

**Comment by pnorman** [comment]
I'm skeptical on if this can be done, for two reasons.

1. Any rendering needs to fit in with the rest of the style and be cartographically sensible. Are there any general purpose maps which render turn restrictions?

2. Given the basic infrastructure of an osm2pgsql rendering database, I'm not sure it's technically feasible to render turn restrictions oriented correctly. Lua transforms give a faint hope, but even there I'm skeptical. At the absolute best this would be a 4.0+ feature, and probably over a year away.

**Comment by matkoniecz** [comment]
In some places turn restriction density is high and even comlu gives up and is displaying only restriction count for a given node - see http://map.comlu.com/?zoom=19&lat=50.065714&lon=19.924534&layer=OSM%20Standard&overlays=TTT

![selection_003](https://cloud.githubusercontent.com/assets/899988/7696038/d2808c7a-fdf8-11e4-955c-70d7725bb67e.png)


And some places have a high turn restriction density, see for example http://map.comlu.com/?zoom=15&lat=40.66392&lon=-74.20102&layer=Grayscale&overlays=TTT

**Comment by matkoniecz** [comment]
This display works for specialist overlay, but it would fail on general purpose map.

**Comment by matkoniecz** [comment]
Though maybe adding some interesting overlays (like this one or opening hours) to http://openstreetmap.org/ would be a good idea?

It seems to not be proposed to this date: https://github.com/openstreetmap/openstreetmap-website/search?q=overlay&type=Issues&utf8=%E2%9C%93 (note: it would be necessary to check whatever this idea fits plans of that project and is it technically feasible).

**Comment by dieterdreist** [comment]
> Am 19.05.2015 um 00:25 schrieb Thomas Rupprecht <notifications@github.com>:
> 
> And i don't think that it would look pretty in the mapnik style. The strong red and blue color of the signs wouldn't fit to the soft colors oft the streets,...


+1, too much for this style IMHO
