### ISSUE TITLE
Country boundaries not well visible

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#1571]
http://www.openstreetmap.org/#map=6/51.193/10.613

Country boundaries (over Central Europe in particular) are rendered in 1px strokes, and have a color very close to roads (have about the same saturation), so that they are practically not recognizable. Google Maps does a better job here.

**Comment by Sovxx** [comment]
I agree.
Zoom level 7, with more than 1px-borders, is better looking.

**Comment by nebulon42** [comment]
This should be fixed by #1938. Sorry, forgot to add issues to the commit message.

**Comment by jengelh** [comment]
I cannot consider the issue addressed. Compare osmcarto z6 and something of similar size on gmaps:
![z6](https://cloud.githubusercontent.com/assets/8861948/11333034/01d506c0-91cb-11e5-95a4-d2f8a62a2502.png)
![z6g](https://cloud.githubusercontent.com/assets/8861948/11333035/0476ce2c-91cb-11e5-8b56-13c13a8a933d.png)
The country boundary is really hard to make out on osmcarto.

**Comment by math1985** [comment]
@jengelh The update has not been rolled out to the server yet, it should be rolled out soon!
