### ISSUE TITLE
Invalid rendering

### ISSUE THREAD

**Issue by socketpair** [gravitystorm/openstreetmap-carto#1575]
(redirected from https://github.com/mapnik/mapnik/issues/2850 )

http://www.openstreetmap.org/#map=19/56.86427/60.63019

![bug](https://cloud.githubusercontent.com/assets/1157412/7784968/2e4523ba-0194-11e5-8908-1ffc169ca7ea.png)

http://www.openstreetmap.org/node/753494744

**Comment by matkoniecz** [comment]
The same problem as in #481, blocked by https://github.com/mapnik/mapnik/issues/1382
