### ISSUE TITLE
aeroway=apron is labeled by its name= but not its ref=

### ISSUE THREAD

**Issue by dbaron** [gravitystorm/openstreetmap-carto#1583]
http://wiki.openstreetmap.org/wiki/Tag:aeroway=apron says that aeroway=apron should be labeled with the ref= key (like for aeroway=runway and aeroway=taxiway).

For aeroway=runway and aeroway=taxiway, the default maps on http://www.openstreetmap.org/ display the names in ref= but not the names in name=, which is good; it encourages correct tagging.

For aeroway=apron the rendering is the opposite:  the name= is rendered, but the ref= is not.  In other words, this changeset: http://www.openstreetmap.org/changeset/31454072 caused the names of the aprons to stop being displayed on the map.  (Equivalents for runways and taxiways caused them to start being displayed.)

**Comment by math1985** [comment]
The ref tag [was added](http://wiki.openstreetmap.org/w/index.php?title=Tag:aeroway%3Dapron&diff=869988&oldid=238320) in 2013 by user Gorm, seemingly without prior discussion.

The name tag is currently more common than the ref tag.

**Comment by dbaron** [comment]
OK, given that, I reverted the changeset in http://www.openstreetmap.org/changeset/31722774
