### ISSUE TITLE
highway=pedestrian + area=yes overlaps other features

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#1585]
Sorry if it's duplicate (I didn't find another issue for this).

Using a `highway=pedestrian` + `area=yes` seems to overlaps other smaller features/objects in area.
For example, here: http://www.openstreetmap.org/way/347397569#map=19/-24.02485/-46.45930&layers=D
The `barrier=wall` isn't rendered.

This `building` neither: http://www.openstreetmap.org/way/347397894
`pitch`: http://www.openstreetmap.org/way/347397648
`water`: http://www.openstreetmap.org/way/347397645
etc

Shouldn't they appear on top of the highway area?

**Comment by dieterdreist** [comment]
> Am 26.05.2015 um 13:44 schrieb Nelson A. de Oliveira <notifications@github.com>:
> 
> The barrier=wall isn't rendered.
> 


rendering bug IMHO 


> This building neither: http://www.openstreetmap.org/way/347397894
> pitch: http://www.openstreetmap.org/way/347397648
> water: http://www.openstreetmap.org/way/347397645
> etc
> 


these are mapping bugs IMHO, as none of them is a pedestrian area they should be excluded (MP)

**Comment by naoliv** [comment]
But isn't it similar to have a full area mapped with `landuse=grass` or `natural=grassland` with a building, water or something else on it?

**Comment by HolgerJeromin** [comment]
this is probably #688

**Comment by math1985** [comment]
Duplicate with #688 and #528.

**Comment by dieterdreist** [comment]
> Am 26.05.2015 um 13:55 schrieb Nelson A. de Oliveira <notifications@github.com>:
> 
> But isn't it similar to have a full area mapped with landuse=grass or natural=grassland with a building, water or something else on it?
> 


it depends on the meaning of the tags, inside a grassland you might find all kind of other things while I'd read landuse=grass as a surface with grass where I would expect buildings or water to be cut out

**Comment by naoliv** [comment]
> I'd read landuse=grass as a surface with grass where I would expect buildings or water to be cut out

Sure, it makes sense (and I also agree that the mapping could be improved in OSM), but it's not how I see most people mapping here in Brazil (ie, they draw a big area (a `park`, `natural=something`, `landuse`, etc) and then the other small objects on top of it, without using any kind of relation to represent the inners and outers.

**Comment by dieterdreist** [comment]
> Am 26.05.2015 um 19:08 schrieb Nelson A. de Oliveira <notifications@github.com>:
> 
> it's not how I see most people mapping here in Brazil (ie, they draw a big area (a park, natural=something, landuse, etc) and then the other small objects on top of it, without using any kind of relation to represent the inners and outers.


for a park it is rare to have holes

**Comment by naoliv** [comment]
Shouldn't churchs, for example, be a hole in the park?

**Comment by dieterdreist** [comment]
> Am 26.05.2015 um 19:15 schrieb Nelson A. de Oliveira <notifications@github.com>:
> 
> Shouldn't churchs, for example, be a hole in the park?

if they are in the park I'd say not, if you have to leave the park then yes ;-)
I've never seen a church in the park (well, maybe it can happen with villas, gardens of castles etc. and in these cases I'd keep them in)
