### ISSUE TITLE
Zoom level for amenity=hunting_stand

### ISSUE THREAD

**Issue by wolfbert** [gravitystorm/openstreetmap-carto#1587]
Hi, 

since recently, amenity=hunting_stand is rendered. However, this happens starting with zoom level 16, which I think is quite early for a relatively insignificant feature (which may occur in large numbers and with only a few hundred meters in between). Hunting stands are now treated like bus stops, churches and fire stations. My proposal would be to show them only from level 17 or 18.

I've mapped a few at http://www.openstreetmap.org/#map=16/48.3033/15.8007 (much more often they can be found in forests, see http://www.jan-kretschmer.de/photo/hochsitzallee.htm for a gallery).

**Comment by kocio-pl** [comment]
Is this really a problem? I guess they are located in some remote places, where there are not too other much objects, and are their density is not even close to shops or other amenities in cities. Looking at your image I see nothing wrong with it - they are good orientation points in this case.

**Comment by wolfbert** [comment]
Well, it's a matter of relative importance (and of personal preference, of course). Hunting stands may be useful on a detailed level (for hunters or occasionally close range orientation). The question is, when does the value gained outweigh the cost of cluttering up the map with unneeded information? Personally, I'd go for level 17, but hopefully we can get a few more opinions.

**Comment by kocio-pl** [comment]
For me only 4 stands in otherwise empty area (just landuses and highways) has nothing to do with cluttering anything (farmland? forest?). I'm not aware of places where can be much more of them to even start being a problem as it may be [in some cities](https://github.com/gravitystorm/openstreetmap-carto/issues/1560). But that's just my opinion, of course.

**Comment by ximex** [comment]
If you think that this are many look here: http://www.openstreetmap.org/#map=16/47.8927/16.1270
There are many hunting stands mapped arround. I think zoom 16 is OK. Zoom 17 is OK too. But zoom 18 is too late

**Comment by dieterdreist** [comment]
> Am 26.05.2015 um 21:27 schrieb Thomas Rupprecht <notifications@github.com>:
> 
> There are many hunting stands mapped arround. I think zoom 16 is OK. Zoom 17 is OK too. But zoom 18 is too late


I think they could be rendered from z15

**Comment by wolfbert** [comment]
Besides real estate, one has to take into account relevancy for users at a given zoom level and consistency in importance with everything else that is shown. 

@dieterdreist: they would then appear together with wind power generators... see paragraph above ;-)

**Comment by dieterdreist** [comment]
> Am 26.05.2015 um 22:38 schrieb wolfbert <notifications@github.com>:
> 
> @dieterdreist: they would then appear together with wind power generators... see paragraph above ;-)


they're kind of "emergency" shelter and always far from other pois / dense areas

**Comment by kocio-pl** [comment]
As of relevancy for users - I guess hunters will find it more relevant if rendered earlier to find them easier.

**Comment by wolfbert** [comment]
Regarding hunters, it probably depends on local law. Over here, hunters are often assigned fixed areas of land which they know intimately. In more liberal (and larger) countries, hunters might be allowed into areas they are not familiar with. 

Looking at the discussion, I think the options are to either try z17 and see what happens or wait another year until more hunting stands have been mapped and see how this works out.

**Comment by lest69** [comment]
z16 seems fine to me. Like kocio-pl mentioned, they can be good orientation landmarks, especially in cases like your example where they're in the middle of farm fields. Unless there are areas where they're denser than in ximex's example, I don't see a problem.

**Comment by matkoniecz** [comment]
z16 seems fine. Even the worst found example ( http://www.openstreetmap.org/#map=16/47.8927/16.1270 ) seems to be OK.

**Comment by cepesko** [comment]
After having added quite a number of hunting_stands,  to me the symbol appears to be much too prominent on carto.
The color black as well as the size are imho too dominating. At least changing the colour to the brown of other amenities (bench, shelter) would be a good step.

**Comment by kocio-pl** [comment]
This is usually the outdoor stuff and I have no problem with it, since it does not make clutter and are not competing with anything. What initial zoom level would you suggest?

I guess color is OK, however brown also makes sense for me (this does not have to be amenity open for everybody to be still kind of amenity).

**Comment by cepesko** [comment]
Hi cocio, 
It's not at all a matter of competing. It's true that hunting-stands are usually in remote areas.  It's just about good style. The contrast with black is just too strong and hurts the eye. The dominating black colour should be reserved for names and important pois. Brown (like shelter or bench) or even the dark green of the picknick-site would be a more decent alternative. 
z17 would probably be just enough, since the use of hunting_stands is limited to the group of hunters. And hunting_stands are more useful for close-range orientation than for far ranging directions. 
Plus, very often carto tiles get a layer on top with black as the main colour, so choosing one of the "nature colours" would be a nice evolution.

**Comment by kocio-pl** [comment]
I understand. I feel perfectly fine with current zoom level, nothing even close to hurting my eyes in some dense stand areas. We try to use colors semantically - brown means something that you can generally use, while grey (`man-made-icon` is `#555`) is for orientation points, which suits this use case better I think.

**Comment by jeisenbe** [comment]
It could be argued that man-made gray should be a little lighter.

I’ve noticed that towers, cranes and telescopes look a little strong. It
might work to try something like the tone of gray used by the HDM /
Humanitarian style for POIs?

**Comment by kocio-pl** [comment]
I makes sense to do some testing, because lighter man made gray sounds good to me.

**Comment by jeisenbe** [comment]
I like option 3 best (#777777)

**Honolulu, z14** - 4 towers
https://www.openstreetmap.org/#map=14/21.3049/202.1434
1) Original, #555
![honolulu-z14-555](https://user-images.githubusercontent.com/42757252/48135627-ca563880-e2e0-11e8-8520-5def12d3b420.png)

2) Slightly lighter #666666
![honolulu-z14-666666](https://user-images.githubusercontent.com/42757252/48135636-d3dfa080-e2e0-11e8-9c05-1cb36bbd7e2b.png)

3) Lighter gray, lucky #777777
![honolulu-z14-777](https://user-images.githubusercontent.com/42757252/48135642-d80bbe00-e2e0-11e8-8f1f-fd144a44e768.png)

4) Even lighter #888
![honolulu-z14-888](https://user-images.githubusercontent.com/42757252/48135852-75ff8880-e2e1-11e8-96a9-fc312c7bad4e.png)


**Ala-Wai Park** - stadium lights
https://www.openstreetmap.org/#map=18/21.28711/202.17081
1) #555
![alawai-z18-555](https://user-images.githubusercontent.com/42757252/48135822-5e280480-e2e1-11e8-804e-1f9662901e4c.png)

2) #666666
![alawai-z18-666666](https://user-images.githubusercontent.com/42757252/48135835-6aac5d00-e2e1-11e8-8f10-b5c48e001309.png)

3) #777777
![alawai-z18-777](https://user-images.githubusercontent.com/42757252/48135849-74ce5b80-e2e1-11e8-8896-3e081b4049ef.png)

4) #888
![alawai-z18-888](https://user-images.githubusercontent.com/42757252/48135859-7ac43c80-e2e1-11e8-9cd1-1d95ecbc79c2.png)


**Diamond Head Lighthouse***
https://www.openstreetmap.org/#map=15/21.2574/202.1878
1) #555
![diamond-z15-555](https://user-images.githubusercontent.com/42757252/48136224-72b8cc80-e2e2-11e8-841f-34ba03288dae.png)

2) #666666
![diamond-z15-666666](https://user-images.githubusercontent.com/42757252/48135915-a21b0980-e2e1-11e8-892e-4c7d061c96ac.png)

3) #777777
![diamond-z15-777](https://user-images.githubusercontent.com/42757252/48136503-27eb8480-e2e3-11e8-9a79-07ed68ea13db.png)

4) #888
![diamond-z15-888](https://user-images.githubusercontent.com/42757252/48135905-9d565580-e2e1-11e8-8d5d-0658ccec98df.png)

**Mauna Kea Telescopes**
1) #555
Stop me if you've seen this one before...
![maunakea-z16](https://user-images.githubusercontent.com/42757252/48135949-c1199b80-e2e1-11e8-9375-c6b07e1aed58.png)

2) #666666
![maunakea-z16-666666](https://user-images.githubusercontent.com/42757252/48135961-cbd43080-e2e1-11e8-81df-42e094676fdd.png)

3) #777777
![maunakea-z16-777](https://user-images.githubusercontent.com/42757252/48135970-d1ca1180-e2e1-11e8-9f8b-fcfd4cb97fe5.png)

4) #888
![maunakea-z16-888](https://user-images.githubusercontent.com/42757252/48136044-ff16bf80-e2e1-11e8-924e-3be3a7c74980.png)


**Hunting Shelters** https://www.openstreetmap.org/#map=16/47.8931/16.1289
1) #555
![shelters-z16-555](https://user-images.githubusercontent.com/42757252/48137119-b280b380-e2e4-11e8-8165-bea04d9392f3.png)

2) #666666
![shelters-z16-666](https://user-images.githubusercontent.com/42757252/48137125-b57ba400-e2e4-11e8-8adb-d6cb6555fd96.png)

3) #777777
![shelters-z16-777](https://user-images.githubusercontent.com/42757252/48137151-be6c7580-e2e4-11e8-9275-d85ea649036b.png)

4) #888
![shelters-z16-888](https://user-images.githubusercontent.com/42757252/48137139-b9a7c180-e2e4-11e8-9779-9e7d9b4b5985.png)

**Comment by matkoniecz** [comment]
Please, open a new issue for new issues

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Nov 2018, at 15:29, jeisenbe <notifications@github.com> wrote:
> 
> Ala-Wai Park - stadium lights


the icon is much too heavy visually for these, generally light objects, IMHO. Did you try a mast without the base?
