### ISSUE TITLE
Add special rendering for shop=beverages

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1592]
Mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/1460

My propositions (derived from Osmic icon for alcohol shop) are:
1) ![beverages-14-1](https://cloud.githubusercontent.com/assets/5439713/7835199/358478a2-0477-11e5-9e98-2f1dbf6df8ca.png)
2) ![beverages-14-2](https://cloud.githubusercontent.com/assets/5439713/7835251/8621a226-0477-11e5-937e-88d5214fd3f2.png)
3) ![beverages-14-6](https://cloud.githubusercontent.com/assets/5439713/7835321/32bfedee-0478-11e5-8b70-06b1032b46be.png)

I guess 3) is the best.

**Comment by nebulon42** [comment]
The straw or something similar might help to differentiate from alcohol shop though.

**Comment by kocio-pl** [comment]
Then I would go for 2) - with higher glass.
