### ISSUE TITLE
Stop rendering historic=castle_walls

### ISSUE THREAD

**Issue by StyXman** [gravitystorm/openstreetmap-carto#1598]
Simple reasons:
* There are [two](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L565) [layers](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L591) trying to render it.
* The value is not listed in [the OSM wiki](http://wiki.openstreetmap.org/wiki/Key:historic).
* There is not even a [tag page](http://wiki.openstreetmap.org/wiki/Tag:historic%3Dcastle_walls) for it.
* There are [17 ways in the whole planet](http://taginfo.openstreetmap.org/tags/?key=historic&value=castle_walls#overview) which probably can be retagged as citywalls.

**Comment by math1985** [comment]
Good point! Care to write a pull request for it by any chance? You seem to understand the relevant code.

**Comment by StyXman** [comment]
I'm on it.

**Comment by dieterdreist** [comment]
> Am 30.05.2015 um 21:39 schrieb Marcos Dione <notifications@github.com>:
> 
> There are 17 ways in the whole planet which probably can be retagged as citywalls.


I guess not, it's not the same feature

**Comment by StyXman** [comment]
I guess castle walls should be part of the castle's polygon, then. I hadn't had the time to find them and see what they are. Talk about finding a needle in a haystack...
