### ISSUE TITLE
Enhance contrast between trunks and vegetation

### ISSUE THREAD

**Issue by ftrebien** [gravitystorm/openstreetmap-carto#1600]
In lower zoom levels, trunks practically disappear within areas with mapped vegetation. An example is the A134 highway in England: http://www.openstreetmap.org/#map=10/52.4740/0.6880

I understand that, at very low zoom levels, trunks need to be lighter in order to highlight motorways. But beginning at zoom level 7, they are probably less evident than primaries, and also easily confused with nature reserve contours: http://www.openstreetmap.org/#map=7/51.642/-1.824

One possible reason is that trunks are too bright. A similar shade with luminance (CIELab) between that of motorways and primaries is 0x77b677.

**Comment by math1985** [comment]
Duplicate with #102.
