### ISSUE TITLE
Buildings are covered by road with tunnel=yes

### ISSUE THREAD

**Issue by rza31** [gravitystorm/openstreetmap-carto#1609]
Hello,

if a tunnel cross a building the building is covered from the highway with tunnel=yes.
Example:
https://www.openstreetmap.org/way/23728286#map=17/48.75380/8.23714

see also https://lists.openstreetmap.org/pipermail/talk-de/2015-June/111347.html

Thanks, Matthias

**Comment by HolgerJeromin** [comment]
somewhat duplicate with #688

**Comment by rza31** [comment]
https://github.com/gravitystorm/openstreetmap-carto/issues/688 is the same tag but another situation.
My example is a road tunnel through a mountain the buildings are on the top.
At the moment there is no mapping on the ground, a underground tunnel is not over buildings.
With layer=-1 / -2 you can it classify  as underground tunnel rendering transparent.

By openstreetmap.de are the buildings correctly over the tunnel:
http://www.openstreetmap.de/karte.html?zoom=17&lat=48.75449&lon=8.2349&layers=B000TT

**Comment by scaidermern** [comment]
It looks very weird when having both buildings and pedestrian areas on top of tunnels. The tunnel is drawn below pedestrian areas but above buildings:
http://www.openstreetmap.org/way/4639799#map=18/51.04115/13.73353
http://www.openstreetmap.org/way/4715664#map=18/51.04115/13.73353

The same area does indeed look nicer on openstreetmap.de, except for the construction site: http://www.openstreetmap.de/karte.html?zoom=17&lat=48.75449&lon=8.2349&layers=B000TT

**Comment by matkoniecz** [comment]
I am not convinced that it is a bad thing. Rendering tunnels under building also would be OK, but there would be different negative consequences (tunnels would be completely hidden on areas with many buildings).

@rza31 

>  With layer=-1 / -2 you can it classify as underground tunnel rendering transparent.

Negative layer is not indication that something is underground.

**Comment by matkoniecz** [comment]
@rza31 

German style is not rendering buildings on top of tunnels, it is using transparency and renders both.

http://tools.geofabrik.de/mc/#17/51.5089/-0.0304&num=2&mt0=mapnik&mt1=mapnik-german

**Comment by rza31** [comment]
@matkoniecz 
It's the opinion from the carto-builder to build here own style. But i am not for rendering underground objects over buildings. This is my Opinion. I don't know about the technical behind the map. I see only the user-site.

**Comment by pnorman** [comment]
Rendering tunnels above buildings is an intentional choice (#623) which avoids problems elsewhere considered worse

As always, PRs will be evaluated if anyone wants to provide them. Just remember, transparency is not an option for reasons articulated elsewhere.
