### ISSUE TITLE
aeroway=parking_position is not being rendered - Should be the same as aeroway=gate

### ISSUE THREAD

**Issue by javbw** [gravitystorm/openstreetmap-carto#1610]
aeroway=gate is for where the plane parks and it is directly serviced via a permanent movable walkway (Skyway)  and people walk directly into the terminal. Gates are rendered properly. However, it's twin brother "parking position" is not. Many airports have parking positions not just for cargo planes, but for new cheaper terminals (like the new "Low Cost Carrier" Terminal 3 at Narita), as gates are expensive to build, so they have parking positions instead and make passengers walk out of the terminl onto the apron, and use portable stairs to get on the plane.

A JetStar plane sitting at a terminal 3 "parking position" while a JAL plane is at a Terminal 3 "gate" (positions 77 and 78) :
http://cache1.asset-cache.net/gc/467471528-jetstar-japan-co-aircraft-front-sits-parked-gettyimages.jpg?v=1&c=IWSAsset&k=2&d=GkZZ8bf5zL1ZiijUmxa7QZEiA2NUUpNnis9Bbrez5W1ueM149NGxeSt152aR3fyadKN39jP0Op2rZkCAjB5Y%2Bw%3D%3D

http://www.openstreetmap.org/#map=17/35.77961/140.38766

This means that both gates and parking positions *need* to be rendered at all airports. 

Many commuter terminals or rural airports are all "parking positions" - no gates.

This distinction between skyway access and portable stair access can be seen in the OSM wiki page http://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dparking_position (as I found it).

Please render aeroway=parking_position as the same as aeroway=gate. I'm correcting a whole lot of "tagging for the renderer" at Narita Airport simply because of this issue (if I am following the wiki correctly) - but this means that all cargo parking positions and most terminal 3 "gates" are not rendered - which is not good. 

Javbw

**Comment by pnorman** [comment]
The common case is that this would result in duplicating the number, e.g. at 
![image](https://cloud.githubusercontent.com/assets/1190866/8196748/0c31b2d0-1444-11e5-9ada-b2bb4f635fa5.png)

the plane is in parking position 4, for passengers to board from gate 4.

**Comment by mboeringa** [comment]
> The common case is that this would result in duplicating the number, e.g. at

I am not an aviation expert, but judging by the Wiki link the OP posted, the Wiki clearly states:

"*If the parking position is at a aeroway=gate/skybridge, the ref=x is usually the same as the gate's ref.* ***But it can sometimes be, typically on larger airports, different from the gate it is serving.***"

So rendering it does make sense (even ignoring the case made by the OP for non-skyway access).

**Comment by gravitystorm** [comment]
The parking reference for the planes themselves (e.g. 504 for Terminal 5, Gate 4 at LHR) is not of general interest to the public, since they are for aircraft operations and don't appear on e.g. boarding passes or TV screens. The same goes for when you take a bus to a non-skybridge parking place. When you walk there from the terminal, you don't get a choice of places to go to, you have to go to a particular plane, so again the reference is not useful to the public.

So I think the parking_place and its reference are for a special-interest map, not for here.

**Comment by javbw** [comment]
Okay, i think i understand my error - i reread gates and parking position. I was focused more on the description from aeroway=gate: "the gates that aeroplanes use" so i assumed this was for mapping where the airplane parks, not where the people are. This was an incorrect assumption on my part based on the wikis wording. I will make the wiki page clearer.

Second - how do we handle parking positons for cargo aircraft then?  There are 50 cargo parking psotions at Narita which are serviced by cargo trucks, but have no gate. 

Should i choose gate for them as well (as they were tagged as gate so they were rendered)  or is there another tag needed (aeroway=cargo_something), so gates can get thier own prominent rendereing, parking position can be left unrendered and different, and cargo terminals can have their cargo plane parking spots rendered (perhaps with a lower opacity label, since its of less importance than the gates for travelers)? 

I understand (now) not wanting the confusion of rendering parkig positon refs if it conflicts with or duplicates the gate's ref, but that leaves a lot of gargo terminals and their "gates" unrendered - or do we lump cargo spots in with gates?

**Comment by gravitystorm** [comment]
I suspect (but I seek opinions) that again, the parking positions of cargo airplanes are not something for a general-purpose map style.

**Comment by javbw** [comment]
> On Jun 18, 2015, at 8:27 PM, Andy Allan <notifications@github.com> wrote:
> 
> I suspect (but I seek opinions) that again, the parking positions of cargo airplanes are not something for a general-purpose map style.
> 
> 

I think you are spot-on about mapping the gates vs the parking positions for the gates for passenger service terminals.

However, there are large sections of airports - usually whole "terminals" - which would then have a huge apron rendered but nothing mapped inside.


This is the south cargo terminal at Narita. 

http://www.openstreetmap.org/#map=16/35.7501/140.3941 <http://www.openstreetmap.org/#map=16/35.7501/140.3941>

This is the north cargo terminal at Narita. 

http://www.openstreetmap.org/#map=16/35.7709/140.3783 <http://www.openstreetmap.org/#map=16/35.7709/140.3783> (still has “gate” tags on the positions). 

I think that these are representative of a lot big airports that have cargo terminals. And (some) mappers are currently mapping the cargo parking spots as “gates” for them to be rendered. 

you can see that, in this case, they are well away from the purple “terminals” - as the cargo ramps don’t really have terminal buildings.

These cargo terminals are usually present at most international airports , but usually on the other side of the runway or not near the passenger terminals, so labeling their parking positions shouldn’t be too much of a bother if the definition of the tag is:

 “aeroway=cargo_parking_Position : a stand-alone parking position without skyway access meant specifically for cargo airplanes. Usually found on the apron in front of cargo terminals” 

should cause minimal or no interference with passenger “aeroway=gate” tag renderings, especially if it has a softer color rendered number. 


Javbw

**Comment by lest69** [comment]
>However, there are large sections of airports - usually whole "terminals" - which would then have a huge apron rendered but nothing mapped inside.

I don't see this as being a problem. If there's nothing of interest to the average map viewer in that apron area, then there's nothing wrong with not rendering anything there.

I also don't see any need for a new tag for cargo-specific parking positions. [aeroway=parking_position](https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dparking_position) is already documented as defining either a passenger or cargo aircraft parking position. I would say that all the parking positions at Narita - regardless of aircraft type - should be tagged as aeroway=parking_position with the appropriate refs, and none of them should be rendered in this style.

If you do want to add more detail to the parking positions, I would suggest aeroway=parking_position along with parking_position=* as a more logical tagging scheme.

**Comment by javbw** [comment]
> On Jun 19, 2015, at 2:40 AM, lest69 <notifications@github.com> wrote:
> 
> If you do want to add more detail to the parking positions, I would suggest aeroway=parking_position along with parking_position=* as a more logical tagging scheme.

That is a very good suggestion.

Javbw

**Comment by javbw** [comment]
I'm going to open a thread on the tagging list for differentiation of parking position. 

parking_position=gateless or parking_position=cargo or similar to differentiate parking positions that are not served by a skyway or a bus gate for passengers. I will come back when I have an approved tagging solution for rendering.

**Comment by javbw** [comment]
Just as an FYI - I realized that the zoom level for rendering the gate numbers is so high that only part of a single large terminal is visible on the screen at one time - at a zoom level where you could see the multiple terminals or the whole airport, the gate numbers are not rendered.  Unless the person zooms in on the terminal and then scrolls across the runway to the cargo parking (away from the purple terminal buildings), they would never see the cargo positions rendered.
