### ISSUE TITLE
Odd coalescing of name

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1614]
landcover-low-zoom has the SQL

``` sql
(SELECT
    way, name, way_pixels,
    COALESCE(landuse, "natural") AS feature
  FROM (SELECT
      way, COALESCE(name, '') AS name,
      ('landuse_' || (CASE WHEN landuse IN ('forest') THEN landuse ELSE NULL END)) AS landuse,
      ('natural_' || (CASE WHEN "natural" IN ('wood') THEN "natural" ELSE NULL END)) AS "natural",
      way_area/(!pixel_width!*!pixel_height!) AS way_pixels
    FROM planet_osm_polygon
    WHERE (landuse IN ('forest')
      OR "natural" IN ('wood'))
      AND way_area/(!pixel_width!*!pixel_height!) > 0.01
    ORDER BY z_order, way_area DESC
  ) AS landcover_low_zoom
) AS features
```

The `COALESCE(name, '') AS name` construction originated sometime between v2.15.0 and v2.14.0, but I can't track down exactly where. We were using a JSON MML at the time, not YAML, so `git blame` and other tools are not useful here.

**Comment by gravitystorm** [comment]
First appears in 4f79e49d5bcd75eeab8e8b076aed4b4497dd67ee (found using git bisect)

**Comment by pnorman** [comment]
It looks like I added it because of the problems with checking if something is null in some versions of carto at the time.

**Comment by kocio-pl** [comment]
@pnorman What do you think about it now? Should it be changed somehow?

**Comment by pnorman** [comment]
Yes, if we don't need it, it should be removed.
