### ISSUE TITLE
Add special rendering for shop=tobacco and shop=e-cigarette

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1618]
First sketch is straightforward, but may work well for both types:
[1)](https://github.com/kocio-pl/openstreetmap-carto/blob/icons/symbols/tobacco-14-1.svg) ![tobacco-14-1](https://cloud.githubusercontent.com/assets/5439713/8331342/effb1b66-1a87-11e5-8b42-69c5c8a7de58.png)

**Comment by lest69** [comment]
It's recognizable for me.

**Comment by kocio-pl** [comment]
We should decide if we want it just for shop=tobacco or maybe for shop=e-cigarette too, since the later is just proposed on Wiki and is used only 304 times. However I'm not aware of any osm-carto policy regarding Wiki or Taginfo and we may decide differently if we think it makes sense.

**Comment by kocio-pl** [comment]
Small variation:
2) ![tobacco-14-2](https://cloud.githubusercontent.com/assets/5439713/8358782/87356038-1b62-11e5-8bd8-f8fdc1be55ee.png)

**Comment by dieterdreist** [comment]
sent from a phone

> Am 25.06.2015 um 13:25 schrieb kocio-pl <notifications@github.com>:
> 
> decide if we want it just for shop=tobacco or maybe for shop=e-cigarette too


around here these are distinct shops, and the smokers won't find what they need at a vaporizer shop and the people inhaling vapors won't want stuff that burns and smokes.
Pharmacies are selling nicotine products as well, but we don't render them as tobacco shops ;-)

**Comment by kocio-pl** [comment]
In real life the distinction between many types of shops are more or less shady, even when we think it should be clear (convenience can be like groceries+newsagent+cafe...). Also when you look for a shoes, it is different when you're a women and need some fashion shoes instead of general ones, but currently we're agnostic regarding it and show men's shoe icon. 

On some level tobacco and e-cigarettes are both "for smokers" and they can use the same icon to give you a hint what kind of shop is it: not necessary the exact type, because - as I said few times already in the past - icons are just the abstract hints hiding many details by design.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 26.06.2015 um 17:02 schrieb kocio-pl <notifications@github.com>:
> 
> On some level tobacco and e-cigarettes are both "for smokers" and they can use the same icon to give you a hint what kind of shop is it: not necessary the exact type,


this was also discussed on tagging, both are shops dedicated to nicotine addicts, but vapor is not "smoke", neither technically nor legally.

**Comment by kocio-pl** [comment]
OK, so I have no problem leaving e-cigarettes for have some other icon - one day maybe - and stick with this icon to just tobacco shops (once we manage to make some agreement about new icons <5k uses with @math1985).

**Comment by yarl** [comment]
What about cigarettes vending machines? [over 11k](http://taginfo.openstreetmap.org/tags/vending=cigarettes) usages.

**Comment by kocio-pl** [comment]
We have no rule for vending machines yet. I rather think it's more interesting for the typical user to know what she can buy or do there (like laundry or post terminals) than if it's a regular shop or just a machine, so it makes sense to me to show them too, but it probably depends on database reload (to have vending=* key available).

**Comment by kocio-pl** [comment]
Do we really don't want shop=e-cigarette to not have the same icon as shop=tobacco? If so, I would close this issue.

**Comment by dieterdreist** [comment]
2016-09-21 0:12 GMT+02:00 kocio-pl <notifications@github.com>:

> Do we really don't want shop=e-cigarette to not have the same icon as
> shop=tobacco? If so, I would close this issue.




e-cigarette shop are different shops in that they often don't sell common
tobacco / cigarettes, therefor it would make sense for customers to be able
to distinguish them on the map.

**Comment by kocio-pl** [comment]
On the other hand I can't think of any special shape for e-cigarette shop - for me it's rather all "for smokers",  whether it's this way or the other and that's the level of abstraction I feel it. I also suspect that some e-cigarette shops may be mistagged as a shop=tobacco. [Wiki page says](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dtobacco) "Use shop=e-cigarette for shops that sell only electronic cigarettes", so when they are mixed, I would made it shop=tobacco as more general category with new subtype included.

Still the e-cigarette tag is still not popular enough, despite having its own wiki page, and current trend tells that it needs a long time to catch up with 2k+ uses, so that's a future problem and I will close this issue for now - it can be reopened any time later.

![taghistory 1](https://cloud.githubusercontent.com/assets/5439713/18708977/f3a592dc-7ffd-11e6-8d39-65951d8c5d85.png)

**Comment by HolgerJeromin** [comment]
@kocio-pl could you try the tabacco icon without the ash part for e-cigarette? I mean a solid line. perhaps too subtle, but perhaps worth a try.

**Comment by kocio-pl** [comment]
Sure:

3) ![tobacco-14-3](https://cloud.githubusercontent.com/assets/5439713/18715535/fc64bac6-8019-11e6-9b97-424ffcb22af2.png)
