### ISSUE TITLE
Avoid rendering waterway=ditch at low zooms

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#1623]
https://www.openstreetmap.org/#map=14/51.4958/9.7228
I feel that rendering all the nameless ditches at zoom <= 15 is unnecessary and should be inhibited. There is not nearly as much water in the overall area as the rendered tiles would suggest (in fact, it's pretty much indistinguishable from waterway=stream objects).

**Comment by matkoniecz** [comment]
Duplicate of "Render waterway=ditch thinner and only from zoom 16 onwards #1101"
