### ISSUE TITLE
render highway=unclassified different from highway=residential

### ISSUE THREAD

**Issue by yopaseopor** [gravitystorm/openstreetmap-carto#1627]
Here in Spain we have some governments that have power to manage roads. At the last levels we have unclassified (in some cases are like paved with asphalt track or some roads that are made quickly and without a big planning) . In some Spanish areas these are the real network that vertebrates the country, house to house, town to town , passing by one side to the opposite side in the town, so it is for this reason why I think it would be interesting render different from the streets, to guide the driver by the correct street to exit it.

**Comment by pnorman** [comment]
I can't think of a way to render it differently without implying it is a higher classification than residential, which would be wrong. Also, as is we have too many different classifications to render to have distinct nonconflicting looks for each, rendering unclassified differently would only make this worse.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 02.07.2015 um 03:11 schrieb Paul Norman <notifications@github.com>:
> 
> I can't think of a way to render it differently without implying it is a higher classification than residential, which would be wrong


I do see it as a slightly higher classification, these are streets of the connection grid between places while residential roads are interesting only to those living there or going there to visit / as customers.

**Comment by matkoniecz** [comment]
> it would be interesting render different from the streets, to guide the driver by the correct street to exit it

I think that it is not good enough reason to introduce yet another separately displayed road class.

**Comment by ftrebien** [comment]
@pnorman What I understand (which may be wrong) is that unclassified is sometimes (but not always) seen as higher than residential. This is the case when the unclassified road goes through a hamlet (it should be unclassified as it passes the hamlet), even when there are residences lying next to it. It is very specific though. However, I agree with both @dieterdreist and @matkoniecz .

**Comment by ftrebien** [comment]
@yopaseopor Perhaps people in Spain are using unclassified for places that are larger than hamlets and this is causing confusion. I've been researching the topic of classifications, discussion and criticism is welcome (please note it's just a draft with references, which may be useful to you): https://wiki.openstreetmap.org/wiki/User:Ftrebien/Drafts/Generic_highway_classification_principles

**Comment by ftrebien** [comment]
However, unclassified roads that are such because they do not have residences nearby are not necessarily higher in importance. Some cities have industrial districts, local ways in these areas should not be mapped with highway=residential since they lack residences. These areas are also served by tertiaries and secondaries. So, in these cases, these roads are equivalent to residentials - from the perspective of classification/importance, not from the perspective of "actual meaning".

**Comment by ftrebien** [comment]
And that all says that they do not deserve any special rendering. But maybe they're not being used "as expected" in Spain.

**Comment by yopaseopor** [comment]
I explain myself better to make you understand  why I wish that.I'm from Spain but also from Catalonia.

First of all I have to say a part of this problem is because some kind of "fights" between Governments .They always don't coordinate their road plans so little administrations make big roads, and big governments sometimes make shit roads.
First level is the Government of Spain, National Roads Ministerio de Fomento.
Second level are autonomic governments as Generalitat de Catalunya, Direcció General de Carreteres.
Third level is Diputaciones Provinciales.
But these three governments aren't the problem I want to explain you.Each government has a reference for it's roads. EG: N-420 , C-15 , BV-2117

I don't talk about conflicts between governments and... between OSM users from Catalonia and the rest of Spain because of that. So I continue my explanation.

The fourth level are...the city councils that manages unclassified roads. They don't have any classification or ref, but they are so much important because Spain has a lot of hamlets and also big and wide neighbourhoods far away of the center of the town and villages.
So you have a neigbourhood in the middle of the mountain with lots of streets and this neighbourhood is communicated with other or the city by a asphalted track with no name, and  without an official reference.Some of them are better than some tertiary roads.But the problem is inside the neighbourhood, all the streets are so similar so how you can distinguish between a street (residential) and the street makes you be able to exit of this laberintic streets to go back to the city? (unclassified)

Of course there is a simple solution of that: making tertiary this "important" track inside the neighbourhood to make it different from the others similar streets.But that is definitely a "don't map because of the render" case.So we have to avoid it, do we?

Here it is an example.What is the important road? the painted one or the stopped one?
http://www.openstreetmap.org/#map=18/41.23104/1.61118
https://www.google.es/maps/@41.230432,1.611487,3a,75y,316.68h,73.9t/data=!3m6!1e1!3m4!1sMuM9n_8R0a-wH-1e7HmrCg!2e0!7i13312!8i6656?hl=ca

What of these three streets is the important here? (you have to watch data to deduce it.
https://www.google.es/maps/@41.293707,1.701984,3a,75y,186.19h,77.6t/data=!3m6!1e1!3m4!1sdXtiON6DFdwblSd-H-heyQ!2e0!7i13312!8i6656?hl=ca
http://www.openstreetmap.org/#map=18/41.29412/1.70184

**Comment by dieterdreist** [comment]
2015-07-03 3:23 GMT+02:00 ftrebien <notifications@github.com>:

> However, unclassified roads that are such because they do not have
> residences nearby are not necessarily higher in importance.



unless the unclassified roads are dead ends (and in this case they are
likely service roads) they are more important for the road grid, indeed are
a part of the road grid, while residential roads are not for through
traffic, i.e. they have an inferior relative importance for the traffic in
general (even if residentials are physically bigger and better
constructed/maintained).
