### ISSUE TITLE
Small glaciers are dominated by borders and look like lakes

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1631]
See for example Alps:

![45](https://cloud.githubusercontent.com/assets/899988/8505493/13020ab4-21e7-11e5-9451-595bd9526141.png)

Obvious solution of basing lines width on way_pixels is not working as in many places glaciers of different sizes are grouped together and different styling is not looking well.

![selection_001](https://cloud.githubusercontent.com/assets/899988/8505495/4c9849dc-21e7-11e5-9e05-48a0b17b2e04.png)

```
  [natural = 'glacier']::natural {
    [zoom >= 6] {
      polygon-fill: @glacier;
      [way_pixels >= 10] {
        line-dasharray: 4,2;
        line-color: @glacier-line;
        line-width: 0.1;
        [way_pixels >= 20] {
          line-width: 0.2;
          [way_pixels >= 30] {
            line-width: 0.3;
            [way_pixels >= 40] {
              line-width: 1.5;
            }
          }
        }
      }
      [zoom >= 8] {
        polygon-pattern-file: url('symbols/glacier.png');
      }
    }
  }
```

**Comment by imagico** [comment]
You could reduce the line width in general with decreasing zoom level.

At the lower zoom levels the dashed line signature is somewhat adverse to map clarity in areas with detailed mapping - a solid and thinner line leads to a calmer, less noisy appearance:  

![z=8 alps](http://www.imagico.de/files/glacier-ol.png)
![z=6 iceland](http://www.imagico.de/files/glacier-ol2.png)

Using:
```
  [natural = 'glacier']::natural {
    [zoom >= 6] {
      line-width: 0.75;
      line-color: @glacier-line;
      polygon-fill: @glacier;
      [zoom >= 8] {
        line-width: 1.0;
        polygon-pattern-file: url('symbols/glacier.png');
        [zoom >= 10] {
          line-dasharray: 4,2;
          line-width: 1.5;
        }
      }
    }
  }
```

Zoom level limits are of course somewhat hairy here - it is difficult to do justice to both large high latitude polar region glaciers and small low latitude alpine glaciers.

Another option would be to use preprocessed data with dissolved inner boundaries at the lower zooms.
