### ISSUE TITLE
stop considering access=public as equivalent to access=yes for parkings

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1634]
Access public is a pointless duplicate of access=yes, documented only for amenity=toilet and present mainly as result of bug in editors - https://josm.openstreetmap.de/ticket/10007 and https://github.com/openstreetmap/iD/issues/2280

That combination is used less than 10k times across 1 738k amenity=parking objects - http://taginfo.osm.org/tags/amenity=parking#combinations.

**Comment by aceman444** [comment]
But what is the proposal? Will you just ignore the tag? And then are the parkings rendered as accessible to public or not?

**Comment by matkoniecz** [comment]
As private, like any access tags other than ```yes```.
