### ISSUE TITLE
railway=tram is visible from z8, tram is too visible at z13, z15, z16

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1637]
During reworking road style I decided to try changing closely related tram style as on z13, z15, z16 it is really strong.

During more close checking of rendering I discovered that tram tracks are rendered also on z10, z11 and z12 what was quite surprising as I never noticed it.

On reading code I discovered that railway=tram is rendered from z8, what makes no sense. Especially with current style as even during looking for tram lines at known positions I failed to notice it.

Overall this contributes to really bad rendering of cities around z10. 

Even in Toronto, city with "the largest streetcar system in the Americas"[1] and quite far on the north (relevant due to distortion of scale) it makes sense to render trams up to z11 - and probably z12 would be more than enough. See http://overpass-turbo.eu/s/ai3 (I linked overpass turbo, as in current rendering tram lines are not possible to find - despite rendering them).

Other example, Vienna - "With 173.4 km of track, Vienna's network is one of the largest in the world."[2] z11 is the lowest zlwevel where rendering tram makes sense ( http://overpass-turbo.eu/s/ai4 - note, query returns large amount of data).

In general it seems that even with large networks rendering tram up to z12 makes sense, z11 may be justified but it is not the best idea but later it is pointless.

My original reason to start tweaking trams is not so clearly justified - but I am convinced that at z13, z15, z16 tram lines are too visible. See for example

![selection_001](https://cloud.githubusercontent.com/assets/899988/8542833/cf6293b4-2498-11e5-9ba6-f3e50d9bc963.png)

I propose to make tram lines visible at z12 (darker colour), slightly reduce widths at z13, z15, z16 and remove it completely from zlevels 8 to 11.

I think that it makes sense to make PR for this independent from the giant "rework entire road styling" as merge conflicts are highly unlikely and current tram line rendering is causing the same problems with current road style, proposed new road style and its variants.

The current code:

```
    [feature = 'railway_tram'] {
      [zoom >= 8] {
        line-color: #ccc;
        [zoom >= 10] { line-color: #aaa; }
        [zoom >= 13] { line-color: #444; }
        line-width: 1;
        [zoom >= 15] {
          line-width: 2;
        }
        .tunnels-fill {
          line-dasharray: 5,3;
        }
      }
    }
```

[1] https://en.wikipedia.org/wiki/Tram_and_light_rail_transit_systems
[2] https://en.wikipedia.org/wiki/Trams_in_Europe

**Comment by kocio-pl** [comment]
I think you're right in general, but I wonder if nobody will complain for using different colors on different zoom levels for the same objects?

**Comment by matkoniecz** [comment]
The attached is current one, not the proposed.

**Comment by daganzdaanda** [comment]
Good changes. Now one can actually use z12 to plan a trip through a city!
