### ISSUE TITLE
Reduce distance of generic dot / icons to shop-label

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1640]
This is related to #957 
Is there any way to reduce the default dy between the dot and the labels? 
In some places, the dot is further from its own label than from the bottom of the next shop: http://www.openstreetmap.org/node/2933990260
The same happens with icons, but they are bigger, so it does not show up so often.

I know that the dy right now has to take into account the "highest" letters possible, e.g. É, but for most Latin names, it's complete overkill...

Without knowing the technical details, here are my ideas:

1) Align the label using its top, not the baseline 
(probably wrongly assuming that the baseline is currently used)

2) Align the label using its rendered height 
(probably not possible, because it would have been done already) 

3) Move the dot from a centered position to the bottom. 
Maybe all the icons could be bottom aligned for this map. 

4) Switch to showing the label to the right of the dot / icon. 
All letters probably need only a small dx. Pretty radical change in looks, though.

5) Reduce dy a bit and allow and accept a few overlapping labels. 

6) Keep dy but increase the minimum distance between labels.
Will lead to less labels.

Maybe a combination of 3, 5 and 6 is possible?

**Comment by kocio-pl** [comment]
I am not sure if it will be better, because there should be many places with both generic and specific icons, so it will loose some uniformity we have now. I'm not all against this proposition, we just need to check it. #957 is also kind of similar regarding this problem.

**Comment by kocio-pl** [comment]
I don't like this idea, so I will close it now. It can be reopened if someone disagrees.

**Comment by jeisenbe** [comment]
We could do this by using a different text-dy on different zoom levels; on the zoom level where an object is rendered as a dot we could use text-dy 4 or 6, versus text-dy 10 when there is a real icon.

I agree that this would look better, though it would be some work to get right.

**Comment by Adamant36** [comment]
It probably add a bunch of extra code for very little gain to. There should be some standard for how things are rendered anyway. There shouldn't vast differences in how any single object is render at different zoom levels. Otherwise, you lose cartographic consistency. Especially if the differences aren't standardized to specific zoom levels, like road rendering transitions are.
