### ISSUE TITLE
Change bank and ATM color to @amenity-brown?

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1642]
I think [bank and ATM should have the color of all other amenities](https://github.com/kocio-pl/openstreetmap-carto/tree/bank-color). Yes, they are special somehow, but still they are more like amenity (or maybe closer to shop?), while I think black is better for generic things, like name=* on a building. I also think about displaying craft=* POIs, so less color diversity of POIs would be better.

![bank-brown](https://cloud.githubusercontent.com/assets/5439713/8571794/026ad316-2589-11e5-9e71-51471d768b0e.png)
![atm-brown](https://cloud.githubusercontent.com/assets/5439713/8572082/9e52ab68-258a-11e5-99d2-9037f20e1d59.png)

It was first mentioned [here](https://github.com/gravitystorm/openstreetmap-carto/pull/1558#issuecomment-118952635).

**Comment by HolgerJeromin** [comment]
seems ok. We could delete the whole variable `@money-icon` as it is not used after this change.

**Comment by kocio-pl** [comment]
Sure, fixed now.

**Comment by math1985** [comment]
Good idea, I'm slightly in favour the retail colour though.

**Comment by kocio-pl** [comment]
That's how it would like like then:

![bank-shop-saski](https://cloud.githubusercontent.com/assets/5439713/8584183/68058ec8-25d4-11e5-9ce9-c69c678a0475.png)
![bank-shop-rotunda](https://cloud.githubusercontent.com/assets/5439713/8584248/f71cceaa-25d4-11e5-8e17-7c6b854823c6.png)

**Comment by matkoniecz** [comment]
I think that @amenity-brown is better - at least for me "bank is an amenity" makes more sense than "bank is a shop",

I prefer @amenity-brown to the current state and the current state to purple.

**Comment by math1985** [comment]
@matkoniecz Giving banks the same colour as shops would make it easier to recognize entertainment areas versus retail areas though. Most of the brown icons are entertainment, and all of the pink items are shops. Banks fit rather in the latter category.

**Comment by matkoniecz** [comment]
OK, I see that it would be nice. Anyway, I have no strong opinion here. I still slightly prefer brown - but current or purple also would be OK.

**Comment by math1985** [comment]
@matkoniecz Giving banks the same colour as shops would make it easier to recognize entertainment areas versus retail areas though. Most of the brown icons are entertainment, and all of the pink items are shops. Banks fit rather in the latter category.

**Comment by kocio-pl** [comment]
Some amenities are for entertainment, but it's hardly their main function, because this category is far less strict than shops - with post office, town hall, police station, fire station, memorial or even courthouse.

The choice is not obvious, so I hope for some more opinions. However there's no hurry, because it's just a small tuning.

**Comment by rmikke** [comment]
I'm for @amenity-brown. It's not a shop.
