### ISSUE TITLE
National park boundary rendered over road

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1643]
It leads to poor rendering especially on low zoom levels. Road covering boundary may also lead to poor result - invisible boundary if it is going along road.

Left - current style, right - experimental road style (problem is more obvious)

https://cloud.githubusercontent.com/assets/899988/8581531/b03d1048-25c1-11e5-8cea-33dad9ce9d19.png

location: http://www.openstreetmap.org/?mlat=50.0511&mlon=19.9096#map=11/50.0511/19.9096

I thought that there issue for that, but maybe I remembered #1470

**Comment by pnorman** [comment]
#69

**Comment by mboeringa** [comment]
To be honest, as with many things in rendering and we all know, this is very much a personal preference. Some people may prefer seeing roads rendered over the park boundaries, others may actually assign more priority to visibility of the park boundaries.

I am therefore not convinced there is a real good solution to this.

**Comment by matkoniecz** [comment]
I thought about rendering borders on top of roads on higher zoom levels and below on low zoom levels. It would at the same time keep low zoom levels less busy and would keep borders from disappearing on zoom levels where roads are wider than border.

But it may be overcomplicating situation for small gain.

**Comment by matkoniecz** [comment]
Given that it is not clear that it is even improvement I will focus on changes that will result in clear improvements.

**Comment by matkoniecz** [comment]
Duplicate of #3685 (I marked old one as duplicate as new report is better).
