### ISSUE TITLE
Switch to ST_PointOnSurface?

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1644]
In vector tiles, polygons cannot be used for labeling, as polygons are clipped to the vector tile bounds.

This is a particular problem for non-PostGIS datasources, but for PostGIS ones, the standard solution is to use ST_PointOnSurface. #349 found that it was not really better or worse than Mapnik label placement.

https://github.com/gravitystorm/openstreetmap-carto/issues/349#issuecomment-36590153 raised the possibility of performance concerns. I am not sure, but there are a couple of ways this can be addressed
1. Appropriate use of `!bbox!`. `(SELECT ST_PointOnSurface(way) AS way FROM planet_osm_polygon) AS p` does not work because the geometry filtering condition used is `ST_PointOnSurface(way) && !bbox!`.
   
   The appropriate way to write the query is
   
   ``` sql
   (SELECT
   ST_PointOnSurface(way)
   FROM planet_osm_polygon
   WHERE way && !bbox!
     AND name IS NOT NULL
   ) AS p
   ```
   
   This will then use indexes to limit the data fetched, with a second filtering taking place in the outer select added by Mapnik. A functional index on `ST_PointOnSurface(way) WHERE name IS NOT NULL` could also help.
   
   I don't know if @mrwojo did this when testing. If not, it could easily explain any performance differences.
2. Where this is both a point and a polygon layer, these can be combined into one query with `UNION ALL`

**Comment by gravitystorm** [comment]
`st_pointonsurface` needs to operate on valid geometries, and calling `where st_isvalid(way)` on some of our larger geometries is a performance killer.

**Comment by imagico** [comment]
Note resorting to ST_PointOnSurface() to accommodate vector tiles workflows would codify the current bad quality label placement even if mapnik should in the future allow better quality - you would be limited in possible improvements to such offered by the database engine which are unlikely to be within its scope.  Ultimately good quality labeling is simply diametrical to the idea of a strictly tiled approach to rendering.

**Comment by pnorman** [comment]
> `st_pointonsurface` needs to operate on valid geometries, and calling `where st_isvalid(way)` on some of our larger geometries is a performance killer

I was hoping this was wrong, but although my canada osm2pgsql DB doesn't have any invalid polygons, my Europe one does.

**Comment by HolgerJeromin** [comment]
Does `st_pointonsurface` crashes with them or skip them?
Why not fix the polygons. I remember you (?) posted a few years ago a small list of buggy polygons on a ML. 
The community is quite good in fixing stuff if they have a up-to-date list available (compare coastline checker). It would be nice to have Polygon errors in the same GUI as the coastlines, as this is curated on a daily basis. @joto

**Comment by gravitystorm** [comment]
> Why not fix the polygons.

We can't expect OSM users to make OGC valid polygons. It would be a nightmare for the mappers, especially since none of the editors make these kind of checks. The coastline system works because that encourages mappers to make the coastlines conform to the OSM rules for coastlines. But here we're talking about OGC validity, which is much stricter.

As Paul says, the way we handle it already is a mixture of osm2pgsql trying to create valid geometries, followed by mapnik not really caring about OGC rules when it comes to rendering. It's only when using PostGIS functions that it starts becoming a problem.

Also, to answer your question, st_poinonsurface throws an error, which then means the entire metatile doesn't render.

I run my own styles with st_isvalid checks, and for some things it works fine, but landuses can be many hundreds of thousands of vertices and calling st_isvalid takes a few seconds on these. And you need to call it for every metatile, so particularly large polygons are checked hundreds of times.

osm2pgsql has the option to drop invalid polygons, but that drops a whole load of stuff that we normally manage to work around (see above). If osm2psgql also populated an "is_valid" column, that could be useful, since the geometry only needs checking during imports and updates rather than hundreds of times. But that still has the problem that OSM-valid polygons will end up unlabelled.

**Comment by pnorman** [comment]
The totals from one of the rendering servers is 187284564 valid, 22870 invalid. Which is surprising, since I only had 1 invalid in Europe, but there are substantial environment differences in place - I'm running a more recent geos and osm2pgsql, and am not consuming updates.

Given that osm2pgsql detects invalid polygons and tries to recover them with a buffer(0) operation, there's probably some issues to be raised there, but given the current state, `st_pointonsurface` is out, which is unfortunate for vector tile compatibility.

**Comment by HolgerJeromin** [comment]
Thanks for explanation. Than the posted buggy osm ids were some other errors. :-)

**Comment by imagico** [comment]
> osm2pgsql has the option to drop invalid polygons, but that drops a whole load of stuff that we normally manage to work around (see above). If osm2psgql also populated an "is_valid" column, that could be useful, since the geometry only needs checking during imports and updates rather than hundreds of times. But that still has the problem that OSM-valid polygons will end up unlabelled.

The advantage of such a stricter approach would be that it encourages mappers to produce valid geometries.  Currently the standard style is very lenient w.r.t. validity and this without doubt contributes to the problem since mappers think something that shows up in the map is valid.  A lot of the invalid polygons in the database are probably higher level boundary relations, landuse and water areas (when i process the global water areas with osmium i tend get tons of errors and warnings).

**Comment by matkoniecz** [comment]
> advantage of such a stricter approach would be that it encourages mappers to produce valid geometries

given that 

> It would be a nightmare for the mappers, especially since none of the editors make these kind of checks

I think that editors are much better place to start introducing such validation rules.

**Comment by imagico** [comment]
> I think that editors are much better place to start introducing such validation rules.

Since editors do not normally have large Multipolygons available as a whole this is not generally possible at the moment.

But this is of course not the right place for that discussion.

**Comment by pnorman** [comment]
I'm reopening this since a few things have changed and we should look at the decision in light of them

- We're finding more cases where Mapnik's label placement results in strange incorrect results (#1465 and connected tickets)
- Invalid geometries should be gone with osm2pgsql versions from the last few years
- Combining the point and polygon queries into one layer is a step that forks want to take (e.g. @rorym's work)
- Doing polygon to point conversion in SQL allows for different placement methods in the future (e.g. [PIA](https://en.wikipedia.org/wiki/Pole_of_inaccessibility))

**Comment by imagico** [comment]
The argument in https://github.com/gravitystorm/openstreetmap-carto/issues/1644#issuecomment-119903596 still applies i think but this is based on the assumption that Mapnik would eventually offer more sophisticated label placement - which is unlikely given that Mapnik is essentially a dead horse.

The idea that you could generate points from polygons from within SQL that are universally significantly better for labeling is probably not realistic though - this too much depends on font size, actual label text, surrounding labels and other stuff.

**Comment by pnorman** [comment]
> The idea that you could generate points from polygons from within SQL that are universally significantly better for labeling is probably not realistic though - this too much depends on font size, actual label text, surrounding labels and other stuff.

Both Mapnik and ST_PointOnSurface just generate a point and place the label. If at some point there were an option that considered label size and surroundings, we could look at it, but for now, that doesn't matter.

**Comment by imagico** [comment]
Well - i guess my main point here is that ultimately ST_PointOnSurface() is going to be a dead end regarding quality label placement but Mapnik likely is as well so it really does not matter.

**Comment by kocio-pl** [comment]
There are more ideas to improve Mapnik algorithm:

https://github.com/mapnik/mapnik/issues/3550#issuecomment-331936469

The question is if someone will try to code a better solution and which one is acceptable regarding speed and complexity.

**Comment by matthijsmelissen** [comment]
I added this issue to the vector tiles project.

**Comment by jeisenbe** [comment]
PRs #3233, #3690, #3712, #3781, and #3874 have switched the layers `springs`, `stations`, `amenity=points`, `buildings`, and `amenity-low-priority` to use ST_PointOnSurface.

But it was noted that `addr:housenumber` now displays at a different location than building names in https://github.com/gravitystorm/openstreetmap-carto/issues/962#issuecomment-533848444

It looks like the `addresses` layer should also be switched. Are there other layers that should still be changed, or will this issue then be closed?

**Comment by jeisenbe** [comment]
I believe all relevant layers have been switched to ST_PointOnSurface, so this issue is resolved.
