### ISSUE TITLE
stop rendering railway=rail with service=spur/siding/yard on z11 and z12

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1645]
service tag gives information that these tracks are relatively unimportant. Currently, rail sidings/yards are displayed as gray blobs on z11/z12 as these tracks merge together in rendering.

After removal of rendering function of area will be displayed by showing landuse.

Removal of excess tracks would also make possible to make rendering of railway tracks distinguishable from roads on lower zoom levels by making railways darker (something similar to #1637).

See for example http://www.openstreetmap.org/?mlat=55.7899&mlon=37.6495#map=11/55.7899/37.6495

![selection_001](https://cloud.githubusercontent.com/assets/899988/8602892/243ef1e2-2675-11e5-9927-4e66842ad2d0.png)

**Comment by matkoniecz** [comment]
rendering test in Moscow (it is possible that coverage by service=* tags is not 100% complete, but improvement is visible anyway):

![moscow - minor rail master-_minor 11 12 450px master - minor](https://cloud.githubusercontent.com/assets/899988/8604275/ddaa6460-267d-11e5-8899-9e5f76b1b435.png)

**Comment by kocio-pl** [comment]
I was not convinced after just reading the description, but images show me it really works.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 09.07.2015 um 20:03 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> service tag gives information that these tracks are relatively unimportant. Currently, rail sidings/yards are displayed as gray blobs on z11/z12 as these tracks merge together in rendering.


I like the current rendering, it gives a good sense how much space is taken up by railway infrastructure, and where/which shape/direction. The color makes it intuitive to understand.
