### ISSUE TITLE
is_building checks

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1646]
I was looking at the is_building checks for point layers introduced in 0dd1b2cb477188a1d183734aaa08c0be51d17b40

Is there a reason for checking these on points?

@math1985

**Comment by matkoniecz** [comment]
It is not common but this building and landuse on nodes tagging sometimes is used. See http://overpass-turbo.eu/s/ali

**Comment by HolgerJeromin** [comment]
but as the building / landuse code has nothing to fill, why is a check for that needed to prevent that?

**Comment by math1985** [comment]
> Is there a reason for checking these on points?

No, but note that the .text layer is used both for points and polygons.

**Comment by matkoniecz** [comment]
Note that labels for landuse on nodes are rendered.

**Comment by kocio-pl** [comment]
What's the conclusion of this discussion? Should we change something or just close this issue?

**Comment by kocio-pl** [comment]
I believe this check makes sense, so I close this issue.
