### ISSUE TITLE
Stop displaying really small bordered areas

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1648]
The inspiration was taken directly from https://github.com/gravitystorm/openstreetmap-carto/pull/1635.

There are many other small bordered areas like zoos and theme parks, so we should check them too. Today I saw that [multiple military areas around Warsaw are too small to be displayed correctly on z10](http://www.openstreetmap.org/#map=10/52.1975/21.1260), but there may be some other similar objects - for example [this nature reserve](http://www.openstreetmap.org/way/158703157#map=10/52.0837/21.0848) is close to the border of being too small, I guess.

**Comment by math1985** [comment]
Good idea!

**Comment by matkoniecz** [comment]
So it would be about landuse=military and amenity=prison. Anything else?

Nature reserve is already using \[way_pixels > 100\].

**Comment by kocio-pl** [comment]
leisure=sports_centre and leisure=pitch also come to my mind, especially because they can be quite large, yet too small to be displayed correctly ([like here](http://www.openstreetmap.org/#map=12/51.4704/-0.2034)), and because they're colored too aggressively (this is also something to fix probably).

**Comment by matkoniecz** [comment]
"too strong color for leisure=pitch, leisure=track" is #1190

**Comment by kocio-pl** [comment]
leisure=playground is also strong and should have minimal way_area limit.

**Comment by matkoniecz** [comment]
> leisure=playground is also strong and should have minimal way_area limit.

It is the last one but I am not remembering obvious examples where it would help - playground are less noisy and small ones are anyway nearly invisible. Can somebody point me to one?

**Comment by matkoniecz** [comment]
If somebody will find case where playgrounds are a problem I will reopen it.
