### ISSUE TITLE
ditch and drain text is not offset

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#1651]
Streams have offset text ![image](https://cloud.githubusercontent.com/assets/1190866/8665251/a3fae43a-2996-11e5-8784-b7d2162be604.png)

ditches and drains do not ![image](https://cloud.githubusercontent.com/assets/1190866/8665288/101aea52-2997-11e5-8afa-46f4d90838d8.png)

This is cartographically inconsistent, and the same visibility issues impact ditch text as stream text.

Rivers are wider features, both physically, and on the map, and are frequently within riverbank polygons, so do not need to be offset
![image](https://cloud.githubusercontent.com/assets/1190866/8665310/803c3dc2-2997-11e5-884c-1914cabc5a48.png)

**Comment by kocio-pl** [comment]
+1

**Comment by ximex** [comment]
:+1:

**Comment by kocio-pl** [comment]
Fixed by #3120.
