### ISSUE TITLE
Stop rendering addr:housenumber if they are only proposed

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#1657]
With more access to public databases, a lot of potential housenumbers are in the database, typically flagged with the addr:inclusion tag:
addr:inclusion=actual (297100) is a number that exists,
addr:inclusion=potential (16170) and estimate (8351) is either only proposed or inaccurate.
(In total, we have 54M addr:housenumber)

They typically clutter green land without obvious reason for the map spectator, but are certainly valuable for navigation and geocoding purposes. More arguments similar to #1654.

Thus I propose to stop rendering `addr:housenumber` 
that is accompanied by `addr:inclusion=* except addr:inclusion=actual`.

Probably an easy SQL line, but does this depend on the database reload?

![86029](https://cloud.githubusercontent.com/assets/8266355/8675215/ef3e65c8-2a42-11e5-93c8-cd14f5958918.png)

**Comment by matkoniecz** [comment]
I think that it should be treated the same way as building=proposed (#485) - ignore this tag and treat it at tagging error.

addr:inclusion=potential rather indicates that this address should not be mapped.

disclaimer: addresses are one of parts of OSM where I have a limited experience in editing.

**Comment by HolgerJeromin** [comment]
IMO addr:inclusion is a bad tagging schema like disused=yes. IMO this should be better solved with a http://wiki.openstreetmap.org/wiki/Lifecycle_prefix

But we have the data (not really much, 16170 or 8351 from 54M) and can build with it nicer maps on some rare places...

**Comment by dieterdreist** [comment]
sent from a phone

> Am 14.07.2015 um 16:17 schrieb polarbearing <notifications@github.com>:
> 
> With more access to public databases, a lot of potential housenumbers are in the database, typically flagged with the addr:inclusion tag:


how could this pass the import procedure?

 Just want to point out, that "housenumbers" do not always refer to houses, e.g. in Germany it's normal for empty plots to have housenumbers assigned (and also posted).

**Comment by polarbearing** [comment]
afaik, e.g. in Berlin they were not imported but rather manually inserted based on a permitted GIS layers from the local government. 

If the housenumber is posted on an empty plot between used ones, I would consider it as 'actual' and thus to be rendered, if it is a development site to be built up in two years, rather not. 

The numbers might look rare in comparison to the 54M total, but they tend to clutter fields in areas where the underlying data are public and thus used by mappers.

**Comment by pnorman** [comment]
This tagging seems like the `proposed=yes` or `disused=yes`, which we have decided [we will not support](https://github.com/gravitystorm/openstreetmap-carto/issues/111#issuecomment-22523995).

A tagging scheme that says "this is a housenumber" with one tag and then "oops, not really!" with a second tag is inherently flawed

**Comment by math1985** [comment]
@pnorman +1

**Comment by dieterdreist** [comment]
> Am 15.07.2015 um 00:28 schrieb math1985 <notifications@github.com>:
> 
> @pnorman +1


+1
if the housenumbers in question are in Berlin my guess is that there is a misconception as these are likely not just proposed but actual housenumbers even if there aren't any buildings yet.

**Comment by polarbearing** [comment]
According to taginfo map view the tag addr:inclusion=potential is used in several clusters globally. This thread convinced me that the tagging is poor, so should we start a discussion to deprecate it in favour of the lifecycle scheme on the tagging list?

**Comment by matkoniecz** [comment]
Probably tagging mailing list is the best place to discuss this.

**Comment by lest69** [comment]
https://wiki.openstreetmap.org/wiki/Addresses#Using_Address_Interpolation_for_partial_surveys describes the usage of this tag, which is intended to indicate the accuracy of an addr:interpolation way (essentially, whether all possible interpolated values actually exist on the ground). If it's being used on address nodes to indicate their accuracy or lifecycle status, then it's being misused.
