### ISSUE TITLE
render educational areas later

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1660]
http://www.openstreetmap.org/#map=13/50.0659/20.0082

![selection_003](https://cloud.githubusercontent.com/assets/899988/8707488/48836be4-2b36-11e5-9cbe-49190740f960.png)

Is there a good reason to render borders for any educational areas at z12? It is more visible with experimental style that I am testing, but also currently it seems completely pointless.

I propose to render amenity=university/college/school/hospital/kindergarten like landuse=residential (gray colour) on z10, z11 and z12 with brown-yellow fill starting from z13 and borders appearing at z14.

**Comment by pnorman** [comment]
They can be pretty big at z12
[![University of British Columbia](https://cloud.githubusercontent.com/assets/1190866/8707895/717f443a-2aed-11e5-9609-1ef79923d9ec.png)](http://www.openstreetmap.org/relation/1424987#map=12/49.2557/-123.2433)

**Comment by matkoniecz** [comment]
Yes, using way_area may make sense.

But for all big ones that I found (also for this one) borders are anyway invisible (or what worse, visible only for small part of border) as other features make it invisible.

http://www.openstreetmap.org/?mlat=38.0407&mlon=32.5099#map=12/38.0407/32.5099

![selection_003](https://cloud.githubusercontent.com/assets/899988/8708399/f9fc280c-2b3b-11e5-9767-67e5ae99fdf8.png)

Fill is also not really visible and I am guessing that gray identical to residential would work better at that scale (an untested idea) with label kept in uni colour. Places where at z12 makes sense are not fully mapped - for example http://www.openstreetmap.org/#map=12/28.4912/77.1985 and http://www.openstreetmap.org/#map=15/22.7122/90.3535

link to UBC: http://www.openstreetmap.org/#map=12/49.2397/-123.1701

**Comment by kocio-pl** [comment]
Even looking at JNU campus example (near new Delhi), which is very big and just roughly mapped, it still seems to me you're perfectly right with all your propositions. Cracow example is of course much more crisp.
