### ISSUE TITLE
rendering highway=road

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1666]
I am not sure how to treat this road type in redesign of road style. 

Maybe make clear that it should be changed to proper highway type? But it would make the map ugly and generally things like fixme=\* are not displayed. Maybe combine it with showing this road much later than current z10?

Or maybe treat highway=road as special kind of fixme=\* and stop rendering this tag? Provided feedback is "you should not use this tag". It also would be highly confusing, this time for people editing map.

Attempt to guess what is the most common proper type and render it in this style or close to it as it done currently? But it breaks [The Mapper Feedback Loop](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md#the-mapper-feedback-loop), also it result in a confusing map where something that resembles highway=unclassified/residential may be anything.

**Comment by daganzdaanda** [comment]
We should show highway=road, imho.
It should probably be looking less important, so better tagging is encouraged.

Maybe rendering without any casing will make it different from the other highways. Width could be like driveways, and the colour a grey that's a bit darker than a residential area.

**Comment by kocio-pl** [comment]
@daganzdaanda Good ideas to try. I also think it should clear they are less interesting to encourage better tagging, but still visible, because for roads it's important to make network with no artificial gaps even if we don't know all the details.

**Comment by HolgerJeromin** [comment]
The zoom should be not too low, as this could be a major connection in rural area. Thinking about African street connecting villages.

**Comment by matkoniecz** [comment]
@HolgerJeromin 

> The zoom should be not too low

I wonder how far it may be pushed. z13? z14? Currently it appears from z10.

**Comment by gravitystorm** [comment]
> Maybe make clear that it should be changed to proper highway type?

In my opinion, this is the most important thing. It should be distinct from all the other highway types, and not be misleading by appearing to be part of the normal hierarchy. The current rendering is too close to e.g. living street so doesn't look like a todo.

Even something like faint yellow dashes would be an improvement, but of course, we use dashes for too many things already!

**Comment by matkoniecz** [comment]
Maybe only casing without fill, like highway=proposed in German style - http://tools.geofabrik.de/mc/#17/50.0743/19.8497&num=2&mt0=mapnik&mt1=mapnik-german ?

**Comment by kocio-pl** [comment]
The idea is very interesting IMO, of course casing color should be less visible than in this example.

**Comment by Skippern** [comment]
Since ``highway=road`` is hardly supported by any routing applications, and was originally thought of only as a temporary tag, I propose to remove the rendering of it entirely, and treat it the same way as ``highway=proposed`` as mentioned in #1654

**Comment by pnorman** [comment]
I would be strongly against not rendering highway=road.

**Comment by Skippern** [comment]
According to [wiki page](http://wiki.openstreetmap.org/wiki/Tag:highway%3Droad), this tag should be for temporary use, and with the number of application not supporting the tag, promoting the use of it is negative.

**Comment by kocio-pl** [comment]
@Skippern That's exactly why we want it to be clear this _type of the road_ is temporary (so it doesn't look the same as the rest), but the road itself is not temporary at all. It's hardly promoting this solution and for me it's the same as showing just the dot for shop=yes: it encourages people to be more specific.

**Comment by HolgerJeromin** [comment]
In well mapped areas this should be really ugly. I am shocked how many roads are tagged in my region. Clear parking aisles for example...
But we do not want (even more) remote tagging of on aerial images barely visible ways to motor vehicle capable ways in less clear situations.
Josm paints this pretty ugly and gives warnings. I opened https://github.com/openstreetmap/iD/issues/2742 for iD.

**Comment by HolgerJeromin** [comment]
It is possible to render the road with an overlay of question marks? 

The open question is not about a name but the classification aka color and thinkness. I think a rainbow colored road is not a good idea :-)

**Comment by fkv1** [comment]
I guess that highway=road mostly means highway=unclassified or residential. Therefore, I suggest rendering it in the same style. Using an extra style for a deprecated tag is fine for validators, but not for a standard map. You are wasting a map symbol that could be used for something else.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 15.08.2015 um 14:35 schrieb fkv1 <notifications@github.com>:
> 
> I guess that highway=road mostly means highway=unclassified or residential. Therefore, I suggest rendering it in the same style.


-1


> Using an extra style for a deprecated tag is fine for validators, but not for a standard map.


this is not a deprecated tag but a fixme, please survey, shortcut.

**Comment by Skippern** [comment]
I am quite against having it rendered at all, given the tag's temporary nature (fixme=need survey), but as 99% of the cases are unclassified/residential I think a semi-transparent version of these can be acceptable (there is a road on the location, it has not been sufficiently surveyed)

**Comment by kocio-pl** [comment]
I think current rendering of highway=road is good. If nobody complains, I would close this issue in a few days.

**Comment by pnorman** [comment]
I'd call it adequate, not good, but I think that's fine.
