### ISSUE TITLE
Start rendering railway=rail + usage=main on same zoom as primary

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#1668]
#1123 dropped railways from z7. On this zoom we render motorway, trunk and primary. I don't see why those roads are more important than a railway main line (railway=rail, usage=main). We are not OpenSTREETmap anymore, all modes of transport should have a share based on their importance. And I'd consider a main line at least as important as a primary road for long-distance travel.

**Comment by kocio-pl** [comment]
Sounds reasonable. I have no time to check why it was dropped however, so I make a little +1 . :smile:

**Comment by matkoniecz** [comment]
Given that #1123 was modified to drop railways only from z6, not from z7 this request is already fulfilled.
