### ISSUE TITLE
Rendering of power areas is too dominant and too close to landuse=quarry

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1679]
Maybe rendering it like landuse=industrial or with darker shade of purple would be better solution? It is special kind of landuse=industrial. It is especially bad for solar panel farms covering large areas.

Or maybe even stop special rendering? It anyway should be on landuse=industrial

Examples http://www.openstreetmap.org/#map=15/52.5618/13.5887

![selection_006](https://cloud.githubusercontent.com/assets/899988/8849817/0808a85a-3143-11e5-99d2-2e80ad5abb77.png)

**Comment by kocio-pl** [comment]
I guess you're right. It's probably remains of old believe that the number of important objects is quite short, so we can use few different colors to cover them all. Now we know that's not the case, so we should not waste the colors for everything and the kitchen sink, like this.

**Comment by imagico** [comment]
power=generator seems wrong tagging here - that would be correct just for the solar panels themselves, the whole area would be power=plant - and it would make sense to render that like landuse=industrial.  Same would apply to power=substation vs. power=transformer.

**Comment by matkoniecz** [comment]
@imagico 

> that would be correct just for the solar panels themselves

So tagging at http://www.openstreetmap.org/?mlat=51.5746&mlon=13.7358#map=13/51.5746/13.7358 is correct? That gives even worse results.

![selection_001](https://cloud.githubusercontent.com/assets/899988/8860739/16d15c18-3186-11e5-87f8-09f2b75cd39e.png)

**Comment by imagico** [comment]
Drawing an outline on power=generator on lower zoom levels than for buildings (i.e. z<15) is certainly a bad idea...

**Comment by matkoniecz** [comment]
According to OSM wiki tagging individual solar panels is right tagging method.

> A power=generator is tagged as a Node, Area or even multipolygon Relation, on the generator itself, if visible (wind turbine, gas turbine, single solar panel...), or on the smallest building containing it (nuclear reactor, hydroelectric turbine...)

http://wiki.openstreetmap.org/wiki/Tag:power%3Dgenerator
