### ISSUE TITLE
Change pattern icon for landuse=quarry

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1681]
I think we should change "q" pattern icon we use currently for quarries for something more universal, like pickaxe icon for example (here's standard 14 px icon - instead of just 7 px - on 30px pattern tile just for test rendering):

![quarry-png-white-30](https://cloud.githubusercontent.com/assets/5439713/8878374/e9b3e520-322a-11e5-82e1-c7ee8c610f91.png)

We could also convert all the pattern icons to SVG, but I was not able to make it work with SVG and it looks like [polygon patterns can't have icon colors defined](https://github.com/mapbox/carto/blob/master/docs/latest.md#polygon-pattern): not polygon-pattern-fill nor polygon-pattern-color did work in my test. Also all the examples I saw include just PNG icons.

**Comment by math1985** [comment]
That pattern was supposed to denote a Q?

I like the idea of changing this, how do other maps represent quarries?

**Comment by kocio-pl** [comment]
Surprise, isn't it? :smile: Initially I thought it's a magnifying glass, but after I've checked it, it became obvious what it was supposed to be. However it's still not clear in general because it uses name in English to describe something universal.

Symbols can be made less contrast to not drag too much user's attention.

**Comment by imagico** [comment]
IMO not bad but the symbol is much too heavy and even when weaker it would not work well at the lower zooms - you would need to go without at least for z=10-12.

Instead of a single pick two crossed hammers/picks are also a common symbol for mines and could be used.  See [here](https://www.google.de/search?q=mine+symbol&tbm=isch) for a few examples.

The standard pattern for quarries on German topographic maps is a brick pattern, like http://opentopomap.org/#map=14/50.91023/6.50876 - this however does not really work that well here due to the fairly broad meaning of landuse=quarry in OSM.

And you need a power of two for the pattern size which gives you additional constraints - but you do not necessarily have to use a square arrangement.

**Comment by math1985** [comment]
> Instead of a single pick two crossed hammers/picks are also a common symbol for mines and could be used.

+1

**Comment by kocio-pl** [comment]
Crossed tools are very common and even look surprisingly good at 7 px (the same size as "q"):
![quarry-x-7](https://cloud.githubusercontent.com/assets/5439713/8882505/9a9b8a84-3247-11e5-8d00-ec09a6e2c000.png)

I don't know how to change the pattern - I just made a substitution of a symbol. Does anybody know if SVG files are possible or we're bound to PNG in case of patterns? If we have no choice, I will make the PR very soon (given nobody objects against this version).

**Comment by math1985** [comment]
Much better!

> Does anybody know if SVG files are possible or we're bound to PNG in case of patterns?

I don't know, sorry.

**Comment by HolgerJeromin** [comment]
I remember svg requires mapnik version 3. But I am not sure.

**Comment by imagico** [comment]
Symbol looks good but still too strong IMO (strong meaning too much contrast between symbol color and background color).  And with such a small symbol you could try a denser pattern.

You need to create a PNG, SVGs don't work (at least not with current mapnik).

I added a (somewhat experimental) function to jsdotpattern to generate regular grid patterns, try [this example](http://www.imagico.de/map/jsdotpattern.php#x,256,jdp35456;gt,30,64,64;rx,250,2,64,64;rx,250,2,64,64;rd,1,0,0,dot,1,10,9,0,jdp27546;).

Note you can't produce a perfect triangular grid in a square pattern of course so it is always somewhat distorted.

**Comment by kocio-pl** [comment]
I agree that it's still too strong (probably because "q" sign has less pixels) and it should be lightened if the symbol will have similar thickness.

Very nice tool! I took new quarry symbol [directly from Commons](https://commons.wikimedia.org/wiki/File:Mining_symbol.svg) because it's tagged as PD (there's also another [similar symbol](https://commons.wikimedia.org/wiki/File:Schlaegel_und_Eisen_nach_DIN_21800.svg)), so maybe you like them to be added to your symbol library? It would be probably useful for other people (including my experiments). 

Some additional options as defining color and some clear place for entering custom symbols might be nice too, if you are willing to expand the code.

**Comment by kocio-pl** [comment]
Using second (thinner) symbol, 0.12 scaling factor and pattern size 128 with jsdotpattern the result looks like this:
![quarry-x2-012](https://cloud.githubusercontent.com/assets/5439713/8886564/efa40c98-326c-11e5-9e33-d8573b987670.png)

**Comment by matkoniecz** [comment]
First seems to dense, second to sparse. Is something in the middle possible?

Also, good catch with Q. I thought that this symbol was weird at first but later I accepted and stopped noticing it.

**Comment by kocio-pl** [comment]
Middle version (distance 45, pattern size 128):
![quarry-x2-s012-d45](https://cloud.githubusercontent.com/assets/5439713/8888971/877ef436-32c4-11e5-9c69-f4ea90cebb53.png)

What about the color? Make it paler (more gray) or leave it white?

**Comment by matkoniecz** [comment]
I like this version (though it may work worse than dense pattern on small areas). I am unsure about colour, I would need to see/make image comparisons.

**Comment by kocio-pl** [comment]
Hm, I have a strange problem with testing: when trying to check some big quarry, I did the export from the website and while the resulting map.osm file looks good in JOSM, TileMill omits landuses - but when I was importing PBF files from Metro Extracts no such problem ever appeared in TileMill. What could be the problem?

**Comment by kocio-pl** [comment]
Hm, seems like exporting takes too narrow box and I use continuous download plugin with JOSM in the background, so it was quietly expanded...

Big quarry test with the same pattern image: 
![quarry-belchatow](https://cloud.githubusercontent.com/assets/5439713/8936329/ddf029ae-3551-11e5-90f5-2da3ad2a12ef.png)

**Comment by kocio-pl** [comment]
Grey 10% (I would use it):
![quarry-grey10](https://cloud.githubusercontent.com/assets/5439713/8940850/64befc98-356c-11e5-80c3-606534f98da7.png)

Grey 20%:
![quarry-grey20](https://cloud.githubusercontent.com/assets/5439713/8940939/08d82764-356d-11e5-9820-1d74c7624244.png)

**Comment by pnorman** [comment]
> Hm, I have a strange problem with testing: when trying to check some big quarry, I did the export from the website and while the resulting map.osm file looks good in JOSM, TileMill omits landuses - but when I was importing PBF files from Metro Extracts no such problem ever appeared in TileMill. What could be the problem?

Make sure you're importing with `--slim`, see openstreetmap/osm2pgsql#151
