### ISSUE TITLE
Render support for highway=give_way and highway=stop

### ISSUE THREAD

**Issue by aaronstar** [gravitystorm/openstreetmap-carto#1683]
Hi there,
upon due consideration please implement support for these tags, complimentary to highway=traffic_signals.
(highway=stop)
(highway=give_way)

What are your thoughts?

Regards,
Aaron

**Comment by matkoniecz** [comment]
Can you give example of area where this features are fully mapped? I am worried that z19 may be not enough to render this features.

**Comment by matkoniecz** [comment]
Also, it is at best borderline for general-purpose map.

**Comment by aaronstar** [comment]
I can't think of a place where it is mapped extensively – however in my opinion, I only map supported mapnik / CartoCSS tags, so only with support would I map this feature. I suck at coding so can't help in that faculty. But do believe that it should be included in CartoCSS as this is the primary OpenStreetMap viewing mechanism, ergo without CartoCSS support a tag or key is redundant. I suggest that maybe it only appear at very high zoom levels like z19 and in greyscale or faded colouring. It would give detail to the map, and support wider usage of this tag.

**Comment by drkludge** [comment]
Mateusz, Here is an area that has it mapped
http://www.openstreetmap.org/node/1556606418#map=17/33.44648/-112.07905.  I
view it no different than highway=traffic_signals.  This traffic_signals
node is in the same general area
http://www.openstreetmap.org/node/41882944#map=19/33.44698/-112.07866.  If
you make an eight sided red icon around the same size as the
traffic_signals icon, then there should be no problem.  The icon will be in
the middle of the street away from other icons.

I am not sure what you mean by borderline for general-purpose map.  Taginfo
says that the stop sign is used extensively with around 211K nodes
https://taginfo.openstreetmap.org/tags/highway=stop#map .

Give_way appears to be used in Europe
https://taginfo.openstreetmap.org/tags/highway=give_way#map at around 108K
nodes.  I just started to map give_way when I figured out that give_way is
the same as a yield sign in the US.  Many of these give_way signs would be
used around SPUI intersections.  If I update this way, here is where a
give_way exists http://www.openstreetmap.org/way/181550752 in the real
world . Once again the sign would be in the middle of the road with no real
node collisions.

I would say that these two kinds of nodes would turn on and off just like
highway=traffic_signals.

In small cities, these two signs are the only traffic control devices.

There's really good coverage for these two features even though the
features are not rendered. Think of the the truth of what aaronstar
says, "however
in my opinion, I only map supported mapnik / CartoCSS tags, so only with
support would I map this feature."  Rendering two vital signs used in
traffic control would only encourage the mapping of the features.
Rendering the signs would give a mapper a reward for their efforts.
Currently,
there are around 748K traffic_signals
https://taginfo.openstreetmap.org/tags/highway=traffic_signals#map .  If
you render these two signs, I'd say that stop signs and give_way signs
would achieve the same density as traffic_signals.  There's more stop signs
in urban residential areas than traffic_signals.

Thank you for your consideration of rendering these two signs.

Regards,
Greg

**Comment by math1985** [comment]
Hi Aaron and Greg, welcome to the repository and thank you for your suggestions!

I was wondering what purpose you would use this for? Would you use it the rendering to improve the tagging in your area? Or would it help you in navigating or route planning to have these signs displayed? Or a different purpose?

Just asking for some background info because I don't use or tag these signs myself.

**Comment by aaronstar** [comment]
Hi math1985, 

I believe these tags serve to identify which roads are link roads or terminating roads, thus the continuing route visually where highway class is similar or so forth

It can serve to aid navigation if implemented in calculating journey times (there is ad hoc support of the highway=traffic_signals in some navigation providers to calucating journey times)

Rendering can also encourage people to use the tag

The primary purpose for me writing this issue was in response to my surprise when I went looking for the tag on the map to see it not rendered, for something that seems so intrinsic to visually identifing the characteristics of intersections. I understand other mapping providers (i.e. Google / Microsoft) do not display these features in their mapping, which is my only doubt or question so to speak, a great aspect of OSM is however the richness and diversity of infromation collected and conveyed.

Not directly related but the usage of this tag would only apply to where there is appropriate jurisdiction of stop or give_way (/ yield, etc.) by a sign or road marking  (I.e an intersecting, unmarked dirt road would not have this tag, a slip road on a motorway would not have this tag, etc.), 

thus clutter should not be expected from the tagging due to the nature of when the tag is used, additionally-supported if the node tags combine or are not rendered at lower zoom levels.

Also thank you to everyone for getting involved with this thread I didn't expect such discussion!

**Comment by pnorman** [comment]
After thinking about it, I'm :-1: on rendering it. Cartographic decisions like this are very much a judgement call

Summarizing the above, it

- Doesn't have a clear use-case on the map
- Could cause problems in densely mapped areas

A couple other concerns I have are
- Although the stop octagon is well-recognized, I'm not sure that one small enough to fit within roads would be clear
- The problems which you see with dualized ways and traffic_signals are also present on stop/give_way

On the plus side, these would be unlikely to collide with POI icons and labels, but likely to collide with road name labels.

If someone wants to see if the above are an issue, open a PR and we can have a look at how it looks in an variety of areas.

**Comment by leijurv** [comment]
I wonder if this could be reopened for `highway=give_way`. Maybe if/when #1943 is visible, a reasonable followup would be give way signs. I think inverted triangle(s) on the road would work, because give way is [internationally](https://en.wikipedia.org/wiki/Yield_sign) signed as a triangle.

**Comment by HolgerJeromin** [comment]
> I think inverted triangle(s) on the road would work, because give way is [internationally](https://en.wikipedia.org/wiki/Yield_sign) signed as a triangle.

Where is the difference to oneway arrow? We have not many pixel to use here.

The UK paints triangles on the road. In my holiday it took days to understand that this should be the giveway sign.
It always confuses me as a pedestrian that this is a oneway street. 

<img width="203" height="302" alt="Image" src="https://github.com/user-attachments/assets/6c18339e-1798-42d2-bade-680f1f667cda" />

**Comment by aceman444** [comment]
The tag is used for route building in apps like OsmAnd. It slows you down if your car has to go through these give way or stop signs.

**Comment by imagico** [comment]
I see the potential to display these at high zoom in a contextualized form similar to what has been discussed with `highway=crossing`

But it remains unclear what the use case is, what the value is for the map user.  There are plenty of other details on roads, in particular at junctions, that we could display at high zoom levels and that i think would have much clearer value for the map user - like:

* turn restrictions (2.3M)
* lanes (20M)
* ground unit rendering (3.5M `width` on `highway`)
* exceptions on access restrictions
