### ISSUE TITLE
water-storage power=generator is eclipsed by the water

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1695]
One can see only parts of the [generator](http://www.openstreetmap.org/way/6281239) which are outside the riverbank area:
![elektrownia debe - wyswietlanie](https://cloud.githubusercontent.com/assets/5439713/8939350/38faa1a0-3564-11e5-8f86-7a1ab28ed00c.png)

**Comment by matkoniecz** [comment]
It seems to be a data issue - waterway=dam is missing (I attempted to add it but "Server returned status code 503".

For generators under water this rendering would be OK.

**Comment by matkoniecz** [comment]
After adding missing tag rendering changed to expected.

**Comment by kocio-pl** [comment]
Thanks!
