### ISSUE TITLE
Use imagico pattern generator to find new pattern for glaciers

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1700]
Current regular style is rather poor for glaciers covering significant part of screen

generator: http://www.imagico.de/map/jsdotpattern.php

![selection_002](https://cloud.githubusercontent.com/assets/899988/8952735/0b7ccf98-35da-11e5-8b0c-809905921873.png)

**Comment by imagico** [comment]
I had already thought about possibilities for the glaciers pattern but nothing good came to mind.  I actually would be in favor of dropping the pattern here but instead render actually mapped glacier surface features, in particular crevasses, moraines and blue ice areas.  Only crevasses are currently mapped more extensively (as natural=crevasse, more than 2000 objects, but in very few areas by essentially only two mappers)

**Comment by kocio-pl** [comment]
I can see that we don't use this pattern at all:

http://www.openstreetmap.org/#map=13/60.0033/6.3298

Do we still want it to have the pattern here?

**Comment by kocio-pl** [comment]
I think we could close this issue now and reopen when needed. What do you think?
