### ISSUE TITLE
Showing some POIs earlier when outside the landuse=residential

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1705]
I took this idea after thinking for some time that while we have problems with some [crowded places](https://github.com/gravitystorm/openstreetmap-carto/issues/1560), we have also much more places where the problem is quite reverse, because they have much less POIs; not because it's not fully mapped, it's just reality. Because of that POIs are generally more important there - in itself and as the landmarks.

Look for example at [this restaurant/inn](http://www.openstreetmap.org/way/362815861): it is rendered from z=17, but for me even z>=13 would be much better.

Of course maybe separate tagging scheme is needed for such objects located by the highways, but I have noticed that it should be easy to tell that it's rural place, because it's not surrounded by landuse=residential area!

Other good examples of useful POIs in some remote places could be:
- health facilities (like clinics)
- convenience shops
- [crosses and shrines](https://github.com/gravitystorm/openstreetmap-carto/issues/131#issuecomment-142845653)
- memorials/[monuments](http://www.openstreetmap.org/way/288351923)
- shelters
  and many others.

I realize that landuse=residential tag is not as universally present as it probably should be, but this is real chance to dynamically adjust rendering in different places all over the world. We can start with some carefully chosen POIs as a test drive to get some experience, make detailed analysis which ones and how many such POIs are rendered outside residential area and maybe tune minimal distance between the POIs, but I think this is promising idea for the future.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 30.07.2015 um 17:53 schrieb kocio-pl <notifications@github.com>:
> 
> I realize that landuse=residential tag is not as universally present as it probably should be, but this is real chance to dynamically adjust rendering in different places all over the world.


from everything you write I believe you mean the place area and not landuse=residential

**Comment by StyXman** [comment]
Gas stations and pharmacies come to mind too.

**Comment by kocio-pl** [comment]
@StyXman Of course - thanks!

@dieterdreist Sure, we may exclude both in case there are some residential landuses outside place areas. We can also exclude some other human-related areas, like industrial maybe, or most everything not being natural (but including farmlands maybe)...

The truth is I don't know exactly what areas to include/exclude and which POIs are more or less suitable to experiment with. We need to start with good research of current status anyway, because it's probably really outside-the-box idea (at least in OSM rendering - I guess GIS-aware users could know this trick already, but for me it was unexpected discovery).

**Comment by matkoniecz** [comment]
Just landuse=residential is not enough. For example http://www.openstreetmap.org/?mlat=50.08829&mlon=19.89283#map=19/50.08829/19.89283 http://www.openstreetmap.org/?mlat=50.06735&mlon=19.94619#map=19/50.06735/19.94619 or currently unmapped POIs in http://www.openstreetmap.org/?mlat=50.0278&mlon=19.9513#map=16/50.0278/19.9513 are not on landuse=residential and despite that rendering this POIs earlier is not a good idea.

**Comment by jojo4u** [comment]
All examples by @matkoniecz are retail. The second link (http://www.openstreetmap.org/?mlat=50.06735&mlon=19.94619#map=19/50.06735/19.94619) has landuse=retail not mapped yet.

**Comment by jojo4u** [comment]
> from everything you write I believe you mean the place area and not landuse=residential

Place areas are not that common yet, perhaps "urban" landuse (residential, retail, commercial, industrial,...) might best for now.

**Comment by daganzdaanda** [comment]
This is an interesting idea, a work-around until we find a way to process "density". 

It might work better in some places than in others. Around here, most hamlets have a residential area mapped. So this would not change a thing. 
I guess that in the beginning, this will also lead to a lot of "false positives" in some places, where people don't map landuses very much.
But I'm just guessing - a trial with a few areas would be interesting.

I would include Hotels / Motels / Guesthouses / B&Bs in the list of POIs. And maybe schools?

Also, yes, place areas should be mapped more. And they would be semantically more correct for this idea. But we'd have the same result as with landuses: if people map place areas, chances are, tiny places will also have an area place=hamlet or isolated_dwelling.

**Comment by daganzdaanda** [comment]
Going off on a tangent:
If it's possible to check whether a node sits on / inside an area, maybe it would be possible to generate a density map and use this information to make decisions? 

A "density map" might possibly be derived from a osm-planet file where all natural features are removed (so that imports of detailed lakes etc don't turn an area "dense"). Or maybe only nodes and ways with POIs should go into the density calculation. 

The hardest part would probably be how to count the data points per area unit, and find good approximations for envelopping polygons. So we would get polygons that cover an area of similar density.
Finetuning the resolution of the areas and the number of density levels might take some time, too. For a start, I'd say even 3 levels (empty, average, dense) would be very useful. 
Also, there's no need to calculate a new density map very often. Maybe once per year would be enough.

Then, when deciding whether to show something on the map, the coordinates of the POI would be checked against the "density map" and return a value which we can use.

Please be aware that I'm no programmer and no mathematician so I have no idea how hard all of this would be to implement - or if it would be possible at all.

**Comment by kocio-pl** [comment]
First the warning statement: we should remember that any action like this comes with a price of more complexity - and some [will treat complicated rules as a reason to reject the change](https://github.com/gravitystorm/openstreetmap-carto/issues/698#issuecomment-125123616). But it's a matter of personal taste how much complication is acceptable.

For me the problem of uneven distribution of objects is serious enough and I'm willing to pay that price. I like the "density map" idea, but I'm also not capable of testing this solution, not even proposing how fine grained should it be (in a meters range or rather kilometers maybe?).

I still plan to test my simpler solution, but it's so novel approach here, that it probably needs more testing (and for more types of objects) than usual, before we can find the more general pattern, and I'm still not ready to take up such a big researching challenge.

**Comment by kocio-pl** [comment]
This proved to be hard to solve, moreover #1957 is more general, so I'm closing this ticket.
