### ISSUE TITLE
Add rendering for shop=boutique and shop=fashion

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1706]
My proposition for such shops (shop=boutique tag is quite popular, but shop=fashion is also established):
1) ![boutique-14-21](https://cloud.githubusercontent.com/assets/5439713/8990530/40137dd2-36f3-11e5-9ff9-f3e80a7b7a6d.png)

**Comment by HolgerJeromin** [comment]
This was my first association:
https://www.maxima.at/uploads/pics/0_header_zopf.jpg
Do we really need a different icon from shop=clothes?

**Comment by kocio-pl** [comment]
Funny. :smile: 

I think it is kind of specialized kind of clothes shop and rather easy to visualize. There's a reason why people tag it this way, just like we have hairdresser/beauty shop, convenience/supermarket or alcohol/wine/drink shops, which all are closely related or just are more specialized kind of the other. I also think we could separate shop with shoes for women if specific tagging scheme will be established.

**Comment by imagico** [comment]
Not a good idea - visualizing things with icons always requires generalization of some sort and sometimes a pars pro toto approach.  But the symbol used should always be more fitting for the class of objects they are used for than for other things visualized in other ways.  If you use just a different piece of clothing for shop=boutique than for shop=clothes this essentially just emphasizes that there is no meaningful difference between these two tags.

There is no point in inventing new icons for various tags just for the sake of having a larger variety of icons, there should be a meaningful and matching difference in the tags definition, its use and the proposed icon.

**Comment by kocio-pl** [comment]
For me personally this *is* meaningful difference - I wouldn't be interested in boutiques, while I may be interested in general clothes shop. And for some mappers this is also meaningful, because such tags exist and are used well over 5k times, which is a lot - isn't it?

If some sub-category is popular enough, it deserves it's own representation. Otherwise we could have only "food" shops instead of convenience/supermarket/bakery/fishmonger/confectionery/deli/greengrocer/meat/ice_cream (and it's probably is not everything). Showing just different food item would mean they are all the same - taking your argument. Categories are always just subjective choice and amount of uses at least gives them some legs.

**Comment by imagico** [comment]
It would help if you'd actually explain the difference in meaning between shop=clothes, shop=boutique and shop=fashion, show that actual use of these tags represents this difference and propose icons that illustrates this difference.

The wiki [explicitly says](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dfashion) the difference between these tags is unclear.

**Comment by kocio-pl** [comment]
Clothes is a general type here, while boutique and fashion are specialized ones. According to wiki:
- boutique - small shop, with elite and fashionable items
- fashion - fashion shop

I don't see the difference between this pair and treat them as just two different tagging schemes for the same type. Boutique definition is better and it's clear it's subcategory (`shop=clothes - Used on a clothes shop. This tag has a more broad definition`). Fashion is less used, it was just observation that they are very similar and really used by mappers.

However I was sure boutique scheme was clearly defined, which unfortunately is not the case when I 
took a look at it. We don't have policy on how to treat Wiki pages and the number of uses, so I tend to treat ~1k uses as a proof of being established tag (which is more or less true for fashion) and Wiki to get what is the meaning of the tag and if it isn't deprecated. I don't consider lack of any doubts in popular de facto tagging scheme outweighing the rest, but I think it's a perfect moment to turn to tagging dept now to make the things as clear as possible, so I plan to write about it on Tagging list.

Regarding "pars pro toto" rule: I sustain my position that _every_ icon, _every_ map and _all_ of its elements are just a highly symbolic form of describing reality and we want it this way. Which element of map do you consider not being simplification and [generalization](https://en.wikipedia.org/wiki/Cartographic_generalization)? I claim there's no such thing - icons included, but they're not exception.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 31.07.2015 um 12:12 schrieb kocio-pl <notifications@github.com>:
> 
> Clothes is a general type here, while boutique and fashion are specialized ones. According to wiki:
> 
> boutique - small shop, with elite and fashionable items
> fashion - fashion shop
> I don't see the difference between this pair and treat them as just two different tagging schemes for the same type.
> 


prices? The former tends to be expensive and the latter cheap, at least that's how I d use them. You may find this a small difference but it actually isn't;-)

**Comment by SK53** [comment]
Boutique & fashion are extremely subjective terms; furthermore in usual meaning they overlap. Personally I avoid them. However, for rendering I would just render this with the same icon as shop=clothes, which would alleviate the issue of these tags not being rendered.

**Comment by kocio-pl** [comment]
Yes, that's the safe choice and I will do it if we won't be able to refine those definitions.

**Comment by SK53** [comment]
Yes, I think this is an example where tagging got too specific to be useful; whereas the theatre/concert hall is exact opposite. However, I am aware of no usable heuristics for identifying either case.

**Comment by kocio-pl** [comment]
Closing as the corresponding PR was rejected.

**Comment by kocio-pl** [comment]
Has anything changed with definitions on wiki since then? There were long discussions on Tagging list and I still don't know how to recognize the difference.

**Comment by matkoniecz** [comment]
Quite late reply - but looking over shop=fashion it seems to be a clear duplicate of `shop=clothes` and can safely be considered as deprecated.

**Comment by dieterdreist** [comment]
sent from a phone

> On 26. Mar 2019, at 13:48, Mateusz Konieczny <notifications@github.com> wrote:
> 
> Quite late reply - but looking over shop=fashion it seems to be a clear duplicate of shop=clothes and can safely be considered as deprecated.


it is a subset, not a duplicate
