### ISSUE TITLE
Rendering for motorroad=yes

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1708]
Roads with this tag should really have some kind of unique rendering. Maybe a blue motorway colored border about 50% of the width?

I know some countries simply restrict the use of trunk to only these roads, but not all do this.

**Comment by matkoniecz** [comment]
There is really no space to render much more information for roads. Rendering surface is problematic, adding toll is nearly impossible.

Given that this tag is less important than surface and toll tags I think that it is better to reject this feature request.

**Comment by Gazer75** [comment]
Well there is separate render for motorway and a motorroad is quite similar in access rights, which is why I think it would be a good idea to make them stand out.

**Comment by imagico** [comment]
The problem here is that highway=trunk in some countries implies motorroad=yes, in others it does not - see http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions

It could be considered that rendering the access restrictions for slow/non-motorized transport would be more valuable than generally rendering highway=trunk which means different things in different parts of the world - that would mean distinct rendering of motorroad=yes together with highway=trunk in those countries where it implies motorroad=yes but rendering highway=trunk without motorroad=yes like highway=primary in those countries where it does not imply motorroad=yes.  Technically that is difficult of course.

**Comment by matkoniecz** [comment]
Yes, one solution may be to render roads with motorroad=yes like highway=motorway. But I am not sure is it a good idea.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 01.08.2015 um 18:28 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Yes, one solution may be to render roads with motorroad=yes like highway=motorway. But I am not sure is it a good idea.
> 


it should be distinguishable because only a motorway is a motorway and people do make a clear distinction between true motorways and other roads with similar access conditions (at least in Germany and Italy).

**Comment by Gazer75** [comment]
I guess one could change the use of trunk to only  be used on motorroads. Would require a lot of reclassification of roads in some countries.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 02.08.2015 um 15:25 schrieb Gazer75 <notifications@github.com>:
> 
> I guess one could change the use of trunk to only be used on motorroads.


this will not find support as the introduction of the motorroad key was deliberately chosen out of the perceived necessity to make a distinction

**Comment by Gazer75** [comment]
Which is why I also think there should be a visual difference...

**Comment by jojo4u** [comment]
Situation in Germany: motorroad is about access and could be every street (e.g. a tunnel in a city). Trunk is about grade separation. IMHO It's more important on a general purpose map to display grade separation. A bicycle map on the other side is more interested in access.

**Comment by matkoniecz** [comment]
> osmarender

Is it also displaying surface and toll tags? Rendering for these tags also was requested. I am pretty sure that it is impossible to render highway, toll, surface and motorroad tags on general purpose map and keep it usable.

**Comment by Gazer75** [comment]
Tbh a trunk or primary with a blue outline that is maybe a pixel or two wider than todays outline wouldn't be a problem.

For toll I haven't found a working solution yet. Should probably get the toll booths in first.

**Comment by mboeringa** [comment]
> For toll I haven't found a working solution yet. Should probably get the toll booths in first.

I currently render toll booth in my personal renderer by a simple "T" letter symbol (of course, not universal around the globe, but just an example, anyway, "P" as parking seems also used around the globe, so it may not be that bad...). I think this is enough of an indication what roads are toll or not...

![arcgis_renderer_for_openstreetmap-toll_booth](https://cloud.githubusercontent.com/assets/7635726/9046578/da698d96-3a2b-11e5-8012-4e8be1dfdb5e.png)

**Comment by pnorman** [comment]
> There is really no space to render much more information for roads. Rendering surface is problematic, adding toll is nearly impossible.
> 
> Given that this tag is less important than surface and toll tags I think that it is better to reject this feature request.

Closing, for basically these reasons.
