### ISSUE TITLE
Clarification on building=roof and layer

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#1710]
In #140 @pnorman on the issue of a highway below building=roof said: 

> We're handling this with covered=yes, and there were no concrete suggestions here aside from transparency, which is not an option.

The wiki page (http://wiki.openstreetmap.org/wiki/Tag:building%3Droof) currently says: 

>If there are already other features below the roof on the map, consider adding layer=1 (or another appropriate layer tag) to the roof. 

So when tagging "for the database" layer=1 on the roof establishes ordering and is sufficient. When "tagging for osm-carto" covered=yes on the highway should be used as an addition. When covered=yes is vastly improving tool support should we add it to the documentation? Or is tagging for the renderer always "evil"?

**Comment by matkoniecz** [comment]
> Or is tagging for the renderer always "evil"?

Adding incorrect data to achieve wanted effect in specific data consumer (AKA tagging for the renderer) is always a bad idea. But it is unrelated to this situation.

> should we add it to the documentation

Probably yes but I see no reason for opening issues to discuss recommended tagging.

**Comment by RicoZ-OSM** [comment]
I did edit building=roof, imho ways going underneath building=roof should be handled like ways going through any other buildings - regarding the "roof" rather as an open-wall building than a free-flying construction.
- way should share nodes where it crosses outline of building=roof
- neither way nor roof need layer (unless required for other reasons)
- way underneath roof should be marked with covered=* or tunnel=building_passage

Cases currently tagged with an additional layer ought to work just as before, which is again consistent with other buildings.

Other "features under building=roof" were never really supported for any purpose as far as I can see and should be considered a case of indoor mapping.

This is for a bunch of reasons:
- technically identical to other buildings and thus hopefully fewer odd corner cases and exceptions to consider
- less exceptions and corner cases could facilitate better error chacking
- roofs don't really hang in the sky unrelated to the ground bellow but in most cases more or less resemble an open-wall building

**Comment by RicoZ-OSM** [comment]
In a similar sense I have added a description how to map building=bridge. The idea is that by adding a man_made=bridge to the building=bridge object would inherit all useful properties of that structure and building=bridge could be handled mostly just like regular buildings.

  http://wiki.openstreetmap.org/wiki/Tag:building%3Dbridge#How_to_map

How to map
- draw the area of the object and tag with building=bridge
- the area should be also tagged with man_made=bridge
- apply layer=* to the structure (typically layer=1)

Ways using such bridges should be probably mapped by indoor mapping methods, possible approach would be:
- ways should share nodes with building where they cross the outline of it
- ways should have the same layer as the overall building=bridge structure
- ways may have a level=* assigned (indicating level within building)
- ways may be tagged with some variant of covered=* or tunnel=building_passage
- ways may be tagged with location=bridge or location=indoor

Such ways should have at least one of covered=*, location=* or bridge=* tags.
