### ISSUE TITLE
Add rendering for landuse=depot

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1716]
I think we should start rendering landuse=depot. It has only [about 500 uses](http://taginfo.openstreetmap.org/tags/landuse=depot), but it's one of those features which never will have much higher number of uses (because it's limited in real life, of course) and is in fact just a subcategory of landuse=industrial, so we can just make it look exactly the same.

**Comment by polarbearing** [comment]
Sorry I disagree. Depending if the public transport stores their buses, or the chemical company their raw materials, it is landuse=commercial or industrial. There are certainly more depots in the world than 500, compare the 70000 mapped townhalls. In the wiki, landuse=depot is just a proposal with little support.

**Comment by matkoniecz** [comment]
I consider landuse=depot as a terrible tagging and I created competing proposal at http://wiki.openstreetmap.org/wiki/Proposed_features/*%3Ddepot

**Comment by kocio-pl** [comment]
OK, so we can safely close this issue.

**Comment by matkoniecz** [comment]
Closing on request from reporter.

**Comment by kocio-pl** [comment]
I like your proposition in general, because it better uses existing categories, however it looks it would be problem when tagging tram depot: how on should railway=tram + railway=depot? Probably you need some other description, like: railway:tram=depot.

**Comment by matkoniecz** [comment]
@kocio-pl Can you ask on tagging mailing list or on wiki? I will reply there.

**Comment by kocio-pl** [comment]
Sure, done on wiki.
