### ISSUE TITLE
Add special rendering for shop=outdoor

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1717]
My proposition for such shops:
1) ![outdoor-14-5](https://cloud.githubusercontent.com/assets/5439713/9028997/1acc1832-398b-11e5-9eff-3779f90feb30.png)

**Comment by pnorman** [comment]
I don't like this one, as this looks like a compass arrow which traditionally has a special meaning in cartography.

**Comment by kocio-pl** [comment]
Yes, it was intended to look like this, thanks! :wink: Do you think this icon in the shop-violet could be really misinterpreted? 

Any other ideas to test? What about reusing [camping icon](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/camping.16.svg) maybe?

**Comment by gravitystorm** [comment]
> in the shop-violet

We shouldn't rely on the colour of the icon to give too much understanding - most people will look at the shapes, and not use the colours as a major thing. In addition, it would be nice when printed, adapted by downstream projects etc, that colours can be changed without icons being confused.

The colour categories are useful and should be coherent, but we shouldn't rely on them to make up for weak icons.

**Comment by kocio-pl** [comment]
I guess it means "we shouldn't" also for camping icon?

**Comment by gravitystorm** [comment]
Yes, we should avoid using the same icon for different features, if possible.

**Comment by kocio-pl** [comment]
Different design:
![outdoor-19](https://cloud.githubusercontent.com/assets/5439713/9996407/12f23452-6087-11e5-9b76-41d0b13bc903.png)
