### ISSUE TITLE
Add layer for proposed objects

### ISSUE THREAD

**Issue by rmikke** [gravitystorm/openstreetmap-carto#1718]
While it's good that proposed ways are not rendered by default, it would be even better if they could be visible on demand. It's good to know, what is planned and OSM should make it possible, especially when someone has already put some work copying all the data from some project documentation. For me, only the proposed ways on OSM show all the projects in Poland in one place and it's much easier to get an overview from OSM than from official documentation, which is hard to come by.

The solution would be creating additional layer in mapnik, that would be visible on demand, like notes are now. By default it would be switched off.

**Comment by matkoniecz** [comment]
> that would be visible on demand, like notes are now

This requires changes that are beyond scope of this project and require changes on OSM website ( bugtracker is at https://github.com/openstreetmap/openstreetmap-website ).

BTW, Overpass Turbo is a good solution to show additional layer of data, not rendered by this style.

**Comment by rmikke** [comment]
OK, moved to https://github.com/openstreetmap/openstreetmap-website/issues/1022
