### ISSUE TITLE
Rendering order buildings / roads / highway-area

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#172]
I am not sure what is the best rendering order for buildings, roads, and highway-areas, and would like your input.

In terms of rendering order, it seems to make sense to have the following three requirements:
1. building > highway-area-fill
   Buildings should be rendered above highway-areas. If buildings are rendered lower than highway-areas, then buildings in the middle of a square become invisible. For example, the kiosk in the middle of [this square](http://www.openstreetmap.org/#map=18/49.61120/6.12893) would [not be rendered](http://i.imgur.com/G8wzYSm.png).
2. roads-casing > building
   Buildings should be rendered below roads. If buildings are rendered higher than roads, then roads are difficult to see in dense built-up areas, as can be seen [here](http://i.imgur.com/FJRS5iA.png). Alternatively, buildings can be rendered below the fill of roads, but above the casing of roads. This leads, however, to gaps in the casing of roads, as can be seen in [this example](http://i.imgur.com/02qaOv4.png), where the casing is made a bit wider and given a red colour.
3. highway-area-fill > roads-casing
   Highway-areas should be rendered above roads (at least above their casings). When highway-areas are rendered below the casing of road, the places where a road runs in an area become [ugly](http://i.imgur.com/qTRO1yH.png).

Unfortunately, requirements 1, 2, and 3 are not compatible.

Violating 1. is an option, but is undesirable as it would require large-scale re-tagging. All the highway-areas with a building in the middle to be tagged should be tagged as multipolygons if we decide to violate this requirement.

Violating 2., in the version where buildings are rendered below the fill but above the casing of roads, is currently used. In the current style, the gaps in the road casing are not a major problem because buildings and road casings have a visually similar colour. However, if someone decides to adapt the colours, this might become a problem.
The version where buildings are also rendered above the casing of roads seems no option for a map that is meant to focus on roads.

Violating 3. seems not an option, because of the ugly rendering.

Or are there any ideas to avoid this problem altogether?

**Comment by K4LCIFER** [comment]
what would be the current status of this issue?

**Comment by Sirorezka** [comment]
Hi, 

Sorry, it's not clear. Why can't you downgrade "area=yes, highway=pedestrian" and "area=yes, highway=footpath" to level of "amenity=parking"? This will solve the issue/

**Comment by matthijsmelissen** [comment]
@Sirorezka that would violate constraint 3, which means the road casings will appear on top of the pedestrian areas. [Example rendering](https://i.imgur.com/qTRO1yH.png)

**Comment by Sirorezka** [comment]
Sorry, what do you mean by 'road casings'? Tunnels or "end of lines rounds?" In case of tunnels it is very much ok to see tunnels if they underneath pedestrian area. In case of end of way rounds - I would say that you don't see often roads that clash directly in pedestrian area. And having this small clashes is much better than not rendering anything on pedestrian area.

**Comment by matthijsmelissen** [comment]
> Sorry, what do you mean by 'road casings'? Tunnels or "end of lines rounds?"

Casings are the dark outlines around roads - for example visible at round lines at the end of lines.

> I would say that you don't see often roads that clash directly in pedestrian area. And having this small clashes is much better than not rendering anything on pedestrian area.

I'd expect you have such roads for most pedestrian areas. To me these clashes look quite bad, but that's a choice for the maintainers to make.
