### ISSUE TITLE
hstore needed?

### ISSUE THREAD

**Issue by cmyk** [gravitystorm/openstreetmap-carto#1721]
This is something that isn't mentioned in the readme.
Does the db have to be hstore enabled prior to import?

**Comment by mboeringa** [comment]
No AFAIK, as regards future, see here:
https://github.com/gravitystorm/openstreetmap-carto/issues/1504

**Comment by math1985** [comment]
Currently we do not use hstore. We plan to start using it soon, and at that point we will make sure to update the documentation.
