### ISSUE TITLE
A highway is not rendered

### ISSUE THREAD

**Issue by Zverik** [gravitystorm/openstreetmap-carto#1722]
Not sure if it is bug with the style or with osm.org backend, but this perfectly good road is not rendered for some reason: https://www.openstreetmap.org/way/141673809

![mosvorota](https://cloud.githubusercontent.com/assets/766031/9073842/03837a3e-3b0d-11e5-8ef0-4c21510081de.png)

**Comment by matkoniecz** [comment]
OK, this is a nice clear case of database glitch. Please, do not edit this element - maybe it is something fixable.

@tomhughes - is this database glitch something that may be investigated and fixed or is it better to edit this element to invalidate broken cache?

**Comment by matkoniecz** [comment]
Rendering of this place - data from Overpass. It is clearly osm.org backend problem.

![https___www openstreetmap org_way_141673809 map 19_59 89218_30 31941 master-_master 18 18 350px master - master 350px](https://cloud.githubusercontent.com/assets/899988/9074343/f0a14b98-3b08-11e5-8612-011f74d268c4.png)

**Comment by matkoniecz** [comment]
Bug report kicked to place that is hopefully more relevant to cause of issue.

**Comment by Zverik** [comment]
Thanks!

**Comment by tomhughes** [comment]
Way 141673809 is present in planet_osm_roads on both servers.

**Comment by pnorman** [comment]
> Way 141673809 is present in planet_osm_roads on both servers

is it in planet_osm_line too?
