### ISSUE TITLE
displaying roads at zoom level 11

### ISSUE THREAD

**Issue by d3netxer** [gravitystorm/openstreetmap-carto#1725]
I made some historical OSM tiles a few months ago. They look odd now. At zoom level 11 my tiles where I used openstreetmap-carto are displaying unclassified roads; where OpenStreetMap tiles display unclasified roads at zoom level 12. So unless I did something wrong when I applied the openstreetmap-carto in the first place I think one of either two things occurred. Do you know if recently either the style of openstreetmap-carto or OpenStreetMap changed when displaying unclassified roads at zoom level 11 and 12?

**Comment by matkoniecz** [comment]
Yes, see history ( https://github.com/gravitystorm/openstreetmap-carto/commits/master )

https://github.com/gravitystorm/openstreetmap-carto/commit/93789b6bac94e7c13bae6fb4a6d8ee7df02aaf3f https://github.com/gravitystorm/openstreetmap-carto/commit/1397a58d419f28acafc3ba8c5947a91cfae6cbd9 https://github.com/gravitystorm/openstreetmap-carto/commit/0156f65078bc472acf79982f591ed9e1d3397d7e https://github.com/gravitystorm/openstreetmap-carto/commit/6197df2f2ecd9ed547afed1e0e4c6fe27fd0f1ea are the most relevant ones.

**Comment by d3netxer** [comment]
Ok, thanks for the info @matkoniecz

**Comment by pnorman** [comment]
> Do you know if recently either the style of openstreetmap-carto or OpenStreetMap changed

It's worth remembering that both of these are constantly changing. With each release what features are rendered on which zoom level can change, as we're always trying to improve.
