### ISSUE TITLE
render highway=residential, construction=residential as a residential in construction

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1730]
Right now sometimes uses recover a road in construction by changing only the highway tag to the right value and forget to remove the construction tag.

So the remaining data in OSM is `construction=residential` AND `highway=residential`. The rendering results in a normal residential because of this line 
`[feature = 'highway_construction'] {`
https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss#L873 

A better feedback loop would be to render it as a construction road...

**Comment by matkoniecz** [comment]
I am not sure. What about users marking existing road as under construction (undergoing maintenance, with long-term unavailability for traffic)?

The same problem may happen (adding only construction=residential without modifying key highway) and in that case consequences would be more problematic.

**Comment by HolgerJeromin** [comment]
The wiki (and my feeling) says:
> construction=* must be used together with tags such as highway=construction, railway=construction, landuse=construction, and building=construction

Long-term unavailable for traffic. Thats exactly the usecase for highway=construction IMO!?
I do not understand your second sentence/example.

**Comment by polarbearing** [comment]
I understand @HolgerJeromin that he wants to highlight incorrect tagging by still rendering construction style when somebody has forgotten to remove the construction= key from a finished highway. 

@matkoniecz fears that this would, at the opposite end of the workflow, encourage to apply only the construction= key when the construction starts, without changing the value of highway=. 

+1 from my perspective. Detecting tagging errors as described in the OP should be done by a QA tool, not in the carto style.

**Comment by pnorman** [comment]
Possible tags are
* `highway=residential`
* `highway=residential construction=residential`
* `highway=construction construction=residential`
* `construction=residential`

The second is an error, and could be introduced when going into **or** from a construction state. Regardless of if we render the second as residential or as construction, it will allow some errors.

QA tools are the appropriate fix to this data error.

For reference, of the 17326 `construction=residential`, about 14k have a `highway tag`, and of those the breakdown is

```
┌───────┬──────────────────────────┐
│ count │         highway          │
├───────┼──────────────────────────┤
│ 12660 │ construction             │
│  1653 │ residential              │
│   283 │ proposed                 │
│   154 │ service                  │
│    67 │ tertiary                 │
│    65 │ unclassified             │
│    56 │ living_street            │
│    52 │ track                    │
│    26 │ secondary                │
│    19 │ footway                  │
│    10 │ pedestrian               │
│     8 │ cycleway                 │
│     6 │ primary_link             │
│     5 │ path                     │
│     4 │ road                     │
│     4 │ tertiary_link            │
│     2 │ yes                      │
│     1 │ construction;residential │
│     1 │ planned                  │
│     1 │ crossing                 │
│     1 │ primary                  │
│     1 │ steps                    │
└───────┴──────────────────────────┘
```

**Comment by pnorman** [comment]
Longer-running SQL finished, so I checked some other numbers.

iD recently fixed openstreetmap/iD#1922, but it hasn't landed in a new release yet. I see a fair number of  `highway=residential construction=residential` last touched by JOSM, so you may want to investigate and create an issue on the JOSM issue tracker.

**Comment by HolgerJeromin** [comment]
Thanks for explaining your reasonable concerns!

**Comment by polarbearing** [comment]
> For reference, of the 17326 construction=residential, about 14k have a highway tag

Don't forget that other things than highways can be constructed, e.g. we have 66 133 ```landuse=construction```, which is combined with ```5186 construction=*``` and ```1811 construction=residential```.

**Comment by HolgerJeromin** [comment]
This is a good candidate for josm validator and the Osmose qa tool. Will try to open issues next week if no one is faster :-)
