### ISSUE TITLE
admin_level=7 rendering too late (name and border)

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1737]
Currently the rendering of these are almost useless. Borders render at z12, and names at Z16. This is way to late imo.
Suggests borders at z11 and names at 12 or 13 with much bigger font, current size is so small its barely readable.

**Comment by matkoniecz** [comment]
Can you show places where it is causing problems? Preferable - both screenshot and link.

**Comment by Gazer75** [comment]
https://www.openstreetmap.org/#map=12/60.1530/5.3394 is a nice location for several municipalities. Would be nice to read the names at that point, z16 is quite far in to view the name along the border. Even the ferry route names show before the municipality names. Once the names show the purple is not easy to read regardless of background IMO.

In the north of Norway, for counties of Nordland, Troms and Finnmark, the municipalities are so big the borders are almost useless. You'll have to scroll quite a bit to find a border up there at z12.
https://www.openstreetmap.org/relation/406389#map=7/70.017/26.125
Try looking for municipality borders in that county and you can almost get lost :)

I think the font should be same size as admin level 4 names, but still along the borders as it is now.

**Comment by kocio-pl** [comment]
Are you aware of the place where it could make things worse?

**Comment by Gazer75** [comment]
If it would be bad in some areas please show us. I can not know the whole world :)

**Comment by kocio-pl** [comment]
I think this is unlikely that this issue could be really fixed. We have a priority of levels, so it's unfortunate that Norway has a big gap between z4 and z7, but I don't like to break the system for every other place where the priority is used more consistently.

**Comment by Gazer75** [comment]
What is inconsistent about it? We use level 7 like all other countries with municipalities.
The problem is not just for Norway, but any place where level 7 is used.
The thing is they show up so late they might as well not be displayed at all.
Borders and names should display at low zoom so you actually see where they are, not at high zoom where you look for smaller details.
A least have names display when the borders show up at z12.

**Comment by kocio-pl** [comment]
There are intermediate levels and changing l7 would require global changes. l6 is rendered on z11+, so l7 on z12+ makes sense.

**Comment by Gazer75** [comment]
Well, at least show names along the borders at z12 and not 16.

There is also nothing wrong with moving all boundary levels out one zoom level.
The gap from admin lvl 4 to 5 is already pretty big, so moving 5 and 6 out one level should be easy enough.

**Comment by kocio-pl** [comment]
Since admin levels make a system, all such changes require big research, changes and testing around the world. If somebody is willing to make such effort, I think more general ticket is needed anyway, because it's not only about level 7 (all the names on borders appear on z16+).

**Comment by Gazer75** [comment]
Why would you need to do a lot of research?
It is all about the rendering and at what level each admin level show up. Nothing else would change.
Tbh the borders are just meaningless clutter unless they have names at a zoom level that is useful.

**Comment by kocio-pl** [comment]
> Why would you need to do a lot of research?

Because the world is big and different and we show admin borders all around it:

https://wambachers-osm.website/boundaries/

> It is all about the rendering and at what level each admin level show up. Nothing else would change.

I agree, I just mean that border problem is global in itself. It covers entire world at many zoom levels.

> Tbh the borders are just meaningless clutter unless they have names at a zoom level that is useful.

I don't agree with that. Seeing shapes of admin entities is OK for me for a start.
