### ISSUE TITLE
Weird multipolygon label positioning

### ISSUE THREAD

**Issue by M1dgard** [gravitystorm/openstreetmap-carto#1740]
https://www.openstreetmap.org/#map=19/51.20334/4.44838

The building in view is one multipolygon. The label is placed awkwardly in a corner on the left of the building.

![Weird label position](https://cloud.githubusercontent.com/assets/4283376/9247827/b1bdbdda-41b6-11e5-81bd-dc958ef3d58c.png)

JOSM puts it a bit better, in the top section of the building.

![JOSM label position](https://cloud.githubusercontent.com/assets/4283376/9247855/fad6ef50-41b6-11e5-9847-81af21bbc3ff.png)

NB: The lines visible in JOSM are building:parts.

**Comment by HolgerJeromin** [comment]
This is intended behavior from the mapnik label placement code. Roughly speaking the center of the polygon is calculated and if there is a "hole" the label is shifted to the right or left till the polygon is hit.

**Comment by M1dgard** [comment]
Oh, ok.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 13.08.2015 um 12:32 schrieb Midgard <notifications@github.com>:
> 
> The building in view is one multipolygon.


mapping error. These are clearly several buildings and not just one

see here: https://www.openstreetmap.org/relation/5432755

**Comment by M1dgard** [comment]
@dieterdreist You haven't seen a building with multiple blocks then? It's a single research facility, in a single building, consisting of multiple parts. As such, the whole building has building=yes. The different parts were previously mapped as separate buildings and have been retained as building:part=yes should someone be interested in 3D-mapping it later.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 13.08.2015 um 15:30 schrieb Midgard <notifications@github.com>:
> 
> @dieterdreist You haven't seen a building with multiple blocks then? It's a single research facility, in a single building, consisting of multiple parts.


I admit this can get philosophical (distinction between a building with several parts/extensions and several connected buildings). The fact that it's a single research facility doesn't mean it's a single building.

Why do you think it a single building? Has it one building name for all parts together? Do the parts don't have names or are these names explicitly indicating "part" rather than building? Is it all from the same architect? Same style? Same period? Has it a common static structure (i.e. parts are structurally not independent)? These might all be soft criteria, but FWIW, looking at this it looks like several buildings that might be connected rather than one building consisting of several parts.

**Comment by M1dgard** [comment]
I'm not so sure either any more. I reckon there's also a bit personal taste involved. To me it looks like one building since you can walk all the way through it. But then again, there are different parts that are used for different things (albeit it's all for one common goal).

**Comment by matkoniecz** [comment]
I think that it would be preferable to discuss tagging on tagging mailing list or on wiki (where discussion will also have higher chance to be found after some time).

**Comment by dieterdreist** [comment]
sent from a phone

> Am 13.08.2015 um 16:13 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> I think that it would be preferable to discuss tagging on tagging mailing list or on wiki (where discussion will also have higher chance to be found after some time).
> 


anyway, the labeling problem is independent from the tagging. If it wasn't all one building it could still all be one function/user/business in several buildings with likely the same labeling problems.
