### ISSUE TITLE
Bridges junction bug: black border badly drawed

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#1741]
Hello, there.

I noticed a bug in the Mapnik stylesheet, as used with OSM [here](https://www.openstreetmap.org/#map=19/48.61263/6.10263&layers=N): the black border of the right side of the D974 bridge should be interrupted at the junction with the pedestrian bridge, to mark the junction between the two bridges, but it isn't.

Regards.

P.-S.: I first reported this bug on the mapnik repo (mapnik/mapnik#3035), but have been told it's a stylesheet issue.

**Comment by matkoniecz** [comment]
#728 was similar

**Comment by matkoniecz** [comment]
I am tempted to describe

![selection_001](https://cloud.githubusercontent.com/assets/899988/14045746/f86fb8fe-f29c-11e5-92cb-73430c6ce718.png)

as a data problem but note that using sidewalk tag instead of mapping footways as highway=footway is popular and accepted tagging scheme in some regions.

**Comment by Penegal** [comment]
I corrected the type of way to footway, but this really is a footway rising to the bridge. There may be another problem in my modelling, but this footway still exists.

**Comment by math1985** [comment]
The primary was tagged with layer=1, while the footway had no layer tag. I fixed the rendering issue by adding a layer tag to the footway.

**Comment by Penegal** [comment]
Great; so it was just that! Then, should this be considered a tagging issue, or is this `layer` tagging not supposed to be necessary?

**Comment by matkoniecz** [comment]
Matching layer are unnecessary in cases like that, so it is a bug in map style - old data was valid.

**Comment by math1985** [comment]
> Matching layer tags are unnecessary in cases like that,

Are you sure? What if the node has a highway=elevator tag?

In any case we have no way of checking  within the stylesheet whether crossing roads share a node, so there is no way we could change this behaviour within our style.

**Comment by nighto** [comment]
Hello!

 

You have a new message, please read <http://tetasvspollas.com/no.php?04qlt>

 

nighto@nighto.net
