### ISSUE TITLE
specific water=lagoon is not rendered

### ISSUE THREAD

**Issue by PalmerAL** [gravitystorm/openstreetmap-carto#1742]
Occurs with this item: 
http://www.openstreetmap.org/relation/2189656

On every other map layer on openstreetmap.org, the above lagoon is rendered, but in the "standard" layer, it is invisible.

**Comment by pnorman** [comment]
Doesn't appear to be a style bug, as it relates to a specific object. It's probably something on the osm2pgsql side, and if I had to guess, openstreetmap/osm2pgsql#67

**Comment by pnorman** [comment]
Just to note what's going on, the relation and members turned into two polygons for what are now its inners. My guess is that it was invalid, and then made valid, but didn't get properly reprocessed.

**Comment by pnorman** [comment]
Ah, no, that wasn't it, the MP outers weren't closed. Fixed the data error in [33329249](http://www.openstreetmap.org/changeset/33329249)
