### ISSUE TITLE
County Road number is cut in half

### ISSUE THREAD

**Issue by iansan5653** [gravitystorm/openstreetmap-carto#1743]
http://www.openstreetmap.org/#map=14/26.5358/-81.7813
http://www.openstreetmap.org/#map=15/26.5358/-81.7813

The CR 885 number is chopped in half horizontally and offset slightly as to make it unreadable. It's only visible on z14 and z15, but it is very obvious.

**Comment by matkoniecz** [comment]
Case of #950
