### ISSUE TITLE
trees now cover lakes

### ISSUE THREAD

**Issue by mvexel** [gravitystorm/openstreetmap-carto#1754]
Before:

![screenshot 2015-08-16 10 07 01](https://cloud.githubusercontent.com/assets/120452/9294053/a3761e58-43fe-11e5-8ee3-0a95430d4ce2.png)

After:

![screenshot 2015-08-16 10 07 05](https://cloud.githubusercontent.com/assets/120452/9294055/aae3606a-43fe-11e5-8278-389d2ab1fa4f.png)

This is way http://www.openstreetmap.org/way/224936302 being 'tree-covered' covered by (I think) http://www.openstreetmap.org/way/260876069

**Comment by nebulon42** [comment]
I think this is a data problem as the lake should be a member of the forest multipolygon with role "inner". See e.g. https://github.com/gravitystorm/openstreetmap-carto/pull/1242#issuecomment-70480285 for discussion as why this might be a desired effect as it leads to cleaning up/adding missing inner members of forest multipolygons.

**Comment by matkoniecz** [comment]
According to current tagging of this area it is both lake and covered by forest (what may happen in some cases like mangroves - https://en.wikipedia.org/wiki/Mangrove#/media/File:Hunting_For_Worms.JPG ).

In cases where it is not a forested area it should be an inner part of forest multypolygon.

There are also situations where forested area and locality named "Forest Foobar" are not equivalent (lake that is not part of forested area but is part of locality) but there is no established tagging for this situations.

**Comment by SK53** [comment]
I'd also point out that natural=wetland and wetland=swamp implies both wetland and tree cover, although I'm not aware of any attempt to render this. It is likely that in some places there is also a polygon of natural=wood or landuse=forest co-incident with the wetland area.

**Comment by imagico** [comment]
> I'd also point out that natural=wetland and wetland=swamp implies both wetland and tree cover, although I'm not aware of any attempt to render this.

wetland=swamp and wetland=mangrove are rendered here with specific patterns since #1497.  There are many cases of course where these are mapped with overlapping wetland and forest/wood polygons instead.  Overlapping water and forest is more frequently an error though.

**Comment by SK53** [comment]
@imagico very nice; and pretty much covers the obvious overlap cases. One other I have noted is an area which is natural=wood and leisure=park: Bosque Yatana in Ushuaia (http://www.openstreetmap.org/#map=18/-54.80297/-68.30968). The rendering shows trees above parkland, which is fine, but may be less so if we want a scattered trees symbology at some later time. (This may be incorrectly tagged, the wood is more a privately run & funded nature reserve with some education programmes).

**Comment by imagico** [comment]
This is already the case here:

http://www.openstreetmap.org/#map=17/48.07266/7.67195

but tree rendering is sufficient strong so it is not a serious problem.

**Comment by mvexel** [comment]
I don't think the multipolygon approach would be viable here as this [huge national forest](http://www.fs.usda.gov/uwcnf) literally contains thousands of lakes. 

Perhaps the problem here is tagging, but in a different way. Perhaps 'National Forests' should be tagged differently, because they contain a variety of land uses: lakes, campgrounds, screes, meadows, ... 

Closing here and taking it to tagging@

**Comment by jojo4u** [comment]
Please reopen. Landuse=forest - as every landuse - is about "human use of land". It does not dictate that every square inch is covered with trees. This change/regression hits our weakness about landuse/landcover. A small pond is IMHO part of a forest. Same goes for a cabin and a small parking space besides.

**Comment by matkoniecz** [comment]
> Same goes for a cabin 

Buildings are intentionally rendered above tree symbols (see )

> and a small parking space besides. 

Small parking space under trees is a part of forest and showing tree pattern is intentional in that case and fixes #888/#1309 (reported for parks but affects also other landocvers like amenity=parking). Huge parking spaces are not a part of forest and displaying pattern is also intentional as it allows to spot tagging problems.

> his change/regression hits our weakness about landuse/landcover.

I agree. Hopefully it will result in introducing tagging scheme allowing in marking areas used by forestry - both forest and area that temporarily is logged and supporting infrastructure (as currently there is no tagging cheme that supports marking areas like this).

**Comment by dieterdreist** [comment]
sent from a phone

> Am 18.08.2015 um 09:28 schrieb jojo4u <notifications@github.com>:
> 
> A small pond is IMHO part of a forest



it can be seen like this, but the current rendering team seems to have decided that landuse=forest does requires trees growing on every part of the area. Basically we can't agree / decide on this (what kind of forest object (or is it a property?) landuse describes) for years (e.g. landcover proposal is from 2010). Fortunately something seems to move recently
