### ISSUE TITLE
Residential landuse too light on midzoom

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#1755]
Now residential roads no longer show up on zoomlevels 12 and smaller, residential areas have become a lot lighter on mid zoom levels:

http://www.openstreetmap.org/#map=11/49.5918/6.1736

![screenshot from 2015-08-16 23 14 58](https://cloud.githubusercontent.com/assets/5251909/9295392/c1f0e110-446c-11e5-845a-becf95de2ad3.png)

Forests and farmland are more colourful, so they attract more visual attention than residential. I would consider residential more important than other landuse at zoomlevels 10-12, so maybe we could make residential a bit darker on these zoomlevels?

CC @pnorman

**Comment by pnorman** [comment]
> I would consider residential more important than other landuse at zoomlevels 10-12,

What about landuses in cities, like industrial, retail, and commercial?

**Comment by matkoniecz** [comment]
I would consider farmland as the worst problem with #1701 as potential method for solving it.

**Comment by kocio-pl** [comment]
@pnorman As far as I remember there was a proposition to aggregate all of human-related areas into something grey (residential or close to it) on some low enough zoom level.

**Comment by imagico** [comment]
In addition to #1701 it might make sense to also brighten the grass color a bit, Lch(92,32,128) seems to work fine, even brighter would collide with campsite.  This is how this looks at z12:

![z12](http://www.imagico.de/files/lc_bright_z12.png)

It could also make sense, at z12 and especially at z<12, to darken the urban landuses somewhat - would need to take care to maintain sufficient contrast with the minor roads of course.

**Comment by math1985** [comment]
This is improved by #1701, after this is rolled out we'd need to see if changes to residential is necessary too.

**Comment by matkoniecz** [comment]
> This is improved by #1701, after this is rolled out we'd need to see if changes to residential is necessary too.

I think that built-up areas should be more prominent.

![selection_001](https://cloud.githubusercontent.com/assets/899988/15944829/a5420ce8-2e8f-11e6-9899-e74647bc7f92.png)

http://www.openstreetmap.org/#map=11/50.3520/18.8223

**Comment by kocio-pl** [comment]
Resolved by https://github.com/gravitystorm/openstreetmap-carto/pull/2654.
