### ISSUE TITLE
Undo/refine "display highway=path like highway=footway"

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#1757]
Rendering of highway=path changed recently with a css update.
I think commit 8d850af2978e9200d18858bc998e04eba85206dc is the one.
Area of interest: https://www.openstreetmap.org/#map=17/51.51748/9.98481

* A proper designated municipal footway with gravel/compacted surface is now in the same visual class as a puny forest trail. Both are rendered with weaker dots, but any designated footway is better than a forest trail.
* The contrast of 'unpaved' ways with their weak dots is now much worse on any kind of green background (like forest and landuse=grass)

I am entertaining a number of independent options:
* Use weak dots for all highway=path, use normal dots for all highway=footway
* Render footways and cycleways as dashes rather than dots, like OsmAnd does
* Considering a darker shade of red for footways
* Using black for footways (since paths no longer have a special rendering)
* Restore black dashed lines for highway=path

**Comment by gravitystorm** [comment]
> A proper designated municipal footway with gravel/compacted surface is now in the same visual class as a puny forest trail.

This has always been the case. Depending on the preference of the individual mapper, both could have been mapped as highway=path, or both could have been mapped as highway=footway. There are extensive discussions on this issue tracker already ( https://github.com/gravitystorm/openstreetmap-carto/issues/1698 , https://github.com/gravitystorm/openstreetmap-carto/pull/1713 , https://github.com/gravitystorm/openstreetmap-carto/pull/1713#issuecomment-131599082  etc)

If you would like to propose specific changes that is great, please open pull requests or specific issues. But the unification of highway=path and highway=footway is deliberate and carefully considered, so if you want to see differences in rendering, you need to consider other tags like surface.
