### ISSUE TITLE
Inconsistent rendering sequence for overlapping natural=wood and amenity=hospital

### ISSUE THREAD

**Issue by BushmanK** [gravitystorm/openstreetmap-carto#1768]
Here http://www.openstreetmap.org/#map=16/55.8363/37.7447 is a closed way, tagged as  `amenity=hospital`: 
http://www.openstreetmap.org/way/48942520#map=16/55.8363/37.7457 

It intersects with three objects, tagged as `natural=wood` with different resulting rendering:
http://www.openstreetmap.org/relation/5446819 "goes under" the hospital territory (only tree pattern is visible of wood texture),
http://www.openstreetmap.org/way/127976385 and http://www.openstreetmap.org/way/366229725 are overlaying it.

Judging by two other cases I know, it depends on what is tagged as `natural=wood` - plain way or multipolygon.

I don't know, which of two variants of rendering is considered correct. For me, being able to see both yellow hospital fill and tree pattern gives an idea, that area is forested, which is good. 
But I don't have any preference here, it only should be consistent.

This difference seems to be causing multiple cases of wrong mapping, where people  adding smaller extra wood objects to overlay pale yellow hospital fill.

**Comment by pnorman** [comment]
The order fills are drawn is by area. See #888 and #882. Unfortunately, there's not really anything we can do here.
