### ISSUE TITLE
Improve living street rendering

### ISSUE THREAD

**Issue by gupascal** [gravitystorm/openstreetmap-carto#1769]
**highway=living_street** is currently rendered using a dark gray which is not very intuitive regarding its meaning for "standard" users. Instead, this color suggests a deserted road or a path where you can not drive. Also, with the current color, when all the center of a city has living streets, there is a big readability loss: http://www.openstreetmap.org/#map=17/45.04412/3.88433

That's why it should be interesting to change the rendering of highway=living_street

Here are a couple of ideas for a new rendering:

* a dashed rendering, with white road and light gray dashes.
* simply a lighter gray road.

**Comment by HolgerJeromin** [comment]
The whole road style including living street is being reworked in #1736

**Comment by matkoniecz** [comment]
Yes, exactly this problem is supposed to be fixed by #1736 (for more thorough discussion about this issue see where @imagico proposed solution used in #1736 see http://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35555 , section "highway=pedestrian, highway=living_street")
