### ISSUE TITLE
Add rendering for landuse=plant_nursery

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#1772]
For [landuse=plant_nursery](http://wiki.openstreetmap.org/wiki/Tag%3Alanduse%3Dplant_nursery), there was an old PR #187 closed because the pattern was not suitable. Still the feature needs rendering, it now has [7.5k](http://taginfo.openstreetmap.org/tags/landuse=plant_nursery) uses. 

I'd say just a fill colour and a name would be suitable, the colour the same as an orchard. Icon would be too tricky to understand (grown trees were difficult enough), the purpose should be recognisable from the name.

[Here is one](http://www.openstreetmap.org/way/9759196#map=17/52.54648/13.27951).

**Comment by HolgerJeromin** [comment]
yes, this would help to show how large this garden_centre is
http://www.openstreetmap.org/way/225030927
landuse=commercial would be another way, but plant_nursery is fitting better.

**Comment by imagico** [comment]
Could use a more fine grained version of the orchard pattern, like [this](http://www.imagico.de/map/jsdotpattern.php#x,128,jdp32360;gv,6,32,32;rd,1,0,0,pixel,0.125,4,4,0,jdp23814,749d6c,aedea3;).

**Comment by polarbearing** [comment]
Usage has grown to 8.4k since opening, people are asking on the tagging list. 

Another possibility to render would be identical to ```greenhouse_horticulture```.

**Comment by kocio-pl** [comment]
Now the usage is 12541 (lines only). I like original proposition - orchard color is already distinct, so using it without the pattern would be enough for me.
