### ISSUE TITLE
render landuse=aquaculture

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#1774]
Hello, dear CartoCSSers.

I just noticed `landuse=aquaculture` isn't rendered. I don't know for other countries, but, here in France, this is a common land use along the coasts, usually tens of hectares lots; mainly oyster beds, but we are not the only ones who have this kind of farming, for oysters or other species, and it can be a useful feature of the seascape to guide oneself on the tidal flats, or simply to avoid damaging them by piloting one's boat on them. Should be good to render it. A suggestion for the rendering: using a striped zone with a deepest blue than the one used for the sea?

Hoping this is relevant,

Regards.

**Comment by polarbearing** [comment]
[6.8K uses](https://taginfo.openstreetmap.org/tags/landuse=aquaculture#overview), and [wiki](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Daquaculture) started 2012.

Can you point to good examples? Can we assume that there is some water feature mapped as well?

**Comment by Penegal** [comment]
Well, there's [this one](https://www.openstreetmap.org/way/67303378) or [that one](https://www.openstreetmap.org/way/67303372), and you can find [here](https://www.openstreetmap.org/edit#map=16/45.8478/-1.1853) an untagged example, to see the space such landuse can... well, use.

**Comment by matkoniecz** [comment]
Probably rendering should happen in layer used by forest symbols to keep it visible in lakes.

**Comment by kocio-pl** [comment]
Maybe some simple shells pattern should be used here?

**Comment by polarbearing** [comment]
Pattern yes, the question is which. Aquaculture could also be salmon in the sea and freshwater fish in ponds. Maybe a fish icon is more generic. The 'fishmonger' would also sell shells.

**Comment by kocio-pl** [comment]
We already use fish icon for fishmonger shops, but it would probably be just the outline and no in violet, so it's also the shape available to use here.

**Comment by kocio-pl** [comment]
Set of propositions on z14 using current seafood icon with black, 10% gray and marina-text with or without background (quarry color):
![aquaculture-black-14](https://cloud.githubusercontent.com/assets/5439713/9706310/a2fc237a-54e1-11e5-863a-55a116be6003.png)
![aquaculture-black-nofill-14](https://cloud.githubusercontent.com/assets/5439713/9706311/a4d7bc86-54e1-11e5-8182-2c7c4cd1e69d.png)
![aquaculture-gray10-14](https://cloud.githubusercontent.com/assets/5439713/9706313/a8bfbd9e-54e1-11e5-8c0c-bca5a77db356.png)
![aquaculture-gray10-nofill-14](https://cloud.githubusercontent.com/assets/5439713/9706314/aa71ba52-54e1-11e5-9ea8-77b008fa4156.png)
![aquaculture-marina-14](https://cloud.githubusercontent.com/assets/5439713/9706315/ad0ae874-54e1-11e5-8405-00905debb624.png)
![aquaculture-marina-nofill-14](https://cloud.githubusercontent.com/assets/5439713/9706316/ae804848-54e1-11e5-8cec-7b848d023ae7.png)

**Comment by HolgerJeromin** [comment]
Imo most of them are too heavy. The variant with the border and the icon is nice. Could you try something between the fourth and last fish color?

**Comment by polarbearing** [comment]
Thanks. The first one looks like a piranha army invading :-) . There should be no special background since it is no different kind of water. A blue lighter than the sea could be used for the fish, I think that is what Holger means, and a blue slightly darker than the sea for the boundary.

**Comment by kocio-pl** [comment]
Icons with water-text color (border gray and water-text):
![aquaculture-water-gray-14](https://cloud.githubusercontent.com/assets/5439713/9706741/8d5387ee-54ef-11e5-85bc-f3cdd003d138.png)
![aquaculture-water-water-14](https://cloud.githubusercontent.com/assets/5439713/9706742/8f0fea0a-54ef-11e5-9a0a-05cf777dc887.png)

**Comment by polarbearing** [comment]
Border in water-text colour is good now. Fish is still quite heavy, I'd prefer the subtlety trees have in the forest. Could we have just the outline of the fish?

The feature should have very little prominence, it's just the crop from some type of farming, comparable with an orchard in feature importance.

**Comment by kocio-pl** [comment]
The same water-text border, icon with halfway color between water and white:
![aquaculture-dae7e7-14](https://cloud.githubusercontent.com/assets/5439713/9706832/d803c372-54f3-11e5-89f2-94af58353c31.png)

**Comment by polarbearing** [comment]
Good progress from my perspective, let's wait for some more opinions from the daytime folks.

**Comment by imagico** [comment]
I am not sure if the fish symbol is ideal here - It could equally indicate a fish catching area, incidentally this is probably a much more common application of a fish symbol pattern in maps.

I have no specific suggestion for a better pattern but something clearly indicating a fixed installation would be important.  Since mollusc farms are frequently in tidal areas it would also be important for it to work well in combination with wetland=tidalflat.

**Comment by Penegal** [comment]
I agree with imagico: even if I have no better idea, that seems to indicate a fishing area, or something limited to fishes, even for mollusc farms. Besides, as this landuse is somewhat mixed, because it doesn't necessarily ban other uses of the area such as swimming or sailing, maybe a dashed limit could be better.

**Comment by kocio-pl** [comment]
> The feature should have very little prominence, it's just the crop from some type of farming, comparable with an orchard in feature importance. 

Let's try something abstract like "underwater orchard" - icon with the same color (green could be good for algae):
![aquaculture-dot-orchardgreen-14](https://cloud.githubusercontent.com/assets/5439713/9719807/71714e28-5588-11e5-84e1-5618bd2e252d.png)

icon with a color halfway between water and white (subtle):
![aquaculture-dot-dae7e7-14](https://cloud.githubusercontent.com/assets/5439713/9719656/bf963b38-5586-11e5-97f1-0255ea244c45.png)

white dot (more contrast then above):
![aquaculture-dot-white-14](https://cloud.githubusercontent.com/assets/5439713/9719938/7576a6de-5589-11e5-9dda-ff72c2a207cf.png)

black dot (as in "general"):
![aquaculture-dot-black-14](https://cloud.githubusercontent.com/assets/5439713/9719844/ab67e1b4-5588-11e5-8d58-0da5bea4f6c0.png)

water-text dot (as the boundary line - like "some water-related things"):
![aquaculture-dot-6699cc-14](https://cloud.githubusercontent.com/assets/5439713/9720018/5bb27eb6-558a-11e5-85ae-637f9c8ae7d2.png)

**Comment by polarbearing** [comment]
So if people don't like fishes, the orchard dots are a good idea. The last one, water-text dot colour, works best for me.

**Comment by HolgerJeromin** [comment]
I do not recognise the first image as green, but i like it anyway. Could live with the last, too.
It is very dependent of the monitor (settings), second image pattern is not visible here.

**Comment by Penegal** [comment]
I agree with @polarbearing : the last one is the best proposal IMHO.

**Comment by kocio-pl** [comment]
@Penegal Yeah, in polish it's the same ("owoce morza") :wink: , however the idea came to me right from the @polarbearing notes.

**Comment by mboeringa** [comment]
+1 for the last proposal.

**Comment by meased** [comment]
I have used this tag in the northwest US to map salmon hatchery grounds that are not over water. I wonder how this would look in that context. Any rendering at all would be awesome though.

Example [here](https://www.openstreetmap.org/#map=17/45.27649/-122.20294).

**Comment by HolgerJeromin** [comment]
The salmon hatchery ground felt wrong at first, but the wiki states "Area on land or sea, where fish, shellfish, or shells are breed". So this should look ok on land, too.

**Comment by kocio-pl** [comment]
I was thinking a bit what does "Area on land or sea" mean and I'm not sure if it's also land devices or just water ponds on the land (as opposed to the open sea). What do you think?

**Comment by polarbearing** [comment]
https://www.openstreetmap.org/way/369021245 seems what @meased means. 

My preferred interpretation would also give the aqua tag only to the water features and keep the site as landuse=farmyard or =commercial.

**Comment by kocio-pl** [comment]
Could you write about it on Tagging? I have some other things at the moment and it's worth making clear.

**Comment by matkoniecz** [comment]
I think that given already found interpretation problems it would beneficial to run it through proposal process before potential rendering.

**Comment by kocio-pl** [comment]
I don't know if the full process is necessary (it's rather clarification than expansion), but there's no rush and I like to work with the Wiki definitions more in a feedback way.

**Comment by meased** [comment]
>My preferred interpretation would also give the aqua tag only to the water features and keep the site as landuse=farmyard or =commercial.

@polarbearing: I like your interpretation better than mine.

**Comment by math1985** [comment]
@malcolmh Am I right that you are the person behind OpenSeaMap?

We have some problems finding a good representation for landuse=aquaculture for the default openstreetmap rendering. Do you have any suggestions? Do you know how aquaculture is displayed on other (maybe paper) maps?

**Comment by malcolmh** [comment]
The international standard for marine maps is: http://www.iho.int/iho_pubs/standard/S-4/INT1_FR_Ed5_2012.pdf
Sections K.44 - K.48 illustrate the symbols used for the various types of aquaculture.

**Comment by polarbearing** [comment]
Ok, so basically a thin outline of either a fish or a shell, and a dotted or dashed border for haven vs. culture. 

And the fish swimming left to right.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 17.09.2015 um 00:32 schrieb Malcolm Herring <notifications@github.com>:
> 
> The international standard for marine maps is: http://www.iho.int/iho_pubs/standard/S-4/INT1_FR_Ed5_2012.pdf
> Sections K.44 - K.48 illustrate the symbols used for the various types of aquaculture.


could we use these from a legal point of view? The document states at the bottom of the page "all rights reserved"

**Comment by math1985** [comment]
I think if we don't copy them literally, but use the same concepts (e.g. a brown dashed line with a shell in it) we should be fine.

**Comment by malcolmh** [comment]
On 17 Sep 2015, at 08:12, dieterdreist <notifications@github.com> wrote:
> 
> could we use these from a legal point of view? The document states at the bottom of the page "all rights reserved"

The document itself is copyright, but the information within is intended for unrestricted use - the whole point of a standard.

**Comment by imagico** [comment]
Please keep in mind this document outlines ideas for printed marine maps.  Those have very special properties, in particular they are not designed for a general audience but for readers with very specific qualifications and expectations.  This style is not a marine map and violates some of the most basic principles of those and is not a printed map either so concepts from marine maps will not necessarily work well here.

Note there are some interesting concepts shown there, in particular the 'outline with symbols interleaved' technique.  In general most of the ideas there will however only work on very specific scales, for marine farms they have three suggestions for example:

* single icon (two different versions)
* outline with single icon in the middle
* outline with symbols interleaved

Each of these is clearly intended and will only work well on a specific scale.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 17.09.2015 um 09:24 schrieb Malcolm Herring <notifications@github.com>:
> 
> The document itself is copyright, but the information within is intended for unrestricted use - the whole point of a standard.


just because it's a standard doesn't automatically mean you can use it for free (could require you to pay licensing fees for instance)

**Comment by imagico** [comment]
Just a remark since this came up in #1990 - both the pictorial and the abstract pattern idea have potential here i think - you would have to rethink the outline though and avoid the fishing association (for example by combining fish and mollusc symbols).

**Comment by kocio-pl** [comment]
I'm not sure that we can find a proper solution and this might be not too important on general map. This ticket can be reopened if there are some ideas how to do it, of course.

**Comment by SomeoneElseOSM** [comment]
As an example of what rendering these look like, have a look at e.g. http://map.atownsend.org.uk/maps/map/map.html#zoom=13&lat=53.2496&lon=-9.7291 .  That's just using the "landuse=commercial" colour from z12, but gives an idea of how much features like this "crowd other features out".

As an aside re tagging, in the UK and Ireland there's also some use of fish_farm and fishfarm for presumably the same features, and "aquaculture" is also used for inland fisheries too.

**Comment by kocio-pl** [comment]
Thanks for your hints! :+1: It's good to compare with something which is already used elsewhere.

This idea is smart (even if I would rather use "industrial" color), but I don't like the rendering, because it's too strong and doesn't look like a water any more.

**Comment by Adamant36** [comment]
@kocio-pl, any chance of revisiting this now that there is a pattern creation tool and its usage has increased to 23,000? Maybe @jeisenbe can come up with something workable. If nothing else, it could just have an outline, since its like a protected area, or the names could just be rendered. 
![taghistory 7](https://user-images.githubusercontent.com/30259065/48937035-bf46ff00-eec1-11e8-94ad-199f59b2b701.png)

**Comment by matkoniecz** [comment]
Rendering just name will encourage tagging for renderer.

I think that it is not at all like protected area (rather opposite).

**Comment by Adamant36** [comment]
@matkoniecz, I guess your right on it not being a protected area. I originally found the tag by look for how to tag fish hatcheries and that was what came up. I think government fish hatcheries would be protected areas. I wouldn't be surprised if people were tagging them with this tag either. Since there doesn't seem to be an alternative. Either way, even if its not a protected area that doesn't mean it couldn't be rendered with an outline.

**Comment by jeisenbe** [comment]
An outline is the best option, if aquaculture areas are to be rendered at
all. These areas can be completely within a larger body of water, such as a
lake or the sea, but other times enclose a number of small artificial
ponds. The ponds or other water are already rendered and should still be
most visible on the map.

Perhaps an outline similar to the farmland outline color would work, with
no fill?

**Comment by polarbearing** [comment]
The test renderings from 2015 were all focusing on sea-based mapping. Could we dig for how many are mapped on land with ponds and how many on sea? 

An outline alone might not be self-explanatory, thus a pattern or an icon would be required.

**Comment by oinag** [comment]
Is this still active? I think that this render should not only include the fish or shell, but icons of all types of aquaculture in the Wiki (fish, oyster, shrimp, mussels).

**Comment by jeisenbe** [comment]
@oinag - would you be interested in designing this?

**Comment by oinag** [comment]
@jeisenbe Yes, although I do not have experience with contributing to Carto. I expect that there is a guide on designing patterns, right?

**Comment by imagico** [comment]
There is no specific guideline for pattern design in OSM-Carto.  Some general tips:

* patterns should be weaker in appearance than individual point symbol or other signatures in the map.
* patterns need to be periodic and in a size that is a fraction of the metatile size (i.e. a power of two).
* patterns should be designed as SVG files although a mapnik bug requires us to use a PNG version for accurate rendering.
* most patterns are designed based on the appearance of the area in question in direct view instead of indirect depiction of products derived from it like crops.  This is not a fixed principle though.
* patterns should if possible be designed in a way that they are intuitively recognizable.
* patterns should not be misleading or encourage abuse of a tag for a different purpose.
* patterns should be designed in a way that their symbols are not mistaken for individual mapped features.
* useful tool for creating patterns is here: http://www.imagico.de/map/jsdotpattern.php

**Comment by oinag** [comment]
@imagico Thank you, I will see what I can do, however I think using the symbols for the products (fish, shrimps...) will be necessary.  As you said, patterns should be easily recognizable

**Comment by endim8** [comment]
It'd be good to have this implemented, currently `landuse=aquaculture` is used 61,425 times.

I think rendering as opaque white with an outline similar to `leisure=nature_reserve` (with the gradated inside) could be good. Also rendering a name. Something like this:
![Screenshot 2022-09-13 at 14 02 26](https://user-images.githubusercontent.com/26939824/189911129-d1572a1b-3949-4cdd-ac45-f2e12426da0d.png)
[location](https://www.openstreetmap.org/way/1094128851)
