### ISSUE TITLE
Tree symbols should now be rendered over natural=water

### ISSUE THREAD

**Issue by tob2** [gravitystorm/openstreetmap-carto#1780]
If one has a landuse=forest and within this landuse a natural=water, the blue water surface is drawn over the green forest background.

However, the tree symbols are drawn after the water-blue and, hence, one gets tree symbols on the water, which looks odd. One example of this is http://www.openstreetmap.org/#map=19/47.92253/11.78772 - but I spotted this elsewhere as well.

**Comment by matkoniecz** [comment]
Duplicate of #1754
