### ISSUE TITLE
Coherent color system for the POIs

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1783]
When trying to add [new icon for amenity=car_wash](https://github.com/gravitystorm/openstreetmap-carto/pull/1777) I have noticed that we have also shop=car_repair and I had the problem [what color to use](https://github.com/gravitystorm/openstreetmap-carto/pull/1778), because they are very similar (paid services for cars), yet they have different key. 

After [asking on Tagging](https://lists.openstreetmap.org/pipermail/tagging/2015-August/026102.html) I've learned that it's more complicated than that and in fact [all the "amenities" which sell goods or services should be shops instead](https://lists.openstreetmap.org/pipermail/tagging/2015-August/026105.html). This is far outside the rendering scope, but it means we should define our guidelines on POI colors.

While I think using purple for health related POIs (be it for people or animals, goods or services, paid or not) and blue for transportation or traveling (paid or not, directly or indirectly like hotel or embassy probably) is pretty clear, and I like black to be used as a general color (for landmarks for example), I'm not sure which system should we use for amenities and shops:

1) Treat them as they're tagged, no matter what. I don't like it, because we don't take things blind in other cases and car wash/car service would look rather strange with different colors.

2) Make it as it should be tagged - shop-violet for anything selling goods or services, amenity-brown for the rest. It would mean making the cinemas and theaters look like shops, because they typically are selling services (through tickets), but also all the eating and drinking places. This would cause changes in a lot of places.

3) Make violet for selling goods (I don't know what about giving goods? maybe it's just kind of service then?) and brown for all the services (paid or not). That is what we have now more or less and car wash/car service would be both brown, but also we should change the color of hairdresser/beauty shop to brown. This would also work [for craft and office POIs](https://github.com/gravitystorm/openstreetmap-carto/issues/1697), once we have them.

I would choose 3, what do you think about it?

**Comment by math1985** [comment]
Question for the native English speakers - would hairdressers and car_repair shops be typically included in the term 'retail'?

**Comment by kocio-pl** [comment]
Another observed color problem: leisure=swimming_pool has brown icon and green text, while golf icon is light green with darker green text. Probably coherent green color for icon+text could be used for all sport activities (not for the shop=sports however).

**Comment by SK53** [comment]
@math1985 yeah I include services in retail, as does Pete Reed (tlalet).

It is certainly useful to keep a distinction between retailers providing services at point of sale (pubs, restaurants, fast food, hairdressers etc), from products. This is particularly true for shop=beauty which may include both nail salons and shops selling cosmetics. Remember certain types of shops have always had a strong service element (department stores come to mind). (One of those areas where one might have started out with retail=shop or retail=services rather than what we have; and shop is also used for a small number of retail areas not outlets such as mall). From my point of view if would be nice to distinguish product vs service, but I dont think it makes a great deal of difference.

That being said, almost everything to do with the motor trade (fuel, shop=car, shop=car_parts, amenity=car_wash, shop=car_repair) has somewhat different characteristics from other retail. For instance car repair yards are usually better tagged as landuse=industrial because they generate toxic waste.

**Comment by HostedDinner** [comment]
@kocio-pl in your comment you mean leisure=water_park (the area around), not leisure=swimming_pool (the pool itself)

**Comment by kocio-pl** [comment]
Thanks, so it's another case to fix.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 24.08.2015 um 20:29 schrieb SK53 <notifications@github.com>:
> 
> This is particularly true for shop=beauty which may include both nail salons and shops selling cosmetics.
> 


i don't think that's a good idea to mix these two.

> Remember certain types of shops have always had a strong service element (department stores come to mind).
> 


the department stores I know of don't offer any services besides a restaurant

> That being said, almost everything to do with the motor trade (fuel, shop=car, shop=car_parts, amenity=car_wash, shop=car_repair) has somewhat different characteristics from other retail. For instance car repair yards are usually better tagged as landuse=industrial because they generate toxic waste.
> 


also computer/electronics shops produce toxic waste, and also some articles found in a drug store are toxic, the same for paint or pharmaceuticals and likely more. I don't think they should all be considered industrial. Producing toxic waste wasn't a criterion so far for deciding whether something is a shop or an amenity. Even offices produce toxic waste (laser toner cartridges) not to speak about hospitals...

**Comment by kocio-pl** [comment]
While fixing inconsistent icon/label colors can (and should) be done for example with #2827, the original idea of crafting color system for icon types, especially shop/amenity, failed, so I'm closing this issue.
