### ISSUE TITLE
unify rendering for railway=rail and railway=preserved

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1785]
Currently railway=rail and railway=preserved are rendered differently. I think that difference between these two features is relatively minor (railway=rail also may have really limited service or be limited to freight and both features are the same structures, with difference only in usage).

Rendering railway=preserved like railway=rail would allow to reduce complexity of map in place where it is not highly useful.

On encountering railway=preserved at http://www.openstreetmap.org/#map=18/48.03615/16.79425 its meaning was not clear and such surprise is probably quite typical given that tag is rare and rendering is not obvious.

In addition [railway:preserved=yes; railway=*] seems to be recommended tagging (at least according to http://wiki.openstreetmap.org/wiki/Tag:railway=preserved ).

Complete removal of railway=preserved is probably a poor idea at this moment given that it is used over 10k times.

**Comment by Gazer75** [comment]
Please do not combine these. It's nice to see what is a museum line and whats not.
The wiki page you link to also have it as deprecated. AFAIK all preserved museum lines should use railway=preserved as is listed in http://wiki.openstreetmap.org/wiki/Key:railway#Values

**Comment by pnorman** [comment]
> In addition [railway:preserved=yes; railway=*] seems to be recommended tagging (at least according to http://wiki.openstreetmap.org/wiki/Tag:railway=preserved ).

Looking at the usage data, I'd disregard what the wiki says and prefer railway=preserved.

Given the similarity, I'd support rendering them the same and leave distinguishing them to a more specialized map style.

**Comment by Gazer75** [comment]
A preserved railway track is actually quite different than regular railway. There is no normal scheduled traffic on the line and it is often maintained by a group of volunteers and/or a private organization.

Why is there a need to change how it currently is? If there are railways tagged with preserved that should not then fix it instead of combining them.
Combining them might make people think that there is a regular service on the line.

**Comment by matkoniecz** [comment]
> Why is there a need to change how it currently is? The details of the default osm map is what set it apart from other maps. 

See #1630. In general - we reached point where maintainers of map are sometimes unable to understand what is displayed on map.

And number of displayed features is still increasing (see https://github.com/matkoniecz/CartoCSSHelper/commits/master/lib/cartocss_helper/style_specific/default_osm_style.rb), we need also to remove less useful distinction

**Comment by gravitystorm** [comment]
I'd prefer to keep the distinction - as @Gazer75 says, there are significant differences between them, in terms of operations, services, prices etc.

**Comment by matkoniecz** [comment]
So once proper tagging will be introduced we will start displaying also freight-only railway lines in a separate style? 

I think that it would be too much for general purpose map - and in that case differences would be even more significant.

**Comment by Gazer75** [comment]
The more the merrier I say :) So I can't really agree with #1630. Only issue might be where to many POIs overlap, but this railway thing is not a problem.

Have to admit I didn't realize there are railways that only do freight. But then I am from Norway with barely 5 million people and an old and outdated rail network. Freight run on the same tracks and mostly at night. No space on our mostly single track network during the day :)
