### ISSUE TITLE
Bug in rendering building over ways when bridge=yes and layer=1

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#1786]
Hello, there.

I noticed a bug in rendering [here](https://www.openstreetmap.org/#map=19/48.56314/6.11026): the building crossing the railways, which is a skyway, is tagged with `building=yes`, `layer=1` and `bridge=yes`, and the railways passing under it have no `layer` tag, so the building should be rendered over the railways, not under; still, it isn't. As far as I know, it's a rendering bug.

Hope I'm not wrong.

Regards.

**Comment by pnorman** [comment]
Area described is

![image](https://cloud.githubusercontent.com/assets/1190866/9482786/b3ec138c-4b4c-11e5-8d73-9e4d03c385b6.png)

Rendering transportation after buildings is an intentional choice, or you'd never see the transportation under them.
