### ISSUE TITLE
Is it a good idea to render destination dashes for path/footway and tracks?

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1787]
According to taginfo over 14k path/footway ways are tagged with access=destination and almost 15k highway=track ways - see http://taginfo.openstreetmap.org/tags/access=destination#combinations

It is more than for some road types where access=destination is rendered but it is not clear for me what is tagged this way in case of footways. In case of tracks adding rendering seems to be a good idea.

It is not rendered for major roads but according to taginfo it is not used in combination with this type of roads.

Below is rendering of current road types with access=destination applied.

https://cloud.githubusercontent.com/assets/899988/9466051/fc0d0920-4b31-11e5-8aa4-6629ef29b2bd.png

**Comment by matkoniecz** [comment]
In case of rendering destination dashes for paths/footways - also cycleways and steps should receive them to keep this in synch.

**Comment by math1985** [comment]
What does access=destination mean in these cases? Only pedestrians can use the paths if they are destination traffic, or cars can use the paths as well if they are destination traffic?

**Comment by pnorman** [comment]
> What does access=destination mean in these cases? Only pedestrians can use the paths if they are destination traffic, or cars can use the paths as well if they are destination traffic?

It's probably unclear what the mappers meant.

**Comment by matkoniecz** [comment]
So it seems that we should assume that access=destination is probably tagging error on footways. What about tracks?

Has anybody encountered highway=track where access=destination was a valid tagging?

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/way/26008471 is a clear agricultural track (so track is right) but cars are allowed to drive to the "forsthaus lohoff". Ok, this is not tagged as access=destination.

cc @flohoff since he has written about access, tracks and routing on german ML a while ago.

**Comment by HolgerJeromin** [comment]
I am not sure if access=destination on footways/path should be a considered a tagging error. There are places in the world, which does not allow passing pedestrian but only for destination. 

If the highway tag forbids vehicles why should i tag foot=destination and bicycle=destination? Probably i had forgotten inline_skates, horses, segways, snowmobiles... with this tagging. IMO it is very clear what the mapper meant. Or at least how the data has to be interpreted.

**Comment by matkoniecz** [comment]
> There are places in the world, which does not allow passing pedestrian but only for destination. 

Can you give an example? I never encountered place that would require such tagging.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 15.09.2015 um 09:12 schrieb Holger Jeromin <notifications@github.com>:
> 
> https://www.openstreetmap.org/way/26008471 is a clear agricultural track (so track is right) but cars are allowed to drive to the "forsthaus lohoff". Ok, this is not tagged as access=destination.


maybe there should be a short way highway=service leading to the Forsthaus Lohoff rather than track? The Forsthaus is on residential landuse, so I'd expect it to be accessible via at least a service road (in Germany).

**Comment by matkoniecz** [comment]
> maybe there should be a short way highway=service leading to the Forsthaus Lohoff rather than track?

It seems likely, I opened https://www.openstreetmap.org/note/435053

**Comment by math1985** [comment]
> Has anybody encountered highway=track where access=destination was a valid tagging?

Yes, hundreds of them in Luxembourg, i.e. [here](https://www.google.nl/maps/@49.6173612,6.0183529,3a,75.9y,268.6h,75.92t/data=!3m6!1e1!3m4!1sxIfftLEL5zpk28X-PfI9_A!2e0!7i13312!8i6656?hl=en). 

The definition of the sign is 'forbidden in both directions for drivers of vehicles and animals, with exception of residents and their suppliers'.

(Don't be confused by the surface, this is really a road for agricultural purpose.)

**Comment by dieterdreist** [comment]
sent from a phone

> Am 15.09.2015 um 11:20 schrieb math1985 <notifications@github.com>:
> 
> Has anybody encountered highway=track where access=destination was a valid tagging?
> 
> Yes, hundreds of them in Luxembourg, i.e. here.
> 
> The definition of the sign is 'forbidden in both directions for drivers of vehicles and animals, with exception of residents and their suppliers'.
> 


this is vehicle=destination, not "access"

**Comment by HolgerJeromin** [comment]
Example for valid footway tagging: https://www.openstreetmap.org/way/37394140 
It has a bollard (so only passable for bicycle and foot, covered by the `highway` tag) and a sign "only for residents of the condominium" (`access`).

**Comment by matkoniecz** [comment]
> only for residents of the condominium

This is access=private. access=destination would allow also anybody wishing to go there (like door-to-door salesman).

**Comment by HolgerJeromin** [comment]
oh, these salesman are a good argument. Thanks.

**Comment by matkoniecz** [comment]
It seems that rendering destination in such cases would not be helpful, especially as anyway it is rare to find person understanding blue dashes.

I will keep for now destination branch that adds rendering of destination for highway=track but it may be deleted at any moment.

**Comment by aceman444** [comment]
> HolgerJeromin commented on 15 Sep 2015

> If the highway tag forbids vehicles why should i tag foot=destination and bicycle=destination? Probably i had forgotten inline_skates, horses, segways, snowmobiles... with this tagging. IMO it is very clear what the mapper meant. Or at least how the data has to be interpreted.

That would be the logical conclusion, however, the current evaluation algorithm of access is not in that way. access=destination on a footway really is to be evaluated as any vehicle can go there if it is destination traffic. See e.g. http://wiki.openstreetmap.org/wiki/Computing_access_restrictions#A_few_worked-out_examples

On the other hand, if the road physically allows vehicles, they are just forbidden unless they are destination, it should not be tagged a footway. That is probably what was meant in the comments above. It is not sure what the mapper really meant.
