### ISSUE TITLE
leisure=water_park should have same text and icon colour (and same zoom level)

### ISSUE THREAD

**Issue by HostedDinner** [gravitystorm/openstreetmap-carto#1794]
In my opinion leisure=water_park should have the same colour for the label and the icon.
Right now the icon is "amenity brown" and the text is "leisure green".
I suggest the green one, because it looks more natural (at least for outdoor swimming pools)
Onother point I have seen is, that the label is getting render at around 15, and the icon at 17. This should be consistent as well.

**Comment by kocio-pl** [comment]
[That's exactly what I think](https://github.com/gravitystorm/openstreetmap-carto/issues/1783#issuecomment-134228799). It's a part of the problem described in #1783.

**Comment by polarbearing** [comment]
This was observed in #1624 as well. However I would tend to see leisure=water_park within the theme_park scope and thus prefer brown icon, label and boundary.

**Comment by pnorman** [comment]
I'd consider it like playground around here

**Comment by HolgerJeromin** [comment]
This should je closed as a dupe #1490

**Comment by kocio-pl** [comment]
It's a different problem (icon/text match vs area outline), however this bug was fixed by #2827.
