### ISSUE TITLE
The forest pattern persists when forest landcover overlaps another landcover

### ISSUE THREAD

**Issue by Xevib** [gravitystorm/openstreetmap-carto#1796]
Example 
![image](https://cloud.githubusercontent.com/assets/2422305/9564343/4ee76c24-4ea4-11e5-9fb4-bcc631ce11f2.png)

Link:
http://www.openstreetmap.org/#map=18/42.42232/-6.70554

In this case residential landuse overlaps forest and the trees pattern persists on the residential zone

**Comment by matkoniecz** [comment]
This is an intended effect, introduced by #1728

In case that it is both residential and forest - rendering is correct and fixes #1309, #888.

In case that it is not both residential and forest - tagging is wrong and should be fixed and rendering intentionally makes problem visible.

**Comment by Nic787** [comment]
I think there should be a better way to put forest over other landuse. I know about not tagging for render, but I don't understand why something it's like that : 

![image](https://user-images.githubusercontent.com/11185348/115937234-68183080-a465-11eb-8868-2e145877a7ff.png)

And other areas it works.

![image](https://user-images.githubusercontent.com/11185348/115937283-93028480-a465-11eb-9fd8-46122bff7aa2.png)

It's very inconsistent.

I had the same problem of rendering farmland inside an airport border. I had to cut the actual farmland into two parts. One for outside the airport and one inside. I actually think vegetation or farmland should be seen more clearly inside other landuse.

**Comment by matkoniecz** [comment]
See #4371
