### ISSUE TITLE
names of amenity=kindergarten/school/college/university/grave_yard are not rendered

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#1800]
Example of the problem: the name of [this object](http://www.openstreetmap.org/way/339573260) was visible, but now it's not even on z19.

**Comment by matkoniecz** [comment]
It seems that something went wrong in https://github.com/gravitystorm/openstreetmap-carto/commit/4745130e3d4a67472e046c9a7c0c25eed6c132c6

(college also seems to be affected)
