### ISSUE TITLE
show names of aerialways

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1807]
http://overpass-turbo.eu/s/bfz - aerialways with names

**Comment by kocio-pl** [comment]
Great idea, the only problem is from which zoom level to start it and how big letter size should we use.

**Comment by yvecai** [comment]
This was removed a while ago, best to know why.

**Comment by mboeringa** [comment]
> Great idea, the only problem is from which zoom level to start it and how big letter size should we use.

1:50k, the first real topographic map scale, close to Z13/14. Many aerialways are at least one, or a couple of kilometres long. At 1:50k, this means at least 2 cm labelling space along the line, and in most cases more, which should be sufficient to place labels.

**Comment by matkoniecz** [comment]
@yvecai 

> This was removed a while ago, best to know why.

There was catch-all rendering - all name tags were rendered (including names on misspelled objects and names that were not deserving rendering).

**Comment by Penegal** [comment]
I'm willing to fix this, but first a question: a naive option could be to render the name as it is rendered for railways, because railways and aeroways are related in that they are mechanized means of transport, based on a steel way. Would that be OK? I ask now because that would mean, IMO, including aeroways in `railways-text-name` code, so I prefer not messing with such a piece of code before having some opinions.

**Comment by kocio-pl** [comment]
I think this is a valid solution.

**Comment by Penegal** [comment]
Would this way do it?
![image](https://user-images.githubusercontent.com/13777824/37389364-593818b8-2764-11e8-8703-3839a03dc7bd.png)
![image](https://user-images.githubusercontent.com/13777824/37389378-66eaec42-2764-11e8-8a22-21f302165531.png)

**Comment by matkoniecz** [comment]
Looks OK based on this examples - but maybe names should be a bit closer (or not, it may require testing with tall characters).

**Comment by yvecai** [comment]
'Petite Mauselaine' looks upside down, is there a way to write it bottom to top? 

Le 14 mars 2018 19:15:38 GMT+01:00, Mateusz Konieczny <notifications@github.com> a écrit :
>Looks OK based on this examples - but maybe names should be a bit
>closer (or not, it may require testing with tall characters).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gravitystorm/openstreetmap-carto/issues/1807#issuecomment-373123579

Yves

**Comment by Penegal** [comment]
It is not fully upside down, but slightly left to right; the problem is the orientation of the aerialway, almost north-south.

**Comment by kocio-pl** [comment]
Mateusz meant probably testing fake names with tallest characters possible with certain font size, like ÈÈÈÈÈÈÈÈ or ÉÉÉÉÉÉÉ.

**Comment by matkoniecz** [comment]
> Mateusz meant probably testing fake names with tallest characters possible with certain font size, like ÈÈÈÈÈÈÈÈ or ÉÉÉÉÉÉÉ.

Yes, I meant this. Sorry for confusion.

**Comment by mboeringa** [comment]
> I had the same issue on opensnowmap with icons on aerialways, but worse: it looks really ugly to have a gondola upside-down.

I don't think they're aiming for gondolas on the map here... Let that be a unique feature of OpenSnowMap.

**Comment by yvecai** [comment]
@mboeringa Sure, I was giving an example that could also apply to the text  orientation. Agreed this is not a major problem. 
Yves

**Comment by Penegal** [comment]
Here you are:
![image](https://user-images.githubusercontent.com/13777824/37524498-495e4a58-292a-11e8-9d70-c219f16d9332.png)

With `text-dy` decreased of 2px:
![image](https://user-images.githubusercontent.com/13777824/37524638-b7123618-292a-11e8-92a9-1cf119e44fa5.png)

**Comment by kocio-pl** [comment]
> With text-dy decreased of 2px:

The label still fits and it looks better, so I vote for this version.

**Comment by matkoniecz** [comment]
As long as it fits it is clearly preferable. Hmm, maybe it would be even better with name on aerialway, without text-dy? (feel free to ignore this idea).

**Comment by Penegal** [comment]
Without `text-dy`:
![image](https://user-images.githubusercontent.com/13777824/37582494-9641b7ea-2b4d-11e8-8920-a85452cf2ef8.png)

It decreases readability IMO; I think I should go with the previous `text-dy` value.
