### ISSUE TITLE
Frankfurt missing in z7 and z8

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#1811]
It is there in zoom6 but then disappears in favor of Offenbach:
http://www.openstreetmap.org/?mlat=50.147&mlon=8.600#map=8/50.147/8.600

**Comment by kocio-pl** [comment]
That's something related to https://github.com/gravitystorm/openstreetmap-carto/pull/1461, can you test if this code fixes the issue?

**Comment by matkoniecz** [comment]
duplicate of #1083
