### ISSUE TITLE
stop rendering historic=citywalls

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1812]
I am not sure is it a good idea to display historic=citywalls. Maybe it is expecting too much, but city walls [may be mapped as building=*](http://www.openstreetmap.org/?mlat=50.06494&mlon=19.94093#map=19/50.06494/19.94093).

Current historic=citywalls rendering is not intuitive, especially in places with building=* - see http://www.openstreetmap.org/#map=19/41.90367/12.45770

![selection_001](https://cloud.githubusercontent.com/assets/899988/6336522/721c2084-bba3-11e4-8c90-e5a986356aac.png)

Citywalls are visible early but it is not clear what is represented

http://www.openstreetmap.org/#map=14/53.3186/13.8433

![selection_001](https://cloud.githubusercontent.com/assets/899988/9682484/49250f46-5307-11e5-9378-a101e468c538.png)

see also  #1333

**Comment by imagico** [comment]
Actually the more common (19k vs. 6k uses) and more logical tagging is `barrier=city_wall`.  A simple city wall, in particular a onesided, embankment-like one - like [this](https://commons.wikimedia.org/wiki/File:Fort_Jaisalmer_at_sunset.jpg), should not be mapped as a building.

**Comment by nebulon42** [comment]
Related to #1333.

**Comment by dieterdreist** [comment]
I used to put both, barrier=city_wall and historic=citywalls, as its both in my case. There is also historic=city_gate http://taginfo.openstreetmap.org/tags/historic=city_gate (which would be nice to render the name btw.) --- barrier=city_gate is negligible. In past discussions the issue of historic citywalls that aren't a barrier now has been raised.

in my opinion we should render both tags.
