### ISSUE TITLE
man_made=bridge not rendering for linear ways, only enclosed areas. 

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#1818]
Hi
As the subject line really.
http://www.openstreetmap.org/way/368285628
http://www.openstreetmap.org/way/258251781

I thought both examples should render. Have I misunderstood the purpose?

Cheers
Dave F.

**Comment by polarbearing** [comment]
What is the point of man_made=bridge as a line with no width? The tag is for the physical feature of the bridge structure, and thus needs to be mapped as an area. Your test example is a tagging mistake. 

Wiki: "Area - Indicates the outline of a bridge and groups together all features for that bridge."

Please do not write test data into the main database.

**Comment by DaveF63** [comment]
It's disappointing its usage is limited to areas.
It should render on linear ways to allow bridges that have no current usage but are clearly visible on the ground to be rendered.

**Comment by matkoniecz** [comment]
See http://wiki.openstreetmap.org/wiki/Tag:man%20made=bridge - defined as 

> bridge defined by the outline of the bridge

As even narrowest bridges have width larger than 0 this tag is defined to be used on areas.

Therefore tagging as lines is a tagging mistake.

**Comment by matkoniecz** [comment]
In general - please, check wiki documentation before using new tags or reporting something that seems to be a bug.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 08.09.2015 um 13:54 schrieb DaveF63 <notifications@github.com>:
> 
> allow bridges that have no current usage but are clearly visible on the ground to be rendered.
> 


you don't need current usage for this tag. All bridges (maybe even fragments) can be tagged (and will be rendered also when there is no current usage).

**Comment by DaveF63** [comment]
On 08/09/2015 14:27, dieterdreist wrote:
>
>
> sent from a phone
>
> > Am 08.09.2015 um 13:54 schrieb DaveF63 <notifications@github.com>:
> >
> > allow bridges that have no current usage but are clearly visible on 
> the ground to be rendered.
> >
>
>
> you don't need current usage for this tag. All bridges (maybe even 
> fragments) can be tagged (and will be rendered also when there is no 
> current usage).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1818#issuecomment-138558660>.
>

Not if bridges are linear ways, which is how the vast majority are 
mapped. Only tagging closed ways for this tag seems an extremely 
restrictive & unnecessary action.

Cheers
Dave F.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by jojo4u** [comment]
The vast majority is tagged only implictly as "this linear way is leading over a bridge" since not better alternative existed.

**Comment by HolgerJeromin** [comment]
do you mix bridge=yes attribute for a highway=* with the standalone man_made=bridge outline?

**Comment by polarbearing** [comment]
> bridges are linear ways, which is how the vast majority are mapped

Could you prove these stats please? We have 5002 man_made=bridge today, I have mapped about 50 of them, 100% of them as area. Routable ways are the only major category in OSM where abstracting a spacial feature with a line provides a benefit. 

If you have a landmark that no longer has a routable way on it, and you want to show the structure, why would you not want to map its footprint? Bridge=yes is the abstraction for the routable way, while man_made=bridge is for the physical structure. 

BTW, your fictional w368285628 is still in the database.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 09.09.2015 um 01:05 schrieb polarbearing <notifications@github.com>:
> 
> Routable ways are the only major category in OSM where abstracting a spacial feature with a line provides a benefit.


there are also barrier, waterways, aqueducts, pipelines, power lines and maybe more. But I agree that bridges like other structures and buildings should be represented by an area.

cheers 
Martin

**Comment by gravitystorm** [comment]
Everyone, as @matkoniecz said when he closed this issue:

> See http://wiki.openstreetmap.org/wiki/Tag:man%20made=bridge - defined as
> 
>>    bridge defined by the outline of the bridge

Please, take any further discussion on bridges-tagged-on-ways to the mailing lists, not here.
