### ISSUE TITLE
Render implied oneways (motorway, motorway_link)

### ISSUE THREAD

**Issue by fred702** [gravitystorm/openstreetmap-carto#1820]
There are many exits and on-ramps that are only routable oneway that should be tagged with oneway=no or mapped differently. Changing the rendering to facilitate routing improvements seems like a no-brainer. 

Duplicate of #1363

JOSM does this  
![oneway](https://cloud.githubusercontent.com/assets/12385766/9762206/06813a58-56d0-11e5-94d9-3db49a64de33.png)

The current rendering makes it seem like there is no issue. 
![twoway](https://cloud.githubusercontent.com/assets/12385766/9762342/de6f05a8-56d0-11e5-86c4-b25b08bc22f6.png)

![norouting](https://cloud.githubusercontent.com/assets/12385766/9762403/482b3cf0-56d1-11e5-9d6f-1a0660458378.png)

https://www.openstreetmap.org/way/31769887
https://www.openstreetmap.org/way/31769819

**Comment by jojo4u** [comment]
JOSM and OSRM are now wrong, the definition has changed since the old ticket [1]. Motorway_link has no implied oneway=yes, see Wiki [2].
In your example: Oneway=no should be tagged to make it clear, turn restrictions are missing (already added by me).

[1] https://josm.openstreetmap.de/ticket/8238
[2] http://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_link

**Comment by fred702** [comment]
I see now, thank you for the clarification. Considering their substantial influence on OSM data, I'm very surprised JOSM and OSRM don't reflect a change that has apparently been on the wiki since 2013. I'll see if issues need to be opened for those respective projects. In the future I hope these kinds of changes will be widely publicized to encourage adoption of standards and keep data quality high.

**Comment by aceman444** [comment]
Yes, JOSM does imply/render oneway=yes on motorway_link. But its validator does report about missing oneway, but only at the "info" severity level. I think there were changes to this recently so if something is wrong please open a ticket while the issue is hot ;)

**Comment by jojo4u** [comment]
Yes, the issue is a bit more complex after some more digging. But this is not the place for discussing it.
