### ISSUE TITLE
Forest pattern draws over all other fills

### ISSUE THREAD

**Issue by bongslut420** [gravitystorm/openstreetmap-carto#1821]
![example](https://cloud.githubusercontent.com/assets/14207079/9775651/a96ff40e-5705-11e5-824c-297b6f17d1a3.png)

By convention, heavily wooded national forests (in the U.S., at least) include a 'landuse=forest' tag in the management boundary polygon. It would be unreasonable to remove this tag until the inside of the polygon has been mapped with greater detail. However, where there is locally greater detail, the forest pattern should not be drawing itself on top of everything else. The pattern should be drawn directly after the 'landuse=forest' fill, and then the other areas filled on top.

**Comment by imagico** [comment]
Tagging administrative divisions with landuse=forest is simply wrong, this tag is for areas where actual forestry takes place, i.e. trees are grown.

**Comment by pnorman** [comment]
Similar to #1754

If there aren't trees there, then it shouldn't be in a `natural=forest` area. This is a problem with the data, not the style.

**Comment by matkoniecz** [comment]
Exact copy of #1796 - see explanation on https://github.com/gravitystorm/openstreetmap-carto/issues/1796#issuecomment-136055939

**Comment by polarbearing** [comment]
@bongslut420, to fix you problem in the OSM data, you need to create a multipolygon, move the forest tags to the relation, use the previous forest outline as 'outer', and all the non-forest areas as 'inner'.

**Comment by matkoniecz** [comment]
@polarbearing In the first place two separate entities (protection area called "National forest" and forest) should not be tagged as one object.

**Comment by bongslut420** [comment]
Hi all, thanks for the responses and sorry I didn't look around enough to see that this is a duplicate issue. My confusion came from the fact that the 'landuse=forest' tag is listed as convention for national forest boundary tagging (http://wiki.openstreetmap.org/wiki/US_Forest_Service_Data) and that almost every national forest boundary in the western U.S. is tagged this way (any solid green boundary at zoom 8). I agree it doesn't make much sense but I that seemed to be the convention. 

I found a surface ownership .shp on the forest service GIS clearinghouse that at least shows land that the forest service owns, which should be a better indication of what counts as actual managed forest land under the administrative boundary. It is quite a few hours work merging the data and requires a bit of QGIS work to add it, but I did it for Tahoe National Forest last night what looks successfully. This is similar to what looks like has been done previously with the Shasta National Forest. Hopefully this information will be helpful for anybody else with this same problem.

**Comment by imagico** [comment]
W.r.t. US national forests - there has been a discussion recently on the talk-us mailing list on the matter:

https://lists.openstreetmap.org/pipermail/talk-us/2015-August/015172.html

This discussion makes it quite clear there currently is no consensus on the matter.  But it would have no direct bearing on this style anyway since specific local uses of tags that differ from their use elsewhere are not normally taken into account here.
