### ISSUE TITLE
Pharmacy and doctors office similar icon. Confusing

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1822]
Noticed the same icon is used for both now. This is very confusing. Was this an intended change?

**Comment by HolgerJeromin** [comment]
hu? Are you sure?
http://www.openstreetmap.org/?mlat=50.77019&mlon=6.03995#map=19/50.77019/6.03995
One pharmacy, one doctors icon...

**Comment by Gazer75** [comment]
Oh! Wow, those are to similar. Just noticed the old square one for pharmacy looked like a doctors office icon.

**Comment by nebulon42** [comment]
Both icons have a certain similarity which is intended. So far it did not occur to me that they are too similar. The old pharmacy icon had the problem that it could be easily confused with hospital and the old doctors icon with the rod of asclepius was not really recognisable at small sizes.

I'm always open for concrete suggestions of improvement though.

**Comment by Gazer75** [comment]
Maybe go back to the green square one? I believe the old one had green and red depending on if the pharmacy had dispensing or not. Though I can not remember which one was used for each.
Never really thought about it much as all pharmacies in Norway are dispensing :)
Alternative is to make a mortal and pestle icon for pharmacy. Don't think we have anything similar to that. Ideas are from the two Norwegian pharmacy chains. Search Google images for "vitus apotek logo" and "apotek 1 logo".

**Comment by HolgerJeromin** [comment]
@nebulon42 And we had no old doctors icon :-) #89
@Gazer75 We had not different icon for dispensing in the past, as this is not possible with the current database structure. Pharmacy was always red #1169
The current color code is quite useful. shop, health, leisure, transport have an own color.

**Comment by kocio-pl** [comment]
I have no problem recognizing both shapes.

**Comment by matkoniecz** [comment]
I think that current icon are OK, though pull requests improving situation are welcomed.

> Maybe go back to the green square one?

Green square may be colour symbol that is used locally but I see nor reason to break overall colour scheme to improve readability for a limited public.

I propose to close this issue.

**Comment by kocio-pl** [comment]
+1

**Comment by Gazer75** [comment]
Tested it on a few people and all agreed with me that the icon is to similar. Thats all I can say.

**Comment by kocio-pl** [comment]
I guess colors should be more or less tied to categories. 

And I still don't have a problem recognizing doctor's bag from bottle of pill's even just by proportions alone (the first is wide, the second is tall) and the top is also different enough, so this issue is a surprise for me.

**Comment by Gazer75** [comment]
Heh. I think the pharmacy icon look more like a bag. Didn't realize it was supposed to be a bottle :)
