### ISSUE TITLE
If and how to render landuse=conservation 

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#1826]
landuse=conservation is currently rendered in grass color which is obviously not a good idea since this rendering implies a certain vegetation that tag does not.

In #1655 i originally intended to render it like nature reserves but i came to realize this might not be the best approach.  The tag description on

https://wiki.openstreetmap.org/wiki/Proposed_features/conservation

is very vague, full of words like 'mostly', 'often' and 'typically' - there is hardly any hard criterion listed there to identify what constitutes landuse=conservation.  I know this tag is used in the UK for a specific purpose but elsewhere its use is fairly arbitrarily.  What characterizes landuse=conservation in the UK seems to be that it is land protected from development.  But this is a restriction that is mostly relevant to the land owner and of little importance to the visitor - in contrast to nature reserves which usually come with restrictions like not to leave paths, no camping, no picking of plants etc.

Overall i think landuse=conservation should probably not be rendered at all.  If there are legal constraints beyond protection from development it should be tagged leisure=nature_reserve or boundary=protected_area.  If anyone can show me an area of landuse=conservation where these tags would be wrong and that should be rendered on the map none the less that would be an argument of course.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/w/index.php?title=Tag:landuse%3Dconservation&redirect=no redirecting to inactive draft from 2009 is an additional reason to reconsider rendering this tag

**Comment by dieterdreist** [comment]
sent from a phone

> Am 11.09.2015 um 16:34 schrieb Christoph Hormann <notifications@github.com>:
> 
> Overall i think landuse=conservation should probably not be rendered at all.


I agree, it likely shouldn't be tagged either ;-)
"conservation" doesn't seem to be a good landuse value but rather a protection property that could be added in addition to a landuse


> If there are legal constraints beyond protection from development it should be tagged leisure=nature_reserve or boundary=protected_area.


yes, with boundary =protected area and subtags it should be possible to map the kind of protection and everything else "conservation" stands for

**Comment by matkoniecz** [comment]
Note that dropping rendering of landuse=conservation would also fix #453

**Comment by pnorman** [comment]
I had a look locally, most `landuse=conservation` are mistagged and should be something else.

There is no consistent use to the tag here. Given this, I don't think we should be rendering it.

**Comment by jojo4u** [comment]
I marked the proposal as abandoned with the following reasoning:
Status abondoned since boundary=protected_area is better way, and it's getting dropped from osm-carto https://github.com/gravitystorm/openstreetmap-carto/pull/1830, Current usage 25000

**Comment by matkoniecz** [comment]
> it's getting dropped from osm-carto #1830

Is not a valid reason (problems mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/1826#issue-106022686 may be valid reasons, lack of rendering by itself is not a good reason to consider tag as abandoned).
