### ISSUE TITLE
Scale marina label according to size of object

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1827]
http://www.openstreetmap.org/way/149850735#map=16/41.7382/12.2467
![selection_001](https://cloud.githubusercontent.com/assets/899988/9831114/2ab69752-594a-11e5-8ddf-d1d49f626abe.png)

**Comment by dieterdreist** [comment]
sent from a phone

**Comment by jojo4u** [comment]
@dieterdreist your comment is empty :)
