### ISSUE TITLE
render railway=light_rail like railway=tram

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1829]
It is rather tradition/cultural difference. See https://en.wikipedia.org/wiki/Light_rail "There is no standard definition". It seems mostly question how given system is named. Metrolink mentioned as example of light rail is tagged in OSM as railway=tram - http://www.openstreetmap.org/way/10521436#map=19/53.46571/-2.27010

Overall there is a little difference between light rail and tram if any - certainly not big enough to justify noticeably different rendering.

extracted from #1828

**Comment by BalooUriza** [comment]
On Sat, Sep 12, 2015 at 2:57 PM, Mateusz Konieczny <notifications@github.com
> wrote:

> It is rather tradition/cultural difference. See
> https://en.wikipedia.org/wiki/Light_rail "There is no standard
> definition". It seems mostly question how given system is named. Metrolink
> mentioned as example of light rail is tagged in OSM as railway=tram -
> http://www.openstreetmap.org/way/10521436#map=19/53.46571/-2.27010
>
> Overall there is a little difference between light rail and tram if any -
> certainly not big enough to justify noticeably different rendering.
>
 Well, North American usage might be worth offsetting this.  Compare the
primarily-on-street Portland Streetcar to the primary dedicated-route (but
still lightweight) Metropolitan Area Express in Portland.  Or the SEPTA PCC
streetcars to SEPTA's still lightweight, but heavier and surface-running,
high speed lines.  Or the HSR lines from more traditional light rail or
streetcars.

Probably worth developing different tags and rendering for streetcars
(which, are typically rail based vehicles with exactly one car) versus
light rail (which is typically a minimum of one car, such as Portland MAX;
or up to 12 cars, as in the New York MTA subway (IRT or BRT)).  That said,
I think we can both agree that the route numbers/letters serving a station
are *not* part of the name=* tag...

**Comment by jojo4u** [comment]
There are quite a lot of differences, if you speak german have a look at the german rail=light_rail page (http://wiki.openstreetmap.org/wiki/DE:Tag:railway%3Dlight_rail#Abrenzung). Perhaps a good time to translate the content over to english...

I miss looking at the data in this issue. The following systems are tagged as rail=light_rail
https://en.wikipedia.org/wiki/Kanazawa_Seaside_Line
https://en.wikipedia.org/wiki/Addis_Ababa_Light_Rail
https://de.wikipedia.org/wiki/S-Bahn_Hamburg
https://en.wikipedia.org/wiki/Berlin_S-Bahn
https://pt.wikipedia.org/wiki/Sistema_de_Trens_Urbanos_de_Jo%C3%A3o_Pessoa
https://en.wikipedia.org/wiki/Blue_and_Green_Lines_%28Cleveland%29
https://en.wikipedia.org/wiki/Lynx_Blue_Line
https://en.wikipedia.org/wiki/Baltimore_Light_Rail
https://en.wikipedia.org/wiki/River_Line_%28New_Jersey_Transit%29
https://en.wikipedia.org/wiki/Hudson%E2%80%93Bergen_Light_Rail

**Comment by matkoniecz** [comment]
> if you speak german

Unfortunately no.

**Comment by jojo4u** [comment]
I translated the page :) http://wiki.openstreetmap.org/wiki/Tag:railway%3Dlight_rail

**Comment by matkoniecz** [comment]
@BalooUriza @jojo4u I admit that I am unsure what is your opinion about this proposed change.

Note that developing different tags should not happen here (tagging mailing list or OSM wiki is preferable).

**Comment by jojo4u** [comment]
Yes, was still drafting it up. I'm not developing different tags, light_rail is established with 20.000 use (vs. 70.000 tram).
It's implementations of light rail are everywhere in between tram and conventional rail. Technological differences are often very high (signaling, speed, own right of way). I'm not against rendering it like tram. But there should be a better reason than "little difference between light rail and tram". One reason might be that 3 styles (rail, light_rail/funicular/narrow_gauge, tram) are too many. Since light_rail and tram (funicular also?) are mostly found in urban environment it might be better to focus on one style here.

**Comment by jojo4u** [comment]
One more thing: I'm not sure where to bring it up (so many tickets now ;): service=* is not considered for light_rail.
Compare
light_rail "SSB-Zentrum" (http://overpass-turbo.eu/s/bqh) with
tram "Straßenbahnwelt" (http://overpass-turbo.eu/s/bqi) with
rail "Hauptbahnhof" (http://overpass-turbo.eu/s/bqj)

on the "new" style: https://osm.rrze.fau.de/map-ll-osm?zoom=13&layer=RRZE%20tileserver%20osm.org%20style%20tiles&lat=48.728&lon=9.1413

**Comment by matkoniecz** [comment]
> One reason might be that 3 styles (rail, light_rail/funicular/narrow_gauge, tram) are too many. 

There are 3 styles now for these rail types (and more for other rail types), adding more is not really feasible. Given that light_rail and tram are quite similar I think that rendering these in the same style would be viable.

Maybe even light_rail and funicular and narrow_gauge and tram may be all displayed in the same style?

**Comment by jojo4u** [comment]
One problem will be when to stop rendering. Tram should be dropped fast, light_rail and narrow_gauge should be displayed longer. One good spot to test can be Philadelphia with both extensive tram and light rail:
light rail http://overpass-turbo.eu/s/bqr
tram http://overpass-turbo.eu/s/bqv

**Comment by matkoniecz** [comment]
I was not 100% sure is it going so solve more problems than create and there are comments opposing this so I am closing.
