### ISSUE TITLE
Recognize and render power=plant

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#1835]
osm-carto currently recognizes and draws power=station, but this seems deprecated and is not listed in the OSM wiki (if it ever was). Instead, the wiki states to use power=plant. Please consider making osm-carto draw it.

Example objects: http://osm.org/way/237100663

**Comment by pnorman** [comment]
see also #1771 (abandoned PR)

**Comment by matkoniecz** [comment]
especially https://github.com/gravitystorm/openstreetmap-carto/pull/1771#issuecomment-133796106 by @kreed 

> It might make sense to render plants the same as landuse=industrial (on all zoom levels). It would make the generators and substations inside the plant easier to spot.

> Here is a comparison:
![download](https://cloud.githubusercontent.com/assets/65656/9427311/2aaad764-493c-11e5-8d09-30bf0179574f.png)
![download 1](https://cloud.githubusercontent.com/assets/65656/9427312/2cee66ee-493c-11e5-8088-e597590a97b9.png)

**Comment by kreed** [comment]
I'll write a new PR for this with the change I suggested.
