### ISSUE TITLE
render compacted footways the same as paved?

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1842]
In most parks and forests are some [constructed footways](http://www.mapillary.com/map/im/3Y5jPxGn1HOx9duNnBiXKg/photo). Most are `surface=compacted` at least in germany. 
They are very nice for hiking, bicycle, even wheelchairs and strollers have no problems with it. 

All other `surface=unpaved` footways are much harder to use. We have problems with wheelchairs and walking needs more concentration.

So it would be useful to be able to differentiate for example [unmaintained](http://www.openstreetmap.org/way/211550997) or [desire path](http://www.openstreetmap.org/way/211550995) in a park and forest.

For walking the difference of asphalt and compacted is not really important. It is (a little bit) for cycling, but such ways are often correctly tagged as cycleway.

**Comment by imagico** [comment]
What you actually want to do here is render `smoothness` - i suggested this in https://github.com/gravitystorm/openstreetmap-carto/issues/1766#issuecomment-132498373 - right now smoothness is not available though.

Although you could say surface=compacted might imply a certain smoothness it does not, compacted only means a certain level of sturdiness and carrying capability, it is not about the surface finish.

**Comment by matkoniecz** [comment]
At this moment surface distinguish between paved and unpaved surface, with interpretation following documentation - http://wiki.openstreetmap.org/wiki/Key:surface

**Comment by matkoniecz** [comment]
IMHO distinction between paved and unpaved is better than distinction between "paved and not so bad unpaved" and "unpaved, except more usable types".

**Comment by imagico** [comment]
The idea behind rendering unpaved with smoothness better or equal intermediate like paved would be that for most users, especially disabled people and users of walking aids of various sorts, this is the more relevant distinction.  Of course some types of paved (like cobblestone) would in turn make sense to be taken out of the 'high comfort' category.

**Comment by SomeoneElseOSM** [comment]
Also "compacted" paths have a tendency to degrade into something "less than compacted" if not maintained (like all the ones near me have) so even something that was mapped correctly a year ago as "surface=compacted" might not be best mapped as such now.   You have to draw the line somewhere, and "paved vs non-paved" is probably as good as any.

**Comment by HolgerJeromin** [comment]
My linked "unmaintained" example was compacted a while ago and is now covered with grass. So the argument "have a tendency to degrade" this is a normal maintenance issue for osm.

**Comment by HolgerJeromin** [comment]
I don't think we should "require" to tag another key (`smoothness`) for a nice rendering. The protest about the "need" of surface tagging was enough :-)

The surface wiki page is a general page, not a "footway surface" page.
While i think paved/unpaved is in general (motorway to path) or for `track` a good distinction, it is not for footways and path. 

And yes, taking `cobblestone` and perhaps even [`wood`](http://wiki.openstreetmap.org/wiki/File:Wooden-bridge.jpg) could be taken into the unpaved render category (which should be renamed in this case).

**Comment by kocio-pl** [comment]
I sometimes think we should have some more specific (foot)way types, like:
- park/cemetery/allotment alley (they should be rendered later, as they tend to be local and rather dense); so maybe **highway=alley + alley=*** then.
- outdoor/touristic/mountain path (those should be rendered earlier and probably more intense, because they are for longer distances and rather the most important thing in such places; highway=pedestrian is advised, but this is different enough IMO than [this](http://wiki.openstreetmap.org/wiki/File:Calle_arenal.jpg)); so maybe **highway=outdoor + outdoor=*** then.
- sidewalk (probably more important than alleys, but less than outdoor path); **highway=footway + footway=sidewalk** is already meant for this.

I guess general type of such ways are easier to use than demanding people adding multiple other options (which is always welcome, of course), because their intended use gives us good enough hints to know how to treat them. We have much more general types for cars, so I think this is the time to take care also for pedestrians.

**Comment by pnorman** [comment]
There is a continuum of surface quality, which differs for each transportation mode.

* We need easily understood logic, so involving surface, smoothness, and potentially other tags isn't a good option as it makes it hard to easily explain
* The quality of two paths with the same surface can be vastly different. See [the earlier wood example](http://wiki.openstreetmap.org/wiki/File:Wooden-bridge.jpg) vs [a well maintained boardwalk](http://www.mapillary.com/map/im/KcQuoUYtxtSflFMV7e5zjw/photo). Asphalt can deteriorate to be worse than solid bare ground

Given the constraints, simply classifying by paved/unpaved is probably the best we can do.

**Comment by HolgerJeromin** [comment]
Wood could be anything and we should leave it, especially on bridges. Cobblestone degrading could be a problem to explain the logic. 
Wiki page states that compacted is near to paved. 

But pavement gives also a hint about guidance where to go best. 

I still believe this would be a better result in the most forests, where we have a uniform unpaved style now. It gives a structure of a hiking network. 

Does someone has an example where the distinction between compacted and asphalt on footways are more interesting?

**Comment by dieterdreist** [comment]
sent from a phone

> Am 18.09.2015 um 21:30 schrieb Paul Norman <notifications@github.com>:
> 
> Given the constraints, simply classifying by paved/unpaved is probably the best we can do.


+1
compacted surfaces also tend to become bad after rain.

**Comment by pos-ei-don** [comment]
+1, but especially on mountain-paths we need to distinguish if it is a path you can hike or if it is a path where you need a certain gear, like crampons or  a "via ferrata set". Living in de Alps we often find people following a path without goog gear who needs to be rescued. 
If you see a path on a map without any notes, one can certainly plan wis hike using this... and some of them don't stop and look for the detour when they notice that they need climbing-shoes.

**Comment by SomeoneElseOSM** [comment]
@pos-ei-don To be fair, of all the possible design goals of a general purpose map style, "whether I need climbing gear to get from A to B" is probably some way down the list.
