### ISSUE TITLE
move bridge casing colour from black to hue of road colour

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1852]
The approach for oneway arrow colouring (#1840) would also work for bridge casings. I think they would look better if their hue would match the road casing colour, of course they would have to be a bit lighter, but not much.

It would look something like that (lightness not necessarily that light):
![bridge_after](https://cloud.githubusercontent.com/assets/3531092/9977656/c644e686-5f0f-11e5-8f4d-23c2e53b4590.png)

instead of
![bridge_before](https://cloud.githubusercontent.com/assets/3531092/9977657/cb87e7b0-5f0f-11e5-89f4-6c18b0d90a38.png)

Before I try it out I'd like to have your feedback.

**Comment by matkoniecz** [comment]
Bridges are less visible and even now bridge/nonbridge casing difference is quite low. Maybe combined with increased casing on bridges it would work (IIRC there are already available variables it set it separately).

**Comment by mboeringa** [comment]
One thing that is working firmly against this is that the bridge casing color starts to suggest another road type, instead of a bridge feature, at least with current casing width nearly similar to normal casing... I think the matching of colors is only really possible for the oneway arrows.

**Comment by nebulon42** [comment]
I don't see why a sufficiently darker (i.e. visually stronger) casing that is not necessarily black could suggest a different road type, even with the same width. Which type should it suggest? Tunnels also don't have similar casing colour (yes, there are other changes in the tunnel style too that help recognizing it as a tunnel).

Regarding the concept of bridges I think what is important here is the visually stronger casing, the colour is (at least for me) only of secondary importance. And tuning the colour to the casing colour looks better for me. I have to admit though that my example could be a bit darker. That's why I wrote: lightness not necessarily that light.

**Comment by jojo4u** [comment]
This makes the bridges less readable in my eyes.

**Comment by nebulon42** [comment]
Currently there seems to be no support for this idea, so I'm not taking this further.
