### ISSUE TITLE
Footway and path, no difference anymore? Cycleway.

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#1858]
Looking now at the Openstreetmap.org site, so I searched where to comment,  problems which we noticed.

Both are rendered in red dotted small lines. I do not see any difference.
These highway=footway highway=path are major basic tags.
And must  be rendered differently, because also the use of path is much wider than only by foot.
These are path’s.
http://www.openstreetmap.org/#map=18/52.14145/5.36803

It looks like the map is more going to be map for more a car view, instead of a overall map for all kinds,  included other vehicle use.

See the blue dotted line for cycleway, look in the Netherlands, this does not look good.
http://www.openstreetmap.org/#map=17/52.14170/5.35811
It also look like the dots are not all the same, because there so small.
Also the are rendered so width that it overlaps the cycleway.

Example:  zoom 17, cycleway and red dotted lines are path and not footway with a footsign.
![osm path cycleway](https://cloud.githubusercontent.com/assets/8817345/9980910/8b560860-5fab-11e5-8341-94279c15fb9a.PNG)

cycleway, path, footway are roads to, should be seen as basic roads.

Hope these lines will be rendered differently and become more/better noticeable.

**Comment by rrzefox** [comment]
The unification of path and footway rendering was a deliberate decision.
See among others the discussion in #1698 #1713 and a search in this issue-tracker will turn up more duplicates.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 21.09.2015 um 11:35 schrieb rrzefox <notifications@github.com>:
> 
> The unification of path and footway rendering was a deliberate decision.


yes, and it was disputed like few other topics (maybe abandoned railways can compete)

**Comment by AllroadsNL** [comment]
For me and others it is a "big" issue, that on a "default" map you can not see a "basic" tag like highway=path.

paved and unpaved are second in line tags.

We use this map also as a background in JOSM!!!
Control, to see where things changed, where we must look in to detail, why.

"deliberate decision" are there to be reconsidered, if it is not understood and what is expected by the community after importation, it must be turned back.

Will you be so kind to reopen this issue!

Yes, I read many pages, I do not agree with that a "basic" tag is unificated.


And in this issue, there where more problems like rendering, cycleway.
Not a word about that. dots and line

**Comment by moliha** [comment]
The 'deliberate decision' to make paths and footways look the same is in my opinion a bad decision. These two ways are clearly different:

Footways are made for pedestrians - like cycleways are made for cyclists. Additional tags may allow additional use.

Paths are unspecified - not 'made' for any specific use - often trampled paths in forests, meadows etc. - used by anybody.

Making these two types of ways look the same is in my opinion a serious mistake. 
The result of 'the decision' is a waste of many mappers time and careful considerations - and a map that is less useful.

This thread should be reopened - and the decision to merge the rendering of these ways should be reconsidered.
In the interest of both mappers and users, the rendering of footways and paths should return to the previous state. Rendering may of course be refined - but the rendering of clearly different ways should never be merged.

**Comment by math1985** [comment]
@moliha @AllroadsNL Welcome to the repository!

Unfortunately, the definition given by @moliha is far from universal. We have seen about as many different definitions of path/footway here as there are contributors. Because there is no agreed definition of the definition of path and footway, we have chosen to instead differ rendering based on better defined tags (for example the surface tag).

See also https://gist.github.com/gravitystorm/ff5a6fdc695f08de1751.

I hope that clarifies the decision!

**Comment by AllroadsNL** [comment]
See also.... I read it:
"What we have is a mess." 

How does we set it right.

Who makes the mess, the ones, who walks, reflects by their POV and say a single tracked is a footway.( I walk to, but learned to watch other category and respect them) 
Even when 100 walks over it and 3 bicycle, 1 mofa, 1 horse and sometimes a motorcycle, etc., it is still a path, used by everyone, that's the difference, let's keep this difference. When a path is designated only to foot then you can make it a footway, just like a path only designated to horse, it is a bridleway. In urban and rural.

So it is written in the wiki, a OSM standard, it clears up, like that, it gives a handhold, and so most of us tagged in this way. And we want that to see it on the default standard map. So we can control it, as we see it in the background of JOSM. 

The explanation:
Walking people who are claiming a road by naming a road, footway, maybe even more take the word "foodpath" in there mouth. And so in all languages,
Because there more walkers, because they say  "General to speak" footpath. This behavior gives a confusion of tongues. 

"General to speak", it is the OSM line we have stick with.

So, do not let you confuse by the "General to speak", do not make it more of a mess by rendering footway and path equal. Stick to the way, we choose in OSM. Give path, it's own color as a basic tag.

Now i must think rural red is different than urban red, confusing!!!

Hope you all understand my point, my native is not english, hope you understand that as well.

Hope the decision is turned back.
I would be very disappointed if this would not happen.

**Comment by xiexed** [comment]
Very sad decision. At least for me in Moscow area it is a reliable difference in `footway`s as artificially served track and `path` as just trampled path, and now to see the difference I need to use another renderers like [OsmAnd](http://osmand.net/) or [MapSurfer.NET](http://korona.geog.uni-heidelberg.de/) hoping that they will not follow this decision.

**Comment by HolgerJeromin** [comment]
@ xiexed
Why not adding additional value to the data and add the surface tag? 
It it is path/footway tag is reliable adding surface is very fast done in a well known place. At least with josm. 
I did in Aachen and it is nice to have something useful to add in my hometown again :-)

**Comment by xiexed** [comment]
@HolgerJeromin , As I understand at this moment difference is shown only between `paved` and `unpaved` surfaces, but very often real surface of some equipped tracks is `compacted` which is classified as `unpaved` so they look the same as trampled paths, so there is no way at this moment for me to make them look different without adding purposely wrong tag information.

If someone thinks that something is wrong with `path` value and its meaning is ambiguous than it is better to deprecate this tag in favor of a more self-determinating like `trampled` or something like this, but not the way it is done at this moment.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 04.10.2015 um 15:29 schrieb xiexed <notifications@github.com>:
> 
> tag in favor of a more self-determinating like trampled or something like this


you can use informal=yes on these

**Comment by xiexed** [comment]
@dieterdreist, [905](http://taginfo.openstreetmap.org/keys/informal#overview) usages overall, are you kidding? There is a different rendering for `highway`s with this tag, really?

**Comment by HolgerJeromin** [comment]
@xiexed the compacted same as paved was sadly rejected ( #1842). I had the same problem.

**Comment by pnorman** [comment]
We're just covering the same ground as before and https://github.com/gravitystorm/openstreetmap-carto/issues/1698#issuecomment-134957452 is as applicable here.
