### ISSUE TITLE
Different icons for shelter_type

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#1860]
Could we have different icons/representations for [shelter_type](http://wiki.openstreetmap.org/wiki/Key:shelter_type)?

For example, right now a `shelter_type=public_transport` http://www.openstreetmap.org/way/314431304 is exactly the same as `shelter_type=picnic_shelter` http://www.openstreetmap.org/node/3248623228

**Comment by kocio-pl** [comment]
How should we render them in your opinion? I guess transport shelter would be good without the icon, with just a building, while other types of shelter (I guess `shelter_type=outdoor` in general) are more important and should look like they do now.

**Comment by Circeus** [comment]
Shelter=public_transport is rarely ever an actual building anyway. 99% of the time it should just be tagged as building=roof with the bus stop under it. In fact [the wiki](http://wiki.openstreetmap.org/wiki/Key:shelter) seems to imply that amenity=shelter is not to be used in such a situation in the first place. People tagging shelters and people tagging public transportation might want to have a chat how to tag that use case.

**Comment by kocio-pl** [comment]
Nobody's talking about `shelter=*` namespace you are in fact referring to, so I guess you've just mixed two similar tag schemes. Real [`amenity=shelter` page](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshelter) explicitly gives an example of it (_In order to more precise the shelter type (picnic_shelter, public_transport, basic_hut ...) just add the shelter_type=* tag._) and [`key:shelter_type` page](http://wiki.openstreetmap.org/wiki/Key:shelter_type#Values) even shows this example.

While building=roof is probably proper tagging scheme for most of the public transport shelters, adding `amenity=shelter + shelter_type=public_transport` makes it complete.

**Comment by naoliv** [comment]
I really wish I had some drawing skills, but what I imagine is something like this:

![shelter example](http://i.imgur.com/ZpxoUNe.png)

_default_ is when there isn't a `shelter_type` defined.
(and I don't know how to draw a public_transport shelter, but you should have an idea)

**Comment by matkoniecz** [comment]
The main problem is fitting this into much smaller icon (16x16 pixels).

**Comment by naoliv** [comment]
Maybe remove the rain from the current icon when we have, at least, `picnic_shelter` and `public_transport`?
Could different colors be used?

**Comment by kocio-pl** [comment]
I could try to make them, but I think we should start with really used ones:

public_transport - 36 665
picnic_shelter - 9 358
weather_shelter - 6 506
lean_to - 2 295
basic_hut - 2 258

Porting the current one to SVG would give us proper weather_shelter and default one. Picnic might be achievable, but I have no ideas for the rest.

**Comment by naoliv** [comment]
Sketched something and indeed the icons are too small... :-/
![Sketch](http://i.imgur.com/mYASSXw.png)

**Comment by kocio-pl** [comment]
Do we still want to have different shelter icons instead of one, despite their small size (as shown above)? If not, we could safely close this issue.

**Comment by matkoniecz** [comment]
Rather not - it is really unlikely that it is doable with such limitations.
