### ISSUE TITLE
simplify yaml2mml.py execution

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#1866]
Currently yaml2mml.py needs the correct files provided to stdin and stdout. But given it's the same files every time, and the directing files to stdin/stdout isn't the worlds most common thing, we can simplify how it works.

* Currently: `python scripts/yaml2mml.py < project.yaml > project.mml`
* Target: `python scripts/yaml2mml.py` or even just `scripts/yaml2mml.py`

The files should be found relative to the script, not the current directory, so that `python scripts/yaml2mml.py` and `cd scripts; python yaml2mml.py` both work.

**Comment by kocio-pl** [comment]
Nice idea.
