### ISSUE TITLE
Render leisure=fitness_station

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#1870]
Could we have [leisure=fitness_station](http://wiki.openstreetmap.org/wiki/Tag:leisure=fitness_station) rendered too?

There is a CC-0 licensed icon here http://osm-icons.org/wiki/File:21009.svg

**Comment by kocio-pl** [comment]
Might work after some tweaking - let's star with just resizing to 14px:
1) ![fitness_station-14-0](https://cloud.githubusercontent.com/assets/5439713/10081584/e2ca6b2a-62f5-11e5-8b92-12791e7efe43.png)

**Comment by HolgerJeromin** [comment]
IMO the treadmill does indicate a indoor gym ([which tagging is not clear](http://wiki.openstreetmap.org/wiki/Gym_/_Fitness_centre)).

You wont find a treadmill at an "outdoor facility" fitness_station

**Comment by naoliv** [comment]
Maybe http://osm-icons.org/wiki/File:21157.svg ?
But it isn't good at 14x14: ![](http://i.imgur.com/ey8SC8M.png)

**Comment by kocio-pl** [comment]
I guess a stepper would be good to depict, because it can be found both indoors and outdoors, so we could have just one icon for both leisure=fitness_station (3 573) and leisure=fitness_centre (2 611):

https://commons.wikimedia.org/wiki/File:Gym_Cardio_Area_Overlooking_Greenery.JPG
https://commons.wikimedia.org/wiki/File:Ansan_034.JPG

**Comment by boothym** [comment]
Both fitness_centre and fitness_station should be rendered, perhaps with some sort of weightlifting or treadmill icon. 

With the gym tagging situation "sorted", I've updated the presets in the iD editor: https://github.com/openstreetmap/iD/issues/3352 - would be nice to get a icon on the map as well.

**Comment by kocio-pl** [comment]
Ideas are welcome, of course, but at this moment we need rather implementations to test them.

**Comment by boothym** [comment]
Well the first one suggested doesn't look too bad at 14px - any chance you could show us what it looks like on the map?

**Comment by kocio-pl** [comment]
I guess if I make it look more like a stepper (change the silhouette) it could actually work for everybody. I will try to do it and show the rendering.

**Comment by boothym** [comment]
Even without the icon can we at least render the name for leisure=fitness_centre on a node, just like sports_centre? At the moment any properly tagged gym is invisible which doesn't help encourage people to tag it correctly.

**Comment by pnorman** [comment]
> can we at least render the name for leisure=fitness_centre on a node, just like sports_centre?

This issue is about fitness stations, not fitness centres.

**Comment by boothym** [comment]
Ok, I'll open a new issue for that.

**Comment by Tomasz-W** [comment]
It's almost 7k of fitenss stations now.
https://taginfo.openstreetmap.org/tags/leisure=fitness_station

I think that fitness stations should be rendered not only as nodes, but as areas also. It's kind of landcover facility, so it should't make a blank hole in map, if it's mapped as area. Maybe playground colour with https://github.com/gravitystorm/openstreetmap-carto/issues/1870#issuecomment-143003811 icon would look good. Playgrounds and fitness stations are similar objects, often standing side by side.

**Comment by kocio-pl** [comment]
I would also do it like this, but first we need icon like stepper (https://github.com/gravitystorm/openstreetmap-carto/issues/1870#issuecomment-226222108). It could be used also for fitness centre. Is there anybody who would like to draw such icon?

**Comment by Tomasz-W** [comment]
@kocio-pl I can try. What are the requirements for icon project file?

**Comment by kocio-pl** [comment]
Look here:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines

You can take existing icon file and start with that (I was trying with [this one](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/sports.svg)). Inkscape is free tool I'm using. If you have more questions, just ask here or on the forum.

**Comment by Tomasz-W** [comment]
What do you think about this icon?
![fitness-station-bow](https://user-images.githubusercontent.com/25656654/28664022-51afee36-72bf-11e7-8acf-c45af7a1b122.png)

**Comment by kocio-pl** [comment]
On a small scale:
- head is too small
- hands could be wider (especially lower hand)
- rear leg should be probably also bent a bit
- maybe handles should be more "X"-crossed to be better visible

Have you made an SVG version of it? Fixing it with PNG makes no sense, since optimal SVG lines should be pixel-aligned.

**Comment by Tomasz-W** [comment]
Yes, I've made a svg version, so don't worry. I'll make changes due to your points and upload new version later.

**Comment by Tomasz-W** [comment]
2nd version
full-scale:
![fitness station bow2](https://user-images.githubusercontent.com/25656654/28670352-8dd787b6-72d8-11e7-8f33-8e66ccef1b9e.png)
14x14: ![fitness-station-bow 14x142](https://user-images.githubusercontent.com/25656654/28670362-96d767dc-72d8-11e7-9ad2-6e5a62306ed7.png)

**Comment by kocio-pl** [comment]
Thanks, that's much better! More leg bending would be nice, I would also try make both hands bolder (just as legs probably, because at 14px we need strong generalization) and move elbow half way between body and the handle, to be more visible. But overall view is now clear enough to me.

**Comment by Tomasz-W** [comment]
3rd & 4th version, hands after workout ;)

I think this bolder hands made it's less visible on 14x14:
![fitness station bow2](https://user-images.githubusercontent.com/25656654/28677133-e6bb9c00-72ec-11e7-9abf-377ff4120cd6.png)
14x14: ![fitness station bow2 14x14](https://user-images.githubusercontent.com/25656654/28677140-eaa580d8-72ec-11e7-862b-79b315a8c0d2.png)

placing elbow half way between body and the handle made it also less visible, so here's version with bold hand near body:
![fitness station bow3](https://user-images.githubusercontent.com/25656654/28677144-eef11f1c-72ec-11e7-9dfb-45ab758ca9ca.png)
14x14: ![fitness station bow3 14x14](https://user-images.githubusercontent.com/25656654/28677153-f3efa86c-72ec-11e7-90f9-f126b35c09cc.png)

I think that in 2nd version the "X" shape is the best visible, but you are more experienced, so you will know, which version is the best.

**Comment by naoliv** [comment]
Version 2 seems better

**Comment by kocio-pl** [comment]
Could you share SVG image with version 2? Or maybe you'd like to make PR with leisure=fitness_station rendering?

**Comment by pnorman** [comment]
Could you render it with a pixel grid behind it to review the scale and alignment?

**Comment by meased** [comment]
All I see are cross country skis.

What about a single dumbell?
![dumbell](https://user-images.githubusercontent.com/14190496/28838861-88c7eb04-76a6-11e7-89bd-2551ffa20f91.png)

Or some kind of a "human-in-action"?
![squat](https://user-images.githubusercontent.com/14190496/28838868-8e6cadd8-76a6-11e7-8e2f-50c4805f854f.jpg)

Or a power lifter?
![people](https://user-images.githubusercontent.com/14190496/28838872-92e0f478-76a6-11e7-979d-83e9c2e470f7.png)

**Comment by kocio-pl** [comment]
We don't look for nice free vector images, there's a lot of them around. We need them to look good enough as a 14 px icon, so try to scale them down first.

**Comment by Tomasz-W** [comment]
I'm new to Inkscape (and making icons), so I'm not sure is it this what you mean, but here's screenshot of project with a grid:
![bez tytulu](https://user-images.githubusercontent.com/25656654/28859908-7d8d09cc-775a-11e7-9788-ed8f36b7fdc5.png)

and exported to 14x14 png:  ![eisure fitness_station](https://user-images.githubusercontent.com/25656654/28859936-9a72453e-775a-11e7-9953-81244af85bee.png)

**Comment by pnorman** [comment]
I'm still not sure about the basic concept of the icon, but the bottom line should be horizontal and pixel aligned, and in general there are way too many sloped lines.

**Comment by kocio-pl** [comment]
I still haven't tried to make some tuning of this icon, but at least I think the color for all physical activity related icons and labels should be leisure-green (#2827).

**Comment by Tomasz-W** [comment]
@kocio-pl https://gist.github.com/Tomasz-W/37318c37debf16e8b7cdc759b9b7eea4
Here you are.

**Comment by kocio-pl** [comment]
Unfortunately this icon don't work for me, even after tuning.

**Comment by kocio-pl** [comment]
After long time trying with different ideas I think the easiest would be to reuse sports icon - this should be pretty clear what it is because of using leisure green instead of shop violet and mirroring the symbol to make it more distinct. For me it works as unified icon for both fitness tags:

fitness station
![2j2si2aq](https://user-images.githubusercontent.com/5439713/31325020-cf2403a6-acb8-11e7-9791-f802902fd647.png)

fitness centre
![t_mkmr65](https://user-images.githubusercontent.com/5439713/31325021-d1eb904a-acb8-11e7-9a85-b4b5bbc8a35d.png)

**Comment by Tomasz-W** [comment]
IMO playground area colour would be better

**Comment by HolgerJeromin** [comment]
You dont use a leisure=fitness_station with a kid. So please no playground colour

**Comment by kocio-pl** [comment]
We have too many colors for very specific features and we're out of colors for at least 2 years, so it's good to make their meaning more general. I would say it should be called a "leisure background", so it fits both playground, fitness station and we use it for dog park too. Having different icons is enough to recognize them.

**Comment by dieterdreist** [comment]
2017-10-09 10:06 GMT+02:00 kocio-pl <notifications@github.com>:

> We have too many colors for very specific features and we're out of colors
> for at least 2 years, so it's good to make their meaning more general. I
> would say it should be called a "leisure background", so it fits both
> playground, fitness station and we use it for dog park too.
>


please, do not use the same color for playgrounds and dog parks. You can
use the toilet color for dog parks...

**Comment by kocio-pl** [comment]
The toilet icon is brown, so is the cinema icon - let's give them different colors! ...said nobody. Seriously - what color then and why?

Leisure is about different physical activity, it seems, so it all fits for me. That's why we have icons and patterns to differentiate things. Color is not the only thing that matters.

**Comment by Tomasz-W** [comment]
> You dont use a leisure=fitness_station with a kid. So please no playground colour

Why not? I've seen a lot of kids working out on outdoor gyms. Second thing - playgrounds and outdoor gyms are very similar objects, often placed side by side, so I don't see any problem with the same area colour for them both. With different icons and current dark-green outline (example here: http://www.openstreetmap.org/#map=19/52.39993/16.97736), I don't think it will be confusing, even if it's side by side.

**Comment by andrewharvey** [comment]
Glad to see this rendered on the map. I'm not sure about the icon though, to me the icon looks like a running track and when next to the path makes it look like the icon is showing that the path is a running track. fitness stations are typically about doing strength training, so some kind of weights icon like a dumbell might be better....

**Comment by kocio-pl** [comment]
It has been proposed, but doesn't look good enough:

https://github.com/gravitystorm/openstreetmap-carto/issues/1870#issuecomment-143010494

However if you think you can make a better one, feel free to do it:
- it has to be CC0/PD licensed
- it has to be SVG
- it has to look good as a 14px PNG
- it would be good if it's unified for both types (fitness station and fitness center)
