### ISSUE TITLE
alley that is smaller than <2.00>

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#1879]
There is highway service,

but there is also service=alley
some of these ways lay behind the sheds of houses, mostly used as residential back entrance or fire escape route. But there are also used as a walk/bike through to a shopping center.
these are 1.20- 1.80 width
example:
http://www.openstreetmap.org/way/256645886#map=18/51.35343/5.42627
should all <2.00> rendered smaller?
It does not look good these alley behind these sheds.
is white a good color? it is the same as residential.should it be gray?
mostly mofa moped is allowed. in this case example.

now rendered the same as highway service?

**Comment by AllroadsNL** [comment]
These are rendered bigger then parking_aisle.

**Comment by math1985** [comment]
This is a tagging mistake - the highway=service tag should not be used for paths too narrow for cars. Better use highway=footway (or highway=path).

For those unfamiliar with Dutch architecture, paths like that are quite common in the Netherlands and look like [this](https://s1.whbo.nl/uploads/order/532/e6f30744fd3aa012bf6a71af109046724e686167.jpg).

**Comment by dieterdreist** [comment]
sent from a phone

> Am 28.09.2015 um 00:39 schrieb AllroadsNL <notifications@github.com>:
> 
> but there is also service=alley
> some of these ways lay behind the sheds of houses, mostly used as residential back entrance or fire escape route. But there are also used as a walk/bike through to a shopping center.
> these are 1.20- 1.80 width


are heavy motorcycles allowed? If not I'd rather use highway=cycleway and add foot=yes moped=yes

This said I agree that also in the region I am mapping there are narrow alley service roads which might be less than 1,80 wide at some spots (1,20 seems too narrow for the cases I am familiar with, though)

**Comment by jojo4u** [comment]
> This is a tagging mistake - the highway=service tag should not be used for paths too narrow for cars. Better use highway=footway (or highway=path).

Alley is exactly fitting for these corner cases where cars might be too wide. I would consider tagging a narrow street in an old city center of unknown width which is open to all traffic as highway=path a tagging error. From wiki (http://wiki.openstreetmap.org/wiki/Tag:service%3Dalley):
"In some medieval European settlements alleys may be the very narrow streets which run in-between buildings, providing public through-access. "

**Comment by math1985** [comment]
@jojo4u: true, and I think that might also apply to @dieterdreist's examples. However, the examples from @AllroadsNL are very different. They only serve as an access to the back of the row of houses (where typically bike sheds are located). All addresses are also reachable by a regular street. They are mainly found in 1960's and 1970's residential suburbs. Motorcycles are not specifically forbidden, but your neighbours would probably hate you if you went there with a motorcycle.

Some more examples: https://www.google.nl/search?q=brandgang

**Comment by AllroadsNL** [comment]
People are mapping it, and it shows on the map. Because they find it small, it is a alley, because the way give a service to residents, it is service.
The case is people tag it as highway=service services=alley, I can understand that.
That is the way openstreetmap works, the render must fit both in his style.
Now these cases do not look good on the map.
For routing path/footway/cycleway, it is not the nicest route, maybe the shortest, not the fastest, you can not drive fast, someone can come out the fence/shed door and do not expect you riding so fast.
This is also not desirable to route over it, but people map it because it is there.
Map-rendering footway/cycleway, give the a wrong image of the situation.

Path would be good but how to tag the service element to the residents
highway=path path=service service=alley (not common used)
This should not be rendered as red dotted, because of the first tag

I am still confused by rendering path as red dotted line like footway.
I read hierarchy, how did a road arise, people used a piece of land to go from a to b, a path or track arises, then they put signs on it to regulate, cycleway footway bridleway make roads wider with sign it became motorway.
path is not the hodgepodge, of what is left over, it is the first tag, then regulation.
footway is a partition of a path.

As the default map is a control map, you want to see the difference, for use, in a view, and then you can look into the tags if they are correct. 

are:highway=* is coming, open data  is coming.

In my opinion this service element must be rendered differently.
If others tag it in a other kind, this must be rendered equal or show a wrong render.
Usability: the map as a control map.

**Comment by AllroadsNL** [comment]
How do you render a not usual  "through route".

**Comment by daganzdaanda** [comment]
I would probably tag these ways as highway=service service=alley, because I'd think "It's a back alley". 
It's only a cosmetic problem, but yes, alleys could be a pixel or two narrower in most zoom levels (but not as thin as a parking aisle). They start tiny at z14 and 15 and then get a bit too fat at z16 to 18. z19 is almost OK, maybe a px less is fine. At z17 parking_aisle has a sensible width.
Rome has a lot of oneway alleys in the city center. That might be a good test area. 
BTW, the new road style will make a few other roads narrower, but not alleys (AFAIK).

**Comment by AllroadsNL** [comment]
"Rome has a lot of oneway alleys in the city center."
But is that highway=service?
More unclassified or residential?

**Comment by dieterdreist** [comment]
sent from a phone

> Am 29.09.2015 um 09:58 schrieb AllroadsNL <notifications@github.com>:
> 
> "Rome has a lot of oneway alleys in the city center."
> But is that highway=service?
> More unclassified or residential?


they're alleys, traffic in the centre is generally forbidden except for authorized (limited traffic zone), i.e. taxis, public services (police, armed forces to protect embassies and government, residents, ...) vehicles, and these alleys often are noexit-alleys used mainly by pedestrians and motorcycles and residents (the latter 2 with authorization). Clearly they aren't unclassified, the bigger ones are residential roads, the smaller ones alleys.

**Comment by polarbearing** [comment]
```service=alley``` is used 600.000 times. Despite the controversy above, I think we should accept the presence of such mapping, and add 'alley' to the list of minor service categories, which already has 'parking_aisle', 'drive-through' and 'driveway', being rendered narrower and later.
