### ISSUE TITLE
[Suggestion] Humanitarian as standard map layer

### ISSUE THREAD

**Issue by SelfishSeahorse** [gravitystorm/openstreetmap-carto#1882]
I'm wondering if the current standard map layer couldn't be replaced by the humanitarian layer (or by a combination of humanitarian and MapQuest Open). In my opinion, it has a clearer layout (e.g., streets and symbols are not overemphasised) and the colours are softer and fit better together.

The town centre of Bern as shown with the humanitarian layer:
![humanitarian layer](https://cloud.githubusercontent.com/assets/14875493/10160603/e4b70400-669e-11e5-9a18-00bafe2f8372.png)

The same place with the standard layer:
![standard layer](https://cloud.githubusercontent.com/assets/14875493/10160606/e7306654-669e-11e5-93a8-da457aebfad1.png)

**Comment by gravitystorm** [comment]
This repository is for designing this particular map style, not for choosing which layer should be the default on osm.org. The process for choosing featured tile layers is found on the openstreetmap wiki at http://wiki.openstreetmap.org/wiki/Featured_tiles

**Comment by SelfishSeahorse** [comment]
Oh, I'm sorry!

**Comment by kocio-pl** [comment]
This is the place you should go when your issue is related to the OSM website:

https://github.com/openstreetmap/openstreetmap-website/issues

**Comment by SelfishSeahorse** [comment]
Thank you!
