### ISSUE TITLE
Should cities get a dot on low zooms?

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#1883]
Looking at Map Compare, I noticed how many maps show dots to mark the position of cities and towns at lower zooms. I think this does make sense and might be a good way to give more information about the size and importance of a city. What do you think?

Here's a link to Map Compare:
http://tools.geofabrik.de/mc/#6/42.3733/0.3446&num=6&mt0=mapnik&mt1=mapnik-german&mt2=hike_bike&mt3=toner&mt4=mapquest&mt5=cyclemap

Google, Bing, Stamen Toner render dots from z4 to z8, 
Here from z4 to z9,
Humanitarian has them from z4 to z10,
OpenMapSurfer / OSM Roads  from z4 to z11, but drops the dots from the biggest cities at z9 (smart!),
OpenCycleMap and Transport Layer from z5 to z7,
Mapquest Open keeps dots from z3 to z18.
The french style has dots for important cities on some zooms, but is not very consistent.

Also my old school atlas has circles and dots for the country-wide maps. It does stop showing the dots for closer maps, where the extent of a city is visible by the landuse / built-up area.

I really like the OpenMapSurfer OSM Roads Style (see openmapsurfer.uni-hd.de/ ). The labeling there is the best I've seen online.

**Comment by kocio-pl** [comment]
It could work. Combined with more elastic placement of the labels (not only on the bottom, see https://github.com/gravitystorm/openstreetmap-carto/issues/957) it could help us show more names.

**Comment by jojo4u** [comment]
Maps.me is marking capitals with a star :) https://medium.com/@Urbica.co/world-map-design-1a9711783333

**Comment by kocio-pl** [comment]
The same for the MapQuest Open style.
