### ISSUE TITLE
Line-color of 'leisure_playground' feature is invalid

### ISSUE THREAD

**Issue by PissedCapslock** [gravitystorm/openstreetmap-carto#1886]
In the `landcover.mss` file, the following line-color is defined
````
@playground: #ccfff1;
...
line-color: saturate(darken(@playground, 60%), 30%);
````
If I calculate this manually, you get

`@playground` is in HSL `164° 100% 90%` (see [online calculator](http://serennu.com/colour/hsltorgb.php)).

According to the [Less CSS website](http://lesscss.org/functions/#color-operations-darken), the `darken` function 

> Decrease the lightness of a color in the HSL color space by an absolute amount

`darken(@playground, 60%)` hence becomes in HSL `164° 100% 30%`

The `saturate` function, again according to the [Less CSS website](http://lesscss.org/functions/#color-operations-saturate)

> Increase the saturation of a color in the HSL color space by an absolute amount.

`saturate(darken(@playground, 60%), 30%)` hence becomes in HSL `164° 130% 30%`

The 130% saturation is invalid as far as I can tell. The acceptable ranges are `[0-360]` degrees for H(ue), `[0-100]`% for S(aturation) and `[0-100]`% for L(ightness). This can for example be seen on the [Less CSS website](http://lesscss.org/functions/#color-channel).

As the saturation is already 100%, it looks like the `saturate` call can simply be removed.

**Comment by math1985** [comment]
Good catch! We use CartoCSS, which dooesn't use LessCSS as far as I know, but I can imagine they work similar. Does ayone more?

**Comment by PissedCapslock** [comment]
According to [this document](https://github.com/mapbox/carto/blob/master/docs/latest.md#color), CartoCSS borrowed those functions from LessCSS. 

> Carto also includes several color functions borrowed from less:

That is why I referred to them.

**Comment by PissedCapslock** [comment]
I created a PR for this. But since I am not too familiar with Github, I messed up and the PR is not attached to this issue. See https://github.com/gravitystorm/openstreetmap-carto/pull/1888 for the PR

**Comment by matkoniecz** [comment]
> But since I am not too familiar with Github, I messed up and the PR is not attached to this issue.

See https://help.github.com/articles/closing-issues-via-commit-messages/
