### ISSUE TITLE
tourism=alpine_hut is too prominent

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#1887]
Sorry if it indeed was intended like this, but isn't `tourism=alpine_hut` too prominent?
For example, at zoom level 13 here: https://www.openstreetmap.org/#map=13/-3.7399/-38.5299
It is the only distinguished object on the map.

![alpine_hut](http://i.imgur.com/NJZYO7e.png)

(one good thing about this is that we can easily find wrongly tagged `tourism=alpine_hut` :-))

**Comment by jojo4u** [comment]
To answer the question you should post some examples of correctly tagged huts.

**Comment by matkoniecz** [comment]
> An alpine hut is a remote building located in the mountains intended to provide board and lodging. It is managed during the opening period. Typically, an alpine hut belongs to and is operated by an alpine club or a similar organisation. 

http://wiki.openstreetmap.org/wiki/Tag:tourism%3Dalpine_hut

So in that case it is a clear tagging error. Please, do not report problems caused by wrong tagging.

**Comment by polarbearing** [comment]
Investigated and fixed underlying tagging error, initially caused by iD 0.0.0.beta
