### ISSUE TITLE
add new milestone for removing features

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#1892]
Features are sometimes removed (as result of changes in tagging and for reasons discussed in #1630).

I think that it would be a good idea to create a new milestone to group tickets like  #1891 #1654 #908 #682 #667 #589 #41 #1812 maybe also #648

It would allow easier finding tickets from this group, it would be also a clear sign that stopping rendering of features is normal and good proposal are welcomed.

I am not entirely sure about name - what about "Remove feature"?

**Comment by imagico** [comment]
Good idea.

In terms of #1630 there are two different variants though - completely stopping rendering elements with certain tags or unifying rendering of different things that were formally rendered in different ways - like wood/forest and grassland/meadow.  The latter is often not technically a feature removal but in terms of design it is a style simplification.

**Comment by matkoniecz** [comment]
Maybe "Feature removal/unification" would be better, to explicitly cover both cases.

**Comment by math1985** [comment]
I think a tag would be better than a milestone.

**Comment by pnorman** [comment]
I don't think this is suitable for a milestone, as it's not a milestone.

**Comment by kocio-pl** [comment]
So "a tag" resolves this question?
