### ISSUE TITLE
leisure=theme_park outline is rendered incorrectly at beginning node

### ISSUE THREAD

**Issue by RicoElectrico** [gravitystorm/openstreetmap-carto#1894]
I checked and there seems to be no error in OSM data - the outline is closed and has 4 nodes as expected.
http://www.openstreetmap.org/#map=19/51.50109/23.53963
![error](https://cloud.githubusercontent.com/assets/1409116/10266990/17462b60-6a7f-11e5-9ab0-296864058b71.png)

**Comment by math1985** [comment]
Thanks for reporting! We are aware of it, see #481. It's caused by a bug in Mapnik.
