### ISSUE TITLE
highway/railway=platform closed way not rendered as area

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#1895]
example: https://www.openstreetmap.org/way/335542454 https://www.openstreetmap.org/way/179871201 
area=yes renders as area: https://www.openstreetmap.org/way/335542455 http://www.openstreetmap.org/way/118900916
public_transport=platform gets rendered as area: https://www.openstreetmap.org/way/335542456

Wiki documents node, way and area for railway=platform A circular platform is much more unlikely than an area-style.

**Comment by jojo4u** [comment]
Quote from http://wiki.openstreetmap.org/wiki/Tag:railway%3Dplatform 
> Platforms (especially wider ones) can also be mapped as areas for more precision. Adding area=yes has traditionally been documented as a requirement for mapping platforms as areas and is still necessary for correct rendering on the Standard tile layer. However, it has since been suggested that closed ways with railway=platform, but without area=yes, should also be treated as areas because ring-shaped railway platforms are unlikely to occur in reality. 

Wiki discussion in 2012 which failed to identify a circular platform since those should be usually splitted:l http://wiki.openstreetmap.org/wiki/Talk:Tag:railway%3Dplatform#area.3Dyes_.3F

I could not find a predecessor ticket here for the issue.

**Comment by math1985** [comment]
I think it would be confusing if closing a linestring suddenly changes the semantics of that linestring. I don't think we have other objects we treat (or want to treat) that way. As far as I know, for all objects that can be either a line or a polygon, the default interpretation is to treat a closed linestring as a line, unless accompanied by area=yes. Therefore, I think that as long tagging a platform as a line is allowed, we should expect mappers to add the tag area=yes to platform areas.

I'll close this issue therefore as won't fix (but I'd be happy to reopen it if counterexamples come up). I think the solution

**Comment by polarbearing** [comment]
> for all objects that can be either a line or a polygon, the default interpretation is to treat a closed linestring as a line

An example is the ```leisure=track``` issue, where the typical stadium oval is rendered filled, which however has led to the current trend of mapping as a multipolygon.

**Comment by dieterdreist** [comment]
2016-03-08 1:11 GMT+01:00 polarbearing <notifications@github.com>:

> An example is the leisure=track issue, where the typical stadium oval is
> rendered filled, which however has led to the current trend of mapping as a
> multipolygon.
>


+1, alternatively you can add area=no but I'm not sure if carto deals
correctly with these. The only true solution seems to be an area data type
with all other linestrings defaulting to linear ways.
