### ISSUE TITLE
Unclear construction in admin.mss

### ISSUE THREAD

**Issue by PissedCapslock** [gravitystorm/openstreetmap-carto#1896]
In the `admin.mss` file, there is the following construction (I left out some parts for brevity)

````
@admin-boundaries:     #ac46ac;
[admin_level = '2'],
[admin_level = '3'] {
  [zoom >= 4] {
    background/line-color: white;
    background/line-width: 0.6;
    line-color: @admin-boundaries;
    line-width: 0.6;
  }
  [zoom >= 7] {
    background/line-width: 2;
    line-width: 2;
  }
}
````
When you look at the rendering on the OpenStreetMap website for the `admin-low-zoom` data (to which this styling applies), you will notice that the lines are always rendered using `@admin-boundaries` as color, even for zoom levels `>=7`.

Why does this work with the above style ? I would expect that you need to nest the zoom-levels to obtain this effect. I was expecting a construction like

````
@admin-boundaries:     #ac46ac;
[admin_level = '2'],
[admin_level = '3'] {
  [zoom >= 4] {
    background/line-color: white;
    background/line-width: 0.6;
    line-color: @admin-boundaries;
    line-width: 0.6;
    [zoom >= 7] {
      background/line-width: 2;
      line-width: 2;
    }
  }
}
````

With the current code, I would expect that for zoom levels `>=7`, the `line-color` property was unspecified, hence the default would be used (black).

If the construct in `admin.mss` is indeed valid and should result in `@admin-boundaries` as line-color for all those levels, can somebody point me to the documentation where this is explained ? And perhaps indicate where this would stop. Would for example this

````
@admin-boundaries:     #ac46ac;
[admin_level = '2'],
[admin_level = '3'] {
  [zoom >= 4] {
    background/line-color: white;
    background/line-width: 0.6;
    line-color: @admin-boundaries;
    line-width: 0.6;
    [zoom >=6] {
      line-color: red;
    }
  }
  [zoom >= 7] {
    background/line-width: 2;
    line-width: 2;
  }
}
````
then result in `red` lines at zoom levels 6, 7, 8, ... or only to `red` lines on level 6, and `@admin-boundaries` lines on level 7,8,...

**Comment by kocio-pl** [comment]
I also like nested sections more, because it looks more like inheritance of properties than clean state.

**Comment by PissedCapslock** [comment]
For me, it isn't really about preference of one style or the other. I really want to know why they both have the same result, and if this is documented somewhere.
I am in the process of trying to write a converter from CartoCSS to SLD, so I need to understand the "rules". And this repository is a good one to test with: the OSM data is freely available, the styling is available in this repository, and the OSM website shows the rendered result.

**Comment by HolgerJeromin** [comment]
@PissedCapslock Zoom 8 matches `>= 4` AND  `>= 7` :-)

**Comment by PissedCapslock** [comment]
@HolgerJeromin I am aware of that. But I was thinking in CartoCSS you define a tree-like structure, and only the styles in your part of the tree are relevant.
In this case, you would have to consider the styles in a "neighbour-branch" as well, which makes things a lot more complicated.

And this was the first time I saw such a structure. None of the previous CartoCSS examples I saw had such a behaviour. So now I am wondering what else I overlooked ...

**Comment by pnorman** [comment]
> Why does this work with the above style

CartoCSS is based on CSS and [less](http://lesscss.org/), which is as close as you're going to get to a formal specification.

**Comment by gravitystorm** [comment]
@HolgerJeromin is right, it's quite straightforward to say that a rule defined as [zoom >= 4] would apply to zoom level 8, since zoom 8 matches that filter.

> Would for example this
[snip]
> then result in red lines at zoom levels 6, 7, 8, ... or only to red lines on level 6, and @admin-boundaries lines on level 7,8,...

Yes, it would give red lines on 6,7,8. You've specified that the red should apply to "[zoom >= 6]", so of course that applies to zoom 7 and 8 too. It would only not apply to those zooms if there was a [zoom < 7] filter too.

It's not clear to me why this is a problem, perhaps @PissedCapslock you're over-thinking this too much?

**Comment by PissedCapslock** [comment]
It wasn't a real problem, but more of a question whether it was a valid construct or not (but I could not mark this issue as such).
In short, I will have to adjust my CartoCSS -> SLD conversion tool to deal with this situation which is going to give me some headaches, but which has nothing to do with this project.

Thanks for the clarification.
