### ISSUE TITLE
add different rendering for building=ruins (or remove rendering)

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1898]
This tag is used rougly 4.7k times according to Taginfo. On the wiki it is defined as "An house, a village or other building abandonned. [sic]" and further as "A (or a group of) ruined building(s)."

I admit that the definition is not fully satisfactory e.g. the "group of" or the "village", but this value is quite different from other building values. So I propose to either render it differently or to drop rendering.

Example usage (not tagged by me): Some artificial ruins of a roman palace in the gardens of Palace Schönbrunn, Vienna, Austria. (https://www.openstreetmap.org/way/139125696) This particular ruin was built like that in 1778 (https://en.wikipedia.org/wiki/Sch%C3%B6nbrunn_Palace#Roman_Ruins).

Other usages: http://overpass-turbo.eu/s/bOo

If the rendering is kept the fill could be lightened and the outline could be dashed. I will try to come up with an example rendering.

**Comment by matkoniecz** [comment]
Rejecting special rule for building=proposed may be relevant here - see #485

**Comment by pnorman** [comment]
This request has the same problem as #485. If it's not a building, don't use a building tag with a non-"no" value.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 05.10.2015 um 12:36 schrieb Paul Norman <notifications@github.com>:
> 
> This request has the same problem as #485. If it's not a building, don't use a building tag with a non-"no" value.


while ruins is likely not a building type, it will in many cases describe something that still could be considered a building, so it's not a real no-value
