### ISSUE TITLE
cafe getting rendered as a pet shop (?)

### ISSUE THREAD

**Issue by danstowell** [gravitystorm/openstreetmap-carto#1909]
Hi - this amenity=cafe seems to me to be rendered with a "pawprint" icon such as I think is used for pet shops:
http://www.openstreetmap.org/node/3161665577

I don't see any reason in the metadata that this would be happening. I've shift-refreshed the tiles a few times. I'm puzzled...

**Comment by math1985** [comment]
There seems to be indeed a pet shop mapped at that place: http://www.openstreetmap.org/node/3161667152

Apart from that, this report is an instance of https://github.com/gravitystorm/openstreetmap-carto/issues/234.

**Comment by danstowell** [comment]
Oh of course! Good diagnosis.

**Comment by aceman444** [comment]
Maybe you could fix the syntax of their opening hours, while you have that POI on the radar :)

**Comment by danstowell** [comment]
@aceman444 those opening hours are not even correct - I was eating there on sunday. I had better simply remove them...
