### ISSUE TITLE
Mapnik rendering issue 

### ISSUE THREAD

**Issue by baditaflorin** [gravitystorm/openstreetmap-carto#1912]
![long island](https://cloud.githubusercontent.com/assets/2330999/10477913/9bd13542-7262-11e5-8f4e-6c1da39733e4.PNG)
apnik not rendering the whole name of Long Island in New York

**Comment by math1985** [comment]
Thanks for reporting! It seems the problem resolved itself now (could you confirm?), probably the tile on the right side was updated a bit earlier than the tile on the left side.

By the way, could you try to add a more descriptive title next time?

**Comment by baditaflorin** [comment]
yep, i can confirm. now is ok

Sure, i will try to add specific description next time :) 

Thank you very much math, have a good day
