### ISSUE TITLE
set z3 as minimum zoom level

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1916]
For me the information conveyed by zoom levels 0-2 is limited.

* z0 only displays land polygons and repeats them, which looks a bit ridiculous
* z1 displays country borders, but not much is visible here anyway
* z2 additionally shows a few labels of the biggest countries.

So it makes sense to start at z3. The only obvious drawback is that the whole world can no longer be visible in the map pane, but since the map can be panned and displayed information is limited that should be ok.

There is a `minzoom` setting in project.yaml, but it did not have any effect in Kosmtik. Is this controlled by the map display library or did I miss something?

**Comment by jojo4u** [comment]
On my desktop I find z2 a good overview of the world, labeling the biggest countries. z0 and z1  are repeating the contintents left and right which looks confusing. On my 420 ppi Android phone I need z1 to display nearly the whole world.

**Comment by math1985** [comment]
I think it'd be good to have the tiles available for people who need them. It might be better to instead limit the zoomlevels on openstreetmap.org (https://github.com/openstreetmap/openstreetmap-website/).

Google and Here stop somewhere around our z3, Bing stops somewhere around our z1

**Comment by gravitystorm** [comment]
I'd prefer to make the lowest zooms useful and/or interesting. For example, the OpenCycleMap layer shows some landcover colouring, and the MapQuest layer goes further and shows ocean and continent labels, among others. So there is scope for producing interesting maps even at these low zooms.

Whether it's worth showing them on osm.org is a question for elsewhere.

**Comment by imagico** [comment]
I don't think there is any gain from not rendering z0-z2.  These zooms are certainly improvable in this style but they don't look bad as is.  In #646 i suggested showing icesheets at z2.  You could also show continent and ocean labels at z1.

**Comment by nebulon42** [comment]
Ok, got me convinced. Let's improve those zoom levels instead of omitting them. Closing.
