### ISSUE TITLE
Error in rendering landuse=landfill partly surrounded with natural=wood

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#1919]
Hello, there.

I mapped [here](https://www.openstreetmap.org/#map=18/48.33172/6.13671) a `landuse=landfill` partly surrounded by `natural=wood`, but there seems to be an error with the rendering, as the tree icons of `natural=wood` also fills the `landuse=landfill` area, even if the background colors are OK. I suspect a Mapnik issue, but, the last bug I thought was a Mapnik issue, #1741, was instead a stylesheet issue, so I prefer asking here before; if this is indeed a Mapnik issue, I will report it to the Mapnik guys.

Awaiting your answers,

Regards.

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/way/376196324 had 

    landuse=landfill
    natural=wood

I just deleted the tag, so the rendering should be correct soon.

**Comment by dieterdreist** [comment]
2015-10-21 11:13 GMT+02:00 Penegal <notifications@github.com>:

> I mapped here <https://www.openstreetmap.org/#map=18/48.33172/6.13671> a
> landuse=landfill partly surrounded by natural=wood, but there seems to be
> an error with the rendering, as the tree icons of natural=wood also fills
> the landuse=landfill area,
>

there is also a natural=wood on the landfill object.
https://www.openstreetmap.org/way/376196324

**Comment by matkoniecz** [comment]
It seems to be a data error that is now fixed.

**Comment by Penegal** [comment]
My bad; sorry for the disturbance.
