### ISSUE TITLE
Standardize pictos of wood/forest and swamp/mangrove

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#1920]
Hello, there.

Some weeks ago, the #1728 pull request changed the tree symbols used for `landuse=forest` and `natural=wood` for smoother ones:
![forest](https://cloud.githubusercontent.com/assets/13777824/10664645/56878086-78c5-11e5-9977-64fc55b7a72e.png)

Now, I'm under the impression that the tree symbols used for `wetland=swamp`
![swamp](https://cloud.githubusercontent.com/assets/13777824/10664585/042b868e-78c5-11e5-95b1-8a9c3827217e.png)
and `wetland=mangrove`
![mangrove](https://cloud.githubusercontent.com/assets/13777824/10664575/ecd258c8-78c4-11e5-93f2-823cf4cd5358.png)
should be updated too to use the same tree symbol for swamp, and a multiroot version for mangroves, as they are now different, the difference being visible as the tree symbol for wetlands is not as smooth as the one for wetlands.

Just saying…

Regards.

**Comment by math1985** [comment]
@imagico what do you think?

**Comment by dieterdreist** [comment]
2015-10-22 14:21 GMT+02:00 math1985 <notifications@github.com>:

> @imagico <https://github.com/imagico> what do you think?



I'm not imagico, but I clearly prefer the existing mangrove/swamp trees
over those in the rendering above. Better looking (IMHO) and better
readable. And much more professional (there is the idea of spatial
extension / shadow / volume as well as being "earthed"/"grounded" that the
new trees are completely missing).

**Comment by Penegal** [comment]
@dieterdreist But the current tree icon of mangrove could be modified to display more roots and still have the general shape of the current one, but smoother like the current tree icon of woods. This is what I wanted to ask, but it seems I didn't express myself the right way: it's not the general shape of the icon, just its smoothness; the current wood icon seems more uncluttered than the tree icon for mangrove and swamps.

**Comment by imagico** [comment]
For mangrove i think there is neither a need or a good possibility for a change - the tree pairs do not make sense there (mangrove is always broadleaved).  You could try to create a symbol closer design-wise to the pairs but i don't think this would look good.

For swamp - yes, the paired symbols could be combined with the wetland pattern here.  Practically broadleaved species are much more common in swamp environments than conifers (with few exceptions like the cypress swamps in the southern US).  Maybe @SK53 has some further thoughts on that.

**Comment by Penegal** [comment]
Ah, I didn't speak clearly once again: I only thought to the broad-leaved tree icon, not the conifer one. Indeed, it would be useless and confusing to use both tree icons, but I only spoke about the broadleaved one.

**Comment by SK53** [comment]
@imagico Very quick response about leaf_type in swamp woodland. There are lots of boreal coniferous forests which are swamps. Muskeg is the example which comes to mind. Our two Russian mappers remarked when walking in woods near Karlsruhe that many northern woods are effectively swamps, which supports this. A quick google reveals at least one coniferous swamp vegetation type found as far S as Massachusetts (http://www.mass.gov/eea/docs/dfg/nhesp/natural-communities-facts/spruce-fir-boreal-swamp.pdf).

I'll need to review some of the current rendering for further comments: I've certainly missed some of the detail in more recent changes to rendering wetland & mangroves.

**Comment by imagico** [comment]
You are probably right although intuitively i would not consider boreal forests swamps.  Many of these are seasonal wetlands being water saturated during spring thawing but drying up during summer.  AFAIK many conifers, in particular Spruce, do not generally grow on permanently waterlogged soil.

Here is the swamp pattern with the wood/forest symbol:

![swamp with tree pairs](http://www.imagico.de/files/wetland_swamp2n.png)

**Comment by Penegal** [comment]
What would it need to merge this in master? Replacing the current PNG, PR this and that's it? Just to know if I can do it without knowledge of the internals.

**Comment by kocio-pl** [comment]
Yes, it seems like a not too hard challenge technically. I wish this discussion was more conclusive, but there will be a chance to tune a PR before it will be merged.

**Comment by Penegal** [comment]
Prepared a PR for that; I had a hard time not mixing authors and using a branch for the PR, but it seems good now.

**Comment by Penegal** [comment]
@imagico: there are comments you could answer on the #3051 PR.
