### ISSUE TITLE
Render most used tunnel=* values

### ISSUE THREAD

**Issue by noenandre** [gravitystorm/openstreetmap-carto#1921]
Similar to #440, tunnels now disappear if you add details.
Please create a list of the most used / documented values.

In addition to "yes", good candidates are "culvert", "building_passage" and "avalanche_protector".

**Comment by math1985** [comment]
The value building_passage should work already.

The value culvert works, but only for waterways - does it make sense for other types of roads?

I'm not familiar with avalanche protectors, does it make sense to render them as tunnels?

**Comment by nebulon42** [comment]
avalanche protectors: some are more and some are less open to one side, but as the cover is quite substantial rendering them as tunnels would make sense.

**Comment by HolgerJeromin** [comment]
avalanche is at least equivalent to covered=yes which is rendered like tunnel=yes

**Comment by dieterdreist** [comment]
2015-10-22 20:05 GMT+02:00 Michael Glanznig <notifications@github.com>:

> avalanche protectors: some are more and some are less open to one side,
> but as the cover is quite substantial rendering them as tunnels would make
> sense.



usually the term "tunnel" describes underground / underwater objects, if an
avalanche protector is "open on one side" (what actually means open on
three sides, because it will always be open at the entrace/exit) I wouldn't
see this as a tunnel, it sounds more like a roof.

**Comment by HolgerJeromin** [comment]
Feel free to propose covered= avalanche_protector on tagging or wiki

**Comment by dieterdreist** [comment]
sent from a phone

> Am 23.10.2015 um 17:16 schrieb Holger Jeromin <notifications@github.com>:
> 
> Feel free to propose covered= avalanche_protector on tagging or wiki


or maybe "gallery"? I believe that's the term for these "open tunnels"

**Comment by HolgerJeromin** [comment]
This is the wrong place for discussion, but I think about art galleries with this term.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 23.10.2015 um 21:16 schrieb Holger Jeromin <notifications@github.com>:
> 
> This is the wrong place for discussion, but I think about art galleries with this term.
> 


could be more explicit like "avalanche_gallery" or "road_gallery"(?)

**Comment by Gazer75** [comment]
culvert is a common term here for small tunnels under roads for streams or foot- and cycleways

**Comment by matkoniecz** [comment]
To summarize:

> In addition to "yes", good candidates are "culvert", "building_passage" and "avalanche_protector".

building_passage works already, avalanche_protector is not a tunnel, culvert works for waterways.

Discussion about new (if any) covered=* values should place elsewhere.

**Comment by Gazer75** [comment]
Around here an avalanche protector is considered a tunnel. Our Public Roads Administration flags them as tunnels in their database.

**Comment by dieterdreist** [comment]
2016-06-07 13:21 GMT+02:00 Gazer75 <notifications@github.com>:

> Around here an avalanche protector is considered a tunnel. Our Public
> Roads Administration flags them as tunnels in their database.



yes, it depends, some are tunnels, others are different constructions...

**Comment by vvoovv** [comment]
@matkoniecz 
Why did you declined rendering for avalanche protectors? The feature exists in the reality and must be rendered somehow.
A photo with avanlance protectors can be found [here](http://wiki.openstreetmap.org/wiki/File:Hahnenkoepfle_galerie.jpg). It's actually located under the ground as shown on the photo.

So I'd suggest to render them as tunnels for a quick fix.

**Comment by Gazer75** [comment]
I just tag them as tunnel=yes because of this "silliness"...

**Comment by matkoniecz** [comment]
Maybe avalanches protectors should be rendered, but "The feature exists in the reality and must be rendered somehow" is a poor argument - existence of something is not enough to show it on the map.

**Comment by vvoovv** [comment]
A very strong argument to render them:
They can be used as a shelter if there is an avalanche danger or just bad weather and save someone's life.

**Comment by vvoovv** [comment]
And the avalanche protectors are quire prominent on their vicinity unlike pure tunnels where we see only two entrances/exits.

**Comment by Gazer75** [comment]
Optimal solution would be a separate rendering of these. Maybe remove the dashed lien on the edge of the road for the side that is open. This would then be handled similar to the way cliffs, coastlines and other one ways are done. So basically one could say the right side of the way is open.

**Comment by HolgerJeromin** [comment]
To "fix rendering"  without lying for the renderer you could add covered=yes

**Comment by dieterdreist** [comment]
2017-06-12 16:17 GMT+02:00 Vladimir Elistratov <notifications@github.com>:

> A photo with avanlance protectors can be found here
> <http://wiki.openstreetmap.org/wiki/File:Hahnenkoepfle_galerie.jpg>. It's
> actually located under the ground as shown on the photo.
>

this one isn't a tunnel IMHO, it is open to one side. In German, this one
is a "Galerie", maybe in English it's a "gallery"? It is also not located
"under ground", but it is an earth covered roof (above ground, the road is
on the (cut) ground, above there's a roof).

**Comment by Gazer75** [comment]
There are many kinds of protections from landslides and avalanches. Some are very open like this, some may only have a very few openings and some are closed completely.
As long as there is no separate way of showing these on the map I feel it is better to display them as a tunnel rather than not.

**Comment by dieterdreist** [comment]
sent from a phone

> On 13. Jun 2017, at 18:15, Gazer75 <notifications@github.com> wrote:
> 
> As long as there is no separate way of showing these on the map I feel it is better to display them as a tunnel rather than not.


this thread is about certain tunnel values, if we decide to visualize them it is encouraging people to use the tag. If the feature isn't a kind of tunnel it shouldn't be tagged like this.

**Comment by vvoovv** [comment]
@dieterdreist 
For you information:
avalanche protector is described in the [OSM wiki](http://wiki.openstreetmap.org/wiki/Key:tunnel#tunnel.3Davalanche_protector).

**Comment by dieterdreist** [comment]
2017-06-14 15:57 GMT+02:00 Vladimir Elistratov <notifications@github.com>:

> avalanche protector is described in the OSM wiki
> <http://wiki.openstreetmap.org/wiki/Key:tunnel#tunnel.3Davalanche_protector>
> .
>



+1, that's fine because it states "A variant of covered
<https://wiki.openstreetmap.org/wiki/Key:covered>=arcade
<https://wiki.openstreetmap.org/wiki/Tag:covered%3Darcade> is *tunnel*
=avalanche_protector and should be used in case of tunnels alongside
mountains.", i.e. only for tunnels. I'm fine with rendering tunnel subtypes
as tunnels in carto.

**Comment by jojo4u** [comment]
The primary discussion about covered/tunnel=avalanche_protector was [here](https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/building_passage#covered.3Davalanche_protector). Though only 2 people participated. I'm a bit miffed about principal tagging discussions here (also about building/man_made in #2620). The tag is "good enough" and there are many much more pressing tagging problems.
