### ISSUE TITLE
Render office=lawyer 

### ISSUE THREAD

**Issue by iansan5653** [gravitystorm/openstreetmap-carto#1922]
Currently law offices aren't rendered at all, which is a problem in areas such as [this one](https://www.openstreetmap.org/#map=19/26.64414/-81.86889) in which an entire side of the block is law offices. They are useful and I see no reason not to render them. As for how they should be rendered, I suggest using the amenity pink styling with a [lawyer scale](https://2012thetrial.files.wordpress.com/2012/03/law-scale_jpg2.jpg) icon. Even though they are really tagged as offices, they are more comparable to medical offices like shop=optician or amenity=dentist.

**Comment by math1985** [comment]
See also #108 and #1697.

**Comment by ccamara** [comment]
I think that proposal should be extended to all types of offices (like office=architect or office=government). Copying from #108 :

> As far as I see it, the main difference between most shop=* and office=* is that whereas the first sell goods, the latter sell services. For that reason I think that if it has been decided that shops have to be rendered because they might be of any interest, offices should be rendered as well, as they are at least as interesting as shops, if not more (I'm thinking now about government offices, which additionally may be considered of public interest).
> 
> It is quite another thing the already mentioned problems of readability, but IMHO that should be addressed later as a different issue (eg: by defining the right icons, colours and zoom levels), but that should come after displaying offices (I find [this proposal](https://github.com/gravitystorm/openstreetmap-carto/issues/108#issuecomment-232641882) a good workaround to be used in the meanwhile)

**Comment by abdeldjalil09** [comment]
Hi,
office=* key is already in database , why you want to re-loading the database ?

**Comment by ccamara** [comment]
I'm not sure of having understood your comment properly. We know `office=*` is already present in the database, but what we are asking for is that those items tagged with them should be rendered in the default map, just as any other shop. (see my reasoning above)

**Comment by abdeldjalil09** [comment]
@ccamara Because the current milestone is "Database layout change".

**Comment by math1985** [comment]
You're right, I fixed the milestone.

**Comment by ccamara** [comment]
Thanks to both for noticing!

**Comment by andrzej-r** [comment]
@abdeldjalil09, @ccamara what do you mean by:
> office=* key is already in database [...]
?

In my PR (#3061) I had to use tags->'office' because I was getting errors saying there is no 'office' column in the table. Do you mean such column already exists in the main osm database and the problem was cause by our osm2pgsql setup used for testing?

Either way, tags->'office' does work, with or without the 'office' column.

**Comment by kocio-pl** [comment]
It probably meant that it is now available for rendering database (previously it wasn't), but this is in the form of hstore, so one has to use `tags->'office'`, indeed.

**Comment by Tomasz-W** [comment]
Do you think #3061 is resolving this issue? I don't have an idea for lawyer symbol, and I think that generic dot would be enough. Of course I'm open to any propositions and ready to try to design proper icon. What do you think?

**Comment by kocio-pl** [comment]
For a long time already I've been thinking of generic [section sign](https://en.wikipedia.org/wiki/Section_sign) (§) - we use such symbols rarely, but I think this is the proper case (pun intended :smile: ).

**Comment by Tomasz-W** [comment]
Simple section sign from https://commons.wikimedia.org/wiki/File:Section_sign.svg put into 14x14 matrix:

![office lawyer](https://user-images.githubusercontent.com/25656654/37360535-dc3ce082-26f0-11e8-8119-eb72ceb097b0.png)

Gist: https://gist.github.com/Tomasz-W/45897e9464e10201426f603535b180b7

**Comment by iansan5653** [comment]
What if we used a set of scales (⚖️) which are traditionally used to represent the law?

**Comment by kocio-pl** [comment]
We use it for a courthouse already: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/courthouse.svg

**Comment by lakedistrictOSM** [comment]
I don't associate the section sign symbol with law and therefore wouldn't interpret it as a lawyer's office if I saw it on a map.

**Comment by kocio-pl** [comment]
There are example like this symbol of a law book:

https://www.shutterstock.com/image-vector/law-book-statute-paragraph-sign-icon-635919041

**Comment by lakedistrictOSM** [comment]
Perhaps it's a standard symbol for law in some countries but not all, feedback from people in other parts of the world is needed. 

Scales of justice (courthouse icon but one side higher than the other) or gavel (judge's hammer) might be better icon designs.

**Comment by kocio-pl** [comment]
For me the scales and gavel are more related to the act of judging than law in general, while section sign is not that specific, but that's interesting to know what other people think about it. Comments?

**Comment by dieterdreist** [comment]
sent from a phone

> On 17. Mar 2018, at 23:34, kocio-pl <notifications@github.com> wrote:
> 
> For me the scales and gavel are more related to the act of judging than law in general, while section sign is not that specific, but that's interesting to know what other people think about it. Comments?
> 


also for me the scale and gavel refer to a judge much more than to a lawyer

**Comment by iansan5653** [comment]
A quick Google Image search for "lawyer logo" yields pretty much entirely
the balanced law scales.

**Comment by Tomasz-W** [comment]
For me, balanced scale is a symbol of justice, and "justice places" are courthouses. Section sign is taken from law books, which lawyers use everyday for their work, so it's more intuitive, I think.

**Comment by 1ec5** [comment]
How about a briefcase (💼)? I think it would be more recognizable than a section sign, clever as a section sign would be. If a briefcase could be confused with other kinds of offices, that would still be better than conflating law offices with courthouses.

**Comment by kocio-pl** [comment]
We already use something close for bag shops (and the briefcase can be related to any kind of office IMO):

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/bag.svg

**Comment by turnsole80** [comment]
Re: The section sign, it's also possible that it might be confused with a
dollar sign ($) at a quick glance. It's a pity, because it was a very
clever suggestion :)

**Comment by dieterdreist** [comment]
2018-03-19 11:54 GMT+01:00 Chris <notifications@github.com>:

> Re: The section sign, it's also possible that it might be confused with a
> dollar sign ($) at a quick glance. It's a pity, because it was a very
> clever suggestion :)




every sign can possibly be confused, I don't think it is an issue that
someone might confuse an $ for a §
but it could be an issue that the sign is not universally understood around
the globe (for me it works, but I believe it is used mainly in the German
speaking countries).
What about a stylized "formal" person, e.g. similar to the first one here:
https://it.dreamstime.com/illustrazione-di-stock-insieme-delle-icone-dell-avvocato-image69740009

**Comment by Tomasz-W** [comment]
Is blue dot enough or do we want to use blue section sign here? What is your opinion?

![1](https://user-images.githubusercontent.com/25656654/37360535-dc3ce082-26f0-11e8-8119-eb72ceb097b0.png)

**Comment by kocio-pl** [comment]
Could someone test a blue section sign rendering? I still like this idea.
