### ISSUE TITLE
Points with barrier=gate could be overlapped by highway name

### ISSUE THREAD

**Issue by vdmit** [gravitystorm/openstreetmap-carto#1923]
I've noticed that points with tag `barrier=gate` may be overlapped with highway names. Please have a look on this area at zoom 17 level: https://www.openstreetmap.org/#map=17/44.61711/33.68970

Barriers of any kind are very important to see at any map resolution.

**Comment by math1985** [comment]
So to be clear, this is a closed gate on a road, but the road itself if accessible from both sides? So you can get to the gate both from the East and the West, but you cannot drive from the East to the West or vice versa?

**Comment by vdmit** [comment]
Actually yes, it is (it's Russia, you see :) )  In this case on part of this road is easily accessible from main highway on the West, and from another... well, if you have good enough 4x4 off-roader - then it's also accessible by another long-long, curvy route. But - still, it's accessible.

Nevertheless, there could be situations when `access` tag could not be properly set - by various reasons (e.g. lack of information, etc). For example, some kind of barrier could prevent mapper from discovering of actual state of track behind this barrier. I will not put `access=private` or `access=restricted`, because I don't know where there is an end of restricted zone, etc.

**Comment by HolgerJeromin** [comment]
same as #1542

**Comment by math1985** [comment]
Good example where rendering the barrier is really important, though.
