### ISSUE TITLE
tourism=zoo corners render strangely

### ISSUE THREAD

**Issue by Grillmannen** [gravitystorm/openstreetmap-carto#1926]
There seems to be a problem in the rendering of zoos. In some corners it looks like there is a stray node, but as far as I have checked it's not a data problem.

Examples:
* https://www.openstreetmap.org/#map=19/55.48741/13.71742
* https://www.openstreetmap.org/#map=19/55.96658/13.52620
* https://www.openstreetmap.org/#map=19/56.03723/12.79137

It's clearly visible even at zoom 13:
* https://www.openstreetmap.org/#map=13/56.0340/12.8277

And zoom 11 if you squint:
* https://www.openstreetmap.org/#map=11/55.9230/13.5805

I have never seen it on more than one corner per polygon though...

**Comment by HolgerJeromin** [comment]
same as #481 The planed upgrade to mapnik 3 will solve the issue.
