### ISSUE TITLE
Create legend

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#1928]
I'd like to create an automatically-generated legend for this style.

I have started the work on the [legend](https://github.com/gravitystorm/openstreetmap-carto/tree/legend) branch, but there is obviously a lot more work to do. Help welcomed. The idea is to have a control file (describing what features to show in the legend) in this repository, and use https://github.com/gravitystorm/mapnik-legendary to generate the legend images.

**Comment by math1985** [comment]
Somebody created a complete (but non-autogenerated) legend on the wiki: https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key

**Comment by Wuzzy2** [comment]
Yes, that was me. I almost feel bad for having wasted so much time on this in a rather inefficient manner. XD

I would definitely love to see an improved legend which is also auto-generated, and I would not be opposed at all if the wiki page gets deleted (but only in favor of the auto-generated one, of course).
The current legend on www.openstreetmap.org is very incomplete and also outdated. The wiki is more complete, but also doomed to be outdated.

The autogenerated legend should IMO be way more complete than the current one which doesn't even get all the surface colors right. Of course putting all shop symbols into the sidebar would be overkill, but here's my idea:
Basic legend with most important features in sidebar, full legend in a seperate page (also generated) which is linked to from the sidebar. I originally intended that this wiki page would be the page to be linked to, but the developers were opposed.

> The idea is to have a control file (describing what features to show in the legend)

Yes, but we should still have a full legend without any exceptions. Each symbol without explanation is a potential mystery to the map user.

It is very important for a map to have a correct and complete legend, so I think this issue should be considered high priority.

**Comment by kocio-pl** [comment]
I don't believe any automated way is enough for such a complicated case as ours.

**Comment by yohanboniface** [comment]
For the record, I made this time ago: https://github.com/yohanboniface/Leaflet.TileLegend
Which sounded me then the best compromise between hand made and autogenerated legends: basically you define lat/lng for each feature on the legend, and a small map of this lat/lng is shown.
It may appear that at some point some feature needs an update (eg. you pointed to an embassy but it has moved over time), but when the rendering changes there is nothing to do.
Funnily enough, four years later, the legend seems still quite up to date here: http://map.hotosm.org/

**Comment by HolgerJeromin** [comment]
You can even optimize that part with a small provided SQL/OSM dump.  This would be even a nice unit test for Travis.

- import osm dump into database
- generate small tile for the legend
- react on errors

**Comment by kocio-pl** [comment]
Currently the best osm-carto legend is on the wiki:

https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key

I try to add and alter the items there and it's in pretty complete shape, but there are things missing (I made a TODO list on the end). It's not a big job, but it takes time as everything, so it would be good if somebody took care of this. At least somebody is adding icons to the wiki pages lately, like here:

https://wiki.openstreetmap.org/w/index.php?title=Tag%3Aamenity%3Dpublic_bath&type=revision&diff=1567356&oldid=1560431

**Comment by geozeisig** [comment]
Since I have already added many icons on the wiki pages, I know the topic. I can imagine helping to complete the page [Standard_tile_layer/Key](https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key). But how does it become a practicable legend? Is not the site too big now? Maybe it would help if it was divided?

**Comment by kocio-pl** [comment]
I guess it could be divided in the 3 big sections (points, lines, areas). 

My question is if there's any automatic way to help producing and maintaining such a rich legend, especially how much mapnik-legendary would be able to do comparing to the wiki version (could anybody test [the example](https://github.com/gravitystorm/openstreetmap-carto/blob/legend/legend.yml) and show the results)? 

I also don't know what to do with a [basic legend on the OSM.org website](https://github.com/openstreetmap/openstreetmap-website/blob/master/config/key.yml) - it's outside the scope of this project, however this is our primary deployment.

**Comment by geozeisig** [comment]
I updated the page [Standard_tile_layer/Key](https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key) and divided into three parts. Any fineness you will not be able to describe. But if something is missing please write on the [ToDo list](https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key). If there are updates I will even have an eye on it.
So far, there are already many features that belong to the legend. I hope you can still present that clearly. Maybe we try it manually first, because there are many exceptions.

**Comment by kocio-pl** [comment]
Thanks! We have mainly features from the last few releases/months missing, but it's still a very useful resource.

**Comment by jragusa** [comment]
Please note that Car repair service (#2658) is displayed with a pink label in the wiki page and not in brown as on OSM.

**Comment by geozeisig** [comment]
Thanks for the hint. I changed it.

**Comment by kocio-pl** [comment]
You have added some not yet released changes - it would be better to start with some already released, but if we have towers section already, there should be also lattice tower lighting symbol.

**Comment by geozeisig** [comment]
@kocio-pl For me it is doubtful if there really is lattice tower lighting. I have not found a convincing example yet. So I wanted to wait in the question until the release.
The question is surely what is a mast and what is a tower? And it's even more complicated as there is also **man_made=communications_tower**. How is it different? And do we need an icon for that too?

**Comment by dieterdreist** [comment]
2018-03-16 14:24 GMT+01:00 geozeisig <notifications@github.com>:

> @kocio-pl <https://github.com/kocio-pl> For me it is doubtful if there
> really is lattice tower lighting. I have not found a convincing example
> yet.
>

http://www.priess.dk/en/cabins-more-competences/lattice-towers first
picture

**Comment by dieterdreist** [comment]
http://www.carl-c.com/market-segments/floodlight-towers

**Comment by kocio-pl** [comment]
man_made=communications_tower is defined as a huge tower:

> A man_made=communications_tower is a huge tower for transmitting radio applications like television, radio, mobile phone or officials radio. It is often made from concrete and usually a far visible landmark. An indication could be a height greater than 100 meters.

> Another indication is, that a man_made=communications_tower has stairs and a lift inside, whereas as man_made=tower, tower:type=communication has to be climbed on the outside. 

We don't need new icon, because we already can show such properties and we use zoom level for showing size (z13+ as with other >100 m towers).

But this is discussions for #2671 or a new issue, not here.

**Comment by geozeisig** [comment]
These photos are not free and I can not use them in the wiki. For me it's also masts. Take a look at the page [DE:Tag:man_made=mast](https://wiki.openstreetmap.org/wiki/DE:Tag:man_made%3Dmast), I mean the Flutlichtmast .

**Comment by geozeisig** [comment]
Since March, many new icons (237 pieces in total) have been added and it would be good if on carto that would be explained in a legend. If no one has a better idea, a link to [Symbols](https://wiki.openstreetmap.org/wiki/SymbolsTab) would be an alternative. There are now many icons that are not intuitively understood by everyone.

**Comment by kocio-pl** [comment]
I think the link should be given to the whole key, not just symbols. There are some wetlands for example that I'm not familiar with. The main question is where we should place such link to be easy to discover? Standard legend on OSM.org website is not suited for both as many objects and for links.

**Comment by jeisenbe** [comment]
The legend in the wiki seems to be up to date (https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key).

If anyone want to make this more visible, they could consider opening a PR at the[ repository for the openstreetmap.org website](https://github.com/openstreetmap/openstreetmap-website), but I don't think there is anything else to be done here.
