### ISSUE TITLE
highway=turning_circle size should depend on @residential-width-zN

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#1931]
The new road style has changed the width of the residential and living_streets, so the size of the turning_circles need to be adjusted in some zoom levels. Below is an area from z15 to z18, and in z15-16 the circles are too prominent. In z17 they still overlap houses, thus they are larger than reality. In z18 they look fine (unchanged in size as seen from the half-refreshed image)

In this context I wonder if we drop the circles completely in z15 and maybe even z16.

![turning_z15](https://cloud.githubusercontent.com/assets/8266355/10860917/16189f6e-7f71-11e5-801f-a8ce4a35f321.png) z15
![turning_z16](https://cloud.githubusercontent.com/assets/8266355/10860918/161a6254-7f71-11e5-8c1a-595bd262a824.png) z16
![turning_z17](https://cloud.githubusercontent.com/assets/8266355/10860920/1627121a-7f71-11e5-8330-8e5c9dc64e61.png) z17
![turning_z18_half_cooked](https://cloud.githubusercontent.com/assets/8266355/10860919/1623a85a-7f71-11e5-9aac-685a42f86110.png) z18

**Comment by matkoniecz** [comment]
Can you give link to these locations?

https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss#L2114 is the problem with turning circle size hardcoded, instead of depending on road widths

**Comment by poempelfox** [comment]
location is probably http://www.openstreetmap.org/#map=18/52.46152/13.74293

**Comment by polarbearing** [comment]
Correct.

**Comment by HolgerJeromin** [comment]
http://www.openstreetmap.org/?mlat=51.88145&mlon=8.49593#map=16/51.88145/8.49593 has a series of turning_circles which shows this problem nice.
