### ISSUE TITLE
new road colours lead to roads dominating z5

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1935]
With the new colours roads are far too emphasised on z5. Example USA:

![us_z5](https://cloud.githubusercontent.com/assets/3531092/10864563/2e2b74b0-7ff2-11e5-9d5a-17c33cebb040.png)

Either the lines are too thick or the colours are too strong.

**Comment by sommerluk** [comment]
Might it be useful to render only motorways at this zoom level?

**Comment by matkoniecz** [comment]
> Might it be useful to render only motorways at this zoom level?

No, see for example http://www.openstreetmap.org/#map=5/56.438/95.669 http://www.openstreetmap.org/#map=5/-18.438/33.530 http://www.openstreetmap.org/#map=5/-12.469/-68.599

In general - main problem is extremely different road density - compare for example South and North America. Even now in some regions are not prominent enough.

**Comment by math1985** [comment]
Or even more ambitious - why render roads at this zoom level at all? It is not suitable even for long-distance planning.

**Comment by dieterdreist** [comment]
2015-11-02 15:41 GMT+01:00 math1985 <notifications@github.com>:

> Or even more ambitious - why render roads at this zoom level at all? It is
> not suitable even for long-distance planning.



it might be, if roads were discernible ;-)

**Comment by pnorman** [comment]
I think part of the road dominating problem is that there's nothing else on that zoom.

But when at I look at it, I find it better for travel planning in the northwest quarter of the US than before. On the east coast, it's not very useful, and it gives you the impression that there's multiple highways everywhere. But this what it's like on the ground, and I don't think it's possible to do useful route planning there at that zoom.

I had a look at z5 at a few maps (click for full scale, Geofabrik is approximately the old osm-carto road style)

![image](https://cloud.githubusercontent.com/assets/1190866/10893197/5dddda84-815c-11e5-947c-cc2133df7776.png)

I would say that the current style or HERE Map are the most useful for route planning, HERE having an advantage with more cities. The low motorway/water, motorway/boundary, and trunk/anything contrast make the old colours less useful.

Bing makes national parks really obvious, Google is similar though not as extreme. Neither of them make it clear that they're national parks and not forests. Google is probably worse here. 

HERE makes forests obvious. MQ Open tries to, but hillshading and terrain at this zoom when combined with JPEG artifacts doesn't work well.

Of the six, I'd probably put HERE on top of route planning at this zoom.

* Dots and offset labels make it easier to see close to cities
* More places are labeled
* There is an indication of being forested
* There is hillshading (not really an option for us)
* A more useful set of roads is shown (potentially a data issue, or specific to this area)
* It handles roads by the water better (e.g. on the east coast of Vancouver Island, potentially a data issue)
* A better representation of water, particularly around the north island.

A couple others I looked at
MapQuest.com: No roads at this zoom, does hill shading and terrain much better than MQ Open
Google vector-based: Same as Google, but doesn't show national parks

**Comment by nebulon42** [comment]
Thorough analysis, thanks. Markers for cities would be the next thing I wanted to experiment with as well as having distinct markers for capitals and giving capitals extra priority. I also think it might be worth considering to change the water colour (#1427, #1781).

**Comment by matkoniecz** [comment]
> A more useful set of roads is shown (potentially a data issue, or specific to this area)

Raw OSM data is poor for displaying the most important roads on low zoom. Without preprocessing only highway tag may be used - and in some regions displaying only motorways leads to blobs of roads, in some displaying both motorway and trunk is not enough.

What worse, there is no obvious method to fix it, as it would be extreemly hard to have consistent tagging without blatant tagging for renderer.

For example in UK on z5 even Yandex is better than OSM.

http://mc.bbbike.org/mc/?lon=-0.711759&lat=52.692589&zoom=5&num=4&mt0=mapnik&mt1=google-map&mt2=yandex-map&mt3=nokia-map&marker=

![selection_003](https://cloud.githubusercontent.com/assets/899988/16166131/c3b2190c-34e8-11e6-9f08-643fd9348de8.png)

And "do not render highway=trunk" is not solution, because in othe region reverse problem is present.

For example http://mc.bbbike.org/mc/?lon=-58.378992&lat=-1.98886&zoom=5&num=4&mt0=mapnik&mt1=google-map&mt2=yandex-map&mt3=nokia-map&marker=  OSM is losing again even with Yandex what is sad.

![selection_004](https://cloud.githubusercontent.com/assets/899988/16166171/2083c7ac-34e9-11e6-90c0-9324c9cd2472.png)

I think that there are minimal gains to achieve by tweaking road style. It is one of cases that shows limits of using raw OSM data.

**Comment by matkoniecz** [comment]
Additional tags that I know about road quality (lanes, surface). Using http://wiki.openstreetmap.org/wiki/Relation:route#Road_routes would require manual tweaking and it would be probably about as irritating in maintemance as manually blacklisting less important motorways.

**Comment by matkoniecz** [comment]
#2175 is related. Here is result of increasing prominence of cities::

![placename 39 1205 -94 4913 z05 750px f470a327f56cc31fe71a33fc6afd7581b498ee1d 750px](https://cloud.githubusercontent.com/assets/899988/16179328/5fb5980e-3662-11e6-8cc0-8cdfd77afa04.png)

Current version: https://cloud.githubusercontent.com/assets/899988/16179329/60ff92e6-3662-11e6-89d3-8bfa111933f0.png

**Comment by matkoniecz** [comment]
Additional before/after are at https://github.com/matkoniecz/before_after_for_placenames

**Comment by matkoniecz** [comment]
See #2189 for potential related change

before
https://cloud.githubusercontent.com/assets/899988/16316631/bc908e6c-3987-11e6-9c24-9cb7b7ab0f1c.png

after
https://cloud.githubusercontent.com/assets/899988/16316632/bc921a84-3987-11e6-899f-33618906009e.png

**Comment by kocio-pl** [comment]
Changing borders color from violet to gray and changing water color to a cooler shade of blue would also decrease road-related red color domination: https://github.com/gravitystorm/openstreetmap-carto/issues/2688#issuecomment-317144397.

**Comment by kocio-pl** [comment]
Resolved by #2933.
