### ISSUE TITLE
low contrast of primary highways

### ISSUE THREAD

**Issue by malenki** [gravitystorm/openstreetmap-carto#1936]
After changing to the new carto style primary highways have low contrast on z11 when running through farmland or woods or – worse – a mixture of them. The effect ist best seen near Meißen:
[permalink](http://www.openstreetmap.org/#map=11/51.1608/13.5266)
![2015-10-31_185500_scr](https://cloud.githubusercontent.com/assets/188565/10865093/225d9154-8001-11e5-9235-71858e19657e.png)

**Comment by nebulon42** [comment]
There is #1701 for changing the farmland colour. Would that be an improvement for you?

**Comment by malenki** [comment]
Brighter landuse=farmland could probably help, yes.

**Comment by kocio-pl** [comment]
+1

**Comment by mboeringa** [comment]
\+1

**Comment by kocio-pl** [comment]
Resolved by https://github.com/gravitystorm/openstreetmap-carto/pull/2654.
