### ISSUE TITLE
improve oneway arrow on cycle ways 

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#1937]
The line of the arrow is not very good visible on (at least paved) cycle ways. 
Perhaps a white halo would help.

**Comment by nebulon42** [comment]
Could you please link a location/post a screenshot? I'm wondering if I have overlooked something when working on them.

**Comment by HolgerJeromin** [comment]
Sorry forgot location. Being on mobile I cannot add a Screenshot right now 
http://www.openstreetmap.org/#map=18/50.76980/6.03935
