### ISSUE TITLE
Country specific ref shields (signs)

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1942]
Is it possible to do something like Here is doing with road numbering?

With the new rendering of roads they look a lot more similar now and its hard to tell them apart. Especially trunk vs motorway.

**Comment by pnorman** [comment]
Are you referring to #508?

**Comment by Gazer75** [comment]
Yes, sorry.... didn't really know what to search for to find any previous ones on this.
