### ISSUE TITLE
Red-green colorblind people and the new changes

### ISSUE THREAD

**Issue by Janjko** [gravitystorm/openstreetmap-carto#1945]
Hi,

I am [red-green colorblind, as well as around 1 in 12 males](https://en.wikipedia.org/wiki/Color_blindness#Frequency_of_red-green_color_blindness_in_males_of_various_populations). The new style is great, but the red motorways become not very visible at lower zooms. From zoom 12 until zoom 8, forests are making them not pop out as much as the blue ones did. I could see the blue ones with peripheral vision, but now they are not as visible. It's probably similar to green trunk roads and forests to people with normal vision.

After zoom 8 we have no more forests, but now motorways are as thick as railways, and I cannot distinguish them.

When I look at other websites with yellowy roads, I see Google maps has much lighter forest, roads are more orange then red, and they are thicker. All these things help. Openstreetmap.de has a yellow centerline with red edges, which makes them thicker, and lighter forests.

Railways could maybe be more black? Or maybe have little marks as seen on lots of maps.

It would be best if other colorblind people said something, and then we can see how big of a problem this is.

Janko

**Comment by polarbearing** [comment]
The advantage of Openstreetmap is that maps can be rendered for any special target groups. We have different renderings for cyclists and for public transport. There are projects printing tactile maps for blind people on plastic sheets with OSM data. 

So, it should be relatively easy to fork a style that adjusts the colour values for the problems colourblind people have. As many colours are now defined as variables at the top of the mss files, it should be possible to have a patch file that can be applied to keep development in the forks in sync.

**Comment by mboeringa** [comment]
I really think you should divert your attention and focus from the Standard style, and have a look at OpenTopoMap, which has a far higher contrast topographical style rendering, which is almost certainly much better suited to colorblind people:

http://opentopomap.org/#map=5/49.000/10.000

**Comment by jojo4u** [comment]
Nevertheless the problem should be taken into account when thinking about tweaking the new road colors.

**Comment by math1985** [comment]
I think one of the goals of this style sheet is to give similar elements the same lightness and saturation. That goal is probably incompatible with making the map friendly for people with colourblindness.

What are the opinions of others? Should we make 'friendliness for users with colourblindness' an explicit goal of the design? @pnorman any opinion maybe?

**Comment by imagico** [comment]
I think it should be a consideration but it should not take precedence above readability for people without color vision deficiencies.  Designing for color blind viewers comes with serious constraints and it would be unfair towards the other viewers to impose these constraints universally on them.

Side note: this is also a matter of principal difficulty: Although there are methods to simulate color vision deficiencies for normal people a normal color vision designer will never be able to fully understand how you view the world with such restrictions.  So they will have to rely much more on others' feedback for their work than normally - which is very difficult.

The only good solution would be a separate map style to address these particular needs.  However with the more limited use of color such a map would have an even harder time satisfying all the different sets of priorities map users have when using the map than a style that can make full use of the available color space.

**Comment by matkoniecz** [comment]
Currently, with so many different objects requiring different colours that even without considering readability for people with color vision deficiencies it is extremely hard.

See for example #1946 or #1936

Unfortunately rendering so many objects (landcover in so many colours is the worst) makes impossible to keep map both pretty, readable, not confusing and allow differentiation of all objects.

For example recent road changes attempted to make map prettier, more readable and less confusing (trunk in forest etc) at cost of making differentiating say highway=trunk and highway=motorway less easy.

Changing it to "map should render nearly everything, be pretty, readable, not confusing and allow differentiation of all objects -  also for colorblind people" may sound nice but it will not mean that it is possible.


> Railways could maybe be more black?

Railways were (as part of road redesign) made significantly more prominent.


> When I look at other websites with yellowy roads, I see Google maps has much lighter forest, roads are more orange then red, and they are thicker. All these things help. Openstreetmap.de has a yellow centerline with red edges, which makes them thicker, and lighter forests.

It is questions of tradeoffs. Rendering forest even lighter (forests were recently changed to be less dark) would make impossible to render other green colour in way that differentiates them from forests.


Unfortunately I see no easy solutions here.

**Comment by mboeringa** [comment]
> **The only good solution would be a separate map style to address these particular needs.** However with the more limited use of color such a map would have an even harder time satisfying all the different sets of priorities map users have when using the map than a style that can make full use of the available color space.

\+1, this is why I referred to OpenTopoMap, which, with its limited color ranges and high contrast, should be much more suitable for colorblind people. And yes, this comes with some restrictions, although I think the people behind OpenTopoMap did a pretty good job.

> Unfortunately I see no easy solutions here or even hard ones.
> 
> Currently, with so many different objects requiring different colours that even without considering readability for people with color vision deficiencies it is extremely hard.

\+1, this style is way to convoluted and evolved to even consider prioritizing color blindness as design consideration.

**Comment by Janjko** [comment]
OpenTopoMap is not the answer because only having a style readable by colorblind people is not the question. We have those, and we can make as many styles as we want.

The question is, do we want our default map, that we use as a showcase for OSM, and as a great tool for mappers, to be less than optimal for a lot of people?

All big sites take colorblindness into account because every little percent of users matters. Never untill now have I seen an important map that has those issues.

Well, we had much bigger issues with green roads on green forests, so this is a big step forward, but I wouldn't just throw colorblindnes to the unsolvable pile. It is a problem you guys didn't take into account, but it's not that hard. Just take it into account when thinking about future changes.

Thanks,

the 9% of males :-)

**Comment by nebulon42** [comment]
It's hard to take everything into account. By saying "just think about it" you're greatly oversimplifying the process. If so many map users are affected then at least one should find the time helping to ensure that osm-carto is usable for colour blind people. Just do it, it could be you. Talk is always cheap, doing things is hard.

**Comment by mboeringa** [comment]
> All big sites take colorblindness into account because every little percent of users matters. Never untill now have I seen an important map that has those issues.

*Most* big sites show nothing of all the subtle details this maps shows (and you as a color blind person unfortunately can not experience). They have far less information and categories being displayed. This is comparing apples and oranges...

> OpenTopoMap is not the answer because **only having a style readable by colorblind people is not the question**. We have those, and we can make as many styles as we want.

OpenTopoMap certainly isn't only for color blind people, it is close to a professional topographic map as created by national mapping agencies, but it sure is one of the better for people having difficulty with color nuances.

> the 9% of males :-)

We're not unwilling to listen, it is just that we, from a technical and design point of view, know that taking care of color blindlesness, will almost certainly negatively influence the map experience for the other 91% of males + 99% of non color blind females ***with this particular style*** that heavily relies on subtle color differences to convey a plethora of object classes.

Really, of all the styles you could choose to ask for color blindness compatibility, this one is the least suitable. This is not a joke.

> If so many map users are affected then at least one should find the time helping to ensure that osm-carto is usable for colour blind people. Just do it, it could be you. Talk is always cheap, doing things is hard.

@imagico had a good remark in this context of the quote above that I would like to repeat:

> Side note: this is also a matter of principal difficulty: Although there are methods to simulate color vision deficiencies for normal people **a normal color vision designer will never be able to fully understand how you view the world with such restrictions**. So they will have to rely much more on others' feedback for their work than normally - which is very difficult.

**Comment by matkoniecz** [comment]
I would propose to close this issue and suggest opening issues proposing some precise changes that would improve situation.

**Comment by kocio-pl** [comment]
+1

**Comment by Janjko** [comment]
+1

čet, 5. stu 2015. 12:15 kocio-pl <notifications@github.com> je napisao:

**Comment by fnorf** [comment]
http://icaci.org/files/documents/ICC_proceedings/ICC2013/slides/S08-A-3_Johannes%20Kr_ger,%20Jochen%20Schiewe%20&%20Beate%20Weninger%20-%20Analysis%20and%20improvement%20of%20the%20OpenStreetMap%20street%20color%20scheme%20for%20users%20with%20color%20vision%20deficiencies.pdf might have some decent hints for colors, that was for the old scheme though.

**Comment by math1985** [comment]
Thanks for the link!

**Comment by kocio-pl** [comment]
So, could we close this issue now?

BTW: There is a way to test different colorblindness types in Mapnik for a year already:
http://mapnik.org/news/color-blind

**Comment by nebulon42** [comment]
I think the original problem with motorways over forests on low zooms could be solved by paler forests, which we are discussing already in #2194 and #1387.

But it could be useful to use the filters for testing. I tried them out, but I would need to add the filter to every layer as far as I understand.

@flippmoke Is there a way to add the `color-blind-*` filter for the overall output just once?

It wouldn't let me add it to the Map object. Since I do not know so much about `image-filters` I might be overlooking something.
