### ISSUE TITLE
Remove stroke for boundary=national park at z7-9

### ISSUE THREAD

**Issue by systemed** [gravitystorm/openstreetmap-carto#1950]
Area features at z7-9 are generally not outlined (e.g. water, urban areas, woodland).

`boundary=national park`, however, has a dark green outline. At first glance this appears as a linear feature and causes confusion with other linear features (roads, railways).

[Point of comparison](http://tools.geofabrik.de/mc/#8/54.2288/-2.1395&num=8&mt0=mapnik&mt1=google-map&mt2=bing-map&mt3=mapnik-german&mt4=nokia-map&mt5=mapquest&mt6=cyclemap&mt7=public_transport): Google and HERE do not show an outline for these features. osm.de shows a thinner, fainted, dotted outline.

Removing the outline would make the map more readable at these zoom levels in areas where there is a high number of linear features in national parks.

**Comment by matkoniecz** [comment]
I would rather propose to remove fill and keep solely border as on other zoom levels.

Google and HERE are bad, rendering national park like forest is a really poor idea.

**Comment by kocio-pl** [comment]
+1

**Comment by math1985** [comment]
@kocio-pl +1 op @matkoniecz of @systemed?

**Comment by jojo4u** [comment]
A national park with forest still must be tagged landuse=forest or comparable.

**Comment by kocio-pl** [comment]
@math1985 +1 for the last (@matkoniecz).

**Comment by imagico** [comment]
I find the current styling of protected areas a problem as well, the boundary styling works reasonably well on intermediate scales relative to the size of the area and with areas of limited geometric complexity like here:

http://www.openstreetmap.org/#map=12/49.2429/7.7727

but in other cases it does less so.  The semitransparency of both boundaries and fill is causing problems by modifying other colors, the fill in particular further obscures the already difficult boundaries between water and forest/wood.

Ideally i think features like this could well be put into a separate overlay and not be part of the general map style but most likely it will be hard to get support for fully removing these.

**Comment by SomeoneElseOSM** [comment]
It's worth noting that the thick green line around national parks at z7 is a (relatively) new feature.  You could argue the case at higher zooms to e.g. distinguish the boundary in a forest, but at z7 where there aren't other green features it's a bit superfluous.  Previously (18 months or so ago) there was a less defined dashed green lines around national parks at z7, and it was far less visible among the green trunk roads:

![rnoeez4](https://cloud.githubusercontent.com/assets/5311740/10910442/5ac32198-8237-11e5-9864-2e735479a3d2.png)

**Comment by almccon** [comment]
There are also cases where national parks properly extend into the water, such as Channel Islands National Park http://www.openstreetmap.org/#map=10/33.8385/-119.9872 or Dadohae Sea National Park http://www.openstreetmap.org/#map=11/34.1743/126.6428

These are arguments for maintaining an outline and potentially even dropping the fill.

**Comment by pnorman** [comment]
I'm not sure about rendering solely as a fill. Where I've seen it done, it tends to lead to confusion with wooded areas

If there's confusion with a linear feature, we should try to address that. Maybe a wider inner line? Maybe a gradient inner line? I've seen this done a couple places.

**Comment by jeisenbe** [comment]
3 comments above by current maintainers ([1](https://github.com/gravitystorm/openstreetmap-carto/issues/1950#issuecomment-153334890), [2](https://github.com/gravitystorm/openstreetmap-carto/issues/1950#issuecomment-153864416), and [3](https://github.com/gravitystorm/openstreetmap-carto/issues/1950#issuecomment-153347098)) are opposed to removing the outline but support removing the semi-transparent green fill color. Another comment suggests that both the border and fill are problematic at these zoom levels: https://github.com/gravitystorm/openstreetmap-carto/issues/1950#issuecomment-153351401
I agree that removing the green semi-transparent fill is a better option. Since it appears we have consensus about this issue, I will close it.
