### ISSUE TITLE
Rendering stale data?

### ISSUE THREAD

**Issue by zeromap** [gravitystorm/openstreetmap-carto#1951]
Over [6 months](https://www.openstreetmap.org/way/20146661) ago I changed the highway value for the roads in [this park](http://www.openstreetmap.org/#map=17/42.93049/-75.99206) from their TIGER imported value of unclassified to service. I also aligned the geometry slightly. In that time those changes have never been rendered on the standard map. I figured maybe it would take a while to update the tiles, but with the recent style change the tiles are fresh but the data rendered is old. This problem doesn't exist in any other renderer or software that I know of. How is this possible? 

![stale](https://cloud.githubusercontent.com/assets/15248277/10910425/5c850f3e-820d-11e5-9361-8fe3a69fd728.png)

Edit: Curiously this also affects other features I made during that changeset
[Building](https://www.openstreetmap.org/way/341793971)
[Building](https://www.openstreetmap.org/way/341793967)

**Comment by math1985** [comment]
@tomhughes Do you have any idea what might cause this?

**Comment by tomhughes** [comment]
No.

**Comment by gravitystorm** [comment]
We should stop asking OSMF tileserver questions to @tomhughes directly - there's an entire team of sysadmins who can deal with these questions, not just Tom.

Until anyone suggests otherwise, we should use the OSMF OWG tracker at https://github.com/openstreetmap/operations

In this specific case, it's a problem with the data on the OSMF tileservers (since the other map styles match the data layer), so not something that's handled in this stylesheet repository.

**Comment by tomhughes** [comment]
I'm not sure what opening a ticket in the ops tracker is really going to achieve either.

At best an op is going to run a query on the production server and go "yeah, the geometry is wrong".

It's not like there's anything they can actually do to find out why an update didn't apply N months ago.

**Comment by gravitystorm** [comment]
At the least, the ops team can realise the db is missing at least one update, and schedule in a reload.

If it keeps happening, someone might figure out what's going wrong with the diff processing. Alternatively, someone might take a look at the timestamps and see if there are any obvious causes, e.g. replication failures from around that time.

**Comment by tomhughes** [comment]
You carry on living in your fantasy world, I'll stay in my real one ;-)

**Comment by tilmanb** [comment]
@zeromap : you can maybe fix this by "tickling" the object in question, that is by applying a small geometry change. Move a node a few centimeters - sometimes that will then cause the openstreetmap.org tile db to update to the correct state.
Of course this is ugly and clutters the ways history.

**Comment by kocio-pl** [comment]
One can also just add some near objects (like tree or grass) or simply fix the geometry even more.

**Comment by zeromap** [comment]
It makes sense now that it's a database issue. Thanks for directing me to the right place.
@tilmanb @kocio-pl Thank you for the advice.

**Comment by polarbearing** [comment]
> One can also just add some near objects
That would cause the tile to refresh, but not change the odd object in the database.

**Comment by mboeringa** [comment]
I would like to add to this issue another example. About a month ago or so, based on a help request on the OpenStreetMap Help forum if I remember it well, I edited a region in the Netherlands with a lot of JOSM validation errors until the particular region and features that were important were free of JOSM issues, including fixing some multipolygons.

Even though the area now shows up properly in all other styles, the Standard style still doesn't show the edits:

http://www.openstreetmap.org/#map=15/52.2821/5.5238
![stale_standard](https://cloud.githubusercontent.com/assets/7635726/11820574/85ce69ca-a365-11e5-9a60-261facceab16.png)
![stale_humanitarian](https://cloud.githubusercontent.com/assets/7635726/11820579/8ca75bbc-a365-11e5-8602-b290f6238f39.png)
![stale_mapquest_open](https://cloud.githubusercontent.com/assets/7635726/11820580/8cc44e66-a365-11e5-8b7b-70ab69639e09.png)
![stale_transport_map](https://cloud.githubusercontent.com/assets/7635726/11820581/8cc7cf50-a365-11e5-927c-73bfb1527b4b.png)
