### ISSUE TITLE
Forest Mapnik Landuse Face Partially Overlying Water Face

### ISSUE THREAD

**Issue by PaulColinSimpson** [gravitystorm/openstreetmap-carto#1954]
When looking at area http://www.openstreetmap.org/#map=17/51.72011/-0.01848 you will notice that the water face only partially overlaps the forest face. For some reason the forest landuse colour disappears only revealing the forest symbols which looks strange.

**Comment by math1985** [comment]
This is a tagging error (assuming there are no trees growing in the lake). The forest should be tagged as a multipolygons with the lakes as 'inner' components.

**Comment by matkoniecz** [comment]
See #1754 for more detailed explanation.

**Comment by PaulColinSimpson** [comment]
Many thanks matkoniecz! I much clearer on this now
