### ISSUE TITLE
trunk_link wider than motorway_link

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#1955]
Perhaps introduced by #1861

![map](https://cloud.githubusercontent.com/assets/156724/10942231/75978c10-830f-11e5-9c5f-8b1ca24ba5cc.png)
http://osm.org/go/0DpSzmveu

**Comment by sommerluk** [comment]
Duplicate of #1109

**Comment by matkoniecz** [comment]
I am not entire

**Comment by jojo4u** [comment]
Yes, looks like duplicate.
