### ISSUE TITLE
 building=* should render over area=yes highway=pedestrian

### ISSUE THREAD

**Issue by sladen** [gravitystorm/openstreetmap-carto#1958]
**building=*** should render on top of **area=yes** + **highway=pedestrian**:

* http://www.openstreetmap.org/way/155150429#map=19/51.46695/-0.44157
* http://www.openstreetmap.org/way/155150423#map=19/51.46689/-0.44169

**Comment by math1985** [comment]
Welcome to the repository, and thanks for the report!

If I'm not mistaken, this is the same issue as #688.
