### ISSUE TITLE
Display both local and English names?

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1960]
Is it possible to do like Mapquest and display maybe English names for Russian, Asian and Arabic names?
I pretty much have to use other maps to view these regions as I can not read the names.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 06.11.2015 um 02:26 schrieb Gazer75 <notifications@github.com>:
> 
> Is it possible to do like Mapquest and display maybe English names for Russian, Asian and Arabic names?
> I pretty much have to use other maps to view these regions as I can not read the names.


What about Russian, Chinese and Arabic names for regions with the Latin alphabet?
Problem is that bigger labels will lead to fewer information and more clutter in general

**Comment by SomeoneElseOSM** [comment]
I actually quite like the idea that the "standard" map is a _local_ map, and uses the language and script of a local country.  3 of the 5 map styles on osm.org already display a latin name in addition to "name" - is there really a need for a 4th to do so too?

(there are of course issues where there's more than one local "name" for a place - see http://forum.openstreetmap.org/viewtopic.php?id=31333 for a good discussion of those - but that's separate to treating a latin-script name as somehow "special").

**Comment by Gazer75** [comment]
The chance of people using one of the non Roman letters actually reading Roman and English is far bigger than the other way around. The standard renderer is supposed to be OSMs face outwards and should be usable for all.

Best thing would be to have a language option on the site, but that has probably nothing to do with the renderer itself.

**Comment by pnorman** [comment]
I feel that this duplicates #803 even though they're talking about different tags.

**Comment by Gazer75** [comment]
You're right. Its pretty much the same thing.

**Comment by math1985** [comment]
Closed as duplicate.
