### ISSUE TITLE
No aeroway=gate rendering, but included in text queries

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1963]
See https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml#L2017
Currently unused, is this correct?

**Comment by HolgerJeromin** [comment]
I am pretty sure we had gate rendering in the not too distant past.

**Comment by nebulon42** [comment]
There is a rule for rendering the name in the style files. I missed that, sorry. This is unrelated to the issue you mentioned.
