### ISSUE TITLE
remove or reduce casing of highway=pedestrian at z13

### ISSUE THREAD

**Issue by nebulon42** [gravitystorm/openstreetmap-carto#1965]
Otherwise it has a quite noisy appearance like here: https://www.openstreetmap.org/#map=13/46.6153/13.8568

![villach_pedestrian_z13](https://cloud.githubusercontent.com/assets/3531092/11021589/709fae92-8646-11e5-9254-aabfa310fe68.png)

**Comment by pnorman** [comment]
I agree it's unclear. I'm not sure reducing the casing is the solution, since it might make it invisible against common backgrounds.

**Comment by daganzdaanda** [comment]
I think they should be turned into a single line in the same colour that service roads have at that zoom, which is the `@unimportant-road` color. I guess the width could be left at 2px.
Z12 could be done similarly (#1964)

**Comment by daganzdaanda** [comment]
Actually if I read the mss right, now at z=13 service roads get line-width: 1 and no casing ([roads.mss#L1452](https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss#L1452) and [L516](https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss#L516)), while pedestrian roads have 2px casing and a fill width of 
`line-width: @living-street-width-z13 - 2 * @casing-width-z13;`
which equals 1 ([roads.mss#L1497](https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss#L1497))
Should highway=pedestrian still be "more important" on the map at z13 than highway=service roads? Could we treat them the same? Or maybe as a compromise, pedestrian roads could be 1.5 px wide with no casing?

**Comment by matkoniecz** [comment]
> Should highway=pedestrian still be "more important" on the map at z13 than highway=service roads? 

This is intentional as there are many cases of pedestrian roads relevant at this scale and for service roads it is fairly rare. Unfortunately it is merely my impression, it is possible that it is untrue for some/many regions - but some (#1964) complained that highway=pedestrian may form not displayed large-scale structures and AFAIK there are no similar complaints for highway=service.

**Comment by pnorman** [comment]
Current rendering of that area
![image](https://cloud.githubusercontent.com/assets/1190866/19843260/b74fcc54-9edd-11e6-9be6-5d41f1ce760c.png)

With the width changes and other changes, I think it's okay as is.
