### ISSUE TITLE
oneway arrow has precedence over fuel icon

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#1968]
This fuel icon is disappearing in zoom19 but visible in zoom 18:
http://www.openstreetmap.org/node/226914672

**Comment by pnorman** [comment]
> This fuel icon is disappearing in zoom19 but visible in zoom 18:
> http://www.openstreetmap.org/node/226914672

Please [include a cropped screenshot of the problem](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#reporting-issues) for future bug reports

![image](https://cloud.githubusercontent.com/assets/1190866/11087741/a5cc2b5a-8811-11e5-9578-a43d9d02e9a3.png)

**Comment by kocio-pl** [comment]
The problem from the example is no longer visible - we can close this issue.

**Comment by math1985** [comment]
Has this been solved in the code too, or is it fixed by a change in the data?

**Comment by kocio-pl** [comment]
The road is still oneway, so it looks like it's been really solved.

**Comment by pnorman** [comment]
Closing since there's no new examples, and the behavior in question is probably covered by #2429

**Comment by kocio-pl** [comment]
Closing, but this time it's for real. :wink:
