### ISSUE TITLE
Legend: footway,path and the description

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#1970]
Now that path and footway is rendered the same, a problem is created in the Legend, like the Dutch legend. It is called "voetpad", this is not right because the name "voetpad" this is a path where only by foot is allowed. A sign gives the access rules of the way or the area.
On path also vehicles are allowed.

The value tag path did not come back in the description (use/access). "Voetpad" is wrong.
"Pad" is right.

Footway is a subdivision of the category path (small ways, single tracked).
You should use a summary term, to express both in the description.

"Voetpad" footway description gives the wrong impression and lead to wrong tagging. Be aware of that! They think, ohh, on the map, all must be footway. This gives a coercive effect, we do not want that, my believe.

As mentioned in other issues, I do not agree with submerge of the two in the rendering. Like many others, i read the lasts month. I find this a issue.
In the Netherlands they conscious tag, path or footway, They liked to see the difference. I made the distinction also. Together with other changes made lately. This lead to the lost of interest by good mappers. And a number of them become more inactive in OSM or in a part of interest, I assume, this we do not want. Be aware of that too. The effect of a default map.

**Comment by matkoniecz** [comment]
Note that legend on the main OSM page is handled at https://github.com/openstreetmap/openstreetmap-website - see for example https://github.com/openstreetmap/openstreetmap-website/pull/1070 and https://github.com/openstreetmap/openstreetmap-website/pull/1017

Translations are handled at https://translatewiki.net/wiki/Translating:OpenStreetMap

**Comment by matkoniecz** [comment]
See also #1928

**Comment by AllroadsNL** [comment]
Closed already within 4 hours after opening
There is no substantive response.

The issue is still open, not solved.
Who makes the map, makes the legend.

**Comment by gravitystorm** [comment]
@AllroadsNL I do not like your attitude. Remember that we are all volunteers - and you are able to volunteer to help too just as much as anyone else.

> There is no substantive response.

Yes there was - @matkoniecz kindly provided you with detailed information as to which project is responsible for the legend on openstreetmap.org , and information about where the translations are handled too. This gives you a clear way forward if you want to help get this fixed.

**Comment by AllroadsNL** [comment]
@gravitystorm about attitude,(first post, second post?), a volunteer, like you all, I know, but can you imaging how it feel when someone takes the step to come over here, take effort to learn Github, how it works, and make a issue and that is closed within 4 hours and marked invalid. I do not agree with that. I am not native english speaker/writer, so my word/sentence choice is maybe based on my native language. My English level is, so so. That I held the project against the light, (first post, last part) was a conclusion of what I read in forums, contact with other OSM people and my own experience, I mentioned it here as a reflection. Items, you could use for self-reflection. Some of you are key players making the map, thanks for that, my appreciation. But be aware of what is happening.

I have a positive attitude. criticism is positive also.
But if you think not pm me, explain it.

Short: The discussion is how is a road called with a combined line for path and footway.
That I mean with substantive response.
Then it could set in the English legend and translated to Dutch.
used in the reference links of @matkoniecz .

I gave some history, that i not agree with, the merge, decisions are made, this issue is separate from it, I treat it like that, but is a result of merging, here i make a point, we can reconsider this decision path and footway, mentioned as a hint. Many would be glad if path is separate on the map
