### ISSUE TITLE
Render railways tagged service=crossover as other service=* railways

### ISSUE THREAD

**Issue by Edward17** [gravitystorm/openstreetmap-carto#1971]
Hi!

Please add rendering of lines with tags __railway=rail + service=crossover__ as other lines __railway=rail + service=*__ (for example, __railway=rail + service=spur__).

__service=crossover__ are renderd now as on the screenshot below (small tracks between main tracks) ([This object in OSM](http://www.openstreetmap.org/way/339638534)):
![bad](https://cloud.githubusercontent.com/assets/11292985/11098715/06ac7714-88a7-11e5-96a9-15dcfef5d03d.png)
But should be rendered so ([This object in OSM](http://www.openstreetmap.org/way/252782085)):
![good](https://cloud.githubusercontent.com/assets/11292985/11098716/06ae336a-88a7-11e5-8f25-cdc6eccef645.png)

Thanks!

**Comment by HolgerJeromin** [comment]
I had the same feeling at first. 
But the crossover is part of the main route. The philosophy is that a train with passangers never use gray rails.

**Comment by Edward17** [comment]
@HolgerJeromin what about `service=crossover` between two gray rails? For example: http://www.openstreetmap.org/way/332450082

**Comment by HolgerJeromin** [comment]
Good point. This looks not right:
![github](https://cloud.githubusercontent.com/assets/2410353/11103116/d9a596dc-88c0-11e5-96f3-ad8e9381c78e.png)

**Comment by Edward17** [comment]
@HolgerJeromin Thanks :)

Is it possible with software used for rendering of Standart layer tiles to distiguish `service=crossover` rails which have minimum one connected non-service rail from crossovers which are connectod only to service-rails?

If yes, hovewer this logic have to be implemented. If no or if this implementation is too hard, it's eisier to render all `service=crossover` as gray rails.

**Comment by Edward17** [comment]
Sorry, bur here:

> rails which have minimum one connected non-service rail

have to be "rails which are connected with minimum __two__ non-service rail", because black rail between one `service=*` and one non-`service=*` rails looks also not right. Example: http://www.openstreetmap.org/way/379590835

**Comment by pnorman** [comment]
> Is it possible with software used for rendering of Standart layer tiles to distiguish service=crossover rails which have minimum one connected non-service rail from crossovers which are connectod only to service-rails?

The rendering DB has no topology, so there is no notion of connected. It's not reasonable to make the rendering of one railway line depend on others nearby.

**Comment by Edward17** [comment]
Well, I propose to render just all `railway=rail + service=crossover` as gray rails (as described in issue text).

**Comment by jengelh** [comment]
If both rails are, for example, service=yard, then would it not make sufficient sense to also tag crossovers as yard? Arguably, in a yard, it's all the same anyway.

**Comment by pnorman** [comment]
> If both rails are, for example, service=yard, then would it not make sufficient sense to also tag crossovers as yard? Arguably, in a yard, it's all the same anyway.

It doesn't matter for us, since this is proposing to render them the same.

**Comment by HolgerJeromin** [comment]
i think jengelh suggested that crossover in a field of yards is a tagging error, so no change in the rendering is needed.

**Comment by Edward17** [comment]
> If both rails are, for example, service=yard, then would it not make sufficient sense to also tag crossovers as yard? Arguably, in a yard, it's all the same anyway.

I posted a question in OpenRailwayMap Mailing list:
http://lists.openrailwaymap.org/archives/openrailwaymap/2015-December/000377.html
(available in German and English)

**Comment by pnorman** [comment]
> i think jengelh suggested that crossover in a field of yards is a tagging error, so no change in the rendering is needed.

Sure, it might be a tagging error, or it might not. Either way, it doesn't change anything for us, since they'd be rendered the same with what is being proposed.

**Comment by Nakaner** [comment]
HolgerJeromin wrote:
> But the crossover is part of the main route. The philosophy is that a train with passangers never use gray rails.

That's not correct. Please have a look at the wiki pages of usage=* and service=*.
https://wiki.openstreetmap.org/wiki/Key:usage https://wiki.openstreetmap.org/wiki/Key:service

A passenger train often uses tracks which have a `service=siding` and no `usage=*`, e.g. if it is being overtaken by a faster train, waiting at a station on a single-track line or if the station only has platforms at its siding tracks (e.g. on high-speed railway lines).

I think that the examples provided by Eduard are tagged wrong. See my posting at OpenRailwayMap mailing list. http://lists.openrailwaymap.org/archives/openrailwaymap/2015-December/000378.html

I like the current rendering of tracks with `service=*` with a gray colour. I don't think that crossover tracks need to be rendered in gray, too. It would be just a QA feature for railway mappers to spot all those tracks which should have a `service=*` tag but do not have it. That's why I leave the decision to render these crossover tracks gray to the developers and their decision if OSM Carto is more a QA tool or an end user map. :-)

**Comment by Edward17** [comment]
@Nakaner thanks for answer. I will set for my examples right tags, as described in OpenRailwayMap mailing list.

So, we don't need a rendering of `railway=rail + service=crossover` as gray rails. I close this issue.

---
_offtopic_
@Nakaner I cannot answer on your message in mailing list because of I forgot to subscribe. So I say to you here: thanks and agree to your tagging examples.

**Comment by jeisenbe** [comment]
FYI, the OSM wiki page for service=crossover does not make it clear that this tag isn't used in yards or on spurs. Could someone please check the wiki page and current usage to see if the description needs to be updated? https://wiki.openstreetmap.org/wiki/Tag:service%3Dcrossover
