### ISSUE TITLE
Consider level=*

### ISSUE THREAD

**Issue by PanierAvide** [gravitystorm/openstreetmap-carto#1977]
Hello, I think the rendering should consider objects with `level=*` tags, as consider I mean ignore or use a special rendering (depending of what is most reasonable). The reason of this issue is that objects with level tags most of the time are under or above ground (level different of 0), so making it appear on map could make people thinking they are on ground when they are not.
Example ([OSM.org](http://www.openstreetmap.org/#map=19/48.12109/-1.70414&layers=N)):
![Villejean Université Subway](https://framapic.org/ewRWwdr56H6m/RO7c1eXw)

Each trash bin, bench and information board is under ground (`level=-1`), but with this rendering it seems like it is on ground.

**Comment by jojo4u** [comment]
Level -1 does not mean underground. It means first basement floor. In a building at a steep hill this can be partly above ground. The key level groups features on one floor together, it's imho not used for "what is above each other" aka "vertical relationships". For example this platform which extends to underground to the right is level=-1: https://goo.gl/maps/XUW99gv6hF72 

For the "vertical relationships" the key layer is used. But this also does not mean that something is invisible from the ground, see example picture from Wiki: http://wiki.openstreetmap.org/wiki/File:Washington_layers.png

The tag location=indoor/underground or the tag indoor=yes comes closest what you want to accomplish.

**Comment by PanierAvide** [comment]
Thanks for your reply. I agree with the point that first basement floor is not always underground, but as level=0 is ground, most of the time it will be underground. The idea of using `level` key is to make the change simple. But in fact it would be more reliable to check if the object is inside the area of a building (and checking its `building:levels` value).

You propose `location` or `indoor=yes`, is it already supported ? If not, I'm not sure using this kind of tag is really a good idea. It's like saying an indoor oriented map should ignore outside objects only if they have an `outside=yes` tag. I'm sure we can find a more subtle way to do this ;)
Just to make it clear, I'm not saying that we should ignore `indoor` tag. This is the right way to distinguish indoor rooms or areas. I'm saying that for other smaller objects like trash bins or benches, it would be better to use something smarter than adding `indoor=yes` to ignore them as they already use other indoor-related tags (such as `level`).

**Comment by math1985** [comment]
@PanierAvide How would you expect this situation to be rendered?

**Comment by PanierAvide** [comment]
Something like this, where small objects with `level=-1` (here in the first basement floor of a subway station) are ignored :
![Subway](https://framapic.org/tkSl5Jzr48ls/BSiV31sJ)
Because they are not visible from the ground.

**Comment by HolgerJeromin** [comment]
Dropping some street furniture probably  would be OK, but important pois should be visible in any case.

**Comment by bjohas** [comment]
Here's another area that's not rendered well: 
https://www.openstreetmap.org/#map=19/51.53049/-0.12381
I've checked the tags very thoroughly, and e.g. tunnel=yes+level=-1 is treated differently from indoor=yes+tunnel=-1. E.g. in OSMAND, such objects look very similar, but as you can see, on OSM some are visible, while others aren't. The rendering on the multipolygon ontop of the underground ways doesn't help either. Thanks!!

**Comment by d1g** [comment]
1. 2D/3D: we are limited to 2D in this style, so I would display _mainly_ one layer (say, level=0); with exceptions
2. at `level=0`:
2.1 outdoor - keep; everyone can see them
2.2 indoor - also keep _if we keep only level=0_; this makes style less complex to compute
3. below - `level=-4` pedestrian footpaths in metro - http://www.openstreetmap.org/way/112391993/history; I would include them as they demonstrate level of detalization in OpenStreetMap and because our [routers can build paths using them](http://www.openstreetmap.org/directions?engine=graphhopper_foot&route=55.76076%2C37.57636%3B55.76094%2C37.57782#map=18/55.76081/37.57737). If we drop them, routing results will _float_ without underlying paths.
4. above - your examples here, please discuss

**Comment by PanierAvide** [comment]
> I would include them as they demonstrate level of detalization in OpenStreetMap and because our routers can build paths using them.
Concerning paths with negative level value, maybe we can render them like tunnel (maybe even lighter or semi-transparent), with appropriate z-index showing that they are feature below other ones.

**Comment by HolgerJeromin** [comment]
lighter/semitransparent is used here to show limited public access (parking for example)

**Comment by PanierAvide** [comment]
What about make the black stroke of the tunnel rendering grey ? The underground path will appear lighter but not that much.

**Comment by dieterdreist** [comment]
sent from a phone

> On 10 Jul 2016, at 14:26, Bjoern <notifications@github.com> wrote:
> 
> I've checked the tags very thoroughly, and e.g. tunnel=yes+level=-1 is treated differently from indoor=yes+tunnel=-1.


Please be more accurate in naming the tags,
are you talking about "level" or "layer"? In this area, both tags are present, but they have very different meaning.
In the whole world there are only 2 instances of tunnel=-1 and it doesn't mean anything (or is not known what it means).

It is also better to link directly to osm objects rather than a link to the map, where it remains unclear which objects you refer to.

**Comment by dieterdreist** [comment]
sent from a phone

> On 16 Dec 2016, at 19:54, Adrien Pavie <notifications@github.com> wrote:
> 
> Concerning paths with negative level value, maybe we can render them like tunnel (maybe even lighter or semi-transparent), with appropriate z-index showing that they are feature below other ones.


have a look:
https://wiki.openstreetmap.org/wiki/Key:layer
https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging

**Comment by daganzdaanda** [comment]
I am starting to believe we should drop rendering for POIs, buildings, and platforms with level<>0. 
This could help with clarity in badly crowded city centers. Of course, we would sacrifice information in other, uncrowded places. 

I am not sure if we should continue to render highway=* with a level other than 0. The presence of a level-tag on a highway suggests to me, that it's a well mapped place which will have highways on other levels as well. Showing all of these will be very hard to understand or [just a mess](http://www.openstreetmap.org/#map=19/52.52501/13.36910).

The level-tag is good enough to use it for this distinction. Level=0 is the ground floor, and would be the most sensible to show in a 2-D-map.

**Comment by kocio-pl** [comment]
I also think we should try rendering only points on the ground, however I would not touch tunnels under ground - they look different enough.

**Comment by kocio-pl** [comment]
Additional idea - what do you think about showing underground (and high overground) objects only on z19+?

**Comment by PanierAvide** [comment]
Could be a solution. Another one adopted by the osmfr rendering is to make them slightly transparent : https://github.com/cquest/osmfr-cartocss/blob/master/amenity-points.mss

**Comment by kocio-pl** [comment]
The more I think, the more I see that `location=underground` is the first thing to consider (as in #3162), because level is not clear enough - for example this might be lower than surrounding objects and open (or covered with just a roof). So probably I will drop the original idea of this ticket, but embrace `location=underground`instead. However I have not decided if it might be general switch for all the possible objects or just for some of them, this needs some testing.

**Comment by jeisenbe** [comment]
Per the [comments](https://github.com/gravitystorm/openstreetmap-carto/issues/1977#issuecomment-156813698) [above](https://github.com/gravitystorm/openstreetmap-carto/issues/1977#issuecomment-379134725) using `level=*` is not likely to be helpful. 

There is also discussion about using `location=underground` in several other places: see issues #552, #2720, #3018 and #3031 - so this issue can be closed.

**Comment by PanierAvide** [comment]
Well, `location=underground` is not something suitable for indoor tagging. Issue #3364 was really interesting in pushing forward a proper basic rendering for indoor features. But as now, this stylesheet is making places mapped indoor looking poorly due to no consideration of `level=*` tag. So for me this issue is closed, but the question is still there : how can we make OSM main map look a bit cleaner on highly-mapped indoor buildings ?
