### ISSUE TITLE
Guidepost and Map Icon

### ISSUE THREAD

**Issue by g4rpch** [gravitystorm/openstreetmap-carto#1978]
Dear All
From my point of view the icon of guidepost and maps could be improved, with something more clear, like:

guidepost: http://wiki.openstreetmap.org/w/images/9/91/Guidepost_doubleguidepost.png
map: http://arcgis.dnr.state.mn.us/ewr/whaf/Explore/img/basemap.png

links are only examples... but would be nice to have an icon more specific.

G4rp

**Comment by HolgerJeromin** [comment]
just for reference: you probably mean osm elements with `information=guidepost` and `information=map`

**Comment by kocio-pl** [comment]
[Another feature](https://github.com/gravitystorm/openstreetmap-carto/issues/1957) that should be handy in the outdoor, but in urban areas would make things worse if we use the uniform zoom level for both.

**Comment by math1985** [comment]
See also #304 and #324.

**Comment by Tomasz-W** [comment]
I don't like that all `information=*` tags are rendered the same, so I've tried to distinguish them:
* information=office
![information office](https://user-images.githubusercontent.com/25656654/36440631-4b7d5e40-1670-11e8-8fa6-ee8eac34f5a8.png)
* information=audioguide
![information audioguide](https://user-images.githubusercontent.com/25656654/36440636-5075d3f0-1670-11e8-8a92-80b23e5aebb0.png)
* information=guidepost
![information guidepost](https://user-images.githubusercontent.com/25656654/36441000-96de2166-1671-11e8-9b9f-bc0e9c29b443.png)
* information=map
![information map](https://user-images.githubusercontent.com/25656654/36441785-f203c288-1673-11e8-8c0e-7ddcde63eee0.png)
* information=board
![information board](https://user-images.githubusercontent.com/25656654/36441896-43bf3990-1674-11e8-830a-63c02a2e68d9.png)

For terminal, tactile_map and tactile_model I have no idea.

**Comment by geowas-github** [comment]
All 5 of them work good for me!

**Comment by Tomasz-W** [comment]
I got some ideas for 3 tags which I mentioned above. 
What about make board icon square instead of rectangle, and use it for terminals and tactile models? For tactile map I think we could use the same icon as for information=map.

**Comment by kocio-pl** [comment]
I can't imagine the outcome, would be good to just see it.

**Comment by Tomasz-W** [comment]
* information=board
![information board rectangle](https://user-images.githubusercontent.com/25656654/36448322-8a062ca2-1687-11e8-854c-5f9809517a0f.png) 
* information=terminal
![information board rectangle2](https://user-images.githubusercontent.com/25656654/36448407-d6edbe18-1687-11e8-8253-1911a2482fdc.png) 

What do you think?

**Comment by dieterdreist** [comment]
sent from a phone

> On 20. Feb 2018, at 21:54, kocio-pl <notifications@github.com> wrote:
> 
> Makes sense for me, however it would be good to make board with white background
> 


+1, actually transparent background, otherwise it’s too prominent compared to the other information icons. Often there a several boards close to each other

**Comment by Tomasz-W** [comment]
At the beginning, I've tried with white background. It made "i" character smaller, and icon not readable.

Gist links:
* information=office
https://gist.github.com/Tomasz-W/f0b0e88571fb956e21cf7121eabe85fd
* information=terminal
https://gist.github.com/Tomasz-W/02047f4f61aa6bf534c26c187ed6f248
* information=audioguide
https://gist.github.com/Tomasz-W/c1b01647b8979e88b14d3dee6fcb3138
* information=guidepost
https://gist.github.com/Tomasz-W/76bd709540f796d83eba9f9dd13780e7
* information=map,  information=tactile_map
https://gist.github.com/Tomasz-W/1e8f2e4a59069ddee99db53ac1a5c1dc
*  information=board,  information=tactile_model
https://gist.github.com/Tomasz-W/d6f962425fbc8ec05b54a696e7eaee66

**Comment by kocio-pl** [comment]
Maybe instead of "i" you could use just some horizontal "script", like here for example:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/plaque.svg

It may look similar to that icon:
https://github.com/gmgeo/osmic/blob/master/shop/computer-14.svg

**Comment by Tomasz-W** [comment]
* information=board
![information board skrypt](https://user-images.githubusercontent.com/25656654/36481563-8393da3e-1710-11e8-8064-1d78d439c966.png)
* information=terminal
![information terminal skrypt](https://user-images.githubusercontent.com/25656654/36481678-d8c57a6c-1710-11e8-959f-6a8056134364.png)

For me, it's not readable, and I would like to stay with "i" character in all of information=* icons. 
Any other thoughts?

**Comment by kocio-pl** [comment]
Sorry, I meant white board with dark script, just like the Osmic laptop icon. Plaque was interesting just to show that script can be irregular, not symmetric.

For the information terminal it was mainly OK for me wit "i" (with script it's less readable), but you might add for example wifi-like symbol to show that "Mostly it is combined with access to the internet" or some other attribute of electronic device (maybe just a cable or antenna?).

**Comment by Tomasz-W** [comment]
* information=board
![information board](https://user-images.githubusercontent.com/25656654/36485187-d490077c-171b-11e8-94cf-7d023ecdd51c.png) (i-version)
![information board skrypt](https://user-images.githubusercontent.com/25656654/36484717-79cd4e04-171a-11e8-875b-6b787dbe374d.png) (script-version)
* information=terminal
![information terminal](https://user-images.githubusercontent.com/25656654/36485204-e0072216-171b-11e8-83b1-ac3bae0dabbe.png) (i-version)
![information terminal skrypt](https://user-images.githubusercontent.com/25656654/36485390-67797d7a-171c-11e8-9d3f-1b985f064867.png) (script-version)

I still find "i-versions" more intuitive.

There is not enough space to add a hand and make a tactile one.

**Comment by kocio-pl** [comment]
I vote for script-version of board and i-version for terminal for now, but it has to be tested on rendering, of course.

**Comment by Tomasz-W** [comment]
Script-version of board icon added to Gist:   https://gist.github.com/Tomasz-W/d6f962425fbc8ec05b54a696e7eaee66

**Comment by kocio-pl** [comment]
Thanks! What about mouse cursor arrow instead of "i" in terminal?

**Comment by Tomasz-W** [comment]
I think it would look more like a public-computer (I don't know how it's called, but at some bus/ train stations there are computers with 1h access for a few coins)

**Comment by kocio-pl** [comment]
So there might be enough space to place it outside (terminal is thinner than board)?

**Comment by Tomasz-W** [comment]
![information terminal](https://user-images.githubusercontent.com/25656654/36487208-a6b77092-1720-11e8-869c-fe634fb497da.png)

For me, it's not readable. and unnecessarily complicated.

**Comment by daganzdaanda** [comment]
How about this:

board on transparent
![information-board-ow33](https://user-images.githubusercontent.com/7693297/36491917-3acbc232-172c-11e8-8cac-dfc0ad4465d9.png)

terminal on transparent
![information-terminal-ow](https://user-images.githubusercontent.com/7693297/36491916-3aac5d2a-172c-11e8-804b-015a3c614d0d.png)

I tweaked your idea and pixel-aligned the "i" so it is strong enough on a transparent background
[Gist](https://gist.github.com/daganzdaanda/d2fc51377dda67c543c4236683e50c2c)
One could even make the dot of the i a perfect square to have no blurriness at all.

**Comment by daganzdaanda** [comment]
Btw, for me the "i" is necessary because it is an well known symbol for tourists all over the world. The generic "script" is better used for things like memorials / plaques etc.

**Comment by Tomasz-W** [comment]
@daganzdaanda I'm not sure about readability of them. I'm worried that "i" is huddled too much.

**Comment by lakedistrictOSM** [comment]
The script versions are clearer for board and terminal but I'd prefer an icon with an "i". I like all of @Tomasz-W 's other designs too. Here's a few designs for board from me:

1 ![board01png](https://user-images.githubusercontent.com/20193716/37181419-d0355758-2324-11e8-8b20-63262f60cbb6.png) and 2 ![board02png](https://user-images.githubusercontent.com/20193716/37181428-da93333c-2324-11e8-9b41-b5fb133ddd04.png) - same as Thomasz's information=office icon, but with the circle replaced  by a square/rectangle 

3 ![board03png](https://user-images.githubusercontent.com/20193716/37181475-0d91fbba-2325-11e8-8677-cca5fe757f80.png) - pixel aligned "i" design

I'm unsure if the boards should have posts/legs (some boards will be on walls, for example).

**Comment by dieterdreist** [comment]
sent from a phone

> On 9. Mar 2018, at 00:14, lakedistrictOSM <notifications@github.com> wrote:
> 
> I'm unsure if the boards should have posts/legs (some boards will be on walls, for example).


for me it works better with legs

**Comment by lakedistrictOSM** [comment]
I think that a sans-serif "i" looks clearer than a serif "_i_" in a little icon. 1px border seems to work too.
B4 ![board04png](https://user-images.githubusercontent.com/20193716/37193616-99945fe4-2362-11e8-8d74-f357fe658a67.png)
B5 ![board05png](https://user-images.githubusercontent.com/20193716/37193637-ab372718-2362-11e8-92a8-a8a2b02cf8eb.png)

Terminals:
T1 ![terminal01png](https://user-images.githubusercontent.com/20193716/37193707-effa8e80-2362-11e8-904b-38d95195d819.png) - legs
T2 ![terminal02png](https://user-images.githubusercontent.com/20193716/37193713-f3a4b6a0-2362-11e8-97b5-d6f957e99604.png) - base/stand
T3![terminal03png](https://user-images.githubusercontent.com/20193716/37193720-f75c8836-2362-11e8-8b1f-ae379ea9c466.png) & T4 ![terminal04png](https://user-images.githubusercontent.com/20193716/37193722-fb5c4552-2362-11e8-80d2-386441a6aa3c.png) - with a "home button" to replicate a giant tablet/iPad

**Comment by dieterdreist** [comment]
2018-03-09 7:31 GMT+01:00 lakedistrictOSM <notifications@github.com>:

> I think that a sans-serif "i" looks clearer than a serif "*i*" in a
> little icon. 1px border seems to work too.
>

I'd argue for the opposite: information i-s are mostly serif i-s, although
you might occassionally find sings with sans-serif versions. The serif
makes it clear it is a character, while the sans-serif version bears the
risk of being misinterpreted (e.g. as a person).

**Comment by lakedistrictOSM** [comment]
The sans-serif idea was also to free up pixels to make the icon more readable, IMO. However B4, B5 and T1-T3 also work with a serif "i" if people prefer.

**Comment by kocio-pl** [comment]
I still think that if the board contains some text, it's probably the information.

**Comment by Tomasz-W** [comment]
My picks:

Board:
![1](https://user-images.githubusercontent.com/25656654/36485187-d490077c-171b-11e8-94cf-7d023ecdd51c.png) (Tomasz-W 'i-version')
or 
![2](https://user-images.githubusercontent.com/25656654/36484717-79cd4e04-171a-11e8-875b-6b787dbe374d.png) (Tomasz-W 'script-version')
 
Terminal:
![3](https://user-images.githubusercontent.com/20193716/37193713-f3a4b6a0-2362-11e8-97b5-d6f957e99604.png) (@lakedistrictOSM T2; I'm not sure about readability, maybe the edges should be thicker, but I like the idea)

**Comment by kocio-pl** [comment]
See also https://github.com/gravitystorm/openstreetmap-carto/issues/324#issuecomment-35800186 and #304.

**Comment by SomeoneElseOSM** [comment]
If anyone wants to borrow (or just get ideas from) the ones at http://map.atownsend.org.uk/maps/map/map.html#zoom=18&lat=-24.997805&lon=135.173656 be my guest.  Icons at e,g, https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/symbols/informationboard.png .  The principle is to keep the "i" but add another symbol to subdivide them.

**Comment by Tomasz-W** [comment]
Talking about zoom levels, my proposition after checking some city and mountain terrains:
* `information=office` -> z16 or z17
* `information=map; guidepost` -> z18
* all the rest (including `tourism=information `without `information=*` tag) -> z19


But firstly, we have to choose proper board and terminal icons. So again:

Board:
![1](https://user-images.githubusercontent.com/25656654/36485187-d490077c-171b-11e8-94cf-7d023ecdd51c.png) (Tomasz-W 'i-version')
![2](https://user-images.githubusercontent.com/25656654/36484717-79cd4e04-171a-11e8-875b-6b787dbe374d.png) (Tomasz-W 'script-version')

Terminal:
![3](https://user-images.githubusercontent.com/20193716/37193713-f3a4b6a0-2362-11e8-97b5-d6f957e99604.png) (@lakedistrictOSM T2)
![information terminal terminal](https://user-images.githubusercontent.com/25656654/37917335-722f3e64-311e-11e8-95c5-aa3c322f4ba6.png) (Tomasz-W)

**Comment by Tomasz-W** [comment]
@kocio-pl @dieterdreist @daganzdaanda @lakedistrictOSM @SomeoneElseOSM 
Can you choose which icons from https://github.com/gravitystorm/openstreetmap-carto/issues/1978#issuecomment-376216722 do you prefer?

**Comment by kocio-pl** [comment]
Board - 2
Terminal - 1

**Comment by dieterdreist** [comment]
sent from a phone

> On 27. Apr 2018, at 12:42, kocio-pl <notifications@github.com> wrote:
> 
> Board - 2
> Terminal - 1


I agree with kocio

**Comment by Tomasz-W** [comment]
Gist links after discussion:
* information=office
https://gist.github.com/Tomasz-W/f0b0e88571fb956e21cf7121eabe85fd
* information=terminal -> @lakedistrictOSM please upload clean SVG of your 'T2' design to Gist
* information=audioguide
https://gist.github.com/Tomasz-W/c1b01647b8979e88b14d3dee6fcb3138
* information=guidepost
https://gist.github.com/Tomasz-W/76bd709540f796d83eba9f9dd13780e7
* information=map, information=tactile_map
https://gist.github.com/Tomasz-W/1e8f2e4a59069ddee99db53ac1a5c1dc
* information=board, information=tactile_model
https://gist.github.com/Tomasz-W/d6f962425fbc8ec05b54a696e7eaee66 (we chose a "script' one)

**Comment by Tomasz-W** [comment]
@lakedistrictOSM Can you upload clean SVG of your "T2" design to Gist? A PR is waiting ;)

**Comment by lakedistrictOSM** [comment]
@Tomasz-W It might be quicker if maybe you could try recreating it? It looks like it's 14px tall, 8px wide, frame width is 1px (base is ~3px), i is 2px thick. All pixel aligned. (I don't have access to it at the moment) :)
