### ISSUE TITLE
Not rendering shops with multiple tags

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1979]
Example: https://www.openstreetmap.org/node/3677098726
https://www.openstreetmap.org/node/3841790026
https://www.openstreetmap.org/node/3841790025
https://www.openstreetmap.org/node/3841790014

At least show it with a dot and the name. Best would be to pick first tag for icon.
This is going to be an issue on many shops around here as they never quite fit into one category.

**Comment by matkoniecz** [comment]
Note that it is highly controversial whatever such tagging is correct (there were numerous threads about this on @tagging).

**Comment by matkoniecz** [comment]
In my view multiple values in one tag for shop key are no more correct than multiple values for surface, landuse, highway, amenity or railway tags.

I know that some objects may be hard to tag due to real-world complexity but I think that lists in keys is not a real solution and propose to reject this proposal.

 > Best would be to pick first tag for icon.

This would be terribly confusing, selecting random one would not make situation clear to neither mapper nor map user.

**Comment by HolgerJeromin** [comment]
See for example this blog: http://blog.jochentopf.com/2013-09-23-semicolons-in-osm-tags.html

**Comment by dieterdreist** [comment]
2015-11-18 8:45 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> I know that some objects may be hard to tag due to real-world complexity
> but I think that lists in keys is not a real solution and propose to reject
> this proposal.
>
> Best would be to pick first tag for icon.
>
>

I agree with the rejection. The examples are not sensible tagging. In this
example: https://www.openstreetmap.org/node/3677098726 "kiosk" is a
building type, not a shop (IMHO, but it is not the only problem).

**Comment by Gazer75** [comment]
So what do I call a shop selling candy, soda, ice cream, tobacco, lottery tickets, magazines and even simple fast food like hot dogs? That is a kiosk here in Norway. We have many of those. Two big ones I can remember right now is Narvesen and Mix.

Problem is that neither of the tags available for shop fully describe the stores.

The music store is not only selling intruments, but other hifi equipment.

**Comment by matkoniecz** [comment]
> So what do I call a shop selling candy, soda, ice cream, tobacco, lottery tickets, magazines and even simple fast food like hot dogs?

That is a question for tagging mailing list, wiki or some regional forum. This issue tracker should not be used to invent a new tagging.

> Rejecting this will mean that a ton of stores around the world will be not be visible.

It affects 0.1% of shops - or to be more exact 2344 of 1857852 shops (see https://gist.github.com/matkoniecz/8b930d6779c57c1a70e8).

Note also that it applies only to shop tagged in style that may be described at best as "highly controversial".

**Comment by Gazer75** [comment]
But would not a simple unknown dot with the name at least be acceptable? It would help until proper way to tag is agreed upon.

**Comment by moliha** [comment]
I agree with Gazer75 that a default shop-dot and the name should be shown if the shop-tagging is useless.
Making the shop invisible is not a solution.

**Comment by matkoniecz** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md#the-mapper-feedback-loop

Displaying these shops would imply that this tagging method is OK.

**Comment by moliha** [comment]
As the github article explains, feedback from map to mapper is important - but generally, wrong tagging should not be displayed as ok. 

So, in this case, where the shop tagging may be bad, there is no good solution.
- Making bad tagging look ok is bad.
- Not showing anything is worse.

For this and similar node-tagging problems, I suggest the following solution:

Create an error-icon. This could be a circle with a slash?

If the tag is bad, show the error-icon.
Always show the name.

This would solve both problems
- Bad tagging is flagged as not ok
- Node is shown with icon and name.

An error-way could be drawn with short slashes /////

An error-area could have a perimeter drawn with error-///.

**Comment by Edward17** [comment]
Hi there,

@Gazer75 , please remove two first links from examples because they don't contain `;` already.

_@Gazer75 wrote:_
>  Best would be to pick first tag for icon.

+1000.

_@Gazer75 wrote:_
> If using semicolon is not acceptable then I would have to create one node for each type of shop tag that fit the store and put the name on it. Is that a better solution you think?

Please don't do. This is very bad solution. See https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element

_@Gazer75 wrote:_
> But would not a simple unknown dot with the name at least be acceptable? It would help until proper way to tag is agreed upon.

If rendering of icon for first value is not possible, then +1.

_@moliha wrote:_
> Making the shop invisible is not a solution.

+1.

_@moliha wrote:_
> If the tag is bad, show the error-icon.
> An error-way could be drawn with short slashes /////
> An error-area could have a perimeter drawn with error-///.

First, "main map layer" isn't a validator, so it shold not highlight the objects with wrong tagging. Second, multiple values in `shop=*` tag isn't wrong tagging.

If you can German, you can read my post on this subject on forum: http://forum.openstreetmap.org/viewtopic.php?pid=560821#p560821 and generally this topic: http://forum.openstreetmap.org/viewtopic.php?id=52421 Otherwise you can use of cource Google Translate.

**Comment by neiljp** [comment]
I don't really see how multiple tags (really, multiple values?) are any different from individual tags which are unclear, unsupported, or not understood by the renderer, which are effectively degraded to shop=yes, right? On that basis, +1 to showing dot (+name if it's present).

**Comment by matkoniecz** [comment]
@gravitystorm @pnorman @math1985 

Do you have any opinion on this topic? My understanding of this topic is that putting multiple values into shop key (shop=butcher;florists) is rare, not standard, controversial and I would recommend rejecting this proposal.

**Comment by kocio-pl** [comment]
The problem of multi values is not resolved at the database/tagging scheme level yet and for now I also think it's fragile. We can only fix it case by case which icon gets rendered.

**Comment by math1985** [comment]
> Do you have any opinion on this topic? My understanding of this topic is that putting multiple values into shop key (shop=butcher;florists) is rare, not standard, controversial and I would recommend rejecting this proposal.


+1
