### ISSUE TITLE
Highway tags are propagated from a containing relation

### ISSUE THREAD

**Issue by Zverik** [gravitystorm/openstreetmap-carto#1980]
See http://www.openstreetmap.org/way/299404315#map=13/42.4342/130.6547
The trunk road actually has highway=unclassified, tertiary and secondary.
But on the tiles all segments are painted like a trunk road, because the route relation has highway=trunk.
Note the different-coloured shields and names.

**Comment by matkoniecz** [comment]
I would say that it is a data issue - road is tagged as unclassified and trunk at the same time, so...

Also, behaviour like this would be obvious consequence of #596

**Comment by matkoniecz** [comment]
It seems to be a purely data problem - highway tag seems to be not supposed to appear on this relation, see http://wiki.openstreetmap.org/wiki/Relation:route

**Comment by math1985** [comment]
+1

**Comment by dieterdreist** [comment]
2015-11-20 13:52 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> I would say that it is a data issue - road is tagged as unclassified and
> trunk at the same time, so...



I don't agree that the road is tagged as both, the road is tagged as
unclassified, but there is a route relation with a suspicious highway tag
in it. The latter should be ignored. That's a route relation, not a road
relation.

**Comment by matkoniecz** [comment]
I am considering unnecessary to add special code useful only to improve display of invalid data.

**Comment by pnorman** [comment]
> Also, similar behaviour would be obvious consequence of #596

That is unrelated, as it's about ref tags.

Duplicate of #302
