### ISSUE TITLE
Add rendering for healthcare=* tags

### ISSUE THREAD

**Issue by morray** [gravitystorm/openstreetmap-carto#1981]
Although the healthcare= tags is still only at about 10% usage of amenity=doctors, it is wothwhile to include it. One advantage is that via the healthcare:speciality=* and healthcare:speciality:*=yes tags can add further information missing in the amenity tagging.

**Comment by matkoniecz** [comment]
Please, be more precise - which tags you propose to display?

See also https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md#the-mapper-feedback-loop

**Comment by morray** [comment]
Hi matkoniecz,

as a start I think 
tags | occurrences 
healthcare=doctor |  4158
healthcare=dentist | 849
healthcare=centre | 654
healthcare=clinic | 459
should be rendered using the same icons as the corresponding amenity tags

additionally 
healthcare=physiotherapist | 1057
healthcare=alternative | 664
might be interesting because of their frequency for dedicated symbols. The rest healthcare=* should get a generic icon

Concerning the specialities: 
healthcare:speciality=general
healthcare:speciality:general =yes
----
healthcare:speciality=ophthalmology		
healthcare:speciality:ophthalmology = yes
----
healthcare:speciality=gynaecology
healthcare:speciality:gynaecology = yes
----	
healthcare:speciality=internal
healthcare:speciality:internal = yes
----
healthcare:speciality = orthopaedics
healthcare:speciality:orthopaedics =yes
----
healthcare:speciality = otolaryngology	
healthcare:speciality:otolaryngology = yes
---
healthcare:speciality = paediatrics
healthcare:speciality:paediatrics = yes

should add a detail to the doctor symbol.

**Comment by matkoniecz** [comment]
And which ones would not be covered by already rendered amenity=doctors, amenity=dentist etc?

**Comment by matkoniecz** [comment]
> should add a detail to the doctor symbol.

I consider it highly dubious that it is possible to find icon that would have a clear meaning, would not result in confusion and be readable (14x14 px, single color).

**Comment by morray** [comment]
Of course these are covered by amenity=doctor and dentist now. But especially for the doctor healthcare is much cleaner, since it puts the type of doctor in the speciality tag. And the detail could be as big as the icon as now done for the dentist.

**Comment by matkoniecz** [comment]
> Of course these are covered by amenity=doctor and dentist now.

In that situation I see no reason for rendering healthcare=* tags. At this moment any properly tagged place will contain amenity=doctors/dentist and maybe some healthcare=* tags.

Maybe in future healthcare=* will be used more widely and in the far future it will replace amenity=doctor/dentist but I see no reason for changes now.

**Comment by polarbearing** [comment]
I didn't comprehend yet what @morray was proposing. If you say a healthcare=doctor should be rendered even in absence of an amenity tag (@matkoniecz calling the future case), than it would need to be evaluated how much it is needed, since this would encourage to move away from the amenity tagging.
If you propose to render different icons for different doctor's specialities, than I'd say that is too much for the general map, and a case of a healthcare-specific overlay.

**Comment by morray** [comment]
@polarbearing: exactly that. The tag should be rendered even in absence of the amenity tag. And yes that probably will lead to the healthcare tag being used more frequently. And yes it probably also leads to a switch on the long term ( if presets are adapted as well) since healthcare is much more intuitive than amenity.

**Comment by polarbearing** [comment]
Understood. Anyway since @matkoniecz already added the 3.x label, this depends on the database upgrade, since the healthcare=* key is currently not imported.

**Comment by mboeringa** [comment]
@morray,

I think there first needs to be some of agreement, and possibly emergency Wiki clean up, to deal with the fact that there are now two healthcare related proposals:

**Key:healthcare**
http://wiki.openstreetmap.org/wiki/Key:healthcare

and

**Proposed features/Healthcare 2.0**
http://wiki.openstreetmap.org/wiki/Proposed_features/Healthcare_2.0

Actually, the Healthcare 2.0 proposal, which seems more in line with the HOT tagging, does away with most of the direct use of **healthcare=x** in the original proposal, favouring **health_x:type=x**, which is a fundamental different tagging scheme.

Actually, there are now *at least* 4 different ways to tag a hospital ;-(:

**building=hospital**
**amenity=hospital** (& possibly building=yes/no)
**healthcare=hospital** (& possibly building=yes/no)
**health_facility:type=hospital** (& possibly building=yes/no)

**Comment by matkoniecz** [comment]
Closing for reason explained in https://github.com/gravitystorm/openstreetmap-carto/issues/1981#issuecomment-158542184
