### ISSUE TITLE
Zoom level for hamlet

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#1984]
I know this has been rejected before, but I feel this needs to be looked at again.

Currenty the zoom levels and name display is making Norway look rather uninhabited. Seems wrong to have to call small settlements of less than 250 people a village instead of a hamlet. And we got a lot of them in a country which recently passed 5 million people :)

At least move hamlets out one level please. Currently it is showing at 15 and that is the same as locality, farm and neighborhood. I would think a hamlet is more important to show than these? It is supposed to be the name of a larger area than a farm.

I see a lot of places tagged as village that should have been a hamlet because of this.

**Comment by imagico** [comment]
Moving the threshold for hamlets from 15 to 14 could work, needs testing though.  There are right now very few low latitude areas mapped in rural areas to a similar density as central Europe.

The general problem of proper display of settlements in areas of different density will not be solved by this though.  The incentive for tagging for the renderer will remain as illustrated by cases like:

http://www.openstreetmap.org/node/1249339989
http://www.openstreetmap.org/node/515065315
http://www.openstreetmap.org/node/3740127665

**Comment by Gazer75** [comment]
Noticed doing a search with Overpass Turbo that there are a lot of hamlets that should have been set as farms in Norway. Currently almost 3k nodes with hamlet.

**Comment by Gazer75** [comment]
Would also suggest giving hamlets a slightly bigger font size to set it apart from locality and farm. Something in the middle of village and the current size.

**Comment by math1985** [comment]
Interesting blog related to this subject: http://www.justinobeirne.com/essay/what-happened-to-google-maps

**Comment by matkoniecz** [comment]
> Interesting blog related to this subject: http://www.justinobeirne.com/essay/what-happened-to-google-maps

Thanks, this was a really interesting article (though unlike author of this blog I think that labels are better after the change - though maybe the change went too far).

**Comment by NKAmapper** [comment]
I am supporting this proposal. A hamlet is supposed to be bigger than an individual farm or dwelling. (Same logic for neighborhood also.)

In sparsely populated northern countries most settlements will be village or hamlet, so at zoom levels <15 the entire map looks empty.

**Comment by kocio-pl** [comment]
Could you make some tests in different parts of the world?

**Comment by NKAmapper** [comment]
Testing rendering at 14? Would be happy to contribute but I have no idea how to do that...
I have just looked at various densely populated parts of Europe, and 14 seems to be possible.

**Comment by kocio-pl** [comment]
@rrzefox Would you be interested in applying this code change on your server?

This means just adding z15+ rules to all the other small placenemes and changing general zoom to z14+:
https://github.com/gravitystorm/openstreetmap-carto/blob/9f1b09feb4a8a57e50a8552e0d1fd3c5e7bd6a8c/placenames.mss#L372-L378

**Comment by rrzefox** [comment]
I have attempted to do this, but am not sure if I got it right (a PR from which I could have pulled the patch would have been helpful).
```diff
--- a/placenames.mss
+++ b/placenames.mss
@@ -368,11 +368,31 @@
     }
   }
 }

 #placenames-small::hamlet {
-  [place = 'hamlet'],
+  [place = 'hamlet'] {
+    [zoom >= 14] {
+      text-name: "[name]";
+      text-size: 10;
+      text-fill: @placenames;
+      text-face-name: @book-fonts;
+      text-halo-fill: @standard-halo-fill;
+      text-halo-radius: @standard-halo-radius * 1.5;
+      text-wrap-width: 45; // 4.5 em
+      text-line-spacing: -0.8; // -0.08 em
+      text-margin: 7.0; // 0.7 em
+    }
+    [zoom >= 16] {
+      text-size: 12;
+      text-wrap-width: 60; // 5.0 em
+      text-line-spacing: -0.60; // -0.05 em
+      text-margin: 8.4; // 0.7 em
+      text-fill: @placenames-light;
+      text-halo-fill: white;
+    }
+  }
   [place = 'locality'],
   [place = 'neighbourhood'],
   [place = 'isolated_dwelling'],
   [place = 'farm'] {
     [zoom >= 15] {
```
It does show different rendering, e.g. at
https://osm.rrze.fau.de/compare-osmfau-osmorg.html#zoom=14&lat=64.31564&lon=10.48396
Warning: Not all files have rerendered yet (this line will be removed once they have).

**Comment by Gazer75** [comment]
I've looked at other places with a lot more hamlets and other tags and it looks good to me.
https://osm.rrze.fau.de/compare-osmfau-osmorg.html#zoom=14&lat=58.09863&lon=6.9225

Use this one to find areas with hamlets in Norway: http://overpass-turbo.eu/s/xRl

**Comment by kocio-pl** [comment]
Are there some places where the hamlets could be potentially harmful, probably near some other, more important placenames? That would make perfect testing case.

**Comment by Gazer75** [comment]
Is there no way to override it so that names for larger places get priority?

Found this area in France:
https://osm.rrze.fau.de/compare-osmfau-osmorg.html#zoom=14&lat=48.00344&lon=2.96545
That look pretty good to me. It look much more alive.

**Comment by NKAmapper** [comment]
Thank you for providing the test rendering.

I have checked many different areas now, in South and Central Europe as well as in Asia and America, and I have not been able to discover any rendering conflicts, including from place=village. By definition place=hamlet is a rural concept, so we are not getting into the problematic areas of 
cities and suburbs.

The proposed rendering at z=14 works particularly well in hilly areas where perhaps no other place names would be rendered at this zoom, such as in this example from Italy:
https://osm.rrze.fau.de/compare-osmfau-osmorg.html#zoom=14&lat=44.08169&lon=10.9041
(Very few areas become as busy with hamlets as in this example.)

This change improved rendering in the North (Scandinavia, Northern Canada, Russia etc), but only a bit. I think perhaps the projection is the problem: One meter on the ground in Oslo or Tromsø is represented with a distance on the map which is 2-3 times longer than one meter in Italy.

Would you be interested in testing also place=neighbourhood at z=14? As with hamlets, neighbourhoods are supposed to represent bigger settlements than individual farms or dwellings. They are found in urban areas, though, so there could be more conflicts.

**Comment by kocio-pl** [comment]
I wouldn't try to change place=neighbourhood, but of course somebody could make some tests in urban environments. Hamlets however are OK for me. We don't have to change rendering priorities, because on this level we already know which larger place we're in. The test rendering looks proper.

Who is gonna to prepare hamlet code PR? It should be probably something like (but it should be tested of course):

```css
   [place = 'hamlet'][zoom >= 14], 
   [place = 'locality'][zoom >= 15], 
   [place = 'neighbourhood'][zoom >= 15], 
   [place = 'isolated_dwelling'][zoom >= 15], 
   [place = 'farm'][zoom >= 15] { 
[zoom >= 14] { 
```

**Comment by Gazer75** [comment]
Still think the text size could be increased to 11...

**Comment by kocio-pl** [comment]
OK, so please test it and show us the comparison.

**Comment by NKAmapper** [comment]
It would be great to have this issue concluded. I believe testing text size is missing. The rendering of place=quarter seems to be fitting quite well, perhaps that code could be reused for hamlet. I am unfortunately not capable of making the PR or technical testing (I have no idea what the various settings are doing).

@rrzefox Would you be interested in including place=hamlet in the place=quarter code on your server? I could then provide some test examples.

**Comment by NKAmapper** [comment]
Thank you! Seems good to me.

**Comment by jidanni** [comment]
It seems for [this particular hamlet](https://www.openstreetmap.org/node/2801169921#map=19/24.34810/120.76896) not rendering at zoom levels 18 and 19 does more harm than good.
