### ISSUE TITLE
Render conveyor belts (man_made=goods_conveyor)

### ISSUE THREAD

**Issue by kopiersperre** [gravitystorm/openstreetmap-carto#1999]
man_made=goods_conveyor is used [nearly 1000 times](http://taginfo.openstreetmap.org/tags/?key=man_made&value=goods_conveyor). Conveyor belts are relevant for bulk materials (coal, iron ore, copper ore, lime, wheat, corn) at open-pit mines, port terminals and industrial plants.

As alternative sometimes railway=monorail is used (example: [http://www.openstreetmap.org/relation/62366#map=14/51.3573/10.5061](http://www.openstreetmap.org/relation/62366#map=14/51.3573/10.5061)) which then could be abandoned.

**Comment by pnorman** [comment]
We don't have much industrial or port infrastructure rendered. Do we want to? If we do, is this the best place to start?

**Comment by imagico** [comment]
Considering how many variants of this kind of feature exist having a clear wiki page would be important.

I am also not sure if it makes sense to render this and not man_made=pipeline - see #640

**Comment by mboeringa** [comment]
> As alternative sometimes railway=monorail is used (example: http://www.openstreetmap.org/relation/62366#map=14/51.3573/10.5061) which then could be abandoned.

I have also seen them mis-tagged as **aerialway=x**

**Comment by dieterdreist** [comment]
sent from a phone

> Am 08.12.2015 um 19:39 schrieb Christoph Hormann <notifications@github.com>:
> 
> I am also not sure if it makes sense to render this and not man_made=pipeline


I'm sure we should render both, particularly the large conveying structures on open pit mining sites (if they are mapped with this tag)

**Comment by kopiersperre** [comment]
@mboeringa May you give me an exmple for aerialway=x?

**Comment by mboeringa** [comment]
> @mboeringa May you give me an example for aerialway=x?

@kopiersperre, here is what I think is a classical example of this kind of mis-tagging:

https://www.openstreetmap.org/#map=17/50.09801/8.65217

Clearly this feature in the middle of an industrial power station must be (also looking at the aerial in ID) a conveyor belt, no aerialway makes this kind of abrupt direction changes.

Of course, with the **man_made=goods_conveyor** not being included on the main **man_made=x** Wiki page (http://wiki.openstreetmap.org/wiki/Key:man_made), but only on a less accessible proposal page (http://wiki.openstreetmap.org/wiki/Proposed_features/Goods_conveyor), the chances of mis-tagging are bigger.

**Comment by pnorman** [comment]
I like the idea of rendering more industrial features, an feature space where we don't do much and there's normally room on the map. But the tagging needs more consistency, better documentation, and wider usage. It may also be best to start with other industrial features like man_made=pipeline.

**Comment by turnsole80** [comment]
Is there any thoughts on re-looking at this issue? Rendering industrial objects could be quite handy

**Comment by kocio-pl** [comment]
I'm not aware of any. It's probably most probable if you take care of it.

**Comment by turnsole80** [comment]
I can do that :)

I want to clean up some of the tagging first. But this is a good an issue as any for me to cut my teeth on

**Comment by kocio-pl** [comment]
Cool, so I reopen the issue. I'm not sure that such design is the easiest - we have special tags for what we think is good for novice osm-carto developers, but it's always better to do what really interests you.

**Comment by pnorman** [comment]
> We don't have much industrial or port infrastructure rendered. Do we want to? If we do, is this the best place to start?

I think the answer to this being the place to start is no. It makes no sense to render this in isolation.

**Comment by EwenH** [comment]
Take a look at this long [conveyor belt](https://www.openstreetmap.org/edit#map=16/-32.6520/116.0005)  in  Western Australia. This belt extends the bicycle route by over 10km however you wouldn't know about why the diversion is in place if you are looking at OSM.  Having the conveyor belt rendered explains why the railway exists, why the industrial is next to the railway line and how the ore is shipped. We are not telling the full story otherwise.

**Comment by jeisenbe** [comment]
Used >4200 times, added to Key:man_made and Map Features as "de facto" after discussion on the Tagging list. 

There is an open PR (#4070) to render `man_made=pipeline` features, which was considered a prerequisite. 

If that PR is approved, we might consider rendering goods_conveyor, if someone can develop an intuitive rendering which can be understood next to aerialways, railways, pipelines etc -

Are there any examples of digital or print maps which show this feature?

**Comment by jragusa** [comment]
Why not a similar pattern than `aerialway=goods` with closer rectangles

**Comment by jeisenbe** [comment]
That might work, but it would need to be clearly different than other aerialways.

**Comment by jragusa** [comment]
Starting point:
https://www.openstreetmap.org/way/627540810 at z18
`dash/line-dasharray: 6,6;`
![conveyor6-6_z18](https://user-images.githubusercontent.com/9897203/76628759-8a8b0b00-653d-11ea-9c16-c792b8ff1f0f.png)
`dash/line-dasharray: 24,6;`
![conveyor24-6_z18](https://user-images.githubusercontent.com/9897203/76629536-b35fd000-653e-11ea-8509-a4dc0a13f4c0.png)
`dash/line-dasharray: 24,25;`
![conveyor24-25_z18](https://user-images.githubusercontent.com/9897203/76628909-cc1bb600-653d-11ea-8e4d-ed0c41ab2568.png)

`aerialway=goods` pattern for comparison
https://www.openstreetmap.org/way/191254475
![goods_z15](https://user-images.githubusercontent.com/9897203/76630140-c7f09800-653f-11ea-8097-8297977246e9.png)

**Comment by jeisenbe** [comment]
dash/line-dasharray: 6,6 is the best of those 3, but the color is a bit strong. Is it `#707070`?

Aerialways are dark gray because they are transportation features which are open to the public, but this is an industrial feature.

Try `#808080` or `#99999` perhaps?

**Comment by jragusa** [comment]
Yes it's the `#707070` but actually the correct value displayed above is `line-dasharray: 12,6`, my apologies.

`line-dasharray: 6,6`
![conveyor6-6_z18](https://user-images.githubusercontent.com/9897203/77188224-efaea580-6ad5-11ea-960a-e66cbdcefddf.png)

`line-dasharray: 12,6` + `#808080`
![conveyor12-6_z18_colour2](https://user-images.githubusercontent.com/9897203/77188269-fe955800-6ad5-11ea-9b1a-3af92dbc8fa7.png)

`line-dasharray: 12,6` + `#999999`
![conveyor12-6_z18_colour3](https://user-images.githubusercontent.com/9897203/77188307-110f9180-6ad6-11ea-94c4-3362153cb247.png)

**Comment by jeisenbe** [comment]
`#999999` seems to be an improvement. It will need testing next to other features with a similar color, like service railways for example.

`line-dasharray: 12,6` appears to work, but feel free to try some other variants.

**Comment by jragusa** [comment]
`line-dasharray: 12,6` + `#999999` along service railways
https://www.openstreetmap.org/way/163719137
https://www.openstreetmap.org/way/163719136
https://www.openstreetmap.org/way/163719139
https://www.openstreetmap.org/way/163719140
![conveyor3_z17](https://user-images.githubusercontent.com/9897203/77222646-6b036c00-6b55-11ea-8034-f9397664b7e1.png)

> feel free to try some other variants

The four patterns showed above are the main alternatives to get a distinct pattern than those of `aerialway=goods`. Then we can adjust finely `line-dasharray` if neccessary.

**Comment by jeisenbe** [comment]
I would recommend opening a "draft" PR and working more on it there
