### ISSUE TITLE
Oneway arrows prevent display of long street names

### ISSUE THREAD

**Issue by pbb72** [gravitystorm/openstreetmap-carto#2006]
Long street names (by the looks of it, over 20 characters long) are not displayed on oneway streets. This is especially troublesome in bilingual areas where the name in both languages is used.

See for example http://www.openstreetmap.org/way/22575474:
![clipboard image 13](https://cloud.githubusercontent.com/assets/1436366/11730316/854b6edc-9f94-11e5-8c87-6db2f4655805.jpg)

**Comment by math1985** [comment]
I can confirm this issue as well.

Are there any places where it occurs i monolingual areas as well?

**Comment by pbb72** [comment]
Ok, it looks like the limit is a bit longer than 20 characters:
![clipboard image 15](https://cloud.githubusercontent.com/assets/1436366/11731877/2624849c-9f9f-11e5-8fb4-b255e15ba991.jpg)

**Comment by pbb72** [comment]
Here is one example where the label is not shown on zoom 19, though it is on lower zooms: http://www.openstreetmap.org/way/7371850
![clipboard image 17](https://cloud.githubusercontent.com/assets/1436366/11731985/155d877a-9fa0-11e5-995c-4c17a708d128.jpg)

**Comment by kdudzik** [comment]
In my opinion it's one of the most irritating bugs, making the map useless in some areas. Street names belong to the most important names, they are essential for navigation and orientation.
Another example would be [this bridge in Warsaw](http://www.openstreetmap.org/#map=15/52.3061/20.9508): the names of the bridge (except man_made=bridge) and some adjacent roads are not visible on any zoom level:
![most](https://cloud.githubusercontent.com/assets/170668/18057524/b0013206-6e10-11e6-8270-f6e9dfca46b4.PNG)
Mostly, the problem occurs on roads with separated directions like motorways - these are the most important roads and always one-way.
It should be quite simple to correct - either by lowering the arrows' priority or by enlarging the space between them.

**Comment by StyXman** [comment]
In fact i think the proper solution is to render arrows later. In my personal fork I shortened the distance between arrows (so they show earlier, important to me for driving around in unknown places) and in one way streets I get no names at all:

![one_way_too_many_arrows](https://cloud.githubusercontent.com/assets/167327/18059345/d89f4c04-6e18-11e6-9893-a4a946948fab.png)

I will try to tackle this problem this week, make a PR.

**Comment by math1985** [comment]
The question is, what is more important, the arrows or the names?

Would it be possible to avoid this problem somehow by making the arrows part of the name in the rendering?

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 29 ago 2016, alle ore 18:46, Marcos Dione <notifications@github.com> ha scritto:
> 
> In fact i think the proper solution is to render arrows later.


I would render them before, and render the name over them (because of the halo the names will still be visible)

**Comment by nebulon42** [comment]
> It should be quite simple to correct - either by lowering the arrows' priority or by enlarging the space between them.

Pull Requests are quite welcome!

**Comment by pbb72** [comment]
I think the arrows are most important, but there are many examples where names could easily have been displayed where instead several arrows are displayed on one street.

If it's a short street that doesn't have space for both an arrow and the name, then only an arrow should be shown.

If it's a long street where there is enough space for at least one arrow in addition to the name, then both should be shown.

Currently you can have very long one-way streets that don't display a name because there are too many arrows.

**Comment by StyXman** [comment]
Well, België/Belgique/Belgien has a terrible problem, not only very long street names, but also in 2/3 languages. 

In any case, I just finished moving one way arrow rendering from the `tunnels`, `roads-fill` and `bridges` layers to the `roads-text-name` layer, and it looks slightly better. It even *mostly* fits with what @pbb72 wants, because if the name doesn't fit, then only arrows are rendered. Of course, there is still a *probability* that only the name will fit.

The question is: is this move correct? Was there any particular reason to put one way arrow rendering in those layers? I'll clean up and post a PR in the afternoon.

**Comment by StyXman** [comment]
PR sent, now the classical before/after images :)

z15 - included to show some pre-existing rendering diffreneces -- it seems that my fonts are different (this is a Debian Sid setup), and I have a slightly outdated database (not enough free space to keep an updatable db, sorry). Also, no bicycle or horse info.

![one_way_too_many_arrows-orig-z15](https://cloud.githubusercontent.com/assets/167327/18127866/3e6e5334-6f83-11e6-85d0-6ae25ba0ac7f.png) | 
![one_way_too_many_arrows-new-z15](https://cloud.githubusercontent.com/assets/167327/18127874/5056ef16-6f83-11e6-8db6-a164500b64ae.png)

z16  - No bicycle info means no one way arrows in the cycleways to the sides of the tertiary at center right. At least one new name “Rue Saint-Vincent/Sint Vincentiusstraat".

![one_way_too_many_arrows-orig-z16](https://cloud.githubusercontent.com/assets/167327/18128033/17c39da6-6f84-11e6-8bfa-fec2f94db6c9.png) | 
![one_way_too_many_arrows-new-z16](https://cloud.githubusercontent.com/assets/167327/18128048/2404ad80-6f84-11e6-8d44-86bc99cd1823.png)

z17 - Two more: “Rustplaatslaan” and “Van Cutsem”.

![one_way_too_many_arrows-orig-z17](https://cloud.githubusercontent.com/assets/167327/18128112/7f4d78e8-6f84-11e6-8e5f-ca1c8ae9020e.png) | 
![one_way_too_many_arrows-new-z17](https://cloud.githubusercontent.com/assets/167327/18128154/b0c14274-6f84-11e6-8c7d-19af9c51293f.png)

z18 - Last one. Even “Dekoster" renders names and arrows.

![one_way_too_many_arrows-orig-z18](https://cloud.githubusercontent.com/assets/167327/18128189/df98b1f4-6f84-11e6-97a6-9644cc9ae664.png) | 
![one_way_too_many_arrows-new-z18](https://cloud.githubusercontent.com/assets/167327/18128193/e777c27a-6f84-11e6-99c8-cd034fa31c3d.png)

**Comment by pbb72** [comment]
Looks great to me! :)

**Comment by StyXman** [comment]
As a comparison with my previous sshot:

![one_way_too_many_arrows](https://cloud.githubusercontent.com/assets/167327/18059345/d89f4c04-6e18-11e6-9893-a4a946948fab.png) vs 
![one_way_too_many_arrows-new](https://cloud.githubusercontent.com/assets/167327/18129513/58a79190-6f8b-11e6-82ae-ed2b9ecb83f9.png)

**Comment by pnorman** [comment]
Just for reference, our arrows used to be made with dasharrays until #1840. Conflicts with names wasn't brought up at the time.

**Comment by dieterdreist** [comment]
2016-09-02 10:32 GMT+02:00 Paul Norman <notifications@github.com>:

> Just for reference, our arrows used to be made with dasharrays until #1840
> <https://github.com/gravitystorm/openstreetmap-carto/pull/1840>.
> Conflicts with names wasn't brought up at the time.
>

+1, because overlap was possible. The overlap should be reenabled with the
new way of drawing arrows, rather than trying to tweak the arrow distances
or similar "tricks" to slightly improve a broken concept.
