### ISSUE TITLE
Turn Restriction Fields Cannot be Completed

### ISSUE THREAD

**Issue by PaulColinSimpson** [gravitystorm/openstreetmap-carto#2009]
At Node: 177731407 there is a Turn Right restriction going from residential road Fourth Avenue onto teritiary road Dagenham Road. When inputting the From: To: details of the turn restriction the To: section will not highlight Dagenham Road as an option. Instead it will provide Fourth Avenue as an option which is in fact the road the restriction is From. For now I have left the To: field blank.
![turn restriction](https://cloud.githubusercontent.com/assets/9841560/11955419/164439ca-a8b2-11e5-8e84-98d740fb8fa2.JPG)

**Comment by pnorman** [comment]
This is the issue tracker for the stylesheet powering the "Standard" layer on osm.org. What you describe is an issue with editor software.
