### ISSUE TITLE
Village names should be to one side of boundaries, not right on top of them!

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#2010]
Based on
https://www.facebook.com/groups/OpenStreetMap.TW/permalink/969547683110701/
https://github.com/Leaflet/Leaflet/issues/4119
we feel (wild guess, no real idea actually) that your project is at fault for putting village
names directly on top of boundaries on
http://opencellid.org/#zoom=17&lat=24.208964&lon=120.74594

**Comment by yohanboniface** [comment]
My bad, tiles come from http://tile.enaikoon.de/osm/17/109497/56445.png not here. Sorry.

**Comment by jidanni** [comment]
1. That tile doesn't have the boundary;
2. Is some website using some outdated CSS that causes the name to appear right on the boundary?
Thus I should tell some website to update the package that contains the CSS?
Or how can I check that the current version of that CSS upstream doesn't still have the bug, and I should report it upstream where?

**Comment by yohanboniface** [comment]
Just contact people from Enaikoon.de.

**Comment by matkoniecz** [comment]
(1) This rendering is not using this map style - see http://www.openstreetmap.org/#map=17/24.20816/120.74495 for map powered by openstreetmap-carto

**Comment by matkoniecz** [comment]
(2) Boundaries are displayed badly on http://opencellid.org/#zoom=17&lat=24.208964&lon=120.74594 that is powered by https://www.enaikoon.com/ using map that seems to be old version of openstreetmap-carto (or based on it).

Compare with http://www.openstreetmap.org/#map=18/24.21027/120.74420

I am not sure is there contact with enaikoon better than https://www.enaikoon.com/en/contact/contact-us/

**Comment by math1985** [comment]
The render server at http://tile.enaikoon.de/ seems to use an older version (at least two years old) of the current style. A large number of improvements have been made (or problems introduced, depending on who you ask ;)) since then. The village name rendering on top of boundaries is exactly one of the things we improved within the last two years.

If you can stay within the tile usage policy (sorry I don't know the details) I would recommend using tiles directly from http://tile.enaikoon.de/osm/1/1/1.png.

I didn't know the rendering at http://tile.enaikoon.de/. Seems we can use that to make the map compare at http://bl.ocks.org/tyrasd/raw/67a00dbb869456094373/ working again!

I like the opencellid site a lot by the way, cool project!

**Comment by jidanni** [comment]
OK let's start back at the top to see what programs can be improved.
* User sees ugly name sitting right on a  boundary.
* User looks around the screen to find out who is at fault.
* user sees "Powered by Leaflet

3.5.0
OpenCellID database CC-BY-SA 3.0
map data: OpenStreetMap© | ODbL 1.0, tiles: CC-BY-SA 2.0"

(Smart) user thinks "but I don't think real OpenStreetMap has this problem" and
checks, and indeed it doesn't. (Dumb user doesn't think anything.)

OK, the remaining links are licenses. Except for http://leafletjs.com/ .
So he looks for a way to file a bug there and indeed does find
https://github.com/Leaflet/Leaflet/ and files
https://github.com/Leaflet/Leaflet/issues/4119 .

Maybe the 3.5.0 refers to Leaflet. Maybe not.

Anyway there is no version information about which he should compare the
latest version of whatever too. etc. etc.

All in all he is 100 miles away from knowing how to check, who to approach, and what to
tell them.

So somehow right on that
http://opencellid.org/#zoom=17&lat=24.208964&lon=120.74594
there should be full details, and even a "?" link to somehow a report
problems link like Google, but problems in what layer, how to tell, what
a big mess.

**Comment by jidanni** [comment]
I don't know anything about tile usage. Just picture me as "Auntie Nelda".
http://www.youtube.com/watch?v=qhwKqq0j1S8&list=PL6E40919035151385
all I did was click on a map and saw an ugly boundary.

**Comment by pnorman** [comment]
OpenCellID and Enaikoon are both third-party sites outside the control of OpenStreetMap or this style.

CONTRIBUTING.md is linked when you create a new issue here, so changes to that would be in-scope for this issue tracker, but changes to any text on other sites is outside of the scope of what we do here.

**Comment by jidanni** [comment]
Re: (1) This rendering is not using this map style - see http://www.openstreetmap.org/#map=17/24.20816/120.74495 for map powered by openstreetmap-carto

OK, but can you believe there, village name are only shown on the SOUTH side of boundaries!
Where in the history of cartography did they come up with that?
So now one must scroll miles and miles north to find what the name on the other side of the line is each time we find a name on this side of the line.

**Comment by math1985** [comment]
> village names are only shown on the SOUTH side of boundaries

I don't think this is the case in general. However, it might be a case for Chinese characters in particular. We have seen some particular bugs before related to non-Latin characters before. If this is indeed a bug, it might be fixed when we upgrad to Mapnik 3 - is somebody able to confirm this report and see if it is fixed in Mapnik 3?


> Where in the history of cartography did they come up with that?

Please be a little more respectful, as you see things are not always as easy as they seem.

**Comment by mboeringa** [comment]
> Where in the history of cartography did they come up with that?

In the history of cartography, it was hundreds of zealously working cartographers bend over their desks all day long using pen, ink and knife to scratch out or take away names and labels and map features, and carefully designing and adding new ones, from stone or photographic film used in lithographic or offset printing.

It would take years, often 5-15 years, to update an entire country, even with a squad of dozens of them. By the time they updated the last patches of the country, the first sheets were often largely outdated...

Now, it's a handful of "cartographers" designing a style, like this one, relying on non-perfect automated routines, to give you a nearly instantaneously updating experience.

Somewhere, there's gotta be a trade-off...

**Comment by math1985** [comment]
>  Seems we can use that to make the map compare at http://bl.ocks.org/tyrasd/raw/67a00dbb869456094373/ working again outside the Benelux countries!

I created a new comparison page based on the enaikoon.de tile server: http://bl.ocks.org/math1985/raw/7d2b0538a8b64b9d31e2/#9.00/51.3683/-0.0782

**Comment by matkoniecz** [comment]
>I created a new comparison page based on the enaikoon.de tile server: http://bl.ocks.org/math1985/raw/7d2b0538a8b64b9d31e2/#9.00/51.3683/-0.0782

Thanks!
