### ISSUE TITLE
Render shop=farm sooner

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2011]
We can't do different rendering for the same features in different areas, but farm shops are normally on farms and not in feature-dense areas, giving us the option to render them at lower zooms.

**Comment by trigpoint** [comment]
This is not always the case, I can think of at least one that is a farm that is now between recent residential and commercial areas.

**Comment by kocio-pl** [comment]
Do we still want to change it? What zoom level would be better?

**Comment by trigpoint** [comment]
It would be better IMHO to leave as is. Farm shops sell produce from a farm but are not always on a farm. They exist in town centres too.

**Comment by kocio-pl** [comment]
I also think so, therefore I'm closing it. Proper change should include detecting the context (farm/urban area), but currently we don't know how to do it - see #1957.
