### ISSUE TITLE
Odd node rendering for a protected_area poly's node

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#2012]
https://www.openstreetmap.org/note/487066#map=19/51.29710/9.50322&layers=N
The lower left corner of the protected_area polygon (node 207582326 of way 19849890) has a "bulge" that probably should not be there.
![x](https://cloud.githubusercontent.com/assets/8861948/12071859/e265ea36-b0c2-11e5-96d6-0ddf1a9d50fc.png)

**Comment by math1985** [comment]
Duplicate with #481 - the upgrade to Mapnik 3 should fix this.
