### ISSUE TITLE
Add rendering for swing_gate

### ISSUE THREAD

**Issue by VA00** [gravitystorm/openstreetmap-carto#2014]
Node with barrier=swing_gate is not diplayed on map, but it should be rendered with same icon as lift_gate. Noteworthy, nearly all forest road barriers in Poland are swing_gates, but due to lack of an icon are notoriously added as lift_gate.

**Comment by HolgerJeromin** [comment]
Right now osm carto renders all barrier values. At least this is what is reported at #818 
But http://www.openstreetmap.org/node/428939203 is not rendered.

**Comment by HolgerJeromin** [comment]
Sorry, #818 is only about named barrier *lines*.  reading the current code: https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml#L2445

**Comment by aceman444** [comment]
I also vote for this to be added. There are many of these in rural/agricultural areas in our country.
Either use the same icon as for lift_gate (as reported), or you could draw a triangular gate icon, based on the photo at http://wiki.openstreetmap.org/wiki/File:Swing_gate.jpg .

**Comment by polarbearing** [comment]
For nodes, only barrier = gate | lift_gate | bollard | block are coded in amenity-points.mss.

As bollard and block are rendered the same, we could also use the same symbols among lift/swing_gate, the difference is insignificant for this map style, while I agree it should be rendered.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 03.01.2016 um 20:55 schrieb polarbearing <notifications@github.com>:
> 
> As bollard and block are rendered the same, we could also use the same symbols among lift/swing_gate, the difference is insignificant for this map style, while I agree it should be rendered.


+1
