### ISSUE TITLE
Roads disappear on Cycle layer

### ISSUE THREAD

**Issue by VA00** [gravitystorm/openstreetmap-carto#2015]
Since at least a few months, some roads do not render in OSM cycle map layer, e.g:

https://www.openstreetmap.org/query?lat=50.07027&lon=19.52751#map=16/50.1180/19.3464&layers=C

All attributes are correct. Roads disappear at any zoom level.

**Comment by HolgerJeromin** [comment]
This is the bugtracke for the defaul map style only. 
Your problem (way https://www.openstreetmap.org/way/348885476) appears on cycle layer.
