### ISSUE TITLE
render water sport facilities (non waterpark)

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2018]
We should render `leisure=sports_centre` + `sport=swimming` same as the current `leisure=water_park` to prevent tagging for the renderer (for not fun orientated water stuff).
All keys are available in the database.

The sports_centre + swimming combination is [quite often](http://overpass-turbo.eu/s/dFz) used (Taginfo says 3272) even now.

**Comment by polarbearing** [comment]
leisure=water_park still lacks [area rendering](1490), being a candidate for a new [boundary style](1624).

**Comment by matkoniecz** [comment]
taginfo link: https://taginfo.openstreetmap.org/tags/leisure=sports_centre#combinations (3420 as of 2016-03-04).

**Comment by SelfishSeahorse** [comment]
@matkoniecz: Here's the link to the discussion on the tagging mailing list about swimming pool facilities: <https://lists.openstreetmap.org/pipermail/tagging/2017-September/subject.html#33466>.

Copied from #2870:

> The result from the discussion on the tagging mailing list is that public indoor as well as outdoor swimming facilities should be tagged `leisure=sports_centre` + `sport=swimming` and that `leisure=water_park` should only be used for real water parks (amusement parks featuring slides, wave pools etc.).
> 
> Therefore I think it would be best to use the swimmer icon for `leisure=sports_centre` + `sports=swimming` (#2018) and to change the icon for `leisure=water_park` for a water slide or similar (as one doesn't swim there).

Current use of `leisure=sports_centre` + `sports=swimming`:  8 028

**Comment by geozeisig** [comment]
We have now revised the water sports in the wiki and cleaned up. There are four features that should have an icon:

1. **leisure=water_park** has now 
![swimming-16](https://user-images.githubusercontent.com/17127509/37283554-b0321b40-25f8-11e8-83fa-72155c7a042b.png)
This is misleading and should be changed. For example, in a water slide or a person in the water playing the ball.

2. **leisure=sports_centre + sport=swimming** should have the following icon:
![swimming-16](https://user-images.githubusercontent.com/17127509/37283742-541cf662-25f9-11e8-97d4-ddb603ea6ed3.png)

3. **leisure=swimming_area + sport=swimming**  should have the following icon:
![swimming-16](https://user-images.githubusercontent.com/17127509/37283768-7751822e-25f9-11e8-91a7-c68b0abf60ae.png)

4. **amenity=public_bath** we have now:
![public_bath](https://user-images.githubusercontent.com/17127509/37283793-95f4469e-25f9-11e8-9bab-871e6b1bf7ad.png)
that's OK

**Comment by HolgerJeromin** [comment]
> 3. leisure=swimming_area + sport=swimming

Wiki makes the sport tag optional

**Comment by geozeisig** [comment]
@HolgerJeromin Thanks for the hint. At leisure=swimming_area it is already clear from the word that it is sport=swimming. So I change my suggestion:

3. **leisure=swimming_area**  should have the following icon:
![swimming-16](https://user-images.githubusercontent.com/17127509/37447908-720560ec-2824-11e8-91a5-8091c7b8d927.png)

**Comment by Tomasz-W** [comment]
related to https://github.com/gravitystorm/openstreetmap-carto/issues/844
