### ISSUE TITLE
Multipolygon rendered using tags from outer way

### ISSUE THREAD

**Issue by zeromap** [gravitystorm/openstreetmap-carto#2019]
![hole](https://cloud.githubusercontent.com/assets/15248277/12277203/236d8894-b948-11e5-8d5d-f2dca6cb965f.png)

The geometry of [r5856226](https://www.openstreetmap.org/relation/5856226) is being rendered with the tags of [w186712414](https://www.openstreetmap.org/way/186712414).

Multipolygon relations should be rendered by the tags they have, not by the tags of one of their members, right? building:part is not rendered so this should appear as a solid building since [w186712414](https://www.openstreetmap.org/way/186712414) has the building=yes tag.

This issue is not about 3D mapping, but for reference the building is three levels above ground and the interior is one level above ground. There are also building:part ways 2 and 3 levels above ground, mapped as such.

[F4map 3D](http://demo.f4map.com/#lat=43.0513690&lon=-76.1544447&zoom=20&camera.theta=59.697&camera.phi=-65.604)

![f4map](https://cloud.githubusercontent.com/assets/15248277/12277211/2a1ed8fa-b948-11e5-94bf-2839f7f2f73b.png)

**Comment by math1985** [comment]
Is this a bug in osm2pgsql perhaps?

**Comment by pnorman** [comment]
> Multipolygon relations should be rendered by the tags they have, not by the tags of one of their members, right? building:part is not rendered so this should appear as a solid building since w186712414 has the building=yes tag.

Multipolygon processing isn't done in OpenStreetMap carto code, so it's either a tagging error, multipolygon geometry generation error in osm2pgsql, or something else not here.

**Comment by math1985** [comment]
@zeromap I'd recommend trying https://github.com/openstreetmap/osm2pgsql/. I can't guarantee that it's in their scope either though.

**Comment by zeromap** [comment]
@math1985 I'll try there.
