### ISSUE TITLE
render mini-roundabouts less prominent at lower zoom levels

### ISSUE THREAD

**Issue by TZornG** [gravitystorm/openstreetmap-carto#2020]
[Mini-roundabouts](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dmini_roundabout) render with the same size symbol on all zoom levels from 16. At least at that zoom level, if not even at 17, the symbol looks much too obtrusive and looks rather like a marker for a city. It is even bigger than the connecting streets.

In my opinion a mini roundabout doesn't need to be rendered at all until level 18 or 19. At least it should be reduced to a simple dot or something else with a smaller size.

[Example](http://www.openstreetmap.org/node/269063436#map=16/51.0347/7.0505)

![mini_roundabout 16](https://cloud.githubusercontent.com/assets/16701177/12321728/ffc0f7d2-baaf-11e5-9028-9264803189e9.jpg)

**Comment by matkoniecz** [comment]
See also #637 (miniroundabouts used to be rendered from 15 before that PR)

**Comment by kocio-pl** [comment]
It was already proposed to be moved further to z17 or z18 and nobody complained:

https://github.com/gravitystorm/openstreetmap-carto/issues/598#issuecomment-47932982

so I think we could push them a bit more. However we should avoid confusing mini-roundabout with turning circle.

**Comment by kocio-pl** [comment]
See also #2558.
