### ISSUE TITLE
Emergency piers

### ISSUE THREAD

**Issue by d1g** [gravitystorm/openstreetmap-carto#2022]
Current examples: http://www.openstreetmap.org/way/313944103 http://www.openstreetmap.org/way/386589616

What is suggested tagging? man_made=pier + emergency=... ? Or should it be tagged as highway? 

I doubt there widely recognized symbol for this; at least text abbreviation would be nice.

Not sure if this was rejected or nobody cared to implement it. Previous discussion was in #715

**Comment by matkoniecz** [comment]
> What is suggested tagging? man_made=pier + emergency=... ? Or should it be tagged as highway? 

For such guestion tagging mailing is a better place.

**Comment by matkoniecz** [comment]
Also, special rendering for emergency piers - differing them from normal ones is an overkill for a general purpose style.
