### ISSUE TITLE
Render cyclelane (cycleway:left|right=lane)

### ISSUE THREAD

**Issue by nighto** [gravitystorm/openstreetmap-carto#2023]
Currently, only cycleways (ways tagged with ```highway=cycleway``` are rendered). Cyclelanes are tagged as ```highway=*``` + ```cycleway:left|right=lane```, and are not rendered, so in many cases cycle lanes are wrongly tagged as cycleways (tag for the renderer).

I think we could follow the cycleway style and make the highway border with the same blue dash.

**Comment by moliha** [comment]
I think this is a good idea - solving the problem that cycleways defined with the lane tag is invisible on the map. In my opinion,  all these invisible cycleways is a major problem. I wonder why the suggested solution has not attracted other comments - for or against ...?

**Comment by rrzefox** [comment]
Since cycleway (and certainly not cycleway:left or cycleway:right) is not currently a column in the rendering database, this is not technically possible before the database has been reimported with hstore (so this depends on #1504).

**Comment by BalooUriza** [comment]
On Fri, Jan 22, 2016 at 7:09 AM, moliha <notifications@github.com> wrote:

> I think this is a good idea - solving the problem that cycleways defined
> with the lane tag is invisible on the map. In my opinion, all these
> invisible cycleways is a major problem. I wonder why the suggested solution
> has not attracted other comments - for or against ...?
>
I think it's a situation most readily solved by using bicycle:lanes and
handles far more flexible cases.  Here's an example, from left to right
let's say we have a left turn lane, a bicycle only lane turning left and
continuing through, two general access lanes continuing through and a
bicycle only lane continuing through.

oneway=yes
lanes=5
turn:lanes=left|left;through|through|through|through
access:lanes=yes|no|yes|yes|no
bicycle:lanes=yes|designated|yes|yes|designated
cycleway=lane

This scheme allows a routing engine for a car turning left to only
highlight the left lane for lane guidance, a bicycle continuing through to
highlight either the left or right bicycle lane, or both, and motorists
continuing through just the 3 and/or 4 lane.

**Comment by matkoniecz** [comment]
I am dubious about value of rendering individual lanes. Especially as road rendering is already near limits and adding even more information to render is going to make situation even more confusing.

I think that lane rendering should not be done in a general purpose map style.
