### ISSUE TITLE
Render priority=backward/forward on highways

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#2026]
Hello, there.

I just wondered: it could be useful to render the `priority` tag on highways, it could warn the travellers about this uncommon — for a driver — local feature and help them as an early warning. This could be rendered by drawing over the highway an asymmetric left-right arrow like this quick and dirty example:

![priority](https://cloud.githubusercontent.com/assets/13777824/12450172/40f70da0-bf82-11e5-91d6-72cac7048793.png)

I don't know if my suggestion is relevant, though, but it can be useful.

Regards.

**Comment by matkoniecz** [comment]
I am highly dubious whatever it will be recognisable with small oneway arrows.

And it would be too easy to confuse with oneway arrows.

**Comment by polarbearing** [comment]
It was confusing me already, so I checked the meaning in the [wiki](https://wiki.openstreetmap.org/wiki/Key:priority). Anything less than how the traffic signs symbolise the situation would lead to misunderstanding. I see no point to show this feature in the general map. Besides construction sites, I remember permanent situations only on small narrow bridges, a driver would not consult the general map for such a thing. The tag is useful for routers to add a time penalty for the disadvantaged side, or to shout a warning when approaching.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 22.02.2016 um 15:10 schrieb polarbearing <notifications@github.com>:
> 
> I see no point to show this feature in the general map. Besides construction sites, I remember permanent situations only on small narrow bridges, a driver would not consult the general map for such a thing. The tag is useful for routers to add a time penalty for the disadvantaged side, or to shout a warning when approaching.


+1, this is not a feature to render, it is useful for routing software, but would only lead to confusion in the standard map
