### ISSUE TITLE
Tunnel=culvert misrendered when in the middle of natural=water/water=river

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#2027]
Hello, there.

I noticed a bug when rendering `tunnel=culvert` in the middle of `natural=water/water=river`: the culvert is rendered above the `natural=water`, which looks like a hole in the middle of water, here under the private access bridge: https://www.openstreetmap.org/#map=19/48.34991/6.15964

Regards.

**Comment by matkoniecz** [comment]
It seems that tagging is wrong

> here under the private access bridge

According to the current tagging there is no bridge there and river is in tunnel* - and at the same according to natural=water polygon there is no river.

*see https://www.openstreetmap.org/way/355739433#map=19/48.35006/6.15979

**Comment by Penegal** [comment]
Ok, I'm wrong on the bridge: as the river is in a culvert, there's no use to reason to tag a bridge, but what's the matter with the natural=water polygon? There is a similar problem here: https://www.openstreetmap.org/#map=19/48.34627/6.14209 From a free surface hydraulics PoV, I must connect the Ruisseau du Ménil, which is in a culvert until the confluence, with the Madon river, but that creates this glitch.

So, may I ask on the tagging ML, or is this still rendering?

**Comment by HolgerJeromin** [comment]
There is no culvert from the riverbed to the center of the river, is it? So this is not tagged right. At least if this part gets a riverbed.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 21.01.2016 um 19:05 schrieb Penegal <notifications@github.com>:
> 
> From a free surface hydraulics PoV, I must connect the Ruisseau du Ménil, which is in a culvert until the confluence, with the Madon river

you name it. Split the culvert way at the confluence and remove the culvert tag on the remaining part that is within the river

**Comment by Penegal** [comment]
Sounds like adapting the reality to fit the technical limitations: the Madon is meters wide at this point, and uses the full width of its riverbed, so the Ruisseau du Ménil gets in the Madon exactly at the culvert exit, but I should model this differently, with an open riverbed, from the Madon riverbed edge to its modeled, null-width path, to be modeled and displayed correctly? Isn't that a problem? I know that modelling reality causes a data loss per se, even a slight one, but isn't it more like modifying reality to fit the computing limitations than just tolerating a precision loss?

I must add that this isn't a rethorical question, but this is against what I thought until then. Whatever, if you can explain me why I'm wrong, that's OK, I will do like that in the future.

**Comment by dieterdreist** [comment]
2016-01-22 9:49 GMT+01:00 Penegal <notifications@github.com>:

> Sounds like adapting the reality to fit the technical limitations: the
> Madon is meters wide at this point, and uses the full width of its
> riverbed, so the Ruisseau du Ménil gets in the Madon exactly at the culvert
> exit, but I should model this differently, with an open riverbed, from the
> Madon riverbed edge to its modeled, null-width path, to be modeled and
> displayed correctly? Isn't that a problem? I know that modelling reality
> causes a data loss per se, even a slight one, but isn't it more like
> modifying reality to fit the computing limitations than just tolerating a
> precision loss?



there's hardly any "right" and "wrong", it's all a question of abstraction
and concepts (and there's often no general agreement how the details should
be modeled). This discussion should continue on the tagging ML. If you do
what I suggested, the end of the culvert will be mapped where it is in
reality (at the border of the river), i.e. the coordinates will be correct
and the rendering will look fine. But there will be a short "virtual"
connection from the border to the center of the river (what you call the
0-width river way), which isn't there (as part of the Ruisseau du Ménil),
it is actually a part of the Madon (that represents the width of the river
so you don't extend length of the Ruisseau d.M. to the center of the
Madon). However you model this, there will be some strange artefacts of one
way or the other. You could change the name for the part within the river
from Ruisseau du Ménil to Madon to make it even more explicit.

**Comment by Penegal** [comment]
So be it: I'll correct the modelling for the Ruisseau du Ménil as you suggested, but what for the first problem? This isn't modelling, or I missed something; the `natural=water` polygon figures the riverbed, and the culvert is on the river side stream, which is a correct modelling, AFAIK.

**Comment by dieterdreist** [comment]
2016-01-22 11:11 GMT+01:00 Penegal <notifications@github.com>:

> the natural=water polygon figures the riverbed, and the culvert is on the
> river side stream, which is a correct modelling, AFAIK.
>


normally this would not be tagged like this but with waterway=riverbank
btw.: https://www.openstreetmap.org/way/392558282
http://wiki.openstreetmap.org/wiki/Tag:waterway%3Driverbank

**Comment by Penegal** [comment]
So this is where the problem is: according to this same wiki page,

> The use waterway=riverbank has been deprecated in favor of natural=water + water=river but the former remains in widespread use and is still preferred by some mappers.

Looks like the rendering does not take into account this deprecation; maybe it should be adapted to also use the new tagging.

**Comment by imagico** [comment]
waterway=riverbank is perfectly fine and valid tagging, no need to make fuzz about it here.  But keep in mind natural=water and waterway=riverbank are both exclusively for surface water, not for underground or in tunnel water areas.

Anyway i think this issue can be closed since it does not indicate anything specific that is rendered in contradiction to how it is mapped in this style.

There are problems with rendering waterway bridges - see here:

http://www.openstreetmap.org/#map=17/52.30307/8.92976

but this is not what this issue is about apparently.

**Comment by Penegal** [comment]
I do not say that there is anything wrong in `waterway=riverbank`, but that `natural=water` + `water=river` should be rendered equally, as this duo deprecated `waterway=riverbank`, but, here, they seem to be rendered differently, causing a glitch. Am I wrong to assume that the rendering should reflect this deprecation by aligning `natural=water` + `water=river` rendering on the rendering of `waterway=riverbank`?

**Comment by dieterdreist** [comment]
2016-01-22 16:18 GMT+01:00 Penegal <notifications@github.com>:

> I do not say that there is anything wrong in waterway=riverbank,
>

I do, there's clearly a semantic problem here: a riverbank is along the
river, at it's border, so it is a linear feature, or it might be considered
the area just below the river (parts that frequently get wet when there's a
lot of water in the river), but surely you can't consider the whole river a
"riverbank", and tagging ways across the river (to close the polygon) with
riverbank seems complete odd.


> but that natural=water + water=river should be rendered equally, as this
> duo deprecated waterway=riverbank
>

I agree it should be rendered the same, I don't agree something has been
"deprecated" besides a vote in the wiki making a certain (non-binding)
statement / expression of desire.

**Comment by pnorman** [comment]
This issue tracker is not for a general tagging discussion like this, which should take place elsewhere.

This style treats `waterway=riverbank` the same as `natural=water`.

The example here is a tagging error. If there's surface water, then there shouldn't be a `tunnel=culvert`. If there isn't surface water, then there shouldn't be a `waterway=riverbank` or equivalent `natural=water`.

-----

>  I do not say that there is anything wrong in waterway=riverbank,
> I do

If you believe there's something wrong with the rendering of `waterway=riverbank`, please open a new issue for it.
