### ISSUE TITLE
chinese characters unreadable

### ISSUE THREAD

**Issue by fkv1** [gravitystorm/openstreetmap-carto#2028]
Chinese characters are denser than latin charaters and should therefore be rendered at least 150% the size of latin characters. As you need fewer charaters, the bigger characters do not occupy more total space than latin text labels.

The obvious anti-aliasing makes chinese characters even more unreadable by blurring them.

![taiwan1](https://cloud.githubusercontent.com/assets/6015933/12551441/c3f12c5e-c36a-11e5-8811-8c9a3e53a5e2.png)
![taiwan2](https://cloud.githubusercontent.com/assets/6015933/12551442/c3f413ec-c36a-11e5-9210-ba8936eb0cd8.png)

These problems also occur with japanese kanji (#294) which are essentially chinese characters, whereas other japanese characters (hiragana, katakana) are less dense.

Hangul (Korean) text also seems too tiny, although it happens to be somewhat readable when using a zoom tool like xmag.

#1335 is related.

**Comment by math1985** [comment]
Yes, it's certainly something that needs to be fixed./ I don't see right-away how, though.

Also, it seems that this is a specific case of #294, so I think it's better to close this issue and continue over there.
