### ISSUE TITLE
Render leisure=sports_centre, sport=swimming as water park

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#2029]
Currently, the tag leisure=swimming_pool is often abused to tag swimming pools as a facility, rather than only the water area. As an alternative, it is recommended to use the tag leisure=sports_centre, sport=swimming.

The tag combination leisure=sports_centre, sport=swimming is currently not rendered in this project. It would be nice if it could be rendered with the same icon as water parks.

**Comment by HolgerJeromin** [comment]
Same as mine #2018

**Comment by math1985** [comment]
Thanks!

**Comment by dieterdreist** [comment]
sent from a phone

> Am 25.01.2016 um 19:06 schrieb math1985 <notifications@github.com>:
> 
> As an alternative, it is recommended to use the tag leisure=sports_centre, sport=swimming.
> 


saying it is recommended stretches the outcome of the voting for leisure=aquatic_centre a bit: it is currently not common practice and there wasn't a solid majority for this combination either in the proposal voting

**Comment by HolgerJeromin** [comment]
leisure=water_park has 8075 uses
sports_centre+sport=swimming has 3272 uses.
But we should discuss this in #2018
