### ISSUE TITLE
Differentiate rendering for amenity=parking

### ISSUE THREAD

**Issue by gormo-osm** [gravitystorm/openstreetmap-carto#2031]
There could be a different symbol for amenity=parking with specific tags, e.g. hgv=designated, to differentiate parking for HGV and other motor vehicles.

Possible test case area: http://www.openstreetmap.org/#map=18/50.93985/9.54331

**Comment by kocio-pl** [comment]
1. Do we really want to have it here?
2. Any proposition how should they look like?

**Comment by pnorman** [comment]
This is a more general case of #81, and I'm 👎 on it

**Comment by kocio-pl** [comment]
Looks like too vague to make it workable. Might be reopen if something more specific would appear.
