### ISSUE TITLE
hedge rendered as fill if combined with nature_reserve 

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#2033]
Hi

http://www.openstreetmap.org/#map=18/51.40169/-2.38212

Three polygons:
Left:
barrier=hedge
Middle:
barrier=hedge
leisure=nature_reserve
Right:
leisure=nature_reserve

The middle polygon is rendering hedge with a fill obliterating any other items, until zoom=15 where hedges stop being rendered & it shows the nature_reserve. I assume hedge/nature_reserve isn't the only combination which causes this anomaly.

Is it a similar problem to mkgmap where it only renders one item in each category of point, lines or polygon?

----
BTW I tried to use the OSM Sandbox to place these temporary edits, but it renders the main database instead of the custom! Is there a way to resolve this?

**Comment by SomeoneElseOSM** [comment]
I'm not sure if "nature reserve" is relevant here; isn't it the same problem as https://github.com/gravitystorm/openstreetmap-carto/issues/971 ?

**Comment by DaveF63** [comment]
True, as I said I thought there maybe other combinations.

Yes it is the same as #971, but I'm not sure it was a satisfactory conclusion.

What I don't understand is why it renders *differently* if another primary tag is added. It would almost make more sense (although I don't think it's the solution) if it didn't render at all.

As 'hedge' isn't in the .style file, where is it defined?  

Where is this 'one element, on tag' rule you mentioned stipulated? I don't understand why a loop can't be used to check all tags of an element and render it multiple times as needed.

 

Out of interest, did you just know about issue #971? I did a good search of all issues & didn't see that one.

**Comment by pnorman** [comment]
leisure=nature_reserve indicates that the way is an area, so the the way gets turned into a polygon, which then gets filled because we have a style for polygon barrier=hedge.

This is from the assumption that an OSM object is either a line or a polygon, and duplicates #971.

**Comment by SomeoneElseOSM** [comment]
> Out of interest, did you just know about issue #971? I did a good search of all issues & didn't 
> see that one. 

I didn't know the number off the top of my head, but I did remember that it had been mentioned before - at the time I was surprised that there was an area representation for barriers at all (not that it's "wrong" - it's just not something that I expected).

**Comment by DaveF63** [comment]
>leisure=nature_reserve indicates that the way is an area, so the the way gets turned into a polygon, which then gets filled because we have a style for polygon barrier=hedge.

To partially repeat my previous question: If 'nature_reserve' defines the way as a polygon/area, why does it get rendered as a hedge (with fill) & not a nature_reserve?

**Comment by matkoniecz** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/issues/971#issuecomment-56404956

**Comment by matkoniecz** [comment]
And http://www.openstreetmap.org/way/394365144#map=18/51.40184/-2.38123 is treated as an area and rendered as hedge (fill) and nature_reserve (green border).

**Comment by pnorman** [comment]
> To partially repeat my previous question: If 'nature_reserve' defines the way as a polygon/area, why does it get rendered as a hedge (with fill) & not a nature_reserve?

It gets rendered as both.

**Comment by DaveF63** [comment]
Just because nature_reserve is defined as an area in the carto, it seems wrong for hedge automatically assume it.

Why do other combinations not succumb to the same problem?
https://www.openstreetmap.org/#map=19/51.40293/-2.38155

**Comment by polarbearing** [comment]
Most likely a real hedge would have a gap where people enter the area. Thus adding an open way on mostly the same nodes would solve your problem, and allow to clearly separate other features of the hedge (height, species) from the area-polygon

**Comment by DaveF63** [comment]
Most entrances are marked with a node, so not requiring hedge ot be split. Walls have similar attributes to hedges. There appears to be inconsistencies in the carto rules.

**Comment by trigpoint** [comment]
I have used area=yes to represent a thick hedge, it is useful whete there is a stile at each end on a footpath, sometimes a footbridge in between .
I would consider the default to be =no however.

Hedges are normally drawn as linear features, I do not normally draw a closed way but joining hedges that continue over several fields.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 30.01.2016 um 15:21 schrieb DaveF63 <notifications@github.com>:
> 
> Most entrances are marked with a node, so not requiring hedge ot be split. Walls have similar attributes to hedges. There appears to be inconsistencies in the carto rules.


mixing different features (here a hedge around a natural reserve and a natural reserve) in one OSM object is common but bad mapping style: it is not clear whether the hedge is mapped as an area or as a linear feature. If you add area=no to the hedge you will have to detach the nature reserve anyway, as you would if you added more information like a height for the hedge, a name or a tag specifying the kind of nature reserve, etc.
