### ISSUE TITLE
Large lakes not shown (depending on resolution)

### ISSUE THREAD

**Issue by JuangDse** [gravitystorm/openstreetmap-carto#2036]
If you go to

http://www.openstreetmap.org/#map=6/-10.984/35.964
http://www.openstreetmap.org/#map=7/-10.984/35.964

and look at the main lake in the center (Lake Malawi), you will notice that the first map only shows its lower part and the second its upper.

**Comment by polarbearing** [comment]
The split view was a tile caching problem. The lake relation was changed a couple of times recently, some tiles dating back to Jan 03. 
http://www.openstreetmap.org/relation/2631184
checking different zoom levels currently

**Comment by math1985** [comment]
If I'm not mistaken, this can be closed.
