### ISSUE TITLE
Request to render: landuse=plant_nursery

### ISSUE THREAD

**Issue by CJTmmr** [gravitystorm/openstreetmap-carto#2039]
In my area are a lot of plant nurseries.
But landuse=plant_nursery is not rendered yet by Standard Layer.
A import many years ago tagged those plant nurseries incorrectly as landuse=orchard.

http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dplant_nursery 
and
http://wiki.openstreetmap.org/wiki/Proposed_features/Plant_nursery

Proposed rendering:
basic color of "landuse=farmland" with overlay of (not too dark) tree-symbols 

When plant_nursery is rendered, we can correct the wrong tags.

Thanks
Kees-Jan

**Comment by polarbearing** [comment]
8858 uses, good idea.

> When plant_nursery is rendered, we can correct the wrong tags.

No, you should start correcting the tags now. Remember not to tag for a particular renderer, also you increase the pressure to implement it because there is more usage for the tag.

**Comment by HolgerJeromin** [comment]
same as #1772

**Comment by matkoniecz** [comment]
Duplicate of  #1772, also see http://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer
