### ISSUE TITLE
leisure=ice_rink

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#2040]
Hello, leisure=ice_rink is not bin rendert. See [here](https://www.openstreetmap.org/way/42425344)

What is the reason for that?
1. Incorrect tagging. We should use leisure=pitch + sport=ice_skating
2. Incorrect rendering. leisure=ice_rink should be rendert like leisure=pitch or any thing else.

**Comment by matkoniecz** [comment]
see #796
