### ISSUE TITLE
render an icon for shop=tobacco

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#2043]
I have recently added a svg icon to JOSM for shop=tobacco and suggest we also render it here. This is the icon file: https://josm.openstreetmap.de/attachment/ticket/12337/tobacco-pipe.svg

**Comment by kocio-pl** [comment]
I like your concept and design, but in my opinion it doesn't look good with 14px raster and is hard to recognize:
![tobacco-pipe-14](https://cloud.githubusercontent.com/assets/5439713/13007999/1b8a8226-d194-11e5-8ae9-4aeff3e9a9d4.png)
My proposition is different (see https://github.com/gravitystorm/openstreetmap-carto/issues/1618):
![tobacco-14-2](https://cloud.githubusercontent.com/assets/5439713/13008004/28209cc8-d194-11e5-9039-32191efe1e92.png)
