### ISSUE TITLE
Runway as area not rendered at z<=13

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2051]
Have a look at this and zoom out:
http://www.openstreetmap.org/#map=14/-6.2207/39.2094

The runway disappears at z=13, the taxiways are still shown.
The runway is tagged as an area only. 
Runways tagged as way are rendered in z13 to 11.

Not sure if leaving out an extra way is a tagging error?

**Comment by mrwojo** [comment]
Presumably highway-area-fill's minzoom=14 [project.yaml#L932](https://github.com/gravitystorm/openstreetmap-carto/blob/65ae9ee7e0ef4d594ce03bba690ac29d079447aa/project.yaml#L932)

Note that the taxiways in the example are linear and thus not affected.

**Comment by pnorman** [comment]
> The runway is tagged as an area only.

Looks like a mapping error then. Rendering linear features before areas start getting rendered is intentional, and common with highways.
