### ISSUE TITLE
Wrong colour for oneway arrow on path with bicycle=designated 

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2054]
![oneway-path](https://cloud.githubusercontent.com/assets/7693297/13204134/595e326a-d8c8-11e5-938c-c5a2ced7e93a.PNG)
https://www.openstreetmap.org/way/367094309

It's a bicycle=designated and foot=designated highway=path with oneway=yes. The arrow is red, the path blue.

**Comment by nebulon42** [comment]
https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss#L3047-L3056 needs to modified so that footway/path with bicycle=designated does not get the red arrow but the blue one instead to be consistent with the line colour.

**Comment by geozeisig** [comment]
When you have an escalator (highway=steps + conveying=forward) oneway is not in use. In this connection conveying=forward (backward) is used to define the direction. It would be nice to mark this with arrows too.

**Comment by matkoniecz** [comment]
@geozeisig Please, create separate issues for separate problems.
