### ISSUE TITLE
render railway=crossing 

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2063]
The wiki (and JOSM validator) says that railway=crossing is for pedestrians, level_crossing for roads. Right now (after #98) only level_crossing is rendered.

**Comment by d1g** [comment]
Based on images of "pedestrian railway crossing" and my experience, this page illustrates objects very well: http://www.centurygrp.com/PhotoGallery/SubCatPhotos.asp?SCID=1116&p2=1116&p8=&p3=4003

You can use horizontal profile of rails/crossing plates. AFAIK, there no internationally understood symbol. On the ground signs (for informing pedestrians) are not uniform, there seem no info info per each country.

**Comment by matkoniecz** [comment]
I am not entirely sure whatever rendering railway=crossing and level_crossing is useful and beneficial.

There are certainly negative effects (map & code complexity).

**Comment by d1g** [comment]
In my locality railway=crossing often found completely apart from level_crossing(s). To me, if style renders level_crossing, then it makes sense to also render a (pedestrian) crossing.

And yes, good portion of railway=crossing found apart from public_transport=platform, but railway companies tend to optimize this.


You can make some spatial analysis of what was mapped previously, but as always not all objects were mapped or tagged properly.

**Comment by matkoniecz** [comment]
> To me, if style renders level_crossing, then it makes sense to also render a (pedestrian) crossing.

I agree, but I am wondering whatever preferable is to render both or neither of them.

**Comment by trigpoint** [comment]
Not sure I understand why there is a difference, surely they are the same thing?
Usage will depend on the highway type, road crossings will typically be for pedestrians.

**Comment by d1g** [comment]
> Not sure I understand why there is a difference, surely they are the same thing?

If you simplify things to statements "they are made of concrete", then yes. But plates differ in terms of load they can handle, their width and practical use.

It is not true that every automobile may pass railway=crossing, but it is true that every pedestrian may cross via railway=level_crossing.

@trigpoint, is difference/use of tags is more clear now?

**Comment by trigpoint** [comment]
No, really not clear why there are two tags.
They are all level crossings, as in they cross on the level.
The way doing the crossing will define what the level crossing is intended for, be it footway, cycleway, bridleway or road type.

**Comment by matkoniecz** [comment]
Note that discussion of tagging like "why there are two tags" is offtopic here.

Such topics should be discussed on OSM wiki, tagging mailing list etc.

**Comment by HolgerJeromin** [comment]
One benefit for rendering the crossing is to show that they are at the same level. 
But otherwise there would be a bridge or something on one way. So I am not sure if this is really needed. 

But if a tag on the junction node is useful in the data, rendering it will help the feedback loop.

**Comment by drkludge** [comment]
Here you go. railway=crossing for pedestrians.
http://www.mapillary.com/map/im/Xn1j2QtxEH2KdWZbBYfskA/photo

Yes at the same area but railway=level_crossing.
http://www.mapillary.com/map/im/6JbFfHhyndUhOkWblvM1jQ/photo

Now go to the boon docks railway=level_crossing but if you want walk
across/horse/bike.
http://www.mapillary.com/map/im/me5C-ECPjP7B7IDMWgH7qw/photo

Why? All school buses and certain trucks must make a full stop before
crossing over tracks. The school bus must open the front exit.  There are
too many dead children and fireballs otherwise. For me that is an important
area to avoid for reduced travel time in a care. The other would be useful
but was dropped.  The level_ thing may be British English or what is used
in the business?

**Comment by aaronstar** [comment]
Hi there,
For reference only here is an image of a non-vehicular level crossing
![screenshot 2016-03-20 15 15 22](https://cloud.githubusercontent.com/assets/10798165/13903279/3d0fe4c6-eeaf-11e5-9e49-02d8a2e364f2.png)

**Comment by HolgerJeromin** [comment]
We have right now both tags in the database. 
This question is to render it or not. 
If we do not want both tags we have to decide it with a proposal and react to it in the rendering. 
Related to #2075

**Comment by boothym** [comment]
Noticed this recently as well - level crossing at the top of the map is rendered but not the crossing near the bottom of the map, see https://www.openstreetmap.org/#map=17/56.14129/-3.94387
![crossing](https://cloud.githubusercontent.com/assets/16965772/17417242/3f8c94c8-5a8a-11e6-9021-ade061ca5ec7.jpg)

The crossing for pedestrians looks like this, and should be marked somehow: http://abcrailwayguide.uk/images/crossings/lc_8145.jpg

**Comment by math1985** [comment]
I think rendering both types of crossings the same would be good enough for now.

Is anyone able to write a pull request?
