### ISSUE TITLE
Render crop=* values

### ISSUE THREAD

**Issue by d1g** [gravitystorm/openstreetmap-carto#2064]
Suggested icons by keder can be observed at http://wiki.openstreetmap.org/wiki/Key:crop or since 17-06-2015 http://wiki.openstreetmap.org/w/index.php?limit=50&tagfilter=&title=Special%3AContributions&contribs=user&target=Keder&namespace=6&tagfilter=&year=2016&month=-1

**Comment by dieterdreist** [comment]
2016-02-26 10:01 GMT+01:00 d1g <notifications@github.com>:

> Suggested icons by Keder can be observed at
> http://wiki.openstreetmap.org/wiki/Key:crop or since 17-06-2015
> http://wiki.openstreetmap.org/w/index.php?limit=50&tagfilter=&title=Special%3AContributions&contribs=user&target=Keder&namespace=6&tagfilter=&year=2016&month=-1
>
>
>

really nice icons, rendering this would surely push the tagging of crops.

**Comment by math1985** [comment]
I'm still not convinced how much crop tagging makes sense.

In the places I know, crop rotates every year, so there will never be rye on a field two years in a row.

Also, crop=corn means something different in American and British English. The current icon is for the American interpretation.

**Comment by dieterdreist** [comment]
2016-02-26 10:30 GMT+01:00 math1985 <notifications@github.com>:

> In the places I know, crop rotates every year, so there will never be rye
> on a field two years in a row.



yes, it depends on the area and crop whether it will be replaced frequently
or not (rotating fruit/crop can be important for the soil quality, it is
traditionally done in many regions). But: in some areas "mappers are so
mad" that they update the crop as it changes. And other crops, such as rice
or vine or olives etc. don't change but require years of preparation
(orchards in general).

**Comment by math1985** [comment]
> But: in some areas "mappers are so mad" that they update the crop as it changes.

Perhaps we then should also tag rye fields with a height tag, so we can keep track of the size of the crop as it grows?

**Comment by dieterdreist** [comment]
2016-02-26 12:06 GMT+01:00 math1985 <notifications@github.com>:

> Perhaps we then should also tag rye fields with a height tag, so we can
> keep track of the size of the crop as it grows?



please discuss this on tagging, osm-carto is a 2D style and your remark is
not pertinent in any way...

**Comment by d1g** [comment]
> In the places I know, crop rotates every year, so there will never be rye on a field two years in a row.

Yes this is due to https://en.wikipedia.org/wiki/Soil but I'm completely incompetent in this: they are rotating cultures and sometimes have _periods of resting_ (https://en.wikipedia.org/wiki/Ley_farming).

It means mappers should retag crop= every year, not that style should change every year :)
It also likely that crop=corn will reappear somewhere in neighborhood.

People would like to see crop=corn planted by them or just in their neighbourhood. Symbols are recognizable by locals and will add readability to the map.

In countries with 90%> urban population it makes no sense, but world isn't about top urban countries (like Japan, Belgium or Netherlands), half of the list is below 60%: http://data.worldbank.org/indicator/SP.URB.TOTL.IN.ZS?order=wbapi_data_value_2014+wbapi_data_value+wbapi_data_value-last&sort=asc
https://en.wikipedia.org/wiki/Urbanization_by_country

https://www.google.com/search?q=field+of+corn is not a yellow rectangle (as maps often oversimplify things). I would prefer more realism in crop=* tag rendering.

**Comment by matkoniecz** [comment]
I am scared by huge number of crops - even if currently this is tagged only on limited scale with just few crops it would make necessary to produce and maintain.

Given how much work is necessary to deal with just SVG transition I am not sure whatever adding necessity to produce so many icons is a good idea (https://en.wikipedia.org/wiki/List_of_most_valuable_crops_and_livestock_products alone lists over 40 plant crops).

Also, I ma dubious whatever further increasing style complexity is a good idea.

I think that it would work better as a separate project/overlay.

**Comment by d1g** [comment]
> on limited scale with just few crops

This one. We only want the most popular crops right now. Rice, Tomatoes, Potatoes (simply follow/use keder list for now). Exotic cultures up to specialized renders.

I would say "Tomamoes" is vague. https://en.wikipedia.org/wiki/List_of_tomato_cultivars we definitely don't want all variants of tomatoes in this project.

> I think that it would work better as a separate project/overlay.

I'm sure there enthusiast(s) about agriculture, but I'm not sure how many of them are able to create their own style. Giving them hint that this is possible to implement will boost mapping of crop=* values.

If one day there separate layer just for crops, then we could drop support in general purpose layer.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 28.02.2016 um 07:47 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> (https://en.wikipedia.org/wiki/List_of_most_valuable_crops_and_livestock_products alone lists over 40 plant crops).
> 


this is completely misleading because that list contains milk, cattle (meat), pigs, chicken (meat), eggs, orchard fruits like lemons and apples, cotton, peppers etc. all of which are classified and tagged differently in OSM.
Crops are typically in areas where there is few other stuff, so it won't clutter the map either.

**Comment by pnorman** [comment]
This would require the addition of too many symbols, add too much complexity, and is better suited to a specialized rendering.

**Comment by polarbearing** [comment]
We have www.openrailwaymap.org for the railway signalling enthusiasts. Crop enthusiasts can make an openagromap, but on the general map here we should keep focussing on high level categories such as farmland, orchard and plant_nursery.

**Comment by matkoniecz** [comment]
> this is completely misleading because that list contains milk, cattle (meat), pigs, chicken (meat), eggs, orchard fruits like lemons and apples, cotton, peppers etc. all of which are classified and tagged differently in OSM.

That is why I commented "over 40 plant crops" (after excluding meat, milk etc).

**Comment by dieterdreist** [comment]
sent from a phone

> Am 28.02.2016 um 20:58 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> That is why I commented "over 40 plant crops" (after excluding meat, milk etc).
> 

if you exclude those from the selection
 that aren't tagged with crop in osm like apples, olives, ... you get much fewer than 40 different values, something like 20, which is not few but still in a different league.

**Comment by d1g** [comment]
keder suggested **11** symbols, but I'm not sure if this counts as: 

> require the addition of too many symbols, add too much complexity

IMO rendering or the crop=* should be implemented with leaf_cycle=* (https://github.com/gravitystorm/openstreetmap-carto/issues/822)
