### ISSUE TITLE
small memorials too prominent

### ISSUE THREAD

**Issue by Merikurkku** [gravitystorm/openstreetmap-carto#2065]
Small memorials like plaques ans stone are rendered inadequately prominent.
Areas with many memorials looks confusing e.g.
http://www.openstreetmap.org/#map=17/53.56953/9.98121

Please render historic=memorial dependent on memorial=*:
Z=17 only memorial=war_memorial | stele | bust | statue 
Z=18 same like Z=17
Z=19 all memorials

**Comment by dieterdreist** [comment]
sent from a phone

> Am 27.02.2016 um 01:12 schrieb Merikurkku <notifications@github.com>:
> 
> Small memorials like plaques ans stone are rendered inadequately prominent.
> Areas with many memorials looks confusing e.g.
> http://www.openstreetmap.org/#map=17/53.56953/9.98121
> 
> Please render historic=memorial dependent on memorial=*:
> Z=17 only memorial=war_memorial | stele | bust | statue
> 


significance of a memorial cannot be deducted from its form, everything becomes individually less important if amassed. Why would we give more prominence to a small war memorial (if it were big we'd tag it as monument anyway) than to a memorial plate?

**Comment by matkoniecz** [comment]
Some busts are also pretty large - see for example https://en.wikipedia.org/wiki/Karl_Marx_Monument

Some steles are also large - see https://en.wikipedia.org/wiki/Yangshan_Quarry and https://en.wikipedia.org/wiki/Stele#/media/File:Stela_aksum.jpg

The same goes for statues https://en.wikipedia.org/wiki/List_of_statues_by_height

On the other hand similar #1066 would be a good idea.
