### ISSUE TITLE
labels of larger historic=archaeological_site should be larger

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2073]
see for example Forum Romanum label: http://www.openstreetmap.org/relation/1841080#map=17/41.89145/12.49100

![selection_002](https://cloud.githubusercontent.com/assets/899988/13549711/1c92bc68-e30c-11e5-8232-be9fd287ef3f.png)

**Comment by matkoniecz** [comment]
Maybe large areas should be displayed solely with label, without icon. Not tested but it would work well at least in that case.

**Comment by math1985** [comment]
Very similar to #1019, but also related to #1355.

**Comment by matkoniecz** [comment]
Also #1020, #1022, #1052

**Comment by Circeus** [comment]
Unless I'm mistaken, **none** of the labels that have accompanying icon were ever implemented using pixelarea, even though it would be obviously a good idea. The problem presumably that icons were barely starting to move to svg?

**Comment by matkoniecz** [comment]
> does this one include a bunch of smaller sites inside the big one

Yes, what worse in that case this tagging is not wrong.

**Comment by Tomasz-W** [comment]
@kocio-pl Please close this ticket as duplicate.
Continue further discussion in https://github.com/gravitystorm/openstreetmap-carto/issues/3284
