### ISSUE TITLE
stop rendering railway=level_crossing

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2075]
On mid zoom levels (z14, z15) it is rather not important nor useful to mark level crossings. On higher zoom levels (z16+) bridge and tunnel styling becomes noticeable so it is possible to check whatever something is a level crossing even without level crossing symbol.

I think that overall rendering of level crossings is not really useful and negatives of rendering them (makes code & map more complex, #2074) IMHO outweight positives.

See #2063, #1630

**Comment by polarbearing** [comment]
I see a positive effect in having both bridge or level_crossing shown. Otherwise the absence of a bridge tag implies level crossing, while the bridge tag might just be missing. And, in contrast to the disused level_crossing in #2074, I do have to pay extra attention when crossing an active one.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 06.03.2016 um 01:55 schrieb polarbearing <notifications@github.com>:
> 
> Otherwise the absence of a bridge tag implies level crossing


no, because at a bridge the road will not have a common road with the rails, while a level crossing will, so this is not only a question of tags but also topology

**Comment by matkoniecz** [comment]
> I do have to pay extra attention when crossing an active one

It is a good reason to handle it in navigation app but I am not sure how it is useful in this map style.

**Comment by aceman444** [comment]
A level crossing may have additional properties (like barriers, lights) which may be useful for navigation apps. The mere intersection of a highway and a railway is not always enough. Also, for disused/abandoned railways, there may not even be a real level crossing (while there is an intersection) and you can drive full speed over it. So tagging it is useful. I agree rendering it is a different matter.

**Comment by aaronstar** [comment]
I support that this tag is continued to be rendered

**Comment by nighto** [comment]
Hello!

 

You have a new message, please read <http://atm-bg.com/seek.php?k2>

 

nighto@nighto.net

**Comment by matkoniecz** [comment]
After implementing and testing I see no reason to support this idea.
