### ISSUE TITLE
historic=monument, tourism=information should display a monument icon

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2076]
see for example http://www.openstreetmap.org/node/4042168387#map=19/49.54256/20.11262

![selection_004](https://cloud.githubusercontent.com/assets/899988/13549811/2ba0cc20-e30e-11e5-9019-5573a86dd6b7.png)

**Comment by polarbearing** [comment]
Is that really a [monument](http://wiki.openstreetmap.org/wiki/Tag:historic=monument) in the OSM meaning? How does it look like on the ground?

Similarly this [wayside cross](http://www.openstreetmap.org/node/4042168375) nearby might deserve a [different tag](http://wiki.openstreetmap.org/wiki/Tag:historic%3Dwayside_cross)?

**Comment by matkoniecz** [comment]
@polarbearing I replied on http://www.openstreetmap.org/changeset/37632715 (as this problem exists even if this case is a tagging error).

**Comment by polarbearing** [comment]
Thanks, I have found the CS discussion and commented there.

I think that the combination historic=monument + tourism=information is rather unusual when tagged correctly. The monument should be monumental enough to be mapped as a polygon, and the information insignificant in relation so it would be a node inside/nearby.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 11.03.2016 um 11:04 schrieb polarbearing <notifications@github.com>:
> 
> I think that the combination historic=monument + tourism=information is rather unusual when tagged correctly.


this is generally common: mixing of different features into one object (e.g. buildings and functions in the buildings, also barriers like fences and the area they encircle).

**Comment by Tomasz-W** [comment]
There are only 25 nodes with this problem on whole map. Part of them are just bad tagged `man_made=obelisk`, and part of them means a memorial plaque on a monument, which is actually its inregrated part, and tagging it as `tourism=information` + `information=board` is also a mistake. I'll try to repair these bad tagged nodes. 

Please close this ticket.
