### ISSUE TITLE
Cycle/Transport style uses ugly bezier lines

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#2079]
Consider https://www.openstreetmap.org/note/520498#map=18/51.55126/9.94087&layers=C .
What is this, 'Comic Sans' for maps?

Anyhow, it appears that the map is rendered using bezier lines. This does not look very appropriate, in particular for the service=parking_aisle ways which, as a result, are all squiggly over the place. I reckon the bezier style may make (some) sense, but given almost all ways are not arranged in such a way as to support bezier rendering.

**Comment by HolgerJeromin** [comment]
This repository is the style for "default" not for cycle or transport style...

**Comment by dieterdreist** [comment]
sent from a phone

> Am 06.03.2016 um 19:39 schrieb jengelh <notifications@github.com>:
> 
> Anyhow, it appears that the map is rendered using bezier lines.


while I agree (problem is that you can't tell from the data if a way is curved or with corners/angular), this is not the right bug tracker, it is only for the osm-carto style
