### ISSUE TITLE
Add basic documentation for scripts

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2080]
We have just a few scripts in this repo, but none of them is currently documented and their detailed purpose is not obvious. It would be good to include simple comment inside the code and let the script print some informations when called without arguments. Nice README.md would be useful here.

**Comment by matkoniecz** [comment]
> Nice README.md would be useful here.

Probably comment at beginning of the script file would be better.

**Comment by kocio-pl** [comment]
It was just a serving suggestion :smile: - details are up to script authors.

**Comment by math1985** [comment]
Related stackoverflow question, illustrating how the current situation confused new users: http://gis.stackexchange.com/questions/183459/styling-osm-data-with-osm-carto

**Comment by nebulon42** [comment]
Slightly OT: When carto 0.16 has been released, it would be possible to get rid of ` 	travis_check_project_files` and `yaml2mml.py` as carto will support YAML MML.

**Comment by pnorman** [comment]
> Slightly OT: When carto 0.16 has been released, it would be possible to get rid of travis_check_project_files and yaml2mml.py

We also need to wait for carto 0.16 to be picked up by at least Kosmtik, and ideally Tilemill as well

> And instead of doing distance calculations in generate_road_colours.py it might be possible to use the HuSL perceptual color space, which will also be included in carto 0.16

Distance calculations will still need a conversion to CIELAB. We've been using [CIE76 colour-difference](https://en.wikipedia.org/wiki/Color_difference#CIE76) for simplicity, and it's defined in Lab. Interpolation should also be done in Lch or Lab.

Given that it all gets converted in the end and the colours are generated by a script and not designed to be edited by hand, we should avoid converting from Lab to HuSL ourselves then HuSL to RGB in Mapnik, as this will introduce more error.

Also, we still need RGB for the road shields.

**Comment by springmeyer** [comment]
> We also need to wait for carto 0.16 to be picked up by at least Kosmtik, and ideally Tilemill as well

Last weekend I got TileMill tests passing again in master (on personal time, not mapbox), so it should be ready for an upgrade of Carto.

**Comment by kocio-pl** [comment]
Great - with [Carto 0.16](https://github.com/tilemill-project/tilemill/pull/2551), [TileMill](https://github.com/tilemill-project/tilemill/commit/b8d74f5842a417b0e774edfa877ffa08d6d89fa4) and [Kosmtik](https://github.com/kosmtik/kosmtik/blob/008db9517bea57e160f0838b0c25898dbc43ca1a/test/loader.js#L17) being ready, we could probably get rid of the MML problem now!

The only remaining question is what Carto version is running on OSM servers?

After removal [_Dependencies_ section in INSTALL.md file](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#dependencies) should be updated too.

**Comment by gravitystorm** [comment]
I don't like saying that you need "tilemill from master" since that doesn't allow people to check if their currently installed version is actually new enough. So I don't think that Tilemill is actually ready, but it will be after the next tag / release of tilemill.

**Comment by StyXman** [comment]
FYI: Tilemill has not been tagged since October 2012 (at least in the [new](https://www.mapbox.com/blog/fall-cleaning/) [public repo](https://github.com/tilemill-project/tilemill)).

**Comment by kocio-pl** [comment]
Would it be enough to ask @tmcw for example (as he's active lately) to tag a new release?
