### ISSUE TITLE
leisure=ice_rink is not rendered

### ISSUE THREAD

**Issue by Inyaheyukan** [gravitystorm/openstreetmap-carto#2083]
leisure=ice_rink is not rendered

See here: [http://www.openstreetmap.org/#map=19/52.53705/13.36909](http://www.openstreetmap.org/#map=19/52.53705/13.36909)

**Comment by HolgerJeromin** [comment]
see #796

**Comment by matkoniecz** [comment]
@HolgerJeromin - thanks!
