### ISSUE TITLE
mandatory pedestrian ways disappeared

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#2084]
OSM.org is showing the **possible way**s that vehicle and pedestrian **can follow**, doesn't it?
Well, pedestrian crossings are ways that the pedestrians are **compelled to follow** but they disappeared from the map.

**Comment by polarbearing** [comment]
Please describe clearly what has disappeared, what was there before, and when.

This map style renders a subset of features that are in the OSM database, not possibilities. 

If you want to discuss that pedestrian crossings should be rendered, that is already discussed in #1943

**Comment by drkludge** [comment]
On Tue, Mar 8, 2016 at 5:06 PM, polarbearing <notifications@github.com>
wrote:

> Please describe clearly what has disappeared, what was there before, and
> when.
>
> This map style renders a subset of features that are in the OSM database,
> not possibilities.
>
> If you want to discuss that pedestrian crossings should be rendered, that
> is already discussed in #1943
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1943>
>
>
> Here is a highway=pedestrian area.  I don't know if area area or way makes
a difference.
http://www.openstreetmap.org/way/115940362#map=19/33.44890/-112.07409 .  In
addition, there are a bunch of crossing.
http://www.openstreetmap.org/way/115940362#map=18/33.44910/-112.07295&layers=C
 Note however, that I had to switch the Cycle Map to see the crossings
reander.
AS of 3/8/2016 at 21:18, both of these features still render.

Regards,
Greg

**Comment by matkoniecz** [comment]
> Note however, that I had to switch the Cycle Map to see the crossings reander.

"Pedestrian crossings not visible" is discussed in #1943

**Comment by a-pirard** [comment]
Please reopen this issue.
It has little to do with #1943 which goes a long way discussing styles.
It is about crossings like
http://www.openstreetmap.org/node/1312239864
http://www.openstreetmap.org/node/1533108508
and many others, all I reckon, that have been **removed** from the map in a recent rendering update.
As I say, they are important for the map to show a GPS route for example, especially that one that children must use to go to their school.
This issue has been discussed on Tagging@osm.org.

**Comment by matkoniecz** [comment]
Rendering of highway=crossing is covered by #1318 and #1943.

highway=crossing tag was never rendered in this style

**Comment by a-pirard** [comment]
On 2016-04-01 17:47, Mateusz Konieczny wrote:
>
> Rendering of highway=crossing is covered by #1318
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1318> and
> #1943 <https://github.com/gravitystorm/openstreetmap-carto/issues/1943>.
>
> highway=crossing tag was never rendered in this style
>
OK, I'll stop mapping crossings until they are useful and they and I can
see which one is missing.
It's a pity to have drawn these ways and steps
<http://www.openstreetmap.org/node/4046783672> and to be unable to
continue the access to the building with just a simple line meaning a
crossing.

**Comment by matkoniecz** [comment]
> OK, I'll stop mapping crossings until they are useful and they and I can see which one is missing.

Note that highway=crossing is rerndered in some styles like http://tile.openstreetmap.fr/?zoom=19&lat=48.86486&lon=2.40945&layers=B0000000FFFFFF

**Comment by a-pirard** [comment]
On 2016-04-01 19:13, Mateusz Konieczny wrote:

> Note that highway=crossing is rerndered in some styles like
> http://tile.openstreetmap.fr/?zoom=19&lat=48.86486&lon=2.40945&layers=B0000000FFFFFF
>
Nice, but I have problems getting people interested in a single OSM.org
already.
What if I would have to show them a catalog of other maps depending on
what they want to see such as ubiquitous and useful features as
pedestrian crossings, ride sharing stop posts like bus stops, amusements
in a park, etc...
That is not asking for extravagance, is it.

**Comment by nighto** [comment]
Hello!

 

You have a new message, please read <http://wewik.org/consumption.php?pxv>

 

nighto@nighto.net
