### ISSUE TITLE
traffic_calming=island

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2086]
I want to discuss rendering of [traffic calming islands](http://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland).
Islands at a [junction](http://wiki.openstreetmap.org/wiki/File:Junction_with_central_island.jpg) or [end of a road](https://www.mapillary.com/map/im/HYgmG8VyNcAk5r4dYWXc6Q) could render like a miniroundabout, but in a [normal way](http://wiki.openstreetmap.org/wiki/File:Trafficcalming-island.jpg) this would be missleading.

**Comment by matkoniecz** [comment]
I am not entirely sure is it a good candidate for rendering.

**Comment by HolgerJeromin** [comment]
My concern is primary about the really "large" mini_roundabout like thing. It is nearly the same as a mini_roundabout or turning_circle, but without a sign in the middle. 

I am with you, that the island in a normal way should not be renderd.

**Comment by HolgerJeromin** [comment]
Should we have another tag to be able to differ these two?

**Comment by matkoniecz** [comment]
> mini_roundabout or turning_circle, but without a sign in the middle. 

Note that mini_roundabout and turning_circle does not require "a sign in the middle".

**Comment by HolgerJeromin** [comment]
http://wiki.openstreetmap.org/wiki/Tag:highway%3Dmini_roundabout has a table of images. One entry is:
"Don't let the island confuse you: there are indications neither of a one-way nor of right-of-way, so this is just a junction with an island used for traffic calming."
exactly the situation of my examples.

**Comment by kocio-pl** [comment]
I've just tried to add the code for it, but roads are very complex issue in this style, so I may try again later. Could anybody help me with that?

**Comment by math1985** [comment]
Exactly why I proposed keeping v3 compatible with other osm2pgsql stylesheets - unfortunately @pnorman disagreed. We could still consider reintroducing compatability at v5.

**Comment by kocio-pl** [comment]
@math1985: Looks to ma like a comment to another issue (https://github.com/gravitystorm/openstreetmap-carto/issues/2666#issuecomment-316991887 probably)?

BTW: Adding `tags->'traffic_calming' as traffic_calming,` to `highway-area-fill` layer works only when there's a `highway=*` tag, but not when there's only `traffic_calming + area=yes`. SQL expert is needed... :smile:

**Comment by SomeoneElseOSM** [comment]
Just a thought, but now that lua is available (notwithstanding the v3/v4 discussion) surely it'd be a lot easier to consolidate features there rather than adding yet more complication to the existing SQL?  It would mean that existing "traffic_calming" wouldn't get rendered until they're modified or the database is reloaded, but in the case of a simple feature add this is less of an issue I think.

**Comment by kocio-pl** [comment]
We have no plans for next database reload, however it seems that we would wait about 6 months (see https://github.com/gravitystorm/openstreetmap-carto/issues/1286), so it can help only with big features.

**Comment by Tomasz-W** [comment]
Just for the note: color used in visualitation from my comment above is #bebebe

Is anybody interested in writing code for this issue?

**Comment by Adamant36** [comment]
Any idea how this should be rendered? are we going with both traffic_calming=island as a point on the road and area:highway=traffic_island as a separate area or are we favoring one over the other? I could see the advantages and disadvantages of both. There's currently 7,383 uses of area:highway=traffic_island and 25,689 uses of traffic_calming=island. Traffic_calming=island is clearly the more popular tag. It seems as though uses of area:highway=traffic_island are petering out, while Traffic_calming=island is growing rapidly. 
![taghistory](https://user-images.githubusercontent.com/30259065/45601939-d2bd8180-b9c9-11e8-9ac3-16c66fe2db11.png)

**Comment by Tomasz-W** [comment]
@Adamant36 As we don't support area:highway=* key at the moment please include only traffic_calming=island. Rendering of traffic calming nodes/ linear ways would propably cause mess on roads, so I mean only areas with `#ceced3` fill.

**Comment by jeisenbe** [comment]
Several comments above suggest that this is not a good candidate for rendering, unless `area:highway` was also rendered at high zoom levels.
