### ISSUE TITLE
Render societal amenity campuses with educational/hospital yellow

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#2087]
In #2071 it was discussed that more campuses of societal amenities should be rendered with the yellow currently being used for educational and hospital areas. The idea sprung from the proposal to use this colour even for sports centres. However, in the continuum of useful facilities, sports centres are further away from educational that things like social or community centres.

Thus, the colour should be renamed from `@educational_areas_and_hospital` to `@societal_amenities`, and applied to the following areas (when not a building) of _Societal amenities_ (see #1624):
- amenity=kindergarten/school/university/college (as is)
- amenity=hospital (as is)
- amenity=community_centre (discussed in #506)
- amenity=social_facility (fixes #1295)
- amenity=police/fire_station (fixes #848)
- amenity=embassy (mentioned in [#775](https://github.com/gravitystorm/openstreetmap-carto/issues/775#issuecomment-136331438))

Further, the labelling should scale consistently, currently educational scales, hospital doesn't.

**Dependencies:**

Icons should be added to the kindergarten/school/university/college as in #120, to distinguish them better. We do have icons meanwhile for the community_centre and social_facility.

**Comment by imagico** [comment]
> However, in the continuum of useful facilities, sports centres are further away from educational that things like social or community centres.

Note this is a subjective assessment and more important it is very culture specific (both in terms of overall culture of a country and in terms of subculture).

The primary purpose of #2071 is reducing the number of colors, this issue seems to be about adding new features - which is hardly feasible to do with new colors.  Then the question would only be if another existing color would be more appropriate - to which the answer is likely no - both for the majority of the above and for sport_centre.

**Comment by math1985** [comment]
I'm still not very sure what to think of this. On the one side, I think there is a need to indicate all campus outlines, and I realize the colour spectrum is limited. On the other hand, I also got quite attached to having yellow as a recognizable school colour.

I think we should also think well about from which zoom level we would like the yellow to show up.

**Comment by kocio-pl** [comment]
> On the other hand, I also got quite attached to having yellow as a recognizable school colour.

But it's already not enough in itself to recognize it - you need some additional objects inside (like pitches) or lack of icons (like for hospital - on z>=15, earlier you can't be sure). Adding icons for schools will keep it distinct enough IMO.

BTW we were also talking about:
- amenity=fire_station
- landuse=religious

I like this proposition in general.

**Comment by math1985** [comment]
I think at this point it would be good to have a mock-up, preferably of a well-mapped area, to judge whether this idea works or not.

**Comment by math1985** [comment]
I think it would be also worth trying police and embassy might in commercial-colour rather than yellow.

**Comment by math1985** [comment]
Or perhaps we could use a shade of gray slightly darker than residential?

**Comment by kocio-pl** [comment]
Another time, when we lack some system. Plus "amenity" is so generic, that it consists of many not too specific categories.

BTW - if I was to free one color for more general use or just enhance its scope, it would be landuse=garages.

**Comment by polarbearing** [comment]
Added fire_station to top post. Not so sure about landuse=religious. While I'd like to see it rendered, and it is a type of campus, it feels a bit different than the other. 

> Or perhaps we could use a shade of gray slightly darker than residential?

For which? I had that in mind for the religious.

**Comment by EdLoach** [comment]
I recently retagged [a hospice](http://www.openstreetmap.org/way/352589191) from amenity=hospital to amenity=social_facility/social_facility=nursing_home, as recommended on the wiki for what was amenity=hospice, and threw in a healthcare=hospice for good measure as that is also mentioned on the wiki. I suspect it was tagged as hospital to make it show. I'm not sure this is the right issue to comment on, but based on the title and it being open I hope it is. An outline for the area would improve things a bit, but a different colour to the residential area behind it would be better too, which is what I think is suggested here, although no updates recently.

**Comment by dieterdreist** [comment]
2017-06-22 2:09 GMT+02:00 EdLoach <notifications@github.com>:

> I recently retagged a hospice <http://www.openstreetmap.org/way/352589191>
> from amenity=hospital to amenity=social_facility/social_facility=nursing_home,
> as recommended on the wiki for what was amenity=hospice
>

IMHO the wiki has overreacted with the acceptance of the social_facility
tag. There are not sufficient documented subtags for the social facility,
and retagging makes us loose information. A nursing home is not the same as
a hospice. I'd retag it to amenity=hospice and change the wiki. Although
overall numbers are low, there is still a constant growth of this tag since
2008: http://taghistory.raifer.tech/

**Comment by kocio-pl** [comment]
I guess it's safe and makes sense now to make amenity=community_centre and amenity=social_facility yellow, see this reasoning:

https://github.com/gravitystorm/openstreetmap-carto/issues/1624#issuecomment-350416072

**Comment by matthijsmelissen** [comment]
Fine with me.

**Comment by polarbearing** [comment]
Most of the areas are now rendered, the remaining should be discussed in a fresh issue: #2985.
