### ISSUE TITLE
Floating dock rendering

### ISSUE THREAD

**Issue by malcolmh** [gravitystorm/openstreetmap-carto#2088]
An object tagged waterway=dock + dock=floating is usually situated offshore & hence the normal dock rendering (water) makes it invisible. There should be a (quite thick) solid outline for this tag combination to render it visible.

**Comment by matkoniecz** [comment]
As https://wiki.openstreetmap.org/wiki/Tag:dock%3Dfloating is used 136 times worldwide I am not convinced that rendering support is a good idea.

**Comment by mboeringa** [comment]
If rendering is desired, it would be wiser to create a generic rendering for waterway=dock instead of a custom one just for floating docks. Docks are pretty well tagged with almost 2500 way features:

https://wiki.openstreetmap.org/wiki/Tag:waterway%3Ddock

**Comment by malcolmh** [comment]
Good idea - if all docks were rendered with a solid border of a colour that contrasts with the water colour, then this would work for floating docks as well, making them visible.

**Comment by BalooUriza** [comment]
Minor nitpick:  I think we're talking about piers (floating or otherwise).
A dock would be where the boat floats in the water next to the pier,
usually with amenities for tying down.  It's roughly the waterway
equivalent to a parking space.

**Comment by malcolmh** [comment]
No, we are talking about floating docks - this is a dry dock where the dock itself is sunk below a ship and then re-floated to raise the ship's keel above the water level. The picture https://wiki.openstreetmap.org/w/images/thumb/c/c8/Ship-Dock.jpg/200px-Ship-Dock.jpg shows such a structure with a ship in it after the dock has been re-floated.

Beware of the en-US misuse of the word "dock"!

**Comment by BalooUriza** [comment]
Either way, we're still talking about the place the ship goes, not the
(usually) pier structure that may be adjacent (which en-us usage often is
called a dock among people who don't leave shore)?

**Comment by pnorman** [comment]
Being a specialized feature with only 136 uses, this is not a good target for a general purpose rendering.

**Comment by imagico** [comment]
However it could be worth considering not rendering waterway=dock in water color in general.  The current rendering does not exactly encourage correct tagging - after all dry docks are usually dry most of the time.

Of course using the waterway key here is fairly inappropriate anyway - man_made=dock or building=dock would make much more sense in principle.

**Comment by matkoniecz** [comment]
> However it could be worth considering not rendering waterway=dock in water color in general.

Creation of a new issue is cheap - if somebody thinks that such change would be a good idea: please open a new issue.
