### ISSUE TITLE
Barrier=retaining_wall and Barrier=fence are rendered the same way

### ISSUE THREAD

**Issue by aaronstar** [gravitystorm/openstreetmap-carto#2091]
Hi there,
Recently when I was mapping the retaining walls and fences in a local area I noticed that they are displayed in the same way for a significantly different function.

In this image a fence is on the left and a retaining wall on the right
![fencebarrierosm](https://cloud.githubusercontent.com/assets/10798165/13903141/328bccaa-eea9-11e5-9a47-6c1bffbdba78.png)

Fences are generally continuous features on flat(ish) land with the exception of the entrance or exit whilst retaining walls generally are intermittent features which have significnat height difference on each side of the linear way feature. I suggest that either fence be updated to have cross-hatching (-------+--------+---------+----- etc.) or that the retaining wall have either dots or hachures on one side of the line as already implemented in natural=cliffs.

See [this](http://wiki.openstreetmap.org/wiki/Talk:Proposed_features/bare_rock#bare_rock_proposal) wiki talk page for some reference

This image from the [wiki](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dretaining_wall) provides an example of rendering, note the barrier=retaining_walls are at the bottom of the image in grey
![city_wall_render_eg1](https://cloud.githubusercontent.com/assets/10798165/13903174/4062458c-eeab-11e5-93e0-1b57a1aa267a.png)

**Comment by dieterdreist** [comment]
sent from a phone

> Am 20.03.2016 um 07:49 schrieb aaronstar <notifications@github.com>:
> 
> Fences are generally continuous features on flat(ish) land with the exception of the entrance or exit whilst retaining walls generally are intermittent features which have significnat height difference on each side of the linear way feature.
> 



fences also occur atop retaining walls, cliffs, roofs or any other situation where you'd want to prevent people from falling down, they are not limited to "flattish" situations 


> I suggest that either fence be updated to have cross-hatching (-------+--------+---------+----- etc.)
> 


IMHO this would suggest pole/post positions, and be confusing/misleading if it wasn't those positions 


> or that the retaining wall have either dots or hachures on one side of the line as already implemented in natural=cliffs.
> 

thinkable, but the more linetypes we introduce the more complex it gets to read the map

**Comment by matkoniecz** [comment]
I think that it is not desirable to use various line colours this way.

Also I would consider

> significantly different function (...) Fences are generally continuous features on flat(ish) land with the exception of the entrance or exit whilst retaining walls generally are intermittent features

to strongly depend on a location and not clear enough to warrant a different rendering. There are really big differences among various things tagged as barrier=fence.

**Comment by aaronstar** [comment]
I would like to note that this issue is in reference to the lack of clarity with barrier=retaining_wall (rather than barrier_fence), (but I proposed changes to both in the original comment as a means of flexibility, changes to barier=retaining_wall would be preferred), also that the image from the wiki shows the retaining wall in greyscale, and does not propose a line colour change from the existing colour?

I agree with dieterdreist that retaining walls can have fences on top of them, in such a case perhaps the retaining wall would be the prevailing feature (in the case of dual tagging), an image is provided below of this situation:

![hong-kong-snapshot_8](https://cloud.githubusercontent.com/assets/10798165/13903372/dcb01868-eeb2-11e5-9cef-f345a7a5b98a.jpg)

Also I totally agree that fences occur on various types of topology and have a wide variety of applications (and differences) from their uses as barriers (intermittent) to cadastral and boundary markers (continuous) or deliniating different types of property, in this case the function or application of the barrier=fence tag is irrelevant.

The purpose of the comparison to the fence tag in the original comment was to highlight that the inherent function of a retaining wall is to retain soil or something similar. Retaining walls generally, always have a height difference between each side of the wall versus a fence which may or may not, but that difference is generally nothing beyond natural height differences, unless the fence is also associated with a retaining wall.

In practical applications a retaining wall is not able to be navigated up or down by pedestrian traffic, including if you map it really poorly, while you could navigate through a fence, as the fence may have gates in it or be poorly mapped and miss details such as openings or breaks in the fence. I would assoicate a barrier=retaining_wall to be more similar in defintion to natural=cliff but rather being man-made. 

If you were planning a journey through a poorly (or well) mapped area and you saw a retaining wall or cliff on the map you would know to go around it, there would be no way to navigate up or down it, while if you saw a fence (depending on the context of the map area you are looking at, rural, urban, peri-urban, what country) along a property line you would know to go towards it so you can cross it (see below)
![img_0028_1 jpg](https://cloud.githubusercontent.com/assets/10798165/13903481/fa10ba5c-eeb7-11e5-9c89-254436d5d675.png)
  
or find the gate (see below)
![screenshot 2016-03-20 16 25 51](https://cloud.githubusercontent.com/assets/10798165/13903494/b4e9aa46-eeb8-11e5-9f2a-26cdf70908a4.png)

(Note in the above image I would not consider the short roadside barrier a fence, but rather a barrier, and that barriers are generally intermittent opposed to fences which are continuous)

I urge you to reconsider the wider implications and usage of this issue and the proposal.

Kind Regards,
Aaron Sta

**Comment by imagico** [comment]
It could be considered rendering [barrier=retaining_wall](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dretaining_wall) like [man_made=embankment](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dembankment).  Of course it would be somewhat tricky to decide on a starting zoom level since a retaining_wall is essentially a horizontally scaleless feature.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 20.03.2016 um 09:31 schrieb aaronstar <notifications@github.com>:
> 
> In practical applications a retaining wall is not able to be navigated up or down by pedestrian traffic, including if you map it really poorly, while you could navigate through a fence, as the fence may have gates in it or be poorly mapped and miss details such as openings or breaks in the fence.


both features typically are barriers and cannot be navigated through, besides very low fences or retaining walls, or through other features (openings, gates, ladders / stairs, etc.)

**Comment by aaronstar** [comment]
>There are really big differences among various things tagged as barrier=fence.



> both features typically are barriers and cannot be navigated through, besides very low fences or retaining walls, or through other features (openings, gates, ladders / stairs, etc.)

These are very valid points
Following further research and in combination with this thread I am now less clear on the rendering this feature different from barrier=fence
