### ISSUE TITLE
Render building with ruins=yes differently

### ISSUE THREAD

**Issue by valhentai** [gravitystorm/openstreetmap-carto#2093]
[ruins=yes](http://wiki.openstreetmap.org/wiki/Key:ruins) is not taken into account for rendering.

A building with **ruins=yes** could be rendered with dashed border or/and stripped fill to show that the building is not a complete building. 

This is the rendering of **historic=ruins** in OsmAnd. We could render **building=⁎** and **ruins=yes** in a similar way.
<img src="https://cloud.githubusercontent.com/assets/13367963/13905935/5ccb1be6-eecd-11e5-9253-9f47c314b7f3.png" width="400">

**Comment by matkoniecz** [comment]
" Add rendering for historic=ruins" is covered by #331

**Comment by valhentai** [comment]
@matkoniecz I edited the issue to leave only the **ruins=yes** part.

**Comment by math1985** [comment]
Do you have an example how you you would use this tagging? amenity=pub+ruins=yes? amenity=place_of_worship + ruins=yes? Doesn't seem like particular good tagging.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 21.03.2016 um 09:43 schrieb math1985 <notifications@github.com>:
> 
> Do you have an example how you you would use this tagging? amenity=pub+ruins=yes? amenity=place_of_worship + ruins=yes?


ruins are likely buildings or similar structures (walls, retaining_walls, monuments, towers, castles, bunkers, bridges, surveillance stations, dams,...), so neither of the above examples makes sense (they are describing functions ).

What about ruins=foo ? It's used much less, but still has more than the occasional occurrence it would have if used by just a handful of mappers: http://taginfo.osm.org/keys/ruins#values

Another scheme in use is ruins:building=* (but even fewer uses)

**Comment by valhentai** [comment]
The [ruins tag wiki](http://wiki.openstreetmap.org/wiki/Tag:historic%3Druins) say that **historic=ruin** should be used when there is no more specific tag to use. else **ruins=yes** should be used.
The most frequent example is a castle (**historic=castle**) which could be in good state or in ruins.
The [historical object map](http://gk.historic.place/historische_objekte/translate/en/index-en.html) use the tag ruins=yes to render the icon differently if the building is a ruin.
<img src="https://cloud.githubusercontent.com/assets/13367963/13913788/2a106c42-ef4a-11e5-997f-640d2ddebf62.JPG" width=400 />

**Comment by dieterdreist** [comment]
sent from a phone

> Am 21.03.2016 um 10:00 schrieb valhentai <notifications@github.com>:
> 
> The ruins tag wiki say that historic=ruin should be used when there is no more specific tag to use


there will always be a more specific tag if not for the very few occasions where it is completely unknown what the structure was (unlikely), and even these cases will typically be archaeological sites (already a generic tag for these). By introducing and supporting overly generic tags we will slow down the creation of tags that better describe the thing.

**Comment by valhentai** [comment]
The **ruins=yes** has to be used with a specific tag. not alone.
for example **historic=castle** + **ruins=yes** where castle is the specific tag.
The probleme with **historic=castle** is that it exlude historic=ruins. So without **ruins=yes**, the information "This castle is in ruins" can't be added.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 21.03.2016 um 10:33 schrieb valhentai <notifications@github.com>:
> 
> The probleme with historic=castle is that it exlude historic=ruins. So without ruins=yes, the information "This castle is in ruins" can't be added.


historic=ruins
ruins=castle

**Comment by valhentai** [comment]
In my second comment, I was awsering the comment before your.
I have the impression you thought I was opposing to your awnser but i was not. I completly agree with
**ruins=foo**. 
I just see a problem in the case of castles. I think someone doing a query on historic=castle expect to get castle in ruins too.
with historic=castle and ruins=castle, queries on castle or ruins can work

**Comment by dieterdreist** [comment]
> Am 21.03.2016 um 12:11 schrieb valhentai <notifications@github.com>:
> 
> with historic=castle and ruins=castle, queries on castle or ruins can work


+1, I was referring to the original demand to render ruins=yes. Modifiers of this kind (additional tags that significantly change the meaning of other tags as opposed to just refining them) are generally bad (similar cases are disused/abandoned/destroyed/removed/dismantled/functional/working/...=yes/no) and should not be "endorsed" by picking them up

The historic key is somehow special anyway, as it already bears a relationship with the past in it.

**Comment by valhentai** [comment]
My idea was to modify the rendering of building=⁎ when there is a tag ruins=⁎.

it will be used like this
`building=yes ,
ruins=restaurant or ruins:amenity=restaurant`
But not 
`amenity=restaurant
, ruins=yes`

**Comment by dieterdreist** [comment]
sent from a phone

> Am 21.03.2016 um 14:14 schrieb valhentai <notifications@github.com>:
> 
> building=yes ,
> ruins=restaurant or ruins:amenity=restaurant


As the tagging is apparently not yet settled this should be discussed on the tagging mailing list, not here

**Comment by pnorman** [comment]
`building=yes ruins=yes` is similar to the case of `disused=yes`, which as a matter of policy, we do not use.

From the OpenStreetMap Carto perspective, `building=yes ruins=yes` is a building, so is rendered like other buildings.
