### ISSUE TITLE
enable pull request squashing

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2103]
I think that it would be a good idea to enable https://github.com/blog/2141-squash-your-commits - sometimes it is useful to squash PR and this method may be faster and less error prone than doing it manually.

**Comment by pnorman** [comment]
Squash merging isn't my preferred strategy as it loses history

**Comment by matkoniecz** [comment]
It certainly is not something that should be always used, especially not for PRs with meaningful diffs.

But sometimes PRs are "fix <something>", "fix syntax error", "fixing stuff" etc where history is not useful.

For example https://github.com/gravitystorm/openstreetmap-carto/commit/42cd70e6dba515478fd5a095cc837d5e03c86fe4 was result of manual squashing of #1452.

**Comment by pnorman** [comment]
If we squish something because the history in the branch is not useful, we still want a merge commit

**Comment by matkoniecz** [comment]
As there is no clear support I am closing this.
