### ISSUE TITLE
Render site relations

### ISSUE THREAD

**Issue by Grillmannen** [gravitystorm/openstreetmap-carto#2108]
Site relations are currently not rendered. This is a problem since they require tagging on both the object and the relation for rendering, which is, AFAIK, tagging for the renderer.

This [1] example was double tagged and I tried to remove the tags on the objects but then the objects disappeared from the map. As the relation is tagged with the same tags as the separate objects would be tagged it seems logical these could be rendered in the same way as multipolygons are tagged.

If I've misunderstood how a site relation is supposed to be used this would also be the place to let me know...

[1] http://www.openstreetmap.org/relation/3060532

**Comment by matkoniecz** [comment]
Given that nobody thought that proper documentation of that relation would be important (see http://wiki.openstreetmap.org/wiki/Relation:site ) I think that despite high relation count it is not well established tag.

Also, is anybody rendering this relation?

**Comment by matkoniecz** [comment]
And from sparse documentation 

> A way to group of features, for example buildings or amenities, which belong together. Examples: the various dispersed facilities associated with a school, college, university, airport or military bases.

> It may contain number of buildings, one or more boundaries, and maybe other amenities such as swimming pools or tennis courts. 

it seems to be used as category of objects, not to tag a single object 

Also, http://www.openstreetmap.org/relation/3060532 seems to be a candidate for http://wiki.openstreetmap.org/wiki/Relation:multipolygon (that unlike site relation is well established).

**Comment by mrwojo** [comment]
I don't expect there'll be a general way to render site relations because the members should not necessarily have the same representation as the whole.

Consider this example from the [proposal](http://www.openstreetmap.org/relation/3006785) (cf. #1678):

http://www.openstreetmap.org/relation/3006785

The site is `amenity=parking` and the members are `amenity=parking_entrance`. I don't think it'd be appropriate to represent them all as `amenity=parking`.

**Comment by Grillmannen** [comment]
You are right. It seems I have misunderstood how the site relation is supposed to be used...

**Comment by dieterdreist** [comment]
2016-04-06 12:33 GMT+02:00 Mateusz Konieczny <notifications@github.com>:

> Given that nobody thought that proper documentation of that relation would
> be important (see http://wiki.openstreetmap.org/wiki/Relation:site ) I
> think that despite high relation count it is not well established tag.
>

+1, very well put. Really appreciate that we don't look at numbers (only).

**Comment by mboeringa** [comment]
> If I've misunderstood how a site relation is supposed to be used this would also be the place to let me know...
> 
> [1] http://www.openstreetmap.org/relation/3060532

For this particular example with two closed ways belonging to the same facility, there is a viable alternative: create a multipolygon relation of the two closed ways, and add the "site" tags to the multipolygon.

This "workaround" is only useful for "sites" that consist solely of closed ways / polygons. You can not mix or combine different geometry types with this (combining individual nodes and ways in the relation).

This alternative option is also mentioned on the http://wiki.openstreetmap.org/wiki/Relations/Proposed/Site Wiki page.

**Comment by matkoniecz** [comment]
> This "workaround" is only useful for "sites" that consist solely of closed ways / polygons. You can not mix or combine different geometry types with this (combining individual nodes and ways in the relation).

This discussion is offtopic here, can we continue it at http://wiki.openstreetmap.org/wiki/Talk:Relations/Proposed/Site#why_not_just_use_multipolygon.3F ?

**Comment by jojo4u** [comment]
For future reference when talking about the site relation: The documentation is in the proposal namespace, the feature page now redirects to it. And the usage count is around 16.000 when subtracting imports of NAPTAN and french IGN data, which is also documented on the wiki page.

**Comment by SomeoneElseOSM** [comment]
As an aside, I did have a look (completely separately to this style) to try and see if it was possible to infer what mappers meant when they used site relations with a view to rendering something.  Beyond "this bit of data is somehow related to that bit" it wasn't possible to generalise.  I would therefore expect it to be difficult to "render site relations" when "render as what" is far from clear.

**Comment by simonpoole** [comment]
@SomeoneElseOSM digging this out because, who knows, one day there might be a database re-import. My, and I suspect the most common expectation, is to simply render the name (potentially just once, label placement is naturally not easy in this case), the individual objects should be rendered as now.
