### ISSUE TITLE
Transfer Github repository to openstreetmap

### ISSUE THREAD

**Issue by der-stefan** [gravitystorm/openstreetmap-carto#2109]
The repository should be moved to the official openstreetmap Github user:
https://github.com/openstreetmap

**Comment by pnorman** [comment]
:-1:, but assigning to @gravitystorm for a decision.

**Comment by math1985** [comment]
@der-stefan What do you see as advantages of such a move?

**Comment by HolgerJeromin** [comment]
At least the name would be easier to remember. 
And it would be made clear that this is the style for the main OSM website.

But i have no strong opinion on that topic.

**Comment by matkoniecz** [comment]
> The repository should be moved to the official openstreetmap Github user:

It would be a good idea to provide good reasons to initiate such change and avoid making such proposals without thorough research. I see no significant benefits and many potential problems (both big and small).

**Comment by pnorman** [comment]
> And it would be made clear that this is the style **for** the main OSM website.

This style is **used by** the main OSM website.

**Comment by d1g** [comment]
You may name it QWERTY, as long second word is "OpenStreetMap" or "OSM" it is perfectly searchable/usable.

I prefer more personalized maintainers rather than "group account". As long we have at least one maintainer active, there no reason to transfer development or ownership.

**Comment by pnorman** [comment]
@der-stefan hasn't elaborated on reasons for a move, so closing
