### ISSUE TITLE
Render name=* when office=yes + building=*

### ISSUE THREAD

**Issue by d1g** [gravitystorm/openstreetmap-carto#2111]
Currently, iD uses office=yes for "Offices".

I think they should be rendered at same level with supermarkets and malls because they equally important and rarely overlap.

PS. not sure if duplicate (looks like building=* + office=yes was never discussed)

**Comment by HolgerJeromin** [comment]
Do you have an example?
I checked a few, but none are important enough to render earlier:
http://www.openstreetmap.org/way/118148456 small building not important POI
http://www.openstreetmap.org/way/165814040 office of a industrial complex
http://www.openstreetmap.org/way/264635142 a big multi office building. And rendering is OK
http://www.openstreetmap.org/way/34597618 small company

**Comment by d1g** [comment]
@HolgerJeromin sure thing

http://www.openstreetmap.org/way/324550178 - "Луч"
site: http://luchcentr.ru/ more photos: http://bcinform.ru/spb/luch.html

http://www.openstreetmap.org/way/28203362 - "Золотая долина"
site: http://www.bc-russam.ru/ more photos: http://bcinform.ru/spb/zolotaya-dolina.html

Business centres are quite common, but they are not tagged as well as they should (unlike shop=malls)

**Comment by dieterdreist** [comment]
I don't think we should require any building for offices to render, neither should we encourage tagging "yes" as value for offices.

**Comment by matkoniecz** [comment]
> http://www.openstreetmap.org/way/324550178 - "Луч"
> site: http://luchcentr.ru/ more photos: http://bcinform.ru/spb/luch.html

It is now rendered from the same z-level as supermarket.

> http://www.openstreetmap.org/way/28203362 - "Золотая долина"
> site: http://www.bc-russam.ru/ more photos: http://bcinform.ru/spb/zolotaya-dolina.html

Rendering it also one zoom level earlier IMHO would not be beneficial.

I think that current building labeling works fine. Also, I see no documentation of office=yes at http://wiki.openstreetmap.org/wiki/Key:office

**Comment by math1985** [comment]
+1
