### ISSUE TITLE
Render power=catenary_mast the same as power=pole

### ISSUE THREAD

**Issue by martinum4** [gravitystorm/openstreetmap-carto#2112]
They both are used to make a power line follow a certain path and it looks really weird to have a power line like http://www.openstreetmap.org/way/412862537 just be on the map without being supported by something...
The main reason for requesting the same rendering as power=pole instead of power=tower is that they are not that huge (usually <10m) and are not really useful as landmarks as the normal powerline towers are

**Comment by matkoniecz** [comment]
power=catenary_mast is for "pylons supporting system of overhead wires used to supply electricity to electricaly powered vehicle equipped with a pantograph" and power=pole if for poles or small masts of overhead power lines.

power=minor_line is for "power lines carried on poles physically smaller than the high voltage pylons/towers" and power_line is for power lines supported by towers or pylons.

I am unaware about tagging for overhead wires supplying power to train, trams etc but I think that neither power=line nor power=minor_line should be used.

So I think that rendering problem is caused here by unstandard tagging - and http://www.openstreetmap.org/way/412862537#map=17/51.34991/9.53408 should not be tagged as power=line what will solve problem.

I think that in general rendering overhead wires supplying power to train (or masts supporting them) is not desirable, as train/tram tracks are already visible and information about overhead wires arrangement/presense is not worth additional clutter.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 24 apr 2016, alle ore 14:30, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> I am unaware about tagging for overhead wires supplying power to train, trams etc but I think that neither power=line nor power=minor_line should be used.



typically these are only mapped as attributes (electrified=yes)

**Comment by martinum4** [comment]
I do not map (and have no intention to map) the normal overhead lines for trains, i agree with you that they are indeed easily mappable by electrified=contact_line
If you have a look at http://www.merkur.de/bilder/2011/08/22/1372139/529346536-5333516_528-1LNG.jpg you can see the normal power line for the Trains on the right (electrified=contact_line) and another one carrying power on the left (power=line), these are the ones i tried to map with the way linked in the first post. These power lines are fixed to the caternary masts as shown in the picture.
If you have a look at http://www.merkur.de/bilder/2011/08/22/1372139/529346536-5333516_528-1LNG.jpg you can see the normal power line for the Trains on the right (electrified=contact_line) and another one carrying power on the left (power=line), these are the ones i tried to map with the way linked in the first post. These power lines are fixed to the caternary masts as shown in the picture.
Is it clear now what i mean or is further explaination needed?

**Comment by matkoniecz** [comment]
> these power lines are fixed to the caternary masts as shown in the picture.

What makes catenary masts also power poles - so I would expect to be mapped them also as power=pole.
