### ISSUE TITLE
possible issue with ordering layers

### ISSUE THREAD

**Issue by gorn** [gravitystorm/openstreetmap-carto#2113]
Openstreet tile http://a.tile.openstreetmap.org/19/283149/177618.png shows bad order of layers. Undeground space http://www.openstreetmap.org/way/401501790 has layer=-1 but covers a building above it http://www.openstreetmap.org/way/173673173 . It should not cover it as it is under it. I even added layer=1 to the building, but the problem persist. On other layers used at the openstreetmap.org portal it is rendered properly (with slight chance that other maps are just having old rendering, but I do not think so).

I am attaching screenshots of bad rendering

![wrong-rendering](https://cloud.githubusercontent.com/assets/19652/14712450/7b66c4f0-07dd-11e6-8ab3-d854bf882925.png)

 and correct one (from humanitarian maps)

![correct-rendering](https://cloud.githubusercontent.com/assets/19652/14712449/7b6494b4-07dd-11e6-9d64-241ed915d69c.png)

look at the building under "New yorker" shop.

PS: Please note that I am not mapnik expert, so this may be caused by something outside mapnik and feel free to correct me and point in the right direction.

PPS: Please note that this is **not a duplicate of [issue 688](https://github.com/gravitystorm/openstreetmap-carto/issues/688)** which deals with rendering highways on top of buildings. This issue is about layers.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 25 apr 2016, alle ore 16:27, Jakub Tesinsky <notifications@github.com> ha scritto:
> 
> and correct one (from humanitarian maps)


apparently they don't render highway areas at all

**Comment by pnorman** [comment]
All buildings are rendered before all highways. The tradeoffs vs rendering all highways before all buildings were considered, see #688 for some of them.

**Comment by gorn** [comment]
This is very poor design decision in case of undegraound areas with hightway=pedestrian. It basically means that all undeground metro pedesrian spaces are going to be in front of buildings.
