### ISSUE TITLE
render tourism=alpine_hut name also on z14

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2115]
tourism=alpine_hut are very important orientation points, are almost always in more remote places with low density of similarly important features.

Proposed by family member, from initial checking it seems to be a good idea.

Rendering icon also on z12 was also proposed but it seems to not be a clear improvement.

**Comment by imagico** [comment]
For areas with high hut density see Japan:

http://www.openstreetmap.org/#map=14/36.3180/137.6493
http://www.openstreetmap.org/#map=14/35.3651/138.7332

In general this is highly latitude dependent - in Northern Europe or Canada you could probably well move to z13.

Do labels for tourism=alpine_hut compete with those for natural=peak?  If yes there might be peak labels vanishing as you zoom in.

**Comment by Ircama** [comment]
Could we consider closing this issue as solved by https://github.com/gravitystorm/openstreetmap-carto/pull/2301?

**Comment by math1985** [comment]
Yep, thanks for the reminder!

By the way, you can also include the text 'resolves #2115' in the text of the pull request, and the issue will get closed automatically once the PR is merged.
