### ISSUE TITLE
include icon for shop=dairy and vending=raw milk

### ISSUE THREAD

**Issue by osm-chenshi** [gravitystorm/openstreetmap-carto#2121]
more german farmers establish own milk product stations becauce of the low milk price.

shop=dairy
amenity=vending_machine + vending=raw_milk

http://wiki.openstreetmap.org/wiki/Tag:shop=dairy?uselang=de

**Comment by pnorman** [comment]
amenity=vending_machine + vending=raw_milk is too specialized, and shop=dairy has insufficient usage to be considered
