### ISSUE TITLE
High zoom, wrong street rendering

### ISSUE THREAD

**Issue by tds4u** [gravitystorm/openstreetmap-carto#2123]
Look at this coordinate:
LatLon: 54.687510 N, 8.553498 E (Föhr, island next to Sylt, Germany)

Level 13:
![image](https://cloud.githubusercontent.com/assets/5459443/15154334/3d66759c-16dd-11e6-9866-4ea7c7476d5a.png)

Level 14:
![image](https://cloud.githubusercontent.com/assets/5459443/15154339/42f654be-16dd-11e6-9fda-5c3dd8f88a82.png)

Rendering level 13 shows streets as it should (the roundabout ones), but 14 defaced everything in it.
So, what is this? I use the latest sources.

**Comment by math1985** [comment]
Seems like a turning circle. Did you change anything to the source code?

**Comment by tds4u** [comment]
Yes, I did. But only because I inserted data via ImpOSM. But all other stuff works well.
And this not a turning circle.

**Comment by gravitystorm** [comment]
Your database import is adding closed-loop ways as polygons.

http://www.openstreetmap.org/way/23214691

It should be treating these roads as linestrings.

**Comment by math1985** [comment]
Closing the issue as it is not a problem with openstreetmap-carto, but feel free to keep asking more questions if you need further assistance.

**Comment by tds4u** [comment]
Problem is here:

```
  - id: "highway-area-fill"
    name: "highway-area-fill"
    class: ""
    # FIXME: No geometry?
```

When disabling this section all is fine, but why? No geometry is set, so is that a polygon, linestring or what else? What does this section, currently I see no difference without it?

**Comment by pnorman** [comment]
> Yes, I did. But only because I inserted data via ImpOSM. But all other stuff works well.
> And this not a turning circle.

You need to change your imposm logic to be the same as osm2pgsql - any differences are problems there.
