### ISSUE TITLE
Support the use of "abandoned:" key prefix?

### ISSUE THREAD

**Issue by RicoZ-OSM** [gravitystorm/openstreetmap-carto#2124]
http://wiki.openstreetmap.org/wiki/Key:abandoned:

Some abandoned objects such as houses or aeroways are still prominently visible on ground even though they are abandoned.

**Comment by HolgerJeromin** [comment]
Can you give an example? prefixed elements should be not visible.

**Comment by RicoZ-OSM** [comment]
http://www.openstreetmap.org/way/66830223/history#map=14/45.1601/59.2991

The aeroway is abandoned but someone added  "aeroway=runway" to get it rendered. Discussing it here http://wiki.openstreetmap.org/wiki/Talk:Key:abandoned:#Usage_of_the_lifecycle_prefix

Not aware of any rule the prefixed elements should not be visible. I think such things must be examined on specific features..  an abandoned runway is probably worth to be rendered as it is likely to be prominently visible but smaller objects may not be.

**Comment by polarbearing** [comment]
One question is its current use. See Berlin-Tempelhof as counterexample, where the former runway is used and tagged as pedestrian area: http://www.openstreetmap.org/way/280461166 

If in the first example there is no active use, tagging a paved service area might help. 

I am not in favour of rendering prefixed objects, either.

**Comment by RicoZ-OSM** [comment]
I think current-use beats abandoned-use. There is no abandoned:aeroway= tag in the Berlin example but if it were it should be disregarded in favour of rendering the current use.

Tagging it as paved service area just to get something rendered is a perfect example of tagging for the renderer.

**Comment by matkoniecz** [comment]
In case of runways rendering paved areas makes more sense than rendering disused aeroways (I have no idea whatever there is consensus how tagged areas that are not roads/footways should be tagged).

Many abandoned aeroways are now something new (see Tempelhof) or are not prominent, as it is case of abandoned grassy aeroways.

In case of ruins - is there some sort of consensus how ruins should be tagged?

**Comment by math1985** [comment]
> Tagging it as paved service area just to get something rendered is a perfect example of tagging for the renderer.


In the Tempelhof-example, tagging it as a paved pedestrian area describes [exactly what it is](http://www.top10berlin.de/sites/top10berlin.de/files/location/mainimages/2014/06/10/fullsize_tempelhoferfreiheit_betreiber_c_lichtschwaermer_02.jpg).

**Comment by RicoZ-OSM** [comment]
@math1985: The Tempelhof example is indeed correct but  is not the original example where someone did a hack to have it rendered.

@matkoniecz: I think specific objects need specific treatment and only some deserve rendering, using interrupted/dotted lines for the outlines may work for many.

**Comment by pnorman** [comment]
Given our choices not to render some specific abandoned features (#542), disused features (#111), and proposed features (#1654), any proposal to render an abandoned feature has a high bar to clear.

If there are specific abandoned features that you feel should be rendered, issues can be opened for them, keeping in mind the above comments.
