### ISSUE TITLE
Use a building's "ref" to supply some text

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#2132]
When a building has no name and no addr:housenumber to be rendered as text ontop of the polygon, I would like to see the ref attribute being used in its stead.
Ex.: garden sheds near https://www.openstreetmap.org/#map=19/51.51465/9.92587

**Comment by HolgerJeromin** [comment]
Would be also nice for amenity=parking to avoid often wrong name= tagging.

**Comment by BushmanK** [comment]
Indeed, using `ref` is typical (and prescribed by documentation) for storage or industrial buildings within a territory with single general street address. However, it should have the lowest priority after `name` and `addr:housenumber`

**Comment by matkoniecz** [comment]
I think that there are two situations

- ref is some internal value that is not used to describe building and rendering it is not useful
- ref is used as building name - in this case it should be tagged as both ref and name tags

And this change

- will make rendering in the first case
- would not change rendering in the second case

So I propose to decline this change.

**Comment by kocio-pl** [comment]
I agree, so closing it now.

**Comment by marcows** [comment]
A number can hardly be considered to be a building name. IMO the number assigned to a garden shed like from the ones in the map link above is neither its name nor an internal value.

So there is a third situation:
- ref is a public value, useful for people searching for a specific building (which neither has a name nor a postal address)

**Comment by Adamant36** [comment]
I think there was a discussion about this awhile back in relation to plot numbers in allotments and it was decided that rendering ref in that way, as a public value, was wrong. I can't remember what issue it was or why it was wrong rendering though. @jeisenbe?

**Comment by jeisenbe** [comment]
There is some opposition to rendering allotments=plot boundaries, but support for rendering the "ref" numbers: https://github.com/gravitystorm/openstreetmap-carto/issues/432#issuecomment-453760210
