### ISSUE TITLE
Rendering issue with wetland=fen?

### ISSUE THREAD

**Issue by jfd553** [gravitystorm/openstreetmap-carto#2135]
https://www.openstreetmap.org/#map=17/45.86773/-71.25878
The above wetland=fen do not render as described in the wiki... http://wiki.openstreetmap.org/wiki/Tag:wetland%3Dfen

It seems it is using the previous rendering version [2015-05-23T06:02:56] of http://wiki.openstreetmap.org/wiki/File:Natural_wetland_marsh.png

Even if the code I found seems still referring to the new marsh pattern (since the marsh pattern renders correctly)
[...]
568     [int_wetland = 'wet_meadow'],
569     [int_wetland = 'fen'] {
570       polygon-pattern-file: url('symbols/wetland_marsh.png');

Maybe I missed something :-)
Daniel

**Comment by matkoniecz** [comment]
Is there anything wrong except "wetland=fen do not render as described in the wiki"? Because that would be purely a problem with outdated wiki page.

**Comment by imagico** [comment]
This is a valid issue - wetland=fen was supposed to be rendered with a solid color background like marsh but at the moment it is not.

Incidentally it would probably be better to render wetland=fen with the same symbols as wetland=bog (indication peat deposits) but with the colors of marsh (indicating a richer, more diverse plant life).
