### ISSUE TITLE
Map not updated everywhere at Z12?

### ISSUE THREAD

**Issue by jfd553** [gravitystorm/openstreetmap-carto#2141]
Not sure it is the good forum for the following problem (please provide a link if not). 

An area I mapped two months ago shows up properly at all zoom levels but Z12, even using /dirty. For instance, the trunk road below (ref=112) is OK at all zoom but Z12 where it still shows a primary road. 
http://www.openstreetmap.org/#map=13/46.0495/-71.3708

Same problem with other features like a national_park about 10 km SE
https://www.openstreetmap.org/#map=11/45.8871/-71.0658

**Comment by daganzdaanda** [comment]
I used /dirty on the tiles at z12 and they did get re-rendered correctly. Do you still see the old ones now?

**Comment by polarbearing** [comment]
You might have had the old tiles in your browser cache, or a proxy in between. Shift-reload.

Anyway, this is a matter of tileserver configuration and not rendering style, thus the issue needs to be closed here.

**Comment by pnorman** [comment]
on tile.osm.org z0-z12 is rerendered monthly. Update issues are not a style issue, so there's nothing we can do to help you here.

**Comment by jfd553** [comment]
You already done it ! 
daganzdaanda used /dirty on its side and updated the tiles, something I was not able to do on my side (even when using the /dirty on Z12). I now know it is a problem with my browser cache, or a proxy in between (polarbearing).
