### ISSUE TITLE
yaml2mml.py is not platform-independent for newlines

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2153]
@ircama could you try changing 
```python
  mml_file = open(mml_path, 'w')
```
to
```python
  mml_file = open(mml_path, 'wb')
```
in yaml2mml.py

**Comment by pnorman** [comment]
@ircama, does the :+1: mean that it works?

**Comment by Ircama** [comment]
> does the :+1: mean that it works?

Apparently yes and it would be very useful.

Anyway, I forgot to test it on a real PR, apologize. As soon as a PR does not create errors with this, I'll let you know. Consider I'm just testing this with Windows.

**Comment by Ircama** [comment]
Confirmed to work, thanks
