### ISSUE TITLE
mention pre-commit hook in readme

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2156]
I just discovered that it is possible to autoregenerate and autocommit .mml file on every commit including change of .yaml.

Solution is quite simple - create `.git/hooks/pre-commit` file with following content.

```
# Redirect output to stderr.
exec 1>&2

#Generate .mml file from staged version - hide unstaged changes
git stash -q --keep-index

#Run .mml generation script
./scripts/yaml2mml.py < project.yaml > project.mml 

#Commit project.mml file
git add project.mml

#Restore unstaged changes
git stash pop -q
```

Before every commit it runs ./scripts/yaml2mml.py script and commits result what should ensure correct content in .mml file without manual regeneration.

If there are no unforeseen consequences here it may be a good idea to mention it in contributing file.

Unfortunately there is no clean method to make this file part of repo... There is http://pre-commit.com/#install that requires anyway installation. Maybe add script that would create this file?

**Comment by matkoniecz** [comment]
Unfortunately it is not so simple... To keep amending possible change described in http://codeinthehole.com/writing/tips-for-using-a-Git-pre-commit-hook/#comment-645959940 was necessary. To handle also Windows it should be written in something more portable.

```
#!/bin/bash 

function regenerate_mml {
	#Run .mml generation script
	./scripts/yaml2mml.py < project.yaml > project.mml;
	#Commit project.mml file
	git add project.mml;
}

# Redirect output to stderr.
exec 1>&2

if git diff-index --quiet HEAD --; 
then
	# no changes between index and working copy; just run tests
	regenerate_mml
else
	# Test the version that's about to be committed,
	# stashing all unindexed changes
	git stash -q --keep-index

	regenerate_mml

	git stash pop -q
fi
```

**Comment by pnorman** [comment]
Does this work with `git add -p`? That's what I've not been sure of in the past when I've looked at this

**Comment by matkoniecz** [comment]
Yes, it works. On `git add -p` nothing special happens as pre-commit hook is triggered only before commit.

On commit "stashing all unindexed changes" branch is used - so unindexed changes (not selected in `git add -p`) are stashed, `regenerate_mml` runs and after that changes are unstashed.

Now normal commit happens, with only staged changes commited.

The only potential problem is with unstashed changes not applying cleanly, but for now I am unable to answer whatever it is purely theoretical.

**Comment by matkoniecz** [comment]
And thanks for `git add -p`, I was using `git add -i` and jumping through an additional menu.

**Comment by kocio-pl** [comment]
Made obsolete by #2473.
