### ISSUE TITLE
Underground power lines displayed as if they were above ground.

### ISSUE THREAD

**Issue by emergency99** [gravitystorm/openstreetmap-carto#2167]
A user even deleted a powerline that is correctly mapped as layer=-2, as it "obstructed his view" on the map... I think things with a layer below 0 or indoors should be rendered less prominently than things above ground or outdoors. Hope i am right to post this here.

Greetings
em99

**Comment by jojo4u** [comment]
Layer below 0 does not mean underground. Please read up the layer tag on the wiki. The tag location is used for that.

**Comment by polarbearing** [comment]
So basically, that user needs to be educated not to delete things he does not understand, and that OSM is more than just one rendered map. But this is not a style issue.

**Comment by matkoniecz** [comment]
> Layer below 0 does not mean underground. Please read up the layer tag on the wiki. The tag location=* is used for that.

Yes, layer tag merely indicates order of objects. Use location=underground for that.

> A user even deleted a powerline that is correctly mapped as layer=-2, as it "obstructed his view" on the map... 

That is pure http://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer

But I agree with topic of issue itself and I support idea of not rendering power=line/minor_line with location=underground.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 15 giu 2016, alle ore 09:35, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> But I agree with topic of issue itself and I support idea of not rendering power=line/minor_line with location=underground.


yes, these are not suitable for a general map, do not serve for orientation (unlike above ground lines). An exception might be situations where an overground power line goes underground for a bit, and not rendering the underground part might lead to inconsistency and strange gaps. Obviously also in this case it would be desirable to distinguish underground ones (e.g. dashed)

**Comment by emergency99** [comment]
The line is also tagged with location=underground. 
Then this should possibly be rendered slightly less prominent...

**Comment by polarbearing** [comment]
Power lines in general have just been made a bit thinner here: #2162

**Comment by matkoniecz** [comment]
>  Then this should possibly be rendered slightly less prominent... 

Is it desirable to render it at all on general purpose map?

**Comment by kocio-pl** [comment]
I guess not. I would rather like to see overground pipelines instead of underground power lines, because they are part of the landscape, while underground power lines are too specialized IMO (we only show tunnels for transportation, because it's a general feature).

**Comment by bjh21** [comment]
Note that for buried power cables the correct tag is power=cable, not power=line.

**Comment by pnorman** [comment]
Tagging issue, use power=cable

**Comment by aceman444** [comment]
What about underground buildings? location=underground does not seem to work.

**Comment by math1985** [comment]
That's a different issue, see #552.
