### ISSUE TITLE
Label color for private parking is non-intuitive

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#2170]
Especially when the corresponding symbol is not rendered above the yellow parking color - like here:

http://www.openstreetmap.org/#map=19/50.04516/8.54655

Should IMO be a lighter version of the normal label color, not a greener tone.

**Comment by jragusa** [comment]
I recently noticed this issue.

Why not use the [key](http://cartocss.readthedocs.io/en/latest/api/mapnik/3.0.6.html?highlight=text-opacity) `text-opacity` to resolve this issue instead of hardcoded the colour ?

**Comment by polarbearing** [comment]
```@transportation-text: #0066ff;```
```@transportation-icon: #0092da;```

The icon uses ```marker-opacity: 0.33;```
The text uses ``` text-fill: @transportation-text;``` when public 
and ``` text-fill: #66ccaf;``` when private. 

not consistent indeed.

@jragusa - are you going to show us test rendering with your proposal?

**Comment by jragusa** [comment]
Yes, I'm preparing this

**Comment by jragusa** [comment]
And voilà :
before (z=19)
![before](https://user-images.githubusercontent.com/9897203/36611934-5fef89e0-18d5-11e8-9798-647c5e15c605.png)
after (z=19)
![after](https://user-images.githubusercontent.com/9897203/36611951-6abc764e-18d5-11e8-88c8-e905d260980a.png)
I only replaced `text-fill: #66ccaf;` by `text-opacity: 0.33;` As you can see, this reduces the readability of the name. With the original setting, the name seems also slightly bigger. Any suggestions ?

**Comment by kocio-pl** [comment]
Since this is a private feature, details like name are not that important anyway, so I vote for this change. Could you prepare a pull request?
