### ISSUE TITLE
Release 2.40.0

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#2174]
A month ago I ran out of time to make a release before I left on a holiday. I've realised that I'm a single point of failure with releases, and despite telling all the other maintainers that the are welcome to take over, I think everyone is still waiting on me to do them!

So I'm going to make a new policy, which is that I want to see every maintainer making a release at least once a year, just to make sure that everyone is comfortable doing so if I'm not around. I'm happy to continue as the main release manager, and I'm also happy to hand over to others. But I think it's worth making sure all the maintainers are happy with the release process.

I've assigned this issue to @math1985 to make the next release, which can be done any time from now.

**Comment by math1985** [comment]
Two reasons I haven't done any release yet:

* @pnorman suggested not to do a release until we know better what causes the landuse polygons problems
* We hardly merged any PRs since last release (until @matkoniecz started his gsoc project), and the changes that were merged don't affect rendering output

I will pick up the next release soon.

**Comment by kocio-pl** [comment]
At least bookshop and library will look different now, so new release would make the difference.

**Comment by pnorman** [comment]
I had written half an email about doing a release about 6 weeks ago, but realized there was nothing yet release-worthy, and I hadn't tested for #2101 on a production renderd setup.

#2101 still concerns me

**Comment by matkoniecz** [comment]
I also considered pushing release, but I decided to wait until #2101 is resolved.

**Comment by math1985** [comment]
I have reverted #2101 for now as it is blocking the release.

**Comment by pnorman** [comment]
With that reverted, are you ready to tag a release?

**Comment by math1985** [comment]
Done, see also https://github.com/openstreetmap/chef/issues/70.

**Comment by gravitystorm** [comment]
Thanks!
