### ISSUE TITLE
more prominent city labels on z5 to z10

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2175]
From comparing with FR fork I think that making labels of cities more prominent may improve map.

I am less sure about increasing how many cities are rendered. And it seems that our algorithm for finding important cities is better than one used in FR style.

http://mc.bbbike.org/mc/?lon=22.000071&lat=51.186417&zoom=7&num=2&mt0=mapnik&mt1=osmfr&marker=

![selection_006](https://cloud.githubusercontent.com/assets/899988/16167127/cedcc71a-34f1-11e6-96f9-b57e38cc08a6.png)

Related to #1935

FR code is probably at https://github.com/cquest/osmfr-cartocss/blob/master/placenames.mss

**Comment by kocio-pl** [comment]
It would be nice and useful.

What strikes me more on this comparison is how FR style avoids our problem of obscuring city names by admin boundary names (https://github.com/gravitystorm/openstreetmap-carto/issues/1391)?

**Comment by sommerluk** [comment]
I think that in this case, the “type color” might have more influence than the font size. That means:

Darker type colour:
– black font face or bold font face
– black text colour

Lighter type colour
– regular font face, book font face
– (lighter) gray text colour

For place=village, we are currently switching starting with z14 from a darker to a lighter text colour. That means less emphasis on higher zoom levels, what is good. This might be a good thing also for other placenames.

#2178 removes bold text for POI. This could be a opportunity for starting using bold typefaces for placenames.

However, it might not be trivial to organize all these parameters hierarchical.

**Comment by matkoniecz** [comment]
Some experimental results.

z11
https://cloud.githubusercontent.com/assets/899988/16179286/0b11f078-3661-11e6-9803-b8ecd783372b.png
https://cloud.githubusercontent.com/assets/899988/16179287/0b14e47c-3661-11e6-9d22-fd69872122ea.png

z10
https://cloud.githubusercontent.com/assets/899988/16179289/0b175752-3661-11e6-9c99-1b4a67a2b2b5.png
https://cloud.githubusercontent.com/assets/899988/16179290/0b1a461a-3661-11e6-9513-d0e9c17b27af.png

z9
https://cloud.githubusercontent.com/assets/899988/16179292/0b2e48ae-3661-11e6-968d-4561c5d8e249.png
https://cloud.githubusercontent.com/assets/899988/16179288/0b164588-3661-11e6-9066-8be9b3766198.png

z8
https://cloud.githubusercontent.com/assets/899988/16179291/0b1f4bd8-3661-11e6-8264-672b15f5eaa3.png
https://cloud.githubusercontent.com/assets/899988/16179294/0b2e96a6-3661-11e6-8853-bec77613a917.png

z7
https://cloud.githubusercontent.com/assets/899988/16179293/0b2e4e44-3661-11e6-87fe-bbd4b2e92a1e.png
https://cloud.githubusercontent.com/assets/899988/16179295/0b31cae2-3661-11e6-9f5d-ed22e5e7269c.png

z6
https://cloud.githubusercontent.com/assets/899988/16179298/0b4ac51a-3661-11e6-8405-9df2f12228e3.png
https://cloud.githubusercontent.com/assets/899988/16179296/0b337554-3661-11e6-844b-792aab63d846.png

z5
https://cloud.githubusercontent.com/assets/899988/16179297/0b38944e-3661-11e6-8835-98a3730d1720.png
https://cloud.githubusercontent.com/assets/899988/16179300/1ba47f46-3661-11e6-96f4-ec1570fface5.png

**Comment by math1985** [comment]
Interesting experiment. I think the dots are currently too heavy (and I'm not sure yet if they are a good idea at all). Maybe making them grayer and/or smaller works?

**Comment by matkoniecz** [comment]
Additional before after are at https://github.com/matkoniecz/before_after_for_placenames

**Comment by imagico** [comment]
Note point signatures for settlements means off center labels and off center labels with a static direction looks fairly primitive in general.  And in any case this kind of labeling can lead to ambiguities (which label belongs to which dot).

Long story short - i think this kind of labeling is only appropriate if there is sufficient finesse behind it to gracefully deal with these things.

**Comment by daganzdaanda** [comment]
It's very interesting, and could be clearer than the label-only approach at showing where exactly a town is. But as @imagico said, it would need more "finesse", and that may be a lot of work. 
One example: right now, a lot of dots don't have a label, and some labels appear without a dot. That's bad, there should never be an "empty" dot or undotted label.

For comparison: the Humanitarian Style has dots for places, and seems to put the label either at top right or bottom left.
