### ISSUE TITLE
bridge on footway not rendered at z13

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2179]
![footway-bridge-z13](https://cloud.githubusercontent.com/assets/7693297/16179198/c5355664-365e-11e6-9cb1-7dd4821b058e.PNG)
http://www.openstreetmap.org/#map=13/45.6865/10.0851
https://www.openstreetmap.org/way/420028382
Looking at the "Floating Piers", I noticed that they are tagged as a footway with bridge=yes. The footway is still rendered at z13, but the bridge casing disappears.

**Comment by matkoniecz** [comment]
Rendering bridges at this zoom level would give all footway bridges undue prominence. Result in this case may be surprising but overall I think that there is no need to change anything here.

**Comment by daganzdaanda** [comment]
I think you are right. It was a surprise to me, also because road bridges are still rendered at that zoom. But it may be better to ignore footway bridges, since the majority will be very short and it might only add 
noise.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 19 giu 2016, alle ore 20:58, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> Rendering bridges at this zoom level would give all footway bridges undue prominence. Result in this case may be surprising but overall I think that there is no need to change anything here.


+1
