### ISSUE TITLE
man_made=bridge name labels rendered on too high zoom levels

### ISSUE THREAD

**Issue by fqdb** [gravitystorm/openstreetmap-carto#2182]
(larger) bridges that have their own name tag have their name rendered at high zoom levels, even though the ways over the bridge may be of minor importance.

Example: http://www.openstreetmap.org/way/364258034#map=14/52.1312/4.6659

It would be better if the label display would be coordinated with that of the (most important) road type on the bridge.

**Comment by dieterdreist** [comment]
2016-06-20 17:29 GMT+02:00 Felix <notifications@github.com>:

> (larger) bridges that have their own name tag have their name rendered at
> high zoom levels, even though the ways over the bridge may be of minor
> importance.
>
> Example: http://www.openstreetmap.org/way/364258034#map=14/52.1312/4.6659
>

IMHO that's a feature. I don't see a problem with the bridge name displayed
at the scale.

Cheers,
Martin

**Comment by fqdb** [comment]
So to circumvent it in this case it would be justified to split the area to make the named area smaller?

**Comment by matkoniecz** [comment]
> So to circumvent it in this case it would be justified to split the area to make the named area smaller?

No. http://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer

**Comment by matkoniecz** [comment]
> IMHO that's a feature.

Yes, it is an intentional effect intended to catch bigger bridges, acting as orientation points. Is it a big unimportant bridge?

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 20 giu 2016, alle ore 19:45, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> Yes, it is an intentional effect intended to catch bigger bridges, acting as orientation points. Is it a big unimportant bridge?
> 


+1, basically all bridges are somehow significant orientation points. There might be some difficulty in finding a suitable area size to start rendering, because it heavily depends on the span (lenght of the bridge), and some short bridges might still be important because you can't otherwise cross the <obstacle>, but will have a smaller area size.

**Comment by matkoniecz** [comment]
I think that in general it works quite well.
