### ISSUE TITLE
highway=bus_guideway in tunnels is not rendered

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2187]
This affects just 12 objects worldwide - see http://overpass-turbo.eu/s/gU8, for example

http://www.openstreetmap.org/#map=19/28.63737/-106.07650 ( www.openstreetmap.org/way/304692748#map=18/28.63658/-106.07525 )

![selection_002](https://cloud.githubusercontent.com/assets/899988/16226109/373c33bc-37aa-11e6-8c4c-904cba6419a6.png)

result of

> WHERE highway = 'bus_guideway' AND (tunnel IS NULL OR tunnel != 'yes')

I am considering just removing tunnel filtering, without inventing special rendering in this case.

**Comment by jojo4u** [comment]
The example is tagged wrong, this is no guideway but just a bus lane: https://goo.gl/maps/TTVvaC1Qk6T2

**Comment by matkoniecz** [comment]
Tagging of this particular place may be discussed at http://www.openstreetmap.org/note/600960

**Comment by math1985** [comment]
Bus guideways are so rare that I wouldn't mind dropping the rendering at all (it could be replaced by highway=service for example).

**Comment by jojo4u** [comment]
@matkoniecz I alread opened a note before you, but closed it in favor of yours ;)

I was curious and checked all places:
Quito: No guideway, just service. Notes added.
Around Paris: Those are rubber trams double-tagged with railway+highway
Melbourne: genuine
Poland: Probable a station/depot -> indoor tagging
South Korea Everland: No guideway, just service. Note added.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 21 giu 2016, alle ore 13:44, math1985 <notifications@github.com> ha scritto:
> 
> Bus guideways are so rare that I wouldn't mind dropping the rendering at all


yes, there are few, but I think it's cool we do support them, they are a particular transport related feature and where they exist they are significant, if they were to be substituted by something else, I'd rather choose tram then service for their substitute

**Comment by mboeringa** [comment]
> I was curious and checked all places:
> Quito: No guideway, just service. Notes added.
> Around Paris: Those are rubber trams double-tagged with railway+highway
> Adelaide: genuine
> Poland: Probable a station/depot -> indoor tagging
> South Korea Everland: No guideway, just service. Note added.

I miss Cambridge in your list. Probably the birth place of this tag... considering OSM originates in the UK.
