### ISSUE TITLE
highways, some preprocessing required to handle branches with different status

### ISSUE THREAD

**Issue by d1g** [gravitystorm/openstreetmap-carto#2193]
I'm not sure if change of style will help here:

https://www.openstreetmap.org/node/26229302#map=17/50.46064/30.63114
https://www.openstreetmap.org/node/26229278#map=18/50.46089/30.62978
https://www.openstreetmap.org/node/26229282

**Comment by matkoniecz** [comment]
Is https://www.openstreetmap.org/way/5154846#map=17/50.46021/30.62813 correctly tagged as trunk_link? Given that in this case main road changes direction I would expect it to be tagged as trunk.

**Comment by matkoniecz** [comment]
In general rendering _link below other roads breaks things significantly less frequently than rendering them over roads so I would second "I'm not sure if change of style will help here".

**Comment by d1g** [comment]
I think that most segments participating along [Minsk-Odessa](https://www.openstreetmap.org/directions?engine=mapzen_car&route=53.902%2C27.562%3B46.485%2C30.733#map=6/50.366/29.421) should be trunk/primary

**Comment by d1g** [comment]
Not sure where to report it.

During preprocessing/import:

If a way (trunk https://www.openstreetmap.org/way/114007328) has **incoming roads with lower status and only one incoming _link with same status**:
* primary (https://www.openstreetmap.org/way/38072388)
* trunk_link (https://www.openstreetmap.org/way/5154843)

Then it should covert the only _link road as best possible match for roads with same status

**Comment by matkoniecz** [comment]
Preprocessing roads is not really feasible. For start - it is unclear whatever this place is even tagged correctly.

**Comment by pnorman** [comment]
In tag processing we can't do anything based on topology or nearby objects and we don't preprocess, nor is preprocessing roads an option.
