### ISSUE TITLE
Tree/wood rendering inconsistent area vs. relation

### ISSUE THREAD

**Issue by midnightcomm** [gravitystorm/openstreetmap-carto#2196]
![screenshot from 2016-06-23 19 51 38](https://cloud.githubusercontent.com/assets/5687236/16324694/3e2e7cba-397c-11e6-8756-0cb66abc2be8.png)

Residential areas and residential relations have different layer precedence with __natural=wood__.

I somewhat like having the green background disappear, and just show tree depictions when there's overlap with housing areas; however, the inconsistent rendering is distracting.

http://www.openstreetmap.org/?mlat=41.14332&mlon=-95.90598#map=19/41.14332/-95.90598

**Comment by pnorman** [comment]
> Residential areas and residential relations have different layer precedence with natural=wood

No - this has nothing to do with relations. Both the way and relation get turned into areas.

See #888

I could see rendering landuse=forest/natural=wood on a different layer than landuse=residential/commercial/retail/etc but that would be a big change that wouldn't be for this issue alone and would need discussion.

**Comment by matkoniecz** [comment]
areas and relation are treated the same, I attempted to explain rendering order in http://wiki.openstreetmap.org/wiki/Standard_tile_layer#Rendering_order

In case that wiki explanation is unclear - improve it or mention problems at http://wiki.openstreetmap.org/wiki/User_talk:Mateusz_Konieczny

In case that somebody is convinced that different layering order would be better and cosidered consequences - please open a new issue.
