### ISSUE TITLE
Fonts and Ubuntu 16

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2200]
During upgrading to Ubuntu 16 I encountered some font-related problems

Instructions in https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#fonts are no longer working properly:

fonts-droid has has been removed from Ubuntu 16 https://lists.ubuntu.com/archives/ubuntu-devel/2016-February/039159.html - recommended replacement is Noto (see #1067), fonts-droid-fallback package is also available

ttf-indic-fonts-core was intentionally removed from Ubuntu 16 - https://bugs.launchpad.net/ubuntu/+source/ttf-indic-fonts/+bug/958345 There is a [fonts-indic package](http://packages.ubuntu.com/xenial/fonts-indic) that may or may not be a replacement. It is a big meta package so installing individual packages may be better.

ttf-kannada-fonts is unavailable. According to apt-get:

> However the following packages replace it:
>  fonts-lohit-knda fonts-knda

Note that OSM rendering machines are upgrading to Ubuntu 16 - https://github.com/openstreetmap/operations/issues/81 so either this problem is already solved by maintainers of OSM tile servers or it should be fixed also there once solution is known. Though if OS is upgraded rather than erased and installed from scratch it will not cause immediate problems.  It is more likely to cause problems with new tile servers, starting in Ubuntu 16.04 (it may or may not happen with plan described in https://github.com/openstreetmap/chef/issues/39#issuecomment-228186758)

**Comment by matkoniecz** [comment]
> Mallige, for Kannada (ttf-indic-fonts-core for normal and bold and ttf-kannada-fonts for oblique) The filename uses "Malige" but the font name uses "Mallige"

Finding replacement is not obvious. `openstreetmap-carto/INSTALL.md` is one of top results in googling results what is not encouraging.

**Comment by pnorman** [comment]
I asked Sebastiaan for some information on package names and will start preparing a PR



> From the INSTALL file:
> 
>  Global
> 
>   * DejaVu Sans, for most languages (ttf-dejavu)
>   * Droid Sans Fallback, as a reasonable fallback (fonts-droid)
>   * Unifont, as a last resort fallback (ttf-unifont)
> 
>  Southeast Asia
> 
>   * Arundina Sans, for Thai (fonts-sipa-arundina)
>   * Padauk, for Burmese (fonts-sil-padauk)
>   * Khmer OS Metal Chrieng Regular, for Khmer (fonts-khmeros)
> 
>  South Asia
> 
>   * Mukti Narrow, for Bangali (ttf-indic-fonts-core)
>   * Gargi Medium, for Devanagari (ttf-indic-fonts-core)
>   * TSCu_Paranar, for Tamil (ttf-tamil-fonts or fonts-taml-tscu,
>                              depending on your Ubuntu version)
>   * Mallige, for Kannada (ttf-indic-fonts-core for normal and bold and
>                           ttf-kannada-fonts for oblique)
>     The filename uses "Malige" but the font name uses "Mallige"
> 
> 
> In Debian unstable I found the following fonts using apt-file to search
> for the (partial) font filenames:
> 
>  * DejaVuSans.ttf is now included in fonts-dejavu-core.
>    It's the successor to the ttf-dejavu package.
> 
>  * DroidSansFallback.ttf is now included in fonts-droid-fallback.
>    Please note it's README.Debian file:
>    "
>     As of release 1:6.0.0r1-1 fonts-droid-fallback does not install
>     DroidSansFallback.ttf to fontconfig monitored path.
> 
>     This is meant to fix bug #762296 (http://bugs.debian.org/762296) as
>     this file share the same name ("Droid Sans Fallback") with
>     DroidSansFallback.ttf showing up before DroidSansFallbackFull.ttf
>     while the latter is the preferred font for rendering Chinese content
>     in some installations.
> 
>     As a consequence, the offending file is moved in
>     /usr/share/fonts-droid/truetype and therefore not automatically seen
>     by fontconfig.
>    "
> 
> https://sources.debian.net/src/fonts-android/1:6.0.1r16-1/debian/README.Debian/
> 
>    The Droid font went commercial, so it's being replaced by Noto where
>    possible.
> 
>  * unifont.ttf is still included in ttf-unifont.
>    It has not adopted the new font package naming convention yet.
> 
>  * ArundinaSans.ttf is still included in fonts-sipa-arundina.
> 
>  * Padauk.ttf is still included in fonts-sil-padauk.
> 
>  * KhmerOSmetalchrieng.ttf is still included in fonts-khmeros.
> 
>  * MuktiNarrow.ttf is now included in fonts-beng-extra.
> 
>  * Gargi.ttf is now included in fonts-gargi.
> 
>  * TSCu_Paranar.ttf is now included in fonts-taml-tscu.
> 
>  * Mallige seems to have been removed.
>    There is the fonts-knda metapackage that depends on
>    fonts-lohit-knda, fonts-gubbi, fonts-navilu to provide replacements
>    for fonts previously included in ttf-kannada-fonts.
> 
> Kind Regards,
> 
> Bas
>
