### ISSUE TITLE
please render place=square

### ISSUE THREAD

**Issue by flohoff** [gravitystorm/openstreetmap-carto#2203]
place=square is a nice way to give names to complicated squares. Please render a label for the node or centroid of the area the place tag is on. 

Rendering should be like place=locality for example.

**Comment by matkoniecz** [comment]
Used only 230 times - http://wiki.openstreetmap.org/wiki/Tag:place%3Dsquare

Documentation page at wiki has no examples of cases where using it is truly useful and superior to tagging highway=pedestrian + area=yes multipolygon.

**Comment by flohoff** [comment]
How do you tag places which are NOT pedestrian areas?

**Comment by matkoniecz** [comment]
> How do you tag places which are NOT pedestrian areas?

Never encountered one, that is why I complained about missing examples.

**Comment by flohoff** [comment]
I have a couple of them - Either beeing a combination of village_green and some ways, or even parking areas with some ways inbetween.

For some i used place=locality as that works for addresses and gets rendered. Now somebody mentioned place=square and that is a much better match. But it does not show up on the map. So its a step back.

**Comment by jojo4u** [comment]
Here you are: https://www.openstreetmap.org/way/3933618

Schlossplatz encompasses highway=footway, area:highway, landuse=grass, historic=memorial, fountains

**Comment by matkoniecz** [comment]
> Here you are: https://www.openstreetmap.org/way/3933618

Please, add tag documentation to wiki. This issue tracker is not a good place to document/discus tags.

**Comment by dieterdreist** [comment]
2016-06-28 14:05 GMT+02:00 Mateusz Konieczny <notifications@github.com>:

> Please, add tag documentation to wiki.



there is documentation:
http://wiki.openstreetmap.org/wiki/Tag:place%3Dsquare

**Comment by kocio-pl** [comment]
@matkoniecz Is there anything more missing or we could try making PR for this tag now?

**Comment by pnorman** [comment]
I can't see rendering a feature with so few uses.

**Comment by math1985** [comment]
I agree.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 26 lug 2016, alle ore 08:58, Paul Norman <notifications@github.com> ha scritto:
> 
> I can't see rendering a feature with so few uses.


I suggest to keep this issue open as the tag is brand new and I expect usage numbers to go up soon

**Comment by polarbearing** [comment]
Indeed it grew from about 40 last October when it was discussed on the tagging list and got properly documented. It went from 230 when @matkoniecz counted 4 weeks ago to 338 today.

**Comment by math1985** [comment]
We can reopen when needed.

**Comment by kocio-pl** [comment]
I think it's worth re-opening. The square labels are very useful and are common on maps, but many squares are much more complicated than just one big pedestrian area. The usage rate of this tag is not only growing, but still accelerating (this kind of object is less frequent than streets, so this trend is not going to last too long, of course):
![taghistory](https://cloud.githubusercontent.com/assets/5439713/18338100/95c54138-7596-11e6-922e-f089c2c2db1c.png)

**Comment by pnorman** [comment]
there's still only 450 usage, that's still too low

**Comment by kocio-pl** [comment]
What number do you consider to be enough for rendering? 

We may just wait with merging PR (once it's ready), but the issue should be reopened, because looking at the context it's a safe bet and a useful feature. The only problem I see could be competing tagging schemes, but I don't see anything like this - [highway=square](http://taginfo.openstreetmap.org/tags/highway=square) has just 4 uses now and has no wiki page.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 08 set 2016, alle ore 09:25, kocio-pl <notifications@github.com> ha scritto:
> 
> The only problem I see could be competing tagging schemes, but I don't see anything like this - highway=square has just 4 uses now and has no wiki page.


the former alternative was highway=pedestrian with area=yes, but it had some problems (mainly areas that were part of the square but not accessible areas)

**Comment by kocio-pl** [comment]
As I said - "many squares are much more complicated than just one big pedestrian area", so that was never a real alternative for me.

**Comment by pnorman** [comment]
> What number do you consider to be enough for rendering (BTW: it's now 509)?

I don't think there's a concrete number at which we can say we will render something. Previous discussions have had numbers from 2k-5k for rendering something.

**Comment by kocio-pl** [comment]
[man_made=obelisk](https://github.com/gravitystorm/openstreetmap-carto/issues/2126) is rendered with only 272 occurences, because it's worth making an exception sometimes. place=square is also about unobtrusive reusing of styling (just a label like we do for footway or pedestrian areas) and I think it deserves rendering even with current usage (547 currently).

**Comment by abdeldjalil09** [comment]
http://taginfo.openstreetmap.org/tags/place=square --> now 1 074 uses

**Comment by polarbearing** [comment]
appears to grow exponentially at the moment. +1 for re-open

**Comment by kocio-pl** [comment]
I also feel it's really the time to reconsider rendering it, even if not yet (but given enough support, I would do it even with 1k+ uses).

**Comment by polarbearing** [comment]
Fine. So first question to discuss, should we just render the name as the OP suggested, or the area as well?

**Comment by kocio-pl** [comment]
I think only about the name, since square can have multiple - and sometimes mixed - forms.

**Comment by Hjart** [comment]
2000+ uses now.

Buildings in a highway=pedestrian;area=yes polygon will not show and in some other cases the old way of tagging squares isn't really appropriate, so I will appreciate if we can have this instead.

**Comment by daganzdaanda** [comment]
I would like to see the name, styled like place=locality or neighbourhood, but starting at z=17

**Comment by Hjart** [comment]
Almost 5K uses now
