### ISSUE TITLE
Parks covering open ocean

### ISSUE THREAD

**Issue by talllguy** [gravitystorm/openstreetmap-carto#2205]
This park is a national park, and used to render with a nice little dotted line around the edge. Now it is just a solid green area. In [one of the comments](https://github.com/gravitystorm/openstreetmap-carto/issues/1141#issue-50444271) on #1141 there is an earlier screenshot of how it used to look. [Map location.](http://www.openstreetmap.org/#map=12/38.2686/-75.2028)

It looks like [a recent change](http://www.openstreetmap.org/relation/4234479/history) added the park tag to the relation, but still, the ocean should have a higher precedence than the green of a park, right?

Additionally, the park within a park is also greening out everything else.

![image](https://cloud.githubusercontent.com/assets/1827881/16466361/d1ba4606-3e10-11e6-99b3-c89f51d89072.png)

**Comment by matkoniecz** [comment]
leisure=park is not for national parks. See http://wiki.openstreetmap.org/wiki/Tag:leisure=park

It is for things like
![veale_gardens](https://cloud.githubusercontent.com/assets/899988/16466757/a4a68da8-3e44-11e6-8e0f-af9c3539f0b4.JPG)

see http://www.openstreetmap.org/note/609461
