### ISSUE TITLE
Define a (bigger) minimal font size

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2209]
Some text in this style is rendered quite small.

I propose to define a policy with a minimal font size that applies all around the map. I suggest 10 as minimal font size. There is currently some text that is rendered with smaller font sizes; we could render these labels at size 10 (or, if cluttering too much, a zoom level later).
- [x] Describe the policy
- [x] placenames.mss (only “.state” for zoom levels < 7)
- [x] roads.mss (node features)
- [ ] roads.mss (line features at `#roads-text-ref` and `#roads-text-name` and `#paths-text-name`)
- [x] stations.mss
- [x] adressing.mss
- [x] ferry-roads.mss

**Comment by sommerluk** [comment]
Currently, these mss files define a font size smaller than 10: placenames, roads, stations, adressing, ferry-roads.

**Comment by math1985** [comment]
> I propose to define a policy with a minimal font size that applies all around the map.

Good idea.

**Comment by nebulon42** [comment]
Small font sizes are currently hard to read but this depends also on which font is used. With the current font 10 might make sense, but with another font it could also be 9. Overall I would be in favour.

**Comment by sommerluk** [comment]
The only remaining part of this issue are the line features in roads.mss (street names…). There are quite a few usages with size 8 or 9. As this is a line feature, the text is bent, following the rendering of the road. That makes it quite difficult to read for latin text, and terrible for CJK text.

What options do we have?
- Simply drop rendering of the labels that are currently rendered at size 8 or 9. This would mean a significant loose of information, which for sure is not desired.
- Render street names at all zoom levels bigger than now. This would preserve the labels at each zoom level, and it would also preserve the raising font size on raising zoom levels. But is would also mean that roads that are rendered very tall will have a text label that is much thicker than the road itself. That’s also confusing.
- Render street names bigger than now only on zoom levels where they are smaller than 10 – not changing the text size on the other zoom levels. This would limit (but not solve) the problem with labels that are much bigger than the thinkness of the road rendering. But “raising zoom level = raising font size” would be less smooth.

As road names are bent to the geometry of the road, there is no pixel-alligned rendering anyway. Maybe it’s worth to experiment with font sizes like 10.5, 10.8…

All in all, I don’t know the perfect solution for this, and I have no experience in road rendering, so I’m probably not the best person for this.

@matkoniecz Thoughts?

**Comment by matkoniecz** [comment]
I made some tests with font size but nothing exhaustive - it would be worth testing again. It is likely that things can be relatively easily improved (unlike colours where significant amount of time was used to test many, many different idea and I would not expect quick & easy gains).

From tests I remember that some text was not readable in poor condition and/or by people with poor eyesight. But it was not mentioned as problem and many people were able to use such labels. And after removal of small labels lack of them was noticeable.

So smallest ones were left present without delusions that 8-sized label will be always readable.

**Comment by kocio-pl** [comment]
@sommerluk Do you have the idea what to do with this issue?

**Comment by sommerluk** [comment]
Our font rendering has evolved quite a lot over the last years. While there are quite a few remaining uses of size 8 and 9 in `roads.mss`, looking at it today, it seems not too bad.
