### ISSUE TITLE
I want to remove the maritime border in higher admin levels( > 4)  

### ISSUE THREAD

**Issue by RevathiZoho** [gravitystorm/openstreetmap-carto#2215]
Am using carto boundaries to generate my map tiles, when my map rendered over admin level 4, it shows  the maritime borders extending on sea which looks very odd on map UI. You could see that in the below link ... , the red colored maritime lines extending on sea. 
(https://cloud.githubusercontent.com/assets/19591188/16609096/ac5066da-436e-11e6-97cb-6fb927ca106d.png)

Kindly help ...am in need .

**Comment by nebulon42** [comment]
Unfortunately, it seems that the borders you want to get rid of are not tagged with `maritime=yes` so it is a bit difficult. One possibility would be to use ocean polygons instead of land polygons to "hide" the parts below the water. Another possibility would be to clip borders on the outlines of the land polygons. But this may need preprocessing since it may be slow on the fly.

Others might have other or better ideas.

**Comment by RevathiKanakapathi** [comment]
I filtered [maritime]=0 in my xml file... its only working for below admin_level <5 and for the above one's

For sample 
<Rule>
      <Filter>[maritime]=0 and [admin_level]=5</Filter>
      &maxscale_zoom8;
      &minscale_zoom18;
      <LineSymbolizer stroke="grey" stroke-width="1" stroke-dasharray="6,3,2,3,2,3" stroke-opacity="0.3"/>
</Rule>

**Comment by nebulon42** [comment]
For Mapnik XML and general help with cartography questions you might get better help on gis.stackexchange.com. In the strict sense this issue tracker is only for discussions around openstreetmap-carto.

**Comment by RevathiKanakapathi** [comment]
Ok thank you so much for your fast response

**Comment by math1985** [comment]
See also #621.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 06 lug 2016, alle ore 11:57, Michael Glanznig <notifications@github.com> ha scritto:
> 
> Unfortunately, it seems that the borders you want to get rid of are not tagged with maritime=yes so it is a bit difficult


maybe you should simply add this tag where it is missing

**Comment by RevathiKanakapathi** [comment]
Yes i can't tag them, but can i add that them manually
