### ISSUE TITLE
Add rendering for construction=steps to distinguish it from roads

### ISSUE THREAD

**Issue by sleske** [gravitystorm/openstreetmap-carto#2224]
Currently steps in construction (highway=construction, construction=steps) are rendered like a road under construction (the same rendering as highway=construction without any construction= tag). See for example this flight of steps in Wuppertal: http://www.openstreetmap.org/way/272616133 .

The present rendering makes steps look like a road under construction, which is weird.

**Comment by mboeringa** [comment]
To be honest, for something that is so transient, short lived and small, I think this is not worth the effort. It will be a steps feature in the near future, in which case you are (hopefully) going to remove the "construction" aspect...

**Comment by sleske** [comment]
Well, construction need not be "so transient". The steps in question have been under construction (or, in this case, renovation) for five years (though they are almost done now). So I believe it would make sense to find a rendering that makes sense.

Also, I just noticed that the problem does not appear to be specific to "construction=steps". Here is a footpath under construction (highway=construction, construction=footpath), which seems to be rendered the same way: http://www.openstreetmap.org/way/73047339

**Comment by sleske** [comment]
Strange... according to #1317 construction=footpath and construction=path should both be rendered more narrow than roads.

The example from #1317 , http://www.openstreetmap.org/way/297085914 , which is construction=path, is currently rendered more narrow. However, my example of construction=footpath (http://www.openstreetmap.org/way/73047339) is not rendered as a narrow line.

The narrow rendering looks fine to me, so this ticket could be resolved by adding "construction=steps" to the list of tags that get the "narrow construction rendering". However, this only makes sense if this narrow rendering actually works...

**Comment by sleske** [comment]
Actually, this looks almost like a duplicate of #876 , which was resolved in #1317.
It looks like the only thing missing is to include "steps" in the list of values for "construction" which trigger a more narrow rendering. In #1317, narrow rendering is applied for 'footway', 'cycleway', 'bridleway', 'path', 'track'. The same rendering would probably make sense for "steps", too.

**Comment by james2432** [comment]
![image](https://user-images.githubusercontent.com/498547/37565996-77701de4-2a89-11e8-8b49-7e54c7c00ac3.png)
and added to the construction tags gives this:
![image](https://user-images.githubusercontent.com/498547/37566005-8f3de2f8-2a89-11e8-83b5-e1fc55f5f8eb.png)
Is this what you were looking for?
