### ISSUE TITLE
Fix whitespace errors in generate_road_colours.py

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2226]
There are some in the `generate_colours` function

**Comment by StyXman** [comment]
Which kind of errors? Running `pep8` on the script gives only some warnings, like:

    scripts/generate_road_colours.py:12:1: E302 expected 2 blank lines, found 1
    scripts/generate_road_colours.py:23:80: E501 line too long (112 > 79 characters)
    scripts/generate_road_colours.py:46:1: W293 blank line contains whitespace
    scripts/generate_road_colours.py:73:52: E251 unexpected spaces around keyword / parameter equals

**Comment by StyXman** [comment]
Maybe this should be merged with #2221 ?

**Comment by pnorman** [comment]
No, they're unrelated. Found the problem and opened a PR
