### ISSUE TITLE
Icon for shop=coffee

### ISSUE THREAD

**Issue by Jotam** [gravitystorm/openstreetmap-carto#2227]
According to taginfo, shop=coffee is getting closer to 2000 instances. I would like to suggest to use this icon for rendering such shops: https://wiki.openstreetmap.org/wiki/File:Shop_coffee2.svg

**Comment by HaskuldNihil** [comment]
Lol?

**Comment by Jotam** [comment]
Would you also have a more precise and qualified comment on this?

**Comment by kocio-pl** [comment]
Rendering with and without label (Warsaw, z19), code is [here](https://github.com/kocio-pl/openstreetmap-carto/tree/coffee):
![6ndfg8k](https://cloud.githubusercontent.com/assets/5439713/17075164/5a5c2510-508b-11e6-9513-7c13395f40c8.png)
![eaxervrh](https://cloud.githubusercontent.com/assets/5439713/17075165/64d5cae6-508b-11e6-9146-d02efcb1b5e8.png)

**Comment by boothym** [comment]
Looks a bit like a rugby ball, or a set of lips - not sure I'd say that was a shop selling coffee at first glance. Maybe something more like http://www.freeiconspng.com/uploads/coffee-bean-icon-9.png or http://www.freeiconspng.com/uploads/coffee-bean-icon-png-7.png ?

**Comment by kocio-pl** [comment]
Thanks, I may try to use them, but SVG examples would be more suitable for testing.

**Comment by Jotam** [comment]
The wavy line is better than my more or less straight version. What I don't like is that the opening cuts through the whole bean and sort of "opens" it up.

**Comment by kocio-pl** [comment]
@Jotam Do you have a fresh idea now? Maybe some coffee could help. :smile:

**Comment by Jotam** [comment]
Let's try this:
2) ![layer1](https://cloud.githubusercontent.com/assets/15984044/18836335/d616aee4-83ff-11e6-9806-e2539480868b.png) - SVG[](http://vdma.aldebaran.uberspace.de/osm/coffee_02.svg)

**Comment by Jotam** [comment]
@kocio-pl: Did you try this?

**Comment by kocio-pl** [comment]
Works for me:
![78ebfvb5](https://cloud.githubusercontent.com/assets/5439713/18884207/b18b4052-84e6-11e6-9624-b60274a3214c.png)

**Comment by Jotam** [comment]
For me too.
