### ISSUE TITLE
Review columns vs hstore

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2230]
We reviewed some of the tags in [openstreetmap-carto.style](https://github.com/gravitystorm/openstreetmap-carto/blob/lua/openstreetmap-carto.style) but mainly the first 20 lines or so.

In particular, area, bicycle/foot/horse, religion, surface, and covered all seem like canidates for removal.

We should also look at the OsmType. e.g. the construction column is never accessed from the points table, so we don't need it on nodes.

**Comment by math1985** [comment]
Is this blocking for #1504? This is already a multi-year project, and I'm afraid that if we hold of rolling this out until we have the perfect code, we'll never get to the point where we can release this.

**Comment by pnorman** [comment]
I'd like to at least look at all the columns we've got

**Comment by mboeringa** [comment]
> I'd like to at least look at all the columns we've got

Why, and more specifically, *what* aspects of this change is it that you want to have a look at?

The fact that hstore offers the ability to kind of arbitrarily add or remove columns/keys to your queries, should make this a no-brainer... You can always later on decide to drop columns and start accessing the keys from hstore and re-write the SQL to access them. Yes, dropping them may be a one-time expensive operation once the database is live, but that still shouldn't withhold implementing hstore now.

Any detailed reviews about performance could also be done later. Once you have hstore, you can access the key both from the database column and hstore, and compare (assuming you store all keys in hstore, not just the once not available as column).

**Comment by math1985** [comment]
> I'd like to at least look at all the columns we've got

I agree it would be great to get this in, but it is non-blocking, right? Do you already have any idea when you have time to look at this? If not, we can of course include it in the next reload in 6 months time or so.

**Comment by pnorman** [comment]
If other people **have looked at** https://github.com/gravitystorm/openstreetmap-carto/blob/lua/openstreetmap-carto.style and are satisfied, I've cleaned up a lot of it.

**Comment by math1985** [comment]
I accepted the PR, so to me obviously it looks fine. Still some more eyes on it would be great, of course.

**Comment by imagico** [comment]
Do we have a criterion for having a column for a certain key or not?  I assume all primary tags (i.e. tags that can stand alone without any other tags to be meaningful) should normally be there (but do not necessarily need to according to https://github.com/gravitystorm/openstreetmap-carto/issues/1504#issuecomment-97203127) but how about others?  Is there an efficiency advantage of having widely used tags as columns?

`covered` for example is still in the list while `culvert` and `cutting` are not.

**Comment by HolgerJeromin** [comment]
Perhaps @giggls can help because the German style has hstore since a few years.

**Comment by kocio-pl** [comment]
I'm not so familiar with this part of the code to review it, so don't count me.

**Comment by giggls** [comment]
@HolgerJeromin  In German style we don't use hstore directly. Instead we use views as an intermediate layer. For this reason upstream non-hstore carto style works on our database without any changes.
See https://github.com/giggls/openstreetmap-carto-de/tree/master/views_osmde for the views we use.

**Comment by pnorman** [comment]
> Do we have a criterion for having a column for a certain key or not?

Ideally it is based on performance. Because evaluating that is slow and takes a hours per tag, I try to judge using the queries. Anything that appears in a partial index or is selective in a low-zoom WHERE clause should have its own column. Tags that don't appear in WHERE clauses shouldn't have a column unless they are very common or something is special about them.
