### ISSUE TITLE
Alternative icon for Department Stores

### ISSUE THREAD

**Issue by Jotam** [gravitystorm/openstreetmap-carto#2231]
I find the icon for department stores quite hard to distinguish, specially when it comes to the smallest size (14x14). I would therefore like to suggest an alternative: 
![rect3477](https://cloud.githubusercontent.com/assets/15984044/16874435/8ed9aa6c-4a99-11e6-8686-b96ecfed6e07.png)

**Comment by math1985** [comment]
Thanks for the suggestion.

I wonder though if it might be confused with dollar stores?

For ATMs we got rid of the dollar sign because it only really makes sense for countries in witch dollars are the currency. Do we want to reintroduce it here?

**Comment by jojo4u** [comment]
I would not like to reintroduce them.

**Comment by Jotam** [comment]
I see the problem. One option would of course be to just use a plain shopping bag, like this:
![rect3477](https://cloud.githubusercontent.com/assets/15984044/16876639/f15cc09c-4aa4-11e6-937e-e78e19e32020.png)

If we want any kind of symbol, another idea would be to use "&". I not only reminds of a typical labelling print on shopping bags, it also stands for all those things that can be found in a department store: clothes & houseware & electronics & ...
![rect3477-2](https://cloud.githubusercontent.com/assets/15984044/16876694/383c79e4-4aa5-11e6-9c32-136cd45c2527.png)

**Comment by Jotam** [comment]
Thanks, Kocio. I'm glad you like it.

**Comment by HolgerJeromin** [comment]
IIRC a plain bag is used in hot style for generic shops.

**Comment by kocio-pl** [comment]
Nope, they use plain basket:
https://github.com/hotosm/HDM-CartoCSS/blob/master/icons/poi/shop-18.png

The closest thing to this is bag with numbers we use for for variety store:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/variety_store-14.svg

but I still like the "& bag" idea.

**Comment by Jotam** [comment]
In this case, should we rather use the same shopping bag as for "variety store"? Like this:
![ds2](https://cloud.githubusercontent.com/assets/15984044/16896532/952e192c-4b96-11e6-9cae-737abef3e949.png)
?

**Comment by nebulon42** [comment]
Refreshing the department store icon is definitely necessary, thanks for the initiative. I also think the dollar sign is not best suited but the & or something else might work. At the bigger scale I like your first bag shape better, but it all depends on how it looks at 14px. Are you able to provide some rendering previews?

**Comment by Jotam** [comment]
Like a link to the SVG? Or would you want me to create a 14px version and paste it in here? The latter is this: 
![ds 14](https://cloud.githubusercontent.com/assets/15984044/16896842/09615ecc-4ba0-11e6-9cbb-a8c5ee6dbdf0.png)

**Comment by nebulon42** [comment]
@Jotam no, I mean creating actual map previews. This would require that you have an development environment set up. Do you plan to also provide an implementation?

From seeing your 14px version I would suggest to maybe emphasise the handle a bit more and also make the difference in width between top and bottom of the bag a bit larger.

**Comment by Jotam** [comment]
I don't have an development environment, sorry. This is my first contribution here, because someone encouraged me to throw in my creative skills. So for a start, I'm focused on the art work side and will need some guidance from this very community. I will try out your design suggestions and get back here later.

**Comment by nebulon42** [comment]
Right, I guess everybody here is happy to help you getting started. The reason why I brought this up is that the actual rendering on the map might influence your design decisions.

**Comment by kocio-pl** [comment]
> This is my first contribution here, because someone encouraged me to throw in my creative skills.

That "someone" was me. =}

What operating system do you use? We have detailed instructions for Ubuntu 14.04: https://github.com/gravitystorm/openstreetmap-carto/issues/657#issuecomment-121279334. I have not tried it with a fresh 16.04 version, but it still works after the system upgrade.

The only big difference is I no longer use TileMill for rendering, which is a legacy editor - after I have switched to 64-bit system, I have also switched to Kosmtik, which requires 64-bit architecture IIRC:

https://github.com/kosmtik/kosmtik

**Comment by matkoniecz** [comment]
> I have not tried it with a fresh 16.04 version

The known problem is that TileMill (abandoned by MapBox is no longer available on 16. I also replaced it by Kosmtik)

In case of any additional problems - please, report them (during fresh 16 install I run only into already fixed #2200). Step-by-step instruction for Kosmtik installation on fresh system (or confirmation that installation instructions provided by Kosmtik are good) also would be welcomed.

**Comment by kocio-pl** [comment]
@Jotam How the things with your development environment are going, do you need some help?

Could you provide a link to SVG icon? I would be happy to test how it looks on the map.

**Comment by Jotam** [comment]
I'm very sorry for the delay. But I'm in the process of moving houses right now and can't give  a lot of time to this. I can, however, give you a link to two version of the icon:

http://roeskamp.de/osm/ds_01.svg
http://roeskamp.de/osm/ds_02.svg

The first one is the original icon which I proposed here. The second one has a stronger handle (as suggested) and uses a different font type for the "&" sign. Thanks for helping out with testing, kocio! I shall be fully operational again in 4-5 weeks. But let me know in between what you think. I'm sure I can always do a little design tweaking.

**Comment by kocio-pl** [comment]
I was just wondering if you're dealing with some problems we could help you, but in this case we probably couldn't. ;-)

Warsaw (z19):
ds_01.svg
![io5gfqz4](https://cloud.githubusercontent.com/assets/5439713/17061508/239b2f3c-502f-11e6-8cfd-70e69b3f5d04.png)
ds_02.svg
![pj8gmagh](https://cloud.githubusercontent.com/assets/5439713/17061513/28943f1a-502f-11e6-98d3-3aeff69a2edf.png)

**Comment by Jotam** [comment]
The first one seems to work a lot better, imho. What do the rest of you think?

**Comment by HolgerJeromin** [comment]
Yes, on my phone the first seems better
