### ISSUE TITLE
Review assignment to roads table

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2235]
We need to make sure what we're putting in the roads table is sensible for us

**Comment by math1985** [comment]
Is this a blocking issue for #1504?

**Comment by math1985** [comment]
@pnorman Same question as for #2230 :)

**Comment by pnorman** [comment]
We shouldn't unconditionally be putting railway=* into roads. Probably nothing but railway=rail, railway=subway, and railway=light_rail, but I'd have to review our styling to be sure. Aside from that, I see nothing we need to remove from it.

**Comment by math1985** [comment]
This is also a nice-to-have and not a must-have, right? Just trying to prevent feature creep... If we can get this in relatively soon that would be great, but at some we need to decide 'good enough'.
