### ISSUE TITLE
Icon for "amenity=waste_disposal"

### ISSUE THREAD

**Issue by HaskuldNihil** [gravitystorm/openstreetmap-carto#2237]
Ok?
![waste_disposal](https://cloud.githubusercontent.com/assets/20424329/16959702/04a86fb4-4def-11e6-8380-29290a4decab.png)
Archive with .svg file.
[waste_disposal.tar.gz](https://github.com/gravitystorm/openstreetmap-carto/files/372051/waste_disposal.tar.gz)

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 19 lug 2016, alle ore 19:31, Аскольд <notifications@github.com> ha scritto:
> 
> Ok? 


it is not pixel aligned, please read the icon guidelines

**Comment by HaskuldNihil** [comment]
@dieterdreist where file with recommendations?

**Comment by HaskuldNihil** [comment]
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#pull-requests
m?

**Comment by dieterdreist** [comment]
http://wiki.openstreetmap.org/wiki/Map_Icons
http://wiki.openstreetmap.org/wiki/Map_Icons/Map_Icons_Standards

maybe a reference should be added here:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md

**Comment by pnorman** [comment]
> http://wiki.openstreetmap.org/wiki/Map_Icons
> http://wiki.openstreetmap.org/wiki/Map_Icons/Map_Icons_Standards
> 
> maybe a reference should be added here:
> https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md

Neither of those pages are part of osm-carto. They do offer some general advise for icons and symbols which is applicable to osm-carto.

In any case, this icon is not suitable for fairly obvious reasons.
