### ISSUE TITLE
Errors in rendering names of administrative boundaries

### ISSUE THREAD

**Issue by cleary2** [gravitystorm/openstreetmap-carto#2245]
There are errors in rendering names of administrative boundaries.   For example  http://www.openstreetmap.org/#map=19/48.99957/-110.00728    shows Canada and United States on the reverse sides of their shared boundary.  Other instances noted in other countries as well.

Does not seem to be the same issue as reported in  #2234. Nor would it be related to #2142 as this was reported to have been reverted  #2233.

**Comment by math1985** [comment]
Thanks for reporting @cleary2. This is in fact the same as #2142, that revert hasn't been rolled out to the servers yet.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 26 lug 2016, alle ore 08:31, cleary2 <notifications@github.com> ha scritto:
> 
> Other instances noted in other countries as well.

+1, also in Italy it was reported

**Comment by SomeoneElseOSM** [comment]
I'm not convinced this is about "labels without ways".  For context see https://lists.openstreetmap.org/pipermail/talk-au/2016-July/011031.html .
