### ISSUE TITLE
How to use CartoCSS step by step to render a osm-data

### ISSUE THREAD

**Issue by easycoca** [gravitystorm/openstreetmap-carto#2246]
is there any link to describe how to use CartoCSS step by step to render a osm-data? 
thank you

**Comment by SomeoneElseOSM** [comment]
Some of the content behind https://www.mapbox.com/tilemill/docs/crashcourse/introduction/ might be useful, but obviously bear in mind that that's an introduction to the "old" TileMill (no longer actively developed by Mapbox) and TileMill is just one way of working with OSM data with CartoCSS stylesheets - https://github.com/kosmtik/kosmtik is another widely-used option that is still supported.

What I'd probably suggest is to start by modifying an existing style - perhaps this one, or something simpler like OSM Bright.

This Github is about the "standard" style though - maybe have a look at https://help.openstreetmap.org/ or the OSM wiki?  There's also a "tile serving" mailing list https://lists.openstreetmap.org/listinfo/tile-serving .
