### ISSUE TITLE
Using vertical alignment with marker labels 

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2248]
I just remembered the problem in the past with too small dy for names under icons. Especially if the font is quite big. 
Did you considered using vertical-alignment=top so a bigger name is not blocked by the icon. 
Default is bottom when used with dy >0 according to the documentation

**Comment by math1985** [comment]
@matkoniecz Do you have time to test this?

**Comment by daganzdaanda** [comment]
Please try this! If it works, it would fix #1640 which I find really annoying ;)

**Comment by nebulon42** [comment]
Carto documentation states that the default value for text-dy > 0 is top anyway.

> Default Value: auto (Default affected by value of dy; "top" for dy>0, "bottom" for dy<0.)

**Comment by HolgerJeromin** [comment]
Perhaps i am wrong, but 
https://carto.com/docs/carto-engine/cartocss/properties#text-vertical-alignment-keyword
> Note: The default value is affected by the dy (text down) value. If the dy value>0, the vertical alignment value is bottom. If the dy value<0, the vertical alignment is top.

And we have positive [dy](https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss#L1223) for amenity points.

**Comment by math1985** [comment]
I tried this harder, but my experience was that this made the map significantly harder to read due to the fact that it was no longer clear which label an icon belonged to in crowded environments.

**Comment by HolgerJeromin** [comment]
@math1985 
The map was harder to read if you reduce the distance between the icon and text (because you need no buffer for very large glyphs)?

**Comment by math1985** [comment]
In any case, the buffer between a label and another icon need to be significantly larger (like 2-3 times?) than between a label and the icon it belongs to.

**Comment by nebulon42** [comment]
@HolgerJeromin Interesting find. I don't know where Carto derives their documentation from. They also use an own fork of CartoCSS. Maybe the confusion stems from the fact that Carto was before called CartoDB and should not be confused with Mapbox' Carto(CSS).

In any case the carto we all use uses [mapnik-reference](https://github.com/mapnik/mapnik-reference) for the documentation and this [commit](https://github.com/mapnik/mapnik-reference/commit/3c315b181f2e49cdcc9a0dd876884c1efecf2fa7) shows that the description was apparently wrong before and was corrected.

**Comment by HolgerJeromin** [comment]
@nebulon42 Thanks for this. 
Than this idea is not needed as it is the default (and code will be rewritten with shields anyway)?

Still i am a little bit confused. [Some](https://trac.openstreetmap.org/ticket/4973) [comments](https://github.com/gravitystorm/openstreetmap-carto/pull/767) from that time indicates that the rendering is depending on the char height...

**Comment by nebulon42** [comment]
Rendering currently depends on char height because we use differerent symbolizers for icon and text. If those collide because of too low text-dy then either one is discarded. With shields this cannot happen because it is only one symbolizer and the shield icon does not block the text and vice versa. Even better would be to use the new GroupSymbolizer in Mapnik 3, but I would have to add support to carto first :).

**Comment by nebulon42** [comment]
I think we have to close this.
