### ISSUE TITLE
dog_park base and pattern colors clash with general color system in this style

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#2250]
See also discussion in #2216.

The base color 

* is close to park, scrub/golf_course and grass making it hard to distinguish at times but at the same time not clearly a derivative of park (which it was probably intended to be).
* has the highest chroma of all green tones currently in the style intuitively indicating a distinct type of vegetation - which it does not.

The symbol color

* is very dark and strong making it very similar to individual symbols and completely unlike other pattern symbols (like wood/scrub/wetland).

Examples:

http://www.openstreetmap.org/#map=15/48.1231/7.8258
http://www.openstreetmap.org/#map=16/48.7070/9.1655
http://www.openstreetmap.org/#map=16/47.4295/8.5128

**Comment by dieterdreist** [comment]
2016-07-27 10:39 GMT+02:00 Christoph Hormann <notifications@github.com>:

> The base color
>
>    - is close to park, scrub/golf_course and grass making it hard to
>    distinguish at times but at the same time not clearly a derivative of park
>    (which it was probably intended to be).
>    - has the highest chroma of all green tones currently in the style
>    intuitively indicating a distinct type of vegetation - which it does not.
>
> The symbol color
>
>    - is very dark and strong making it very similar to individual symbols
>    and completely unlike other pattern symbols (like wood/scrub/wetland).
>
>


dog parks are (at least in this area) normal parks, usually fenced areas of
regular parks, with the only difference dog owners being allowed to let
their pet off the leash (and the drinking water fountains having a dog head
as a tap, but that's likely a local particularity ;-) ). Hence I'd expect
the dog parks to be very similar in appearance to other parks (like same
fill, but with hatch / symbol).

**Comment by imagico** [comment]
Note the examples i linked to are specifically cases where these are not parts of a regular park.  Looking over occurrences it seems separate dog areas and parts of regular parks are similarly common.

**Comment by pnorman** [comment]
Wow, that's strong.

**Comment by daganzdaanda** [comment]
It's nice that dog parks get rendered - thats something that can show off the data of OSM. But I agree with all points above, the current rendering is not working. 
My proposal would be 
- make the fill exactly the same as a park 
- add a outline similar to marinas etc in a subtle green shade that's not far away from the fill
- make  the paw the same subtle shade as the outline
- maybe increase the distance between the paw-markers

**Comment by meased** [comment]
I've been playing around and came up with this:
![dogparkinpark](https://cloud.githubusercontent.com/assets/14190496/17392132/095359ce-59d0-11e6-93e8-dcaff56133d0.png)
(this dog park is combined with barrier=fence)

The new playground color is used (on the grounds that dog parks are playgrounds for dogs, and its a good enough color anyway).

The shop_pet icon is reused in the pattern. I don't think the new paw icon is significantly different from the shop_pet one we already have (shop_pet on the left, current paw pattern on the right).
![dog_icons](https://cloud.githubusercontent.com/assets/14190496/17391630/84ffbf76-59cc-11e6-9453-03d20d0467ac.png)
I don't think the slant matters one way or the other.

It also seems like dog parks mapped as nodes should be in amenity-brown for the same reason playgrounds are.

@daganzdaanda, I'm afraid having a green "site" border will make it look like a nature reserve.

**Comment by kocio-pl** [comment]
@meased Could you create a PR for testing?

**Comment by imagico** [comment]
The problems raised here have been addressed in #2268.

This does not mean the new design is without issues - the problems mentioned in #2270 still apply - with the added awkwardness of an implied similarity between playgrounds and dog parks.
