### ISSUE TITLE
Use randomizes pattern for scrub

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2253]
It would be nice to have a randomized pattern (like for forests) also for scrub.

**Comment by imagico** [comment]
jsdotpattern has a scrub symbol included but not a very good one:

http://www.imagico.de/map/jsdotpattern.php#x,256,jdp80122;g5,32,32,32;s,jdp56625;s,jdp2646;s,jdp30409;rx,250,2,32,32;rx,250,2,32,32;rx,250,2,32,32;rx,250,2,32,32;rx,250,2,32,32;rx,250,2,32,32;rx,250,2,32,32;rd,1,0,0,scrub,0.75,7.5,7.5,0,jdp61437,71b571,b5e3b5;

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 27 lug 2016, alle ore 16:43, Christoph Hormann <notifications@github.com> ha scritto:
> 
> jsdotpattern has a scrub symbol included but not a very good one:


the grass_tall on this page looks better, maybe it could become grass_even_taller.svg
