### ISSUE TITLE
Render main entrance

### ISSUE THREAD

**Issue by bugfish** [gravitystorm/openstreetmap-carto#2254]
Please consider rendering notes with the key entrance=main. maybe only in combination e.g. access=customers, permissive, yes

It would be a big advantage on big sites like university’s, shopping malls, company sites to know where to enter the building/sites.

https://wiki.openstreetmap.org/wiki/Key:access
https://wiki.openstreetmap.org/wiki/Key:entrance

https://www.openstreetmap.org/node/4321314820

**Comment by mboeringa** [comment]
> https://www.openstreetmap.org/node/4321314820

Are you local for the above example? Do you know what is going on on the "construction" site to the left of this shopping centre?

Please remove the "Pac-Man" on the site. If these are buildings being demolished, remove them entirely, instead of half.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 28 lug 2016, alle ore 10:08, mboeringa <notifications@github.com> ha scritto:
> 
> Are you local for the above example? Do you know what is going on on the "construction" site to the left of this shopping centre?


also this building shape is clearly bogus: https://www.openstreetmap.org/way/433450681

**Comment by HolgerJeromin** [comment]
Thanks for your suggestion. 
This is related to  #740

**Comment by bugfish** [comment]
* @HolgerJeromin ty for mentioning it, didn't found it with my search
* @dieterdreist, done
* @mboeringa, done
