### ISSUE TITLE
Add linear landforms to natural area exclusion list

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2258]
natural=cliff is covered, but others aren't
- natural=ridge
- natural=arete

cc @imagico

**Comment by imagico** [comment]
Agreed.

Circular ridges are much less common than circular cliffs, the only case where such are commonly found is craters, circular cliffs OTOH also occur with buttes and similar relief forms.

**Comment by pnorman** [comment]
Do any other natural=* tags that are for linear features come to mind?

**Comment by HolgerJeromin** [comment]
According to wiki:

* tree_row
* valley 
* river_terrace
* coastline (has special handling anyway)

**Comment by imagico** [comment]
tree_row is already included, valley and river_terrace have no meaning as a closed way other than an area so the answer is none.

There is natural=hedge with ~500 uses but that's just wrong tagging for barrier=hedge probably.

**Comment by math1985** [comment]
@kocio-pl Do you have time to write a PR for this?

**Comment by kocio-pl** [comment]
I have the time, but I'm totally lost here. 

I don't understand what "natural area exclusion list" is and how could we exclude the things which are not rendered yet. I thought it's what @Ircama was trying to achieve. After him closing https://github.com/gravitystorm/openstreetmap-carto/pull/2138 I'm not even sure what to do. 

Could you elaborate how this code should work?

**Comment by pnorman** [comment]
https://github.com/gravitystorm/openstreetmap-carto/blob/lua/openstreetmap-carto.lua#L40 needs changing

**Comment by math1985** [comment]
Resolved by #2455
