### ISSUE TITLE
Make font size scaling easier for forks

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2266]
Asian scripts have different needs for font size than latin scripts. See #2265 for details.

It might be usefull to make scaling of the font size easier for forks of this style. I could image to define a standard font size of 10 in style.mss. In all other places use a value relative to this standard font size. Example for font size 12: “1.2 × standard_font_size”.

Do you think this might be worth the effort? It is not a solution for #2265 but at least forks that address espacially Asia might easily change the font size of all text in the style…

**Comment by kocio-pl** [comment]
Font size can be hard to scale like this - for example if standard would be 12, then 1.2 x  standard_font_size = 14.4.

**Comment by gravitystorm** [comment]
It's worth considering having font-size variables, like `@font-small: 10px` which would let people change the values more easily. The downside is making all the style definitions harder to read.

The other downside is that other things (like text-dy) are affected by font-sizes, often in a non-obvious way. So we need to not mislead anyone into thinking that, for example, you can just increase the font sized used by shop labels without there being subtle problems.

I would avoid having a single font size defined and having lots of maths everywhere.

**Comment by sommerluk** [comment]
> Font size can be hard to scale like this - for 
> example if standard would be 12, then
> 1.2 x standard_font_size = 14.4.

I do not think this is a problem. Font are vector graphics, and on the map anyway they are placed diagonal or curved and so on, so this would probably not get worser than it is.

**Comment by sommerluk** [comment]
> The other downside is that other things (like text-dy) are
> affected by font-sizes, often in a non-obvious way. So we
> need to not mislead anyone into thinking that, for example,
> you can just increase the font sized used by shop labels
> without there being subtle problems.
>
> I would avoid having a single font size defined and
> having lots of maths everywhere.

Yes.

Closing.

**Comment by HolgerJeromin** [comment]
Perhaps #2248 can help with the dy problem.

**Comment by sommerluk** [comment]
Yes, maybe…
