### ISSUE TITLE
Survey Point should display on map

### ISSUE THREAD

**Issue by OmniBus** [gravitystorm/openstreetmap-carto#2271]
Currently survey point does not show on map. It is good to show it on map as it is a kind of accurate locator in the rural, especially pillar type.

**Comment by kocio-pl** [comment]
How should the icon look like and from which zoom level do you think it should be visible?

**Comment by OmniBus** [comment]
In the wiki page [Survey Point](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurvey_point), User:Chrisana13 suggests an icon circle with dot 

Zoom Level : 15 to 19

**Comment by kocio-pl** [comment]
We already use it for mini roundabouts ([example](http://www.openstreetmap.org/node/3404845697)), so maybe small black triangle without the filling?

z15 may be good for rural areas, but what about cities or other urban areas? They would be more visible than monuments for example. I don't know if they are rare in such places or can be very popular?

**Comment by OmniBus** [comment]
Yes, that is good. Or colour with dark grey / purple.

OpenStreetMap does not distinct various types of survey points well at this moment. Pillar is very notable object wherever in urban or rural. 

But, there are some survey points like a piece of shiny metal on the ground and some with a metal cover. They are mostly found in urban area. In this case, z18 - z19 is more appropriate.

**Comment by kocio-pl** [comment]
Looks like people don't add the type tag, so we wouldn't be able to recognize it even after database reload:
http://taginfo.openstreetmap.org/tags/man_made=survey_point#combinations

So the only safe option is to treat it as a small plaque, which belongs to z19 probably.

**Comment by OmniBus** [comment]
Yes, that is safe option. At least there is a way to show it. Unless OpenStreetMap have improvement proposal like structure=pillar, there is no way to distinguish various types.

**Comment by pnorman** [comment]
I don't think there's a use-case for rendering all survey points, and currently no way to distinguish notable ones.

**Comment by SomeoneElseOSM** [comment]
@pnorman Not even at z19?  Even a small marker in the middle of a town probably justifies something at that level (e.g. http://www.openstreetmap.org/node/670547112 ).

**Comment by math1985** [comment]
Many survey points look like this: http://api.ning.com/files/E0k6Mgw4p3ggISw7kTxaRzKm7FXax4owDnqXUZvzMPe6k*VY8c-t7Pjzyuh4KL4Ji1YBG185Md*1Kx3zqXIEjg__/CIMG0960.JPG?width=737&height=552

**Comment by kocio-pl** [comment]
At the moment I think that:
1. People should start adding survey point types, which allows us to recognize more important ones from the rest (currently probably we have only height for 6 423 objects).
2. Probably database reload is needed.

**Comment by matkoniecz** [comment]
At this point I see no reasonable way to render survey points.

Closing per 

> I don't think there's a use-case for rendering all survey points, and currently no way to distinguish notable ones.

> Many survey points look like this: http://api.ning.com/files/E0k6Mgw4p3ggISw7kTxaRzKm7FXax4owDnqXUZvzMPe6k*VY8c-t7Pjzyuh4KL4Ji1YBG185Md*1Kx3zqXIEjg__/CIMG0960.JPG?width=737&height=552

**Comment by SomeoneElseOSM** [comment]
For completeness, here's how what I ended up going with looks like at z19: https://map.atownsend.org.uk/maps/map/map.html#zoom=19&lat=51.5726&lon=-0.27983

**Comment by jidanni** [comment]
Sure wish https://www.openstreetmap.org/node/5970858911 had shown up on the map.
I was certainly just a few steps away from it the day I took the effort to climb that treacherous mountain.
Finding that pillar erected by the Japanese government 100 years ago would have made my day.
Alas.. I just didn't know. It was hidden on the map.
In fact I had paid special attention to the final top of the hill trying to notice any such markers.
Must have been in the bushes. If I had known there was a marker there I would have taken the extra time to find it.
