### ISSUE TITLE
Show mall icons on low zooms (as department_store)

### ISSUE THREAD

**Issue by kvlahromei** [gravitystorm/openstreetmap-carto#2276]
Hi,
it's pretty useful that the style shows (only) the big shopping amenities, as (local) people usually use it for orientation within cities. Currently it seems a tip confusing, why department stores (one operator) are still visible on low zooms, if malls (multiple smaller operator in one huge building)  aren't :confused:  For example, the [inner city of Rostock z16](https://www.openstreetmap.org/#map=16/54.0865/12.1411).
![osm rostock city shopping](https://cloud.githubusercontent.com/assets/8177370/17548634/0a125f46-5eed-11e6-9723-c4d00850aaac.jpg).

IMHO it would make sense, if we show also the icons for the mall buildings in the same way :+1: . I guess printing the labels would be nice but result in visual clutter? Also skipping small supermarkets/shops might improve the visual impression (at least for cities).

**Comment by math1985** [comment]
Thanks for your suggestion. 

Normally we do print the names of malls at larger zoomlevels, if the mall is large enough. In this case, I suspect the name conflicts with the Schwaanse Straße street name. Street names have priority over mall names.

**Comment by kvlahromei** [comment]
Thanks for the analysis, but the labeling is just an nice-to-have. The essential part of this issue is the icons for malls :wink:

**Comment by Tomasz-W** [comment]
I'm okay with label-only. A dot-rendering for this feature was rejected in https://github.com/gravitystorm/openstreetmap-carto/issues/2651 so I think we don't need an icon here. 

@kocio-pl There hasn't been any new comments here for almost 2 years, so I propose to close this issue.

**Comment by kocio-pl** [comment]
I'm OK with that too., so I'm closing it. If someone wants to discuss it more, it can be reopened.
