### ISSUE TITLE
Check leisure=slipway area status

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2277]
From #484 - how are we handling them, and how do we want to?

**Comment by math1985** [comment]
If a tag can be used on lines, we should also treat a closed linestring without area=yes tag as linestring (we don't want a situation where accidentally closing a loop changes the semantics of the object).

The tag leisure=slipway is commonly used on lines, so we should adapt the lua-file to indicate that leisure=slipway is always a linestring (unless it has an area=yes tag).

**Comment by math1985** [comment]
Resolved by #2455
