### ISSUE TITLE
Please reconsider „add rendering for tourism=apartment“ 

### ISSUE THREAD

**Issue by geowOSM** [gravitystorm/openstreetmap-carto#2283]
A former suggestion was declined in March, 2014.

According to taginfo, **tourism=apartment** is getting closer to **3000 instances**, regional focus is **Europe**: https://taginfo.openstreetmap.org/tags/tourism=apartment#overview

tourism=apartment are particularly **popular and important** in Austria, Germany, Switzerland and parts of northern Italy. Due to structural change in the tourism industry former guest houses and small hotels have been and are being replaced extensively by holiday apartments. 

It appears that mappers are massively inclined to use descriptive names and to **misuse tourism=chalet to get apartments rendered**. I would suggest to render tourism=apartment with the same symbol as tourism=chalet, but starting at a lower zoom-level.

Thanks for your time and consideration
geow

**Comment by nebulon42** [comment]
For me that would be also important as some apartment houses have the names of the owners and without a special symbol these names show up at the houses, which is weird. I don't have a good icon at the moment though.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 15 ago 2016, alle ore 20:32, Michael Glanznig <notifications@github.com> ha scritto:
> 
> For me that would be also important as some apartment houses have the names of the owners and without a special symbol these names show up at the houses, which is weird


it's a data problem, you shouldn't map building=* name=foo and some other tags, if the name is not the name of the building...

**Comment by nebulon42** [comment]
Fair enough. Disregard this reason then. :)

**Comment by math1985** [comment]
On 15 August 2016 at 21:11, dieterdreist <notifications@github.com> wrote:

> it's a data problem, you shouldn't map building=* name=foo and some other
> tags, if the name is not the name of the building..
>


Many mappers disagree. Tagging building=yes, shop=supermarket, name=Tesco
is quite common.

-- Matthijs

**Comment by pnorman** [comment]
Re-opening #401 in favour of this issue

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 15 ago 2016, alle ore 23:58, Matthijs Melissen <notifications@github.com> ha scritto:
> 
> Many mappers disagree. Tagging building=yes, shop=supermarket, name=Tesco
> is quite common.


I know that it's common, but that doesn't make it better, you need AI (or human intelligence) to understand where the tags belong to. It's bad style and should be discouraged.
