### ISSUE TITLE
Generate  vector tiles

### ISSUE THREAD

**Issue by easycoca** [gravitystorm/openstreetmap-carto#2307]
I’v installed  osm2vectortiles,   
http://osm2vectortiles.org/docs/own-vector-tiles/
===============================================================
[root@localhost osm2vectortiles]# docker-compose up import-osm 
WARNING: The AWS_S3_HOST variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
Starting osm2vectortiles_cache_1
Starting osm2vectortiles_pgdata_1
osm2vectortiles_postgis_1 is up-to-date
Starting osm2vectortiles_import-osm_1
Attaching to osm2vectortiles_import-osm_1
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name execveat: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name getrandom: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name memfd_create: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name renameat2: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name sched_getattr: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name sched_setattr: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name seccomp: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name breakpoint: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name cacheflush: could not resolve name to syscall - ignoring syscall.
import-osm_1            | 2016/08/25 11:20:07 Error resolving syscall name set_tls: could not resolve name to syscall - ignoring syscall.
import-osm_1            | No PBF files for import found.
import-osm_1            | Please mount the /data/import volume to a folder containing OSM PBF files.
osm2vectortiles_import-osm_1 exited with code 148

/data/import  pbf exist ,   what's wrong ?  thx .

**Comment by math1985** [comment]
This is not the osm2vertortiles repository, so I'm afraid we won't be able to help you. You could try to contact the authors, you can find contact information at the bottom of http://osm2vectortiles.org/faq/.

**Comment by tilmanb** [comment]
Their github repo is at https://github.com/osm2vectortiles/osm2vectortiles
