### ISSUE TITLE
Review query performance data

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2312]
openstreetmap/operations#105 has a list of queries gathered through sampling. We haven't looked at what queries are slow running for a long time.

**Comment by math1985** [comment]
@pnorman What does the output text file mean exactly? How would you interpret this data?

**Comment by StyXman** [comment]
It's `pid`, `date`, `time`, `time_spent_so_far`, `query`. `date` and `time` are from the moment the stats are taken. `time_spent_so_far` is how much time was used for processing the query at the moment the measure was taken. It's very strange that some times appear to be negative.

**Comment by pnorman** [comment]
I didn't see anything much at the time, and I'd want new data with the 4.0 change if looking at it. Perhaps **after** roads cleanup, when the performance characteristics may have changed.
