### ISSUE TITLE
Bad name posistion for area/multipolygon

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#2331]
Names are often placed in a bad spot for areas.

https://www.openstreetmap.org/relation/5742213
Notice how the name is put in the western corner of the glacier arm.

I have seen this other places as well, but can't seem to find them now.

**Comment by ethan-nelson** [comment]
I just noticed this today as well after adding in survey data. [Here's another example](http://www.openstreetmap.org/way/374776705) where the name is rendered at westernmost point (though I'm not sure if it's related to the beauty node within the way or not).

**Comment by pnorman** [comment]
Duplicate of #349
