### ISSUE TITLE
Render highway=corridor

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2332]
[highway=corridor](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dcorridor) has currently 4803 uses, so it's rare compared to footway (6m+), path (4m+) and pedestrian (400k+), but it has well defined scope (unlike the footway/path problem we had), its own wiki page and the usage is still quite high and growing fast, especially in last year:
![taghistory](https://cloud.githubusercontent.com/assets/5439713/18337010/26ef2c0a-758d-11e6-9703-fb462aba8b01.png)

It's already rendered [on HOT layer](http://www.openstreetmap.org/way/287556526#map=18/51.10029/17.02564&layers=H) as a thin line. We could render it like footway tunnel, probably with some modifications like higher starting zoom level (z17? z18?) and maybe without red dots inside.

**Comment by HolgerJeromin** [comment]
Many ([example](https://www.openstreetmap.org/way/414224953)) are probably mapped as footway and tunnel=* to have them rendered.

**Comment by d1g** [comment]
Why another highway=* tag?

https://overpass-turbo.eu/?w=highway=corridor%20in%20Moscow&R -almost unused
https://overpass-turbo.eu/?w=highway=footway%20and%20indoor=*%20in%20Moscow&R - this is what was used for corridors
https://overpass-turbo.eu/?w=highway=footway%20and%20covered=*%20in%20Moscow&R

Style that renders highway=footway + indoor=* would be more useful.

**Comment by kocio-pl** [comment]
> Why another highway=* tag? Now you made it not just footway/path/bridleway/cycleway but also .../corridor, because some of them were tagged as hw=footway already.

We have much more types and subtypes just for vehicles, which allows us to render them differently, and all the other uses (bicycles, bridle and horse riding) squeezed in just a few tags. highway=footway is for me as generic as highway=road or building=yes: it can be used as a fallback, but it's better to know more what type it is, so we know how to show them.

highway=* + indoor=* is not documented, but has [about 38k of uses](http://taginfo.openstreetmap.org/keys/indoor#combinations), so it may be also interesting. indoor=corridor is mentioned on [indoor wiki page](http://wiki.openstreetmap.org/wiki/Key:indoor) and has [2357 uses](http://taginfo.openstreetmap.org/tags/indoor=corridor). Looks like it should be first decided which is preferred way of tagging corridors.

**Comment by d1g** [comment]
> but it's better to know more what type it is

@kocio-pl, please use additional tags to hw=footway. [highway=* tags are somewhat reserved for routing and routing tags are much more complex](http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions) than rendering or this style.

Please use consistent indoor tagging for indoor objects.

I think [we can retag](http://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct) hw=corridor to hw=footway + [indoor=corridor](http://wiki.openstreetmap.org/wiki/Key:indoor), part of http://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging#Modelling_the_different_indoor_elements.

**Comment by kocio-pl** [comment]
I don't believe highway should stay as it is just because of current routing problems, but it's not about what I would tag or retag - this 5k uses and 2 alternative schemes with also high number of uses is a problem in itself. Before we touch anything, it would be better to set some agreement and fix the documentation first.

I will therefore close this issue now. It can be reopened once the tagging mess is resolved. Thanks for showing different existing scheme.
