### ISSUE TITLE
Adding icon for shop=tea

### ISSUE THREAD

**Issue by Jotam** [gravitystorm/openstreetmap-carto#2347]
The tag shop=tea is now coming very close to [2000 instances](https://taginfo.openstreetmap.org/search?q=shop%3Dtea). I would like to suggest two options:

1) ![teapot](https://cloud.githubusercontent.com/assets/15984044/18515340/53fa64b4-7a95-11e6-974a-90efeda565c8.png) - [SVG](http://vdma.aldebaran.uberspace.de/osm/tea_01.svg)
2)  ![teacup](https://cloud.githubusercontent.com/assets/15984044/18515369/6d3f3238-7a95-11e6-9389-deec79ad5693.png)  - [SVG](http://vdma.aldebaran.uberspace.de/osm/tea_02.svg)

Let me know what you think.

**Comment by kocio-pl** [comment]
I'm thinking about [old type kettle](http://www.publicdomainpictures.net/view-image.php?image=77850&picture=teapot-silhouette) for [shop=houseware](http://taginfo.openstreetmap.org/tags/shop=houseware) (3,3k), but I guess the shape will be distinct enough and turned left - so I choose 1).

**Comment by aceman444** [comment]
It could be a tea bag (the small one put into the glass/pot).

**Comment by polarbearing** [comment]
A tea shop is normally proud of selling loose leaf tea, not the dust that is swiped off the floor and put into tea bags.

**Comment by Jotam** [comment]
Exactly my thoughts, @polarbearing. :-) I had in fact thought about a tea bag as a symbol. It's what they use in JOSM after all. But at least here in Germany, you simply don't find tea bags in a tea shop. It's almost like a deli shop. You only go there if you're looking for something special or of particular high quality.

**Comment by Jotam** [comment]
@kocio-pl: Would you be able to provide a sample rendering with the tea pot? Thanks!

**Comment by kocio-pl** [comment]
You should test the shape on 14px matrix from the beginning - now it doesn't look so good and is harder to recognize for me:
1) ![tea-14-1](https://cloud.githubusercontent.com/assets/5439713/18556015/4b2cb6b8-7b6a-11e6-820c-4ce8adc35a7b.png)

**Comment by meased** [comment]
Is there anything wrong with just reusing the cafe icon?

**Comment by kocio-pl** [comment]
Which one do you mean? amenity=cafe?

**Comment by meased** [comment]
Yeah. The cup icon.

**Comment by Jotam** [comment]
Well, the fact that it's not a cafe. I believe this would be very confusing. The tea pot might be more distinct for tea. I re-worked the SVG and tried to make it less sophisticated. Let's try this:
3) ![g4217](https://cloud.githubusercontent.com/assets/15984044/18579605/f82a2a76-7bf6-11e6-806a-fe183b2d271b.png) - [SVG](http://vdma.aldebaran.uberspace.de/osm/tea_03.svg)

**Comment by dieterdreist** [comment]
2016-09-16 10:19 GMT+02:00 Jotam <notifications@github.com>:

> Well, the fact that it's not a cafe. I believe this would be very
> confusing. The tea pot might be more distinct for tea.


+1, teapot is the typical icon for tea shops, very recognizable, the cafe
icon would be highly confusing

**Comment by kocio-pl** [comment]
I had to resize the image, because it was still 15 px wide (not 14 px). Here's the result:

![2igh7dbn](https://cloud.githubusercontent.com/assets/5439713/18619202/d67b2f0e-7df6-11e6-803c-b722e78c0289.png)

Pretty good for me, but I would try make the spout longer.

**Comment by dieterdreist** [comment]
2016-09-18 23:26 GMT+02:00 kocio-pl <notifications@github.com>:

> Pretty good for me, but I would try make the spout longer.



+1, and the whole pot a bit flatter, maybe the top "knob" could be slightly
less high as well.
