### ISSUE TITLE
Adding icon for shop=art

### ISSUE THREAD

**Issue by Jotam** [gravitystorm/openstreetmap-carto#2350]
With more than [6000 instances](https://taginfo.openstreetmap.org/tags/shop=art), shop=art should have an icon of its own. May I suggest this one? (Credit goes entirely to [yanathan at openclipart](https://openclipart.org/detail/260224/palette).)

1) ![art_01](https://cloud.githubusercontent.com/assets/15984044/18610451/e76f8100-7d1c-11e6-94c4-7bfe62d93c38.png) - [SVG](http://vdma.aldebaran.uberspace.de/osm/art_01.svg)

**Comment by kocio-pl** [comment]
Could you make the holes more visible? Besides that it looks pretty good to me.

**Comment by boothym** [comment]
This icon is use by iD editor to represent artwork or art gallery:
![art](https://cloud.githubusercontent.com/assets/16965772/18630360/fd7c985a-7e63-11e6-9ca1-359ea41d60e1.png)

**Comment by Jotam** [comment]
@boothym : Not bad at all. Could you provide a SVG version of the icon?

**Comment by Jotam** [comment]
This is my proposal with the holes a tiny little bit bigger.
2) ![art_02](https://cloud.githubusercontent.com/assets/15984044/18639748/64090302-7e95-11e6-9192-407892b8d8e4.png) - [SVG](http://vdma.aldebaran.uberspace.de/osm/art_02.svg)

**Comment by Jotam** [comment]
But I liked @boothym 's proposal as well. And it's not bad to use the same icon as one of the editors. Would do you guys think?

**Comment by dieterdreist** [comment]
2016-09-19 18:19 GMT+02:00 Jotam <notifications@github.com>:

> And it's not bad to use the same icon as one of the editors. Would do you
> guys think?



it doesn't matter what the editors use, all that matters is that our icons
are consistent within our map.

**Comment by Jotam** [comment]
Sure. But it's not BAD to use the same icons. And it's pretty consistent, too. Don't you think?

**Comment by boothym** [comment]
@Jotam I couldn't find anything in the iD source - and wasn't able to extract the source using inspect element on the image in iD, but I've asked for the source.

**Comment by boothym** [comment]
Here's the svg used by iD: https://github.com/bhousel/maki/blob/mb-pages/src/art-gallery-24.svg

**Comment by kocio-pl** [comment]
iD version doesn't work after rescaling - but of course, maybe making holes bigger could work too:
3) ![art-14-3](https://cloud.githubusercontent.com/assets/5439713/18688639/8c181932-7f85-11e6-81a4-d8d7fc820f4f.png)

2) rendering:
![zkqn_f7q](https://cloud.githubusercontent.com/assets/5439713/18689584/250aa0de-7f8a-11e6-9326-05bbb769023e.png)

This shape is great, but see how the icons are placed - under Kosmtik with Mapnik 3.5.13 the labels are invisible and the icons are shifting across the zoom levels! Changing icon (bag-14.svg) restores normal placing, but still I don't know what's wrong with [this file](https://github.com/kocio-pl/openstreetmap-carto/blob/art/symbols/art-14.svg) and we need it to behave... =}
