### ISSUE TITLE
Label wrapping is not calculated on a per zoom level basis

### ISSUE THREAD

**Issue by IknowJoseph** [gravitystorm/openstreetmap-carto#2352]
Based on recent OSM-Talk discussion. Related to issue #1028 ? Not a openstreetmap-carto issue?

Label wrapping seems to be calculated once and applied for all zoom levels. for example, at zoom level 9 a label must be split into three lines to fit within a feature:

![screenshot from 2016-09-19 13-11-28](https://cloud.githubusercontent.com/assets/1896882/18631654/271ab7ee-7e6b-11e6-97a3-de9311ae7b5d.png)

But zoomed in the label would fit on two lines:

![screenshot from 2016-09-19 13-11-57](https://cloud.githubusercontent.com/assets/1896882/18631684/4ef29a84-7e6b-11e6-8068-2189fb47e3e8.png)

Zoomed in further there's no reason to split the label over any number of lines:

![screenshot from 2016-09-19 13-12-25](https://cloud.githubusercontent.com/assets/1896882/18631695/628e3512-7e6b-11e6-99e9-0c495b78fe85.png)

![screenshot from 2016-09-19 13-12-48](https://cloud.githubusercontent.com/assets/1896882/18631697/6462b16a-7e6b-11e6-9f5c-0c4c14e4f9b6.png)

Can the wrapping of a label be recalculated at every zoom level?

**Comment by kocio-pl** [comment]
I guess this is a Mapnik issue. Do we have a way to control wrapping via Carto?

**Comment by math1985** [comment]
> Can the wrapping of a label be recalculated at every zoom level?

Yes, per zoom level, we specify the line length.

You seem to suggest that a label should always be as long as possible. I'm not sure though if that is really the nicest looking way of rendering?

**Comment by IknowJoseph** [comment]
Yes, I think that the label should be as long as possible (as defined by not overlapping / clashing with others). The original thinking behind this being that current label rendering is splitting names at hyphens, making them appear incorrect. 

See for example the Steven F. Udvar-Hazy Center:

![screenshot from 2016-09-19 15-06-33](https://cloud.githubusercontent.com/assets/1896882/18634917/f6797570-7e7a-11e6-90ca-13f6aab9635c.png)


In this example there is space to render the label as a single line, but it is instead rendered "wrongly" by inserting a line break after a hyphen.

Both the examples in this issue, hyphenated or not, would arguably look much better if the label rendering was calculated at each zoom level to make the most of the available horizontal space.

**Comment by imagico** [comment]
One reason for having line breaks is reducing metatile boundary issues, the other is keeping the label within or close to the feature it labels.  For the latter the conditions could be relaxed when the feature is large compared to the label size, the former is a scale independent and therefore universal problem.

**Comment by math1985** [comment]
> Both the examples in this issue, hyphenated or not, would arguably look much better if the label rendering was calculated at each zoom level to make the most of the available horizontal space.

I disagree actually. In this case, wrapping the label (but perhaps not at the hyphen) looks better to me, especially in conjunction with the icon.

**Comment by IknowJoseph** [comment]
Ok, so I've found an example of rendering changing on a per zoom level basis. Atlantic City on two lines:

![screenshot from 2016-09-19 15-28-49](https://cloud.githubusercontent.com/assets/1896882/18635735/ed3365e0-7e7d-11e6-88f7-a69115819935.png)

And then zoom in and it goes to a line:

![screenshot from 2016-09-19 15-29-05](https://cloud.githubusercontent.com/assets/1896882/18635751/fb17cd68-7e7d-11e6-8544-0a292f4c7ea2.png)

Is this different because it's a point an not an area? I'm not sure I've seen any areas that behave like this.

My request then, I suppose, would be for more of this removal of line breaks where horizontal space allows. It's still my opinion that the rigid looking rendering style in the first example (insisting that the area label must be rendered on three lines even when horizontal space allows for less) is aesthetically unpleasing.

**Comment by math1985** [comment]
I like the 'Atlantic City' label in the first image, though.

**Comment by IknowJoseph** [comment]
Me too :)

Or rather, I like how the rendering of the labels changes with zoom level to give the impression of making the most of the available space. It makes me think that software is making choices based on some rules and the nature of the data to be rendered rather than adhering to some arbitrary rules that don't take into account instances such as "massive areas".

I can see that this is an issue of personal preference, however, and I'm new to openstreetmap-carto and don't know how decisions get made around here, so I'm happy if you just want to mark as won't-fix.

**Comment by StyXman** [comment]
I think it's not so much a matter of arbitrary limit, it's that's computationally faster to apply a rule that's based on local data (the length of the label) than one based on the environment (see if other labels collide and resolve which should be warped and which not, and probably which labels not to render at all). The first has a complexity of O(1), the latter O(N²) where N is the amount of labels. In places full of labeled features (regions full of shops, etc) this can take considerably longer.

**Comment by pnorman** [comment]
> Label wrapping seems to be calculated once and applied for all zoom levels

No. Each zoom level is rendered completely independent of others. For that matter, so is each metatile.

I'm of the view that it's generally better to have labels wrap consistently and that there's nothing with the first three images. The fourth one has issues, but line wrapping is the least of them.

**Comment by pnorman** [comment]
> I'm of the view that it's generally better to have labels wrap consistently and that there's nothing with the first three images. The fourth one has issues, but line wrapping is the least of them.

Closing this issue, as the original report was based on a misconception.
