### ISSUE TITLE
Add icon for shop=funeral_directors

### ISSUE THREAD

**Issue by boothym** [gravitystorm/openstreetmap-carto#2355]
Noticed the iD editor has an icon for this, but it's not rendered here. The tag has over 7000 uses: http://taginfo.openstreetmap.org/tags/?key=shop&value=funeral_directors

The gravestone/cemetery icon is available here: https://github.com/bhousel/maki/blob/mb-pages/src/cemetery-24.svg

**Comment by kocio-pl** [comment]
Thank you for opening this ticket! 

I guess this icon does not work standalone (only as an element of cemetery pattern) and is somehow similar to memorial icon. However I was thinking about it for months and I guess simple grave candle [like this](http://image.shutterstock.com/display_pic_with_logo/3984323/373834150/stock-photo-black-candle-373834150.jpg) would be OK. Maybe coffin shape could work too, but it's probably hard to avoid cross on it to make it more recognizable, and that wouldn't be so universal then.

**Comment by SomeoneElseOSM** [comment]
FWIW elsewhere I went with https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/symbols/shop_funeraldirectors.p.16.png - but as you say with a cross on it it's really not universal.

**Comment by boothym** [comment]
@kocio-pl I know you think it doesn't work but could you please render it anyway? Thanks

**Comment by kocio-pl** [comment]
2) ![funeral_directors-14-8](https://cloud.githubusercontent.com/assets/5439713/18691718/85f59ec0-7f95-11e6-8938-0219367375c8.png)

**Comment by boothym** [comment]
Looks like the perfect icon for a candle shop! ;)

**Comment by pnorman** [comment]
With moderate usage and being a *very* specialised shop, I'm inclined towards not rendering with its own icon.

**Comment by boothym** [comment]
It has more than the art, tea and tobacco shops,and almost the same deli - all of which have been discussed recently and submitted. What level of usage would it need to get rendered?

**Comment by dieterdreist** [comment]
2016-09-23 11:49 GMT+02:00 Paul Norman <notifications@github.com>:

> With moderate usage and being a *very* specialised shop, I'm inclined
> towards not rendering with its own icon.
>


why would we not want to show specialised shops? Millions of people are
dying every month. IMHO the less specialised a shop (category) is, the less
interesting it is to show it, because you won't be sure it offers what you
are looking for.

**Comment by boothym** [comment]
I notice shop=bag, hifi, musical_instrument, outdoor, and seafood are all rendered but are used less than funeral_directors, and arguably just as specialised.

Is there any difference in priority given to a shop tag rendered with its own icon than one with a dot? If not then what is the problem with icons for lesser used shop tags, since they will just be replacing a dot?

**Comment by kocio-pl** [comment]
I also don't understand why do you consider them "specialized" - I feel they are very generic. For me specialized could mean mobile phone (subclass of shop=electronics) or cheese (subclass of shop=food). What more general category do you see for this one? Or how do you define the term "specialized"?

shop=funeral_directors  is one of the most typical "shops" we don't show now (or don't do it clearly) - like clockmaster, tax office, electronic repair, tailor, lawyer etc. Some of them have a lot of uses, while others are rare in our database, and we have a database limitation excluding some of the keys. That's just tagging or technical problem we have to deal with, but this tag has no such issues. So I don't see the reasons against showing this icon.

**Comment by kocio-pl** [comment]
Rendering preview - 1) still does not work for me:
1) 
![bbuauoad](https://cloud.githubusercontent.com/assets/5439713/18808555/bcd7d7a0-8265-11e6-949f-e4c900d6f03b.png)

4) 
![oxs 1bhg](https://cloud.githubusercontent.com/assets/5439713/18808552/b265cd2c-8265-11e6-997b-96578a047472.png)

**Comment by pnorman** [comment]
> What level of usage would it need to get rendered?

I don't see a hard cutoff when the decision needs to change.

When looking at the map to see what is around you, I see the generic dot rendering as sufficient. I don't regard someone looking at the map to **find** a funeral directors as a significant usecase.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 26 set 2016, alle ore 10:33, Paul Norman <notifications@github.com> ha scritto:
> 
> I don't regard someone looking at the map to find a funeral directors as a significant usecase.


this can be said for anything, especially if no reasoning is given. Anything shown in the map is suitable for orientation anyway, if it is visible in the real world

**Comment by kocio-pl** [comment]
As I said few times already, I don't expect to find things on this map, rather to explain the space. Finding POIs is a job for app like OsmAnd or other specialized service.

**Comment by Jotam** [comment]
I would like to see funeral directors rendered in their specific way. But I admit it is also hard to find a suitable icon. Funeral rites are extremely diverse across cultures. The cross is certainly not the perfect choice. And a tomb stone would suggest there is ... mmh ... well ... a tomb. What about a coffin? That is pretty universal (although not entirely of course).

**Comment by kocio-pl** [comment]
Just try to draw a coffin with just 14px matrix... My take was horrible, so I just skipped it:
![funeral_directors-14-2](https://cloud.githubusercontent.com/assets/5439713/18883278/edd2228c-84e2-11e6-8b32-60600b7f3e10.png)

**Comment by kocio-pl** [comment]
Another [try](https://github.com/gravitystorm/openstreetmap-carto/issues/2619) (by @MaestroGlanz):
![funeral_directors-14-13](https://user-images.githubusercontent.com/5439713/27511771-0e7f0440-592d-11e7-9056-8c5ac3c65f46.png)

What do you think about it?

**Comment by HolgerJeromin** [comment]
I dont think dead muslime people are burried in a box with a cross on it :)

**Comment by MaestroGlanz** [comment]
I support that too ;) 

@HolgerJeromin But what would you suggest?

**Comment by kocio-pl** [comment]
What about something like this (without the cross on top, I think):

https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/symbols/shop_funeraldirectors.p.16.png

**Comment by matkoniecz** [comment]
It would look like a car shop.

**Comment by Jotam** [comment]
IMHO the car _without_ the cross doesn't work at all. The more I think about it, the more I'm convinced that finding an icon that would depict all cultures worldwide is next to impossible. Funeral rites are extremely diverse. 
However, the question then is whether in Asian or Muslim cultures, there are funeral directors at all? Or is this maybe a specifically western thing? In that case, a coffin with a cross would work perfectly well.

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/tags/?key=shop&value=funeral_directors#map is showing it across the world, including high presence in Japan

**Comment by Jotam** [comment]
Okay, I admit Japan is a bit of problem there. 

However, it seems to me that 99% of the rest of funeral directors are based in countries that have a predominantly Christian heritage. This goes of course for all of Europe, the US, Australia, Latin American as well as African countries. And the big chunk in the South China See are the Philippines, which are the biggest Christian country in Asia.

So maybe the cross symbol would be okay for the (by far) biggest part of the world.

**Comment by kocio-pl** [comment]
Thanks for asking this question and for checking it! 

I would rather avoid religion symbols. It's not always easy - we stucked with cross for hostpitals and similar items, because general symbol exists, but who heard about "[red crystal](https://en.wikipedia.org/wiki/International_Red_Cross_and_Red_Crescent_Movement#The_Red_Crystal)"? 

For funeral there can be less loaded symbols, even if truly universal one is not possible to find, and I still think that coffin shape might be of use.

**Comment by SomeoneElseOSM** [comment]
Re gravestone, I'm not convinced that's culturally neutral either (nor is a "funeral car" or even a coffin), but an outline coffin shape is probably the least worst option of what's been suggested so far (including mine).

**Comment by Jotam** [comment]
Just what I'm saying: There simply is no culturally neutral symbol for funerals. The topic is much too diverse. However, I was suggesting that the profession of funeral **directors** seems to exist predominantly in Christian cultures (Japan excluded). So my choice would be a coffin shape with a cross on top. (My concern is that without a cross the coffin would not be recognized as such.)

**Comment by MaestroGlanz** [comment]
I agree with @Jotam. I think we should use this kind of symbol and use another one for i.e. primary muslim countries. Unfortunately, I cant say, what kind of symbol would be accurate there. It cant be a coffin, since they dont use them as far as I know.
So, this would be a renderer's rule "if fun.dir. NAND country==x" for any country and "if fun.dir. AND country=Egypt" for an exception.

**Comment by kocio-pl** [comment]
Could anybody make a PR then? I expect that it will still needs some testing and discussion (especially idea of different rendering in different countries), but maybe this is the way to go and I have not so much time for this lately.

**Comment by Jotam** [comment]
How about this one? 
![path4177](https://user-images.githubusercontent.com/15984044/33210882-3ae4456a-d11c-11e7-939b-62d6a80f8420.png)
SVG file is here: http://www.roeskamp.de/shop_funeraldirector.svg

**Comment by kocio-pl** [comment]
The shape is OK for me, however:
- please test all the icons at 14 px to see how they would look on the map - scaling down doesn't work for many otherwise nice icons
- what is the license? It has to be CC0/PD for us to be used.

**Comment by Jotam** [comment]
Sure, I tested the SVG with 14px. Only the PNG came out a little bigger (22px). This one is a 14px-PNG sample: ![path4177](https://user-images.githubusercontent.com/15984044/33211096-4732d4ac-d11d-11e7-89c2-c056d70f072d.png)

Since I created it, the license is anything we need it to be. :-) I'm very happy to release this as CC0/PublicDomain.

**Comment by kocio-pl** [comment]
Great, it still looks good for me! 

So - anybody willing to make a PR and test rendering?

**Comment by Jotam** [comment]
I can do the PR. But I don't have a testing environment for rendering.

**Comment by kocio-pl** [comment]
That's why we have a Docker environment:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

If you have Windows or macOS you may have problems installing Docker (especially with not the latest OS versions), but I would advise to just run VirtualBox with Linux inside and install Docker inside it. I can help you with that if you want.

**Comment by MaestroGlanz** [comment]
@Jotam then you could list it in the OSM-Wiki, like mine:
https://wiki.openstreetmap.org/w/images/3/34/Bestatter.svg

**Comment by Jotam** [comment]
This is what it would look like:
![funeral_example](https://user-images.githubusercontent.com/15984044/33557439-84b06690-d907-11e7-825a-13205b8f1a2f.png)

**Comment by kocio-pl** [comment]
Great, I see that you have managed to set the environment! Could you prepare the pull request?

**Comment by Jotam** [comment]
PR created.

**Comment by boothym** [comment]
Sorry but there should not be a cross on the coffin unless it is explicitly marked as religion=christian. A funeral director's shop, in the UK anyway, is normally secular - if someone wants a religious funeral or service it is then arranged with the local place of worship as part of the service provided by the funeral director.

**Comment by matthijsmelissen** [comment]
A cross is a recognizable symbol for the death / graves - just like a phone horn represents calling even on devices without horn.

**Comment by kocio-pl** [comment]
We are very careful with symbols and that's why it takes a lot of time to find them sometimes, like in this case. But there are many cases when there is hard to find symbols not related to religious background - or they exist, but would be not recognizable (ever heard about "[red crystal](https://en.wikipedia.org/wiki/International_Red_Cross_and_Red_Crescent_Movement#The_Red_Crystal)" for example?).

**Comment by pnorman** [comment]
👎 for a cross.

The symbol also seems a bit heavy in relation to those around it.

I'm still 👎 the idea of rendering it with its own symbol, for the reasons above.

**Comment by matkoniecz** [comment]
> Noticed the iD editor has an icon for this, but it's not rendered here.

This shop is rendered - just not with a special icon.

I agree with @pnorman that none of proposed icons work and it is really unlikely that we will find fitting one, so I would propose to close - and welcome PR that would solve this issue (though I am not expecting that it is fixable).

**Comment by kocio-pl** [comment]
We have cross in hospital, doctors, pharmacy and veterinary outside the religious objects. I can think of changing hospital cross into hotel bed icon (with health color and in the circle, of course, probably also mirrored to make additional difference), but with the rest it's hard to get rid of the cross. We should try (and we did here), but if there's no good alternative, it's reasonable to use what works mostly. 

I feel https://github.com/gravitystorm/openstreetmap-carto/issues/2355#issuecomment-346708082 is a correct description of the problem.

**Comment by Jotam** [comment]
I absolutely agree with @kocio-pl. We have indeed discussed many different options. But this simply is the best in terms of recognizability. 
In this context, the cross is _not at all a religious symbol_. Almost universally, the cross is recognised as a symbol for **medicine / healthcare** and for **death**.

**Comment by polarbearing** [comment]
Note that the christian cross and the medical one have different shapes (different vs same length of the bars), thus please don't mix them. 

On cemeteries/graveyards we explicitly use the christian cross if religion is set accordingly, in contrast to a tombstone if not.

**Comment by Jotam** [comment]
Again, this is not a Christian cross in the sense that it is a religious symbol. It's just a (almost) universal symbol for death.

**Comment by polarbearing** [comment]
Can you provide some evidence for such cross-cultural universality?

**Comment by ArcticGnome** [comment]
If you don't want a cross, I see a lot of Halloween-related icons put a horizontal line through the widest part of the coffin. For some reason, that makes it look more coffin-like.

**Comment by kocio-pl** [comment]
Could you show us how would it look like?

**Comment by kocio-pl** [comment]
@ArcticGnome Do you plan to give it a try?

**Comment by Tomasz-W** [comment]
I'm worried that any symbol (all of them are connected with religion/ cemetery/ death) put in shop-violet would look bad. Default dot in enough for me in this case.

**Comment by kocio-pl** [comment]
I was thinking about brown because of that.

**Comment by Tomasz-W** [comment]
But then it may be confusing, and seen as some amenity instead of shop.

**Comment by kocio-pl** [comment]
I have proposed once to render violet only shops selling physical objects, while shops selling services (like travel agent, hairdresser or funeral directors) would be rendered in brown. I still think this is good idea.

**Comment by Tomasz-W** [comment]
As we didn't find consensus about proper icon for this feature, I propose to stay with dot-rendering and close this issue.

**Comment by kocio-pl** [comment]
OK, I give up for now, might be reopen if needed.
