### ISSUE TITLE
Updating the image in README.md

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2362]
I'd like to know how to generate image [we show in README.md](https://github.com/gravitystorm/openstreetmap-carto/blob/master/README.md#openstreetmap-carto)? 

I think we should add this instruction just before ["Tagging a release" section in RELEASES.md](https://github.com/gravitystorm/openstreetmap-carto/blob/master/RELEASES.md#tagging-a-release), to make sure we always have current rendering with each release.

**Comment by pnorman** [comment]
:+1: to adding it to RELEASES.md, although not all releases will need a new image

**Comment by nebulon42** [comment]
Always showing the current rendering may be tricky as the image has to be updated when
* any rendering of the shown features changes in the style
* the data of the shown area changes and leads to changes in rendering

This has to be verified manually. The person updating the image also needs up-to-date data in the given area.

**Comment by kocio-pl** [comment]
For me RELEASES.md is a general TODO checklist - and that's good. The maintainers are supposed to make decisions in case of doubt, but they should at least know all the typical steps.

This image is a minor problem - just a general idea how does this style look like - and lack of current construction color is not important, but over time there can be more things needing update. We can just say something like: "check if rendering of the example image should be updated, and here is how to do it..." and that would be enough.

I guess @matkoniecz is the one who knows how to generate the example?

**Comment by kocio-pl** [comment]
I was [wrong](https://github.com/gravitystorm/openstreetmap-carto/blob/33294204576e778b3072ee38446ea140961e1a96/preview.png) - @gravitystorm and @sommerluk did it too. Could you share how did you generate it?

**Comment by sommerluk** [comment]
I had just made a screenshot at osm.org and then cut it in Gimp to the correct dimensions.

Hower, you could render it also locally:
- Download data of this place (for example with Josm)
- Render it locally and make the screenshot
- Cut it in your favorite image editor

**Comment by kocio-pl** [comment]
I thought rather some command line tool to easily export the same area from Kosmtik for example. Screenshot from OSM.org is always a postcard from the past, not a sneak peek into the future. =}

**Comment by gravitystorm** [comment]
I always took a screenshot too, since I've never had a Chicago extract loaded locally.

**Comment by kocio-pl** [comment]
I think [having bounds defined in the Kosmtik configuration](https://github.com/kosmtik/kosmtik/issues/159#issuecomment-240774850) would make it easy to export current rendering when needed.
