### ISSUE TITLE
Render countries capital based on their admin_centre nodes

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#2365]
As per https://github.com/gravitystorm/openstreetmap-carto/pull/2314#issuecomment-249276557 and https://github.com/gravitystorm/openstreetmap-carto/pull/2314#issuecomment-249291847, it would be good if we could have the countries capitals rendered based exclusively on their `admin_centre` nodes, instead using nodes with `capital=yes` + `admin_level=2`

ie,  querying for the `admin_centre` node of `admin_level=2` relations

An example in overpass for South America:
http://overpass-turbo.eu/s/ixw

This should solve old discussions like https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/capital#Use_the_relation_boundary and also avoid adding an unnecessary `admin_level` tags in the nodes (which seems to be only a workaround for renderers)

An example for this: [Brasília](https://www.openstreetmap.org/node/34567423) is the `admin_centre` of 3 relations: an `admin_level=2`, `admin_level=4` and an `admin_level=8`

By having `admin_level=2` in its node, just to have it rendered as a capital, has one issue: people looking at the node will think that Brasília is only part of an `admin_level=2` relation/area (which is an incomplete information). This is basically the discussion [here](https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/capital#Combination_with_admin_level)

The Humanitarian style also has the same issue hotosm/HDM-CartoCSS#281

**Comment by pnorman** [comment]
We do not have this information in the database. osm2pgsql does not have membership information and nodes as relation members do not make it into geometries.
