### ISSUE TITLE
StateOfTheMap birds of a feather

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2366]
We will be holding a birds of a feather session at 10 am on sat (today) at SOTM. I'm opening this issue both because on absence of a mailing list its the best way to notify peope, and to capture notes related to the session.

We can decide what to talk about when everyone gets together. Topics I'd like to cover include
- next steps for lua and db reload
- setting style purpose and cartographic direction
- a framework for better colour palletes and selection
- being better at closing requests for new features, and the backlog that needs closing against the reload milestone

**Comment by kocio-pl** [comment]
This event is already behind us.
