### ISSUE TITLE
Some Travis checks are failing

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2372]
If you look inside Travis tests, like this:

https://travis-ci.org/gravitystorm/openstreetmap-carto/builds/162536783

there are multiple errors like:

`Error: placenames.mss:65:4 Unrecognized rule: shield-margin`

or

`-:1: parser error : Document is empty`

Yet the "build exited with 0".

Is it expected behavior and should ignored or there's something wrong under the hood and some action is needed?

**Comment by StyXman** [comment]
From `bash`'s doc: The return status of a pipeline is the exit status of the last command, unless the `pipefail` option is enabled.  If `pipefail` is enabled, the pipeline's return  status  is  the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands exit successfully.

The test is adding `wc -l` as the last command, so unless `pipefail` is enabled, this will always succeed. I can only wonder why is that there. Should we replace it with a redirection to `/dev/null`?

**Comment by math1985** [comment]
Thanks @StyXman!

**Comment by HolgerJeromin** [comment]
@StyXman the `wc` is there to see if the style rules generates a combinatorial explosion. 
But i dont know if someone really looks at the number and is alerted if the line count jumps :-)

**Comment by nebulon42** [comment]
Speaking of Travis tests: is there a specific reason why still 0.12.1 is used for Carto? Is that the live version? IMO it should be replaced with the latest version but targeting a specific Mapnik API version. This is now possible with:

-a / --api VERSION - Specify Mapnik API version (e.g. --api 3.0.10) (default: 2.3.0)

**Comment by kocio-pl** [comment]
I think we're [ready to drop MML](https://github.com/gravitystorm/openstreetmap-carto/issues/2080#issuecomment-249390120), so 0.13.x would be necessary. 

It would probably also mean more changes in `.travis.yml` and removing `travis_check_project_files` - am I right?
