### ISSUE TITLE
Add leisure=fitness_centre icon/text

### ISSUE THREAD

**Issue by boothym** [gravitystorm/openstreetmap-carto#2375]
Currently leisure=fitness_centre is not rendered (neither is fitness_station as mentioned in #1870). 

Even without an icon at the very least the name should be displayed, just like sports_centre. 

At the moment any properly tagged gym is invisible which doesn't help encourage people to tag it correctly.

**Comment by micahcochran** [comment]
There are now 4789 instance of this tag.

How about this as an icon?
![weight lifter 2](https://cloud.githubusercontent.com/assets/7433104/19945714/5dc24dd6-a10f-11e6-8c7f-2fd0957fc3a0.png)

**Comment by boothym** [comment]
I notice in the maps.me app it is rendered with weights:  https://github.com/mapsme/omim/blob/e646b270bd68d0c27adac5ed712682cf1500b68c/data/styles/clear/style-night/symbols/gym-l.svg - I wonder if they would allow it to be used?

**Comment by boothym** [comment]
@gravitystorm @math1985 @pnorman @matkoniecz 

Any chance we could get leisure=fitness_centre rendered the same way as a sports_centre node, so that the name is visible? Right now there are many correctly tagged gyms etc. which aren't rendered on the map. An icon can be added or text fine-tuned later.

**Comment by boothym** [comment]
@kocio-pl while we wait for an icon, any chance of the fitness_centre being rendered exactly like sports_centre, so that the text is visible?

**Comment by kocio-pl** [comment]
I do few other things here, so if somebody creates the code, that would be great. Are you willing to do that?

**Comment by boothym** [comment]
If all that's required is adding fitness centre beside sports centre in project.mml then I will submit a PR with that change soon.

**Comment by kocio-pl** [comment]
Look for sports centre also in MSS files - project.mml is more or less a database part, styling is defined in MSS.

**Comment by kocio-pl** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/issues/1870#issuecomment-335064319
