### ISSUE TITLE
Where to find "Noto Emoji Regular"

### ISSUE THREAD

**Issue by giggls** [gravitystorm/openstreetmap-carto#2379]
Is "Noto Emoji Regular" included in Ubuntu? On Debian I needed to install it manually from https://github.com/googlei18n/noto-emoji/blob/master/fonts/NotoEmoji-Regular.ttf

**Comment by matkoniecz** [comment]
To quote https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md

> On Ubuntu 16.04 or Debian Testing you can install all required fonts with

> sudo apt-get install fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted ttf-unifont

What is your distribution?

**Comment by pnorman** [comment]
Looks like it's not included on Debian, or probably Ubuntu. We need to add something to the documentation that the packages don't include all Noto fonts. If someone wants to bother with this particular one will be up to them - most deployments won't care about it.

**Comment by giggls** [comment]
@matkoniecz: Why do you ask for my distribution? I clearly stated, that I had to manually install the font on **Debian**.

However looking at http://packages.ubuntu.com and https://packages.debian.org it seems like the Ubuntu packages are taken verbatim from Debian into Ubuntu. Thus it might be a good Idea to open a Bug against the Debian package to get the Emoji fonts included.

**Comment by pnorman** [comment]
Reported to Debian at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841890

**Comment by matkoniecz** [comment]
> Why do you ask for my distribution? I clearly stated, that I had to manually install the font on Debian.

Because there is Debian Stable, Debian Unstable and Debian Testing (mentioned in install instruction). At least according to https://www.debian.org/doc/manuals/debian-faq/ch-choosing.en.html Debian has multiple Distributions (or maybe Debian Stable/Debian Unstable/Debian Testing is simply considered as a separate LInux distribution?)
