### ISSUE TITLE
Outline for  leisure=sports_centre and stadiums missing

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2388]
[Sports_centre](http://www.openstreetmap.org/way/370767384#map=19/51.87857/8.48727) has no fill/stroke color, so the outline is not visible. I think this is a regression.

The [definition](https://github.com/gravitystorm/openstreetmap-carto/blob/b6d96dbccced3ec658fadbe577ecf0caea84e98a/landcover.mss#L60) and the [code](https://github.com/gravitystorm/openstreetmap-carto/blob/b6d96dbccced3ec658fadbe577ecf0caea84e98a/landcover.mss#L531-L538) says this should have a fill color. 

Edit: 
Same for leisure=stadiums
http://www.openstreetmap.org/relation/185411

**Comment by imagico** [comment]
It has a fill but should probably also get an outline at the higher zooms (though not from z13 as it is currently rendered for other areas with the same color).

**Comment by kocio-pl** [comment]
What if the outline would be green instead of brown (as in schools or hospitals)?

**Comment by kocio-pl** [comment]
Fixed with https://github.com/gravitystorm/openstreetmap-carto/pull/2574 (I don't know why this issue was not closed automatically).

**Comment by HolgerJeromin** [comment]
This issue was mentioned in a comma separated list. That's why it was not closed by github itself.
