### ISSUE TITLE
Render an icon for shop = craft

### ISSUE THREAD

**Issue by Alekzzander** [gravitystorm/openstreetmap-carto#2389]
Hello!

Please render shop = craft, I mean, it's for shops that sell anything for art, and hope it'll be useful.

Thanks a lot.

**Comment by pnorman** [comment]
:-1: to having its own icon with 2.4k uses and no special considerations. With that usage I would expected it to already be rendered as a generic shop.

**Comment by kocio-pl** [comment]
I'm not aware of any special considerations needed here and numbers are not a problem for me - the usage is already above 2k limit and rising fast, so reaching upper limit (like 5k) may happen in not so distant future:
![taghistory 2](https://cloud.githubusercontent.com/assets/5439713/19022982/b126cb3a-88e3-11e6-804f-d86c47f38c81.png)

But I just don't know how should this icon look like. Any ideas?

**Comment by d1g** [comment]
> be rendered as a generic shop

It should be rendered as a generic shop first (I forgot issue where it was discussed last time)

We don't have time to pick/draw proper icons for ever shop, but we draw more shops (dots)

**Comment by aceman444** [comment]
I think the dot should be draws for any shop, where specific icon is not done. Not just for a selection of shops.

**Comment by kocio-pl** [comment]
@aceman444 Please fill new issue for this, since it's much broader than current issue.

**Comment by kocio-pl** [comment]
Looks like we already have an issue including this problem, so [I wrote my comment](https://github.com/gravitystorm/openstreetmap-carto/issues/2099#issuecomment-254392921).

**Comment by kocio-pl** [comment]
Resolved by https://github.com/gravitystorm/openstreetmap-carto/pull/2415.
