### ISSUE TITLE
Special case rendering for private roads inside landuse=military

### ISSUE THREAD

**Issue by d1g** [gravitystorm/openstreetmap-carto#2390]
After 2.44.0, 5ee3078d492afcdb320607d203e6964354d7a8c4 new style does great job for civil private/no roads, but military-related objects should be always in red IMO

http://www.openstreetmap.org/#map=15/51.4132/41.9416

Is possible/feasible to tag them "inside_landuse_military" during import and set custom style?

See also #1889

**Comment by math1985** [comment]
Thanks for the suggestion. Honestly I don't see reason to render roads on military land different from roads on (civil) secret service land, embassy land, airport grounds or whatever. I therefore don't think we should implement this.
