### ISSUE TITLE
Noto font is not used for Korean (and probably Chinese and Japanese)

### ISSUE THREAD

**Issue by vholten** [gravitystorm/openstreetmap-carto#2391]
Version 2.44.0 of the stylesheet has been rolled out to the openstreetmap.org servers, and we can see the new Noto font for Latin and Arabic, for example. However, it is not used for Korean. This is an image from #2349, where the old font and Noto were compared:
![compare](https://cloud.githubusercontent.com/assets/5209216/19003398/e12afcbe-8750-11e6-9f99-bc6f1011d592.png)
Currently on openstreetmap.org, the font looks like the old font on the left. Re-rendering is not the problem; the following example from openstreetmap.org has been re-rendered as can be seen from the new city dots.
![12](https://cloud.githubusercontent.com/assets/5209216/19003423/fbfc89d6-8750-11e6-8055-01b21a0e3537.png)

Probably, Noto is also not used for Chinese and Japanese. There was a discussion in #2349 about the character 门 which would change in appearance in Chinese, but it has not changed.

**Comment by math1985** [comment]
Are the tiles re-rendered? If not, maybe the right font is missing on the tile servers?

**Comment by math1985** [comment]
Sorry for the bureaucracy, but would somebody be able to open an issue at https://github.com/openstreetmap/chef/?

**Comment by littlebtc** [comment]
http://www.openstreetmap.org/user/Littlebtc/diary/39593#comments

Fonts seems to be installed to the server. Is there any reason that font still not rendered?

**Comment by vholten** [comment]
See my comment at https://github.com/gravitystorm/openstreetmap-carto/issues/2397#issuecomment-251492324 for a possible reason.

**Comment by littlebtc** [comment]
mod_tile Patch is now available and asia region is under update.

I open #2402 as a follow-up.
