### ISSUE TITLE
Don't rely on noto metapackage recommends

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2397]
Ref #2396

Install instructions say to use the metapackage but on 16.04 this relies on recommends. Instead we should specify hinted, unhinted, and mono.

This is not an issue on 14.04.

**Comment by sommerluk** [comment]
As I’m working under openSUSE, I can’t help much with the necessary Debian/Ubuntu packages.

Note however that in the Noto github repository, we have:
- Noto fonts for most scripts are available both as hinted and unhinted version
- Noto fonts for some (less common) scripts are available only as unhinted version
This should be taken in account. Maybe the hinted and the unhinted packages are mutually exclusive on Ubuntu?

The Noto Mono fonts should not be necessary as we do not use them in our font list.

Could we recommend

**Comment by sommerluk** [comment]
As I’m working under openSUSE, I can’t help much with the necessary Debian/Ubuntu packages.

Note however that in the Noto github repository, we have:
- Noto fonts for most scripts are available both as hinted and unhinted version
- Noto fonts for some (less common) scripts are available only as unhinted version This should be taken in account. Maybe the hinted and the unhinted packages are mutually exclusive on Ubuntu?

The Noto Mono fonts should not be necessary as we do not use them in our font list.

Could we recommend installing the fonts directly from the github repository? This would be less comfortable for system admins, but we do not need to keep up to date a package list for linux distribution. And of course the github repository has the most current version of the font. Noto fonts are reparted among various repositories: https://github.com/googlei18n?query=noto

**Comment by pnorman** [comment]
> Could we recommend installing the fonts directly from the github repository?

We could require or recommend a minimum version of the fonts which might require us to change our install instructions to not reference the packaged versions, but we'd need a reason to do so.

**Comment by sommerluk** [comment]
I’m okay with updating the Ubuntu instructions.

Question: Following http://packages.ubuntu.com/xenial/all/fonts-noto-cjk/filelist this Ubuntu package contains the TTC format of the CJK font (instead of language- and weight-specific TTF fonts). Have you tested if the TTC font works correctly with mapnik?

It might nevertheless be worth to mention in the install instructions that Noto is under active development (which is not natural for fonts) and newer versions can improve the rendering.

**Comment by vholten** [comment]
Thanks @sommerluk for checking the file format. I think that the TTC format of the CJK font is indeed the reason why it is not loaded. In the `load_fonts()` C++ function in https://github.com/openstreetmap/mod_tile/blob/master/src/gen_tile.cpp#L172 it is specified that fonts are only loaded `if (p && (!strcmp(p, ".ttf") || !strcmp(p, ".otf")))`, so fonts with a `.ttc` extension would be skipped.

(Mapnik itself does support TTC fonts as documented at https://github.com/mapnik/node-mapnik/blob/master/docs/Using-Fonts.md)

**Comment by littlebtc** [comment]
TTC seems to be supported seems Mapnik 2.3.x. mapnik/mapnik#2274

So which may be the best way to fix that? Change `mod_tile` to support TTC or split the TTC file anyway?

**Comment by gravitystorm** [comment]
Excellent detective work @vholten.

I would suggest fixing mod_tile is the best approach.

**Comment by littlebtc** [comment]
I opened openstreetmap/mod_tile#141.

Seems to be a easy fix, but I don't know how to do it properly, and what else could be happened.
