### ISSUE TITLE
capital-names doesn't require place tag

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2407]
The WHERE condition on the `capital-names` layer is
```sql
WHERE capital = 'yes'
  AND admin_level = '2'
```

Capitals [used to require `place IN ('city', 'town') AND name IS NOT NULL`](https://github.com/gravitystorm/openstreetmap-carto/pull/2314/files#diff-0abb12fe08393e8ddccd19e688ded6e5R1597). This means the new code can't use the point place partial index with its `place IS NOT NULL AND name IS NOT NULL` current index.

**Comment by pnorman** [comment]
Not sure if this should be fixed before v2.44.1 or not

**Comment by nebulon42** [comment]
Looks like I've not delivered the quality one should expect. Mea culpa and thanks for correcting it. I would suggest to include it into the patch release.
