### ISSUE TITLE
Change the way the attribution is showed in map

### ISSUE THREAD

**Issue by yopaseopor** [gravitystorm/openstreetmap-carto#2412]
In the Spanish talk-es email list we are talking about licenses and specially attribution. The main sentence is: We need an specific permission about every use of some open data to OSM because we only put source attribution in changeset and in element, because OpenStreetMap contributors is not enough for the attribution clauses of CC-by for the majority of administrations with open data (for example). So I have a question, what about change the way attribution it is showed in OSMCarto, being similar to other maps like Gmaps (depending the zone you have other attributions than only Google 2016) ? Map would can show the sources of the changesets you are watching every moment, for example, making the attribution clear and immediate.

**Comment by math1985** [comment]
OSMCarto does not show any attribution. If you are referring to the text '© OpenStreetMap contributors ♥ Make a Donation' on the bottom right of openstreetmap.org, this is put there by the opestreetmap website. Their repository is located at https://github.com/openstreetmap/openstreetmap-website.
