### ISSUE TITLE
Monaco country label displayed on water

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#2413]
Just to discuss whether this is wanted and if not whether there are alternatives.

![screenshot_2016-10-15_12-40-13](https://cloud.githubusercontent.com/assets/156724/19409488/a7b20826-92d4-11e6-84c5-3c4d634a0abe.png)

Features of interest
* land+water https://www.openstreetmap.org/relation/1124039 relation boundary=administrative, admin_level=2
* only land https://www.openstreetmap.org/relation/36990 relation boundary=land_area, admin_level=2
* city https://www.openstreetmap.org/node/1790048269 node place=city role admin_centre for first two relations

**Comment by jojo4u** [comment]
One addition: Usual tagging practice for most other countries is a node with place=country which has role=label on the boundary relations. The usage of a "label" role is rejected by osm-carto - a decision I agree with.

**Comment by matkoniecz** [comment]
I think that in this case it is acceptable - especially as it in center of land area would result in collision with a city label.

Generally, this situation is really rare (microstates with territorial waters) that it seems to not be a problem.

place=country nodes, role=label is tagging for render what invites moving nodes around - tagging for renderer.

I thinkat that there is no need for changes.

**Comment by pnorman** [comment]
If we changed our rendering of boundaries over water this might need reconsideration.
