### ISSUE TITLE
rendering for man_made=spoil_heap

### ISSUE THREAD

**Issue by Autharite** [gravitystorm/openstreetmap-carto#2421]
Hello. Disused spoil heaps generally cover large areas and they are remarkable in the landscape. Presently there is no rendering at all for them. I think their names should be rendered (like for forests, parks...). Thank you.

**Comment by kocio-pl** [comment]
Probably it could be rendered like landuse=landfill.

**Comment by Autharite** [comment]
I do not think so. Disused landfill should be tagged with disused:landuse=landfill or abandoned:landuse=landfill, because they are not landfills any more. They can be sometimes be tagged (entirely or partially) with landuse=forest. disused:landuse=landfill and abandoned:landuse=landfill have no rendering.

**Comment by kocio-pl** [comment]
We sometimes reuse the same look for different objects (with different tagging). We can't show every type of object in a different way, because there's so many of them, so if they are somewhat similar, they could look the same.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 27 ott 2016, alle ore 16:45, Autharite <notifications@github.com> ha scritto:
> 
> Disused landfill should be tagged with disused:landuse=landfill


disused landfill is a landfill where the filling has been removed? As long as the landfill is there, it could be considered a landfill, not?

**Comment by polarbearing** [comment]
Yeah but the original question was about spoil heaps. [Wiki](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dspoil_heap). 966 uses so far. Taginfo does not show combinations, though there are objects co-tagged with landuse or names indeed?

**Comment by Autharite** [comment]
I do not think it is suitable to tag disused spoil heaps with landuse=landfill, because it is not the present use of the land. Many of them are now covered with forests. So why should we use landuse=landfill whereas the present use of the land is landuse=forest? man_made=spoil_heap exists (as well as disused:landuse=landfill and abandoned:landuse=landfill) and I think it makes much more sense: this is a man-made structure which still exists (it has a huge impact on the landscape), but the present landuse is not landfill any more.

The rendering problem is for me the following: when the whole area is covered with forest it is OK, because the name of natural=wood or landuse=forest is rendered, so the name of the spoil heap appear. (see here for an example https://www.openstreetmap.org/way/197160020#map=17/50.45042/4.40840)
However, when the spoil heap is partly covered with wood, scree, scrub... the name of the spoil heap does not appear. (see here for an example https://www.openstreetmap.org/way/446298382)

This is why I propose to have a rendering for the area tagged with man_made=spoil_heap. In my opinion, it should be rendered the same way as the name of natural=wood or landuse=forest.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 28 ott 2016, alle ore 15:20, Autharite <notifications@github.com> ha scritto:
> 
> man_made=spoil_heap exists (as well as disused:landuse=landfill and abandoned:landuse=landfill) and I think it makes much more sense


+1, I also prefer tagging them as explicit feature and not as land property 


cheers,
Martin

**Comment by mboeringa** [comment]
As a side node: it might be an idea to add man_made=embankment way features along the outer extent of the heap if the spoil heap is no longer in active use and being extended. That will emphasize its size and structure and be visible on the map as a clearly man_made structure.

**Comment by d1g** [comment]
> Probably it could be rendered like landuse=landfill.

I'm sure that at least some of https://en.wikipedia.org/wiki/Spoil_tip were simply tagged as landuse=landfill pre 2015. If we have experts in mining with free time, they should check planet for (im)proper tag usage.

To me, man_made=spoil_heap + abandoned:landuse=landfill makes sense.

**Comment by Tomasz-W** [comment]
Whichever color we choose, it should be used also in #372 , very similar object. IMO it should be something between grey, brown and green, matching current landfill color.
https://www.openstreetmap.org/way/385790303

**Comment by jeisenbe** [comment]
https://overpass-turbo.eu/s/M89 shows that 583 have `landuse=landfill` in combination, and the wiki page `landuse=landfill` shows "mining waste" as an example. So these features can be tagged with `landuse=landfill` in addition, when appropriate, and this is rendered. 

If the feature is not "a site for the disposal of waste materials", because it has been abandoned and is now overgrown with shrubs or trees, the present landuse or natural vegetation can be mapped and rendered. Closed.
