### ISSUE TITLE
highway tag for elements of highway relation not honoured

### ISSUE THREAD

**Issue by mfrasca** [gravitystorm/openstreetmap-carto#2422]
mapnik/mapnik#3458
@der-stefan suggests it's something that can be solved at style level, while @mboeringa suggests a different way to tag objects as to avoid the problem.
what would you people here say?

**Comment by matkoniecz** [comment]
I would argue that https://github.com/mapnik/mapnik/issues/3458 is mapped incorrectly and linear highway=residential also should be mapped like highway=pedestrian at http://www.openstreetmap.org/way/234875262#map=18/50.06165/19.93733

**Comment by pnorman** [comment]
Please provide complete tagging information in a ticket if its relevant. From the basic information here this is a duplicate of another issue about highway tags on relations

**Comment by mboeringa** [comment]
I think this issue can be safely closed. As I stated in the linked issue, there is a better way of tagging this by only re-using nodes instead of ways, not even requiring a multipolygon to get the desired rendering.

**Comment by mfrasca** [comment]
how do you map something as highway=residential at the same time as highway=pedestrian?
the objects I was editing and about which I reported, are members of this relation:
http://www.openstreetmap.org/relation/6357817

the current edits do not represent reality as observed by me. it is a triangular square where you can drive or park, as you prefer. there is no "parking area", the whole area is a parking lot if you think so, and the whole area is a road if that's what you need.

**Comment by mboeringa** [comment]
> how do you map something as highway=residential at the same time as highway=pedestrian?

You don't, **you re-use the _nodes_** to create **_new_** way objects for the highway=residential objects, that then become independent objects from the highway=pedestrian triangular area. They will get their own OSM id in this case.

What you currently did, was re-using the **_ways_** to build a multipolygon, which is unnecessary and doesn't give the result you actually want. Please review your tagging practice and try to understand what I suggest.

Anyway, in the end, you simply cannot represent two different things as a single object. If objects are as transformable and ephemeral as you suggest in the following quote:

> the whole area is a parking lot if you think so, and the whole area is a road if that's what you need.

you will have to satisfy yourself with the given cartographic abstraction and representation of reality of a certain map style. If you cannot live with that, you shouldn't be using cartographic maps, or develop your own visualization.

**Comment by mfrasca** [comment]
> If objects are as transformable and ephemeral as you suggest in the following quote:
>>    the whole area is a parking lot if you think so, and the whole area is a road if that's what you need.


I'm sorry, I obviously didn't explain the situation.
it's not transformable, nor ephemeral.
people in countries like mine and like Morocco use the space freely. there's no parking lot as such, but there's a residential road which spans the whole triangle, and where people park if they think so, and where they drive where no cars have been parked. It's not a parking lot, it's not pedestrian area, you might call it a multipurpose residential area. The place in the example is not at all an exception.

> What you currently did, was re-using the ways to build a multipolygon, which is unnecessary and doesn't give the result you actually want. Please review your tagging practice and try to understand what I suggest.

Looks like I'm starting from a different point of view. I indeed reused the ways to build a multipolygon, and I expected a result as I described at mapnik/mapnik#3458. My understanding was that laying two ways on top of each other was bad practice and I did my best precisely to avoid that. I understand what you suggest, but (my perception:) (1) sounds to me like you're suggesting this because the renderer behaves as it behaves; (2) it conflicts my previous understanding of the mapping guidelines. Is this really the intended practice? Do you have links to the page where your suggestions are included as best practice?

**Comment by dieterdreist** [comment]
sent from a phone

> On 21. Oct 2017, at 00:50, Mario Frasca <notifications@github.com> wrote:
> 
> it's not transformable, nor ephemeral.
> people in countries like mine and like Morocco use the space freely. there's no parking lot as such, but there's a residential road which spans the whole triangle, and where people park if they think so
> 

IMHO, a triangular space like this is a square (omnidirectional), not a residential road (linear). The tagging details should be discussed with the Italian community (e.g. because in Italy there’s a distinction between “parking” and “staying” (sosta), with both implying the driver to walk away, but the first requiring a signed parking lot), to find out whether amenity=parking should be added or not.
For the square there’s a place=square tag (often different from the actual road surface)

**Comment by mfrasca** [comment]
[place=square](http://wiki.openstreetmap.org/wiki/Tag:place%3Dsquare) is not rendered, or is it? I'm not aware of a name for the place in question, I didn't ask.
the location under discussion is in Tinghir, Morocco, I spent there a month last year, and I'm from Naples, Italy.
I'm afraid there's no active Moroccan OSM community, I tried to find one, to no avail.

The original point was about this behaviour:
Situation:
You have three roads entering a triangular place. Buildings are along the three sides. You can drive from one corner to the other, and you can drive using all the available space. There's no signalization, but you see that a few cars are parked, scattered in the area, or along the edges. Next time you observe, the parked cars are scattered differently.
Action and Intention:
I tag the three legs of the triangle as highway=residential, and I would like the included area to be rendered just as the legs, merged with them, so I add a relation defining the area, and tag it as highway=residential.
Observed rendered result:
the highway tag in the three legs is not honoured in the rendering.
Trying other tags:
if I tag the legs differently than the relation, then they are rendered.
(and this was the reason for tagging the relation with "amenity=parking", which does help describe reality even if not signalled nor formalized.)

**Comment by dieterdreist** [comment]
for the case you describe, amenity=parking seems suitable, as it is used for parking and it is at least tolerated to park. Highway=* seems also   appropriate (with * at least residential), as the square is needed to go from one of the roads to the others, right?

**Comment by HolgerJeromin** [comment]
Keep in mind that a linear street models the center line and an area street models an outline. So reusing the middle line for another area outline could be wrong.

**Comment by mfrasca** [comment]
exactly as @HolgerJeromin writes, this is the core of my report.
when I added the three ways `highway=residential`, plus the relation containing all of them and defining the area also as `highway=residential`, I had expected this result:
![untitled-1](https://user-images.githubusercontent.com/122869/31863044-9aff4554-b70d-11e7-967b-eebd751fc6f5.png)
My observation is that the `highway` tag on the ways is only honoured if the relation does not redefine the same tag.
The only workaround was offered by @mboeringa , requiring me to only reuse nodes, not the ways.

**Comment by dieterdreist** [comment]
2017-10-22 16:47 GMT+02:00 Mario Frasca <notifications@github.com>:

> exactly as @HolgerJeromin <https://github.com/holgerjeromin> writes, this
> is the core of my report.
> when I added the three ways highway=residential, plus the relation
> containing all of them and defining the area also as highway=residential,
> I had expected this result:
>


actually @HolgerJeromin <https://github.com/holgerjeromin> wrote that you
can't do it like this, because the area is not delimited by the centre of
the road, so there are different ways required for defining the area and as
roads on the square.

**Comment by mfrasca** [comment]
I'm afraid I don't follow your reasoning, and I don't manage to have others see my point.

**Comment by dieterdreist** [comment]
2017-10-25 2:01 GMT+02:00 Mario Frasca <notifications@github.com>:

> I'm afraid I don't follow your reasoning, and I don't manage to have
> others see my point.
>

the screenshot you posted seems to illustrate the situation well. The
square is the space signed as "parking", if it has a name it should get a
place=square tag as well. If the square is delimited by the buildings
around it, the buildings should share nodes with the square (topology).

The roads seem to be mapped fine.

Which tags aren't "honoured" as of the issue title?

**Comment by mfrasca** [comment]
I have tagged the area as parking just to have the roads correctly rendered. my observation suggests there's no formal parking there, there's a residential area/road used indifferently as parking or as road.
My initial tagging was different, and the surprising resulting rendering you can see in the [initial issue](https://github.com/mapnik/mapnik/issues/3458)

**Comment by dieterdreist** [comment]
sent from a phone

> On 25. Oct 2017, at 14:19, Mario Frasca <notifications@github.com> wrote:
> 
> I have tagged the area as parking just to have the roads correctly rendered. my observation suggests there's no formal parking there, there's a residential area/road used indifferently as parking or as road.
> My initial tagging was different, and the surprising resulting rendering you can see in the initial issue
> 


thank you for the link. Your initial issue is due to oldstyle multipoligon handling in osm2pgsql. Still it could be considered a mapping problem: you connected centre lines to the outline of an area, but should extend the area beyond the highway lines (to their outer borders at least). This way you wouldn’t be able to reuse them for the relation, and won’t encounter the “bug”
