### ISSUE TITLE
Rendering artifact ...

### ISSUE THREAD

**Issue by ticino** [gravitystorm/openstreetmap-carto#2427]
There is some strange rendering artifact here at this zoomlevel:
https://www.openstreetmap.org/#map=17/50.57183/9.57566
If you zoom in or out it looks normal ...

**Comment by pnorman** [comment]
Nothing is jumping out to me.

![image](https://cloud.githubusercontent.com/assets/1190866/20029049/05e11cf4-a2ff-11e6-847b-1b0aa6965204.png)

[If reporting a rendering bug, you always need to include a cropped screenshot of the issue](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#reporting-issues)

**Comment by ticino** [comment]
Hi, 

 OK in your snapshot it's fine. But here it looks like this: 
(tried different browsers also in oruxmaps)

![Uploading Snapshot_b.png…]()

**Comment by ticino** [comment]
Ok  next try to upload the screenshot ... sorry.

![snapshot_b](https://cloud.githubusercontent.com/assets/5102134/20029268/0c48abb8-a348-11e6-86e2-d17f14cfd787.png)

**Comment by imagico** [comment]
This is a data error (someone drawing a really big building) that has meanwhile probably been fixed but has not fully grown out of the caches yet.  Nothing to do with the style.

**Comment by ticino** [comment]
Ok Thanks!

**Comment by aceman444** [comment]
Yes, there was recently a known incident of a building covering the whole world (or so), so these "rendering artifacts" can be seen all over the globe.
