### ISSUE TITLE
Name rendering of unusually shaped forest

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#2428]
Hello, there.

I found what seems to be a name rendering problem: https://www.openstreetmap.org/way/448092558

As you can see, this forest has a very unusual shape, and that seems to cause a problem in the rendering of it's name: it's not centered on it, even roughly, but on the far left of the polygon. Even if it can't be displayed on the geometrical center of the polygon, it should be a lot closer of it than it is currently.

I suspect this to be a Mapnik issue, but, as I don't know how deep the rendering can be affected by the stylesheet, I prefer reporting it here to be sure, and will report it to Mapnik if relevant.

Regards.

**Comment by HolgerJeromin** [comment]
The current algorithm is: find centroid, if this is not inside the polygon go to one side and find a suitable place there. North/south position is not changed.
#1740

**Comment by Penegal** [comment]
That could be improved this way:
1. find the centroid;
2. if it is inside the polygon, write label here; if outside, try slightly more on the left, then slightly more on the right, and keep trying while pushing away.

This way, the label would be the closest possible of the centroid, at the cost of complexifying the algorithm; that would improve rendering in such corner cases, though, and the 2., AFAIK, won't be executed on the vast majority of polygons, only on corner cases.

**Comment by pnorman** [comment]
We have very little control over where Mapnik labels polygons, so can't really do anything in the stylesheet.

**Comment by HolgerJeromin** [comment]
The correct place would be https://github.com/mapnik/mapnik/issues/

**Comment by polarbearing** [comment]
I have a parking P icon rendered outside the [polygon](https://www.openstreetmap.org/way/454480657), so it appears the parking would be in the building, where it is not. 

Is that also a mapnik issue, or worth a new ticket here?

![52778](https://cloud.githubusercontent.com/assets/8266355/20455432/5cd41d78-ae5c-11e6-94d4-fdc99499c882.png)

**Comment by pnorman** [comment]
> I have a parking P icon rendered outside the polygon,

Outside the polygon is an issue here.

**Comment by math1985** [comment]
Hmm, it sees the relevant code on our side does contain ' marker-placement: interior;'. Is somebody able to create a mimimal example  (minimal db and minimal cartocss/xml) to definitely prove it's not a problem on our side?
