### ISSUE TITLE
Width and height attributes on SVG symbols

### ISSUE THREAD

**Issue by joto** [gravitystorm/openstreetmap-carto#2430]
SVG files contain several places where they have the width and height of the image. There is the `width` and `height` attributes as well as the `viewBox` attribute on the `<svg>` element. Some of the icons currently use `width="100%"` and `height="100%"` (for instance [bag-14.svg](https://raw.githubusercontent.com/gravitystorm/openstreetmap-carto/372032b80475b6b4ef2883254689f7e0c46b828b/symbols/bag-14.svg)) in addition to having the "real" size on the `viewBox`, some icons set a specific width (for instance [tea-14.svg](https://raw.githubusercontent.com/gravitystorm/openstreetmap-carto/372032b80475b6b4ef2883254689f7e0c46b828b/symbols/tea-14.svg)).

The Mapnik rendering seems not to care about the `width` and `height` attributes, the icons all render fine, but the icons are often imported into the OSM wiki for documentation and Mediawiki doesn't handle them equally well. In the wiki icons with the `100%` setting will appear as 512x512 pixel monsters unless the size is set explicitly. (I stumbled upon this in the context of the [taglists](https://wiki.openstreetmap.org/wiki/taginfo/taglists)). I think it would be easiest to change the icons at the source, ie this repository, instead of having to do something special for the wiki, unless there are some problems I am not seeing (@nebulon42 mentioned there are problems when I raised this on the talk mailinglist, but didn't elaborate).

(And yes, it is somewhat strange that we need to import those icons into the wiki instead of using them directly etc. etc., but I am trying to fix one problem at a time here.)

I'd be willing to make the changes to the icons if there is some agreement here.

**Comment by math1985** [comment]
I ran into this problem as well, but didn't know about the solution. Thanks! I agree we should fix the icons on our side.

**Comment by kocio-pl** [comment]
They could be at least consistent, but it's not clear which form should we use until @nebulon42 tell us why he prefers %.

**Comment by nebulon42** [comment]
I wanted to have full previews in Github for my Osmic repository and I wanted that the size can be controlled in Carto via attributes.

> The Mapnik rendering seems not to care about the width and height attributes

That seems to be correct as I found out. So I guess there is not really a reason left to not change it if it helps elsewhere.

**Comment by kocio-pl** [comment]
@joto 
> I'd be willing to make the changes to the icons if there is some agreement here.

Go ahead then!
