### ISSUE TITLE
Change color for natural=grassland

### ISSUE THREAD

**Issue by Taunide** [gravitystorm/openstreetmap-carto#2433]
Please set back the color of natural=grassland to what it already was some time ago.
And how it is described in https://wiki.openstreetmap.org/wiki/Tag:natural%3Dgrassland
It is for a reason that it is a little bit darker like landuse=meadow, because it makes ground structure in the High Vosges, High Rhoen mountain or other regions better distinguishable. One color for everything has no meaning for map usage, better leave it blank.
http://www.openstreetmap.org/#map=15/50.4666/10.0429
If you need to "save" colors urgently, save natural=scrub and make it like natural=wood. Both are far less distinguishable.
Thanks.

**Comment by pnorman** [comment]
changed in 5f76d2acd20d5d8ca33fa14f01d54104bdead0b1 as part of #1655

**Comment by imagico** [comment]
This was changed in #1655 after it has previously already been discussed in context of the wood/forest color unification.

Mapping practice shows no consistent difference between areas mapped as natural=grassland and landuse=meadow.  Locally there are sensible uses of these tags for different purposes but globally it is just a huge mess - quite similar to wood/forest.  So the decision was to not make this distinction in rendering.

Suggesting to unify natural=scrub and natural=wood - tags for areas with physically very distinct characteristics - in favour of differentiating natural=grassland and landuse=meadow - tags with, if at all, just nuances in meaning regarding human use of the areas which are often not verifiably - is not really that practical.

**Comment by math1985** [comment]
@Taunide Thanks for your request! I agree with the reasoning set out by @imagico, so I will close this request as won't fix.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 11 nov 2016, alle ore 11:23, Christoph Hormann <notifications@github.com> ha scritto:
> 
> Locally there are sensible uses of these tags for different purposes but globally it is just a huge mess - quite similar to wood/forest.


is this really a big issue? People typically use the map locally, not to compare areas on a global level

**Comment by Taunide** [comment]
Thanks Dieter. Moreover I doubt that it can be judged "as a mess" on a global level, just local. I already provided a link to local mapping where the tagging decisions were made sensible and with local knowledge. Since this case was closed already by the board further discussions here are probably a waist of time and energy since the case will not be re-opened.

**Comment by dieterdreist** [comment]
natural=grassland seems more kind of a landscape type to me, rather than an
actual feature like a meadow, and I agree the wiki definition is rather
fuzzy for distinction of this tag and other similar tags.

I didn't want to endorse the specific tag, what I wanted to point out: if
people locally have an idea what different tags are representing (for them
/ in their context) and they deliberately and consistently (in the
spatially delimited context) use different tags, it could make sense for
this style to differentiate the rendering of these tags, even if there's no
consistent use on a global level.

**Comment by imagico** [comment]
So far no arguments have been brought against the reasoning for not differentiating landuse=meadow and natural=grassland here or in the [in the German forum](https://forum.openstreetmap.org/viewtopic.php?id=56346)

Even if @math1985 was probably a bit quick to close the lack of actual arguments on the matter itself in both places confirms his decision.

For everyone interested to form an opinion on tagging consistency here overpass turbo links for landuse=meadow and natural=grassland - choosing the area around Hamburg as an example but you can also look in other places of course:

http://overpass-turbo.eu/s/k0m
http://overpass-turbo.eu/s/k0l

I won't argue the point that consistent use of tags according to a documented and verifiable specification is not a requirement for rendering it here - this would essentially be equivalent to have mappers tag styling directly (i.e. this area should be rendered in color x etc.) and contradicts the core ideas behind mapping in OSM IMO.

**Comment by andischan** [comment]
> So far no arguments have been brought against the reasoning for not differentiating landuse=meadow and natural=grassland here or in the in the German forum

@imagico Distinguishable features in the landscape should have a different rendering.

**Comment by Taunide** [comment]
Last message I've got was the case was closed anyway (without asking), so no need to discuss it further. 

    andischan <notifications@github.com> schrieb am 13:59 Montag, 27.März 2017:
 

 
So far no arguments have been brought against the reasoning for not differentiating landuse=meadow and natural=grassland here or in the in the German forum
@imagico Distinguishable features in the landscape should have a different rendering.—

**Comment by imagico** [comment]
> @imagico Distinguishable features in the landscape should have a different rendering.

I would love to introduce differentiated rendering of different kinds of grass dominated areas but we cannot render directly based on what is observable in reality here, we can only render what is actually mapped and tagged in the OSM database.

If you want to see this happen in the long term the most essential prerequisite for that would be a well defined, globally usable and not climate or culture specific tagging scheme to indicate such differences.
