### ISSUE TITLE
historic=wayside_shrine not rendered

### ISSUE THREAD

**Issue by PontiacCZ** [gravitystorm/openstreetmap-carto#2434]
I added a wayside shrine to OSM 19 days ago (http://www.openstreetmap.org/node/4460585378), it does not render. Its importance for orientation in the countryside is the same as wayside_cross, I believe it should have the same rules (from which zoom to render, etc.)

**Comment by HolgerJeromin** [comment]
Thanks for your suggestion. 
This is already beeing discussed in #131.
