### ISSUE TITLE
Remove admin_level from capital queries

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#2437]
The code for capital=yes and admin_level can be simplified now: The only remaining nodes with place=* and capital=yes are country capitals [(overpass)](http://overpass-turbo.eu/s/k1x). The usage of admin_level=2 for capitals is also problematic as detailed [here](https://lists.openstreetmap.org/pipermail/tagging/2016-October/030312.html).

Some background:
In October I documented the defacto usage of capital=yes only on country capitals [on the wiki](https://wiki.openstreetmap.org/wiki/Key:capital) and cleaned up capital=yes in around 40 cities plus around 80 in Russia [(edit page)](https://wiki.openstreetmap.org/wiki/Automated_edits/Jojo4u#2016-10_Edit_of_capital.3D.2A_on_Russian_county_capitals)

#2365 gave country capitals a special rendering. Because of the complexity of the needed SQL there where some regressions (#2408 #2393 #2399).

The discussion about expanding the capital query to more than city and town (reference: #2408) was done [on wiki](https://wiki.openstreetmap.org/wiki/Talk:Key:capital). Village and hamlet still are used with some good arguments while municipality ~~is used because there is no better tag~~ and the alternative place=atoll might be too obscure. The current cases are documented [here](https://wiki.openstreetmap.org/wiki/Key:capital#Capitals_which_are_not_tagged_as_city_or_town).

**Comment by nebulon42** [comment]
@jojo4u Thank you for your work on this. Since data now looks that way I have no problem with just using `capital=yes` and also promoting villages and (maybe) hamlets to capitals. I'm not in favour of municipality as it is a bit odd.

I would suggest that you try to do the PR yourself. I can offer help if needed.

**Comment by nebulon42** [comment]
We still might want to include `capital=2` too.

**Comment by kocio-pl** [comment]
Manually closing after manual merging https://github.com/gravitystorm/openstreetmap-carto/pull/2472.

**Comment by nebulon42** [comment]
Ah, thx.
