### ISSUE TITLE
Document hstore extension need

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2439]
There is no mention of CREATE EXTENSION hstore in the section about loading the data.

**Comment by pnorman** [comment]
Not sure why Github didn't close this when #2486 was merged, but it's fixed.

**Comment by HolgerJeromin** [comment]
> Not sure why Github didn't close this when #2486 was merged, but it's fixed.

Because this was not merged into the main branch. After merging lua to master this issue would be closed by github.
