### ISSUE TITLE
Rendering of leisure=beach_resort

### ISSUE THREAD

**Issue by doktorpixel14** [gravitystorm/openstreetmap-carto#2440]
[Leisure=beach_resort](http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dbeach_resort) is an important tag in touristical regions. The wiki tells us, that we have to tag this instead of natural=beach, if the beach area is managed. Because of that, there is a white hole on the map in some coastal areas and that doesn't look very good. Maybe you could use the same colour like on natural=beach, but with an parasol symbol in the center.

**Comment by dieterdreist** [comment]
2016-11-14 21:42 GMT+01:00 doktorpixel14 <notifications@github.com>:

> The wiki tells us, that we have to tag this instead of natural=beach,



that's orthogonal. You'll tag the beach as natural=beach and a beach resort
as leisure=beach_resort, and both tags can be valid at the same spot.

**Comment by doktorpixel14** [comment]
> "Use natural=beach for areas of sand next to the sea or to water **which are not managed.**"

So should we change this in the Wiki? Because in my opinion, it sounds like you can't use both tags in one place.

**Comment by dieterdreist** [comment]
2016-11-15 19:13 GMT+01:00 doktorpixel14 <notifications@github.com>:

> "Use natural=beach for areas of sand next to the sea or to water *which
> are not managed.*"
>
> So should we change this in the Wiki?
>

The natural=beach tag has no such limitations and even explicitly mentions
spatial overlap of beaches and beach ressorts:
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dbeach

**Comment by doktorpixel14** [comment]
Okay, so we clarified that, but I think, that it would be still a good idea to render this tag ;-)

**Comment by d1g** [comment]
> instead of natural=beach, if the beach area is managed

It says opposite: "Use additional objects tagged with natural=beach and name=* for entire beaches."

> So should we change this in the Wiki? Because in my opinion, it sounds like you can't use both tags in one place.

Wiki never said "instead", please read carefully.

**Comment by doktorpixel14** [comment]
> It says opposite

Yes, after dieterdreist changed it :)

**Comment by doktorpixel14** [comment]
![beach_resort](https://user-images.githubusercontent.com/23462396/32106477-13dde288-bb2c-11e7-81e7-68ad5e42448c.png)
What do you think of this symbol? The water is based on the already existing "swimming" icon.

**Comment by kocio-pl** [comment]
Looks OK for me, but the most important part is testing icons with 14 px, because even nice design can break with so small matrix.

**Comment by doktorpixel14** [comment]
I already have it as an svg but can't attach it to posts here

**Comment by kocio-pl** [comment]
You can export it as PNG (which is needed anyway, because it's how it will look on the map) and SVG can be uploaded as gist, because it's just code (XML) after all.

**Comment by doktorpixel14** [comment]
I think it also looks good in 14x14px. So how can I test it? ![beach_resort_14x14](https://user-images.githubusercontent.com/23462396/32109855-32d5598c-bb36-11e7-8dec-7979e317a521.png)

**Comment by kocio-pl** [comment]
It still looks nice and readable for me.

The best way is to make a fork with a branch, change the code to use this icon and render some real area. I guess it's easiest to install Docker-based testing environment:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

If you need some help just write.

**Comment by doktorpixel14** [comment]
Unfortunately Docker doesn't work on my computer, beacause I can't activate "Hyper-V". So it would be nice if someone else could try it out for me... (I expect that it doesn't take that much time, does it?)

**Comment by kocio-pl** [comment]
There's also traditional way, Docker is meant only to make the process easier:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md

If you make the code, I can try it too.

**Comment by kocio-pl** [comment]
If you're on Windows, you can probably try VirtualBox and install Linux inside, like Ubuntu 16.04 for example - 64-bit arch might be needed for Kosmtik.

**Comment by Tomasz-W** [comment]
@doktorpixel14 Can you upload your SVG file to Gist?

https://gist.github.com/

**Comment by doktorpixel14** [comment]
Yes, you can find it here: https://gist.github.com/doktorpixel14/fe72d5aa4d070385b6ba3f993bec0ca3

**Comment by doktorpixel14** [comment]
I did  some testing now with this being the result:
![beach_resort_17](https://user-images.githubusercontent.com/23462396/38088170-27b98aee-335b-11e8-9b07-463b7689eb7e.png)
Zoom level 17 ...
![beach_resort_18](https://user-images.githubusercontent.com/23462396/38088174-2a7a719e-335b-11e8-939f-f70533be0643.png)
... and 18

The problem with this two examples shown here is that they have 'natural=beach' and 'leisure=beach_resort' tagged on one way. So normally there should also be the rendering for the beach. How could I solve that?

**Comment by kocio-pl** [comment]
They should be independent, I guess. Where is this place - could you post a link?

**Comment by doktorpixel14** [comment]
https://www.openstreetmap.org/way/182023373

**Comment by doktorpixel14** [comment]
Another idea that came to my mind is to add an outline to beach resorts which are mapped as an area. It would be useful to see where the resort ends and where the next one begins or where there is a public beach again.

**Comment by kocio-pl** [comment]
Try to check in the Data inspector in Kosmtik how is it being selected. The area rendering is defined in https://github.com/gravitystorm/openstreetmap-carto/blob/master/landcover.mss.

**Comment by doktorpixel14** [comment]
I don't really get how to use the data inspector what do the colours mean. I only see different brown shades.

**Comment by kocio-pl** [comment]
You go close to the item you want to inspect (to avoid clutter) and click on the map on it, so the list of data attributes appears - that's the data as defined in project.mml. To make the selection more strict, you can turn on the view of only the data layers you want to test.

**Comment by doktorpixel14** [comment]
If I click on an item nothing happens. Do I have to select a tool or something  like that first?

**Comment by kocio-pl** [comment]
When the data inspector is on you can control it by the right side menu. I just turned it on and clicked in some less dense area, here is how it looks like:
![screenshot-2018-3-29 openstreetmap carto kosmtik](https://user-images.githubusercontent.com/5439713/38091045-a3e30c86-3364-11e8-99e2-98a2f88d3d6e.png)

**Comment by Tomasz-W** [comment]
Thanks for testing it!

> Another idea that came to my mind is to add an outline to beach resorts which are mapped as an area. It would be useful to see where the resort ends and where the next one begins or where there is a public beach again.

As I know, most of these resorts doesn't have a physical borders, so I think outline would be unnessesary and little bit confusing.

**Comment by doktorpixel14** [comment]
So is it an error if it looks like this:
![image](https://user-images.githubusercontent.com/23462396/38091895-151b5500-3367-11e8-89c5-899f750c9343.png)

**Comment by kocio-pl** [comment]
Yes, there's a problem with layers, as you can see. My Docker is out of order now and I don't know why, so I can't check the source of it, but maybe try to rebuild the kosmtik container.

**Comment by doktorpixel14** [comment]
Hmm, didn't help.

**Comment by kocio-pl** [comment]
Does anybody else with Docker could test if it builds properly? That's probably something with Mapnik, CartoCSS changes and Kosmtik npm version, so packaging and dependencies in general.

**Comment by kocio-pl** [comment]
Could you publish the code at least, so we could test it too?

**Comment by doktorpixel14** [comment]
Where should I?

**Comment by kocio-pl** [comment]
The most convenient way is to just use your fork and push the changes to a branch named like "beach_resort" and then just let us know which is it (for example https://github.com/kocio-pl/openstreetmap-carto/tree/castle ).

**Comment by doktorpixel14** [comment]
Just follow the link in my previous post. I already did that.

**Comment by kocio-pl** [comment]
Here is the fix: https://github.com/gravitystorm/openstreetmap-carto/commit/74915de812a948a22eff77edbd84fc6e1de00efe

The problem was you have added it to the `landcover` layer and it was selected for landcover instead of beach, but beach resort doesn't have any landcover defined by itself, so we get nothing to show as a background. BTW: there are also other elements added lately which also have no landcover defined, I'll try to fix it soon.

The only layer you need for selecting areas for icons is `amenity-points-poly`- the rest is `amenity-points` for nodes, `text-poly` for area labels and `text-point` for node labels, just like you did.

**Comment by kocio-pl** [comment]
I would try with z16+ - these are bigger, general areas, and that would be also on pair with similar picnic zone (tourism=picnic_site) or camping (tourism=camp_site).

**Comment by doktorpixel14** [comment]
Yes, that's probably better, because you would also see it before the resort's amenities then.

**Comment by doktorpixel14** [comment]
So here are some updated screenshots:

![beach_resort_16](https://user-images.githubusercontent.com/23462396/38098976-abb776a8-3379-11e8-9bb4-9924016f3d0b.png)
New zoom level 16 ...
 
![beach_resort_18](https://user-images.githubusercontent.com/23462396/38098983-af30328e-3379-11e8-85f9-ff6267f88c26.png)
... and updated zoom level 18, now with the 'natural=beach' being rendered too.

Would it be better to not show the name on lvl 16?

**Comment by kocio-pl** [comment]
I'm not sure, but if you have no specific needs or known pitfalls, try to follow similar cases (like mentioned camping or picnic sites) for the sake of conceptual consistency and code compactness.

**Comment by doktorpixel14** [comment]
Okay, I followed the example of the picnic sites by hiding names in zoom level 16. In addition, I made the code for the label a bit more compact.

So would you declare it ready for an pull request or is there still a step missing?

**Comment by kocio-pl** [comment]
It is more or less ready in my opinion, there are however some technical things related to a project management:
- it's always better to have a specific branch for every feature you introduce/change instead of master branch of your fork - this one is kind of special and serves as default branch
- before creating a pull request, please merge all the commits into one and name it clearly so somebody making a fork of the osm-carto could easily pick/filter/review features

**Comment by doktorpixel14** [comment]
And how do I merge the commits?

**Comment by doktorpixel14** [comment]
Is this really necessary? I don't find a way that works for me ...

**Comment by kocio-pl** [comment]
Do you have a problem with `git merge --squash`?

It's not mandatory, but it's always good to not have many changes that are not standalone and are just part of the solution. If you fail, we can go on with what you have for now.

**Comment by doktorpixel14** [comment]
Yes. I've created a new repository with a new branch where I changed the things again. But if I'm trying to use squash I get this output:

![image](https://user-images.githubusercontent.com/23462396/38105065-4b00260e-338b-11e8-8434-918927dcc53d.png)

**Comment by kocio-pl** [comment]
So OK, I will squash them later and try to do it on my own to learn. Or maybe somebody with better git knowledge can help you?

**Comment by doktorpixel14** [comment]
Ah, I found a simple way to merge the commits via the web interface by myself.
