### ISSUE TITLE
Rethinking shops rendering

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2444]
I think we should rethink shops rendering, because it seems [we're not done with this topic](https://github.com/gravitystorm/openstreetmap-carto/pull/2415#issuecomment-260951165). It's a tough matter, but let's look for a solid, long time solution instead of "fixing" it.

Different people might have different problems with it, like:
- too many shops at all (?)
- too many shops at some zoom level (too early)
- too many shops at some places
- too many icons
- too few icons
- catch-alls
- no tools for filtering shops
- maintainability of the list
- error checking (typos)
- amount of code needed
- shop definition (how is it different from amenity) 

...and so on. 

To avoid repeating the issues we already know and going off topic, I'd like to concentrate only on what is the most important annoyance for you personally and how far can we go with a solution to be still acceptable. Please, be precise. I see it as the only way to find a common ground instead of trying to get "as-much-as-it's-possible".

For me shops are one of the most important things on micromapping level in a big city (my main activity in OSM) - the buildings and streets being just a background there and only some amenities are that popular. If we could filter them somehow and show some of them later or make them less visible before z-max, that would be acceptable for me. The only thing I don't accept is the unmaintainable, hardcoded list not related to the rest of the project.

**Comment by mboeringa** [comment]
> To avoid repeating the issues we already know and going off topic, **I'd like to concentrate only on what is the most important annoyance for you personally** and how far can we go with a solution to be still acceptable. Please, be precise. I see it as the only way to find a common ground instead of trying to get "as-much-as-it's-possible".

@kocio-pl , I still think this topic has a high risk of de-railing at the first turn in the track with this particular request...

While I agree the current shop rendering is unsatisfactory, I also think it is unsolvable through any of the current approaches to pre-rendering as part of the style.

Personally, and I said this before in other issue threads, I only see a real solution in a dynamic, Overpass based, rendering of shops. This will allow fancy stuff like personalized filtering of desired shop values, something completely impossible and unthinkable now on the main website.

Technically, this is implementable in a website, as witness-able through e.g. Marc Zoutendijk's "OpenPOIMap" map (http://openpoimap.org/).

However, a "simple" website like OpenPOIMap is not the same as the Rails port that runs the main OpenStreetMap website, API and all the editing infrastructure. That is a different beast AFAIU.

However, as far as I understood it, the Rails port that runs the map OpenStreetMap website, and all the underlying infrastructure, needs real work to allow better customization. If I am right, this is one of those things that in fact Andy @gravitystorm and some of the other maintainers are working on right now: to update the main website infrastructure to allow better customization and thus make it more future proof.

E.g. see Andy's blog:
https://blog.gravitystorm.co.uk/
and this issue Andy opened:
https://github.com/gravitystorm/openstreetmap-website/issues/2

**Comment by pnorman** [comment]
Too many shop icons - both in the number we have in the style and the number that end up on the map.

**Comment by Klaus-Tockloth** [comment]
Start rendering the shops with small coloured dots and than continue, if there is enough space, with icons.

**Comment by math1985** [comment]
I'm not convinced rendering for a place like [this](http://bl.ocks.org/math1985/raw/7d2b0538a8b64b9d31e2/#17.00/49.58138/6.13338) (stripmall in the middle) really improved.

Places like [this](http://www.openstreetmap.org/#map=17/52.47961/-1.89705) have really become unreadable.

On the other hand, I like the rendering in small villages like [this](http://www.openstreetmap.org/#map=17/49.80364/18.60422). Although even here one could wonder if the flower kiosks don't distract from the more important features like supermarkets.

The main problem I think is that the current rendering causes a visual overload that makes it hard to see the most important amenities/shops as a glance. Try for example finding a supermarket in the Birmingham example.

> Start rendering the shops with small coloured dots and than continue, if there is enough space, with icons.

I like this idea as well. Sort of like how we render fountains or trees. Should we do this for all shops, or exclude shops people actually might search for, such as shops?

An even more radical idea is to render shops only with a name, without an icon.

I would be interested in seeing example renderings of both (and possibly other) ideas.

**Comment by gravitystorm** [comment]
> what is the most important annoyance for you personally

Catch-alls.

> the unmaintainable, hardcoded list

I'm interested to hear why this was unmaintainable, since we [had a script](https://github.com/gravitystorm/openstreetmap-carto/blob/c17cc64cbf37b96710439b1ca6c64ca73e514883/scripts/shop_values.rb) to generate the list.

**Comment by d1g** [comment]
@gravitystorm, issue wasn't only technical. It was _just slow_ for the mappers perspective. 

With manually updated white-list you have to wait up to months until your newly created shop=* will be displayed.

With "catch all and display as dot" approach mappers would get a dot within 5 minutes without contacting anyone - especially if they don't know this Github list or English.

well if we count all requests to add new shops (say, 2347 2350 2386) it means that script should be run frequently without human intervention or issues (trust any new shop=* value except for no/disused and previously blacklisted as display them as dot)

**Comment by d1g** [comment]
> shop definition (how is it different from amenity)

shop=* is a POI there you can buy goods. Good is a thing you can contain in your pocket/car.
amenity=* is a terribly ambiguous English-only word.

infrastructure=* or public_infrastructure=* should be used 10 years ago. You don't need to translate "infrastructure" in other languages: https://www.wikidata.org/wiki/Q121359

https://en.wikipedia.org/wiki/Amenity is not translated in other languages.

**Comment by mboeringa** [comment]
> amenity=* is a terribly ambiguous English-only word. It is still not defined at OSM wiki.
>...
>https://en.wikipedia.org/wiki/Amenity is not translated in other languages.

That is not entirely true. Probably a lot of languages have a word that describes something similar. The closest equivalent that I can come up with for Dutch, my native language, is **"Voorziening"**, which is equally vague and ambiguous in Dutch as in English, but equally points to stuff that: 

_"In real estate and lodging, an amenity is something considered to benefit a property and thereby increase its value."_

and can mean anything from having a nearby railway station to something as mondain as a pub around the corner, or a social facility or clinic in your neighbourhood, to something as small as a postbox to drop off your mail.

In Dutch, the word "Voorziening" even has a number of different meanings besides "amenity" in English. And yes, the word "Voorziening" has an equally poor Dutch Wikipedia page, only listing the different meanings, where "voorziening (geografie)" is the one closest to "amenity" in English:

https://nl.wikipedia.org/wiki/Voorziening

**Comment by d1g** [comment]
> "In real estate and lodging, an amenity is something considered to benefit a property and thereby increase its value."

There may be word in some languages. Point is that all of them are vague, if we pick vague definitions we will have (potentially endless) discussions "this object is A" or "this object is not A". 

I think there no specific word for given definition in Russian. The closest equivalent is "_объектов недвижимого имущества_" literal: "objects of the real estate"

See "[_Территориальные организации по государственной регистрации_ обладают правом осуществления регистрационных действий в отношении нижеперечисленных _объектов недвижимого имущества_: • земельных участков; • капитальных строений (зданий, сооружений); • незавершенных законсервированных капитальных строений; • изолированных помещений, в том числе жилых; • машино-мест.](https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%B4%D0%B2%D0%B8%D0%B6%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C)"

> and can mean anything from having a nearby **railway station** to something as mondain as a **pub** around the corner, or a social facility or **clinic** in your neighbourhood, to something as small as a **postbox** to drop off your mail.

https://en.wikipedia.org/wiki/Good_(economics) - please note that this page translated right now in 59 languages

**Comment by pnorman** [comment]
> > the unmaintainable, hardcoded list

> I'm interested to hear why this was unmaintainable, since we [had a script](https://github.com/gravitystorm/openstreetmap-carto/blob/c17cc64cbf37b96710439b1ca6c64ca73e514883/scripts/shop_values.rb) to generate the list.

The biggest data point is how we were failing to maintain it. The script was a good idea, but **this** script wasn't working out in practice.

* The script contained a list of values with more than MIN_COUNT uses, but we wanted shop values that were not otherwise rendered
** If we added the shop values rendered to the script excluded list, then when adding a shop you'd need to add it to the MSS, SQL, script, and then rerun the script to update the second part of the SQL
* We didn't have a clear workflow for using the output of the script. It gives us a list, then we do what with it?

Even if we had a script and documentation which resolved those, I'd still have maintainability concerns.

**Comment by nebulon42** [comment]
So there would have been clearly the need on our side to improve the workflow before removing it. Or now re-introducing a better workflow for this. Maybe also more general. I have a similar opinion as @gravitystorm on catch-alls. One goal for openstreetmap-carto is (should be) to help preventing tag value inflation. Without whitelisting we are failing on this like with buildings and now with shops.

@d1g If there is a newly created shop value, why should it show up immediately on the map? If there are requests to render a new shop value, who says that they should be rendered in any case? This would lead to a un-curated map, which would be unusable.

Apart from that I also like the idea of @Klaus-Tockloth.

**Comment by kocio-pl** [comment]
What the Paul just wrote, plus the script had some exceptions - that mean we were trying to do another level of data validation on our own, without clear rules. 100 uses limit was arbitrary but clear, but how do we know what is a typo - "bag" or "bags"? And what about wiki status - should we use it to decide? That should be done on data definition level, it doesn't belong to rendering.

**Comment by d1g** [comment]
> a newly created shop value, why should it show up immediately on the map? 

@nebulon42, because it exists IRL and won't be contested by other shops (in very same place).

`shop=fireworks` (only 99 items is osm!) still not rendered, there no single reason not to display single coloured dot for them (please check global overpass).

Threshold should be `10` or `30` or `50` but not `100`.

> data definition level

@kocio-pl, any shop=* value (except shop=no and shop=disused) is a shop (can be rendered using unspecific shop style). It was defined at wiki already. Custom and additional rendering are possible.

**Comment by nebulon42** [comment]
Yes, you are right. But that only works if the data definition level would be mandatory. But it isn't. Generally, everybody is free to add own tags. This is both a strength and weakness of OSM. So there have to be checks and balances and osm-carto is part of these checks and balances. This does not mean there shouldn't be guidelines and discussions.

@d1g I disagree here. What about typos? And about any shop value. Is `shop=brweoirjf` a shop? How do you know?

**Comment by d1g** [comment]
@nebulon42, I see, but please don't overstate. At least 3 `shop=fireworks` were mine; they sell only fireworks IRL, they weren't typos.

> How do you know?

I would ask an individual mapper what he meant in each object.

Could you provide more realistic example from database that would break at least `10` threshold?

http://taginfo.openstreetmap.org/compare/shop=beds/shop=bed
http://taginfo.openstreetmap.org/compare/shop=clothes/shop=одежды

**Comment by kocio-pl** [comment]
> @kocio-pl, any shop=* value (except shop=no and shop=disused) is a shop (can be rendered using unspecific shop style). It was defined at wiki already. Custom and additional rendering are possible.

I agree with you, that's why I made all shops being at least marked as a shop dot. 

> What about typos? And about any shop value. Is shop=brweoirjf a shop? How do you know?

`shop=brweoirjf` is still a shop for sure and we don't claim we know what type is it, which is fair and accurate rendering of the data. No _Oxford English Dictionary_ would be enough to validate - we need to know not only if it's an British English word, but also what is valid inside the project, but that means it's better to have such vocabulary closer to the data as a shared OSM resource (hence the question about Wiki status).

> Apart from that I also like the idea of @Klaus-Tockloth.

Sounds acceptable for me in general.

> Personally, and I said this before in other issue threads, I only see a real solution in a dynamic, Overpass based, rendering of shops.

Restaurants/fast foods are sometimes also crowded, so POIs in general. With vector tiles that would be great and I hope one day we will have it.

**Comment by SomeoneElseOSM** [comment]
"the most important annoyance for you personally"

1. The first thing is that there are a large number of different shop icons.  Personally I'd find it easier to understand if related shops had the same or perhaps similar icons (maybe "sports" and "outdoor"?  Or hairdressers and beauty salons?).

2. The second is that a lot of the shop icons make use of a lot of filled colour, so at z17 (se @math1985's Birmingham example) a significant amount of the map is purple.

3. Finally shops are currently overrepresented compared to some other features, such as offices, though obviously there's a separate tagging discussion around those, and once they appear on the map that problem will go away.

![screens_20161117b001s](https://cloud.githubusercontent.com/assets/5311740/20412947/cabab888-ad21-11e6-8870-10e83d7f3906.png) ![screens_20161117b002s](https://cloud.githubusercontent.com/assets/5311740/20412949/ce3b48ec-ad21-11e6-918b-f7d3785597ec.png)

Here's a quick and dirty example of (2) and (3) above - z19, scaled down to fit side by side - don't worry about the legibility, just the proportions of colour.

The icon for "electronics" deliberately makes use of relatively little colour. Offices are shown, but with a minimal black dot.  I haven't changed the "clothes" icon, and probably should, to an outline instead of filled colour.  See https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/tree/master/symbols for those symbols - most definitely aren't as nice looking as the standard osm-carto ones so I don't think they'll be replacing any of those any time soon, but some of the ideas (e.g. line drawn rather than filled colour) might work.

Finally it must be said that I don't really see any of these as "annoyances" with the standard style - it's just what it does.  I definitely think @Klaus-Tockloth's idea is worth pursuing though.

**Comment by d1g** [comment]
> I'm not convinced rendering for a place like this (stripmall in the middle) really improved.

@math1985, I wasn't able to tell that "AVA" was a shop without purple icon. Only JBC with clothing icon gave me hint about possible group of shops, actually you can guess this too (based on parking)

... but "bétons feidt" is much harder question for a non-local.

To me, it's better to have tiny styled dot ("a shop"), than unstyled text (no information about POI class).

**Comment by kocio-pl** [comment]
Thanks all for balanced and precise comments. I think we can start to take this issue bit further. 

It seems that a common thread is to render icons later and start with just the dots. How should it be done in practice then? Which shops should stay as they are (supermarket? convenience?) and which level should we push the icons to (z18+?)?

**Comment by math1985** [comment]
> It seems that a common thread is to render icons later and start with just the dots. How should it be done in practice then? Which shops should stay as they are (supermarket? convenience?) and which level should we push the icons to (z18+?)?

I don't have clear answers to these questions either, perhaps somebody (maybe @kocio-pl) could make a start with an example rendering (which does not need to be perfect) and we could go from there?

**Comment by math1985** [comment]
> It seems that a common thread is to render icons later and start with just the dots. How should it be done in practice then? Which shops should stay as they are (supermarket? convenience?) and which level should we push the icons to (z18+?)?

I don't have clear answers to these questions either, perhaps somebody (maybe @kocio-pl) could make a start with an example rendering (which does not need to be perfect) and we could go from there?

I think at this stage, dropping the shops icons altogether (rendering them only by name or dot) should still be an option to consider too.

**Comment by kocio-pl** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2276, https://github.com/gravitystorm/openstreetmap-carto/issues/2011 and https://github.com/gravitystorm/openstreetmap-carto/issues/2417.

**Comment by kocio-pl** [comment]
I guess at this point shops issue is resolved to some extent and there was no other proposition that was agreed by most of the people here, so I'm closing it now. If there are some other ideas that we could use, it can be reopen.
