### ISSUE TITLE
yaml2mml not compatible with python 3.5

### ISSUE THREAD

**Issue by jojo4u** [gravitystorm/openstreetmap-carto#2447]
On my Arch Linux with python 3.5 yaml2mml.py fails. Probably because of #2225.

```
Traceback (most recent call last):
  File "./yaml2mml.py", line 27, in <module>
    json.dump(yaml, mml_file, indent=2, separators=(',', ': '))
  File "/usr/lib/python3.5/json/__init__.py", line 179, in dump
    fp.write(chunk)
TypeError: a bytes-like object is required, not 'str'
```

Steps to reproduce:
\> python --version
Python 3.5.2
\> pacman -Qi python-yaml
Version         : 3.12-1
\> git clone https://github.com/gravitystorm/openstreetmap-carto.git
\> ./scripts/yaml2mml.py
[Error above]

Python 2 works fine
\> python2 --version
Python 2.7.12
\> pacman -Qi python2-yaml
Version         : 3.12-1
\> python2 ./scripts/yaml2mml.py
[No error]

**Comment by pnorman** [comment]
Also has the same error on Debian with 3.5.

We could make it a Python 2 script, but I'm open to suggestions which make it work on both while keeping output the same on Linux and Windows.

**Comment by StyXman** [comment]
The problem mostly arises from the fact that the file is opened as binary. Is there a reason for this? In theory a text file should be enough, as json should be text. Removing the 'b' from line 26 makes it work for both py2 and py3.

**Comment by HolgerJeromin** [comment]
The reason for binary was #2153

**Comment by pnorman** [comment]
Yes, we need 'b' or it doesn't work on py2, giving different output depending on newline settings.

**Comment by jojo4u** [comment]
I understand we want only \n on every platform as newline? I found no compatible way with JSON.dump() but using JSON.dumps() and encode to byte array seem to do the trick:

```
json_bytes = (json.dumps(yaml, indent=2, separators=(',', ': '))).encode(encoding = "ascii")
mml_file.write(json_bytes)

```
With python2 both methods yield files with same sha256sum. Tested only on Linux, I have no Windows system at hand.

The python3 output is different each time, the properties seem to have random sorting. The python2 output is stable (same sha256sum). 

Should I prepare a merge request?

**Comment by math1985** [comment]
> The python3 output has different sha256sum after every execution, the properties seem to have random sorting. 

That would be not so practical when working with git, maybe we can explicitly add a sort?

**Comment by jojo4u** [comment]
Yes, adding sort_keys=True does produce the same and stable output for python 2/3.

`json_bytes = (json.dumps(yaml, sort_keys=True, indent=2, separators=(',', ': '))).encode(encoding="ascii")`

**Comment by pnorman** [comment]
> Yes, adding sort_keys=True does produce the same and stable output for python 2/3.

Is the Windows output the same?

**Comment by kocio-pl** [comment]
Just for the record: Microsoft publishes [virtual machines](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) for testing Internet Explorer/Edge in different versions, but they are in fact just plain generic Windows machines, that you could use for anything. The only drawback is that the license is expiring every 90 days, so one has to roll back to the snapshot once in a while. It's even easy to remember the basic URL: _modern.ie_.

**Comment by StyXman** [comment]
The real answer to the original problem would have been to use [`core.autocrlf`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace).

**Comment by jojo4u** [comment]
> The real answer to the original problem would have been to use core.autocrlf.

This would probably not work for project.mml because it is marked as binary file (34ef13692e44345e25c610bdd7e21e91b1aa929b). You lose autocrlf but gain: _"nor will it try to compute or print a diff for changes in this file when you run git show or git diff on your project."_

**Comment by pnorman** [comment]
> This would probably not work for project.mml because it is marked as binary file (34ef136). You lose autocrlf but gain: "nor will it try to compute or print a diff for changes in this file when you run git show or git diff on your project."

We can change this if needed

**Comment by jojo4u** [comment]
#2459 has been refined and now been tested with Linux and Windows. Python 2&3 on Linux and Windows are producing same output (with LF newline). Only exception is redirecting output of --check parameter to file, but this is not what this switch is vor.

**Comment by kocio-pl** [comment]
Made irrelevant by https://github.com/gravitystorm/openstreetmap-carto/pull/2473.
