### ISSUE TITLE
Rendering of amenity=clinic as area

### ISSUE THREAD

**Issue by Fringillus** [gravitystorm/openstreetmap-carto#2449]
I wonder if it's suitable to maybe render amenity=clinic in the maps. Maybe in a similar way to amenity=hospital.

Example: [This](http://www.openstreetmap.org/way/446541166) a major clinic but not suitable for hospital tagging leaves an odd clear space.

**Comment by polarbearing** [comment]
Could be discussed in context of other _societal amenities_ as defined in #1624, such as social_facility and community_centre.

**Comment by d1g** [comment]
For A=clinic, I would prefer to display [HC 2.0](http://wiki.openstreetmap.org/wiki/Proposed_features/Healthcare_2.0) tagged objects (`health_facility:type=*`), because it is [supported](https://github.com/osmandapp/OsmAnd-resources/search?utf8=%E2%9C%93&q=health_facility%3Atype) in OsmAnd already.

**Comment by Fringillus** [comment]
So this is nothing that can be implemented?

**Comment by kocio-pl** [comment]
It could be, but no one wrote a code for it yet.
