### ISSUE TITLE
Icon label cropped

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#2461]
Perhaps related to my other issue #1135 
"Zweirad-Heier" is rendered as "weirad-Heier"
http://www.openstreetmap.org/node/3996158713#map=18/51.88032/8.49274
The data is about 10 Month old, so i am pretty sure this is no "outdated tile" problem.
![image](https://cloud.githubusercontent.com/assets/2410353/20576682/2cd0354c-b1bf-11e6-969d-109982be4d44.png)

This is really a tile (probably a metatile) border. I moved the [left tile](http://a.tile.openstreetmap.org/18/137255/86731.png) div, added a border to the [right tile](http://b.tile.openstreetmap.org/18/137256/86731.png) and added a green background:
![image](https://cloud.githubusercontent.com/assets/2410353/20576921/36d884c6-b1c0-11e6-891d-34767cd7c5b8.png)

Perhaps the overlapping margin of the metatiles is not large enough to prevent labels on both sides or the overlapping is not working at all.

**Comment by pnorman** [comment]
> Perhaps the overlapping margin of the metatiles is not large enough

It's large enough this won't be a direct cause.

**Comment by HolgerJeromin** [comment]
This example is not visible anymore. Should we close this issue?

**Comment by nebulon42** [comment]
Let's close and re-open if happening again.
