### ISSUE TITLE
roads link oddness

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2469]
The roads SQL turns `highway=motorway_link` into feature=motorway link=yes, including on the roads-text-name, but the MSS checks for motorway_link

**Comment by james2432** [comment]
has this been fixed already? as the only one that checks motorway_link is .directions::directions is roads.mss which seems to be for text(which motorway_links don't usually have). Others already check [link=yes] or [link=no] else where

**Comment by matthijsmelissen** [comment]
I cannot reproduce this.
