### ISSUE TITLE
Too few oneway arrows

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#2476]
currently there are quite few oneway arrows even where there seems to be lots of space, e.g. here in zoom16: http://www.openstreetmap.org/#map=16/41.8631/12.4910
a lot of oneway streets show neither name nor oneway arrows in this area.

**Comment by pnorman** [comment]
The bus stops are rendered before the oneway arrows. 

@dieterdreist, how does it look if you turn off the `amenity-points-poly` layer? Can you provide a screenshot if there's a change to the oneway arrow density.

**Comment by dieterdreist** [comment]
That's a good question, unfortunately I don't have a local rendering stack
at the moment and cannot tell. But I've noticed that this is a frequent
problem at the moment, and I would almost bet it was better some time ago
(regression). IMHO these oneway arrows could even slightly overlap (under)
the amenity points icons (almost never will there be correct amenity icons
in the middle of the street anyway).

**Comment by dieterdreist** [comment]
I have other instances where oneway arrows aren't shown, but there doesn't seem to be any conflicting symbols nearby, e.g. http://www.openstreetmap.org/way/476920348 doesn't show a oneway arrow at any zoom level.

**Comment by matthijsmelissen** [comment]
This is duplicate with #595.
