### ISSUE TITLE
Rendering of name=* in highway=construction

### ISSUE THREAD

**Issue by s3b4s5** [gravitystorm/openstreetmap-carto#2477]
Hi. For some time the name of some streets under construction has been rendered from certain levels of zoom.

I leave a very clear example of something that I think is not correct. The zoom level is 14. It is `highway=construction` + `construction=residential`. As you can see, these streets under construction highlight their name on the map too much more than even the roads that are primarias/secondary.

I think that should not happen with the names. Anyone knows that a primary road is much more important than a residential one which is closed to access due to construction work.
http://www.openstreetmap.org/#map=14/-27.4061/-55.9754
![renderingconstr](https://cloud.githubusercontent.com/assets/14035422/20726390/1a9cc432-b654-11e6-8d17-a248bafb8446.PNG)

PS: I'm not against showing the names, but set another priority when showing them. A residential road under construction is not so important to the map; But a motorway under construction is important.

**Comment by nebulon42** [comment]
We currently have no means to distinguish `construction=motorway` from `construction=residential` as the key is not in the rendering database. So we probably should move name rendering of roads under construction generally to a higher zoom level.
