### ISSUE TITLE
Highway refs don't properly fit the shield

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#2478]
Using this example (from https://www.openstreetmap.org/#map=18/-21.81209/-48.18708):

![](https://cloud.githubusercontent.com/assets/982338/20751828/344be0ac-b6e5-11e6-99b8-abaad30f760e.png)

See how `SP-310` and `BR-364` are touching the upper and lower shield borders.
Actually, if we zoom, we can see that `BR-364` is surpassing the box:

![](https://cloud.githubusercontent.com/assets/982338/20752096/98cddfde-b6e6-11e6-9c87-0a0480cb3269.png)

Isn't it possible to add some pixels on top and on bottom of the shield, to avoid this?
Or maybe reduce the vertical spacing between the values.

**Comment by nebulon42** [comment]
I suspect that this a consequence of the recent font change.

**Comment by jojo4u** [comment]
Yes, it's Noto font metrics. I think the spacing should be reduced. The question is: Are tall glyphs to be expected on road refs? Or should only "X" and "g" taken into account? If the latter, the line height can be reduced up to 30% (as measured with the actual font metrics of Noto UI). Related to #2470.

**Comment by jojo4u** [comment]
Some examples with tall glyphs:
https://www.openstreetmap.org/#map=18/49.50693/10.88807
https://www.openstreetmap.org/#map=19/24.43478/120.69034

**Comment by pnorman** [comment]
> Yes, it's Noto font metrics. I think the spacing should be reduced.

We need to recompute all the shield sizes, even if we reduce the spacing.

**Comment by jojo4u** [comment]
generate_shields.py has not comment how config['base'] was derived.

**Comment by nebulon42** [comment]
That are values I came up with by trying.
