### ISSUE TITLE
Tobacco icon mangled with theater icon

### ISSUE THREAD

**Issue by meased** [gravitystorm/openstreetmap-carto#2479]
The shop=tobacco icon:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/tobacco.svg

Now has both the cigarette icon and the theater icon overlayed in one SVG file.

![tabacco](https://cloud.githubusercontent.com/assets/14190496/20772508/94bebf64-b702-11e6-92a3-6d8aeabcbde6.png)

**Comment by kocio-pl** [comment]
Could you post the link to this location so that we could test it?

**Comment by meased** [comment]
It's here:

http://www.openstreetmap.org/?mlat=45.62165&mlon=-122.55384#map=19/45.62165/-122.55384

**Comment by nebulon42** [comment]
It's a copy and paste mistake of me. The theater icon is really in the tobacco icon now. Should be easily fixed.

**Comment by kocio-pl** [comment]
@nebulon42 Do you plan to do that? I would like to merge it soon and issue v2.45.1 (probably also with [SVG lint](https://github.com/gravitystorm/openstreetmap-carto/pull/2480)).

**Comment by math1985** [comment]
Sorry, missed that.

We should try to avoid bug releases. Every release means high latency on the server for a day or two (many old tiles being served), which is quite troublesome for mappers. The fewer releases, the better from this perspective.

Not saying whether or not we should release a .1 version for this particular bug.

**Comment by kocio-pl** [comment]
I'm aware of a burden it causes. I don't like big code changes and prefer smaller steps. I made a general preview of this change, but unfortunately there was no tobacco shop on this area.

**Comment by HolgerJeromin** [comment]
Svg lint found no XML problems. So has only benefits for future PRs to find early problems. 
It has no real value to include it in a release. 
Despite this tobacco fix produces an invalid svg :)
