### ISSUE TITLE
Merge of historic=monuments and historic=memorial icons ?

### ISSUE THREAD

**Issue by Cybereric** [gravitystorm/openstreetmap-carto#2481]
Hello,
On some areas (at zoom 17) I've seen that memorials (historic=memorial) and monuments (historic=monument) have the same icon (from monument).
I hope it's a bug.
If not please don't merge  these categories with only one icon because these two objects are quite different. 
![icones](https://cloud.githubusercontent.com/assets/7645549/20799566/d746486c-b7e2-11e6-910b-82c199c594be.png)
See https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmonument
and https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmemorial
Thanks.

**Comment by HolgerJeromin** [comment]
Probably another copy and paste error of #2451
Memorial had a different icon before this PR. See the other branch which is not updated:
https://github.com/gravitystorm/openstreetmap-carto/blob/lua/symbols/tourist_memorial.16.svg

**Comment by nebulon42** [comment]
> Probably another copy and paste error of #2451.

Yes, sorry for that.

**Comment by kocio-pl** [comment]
Fixed in v2.45.1.
