### ISSUE TITLE
Render addr:unit on building entrances

### ISSUE THREAD

**Issue by tpikonen** [gravitystorm/openstreetmap-carto#2488]
The recommended way of tagging staircases in apartment buildings is to use addr:unit (see: http://wiki.openstreetmap.org/wiki/Key:addr#Detailed_subkeys). This tag can be conveniently added to the entrance=staircase nodes on the building perimeter. Currently addr:unit is not rendered in the default OSM layer.

The Finnish OSM community currently has some momentum on improving addresses, but since addr:unit is not rendered, people have resorted to the incorrect method of using addr:housenumber on entrances. 

The screenshot below, taken at http://www.openstreetmap.org/#map=18/60.15612/24.74071 shows two buildings of the same apartment complex, both with addr:housenumber=5. The building above is tagged correctly with addr:unit=C and D on main staircase entrances. The building below has entrances incorrectly tagged with addr:housenumber=5A (and 5B and 5C). By panning around in this area, one can see many examples of this incorrect tagging, made probably because it's the only way to make entrance addresses visible on the default map. 

It would be really nice to have addr:unit tags on entrances rendered on higher zoom levels, perhaps one zoom level higher than when addr:housenumber becomes visible and with a slightly smaller font than addr:housenumber. 

![entranceunit](https://cloud.githubusercontent.com/assets/3215/20867067/a59ac694-ba44-11e6-92b7-62368535dc0e.png)

**Comment by nebulon42** [comment]
I have not found `addr:unit` tags on the mentioned building. But anyway, yes I agree that it would be worthwhile to render `addr:unit`. I personally would require also the presence of `addr:housenumber` in addition to `addr:unit`. Else how do you know to which address the unit does belong to? That said I would extend the current rendering of `addr:housenumber` and `addr:housename` to also include `addr:unit`when present.

cc @sommerluk

**Comment by tpikonen** [comment]
The addr:unit tags in the top building are in the entrance nodes.

Rendering also addr:housenumber in the case of entrance=staircase nodes would lead to unnecessary clutter IMO, like in the lower building in the image, where the unit letter is added to addr:housenumber tag in the entrance to make it visible. If a building has an addr:unit tag, it would make sense to render it. Taginfo says that addr:unit is used on 180k nodes and only 20k ways, so there are not that many buildings with addr:unit tags. Not surprising, since units are usually staircases and other building-internal features.

The top building in the image below shows how to render addr:unit in entrances with (IMO) least clutter and most useful information.
![entrancefix](https://cloud.githubusercontent.com/assets/3215/20900866/967fad88-bb38-11e6-8a91-57ba8ea9f175.png)

**Comment by tpikonen** [comment]
addr:unit is now rendered both on buildings and entrance nodes (and probably also everything else for that matter). The rendering has some problems as it is IMO, but I'll open another issue for those and close this one.
