### ISSUE TITLE
highway=bus_guideway incorrectly renders on top of bridges

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#2489]
Where the Cambridge Guided Busway passes under roads and the road is clearly marked as a bridge the busway is still being rendered over the road. Here for example it's shown going over the A14 rather than under the A14 bridges (note that the guided bus cycle way next to it does get rendered correctly)..

![screenshot - 041216 - 16 04 16](https://cloud.githubusercontent.com/assets/8981901/20867416/567ebbe6-ba3b-11e6-9dd8-98bd425eb707.png)

This seems to be true for all the bridges involved so I suspect it's the CSS rather than the markup.

**Comment by nebulon42** [comment]
Location at https://www.openstreetmap.org/#map=18/52.23627/0.12744.

**Comment by jojo4u** [comment]
Bus guideways are currently defined very simple, without bridge handling. Special handling of tunnels was rejected in #2191. This would add further complexity to roads SQL query.

**Comment by imagico** [comment]
Closing in favor of #3581, which covers the broader underlying issue.
