### ISSUE TITLE
Schema documentation references

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2490]
README.md states "You need a PostGIS database populated with OpenStreetMap data in the standard osm2pgsql database", which is no longer true.

Also, as follow-up to #2486, the CREATE EXTENSION code should be on its own line.

**Comment by pnorman** [comment]
Obviously not a blocker, but should be an easy fix.

**Comment by kocio-pl** [comment]
Both are addressed now, after merging these PRs this issue should be closed.
