### ISSUE TITLE
render disused:railway=station

### ISSUE THREAD

**Issue by Geogast** [gravitystorm/openstreetmap-carto#2495]
`railway=station` is used for stations that are in use in this moment, for passenger or cargo transport. 
In South America (and elsewhere), there are many, many train station that do not fit this definition (no passenger service and no cargo handled). But they are still important orientation points, attracting visitors and commerce. Everybody in town knows where the train station is although there might stop no passenger trains.
Therefore, IMHO `disused:railway=station` should be rendered; of course, differently than active `railway=station`, perhaps in grey.
This would motivate using correct tagging (i.e. add `disused:` to a disused station).

**Comment by kocio-pl** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2030.

**Comment by jojo4u** [comment]
@Geogast please provide some examples which you deem representative.
I would be interested what infrastructure is still present. Are there switches, platforms, station buildings? building=train_station rendering was improved in #2443.

**Comment by Geogast** [comment]
Here some examples of disused train stations that are still there. 
http://osm.org/go/MnX486sug--, http://osm.org/go/NrOOBlUBF--, http://osm.org/go/MlfZajKZE-, http://osm.org/go/M~xSbKsKV, http://osm.org/go/M~xhExc6N--
Often, mapping is quite poor; perhaps because personal access is forbidden und grass grew over the rails.
The fact that these stations are disused does not mean that they were un-built. Very often, they were left as they were; and some cargo trains might use the rails.
If you see them, you may think of them as very badly maintained, but complete train stations – "just" without passenger traffic.

**Comment by jojo4u** [comment]
While it may be tempting to just use disused:railway=station but there are [better possibilities as documented for openrailwaymap](http://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging#Marshalling_Yard.2FClassification_Yard.2FFreight_Yard.2FFreight_Station). IMHO the possibilities of mapping what's still there should be explored before disused:*=* is taken into consideration. 

- if freight usage is still possible and is happening from time to time: railway=yard (not rendered yet)
- If the station just used for overtaking, train crossings, changes of the locomotive and not for (un)loading of freight trains or to composite new freight trains, use railway=service_station instead (not rendered yet)
- if no usage is possible anymore landuse=railway with name= might stille be used

**Comment by dieterdreist** [comment]
sent from a phone

> On 7 Dec 2016, at 01:22, jojo4u <notifications@github.com> wrote:
> 
> if no usage is possible anymore landuse=railway with name= might stille be used


isn't this a kind of contradiction?

**Comment by Geogast** [comment]
> While it may be tempting to just use disused:railway=station
This sounds as if `disused:X=Y` was a tag that had to be avoided. I don't see why. Even the ORM wiki page you, jojo4u, quote, says:
> Disused or abandoned stations can be mapped using disused: 
The stations I am talking about are no railway yards (although they may have one near).
They/most of them are no employee stations (i.e. r=service_station)
And landuse=railway is way too generic in this case. If there is more precise tagging, why use this tag?!
We map what we see; and what you see is a disused train station.
In addition to my examples above, I have to say that perhaps 90% of train stations (and halts) outside mayor cities of South America are disused.

**Comment by jojo4u** [comment]
Sorry I gave the wrong impression. I listed some tags which may be preferable to render. If the station is a disused passenger station it should still be tagged disused:railway=station.

**Comment by matthijsmelissen** [comment]
Unfortunately I think this request is too specific for a general purpose map. I am therefore going to reject it.

**Comment by dieterdreist** [comment]
sent from a phone

> On 8. May 2018, at 02:08, Matthijs Melissen <notifications@github.com> wrote:
> 
> Unfortunately I think this request is too specific for a general purpose map.


they are often landmarks. You don’t have to be a railway freak to recognize a former train station.
