### ISSUE TITLE
Please render "amenity=arts_centre"

### ISSUE THREAD

**Issue by abdeldjalil09** [gravitystorm/openstreetmap-carto#2505]
http://taginfo.openstreetmap.org/tags/amenity=arts_centre --->13 670 uses

**Comment by HolgerJeromin** [comment]
Thanks for the suggestion 
It was also mentioned in the list of #108

**Comment by kocio-pl** [comment]
I also think we should render it, but there's a question how should this icon look like? This is not a trivial problem.

**Comment by HolgerJeromin** [comment]
I would remove the duplicate tag, because we have no other place to discuss an icon. I just wanted to link both issues

**Comment by abdeldjalil09** [comment]
@kocio-pl I suggest to render like "shop=art" but brown.

**Comment by kocio-pl** [comment]
I thought it would make more sense to use it with tourism=gallery.

**Comment by abdeldjalil09** [comment]
Please remove "duplicate" tag, this is not duplicate of another issue.

**Comment by math1985** [comment]
Fixed.

**Comment by meased** [comment]
The [theatre](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/theatre.svg) icon also seams very fitting.

**Comment by kocio-pl** [comment]
Makes sense for me, with z17+ (theatre is z16+).

**Comment by kocio-pl** [comment]
[tourism=gallery has now 2 465 uses](http://taginfo.openstreetmap.org/tags/tourism=gallery), so it passes the lower limit for rendering. I like the idea to use brown palette for it and theatre icon for amenity=arts_centre, as proposed above, this would be consistent.
