### ISSUE TITLE
Render shop=pastry like shop=confectionery

### ISSUE THREAD

**Issue by abdeldjalil09** [gravitystorm/openstreetmap-carto#2514]
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dpastry

**Comment by kocio-pl** [comment]
[Current TagInfo counter](https://taginfo.openstreetmap.org/tags/?key=shop&value=pastry) shows 1 467 uses, so it's quite close to our standard limit (2-5k).

Code wise it's dead easy task, the problem is do we think we can render it?

**Comment by abdeldjalil09** [comment]
Yes, because they're :
shop=photo_studio--> only 678 uses rendered like shop=photo
shop=perfumery --> only 1 164 uses rendered like shop=cosmetics
and shop=pastry -->1 475 uses should be rendered like shop=confectionery

**Comment by Circeus** [comment]
I don't like it. It makes it impossible to have a sensible icon for stores like Cocobun, who sell both savoury (i.e. asian-style meat-filled buns) and sweet pastries. It doesn't help that Cocobun also sells cakes, but that is a much more minor element of their product line in practice.

Personally I'd _much_ rather use the bakery icon.

**Comment by dieterdreist** [comment]
I'd use a new icon for confectionery, like
http://www.dev.bowdenweb.com/maps/a/svg/svg/shopping/confectionery.svg
and use the current confectionery icon for shop=pastry

**Comment by kocio-pl** [comment]
First I'd like to see 14px raster version of the icon. The best I was able to draw was this:
![confectionery-14-6](https://cloud.githubusercontent.com/assets/5439713/21429965/64cb276e-c861-11e6-920f-0986900be837.png)

**Comment by pnorman** [comment]
👎 to having an icon unique to this

**Comment by kocio-pl** [comment]
And what about rendering as requested originally (once we pass 2k uses)?

**Comment by pnorman** [comment]
I could see rendering it the same as something else, but would have to look at icons and usage to make sure it makes sense. I don't see something magical about 2k usage either.

**Comment by kocio-pl** [comment]
@abdeldjalil09 What do you think about rendering it like bakery (suggested by @Circeus)?

**Comment by kocio-pl** [comment]
It's 3117 uses now and I think the original suggestion was right, since current icon depicts kind of a muffin, which is a pastry.
