### ISSUE TITLE
Proposed Monitoring Station Icon

### ISSUE THREAD

**Issue by tex04** [gravitystorm/openstreetmap-carto#2516]
Hi to everyone,

I write for propose a icon to visualize the tag_made=monitoring_station on openstretmap.
How can I do?

Best Regards,

tex04

**Comment by kocio-pl** [comment]
You probably mean http://taginfo.openstreetmap.org/tags/man_made=monitoring_station :

1. Do we want this icon (usage is decent - 8k+)?
2. How should it look like (real 14px examples are preferred, but not required)?

**Comment by tex04** [comment]
I propose this

![monitoring_station](https://cloud.githubusercontent.com/assets/19594432/21343680/3313c3c2-c698-11e6-9802-2bad36603e40.png)

What do you think?

**Comment by HolgerJeromin** [comment]
With 14px this would be (scaled quick and dirty with a paint programm) 
![image](https://cloud.githubusercontent.com/assets/2410353/21343963/a3c4db78-c699-11e6-8d80-03f215ed0565.png)

**Comment by tex04** [comment]
I try another image then

**Comment by kocio-pl** [comment]
We use SVG icons, by the way. 14px PNG is just to preview them here.

**Comment by tex04** [comment]
What do you think about that?

![sensor-on-pole-icon-with-solar-panel](https://cloud.githubusercontent.com/assets/19594432/21392650/2cc11fb6-c791-11e6-93db-16a426f2a7fc.png)

**Comment by kocio-pl** [comment]
Hard to recognize for me. Maybe rather something [like this](https://terryfic3d.files.wordpress.com/2011/08/weatherstation_3874.jpg) or a windsock?

**Comment by tex04** [comment]
The Windstock icon it should be that:

![6-512](https://cloud.githubusercontent.com/assets/19594432/21392967/a48c15fe-c792-11e6-8418-0590d1230de0.png)

**Comment by dieterdreist** [comment]
sent from a phone

> On 21 Dec 2016, at 15:32, tex04 <notifications@github.com> wrote:
> 
> The Windstock icon it should be that:


I think it's too wind specific, the generic monitoring station should get something more universal

**Comment by meased** [comment]
Perhaps just a thermometer would be recognizable and get the point across. Something like this:
![therm](https://cloud.githubusercontent.com/assets/14190496/21406637/78254dac-c781-11e6-9187-1156d2506c88.png)

**Comment by pnorman** [comment]
I think this feature is too specialized and not of sufficient **general** interest for this rendering.

Also, all the icons proposed relate to weather, not the general idea of monitoring, which includes radiation, gps, traffic, water, air quality, chemical agents, etc.

**Comment by dieterdreist** [comment]
sent from a phone

> On 21 Dec 2016, at 23:39, Paul Norman <notifications@github.com> wrote:
> 
> I think this feature is too specialized and not of sufficient general interest for this rendering.
> 
> Also, all the icons proposed relate to weather, not the general idea of monitoring, which includes radiation, gps, traffic, water, air quality, chemical agents, etc.
> 


indeed the tag is very generic in meaning, also includes water level measurement and tide gauge: https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmonitoring_station

in recent years, air quality monitoring has been widely extended in cities, at least in the european union. IMHO there is some general interest in the location of the measurement devices.

**Comment by tex04** [comment]
What do you think about this?
![monitoring_station](https://cloud.githubusercontent.com/assets/19594432/21457981/6fe4bb42-c933-11e6-8142-78028f0603f7.png)

I think it's very generic and appropriate for all stations

**Comment by micahcochran** [comment]
Regarding the windsock icon rendering, I don't think is a good choice. 

The wiki page for man_made=monitoring_station currently does not explicitly state that this is for tagging a windsock.

There is already [aeroway](http://wiki.openstreetmap.org/wiki/Key:aeroway)=windsock tag and [seamark:landmark:category](https://wiki.openstreetmap.org/wiki/Key:seamark:landmark:category)=windsock that seem to be the current best way to tag these features.

**Comment by imagico** [comment]
Closing this since the general feeling among the maintainers is that a general rendering of all monitoring stations is not desirable for this style.

If there is a specific type of monitoring station that is widely mapped and of general interest discussing this specifically might be useful and warrant a separate issue.

**Comment by Adamant36** [comment]
What about rendering them as a dot so at least the name renders? Currently about 50% of them have the name tag and it would be useful for at weather stations (and I'm sure other types). 

Outside of that, there's 5143 instances of monitoring:weather and 2940 of monitoring:water_level. So, those might be worth rendering now. It would be great if there was specific rendering for monitoring:water_level. Since there's a ton of them around where I live. Although, I'd be fine with just a dot if an adequate icon can't be found.

**Comment by jidanni** [comment]
Yes, from a city persons' viewpoint a
https://en.wikipedia.org/wiki/Weather_station
has no entertainment value or whatever, but from a
country person's viewpoint, they might be the most important landmark for miles.
