### ISSUE TITLE
Label scaling incorrect with scale factor

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2524]
This is from Germany with scale-factor 6, the resulting image scaled by 1/6 to get a result which should look the same except for antialiasing, quality of rendering, and PNG patterns

![image](https://cloud.githubusercontent.com/assets/1190866/21406427/7185471e-c780-11e6-84b4-aa32776e2994.png)

On osm.org the label doesn't even get placed at that scale
![image](https://cloud.githubusercontent.com/assets/1190866/21406451/965dc700-c780-11e6-8a25-bc45d266e850.png)

At a 4x higher scale, this is what it looks like

![image](https://cloud.githubusercontent.com/assets/1190866/21406473/b63f3860-c780-11e6-9115-6046c47a9f86.png)

cc @woodpeck

**Comment by imagico** [comment]
> This is from Germany with scale-factor 6, the resulting image scaled by 1/6 to get a result which should look the same except for antialiasing, quality of rendering, and PNG patterns

Assuming that by _scale-factor 6_ you mean rendering at six times the normal resolution (scale factor to me usually means [something different](https://en.wikipedia.org/wiki/Mercator_projection#Scale_factor)) that seems not quite correct since we make a lot of use of `way_pixels` for labeling and this i would assume varies with rendering resolution.

**Comment by pnorman** [comment]
> Assuming that by scale-factor 6 you mean rendering at six times the normal resolution

scale factor is a mapnik parameter: https://github.com/mapnik/mapnik/wiki/Scale-factor

> that seems not quite correct since we make a lot of use of way_pixels for labeling and this i would assume varies with rendering resolution.

I see a couple options

1. Use way_area directly. We used to do this, but it involves a lot of duplication with a selector needed for each zoom level. We might be able to simplify this if we can use the mapnik parameter zoom in a selector, but I don't think that's possible. @rory had to do something like this when adapting osm-carto to vector tiles

2. Alter the queries so their results do not depend on scale factor. This is my preferred approach, and what should have been done originally, but I don't think we adequately tested output for higher resolution devices.

**Comment by imagico** [comment]
The underlying cause for the whole mess seems to be that mapnik does not properly separate between map scale and rendering resolution.  It makes sense for compact code in the style to normalize way_area with the map scale but it obviously does not make much sense to normalize with the rendering resolution if you want to be able to generate the same map scale in varying resolutions.

**Comment by math1985** [comment]
Do we want to support scale_factor at all?

**Comment by pnorman** [comment]
> Do we want to support scale_factor at all?

Yes, it's essential for print.

**Comment by woodpeck** [comment]
Essential for print, as @pnorman says, but the issue will already lead to distorted styling when you produce retina tiles.

**Comment by talaj** [comment]
I think that Mapnik should make a correction by `scale_factor` to `!pixel_width!` and `!pixel_height!` the same way as now corrects scale denominator to be the same when rendering in different resolutions.

One can now object that it would change meaning of `!pixel_width!` and `!pixel_height!`. Yes, it would, but I think that names of these two parameters were not chosen appropriately. Mapnik has a reference resolution of 90.71 DPI. Scale denominators are calculated against this resolution. When you want to render retina tiles, for example, you have to say to Mapnik that you are going to render with two times bigger resolution (in one dimension) by `scale_factor` to allow Mapnik to correct scale denominator. Hence `!pixel_width!` and `!pixel_height!` should also be corrected by `scale_factor` and called `!native_pixel_width!` and `!native_pixel_height!` to emphasize they literally are `!90.71_dpi_pixel_width!` and `!90.71_dpi_pixel_height!`.

**Comment by Tomasz-W** [comment]
@kocio-pl Is this issue still up to date after last Mapnik update?

**Comment by imagico** [comment]
Should be fixed by #3657.
