### ISSUE TITLE
Add rendering for building=bakehouse

### ISSUE THREAD

**Issue by Yvan-Masson** [gravitystorm/openstreetmap-carto#2539]
Hi,

Recently two related proposals were approved: [building=bakehouse](https://wiki.openstreetmap.org/wiki/Tag:building%3Dbakehouse) and [amenity=baking_oven](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbaking_oven).

I think it would be interesting to have a particular rendering of the bakehouse buildings, as those are often particularly visible an can help finding your bearings. I made a small icon proposal based on the one used for shop=bakery you will find attached: ![building-bakehouse_prototype1](https://cloud.githubusercontent.com/assets/9531149/21743953/cf8aa068-d50c-11e6-82c6-103bf372ff05.png)

I do not know if an icon is the best choice, or if the color is well chosen: criticism are welcome…

Best regards,
Yvan

**Comment by kocio-pl** [comment]
Thanks for your idea. However the usage of both is so low, that I don't think these features have proven they are established in any way. Therefore I'm closing it for now. Once the numbers will be more convincing, that people are actually using it, it can be reopened.

The icon is a problem in itself for me - I'm not able to recognize it. But that is secondary issue for now.
