### ISSUE TITLE
Add rendering for amenity=vending_machine

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2540]
[amenity=vending_machine](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dvending_machine)
About [84 000 uses](https://taginfo.openstreetmap.org/tags/amenity=vending_machine), currently not rendered at all.
Since it's only used on nodes, there's no way to see them.

**Comment by kocio-pl** [comment]
Thanks for your input, but this idea was already rejected, so I'm closing it also:

https://github.com/gravitystorm/openstreetmap-carto/issues/1561
