### ISSUE TITLE
Add rendering for vending=excrement_bags

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2543]
wiki: [vending=excrement_bags](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dexcrement_bags)
taginfo: [about 12 000 uses](https://taginfo.openstreetmap.org/tags/vending=excrement_bags).

**Comment by kocio-pl** [comment]
It's partial duplicate of #1561, closing it.

**Comment by tbertels** [comment]
This isn't a duplicate, #1561 is about a generic icon for vending_machine, and was closed because of that.
