### ISSUE TITLE
Add rendering for vending=public_transport_tickets

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2544]
wiki: [vending=public_transport_tickets](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dpublic_transport_tickets)
taginfo: [about 12 000 uses](https://taginfo.openstreetmap.org/tags/vending=public_transport_tickets).

**Comment by kocio-pl** [comment]
It's partial duplicate of #1561, closing it.

**Comment by tbertels** [comment]
This isn't a duplicate, #1561 is about a generic icon for vending_machine, and was closed because of that.
