### ISSUE TITLE
Add rendering for vending=drinks

### ISSUE THREAD

**Issue by tbertels** [gravitystorm/openstreetmap-carto#2545]
wiki: [vending=drinks](https://wiki.openstreetmap.org/wiki/Tag:vending%3Ddrinks)
taginfo: [about 8 000 uses](https://taginfo.openstreetmap.org/tags/vending=drinks).

**Comment by kocio-pl** [comment]
It's partial duplicate of #1561, closing it.

**Comment by tbertels** [comment]
This isn't a duplicate, #1561 is about a generic icon for vending_machine, and was closed because of that.
