### ISSUE TITLE
SVG File for Cemetery

### ISSUE THREAD

**Issue by Jersig** [gravitystorm/openstreetmap-carto#2553]
I'm looking for the SVG file for this cemetery 
http://www.openstreetmap.org/#map=19/43.39214/-1.65720
But I don't find it on this repository.
Do you where is it ?

**Comment by nebulon42** [comment]
There is none. Currently patterns are still PNG. The file is here: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/grave_yard_generic.png

**Comment by kocio-pl** [comment]
We plan to [move the patterns to SVG](https://github.com/gravitystorm/openstreetmap-carto/issues/2045) eventually, but that was not possible until recently and [I've found some problems to do it now](https://github.com/gravitystorm/openstreetmap-carto/pull/2537#issuecomment-272565047).

**Comment by Jersig** [comment]
Ok. 
Thanks a lot for your quick answer.
