### ISSUE TITLE
admin_centre as a way in a boundary relation causes border style rendered on building outline

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#2559]
Having a way (and not a node) such as the townhall as the ```admin_centre``` in a boundary relation of a place causes border style and naming of all those relations rendered on the building outline. Only the ```outer``` and ```inner``` members of such relation should be drawn as borders.

![admin_centre_renders_as_border](https://cloud.githubusercontent.com/assets/8266355/22309515/dcc24a72-e34b-11e6-9852-9b62e29f986d.png)

https://www.openstreetmap.org/relation/16334
https://www.openstreetmap.org/way/252904411

JOSM seems to have a similar effect, btw.

**Comment by pnorman** [comment]
The current behavior is part of osm2pgsql, not openstreetmap-carto.

With lua we have some influence over geometry generation which lets us change the superseded status, but that won't impact this behavior.

You're better off reporting it on the [osm2pgsql](https://github.com/openstreetmap/osm2pgsql/issues) with a simplified testcase so it can be discussed if its a bug.
