### ISSUE TITLE
Phantom spots on map in Levels 8 and 9

### ISSUE THREAD

**Issue by emilde** [gravitystorm/openstreetmap-carto#256]
Please see this map:
http://www.openstreetmap.org/#map=9/37.4400/68.3487

In the map center, you can see a number of grey spots (usually representing something like residential areas). But in OSM data, they do not exist. I made sure the tiles get re-rendered. They appear on map levels 8 and 9.

Actually, for the cases I checked, the areas represented would make sense for settlements, so I wonder where they disappeared. But that's a different matter.

**Comment by matthijsmelissen** [comment]
I think it's worth to look at this again now.
