### ISSUE TITLE
Add rendering for shop=boutique

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#2560]
Please add rendering for shop=boutique. It should be rendered in the same way as shop=fashion [clothes.svg](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/clothes.svg). Boutique is used 10500 times while fashion is used only 3779 times.

**Comment by HolgerJeromin** [comment]
Thanks for your suggestion. You mean that we should have an icon for that. Right now we have a dot already.
This was discussed in #1719 and was (at that time) rejected.
Not sure if the situation has changed...

**Comment by pnorman** [comment]
Duplicate of #1706
