### ISSUE TITLE
Access restrictions are now almost invisible (not enough contrast)

### ISSUE THREAD

**Issue by martenjj** [gravitystorm/openstreetmap-carto#2561]
Road access restrictions used to be rendered in colour (e.g. blue dots = destination, red dots = private etc).  Now they appear to be a very light shade of grey with the length of the dots indicating the type of access.

This is not good for two reasons:

(a) there is not enough contrast to show up easily - see screen shot.  The access of the road changes from destination to private along this stretch, but is it obvious where?
(b) there used to be a mnemonic value (i.e. red being more restrictive than blue).

It would be good to see the original colour rendering restored - maybe with slightly less saturated colours if the reason for change was felt that they were too obtrusive.

![image](https://cloud.githubusercontent.com/assets/10631760/22551869/83b42302-e94e-11e6-89b5-3b3943a312eb.png)

**Comment by HolgerJeromin** [comment]
The main reason with the change in #2257 was to have "unusable" ways to show less and not show better/more.

**Comment by imagico** [comment]
As @HolgerJeromin explained the aim here is specifically not to emphasize access restricted roads.  The example does not indicate a real readability problems, it is not prominent but that is intentional.

So i am inclined to close this.

Changes like this will always generate some level of discomfort for those who were familiar with the old styling.  But that on its own is not enough reason to keep everything the way it is.

**Comment by pnorman** [comment]
I prefer the current styling to the older styling. Of course, improvements are always possible, and if someone wants to play around with colour, width, spacing, etc and come up with something they feel is better, they can open a pull request.

**Comment by d1g** [comment]
>  but is it obvious where?

@martenjj, I'm not sure if it is possible to increase contrast for chunks of ways.

> i.e. red being more restrictive than blue

In any case, private, no and "destination" are not always codified using color on the ground. 

Sometimes it is **yellow/white signs** that prevent you from entering some route, not **red**. 

Older scheme is not better in this sense.
