### ISSUE TITLE
icon for tourism=apartment

### ISSUE THREAD

**Issue by hakuchi** [gravitystorm/openstreetmap-carto#2564]
Can we add a icon for tourism=apartment to the OSM map?
there are over 4000 apartments mapped in OSM

Something like this:

![version1](http://fs5.directupload.net/images/170204/mmqcrn2w.png)

or
![version2](http://fs5.directupload.net/images/170204/jh75rpnw.png)

**Comment by HolgerJeromin** [comment]
Thanks for the suggestion. 
This was rejected in #401 four months ago. 

Right now all icons are monochrome and 14 px sized.

**Comment by pnorman** [comment]
Duplicate of #401
