### ISSUE TITLE
Render Forest Compartment Identifiers

### ISSUE THREAD

**Issue by SK53** [gravitystorm/openstreetmap-carto#2567]
Large forests in many countries (France, Germany, Russia, Poland to my certain knowledge) are often divided into many much smaller compartments. Compartments are often signed with an identifying reference at their edges. The signs are extensively used for navigation within these large forests as individual path junctions are often indistinguishable without such cues. There has been a long-standing desire for such compartments to be mapped in OSM (see for instance this discussion).

This issue is an enhancement request for rendering of compartment references in a future release of the CartoCSS style. Note that at present the total number of elements so mapped is probably lower than the threshold for active consideration, additionally there are at least two tagging styles. Therefore the purpose of this note is largely to document the relevant issues and ideas more precisely.

**Cartographic Exemplars**

The precedent for showing compartment numbers from mainstream 'authoritative' cartography is the Top25 map of the French IGN covering the Foret de Fontainebleau (extract below).

![fdf_forest_comparments](https://cloud.githubusercontent.com/assets/5452818/22779819/2d392606-eeb4-11e6-8c2c-7a0448abf992.jpg)

-- more to be added --

**Cartographic Experiments**

Current experimental examples are based on the IGN approach, using QGIS and overlayed on current CartoCSS tiles:

- Ref placed at compartment centroid
- A partially translucent  border
- Both in a green darker than woodland colour
- Features rendered at scales under 1:100k

The various examples include text with/without drop shadows and one example with 70% opacity.

First a  mapped area in Russia;

![fc_russia2](https://cloud.githubusercontent.com/assets/5452818/22802706/cce07dc6-ef09-11e6-8868-0a663182f0c7.jpg)

![fc_russia1](https://cloud.githubusercontent.com/assets/5452818/22802707/cce3be46-ef09-11e6-9d37-ad1c77f9fcd8.jpg)

Next several examples for Foret de Fontainebleau. The compartments are simulated from OSM by creating polygons from the highway network:

![fc_fontbleau_eg1](https://cloud.githubusercontent.com/assets/5452818/22802601/49e4f528-ef09-11e6-9054-f3b45c665631.jpg)

![fc_fontbleau_eg2](https://cloud.githubusercontent.com/assets/5452818/22802645/76a371d4-ef09-11e6-82eb-8407d0f30aa5.jpg)

![fc_fontbleau_eg3](https://cloud.githubusercontent.com/assets/5452818/22802648/8187d61c-ef09-11e6-933a-051c785ff343.jpg)

![fc_fontbleau_eg4](https://cloud.githubusercontent.com/assets/5452818/22802660/8fbb8954-ef09-11e6-89f1-f2fd46373ca6.jpg)

**Comment by imagico** [comment]
I would not be opposed to rendering labels for this in principle but there are a number of things to consider here IMO:

* there does not appear to be documentation on how to map this on the wiki - the only thing i could find is http://wiki.openstreetmap.org/wiki/RU:Tag:boundary%3Dforestry_compartment.
* I have no idea how widely and how consistently this is actually mapped - there are apparently about 100k combinations of `landuse=forest` + `ref=*` but there is no documentation of this and i am not sure how many of these are actually compartment identifiers.
* without the intention to go into a tagging discussion here the question arises regarding verifiability.  If there are signs for these numbers the signs are certainly verifiable but i am not sure if this applies to the boundaries as well.
* boundaries that are not physically observable in nature and have no legal meaning for normal people (as nature reserve boundaries have for example) should probably not be rendered in this style.  If the boundaries are aligned to physical features (like paths, cutlines, fences) on the other hand it would probably be neither necessary nor desirable to render them and this way obscure the physical feature behind.  This would not preclude rendering labels of course.

So overall i think you are getting a bit ahead of things with discussing specific rendering ideas.

**Comment by pnorman** [comment]
It doesn't appear that the tagging usage (or documentation) is there yet to add this to the rendering. When there's settled tagging and wider usage we can consider it again.

Of the examples, the last two are the best starting points because the others have drop shadows, which is inconsistent with the rest of the style.

Aside from that, I support @imagico points.

**Comment by SMoONF61** [comment]
> It doesn't appear that the tagging usage (or documentation) is there yet to add this to the rendering. When there's settled tagging and wider usage we can consider it again.

The tagging scheme was approved last February:
https://wiki.openstreetmap.org/wiki/Proposed_features/boundary%3Dforest(_compartment)_relations_(v3)

And there are now more than 10000 objects with this tag.

For the many OSM users in the Forest (hikers), where these landmarks are often indispensable, it would be useful to advance this rendering issue 🙂

**Comment by Penegal** [comment]
> For the many OSM users in the Forest (hikers), where these landmarks are often indispensable, it would be useful to advance this rendering issue slightly_smiling_face

Especially when the approved tagging mandates that the `ref` attribute of the OSM object must be the one displayed on the ground.

**Comment by jeisenbe** [comment]
Also it appears the tag boundary=forest has still been used only 426 times - [426](https://taginfo.openstreetmap.org/tags/?key=boundary&value=forest#overview).
The smaller boundary=forest_compartment tags have been used 10k times - https://taginfo.openstreetmap.org/tags/?key=boundary&value=forest_compartment - but usage has not increased very quickly or smoothly, and the geographical extent is mostly in Poland, Belarus, and a few other European regions:
https://taginfo.openstreetmap.org/tags/?key=boundary&value=forest_compartment#map
<img width="701" alt="Screen Shot 2022-06-08 at 12 37 35" src="https://user-images.githubusercontent.com/42757252/172702866-7f93e1c9-a9b8-4768-b785-71dd1d7ca15e.png">

The competing tags `boundary=forestry` and `boundary=forestry_compartment` are still common:
<img width="799" alt="Screen Shot 2022-06-08 at 12 39 18" src="https://user-images.githubusercontent.com/42757252/172702975-368e222a-d769-4045-a380-fb4711104ed6.png">

https://taghistory.raifer.tech/#***/boundary/forest&***/boundary/forest_compartment&***/boundary/forestry&***/boundary/forestry_compartment

**Comment by Penegal** [comment]
> How would such information be useful to a general map user?

The approved `boundary=forest_compartment` tagging mandates that the `ref` of such objects must be the one displayed on the ground. Rendering such objects would be useful for orientation, especially in relatively big forest with many highways.

**Comment by SMoONF61** [comment]
> How would such information be useful to a general map user?

What is the purpose of a map?
Why are road numbers indicated on the map?

In large forests, there are often no other markers: the foresters who manage the forest have needed to quickly identify the parcels, and this identification system is used by all forest users: hikers, cyclists, hunters, tourists, naturalists, etc.

Examples (real life) :
- extract from the guidebook: "turn right between parcel 14 and 15".
- naturalist activity: "I observed a station of this very rare plant to the north-west of parcel 27".
- hunters' meeting: "be careful, the hunting lot today concerns parcels 15 to 32: be particularly careful on parcel 32, as the GR22 hiking trail passes to the north".

It is not surprising that the topographic maps of the professional publishers display this information ... Example with the IGN maps in France (they did not display them anymore last years only for rights issues, but their display is reprogrammed on the new editions)
![image](https://user-images.githubusercontent.com/79086196/172782704-e9526600-c728-4637-921b-d40fa6cf16b7.png)


_NB.  I speak French and I am not sure of the exact translation of "parcelle" (French). What word is used in everyday language by English speakers for these "forest_compartment"?_

**Comment by fpose** [comment]
We also have forest compartments in Kleve, Germany (called [Jagen](https://de.wikipedia.org/wiki/Abteilung_(Forstwirtschaft))).

![reichswald](https://user-images.githubusercontent.com/16304797/185652011-35c99bb2-1e7b-4ab9-900f-594b3e9140af.png)

Here is an official map sample, but I like having the numbers in dark green better, like this:

![reichswald2](https://user-images.githubusercontent.com/16304797/185652754-423ab6b7-0aca-482e-87e8-2336ad19e2bb.png)

**Comment by StC-OSM** [comment]
> Thank you for a rendering example. The lines could be mistaken for hedges, fences or another physical barrier with that type of rendering. The text labels are rather prominent. The rendering is quite prominent.

The first picture provided by the original poster (the IGN) has text labels and borderlines that are actually not that obtrusive when you are reading the map, and there is no chance of any confusion with physical barriers. The last picture in the message above is also quite efficient.

> How would such information be useful to a general map user?

Find their way out of the forest? Just like street names, no more no less.
