### ISSUE TITLE
Icon for office=newspaper

### ISSUE THREAD

**Issue by NetWormKido** [gravitystorm/openstreetmap-carto#2570]
Hi!
office=newspaper is currently not rendered in the map. Can this be changed?

http://wiki.openstreetmap.org/wiki/Tag:office%3Dnewspaper
Icon: http://osm-icons.org/wiki/File:25040.svg
https://taginfo.openstreetmap.org/tags/office=newspaper

**Comment by HolgerJeromin** [comment]
Thanks for your suggestion. 
Just for reference:
Adding rendering for office=* was discussed in #108 and #1697 (which started a list of useful values)

**Comment by abdeldjalil09** [comment]
Milestone should be "New feature" not "Database layout change" because we have "office" previously

**Comment by math1985** [comment]
Fixed!

**Comment by Tomasz-W** [comment]
I don't think a special icon is needed here, because newspaper offices aren't a common-needed feature, and generic dot would be enough here. Any other voices?

@kocio-pl If there won't be a call for separate icon, please reference this issue in #3061 with 'resolves' line.
