### ISSUE TITLE
INSTALL.md doesn't actually tell the user how to install

### ISSUE THREAD

**Issue by SomeoneElseOSM** [gravitystorm/openstreetmap-carto#2576]
It reads fine as far as "Scripted download" but then gets a bit waffly:

"Manual download" doesn't explain when or why you'd do that instead of "scripted".
"Fonts" would benefit from "which font is used where" - do I most of the Noto variants listed in the code make geographical sense but Emoji?
What is the "Non-latin scripts" section supposed to mean?

Re the dependencies, it's debatable whether "Kosmtik" is one - it's needed if you want to develop the style, not just use it.

"carto" _is_ required but there are no clues here about how to install an appropriate version.  The latest Ubuntu 16.04.2 LTS has "carto 0.9.5" (not high enough) so the otherwise reliable https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/ doesn't help.  https://github.com/mapbox/carto#installation suggests just "npm install -g carto" which doesn't work there either.

Further on, the "osm2pgsql to import your data into a PostGIS database" section is surely misplaced as INSTALL.md gave instructions for using osm2pgsql a few paragraphs above.  "Not all users will need these dependencies" should perhaps read something like "You will only need these if you want to adjust the colours used and want them to be evenly spaced as the current colours are".

(edit: typing error)

**Comment by nebulon42** [comment]
>  https://github.com/mapbox/carto#installation suggests just "npm install -g carto" which doesn't work there either.

Why does this not work? I suggest opening an issue for that at the Carto issue tracker and I'll look into it.

**Comment by SomeoneElseOSM** [comment]
Re "Non-latin scripts", it'd also be good to know how to check whether "FreeType 2.6.2 or later" is installed (on at least the most common OSes).  Also what is "A recent enough version" of Noto?

The Emoji question above got an answer on IRC - apparently its in a shop name in the US somewhere :)

**Comment by pnorman** [comment]
The issue with fonts and international scripts is there's a big difference between what's required and what gets the best results. To work what's required is either Noto Sans (or DejaVu) and Unifont, with any version of FreeType that Mapnik compiles against. To get the best results the latest versions of all of the Noto fonts from their git repo is required as well as a recent FreeType. Other font subsystem components might need upgrades too.

If you're rendering Latin text you won't see the difference. Once you start rendering other languages, particularly SE Asian ones, the versions matter.

-----

Manual download should be a subsection of scripted download, and more clearly explain that it's an alternative to the script.

**Comment by kocio-pl** [comment]
@SomeoneElseOSM: Are you fine with the answers and we can close this issue or you feel there are some problems that should still be resolved (if yes, please list them)?

**Comment by SomeoneElseOSM** [comment]
It's still says things like "It might be useful to have a more recent version of the fonts for rare non-latin scripts".  If I'm a newcomer to this repository, how do I know if I need to do this?  I'd expect "Install.md" to list what I need to do, in order, from start to finish, not say "you might need to do X".

That's only one example, another is the statement "On Ubuntu 16.04 or Debian Testing you can download and install the required fonts except Noto Emoji Regular with" which doesn't mention DejaVu.  Do I need that or not? (I suspect not).  FWIW I tried to add a "why you might need to install certain fonts" in the "Fonts" section over at https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ (saying that there was an emoji in an American shop name, and not mentioning DejaVu because I don't think it's needed - but please correct me if I'm wrong).

**Comment by kocio-pl** [comment]
I think that newcomers should not bother with manual configuration at all - it's complicated and error prone, but until now it was the best we could offer them. Now that we've just enabled Docker installation, any new user should try it and I want it to be clear. That's why I want [to show this information at the very beginning](https://github.com/gravitystorm/openstreetmap-carto/pull/2676) of our installation guide.

More experienced users shouldn't have a problem with choosing things according to their needs. In my opinion this is the case with your first example - and probably with the second one too. I don't think we can get rid of all the "you might", "you should" or "you can" in general. There can be specific problems that could be reworded or explained, however I'm not interested in digging there.

**Comment by SomeoneElseOSM** [comment]
(re Docker) agreed - although it's not something I've done much with.  If that does allow people to play with the style and tweak it (and especially if it allows them to run Kosmtik in places where it wouldn't otherwise run) then that'd be a better place to start than a vanilla "Install.md".

**Comment by kocio-pl** [comment]
As far as I know Docker installation is exactly what you need. Yes, you have the osm-carto code from repository to play with and when you want to see the results, just:

- download the needed data extract (at least the first time), 
- run the magic command, 
- wait until it's ready (only first time it's long), 
- point your web browser to a given URL 

and _voilà_ - you can see the map and even export it as an image!

I strongly encourage you to test [dockerized installation](https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md) and report here how do you like it and what's wrong in your opinion.

**Comment by kocio-pl** [comment]
I think this issue can be closed as too generic. For improving (installation) documentation please open more specific tickets.

**Comment by SomeoneElseOSM** [comment]
@kocio-pl Each sentence of https://github.com/gravitystorm/openstreetmap-carto/issues/2576#issue-210661614 identifies a specific problem.  Would you like me to create 8 individual issues for the 8 remaining problem sentences?  This just seems like a recipe to waste everyone's time...

**Comment by kocio-pl** [comment]
Have you tried Docker installation to see if it suits your needs for a start? In my opinion manual installation is just not for everybody and it might be your case. But we can fix it bit by bit if there will be some propositions at least, so specific PRs are more than welcome instead of one big issue.

**Comment by SomeoneElseOSM** [comment]
@kocio-pl For what I was doing when I logged this (trying to create https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ ) a Docker installation wouldn't have been suitable, but there are obviously other use cases where it would be.  It's still worth having a usable INSTALL.md though.

**Comment by kocio-pl** [comment]
OK, I understand. So please create a PR with all the changes you propose for a start, so we could discuss specific things.

**Comment by SomeoneElseOSM** [comment]
I can't propose a PR for e.g. '"Manual download" doesn't explain when or why you'd do that instead of "scripted".' because I don't know the answer to the question.

**Comment by kocio-pl** [comment]
But you have some propositions, so let's start with low hanging fruits and we can add more things later.

**Comment by Ircama** [comment]
> "carto" is required but there are no clues here about how to install an appropriate version.

@SomeoneElseOSM, meanwhile I think I happened to update the [tutorial](https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#install-carto-and-build-the-mapnik-xml-stylesheet) some time ago, maybe addressing your request. I understand you might find my answer not really just in time, anyway.

**Comment by SomeoneElseOSM** [comment]
@Ircama Your changes to your tutorial address the "https://github.com/mapbox/carto#installation suggests just "npm install -g carto" which doesn't work there either" issue, and for completeness the actual problem there was fixed via https://github.com/mapbox/carto/issues/468 and I think https://github.com/mapnik/mapnik-reference/pull/137 .  The whole issue of "Ubuntu 16.04 ships with an antique version of node.js" will presumably be resolved when Ubuntu 18 LTS comes out shortly, at least until the node.js community starts racing ahead of itself again :)

It'd actually be good if Install.md linked to https://ircama.github.io/osm-carto-tutorials/ after the link to Docker.md (which is itself a great addition, although not one I've tested myself).

**Comment by Ircama** [comment]
@SomeoneElseOSM Indeed I mentioned this:

> Install nodejs-legacy:
>````
>sudo apt install -y nodejs-legacy
>````
> Install npm:
>````
>    sudo apt install -y npm
>````
>Install the latest version of carto:
>````
>sudo npm install -g carto@0.18.0
>````

Is that appropriate?

**Comment by SomeoneElseOSM** [comment]
@Ircama Thanks - that works now I believe (it's what https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ says also), although it'll need rechecking when Ubuntu 18 LTS comes out.  I believe I followed the switch2osm guide accurately about a week ago without problems.
