### ISSUE TITLE
Render highway=milestone

### ISSUE THREAD

**Issue by muralito** [gravitystorm/openstreetmap-carto#2577]
Please consider rendering the elements highway=milestone & distance=*
It is an important reference in routes.

Is needed to a visual search for addresses in suburban areas.

**Comment by dieterdreist** [comment]
2017-03-03 17:22 GMT+01:00 muralito <notifications@github.com>:

> Please consider rendering the elements highway=milestone & distance=*
> It is an important reference in routes.
>
> Is needed to a visual search for addresses in suburban areas.
>

In many areas these are placed each 100m on important roads, would be quite
a clutter...

**Comment by imagico** [comment]
In most cases this tag is used on nodes on the road which is in conflict with the purpose of the tag which is for mapping the physical markers.  Rendering the physical markers is something that could be considered for z19, rendering the distance on the road as tagged is not something i would consider suitable for this style.  And we should not support incorrect use of tags anyway.

So i am inclined to close this.

**Comment by muralito** [comment]
The clutter problem could be solved by just rendering only integers values (one element per km or mile) or some other criteria.

About the incorrect use of tags I agree, the tagging could be improved. About the location of the node, it has the same issues that highway=traffic_signals and traffic_signals are rendered at z17.

I don't know why is considered correct use to map some signs (stop, giveway, traffic lights...) as a node of the way, and is incorrect to map the milestone in the same way? 

It's a data to find a location, just like the data in addr:* elements, so if addr:* are rendered i think milestones could be also rendered. Also, addr:* are rendered at z17 like traffic_signals.

There are 10.000+ nodes tagged as milestone.

**Comment by muralito** [comment]
Also, highway=bus_stop which are rendered at z16.

Also, someone can argue that the milestone exist for itself, but it would'nt exists if they weren't for the road it belongs to.

The milestone is an important reference, so I want to understand the criteria that should be complied to be rendered, if the tagging should be improved or corrected, it should be done, but with the ide that it will be rendered.

In suburban areas it's difficult to find where to map some elements without the km markers. The rendering of these elements should make mapping those areas a lot more easy and less error prone. 
For example, a need to map a new gas station, the imagery is several years old, but if I know that it's aprox on the 180Km of some route, and the milestones are in place and rendered, it could be located and maped easily.

**Comment by dieterdreist** [comment]
2017-03-03 19:09 GMT+01:00 muralito <notifications@github.com>:

> Also, highway=bus_stop which are rendered at z16.



there are 900.000 highway=traffic_signals which are defined as "The mapping
of traffic signals is an abstraction that the particular junction or way is
regulated by traffic lights.
It is not a representation of a particular device.", so this is not
comparable to milestones, neither by quantity, nor by the way (where) it is
mapped.
Similarly there are 1.800.000 highway=bus_stop and these are mostly mapped
at the side of the road (I guess, not checked in a representive way).

@christoph although I thought it was like you say (should be mapped on the
actual position, i.e. aside the road) it is not defined like this.
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmilestone
isn't explicit, and the linked proposal
https://wiki.openstreetmap.org/wiki/Proposed_features/Milestones states:
"In any case, the milestone node *must* be part of the way it is referred
to."
I suggest to bring this up on tagging-ml

**Comment by imagico** [comment]
The [wiki page](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmilestone) is currently clear that it is about the physical marker:

> A stone or metal marker on the side of a road denoting the reference and distance travelled.

Discussion about this and about possible other ways to map distance measures along roads should be taken to the wiki or the mailing lists.

I understand the desire to display something like this on the map but as it is currently used the tag `highway=milestone` is not suitable for being rendered here.  This is not meant to prejudice the question if it would be desirable in principle to render either physical markers or mileage numbers in some way at some zoom level.

**Comment by jidanni** [comment]
I just had an experience with this in rural areas. People wishing to communicate the scene of an incident to police, at between km. 7 and 8, but nobody being able to find them on the map (unless one is a "power user".) 
So please add a Crisis Management tag to this issue.

**Comment by jidanni** [comment]
You folks are using the city slicker philosophy that every mom and pop's house addresses should be rendered (even if they just are in some database, but have fallen off the wall), but not the often much more highly visible [kilometer markers](https://www.openstreetmap.org/node/4792030297). [Today's news](https://tw.appledaily.com/local/20210425/MXSXRF2KAVGD7ATUFJ7SGDMW5I/), right in the first sentence, refers to Km. 29.7 . Alas,  users must click on the _data layer_, and then poke around to find the nearest marker...

**Comment by Dimitar5555** [comment]
It seems like the wiki has been updated:

> Draw the node node where the milestone is, and add [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=milestone and other tags describing the sign.
>
> Like [traffic signs](https://wiki.openstreetmap.org/wiki/Key:traffic_sign#On_nodes), the node can be placed either directly on the way that represents the road, or separately at the physical location of the sign besides the road. The pros and cons of both methods are similar to [traffic signs](https://wiki.openstreetmap.org/wiki/Key:traffic_sign#On_nodes).

Rendering only integers at lower zoom levels should be fine. At zoom level 15 for example, there would be a number every 5 cm of the screen which seems reasonable to me (of course it would be nice if there are some example renderings in a place using the metric system and place using the imperial system).

As a matter of fact, having milestones on the map would be good for emergency services (dispatchers and drivers) since they will know exactly where the incident is and how far away they are (instead of relying on info like "Road X between villages Y and Z, after the bridge over river Q").
