### ISSUE TITLE
Underground building rendering.

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#2579]
In the Netherlands we have a BAG import and update. The buildings are very accurate on their position.
In this import there are buildings that are underground, like parkings etc.

[example](http://www.openstreetmap.org/way/440413738#map=19/52.26336/6.79206&layers=N)
**building yes** 
**layer -1** 
**location underground** 
note Parkeergarage De Brink 
ref:bag 164100000291060 
source BAG 
source:date 2016-09-02 
start_date 2000 

Can we render buildings underground  different then buildings on top of it?

On the ground, their could be landuse grass and the parking underground, 
How to render?

Other parking examples:
[1.](https://www.openstreetmap.org/way/264626824#map=18/52.08532/4.31941) Should be under the [grass ](https://www.openstreetmap.org/way/95692434) visible, even better less visible.
[2.](https://www.openstreetmap.org/way/253796669)

**Comment by HolgerJeromin** [comment]
Thanks for your input. 
This is discussed already in #552

**Comment by AllroadsNL** [comment]
I did search for a moment for a topic, keyword underground, must search better next time, thanks for the link.

Now we can go on #552
