### ISSUE TITLE
Unexpected token s

### ISSUE THREAD

**Issue by simpetus** [gravitystorm/openstreetmap-carto#2583]
Hello Im trying to generate mapnik style using carto with project.mml 

Following is the error 

carto project.mml > osm.xml
carto: Unexpected token s

Mapnik version is 3.1 

carto version is 0.9.5

Please help point for a solution as this has been stuck for quite a while and we need to render planet data. 

Regards 

Bhushan

**Comment by SomeoneElseOSM** [comment]
That's the problem that I hit when I logged https://github.com/gravitystorm/openstreetmap-carto/issues/2576 (which when trying to fix I disappeared into a rabbit hole of other problems).  I suspect you can either:

* use a later "carto" version (which I couldn't do for various reasons)
* use an earlier stylesheet version (as https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ currently does)

**Comment by pnorman** [comment]
> carto version is 0.9.5

The [minimum carto version is 0.16.0](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#dependencies), and you also need to specify the Mapnik API version (e.g. `carto -a "3.0.0"`)

**Comment by tylkomat** [comment]
The solution is quite simple. Convert the content of the `project.mml` from `YAML` to `JSON`
