### ISSUE TITLE
Overlapping colours for hospice

### ISSUE THREAD

**Issue by chipyzs** [gravitystorm/openstreetmap-carto#2585]
HI,
I have added a hospice under the tag hospital grounds.
Then I drew the building and marked it as building = hospital.
The issue is that the colours are the same.
I think this is because amenity = hospital is treated the same as building = hospital.
You can see for yourself here: http://www.openstreetmap.org/#map=19/50.82496/-0.78436
I'm not sure if I am just using the wrong tag, but these seem like the correct ones to use, as grounds would cover the gardens, parking, etc.

**Comment by pnorman** [comment]
![image](https://cloud.githubusercontent.com/assets/1190866/24172920/4878d7a6-0e47-11e7-9d0f-ec78359cd131.png)

In the future, please include a screenshot so we can see what you're seeing.

The hospital and building colours are quite different, but the [outer way](http://www.openstreetmap.org/way/477769674) was tagged as a building with building=yes, which was incorrect. I fixed this particular one, but this was a data issue, not a style issue.

**Comment by dieterdreist** [comment]
sent from a phone

> On 21 Mar 2017, at 22:26, James <notifications@github.com> wrote:
> 
> I have added a hospice under the tag hospital grounds.
> Then I drew the building and marked it as building = hospital.
> The issue is that the colours are the same.
> I think this is because amenity = hospital is treated the same as building = hospital.
> You can see for yourself here: http://www.openstreetmap.org/#map=19/50.82496/-0.78436


as a side note you could consider using "hospice" rather than hospital, for both, the building and the amenity key. https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dhospice

**Comment by polarbearing** [comment]
In the example there were even more problems, the polygons for the campus and for the building were each duplicated, carrying different tags. Those are fixed now. 

As a hospice is a special form of a nursing home, it should be (and already was on one of the polygons) tagged as amenity=social_facility + social_facility=nursing_home. 

As for carto, I do not see a need for rendering a hospice separately. amenity=social_facility is currently rendered as a label only, the area should eventually be rendered as well, see #1295 / #1624 / #2087.
