### ISSUE TITLE
Typography guideline

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2599]
With the recent typography tuning, I think it would be useful to document somewhere what we have done. Unfortunately, my English is quite bad. But I have a draft that maybe someone could review:

# Typography

This style uses the font “Noto” (and the font “Unifont” as last resort fall-back) for a world-wide covering of scripts. The font size should be ≥ 10 (legibility).

### Multi-line labels

Additional to text-size  we have to set text-wrap-width and text-line-spacing, For both, the absolute value is meaningless, it should be interpreted relative to the font size (em):
```
text-size: 10;
text-wrap-width: 30; // 3.0 em
text-line-spacing: -1.5; // -0.15 em
```
If text-size increases on higher zoom levels, the other parameters must be adjusted also:
```
text-size: 12;
text-wrap-width: 36; // 3.0 em
text-line-spacing: -1.8; // -0.15 em
```
Usually, with higher zoom levels we increase the line length (text-wrap-width in em). Following an old typography convention, we use narrow line spacing for short lines and wider line spacing for longer lines.
```
text-size: 15;
text-wrap-width: 75; // 5.0 em
text-line-spacing: -0.75; // -0.05 em
```
Noto’s line spacing is rather large to allow also tall scripts like Myanmar to be rendered without collisions. But the line spacing is too large for cartographic usage, therefor we reduce the line spacing. Currently, the line spacing ranges from -0.15 em to -0.05 em. (Even at -0.15 em, collisions are seldom and even then the text stays legible).

**Comment by nebulon42** [comment]
Thanks! Looks good to me apart from some typos and minor adjustments. I think this should go into CONTRIBUTING.md.
