### ISSUE TITLE
Typography for amenity-points.mss

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2600]
I was thinking about typography tuning for amenity-points.mss but with #2589 and #2597 open, I’m not sure if it’s the right moment…

CC @math1985 @nebulon42

**Comment by math1985** [comment]
I can easily rebase, so for me it's not a problem. Not sure about @nebulon42.

**Comment by nebulon42** [comment]
Difficult to say. There might be a few text inconsistencies now that are gone after #2597 gets merged. Assuming there is nothing in #2597 that would prevent it from being merged (I don't know yet.) it would be best to wait a bit. Just to save you from additional work if amenity-points.mss changes quite a bit. Or you could do the PR against my branch and I'll incorporate your commit then.

**Comment by math1985** [comment]
I'd prefer that #2597 doesn't cause rendering changes (perhaps except for obvious bugs being fixed). So let's do first #2597 and then do the font changes at a later moment.

**Comment by kocio-pl** [comment]
Since both #2589 and #2597 are merged/closed now, do you plan to move on with this issue in the near future?

**Comment by sommerluk** [comment]
Yet resolved in #2730 

I forgot to mention this issue in the Github description of #2730, thanks for the hint.

Closing.
