### ISSUE TITLE
highway=turning_circle at the (shared) terminus of track and secondary should render with the higer priority road, not track

### ISSUE THREAD

**Issue by artischocke** [gravitystorm/openstreetmap-carto#2604]
The [west terminus of Hillsboro Boulevard](http://www.openstreetmap.org/#map=17/26.33379/-80.29085) is a turning circle. A track shares this node as its east terminus. I would expect the turning circle to be rendered using the higher priority road (`highway=secondary` in this case), but it is rendered instead for the track.

![capture1](https://cloud.githubusercontent.com/assets/19168045/24547714/7ecfcbb2-1611-11e7-95b0-8b4e8edbfb5d.PNG)

**Comment by daganzdaanda** [comment]
This does not happen if it's a highway=residential or unclassified meeting a track. 
Your example is a secondary road with a turning circle, that's a very rare thing. 

As far as I can tell [from the code](https://github.com/gravitystorm/openstreetmap-carto/blob/8be18f04707d5781470d7f1a6092437794c353d4/project.mml#L1031), we only render turning_circles for tertiary, unclassified, residential, living_street, service and track.

This list makes sense to me, I really have a hard time to see a secondary road as having a turning circle: The wiki says, a secondary highway should be "forming a link in the national route network". A turning circle is usually at a dead end, so this is not forming a link anywhere any more. So IMHO the tagging should be changed to "unclassified", at least for the part that leads to the cul-de-sac.

**Comment by artischocke** [comment]
You're right, of course. I have not ventured into editing road priorities so far as I thought these came from TIGER imports, but your suggestion & argumentation makes sense as far as the definition for `secondary` is concerned so I'll go ahead and edit the road. The list you mentioned indeed seems to be logical, so I'll go ahead and close the issue. Thanks for your response! :)

**Comment by dieterdreist** [comment]
sent from a phone

> On 1 Apr 2017, at 11:54, artischocke <notifications@github.com> wrote:
> 
> I have not ventured into editing road priorities so far as I thought these came from TIGER imports


particularly because they came from tiger it is advisable to check the highway class ;-)
