### ISSUE TITLE
INSTALL.md: add link for installing Noto fonts on macOS

### ISSUE THREAD

**Issue by gregrs-uk** [gravitystorm/openstreetmap-carto#2606]
I tried installing OpenStreetMap Carto on macOS 10.11 and viewing using Kosmtik, but having only installed Noto Sans Regular, Italic, Bold and Bold Italic and not all the other international variants I received a large warning message in Kosmtik (`the font ... is not a known font on your system, please provide an existing font face name`) that obliterated my view of the map itself.

It might be worth adding into INSTALL.md that the easiest way for non-Ubuntu users to obtain all the Noto fonts is by visiting https://www.google.com/get/noto/.

Thanks.

**Comment by sommerluk** [comment]
Thanks for reporting!

1.) The documentation issue could be fixed by #2607 

2.) Could you add a screenthos of the warning message that blocks the map itself?

**Comment by gregrs-uk** [comment]
Thanks for commenting quickly and submitting the PR.

I deleted all the Noto fonts except Noto Sans again and got the following screenshot of the error message that blocks the map:

![screenshot1](https://cloud.githubusercontent.com/assets/7353938/24837768/7536baf6-1d33-11e7-9d72-b667f61d9153.jpg)

The same error appears on the command line. When the page is refreshed, the following is displayed instead:

![screenshot2](https://cloud.githubusercontent.com/assets/7353938/24837770/7f0bc490-1d33-11e7-96eb-42e8481b9bbe.jpg)

However it seems tricky to reproduce the first error (the one that blocks the map). More often than not the second (shorter) error seems to appear straight away instead.

Hope that helps. Thanks.

**Comment by sommerluk** [comment]
Hm.

I also do not have installed all the fonts, but I never got this warning message in the browser windows. (Instead, I see the warning message on the console from which I started kosmtik.)

Overall, it looks to me rather as thsi is an issue Kosmtik itself and not of openstreetmap-carto…

cc @pnorman

**Comment by gregrs-uk** [comment]
I should've said that having installed all the Noto fonts using the Google link everything works fine.

**Comment by SomeoneElseOSM** [comment]
@sommerluk I think that Kosmtik has changed its behaviour recently to show error messages in that style.  Obviously if the resulting error message obscures useful content that's a Kosmtik issue, but the initial request (explain to people how to install fonts on MacOS) isn't really related to that and it's openstreetmap-carto that needs those fonts, not Kosmtik per se.

**Comment by sommerluk** [comment]
So I would consider this issue as solved once #2607 is merged.

**Comment by sommerluk** [comment]
So I would consider this issue as solved once #2607 is merged.
