### ISSUE TITLE
regression: building disappears

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#2611]
This building http://www.openstreetmap.org/way/341791043/history used to be rendered correctly, and even when its disappearence was reported on the tagging list, I could load a page with correct rendering. However, zooming and refreshing caused the building disappear for me as well. 

First suspicions are a regression in carto for the combination of ```amenity=school``` and ```building=school```, or a glitch in the rendering database?

Cached or different tileserver? initial view:
![school-cached](https://cloud.githubusercontent.com/assets/8266355/25070285/dde78a1e-229a-11e7-947b-cb1fc899c7ce.png)
Refreshed view:
![school-current](https://cloud.githubusercontent.com/assets/8266355/25070289/e2e1d39e-229a-11e7-8f9a-e461069473bc.png)

Tile servers say it was rendered Thu Apr 13 15:30:06 2017
http://b.tile.openstreetmap.org/18/63088/94343.png/status (all, a b and c), the tile showing without the building.

[This was the question](https://lists.openstreetmap.org/pipermail/tagging/2017-April/032100.html) on tagging.

**Comment by polarbearing** [comment]
Hm, I probed a couple of other ```amenity=school + building=school```, with and without campus grounds, they all render correctly.

**Comment by mboeringa** [comment]
I see it properly displayed at all scales from Z13 onward where buildings start to appear, even after hitting F5 several times.

**Comment by polarbearing** [comment]
So how do you see the single tile cited above? This it what I get currently, the tip of the car park, and no building:
![94343](https://cloud.githubusercontent.com/assets/8266355/25070956/61b3ed82-22ab-11e7-813f-d1cabbea7a0e.png)
I wonder if @tomhughes could help here and check rendering/caching machines. 
Can we compare what http://tile.openstreetmap.org/cgi-bin/debug delivers, that might help him, for me:
```
tile.openstreetmap.org debug
Server Stats
Cache Server: kalessin.openstreetmap.org
Render Server: scorch.openstreetmap.org
Load Average: 8.42
```

**Comment by mboeringa** [comment]
> So how do you see the single tile cited above?

Z19 view (but as said, I see the building on all other zoom levels as well):

![school_building](https://cloud.githubusercontent.com/assets/7635726/25071081/c7b2e432-22ae-11e7-8ca8-cb0c2849954a.jpg)

**Comment by mboeringa** [comment]
> Can we compare what http://tile.openstreetmap.org/cgi-bin/debug delivers, that might help him, for me:

tile.openstreetmap.org debug
Server Stats

Cache Server: trogdor.openstreetmap.org

Render Server: scorch.openstreetmap.org
Load Average: 8.03

**Comment by pnorman** [comment]
Based on the above it doesn't seem to be a style issue.

**Comment by polarbearing** [comment]
Tom has identified that as a rendering database glitch, see the operations (156) ticket above.
