### ISSUE TITLE
Creation of a projects file for Taginfo

### ISSUE THREAD

**Issue by giggls** [gravitystorm/openstreetmap-carto#2614]
Taginfo has a neat feature about which tags are used in which project:
https://taginfo.openstreetmap.org/projects

Unfortunately this project (which I consider one of the most important ones at all) is not yet part of it.

If I understand it correctly we would need to create such a file manually, as the tags in use are hidden behind complex SQL queries and sometimes even renamed internally in the style.

I already have a key-only version in my fork of the style:

https://taginfo.openstreetmap.org/projects/osm_carto_de

I would be willing to try to set up a first version of such a file. After it got merged, we could then change the rules for contributers in a way, that changes have to be added to this file in addition to the ones in the style itself.

Sven

**Comment by HolgerJeromin** [comment]
There was an old closed issue about the same: #961

**Comment by nebulon42** [comment]
The concerns were about not being able to manually maintain such a list. The discussion should continue in #961. I'm re-opening that so we can revisit this topic.
