### ISSUE TITLE
Name for landuse=industrial ommited at zoomlevels 15/16

### ISSUE THREAD

**Issue by manfredbrandl** [gravitystorm/openstreetmap-carto#2627]
'Marienhütte'
z14
![image](https://cloud.githubusercontent.com/assets/5360273/25666965/5524152c-3022-11e7-83a3-bb6f679fd407.png)
z15
![image](https://cloud.githubusercontent.com/assets/5360273/25666994/67ceb0b0-3022-11e7-9c64-0acaac75e0a8.png)
z16
![image](https://cloud.githubusercontent.com/assets/5360273/25667016/77d2bd94-3022-11e7-9177-b48f6d9b1146.png)
z17
![image](https://cloud.githubusercontent.com/assets/5360273/25667036/876a6388-3022-11e7-9571-0aacb7eba0a9.png)

Could this become more consistent?
See https://www.openstreetmap.org/#map=17/47.06182/15.41622

**Comment by dieterdreist** [comment]
2017-05-03 17:04 GMT+02:00 Manfred Brandl <notifications@github.com>:

> Could this become more consistent?




I propose to remove labeling from landuse queries if there aren't other
tags to describe what it is (feature tags). Generally, this style wants to
deliberately decide the features for which names are rendered (as opposed
to rendering any name on any area in the rendering db as it was before),
and a properties like landuse, surface or similar hardly qualify as
features. Toponyms of settlements or their parts can nicely be mapped with
"place". Have a look at suburb, neighbourhood or
https://github.com/gravitystorm/openstreetmap-carto/issues/798

**Comment by kocio-pl** [comment]
There are two big classes of objects we have problem with being more specific - buildings and shops. With landuse I don't feel we need to be more strict, because we already render only some types of landuse.

But this issue is about different problem - most probably the name is omitted because of parking icon (see https://github.com/gravitystorm/openstreetmap-carto/issues/2429) and maybe street name.

**Comment by math1985** [comment]
Indeed, we have a choice here between rendering street names and landuse names on this zoomlevel. The choice has been made to prioritize street names. Changing this priority will lead to different problems. Unfortunately there's not much we can do here.

**Comment by manfredbrandl** [comment]
In the meantime the name "Marienhütte" is not displayed on z14 but consistently displayed on z17/z18/z19 .

**Comment by kocio-pl** [comment]
On z14 there are named railway tracks now, the rest is the same probably.
