### ISSUE TITLE
some issues in get-shapefiles.sh (curl and unzip) (in Ubuntu 12.04 LTS)

### ISSUE THREAD

**Issue by fastrde** [gravitystorm/openstreetmap-carto#263]
hi,

the curl -z option is explained in the manpage as a shortcut for --time-cond and expected a timestamp not a filename. The unzip matching {shp,shx,prj,dbf,cpg} doesn't match any file in the simplified-land-polygons-complete-3857.zip container.

```
curl -L -o "data/simplified-land-polygons-complete-3857.zip" "http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip"
```
and
```
unzip $UNZIP_OPTS data/simplified-land-polygons-complete-3857.zip -d data/
```

works for me.

lg

fastrde

**Comment by pnorman** [comment]
There's no bug here, though it'd be nice to not have the warnings.
