### ISSUE TITLE
Rendering leisure=track on lines

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#2632]
We are rendering `leisure=track` on areas but not on ways - neither circular nor linear.  With the database reload we are also not going to interpret closed ways as areas by default any more.

Adding line rendering for tracks would be possible and would make sense.  It could be done in a way that is visually similar and compatible to area rendering with a fill and casing in the same colors as used for areas.

See also #574, #2238, #1504, #2533.

**Comment by polarbearing** [comment]
Does this still have dependencies or can that be fixed now?

**Comment by kocio-pl** [comment]
I guess it should be possible to fix now.

**Comment by kocio-pl** [comment]
Could anybody try to create a PR? It should be pretty straightforward.

**Comment by Tomasz-W** [comment]
It could be rendered the same as attraction=water_slide ways (https://github.com/gravitystorm/openstreetmap-carto/pull/3346), but without bridge-like black side lines

**Comment by polarbearing** [comment]
Yes as long as it is the identical colour to leisure_track on area, I fully agree.
