### ISSUE TITLE
rendering of Muslim cemeteries

### ISSUE THREAD

**Issue by michalfabik** [gravitystorm/openstreetmap-carto#2638]
Hi, can we please have Muslim cemeteries render like [this](https://wiki.openstreetmap.org/wiki/File:Landuse-cemetery_muslim.png)? As of now, we have patterns for [Christian, Jewish and atheist/other/unknown cemeteries](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dcemetery#Rendering), but none for Muslim ones. For example, [here](http://www.openstreetmap.org/#map=16/43.3336/17.8198), the cemetery to the south looks like an atheist one (as opposed to the Christian one to the north), but in fact it is a Muslim cemetery.  

I think this could improve the map in places like the Balkans, Israel, Egypt, Northern Caucasus, Indonesia and elsewhere where Islam coexists with other religions.

**Comment by nebulon42** [comment]
Thanks for the pattern file. Yes, that would be possible. We might want to already use SVG pattern files or otherwise just use this.

**Comment by imagico** [comment]
In principle i think this is a good idea - i would however like to verify that the hilal is considered an appropriate symbol for a cemetery by Muslim.  In Christianity the cross is obviously widely used as a symbol for graves and graveyards but i would not want to automatically assume the same applies in Islam for the crescent moon symbol.

As @nebulon42 indicated this would be a good opportunity to move the graveyard patterns to SVG - see #2045.

**Comment by michalfabik** [comment]
I'm not sure about the .svg files: in the OSM Wiki, icons that are intended for nodes indeed are .svg files (e.g. [here](https://wiki.openstreetmap.org/wiki/File:Memorial-16.svg)), but patterns for areas/landuses are .png's. I did read the guidelines for reporting issues here and it did mention .svg files, but again, only for icons, nothing about areas. So I went with what the Wiki uses. Sorry if I did it wrong, I'm quite new to this.

**Comment by mboeringa** [comment]
> In principle i think this is a good idea - i would however like to verify that the hilal is considered an appropriate symbol for a cemetery by Muslim. In Christianity the cross is obviously widely used as a symbol for graves and graveyards but i would not want to automatically assume the same applies in Islam for the crescent moon symbol.

Good question. The University of Texas library seems to have a nice collection of Middle East (topographic) maps online:

http://www.lib.utexas.edu/maps/israel.html

**Comment by imagico** [comment]
@michalfabik  - you did nothing wrong, we would just like to move to using SVGs for patterns to allow easier rendering of this style at different resolutions.

I added some symbols to jsdotpattern to simplify that - here an example, probably requires some tuning:

http://www.imagico.de/map/jsdotpattern.php#x,128,jdp64237;gs,16,32,32;rd,0,0,0,hilal2,1.25,8,8,0,jdp97473,88b78e,aacbaf;

**Comment by mboeringa** [comment]
So far looking over some of the Texas University maps it's become clear to me that, probably not unsurprising given the region and history, mapping cemeteries seems to have had very little to no priority at all in the Middle East or for western nations historically involved in the region. Most maps seem void of them...

In fact, OSM may be the first map that may put them on the map for the region.

But maybe someone with local knowledge chimes in...

**Comment by StyXman** [comment]
I asked several coworkers descendants of Muslims and they agree that the crescent is ok. I can look for a more reliable source if you want...

**Comment by StyXman** [comment]
See also: https://en.wikipedia.org/wiki/Symbols_of_Islam#Symbols

**Comment by michalfabik** [comment]
> I asked several coworkers descendants of Muslims and they agree that the crescent is ok.  
  
Same here, I asked some of my friends who are Muslims themselves (Sunni, from Bosnia, if it makes a difference).

**Comment by math1985** [comment]
An alternative would be to drop the crosses/David stars at all, and use the generic cemetery in all cases. Is it really important to know for a casual map user what religion a cemetery is?

**Comment by imagico** [comment]
I think this is useful information.  It is rather common that different religions have separate cemeteries.  And the rendering we use is fairly intuitive.  We could think about a somewhat weaker contrast between base color and pattern to avoid interference with mapped trees at z16/17.

Thanks for the feedback on the suitability of the symbol - it at least seems this is not a big faux pas.

**Comment by michalfabik** [comment]
@math1985
> Is it really important to know for a casual map user what religion a cemetery is?  
  
I would tend to agree that it's not that important if peoples of individual religions lived on strictly separated, perfectly homogenous territories.  
However, this is not always the case and sometimes the cemeteries and their religion can tell you a lot.  
A big atheist/free-for-all cemetery near the centre of a city? Most likely a run-of-the-mill one run by the municipality, expect a lot af traffic around and maybe a public transport hub. Otherwise move on, nothing to see here.  
Are there many small Muslim ones this side of the river? Expect a noisy bazaar, twisty narrow streets, kebab stalls and cheap accommodation.  
There's a small graveyard on a hill at the end of of this village? Well big deal, every village has one. But does it happen to be Jewish? Then it might have a small Holocaust museum or something of that sort, probably worth a visit.  
YMMV, I'm not saying I'm necessarily a casual map user.

**Comment by micahcochran** [comment]
Cemeteries that are not religious ones should be considered secular, not atheist.

@math1985 
>  Is it really important to know for a casual map user what religion a cemetery is?

In my opinion, I don't think it is necessarily for a base map.   

If you just look at [`landuse=cemetery` with `religion` on taginfo](https://taginfo.openstreetmap.org/tags/landuse=cemetery#combinations) there are 52 186 instance,  `christian` has 40 198, and `muslim` has 8 760.  There aren't even 1 000 instance of Jewish cemeteries tagged.  I think there is a case that could be made to have Muslim cemeteries render.

How far should rendering religious cemeteries go?  There are multiple values specified for [religion tag](https://wiki.openstreetmap.org/wiki/Key:religion), but only christian, muslim, buddhist, hindu, shinto, jewish, and taoist have more than 2 000 instances.

**Comment by michalfabik** [comment]
@micahcochran 
> Cemeteries that are not religious ones should be considered secular, not atheist.  
  
My bad, we don't normally distinguish between the two in my language.

**Comment by grischard** [comment]
What would be good symbols for those other missing ones then? How do maps in countries where those religions are common represent cemeteries?

Possible symbols could be:

Hinduism - Om symbol
Shintoism - Shinto torii
Taoism - Yin and Yang
Buddhism - Buddha or dharmachakra?

**Comment by imagico** [comment]
I think this is outside the scope of this issue which is about muslim cemeteries.  Those are known to be widespread and the suggestion to add a distinct rendering for them is sound - at least as long as we distinguish cemeteries by religion in general.

Anything else will need to be looked at separately.  Does a religion practice burial in cemeteries?  Does it maintain exclusive cemeteries for members of their faith?  At least for hinduism the answer is no.
