### ISSUE TITLE
Render addr:flats or addr:unit tags like housenumber or housename

### ISSUE THREAD

**Issue by saerdnaer** [gravitystorm/openstreetmap-carto#264]
Before I create a pull request, a little discussion:
We in munich have a problem with the tagging of one of the student home neighborhoods. There is a area where every building has the same offical housenumber, but each apartment has it's own building entrance and a own apartment number. Basically an extreme version of terraced housing.

Some user used this appartment number as content for addr:housenumber. In the discussion at our local meeting we came to the conclusion to use addr:flats insteat, but this is not rendered yet. 

Is this the right tag to use, or would you prefer an other one?

More information: 
http://www.openstreetmap.org/#map=19/48.17930/11.55186
http://www.studentenwerk-muenchen.de/typo3temp/pics/b9b5aaba19.jpg

**Comment by ERnsTL** [comment]
There is [another case example](https://help.openstreetmap.org/questions/39962/how-to-tag-block-of-apartments-with-units) of an apartment complex, using addr:housenumber and addr:unit, with detailed info over at the OSM Help Forum.

I am open to any solution tagging-wise, but the rendered result should look better than right now, see the link, and if not too cluttered, include the flat/unit number at high zoom level.

Post solution here please, so that I can finish tagging that apartment complex. Thanks.

**Comment by 1ec5** [comment]
> alternatives might be addr:door or addr:unit, but as addr:flats is used 10 times more often I'd probably go with it.

Now `addr:unit` is used twice as much as `addr:flats`. (openstreetmap/iD#3980 would add `addr:unit` to iD, which would likely increase usage of this field where unit numbers are erroneously placed in `addr:housenumber` or `addr:street`.)

**Comment by BalooUriza** [comment]
I would prefer addr:unit instead, as this handles everything along that
same general concept, including private mailboxes, apartments, office
suites, townhouses, trailer park lots, campsites, etc.

**Comment by saerdnaer** [comment]
For reference – here is link to a TagInfo comparison view: https://taginfo.openstreetmap.org/compare/addr:unit/addr:flats/addr:door/addr:housename

**Comment by tpikonen** [comment]
I don't have local knowledge on the original example, but I think the correct way to tag it would be to use, for example, addr:unit="Q" and addr:flats="59" and perhaps also building:part=yes for the ways defining separate flats. Currently the tagging is addr:housename="Q59" and building=yes.

Release 4.4.0 added rendering of addr:unit, so rendering of addr:flats would still be needed to fix this issue.

**Comment by matthijsmelissen** [comment]
We render addr:unit since #2494.
