### ISSUE TITLE
Use OpenType features to get better legibility

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2647]
There are some characters that might easily be confounded. 1lI are such characters (U+0031 DIGIT ONE, U+006C LATIN SMALL LETTER L, U+0049 LATIN CAPITAL LETTER I), and O0o are (U+004F LATIN CAPITAL LETTER O, U+0030 DIGIT ZERO, U+006F LATIN SMALL LETTER O). One of the design goals of this map style is to give mappers feedback for their work. So it is good if similiar letters can easily be distinguished.

The current release version of Noto does not give us any options here. But the current alpha version of Noto has the “zero” OpenType feature, that gives a different shape of U+0030 DIGIT ZERO to distinguish it from U+004F LATIN CAPITAL LETTER O. Usually the “zero” OpenType feature is implemented by a slash or a dot in the inner of the U+0030 DIGIT ZERO glyph. See https://github.com/googlei18n/noto-fonts/files/685675/en-733-slashed-zero-NotoSans-Regular.pdf for a rendering sample of Noto’s alpha version. Once released, it might be interesing for us to use it…

**Comment by pnorman** [comment]
What would we change on our end to do this?

**Comment by sommerluk** [comment]
We would have to set http://mapnik.org/mapnik-reference/#3.0.6/text-font-feature-settings for text. Currently, we do not set it explicitly, and the gives us the default OpenType settings (liga… enabled. dlig, hlig, zero… disabled). I suppose this Mapnik property is also available in CartoCSS??

**Comment by nebulon42** [comment]
> I suppose this Mapnik property is also available in CartoCSS??

If you find it in mapnik-reference then you can use it in CartoCSS if carto uses that specific version of mapnik-reference.

**Comment by sommerluk** [comment]
> Other OpenType features might be interesting though.

After taking a look into NotoSans-Regular.ttf with FontForge, I think most of the other OpenType features are not interesting for us.

We have:

- `aalt` provides `LATIN CAPITAL LETTER ENG` (`U+014A`) with different shapes for european and african languages. Should be treated with `locl`, see #2208 Same for `U+03D0` `GREEK BETA SYMBOL`
- `ccmp` is yet enabled (Mapnik applies the default OpenType recommendation for enabled/disabled features), and that’s okay.
- `locl` see #2208 
- `subs` `sups` `ordn` (subscript, superscript, ordinals) not interesting for us because we do not know where to use. (Example: “1er arrondissement” – “er” should have `ordn`)
- `numr` `dnum` `frac` (typographic fractions) not interesting for us – see above
- `case` useful case-sensitive forms would require more preprocessing than we can do with Mapnik. Furthermore, currently Noto only changes the digits, so we can do the same thing easier with `lnum`, which is the default anyway.
- `rtlm` Only provides a mirrored “sum” sign (∑). I think we should left right-to-left handling to Mapnik/harfbuzz, which works reasonable well.
- `c2sc` `smcp` Small capitals could be confusing for mapper feedback.

Maybe interesting:

- `lnum` `onum` (upper-case/lower-case digits). Noto defaults to upper-case digits. I suppose the [lower-case digits](https://en.wikipedia.org/wiki/Text_figures) won’t improve the rendering much?
- `tnum` `pnum` (monospaced/proportional digits). Noto defaults to monospaced (“table”) digits. Monospaced digits make sense for tables, so that in rows of numbers, one digit is exactly below the other digit. As we don’t render tables, it might make sense to switch to proportional digits that might look smoother.

What do you think about the last two?

**Comment by kocio-pl** [comment]
`lnum onum` looks to me rather as a fancy stuff (making text more interesting, not more legible), but `tnum pnum` might be useful. However I personally don't have any problems with reading numbers on osm-carto, so for me it's just nice to test if you want.

**Comment by kocio-pl** [comment]
@sommerluk Are you still interested in this issue? If not, I would suggest to close it.

**Comment by sommerluk** [comment]
Closing.

Reasons:

- The original idea of the slashed zero has not worked well in #2997.
- Most other OpenType features are not interesting for us for either technical reasons (yet a good default value or lack of information) or because they are yet covered by other issues – see https://github.com/gravitystorm/openstreetmap-carto/issues/2647#issuecomment-354422847
- `onum` is nice, but today many people are not used to see them. Furthermore, they are interesting for numbers within text, but probably most of the digits on the map are `ele` data for mountain peaks, and in this case `onum` does not help anyway. So I think it’s better not to use it.
- `pnum`: People are used to see `pnum` digits. But for isolated `ele` data (which is most of the digits on our map), `tnum` (which is the default) is better, so no need to change something here.
