### ISSUE TITLE
providing a map symbology for every tile created

### ISSUE THREAD

**Issue by MaestroGlanz** [gravitystorm/openstreetmap-carto#2650]
This is a feature request/idea:

Normally the different items, rendered in one tile are not many different ones. In my opinion, it would be useful, to create a map symbology for every tile as a list of icons and meaning. It must be a list, because normally, there are several tiles displayed, which generates duplicates.

If there are i.e. 5 tiles displayed, it collects all lists, eliminates duplicates and displays the list in the corner.

Problem: 
-There must be names for all the amenities, shops, etc. in the current language. I found this neither in taginfo nor in the wiki.
-For some regions the list can become very long

This is just an idea, but I think, it has great potential.

**Comment by imagico** [comment]
I don't think this is a workable request for this style.  Something like this would require support from the renderer and if there was such support it would be something that could not be made use of by this style but by the map application displaying the map (i.e. openstreetmap-website).

For the more general task to create a map legend see #1928.

**Comment by kocio-pl** [comment]
Thanks for your idea, @MaestroGlanz! I guess this is not something we can apply now, so closing it. Feel free to reopen the discussion once it could be really implemented.
