### ISSUE TITLE
shop=mall dot at z17-19

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2651]
I just noticed a big fat dot on z18, that turned out to be a mall: http://www.openstreetmap.org/node/380498034
It works on ways, too: https://www.openstreetmap.org/way/126248046

It seems as if the name still shows until z15 or z16, but then at z17 the generic dot takes over and gets bigger for z18 and z19.  The style of the dot is a bit strange, too - it has a black border.
Possibly this was introduced with https://github.com/gravitystorm/openstreetmap-carto/pull/2589
The black outline is discussed there and @math1985 had adressed that issue. Maybe malls were overlooked? 

I think we should not switch from a red name without dot to a pink dot without name. So how to make it more consistent?
Do we have any other names in red? Are malls worth a special treatment?
Should we add an icon (see #2276) to the name from z15 and keep it until z19?
Or return to the previous state? (IIRC, malls only had the red text and no icon.)

**Comment by math1985** [comment]
Correct, this is a bug that I introduced.

**Comment by math1985** [comment]
I think we should not display a dot for malls at all (as you say, they have a red label already).
