### ISSUE TITLE
man_made=pier, finer? color?

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#2652]
[Rendering is to big on z17.](https://www.openstreetmap.org/#map=17/52.68170/5.94702)
![pier](https://cloud.githubusercontent.com/assets/8817345/26659487/3f359938-4671-11e7-8763-d27e26af4c28.PNG)

Also other zoom levels needs a finer adjustment. higher and lower z.

[z16](https://www.openstreetmap.org/#map=16/52.6811/5.9478)

Does it need to be visible on z12 - z14, z15.
I do not think so, maybe z15 could be discussed.
Is it needed for the overall view? Me, no.

Is white the best color for a pier?
This white looks, if it is not balanced with the surrounding.

**Comment by pnorman** [comment]
> Is white the best color for a pier?
> This white looks, if it is not balanced with the surrounding.

It's not white, it's the same land colour as the background.

**Comment by AllroadsNL** [comment]
This, I thought so, like the man_made=reinforced_slope.

**Comment by meased** [comment]
I have always thought that piers are way too thick. Large piers should probably be drawn as areas anyway, so piers drawn as ways should be assumed to be just wide enough to walk on.

I am ok with the land color as it has nice contrast with the water.

**Comment by imagico** [comment]
We currently do not render any lines in a width that corresponds to a real life width on the ground, some time ago the decisions was made not to have this anywhere in this style (see https://github.com/gravitystorm/openstreetmap-carto/pull/1853#issuecomment-181783967)

**Comment by AllroadsNL** [comment]
`We currently do not render any lines in a width that corresponds to a real life width on the ground, some time ago the decisions was made not to have this anywhere in this style`

If the line was not rendered then the background color where a pier should be, should not been seen.
Water is not all blue.
The pier is rendered, as a line .........

It is half done.

You set a pier on the map or not, render it fully or not.

**Comment by pnorman** [comment]
> If the line was not rendered then the background color where a pier should be, should not been seen.
> Water is not all blue.
> The pier is rendered, as a line .........

I'm having a hard time comprehending what you're trying to say, could you try rephrasing it?

**Comment by AllroadsNL** [comment]
Hope this clears it up, not native language, gives these hick ups. I suppose.

If it was not rendered, then there was not a hole in the water area, then you could not see the background.
![water no hole](https://user-images.githubusercontent.com/8817345/26878877-587f698c-4b8f-11e7-800b-cfbe6bb158c3.PNG)

![water hole](https://user-images.githubusercontent.com/8817345/26878885-61f03028-4b8f-11e7-9745-30df972fa6d9.PNG)
The man_made=pier is rendered making a open spot in the water area.
This means the man_made=pier is rendered with transparent or not drawn outline and not drawn shape.
The vector(line) is there but we do not see it. 
We see it, because there is a hole in the water and different background color.

In Carto the man_made=pier (line) is mentioned to do so, (rendering)
Line is giving a wide, in the several zoomlevels. This could be changed to appropriate zoomlevel wide.
Or drawn outline or shape, coloring.

**Comment by math1985** [comment]
> This means the man_made=pier is rendered with transparent or not drawn outline and not drawn shape.

This is not correct. Piers are rendered with a line that happens to have the same color as the background of the map. The result is the same, of course.

**Comment by AllroadsNL** [comment]
My misunderstanding.

Still to thick and visible on z12 - z14, z15.

>  in a width that corresponds to a real life width on the ground,

but the proportion to other map objects must be right.

**Comment by imagico** [comment]
> > in a width that corresponds to a real life width on the ground,

> but the proportion to other map objects must be right.

I agree - in particular in this case since the color does not imply an abstract line but a real world geometry - this is a model case of confusion between a styling element and a mapped geometry as we come time ago discussed in #2462.

One option would be - since a pier is kind of like a footway bridge - to render it in a styling that resembles the way we render footway bridges (like [here](http://www.openstreetmap.org/#map=19/47.99032/7.85101)).

**Comment by matkoniecz** [comment]
Given that walkable man_made=pier are supposed to be tagged also with highway=footway (or other highway=* tag if appropriate), maybe we can just stop rendering this object and expect people to add missing tags?

> One option would be - since a pier is kind of like a footway bridge - to render it in a styling that resembles the way we render footway bridges (like here).

I would be against this solution as it would mask missing data.

**Comment by HolgerJeromin** [comment]
> Given that walkable man_made=pier are supposed to be tagged also with highway=footway (or other highway=* tag if appropriate)

This is surprising and not mentioned in the wiki

https://wiki.openstreetmap.org/w/index.php?title=Tag:man_made%3Dpier

**Comment by pnorman** [comment]
> Given that walkable man_made=pier are supposed to be tagged also with highway=footway (or other highway=* tag if appropriate), maybe we can just stop rendering this object and expect people to add missing tags?

No, that's incorrect.

I looked at a few piers. Overall, I'm happy with how piers on z17 are currently being rendered.

**Comment by matkoniecz** [comment]
> No, that's incorrect

Yes, you are right. I confused my preferred tagging with one that is really used.

**Comment by matkoniecz** [comment]
http://overpass-turbo.eu/s/sxQ finds man_made=pier with highway tag other than highway=path/footway

It turns out that there are mutiple cases with highway=pedestrian, highway=service, highway=steps.

(note, I started discussion on tagging mailing list about tagging if this feature)
