### ISSUE TITLE
shop=car_repair color inconsistency dot vs icon

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2658]
Hi, just noticed this: For shop=car_repair, as long as it's displayed as just a dot, the color is violet, but when the icon shows up, it is brown. 
It seems this is the only shop=* value that is rendered with a brown icon. 
It would look better if either the dot for car repairs was brown, or even if there was no dot for this (because we do not use any brown dots atm, IIRC)

Related PRs #2589 and #1778, also discussion #1783 and closed PR #1868

**Comment by HolgerJeromin** [comment]
I just wanted to report the same. To save my work here are some screenshots :-)

[This](https://www.openstreetmap.org/node/4436235201) car_repair can not be fully rendered in every zoom, but is rendered with a pink dot. Bug full icon is brown...
Z17
![image](https://user-images.githubusercontent.com/2410353/28888992-db6a2990-77c2-11e7-919a-ff491696b651.png)

Z18
![image](https://user-images.githubusercontent.com/2410353/28888970-cad21778-77c2-11e7-80a0-c499bc3ca0c3.png)

**Comment by Tomasz-W** [comment]
@polarbearing related to #3069

**Comment by polarbearing** [comment]
I still prefer shop=car, car-repair, bike, bike-repair --> violet

**Comment by lakedistrictOSM** [comment]
And now there's a name/icon colour mismatch, too:

![btae](https://user-images.githubusercontent.com/20193716/44302690-2a62c180-a326-11e8-9143-1419c44ad591.PNG) https://www.openstreetmap.org/way/354086766

**Comment by polarbearing** [comment]
Just checked, it's on the same tile. But in z19 only, z18 is all brown, z17 is a purple dot.

**Comment by jragusa** [comment]
Pink icon is not correct since both icon and label are defined in amenity-brown colour. However, I don't understand where is the issue in the code.

**Comment by polarbearing** [comment]
See discussion about service vs self-service in 3395#issuecomment-421578484 .
If we agree on purple than the fix is simply remove the [colour-exemption ](/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss#L1019).

**Comment by Tomasz-W** [comment]
Just for the note: there is the same problem with `shop=massage`

**Comment by jragusa** [comment]
Is everyone ok to to use purple colour for `shop=car_repair` ?

This issue wants desperately to be resolved by a very small fix ;)

**Comment by kocio-pl** [comment]
I still think that shops should be for selling goods and brown amenities for the places that are selling services, like in his case.

**Comment by jragusa** [comment]
So what would be the rendering at z17 ? icon or brown dot ?

**Comment by kocio-pl** [comment]
I would use brown icon with brown label, just like any other service POI. It's easier to stick to the tagging, but hairdresser for example is also not a shop for me, so I would treat it as library or cinema for example.

**Comment by Tomasz-W** [comment]
> brown amenities for the places that are selling services

and leisure-green for places selling leisure-like services (e.g. shop=massage) ;)

**Comment by kocio-pl** [comment]
Yes - we have more types of services and it's always good to use as specific category as possible.

**Comment by jragusa** [comment]
If there is no opposition, I will prepare a PR to change purple colour of `shop=car_repair` and `shop=hairdresser` to brown amenity colour

**Comment by kocio-pl** [comment]
I would also check all the other shops we currently render. For example beauty shop is also selling services, but there can be more of such "shops".

**Comment by Tomasz-W** [comment]
@kocio-pl @jragusa 

I've checked shop icons list and I would move to amenity-brown these ones:
* shop=laundry
* shop=dry_cleaning
* shop-=car_repair
* shop=hairdresser
* shop=beauty

**Comment by HolgerJeromin** [comment]
Please use a special color variable
@shop-service or @service-shop
and not 
@amenity-brown or @public-service

**Comment by dieterdreist** [comment]
sent from a phone

> On 26. Nov 2018, at 21:48, Tomasz Wójcik <notifications@github.com> wrote:
> 
> shop=laundry
> shop=dry_cleaning
> shop-=car_repair
> shop=hairdresser
> shop=beauty


like theatres, memorials, archaeological sites, museums and cinemas? 

IMHO we should not deviate from the classification that the mappers invented, shops are explicitly selling goods andor services. The above are all clearly shops (they are private businesses), showing them like historic items or cultural places is neither appropriate nor will it facilitate map reading.

**Comment by kocio-pl** [comment]
> like theatres, memorials, archaeological sites, museums and cinemas?

Somebody once asked here in disgust about some POI (I can't remember which one) "why brown, as in toilets?"... Nobody ever reported this (cultural and entertainment having the same color as toilets) as a problem.

We have a gastronomy and health classifications for example, which clearly "deviate" from "amenity", so there's already not a clear color=key rule (with pharmacy being shop, because you buy physical goods, but tagged as amenity...).

**Comment by polarbearing** [comment]
Traditionally a pharmacy used to prepare your drugs, mix your ointments, thus the perspective as an amenity.

**Comment by dieterdreist** [comment]
sent from a phone

> On 27. Nov 2018, at 02:07, kocio-pl <notifications@github.com> wrote:
> 
> Somebody once asked here in disgust about some POI (I can't remember which one) "why brown, as in toilets?"... Nobody ever reported this (cultural and entertainment having the same color as toilets) as a problem.
> 


as long as you follow the osm classification (amenity), it is less of a question, and it is consistent for those knowing the tagging system 


> We have a gastronomy and health classifications for example, which clearly "deviate" from "amenity", so there's already not a clear color=key rule (with pharmacy being shop, because you buy physical goods, but tagged as amenity...).
> 


“deviating” (splitting a subgroup of things to a new group) also raises less issues, the question is with shifting things from one group into another.
A pharmacy isn’t a simple shop, at least not in Germany or Italy, it is a place where you can get qualified advice by a pharmacist. Other than selling products, they also prepare them (still today, it is not just a historic anecdotal thing).

**Comment by jragusa** [comment]
So following previous comments I propose to move `shop=laundry`, `shop=dry_cleaning`, `shop=car_repair`,  `shop=hairdresser` and `shop=beauty` with brown colour of amenity with dedicated variable such as @shop-brown.

Is that ok for everyone ?

**Comment by Adamant36** [comment]
If the color isn't changing its a superficial change at best. I could see a day when so many things are rendered its better to have variables/colors that aren't tied to the tag types (like with issue #3326). I don't if its at that point yet though. plus there's both advantages and disadvantages. It seems like it will necessary to some degree at some point though.

**Comment by jeisenbe** [comment]
I haven’t researched this enough to have an opinion, but I suspect there
are other shops that provide services. I’d suggest looking through the
whole list before making changes

**Comment by Tomasz-W** [comment]
@jeisenbe See https://github.com/gravitystorm/openstreetmap-carto/issues/2658#issuecomment-441792517. Please read discussion before you start to participate, otherwise it's a lack of respect for another users and more-or-less their time wasting by discussion messing.

**Comment by Tomasz-W** [comment]
@kocio-pl As I support moving service-like shops to brown, but we won't use brown generic dot (it would be too simillar to gastronomy objects and propably not intuitive )I think that following objects https://github.com/gravitystorm/openstreetmap-carto/issues/2658#issuecomment-441792517 shouldn't be rendered as icons at z17 (they are not so important to show them there, maybe shop=car_repair is an exeption) but z18.

**Comment by kocio-pl** [comment]
It's not about importance, for shops and gastronomy it's about their density only. All the other objects don't clutter z17.

**Comment by kocio-pl** [comment]
For example it was the same with excluding night clubs from gastronomy in #3475.

**Comment by jragusa** [comment]
Update of the shop variable which would be shifted to amenity brown colour:
`shop=laundry`, 
`shop=dry_cleaning`, 
`shop=car_repair`, 
`shop=hairdresser`
` shop=beauty`
`shop=travel_agency` (new)

**Comment by polarbearing** [comment]
Wouldn't it be better to move all the daily-life services as above, along with the driving school and crafts, to office-craft-service-blue?

**Comment by jeisenbe** [comment]
My preference is that the color should patch the key. One of the most important features of this style is mapper feedback, and using the same color for all `shop=*` values will help mappers to recognize the icon as a type of `shop=` tag.

**Comment by HolgerJeromin** [comment]
> will help mappers to recognize the icon as a type of `shop=` tag.

With preset-driven Editors like iD many mappers does not know the keys behind the features.

**Comment by jragusa** [comment]
In addition there is two colours for `amenity` key: orange and brown, and we aim to use the same red health colour for `healthcare` key and some amenities. I add `amenity=driving_school` to the list.

**Comment by jdhoek** [comment]
There is something to be said for both standpoints regarding the colour `shop=car_repair` should have, but:

![nope](https://user-images.githubusercontent.com/683699/164529369-d236f69f-b589-4f80-bbaa-7dd529e0f92d.png)

…this bug is rather jarring, and has been with us for quite a while. I've prepared two mutually exclusive PR's: one makes it purple, the other brown. Might one of these serve as an interim solution while the long-term direction of these colours is considered?

* #4535
* #4536

**Comment by kocio-pl** [comment]
Thanks for reviving this ticket!

Once I wanted to create some separation between selling things and selling services, but now I think it's hard to separate, especially with some types of offices selling services too (like [`office=estate_agent`](https://wiki.openstreetmap.org/wiki/Tag%3Aoffice%3Destate_agent)). 

Now I would prefer simple technical solution - color referring to OSM type (in this case shop->violet), but if community wants brown version I would not argue. So maybe let's keep it simple - if you're interested, please give a like for the solution you prefer.
