### ISSUE TITLE
Move icon for car_wash to z18 or 19

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#2659]
Icons for car_wash show up at z17, and these are really not very important. We could move the threshold to z18 or z19. 

Most amenity=* values that have an icon are starting at z17 (except for a few at z16 and bench and waste_basket at z19) 
I don't think there are icons starting at z18 right now, so this would open a new category. I don't know if we could find other amenitys that would fit into this group, maybe amenity=recycling without recycling_type=centre?

**Comment by kocio-pl** [comment]
I would not push such big feature to z19 - rather some small ones (as proposed [here](https://github.com/gravitystorm/openstreetmap-carto/issues/1745)). We currently don't have recycling_type tag in rendering database, I guess, so we have to wait a moment, but I had similar idea there.

**Comment by kocio-pl** [comment]
I don't think it's so unimportant to push it later. Also it takes some space, so it's not a small amenity.

**Comment by matkoniecz** [comment]
@kocio-pl I agree, in my experience it is not an issue.

@daganzdaanda Can you consider posting examples of situations where proposed change would improve situation? Maybe Poland has unusually large car washing amenities or there is some other information what we missed.
