### ISSUE TITLE
Rendering shop=medical_supply with a special icon

### ISSUE THREAD

**Issue by Jotam** [gravitystorm/openstreetmap-carto#2660]
The tag shop=medical_supply has > 3,400 instances. I suggest the following icon:
![med](https://user-images.githubusercontent.com/15984044/27228542-589ffd76-52a8-11e7-8cd3-af25a59af473.png)

**Comment by kocio-pl** [comment]
Is there an SVG version of this image?

**Comment by Jotam** [comment]
Sure. Here you go: https://github.com/Jotam/openstreetmap-carto/blob/patch-1/symbols/shop/medical_supply.svg

**Comment by Jotam** [comment]
@kocio-pl: Did you get the SVG file as requested?

**Comment by kocio-pl** [comment]
Yes. Technically speaking I would like to make it lighter - probably big wheel could be empty inside.

However there was kind of agreement not to add more shop icons (see https://github.com/gravitystorm/openstreetmap-carto/pull/2386#issuecomment-264728777). It does not change my opinion - I would still add them as long as they are very popular (tyres have above 12k uses, I just failed to design good enough icon; funeral_directors, tailor or interior_decoration are all above 5k uses) or easy to depict (ticket, locksmith). This one falls into the second category, so I consider it worth rendering. 

After most of the shop icons was moved from z17+ to z18+ adding new icon could be more acceptable, but I'm not sure how big difference it makes.

**Comment by Tomasz-W** [comment]
Icon proposals based on @Jotam design:

![shop medical_supply](https://user-images.githubusercontent.com/25656654/37023894-a858c7e6-2127-11e8-958c-ff1f908e85e1.png) (plaster)
![shop medical_supply2](https://user-images.githubusercontent.com/25656654/37024328-d01ef7cc-2128-11e8-95f2-bdf9ddeb5f7b.png) (pill)

Wheelchair-only icon may be confusing (these shop offer a lot of other equipment too), so I've tried to combine it with other elements.

**Comment by Jotam** [comment]
Excellent idea! I like what you did with the wheelchair. I does indeed look a lot lighter.
The only problem I see is that the plaster and the pill are hard to recognize at such a small scale. Reminds me somehow of an American football. :-)

**Comment by kocio-pl** [comment]
I also can't recognize them. I would opt for just a wheelchair - it looks better for me without a wheel filling.

**Comment by Jotam** [comment]
I agree with @kocio-pl : Just the wheelchair in the light version you proposed would be perfect.

**Comment by Tomasz-W** [comment]
Here you are. Gist link:

https://gist.github.com/Tomasz-W/e3f64b453b582d83e3965f68120a9104

**Comment by kocio-pl** [comment]
Thanks! Another task for a coder - anybody willing to make a PR?
