### ISSUE TITLE
Rendering scenic=yes on highways

### ISSUE THREAD

**Issue by fqdb** [gravitystorm/openstreetmap-carto#2661]
The tag scenic=yes is for marking roads with scenic views, but currently it is not rendered. I think a good way to render it would be like how Michelen road maps show scenic roads, with a green outline.
![image](https://user-images.githubusercontent.com/2826336/27477133-88b32c78-580b-11e7-9041-bd7d1d6c1be7.png)

The boundary of leisure=nature reserve would be a good fit I think, if the width of the line is reduced a bit. I  made a quick mockup of how it could look:

![image](https://user-images.githubusercontent.com/2826336/27477188-b476f0c4-580b-11e7-80e5-bc38329f095a.png)

**Comment by imagico** [comment]
[Tag documentation](https://wiki.openstreetmap.org/wiki/Key:scenic) - 4700 uses.

Note the tag as documented is not meant for scenic roads, it is meant for _roads signed to be scenic_.  Tagging scenic roads that are not signed as such would be inherently non-verifiable - though a large portion of current use of the tag is not according to the definition, in Germany it is for example mostly used on paths and tracks in a completely subjective way.

I don't think we should render that, we already have lost of attributes on roads we render and additional ones we want to render (#2621, #110) so there is hardly room to also show such a relatively minor and ultimately fairly arbitrary distinction.

**Comment by math1985** [comment]
Agree per the above.
