### ISSUE TITLE
circular cliffs are not rendered

### ISSUE THREAD

**Issue by fkv1** [gravitystorm/openstreetmap-carto#268]
Cliffs that are closed ways (i.e. start node = end node) are not rendered. They should be rendered in the same style as open-way cliffs, with ticks on the right side. Interpreting them as areas by default makes no sense, because areal cliffs are of historical interest at best. For areas with rock surface, the tag natural=bare_rock has been approved by voting.

See https://trac.openstreetmap.org/ticket/3294 for the history of this bug. It is annoying not only that is has not been fixed for 3 years, but also that the ticket wasn't migrated to the new bug tracking system.

**Comment by fkv1** [comment]
Clarification finished. Ways tagged natural=cliff do now default to area=no.
http://wiki.openstreetmap.org/wiki/Proposed_features/cliff_clarification

**Comment by fkv1** [comment]
See #1227 for a follow-up.

**Comment by math1985** [comment]
Best solved with a new database import.

**Comment by kocio-pl** [comment]
Probably related to https://github.com/gravitystorm/openstreetmap-carto/issues/892.
