### ISSUE TITLE
Italic vs high-contrast fonts

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2692]
![screenshot 1](https://user-images.githubusercontent.com/6830724/28326817-54a8f32a-6bd1-11e7-9c74-2150f4b34bcd.png)

The screenshot uses Noto Serif Regular instead of Noto Sans Italic.

Currently, for `oblique-fonts`, we use Noto Sans Italic, which covers the latin, greek and cyrillic scripts – following https://en.wikipedia.org/wiki/List_of_writing_systems#List_of_writing_scripts_by_adoption that’s about 58% of the population. For the other scripts, we fall back to the regular style; so 42% do not see any difference between `oblique-fonts` and `book-fonts`.

It is unlikely that we will ever have italic/oblique fonts for the other scripts, because italic/oblique design is a particularity of latin/greek/cyrillic typeface design and mostly unknown in other cultural contexts.

On the other hand, the difference between sans/low-contrast on one hand, and serif/high-contrast on the other hand is more widespreaded. (Contrast means the contrast in stroke thickness within the glyphs: In low-contrast fonts all parts of the strokes have almost the same thinkness, and in high-contrast fonts some parts show a much thicker stroke than other parts.) With the currently released Noto Serif fonts, we would cover about 85% of the population. And in the next Noto release, there will be further more Serif fonts, the the coverage would raise again.

The biggest “coverage gain” we would have with the CJK scripts. But because of the complex glyph forms and the often small font size in openstreetmap-carto, a high-contrast CJK glyph is here also problematic for legibility. Note also that, as far as I know, Noto Serif CJK (though released some months ago) is still not packaged for Ubuntu, which might mean that it won’t be available on the osm.org servers soon.

Noto Italic vs Regular means that the Italic font is designed to be harmonic with the Regular style, but at the same time have an easy-to-spot difference. Noto Serif vs Sans means that the Serif font is also designed to be harmonic with the Sans style, but it’s _not_ designed to have an easy-to-spot difference; of course it looks different, but it’s not so obvious.

In general, serif/high-contrast styles are more difficult to render and read at small font sizes that sans/low-contrast fonts.

Advantages of Serif:
- Get away from cultural bias to western typography
- Extends greatly the coverage of the `@oblique-font` (as it’s currently called) style (from 58% to at least 85%)

Disadvantages of Serif:
- More dificult to spot the difference with the regular style for western scripts (about 58% affected here)
- Maybe more difficult to read at small font sizes

Comments?

**Comment by mboeringa** [comment]
Always good to have the comparison image of the current rendering of the same area:

http://www.openstreetmap.org/#map=13/5.3282/-4.0782

![afbeelding](https://user-images.githubusercontent.com/7635726/28329696-fb0798b6-6bea-11e7-9db8-47cfc0f652b5.png)

**Comment by kocio-pl** [comment]
Interesting proposition. I'd like to know what the people using these scripts (other than latin, greek and cyrillic) think about it?

**Comment by imagico** [comment]
To me this looks mostly awkward but i would be interested in examples where this supposedly leads to advantages and in opinions for native users of scripts where this would apply.

Also i would like to hear to what extent different scripts know the serif/sans serif and the regular/oblique concepts or something comparable to them (or to the other script variants known for Latin like bold or small caps) and how these concepts are currently mapped to the fonts we use or could be to improve the map in those areas.

In Arabic we have for example the Naskh/Kufic distinction - see #2496 - which cannot be compared to either of these, it is more like the Latin Antiqua/Fraktur distinction.

**Comment by sommerluk** [comment]
An example with CJK glyphs (especially left bottom and right top).

Serif:
![screenshot 1](https://user-images.githubusercontent.com/6830724/28615445-9ae12a84-71e8-11e7-9ccf-c1076a08714a.png)

Oblique/Italic (current):
![screenshot 2](https://user-images.githubusercontent.com/6830724/28615468-ab1678e6-71e8-11e7-9f65-94a63ea0b691.png)

**Comment by sommerluk** [comment]
About regular vs bold: Its usage is quite clear: bold are labels that we want to emphasis: They stand out compared to regular labels.

What’s our policy for italic/oblique labels? When do we use regular, and when oblique? It seems that areas are often rendered oblique, but on the other hand motorway connections are point geometries, and also rendered oblique. Is there a policy?

**Comment by sommerluk** [comment]
I do not know so well non-latin scripts. But as far as I know about the scripts:

- Regular/[italic ](https://en.wikipedia.org/wiki/Italic_type) is something quite particular to the LGC (latin/greek/cyrillic) script. I don’t know of other scripts to have something similar.
- Regular/[oblique ](https://en.wikipedia.org/wiki/Oblique_type) is something that (apart from LGC) I have seen also for Thai fonts. In general, like italic it’s not so widespreaded outside LGC fonts.
- Regular/[automatically-slanted regular “fake oblique”](https://en.wikipedia.org/wiki/Oblique_type#Automated_obliques.2C_or_.22fake_italics.22) (that means the software slants simply the regular style because the font family does not provide an own italic or oblique style) is not available in Mapnik, and it’s good that it’s not available. Typographically that’s really bad style.
- Regular lowercase/[small caps or petite caps](https://en.wikipedia.org/wiki/Small_caps) can only be available for [bicameral scripts](https://en.wikipedia.org/wiki/Letter_case#Bicameral_script). Apart from LGC, this applies to some more scripts, but none of them is widespreadly used.
- Regular lowercase/[all caps](https://en.wikipedia.org/wiki/All_caps) is obviously also only  available for [bicameral scripts](https://en.wikipedia.org/wiki/Letter_case#Bicameral_script). 
- Regular lowercase/[capitalization](https://en.wikipedia.org/wiki/Capitalization) is obviously also only  available for [bicameral scripts](https://en.wikipedia.org/wiki/Letter_case#Bicameral_script).
- Regular/[letter-spacing](https://en.wikipedia.org/wiki/Letter-spacing) works for LGC scripts and probably most other scripts without big problems [except cursive scripts](https://drafts.csswg.org/css-text/#cursive-tracking) like arabic. [Some Mapbox software even disables letter-spacing for Arabic scripts](https://github.com/mapbox/mapbox-gl-js/issues/4208).
- Regular/[underline](https://en.wikipedia.org/wiki/Underline) is independent of the script, but will likely not look good for cursive scripts like arabic or joint scripts. I think it’s also ugly in general.
- Regular/[bold](https://en.wikipedia.org/wiki/Font#Weight) will probably exist for all scripts. All scripts can also be written by hand, with both think and thin pens, so the concept of thick vs thin lines (heavy vs light font) is quite universal. So you can find this concept also in printed typography.
- [Serif](https://en.wikipedia.org/wiki/Serif)/[sans ](https://en.wikipedia.org/wiki/Sans-serif) is, as far as I understand, something particular to LGC fonts. For CJK fonts, there is [Ming](https://en.wikipedia.org/wiki/Ming_(typefaces))/[gothic](https://en.wikipedia.org/wiki/East_Asian_gothic_typeface) which is quite similar (more decorations/less decorations). Outside LGC and CJK (as far as I see) it seems that this concept is not much used.
- High-contrast/low-contrast: The contrast between thick and thin strokes within the same glyph seems to be also a quite universal concept. You can write every text with a [dip pen](https://en.wikipedia.org/wiki/Dip_pen) and get high-contrast glyphs, and you can write a text with a [ballpoint pen](https://en.wikipedia.org/wiki/Ballpoint) and get low-contrast glyphs. So you can find this concept also in printed typography.

Some technical remarks:
- Mapnik does not support underline.
- Letter-spacing needs more space than regular text, which is problematic for use in cartography. Furthermore, in cartography, letter-spacing will interfere more with the underlying yet drawn objects like outlines of houses, roads and so on. Overall, I think this would be problematic. While I was working on the font size for water features, I had played around a little bit with larger spacing, because there are quite a few (printed) maps that do so. But I did not get good results. I think for good letter-spacing a computer/Mapnik cannot do that. A human has to place this text manually; otherwise it will not look good.
- All caps: I don’t think this would be a good idea because this would break the feedback loop.
- Arabic typography seems to be less developed compared to other scripts. Perhaps because Arabic has more a calligraphic tradition and typography was less important. Anyway there seem to be some development, and as for western scripts there are various forms, I suppose this be become more common also for Arabic. In my opinion, at least the basic concepts like regular/bold and high-contrast/low-contrast can be applied to the Arabic script without problems.
- In general, when various font styles are mixed because you use a different font for the title and for the continuous text, you would not take them from the same font family (like Noto Sans/Noto Serif), but you would choose two very _different_ fonts to distinguish them easier. Anyway, I think that’s not an option for us, because cartographic use is different from pure text rendering, we do not have another font with a similar coverage like Noto, and we do not have to distinguish title vs continuous text (who’s positions are clear) but we have many irregular-placed labels and a too-different font might make the map harder to read.

Some Noto-related remarks:
- “Noto Sans Italic” is not italic, but oblique. (This detail is probably not so important for openstreetmap-carto.)
- I doubt that Noto will implement small caps or petite caps for scripts other than LGC soon. Even for LGC, Noto alpha Phase III does not provide a complete support for small caps.
- [“Noto Serif” has not always serifs, but is always high-contrast. “Noto Sans” has never serifs and has always low contrast.](https://github.com/googlei18n/noto-fonts/issues/749#issuecomment-252911079) For LGC, “Noto Serif” has indeed serifs. For CJK, it’s like Ming, so also a sort of serifs. For other scripts like Devanagari or Georgian, there are no serifs. So a more exact name for “Noto Sans” might be “Noto low-contrast”. And a more exact name for “Noto Serif” might be “Noto high-contrast”.
- Noto will have a “Noto Sans Arabic” (=low contrast font) in the next release.

**Comment by imagico** [comment]
There seem to be two different effects here:

* styling consistency within the individual label with multilingual name tags tagged for the renderer.  I don't consider this relevant because it is wrong tagging.
* a distinct styling difference between the different types of labels in non-Latin texts similar to the normal/oblique difference in Latin.  This seems a good idea but i wonder if it would be possible to combine fonts so that we have the oblique in Latin and the serif version in scripts that do not have an oblique variant - which at least in CJK does not appear to be a real serif font anyway although it is similar in featuring a higher contrast than sans serif.

**Comment by kocio-pl** [comment]
> What’s our policy for italic/oblique labels? When do we use regular, and when oblique? It seems that areas are often rendered oblique, but on the other hand motorway connections are point geometries, and also rendered oblique. Is there a policy?

My wild guess is that we have no rules here.

**Comment by math1985** [comment]
>  Is there a policy?

Not at the moment.

**Comment by sommerluk** [comment]
> i wonder if it would be possible to combine fonts so that we have the oblique in Latin and the serif version in scripts that do not have an oblique variant

Interesting proposal! Technically, it is possible! And it would preserve the advantage of a visually easy to spot distinct rendering for LGC, and at the same time make a (less) distinct rendering for other scripts possible.

In general, I am reluctant to use so different concepts like regular/italic on one place and sans/serif on other places, but for the main cartographic feature. That’s not mainly about multi-language labels. You will also have situations where some POI on your screen have one script, and others another script (country boarders, bilingual regions…). And even if you do not see them on the same screen at the same moment, it might feel less intuitive when you are familiar with the rendering in latin regions and than you switch to an asian region.

But I think it might be an option to combine both: Use “Noto Serif Italic” for LGC, “Noto Serif * Regular” for other available serif scripts (and our usual fallback fonts). So we could preserve both, the oblique rendering for LGC (but with serifs now), and nevertheless have a consistent look&feel with the difference “serif vs. sans” that will be available in most places of the planet. It would look like this:
![screenshot 1](https://user-images.githubusercontent.com/6830724/28672517-7a21302c-72cf-11e7-9948-6f6626f27738.png)

**Comment by imagico** [comment]
I definitely prefer the _serif italic_ to the _serif regular_ for latin script.  It might even be that this improves on #2380 relative to the current design.

My main reasoning was that the serif - sans serif distinction on non-latin scripts is fairly different from both the regular - oblique and the serif - sans serif distinctions so it might not be such a big problem to combine them differently.  For most non-native readers the styling nuances of foreign scripts are probably not that meaningful (but opinions from the other side, i.e. from non-native latin readers, would be useful here).

But if _serif italic_ works nicely for what we currently use _sans oblique_ for that would also work.

**Comment by sommerluk** [comment]
There is one design pattern that I forgot in the list above:

Regular/condensed: The font width. In condensed font faces, the glyphs take less horizontal space. This one might be interesting, as Noto Phase III will support this for a varity of fonts.

**Comment by sommerluk** [comment]
I’ve updated https://github.com/gravitystorm/openstreetmap-carto/issues/2692#issuecomment-318041654 about font width and also font weight.

**Comment by sommerluk** [comment]
Current usage of @oblique-fonts is:
- All water.mss is rendered oblique (names of rivers, lakes…).
- Of placenames.mms, only state names are oblique. All others not.
- Of roads.mss, only motorway_junction is oblique. All others not.
- amenitypoints.mss: islands, islets, aerodromes and @landcover-face-name are oblique.

**Comment by kocio-pl** [comment]
I believe this can be closed as the code solving it was rejected.
