### ISSUE TITLE
man_made=breakwater now require area=yes to fill. intentional?

### ISSUE THREAD

**Issue by Gazer75** [gravitystorm/openstreetmap-carto#2693]
Was this an intentional change?

**Comment by imagico** [comment]
Yes.  See #1504.

**Comment by Gazer75** [comment]
Can't say i agree with this move, but ok...

**Comment by math1985** [comment]
The rationale: all objects that can represent both linear and area features now require explicit area=yes to treat them as areas. In the old situation, closing a linear feature could (unexpectedly) change the semantics. Perhaps for breakwater this was not a big practical problem, but for other features like city walls it was.
