### ISSUE TITLE
Please like issues you would like to see prioritized

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#2696]
Github nowadays has the option to sort by thumbs up and thumbs down reactions. That allows us to easily prioritize issues by number of thumbs up. Of course, being an open-source repository with volunteer contributions, nobody can tell anybody else what to do. And also sometimes maintainers have a more high-level view which might make us prioritize things differently. However, I will try taking into account which issues are important to you when deciding what to work on.

I would therefore like to invite everyone to indicate with :+1: reactions which issues you would like to see prioritized.

The current ranking is:
* #2548 Add rendering to landcover=grass and landcover=trees - 4 upvotes
* #688 Building doesn't render on top of highway areas any more - 2 upvotes
* #1874 Render brand=* for amenity=fuel - 2 upvotes
* #2209 Define a (bigger) minimal font size - 2 upvotes
* #2557 Render name for waterway=dock - 2 upvotes

However, this feature is not yet commonly used, so I can imagine the ranking might change if more peple start using this feature. Please do so!

**Comment by kocio-pl** [comment]
Where could we see this ranking?

**Comment by math1985** [comment]
On the issue page, and then Sort-:+1:.

**Comment by kocio-pl** [comment]
When trying to resolve https://github.com/gravitystorm/openstreetmap-carto/issues/2548 and https://github.com/gravitystorm/openstreetmap-carto/issues/1874 I've noticed that I don't understand what is a "feature" (like feature=k_v). Looks like some special type, which works different than simple k=v (probably the same problem here: https://github.com/gravitystorm/openstreetmap-carto/issues/2086#issuecomment-317030913). I failed to make working code and I'd like to learn how to deal with it. 

Now we have also new style+lua files, which adds another layer of tag filtering (beside using tags from hstore). So we have pretty complicated, 3-layered system, which is not documented nor explained anywhere. It makes it harder for all developers to work with osm-carto code.

I would be glad to read kind of tutorial on solving complicated cases. Something like blog entry explaining one such case would be enough probably.

**Comment by kocio-pl** [comment]
Sorry, wrong button.

**Comment by math1985** [comment]
> When trying to resolve #2548 and #1874 I've noticed that I don't understand what is a "feature" 

We did this to prevent combinatorial explosion. For example, in the amenity_points layer, we want to display man_made features, shop, amenities etc. If we just used rules like [shop=supermarket] and [amenity=bank], then carto would also create a Mapnik rendering rule for objects with both [shop=supermarket] and [amenity=bank], or for every combination of keys. To prevent this, we use features as a key. For example in highway_area_casing we have this:

``
COALESCE((
  'highway_' || (CASE WHEN highway IN ('residential', 'unclassified', 'pedestrian', 'service', 'footway', 'cycleway', 'track', 'path', 'platform') THEN highway ELSE NULL END)),
  ('railway_' || (CASE WHEN railway IN ('platform') THEN railway ELSE NULL END))
) AS feature
``

COALESCE is a function that takes the first non-null value from a list, and || is used to concatenate two strings (note that a string concatenated to NULL results in NULL). So if an object has one of the mentioned highway tags, for example residential, then we get highway_residential. If highway is NULL, than the result of the entire highway line is also NULL, so we use the result of the railway line, assuming railway is not NULL. The entire result is stored in feature.

**Comment by kocio-pl** [comment]
Seems to me like "feature" also works different. For example when trying to solve https://github.com/gravitystorm/openstreetmap-carto/issues/435 like this:

https://github.com/gravitystorm/openstreetmap-carto/compare/master...kocio-pl:public_transport_platform

there's no change in rendering. When I try to add `public_transport_` as a feature:

`'public_transport_'|| CASE WHEN tags->public_transport IN ('platform') THEN public_transport ELSE NULL END,`

I get this error:

```
Postgis Plugin: ERROR:  column "public_transport" does not exist
LINE 21:       'public_transport_'|| CASE WHEN tags->public_transport...
                                                     ^
```
and the same happens when skipping `tags->` prefix.

What is the problem and how can I fix it?

**Comment by math1985** [comment]
Should be `THEN tags->public_transport`.

**Comment by kocio-pl** [comment]
With:

`'public_transport_'|| CASE WHEN tags->public_transport IN ('platform') THEN tags->public_transport ELSE NULL END,`

and using `feature =` notation:

https://github.com/gravitystorm/openstreetmap-carto/compare/master...kocio-pl:public_transport_platform

I have the same error.

**Comment by math1985** [comment]
I think public_transport in https://github.com/gravitystorm/openstreetmap-carto/compare/master...kocio-pl:public_transport_platform#diff-2d6c6d06f63a6fab47286addedefc335R2123 is undefined, you need to add it in https://github.com/gravitystorm/openstreetmap-carto/compare/master...kocio-pl:public_transport_platform#diff-2d6c6d06f63a6fab47286addedefc335R2187 like you did with bus. I have no carto at hand so I didn't actually test this.

**Comment by kocio-pl** [comment]
Still no luck - if I add just a name, the error is shown like this:

```
Postgis Plugin: ERROR:  column "public_transport" does not exist
LINE 3:     public_transport,
            ^
```
`text-point` layer seems to have special handling of hstore tags.

OK, I will try again if anybody could help me later.

**Comment by pnorman** [comment]
> text-point layer seems to have special handling of hstore tags.

None of the layers have special handling. The problem looks like you're trying to extract the value of the `public_transport` tag, but you're telling it to extract the value of whatever key `"public_transport"` is (e.g. bus). Text values need single quotes.

**Comment by kocio-pl** [comment]
Current Top 7 (at least 3 up up votes):
1. #1874 Render brand=* for amenity=fuel (+9) - undecided
2. #2704 Render tourism=museum areas (+7) - undecided
3. #688 Building doesn't render on top of highway areas any more (+6) - undecided
4. #2697 Render landuse=religious (+4) - PR ready, but undecided
5. #103 Render place names on areas the same way as on nodes (+3) - PR ready, but undecided
6. #508 Add pictorial route shields (+3) - bigger effort, lack of PR
7. #1870 Render leisure=fitness_station (+3) - undecided

Next 9 issues have 2 up votes.

**Comment by andrewharvey** [comment]
https://mapbox.github.io/top-issues/#!gravitystorm/openstreetmap-carto is a good way to see what's got the most reactions.

**Comment by Tomasz-W** [comment]
This ticket was more like an information for all users, not an actual issue (there is no other methods to give statements like this, so I fully understant it). But is it still needful for anybody to be open?

**Comment by kocio-pl** [comment]
I guess we might close it. Reactions may help to decide, but all the top issues are just hard to resolve.

**Comment by matthijsmelissen** [comment]
Closing per @Tomasz-W.
