### ISSUE TITLE
Render landuse=religious

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#2697]
Although being discussed in various places (#771, #1206, #2087, etc) it appears to me that there is no standalone issue for rendering ```landuse=religious```.

We know it is seen controversial by some participants here, however since #771 (1.6k uses in 2014) it has grown to 11k uses now. 

My proposal is still a gray tone, slightly darker than residential.

**Comment by kocio-pl** [comment]
Could you be more specific with this color? It makes further discussion easier, since I can make test rendering.

**Comment by pnorman** [comment]
What other colours would this be near? Power stuff comes to mind
