### ISSUE TITLE
Add rendering for amenity=parking_entrance

### ISSUE THREAD

**Issue by scaidermern** [gravitystorm/openstreetmap-carto#270]
`amenity=parking_entrance` represents an alternative to `amenity=parking` for _underground_ or _multi storey_ parking facilities. Each entrance is mapped separately using the `parking_entrance` value and all of them are added to a _site_ relation.

For the start I suggest to render all `amenity=parking_entrance` nodes same way as `amenity=parking`. This involves just simple tag parsing without any relation and can be improved later.

**Comment by matkoniecz** [comment]
Is it necessary to check entrance key as it is done by #517 (with rendering only for entrance = main and entrance = yes)?

**Comment by jojo4u** [comment]
Taginfo does not list entrance=* as used together with amenity=parking_entrance (https://taginfo.openstreetmap.org/tags/amenity=parking_entrance#combinations)
The documentation says "If appropriate, the tag can be combined with entrance=*." which is not very helpful (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_entrance). 
IMHO checking is not needed.

**Comment by HolgerJeromin** [comment]
This would be very nice and easy. 
Most `amenity=parking`, `parking=underground` i tagged in the past should be better `parking_entrance` :-)

**Comment by kocio-pl** [comment]
How should it be rendered? What about this proposed icon:

https://wiki.openstreetmap.org/wiki/File:Amenity_parking_entrance.svg

Maybe some variant with an arrow, like in [entrance.10.svg](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/entrance.10.svg)?

**Comment by kocio-pl** [comment]
My proposition for underground parking entrance (and not to render others, because it's easy to see where they lead to):
1) ![parking-entrance-19](https://user-images.githubusercontent.com/5439713/30831203-e818c22e-a246-11e7-87eb-748a258c9eb2.png)

**Comment by jragusa** [comment]
I didn't notice the PR. Next time I will better read the thread. Sorry for the disturbance
