### ISSUE TITLE
Render non-building shop=mall like landuse=retail

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#2702]
Based on discussion in #2700 we could consider rendering shop=mall like landuse=retail in case it is used on features without a building tag and has no landuse tag.  This would essentially affect malls that contain outdoor areas (which is not uncommon in countries with appropriate climate).

It would improve mapper feedback because you would see the mall as mapped independent of labels meaning there would be feedback on accuracy of the geometry.

This would probably only affect about 10 percent of the malls currently mapped - others have a building or a landuse tag.

**Comment by kocio-pl** [comment]
Sounds reasonable to me when talking about area with this tag.

**Comment by HolgerJeromin** [comment]
Some mapper will drop tagging landuse.
Is that a good thing?

**Comment by polarbearing** [comment]
As said in #2700, rendering the landuse should be sufficient.

**Comment by dieterdreist** [comment]
sent from a phone

> On 24. Jul 2017, at 00:07, Holger Jeromin <notifications@github.com> wrote:
> 
> Some mapper will drop tagging landuse.
> Is that a good thing?


landuse here is kind of superfluous anyway, a shopping mall implies retail landuse

**Comment by matkoniecz** [comment]
I would expect such shop=mall to be part of landuse=retail. Is there an example of correctly mapped place, with mapped landuse that would benefit from this change?

**Comment by imagico** [comment]
Of the ~36k ways with shop=mall about 23k have a building tag and about 1.5k have a landuse=retail tag.  

A few examples of such cases:

https://www.openstreetmap.org/way/279460081
https://www.openstreetmap.org/way/363949116
https://www.openstreetmap.org/way/100853666
https://www.openstreetmap.org/way/24516528
https://www.openstreetmap.org/way/24690224
https://www.openstreetmap.org/way/179229712
https://www.openstreetmap.org/way/68674783

These are just random examples - and as said in the initial comment global distribution of such cases is quite strongly tied to climate obviously.

Prophylactically: Please don't start a tagging discussion out of this here - any discussion on what is good and bad mapping in this context belongs in other places.

**Comment by Tomasz-W** [comment]
Did somebody ask about proper using of `shop=mall` on Tagging list?

**Comment by jeisenbe** [comment]
I'd like to submit a PR to fix this issue. The simplest option is to render `shop=mall` with the same color fill and outline as `landuse=retail` and `amenity=marketplace`. 

The other option is to use only an outline. This is the solution that was used for `man_made_works`, since it was agreed that these areas should also be tagged landuse=industrial (or be included within a large industrial landuse area). The wiki page for shop=mall mentions using landuse=retail https://wiki.openstreetmap.org/wiki/Tag:shop=mall

Most shop=mall are also tagged as a building. Rarely there are underground malls; these probably should not be rendered with a fill (or even an outline?) There are a small number that are mapped as an area around the whole mall area and lack landuse=retail; these will be affected by the change. Taginfo isn't quite right because most of the retail areas are mapped as separate features: https://taginfo.openstreetmap.org/tags/?key=shop&value=mall#combinations

In that case, `amenity=marketplace` could also be changed to only have an outline. However, the wiki page does not mention adding landuse=retail so we could also consider this to be implied: https://wiki.openstreetmap.org/wiki/Tag:amenity=marketplace

Thoughts on fill vs outline, and if location=underground should be excluded from the outline / fill rendering? 
And should the text label be shown for shop=mall with location underground?

**Comment by jeisenbe** [comment]
Diamond Run Mall, Vermont. https://www.openstreetmap.org/#map=18/43.58108/-72.96442

The main building is tagged shop=mall but the whole area including parking lots and service roads is also mapped as shop=mall without landuse.
 
**Rendering without fill or outline** (with PR #3760 to restore the text labels)
z17
![z17-diamond-run-mall-fixed](https://user-images.githubusercontent.com/42757252/56552065-0c401600-65c5-11e9-9c44-6628adec8142.png)

**Add outline only (z16 and higher)** - same outline as used on landuse=retail, but without fill
z17
![z17-diamond-run-outline](https://user-images.githubusercontent.com/42757252/56552998-ecf6b800-65c7-11e9-97ef-c69f03a8d9be.png)

z16
![z16-diamond-run-outline](https://user-images.githubusercontent.com/42757252/56553028-00a21e80-65c8-11e9-99f4-4126228504ef.png)

z15
![z15-diamond-run-mall-outline](https://user-images.githubusercontent.com/42757252/56553007-f2540280-65c7-11e9-9cf2-f16911b0d63c.png)

**Add fill as well**
z17
![z17-diamond-run-mall-fill](https://user-images.githubusercontent.com/42757252/56553059-19123900-65c8-11e9-8486-4fb7e8f744f2.png)

z15
![z15-diamond-run-mall-fill](https://user-images.githubusercontent.com/42757252/56553061-1ca5c000-65c8-11e9-9676-7b2f84cda061.png)

**Comment by jeisenbe** [comment]
The one issue is underground malls. Usually these should be tagged `location=underground` but I've also found some tagged `underground=yes` in Singapore, where there are a number of these features. But `underground=yes` is a rare tag (<700 times), so I think we would only need to check for location=underground, which is well established (>66,000 uses).

# Singapore, Raffle's Place

## Label only rendering
(similar to current rendering and if location=underground is excluded)
z16 
![z16-no-fill-underground](https://user-images.githubusercontent.com/42757252/56556288-92af2480-65d2-11e9-8e7b-ce328e7b2a81.png)

z18 - (text label is blocked by amenity icons)
![z18-no-underground-malls](https://user-images.githubusercontent.com/42757252/56556300-9f337d00-65d2-11e9-88e3-a98acf8a54c5.png)

## With retail-color fill
z16 - just visible (remember, this zoom level in Singapore is similar to z15 in northern Europe)
![z16-singapore-downtown-malls-after](https://user-images.githubusercontent.com/42757252/56556332-b4a8a700-65d2-11e9-94f9-d1e0487fcca3.png)

z18
![z18-marina-bay-mall-underground](https://user-images.githubusercontent.com/42757252/56556389-e15cbe80-65d2-11e9-84c8-20aa1ae5e0ca.png)

z19
![z19-marina-bay-link-mall-after-underground](https://user-images.githubusercontent.com/42757252/56556397-e6ba0900-65d2-11e9-9a17-13d5f18edf5f.png)

## With outline only
z18
![z18-mall-underground-outline-only](https://user-images.githubusercontent.com/42757252/56556420-f46f8e80-65d2-11e9-90aa-26796fed8d4b.png)

## Thicker double-outline
- thin line in `@retail-line` color on top of thicker 2 pixel line offset toward polygon center in `@retail` fill color

![z18-underground-mall-retail-double-outline](https://user-images.githubusercontent.com/42757252/56556442-018c7d80-65d3-11e9-937d-1c0fedc6b5a6.png)

# Singapore, Downtown
https://www.openstreetmap.org/#map=18/1.29233/103.85458

## Text labels only
z17
![z17-citylink-label-only](https://user-images.githubusercontent.com/42757252/56556531-37c9fd00-65d3-11e9-988d-60108d49355e.png)

z19
![z19-underground-citylink](https://user-images.githubusercontent.com/42757252/56556539-3c8eb100-65d3-11e9-8788-ac195fe73ff8.png)

## Fill color
z18
![z18-citylink-fill](https://user-images.githubusercontent.com/42757252/56556566-4adccd00-65d3-11e9-8783-d893750262a3.png)

z19
![z19-citylink-fill](https://user-images.githubusercontent.com/42757252/56556581-529c7180-65d3-11e9-97a7-993f5d4df730.png)

## Outline (double)
z18
![z18-citylink-outline](https://user-images.githubusercontent.com/42757252/56556610-621bba80-65d3-11e9-91c1-f3c5305644f2.png)
z19
![z19-citylink-outline](https://user-images.githubusercontent.com/42757252/56556623-6a73f580-65d3-11e9-938f-72718d6ded4f.png)

Perhaps it's best not to these underground features in the landcover layer?

**Comment by dieterdreist** [comment]
I would prefer a fill for all malls, regardless of someone having added retail landuse or not.

**Comment by jeisenbe** [comment]
The fill certainly looks better than the outline. A doubled outline looks ok for areas where there is no other landcover, and does show the extent of the geometry in the database:

### Double outline

Diamond Run Mall, Vermont. https://www.openstreetmap.org/#map=18/43.58108/-72.96442
z16 
![z16-diamond-run-double-outline](https://user-images.githubusercontent.com/42757252/56580048-a5464f80-660c-11e9-8710-1f003763dd57.png)
z17
![z17-diamond-run-double-line](https://user-images.githubusercontent.com/42757252/56580071-b5f6c580-660c-11e9-9d5a-88f74e07c3b9.png)

But it is hard to see when parking lots, grass area or other landcovers are mapped:
Carrefore Zahira https://www.openstreetmap.org/#map=17/37.89343/-4.74746
![z17-zahira-outline-double](https://user-images.githubusercontent.com/42757252/56580175-f22a2600-660c-11e9-9bf0-ae3af7632492.png)

Sicilia Outlet Village https://www.openstreetmap.org/#map=17/37.573296/14.480978
![z17-sicilia-double-outline](https://user-images.githubusercontent.com/42757252/56580297-37e6ee80-660d-11e9-97aa-7069bba6f2dc.png)

### Fill color
This looks better in most cases where it makes a difference:
Diamond Run z17 - see above also
![z17-diamond-run-mall-fill](https://user-images.githubusercontent.com/42757252/56553059-19123900-65c8-11e9-8486-4fb7e8f744f2.png)

Zahira z17
![z17-zahira-after-fill](https://user-images.githubusercontent.com/42757252/56580373-606ee880-660d-11e9-9ce4-497dfb8a3168.png)

Sicilia z16
![z16-sicilia-outlet-village-fill](https://user-images.githubusercontent.com/42757252/56580433-7b415d00-660d-11e9-9410-3c4ebbdda315.png)

z17
![z17-sicilia-fill](https://user-images.githubusercontent.com/42757252/56580405-7086c800-660d-11e9-9ba1-48f979d52b25.png)

**Comment by jeisenbe** [comment]
I'm going with the fill, and not rendering underground malls for now.
