### ISSUE TITLE
Render cross in the centroid of christian churches

### ISSUE THREAD

**Issue by LucFreitas** [gravitystorm/openstreetmap-carto#2709]
The cross and name appear out of shape.

Example "Santadart":
![1](https://user-images.githubusercontent.com/19976610/28620238-79285dc8-71e2-11e7-899d-f5b0501a1049.PNG)

HOT:
![2](https://user-images.githubusercontent.com/19976610/28620239-792902e6-71e2-11e7-9a44-9d65a9fd5a45.PNG)

http://www.openstreetmap.org/way/49840192

**Comment by polarbearing** [comment]
related to #2457 ? Though there, the P is in the centre of an oddly shaped polygon, while here at least the centre of the text label is inside.

**Comment by HolgerJeromin** [comment]
Duplicate of  #2511 which was closed as a duplicate,  too. 
Someone should collect the current issues and report them to the mapnik repository

**Comment by HolgerJeromin** [comment]
Thanks pnorman!
