### ISSUE TITLE
Add rendering for office=government or office=administrative

### ISSUE THREAD

**Issue by a-peter** [gravitystorm/openstreetmap-carto#271]
It's quite common that big buildings used by the government are having several administrative department. It's not really good to tag all the departments within the name of the complete building like "name=department one and department two ...".

It would be nice if office=government and office=administrative would be rendered. In this case multiple points within one building could be tagged like this and the result would be rendered.

**Comment by abdeldjalil09** [comment]
Hi, 
We should start rendering "office=government" because it's very important tag (51 951
 uses) , icon is here:
https://github.com/gmgeo/osmic/blob/master/administration/government-14.svg

**Comment by abdeldjalil09** [comment]
http://taginfo.openstreetmap.org/tags/office=government --> 53 014 uses

**Comment by kvlahromei** [comment]
http://taginfo.openstreetmap.org/tags/office=government --> 78 126 uses

As JOSM recommends to replace amenity=public_building (which is rendered), I recommend to add both office keys to the style, too.

**Comment by math1985** [comment]
We don't render public_building in this style.

**Comment by polarbearing** [comment]
Rendering should consider the cases: 
- node (within a building or without a mapped building)
- building outline

It should also have in mind that at some point we would like to render campuses/landuse of governmental/administrative areas, #2985.

**Comment by Tomasz-W** [comment]
Is blue dot enough, or do we want some special rendering here (black dot or separate icon) ? What do you guys think?
