### ISSUE TITLE
White mid-zoom roads do not work on some backgrounds

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2731]
With the changes in 5fd79b7bfad1d895c543e52838c65657fcd9fe1a, there is a huge difference in how the roads look between different areas

![image](https://user-images.githubusercontent.com/1190866/29053168-4c864f08-7ba3-11e7-89cf-99495b11c5a1.png)

In Surrey, the roads are readable with the residential background. In Langley, they're not, with most of them against our base colour.

**Comment by imagico** [comment]
I noticed the same when testing the bright roads without landcover fading and found that adding a darker halo with `line-comp-op: darken` to the white roads helps.  This will however probably look fairly heavy with the faded landcovers emphasizing roads even more and adds quite a bit of visual noise especially if the roads are not all strait like in the example you showed.  I am not even sure i like it without landcover fading.

**Comment by kocio-pl** [comment]
I'm not sure if that's a bad thing or even regression. Midzoom changes are about _intentionally_ hiding some details (and at this zoom level I wouldn't like them to be more visible):

> [Unimportant roads are now white rather than gray.](https://github.com/gravitystorm/openstreetmap-carto/pull/2654#issue-233370622)

**Comment by pnorman** [comment]
> I'm not sure if that's a bad thing or even regression. Midzoom changes are about intentionally hiding some details (and at this zoom level I wouldn't like them to be more visible):

If the visibility was consistent I'd see it as okay, but it's not consistent.

**Comment by math1985** [comment]
For what it's worth, I agree with @pnorman that there is an issue here.

**Comment by kocio-pl** [comment]
What do you plan to do with it? Do you want to make any changes before v4.2.0?

**Comment by matkoniecz** [comment]
I also agree that issue exists.

**Comment by math1985** [comment]
> Do you want to make any changes before v4.2.0?

I'm quite busy with other stuff at the moment, so unfortunately I won't have time to work on it the next couple of weeks. I'll leave it to you how to proceed.

**Comment by kocio-pl** [comment]
I would probably revert this particular change as the safest choice for now. I'm pretty sure we will tune midzoom in the nearest future anyway, because its biggest visual change from the new road system introduction 2 years ago, so there will be good opportunity to think what we could do with these roads.

**Comment by imagico** [comment]
In case someone wants to try it - the darker halo with `comp-op: darken` can be found implemented in

https://github.com/imagico/openstreetmap-carto/commit/8b82a8d78e79a8f30c045a77ff1535df011b462d

I have not tried it with the faded landcovers or in urban areas with largely unmapped landcover.
