### ISSUE TITLE
Ignore unknown "waterway" values?

### ISSUE THREAD

**Issue by RicoZ-OSM** [gravitystorm/openstreetmap-carto#2733]
I am experimenting with waterway=riverbed ( https://wiki.openstreetmap.org/wiki/User:RicoZ/waterway%3Driverbed ) and noticed that for example that a small patch of natural=scrub entirely within the area covered by waterway=riverbed is not rendered.

For my purposes it would be better if it was rendered and I don't see why unknown waterway values should cause such mysterious behaviour. Either a feature is fully supported or not at all - anything inbetween leads to strange results.

**Comment by kocio-pl** [comment]
Could you give a link to this location? 

It can be for example a popular problem with river tagging which started to be visible with v4.0.0 - if there's a relation and water is tagged not only in the relation itself, but also on the outer way. It should be only in relation, but it was just rendering nice until recently.

**Comment by pnorman** [comment]
Check if the object [is an area or not](https://github.com/gravitystorm/openstreetmap-carto/blob/master/openstreetmap-carto.lua#L386-L406). Without an example, it's hard to say anything for sure.

**Comment by rgh36167** [comment]
Yes I am aware of the bug you are mentioning, it is not this one.

The scrub I want rendered
http://www.openstreetmap.org/way/511489717
 is within
http://www.openstreetmap.org/way/511489715#map=15/46.2907/8.6386&layers=T

Yes, waterway=riverbed is to be interpreted as area and of course it is not known to Carto.

**Comment by sommerluk** [comment]
> The scrub I want rendered
http://www.openstreetmap.org/way/511489717

This scrub _is_ rendered.

Note that the second URL (for the riverbed) points to the transport layer which is independent from this github repository here.

**Comment by rgh36167** [comment]
Sorry, totally stupid from me. Apparently I should delete cookies more often?
