### ISSUE TITLE
Explicit nulls on feature statements

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2735]
Right now our feature statements are like
```sql
COALESCE(
  'aeroway_' || CASE WHEN aeroway IN ('helipad', 'aerodrome') THEN aeroway ELSE NULL END,
  'power_' || CASE WHEN power IN ('generator') THEN power ELSE NULL END,
  ...
) AS feature
```

The explict `ELSE NULL` does nothing, as a case statement where none of the conditions are true and there is no else clause is already null.

Does this help people understand the statements? If I was writing for myself, I wouldn't add it, but I write a lot of SQL.

Either way, we should document it in the code standards.

**Comment by math1985** [comment]
I would drop it - the construction is tough to understand either way :)

**Comment by kocio-pl** [comment]
For me it would be important to have more comments in the code and general documentation/explanations about things we use (like "feature" or layers order). I understand that this could be a lot of work and sometimes just asking questions is enough, but it's just what I would like to have as a non-programmer.

**Comment by jeisenbe** [comment]
It would be nice to drop this. I don't write any SQL outside of this project, and "ELSE NULL END" is quite hard to understand, even as a native English speaker.
