### ISSUE TITLE
Quarry pattern is not periodic any more

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#2737]
http://www.openstreetmap.org/#map=19/48.07891/7.70540

due to #2683, likely the same problem as in #2685.

**Comment by kocio-pl** [comment]
Thanks for noticing! I think we can probably safely revert this PR. Fixing problems with Mapnik rendering of SVG would be much better, of course.

**Comment by kocio-pl** [comment]
I've just found this (https://github.com/gravitystorm/openstreetmap-carto/issues/937#issue-42473750):
> Without a fixed metatile size, this implies both pattern dimensions should be a multiple of two, and at most 256.

This SVG is 512 px. Could it be a problem here? Why 256 should be max size for patterns?

**Comment by sommerluk** [comment]
I suppose this can be easily solved by re-creating the pattern with the most recent version of jsdotpattern, that (since last sunday) also adds a dummy geometry when sanitizing, right?

**Comment by kocio-pl** [comment]
I was not aware of the change, but it works. I can merge fix, but there's still [a question about all 512 px patterns](https://github.com/gravitystorm/openstreetmap-carto/issues/937#issuecomment-322666309).

**Comment by sommerluk** [comment]
Anyway: As the current pattern is a regular pattern I suppose that’s not a big deal. Or course, it will round the distance to something that’s a divisor of 256, so the symbal distance might be slightly bigger or smaller, but likely < 10% difference.
