### ISSUE TITLE
Identify big areas

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2742]
It would be good to have a list of biggest areas already tagged (in the world and per continents) and some visualizations for each type of natural/landuse areas to show where they are located. Another thing would be to find out what kind of big objects are currently not even tagged - maybe natural/landuse system is missing something important.

Rationale: 

When looking how to improve [medium](https://github.com/gravitystorm/openstreetmap-carto/issues/2194) and [low zoom](https://github.com/gravitystorm/openstreetmap-carto/issues/2688) levels, I was trying to identify big areas that could be shown there. With some clues from other generalized maps I was able to notice that farmlands and sand can be shown earlier, because big enough areas are tagged. However checking it manually is tedious and Overpass server is not able to show for example `natural=*` for the whole world, nor even single continent.

**Comment by math1985** [comment]
Sorry, I'm not sure what you mean with this issue?

**Comment by kocio-pl** [comment]
I mean a database tool/service (or just output) with such data. Also a list of potentially interesting big objects which are not in database (for example "Australian deserts").

**Comment by kocio-pl** [comment]
I guess this general list is enough for now:

https://wiki.openstreetmap.org/wiki/User:Kocio/low_zoom_rework
