### ISSUE TITLE
Shape Plugin error

### ISSUE THREAD

**Issue by arsenik** [gravitystorm/openstreetmap-carto#2745]
I am not sure this is linked to the project, please let me know: 

After cloning the project
```
scripts/get-shapefiles.py (works fine)
carto -v   (carto 0.18.2 (Carto map stylesheet compiler))
carto project.mml > mapnik.xml 
sudo -u pdsmap renderd -f -c /usr/local/etc/renderd.conf
renderd[27650]: An error occurred while loading the map layer 'default': Shape Plugin: missing <file> parameter  encountered during parsing of layer 'world' in Layer at line 268 of '/home/julien/src/openstreetmap-carto/mapnik.xml'renderd
```

**Comment by kocio-pl** [comment]
I guess this might be a problem with [dependencies](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#dependencies). What version of osm-carto, CartoCSS and Mapnik are you using?

**Comment by arsenik** [comment]
carto 0.18.2
osm-carto master branch

Mapnik 3.X ( I am not sure how to get this version)
I have multiple mapnik plugin dir, I followed these instructions https://github.com/mapnik/mapnik/wiki/UbuntuInstallation#ubuntu-1604
and probably another... so I am not sure.

If I use this plugin dir /usr/local/lib/mapnik/input I get the error I first shown you.

If I use /usr/lib/mapnik/3.0/input, I get this error :

```
renderd[32032]: An error occurred while loading the map layer 'default': Postgis Plugin: ERROR:  relation "planet_osm_polygon" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM planet_osm_polygon WHERE ...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM planet_osm_polygon WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'landcover-low-zoom' in Layer at line 561 of '/home/julien/src/openstreetmap-carto/mapnik.xml'
renderd[32032]: An error occurred while loading the map layer 'default': Postgis Plugin: ERROR:  relation "planet_osm_polygon" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM planet_osm_polygon WHERE ...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM planet_osm_polygon WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'landcover-low-zoom' in Layer at line 561 of '/home/julien/src/openstreetmap-carto/mapnik.xml'
```

**Comment by kocio-pl** [comment]
I'm not sure what could it be. You can also test it with Kosmtik to see, if the problem would be the same, or ask at https://github.com/openstreetmap/mod_tile/issues.

**Comment by arsenik** [comment]
I want to have a map only of france, therefore I only loaded this file http://download.geofabrik.de/europe/france-latest.osm.pbf , could that be why I am missing something?

**Comment by arsenik** [comment]
I will ask around and close this issue if I find.

**Comment by arsenik** [comment]
osm2pgsql did not fnished correctly. I went with smaller region and it worked.
