### ISSUE TITLE
List of surface=* is not identical with wiki for “unpaved”

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2753]
Our SQL querry for “unpaved” road surface is not identical with the wiki:

- The three values `gravel_turf`, `ice` and `snow` are in the wiki, but not in our SQL querry.
- The value `clay `is in our SQL querry, but not in the wiki list (in the wiki, it’s in the “special” list, not in the “unpaved” list).

Is this intentionally or does the code need an update?

**Comment by matkoniecz** [comment]
Intentional.

`gravel_turf`, `ice` and `snow` according to my check was not appearing on correctly mapped linear highway=* (both at time of writing the code).

`clay` was appearing on roads that seemed to be correctly mapped linear highway=* and is a value that may appear as result of a good edit.

In case that this changed update would be a good idea.

**Comment by matkoniecz** [comment]
@sommerluk Do you think that it should be changed or documented?

**Comment by sommerluk** [comment]
I’ve taken a look at overpass-turbo at gravel_turf, ice and snow, and (though I don’t have much experience with this road type) is looks okay for me. Therefor, and as a mapping incentive, I would propose to treat it like “unpaved”. “clay” could get documentated in our code; maybe it could be changed in the wiki to be in the “unpaved” section…

**Comment by sommerluk** [comment]
By the way: The list appears various times in different SQL querries. Might it make sense to calculate it in the Lua transformation to avoid duplicate code in project.mml after the next database reload? (Just asking, I do not know anything at all about Lua…)

**Comment by matkoniecz** [comment]
Deduplication is always good if it is not causing anything terrible. But I also do not know anything at all about Lua, so...
