### ISSUE TITLE
kosmtik_1  | Mapnik LOG> 2017-08-15 22:19:58:  could not create BreakIterator: U_MISSING_RESOURCE_ERROR

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#2755]
If I run the stylesheet with Docker, I get the following errors:

> kosmtik_1  | Mapnik LOG> 2017-08-15 22:19:58:  could not create BreakIterator: U_MISSING_RESOURCE_ERROR

Also the labels are no longer wrapped over separate lines.

Is anybody else running into the same problem?

**Comment by kocio-pl** [comment]
Yes, I see the same problem.

**Comment by nebulon42** [comment]
I get this error occasionally, but have never seen any other effects associated with it.

**Comment by math1985** [comment]
> I get this error occasionally, but have never seen any other effects associated with it.

Are you sure long lines nicely wrap in two (or more) parts for you?

**Comment by kocio-pl** [comment]
Updating Kosmtik to 0.0.16 and installing libicu57 didn't help with this bug.

**Comment by kocio-pl** [comment]
I've tested it changing base distro to `ubuntu:latest` and the bug was gone. Looks like `libicu55` is needed for Kosmtik from npm repo, but this library is not available in `debian:stretch` - it was replaced by `libicu57`. Bit more of a testing is needed just to make sure, but basically we can probably:
- switch Dockerfile to Ubuntu
- ask the Kosmtik team to link with a newer ICU version
- try to use the source

What do you think?

**Comment by nebulon42** [comment]
As I said elsewhere this problem is not related to Kosmtik, it is a Mapnik problem. Great that you found a probable solution, but there are no changes Kosmtik can do besides using a newer version of Mapnik as this is one of the few libraries which uses native code.

**Comment by kocio-pl** [comment]
Sorry for being too vague. Here I think of Kosmtik as a functional whole (with all the modules), not the code alone. 

I don't know npm - is there a way to install Kosmtik from npm repo and force building Mapnik with local ICU version? Or maybe Mapnik npm package should be upgraded? It will probably cause problems with new Debian anyway.

**Comment by math1985** [comment]
I cannot reproduce this issue anymore, it seems to work fine with Debian now.

@kocio-pl Just to be sure you sure switching to ubuntu:latest was the solution, and not something else?

**Comment by kocio-pl** [comment]
This time rebuilding with Debian from the ground up failed when trying to compile Mapnik:

```
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.5.14 and node@6.11.3 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/6.11.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/kosmtik/node_modules/mapnik/.node-gyp"
/bin/sh: 1: mapnik-config: not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
```

**Comment by kocio-pl** [comment]
I have tested with Debian base and it works - something like:

docker-compose build --pull --no-cache kosmtik

So this was probably just something broken in Debian at that moment.

**Comment by math1985** [comment]
I encountered this bug (but I could not reproduce it) with the ubuntu image. So probably there is something else at play.
