### ISSUE TITLE
Artifacts in plant_nursery pattern

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2771]
Follow up to https://github.com/gravitystorm/openstreetmap-carto/pull/2759#issuecomment-323471187.

Current plant_nursery pattern is not regular - there are subtle artifacts (some rows and columns are bit wider):
<img width="194" alt="screen shot 2017-08-19 at 00 04 29" src="https://user-images.githubusercontent.com/5251909/29479379-17a837c4-8472-11e7-97ac-c70e07e49114.png">

It's visible in pattern generator with current settings:

 http://www.imagico.de/map/jsdotpattern.php#x,128,jdp32360;gv,6,32,32;rd,1,0,0,pixel,0.125,4,4,0,jdp23814,749d6c,aedea3

Changing distance from 6 to 8 seems to be enough to get rid of this effect:

http://www.imagico.de/map/jsdotpattern.php#x,128,jdp32360;gv,8,32,32;rd,1,0,0,pixel,0.125,4,4,0,jdp23814,749d6c,aedea3

The question is if it would be safe to produce SVG version or just recreate PNG image with a fixed pattern?

**Comment by sommerluk** [comment]
> some rows and columns are bit wider

This is because 6 (the distance) is not a divisor 128 (the pattern size), so obviously using 8 as distance fixes this. This is _independent_ of #2750 and applies to both SVG and PNG.

As rendering is pixel-aligned and the symbol _is_ a simple pixel, this pattern might likely work as SVG.

**Comment by kocio-pl** [comment]
Makes sense now... :smile: 

PNG (distance 6)->SVG (distance 8), z19 (click to see full size images)

Before 
![yjqe4jcx](https://user-images.githubusercontent.com/5439713/29632631-db7d680c-8843-11e7-9182-2beeb2fa3faa.png)
After
![yc nl7sc](https://user-images.githubusercontent.com/5439713/29632645-e37fbdb6-8843-11e7-86bf-65114807f4cf.png)

**Comment by kocio-pl** [comment]
Well, no SVG this time, since it also uses gamma (like an orchard):
https://github.com/gravitystorm/openstreetmap-carto/blob/dbc633a0b2c55124d36eb5f4eeaae71e955baa7a/landcover.mss#L161-L173

**Comment by kocio-pl** [comment]
Closing this as a small problem which I'm not going to investigate deeper at the moment. It can be reopened if needed, of course.
