### ISSUE TITLE
landuse=residential color change

### ISSUE THREAD

**Issue by Vort** [gravitystorm/openstreetmap-carto#2777]
Hello.

With new style, residential color variation between zoom levels looks arbitrary.
It becomes darker and brighter several times as you zoom in.

z8, z9 - 221 (bright)
z10 - 212 (dark)
z11 - 216 (bright)
z12 - 211 (dark)
z13 - 223 (bright)

And at zoom=12 it looks just bad in my opinion:
(residential areas receives too much emphasis)
![z12_bad](https://user-images.githubusercontent.com/1242858/29739586-c0ec374a-8a49-11e7-8434-1b5f62ca4534.png)

Before-after comparison:
![z12_change](https://user-images.githubusercontent.com/1242858/29739587-cabef668-8a49-11e7-9b31-1a9fa00c84f4.png)

**Comment by math1985** [comment]
This is becajse not all of the tiles have been re-rendered yet. Wait a day or so and it should be better.

**Comment by Vort** [comment]
@math1985, no, all colors was checked for updated tiles.
My last screenshot was intentionally half-updated to show the differences.
Please reopen the issue.

**Comment by math1985** [comment]
Reopening.

**Comment by mboeringa** [comment]
> And at zoom=12 it looks just bad in my opinion:

Actually, I think part of the problem is that the darker colour now more clearly reveals where there are missing residential polygons. In the first image you posted, there are clearly large missing sections, causing a "broken up" look of the residential area, which I think is part of what causes the undesirable look.

However, that is not an issue of the colour change per se, but may actually be an incentive to start mapping them!

Especially in well mapped countries like e.g. the Netherlands, where almost the total surface area is somehow tagged, including residential areas, the colour doesn't look that bad... E.g.:

http://www.openstreetmap.org/#map=12/52.3504/4.7766

(I realize that the "ideal" situation is unlikely in much larger countries due to much less human influence and maybe no sensible natural tags to cover large swaths of land)

**Comment by Vort** [comment]
That color at z12 also "hides" residential roads.

**Comment by mboeringa** [comment]
> That color at z12 also "hides" residential roads.

Although the colour could potentially be maybe a bit lighter, at Z12 and lower zoom levels, the fact that it partially "hides" residential roads is for the most part a positive thing. At Z12, residential roads really cannot be displayed without causing a huge amount of clutter or high frequency noise in the image, especially in (historic) cities and countries with very dense build up.

Only at Z13 does the display of residential roads really become palatable...

**Comment by boothym** [comment]
Hard to tell the difference between industrial and residential areas at z11, one or the other needs to be fixed.

**Comment by kocio-pl** [comment]
@boothym It's on purpose - they are rendered the same until z13+:

https://github.com/gravitystorm/openstreetmap-carto/blob/3c7a2d7a7a33d512dbaa88b6b1bc7596bb4fb08b/landcover.mss#L359-L362

**Comment by boothym** [comment]
I realise that, but surely they should be different so you can tell them apart? Can't you make industrial more pink/purple like z13+?

**Comment by kocio-pl** [comment]
We try to hide the differences between some human landuses, because they are small compared to natural areas on midzoom. I think that only some big human-related areas (like forests, farmlands and military zones - possibly some others too) are worth showing here.

**Comment by boothym** [comment]
Sure, but there are some big industrial areas as well - for example: https://www.openstreetmap.org/#map=14/53.4699/-2.3257 - zoom out to z12 and it just becomes part of the big grey blob that is Manchester.

**Comment by kocio-pl** [comment]
It's still small compared to nature on midzoom. It's big on z14, not-so-big on z13 and on z12 it's just a tiny part of the screen, so for me it's good that it's not anything special on that zoom.

**Comment by matkoniecz** [comment]
> And at zoom=12 it looks just bad in my opinion:

Residential seems to become lighter at zooming to z13

For example at http://www.openstreetmap.org/#map=12/52.1863/20.8790

```
@built-up-upper-lowzoom: #c0c0c0;
(...)
@residential: #e0dfdf; // Lch(89,0,0)
(...)
[zoom >= 11] { polygon-fill: @built-up-upper-lowzoom; }
[zoom >= 13] { polygon-fill: @residential; }
```

is a relevant code, so at zooming in to z13 it becomes lighter.

I agree that it is really strong at z12, too strong in cities that I checked.

---

> It becomes darker and brighter several times as you zoom in.

@Vort Can you check this again? From testing and reading code seems that it is not happening.

**Comment by Vort** [comment]
@matkoniecz: here is the result of retest:

![carto_residential](https://user-images.githubusercontent.com/1242858/31858790-04cb3c86-b709-11e7-8243-7c4bea542446.png)

**Comment by matkoniecz** [comment]
It is likely to be a rediscovery of #1940

**Comment by Vort** [comment]
Can anyone make lossless tiles for checking?

**Comment by Vort** [comment]
@matkoniecz, I have found a place, where are too little colours used, so that 256 colour palette becomes semi-empty.
Result is still 216/211 for z11/z12.
If that's a result of quantization, then it is done wrong.

![tile_palette](https://user-images.githubusercontent.com/1242858/31862693-dd9af8bc-b74a-11e7-97a8-05e5bc5e36d5.png)

**Comment by kocio-pl** [comment]
I started to dislike z12 residential rendering and would like it to be like on z11. Anybody interested in testing it?

**Comment by matthijsmelissen** [comment]
I also noticed this independently. Residential on z12 should be lighter.

**Comment by boothym** [comment]
I notice landuse=railway and industrial on z11/12 are not the same - I'd like to suggest industrial is changed to match railway so that it retains its light purple colour and is different to residential.

**Comment by kocio-pl** [comment]
I would not change it. Typically railway are used for long, thin rail related landuses, so should be light to let the rails be visible, but industrial tend to be like other landuses and it indicates human activity and presence area, similar to residential in that respect (which is not true in general for railways).

**Comment by boothym** [comment]
Well you don't really see the railway landuse around rails on z12 because the area is too small. But I noticed the difference with a railway yard next to an industrial area: https://osm.org/go/evfhVRh--?m=

On z13+ railway and industrial are the same, but on z11-12 they are not. So one needs to change - I'd prefer it if industrial changed to match railway so that it is different to residential.

**Comment by kocio-pl** [comment]
> On z13+ railway and industrial are the same, but on z11-12 they are not. So one needs to change 

But why? They are different tags, so they can behave differently when the difference is important (midzoom), even when sometimes they are similar (high zoom) and they can look similar. I feel this is good when you are able to detect a meaning by visual differences.
