### ISSUE TITLE
Not showing Noto Sans font on Korean when not standard map

### ISSUE THREAD

**Issue by ryush00** [gravitystorm/openstreetmap-carto#2780]
I checked #2349.

![Standard Layer](https://user-images.githubusercontent.com/4997174/29751686-8abbc5b2-8b8b-11e7-89c3-fce1c5e7d397.png)
Standard layer uses Nono Sans. So it is well readable.

----

![Cycle Layer](https://user-images.githubusercontent.com/4997174/29751613-db2e9a7a-8b8a-11e7-9d1f-141ab33c9aa1.png)

![Transport Layer](https://user-images.githubusercontent.com/4997174/29751620-e4a95478-8b8a-11e7-9f4d-fc345d4bd454.png)

![Humanitarian layer ](https://user-images.githubusercontent.com/4997174/29751628-f48111f6-8b8a-11e7-9f54-54dc35ae073e.png)

But Cycle, Humanitarian, Transport layer doesn't use this font. It is really not-readable.

Is this a bug?

**Comment by math1985** [comment]
All layers are created by different (teams of) people. This issue tracker is only for the Standard layer.

For the Humanitarian layer, you can create an issue here: https://github.com/hotosm/HDM-CartoCSS

Cycle and Transport are created by @gravitystorm, you can get file bugs directly with him at andy@gravitystorm.co.uk  . I'm not sure if these are still actively developed though.

**Comment by pnorman** [comment]
Closing as not about this project.

**Comment by sommerluk** [comment]
@ryush00 There seems to be yet an issue for the HOT style that is tracking Noto support: https://github.com/hotosm/HDM-CartoCSS/issues/284

**Comment by gravitystorm** [comment]
> I'm not sure if these are still actively developed though.

They're definitely still actively developed! Bug reports are welcome at the email address above.
