### ISSUE TITLE
Golf course icon alignment and dot artifact

### ISSUE THREAD

**Issue by meased** [gravitystorm/openstreetmap-carto#2787]
Some (not all) golf course text and icons are not aligned. A black dot is where the icon should be, sometimes to the left, sometimes to the right. For example:

![golf_courses](https://user-images.githubusercontent.com/14190496/29883234-7ff1b4d6-8d64-11e7-8ca8-6ea957368398.png)

http://www.openstreetmap.org/#map=15/45.5950/-122.6478

**Comment by lakedistrictOSM** [comment]
leisure=miniature_golf and tourism=guest_house are also getting this black dot.
(zoom level 17 on screenshot)
![osmblacksquares](https://user-images.githubusercontent.com/20193716/29922299-edb576a4-8e4c-11e7-9dc8-7d1e36649aee.PNG)
