### ISSUE TITLE
extraneous zoom constraint in placenames.mss for placenames-small

### ISSUE THREAD

**Issue by stevenLAD** [gravitystorm/openstreetmap-carto#2793]
At line 332 in placenames.mss, the presentation is restricted to zoom levels 12-16. However within this conditional at line 342, there is another constraint for zoom levels >=11, which appears extraneous.

Please excuse if this is an error of understanding

**Comment by kocio-pl** [comment]
Thanks, it looks like a progression typo - it should be probably >=13 instead:

https://github.com/gravitystorm/openstreetmap-carto/blob/df45b20f2621b0aa6f34d31b01a086f22058a69c/placenames.mss#L330-L370

**Comment by stevenLAD** [comment]
Agreed - makes sense
