### ISSUE TITLE
Direction of development 

### ISSUE THREAD

**Issue by dhdl** [gravitystorm/openstreetmap-carto#2812]
Some notes on the [midzoom](https://github.com/gravitystorm/openstreetmap-carto/pull/2654) changes:

I appreciate change and I'm even open to change colours from time to time, but the recent changes have driven the general style even more in the direction of the "overlay styles" like osm-bright.
The paler colours are clearly a loss of distinguishability. The point is, that we are not lacking bright and information-less styles: Besides osm-bright there are dozens from Mapbox, Mapzen, Wikimedia Maps, etc..

IMHO we should focus on a feature-rich, color-rich style meant for the mappers and individual users. If you need an overlay style, you have the choice – but for mapping feedback there are basically no real alternatives. The French and German style are far less often rerendered.

Additionally I think it wasn't right, to break coloring consistency between zoom levels.

**Comment by kocio-pl** [comment]
There is a disagreement if that was good or bad. 

I'm happy with that change - less intensive color for backgrounds leads to better distinguishability of linear and point features, which were obscured before, yet the background is still not uniform and can be recognized with a bit more effort, so I see it as better balance between areas vs. lines+points. 

I didn't like the fact that forest/wood were the most important thing visually - the small spots worked like a typical camouflage effectively.

**Comment by dieterdreist** [comment]
completely agree with dhdl, we don't need yet another pale style. Fading colors across zoom levels is not very intuitive either. Higher contrast improves leggibility.


sent from a phone

**Comment by kocio-pl** [comment]
Looks like some landuses on some zoom levels are the only thing you care for - what about other elements you don't mention? I try to see the whole map on all zoom levels.

Higher contrast for background improves legibility of a background but decreases legibility of the foreground, so your statement is oversimplification. Water color (on all zoom levels) and human-related areas (on some zoom levels) are now more intensive, so overall changes go both ways, not just "making map paler".

**Comment by math1985** [comment]
To be clear: making the map more suitable as an overlay map was not a consideration when designing the style. If the map is a better overlay map now, that is purely a side effect of our design decisions.

**Comment by kocio-pl** [comment]
I also see it this way. I see nothing bad in going in some directions if it helps resolving real problems - but this is not just one direction. Overlay maps show very limited set of features and their general brightness is designed as a general feature - osm-carto shows a lot of elements and brightening some of them on some zoom levels was needed to show some other elements more clearly.

**Comment by math1985** [comment]
@dhdl I'm happy to hear your point of view, however I don't think there's anything concrete now we can do (except reverting the change, which does not seem to have support). I'll therefore close this issue.

If you have any concrete proposals, feel free to create a new more specific issue (or even better, a PR).

You might also be interested in #1975.

**Comment by kocio-pl** [comment]
Interesting [comment](https://github.com/gravitystorm/openstreetmap-carto/issues/1863#issuecomment-144336848) from a previous similar issue: 

> When we started recolouring the map we had all kinds of different colours and no method to the jumble - trunk roads couldn't be seen in forests, sports centres were (are) more brightly coloured than points of interest, etc. So my idea was, and still is, to bring a rough order of precedence to the colouring, namely polygons < lines < icons and labels. Given the size of polygons compared to other features, it's natural for them to be less eye-catching, otherwise they dominate the map and it's really hard to find linear or point features among them.
