### ISSUE TITLE
Ford symbol is blurry

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#2822]
From https://github.com/gravitystorm/openstreetmap-carto/pull/2743#issuecomment-328388361

![image](https://user-images.githubusercontent.com/1190866/30255021-97b99914-9654-11e7-82ef-c1dcecfa98da.png)

I haven't investigated, but I bet it's not pixel aligned

**Comment by pnorman** [comment]
Yep, it's not pixel aligned. The top is a fairly easy fix, but the bottom needs more work because there's two wavy lines close to each other.

**Comment by kocio-pl** [comment]
@meased Would you like to fix also this icon?

**Comment by meased** [comment]
@kocio-pl Sure.
