### ISSUE TITLE
Import custom shape files

### ISSUE THREAD

**Issue by RandyHBH** [gravitystorm/openstreetmap-carto#2837]
I have a set of shepfiles for my region, downloaded from geofabrik, how can I import them? or I do not need them.
I'm using the Docker  installation guide.
Regards

**Comment by pnorman** [comment]
The [install instructions](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md) call for OSM-formatted data, not Geofabrik's shapefiles.

**Comment by RandyHBH** [comment]
lo siento si este no es el lugar para pedir, pero estoy tranquilo nuevo en esto. Usted quiere decir que los datos OSM en mi caso
> myregion.osm.pbf
es suficiente, no se necesita Shapefiles de Geofabrik, solo los descargados por el script python?

**Comment by kocio-pl** [comment]
Yes, that's all that is needed for rendering. Any additional data are downloaded automatically during start, if needed.
