### ISSUE TITLE
Townships in Michigan do not render

### ISSUE THREAD

**Issue by gappleto97** [gravitystorm/openstreetmap-carto#2844]
In Michigan there are two types of populated areas: cities and townships. They're of equal governmental importance, but convention has given them a different admin_level tag (8 and 7, respectively), so they are not being rendered.

It would be very nice if they were rendered, as they are a very useful part of any Michigan maps.

**Comment by matkoniecz** [comment]
Can you link an example object that is affected?

**Comment by maxerickson** [comment]
Presumably http://www.openstreetmap.org/way/510375703 and http://www.openstreetmap.org/way/510363557 

But I guess the issue there is that boundary ways aren't rendered, http://www.openstreetmap.org/relation/2682592 shows up fine.

**Comment by matkoniecz** [comment]
So it is new case of issue tracked at #713

**Comment by gappleto97** [comment]
@maxerickson, so should I just make the ones near me a relation? I think that's the way you're supposed to anyways, but I'm not sure if this would be considered "tagging for the renderer".

**Comment by matkoniecz** [comment]
Tagging for renderer means introducing false data or removing correct - in this case it would be just changing form of data.

It should not be necessary, it is result of a bug but such edit would not be wrong.
