### ISSUE TITLE
Toboggan not rendered

### ISSUE THREAD

**Issue by manfredbrandl** [gravitystorm/openstreetmap-carto#2858]
At http://www.openstreetmap.org/#map=17/46.91400/13.86941
there is a toboggan http://www.openstreetmap.org/way/55284714 in the database
![image](https://user-images.githubusercontent.com/5360273/30739673-82ce5402-9f8e-11e7-9256-34b41a8c2212.png)
and it is not rendered. I think it should be rendered.

There is another one which has the extra tag "highway=raceway" and I suppose that is why its rendered:
![image](https://user-images.githubusercontent.com/5360273/30739838-08e36528-9f8f-11e7-9035-08b884307df6.png)
See http://www.openstreetmap.org/way/40454225
According to https://wiki.openstreetmap.org/wiki/DE:Tag:sport=toboggan the extra tag should maybe not be there.

**Comment by kocio-pl** [comment]
How should it look like in your opinion? It's not obvious to me. We don't render many other sports because of that - golf is an exception.

**Comment by HolgerJeromin** [comment]
No `sport=*` and iirc no `attraction=*` is rendered on its own.
We have no "main" tag here. I would suggest adding `tourism=attraction` or a `leisure` tag.
The german wiki suggests adding `leisure=track`.

**Comment by polarbearing** [comment]
leisure=track sounds plausible, so it was a bit short-sighted from the editor of the way cited in the first picture to remove the physical tag from the feature without providing a better one.

**Comment by polarbearing** [comment]
Tagging has been improved in both cases - but now we depend on _Rendering leisure=track on lines_ #2632 :-(

**Comment by manfredbrandl** [comment]
@kocio-pl Rendering of a summer toboggan could be a medium dark grey line with dots. It may be be a bit broader than an aerial cableway and the dots (round, not squared?) could be less visible as those of an aerial cableway. But I am not an expert in map designing!

**Comment by manfredbrandl** [comment]
@kocio-pl I think the rendering should be based on the attraction=summer_toboggan attribute not on sport=toboggan. As sport=* is an non-physical tag it is probably okay not to be rendered. The summer_toboggan is a big and good visible structure.

**Comment by manfredbrandl** [comment]
@HolgerJeromin leisure=track did not help. Do you think that should be rendered?

**Comment by HolgerJeromin** [comment]
> leisure=track did not help. Do you think that should be rendered?

We have  #2632 for that

**Comment by manfredbrandl** [comment]
So I close my own issue. Thanks.
