### ISSUE TITLE
Oneway arrows for highway=cycleway/footway/path

### ISSUE THREAD

**Issue by evod** [gravitystorm/openstreetmap-carto#2865]
Some time ago (I guess more than a year already) cycleways tagged with oneway=yes featured arrows. I think it would be very useful to reintroduce this feature as this motivates the correct mapping of unidirectional cycleways.

An example area with a mix of unidirectional and bidirectional cycleways:
http://www.openstreetmap.org/way/19649973#map=19/48.27127/16.42020

**Comment by HolgerJeromin** [comment]
This seems like a regression. Footway is affected too:
http://www.openstreetmap.org/way/72763209#map=19/50.76436/6.07543

![image](https://user-images.githubusercontent.com/2410353/30846313-6adedb6c-a297-11e7-8e35-3dc5b3a92cd3.png)

#1937 has a screenshot from late 2015 of this place

**Comment by dieterdreist** [comment]
sent from a phone

> On 26. Sep 2017, at 08:49, Holger Jeromin <notifications@github.com> wrote:
> 
> This seems like a regression. Footway is affected too:
> http://www.openstreetmap.org/way/72763209#map=19/50.76436/6.07543
> 


the tagging looks a bit suspect. How can it be segregated and only foot designated?

**Comment by pnorman** [comment]
> the tagging looks a bit suspect. How can it be segregated and only foot designated?

That's not relevant for us, we don't use those tags.

**Comment by dieterdreist** [comment]
2017-09-27 6:26 GMT+02:00 Paul Norman <notifications@github.com>:

> the tagging looks a bit suspect. How can it be segregated and only foot
> designated?
>
> That's not relevant for us, we don't use those tags.
>

The question was if we should care for oneway properties on footways. While
these do occur, they are extremely rare (unlike pedestrian highways, where
it is rather common).

**Comment by evod** [comment]
@dieterdreist good point, the issue is also relevant for footway and path.

Oneways for footways (and also paths!) occur when the path is a combined foot- and cyclepath that is e.g. mapped as highway=footway|path|cycleway, bicycle=designated, foot=designated, oneway=yes.

(see tagging examples here: https://wiki.openstreetmap.org/wiki/Tag:access%3Ddesignated)

**Comment by matkoniecz** [comment]
> The question was if we should care for oneway properties on footways. While these do occur, they are extremely rare (unlike pedestrian highways, where it is rather common)

It is important information for some routes in mountains - for example Orla Perć in Poland - http://www.openstreetmap.org/way/95132011

**Comment by matkoniecz** [comment]
@evod 

highway=footway, bicycle=designated, foot=designated, oneway=yes

This is tagging error, highway=path should be used instead. SO that case is not a good reason to support rendering oneway arrows on paths.

**Comment by evod** [comment]
@matkoniecz I am not sure your example classifies as tagging error. At least a slightly different example (highway=cycleway + foot=designated + segregated=no) is mentioned on http://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway.

In general when bicycle and foot restrictions are both explicitly stated I guess it makes no (big) difference which one of highway=cycleway/footway/path is used.

Anyway, I think broadening the issue to all requests is necessary.

**Comment by geowOSM** [comment]
Oneway attribute on highway=path do occur also on mountain bike downhill trails and on highway=path + via_ferrata_scale=*

**Comment by evod** [comment]
Any news on this issue? I really miss the oneway arrows :(

**Comment by jeisenbe** [comment]
I have a solution, PR #3614:
![path-oneway-after](https://user-images.githubusercontent.com/42757252/50558361-fd410980-0d30-11e9-8296-d29f82d3dd33.png)

**Comment by evod** [comment]
Thank you for the great work on this issue @jeisenbe! Should the change already be live? This bug was referenced in https://github.com/gravitystorm/openstreetmap-carto/blob/master/CHANGELOG.md as change for v4.20.0 - 2019-02-15, but the map on osm.org does not yet contain oneway arrows (at least in Vienna, Austria)

**Comment by jeisenbe** [comment]
I think v4.20 has not yet been applied to the OSM servers, unfortunately.

**Comment by kocio-pl** [comment]
They have some technical problems currently: https://github.com/openstreetmap/chef/issues/218#issuecomment-471106000.
