### ISSUE TITLE
Add rendering for historic=fort

### ISSUE THREAD

**Issue by fqdb** [gravitystorm/openstreetmap-carto#2871]
Seeing as rendering for castles is already proposed, please also add support for historic=fort.

Made a possible design for an icon as well, needs some polishing of course, anyone is free to use it if they feel the need to contribute.
[fort.pdf](https://github.com/gravitystorm/openstreetmap-carto/files/1337760/fort.pdf)

**Comment by kocio-pl** [comment]
I'm not sure what this icon means, so this could be tweaked, but we need 14x14 px SVG (pixel aligned) version anyway.

**Comment by kocio-pl** [comment]
This tag has 2888 uses and a wiki page:

https://wiki.openstreetmap.org/wiki/Tag%3Ahistoric%3Dfort

**Comment by kocio-pl** [comment]
What about Osmic icon design:

https://github.com/gmgeo/osmic/blob/master/tourism/fort-14.svg

Another idea would be to draw a shape of "half star", resembling the typical shape of the fort from the aerial view.

**Comment by Tomasz-W** [comment]
I though about this:   http://1.bp.blogspot.com/-_xfoktodFMY/UJksjLQlDRI/AAAAAAAAAJs/EPObvzNgtsQ/s1600/VaubanPlan.jpg

Give me feedback is there a need to make an icon project with this shape.

**Comment by kocio-pl** [comment]
Something like this could work, but it might be hard at 14 px.

**Comment by Tomasz-W** [comment]
I've tried also rectangle-shaped and pentagon-shaped fort outline, but it actually didn't work. For example, five-armed shape 
http://www.syler.com/SiegeWarfare/basicconcepts/imgs4BasicConcepts/StarFort01.jpg
in 14x14 gives just simple star: ![historic fort](https://user-images.githubusercontent.com/25656654/35779643-fc9b01e8-09d0-11e8-87b4-e1a62f74bc4f.png)

**Comment by StyXman** [comment]
I made this icon for my style:

https://github.com/StyXman/elevation/blob/master/osm-carto/symbols/local/fort.svg

Do whatever you want with it, OSM gets any permisison from me :)

**Comment by kocio-pl** [comment]
Thanks. 😄 How would it look like with 14 px?

@Tomasz-W Have you tried something like this?:
https://wiki.openstreetmap.org/wiki/File:Castle_fortress.png

It wouldn't look like a simple star because of the inner part is empty and the shape is stretched.

**Comment by Tomasz-W** [comment]
@kocio-pl:
![pobrany plik](https://user-images.githubusercontent.com/25656654/35795068-4133b0a2-0a58-11e8-89a0-87530f7ee8dd.png)   (Osmic)
![pobrany plik2](https://user-images.githubusercontent.com/25656654/35795158-92607924-0a58-11e8-8e5a-bf0d41f04bb8.png)   (@StyXman )
![svg historic fort styxman](https://user-images.githubusercontent.com/25656654/35795386-4caff728-0a59-11e8-91f5-97ac1efb8cd7.png) (@StyXman without inner part)
![historic fort3](https://user-images.githubusercontent.com/25656654/35794616-ba91a17c-0a56-11e8-8ac5-d6675c3bf5d2.png)   (star shape without inner part)

**Comment by kocio-pl** [comment]
Thanks for testing them! 3 looks quite promising for me, but it's based on rectangle instead of pentagon. Could you test pentagon with similar features?

**Comment by Tomasz-W** [comment]
I've made corner elements a little bit bigger, but it's still not working for me:

![historic fort3](https://user-images.githubusercontent.com/25656654/35800394-1f06db88-0a69-11e8-969d-0c61c8e08b3a.png)

14x14:  ![historic fort](https://user-images.githubusercontent.com/25656654/35800393-1ed7b074-0a69-11e8-87b7-8aa272aee626.png)

If someone wants to tune it up, here is the Gist:   https://gist.github.com/Tomasz-W/615d2766d2b7e9c4295cd11cb998c8de

**Comment by kocio-pl** [comment]
Maybe with a thin line on top instead of top feature would be better? It would be [isosceles trapezoid](https://en.wikipedia.org/wiki/Isosceles_trapezoid) then instead of pentagon.

**Comment by Tomasz-W** [comment]
@kocio-pl Did you mean this?
![historic fort linia 2](https://user-images.githubusercontent.com/25656654/35804492-614d9f68-0a78-11e8-9794-88a80fa538d4.png)
14x14: ![historic fort linia](https://user-images.githubusercontent.com/25656654/35804497-64c14686-0a78-11e8-8b4d-e322199ba365.png)

**Comment by kocio-pl** [comment]
Yes, with thinner line on the top (to show the side where the fort connects with the city for example). It looks quite good, but I'm thinking also about other variations:
- 1 thin line on top and 4 thick walls on the bottom (instead of 3 thick walls)
- the same (3 or 4 thick walls), but with with thick elements (small thick rectangles) in the middle of thick walls (instead of on nodes/vertexes)

I hope this is more or less clear... 😃

**Comment by Tomasz-W** [comment]
I'm not sure if I understand it correctly, so I'm uploading both versions (trapezoid and pentagram) on Gist. Please tune it up on your own hand.
https://gist.github.com/Tomasz-W/0458d47f40b74c06b81888ba696cc6f1

**Comment by kocio-pl** [comment]
I think this is even better than the last one and would fit the rest of castle/palace icons (original Osmic fort icon also fits them of course, but is less readable at 14 px):
![fort-20](https://user-images.githubusercontent.com/5439713/35821570-b92d4c3e-0aa9-11e8-84e1-b38caf4ab1b5.png)

**Comment by kocio-pl** [comment]
@Tomasz-W Thanks for your design ideas, it helped me a lot to have a reference.
