### ISSUE TITLE
Disappear roads at zoom level 17 and reappears at 20

### ISSUE THREAD

**Issue by nafis042** [gravitystorm/openstreetmap-carto#2876]
So I have a weird problem. I added a road segment connecting 2 roads(previously existed) using JOSM and upload data into database. After that when I try to show this into map, it works fine at zoom level 16 then at zoom level 17 it disappears and at zoom level 20 it reappears. What am I missing? I only added 2 tags for this road: highway -> residential , name -> something

**Comment by math1985** [comment]
Probably zoom 18 and 19 have not been updated yet. Wait a couple of hours, in the worst case days, and it should appear!
