### ISSUE TITLE
Mapnik version

### ISSUE THREAD

**Issue by hiarcat** [gravitystorm/openstreetmap-carto#2880]
Which mapnik version is the best to use with openstreetmap-carto?

Mapnik 3.0.15 doesn't render road shields (while 3.0.12 does). Tested with the same xml-file.

**Comment by math1985** [comment]
I'm not aware of this issue. Any version 3.0 or greater should work, according to our documentation. 

For reference, 3.0.15 is the latest version, so something should be fixed at either our side or Mapnik's.

**Comment by hiarcat** [comment]
Thanks.
I'll try some older versions. Do you know which version is used on osmf-servers?

**Comment by math1985** [comment]
> Do you know which version is used on osmf-servers?

I don't know, sorry.

**Comment by kocio-pl** [comment]
I'm just testing with newest Kosmtik from git, which has lately updated Mapnik from 3.0.12 to 3.0.15, and the road shields are rendered.

**Comment by HolgerJeromin** [comment]
they "started" with 3.0.9 
https://github.com/openstreetmap/chef/issues/39#issuecomment-246193500
But i am unsure if there was an update since then.

**Comment by pnorman** [comment]
> Mapnik 3.0.15 doesn't render road shields (while 3.0.12 does). Tested with the same xml-file.

If this is true, it's a Mapnik bug.

**Comment by hiarcat** [comment]
Sorry, it was my fault, I installed the "master" branch a couple of days ago. This version doesn't render road shields (and some svg).

The mapnik 3.0.15 release is ok!

But there is one issue on my 32 bit dev-system:

When I use "::upper-mid-zoom[zoom >= 12][zoom < 13] { image-filters: scale-hsla(0,1,0,1,0.4,0.97,0,1); } in landcover.mss, my forest is pink (#e0bdbd) in zoom 12 for example.

Is scale-hsla unusable on 32 bit machines?

**Comment by pnorman** [comment]
> When I use "::upper-mid-zoom[zoom >= 12][zoom < 13] { image-filters: scale-hsla(0,1,0,1,0.4,0.97,0,1); } in landcover.mss, my forest is pink (#e0bdbd) in zoom 12 for example.
> 
> Is scale-hsla unusable on 32 bit machines?

If it is, it's nothing to do with OpenStreetMap Carto. It would be a Mapnik bug and you should ask at https://github.com/mapnik/mapnik.

**Comment by hiarcat** [comment]
I set up a new dev system (Gentoo 64 bit now, was Gentoo 32 bit, same machine).
The forest is green now and a bit lighter (as expected)

So scale-hsla seems to be unusable on 32 bit machines.

I'm happy now, problem is solved!
