### ISSUE TITLE
Show names of seas and oceans on the map

### ISSUE THREAD

**Issue by hikemaniac** [gravitystorm/openstreetmap-carto#2882]
It would be very helpful to have the names of [seas](https://wiki.openstreetmap.org/wiki/Tag:place%3Dsea) and [oceans](https://wiki.openstreetmap.org/wiki/Tag:place%3Docean) rendered on OSM-Carto at least on low zoom levels. The inaccuracy of arbitrarily positioned nodes would not really matter on low zoom levels (maybe z0, z1, z2, z3). This would go along with all the great work done recently (and still going on) on improving low zoom levels.

This issue is quite similar to #2278.

**Comment by math1985** [comment]
Duplicate with #2278!

**Comment by math1985** [comment]
Oh wait, you mentioned #2278. What is the difference between that issue and this request?

**Comment by kocio-pl** [comment]
Since there's no response yet, I will close it, since it looks like a reminder, but it could be reopen if there is really something different than in #2278.
