### ISSUE TITLE
Render housenumbers on entrances inside the building

### ISSUE THREAD

**Issue by manfredbrandl** [gravitystorm/openstreetmap-carto#2888]
In http://www.openstreetmap.org/#map=19/47.06470/15.43693
z19
![image](https://user-images.githubusercontent.com/5360273/31340073-50d203fc-ad05-11e7-9735-4873ca979560.png)
z18
![image](https://user-images.githubusercontent.com/5360273/31340202-abff5a72-ad05-11e7-8aca-597773d9e348.png)
z17
![image](https://user-images.githubusercontent.com/5360273/31340171-9897a750-ad05-11e7-92db-435fae988a29.png)
I think the housenumbers would be more readable inside the building.

**Comment by kocio-pl** [comment]
I don't think it's doable with our toolkit.

**Comment by manfredbrandl** [comment]
If it is not doable now, maybe keep it as a 'bluesky' improvement?

**Comment by kocio-pl** [comment]
Don't worry, if there is something that can be done, we can always reopen the issue, it won't disappear. However that would mean rather big changes in the software.
