### ISSUE TITLE
Problème d'affichage du nom de mon entreprise

### ISSUE THREAD

**Issue by IZ22** [gravitystorm/openstreetmap-carto#2889]
Bonjour,
Depuis un certain moment je n'arrête pas d'essayer de faire apparaître le nom de mon entreprise sur la carte OpenStreetMap, mais je n-y arrive toujours pas, bien que j'aie suivis absolument toutes les étapes exigées.
J'ai beau essayer de modifier légèrement son emplacement sur la carte de temps à autre mais le nom ne s'affiche toujours pas. (C'est le numéro de porte du bureau de l'entreprise qui s'affiche sur la carte et non pas son nom !)
Veuillez m'aider à afficher le nom de mon entreprise sur la carte.
Merci d'avance.
Cordialement.
![photo 01](https://user-images.githubusercontent.com/32734782/31491715-7d476572-af48-11e7-8da7-faec46293496.jpg)

**Comment by dieterdreist** [comment]
this refers to this object:
http://www.openstreetmap.org/node/5134887422

en français: le problème est la typologie de l'entreprise. C'est un bureau
e les bureaux ne sont pas visualisés actuellement dans ce style. Mais les
données sont contenues (pour la recherche) e l'adresse est visible.

**Comment by IZ22** [comment]
La première fois que j'ai entré le nom de mon entreprise, il s'était bien affiché sur la carte tout comme je le demande maintenant, il s'affichait normalement sur mon GPS aussi; cependant, je m'étais trompé sur son emplacement réel, j'ai dû donc le modifier par la suite pour le mettre au bon endroit.
Donc même les noms de bureau s'affichent finalement; je regrette juste d'avoir modifié son emplacement (ce qui m'a fait tout perdre.)
Que dois-je faire pour le ré-afficher S.V.P

**Comment by sommerluk** [comment]
Les bureaux d’entreprise ne sont pas visibles dans la carte standard.

Si les bureaux d’entreprise sont visibles « dans le GPS » dépend de l’application que vous utiliser. OSMand pour exemple peut les afficher.

En général, les données de l’entreprise me semblent correctes. J’ai corrigé le numéro de téléphone (format international).

Quelle est la ligne d’activité de l’entreprise, s’il vous plaît ?

**Comment by IZ22** [comment]
Il s'agit d'une entreprise d'architecture d'intérieur/décoration et de traitement de façades.

**Comment by sommerluk** [comment]
Tagging is correct as-is, see #108 and #1697 for discussion about rendering.

**Comment by IZ22** [comment]
Merci sommerluk mais je ne comprends pas ce que vous dîtes. Pouvez-vous m'expliquer ?

**Comment by sommerluk** [comment]
Vous avez introduit correctement le bureau de votre entreprise en OSM. Il ne va quand-même pas être visible sur la carte standard à openstreetmap.org parce que actuellement tous les bureaux d’entreprises sont invisibles. Voyez voir #108 et #1697 pour la discussion sur l’affichage des bureaux d’entreprise.

Indépendant d’openstreetmap.org les applications pour les portables (OSMand, Maps.me…), eux ils affichent souvent les bureaux d’entreprise.

**Comment by IZ22** [comment]
Merci bien,
Pouvez-vous me dire quand est-ce que je devrais voir le nom de mon entreprise affiché sur la carte de Maps.me ?

**Comment by sommerluk** [comment]
Maps.me prend plusieurs mois pour actualiser la carte. En Afrique, en
général c’est encore plus lent que en Europe.

Lukas Sommer

2017-10-12 15:40 GMT+00:00 IZ22 <notifications@github.com>:

**Comment by IZ22** [comment]
Je vous remercie monsieur Lukas Sommer de toutes vos réponses.
Je vois que malheureusement je dois attendre un long moment pour voir le nom de mon entreprise affiché sur la carte d'OpenStreetMap.
Quand je l'ai ajouté la première fois, ça n'a pris que 2 jours pour s'afficher sur la carte... Je suppose que ça a dû coïncider avec une mise à jour.
Tant pis, s'il n-y a pas de solution pour accélérer le processus; je vais attendre...
