### ISSUE TITLE
rename "easy" label to "good first issue"?

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2899]
I noticed Github banner

> Now, GitHub will help potential first-time contributors discover issues labeled with "help wanted" or "good first issue"

I think that there is no reason to not use name that is recognized by GitHub and in addition is (I think) more welcoming potential contributors.

**Comment by math1985** [comment]
Yes, I wasn't aware of that yet, let's move over!

**Comment by matkoniecz** [comment]
Done.

**Comment by math1985** [comment]
We also need to change the link in https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md .

**Comment by matkoniecz** [comment]
@math1985  Thanks for spotting, #2900 fixes this problem.

**Comment by kocio-pl** [comment]
BTW - GitHub also recommends other "community standards", of which we lack only issue and PR templates: 
* https://help.github.com/articles/creating-an-issue-template-for-your-repository/
* https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Do you think we need them?
