### ISSUE TITLE
Where to get "Noto Sans Arabic UI"

### ISSUE THREAD

**Issue by giggls** [gravitystorm/openstreetmap-carto#2906]
Hello,

in v4.4 release notes you state "Introducing Noto Sans Arabic".

Well I suppose you should also have updated INSTALL.md whith the place where the fonts you are introducing to us are available from.

Unfortunately it is neither inside fonts-noto-hinted package from Debian/Ubuntu nor downloadable from https://www.google.com/get/noto/

Am I right in the assumption that https://github.com/googlei18n/noto-fonts is the place to go?

Regards

Sven

**Comment by sommerluk** [comment]
INSTALL.md has been updated and indeed refers to the Noto Github repository (which is the repository for all Noto fonts except CJK and emoji).

The font is available at https://github.com/googlei18n/noto-fonts/tree/master/hinted and https://github.com/googlei18n/noto-fonts/tree/master/unhinted (depends if you wan the hinted or the unhinted version).
