### ISSUE TITLE
Update code for UI fonts vs normal fonts

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#2908]
For some scripts, Noto Sans offers both, a _UI_ and a _normal_ font. For the other scripts, it offers only the _normal_ font.

Apparently now there will be no more UI version of the Noto base font (latin script…): https://github.com/googlei18n/noto-fonts/pull/985

In a nutshell:
- “Noto Sans UI” was always the same thing (same file with another name) as “Noto Sans”. (We suspected that yet…)
- “Noto Sans UI” won’t be part of the release any-more
- The other UI fonts (mostly for Asian scripts) will continue to exist and maintained

We should therefore replace “Noto Sans UI” by “Noto Sans” in our style.

Looking at our current font list, for the non-latin scripts we have for some scripts the UI font _and_ the normal font as fallback. For other scripts, we have the UI font only. Maybe we could use the same policy for all scripts.

cc @pnorman

**Comment by sommerluk** [comment]
I prefer to be on the safe side and add both—UI _and_ non-UI— if available.

**Comment by zenonp** [comment]
Most (but not all) UI fonts have been removed from the latest fedora 40 noto rpm. However, they are still referenced by scripts/get-fonts.sh and the style.xml that carto produces. Eventually this is going to cause surrepticiously misrendered tiles on all redhattish systems. 

These are currently missing:

NotoEmoji-Bold.ttf
NotoSansArabicUI-Bold.ttf
NotoSansArabicUI-Regular.ttf
NotoSansKhmerUI-Bold.ttf
NotoSansKhmerUI-Regular.ttf
NotoSansLaoUI-Bold.ttf
NotoSansLaoUI-Regular.ttf
NotoSansMyanmarUI-Bold.ttf
NotoSansMyanmarUI-Regular.ttf
NotoSansOriyaUI-Bold.ttf
NotoSansOriyaUI-Regular.ttf
NotoSansThaiUI-Bold.ttf
NotoSansThaiUI-Regular.ttf

These have been obsoleted in Fedora 40:

$ grep obsoletes rpmbuild/SPECS/google-noto-fonts.spec 
--obsoletes: array: outdated package name to replace by
      obsoletes={ "sans-ui", "sans-display" },
      obsoletes={ "sans-anatolian-hieroglyphs-vf" }
      obsoletes={ "sans-arabic-ui" },
      obsoletes={ "sans-avestan-vf" }
      obsoletes={ "sans-bengali-ui-vf" },
      obsoletes={ "sans-buginese-vf" }
      obsoletes={ "sans-buhid-vf" }
      obsoletes={ "sans-carian-vf" }
      obsoletes={ "sans-cuneiform-vf" }
      obsoletes={ "sans-cypriot-vf" }
      obsoletes={ "sans-deseret-vf" }
      obsoletes={ "sans-devanagari-ui-vf" }
      obsoletes={ "sans-egyptian-hieroglyphs-vf" }
      obsoletes={ "sans-elymaic-vf" }
      obsoletes={ "sans-gothic-vf" }
      obsoletes={ "sans-gurmukhi-ui-vf" },
      obsoletes={ "sans-hanunno" }
      obsoletes={ "sans-hatran-vf" }
      obsoletes={ "sans-hebrew-droid", "sans-hebrew-new" },
      obsoletes={ "sans-imperial-aramaic-vf" }
      obsoletes={ "sans-khmer-ui" },
      obsoletes={ "sans-lao-ui" },
      obsoletes={ "looped-lao", "looped-lao-ui" },
      obsoletes={ "sans-linear-a-vf" }
      obsoletes={ "sans-linearb", "sans-linear-b-vf" }
      obsoletes={ "sans-lycian-vf" }
      obsoletes={ "sans-lydian-vf" }
      obsoletes={ "sans-mandaic-vf" }
      obsoletes={ "sans-marchen-vf" }
      obsoletes={ "sans-math-vf" }
      obsoletes={ "sans-mayan-numerals-vf" }
      obsoletes={ "sans-meeteimayek" }
      obsoletes={ "mono" },
      obsoletes={ "sans-mro-vf" }
      obsoletes={ "sans-multani-vf" }
      obsoletes={ "sans-myanmar-ui" },
      obsoletes={ "sans-nabataean-vf" }
      obsoletes={ "sans-ogham-vf" }
      obsoletes={ "sans-oriya-ui" },
      obsoletes={ "sans-osmanya-vf" }
      obsoletes={ "sans-phags-pa" },
      obsoletes={ "sans-phenician-vf" }
      obsoletes={ "sans-runic-vf" },
      obsoletes={ "sans-shavian-vf" }
      obsoletes={ "sans-sinhala-ui-vf" },
      obsoletes={ "sans-soyombo-vf" }
      obsoletes={ "sans-syriac-estrangela" }
      obsoletes={ "sans-tagbanwa-vf" }
      obsoletes={ "sans-takri-vf" }
      obsoletes={ "sans-tai-viet-vf" },
      obsoletes={ "sans-thai-ui" },
      obsoletes={ "sansthai-looped-vf", "sans-thai-looped-vf", "looped-thai-ui", "looped-thai-vf", "looped-thai-ui-vf" }
      obsoletes={ "sans-ugaritic-vf" }
      obsoletes={ "sans-vai-vf" }
      obsoletes={ "sans-wancho-vf" }
      obsoletes={ "sans-warang-citi-vf" }
      obsoletes={ "sans-yi-vf" }
      obsoletes={ "sans-zanabazar-square-vf" },
      obsoletes={ "serif-display" },
      obsoletes={ "sans-balinese" }
      obsoletes={ "serif-dogra-vf" },
      obsoletes={ "serif-nyiakeng-puachue-hmong" },
      obsoletes={ "serif-tamil-slanted" },
      obsoletes={ "serif-tangut-vf" }
      obsoletes={ "sans-tibetan" }
      obsoletes={ "sans-display-vf" },
      obsoletes={ "sans-arabic-ui-vf" },
      obsoletes={ "sans-gurkukhi-ui-vf" },
      obsoletes={ "sans-hebrew-droid-vf", "sans-hebrew-new-vf" },
      obsoletes={ "sans-khmer-ui-vf" },
      obsoletes={ "sans-lao-ui-vf" },
      obsoletes={ "looped-lao-vf", "looped-lao-ui-vf" }, nogroup=1,
      obsoletes={ "serif-myanmar-vf", "sans-myanmar-ui-vf" }
      obsoletes={ "sans-oriya-ui-vf" },
      obsoletes={ "sans-tamil-supplement-vf" },
      obsoletes={ "sans-thai-ui-vf" },
      obsoletes={ "serif-display-vf" },
      obsoletes={ "serif-nyiakeng-puachue-hmong-vf" },
      obsoletes={ "serif-tamil-slanted-vf" },

**Comment by pnorman** [comment]
This is an old issue so it's best to open a new issue if there is one. System fonts have always had problems with missing stuff or versions which is why we don't use them and download the latest version ourselves.
