### ISSUE TITLE
`man_made=silo` is not being rendered

### ISSUE THREAD

**Issue by ThomasA** [gravitystorm/openstreetmap-carto#2909]
I recently changed a lot of silos and storage tanks along Aalborg Harbour from `building=yes` to `man_made=silo` and `man_made=storage_tank`, because I find that a more accurate reflection of what is actually there. However, now they are no longer rendered on openstreetmap.org. Why does it not render these - physically quite prominent - features?

**Comment by kocio-pl** [comment]
#588 was closed, but can be reopened (see also #372). Please change name of this ticket to drop `man_made=silo`, so the tickets don't overlap.

For every such object we need an idea how should they be rendered. Do you have one?

**Comment by ThomasA** [comment]
Sorry, didn't see that issue...

**Comment by dieterdreist** [comment]
2017-10-26 10:53 GMT+02:00 Thomas Arildsen <notifications@github.com>:

> I recently changed a lot of silos and storage tanks along Aalborg Harbour
> from building=yes to man_made=silo and man_made=storage_tank, because I
> find that a more accurate reflection of what is actually there. However,
> now they are no longer rendered on openstreetmap.org. Why does it not
> render these - physically quite prominent - features?
>


IMHO you shouldn't replace tagged properties ("is a building in OSM") with
different properties, if both apply. You can keep the building tag (or
replace it with a more accurate value like "silo") and still add the
man_made tags. Obviously only in case, the tagged objects are considered
buildings in OSM (to see this, I'd ask on the tagging list, look up the
wiki _and taginfo_).

**Comment by matkoniecz** [comment]
I suspect that silos should also have a building tag.

**Comment by matkoniecz** [comment]
I propose to close this issue and reopen it if there are man_made=silo objects that should not be tagged as building.

**Comment by matkoniecz** [comment]
If there are man_made=silo where building tag is wrong it would be a good idea to give example (with photo) at https://wiki.openstreetmap.org/wiki/Tag%3Aman_made%3Dsilo

In my very limited experience building tag is applicable for such structures.

**Comment by kocio-pl** [comment]
I reopen this as I made a mistake closing this - bunker silo needs a different visual representation probably and I think silo is closer to storage tank (closed space), see the proposition for rendering them: https://github.com/gravitystorm/openstreetmap-carto/issues/588#issuecomment-373903971.

**Comment by matkoniecz** [comment]
> I reopen this as I made a mistake closing this

Do you have any example of object correctly tagged with man_made=silo where adding also building=silo would be wrong?

**Comment by eigenwillig** [comment]
Silos are more structures than buildings. If we accept that there is a separate tag for storage tanks (with man_made) the same should apply for silos!

**Comment by Tomasz-W** [comment]
As silos are very similar to storage tanks outside (the difference between them is about what is inside - silos are for bulk materials and storage tanks are for liquids) I think both tags could be rendered with the same icon:

![1](https://user-images.githubusercontent.com/25656654/37558876-7b9653e8-2a1b-11e8-94c4-3ff599f2054b.png)

**Comment by eigenwillig** [comment]
Another argument for not using building=silo:

Storage tanks are never made from concrete, while silos are made from either steel (esp. North America / grains) or concrete.

**Comment by matkoniecz** [comment]
@Tomasz-W 

I am not convinced that icon is a good idea, I would just render them like building=*

> Another argument for not using building=silo:

I have no idea why this is relevant for either
 - whatever building=silo is a good idea (we already established that at least some silo are not taggable with building=silo)
- I have no idea why construction material is relevant to using building tag (there are building made both from reinforced concrete and steel)

**Comment by matkoniecz** [comment]
@Tomasz-W 

I am not convinced that icon is a good idea, I would just render them like building=*

@eigenwillig 
> Another argument for not using building=silo:

I have no idea why this is relevant for either
 - whatever building=silo is a good idea (we already established that at least some silo are not taggable with building=silo)
- I have no idea why construction material is relevant to using building tag (there are building made both from reinforced concrete and steel)

**Comment by kocio-pl** [comment]
Since they are located outside city centers, I guess we could also render icon on high zoom, like z18+, since this is information which will not clutter space. However rendering them like buildings by default seems fine to me. People use building tags for very different structures, like silos or monuments, so it looks like intuitive enough.

**Comment by dieterdreist** [comment]
sent from a phone

> On 18. May 2018, at 12:30, kocio-pl <notifications@github.com> wrote:
> 
> Since they are located outside city centers, I guess we could also render icon on high zoom, like z18+, since this is information which will not clutter space. However rendering them like buildings by default seems fine to me. People use building tags for very different structures, like silos or monuments, so it looks like intuitive enough.



what could be an argument for rendering an icon is that they are usually tall structures and can serve as landmarks.

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/4ebcb87699e6442d696f9c06ce16c31f
