### ISSUE TITLE
Add icon for leisure=firepit

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#2910]
W have 8,5k  of leisure=firepit, but is not rendered. 
https://taginfo.openstreetmap.org/tags/leisure=firepit

Examples:
http://www.openstreetmap.org/way/525604639
https://www.openstreetmap.org/way/527840126
https://www.openstreetmap.org/node/5128204779

I think firepits may be important information for tourists, and should be rendered.

My icon proposal:
![leisure firepit2](https://user-images.githubusercontent.com/25656654/32134161-6765c7e8-bbe7-11e7-84ff-45a0b854f612.png)
14x14:
![leisure firepit](https://user-images.githubusercontent.com/25656654/32134164-6d0e1efc-bbe7-11e7-91a2-9cbbd602be77.png)

**Comment by kocio-pl** [comment]
Sounds reasonable to me. My questions:
1. What should be the color?
2. Is it enough to distinguish from [firestation icon](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/firestation.svg)? 
2. Could you prepare also code and test rendering?

**Comment by Tomasz-W** [comment]
@kocio-pl
1. Brown, I think. Then it will fit other tourism elements
2. For me, it's ok (different fire shape and "x" part), but I'd like to hear another users opinion.
3. Unfortunely no, I have no skills in that things.

BTW. I found that tourism=picnic_site and leisure=picnic_table are rendering the same. 
Example: http://www.openstreetmap.org/#map=19/52.40365/16.85518
I think it's bad and it could make misunderstandings. Picnic sites are non-physical feature (it's rather area description), and picnic tables are physical things. Mayby just changing picnic sites icon colour to green (the same as playgrounds or minigolf) would be good? What do you think?

**Comment by kocio-pl** [comment]
I agree with you, picnic site icon and label should be leisure green.

**Comment by kocio-pl** [comment]
Could you publish SVG code of a firepit icon?

**Comment by Tomasz-W** [comment]
https://gist.github.com/Tomasz-W/ba7dbf8f3202725975129a03a2760611

**Comment by geesona** [comment]
I do like the firepit icon but do not think it suitable for an electric BBQ.  Perhaps the cross could be changed for an electric charging sign, or lightning flash?

**Comment by sommerluk** [comment]
> I do like the firepit icon but do not think it suitable for an electric BBQ.

That’s exactly what we want. leisure=firepit is defined as place for open fire, not for electric BBQ.
