### ISSUE TITLE
Change tourism=picnic_site icon colour to green

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#2915]
Separate issue due to https://github.com/gravitystorm/openstreetmap-carto/issues/2910#issuecomment-340205123

I found that tourism=picnic_site and leisure=picnic_table are rendering the same.
Example: http://www.openstreetmap.org/#map=19/52.40365/16.85518
I think it's bad and it could make misunderstandings. Picnic sites are non-physical feature (it's rather area description), and picnic tables are physical things. Maybe just changing picnic sites icon colour to green (the same as playgrounds or minigolf) would be good?

**Comment by polarbearing** [comment]
Isn't tourism brown and leisure green? So, should the colours assigned vice versa?
