### ISSUE TITLE
text-wrap not respected in kosmtik

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#2917]
this moment I am not sure what is going wrong but I used openstreetmap-carto docker - https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

http://www.openstreetmap.org/#map=19/50.05094/20.07343 is rendered differently in Kosmtik

http://www.openstreetmap.org/#map=19/50.05094/20.07343

![selection_005](https://user-images.githubusercontent.com/899988/32338306-9f66def0-bff4-11e7-9a0a-c3b142f18585.png)

http://localhost:6789/openstreetmap-carto/#19/50.05094/20.07343

![selection_006](https://user-images.githubusercontent.com/899988/32338292-99367496-bff4-11e7-94e0-0205f112bd3d.png)

At this moment I have no idea what is causing this - it may be a Kosmtik bug, recent not deployed change in style, bug in Mapnik...

**Comment by matkoniecz** [comment]
It appears to affect also other labels like place=* and landcover.

**Comment by kocio-pl** [comment]
Have you tried to update Docker images? I suspect this is duplicate of #2755, which was fixed by #2818 or maybe just because there was a bug in packages and rebuilding them pulled fixed versions.

**Comment by matkoniecz** [comment]
I thought that I did this, but appears that I was confused where docker stores its images.

**Comment by matkoniecz** [comment]
Thanks for pointing me to a duplicate!
