### ISSUE TITLE
Is lowercase "unifont" needed?

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2924]
I wonder if we need "unifont Medium" here:

https://github.com/gravitystorm/openstreetmap-carto/blob/623b9514e010cd10fb1be6818005eaaa8a089d8b/fonts.mss#L125

it gives me warnings, which I was not able to get rid of after installing unifont (it silenced only "Unifont" warnings).

**Comment by pnorman** [comment]
Yes, because the font has changed names in the past, see #429

**Comment by SomeoneElseOSM** [comment]
Whether or not the name has changed in any particular distribution it's "Unifont" in some current distributions and "unifont" in other current ones.  It's easier the removed font names that cause warnings than it is to figure out what a missing value should be, so it makes sense to leave the duplication in.

My recollection is that some tools (I believe it was generate_tiles.py) will give you more than a warning for missing fonts, so if using that you'll need to "curate" the list of fonts used in the style anyway.
