### ISSUE TITLE
Low-zoom: decide which features to render

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#2925]
Some features that we currently render for which we do not (yet) have a use case:
* Province/state names and borders on z5
* Roads on z5
* National parks on z7
* Railways on z7
* Minor water areas on z5/6/7
* Glaciers and icesheets on z6 and z7
* Military areas on z7
* Ferry routes on z7
* Island names on z5/6/7

In which cases do we want to add use cases, and in which cases do we want to drop rendering?

CC @kocio-pl

**Comment by math1985** [comment]
My opinion:

> Province/state names and borders on z5

This really depends on the area. I guess we cannot avoid rendering for larger countries such as the US, and as we have no way to distinguish country size currently, we should render all borders.

> Roads on z5

I'm in favour of dropping rendering.

> National parks on z7

I'm in favour of dropping. I fail to see how the current rendering is useful for any purpose.

> Railways on z7

I guess people who like tracing railway lines to see along which route they are travelling (including me) can zoom in one zoom level more. So I'd say drop.

> Minor water areas on z5/6/7

Guess nothing we can do about.

**Comment by matkoniecz** [comment]
> This really depends on the area. I guess we cannot avoid rendering for larger countries such as the US, and as we have no way to distinguish country size currently, we should render all borders.

documented in #2926

**Comment by matkoniecz** [comment]
My opinion:

> Province/state names and borders on z5

It depends on location and I am tempted to introduce some form of hardcoding here. Where (except USA) showing internal division is useful?

> Roads on z5

advocatus diaboli: it nicely shows population density (seee for example USA http://www.openstreetmap.org/#map=5/41.212/-95.010 )

but given that strongest argument is really weak - I think that it may be dropped

> National parks on z7

I'm in favour of dropping since #1669. I fail to see how the current rendering is useful for any purpose.

> Railways on z7

Here I would be against change. At this scale showing railway structure IMHO makes sense.

> Minor water areas on z5/6/7

Depends on what one considers as minor. But given technical problems for now I will ignore this issue.

**Comment by math1985** [comment]
> > Railways on z7

> Here I would be against change. At this scale showing railway structure IMHO makes sense.

What is the use case? :)

**Comment by matkoniecz** [comment]
> What is the use case? :)

Showing structure of railway network - but given that using "it is interesting for me" one may justify showing anything, from showing density of stork nests to showing capacity of bicycle parkings it is not a real usecase :(

**Comment by kocio-pl** [comment]
I have a general problem with fitting in the "use case" approach here. I think about natural areas as important general context, but they can be interesting in themselves (especially on low zoom levels), because my primary aim when looking at the map is _to understand the space_ (is this a use case? I don't know).

I don't know how to answer the question like "what for would you like to see the river on the map"? I think that on z5-z7 we can have a minimal context as described, but having rivers, lakes, woods, farmlands (let's simplify things a bit assuming that they are natural), meadows, sands, deserts or ice makes it better. Speaking just about the context - for me road going through the forest is different than one going through farmlands or sands.

It's a also good to see mountain areas, even if we don't have tags for hillshading probably. So it's a different problem how much we want to avoid external sources - I would accept this exception, because it's out of OSM scope currently.

We should also examine West Coast (USA) - there are a lot of big military areas (use case - avoiding such areas when planning a route?) and nature reserves (use case - probably they are kind of big parks, like Yellowstone for example, so maybe looking for such places when planning a route?). They are already visible on z7, but there's so much of them, that they would be also visible on z5 and z6.

**Comment by math1985** [comment]
> to understand the space (is this a use case? I don't know).

Yes, absolutely! But probably it is possible to make it even more specific. Maybe something like 'Understanding what part of the area has legal protection' or 'Understanding what the area looks like' or 'Learning what are the important named toponyms'. By making the use case more specific, we can also be more specific in the rendering: is it important to show the boundaries of the individual nature areas, or perhaps just the boundary between protected and non-protected areas? Do we need the names? Or perhaps a different feature, like landcover, answers the question better than natural areas.

(I wouldn't call this use 'context' though. If it was used as context, it would be more like finding out things like 'the village is next to Yellowstone NP' or 'the museum is inside the national park').

**Comment by math1985** [comment]
> Showing structure of railway network 

Would it be possible to make that more concrete too? Why exactly do we want the structure of the railway network? What can it teach us?

**Comment by math1985** [comment]
> advocatus diaboli: it nicely shows population density 

In well-developed areas, yes. If we want to show population density, I guess we should show it in a different way.

**Comment by kocio-pl** [comment]
OK, I will try to make it as specific as I can.

> (I wouldn't call this use 'context' though. If it was used as context, it would be more like finding out things like 'the village is next to Yellowstone NP' or 'the museum is inside the national park').

For me it's both subject and the context, depending on a current view:

1. When I want to see what's the dominating form on land on z5-z7, natural areas like mountains or sand are the subject, while the land/water borders (like continents and oceans) are the context.

2. But when I look at USA or China and I notice that west parts of both countries are visibly less populated than east ones, the mountains and deserts are the answer ("population of this continent lives mostly away from high and dry areas").

**Comment by pierzen** [comment]
As was said previously, we should not have the same rule for large territories and dense populated Europe. In less populated territories, Borders and important infrastructures should be rendered from Z5. This includes Major Roads, railways, National Parks, Dams and Major electric lines. A comparison at zoom level 5 between the «Blank Map» for east of Canada and the dense network of roads for Europe speaks by itself. I will speak of a territory where I did a lot of mapping, North of Quebec. This is a very low population density territory, with hydro-electric dams, Major Power lines,  mining sites, railways, nature activities and some major roads. A few villages and airports are spread mainly around the north sea and the major economic activities. 

* Province/state names and borders on z5
For areas like Canada, this should be kept.
See https://www.openstreetmap.org/#map=5/50.986/-73.499

* Places and airports
In nordic territories where villages are hundred of km distant from each other, name of isolated villages and airport icons should be rendered at z5.
Try to find the villages and airports disseminated in this territory.
https://www.openstreetmap.org/#map=5/59.198/-75.388

* Roads on z5
From Secondary going up in the hierarchy of road, this should be kept.

* National parks on z7
For areas like Canada, the nature reserves are important infrastructures and should be rendered at z5
See https://www.openstreetmap.org/#map=7/46.785/-74.822

* Railways on z7
For areas like Canada, major railways (based on length ?) should be rendered at z5. Why compare such major infrastructures with bycycle parking? or Junk Food??
See https://www.openstreetmap.org/#map=7/51.427/-68.022

* Minor water areas on z5/6/7
In nordic countries, it is irrelevant to show the million of small lakes or short rivers at lower zoom levels. Many styles like the Carto style have rules to progressively show Minor water areas. Similar rules would help to visualize the Map in the nordic territories.

* Major Dam Infrastructures
Dams are rendered from z13. For large territories, they should be rendered at z9.
See https://www.openstreetmap.org/relation/6572626#map=9/54.3598/-72.3326

* Major Power Lines
For large territories, they should be rendered from level 5
See https://www.openstreetmap.org/relation/4504531#map=5/50.903/-69.587

* Forest zones
Forest areas rendered from zoom 7 could be rendered at higher zoom levels or the color attenuated. Plus could OSM Forest areas be replaced by a more uniform landcover info extracted from Landsat imagery?

**Comment by pierzen** [comment]
Ok if I follow you, Well let's keep territories like Canada a «Blank Map», a no «OSM territory».

**Comment by math1985** [comment]
> For areas like Canada, major railways (based on length ?) should be rendered at z5

Could you please expand a bit on why they should be kept?

**Comment by pierzen** [comment]
For railways and airports, we should use the same arguments as major roads. Why do we keep these at lower zoom? Because they are the major way to circulate. In case of low density territories, the only access to some part of the territory is by railway or airplane. We need rules that adapt to various types of territory.  General rules like the actual ones do represent well the western europe, but Europe is not representative of other parts of the global map.

**Comment by kocio-pl** [comment]
> General rules like the actual ones do represent well the western europe, but Europe is not representative of other parts of the global map.

Of course, but please note, that it's also true for Canada - in fact, no part of the world is representative for the whole planet. The world is not uniform, hence there will be always problems. And it's one thing to have policy how should it look like (and I share your concerns), but the other how to achieve it and this is where we stucked.

Resolving #1957 is the only hope to make a change. Until we know how exactly make a difference (PR would be preferable), I wouldn't like to apply such policy, because urban areas would be unreadable at the cost of nice rural areas.

**Comment by kocio-pl** [comment]
I like the subject of this issue, as it moves us forward, but the proposed method still feels foreign to me.

>    Roads on z5
> I'm in favour of dropping rendering.

>    Railways on z7
> I guess people who like tracing railway lines to see along which route they are travelling (including me) can zoom in one zoom level more. So I'd say drop.

The weakness of the use cases is it does not tell us what zoom level would be good for them. We can only say they are useful for route planning, to see the transportation network overview and that they're general enough to be on this map - just not when to start showing them. But we already know that we want to show them somwhere.

For me it's still the old good "they are too dense/visible in some places" ([roads](https://github.com/gravitystorm/openstreetmap-carto/issues/1935)) or "they're not visible enough anyway and just add some clutter" (railways) which works better. I guess you're right with roads and railways, but use cases don't explain why roads should be visible on z6+ while railways on z8+.

>    National parks on z7
> I'm in favour of dropping. I fail to see how the current rendering is useful for any purpose.

So what's the use case for national parks at all? For me it's that they are big and are related to leisure in some cases. But the size is different and some of them really look well on z7 even individually (and can still be visible as a group on z5+, I guess). Lack of use case would rather mean to drop rendering them at all, not just "show them later" (I know that we're testing limited zoom level range).

My take: if we have something other to show here, we might move parks later, so it depends on what we have tagged and we know how to show it. BTW: maybe if we have more background, roads would stop dominating the space and should stay on z5+? It's also more context related than use casing shows.

**Comment by math1985** [comment]
>  the proposed method still feels foreign to me.

As I said, this is also a new approach for me, so if it doesn't work out we'll find out soon enough...

> The weakness of the use cases is it does not tell us what zoom level would be good for them.

Maybe in this particular case yes, but for the roads I think it was quite useful. We can be quite sure that we won't start planning routes on z5.

The disadvantage of the 'too dense' method is that we're trying to render as much as possible ('cram as much as possible in the map') without considering whether the information we're giving is useful. A map that is not filled with information as much as possible might be better legible.

The difference between roads and railways, in my opinion, is that road users will base their itinerary on the map, while railway users probably will base their itinerary on an (online) route planner. For example, somebody travelling from Warsaw to Krakow cannot / will not use the map to see if he should travel over Radom-Kielce, Wlosczowa or Piotrkow-Trybunalski (at least with the current state of the map, where we don't distinguish between long-distance railways and others). The same holds in Canada for somebody travelling from Winnipeg to Saskatoon for example.

On higher zoom levels, like from z10, using the map for train route planning seems to work better. For example, for any of the towns villages around Warsaw visible on z10 it is clear by which train line how to get there.

> So what's the use case for national parks at all? For me it's that they are big and are related to leisure in some cases. But the size is different and some of them really look well on z7 even individually (and can still be visible as a group on z5+, I guess). Lack of use case would rather mean to drop rendering them at all, not just "show them later" (I know that we're testing limited zoom level range).

Some usecases could be 'Trying to find a known famous nature reserve', 'Understanding what the area is used for'. Probably you wouldn't look for the Kampinoski national park at z7, and knowing there is a national park east of Warsaw is not very relevant at that zoom level either. However, at z10, it is very interesting to know that there is a large national park there. That leaves z8 and z9 as zoom levels to be discussed.

> BTW: maybe if we have more background, roads would stop dominating the space and should stay on z5+? It's also more context related than use casing shows.

Yes, I think that's a very good point. Another way to see it: the amount of map subject matches the amount of map context. It doesn't make sense to render subject for which we have no context (all railway lines in Germany at z7 of which you have no idea where they lead to, or all national parks in Poland on z7).

This is basically the same as the external link we had earlier about not rendering roads for which we don't render the cities they connect, versus rendering cities without showing the relevant roads.

**Comment by kocio-pl** [comment]
> Maybe in this particular case yes, but for the roads I think it was quite useful. We can be quite sure that we won't start planning routes on z5.

Of course. My use case would be "transportation network overview" (this not hypothetical - I really do it, similar to what Mateusz said about road network).

> Another way to see it: the amount of map subject matches the amount of map context. It doesn't make sense to render subject for which we have no context

:+1: - it's a very useful general rule.

**Comment by math1985** [comment]
I have updated the USECASES file based on the last merge (as it's a meta file, let's update it directly and not work with PR's. We could perhaps also consider using an issue to track the info in the file).

I added some last things on which we need to decide whether we have a usecase:

* Glaciers and icesheets on z6 and z7
* Military areas on z7
* Ferry routes on z7
* Island names on z5/6/7

**Comment by matkoniecz** [comment]
>  let's update it directly and not work with PR's

I think that PRs are better, but even if we switch to direct changing I prefer to ask

> Long distance road trip planning | Motorways

I think that trunk roads also should be here - in countries without motorways trunk roads are (supposed) to form network of the most important roads, forming basic road network.

**Comment by matkoniecz** [comment]
> Military areas on z7

Where one may see them on z7? I found USA, Russia-Finland border and Russia ( http://www.openstreetmap.org/#map=7/59.809/29.465 )

**Comment by math1985** [comment]
> I think that PRs are better, but even if we switch to direct changing I prefer to ask

Fine.

> Where one may see them on z7? 

There's also one in the baltic between Sweden and Poland, and one in western Canada.

**Comment by math1985** [comment]
As we don't render any landcover features on z6/z7, I'm considering removing glaciers and icesheets from z6/z7.

**Comment by kocio-pl** [comment]
I have added it (together with other natural and semi-natural objects) as a use case in #2946, so it depends if we accept it and how long could it take.

**Comment by math1985** [comment]
Rendering of (inland) ferries leads to a lot of noise on z7, while the ferries are not really detectable otherwise.

This is the Rotterdam area (ferries only), z7:

<img width="150" alt="screen shot 2017-11-12 at 21 46 28" src="https://user-images.githubusercontent.com/5251909/32703235-07ccb158-c7f3-11e7-8d10-2138065d6055.png">

You can see the same effect in the Swiss' lakes.

**Comment by kocio-pl** [comment]
I don't think this has anything to do with use cases. But I also don't know what is the problem exactly? We might probably just cut short lines (`way_lenght`?), but there are some other legitimate and easy to see short ferry lines.

**Comment by math1985** [comment]
Some areas where the amount of water is currently a bit overwhelming / giving more information than useful and distracting from the useful information:

<img width="237" alt="screen shot 2017-11-20 at 12 58 18" src="https://user-images.githubusercontent.com/5251909/33017426-95301eb8-cdf2-11e7-9b16-d53cfd711a13.png">
<img width="151" alt="screen shot 2017-11-20 at 12 58 11" src="https://user-images.githubusercontent.com/5251909/33017427-954745de-cdf2-11e7-9f66-44a8c6098ebf.png">
<img width="159" alt="screen shot 2017-11-20 at 12 57 48" src="https://user-images.githubusercontent.com/5251909/33017429-955ba4e8-cdf2-11e7-922e-12e1c198eb7c.png">

**Comment by kocio-pl** [comment]
> Is there a reasonable usecase for ferry routes on z7? I would be happy to remove them altogethr from this zoomlevel.

I don't feel they are visual problem (only Baltic Sea area can be seen as such), but moving them later won't be a problem for me.

**Comment by kocio-pl** [comment]
> Some areas where the amount of water is currently a bit overwhelming / giving more information than useful and distracting from the useful information:

The question is - what filter do we want to use and up to which zoom level?

**Comment by math1985** [comment]
@rrzefox would it be possible to test this on your server?

**Comment by math1985** [comment]
> The question is - what filter do we want to use and up to which zoom level?

Good question. I created #2952 and will respond there.

**Comment by kkofler** [comment]
How is displaying less information an improvement? And why is planning long-distance road trips a use case, but planning long-distance train trips not? (Relying exclusively on the train company's routing algorithm is not going to work, their routing software will just time out if you ask it to compute long routes without splitting at suitable points.) Major railroads ought to be shown at a lower zoom level. I know that OSM is historically the Open**Street**Map, but it has grown into mapping much more than just streets and the focus exclusively on streets is unhelpful. Going by train is nicer to the environment than going by car or plane.

**Comment by polarbearing** [comment]
There are map styles specialised on public transport. 
When it comes to routing, which is not an issue for the carto style here, railways are significantly different from road routing, as they depend on schedules and connectivity. 
The bugs in railway provider's routing engines are also irrelevant for this style.

**Comment by matthijsmelissen** [comment]
> And why is planning long-distance road trips a use case, but planning long-distance train trips not? 

I commented on that here:
https://github.com/gravitystorm/openstreetmap-carto/issues/2925#issuecomment-342471121

**Comment by matthijsmelissen** [comment]
As we decided on these issues now, I am going to close this issue.
