### ISSUE TITLE
Add icon for shop=music

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#2929]
https://wiki.openstreetmap.org/wiki/Tag:shop=music
4503 uses (https://taginfo.openstreetmap.org/tags/shop=music)

I suggest using the same icon as amenity=nightclub but in shop-icon purple.

**Comment by kocio-pl** [comment]
Makes sense for me.

**Comment by kocio-pl** [comment]
It's better if we don't rely just on the color as a distinctive feature, so I prefer using different note shape (which should be easy - probably ♪). But since this is a record store, maybe there is something more resembling records (like half a disc visible from the sleeve)? We have some freedom here, which is good.

**Comment by lakedistrictOSM** [comment]
Some quick sketches of possible icons:
![cd7](https://user-images.githubusercontent.com/20193716/32519231-f51a8492-c403-11e7-982a-a9721b884e4a.png)

And my first attempt at an svg icon at 14x14: (.png copy)
![music-14-v03](https://user-images.githubusercontent.com/20193716/32519253-0a677d5a-c404-11e7-9722-b416d633e305.png)
(not very clear so needs improving)

**Comment by kocio-pl** [comment]
Thanks, it's exactly what I've been thinking about to try.

From my experience: it's better to show only 14 px PNG versions (with links to SVG probably), because nice large scale design can make a better impression than it actually will look like on the map. I also number them to make it easier to discuss.

**Comment by lakedistrictOSM** [comment]
Thanks for the tips. Here's a few more ideas based on the record/disc theme:

2) ![music-14-v04png2](https://user-images.githubusercontent.com/20193716/32568910-860091f0-c4b7-11e7-8a5c-899535edacba.png)
3) ![music-14-v05png2](https://user-images.githubusercontent.com/20193716/32569032-dd2b1d6a-c4b7-11e7-8fac-7c8dc7907309.png)
4) ![music-14-v06png](https://user-images.githubusercontent.com/20193716/32569155-3192ed92-c4b8-11e7-8aa5-f4b7369a1bc6.png)
5) ![music-14-v07png](https://user-images.githubusercontent.com/20193716/32569269-912f1f28-c4b8-11e7-81c6-eca878b490b1.png)
6) ![music-14-v08png](https://user-images.githubusercontent.com/20193716/32569762-f7c65d86-c4b9-11e7-8c92-a3a99c02f84a.png)
7) ![music-14-v09png](https://user-images.githubusercontent.com/20193716/32569922-8688f8bc-c4ba-11e7-8484-d74697309861.png)
8) ![music-14-v10png](https://user-images.githubusercontent.com/20193716/32570162-35c7871c-c4bb-11e7-9a87-63de1db1ef54.png)

**Comment by kocio-pl** [comment]
I like 6 the most and I think the note could be probably thicker - the disc can take even just a half of space, if needed (as in 1-5), and would be still recognizable, I guess. Another quite clear picture is 7 for me.

**Comment by lakedistrictOSM** [comment]
Thicker note half disc:
9) ![music-14-v11png](https://user-images.githubusercontent.com/20193716/32570867-73fdaf3c-c4bd-11e7-8695-6713a0da1635.png)
Thicker note whole disc:
10) ![music-14-v12png](https://user-images.githubusercontent.com/20193716/32570959-cccdbec2-c4bd-11e7-843b-992e70f51dac.png)
11) ![music-14-v13png](https://user-images.githubusercontent.com/20193716/32571217-90cd376c-c4be-11e7-8232-a590f55ac964.png)

**Comment by kocio-pl** [comment]
9 seems good enough for me, but please give the links to all of them just in case. 

Could you make a PR and test rendering (probably using Docker would be easiest)?

**Comment by lakedistrictOSM** [comment]
I need to correct the colours in them first, there's some white where it should be transparent, and I also have no experience of using Docker, so it will be a while before I can make a PR and test. :)

**Comment by Jotam** [comment]
They look great! 9) is okay. 
But I would even prefer 11). The whole disc makes it somehow clearer to me.

**Comment by kocio-pl** [comment]
@lakedistrictOSM Any news? Do you need some help?

**Comment by lakedistrictOSM** [comment]
@kocio-pl I've been busy recently so I haven't done much more on it yet, I'll give you a shout if I need any help :)

**Comment by Mxdanger** [comment]
> But I would even prefer 11). The whole disc makes it somehow clearer to me.
I would have to agree with that. The half-disc design doesn't look quite right.

**Comment by Jotam** [comment]
@lakedistrictOSM Any progress there? I would love to see this icon included soon. It looks great!

**Comment by lakedistrictOSM** [comment]
@kocio-pl :( Unfortunately I can't proceed any further with this icon - I can't change the white areas to transparent. Probably the best way forward is for someone to redraw it - all parts pixel aligned, CD edges 1 pixel thick centered in middle of grid, music note (cropped from nightclub icon) is 2 pixels wide.
![image](https://user-images.githubusercontent.com/20193716/37167708-9c6ba6d6-22fa-11e8-885b-5d46d9045998.png)
Or https://gist.github.com/lakedistrictOSM/ca42a78c33fe982544911e9283bd88b5

Hopefully someone with the right skills can take it from here. :)

**Comment by kocio-pl** [comment]
OK, thanks for your design work!

**Comment by Tomasz-W** [comment]
Gist link with clean SVG:   https://gist.github.com/Tomasz-W/09338c6cf9635ae63f7d5dda6fc3e9ba

**Comment by kocio-pl** [comment]
Thanks! 

So who wants to make a PR? @Jotam would you like to try?

**Comment by james2432** [comment]
Added the pull request, first time editing this, so go easy ;)

**Comment by kocio-pl** [comment]
Resolved by #3123.
