### ISSUE TITLE
Add terrain relief data

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#2931]
I think about adding terrain relief data and here's a basic shopping list:

1. Kind of terrain sculpture is missing not only in this style, but also in OSM in general. We have only peak, saddle and embankment tags and it doesn't look like this project is capable of having much more details about it. So it means using external data.

2. I believe contour lines are too detailed and don't belong to general style (they are used for example in the cycling layer on OSM website) and using colors would be also too intrusive and not blending well with our color usage (OpenTopoMap uses relief colors [up to z8](https://opentopomap.org/#map=8/51.3769/-0.1071), and then changes the meaning of colors on z9+, which is confusing to me). It means we should probably use hillshading, which is not too disturbing, yet shows the basic shape of a terrain - you can taste it also on cycling layer.

3. We use some data from Natural Earth project and there's also a [1:10m Shaded Relief](http://www.naturalearthdata.com/downloads/10m-raster-data/10m-shaded-relief/) and [1:50m Manual Shaded Relief](http://www.naturalearthdata.com/downloads/50m-raster-data/50m-manual-shaded-relief/). It looks like precise enough to me.

The problems are (1) if we decide to add such data to our style - that means discussing how useful or how disruptive is that - and in case we decide to use it, (2) how to do it exactly.

I would like to test hillshading myself, but I don't know where to start, so any hints and help with that would be welcome.

**Comment by math1985** [comment]
Im against. The map is alreaady busy enough, and this project is about showcasing osm data.

**Comment by matkoniecz** [comment]
I am also against - it is supposed to show primarily OSM data and it would cause problems with cases where OSM data mismatch relief data (for start: sloped lakes, natural=peak/saddle mismatching relief data).

I believe that everything wrong visible in this style should be fixable by editing OSM data, without tagging for renderer.

Iff there was some open, high-quality, preprocessed to remove mismatches from OSM data relief data I would consider this, but AFAIK there is nothing like this.

**Comment by math1985** [comment]
Closing the issue.

**Comment by kocio-pl** [comment]
Thanks for you comments.

> Im against. The map is alreaady busy enough, and this project is about showcasing osm data.

The argument about being busy is not true for low level and I don't expect it ever will. We don't have to show hillshade for all zoom levels, it's the most important for low zoom. 

> I am also against - it is supposed to show primarily OSM data and it would cause problems with cases where OSM data mismatch relief data (for start: sloped lakes, natural=peak/saddle mismatching relief data).

I think for the low zoom there shouldn't be such cases. I also believe that in some cases mismatch could be on our side and it should be good to indicate problems.

BTW: @gravitystorm What kind of hillshade data do you use in your maps? Did you found any problems with it?

> Iff there was some open, high-quality, preprocessed to remove mismatches from OSM data relief data I would consider this, but AFAIK there is nothing like this.

It makes sense for me, so it's worth asking the community about it.

**Comment by matkoniecz** [comment]
examples of problems: http://www.openstreetmap.org/#map=15/49.2390/20.0082&layers=C

lake mismatching relief data, waterway not going in the lowest part of valley

![selection_021](https://user-images.githubusercontent.com/899988/32694975-9cffe898-c74f-11e7-8a25-5caa7807e610.png)

note one more issue: relief data would need to be updated regularly to match OSM updates. I really doubt that we will have satisfying source of such data soon.

**Comment by kocio-pl** [comment]
Possible solutions to avoid problems with external data:
1. Use [hand crafted version](http://www.naturalearthdata.com/50m-manual-shaded-relief/manual-shaded-relief/) of hillshading (by [Tom Patterson](https://en.wikipedia.org/wiki/Tom_Patterson_(cartographer))).
2. Use gamma - hillshading on higher zoom levels would be less visible than on low zoom levels.

Please note that I don't want to use contour lines and hillshading is less strict.

**Comment by kocio-pl** [comment]
Example of hillshading on osm-carto can be seen on Hike&Bike map (use "OSM Mapnik" and "Hillshading" or "Hillshading (exaggerate)" layers):

http://hikebikemap.org

They stop rendering hillshading on z16 (and the base map at z17). 

I guess we could stop at z11 or maybe z12, so there is 1-2 zoom levels when we can see the general hillshading with peaks, but it'd be better if hillshading would be gamma-lightened there, so it's not just abruptly disappearing at z13. That would help us show relief on low zoom, where it is mostly needed as a natural feature, let us see if peaks and hillshading are more or less synchronized, but don't get into hard details of relief.

**Comment by vince-from-nice** [comment]
I think having the relief display on osm.org's standard rendering would be a huge advantage.

Not only the map would be much more beautiful but it would also be much clearer because the relief, when there is one, makes it easier to find things.

Ideally I would like to have both the level lines and the hillshades that complement each other very well.

Regarding the problems observed on lakes and rivers, I find that they are not really shocking in addition to being relatively rare. And they could even be used to detect problems that would be on the side of OSM.

In addition, the relief display could be an option (as well as the display of notes or data) and therefore with a small checkbox that would be disabled by default.

Is this issue definitely closed? ;)

**Comment by vince-from-nice** [comment]
Another website with beautiful rendering: http://opensnowmap.org (in the settings you can also choose the default rendering of OSM)

**Comment by vince-from-nice** [comment]
_note one more issue: relief data would need to be updated regularly to match OSM updates._
I don't understand why, could you please detail ?

**Comment by matkoniecz** [comment]
>  I don't understand why, could you please detail ?

Outdated relief data may result in a confusing map in places where OSM data was updated and terrain shape shows an old state.

It would affect primarily high zoom level as large-scale terrain changes are fairly rare.

**Comment by kocio-pl** [comment]
> Is this issue definitely closed? ;)

I still think it would be useful, but since we just don't have any new things to discuss, it doesn't matter to me if it's open or closed. Ticket is just a way of organizing things.

> In addition, the relief display could be an option (as well as the display of notes or data) and therefore with a small checkbox that would be disabled by default.

This is the ticket to be open in this project:

https://github.com/openstreetmap/openstreetmap-website/issues

**Comment by kocio-pl** [comment]
Some informations about hillshade rendering:

https://wiki.openstreetmap.org/wiki/Shaded_relief_maps_using_mapnik

**Comment by vince-from-nice** [comment]
Thanks for the link, very good page.

What a pity that the relief is not present directly on www.openstreetmap.org
.

2018-03-15 11:48 GMT+01:00 kocio-pl <notifications@github.com>:

**Comment by vince-from-nice** [comment]
Thanks for the link, very good page.

What a pity that the relief is not present directly on the official site of
OSM.

Thanks

2018-03-15 11:48 GMT+01:00 kocio-pl <notifications@github.com>:

**Comment by kocio-pl** [comment]
Well - it is, but on the other map "layer" than a default one:

https://www.openstreetmap.org/#map=8/46.766/10.341&layers=C

**Comment by vince-from-nice** [comment]
Sure, it's better to have that layer on osm.org than nothing but for me
it's not usuable because it's too much specific for bike&hike. What I want
is the relief and the display of all (or almost) the data present in the
OSM DB (like the default layer).

Futhermore the hillshade rendering is not very good if you compare it to
other maps like www.opensnowmap.org for example.

2018-03-15 21:03 GMT+01:00 kocio-pl <notifications@github.com>:

**Comment by matthijsmelissen** [comment]
FYI, https://osm.ch/# now renders our style with relief and contour lines.

**Comment by kocio-pl** [comment]
After few days of inspecting it randomly, I'm deeply impressed how smooth current osm-carto blends with relief shading (and also with contour lines, even if I'm not interested in them).

**Comment by kocio-pl** [comment]
For z8+ it's also possible to see the osm-carto with hillshading for the whole planet using historical map with specific set of layers - for example:

http://gk.historic.place/historische_objekte/translate/en/index-en.html?zoom=8&lat=46.97647&lon=9.25604&pid=GsSa
