### ISSUE TITLE
make wikidata tag a clickable link

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [gravitystorm/openstreetmap-carto#2937]
Hi,

Would it be possible to make wikidata tag a clickable link?

Together with
name:etymology:wikidata
operator:wikidata
network:wikidata
brand:wikidata
artist:wikidata
subject:wikidata
architect:wikidata

Many thanks,

Polyglot

**Comment by math1985** [comment]
The output of this project is a map that has the form of an image, so no, within this project we cannot create clickable links.

If you would like to have clickable links on the openstreetmap.org website, try https://github.com/openstreetmap/openstreetmap-website .

**Comment by PolyglotOpenstreetmap** [comment]
When looking at the details of an object.

**Comment by giaccai** [comment]
But still now the item Wikipedia is a link.  Susanna

**Comment by math1985** [comment]
Yes, but what I was trying to say is that this project is not responsible for that part of the website. This project only handles the map itself, not the userface around it (including the details of objects).

You can report an issue at https://github.com/openstreetmap/openstreetmap-website .

**Comment by HolgerJeromin** [comment]
The feature you requested is already implemented: https://github.com/openstreetmap/openstreetmap-website/pull/788
For example here: http://www.openstreetmap.org/node/1080146569

**Comment by PolyglotOpenstreetmap** [comment]
I misunderstood Susanna's problem. We are telling her to use name:etymology:wikidata instead of wikidata/wikipedia pointing to a person, but those links are not clickable on the main website. It doesn't seem this will be solved on that side and it's  not an issue on the rendering side.
