### ISSUE TITLE
Boundaries of Australian state forest parks, and New Zealand forest and regional parks not shown

### ISSUE THREAD

**Issue by ljbade** [gravitystorm/openstreetmap-carto#2944]
I have noticed an anomaly in the drawing of park boundaries in Australia and New Zealand compared to US.

In the US state parks are drawn with a slightly lighter green border compared to national parks. In Australia and New Zealand only national parks and nature reserves are given a boundary.

I think that Australian state forest parks, and New Zealand forest parks and regional parks are drawn with this same lighter boundary as US state parks.

I am not familiar with the way the style sheets work, but am happy to help show examples of the relevant tags.

**Comment by matkoniecz** [comment]
Can you link examples of affected objects?

**Comment by math1985** [comment]
> In the US state parks are drawn with a slightly lighter green border compared to national parks.

No, this is not correct. US state parks and national parks are rendered the same.

As this does not seem to be a bug report, I'll close this issue. However, feel free to respond if you have further questions.

**Comment by matkoniecz** [comment]
In general, please always give example. I am sure that it is tagging issue (one area tagged multiple times, green seems stronger/weaker due to green background) or it is #1940

**Comment by ljbade** [comment]
Sorry I was travelling last few days so didn't have chance to reply. I'll dig up some examples and the relevant tags.

If US treats national and state parks the same, are the US state parks tagged as national parks?
