### ISSUE TITLE
Parkings are not yellow anymore?

### ISSUE THREAD

**Issue by riiga** [gravitystorm/openstreetmap-carto#2947]
Why did the colour of parkings suddenly change? It looks terrible now, especially in residential areas where you can't distinguish parkings very easily anymore. :-1:

**Comment by HolgerJeromin** [comment]
Ref  #2904

**Comment by riiga** [comment]
Yeah, and I disagree with colour change. Parkings should be prominent. Having them grey also makes the difference between a surface parking and a parking garage hard to tell.

**Comment by HolgerJeromin** [comment]
This style is no car or parking map.

**Comment by riiga** [comment]
No, but parkings are a typical landuse, and should be rendered as such.

**Comment by kocio-pl** [comment]
I have tried to get into details as much as it's possible in this reasoning: https://github.com/gravitystorm/openstreetmap-carto/pull/2934#issuecomment-344256244.

In short - it was _too easily_ to distinguish them. I think that they are not typical landuse - they make a part of different landuses, so should be weaker, and yet they were _stronger_ than most of them, so it seemed that they are super important.

**Comment by math1985** [comment]
Please continue the discussion in #2934.

**Comment by imagico** [comment]
@math1985 - the creator of this issue reported a problem that exists and for which no other issue is currently open.  Closing this issue for reasons other than wontfix or because there is a change fixing it and deferring discussion to the merged PR creating the issue would be a major change in procedure in this project and it also would not work in general since issues are not always the result of a single identifiable change (the difficulty to distinguish between residential areas and parkings is the result of both the parking color and the residential color).

If you think this issue does not need to be addressed make a clear statement to that end and close it as wontfix - otherwise please leave it open.

**Comment by kocio-pl** [comment]
I guess you're right, it's not quite the same as "Parking too prominent". However this is secondary problem for me - the most important thing now is discussing the change, not the state of the ticket, as the conversation is not locked.

@riiga (or anybody else, for that matter), please respond what do you think is wrong/missing/not clear with my reasoning. There were other possibilities discussed that I thought were not sufficient, but maybe there was something else we could improve?

**Comment by riiga** [comment]
I accept that parkings could be made less prominent, but grey is not really an ideal colour. It's not easily distinguished from the colour of residential landuse and grey makes surface parkings hard to tell from parking garages (which are also buildings). There was a proposal for a lighter shade of yellow which I think looked quite good as a compromise. Perhaps private parkings could be rendered less visibly to reduce clutter, as already done with the faded P.

**Comment by kocio-pl** [comment]
I'm not sure which part of discussion did you read, but it all has been already discussed.

Lighter yellow was rejected as almost identical to societal amenities (schools, hospitals etc.). Private parkings are not the main problem (about 10%), so solving it does not change too much - the bad examples I saw were mainly simple public parkings with open access.

What other color or solution would you propose? I feel light gray works well on residential landuse - it's closer to the land color than residential areas.

**Comment by kocio-pl** [comment]
I will close this issue, because nothing new has been proposed or reported. It can be reopened if needed later, of course.
