### ISSUE TITLE
Render highway=turning_loop

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#295]
This value was added for `turning_circle`s that have a non-traversable islands in the middle.

[Here](http://i.imgur.com/Zhs6dut.png) is a photographic example (I thought the wiki's photo was insufficient). Admittedly, it's lifted from Google StreetView as I couldn't find a more fitting photo online... let alone a freely-licensed one.

[Wiki page](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_loop). I personally think the best rendering for this would be the rendering used for `turning_circle` but with a rounded dot in the middle.

**Comment by boothym** [comment]
Revisiting this as I'm adding it as a preset to iD https://github.com/openstreetmap/iD/issues/3557 - and I noticed the rendering of both the loop and circle are the same.

Can a black circle please be added to the middle of turning_loop, to differentiate it from turning_circle?

**Comment by HolgerJeromin** [comment]
Rendering this like highway=mini_roundabout would be better, yes. But please open a new issue for that.
