### ISSUE TITLE
Office type PoIs rendered like address PoIs

### ISSUE THREAD

**Issue by andrzej-r** [gravitystorm/openstreetmap-carto#2953]
In case of company office PoIs, and likely most other office PoIs, the most important bit of information is is the name tag. Currently, these PoIs are rendered as house numbers, just like address PoIs. This is not useful and often redundant, as many offices may share the same house number, which then gets repeated multiple times. 

The online editor is already rendering these PoIs as an office icon + name, which makes sense to me. This (rendering names) is also consistent with most other types of PoIs, such as shops or restaurants. 

A side effect of this limitation is that many contributors map offices as addresses, usually by adding a company name to an existing address PoI. In either case they get the same result, so it is easy to miss the mistake.

**Comment by math1985** [comment]
Thank you for your report! This is already being discussed in #108 and #1697 so I will close this issue - feel free to join the discussion in the other issues, or even better, propose a pull request.
