### ISSUE TITLE
Stream names should not render in lakes or reservoirs

### ISSUE THREAD

**Issue by pigsonthewing** [gravitystorm/openstreetmap-carto#2967]
Where a stream or river is "routed" through a waterbody such as a lake or reservoir, the stream name is shown; please do not do this.

Example, annotated, screenshot - from https://www.openstreetmap.org/#map=16/52.4581/-1.9251  - attached. Ways involved are:

https://www.openstreetmap.org/way/23771443
https://www.openstreetmap.org/way/80997081

![screenshot-2017-12-3 openstreetmap](https://user-images.githubusercontent.com/89541/33528893-8a9da330-d860-11e7-925e-23dc18a02423.png)

**Comment by matthijsmelissen** [comment]
Hi Andy! Good to hear from you again.

I'm actually not quite sure about the desired behaviour. Would you say the stream runs through the pool? In that case, rendering the stream name doesn't sound that strange to me. If you wouldn't say the stream runs through the pool, I guess the tagging is wrong.

**Comment by pigsonthewing** [comment]
Yes, the stream logically run through the pool, but the labelling is cluttered, and belongs outside such areas, since the pools themselves have other names.

**Comment by dieterdreist** [comment]
2017-12-03 23:31 GMT+01:00 Andy Mabbett <notifications@github.com>:

> Yes, the stream logically run through the pool, but the labelling is
> cluttered, and belongs outside such areas, since the pools themselves have
> other names.
>


technically, rivers and streams that enter a lake, pool and leave it again
(keeping their name or not), are still not streams while in the pool / pond

**Comment by pigsonthewing** [comment]
I don't think tat;s a common view; and certainly not a unanimous one. This is how I was taught to map, and have always mapped, with no complaints.

And when one gives the "total" length" of a stream, it includes any lakes etc. that the stream passes through.

**Comment by dieterdreist** [comment]
sent from a phone

> On 5. Dec 2017, at 19:41, Andy Mabbett <notifications@github.com> wrote:
> 
> I don't think tat;s a common view; and certainly not a unanimous one.


rivers and streams are watercourses with a current, which drops in lakes, that is why inside the lake there is no river/stream.

**Comment by matthijsmelissen** [comment]
Even in Germany that’s not a generally accepted truth:

https://en.m.wikipedia.org/wiki/Seerhein

**Comment by dieterdreist** [comment]
> On 6. Dec 2017, at 01:12, Matthijs Melissen <notifications@github.com> wrote:
> 
> Even in Germany that’s not a generally accepted truth:
> 
> https://en.m.wikipedia.org/wiki/Seerhein
> 


I wanted to bring the same example up to support what I had written (rhine inside lake constance doesn’t exist, these 4 kilometers of the outflow only support this, as that’s a tiny part at the 
end of the lake)

**Comment by kocio-pl** [comment]
Isn't it rather a tagging problem than rendering issue?

**Comment by matkoniecz** [comment]
I am not convinced that this tagging is wrong, but I have no strong opinion.

**Comment by polarbearing** [comment]
From the waterway perspective it would probably be correct to draw the middle line of the river across the lake, wouldn't it? Otherwise you would lose connectivity for waterway routing. 

Would it be technically possible to suppress the river labelling when it runs through a water body with a different name? (we must not suppress within a water body in general since wider rivers are mapped as area as well)

**Comment by HolgerJeromin** [comment]
> Would it be technically possible to suppress the river labelling when it runs through a water body with a different name?

We could render lakes area later (on top of river lines)

**Comment by matkoniecz** [comment]
It would resume in labels on edges of lakes to be partially hidden, partially visible.

**Comment by kocio-pl** [comment]
I agree with @Tomasz-W on that, so I'm closing this ticket without any action.
