### ISSUE TITLE
Docker Toolbox

### ISSUE THREAD

**Issue by OnkelTem** [gravitystorm/openstreetmap-carto#2980]
Hi everybody!

This ticket is only indirectly related to *OpenStreetMap Carto* project so excuse me if this is in some way against the rules. I plan to use it as a sort of newsfeed on development progress of "Toolbox" first mentioned in this thread #2928. Basically it's gonna be a tool to work with different styles without  complicated and time-consuming system configuration but instead - by issuing just a couple of commands.

At the present moment there is a project https://github.com/OnkelTem/osmcarto-docker which may or may not be a precursor of the future Toolbox. You can check it out to see how OSM Carto works there. 

Priority tasks for now:
* Isolate styles into a separate directory
* Add OSM Bright style
* Create a docker image with TileMill and get it running smoothly with the styles
* More to come

Related issues: 
#2928, #2913 
related pr:
#2914

**Comment by kocio-pl** [comment]
I guess that is enough to make people aware of this project, however tickets are not the best way of communicating things and we have more than enough open issues about real osm-carto stuff, so I will close it now. Good luck, anyway!
