### ISSUE TITLE
Rendering of amenity=archive

### ISSUE THREAD

**Issue by stefannagy** [gravitystorm/openstreetmap-carto#2983]
Please consider rendering objects with the amenity=archive tag. In my view you could use the same symbol you use for amenity=library.

**Comment by HolgerJeromin** [comment]
Right now we have 31 objects with this tag and no good documentation for it.
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Darchive

This is much too early for rendering this tag.

**Comment by stefannagy** [comment]
The thing is at least I tagged archives as libraries until now, because it's the easy way to get them rendered. There are quite a lot of archives out there…

**Comment by kocio-pl** [comment]
I don't think it's of use for general public, unlike the library.

**Comment by matkoniecz** [comment]
Closing per @HolgerJeromin

**Comment by polarbearing** [comment]
> I tagged archives as libraries until now, because it's the easy way to get them rendered

This is classic [Tagging for the renderer](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer), please don't do that. There are other tools to visualize lower-frequency tags.

As for a potential icon (should the feature be tagged more frequently), the library icon is unsuitable, since an archive is typically not as public as a typical library, so using the same icon would be misleading.

**Comment by stefannagy** [comment]
> This is classic Tagging for the renderer, please don't do that. There are other tools to visualize lower-frequency tags.
You are right, sorry. I'm going to correct that.

> I don't think it's of use for general public, unlike the library.
Only a small part of general public uses libraries and an even smaller part uses archives. That's true. But archives are (at least in my view) important memory institutions just like libraries or museums and parts of cultural property. So it seems quite strange to me that every small shop=beauty or shop=mobile_phone is rendered while archives are not…

However, thanks for your replies!

**Comment by kocio-pl** [comment]
> So it seems quite strange to me that every small shop=beauty or shop=mobile_phone is rendered while archives are not…

Probably it makes more sense when you think about general map for plain user - I guess shops are more usable than offices and institutions most of the time, which doesn't mean they are more important for culture.

**Comment by polarbearing** [comment]
As the archive would be either a building or a commercial landuse, its name would render regularly with these tags.

**Comment by stefannagy** [comment]
> Probably it makes more sense when you think about general map for plain user - I guess shops are more usable than offices and institutions most of the time, which doesn't mean they are more important for culture.

What is useful and what isn't is very subjective. We are all plain map users and we are all interested in different things, look for different places.

In my view it makes no sense to argue about the relevance of objects. But it does makes sense to me that you don't decide to render objects which seem to be irrelevant to the vast majority of mappers. If there were (much) more objects with this tag (than 36 worldwide) and good documentation I guess nobody would argue that it's a bad idea to render archives. Mappers decide what is relevant in OSM and that's a good thing.

> As the archive would be either a building or a commercial landuse, its name would render regularly with these tags.

Thanks, I know but the archives I'm looking at are all located in bigger buildings, so that doesn't help.

**Comment by kocio-pl** [comment]
While it is always subjective, we have to think about relevance. The tag popularity is a hint, but it's not enough IMO. However in this case we have some other amenities and offices which should be rendered before we start to think about archives, like #271.

**Comment by stefannagy** [comment]
> However in this case we have some other amenities and offices which should be rendered before we start to think about archives, like #271.

In my view that's a completely different thing. In this context it makes much more sense to compare archives to beauty salons than to government offices…

If most archives were closed to the general public I wouldn't ask for a symbol on the map – just because they are important parts of cultural property. I was asking for a symbol because most archives in fact _are_ intended for the general public (everyone looking at the map).

I guess no one would argue that government offices are irrelevant. But they are _not_ intended for the general public. So why do you want a symbol for these offices? I get the feeling I misinterpreted the meaning and purpose of symbols on the map all along…

**Comment by kocio-pl** [comment]
> I get the feeling I misinterpreted the meaning and purpose of symbols on the map all along…

I don't feel like that. In my opinion the only universal property for general map would be size (and we use it in many cases if possible), all the other features are just hard to evaluate, so anyone can have a different view what's more or less important. Still just a dozen objects tagged as `amenity=archive` is far too few to consider them before some other, much more popular objects.
