### ISSUE TITLE
Names on footway=sidewalk make map hard to read

### ISSUE THREAD

**Issue by ghost** [gravitystorm/openstreetmap-carto#2986]
Please don't display `name` tags in combination with `footway=sidewalk` as this results in a confusing map (see [example](http://www.openstreetmap.org/#map=18/46.93800/7.44800)).

Note that `name` tags are important for pedestrian navigation applications to provide useful instructions like 'follow (the footway along) Powder Mill Lane' instead of 'follow the footway'.

**Comment by matkoniecz** [comment]
I am not sure whatever it is even correct tagging to duplicate street name on sidewalks (I was recently surprised by discovering recommendation to do this on wiki).

**Comment by SelfishSeahorse** [comment]
This has been [discussed on the mailing list](https://lists.openstreetmap.org/pipermail/talk/2015-April/subject.html#72613) and the majority seemed to be either in favour with it or neutral.

Note that pavements are part of a road, so it is only logical to name sidewalks, too. Besides, we also duplicate `name` tags for individual carriageways or road stretches.

Another solution would be to not name roads at all and instead adding them to named relations, but this would be a bigger change.

**Comment by kocio-pl** [comment]
Technically it should be possible to hide names for `footway=sidewalk` if we wouldn't find some other problems with that.

**Comment by imagico** [comment]
I suggest to close this - taginfo reports <4 percent of all footway=sidewalk to have a name tag so it is quite clear that it is not generally accepted practice to duplicate the road name on separately mapped sidewalks.
