### ISSUE TITLE
Rendering of man_made=breakwater is filled in multipolygons and not in closed ways

### ISSUE THREAD

**Issue by muralito** [gravitystorm/openstreetmap-carto#2987]
The rendering of man_made=breakwater is filled in multipolygons and not in closed ways.
It can be seen here https://b.tile.openstreetmap.org/15/11455/19749.png
in [https://www.openstreetmap.org/#map=15/-34.6513/-54.1438](url)

**Comment by matthijsmelissen** [comment]
Correct. All tags that can both be areas and lines are always treated as lines now, unless they have an explicit area tag. This is true even if they are closed, to avoid confusion. I doubt circupar breakwaters exist, but behaviour was made the same for all features, for consistency reasons.

**Comment by muralito** [comment]
OK .Will document in wiki.

There exist a list of the features that have their default changed so their wiki pages can be updated?
