### ISSUE TITLE
no color for garages on 12 zoom

### ISSUE THREAD

**Issue by drmx** [gravitystorm/openstreetmap-carto#2988]
on 9-12 zooms color of landuse=garages is missing. in big city it is very big area.
+ maybe color of amenity=school (etc) must be gray as landuse=residential (industrial etc)

**Comment by kocio-pl** [comment]
Could you be more precise? Some examples would be helpful to understand the problem. 

Also if you have some more issues which are not closely connected (and I don't see the relation between these types), please open separate tickets for them.

**Comment by drmx** [comment]
http://www.openstreetmap.org/#map=17/51.59589/45.98041  
in our cities there are quite large areas with garages. on large scales these sites do not have color instead of gray (like all around)

**Comment by kocio-pl** [comment]
Now I see. Sounds like a valid issue for me.

**Comment by polarbearing** [comment]
I tried to get the general perspective on this issue in #3007.

**Comment by kocio-pl** [comment]
I think it makes sense, thanks!
