### ISSUE TITLE
"amenity=ferry_terminal" has wrong icon

### ISSUE THREAD

**Issue by DENelson83** [gravitystorm/openstreetmap-carto#2990]
Right now ferry terminals are marked in carto with an anchor icon.  Where I live, the anchor pictogram on a road sign refers to a marina, not a ferry terminal.  I would like "leisure=marina" to be marked with the anchor icon instead, coloured blue to match the label style for a marina, while "amenity=ferry_terminal" should be marked with the icon linked to below, coloured the same shade of purple used by the label for a ferry terminal.

http://www.aiga.org/globalassets/symbol-signs/26_watertransportation.gif

**Comment by kocio-pl** [comment]
Hi,

this has been already discussed in details in #2785. If you feel something else should be added, please comment there.
