### ISSUE TITLE
Rendering of amenity=bbq

### ISSUE THREAD

**Issue by geesona** [gravitystorm/openstreetmap-carto#2996]
I have done a fair amount of mapping contributions and I am wondering why the amenity=bbq is not being rendered.

**Comment by HolgerJeromin** [comment]
Ref #108 but no duplicate

**Comment by kocio-pl** [comment]
We simply have no icon for that. Somebody has to design it first or find suitable vector shape on a proper license, which will look good as a 14 px image.

**Comment by geesona** [comment]
Potlatch 2 has a pull and drop BBQ icon in its amenity selection?

**Comment by geesona** [comment]
I probably would prefer to use a 'bbq' instead of an icon as it is far more descriptive. There are a number of examples where a node has been labelled or named as 'bbq'.

**Comment by kocio-pl** [comment]
We have specific requirements for icons:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines

We use text for labels (individual names) when they exist - "bbq" is not a universal symbol.

**Comment by matkoniecz** [comment]
> There are a number of examples where a node has been labelled or named as 'bbq'.

I would expect that in most cases this is tagging for renderer and that such names should be deleted.

**Comment by geesona** [comment]
I agree but if amenity=bbq doesn't do anything whats a mapper going to do?

**Comment by kocio-pl** [comment]
A mapper should add the proper data, but she can also propose/design rendering for suitable map styles, as you just did. 

Now we need the icon - for example [leisure=firepit has been proposed and properly designed](https://github.com/gravitystorm/openstreetmap-carto/issues/2910), and because of that [we could add it soon](https://github.com/gravitystorm/openstreetmap-carto/pull/2992).

**Comment by geesona** [comment]
How do I put an SVG image in this post.  I only seem to get a url?
/home/arthur/bbq_icon.svg

**Comment by kocio-pl** [comment]
You can just make a gist for example:

https://help.github.com/articles/creating-gists/

**Comment by polarbearing** [comment]
@geesona - your URL is lacking the hostname. 
You can drop images into the comment filed. 

As for the argument in #2910, the icon for BBQ should be agnostic of the fuel, i.e. not specific to either electric, coal or gas. It might use a grill for symbolism.

**Comment by geesona** [comment]
Could you have a look at this idea for a bbq icon and perhaps change the electric sign to a couple of candles? I have only just loaded inkscape and I have a long learning curve.

https://gist.github.com/geesona/9fb46d8467468eeb31d733e0129c7fe2

**Comment by kocio-pl** [comment]
I don't see it as a recognizable shape, but if you think it would be good, you have to test everything at 14 px.

**Comment by geesona** [comment]
I have made a few changes and it is now at 14 x 14 I hope.

https://gist.github.com/geesona/a5912e34c377d644e088889ecf40d09d

**Comment by kocio-pl** [comment]
This one looks better.

**Comment by geesona** [comment]
Is it possible to get someone to check the icon for us?

**Comment by kocio-pl** [comment]
I'm sorry, I'm currently trying to get few other things to work, so not at the moment. Maybe somebody else is willing to do it?

**Comment by Ham-eatr** [comment]
One idea for the icon- use the same fire logo as used for the fire fighters, just changing the colour. The fire fighters logo is black, for a bbq it could be blue, as in the tourism icons. This will suggest initially a gas fire, then a cool fire or controlled one. The fire pit icon is not appropriate.

**Comment by geesona** [comment]
A blue flame would be ok if it were included in the map key because it would not be immediately identifiable as a bbq.  Infact there are a whole lot of icons that are not in the map key?

**Comment by Tomasz-W** [comment]
I've tune up @geesona draft. 
Would it be readable enough in amenity-brown color? What do you think?

![amenity bbq](https://user-images.githubusercontent.com/25656654/36088436-90cac1f8-0fd7-11e8-8c20-4162bb380ea2.png)

**Comment by kocio-pl** [comment]
It might have a sense, however I was also thinking to test this shape:

https://github.com/gravitystorm/openstreetmap-carto/pull/1519#issuecomment-98638905
https://github.com/mapbox/maki/blob/master/icons/bbq-11.svg

What do you think about it?

**Comment by geesona** [comment]
All though I like the icon above it does depict a portable bbq with a wheel but all the ones in the parks are very permanent structures and I do like the one by Tomasz-W above.

**Comment by kocio-pl** [comment]
For me this shape is just easier to recognize, which might be more important than trying to precisely depict how this object looks like. But if people think it's clear enough, I can go with your design too, because it's quite good.

**Comment by Tomasz-W** [comment]
I also think that icon of amenity=bbq shouldn't suggest a grill. 

Gist with my icon project: https://gist.github.com/Tomasz-W/4ff000df11e004abf24d5e77f5b8db62

**Comment by kocio-pl** [comment]
OK, let it be your way than. 😄

Could you make this icon proper (clean SVG instead of the Inkscape bloat, joining the elements, removing white background etc) and maybe prepare a PR with it, if possible? That would be great.

**Comment by Tomasz-W** [comment]
@kocio-pl I've updated SVG in Gist link:
https://gist.github.com/Tomasz-W/4ff000df11e004abf24d5e77f5b8db62

I hope everything is all right now. If not, give me an info, I'm still learning Inkscape :)

**Comment by kocio-pl** [comment]
1. You didn't save it as a "clean SVG" ("Save As..." then pick it instead Inkscape SVG) - it's easy to detect it: after that there is no "inkscape" strings inside XML and the file is much smaller.

2. There are some points left after merging shapes, which are not needed any more. After removing them the edges become "bezier shaped", so you need to select both nodes and click blue icon with two dots and a straight line inside, which will make the lines between them straight.

I use Polish interface and I'm also not too skilled in Inkscape, so I can find proper English names, but it will take me some more time to do it and I hope you can to do it yourself. 😄

**Comment by Tomasz-W** [comment]
@kocio-pl Done in the same Gist links for amenity=bbq and historic=wayside_shine also.

**Comment by kocio-pl** [comment]
Anybody wants to prepare a pull request with this icon? It should be rather easy and I can help.

**Comment by geesona** [comment]
I will have a go at the pull request but I have no idea yet of what is required or where we are going?

**Comment by kocio-pl** [comment]
Great! Steps needed for rendering of bbq:
- the proper icon (we have it now)
- the code which will render it
- pull request (PR) to - well... :smile: - request to pull that code into master branch of osm-carto
- discussion (if someone will feel the need, which is often the case), code tuning and decision to merge it
- release and deployment on servers

In order to prepare the PR you need to make a fork, modify the code and test if it really works. That's why testing environment is needed and this is probably the easiest way to do it:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

Is it clear or you need some more guidance? Try to be precise, it will help me to give the proper answers.

**Comment by geesona** [comment]
Problem with Docker:
arthur@arthur-Aspire-5750G:~$ sudo apt-get install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
arthur@arthur-Aspire-5750G:~$ apt-cache madison docker-ce
arthur@arthur-Aspire-5750G:~$

**Comment by kocio-pl** [comment]
OK, I see - did you take 4 steps to set up the repo first?:

https://docs.docker.com/install/linux/docker-ce/ubuntu/#set-up-the-repository

**Comment by geesona** [comment]
Yes. Everything was following well until the install. Perhaps the server is down and I need to try again tomorrow?  I looked at trying the .deb file but was also unable to find that.

**Comment by kocio-pl** [comment]
Let's check the state of your repos:

```bash
cat /etc/apt/sources.list | grep docker
```

My output (I use 17.10 version, hence `artful`):
_deb [arch=amd64] https://download.docker.com/linux/ubuntu artful stable_

Next thing - do `apt update` (paste the output if you see anything strange) and then: `apt install docker-ce`.

**Comment by geesona** [comment]
arthur@arthur-Aspire-5750G:~/openstreetmap-carto$ cat /etc/apt/sources.list | grep docker
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
# deb-src [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
arthur@arthur-Aspire-5750G:~/openstreetmap-carto$ apt update
Reading package lists... Done
W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
arthur@arthur-Aspire-5750G:~/openstreetmap-carto$ apt install docker-ce
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
arthur@arthur-Aspire-5750G:~/openstreetmap-carto$ sudo apt install docker-ce
[sudo] password for arthur: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
arthur@arthur-Aspire-5750G:~/openstreetmap-carto$ 

I do not understand the problem, where is W: and E: ?

**Comment by geesona** [comment]
I am using Ubuntu 16.04

**Comment by kocio-pl** [comment]
` E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?`

You're not :smile: , because you have used `apt install docker-ce` instead of `sudo apt install docker-ce`. I was editing this, sorry.

**Comment by geesona** [comment]
I did it again with sudo:

arthur@arthur-Aspire-5750G:/$ sudo apt update
[sudo] password for arthur: 
Hit:1 http://au.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://au.archive.ubuntu.com/ubuntu xenial-updates InRelease             
Hit:3 http://au.archive.ubuntu.com/ubuntu xenial-backports InRelease           
Hit:4 http://au.archive.ubuntu.com/ubuntu xenial-proposed InRelease            
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Hit:6 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease            
Hit:7 https://download.docker.com/linux/ubuntu xenial InRelease                
Get:8 http://security.ubuntu.com/ubuntu xenial-security/main i386 DEP-11 Metadata [67.5 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [72.2 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/universe i386 DEP-11 Metadata [51.4 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe DEP-11 64x64 Icons [85.1 kB]
Fetched 378 kB in 4s (94.1 kB/s)                                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
arthur@arthur-Aspire-5750G:/$ sudo apt install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
arthur@arthur-Aspire-5750G:/$

**Comment by kocio-pl** [comment]
It looks like it ignores this repo - maybe the problem is with the key or HTTPS repos?

You can also try older method (maybe just `sudo apt install docker-engine` would be enough):
https://linoxide.com/linux-how-to/install-docker-engine-ubuntu-16-04-lts-xenial/

or just download and install the package manually:
https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/
https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-from-a-package

**Comment by geesona** [comment]
I have tried all that with no success.  The manual package said I needed i386 not amd64 but I did a search of the download web site but there was no sign of an i386 version.  The install docker-engine had a very similar result to the install docker-ce. A frustrating few hours.

**Comment by geesona** [comment]
I had a glass of wine to cheer me up.  While chasing around I found that there were a lot of old linux images on the machine so I got rid of lots of them, then I noticed that they were 32 bit images!

**Comment by kocio-pl** [comment]
So it must be architecture problem... While it's possible to have 32-bit Docker, Kosmtik works only in 64-bit world.

**Comment by geesona** [comment]
I now have a 64 bit machine and have loaded docker. Now struggling going through the documentation. I shall be absent on and off between 15 March to 15 April.

**Comment by james2432** [comment]
PR added
