### ISSUE TITLE
Add icon for advertising=column

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3002]
There is more than 7k of an advertising colums:
https://taginfo.openstreetmap.org/tags/advertising=column

Nowadays it's rather rare, archaic thing, so I think it wouldn't make mess (as e.g. rendering of advertising=billboard). In modern cities these columns are often used as orientation/ meeting point, so it would be useful to have them on a map.

**Comment by kocio-pl** [comment]
I guess it's OK for z19 and there are some in my city. How exactly do you think they should be rendered?

**Comment by Tomasz-W** [comment]
I think this shape would bo good:
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Column_Morris%2C_Paradise_Circus_-_geograph.org.uk_-_556615.jpg/200px-Column_Morris%2C_Paradise_Circus_-_geograph.org.uk_-_556615.jpg
https://thumbs.dreamstime.com/b/old-advertising-column-paris-blank-isolated-white-clipping-path-included-46389911.jpg
I have tried to make an icon project, but I didn't achieved anything good, so I threw it.

**Comment by kocio-pl** [comment]
You might look for a ready public domain vector icon and tune it. Having general idea is OK for a start, but 14 px matrix restriction is very demanding and the devil is in the detail.

**Comment by polarbearing** [comment]
It's neither rare nor archaic. In Berlin they are still quite typical, named after their inventor [Ernst Litfaß](https://de.wikipedia.org/wiki/Ernst_Litfa%C3%9F) "Litfaßsäulen". 
In favour.

**Comment by matkoniecz** [comment]
In my experience these features are quite popular (at least in Poland) and it is the first time that I heard of using them as landmarks.

**Comment by Adamant36** [comment]
How about something like this for the icon? its from Noun Project. I don't know anything about the icon sizing or what their terms of use are, but it at least makes a good template to go off of. 
![advertising column](https://user-images.githubusercontent.com/30259065/34475158-f1995b26-ef3d-11e7-8309-aadf4eacee61.png)

**Comment by Tomasz-W** [comment]
@Adamant36 https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines

**Comment by Tomasz-W** [comment]
![icon_column2](https://user-images.githubusercontent.com/25656654/34639769-8c42d7dc-f2e6-11e7-888c-206d36f00ffc.png)

14x14: ![icon_column](https://user-images.githubusercontent.com/25656654/34639775-9c38e94c-f2e6-11e7-85f9-2bd1caca11a4.png)

Gist: https://gist.github.com/Tomasz-W/5ecf3dafc35f35bc6f7d310e51d12b3e

@kocio-pl What do you think?

**Comment by kocio-pl** [comment]
It's too solid for me - details are not that visible. I guess body should be even taller.

**Comment by polarbearing** [comment]
Proportions would be fine for me with the de:Litfaßsäulen in mind. 
If too solid, the advertising area could be sprinkled with a few white pixels which could create the experience that there is a poster posted.

**Comment by Tomasz-W** [comment]
>  the advertising area could be sprinkled with a few white pixels which could create the experience that there is a poster posted.

@polarbearing Can you edit this svg file from Gist including your notice? I'm not sure did I understand 
it correctly.

**Comment by Tomasz-W** [comment]
Version with posters:
![icon_column2](https://user-images.githubusercontent.com/25656654/34648570-c24af764-f39b-11e7-88dd-347dd4a87695.png)

14x14: ![icon_column](https://user-images.githubusercontent.com/25656654/34648573-c940e268-f39b-11e7-80de-941603cd7687.png)

**Comment by polarbearing** [comment]
Yes that's getting better for me. Could you try a version with 4 posters arranged symmetrically, for comparison? This would avoid the diagonal illusion that appears in the small size.

**Comment by Tomasz-W** [comment]
@polarbearing 
![icon_column21](https://user-images.githubusercontent.com/25656654/34649861-62c8497e-f3b7-11e7-92f7-6a69e5a0cf99.png)
14x14: ![icon_column1](https://user-images.githubusercontent.com/25656654/34649867-6945b6ba-f3b7-11e7-82a5-7d37cd6b243a.png)

**Comment by kocio-pl** [comment]
That looks more like a building symbol. I would rather use 2-posrter version and try to make the posters bigger. The color should be probably man made.

**Comment by polarbearing** [comment]
I was playing with some white ![ad-col1](https://user-images.githubusercontent.com/8266355/34653378-490e290c-f3eb-11e7-9877-284231da99cf.png) or grey ![ad-col2](https://user-images.githubusercontent.com/8266355/34653381-4ccd3056-f3eb-11e7-9ff0-e467d81db7df.png) random pixels in the poster are. Is the 14px version allowed to have halftone pixels?

**Comment by kocio-pl** [comment]
As far as I'm aware, halftones are generated automatically by Mapnik when the pixel is not fully covered, so no, we use mostly a full color (and occasionally two colors - bus station is a special case when lack of white areas made it a mess on some places).

**Comment by Tomasz-W** [comment]
May I ask you for finish the project? I think that general column shape is ok, of course I can still try to make a poster-version, but this was your idea (good idea), and you will know best, what effect you want to achieve.

**Comment by Adamant36** [comment]
@kocio-pl and @Tomasz-W  I made some more possible icons for you to consider. They look a slightly larger in the message then in they do in the original file for some reason. I think the last one is my favorite. Let me know what you think and maybe I'll tweak them around if need be. 
![advertising column double sided up and down fater version double sided up and down- maybe favorite](https://user-images.githubusercontent.com/30259065/34977819-e6119282-fa50-11e7-8719-6dd6825d7180.png)
![advertising column double sided up and down fater version double sided up and down two paned aligned](https://user-images.githubusercontent.com/30259065/34977828-f273836e-fa50-11e7-9bdb-408c199d1540.png)
![advertising column double sided up and down fater version double sided up and down two paned off center](https://user-images.githubusercontent.com/30259065/34977831-f659428e-fa50-11e7-91af-337aeaa4f63a.png)
![advertising column double sided up and down fater version double sided up and downthree paned](https://user-images.githubusercontent.com/30259065/34977836-fa805136-fa50-11e7-951b-d016fc3e9ab8.png)
![advertising column double sided up and down fater version double sided - maybe favorite](https://user-images.githubusercontent.com/30259065/34977809-d9d7f36c-fa50-11e7-9b1a-8a74a12da19e.png)

**Comment by dieterdreist** [comment]
2018-01-16 9:09 GMT+01:00 Adamant36 <notifications@github.com>:

> [image: advertising column double sided up and down fater version double
> sided up and down- maybe favorite]
> <https://user-images.githubusercontent.com/30259065/34977819-e6119282-fa50-11e7-8719-6dd6825d7180.png>
> [image: advertising column double sided up and down fater version double
> sided up and down two paned aligned]
> <https://user-images.githubusercontent.com/30259065/34977828-f273836e-fa50-11e7-9bdb-408c199d1540.png>
> [image: advertising column double sided up and down fater version double
> sided up and down two paned off center]
> <https://user-images.githubusercontent.com/30259065/34977831-f659428e-fa50-11e7-91af-337aeaa4f63a.png>
> [image: advertising column double sided up and down fater version double
> sided up and downthree paned]
> <https://user-images.githubusercontent.com/30259065/34977836-fa805136-fa50-11e7-951b-d016fc3e9ab8.png>
> [image: advertising column double sided up and down fater version double
> sided - maybe favorite]
> <https://user-images.githubusercontent.com/30259065/34977809-d9d7f36c-fa50-11e7-9b1a-8a74a12da19e.png>
>

to me these all look like houses. IMHO the proportions are not right (too
large width). It should be a small icon with the characteristic shape of
these columns.
See here for example:
https://www.wandtattoos.de/images/product_images/original_images/1308_1_wandtattoo_litfass_tafelfolie.gif

**Comment by Adamant36** [comment]
@dieterdreist Yeah I agree they are a little wide. I tried some that were thinner though and they were all to thin to see the details like the other ones are.   They still fit the 14x14 pixel area to. So its probably going to be either to wide or not look good. I was also looking at man_made windmill as a reference. Which looks a tad fat to depending on the type of windmill being mapped. Some advertising columns can be widder and shorter also. 
http://www.adboard.pl/files/foto_add_big/foto_add-122.jpg
https://upload.wikimedia.org/wikipedia/commons/b/b1/Gentofte_Municipality_-_advertising_column.JPG
So  I'm not sure what the answer is. I'll probably tweak around with them more. As far as them looking like houses. A few kind of do. I dont think the last one of first series or the first one of the second batch really do. It is hard to get a rounded column look though. Personally, I think a few of them look more like telephone boxes if anything.

**Comment by polarbearing** [comment]
<img src="https://cdn.rawgit.com/polarbearing/19bc8a5c7ec6d93202e1a3b93ef02fe7/raw/deb33fce9b947d65f6396b0fd7d2b1f39e1f072a/advertising_column5.svg">
Was working on @Tomasz-W 's svg, cleaning details that would not convert to 14px and applied the halftone technique I learned from the guest_house.

**Comment by kocio-pl** [comment]
Both this version and https://github.com/gravitystorm/openstreetmap-carto/issues/3002#issuecomment-355812224 are promising. Is there anybody willing to make the code and test the rendering?

**Comment by polarbearing** [comment]
As advertising=* ist not yet being used in the repo, is there any database issue to be considered?

**Comment by kocio-pl** [comment]
No, from v4.0.0 up we have hstore database, so we can add any key we need.

**Comment by polarbearing** [comment]
So what is the stuff I installed via docker last week using, is that hstore/4.0.0. ready?

**Comment by kocio-pl** [comment]
Yes, Docker was introduced in v4.1.0 and it works with new database format from day zero.

**Comment by polarbearing** [comment]
The tag is used 7200x on a node and 212x on a way. 
These ways include, see https://overpass-turbo.eu/s/uWm, 
- micromapped circles as you would expect (https://www.openstreetmap.org/way/481239870)
- sometimes wasting 18 nodes for this circle (https://www.openstreetmap.org/way/194622262)
- linear ways (eg https://www.openstreetmap.org/way/384166384 probably mistagged), 
- and in particular in Mannheim, DE, features also tagged as buildings (https://www.openstreetmap.org/way/225126108)

Would we want to include the ways in the rendering?

**Comment by Tomasz-W** [comment]
> Would we want to include the ways in the rendering?

https://wiki.openstreetmap.org/wiki/Tag:advertising%3Dcolumn
Mapping it as areas is allowed, so I think it should be rendered as icon in the middle.

**Comment by polarbearing** [comment]
We haven't discussed the colour yet, I think tourism brown would suit.
1 halftone poster area: ![ad-col-trans1](https://user-images.githubusercontent.com/8266355/35047162-63c0b386-fb99-11e7-92a3-a537f2c60a33.png)  2 two posters: ![ad-col-posters1](https://user-images.githubusercontent.com/8266355/35047165-67610d6a-fb99-11e7-94a5-2a51b42ef8fd.png)

**Comment by kocio-pl** [comment]
Maybe man_made gray would be better, because you don't "use" them other than just looking at them (bench, toilet or trash can are different - you interact with them somehow).

**Comment by polarbearing** [comment]
man_made grey:
![ad-col-trans2](https://user-images.githubusercontent.com/8266355/35048718-28de5264-fb9e-11e7-89a8-6ac53bc8f44f.png) ![ad-col-posters2](https://user-images.githubusercontent.com/8266355/35048612-e2dc8790-fb9d-11e7-977a-4e227bb9ee69.png)

**Comment by kocio-pl** [comment]
For me gray with posters is the best choice.

**Comment by Tomasz-W** [comment]
I like gray version without posters the most. It's attracting less attention (as less-important elements should) and it's more readable, I think.

**Comment by matkoniecz** [comment]
I admit that I am still unconvinced that rendering this feature is a good idea.

**Comment by dieterdreist** [comment]
2018-01-17 16:22 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> I admit that I am still unconvinced that rendering this feature is a good
> idea.
>

I also find them a bit obtrusive, maybe a much smaller icon, like this: [image:
Inline-Bild 1]
admittedly, it is not quite recognizable at this size.

**Comment by dieterdreist** [comment]
even smaller: [image: Inline-Bild 1]

**Comment by dieterdreist** [comment]
these are the pictures
![litfass7](https://user-images.githubusercontent.com/581288/35058392-19d69f46-fbb8-11e7-9e93-aeadc40931b7.png)
![litfass11](https://user-images.githubusercontent.com/581288/35058394-1a078890-fbb8-11e7-9b92-7162e701701e.png)
![litfass14](https://user-images.githubusercontent.com/581288/35058396-1a2ab5ea-fbb8-11e7-9fc5-fd94ef7e4221.png)

**Comment by kocio-pl** [comment]
I can't recognize them, they all look like simple rectangles.

**Comment by dieterdreist** [comment]
here's an outline version:
![litfass256-ol](https://user-images.githubusercontent.com/581288/35069414-6c397cf0-fbda-11e7-9695-919d203b963c.png)
![litfass12-ol](https://user-images.githubusercontent.com/581288/35069448-84e921e2-fbda-11e7-819c-bcd819085bab.png)
![litfass14-ol](https://user-images.githubusercontent.com/581288/35069449-850cc0d4-fbda-11e7-8b97-9182b29b2ea8.png)

**Comment by kocio-pl** [comment]
Big outline design is nice, but also doesn't work when in small size.

**Comment by polarbearing** [comment]
![ad-col-outline1](https://user-images.githubusercontent.com/8266355/35072332-681f15bc-fbe4-11e7-93ad-a064c8a11b1d.png) Simpler outline version a bit more pixel-aligned

**Comment by kocio-pl** [comment]
This one is recognizable enough for me.

**Comment by polarbearing** [comment]
man_made grey:
![ad-col-trans2](https://user-images.githubusercontent.com/8266355/35048718-28de5264-fb9e-11e7-89a8-6ac53bc8f44f.png) ![ad-col-posters2](https://user-images.githubusercontent.com/8266355/35048612-e2dc8790-fb9d-11e7-977a-4e227bb9ee69.png) ![ad-col-outline_manmade](https://user-images.githubusercontent.com/8266355/35072972-1f9bd1d8-fbe7-11e7-9150-e4df30a7d7d4.png)

**Comment by kocio-pl** [comment]
Still B, than A, than C (not good on a map).

**Comment by dieterdreist** [comment]
I'm tending against rendering this feature, especially at zoom 17 as in the
example renderings. It is nice in "empty" areas like the upper right
column, but it is completely disturbing in the urban setting down left,
where it hides the house. In zoom 19 they would be nice to have and are
some of those features that distinguish us from other maps. Unsure about
z18.

**Comment by polarbearing** [comment]
The test renderings were not meant to propose a particular zoom level. 19 and maybe 18, yes.

**Comment by dieterdreist** [comment]
yes, but they influence the perception of the icon. in z17, all icons are
close together (and of a certain "importance"), having advertising columns
between them feels "odd".

**Comment by polarbearing** [comment]
z18
![ad-col-outline_z18](https://user-images.githubusercontent.com/8266355/35074404-fe1bbaa8-fbed-11e7-9381-068b79dd4e16.png) ![ad-col-outline1_z18](https://user-images.githubusercontent.com/8266355/35074503-8789fb24-fbee-11e7-9fce-c8f7ef226102.png)

z19
![ad-col-outline_z19](https://user-images.githubusercontent.com/8266355/35074391-edae62d8-fbed-11e7-8bf5-fa5fac6473fd.png) ![ad-col-outline1_z19](https://user-images.githubusercontent.com/8266355/35074515-95877724-fbee-11e7-80a2-b6439e3fa0f4.png)

**Comment by kocio-pl** [comment]
z18 is still to early for me, but the outline might work.

**Comment by polarbearing** [comment]
z19 comparison 
![ad-col-outline_z19_combo](https://user-images.githubusercontent.com/8266355/35074707-74d409c4-fbef-11e7-8ac9-9c8c2e52071e.png)

**Comment by kocio-pl** [comment]
Again - B, A, C.

**Comment by dieterdreist** [comment]
thank you polarbearing for the renderings. I also prefer the checkerboard B.

**Comment by Tomasz-W** [comment]
Well, paradoxical I like @polarbearing 's ''halftone' version, more than my 'checkboard' one. As I said, I think this element should be rendered, but it should also attract small attention. https://github.com/gravitystorm/openstreetmap-carto/issues/3002#issuecomment-358497089 third icon fits the best for me, Any other "votes"?

**Comment by james2432** [comment]
So to recap:
https://user-images.githubusercontent.com/8266355/35048612-e2dc8790-fb9d-11e7-977a-4e227bb9ee69.png
At zoom >= 19
colour: man made grey
?

**Comment by Tomasz-W** [comment]
I still think that 'checkboarded' version is too solid for not-so-important feature like advertising columns, so I prefer half-toned @polarbearing project.

**Comment by james2432** [comment]
This one? ![Image](https://camo.githubusercontent.com/63a3913192183f7868671f8700430255e45fdeed/68747470733a2f2f63646e2e7261776769742e636f6d2f706f6c617262656172696e672f31396263386135633765633664393332303265316133623933656630326665372f7261772f646562333366636539623934376436356636333936623066643764326231663339653166303732612f6164766572746973696e675f636f6c756d6e352e737667)

**Comment by kocio-pl** [comment]
Well, it's also acceptable solution for me.

**Comment by Tomasz-W** [comment]
@james2432 https://gist.github.com/polarbearing/19bc8a5c7ec6d93202e1a3b93ef02fe7

**Comment by james2432** [comment]
PR Created
