### ISSUE TITLE
Primary highway rendered on top of trunk_link

### ISSUE THREAD

**Issue by georgek** [gravitystorm/openstreetmap-carto#3006]
It seems that a highway=primary way will be rendered on top of a highway=trunk_link way. This causes a strange looking junction in the case where a primary road turns into a trunk road, for example here: https://www.openstreetmap.org/#map=17/52.68063/1.26529

It's an unusual situation but it does happen.

To make this look nicer trunk_link would be rendered after primary. I'm not sure if this would cause any other problems, but I can't think of any.

**Comment by matkoniecz** [comment]
> To make this look nicer trunk_link would be rendered after primary. I'm not sure if this would cause any other problems, but I can't think of any.

What about more typical situation where trunk_link joins primary road? Like at https://www.openstreetmap.org/way/205938118#map=18/52.62800/1.38431

Rendering trunk_link above primary would break rendering in this, more common, type of crossings.

See #266, #678, #1334, #1985, #2055 and probably other for similar/duplicates.
