### ISSUE TITLE
Kosmtik in Docker complains about missing fonts 

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#3020]
Kosmtik in Docker (MacOS host) complains about missing fonts at runtime. Map ist still rendered.
Docker is the stable MacOS package from [here](https://docs.docker.com/docker-for-mac/install/)
Installation followed the DOCKER.md instructions in this repo. 

```
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Cherokee Bold' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Sinhala UI Bold' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Symbols Bold' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Arabic UI Bold' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Adlam Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Adlam Unjoined Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Chakma Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Osage Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Sinhala UI Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Symbols2 Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Sans Arabic UI Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'HanaMinA Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'HanaMinB Regular' in FontSet 'fontset-2'
kosmtik_1  | Mapnik LOG> 2018-01-13 04:10:08: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'
```

**Comment by HolgerJeromin** [comment]
We add a massive amount of fonts to have support for all platforms and names. 
So these message are "on purpose"

**Comment by HolgerJeromin** [comment]
We add a massive amount of fonts to have support for all platforms and name=*.
So these message are "on purpose"

**Comment by d3netxer** [comment]
How do I add all of the fonts. Following the directions on openstreetmap-carto I installed the fonts using this command (Ubuntu 16.04):

```
sudo apt-get install fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted fonts-hanazono ttf-unifont
```

so I wasn't expecting to find any warnings.

**Comment by HolgerJeromin** [comment]
Tt is not possible to install all referenced fonts as at least with 
`"Unifont Medium", "unifont Medium"` we have the same font with different names (for different OS Variants).
ref #2948 and #2924

**Comment by kocio-pl** [comment]
>I installed the fonts using this command (Ubuntu 16.04) so I wasn't expecting to find any warnings.

[In the same section](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#installation-on-ubuntudebian) you can read also:

> The current upstream font release has also some more scripts and style variants than in the Ubuntu package. It can be installed from source.

I guess we can close this issue, since font warnings are unavoidable even if you add them manually (see #2924 ).
