### ISSUE TITLE
leisure=garden & leisure=park have the same colour

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#3022]
Public gardens are often sections within parks but atm there's no visible difference: 
https://www.openstreetmap.org/way/191318876#map=19/51.45508/-2.58866

Slight darker shade or a boundary?

**Comment by SomeoneElseOSM** [comment]
Example of what a "slightly darker shade" would look like: http://map.atownsend.org.uk/maps/map/map.html#zoom=19&lat=51.455193&lon=-2.589031 (different map style, but parks are the same colour, gardens different).

**Comment by DaveF63** [comment]
Is my memory fading or is that the shade OSMCarto rendered gardens until recently?

**Comment by SomeoneElseOSM** [comment]
It's certainly the shade that OSM Carto rendered gardens in 2014 - I haven't changed it since then.

**Comment by chrisfleming** [comment]
This was changed quite recently,
https://github.com/gravitystorm/openstreetmap-carto/commit/8732cad808b15b6778b03a4089c7fad9d67d1607

I agree Gardens and Parks should be different shades of green, where
we've been mapping "private" gardens around houses I think the lurid
green looks pretty bad against the buildings and also there is no
difference with parks, for example:

https://www.openstreetmap.org/search?query=edinburgh#map=16/55.9398/-3.1911


Cheers
Chris

**Comment by Tomasz-W** [comment]
What do you think about pattern for garden areas: grass green shade with small colorful dots (symbol of flowers) added to it?

**Comment by DaveF63** [comment]
What's preventing it returning to it's previous shade, which from memory was the same as @SomeoneElseOSM's current.

I'm not keen on patterned polygons. The translucence of footpaths makes it difficult to see within woods, even when zoomed in.

**Comment by matthijsmelissen** [comment]
> What's preventing it returning to it's previous shade

Before, parks had the same color as grass, so areas of grass in parks were invisible.

**Comment by dieterdreist** [comment]
just wanted to mention that parks aren't always public, not even in OSM and
according to the wiki, and gardens are not always privately owned and might
be publicly accessible even if privately owned.

**Comment by kocio-pl** [comment]
I have introduced this change in #2964.

The problem with garden is that it can be a lot of things - it can be:
- basically a public or private park, were you can walk (kind of "Palace Garden" or "Botanical Garden"),
- small decorative area in the public place (similar to flower bed, but filled with other plants)
- private green area at the backyard of the house, which is not just a lawn (so called [back garden](https://en.wikipedia.org/wiki/Back_garden)),
- kind of food garden (thus similar to farmland).

So it can be for leisure, decorative or food purposes (maybe some others too). With so much colors used already it's no longer the option to have separate color for every object type, some objects should be grouped. The garden has been clustered with grass areas, which I think is less similar than the park (grass only area vs different plants area).

**Comment by dieterdreist** [comment]
2018-01-15 17:08 GMT+01:00 kocio-pl <notifications@github.com>:

> I have introduced this change in #2964
> <https://github.com/gravitystorm/openstreetmap-carto/pull/2964>.
>
> The problem with garden is that it can be a lot of things - it can be:
>
>    - basically a public or private park, were you can walk (kind of
>    "Palace Garden" or "Botanical Garden"),
>    - small decorative area in the public place (similar to flower bed,
>    but filled with other plants)
>    - private green area at the backyard of the house, which is not just a
>    lawn (so called back garden <https://en.wikipedia.org/wiki/Back_garden>
>    ),
>    - kind of food garden (thus similar to farmland).
>
> So it can be for leisure, decorative or food purposes (maybe some others
> too). With so much colors used already it's no longer the option to have
> separate color for every object type, some objects should be grouped. The
> garden has been clustered with grass areas, which I think is less similar
> than the park (grass only area vs different plants area).
>
>

yes, there are different styles and kinds of gardens. Typically, I'd see a
garden as more intensively cared for (requiring more care), than a park
(yes, someone will now post a pic of his garden which he didn't care for in
the last 30 years, telling me he wants it exactly like this).

For the record: there are subtags for distinguishing different aspects and
types of gardens, and if this style would render some of them differently I
am sure, people would use them even more:
https://wiki.openstreetmap.org/wiki/Proposed_features/Garden_specification

**Comment by chrisfleming** [comment]
FYI - I grabbed this screenshot when the changes to the garden colour rolled out.

![screenshot-2017-12-18 openstreetmap](https://user-images.githubusercontent.com/230932/34951018-cd36753c-fa0c-11e7-8196-59aefc8e8ce0.png)

My main issue is that I don't actually like the new colour and I do agree that we can't have a different colour for everything. 

However I do like to be able to see the difference, partly because there are so many Pokemon go players changing Gardens to Parks, and also because I think it's good to see a difference between the largely public park areas's and the largely private gardens. And I think gardens can be summarised as cultivated in some ways and parks which are overall large grass areas.

**Comment by kocio-pl** [comment]
@dieterdreist Thanks, I was not aware of it! [`garden:type`](
https://wiki.openstreetmap.org/wiki/Key%3Agarden%3Atype) is being massively used (37k+), however we should look closer if it's clear enough and how should they be rendered then.

**Comment by kocio-pl** [comment]
Quick and dirty review:
- `botanical`- very close to a park, so should be rendered the same as parks, so no change
- `residential` - most of the time it will be probably "front yard/back garden", I'm not sure how should they be rendered like, but they are not for walking. But residence can be also a manor or palace and the garden can be more similar to park then.
- `community` - I don't recognize this type at all just reading definition.
- `castle` - definition not presented, probably something similar to manor/palace, but narrow - probably it would be good to have a single tag for all of them (or some hint should be added to wiki pages to simply tag them as parks).
- `monastery` - most probably a food garden, but may have walking space - I don't know.

I guess park and big walkable gardens are similar, small residential gardens might be rendered different (how? just like the lawn?) and food garden, if we can identify it, might be rendered different (like a farmland maybe?).

**Comment by DaveF63** [comment]
> So it can be for leisure, decorative or food purposes (maybe some others too)...

Unless OSMCarto is using sub-tags to differentiate 'leisure=garden' I'm unsure how the multiple ways it's used in OSM is relevant. OSMCarto needs to ensure it doesn't clash with other entities it's gets added on top of.

**Comment by kocio-pl** [comment]
We are capable of using sub tags, so this is not a problem. Still we need to decide which ones are really useful and how should each type they be rendered. What are your propositions and remarks about `garden:type` for example?

There can be all the combinations - I have seen garden in the park, but also grass in the garden or park, I haven't seen garden in the grass area, but it's possible too... So I guess it won't help us to decide.

**Comment by dieterdreist** [comment]
2018-01-15 17:49 GMT+01:00 kocio-pl <notifications@github.com>:

> Quick and dirty review:
>
>    - botanical- very close to a park, so should be rendered the same as
>    parks, so no change
>
>

no way, it is very different from a park (IMHO), it's a place of
conservation and study, no leaving of the paths, etc.



>    - residential - most of the time it will be probably "front yard/back
>    garden", I'm not sure how should they be rendered like, but they are not
>    for walking. But residence can be also a manor or palace and the garden can
>    be more similar to park then.
>    - community - I don't recognize this type at all just reading
>    definition.
>    - castle - definition not presented, probably something similar to
>    manor/palace, but narrow - probably it would be good to have a single tag
>    for all of them (or some hint should be added to wiki pages to simply tag
>    them as parks).
>
>
+1, I could maybe imagine having a type like "stately", which is
distinguished from "ordinary residential" gardens, but "castle" doesn't
seem helpful as a term here (and is ambiguous as well).


>
>    - monastery - most probably a food garden, but may have walking space
>    - I don't know.
>
>
IMHO ok to have this, although I would expect a monastery to have different
garden zones, from decorational to useful (vegetables and salad, herbs and
spices, orchard, etc.)

**Comment by kocio-pl** [comment]
> no way, it is very different from a park (IMHO), it's a place of conservation and study, no leaving of the paths, etc.

In the parks I know leaving the paths is not allowed (I know UK might be different, but that's how it is in Poland). In general they are walkable and this is the main similarity. Botanical gardens in Warsaw I know are meant for public just like a park, this is not contradicting scientific use.

**Comment by dieterdreist** [comment]
2018-01-15 18:17 GMT+01:00 kocio-pl <notifications@github.com>:

> no way, it is very different from a park (IMHO), it's a place of
> conservation and study, no leaving of the paths, etc.
>
> In the parks I know leaving the paths is not allowed (I know UK might be
> different, but that's how it is in Poland). In general they are walkable
> and this is the main similarity. Botanical gardens in Warsaw I know are
> meant for public just like a park, this is not contradicting scientific use.
>

yes, all botanical gardens I know are open to the public. The difference to
a park is that usually they impose more strict behavioural rules, often
require an entrance fee, typically have strict and not so long opening
hours., Cycling is usually not allowed, usually there are also indoor
areas, a lot of surface is intensively cared for (as opposed to parks where
most of the area is typically lawn) etc.

**Comment by DaveF63** [comment]
Sorry, I didn't see your previous post until I sent my last one.
Unaware ` garden:type` was in use. It would certainly help differentiate when overlaid.
`botanical `and `residential` would definitely be beneficial. I've tagged what described as `community` as `allotments` as they've been 'alloted' from public land & often have vegetables as well as flora.

The example I gave in my OP isn't really described. 

From my experience:
`botanical `and `community` & the one in my OP need to be a different shade to `park`

`residential `won't coincide with `park `so could be the same shade if required

Here's a Google 360 of another example of a garden with a park:
http://tinyurl.com/y77u6h4w

**Comment by imagico** [comment]
For better understanding:

* `leisure=park` in OSM is an urban/near-urban area dedicated at a wide range of leisure/recreation activities (unless it is abused by some native English speakers for _anything named park_)
* `leisure=garden` in OSM is for areas where _gardening_ of some form is the primary purpose of the area - for mostly decorative, to a lesser extent scientific purposes or for small scale (individual household) consumption.

As usual i would suggest to look at:

* the actual use of the tags in OSM (world wide and not just in your home town)
* how other maps render parks and gardens (the distinction between those is not something OSM invented)

**Comment by dieterdreist** [comment]
2018-01-15 18:34 GMT+01:00 Christoph Hormann <notifications@github.com>:

> For better understanding:
>
>    - leisure=park in OSM is an urban/near-urban area dedicated at a wide
>    range of leisure/recreation activities (unless it is abused by some native
>    English speakers for *anything named park*)
>
>

this really depends on the context, in some cases the park is dedicated to
a very narrow range of leisure activities (go for a walk, but not cycling,
not leaving the path).

**Comment by kocio-pl** [comment]
@dieterdreist 

In the parks I know cycling is also not allowed, some of them require fee and some are fenced.

However making the list "gardens vs parks" is not our ultimate goal - of course we may find differences between types, but the real problem is how should gardens be rendered? There will be always differences between objects in a "cluster", but we need to find patterns of _similarities_.

In other words: which clusters do you propose - and how should they be rendered?

@imagico 

> For better understanding:

This sounds like a clear difference, but I'm afraid it may be not very helpful. Gardening and leisure is where parks and gardens are similar in many cases (parks might not be about plants gardening, but I haven't seen it yet). And leisure is a common back garden purpose, just like food production, depending on the part of the world.

> unless it is abused by some native English speakers for anything named park

Some "national parks" are good example (look at the California). However that seems to be true for gardens too, that's why I think big residential gardens (like "Royal Garden") might be just tagged as parks. And this is the same common problem in Polish.

> As usual i would suggest to look at:

You're great at analysis, could you make such worldwide research? My research was not based only on my home town, but this is not what I do the best.

**Comment by dieterdreist** [comment]
2018-01-15 19:11 GMT+01:00 kocio-pl <notifications@github.com>:

> @dieterdreist <https://github.com/dieterdreist>
>
> In the parks I know cycling is also not allowed, some of them require fee
> and some are fenced.
>
> However making the list "gardens vs parks" is not our ultimate goal - of
> course we may find differences between types, but the real problem is how
> should gardens be rendered?
>


I agree it depends completely on the type of garden. I would expect

1. a botanical garden to be different from a park, but similar, e.g. like
zoos.
1b Also "rosarium" would be a similar "feature" garden, flower beds, etc.

2. allotments are probably the same as or similar to "community" gardens
(unsure on this, the communities are often quite different kind of people,
so maybe it makes to map less usefull not to distinguish), a set of smaller
gardens forming an unit and not surrounding a residence).

3. Stately gardens (or castle, royal, villa, etc.) as well as monastery
gardens and residential gardens could make a class of gardens serving a
residence (and could be seen as less interesting for the general public
from first to last, i.e. stately most intense colour, residential least).

**Comment by matthijsmelissen** [comment]
Would giving gardens an outline solve this issue?

**Comment by kocio-pl** [comment]
It would make the small ones (like backyard gardens or flower-bed alike) look worse, so at least not in general.

**Comment by Tomasz-W** [comment]
I've made few mock-ups in Photoshop (I'm unable to do a test rendering).
Grass green shade with colorful dots on it (click for full-size)

Example1 (25%)
![klasztor25](https://user-images.githubusercontent.com/25656654/35182989-bbd67050-fdde-11e7-8d7f-fc7431260caf.jpg)
Example1 (50%)
![klasztor50](https://user-images.githubusercontent.com/25656654/35182990-bbf39144-fdde-11e7-93f2-1275e0acd215.jpg)
Example2 (25%)
![malta25](https://user-images.githubusercontent.com/25656654/35182992-bf90cc9a-fdde-11e7-9abe-02dddb1790d6.jpg)
Example2 (50%)
![malta50](https://user-images.githubusercontent.com/25656654/35182993-c00ad274-fdde-11e7-8da3-ff0b5b7623c8.jpg)
Pattern (50%)
![pattern50](https://user-images.githubusercontent.com/25656654/35182994-c2a6bef8-fdde-11e7-8bc3-32ab4e68e7c8.jpg)

Note, that it's just very first version for showing you the idea.

**Comment by kocio-pl** [comment]
Interesting, we could use some patterns (rather monochrome, I guess) with light green too. Maybe that would be good for all the gardens that are not similar to parks (which maybe should be just tagged like a park).

**Comment by Tomasz-W** [comment]
I'll try version with green and red dots (like roses). @kocio-pl What about dots size and space beetween them, are they ok?

**Comment by kocio-pl** [comment]
I don't know, since I'm busy with other things and only try to figure out what could work, but I would start with the orchard pattern probably - it should be regular, because gardening is a human activity and also because orchard is just a special kind of garden in fact.

It would be interesting how would grass areas look inside the garden then.

**Comment by kocio-pl** [comment]
This idea seems to be general enough - we don't need to look at garden subtypes, which are not that clear it seems, so I like it even more. 

If we only add a note in the wiki to treat mainly "walkable" gardens as parks (not every park have to be garden with plants, but all the parks I know are in fact "walkable gardens"), no matter if the name includes Garden/Jardin/Ogród/... etc., that would be enough probably to render everything good.

**Comment by dieterdreist** [comment]
2018-01-22 19:32 GMT+01:00 kocio-pl <notifications@github.com>:

> Well mapped botanical garden for testing how the new look will work with
> different types of sub-areas:
>
> https://www.openstreetmap.org/way/26633037
>

another one in Berlin:
https://www.openstreetmap.org/way/125194752
another one with different tagging:
https://www.openstreetmap.org/way/26481293

**Comment by kocio-pl** [comment]
The first one is interesting because it has an orchard inside.

The second one should have probably operator defined instead of amenity=university. But what are really these parts, like that:

https://www.openstreetmap.org/way/226294581

Currently I think botanical gardens (`leisure=garden + garden:type=botanical`) might be the only gardens that should be rendered like a park.

**Comment by dieterdreist** [comment]
2018-01-22 19:49 GMT+01:00 kocio-pl <notifications@github.com>:
>
> The second one should have probably operator defined instead of
> amenity=university.
>

it is part of the university though

**Comment by kocio-pl** [comment]
I tag the general campus this way, but not specific types of objects, for example garden of Warsaw University I tag as a garden (adding operator there would be good):

https://www.openstreetmap.org/way/5081150

I think this is the case when both tagging has its merits, so we can choose what looks better - it's not bad data. I would argue that operator has a bit more sense.

**Comment by dieterdreist** [comment]
2018-01-22 21:11 GMT+01:00 kocio-pl <notifications@github.com>:

> I tag the general campus this way, but not specific types of objects, for
> example garden of Warsaw University I tag as a garden (adding operator
> there would be good):
>
> https://www.openstreetmap.org/way/5081150
>

in the case of Tübingen, the botanical garden is part of the "campus"
(actually, it is not a campus university I think)
https://www.uni-tuebingen.de/einrichtungen/zentrale-einrichtungen/botanischer-garten.html

**Comment by kocio-pl** [comment]
I don't see any educational buildings there, so I wouldn't call it campus - just some garden which is university property (school can be owned by church, but I tag it as a school then). The same is true for BG of Warsaw University:

http://www.ogrod.uw.edu.pl/en

However I added university tag for the rest of the area, where there are no more specific landuse than just general university: 

https://www.openstreetmap.org/way/25748407

But this is ambiguous question. The only important thing in this ticket is that in current state it probably won't work as a testbed for garden rendering.

**Comment by dieterdreist** [comment]
sent from a phone

> On 22. Jan 2018, at 21:26, kocio-pl <notifications@github.com> wrote:
> 
> I don't see any educational buildings


if we continue, this should better go to the tagging ml ;-). Universities usually do research and education. AFAIK in the botanical garden both is done.

**Comment by kocio-pl** [comment]
Another idea might be different shade of green, since we have a lot of them they work surprisingly well. One possible way might be to take green from camping site, which has different shade already, since we try to design outline for accommodation areas anyway (see #2290).

**Comment by Tomasz-W** [comment]
I've made new version of pattern with regular red and dark green dots:
![pattern red](https://user-images.githubusercontent.com/25656654/35470622-1cdbf226-034d-11e8-88ad-06e5aedf5823.jpg)

Examples (still just a Photoshop mock-ups, click for full-scale):
![bloki](https://user-images.githubusercontent.com/25656654/35470625-23d6c0f6-034d-11e8-86c2-935068a46878.jpg)
![klasztor](https://user-images.githubusercontent.com/25656654/35470626-23f3f90a-034d-11e8-9048-1d83d2b770d1.jpg)
![malta](https://user-images.githubusercontent.com/25656654/35470627-24135a98-034d-11e8-935c-2f3958d967a9.jpg)
![ue](https://user-images.githubusercontent.com/25656654/35470628-2435caf6-034d-11e8-9a00-b3069c7973da.jpg)

**Comment by polarbearing** [comment]
The red dots are a bit noisy for me, even if they are roses :-)

What about a shape, like a flower with petals ![flower1](https://user-images.githubusercontent.com/8266355/35486134-0a2a05f0-046a-11e8-96ad-27b3bee0a13b.png), rendered in a light-grey pattern such as forest trees?

**Comment by kocio-pl** [comment]
After some time off, I think now that we should use just another kind of green for gardens. They can be very different in size, access and purpose:
- big garden which is meant for walking -> probably better tagged as public park
- botanical garden to walk (like a park), but also with special plants species to show/preserve/study, so like a public or private park
- [Japanese rock garden](https://en.wikipedia.org/wiki/Japanese_rock_garden) (zen garden), where the plants are just part of minimalistic decoration
- monastery garden, which can be for growing vegetables (hence similar to farmland) or walking/contemplation (like private park)
- residential garden, which can be big when being a part of a palace or manor (so a private park for walking), but also small - small backyard lawn with some trees, small [front garden](https://en.wikipedia.org/wiki/Front_yard), which can be just a lawn, but also consist of [some bushes, herbs and flowers](https://en.wikipedia.org/wiki/Front_yard#/media/File:Sandvig_-_front_gardens.jpg)
- small patch of green plants (other than just grass) in the urban area, sometimes tagged as a village_green

Flower pattern is appropriate just for some forms of the garden, dots (colorful or just black in rows) might be good for more types, but they suggest growing plants (which sounds to me like most important feature of gardens in general), which might be not proper for zen garden (very few plants) or small residential garden (mainly grass).

So I guess we should use just another green shade, which is similar to grass, but maybe 10% lighter (or start with tourism=camp_site backbround), so we can show the structure if there are grass patches inside, but stay generic enough. We could also use dotted version as a generic pattern, so people will add more specific tags (type/style) which contain no dots - it's always better to have more specific tagging so generic values might have some annoyances/ambiguity.

What do you think about it?

**Comment by Tomasz-W** [comment]
> We could also use dotted version as a generic pattern, so people will add more specific tags (type/style) which contain no dots

I like this idea. because most of gardens contains plants, so we should be more focused on them than on the less popular types.
What should be this pattern like then? What colours? With dots or some shape?

**Comment by kocio-pl** [comment]
I think black orchard pattern (with a different green shade in the background) would be good.

**Comment by Tomasz-W** [comment]
I don't like the idea of adding new shade of green, bacause I think we have them too much now, and adding next one will made mess even worst.

Look at this:
https://www.openstreetmap.org/#map=18/52.40511/16.97364
or this:
https://www.openstreetmap.org/#map=18/52.41408/16.93156

I think we shoud look for ways to reduce amount of green shades, not add new ones. That's the reason why I proposed dotted pattern with current grass-green background. 
I also would like to distunguish grasses and meadows in the future, so make two patterns based on grass-green would be good solution here, I think, because all those vegetation areas (grasses, gardens, meadows) are on similar level (height).

**Comment by kocio-pl** [comment]
I'm quite surprised how well many shades of green work and how easy it's for me to recognize them. For me both examples work good.

Testing with grass color and orchard pattern looks OK for me for big areas and small patches of plants:
![a4gamn0r](https://user-images.githubusercontent.com/5439713/36505808-ee4f09e0-1754-11e8-9acc-36976161389f.png)
![bvk2sji8](https://user-images.githubusercontent.com/5439713/36505816-f27465a6-1754-11e8-9bc5-1acacc66eec2.png)
![in uvomu](https://user-images.githubusercontent.com/5439713/36505818-f403b174-1754-11e8-91ba-65323ac12669.png)
![pu5jxsex](https://user-images.githubusercontent.com/5439713/36506003-96475c42-1755-11e8-97af-73c9ab5e412a.png)

I was worried about small residential gardens, but that is also quite OK:
![sbto5sxw](https://user-images.githubusercontent.com/5439713/36505812-ef7b88f2-1754-11e8-93c9-a2b073e51e31.png)

Orchard for comparison:
![1b_nllh_](https://user-images.githubusercontent.com/5439713/36506333-97745e02-1756-11e8-97d7-a4b62f7c289e.png)

The only thing that would be not good probably are grass areas inside the garden. I haven't found such place, but this is similar one, where grass and garden are near each other:
![50qkyk7w](https://user-images.githubusercontent.com/5439713/36505814-f10d1104-1754-11e8-8a4b-781c644f5c94.png)

**Comment by Tomasz-W** [comment]
2 remarks:
* Don't we want any colours in this pattern? I can admit that my project was too noisy, but I'm not sure if grey-dots-only pattern is good to show gardens, and I would like to hear feedback of other participants.
* I think this pattern should be crossed like this one: https://user-images.githubusercontent.com/25656654/35470622-1cdbf226-034d-11e8-88ad-06e5aedf5823.jpg

**Comment by kocio-pl** [comment]
So let the others speak about the colors, please. 

We use the crossed pattern for plant_nursery currently (which is also dark green, like an orchard):
![46mgszgb](https://user-images.githubusercontent.com/5439713/29636904-a6303166-8852-11e7-94ae-128f5a536215.png)

but if that's OK for the others, we can use this one instead - it is denser, so the difference with grass will be more visible:
![pjgjjfpq](https://user-images.githubusercontent.com/5439713/36535060-b40db302-17c8-11e8-9821-04b69ba54526.png)
![hkjjcmmq](https://user-images.githubusercontent.com/5439713/36535061-b56b6316-17c8-11e8-9e71-d96423dbf5ad.png)
![96n6tv7s](https://user-images.githubusercontent.com/5439713/36535134-f5ff1bde-17c8-11e8-95d2-653a71bcec9c.png)
![fugmp8aw](https://user-images.githubusercontent.com/5439713/36535211-31ee4ca0-17c9-11e8-9f7a-f9a48da2deba.png)

**Comment by daganzdaanda** [comment]
IMHO the coloured patterns are drawing too much attention to themselves, even when the opacity is low.

I believe patterns should be used sparingly, and always be as subtle as possible, because they always raise the noise level. The plant-nursery pattern example is still too dark for my taste. It should have even less contrast to the background. Maybe 40% opacity is enough to make it visible but not irritating?

**Comment by kocio-pl** [comment]
Could you provide such file? I have problems with processing opacity.

**Comment by daganzdaanda** [comment]
The 40% was just a guess. I played with paint to come up with `#A8C090` as a subtle colour for the pattern:
![aa526](https://user-images.githubusercontent.com/7693297/36569692-0fd564b2-182f-11e8-8a7e-b265a9a2b432.png)

Can a pattern use black pixels and be set to have something like .4 or .25 opacity?

**Comment by kocio-pl** [comment]
I'm not sure, one has to check CartoCSS documentation or seek examples in our code.

**Comment by daganzdaanda** [comment]
https://cartocss.readthedocs.io/en/latest/api/mapnik/3.0.6.html?#polygon-pattern-opacity

**Comment by kocio-pl** [comment]
Thanks! 

40% opacity real rendering examples:
![gw3iv1d0](https://user-images.githubusercontent.com/5439713/36570904-876f35f2-1834-11e8-9ae1-0869aedb2953.png)
![v9ew_f p](https://user-images.githubusercontent.com/5439713/36570906-8914c822-1834-11e8-8608-aa2f9d3e3a21.png)

**Comment by Tomasz-W** [comment]
I like the previous '100%-version' more.

**Comment by Tomasz-W** [comment]
I think 80% is visible good and not too noisy. Any other votes?
