### ISSUE TITLE
land polygons missing, seeing blue water where land should be

### ISSUE THREAD

**Issue by d3netxer** [gravitystorm/openstreetmap-carto#3023]
I have downloaded a .pbf of bangladesh from geofabrik and successfully imported into PostGIS and ran the get-shapefile scripts with an up to date version of the openstreetmap-carto layer.

I am testing locally using kosmtik, as you can see in the screenshot, it is blue where there is supposed to be land. Any ideas what the issue might be? I am not sure if kosmtik is causing this or openstreetmap-carto. Thanks.

![screenshot from 2018-01-16 19-00-18](https://user-images.githubusercontent.com/2665840/35018499-dddcfc42-faef-11e7-8bae-93a63beaa459.png)

**Comment by matkoniecz** [comment]
It seems that something went wrong with shapefiles.

Can you delete shapefiles, rerun download script (and look closely is it reporting any problems) and check how map looks again?

**Comment by d3netxer** [comment]
I deleted the shapefiles and downloaded new ones using the download script. It downloaded the shapefiles successfully with no errors. I also was able to open the shapefiles in QGIS and they show up good. I still cannot see them displayed when using kosmtik

**Comment by kocio-pl** [comment]
Which exact file did you download? I get [this PBF](http://download.geofabrik.de/asia/bangladesh-latest.osm.pbf) (md5sum: 593eb5629d20ca763ccb7ee3fee51fef), I have also updated shapefiles with a script and it's working good in Kosmtik. 

You may try with some other country with small amount of data to check if the problem will strike again or look if the same place without data will be also flooded or not. The more testing different things, the better.

**Comment by matkoniecz** [comment]
> I deleted the shapefiles and downloaded new ones using the download script. It downloaded the shapefiles successfully with no errors.

Please, post log of download script to http://gist.github.com/

**Comment by matkoniecz** [comment]
ping @d3netxer - can you post link to logs?

**Comment by matkoniecz** [comment]
Closing due to no response (please post logs once it will be possible for you and I will reopen this issue).

**Comment by d3netxer** [comment]
hi @mackerski do you have any idea how I can retrieve my logs for kosmtik?  Thanks

**Comment by d3netxer** [comment]
hi @mackerski and everyone. Today I tried running the Docker files and it was working great. I then tried installing everything manually using the Docker files as a blueprint, and it was working great. I am not sure what the difference was, I guess it could have been any number of things, including installing nodejs, kosmtik, and postgis using different commands. Thanks
