### ISSUE TITLE
Source of country labels

### ISSUE THREAD

**Issue by Kinslayer-DE** [gravitystorm/openstreetmap-carto#3026]
Hi,
I am stuck a bit with a "latin-only"-version of a OSM map. My first idea was to just include "name:en" for all labels - which turned out to be not the best solution. It seems the openstreetmap-carto-project does a quite good job - so this is perhaps the way to go... BUT... I am puzzled about something I found while testing around with the mapnik xml a bit: Some places still get non-latin labels although I only use "name:en" (COALESCE("name:en", '') AS name). For example when I view the Inner Mongolia at zoom level 4 I get 内蒙古.  Two Things I do not get: Why are there labels in non-latin languages anyway and there is no entry in the database with the three characters 内蒙古 - where do they come from?  What am i missing here?

Thanks for any hint.

Best, Jan

**Comment by matkoniecz** [comment]
> I am stuck a bit with a "latin-only"-version of a OSM map. My first idea was to just include "name:en" for all labels

And therefore it is offtopic on this issue tracker as it is not about this style. Why you posted here?

>  Two Things I do not get: Why are there labels in non-latin languages anyway and there is no entry in the database with the three characters 内蒙古 - where do they come from? What am i missing here?

> Thanks for any hint.

https://www.openstreetmap.org/relation/161349#map=6/53.134/26.895 has '内蒙古' set as ref. Is it possible that you display ref somewhere?

**Comment by kocio-pl** [comment]
I don't get the whole picture, but let's start with some basic facts. I guess you're trying to modify osm-carto style to have some other version.

1. When using osm-carto there's no this name at z4: https://www.openstreetmap.org/relation/161349#map=4/36.77/120.98 , and on z5 it shows the whole name, as expected (see https://www.openstreetmap.org/#map=5/44.825/116.829).

2. The name you see looks like the `alt_name`, not `name:en`, so it was probably included somehow - check it please.

3. There is a fork of osm-carto which shows the names in a different languages than default - maybe it's easier to use this:
https://github.com/giggls/mapnik-german-l10n
