### ISSUE TITLE
Add Icons for Cuisine Key

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3029]
pizza | 57569
burger | 48817
Italian | 36855
Chinese | 29080 
coffee_shop | 26392 
sandwich | 20454
Mexican | 15750 
Japanese | 14102
kebab | 12557
Indian | 12555
chicken | 12466 
German | 11799 
american | 11423
Asian | 11209
french | 10054
ice_cream | 9777
Seems like the usage numbers are there. Plus, it would be cool to find a pizza place just by glancing at the map. As far as what icons to use, that's really my specialty. Amenity=cafe already has an icon. So maybe the one for coffee_shop could be similar. Plus fast food is a burger symbol. So that one might be similar for burger. I have no clue what kind of icon would work for regional cuisine. Maybe a taco for Mexican, a bowl of steaming noodles for Chinese or Japanese, and a bowl of rice with some curry on top for Indian? Italian could be a plate of spaghetti.

**Comment by SomeoneElseOSM** [comment]
As an example, here's what I did for "fast food cuisines" in a different map style: http://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=-24.987809&lon=135.17652

**Comment by kocio-pl** [comment]
Without set of readable icons it's hard to think about doing it and UK style does not work for me, unfortunately. However it's doable for ice_cream for example, because we have the icon already and use it (for both cafes and shops), the question is if we want only this case to be considered.

**Comment by matkoniecz** [comment]
I worry that we would exchange well recognizable icon to bunch of not obvious icons.

**Comment by polarbearing** [comment]
I agree that we cannot cover the world's inventory as icons in a general map. Next would come the shops with all sorts of different products. 
For the restaurants, this would be a good case for a specialised map.

**Comment by matkoniecz** [comment]
>  For the restaurants, this would be a good case for a specialised map.

And in (very unlikely) case that somebody would invent cuisine specific icons, as recognizable as current amenity=restaurant icon we would reopen this issue.

**Comment by SomeoneElseOSM** [comment]
@matkoniecz, I think you're missing the point here.  The idea isn't to "invent cuisine specific icons as recognizable as current amenity=restaurant icon", it's to create _variations_ of a recognisable restaurant (or fast food) icon that can be changed slightly to give a nod towards the cuisine.  Currently https://www.openstreetmap.org/node/2986911576#map=19/52.95646/-1.14639 gets a burger icon, which is pretty silly.  

It's not necessarily straightforward to do, but it's not impossible (I've done it with a few classes of icons - pubs and tourist info among others).  Closing this ticket after a day seems to send a message of "don't bother" to any potential contributors who might be thinking of a way of trying to solve this problem.

**Comment by dieterdreist** [comment]
2018-01-22 15:35 GMT+01:00 SomeoneElseOSM <notifications@github.com>:

> @matkoniecz <https://github.com/matkoniecz>, I think you're missing the
> point here. The idea isn't to "invent cuisine specific icons as
> recognizable as current amenity=restaurant icon", it's to create
> *variations* of a recognisable restaurant (or fast food) icon that can be
> changed slightly to give a nod towards the cuisine.
>


+1



> Currently https://www.openstreetmap.org/node/2986911576#map=19/52.
> 95646/-1.14639 gets a burger icon, which is pretty silly.
>


I don't know about the ice cream they sell, but I can tell you that here in
Italy, ice cream is considered an art, not fast food. It is produced in
artisanal way by craftsmen (a subclass of pastry chefs).

**Comment by kocio-pl** [comment]
If anybody is thinking how to solve this, that would be good. However it might be hard - if we want a burger icon for burger restaurant (I know such places), what should be the icon for generic fast food?

**Comment by polarbearing** [comment]
> https://www.openstreetmap.org/node/2986911576#map=19/52.

There is [amenity=ice_cream(https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dice_cream) for that, used 13k times.

**Comment by dieterdreist** [comment]
2018-01-22 15:51 GMT+01:00 polarbearing <notifications@github.com>:

> https://www.openstreetmap.org/node/2986911576#map=19/52.
>
> There is [amenity=ice_cream(https://wiki.openstreetmap.org/wiki/
> Tag:amenity%3Dice_cream) for that, used 13k times.
>

yes, but it covers every place that (dedicatedly) sells ice cream,
regardless of the type of place (cafe, shop / bakery, booth, ...) Can be an
advantage or disadvantage of course.

**Comment by Adamant36** [comment]
OK. Could there at least be icons for like pizza | 57569, burger | 48817, and sandwich | 20454? I can see why some of them might be hard to create icons for and considered "specialized." But burger already has an icon and icons for the other two should be fairly easy to come up with. Plus, 57,569 uses hardly seems specialized. It would be nice if there was a clearer guideline or something on what qualifies for the map VS what doesn't and what kind of usage numbers there has to be for something to count. For instance there's currently discussion about icons being added for both shop=music  and sport=chess, with 4,644 uses and 1,471. How are those things any less specialized then Pizza's 57,569, which is close to 50 times greater then the number for chess. It seems kind of arbitrary. 

Also, declining the issue by stating that it doesn't fit the map and its unlikely anyone would create an icon for any of them anyway is rather black and white. Instead of doing that, why not at least give some feedback on what could move it along? If I created a different issue for each one would help? Would creating a Wiki page for them or getting their usage numbers higher, even though they are high enough, make them "legitimate" enough to be included or at least for the issue open long enough to hear more then just 6 peoples opinions @matkoniecz? There's 54 contributors, let alone a lot more random passer byes. Maybe other people had something to add.

**Comment by matkoniecz** [comment]
> why not at least give some feedback on what could move it along? 

I did this: 

> And in (very unlikely) case that somebody would invent cuisine specific icons, as recognizable as current amenity=restaurant icon we would reopen this issue.

**Comment by Adamant36** [comment]
@matkoniecz I appreciate that. I'd still like to know in the mean time though if adding individual issues for pizza etc in the meantime would help. Plus what the number of uses a thing needs to have in order to qualify for being added to the map or there is anything else I can do. Because its not really clear. 

Also, you know someone probably isn't going to come along and add contribute icons for all of them, especially for an already closed issue that's not going to be seen by most visitors. Since its not on the main page anymore. Your kind of setting the bar high by making that the criteria. 

I'm perfectly willing to start a new issue for each cuisine key individually if I have and contribute icons for all of them I have too if it comes to it. I'm pretty sure the icons are already out there and don't have to be "invented." There's already icons for hamburger and ice-cream as you know. They would probably have to be modified though and my modifications would probably be crap. Like I've said, it doesn't help to shove the issue into the dust bin. Your willing to let other issues sit there open for months. So why not this one?

Whatever your personal hangups are, I'd like still like to know what I can do on my own to refine this issue so it will satisfy the criteria for inclusion in the map. The icons aside, there were other issues you and others had. So the icons are just one of several problems. There's still the odd issue people have of OSM-Carto being the wrong map for "that type of thing" along with a few other things. I rather be proactive if its possible and solve those qualms if I can instead of waiting for some white knight to come along with the cuisine icons.  Especially since its probably not going to happen. Plus, I think it would be valuable to know what the specific criteria you guys are using to qualify things so it can be added to the documents or something and maybe save other people in the future from running into the same problems I have.

**Comment by Adamant36** [comment]
Screw it. Since there's no cuisine icons, what color would they theoretically be? Same color as the restaurant forks or what?

**Comment by dieterdreist** [comment]
2018-02-01 5:18 GMT+01:00 Adamant36 <notifications@github.com>:

> OK. Could there at least be icons for like pizza | 57569, burger | 48817,
> and sandwich | 20454? I can see why some of them might be hard to create
> icons for and considered "specialized." But burger already has an icon and
> icons for the other two should be fairly easy to come up with. Plus, 57,569
> uses hardly seems specialized. It would be nice if there was a clearer
> guideline or something on what qualifies for the map VS what doesn't and
> what kind of usage numbers there has to be for something to count. For
> instance there's currently discussion about icons being added for both
> shop=music and sport=chess, with 4,644 uses and 1,471. How are those things
> any less specialized then Pizza's 57,569, which is close to 50 times
> greater then the number for chess. It seems kind of arbitrary.
>

it isn't about usage numbers alone. Some things with high usage numbers
won't be rendered anyway by this style, e.g. traffic_sign=city_limit
147.000 uses. Please also note that we are discussing here the distinction
of things that are already rendered, not the addition of something that
otherwise wouldn't show up.



> Also, declining the issue by stating that it doesn't fit the map and its
> unlikely anyone would create an icon for any of them anyway is rather black
> and white. Instead of doing that, why not at least give some feedback on
> what could move it along?
>

I agree it would be an improvement to distinguish pizza, burger, kebab and
sandwich within fast food.

**Comment by matkoniecz** [comment]
> adding individual issues for pizza etc in the meantime would help

Rather not, though looking for a good icons may help.

> I agree it would be an improvement to distinguish pizza, burger, kebab and sandwich within fast food.

It makes more sense, given that fast food is already rendered with food-specific icon.

**Comment by Adamant36** [comment]
@dieterdreist That's a distinction I hadn't thought of. Fair point. Also, I think pizza, burger, kebab, sandwich, and maybe chicken are the main ones on my list. I originally decided to request the icons be added because I mapping a couple of Subways and I didn't think the hamburger or fork fit it at all. Sandwiches are not really fast food and you don't eat them with a fork. 

@matkoniecz OK. I'll just keep with this issue and see what I can do about the icons. Maybe I can come up with some fairly mediocre but tweak-able icons that someone can improve for me. Otherwise, its possible I'll get lucky and someone will come along with some icons of their own to contribute.

**Comment by dieterdreist** [comment]
we could also check for cuisine=ice_cream which is one of several alternative tags that somehow have to do with ice cream, and for these it likely makes most sense to give an ice cream icon precedence over shop and fast food primary tags (unsure about amenity=cafe ). There might not be so many, but we already have an icon for them, and burger icons etc. are a bad choice for these.

**Comment by kocio-pl** [comment]
> I agree it would be an improvement to distinguish pizza, burger, kebab and sandwich within fast food.

Me too. However the problems to solve are:
1. Icons - without some good ones we won't go too far.
2. System:
a) is `cuisine` always more important than amenity type (if not then the cases should be defined)?
b) which amenity types do we want to alter with cuisine: restaurant, fast_food - but maybe others too, like coffee?
c) do we want to use colors to distinguish things - and which way if yes?

For example we have [6 608 burger restaurants](https://taginfo.openstreetmap.org/tags/cuisine=burger#combinations) - is it more important to show what you can eat there or the type/class of the amenity (as currently)? What the burger icon would mean then in general - burger cuisine, fast food or maybe both?

As of color, I was thinking about changing the color of all the gastronomy POIs to not overuse brown, but I've found no obvious color - see https://github.com/gravitystorm/openstreetmap-carto/pull/2824#issuecomment-328521710.

**Comment by Adamant36** [comment]
I have no clue if these are any good, but I spent the last couple of hours working on them. So I'll just put them out there. I can't figure out how to use Inkscape properly. So they aren't in SVG format or anything. But at least its something. I like the burger and pizza box with the heat coming off of it.
![pizza box filled](https://user-images.githubusercontent.com/30259065/35676170-a2ccb1e4-06ff-11e8-9465-55bbcbce884e.png)
![closed pizza box white inside with heat](https://user-images.githubusercontent.com/30259065/35676161-9c058b60-06ff-11e8-933c-0e6f4e3a26fd.png)
![piece of pizza](https://user-images.githubusercontent.com/30259065/35676174-a36b51b4-06ff-11e8-8262-8bf021711c2a.png)
![hamburger](https://user-images.githubusercontent.com/30259065/35676171-a2f1a238-06ff-11e8-952f-95348164cf39.png)

Is there a good guide out there on how to make icons in Inkscape or another program I could use to make them with that will save as SVG?

**Comment by kocio-pl** [comment]
You can check here:
https://inkscape.org/en/learn/tutorials/
