### ISSUE TITLE
Help required with styling

### ISSUE THREAD

**Issue by carrbrpoa** [gravitystorm/openstreetmap-carto#3032]
Hello,

Anyone has an idea about what should I do to avoid things like this:

Zoom X, everything is Ok:
![image](https://user-images.githubusercontent.com/10212618/35230679-d90bb19e-ff7d-11e7-9e12-4c0adcf22975.png)

Zoom X+1, only label is being displayed:
![image](https://user-images.githubusercontent.com/10212618/35230701-ede24236-ff7d-11e7-956c-80843974dd17.png)

I wish that in such cases, map could display icon and label, only label, or nothing.

Thanks in advance!

**Comment by dieterdreist** [comment]
this is offtopic here, but have a look at the shieldsymbolizer.
