### ISSUE TITLE
Airport Terminal Icon

### ISSUE THREAD

**Issue by GEdSS** [gravitystorm/openstreetmap-carto#3042]
aeroway=terminal deserves an icon

**Comment by kocio-pl** [comment]
Thanks for the idea, but for me it's enough that terminals are darker than standard buildings. There can be multiple icons inside if mapped well and it's clear what the standard airport area shape looks like.

**Comment by GEdSS** [comment]
Thanks for the response.  Do you know that MapFactor Navigator will not have the terminal as a point of interest without an icon?  I suspect this applies to other uses of the map.

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 29, 2018 at 1:16 PM, kocio-pl<notifications@github.com> wrote:   
Thanks for the idea, but for me it's enough that terminals are darker than standard buildings. There can be multiple icons inside if mapped well and it's clear what the standard airport area shape looks like.

**Comment by kocio-pl** [comment]
No, I'm not aware of any application relying on osm-carto features and it doesn't make sense for me. I guess all of them use OSM data source (just as we do) and render using their own vector style, which has nothing to do with a raster map our style is producing. Why do you think they rely on this style? 

Anyway, I think it's best if you talk with them to add icon if you want it. We try to make usable map in itself and it's hard enough to meet [our set of goals](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md), so even if your information was correct, we won't add something just for some external use.
