### ISSUE TITLE
Strange rendering of amenity=toilets as a brown circle at zoom level 19

### ISSUE THREAD

**Issue by SelfishSeahorse** [gravitystorm/openstreetmap-carto#3043]
Since the last update (v4.7.0), `amenity=toilets` are rendered as a brown circle instead of the toilets symbol at zoom level 19 (but not at zoom levels 17–18):

![screen shot 2018-01-29 at 20 43 35](https://user-images.githubusercontent.com/14875493/35531252-b64006c4-0536-11e8-902a-31ea3b539ae9.png)

I suspect this to be a bug, because I couldn't fine a reference in the change log (and this change doesn't seem to make sense).

**Comment by kocio-pl** [comment]
Could you post a link to this location? Otherwise it'd hard to investigate it.

**Comment by SelfishSeahorse** [comment]
The screenshot was from here:

* <https://www.openstreetmap.org/node/5141331468>

but it seems to affect all `amenity=toilets`.

**Comment by kocio-pl** [comment]
I don't see this effect wnywhere. Could you post which rendering server are you being served by?: http://tile.openstreetmap.org/cgi-bin/debug

Mine is orm.openstreetmap.org .

**Comment by geowas-github** [comment]
Same with playgrounds:
https://www.openstreetmap.org/#map=19/49.99088/8.27042
![grafik](https://user-images.githubusercontent.com/2790128/35535028-96ff2db0-0542-11e8-8e31-95eabd4a894e.png)

Unfortunately I have just redrawn the plaground, so probably you won't see it any more.

**Comment by kocio-pl** [comment]
Please also report which server did such rendering, I suspect this the source of the problem.

**Comment by geowas-github** [comment]
How do I see this?

**Comment by kocio-pl** [comment]
Through the link I included:

http://tile.openstreetmap.org/cgi-bin/debug

**Comment by geowas-github** [comment]
orm.openstreetmap.org

**Comment by kocio-pl** [comment]
I have seen this just for a moment with orm, but now it's gone. I will check it again tomorrow.

**Comment by SelfishSeahorse** [comment]
> I don't see this effect wnywhere. Could you post which rendering server are you being served by?: http://tile.openstreetmap.org/cgi-bin/debug

scorch.openstreetmap.org

There are even `leisure=pitch + sport=table_tennis` nodes rendered as brown circle:

![screen shot 2018-01-30 at 08 46 05](https://user-images.githubusercontent.com/14875493/35553935-279d97f6-059a-11e8-8ba9-9c484f9211d8.png)

Location: <https://www.openstreetmap.org/node/5148254822>

**Comment by alexander-ii** [comment]
Same thing with the `access=permissive` + `barrier=gate`.
Link to [node history](https://www.openstreetmap.org/node/5370583084/history)

![image](https://user-images.githubusercontent.com/25887642/35564109-16384526-05ca-11e8-89d4-7458893ae2d6.png)

**Comment by jragusa** [comment]
For the record, bicycle_parking at z=19 is also concerned but surprisingly, not all are modified (related to the cache?). At z=18, the correct icon appears.

Example : https://www.openstreetmap.org/node/4693394595

z=18
![z 18](https://user-images.githubusercontent.com/9897203/35568210-59bc774c-05c8-11e8-86ed-7fbe3c3b9dd7.png)
z=19
![z 19](https://user-images.githubusercontent.com/9897203/35568218-5f719b7c-05c8-11e8-8e5f-215cff1a8463.png)

**Comment by kocio-pl** [comment]
Looks like a real style bug, I guess v4.7.1 would be needed soon... 

So the first thing is to find the faulty commit.

**Comment by zerebubuth** [comment]
Might it be related to the [entrances query](https://github.com/gravitystorm/openstreetmap-carto/blob/ebe9c886576668107111399aba8b9bca31981307/project.mml#L1102-L1103)?

```sql
        (SELECT
            way,
            tags->'entrance' AS entrance,
            access
          FROM planet_osm_point
          WHERE tags->'indoor' = 'no'
            OR tags->'indoor' IS NULL)
         AS entrances
```

Seems very general to me, and [this block in `entrances`](https://github.com/gravitystorm/openstreetmap-carto/blob/ebe9c886576668107111399aba8b9bca31981307/buildings.mss#L75-L78) seems to only filter on the `access` tag:

```
#entrances {
  ...
 [zoom >= 19] {
    ...
    ["access" = "yes"],
    ["access" = "permissive"] {
      marker-fill: @entrance-permissive;
    }
    ["access" = "no"] {
      marker-fill: @entrance-normal;
      marker-file: url('symbols/rectdiag.svg');
    }
  }
  ...
}
```

**Comment by kocio-pl** [comment]
This was my primary suspect, thanks for taking a look at it!

In case this is a real reason, the question is if it can be fixed soon ( @tpikonen ?) or it should be just reverted?

**Comment by jragusa** [comment]
I confirm that the ```access``` tag is responsible of the bug because ```bicycle_parking``` without this tag are correctly rendered.

**Comment by tpikonen** [comment]
Yes, the bug is where @zerebubuth indicated. I'll prepare a PR soon.

**Comment by tpikonen** [comment]
Ok, please test PR #3048 if you can. Entrances and toilets with permissive access now render correctly here, but it would be nice to get a confirmation.
