### ISSUE TITLE
Lost rendering of museum building at zoom level 19 / rendering conflict with name of sourrounding pedestrian area

### ISSUE THREAD

**Issue by osm-ToniE** [gravitystorm/openstreetmap-carto#3049]
Hi,

when zooming in from

https://www.openstreetmap.org/#map=18/48.14540/11.56773
to
https://www.openstreetmap.org/#map=19/48.14540/11.56773

the redering of the Museum building "NS-Dokumentationszentrum München" (https://www.openstreetmap.org/way/280336045) gets lost

This is new since I created the "embracing arms" of the pedestrian area "Max-Mannheimer-Platz" (https://www.openstreetmap.org/way/557265455) which now sourrounds the building from 3 sides. 

Br
Toni

**Comment by kocio-pl** [comment]
Thanks for reporting, but it seems like another duplicate of #1465. 

This is not our fault, but a Mapnik bug which is being repaired currently (latest release v3.0.18 doesn't include this bug, but has [another problem](https://github.com/mapnik/mapnik/pull/3811#issuecomment-361407576)). After that, the proper Mapnik version should be deployed on OSMF servers which will fix the issue without any action from our side.

**Comment by polarbearing** [comment]
@kocio-pl - seems your answer refers to the label placement of "Max-Mannheimer-Platz", not to a disappearing museum. 
@osm-ToniE - if indeed the museum building gets lost, could you attach a screenshot, since it renders for me both on z18 and z19, including the new rendering of the entrance nodes.

**Comment by osm-ToniE** [comment]
@polarbearing: Same now for me, fixed.

The original zoom level 19 did not show the building colour and only the housenumber.

Thanks
Toni
