### ISSUE TITLE
Add Rendering of Barrier=log

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3052]
It has 2,874 uses. It would be cool to be able to see when they are blocking roads or acting as barriers in more primitive parking lots. There's a few parking lots and roads around where I live with logs blocking them that look like they can be accessed when they can't because there is a log blocking them that isn't rendered. I suggest logs be rendered similar to how tree rows are with the rounded corner, except thinner and brown. That way, it would be clearly differentiated from a gate, fence, or any other similarly tagged thing.

**Comment by kocio-pl** [comment]
It's hard for me to visualize it, could you provide a sketch and comparizon with tree row?

**Comment by Adamant36** [comment]
Now that you mention it, I realized later on that it should't be mapped as a way like tree row is. So I guess it would probably need an icon instead right? Sorry about that.

**Comment by kocio-pl** [comment]
No problem, but we need the icon proposition anyway to make it show.

**Comment by Adamant36** [comment]
OK. I'll probably attempt an icon hack job for it then.

**Comment by kocio-pl** [comment]
Great, please look here to follow our standards as close as it's possible:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines

**Comment by polarbearing** [comment]
If I understand correctly, these are a log of wood across the way, e.g. to prevent to drive into the forest. It stops mostly motor vehicles, while pedestrians and bikes can go over it (bike dismount), but the barrier itself cannot be opened.
Among such barriers, currently ```bollard``` and ```block``` are rendered with a 3 pixel grey dot (4px >=z18).
Barriers that can be lifted/opened (```gate```, ```lift_gate```, ```swing_gate```) are rendered with an icon.

Thus, the log can easily be grouped with the block, as it is similar in function; and we would not need an icon currently.

**Comment by kocio-pl** [comment]
Sounds good to me. Anybody to make the code?

**Comment by polarbearing** [comment]
Good exercise for @Adamant36 :-)

**Comment by dieterdreist** [comment]
sent from a phone

> On 3. Feb 2018, at 22:08, polarbearing <notifications@github.com> wrote:
> 
> It stops mostly motor vehicles, while pedestrians and bikes can go over it (bike dismount), but the barrier itself cannot be opened.


I’ve seen logs which were put to generally block a way, including pedestrians

**Comment by polarbearing** [comment]
True, but we do not render access currently, and we cannot distinguish if a gate is opened every day or permanently closed with a rusty chain. Just log falls in the same category as block.

**Comment by Tomasz-W** [comment]
If gate symbol is two lines.
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/gate.svg

What about just one simple line which would be crossing blocked way? I think it would be intuitive symbol of a log laying down on a path/ track.

**Comment by kocio-pl** [comment]
We should test if it wouldn't be too close to the gate then (or maybe hardly recognizable).

**Comment by Adamant36** [comment]
Thanks @polarbearing ;) I'm clearly out of my depth. Plus, I think you guys can get it done easier without me mucking things up. So I rather just sit this one out, instead of pointlessly sending things off the rails and looking like a pompous douche bag again.

As a side note, I appreciate the work you people put into this project. Its pretty amazing.

**Comment by polarbearing** [comment]
@Tomasz-W You would need to rotate that single line depending on the orientation of the line to achieve that effect.
