### ISSUE TITLE
Rendering shop=water on the map

### ISSUE THREAD

**Issue by govvin** [gravitystorm/openstreetmap-carto#3060]
In our country, although `amenity=drinking_water` is sometimes available in public areas, the most often commericial source is `shop=water`.  Many contributors resort to using the former because it's rendered on the map, while the latter isn't.

[Taginfo](https://taginfo.openstreetmap.org/tags/shop=water) shows that this feature isn't unusual in other countries, too. 

Kindly consider rendering `shop=water on the map.

**Comment by kocio-pl** [comment]
This would be rather easy (some icons are designed in #3011), but I guess 349 uses doesn't indicate wide acceptance of this tag. However it already has a wiki page:

https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Dwater

**Comment by Tomasz-W** [comment]
I think generic violet dot is enough for these shops. If we are considering icons for water points and taps, similar icon for shop may be confusing.

**Comment by kocio-pl** [comment]
792 uses now in very short time, which doesn't clearly indicate wide acceptance. I will close this issue now, but if it will pass 2k-5k uses, I'll be glad to add an icon.
