### ISSUE TITLE
Add rendering for leisure=sauna

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#3062]
leisure=sauna https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsauna has over 7000 uses. Half of them as ways like
https://www.openstreetmap.org/way/558362650

perhaps we dont need an icon on the first run as most pois have a matching name

The fill could be the same as sports_centre (proposed for waterpark #1490)

**Comment by kocio-pl** [comment]
I prefer proper icon from the start, but I have no idea how should it look like.

**Comment by Tomasz-W** [comment]
I think there are two options:
* a hot pail
https://image.flaticon.com/icons/svg/273/273395.svg
* a person in sauna
https://cdn3.iconfinder.com/data/icons/sport-activity/1024/ic_sauna-512.png
https://cdn3.iconfinder.com/data/icons/glypho-signs/64/user-steam-bath-sauna-512.png

**Comment by kocio-pl** [comment]
All of them are detailed, so it will be hard to have them on 14 px matrix.

**Comment by Tomasz-W** [comment]
What about this?

![leisure sauna2](https://user-images.githubusercontent.com/25656654/36089979-c7cd7b1c-0fde-11e8-80c8-ee6c3a6f3bff.png)

14x14:  ![leisure sauna](https://user-images.githubusercontent.com/25656654/36089983-ccbec022-0fde-11e8-825f-4da53804ed6f.png)

**Comment by kocio-pl** [comment]
Quite good and readable shot! Are you a graphic designer?

I would also try more generic version with heat waves without the bucket (it looks like a square, which makes it harder to guess, and is probably not even needed to understand the concept).

**Comment by Tomasz-W** [comment]
I've ereased the bucket and in my opinion it made icon less intuitive. I'm putting Gist link, please finish the project to acheive effect that you want. I would like to see test rendering in leisure-green, but I think it is readable enough at current shape.

https://gist.github.com/Tomasz-W/9e8e326f76605574264370a23bb17d9f

**Comment by polarbearing** [comment]
what about a person laying flat, more steam waves, and no bucket?

**Comment by HolgerJeromin** [comment]
@polarbearing with the limited space this could be a grilled man (waves under person) or a steaming man (waves over person :-)

**Comment by kocio-pl** [comment]
I think we can go with this design, bucket is not that bad. Anybody wants to prepare the PR?
