### ISSUE TITLE
Highway outline?

### ISSUE THREAD

**Issue by LucFreitas** [gravitystorm/openstreetmap-carto#3064]
![capturar](https://user-images.githubusercontent.com/19976610/36075555-c2a031d6-0f37-11e8-91b0-34b3728e55b2.PNG)

https://www.openstreetmap.org/?mlat=43.83462&mlon=20.04059#map=19/43.83462/20.04059

**Comment by HolgerJeromin** [comment]
The "both" center lines are one osm way:
https://www.openstreetmap.org/way/301484309

**Comment by manfredbrandl** [comment]
I broke up the way and it should look nicer soon.

**Comment by kocio-pl** [comment]
However this might be a Mapnik error - you can try report it.

**Comment by matthijsmelissen** [comment]
Looks like a Mapnik error to me too. I don't think there's anything we can do to fix this on our side.

**Comment by kocio-pl** [comment]
I have found another place where this is visible and might be useful for testing:

![screenshot-2018-4-20 openstreetmap](https://user-images.githubusercontent.com/5439713/39029035-1c026d00-445a-11e8-9dad-d13f95f502b0.png)


https://www.openstreetmap.org/#map=19/54.40491/18.67671

**Comment by matthijsmelissen** [comment]
It was in fact an issue on our side. Fixed by #3202.

**Comment by LucFreitas** [comment]
Thanks!
