### ISSUE TITLE
 Add rendering for amenity=shower

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3067]
Related to #3062 and #2856. May be useful especially for rendering camping, sport places or beach areas.

It can be designed probably quite easily - anybody wants to try?

This tag is quite popular (12 695 uses) and has its own wiki page:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshower

**Comment by Tomasz-W** [comment]
I can try, but you have to tell me what should this icon show.

**Comment by kocio-pl** [comment]
Some ideas are on the wiki page, we could also make something similar to what I did with car wash icon:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/car_wash.svg

**Comment by Tomasz-W** [comment]
I've tried with man shape under this tap at the begining, but it was too detailed in my opinion. 
Tap with water drops under it:

![amenity shower](https://user-images.githubusercontent.com/25656654/36110228-30ead660-1022-11e8-88c0-327a516417da.png)

**Comment by kocio-pl** [comment]
Looks clear and nice for me - another candidate for PR.

**Comment by Tomasz-W** [comment]
Great :) Gist link:
https://gist.github.com/Tomasz-W/45eaf50dad5154effc73fc5e73f4d53c

**Comment by polarbearing** [comment]
Here is an idea with a larger shower head:
<img src="https://upload.wikimedia.org/wikipedia/commons/0/09/Shower_icon_-_Noun_Project_3670.svg"> [source](https://commons.wikimedia.org/wiki/File:Shower_icon_-_Noun_Project_3670.svg)

**Comment by kocio-pl** [comment]
I still feel @Tomasz-W version is better, but @polarbearing make sense too - as always, we need 14 px version to see if it can really be recognized.

Is anybody willing to prepare the PR?

**Comment by Tomasz-W** [comment]
comparsion:

![amenity shower](https://user-images.githubusercontent.com/25656654/36426115-5b92745e-1649-11e8-8d5f-5cdd4f171b6d.png) (Tomasz-W)
![icon_column0000](https://user-images.githubusercontent.com/25656654/36426133-69d3d40e-1649-11e8-88d6-c64624123a69.png) (Noun Project)

**Comment by kocio-pl** [comment]
1) is clearly better for me at this scale.

**Comment by james2432** [comment]
PR added

**Comment by polarbearing** [comment]
The first one looks a bit like garden watering for me. 
The second one has too many drops for the scale, it might be clearer with fewer:

<image src="https://cdn.rawgit.com/polarbearing/384b58b9f4a908b94fdda6f7dd50c378/raw/51a6de9ca063604244e6ec67f8cb1ce44be80019/shower-head.svg"> [source](https://gist.github.com/polarbearing/384b58b9f4a908b94fdda6f7dd50c378)

**Comment by turnsole80** [comment]
Even fewer drops maybe?

**Comment by james2432** [comment]
Tomasz-W's shower looks like a shower head:
![image](https://user-images.githubusercontent.com/498547/37654055-416ead5c-2c17-11e8-8762-41f45e793682.png)

The other one looks like a ufo taking off

**Comment by polarbearing** [comment]
The UFO strikes back:
<img src="https://www.hornbach.de/data/shop/D04/001/780/492/218/65/DV_8_8631824_01_4c_DE_20130111211501.jpg">

**Comment by kocio-pl** [comment]
`amenity=shower + standard=prestige` :smile:

**Comment by james2432** [comment]
I think everyone would be happy with a rain fall shower head, but sadly it's not the standard, unless you are rich...
