### ISSUE TITLE
After running this command "sudo docker-compose up import" got an error. Any Solution???

### ISSUE THREAD

**Issue by 92Emzee** [gravitystorm/openstreetmap-carto#3068]
> import_1   | Reading in file: data.osm.pbf
> import_1   | Invalid blocksize 0
> import_1   | Error occurred, cleaning up

**Comment by matthijsmelissen** [comment]
How did you obtain the data.osm.pbf file?

**Comment by 92Emzee** [comment]
I downloaded it online from the official link and add it in the OSM_Project folder as the format mentioned in the readme file.

> https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md)
Study the quickStart from this link

**Comment by matthijsmelissen** [comment]
The error suggests something is wrong with the pbf. Which extract (direct URL) from http://download.geofabrik.de/ did you use exactly?

**Comment by kocio-pl** [comment]
Could you also check the size and `md5sum` of this file to exclude the possibility of file corruption?

**Comment by kocio-pl** [comment]
Since we lack more information, I will close this issue now. We can reopen it if the reporter will tell us more.
