### ISSUE TITLE
Add rendering for amenity=clock

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3070]
https://wiki.openstreetmap.org/wiki/Tag:amenity=clock
Quite popular tag, it has 11,8k uses.

Pole clocks are sometimes used as meeting points; sundials are tourist attraction, but both aren't rendered so they are unvisible on a map.

Icon proposal:
![amenity clock](https://user-images.githubusercontent.com/25656654/36200731-e5f3eaa4-117d-11e8-9c41-8af80f096819.png)

**Comment by HolgerJeromin** [comment]
We had a PR #2218 
With the current setup we are now able to better show important clocks and hide unimportant clocks.
Perhaps use the [visiblity=* Tag](https://wiki.openstreetmap.org/wiki/Key:visibility)
ping @jdhoek

**Comment by kocio-pl** [comment]
Which ones should be visible and from which zoom level?

**Comment by jdhoek** [comment]
Did something change that will make #2218 possible now? Can we filter on `visibility`?

**Comment by SomeoneElseOSM** [comment]
> Which ones should be visible and from which zoom level?

I'd definitely show at the very least "sundial" - see e.g. [here](https://map.atownsend.org.uk/maps/map/map.html#zoom=20&lat=-25.002957&lon=135.174039) for an example icon (follow the link in "changelog" there to get to the map style and symbol if needed).

**Comment by kocio-pl** [comment]
I like the @Tomasz-W proposition, @SomeoneElseOSM proposition is not clear for me (it's rather "angle", for which I couldn't find anything related on the map).

Since v4.0.0 we can use whatever tags we like (without some not display related, like `source`), because hstore has been introduced and any `key` which hasn't its own space within database can be used with `tags->'key'`.

I agree sundials would be useful, what about some other types?

**Comment by Tomasz-W** [comment]
I'm thinking about excluding small digital clocks like this:
http://l7.alamy.com/zooms/de425e2cb1ed4561bb75b66065ad33c1/digital-platform-clock-victoria-train-station-london-uk-europe-b8adx7.jpg

but at the same time I would like to see big digital clocks like this:
http://stare-neony.pl/pbd2.jpg

Is it technically possible to include` display=digital` + `visibility=area` but exclude `display=digital` with lower visibility or without this tag?

I think all allowed clocks should be rendered on zoom 19, and only clocks with` visibility=area` should be on zoom 18.

**Comment by polarbearing** [comment]
Thus, digital or not is not a criterion in my perspective.

**Comment by kocio-pl** [comment]
> I think all allowed clocks should be rendered on zoom 19, but only clocks with visibility=area should be on zoom 18.

Good idea. I think somebody can make a PR any time she thinks everything is clear.

**Comment by Tomasz-W** [comment]
Gist link:   https://gist.github.com/Tomasz-W/07ed36017474669db82b11cb7f64dd26

**Comment by james2432** [comment]
Do we have an icon digital vs analog or are we just going with the analog version?

**Comment by Tomasz-W** [comment]
@james2432 Analog version for all types.

**Comment by james2432** [comment]
what colour should this be? Brown?

**Comment by Tomasz-W** [comment]
I think man_made-grey would fit this better.

**Comment by james2432** [comment]
PR Created

**Comment by matkoniecz** [comment]
> Pole clocks are sometimes used as meeting points

amenity=clocks includes rendering for all types of clocks.

> sundials are tourist attraction, but both aren't rendered so they are unvisible on a map.

Tourism attractions (at least named ones) are rendered.

**Comment by james2432** [comment]
Are we requiring sundials to be apart of the pull request or has this discussion been only for clocks?

**Comment by Tomasz-W** [comment]
I think the PR should include sundials too.

**Comment by james2432** [comment]
do we have an Icon for it?

**Comment by Tomasz-W** [comment]
@james2432 No separate icon needed, just use an icon from https://github.com/gravitystorm/openstreetmap-carto/pull/3135#issuecomment-387407378

**Comment by james2432** [comment]
The PR ever going to get merged then?

**Comment by matthijsmelissen** [comment]
Closing per https://github.com/gravitystorm/openstreetmap-carto/pull/3135#issuecomment-447722793.

**Comment by matkoniecz** [comment]
I think that it would be better to open new issue "render prominent amenity=clock" or something similar
