### ISSUE TITLE
Forest using tree icons looks strange and cluttered

### ISSUE THREAD

**Issue by OndrejSpanel** [gravitystorm/openstreetmap-carto#3076]
I hope this is the right place to raise the issue, if not, please close it and write me where should I write it instead.

This is probably most glaring aspect of default OSM map style: forests are using not only green color, but tree icons as well:

![image](https://user-images.githubusercontent.com/6927223/36384857-01439f9a-1591-11e8-89a3-70ef8d7ca924.png)

In my opinion the tree images add very little, and clutter the map unnecessarily. They also make the map looking very unusual to me. Notice how clean the map looks like without those symbols:

![image](https://user-images.githubusercontent.com/6927223/36385114-e8c13e40-1591-11e8-9a4f-293057b40736.png)

I understand the idea is the symbols can provide additional information about leaf type (needles, broad leaves, cactus ...). I think in most cases this is not necessary or useful for general public and should not be rendered. At the very minimum, if the leaf type is not specified, the forest could be rendered without the images specifying the leaf type.

**Comment by OndrejSpanel** [comment]
My reasons against using them in a general map view:
- no other map service uses them
- several persons I have shown OSM maps to complained about them, telling me they look strange and clutter the map
- they do not provide any useful info for me, as all forests around here miss the property, and are therefore rendered as mixed
- they look especially ugly when combined with contours, because the contours are much easier to read when on uniform area. This is a case when using Cycle Map layers, or using other services, which combine Mapnik layer with other additional information
- even if the info would be there, I am in general not interested, as the difference between broad leaf / needles is not much important for my activities (hiking, running, MTB)

**Comment by SomeoneElseOSM** [comment]
@OndrejSpanel There was quite a lot of discussion about the forest pattern before it was used, and at the time most people were definitely in favour of it (and chose this pattern over other options).  Would another pattern work better for you?  For example [here](https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=53.157975&lon=-1.08849) is a different style of pattern - does that look better or worse to you, or equally bad?

For completeness it must be mentioned that the cycle map layer is completely independent of this style.  It does use a forest pattern, but a different one.

**Comment by kocio-pl** [comment]
I don't remember anybody complaining about icon clutter (at least I don't remember it). This is general map, there are special maps for hikers, so we try to cover broad spectrum of universal features. Leaf type is one of them and I guess showing lack of leaf type encourages people to add it eventually - and in the places I check, they do add this feature. I was also trying to [visualize leaf_cycle](https://github.com/gravitystorm/openstreetmap-carto/issues/1756#issuecomment-327063068), but it was rejected, so current rendering is half way from what I would like. Of course you have right to see it differently.

**Comment by OndrejSpanel** [comment]
@SomeoneElseOSM It looks quite similar to me at first sight, I would even say their pattern is more visible and therefore more cluttering to me, with one important exception:

There are some areas without tree icons. Those areas use "mixed" icons on normal OSM and on inspection they have no leaf type property. There they show the "mixed" icon only only where leaf type is explicitly specified as "mixed" on that map. This alone would be huge improvement for me. It seems [German version of OSM](https://www.openstreetmap.de/karte.html?zoom=14&lat=53.13873&lon=-1.09651&layers=B000TF) works the same way.

What they have in common is that when they use the forrest pattern, the forest pattern is unnecessarily dense. It looks to me repeating the same icon brings little information while cluttering the display.

I understand this feature has a long history and is a result of discussions and decisions. I just wanted to raise a voice of concern of a user who is coming more or less from outside and has no connection to that history. For me the tree pattern is the reason why I am preferring different renderer when available, like [MapBox Outdoors](https://www.mapbox.com/maps/outdoors/) or [OpenTopoMap](https://opentopomap.org).

**Comment by OndrejSpanel** [comment]
> I guess showing lack of leaf type encourages people to add it eventually - and in the places I check, they do add this feature

@kocio-pl It may be a country / region dependent. I have inspected a few areas here in Czech maps and I did not found many locations where the leaf type would be present. It seems it is similar in this respect in Germany - when checking Germany with the German version of OSM (which does not show leaf type unless specified) many areas in Germany do not have leaf type information.

My suggestion is: do not show the leaf type when it is not specified explicitly.

**Comment by SomeoneElseOSM** [comment]
> There they show the "mixed" icon only only where leaf type is explicitly specified as "mixed" on that map.

Yes - that's exactly what it's doing

> My suggestion is: do not show the leaf type when it is not specified explicitly.

In order to see what that looks like (and how hard it is to do) why not create a version of this map style that shows leaf type (with a forest pattern per leaf type of your choice)?

**Comment by OndrejSpanel** [comment]
> In order to see what that looks like (and how hard it is to do) why not create a version of this map style

I would gladly try that, however I am afraid I would need at least some pointers for this to get started. I do not have a working setup of OSM/Mapnik renderer. I have tried recently to follow some tutorials on how to setup my own Mapnik server, however I am afraid they were too complicated for me. Is there some easier way how to test a map style?

**Comment by kocio-pl** [comment]
Yes, for testing purposes Kosmtik under Docker is probably the easiest way (and might be also enough for not too popular server):

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by kocio-pl** [comment]
Having icons allows also to show the trees when some landuses overlap, like here:

https://wiki.openstreetmap.org/wiki/Standard_tile_layer#Rendering_order
https://wiki.openstreetmap.org/wiki/File:Rendering_order_in_openstreetmap-carto.png

**Comment by kocio-pl** [comment]
I think this proposition is far from what people expect (including me), so I will close this issue now. If some new arguments or ideas arise, it can be reopened.
