### ISSUE TITLE
Weird white Area on the map 

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3080]
There appears to be a weird area on the map in Elk Grove California with z14 and z15. It doesn't seem to happen at any other zoom level though. Its been there a while. Closing and reopening the browser to refresh things didn't seem to help. I don't know if it is a bug with OSM-Carto rendering wrong or something else, but I thought id post it here anyway. 
![2018-02-20](https://user-images.githubusercontent.com/30259065/36468070-b76a3300-1696-11e8-9120-c29503c84779.png)
![2018-02-20 1](https://user-images.githubusercontent.com/30259065/36468075-bfb93678-1696-11e8-891c-4ac3080b0e06.png)

Here's a link to the area https://www.openstreetmap.org/#map=14/38.4654/-121.3405&layers=N

**Comment by sommerluk** [comment]
It happens probably at all zoom levels – the other zoom levels are just not updated.

It’s not a problem of this style. The responsible object is likely https://www.openstreetmap.org/way/33236659#map=13/38.4703/-121.3435 with its “highway=service” tag, which is a data error. I’ve corrected the data error, so it should render fine now (once the tiles have been re-rendered in a couple of hours – currently rendering seems slow). For now, closing this issue. If there are further problems, just comment here. Thanks!
