### ISSUE TITLE
Distinguish different memorial types

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3088]
Currently we render all of memorials by just two icons, which are not every time match real object shape well. I would like to propose more icons to distinguich certain types of memorials.
https://wiki.openstreetmap.org/wiki/Key:memorial

My proposition:
* memorial=war_memorial
![z_memorial](https://user-images.githubusercontent.com/25656654/36630286-4df6c674-1964-11e8-87c9-19fabec3b25e.png) ('memorial' icon)
* memorial=plaque
![z_plaque](https://user-images.githubusercontent.com/25656654/36630290-595d0d0c-1964-11e8-94b5-76ae4c28da46.png) ('plaque' icon)
* memorial=blue_plaque
![z_plaque](https://user-images.githubusercontent.com/25656654/36630290-595d0d0c-1964-11e8-94b5-76ae4c28da46.png) ('plaque' icon)
* memorial=statue
![memorial statue](https://user-images.githubusercontent.com/25656654/36630291-6ebfb21c-1964-11e8-9298-78a24d630ca9.png) (**new**)
* memorial=bust
![memorial bust](https://user-images.githubusercontent.com/25656654/36630295-83cc10f6-1964-11e8-8547-276221216235.png) (**new**)
* memorial=stele
 ![z_memorial](https://user-images.githubusercontent.com/25656654/36630286-4df6c674-1964-11e8-87c9-19fabec3b25e.png) ('memorial' icon)
* memorial=stolperstein
![z_plaque](https://user-images.githubusercontent.com/25656654/36630290-595d0d0c-1964-11e8-94b5-76ae4c28da46.png) ('plaque' icon)
* memorial=stone
![memorial stone](https://user-images.githubusercontent.com/25656654/36630303-a410ce4c-1964-11e8-8831-d5da534105df.png) (**new**)
* memorial=obelisk 
![memorial obelisk](https://user-images.githubusercontent.com/25656654/36630306-afe9789a-1964-11e8-9f77-0480c20c5eba.png) (**new**)

For comparsion:
* ![memorial obelisk](https://user-images.githubusercontent.com/25656654/36630306-afe9789a-1964-11e8-9f77-0480c20c5eba.png) (obelisk icon proposal)
* ![z_monument](https://user-images.githubusercontent.com/25656654/36630319-f95e5cf2-1964-11e8-9ea3-a4cd5c395349.png)  (historic=monument current icon)

* ![memorial statue](https://user-images.githubusercontent.com/25656654/36630291-6ebfb21c-1964-11e8-9298-78a24d630ca9.png) (statue icon proposal)
* ![z_artwork](https://user-images.githubusercontent.com/25656654/36630322-08949c7c-1965-11e8-92dc-7ee717313039.png) (tourism=artwork current icon)

Potentially. we could think about change tourism=artwork icon. Some fast-made ideas (lower block set to 50% transparency):

1) ![tourism artwork](https://user-images.githubusercontent.com/25656654/36630387-e130f1a2-1965-11e8-9847-cb88a7a88e68.png)
2) ![tourism artwork2](https://user-images.githubusercontent.com/25656654/36630388-e15ac5cc-1965-11e8-9f96-0e4d7fc32753.png)
3) ![tourism artwork3](https://user-images.githubusercontent.com/25656654/36630389-e178cfd6-1965-11e8-8207-621b409b9d17.png)

**Comment by kocio-pl** [comment]
Thanks for trying with another set of icons!

I'd rather not change the artwork icon to anything bigger. It was hard to find something generic enough and unobtrusive (see #855 and #2236).

**Comment by kocio-pl** [comment]
See also [proposed rendering of towers (and masts)](https://github.com/gravitystorm/openstreetmap-carto/pull/2671#issuecomment-368689153) by @BushmanK and @wmyrda. The problem is however smaller, since they use different color (man-made gray).

**Comment by Tomasz-W** [comment]
Comparsion:

![b11b4238-df14-11e6-8454-8ce91f5f1a5b](https://user-images.githubusercontent.com/25656654/36717189-5c83e04c-1b9d-11e8-86a0-6ddd4718f7ea.png) (tower in man_made-grey)
![memorial obelisk](https://user-images.githubusercontent.com/25656654/36717107-0dbf8eca-1b9d-11e8-9d84-4b1a0b03c797.png) (obelisk in historic-brown)

For me, it's ok as it is.

**Comment by Tomasz-W** [comment]
Gist links:
* memorial=statue https://gist.github.com/Tomasz-W/56b546f36ca1156856c05f958a8dad01
* memorial=bust https://gist.github.com/Tomasz-W/83c3f9fc135c5d8b0919a9d05eb4017b
* memorial=stone https://gist.github.com/Tomasz-W/f1306db9c0086f0d209c50a9bf30ec73
* memorial=obelisk https://gist.github.com/Tomasz-W/69bc32441fe75c42333915165a01732c

**Comment by geozeisig** [comment]
memorial:type=stolperstein is much more common than memorial=stolperstein. If now memorial=stolperstein is to be rendered we must clarify before how we can make a mass edith.

**Comment by kocio-pl** [comment]
I was reporting the problem of stolperstein and blue_plaque definitions once on Tagging, but got no response. They need some unification or just clearance, but we can decide on our own what we want to render and how, of course.

**Comment by jragusa** [comment]
Ok, I'm taking care of this thread.

**Comment by jragusa** [comment]
@Tomasz-W in reference to your comment of 27/02, there is 3 different icons to compare:
![tower](https://user-images.githubusercontent.com/25656654/36717189-5c83e04c-1b9d-11e8-86a0-6ddd4718f7ea.png) `man_made=tower`
![obelisk](https://user-images.githubusercontent.com/25656654/36717107-0dbf8eca-1b9d-11e8-9d84-4b1a0b03c797.png) `man_made=obelisk`
![monument](https://user-images.githubusercontent.com/9897203/41202353-4b32a2de-6cc8-11e8-9073-58ee805fa611.png) `historic=monument`

**Comment by jragusa** [comment]
Indeed, there is 3 different tags for the same feature and the wiki does not provide any difference between memorial and man_made.

I would suggest to propose a new icon for monument with a different shape to better differentiate from obelisk. Both present a vertical shape and I'm not sure that people will understand the difference. We can also leave the current one to obelisk which remains different to man_made=tower.

Additionally, I'm wondering about the zoom level. Currently:
+ basic memorial tag z=17
+ subtag memorial (plaque, etc) z=19
+ obelisk and monument z=16

Should I change something or leave as it ?

**Comment by Tomasz-W** [comment]
Any other comments about obelisk/ monument icons? As always, I'm open for icon ideas.

@kocio-pl Can you review the topic and share your thoughts? You know the proper zoom levels for certain features the best :)

**Comment by dieterdreist** [comment]
IMHO we should render only man_made=obelisk. It is the first of these tags
and the one with the most usage. The other tags don't have different
semantics / meaning so supporting them will only lead to tag fragmentation.

**Comment by Tomasz-W** [comment]
What do you think about `historic=memorial` + `amenity=bench` combination? Should it be rendered as memorial, bench or do you want special icon for it?

Examples:
![1](https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Vietnam_Veterans_bench_monument%2C_Georgia_Veterans_State_Park.JPG/800px-Vietnam_Veterans_bench_monument%2C_Georgia_Veterans_State_Park.JPG)
![2](https://www.researchgate.net/profile/Maria_Kaczmarek/publication/304368296/figure/fig1/AS:378576516993029@1467271083290/The-so-called-Swiecicki-Bench-a-monument-situated-in-front-of-Collegium-Minus.jpg)

**Comment by jragusa** [comment]
I can test if you submit an icon. Otherwise, I thought about an [equestrian statue](https://en.wikipedia.org/wiki/Equestrian_statue) ([example](https://en.wikipedia.org/wiki/Equestrian_statue#/media/File:Estatua_de_El_Cid.jpg)) but it's probably too much detailled.

**Comment by SomeoneElseOSM** [comment]
If it helps anyone, feel free to draw inspiration from the icons at https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=-25.005818&lon=135.17675 and e.g. https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/symbols/memorial_bench.png ).

**Comment by jragusa** [comment]
Currently,

`memorial=statue`
https://www.openstreetmap.org/node/3822475193
Note the difference with `tourism=artwork` to the right
![memorial_statue](https://user-images.githubusercontent.com/9897203/42136382-56f7801a-7d5a-11e8-9b45-051765e075f6.png)

`memorial=bust`
https://www.openstreetmap.org/node/5501258534
Note the two `memorial=stele` to the bottom right
![memorial_bust](https://user-images.githubusercontent.com/9897203/42136392-7f5b7afc-7d5a-11e8-93b5-115adedfaa7d.png)

`memorial=stone`
https://www.openstreetmap.org/node/4987880673
![memorial_stone](https://user-images.githubusercontent.com/9897203/42136394-920270a2-7d5a-11e8-8fde-e018636e0736.png)

**Comment by Tomasz-W** [comment]
For memorial benches I vote for 'left' version. I also would like to see a test rendering of `man_made=obelisk` new icon next to `historic=monument`.

PS. @jragusa Did you download my icons after 11.06? I was pixel-aligning them and meanwhile I've updated the files in Gist links.

**Comment by jragusa** [comment]
I don't remember but I did the first commit on 12/06 so, in case of, I will reupload your icons

**Comment by matthijsmelissen** [comment]
> To be honest, I think this proposal goes into too much detail, and I wouldnt be happy to add so much new icons for relatively similar objects.

Unfortunately, nobody has responded to this.

I'm still not convinced how much we're gaining from rendering different monument types.

**Comment by kocio-pl** [comment]
Well, for me these are 2 issues: more icons and more detailed rendering rules. More icons are good because they are representing what people see on the ground more accurately and more detailed rules are good to avoid clutter (in this case something I started with #2689, which was the most severe problem).

This is related to the freedom of categorizing and tagging. We try to render tags, because it's simpler technically, but I believe we should render things people see. It's hard to tell if something is forest or woods, so we show the trees, which is what people see (poor tagging definitions is secondary here). It's easy to tell if the memorial is statue or obelisk, so they should be rendered differently (if we have proper icons, not by all means).

**Comment by matthijsmelissen** [comment]
> More icons are good because they are representing what people see on the ground more accurately 

The risk of adding more icons, though, is that map users will need to spend more effort in order to ‘learn’ the meaning if all symbols.

**Comment by kocio-pl** [comment]
But we design icons depicting things more accurately, so in my opinion it will make it easier to recognize than currently, not harder.

**Comment by Adamant36** [comment]
There should be a link on the main site to a list of the icons and their meanings like there is for the road type key. 
Most of the icons are are pretty intuative, but some aren't, and most maps explain what the icons on them are either way. So it would still probably help.

**Comment by Tomasz-W** [comment]
@Adamant36 See https://github.com/gravitystorm/openstreetmap-carto/issues/1928

**Comment by SomeoneElseOSM** [comment]
In the absense of progress on https://github.com/gravitystorm/openstreetmap-carto/issues/1928 , someone might find https://github.com/SomeoneElseOSM/SomeoneElse-style-legend useful (if only for style development and testing).  It contains the raw data that is used to show the legend at https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=-24.988028&lon=135.17629 .

**Comment by kocio-pl** [comment]
I like https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key more, but that's a problem that it's big (and needs updates), while OSM.org website has some short legend, but not suited for such a rich style, and doesn't have even link to this page.

**Comment by Tomasz-W** [comment]
@SomeoneElseOSM @kocio-pl 
Here's more proper ticket to discuss this issue https://github.com/openstreetmap/openstreetmap-website/issues/1307 ;)

**Comment by jragusa** [comment]
@Tomasz-W I updated icons

Few questions remains about obelisk: 
1/ which icon should I include ? the former one or the new one ? (see this [comment](https://github.com/gravitystorm/openstreetmap-carto/issues/3088#issuecomment-396052063))
2/ obelisk is currently set to z16. Should I leave as it or shift to z17 (as the generic icon) or z19 (as dedicated icons) ?

**Comment by jragusa** [comment]
`memorial=obelisk`
https://www.openstreetmap.org/way/72937686

Before
![memorial_obelisk_before](https://user-images.githubusercontent.com/9897203/43047321-e3dd39e4-8dd5-11e8-8954-dc4a0ce5018f.png)

After
![memorial_obelisk](https://user-images.githubusercontent.com/9897203/43047306-b16cf85a-8dd5-11e8-8078-29a7f42fcb97.png)

**Comment by Tomasz-W** [comment]
@jragusa it's not `memorial=obelisk` but `man_made=obelisk` ;) (test rendering is correct but its description isn't, because we decided not to render `memorial=obelisk`)

**Comment by jragusa** [comment]
@Tomasz-W sorry it's a typo error. It's actually a `man_made=obelisk` :)

**Comment by jragusa** [comment]
Sorry for the long pause, I had to finish corrections on a manuscript. I'm working on it.

**Comment by Tomasz-W** [comment]
If someone has an idea for better non-statue artwork icon, give me an info.

**Comment by wmyrda** [comment]
I was thinking about something like https://abstractmetaldesign.com/wp-content/uploads/2017/04/Abstract-Metal-Design411.jpg so as second proposition looks closest to it I am all for it.
Shape of that kind is abstract enough not to resemble anything in particular therefore would not be mistaken with anything else. Third proposition on the other hand looks close enough to the chess figure and could for some imply garden chess.

**Comment by Tomasz-W** [comment]
@wmyrda Please see https://github.com/gravitystorm/openstreetmap-carto/pull/3356#issuecomment-415962852
