### ISSUE TITLE
Render Service Roads in their own color

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3090]
Any chance of having service roads render in their own color along with or instead of just being thinner than normal roads? Not that thinner roads is necessarily an issue, but changing them would make them easier to view and differentiate from normal roads at higher zoom levels. I'm not sure what color would work best. Something like what is being proposed in the issue about rendering road surface might be cool to.

**Comment by kocio-pl** [comment]
It's bigger than you think - roads makes a system, so changing anything requires at least looking how it relates to other. Therefore I will close this issue now.

The main design principle for current roads rendering is making a color scale from very intense (red) to very pale (white), and the steps between colors is well tempered (we use even visual distance between them). One can test road color changes as described here: https://github.com/gravitystorm/openstreetmap-carto/issues/110#issuecomment-367976882. I think without some practice with this code it doesn't really make sense to open issues for just one aspect.

BTW: I was testing light yellow for tertiary, but it didn't work - see #2228 - so it's even less probable for service roads.

**Comment by dieterdreist** [comment]
2018-02-26 2:57 GMT+01:00 Adamant36 <notifications@github.com>:

> Any chance of having service roads render in their own color along with or
> instead of just being thinner than normal roads? Not that thinner roads is
> necessarily an issue, but changing them would make them easier to view and
> differentiate from normal roads at higher zoom levels. I'm not sure what
> color would work best. Something like what is being proposed in the issue
> about rendering road surface might be cool to.
>

probably something that should be discussed on [tagging]: what do you mean
by "normal" road, and why doesn't this comprise service roads?

**Comment by Adamant36** [comment]
@kocio-pl I can understand that. I wasn't neccesarily talking about a complete redesign or anything that drastic though. If you don't mind me giving you an example, maybe you can come up with a solution for the problem that I'm not thinking off or maybe I'm imagining things and its not even a problem in the first place. This is from an Oil Refinery in the Bay Area. 
Z16
![z16](https://user-images.githubusercontent.com/30259065/36668365-ed242bc8-1aa5-11e8-8d12-020b851efe5e.png)
Z15
![z15](https://user-images.githubusercontent.com/30259065/36668397-0b7df1f8-1aa6-11e8-9218-b3abe6d6efc7.png)
Z14
![z14](https://user-images.githubusercontent.com/30259065/36668416-1f1ea7a2-1aa6-11e8-8c07-1ec42367d937.png)
Z13
![z13](https://user-images.githubusercontent.com/30259065/36668464-3e3fa366-1aa6-11e8-8342-51b9d0cecdba.png)
On Z16 things look fine, but then the service roads almost become non-viewable on Z15. I'm not sure why, but it seems like they become a little easier to see on Z14 compared to Z15 for some reason. Even though it is zoomed out further. Then on Z13 the roads become gray and are way easier to distinguish. So would it be possible to also make them gray on Z14 and Z15 since they are to thin to see at as white at that point? 

As a side note to that, there is also an inconsistency between just normal service roads and parking aisles where parking aisles will disappear at Z15 and above, but normal service roads will not. Personally, I think having all service roads either turn gray at Z15 and above so are view-able would be cool. It seems to work good already at Z13 on normal service roads or they could all just disappear after Z15 like parking aisles do. Whatever option works best.

**Comment by dieterdreist** [comment]
IMHO, if the roads need to be visible in zoom13 or 14, they should likely
not get the tag highway=service.

**Comment by imagico** [comment]
> IMHO, if the roads need to be visible in zoom13 or 14, they should likely not get the tag highway=service.

This is wrong on several different levels.

highway=service has a functional definition that bears no direct relationship to at what scale (let alone at what zoom level) it should ideally be shown in a map from a cartographic viewpoint.

Filtering which roads to show exclusively based on zoom level and tags is just a very crude approach to rendering which visibly fails in many cases.  This is not a good reason to re-purpose `highway=service` into `show_at=z15+` or something like that.

**Comment by polarbearing** [comment]
> inconsistency between just normal service roads and parking aisles where parking aisles will disappear...

Parking aisles and driveways are considered 'minor' service roads, so the different behaviour is intentional. Note that a parking area should have its access roads not being tagged parking_aisle.

**Comment by Adamant36** [comment]
@polarbearing OK. It doesn't make that differentiation on the Wikipage. There's some pretty non minor driveways, especially shared ones, to that are more like residential roads in width etc, but still qualify as driveways in my opinion. So if that is the case, how is what qualifies as "minor" even defined? 

@imagico Realistically, I would say your right. But functionally if every "road" was shown on the map at further zoomed out levels I would imagined the roads would overwhelm everything else. Especially considering how close together certain service roads like parking aisles are. Parking lots would just be a big clump of white. I also don't think people who are viewing a map at the regional scale care that much about where a parking aisle or driveway in some random shopping mall that they can barely see is. They probably only care about that type of information when they are zoomed into the neighborhood level. I can't imagine someone would be looking at the area in my example at the Z13 or Z14 level to find out that type of thing.

**Comment by dieterdreist** [comment]
2018-02-26 13:19 GMT+01:00 Christoph Hormann <notifications@github.com>:

> IMHO, if the roads need to be visible in zoom13 or 14, they should likely
> not get the tag highway=service.
>
> This is wrong on several different levels.
>
> highway=service has a functional definition that bears no direct
> relationship to at what scale (let alone at what zoom level) it should
> ideally be shown in a map from a cartographic viewpoint.
>

OK, I was speaking from experience, i.e. for situations I am familiar with
(and in latitudes 40-50), and there might be other cases in "empty" areas
where you'd want to see the service in these zoom levels (despite it being
unimportant for the road grid, what is implied by "highway=service").
Certainly, the posted example works for me:
https://www.openstreetmap.org/#map=16/38.0189/-122.1076
These are roads on a private site (I guess), so you won't be interested in
them if "outside", even if the site is very big, those roads don't have to
show up in high contrast at low zoom levels.


Filtering which roads to show exclusively based on zoom level and tags is
> just a very crude approach to rendering which visibly fails in many cases.
>


agreed, but this is how we do it here anyway. It clearly is a compromise,
also because different latitudes show very different scales at the same
nominal zoom level (not to speak about significance and feature density).

**Comment by dieterdreist** [comment]
for reference, a similar case of an industrial area (private access), here
unclassified was used (perhaps this choice could be contested):
https://www.openstreetmap.org/way/460913555#map=16/48.6981/8.9953

**Comment by SomeoneElseOSM** [comment]
To return to the original question:

> Any chance of having service roads render in their own color along with or instead of just being thinner than normal roads?

I'd certainly support that.  I'm aware of what this map style is trying to do with road colours and I'm aware there's no easy answer (because colours used for different sorts of roads) will be effectively unavailable for other features), but I don't think the current colour choice "works" for me at all.

However, it;s worth noting that other map styles on osm.org can be used to see roads that are missing from the "standard" map.  See for example https://www.openstreetmap.org/#map=15/53.1226/-1.3087 and https://www.openstreetmap.org/#map=15/53.1226/-1.3087&layers=C .

**Comment by kocio-pl** [comment]
> Any chance of having service roads render in their own color along with or instead of just being thinner than normal roads?

>> I'd certainly support that.

The only chance I see (so this is just my opinion on the subject) is somebody making a road colors tuning, but it's a bigger task, which requires somebody willing to take care of this.

**Comment by polarbearing** [comment]
> how is what qualifies as "minor" even defined?

I have difficulties to understand your question, and do not know which wiki page you refer to. 
To distinguish between minor and major service road rendering is a decision in this style here.

**Comment by Adamant36** [comment]
I mean how is it decided what qualifies as a minor service road? on the wiki page for highway=service it does not split them into major and minor catagories. So is that something your saying OSM-Carto does? Or is it that you consider residential and other roads outside of the highway=service tag to also be "service roads", just not ones included on in the key? I guess service roads are usually considered as frontage roads, which kind of excludes some of it subkeys.

**Comment by dieterdreist** [comment]
sent from a phone

> On 26. Feb 2018, at 18:00, Adamant36 <notifications@github.com> wrote:
> 
> I mean how is it decided what qualifies as a minor service road? on the wiki page for highway=service it does not split them into major and minor catagories. So is that something your saying OSM-Carto does?



yes, it is done by the service=* subtag, e.g. service=drive_way and parking_aisle are considered minor with respect to “generic” service ways

**Comment by Adamant36** [comment]
Ah. Ok. Thanks for elaberation. Its still a side thing to my original complaint about service roads having viewing issues at certain zoom levels, but whatever. However you want to catagorize them or not the issue still exists and can probably be fixed.

**Comment by matthijsmelissen** [comment]
Which zoomlevels are the main  problem according to you?

**Comment by Adamant36** [comment]
I went into detail about it in my second message I think. The one with the pictures. The problem is on Z15 and Z14. On Z15 they are are really distorted and hard to see. It gets a little better on Z14 for some reason, but they are still not easy to make out. Then on Z13 they turn grey, which seems to solve the problem. So I was thinking they could turn grey on Z14 and Z15 or just disappear, like parking aisles do already at those zoom levels. Things went off track really quickly though and it never went anywhere.

**Comment by matthijsmelissen** [comment]
Yes, I see what you mean. As I'm quite busy, could you perhaps prepare a pull request?
