### ISSUE TITLE
Render "admin_level=6" ways at zoom levels 9 and 10

### ISSUE THREAD

**Issue by DENelson83** [gravitystorm/openstreetmap-carto#310]
Right now, when you look in the "Standard" map layer on the main openstreetmap.org page, ways tagged as "border_type=county" are rendered at zoom levels 9 and 10, but ways tagged as "boundary=adminstrative" and "admin_level=6" either in the way itself or in a relation are not rendered at those zoom levels.  Could you take the CSS from "border_type=county" and put it into "boundary=adminstrative" and "admin_level=6" for zoom levels 9 and 10?  I would really like to see county boundaries at those zoom levels.

**Comment by matkoniecz** [comment]
https://github.com/gravitystorm/openstreetmap-carto/issues/3678#issuecomment-466934855 has some hints that admin_level 6 may be rendered earlier but I am not convinced by my own analysis.

**Comment by jeisenbe** [comment]
According to https://github.com/gravitystorm/openstreetmap-carto/issues/3678#issuecomment-466919919 the median admin_level=6 area has about 750 square kilometers of area, so this would be 1/2 of the area of a tile at z10. I believe these are 256x256 pixel tiles we are talking about, so an median-sized admin_level=6 polygon should be about 32,000 standard pixels at z10, and 8000 pixels at z9.

Most area features have a name label shown when the area is over 3000 pixels, and the protected_area and tourism boundaries are shown at only 750 pixels, for comparison.

**Comment by jeisenbe** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/issues/3678#issuecomment-605545631

As mentioned above, the median admin_level=6 area is just under 10k way_pixels at the equator at z9. 

The average admin_level=6 area is 2800 km2, so would render at z9 at 60 degrees lattitude as 350x350 pixels, or ~120,000 way_pixels - quite large already.

This suggests that admin_level=6 features could be rendered at z10 or even z9, based on the mean and median sized features at 0 and 60 degrees.

And in fact if we want to implement #4004 (render a central text label for admin_level=6), z10 would be the latest where average-sized areas would still render at mid and low lattitudes, though at high lattitudes only z9 is soon enough.

**Comment by jeisenbe** [comment]
I checked other styles. The German-style fork of this style renders admin areas at the same zoom levels, but the French-style at openstreetmap.fr starts to render admin_level=6) from z7 as a thin, 0.33 pixel-wide line. At z11 admin_levels 7,8 and 9 are rendered.

```
  [admin_level =~ '(5|6)'][zoom >= 7] {
    line-width: 0.33;
    background/line-width: 0.33;
```

See https://github.com/cquest/osmfr-cartocss/blob/master/admin.mss

I suspect this works well for France, but would be too soon for some other countries.
