### ISSUE TITLE
Scrub has different colour with barrier=hedge

### ISSUE THREAD

**Issue by HT43-bqxFqB** [gravitystorm/openstreetmap-carto#3106]
A scrub area with barrier=hedge as the dark hedge colour instead of the default scrub pattern/colour. When a line with barrier=hedge is drawn around the scrub area this bug does not occur.

This example shows the difference between two different tiles after adding the extra line and removing the barrier tag from the scrub area:
![example picture](https://i.imgur.com/X7A1YBf.png)

I'm not sure if this is a bug or a wanted behaviour. :confused:

**Comment by SomeoneElseOSM** [comment]
I believe that barrier=hedge is considered an area tag by the style, which explains what you're seeing.

**Comment by dieterdreist** [comment]
yes, barrier=hedge can be linear or mapped as an area, you can add area=no if it should be interpreted as a linear feature, but then you shouldn’t add an area tag like natural=scrub to it

**Comment by polarbearing** [comment]
Duplicate of #971.
The barrier using the same polygon as the scrub is considered against the 'one feature - one element' rule. 
Mapping a hedge as a closed line is considered a tagging error, as a common hedge around an area would have a gap somewhere to enter the area.

**Comment by HT43-bqxFqB** [comment]
In this case the area is closed of for entering on purpose i'll guess. In the picture https://upload.wikimedia.org/wikipedia/commons/c/cd/PrenzlauerBergArnimPlatz.jpg you can see it on the right side in real life. How should this then be mapped in OSM?

If this is not a bug I will close the ticket.

Kind regards.

**Comment by polarbearing** [comment]
Interesting case. You could map the hedge and the scrub separately, the scrub as an inner ring of the hedge as a multipolygon.

**Comment by HT43-bqxFqB** [comment]
As this seems to be expected behaviour I will close this issue.
