### ISSUE TITLE
Add area rendering for amenity=taxi

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3110]
Similar as amenity=parking, taxi stands are places where cars are parked, so I think they could be rendered with the same area fill. There are two distuinguished icons for these objects, so they won't be confused with each other.

Example places:
https://www.openstreetmap.org/way/359796932
https://www.openstreetmap.org/way/421568284

As you can see, the borders of taxi stand areas are unvisible.

**Comment by kocio-pl** [comment]
I like this idea.

**Comment by dieterdreist** [comment]
sent from a phone

> On 8. Mar 2018, at 18:51, Tomasz Wójcik <notifications@github.com> wrote:
> 
> Similar as amenity=parking, taxi stands are places where cars are parked

actually different to a parking, cars are not parked at a taxi stand, they are standing there waiting for customers. It’s more like a coach at a bus station waiting until it is full and leaves.

**Comment by kocio-pl** [comment]
Would make a lot of sense in place like this:

https://www.openstreetmap.org/way/352186627

The question is if it's really that different that using this color with a different icon would hurt?

**Comment by polarbearing** [comment]
Just for clarification, the retail pink in the example above comes from underlying landuse. 

I'd prefer to paint the area as a highway=service area, i.e. white. That's basically what it is anyway.

**Comment by kocio-pl** [comment]
Anybody to prepare the code to test this idea?

**Comment by HolgerJeromin** [comment]
> I'd prefer to paint the area as a highway=service area, i.e. white. 

Large white areas are very ugly and prominent. 
https://www.openstreetmap.org/#map=15/51.8856/8.4435
This would not be good for unimportant taxi area

**Comment by jragusa** [comment]
With parking pattern
https://www.openstreetmap.org/way/284714637
![taxi](https://user-images.githubusercontent.com/9897203/38581327-d849f118-3d0c-11e8-8504-ce18844a6597.png)

**Comment by Tomasz-W** [comment]
@jragusa Great, thanks! Are you able to prepare a PR?

**Comment by jragusa** [comment]
Yes, I will do :)

**Comment by kocio-pl** [comment]
@jragusa Any news about PR? It should be rather straight to do.

**Comment by jragusa** [comment]
I completely forgot this PR, I will do it this evening.

Thanks for remind me
