### ISSUE TITLE
Don't render duplicate label/shield for connected ways with the same computed style

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#3111]
When there are several ways connected one after the other, their labels are rendered, if possible, one after the other, which leads to such renderings:
![image](https://user-images.githubusercontent.com/13777824/37092526-89133a34-220c-11e8-94ce-e01582d86ad3.png)

You can see here that the _Ruisseau de la Tuilotte_ label is duplicated because the way has been splitted several times because of tagging differences. Still, the rendering of the constituting ways is always the same, but the label is duplicated. Depending on the case, there can be tens of such duplicates. The problem also arises for, for example, road shields:
![image](https://user-images.githubusercontent.com/13777824/37092656-eef83764-220c-11e8-8a86-2bf2b85e439a.png)

My point is, this behavior clutters the tiles with duplicated information: when the name of a waterway is always the same, there is no point in rendering it nonstop, and that can be applied for virtually any label or shield; couldn't we use [`repeat-distance`](http://mapnik.org/mapnik-reference/#3.0.6/text-repeat-distance), as explained on mapnik/mapnik#3869? We could at least use it to limit such duplications.

**Comment by matthijsmelissen** [comment]
We do have text-spacing, which I believe effectively accomplishes the same: https://github.com/gravitystorm/openstreetmap-carto/blob/master/water.mss#L273

However perhaps we should increase the value.

**Comment by matthijsmelissen** [comment]
Labelling this as 'good first issue' as I think the solution should be relatively straightforward.

**Comment by Adamant36** [comment]
Similar to issue #2411. It is a pretty easy issue to tweak. There's some sample images on that issue from me tweaking around with it if anyone wants to have a look. Like matthijsmelissen says, its pretty straight forward.
