### ISSUE TITLE
Render aeroway=landingpad as aeroway=runway

### ISSUE THREAD

**Issue by Codain** [gravitystorm/openstreetmap-carto#3112]
The new tag aeroway=landingpad is not yet rendered.

I propose to render them like aeroway=runway.

See https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dlandingpad

**Comment by imagico** [comment]
I think this is a first - a suggestion to render a tag that is currently not in use.

https://taginfo.openstreetmap.org/tags/?key=aeroway&value=landingpad

**Comment by Adamant36** [comment]
@imagico It seems like landingpad forwards to spaceport now, which supposedly has 42 uses. It's still not that many, but then there probably isn't that many spaceports or landingpads in the world to start with.

**Comment by Codain** [comment]
@Adamant36 No, there is a redirection because aeroway=landingpad is described in the aeroway=spaceport page. A redirection does not mean it has been replaced.

@imagico The thing is that there are not that much landingpad in the world yet (I only have those of SpaceX in mind). But there are two taged in Florida. Taginfo may not be updated because a user replaced them in order for them to be rendered on the map (see http://www.openstreetmap.org/changeset/57057243) but I reverted them (see http://www.openstreetmap.org/changeset/57082461). Two may not be enough for you but I don't think that applying the already existing helipad and runway style will complexity the map. And who knows, others might exists and waiting to be tagged (or have been removed by the same user).

**Comment by imagico** [comment]
I meant this as a simple matter-of-factly observation.  The mapper-developer interaction in style development is a fascinating subject and mappers starting to call for rendering tags that are not (yet) used is a notable development in that regard.

If the concept of a spaceport or a landingpad is practically verifiable for the mapper and if these tags are consistently used in the database - just to mention two criteria which should be central to the decision if something might be rendered here - is a completely different matter.

**Comment by Codain** [comment]
@Adamant36 Yes launchpad can also be displayed. I think it would be a Nice thing to avoid map for renderer changesets.

I'm afraid landingpad will stay a rare thing for the whole century compared to launchpad which are spreading. I don't think it's a good thing to set a minimum number of occurrences for this feature. It's not a new concept, it's a subtype of feature.

**Comment by chatelao** [comment]
Hi guys, I mapped the second one in Florida and miss the rendering too :-)

So, actually as SpaceX is the only company able to land, there are:
- 2 Landing Pads in Florida; https://www.openstreetmap.org/?mlat=28.6178&mlon=-80.6125&zoom=12#map=18/28.48632/-80.54306
- 1 Landing Pad in California (mapped as runway): https://www.openstreetmap.org/?mlat=28.6178&mlon=-80.6125&zoom=12#map=17/34.63436/-120.61106
- It is not clear, if there will be one in Texas. Maybe there will be only the drone ship.

BUT: the future of space industry is oriented to recycling.

=> We could change the tags to "runway" and wait for more to appear. But this would be "tag for render", something I don't like first hand.

**Comment by Codain** [comment]
Thanks @chatelao but we shall not tweak OSM database based on one rendering among many others, otherwise OSM will never improve its data. I can understand that this feature (along with spaceports, launchpads...) will not be rendered because there are not that many in the world (I can understand even if I'm not pro), but one can't say "Hey, let us wait for more tags and meanwhile remove the existing ones in order to render them". Aeroway=landingpad and launchpads may be a rare feature but it exists and has been validated by the community (https://wiki.openstreetmap.org/wiki/Proposed_features/include_spacecraft_in_aeroway).

For information the third landingpad (tagged as a runway) has been created by the same user which has removed the landingpad tag from the Florida ones. I will apply the right tag, even if it means that it will disappear from the rendering.

The question (and request) is if it is possible to render landingpads as runways or helipads. The question can be extended to launchpads and spaceports (which can be rendered as airports).

For information, I'm currently consolidating spaceports in OSM with those in Wikidata and I can tell you that we are missing many spaceports and launchpads in OSM. However we all know the impact of not rendering a feature in order to create the willing to add them (with right tags) in the map.

**Comment by matkoniecz** [comment]
aeroway=landingpad is used exactly 3 times worldwide. Therefore it is too early to render them.

**Comment by matkoniecz** [comment]
> It's not a new concept, it's a subtype of feature.

Then it is enough to render the main type of feature (and tag subtybe using subtags, especially in cases where subtypes are extremely rare).

**Comment by matkoniecz** [comment]
I started tagging discussion at https://wiki.openstreetmap.org/wiki/Talk:Tag:aeroway%3Dspaceport#subtag

**Comment by imagico** [comment]
Well - that is not quite the same.  We also render various tag combinations, in particular for roads, that are practically not used.  `highway=*_link` is kind of like a tag combination, i.e. a concept that is used in analogy without it being invented individually as a distinct tag.

**Comment by coffeepotprotocol** [comment]
"Closed ways are **assumed to be areas** in most other situations, including: aeroway=*" https://wiki.openstreetmap.org/wiki/Key:area, which would include https://taginfo.openstreetmap.org/tags/aeroway=launchpad, so why isn't it rendered ?

**Comment by matkoniecz** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/issues/4917#issuecomment-1870655457
