### ISSUE TITLE
Add icon for shop=ticket

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3115]
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dticket
8.9k uses

From #2541 by @kocio-pl 
> 1. ![](https://cloud.githubusercontent.com/assets/5439713/21753944/0621a028-d5f7-11e6-9028-ac28f66962db.png)

My designs:
2 ![ticketdraft01png](https://user-images.githubusercontent.com/20193716/37281335-9b2db07a-25e8-11e8-8973-bb4d98939d39.png)
3 ![ticketdraft2png](https://user-images.githubusercontent.com/20193716/37281343-9f9df32c-25e8-11e8-8428-cef6fbe6a4fd.png)
4 ![ticketdraft3png](https://user-images.githubusercontent.com/20193716/37281349-a3269742-25e8-11e8-8947-1b906de3fdd7.png)

Shape, rotation, size and text/fill can be adjusted as needed.

Or perhaps an icon based on @Tomasz-W 's vending=* designs?

**Comment by Tomasz-W** [comment]
You can work on some of Noun Project SVG's. It helps a lot.

https://thenounproject.com/search/?q=ticket

**Comment by kocio-pl** [comment]
Maybe 4 with some text would be nice? Just guessing.

**Comment by Tomasz-W** [comment]
@lakedistrictOSM 
Here's a SVG with ticket shape which I used. Maybe it will be useful for you.

https://gist.github.com/Tomasz-W/b18eee2375829d1fa2e97f40fd855968

**Comment by kocio-pl** [comment]
Closed by #3286.
