### ISSUE TITLE
Add icon for shop=video

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3116]
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dvideo
4.3k uses

Based on the proposed icon for shop=music, using a disc design with some film reel:
1 ![video01png](https://user-images.githubusercontent.com/20193716/37281483-1ecc88e8-25e9-11e8-8baa-b12ed1118779.png)
2 ![video02png](https://user-images.githubusercontent.com/20193716/37281491-24452b4a-25e9-11e8-8cfa-69eff79e36ce.png)

**Comment by kocio-pl** [comment]
2 is more readable for me.

**Comment by Tomasz-W** [comment]
Can you delete 1-2 white squares on the left and make the rest bigger? I think it will be more readable then.

**Comment by lakedistrictOSM** [comment]
> Can you delete 1-2 white squares on the left and make the rest of them bigger? I think it will be more readable then.

The proportions are the same as the amenity=cinema icon, but here's a few variations:
3 ![video03png](https://user-images.githubusercontent.com/20193716/37304886-c26901de-262a-11e8-8ed6-5fb811677abf.png)
4 ![video04png](https://user-images.githubusercontent.com/20193716/37304900-ccda0802-262a-11e8-9304-003759917266.png)

And some variations on 2:
5 ![video05png](https://user-images.githubusercontent.com/20193716/37304938-e7bfe574-262a-11e8-9d26-73413ca7add4.png)
6 ![video06png](https://user-images.githubusercontent.com/20193716/37304947-ee2c47ae-262a-11e8-82ef-7100914d36a1.png)

**Comment by kocio-pl** [comment]
I can't distinguish 3 and 4, but both are even better than 2 (perforation holes are more visible). 5 is possible too, 6 is not working for me.

**Comment by Tomasz-W** [comment]
I think it should match `shop=music` icon, so the film stock should be on the left side.

**Comment by turnsole80** [comment]
I would have thought an antique icon would be more appropriate 😂

**Comment by lakedistrictOSM** [comment]
Any further feedback so I can make any final tweaks/variations before releasing the SVG files?

**Comment by jragusa** [comment]
I propose 2 with the perforation holes of 6

**Comment by lakedistrictOSM** [comment]
> I propose 2 with the perforation holes of 6

That looks like...
7 ![video07png](https://user-images.githubusercontent.com/20193716/42137747-fd850d08-7d69-11e8-9cf4-2e7e55717814.png)

**Comment by jragusa** [comment]
@lakedistrictOSM  exactly :)

**Comment by Tomasz-W** [comment]
@lakedistrictOSM Please release Gist link for further PR.

**Comment by lakedistrictOSM** [comment]
Gist for 7: https://gist.github.com/lakedistrictOSM/fea69d2bc425c759e57a1fc60dadb77d

**Comment by jragusa** [comment]
https://www.openstreetmap.org/node/2627276478
![video_after](https://user-images.githubusercontent.com/9897203/42703455-f8974ad8-86cc-11e8-88af-c19c47fbb50c.png)
