### ISSUE TITLE
Add icon for shop=video_games

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3117]
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dvideo_games
2.6k uses

Using the disc design from shop=music with some sort of games console?
Just to give an idea, a very quick sketch: ![video_gamesdraft01png](https://user-images.githubusercontent.com/20193716/37281607-8c8451b8-25e9-11e8-9da3-acecc2c84d95.png) (needs a better design)

**Comment by Tomasz-W** [comment]
It's not readable for me with a CD element. Maybe just a pad will be enough (shop-violet will suggest that is a shop)

**Comment by kocio-pl** [comment]
A pad should be central, and if not alone, maybe add the console box (the one that is easy to recognize) or a simple TV set in the background?

**Comment by doktorpixel14** [comment]
What do you think of this one: https://gist.github.com/doktorpixel14/3b5a5bb589e546f9a12b7716a5d1aecc
It's a generalized gamepad. I think it would be unnecessary to add more objects into the icon, a pad is the most representing thing for video games in my eyes.

**Comment by kocio-pl** [comment]
For me it's OK.

**Comment by lakedistrictOSM** [comment]
It's OK but a little unclear at 14x14. Could you try pixel-aligning the buttons? I agree that nothing else should be added to the icon, although a cable coming out of the top might work.

**Comment by kocio-pl** [comment]
I had also the idea to have a cable "flowing" from the top - it is (probably) included in the original proposition, but not too visible and rather straight.

**Comment by doktorpixel14** [comment]
So here is another version with a small cable: ![image](https://user-images.githubusercontent.com/23462396/38272382-59b3a8c2-3789-11e8-817f-e81171dc1975.png)
For comparison, without: ![image](https://user-images.githubusercontent.com/23462396/38272448-845ad604-3789-11e8-99eb-17443333f8d3.png)
I actually like the one with the cable more.

**Comment by doktorpixel14** [comment]
Okay, so how about this one: ![image](https://user-images.githubusercontent.com/23462396/38295023-fd71b41e-37ec-11e8-98d0-e14794f4056d.png)
I also enlarged the buttons so that they are a bit more visible.

**Comment by dieterdreist** [comment]
2018-04-04 9:47 GMT+02:00 doktorpixel14 <notifications@github.com>:

> Okay, so how about this one: [image: image]
> <https://user-images.githubusercontent.com/23462396/38295023-fd71b41e-37ec-11e8-98d0-e14794f4056d.png>
> I also enlarged the buttons so that they are a bit more visible.
>


I must admit I had the same idea as kocio, I'd try to make the cable
significantly longer (curved, to the left end of the icon and a litte big
back)
Generally, I like this icon

**Comment by doktorpixel14** [comment]
Ah okay, I updated it: ![image](https://user-images.githubusercontent.com/23462396/38296937-397cc5d8-37f3-11e8-9274-622a9c3bf651.png)
You're right, it doesn't look that apple like anymore.

**Comment by doktorpixel14** [comment]
So here are some test renderings:

Way z17 in [Orange Walk Town](https://www.openstreetmap.org/way/411391995) (has no name):
![video_games way z17](https://user-images.githubusercontent.com/23462396/38297628-62aefdb6-37f5-11e8-936f-e42dbdfb8b63.png)
z18:
![video_games way z18](https://user-images.githubusercontent.com/23462396/38297633-64522fe4-37f5-11e8-9e21-a8abb6e6888e.png)
Node z17 in [East Greenwich](https://www.openstreetmap.org/node/4969327777):
![video_games node z17](https://user-images.githubusercontent.com/23462396/38297624-5f519656-37f5-11e8-92f2-2228b8c2fef8.png)
z18:
![video_games node z18](https://user-images.githubusercontent.com/23462396/38297627-60edbf1c-37f5-11e8-927d-30eb11aff7da.png)
