### ISSUE TITLE
Add name of region on a map

### ISSUE THREAD

**Issue by lstolcman** [gravitystorm/openstreetmap-carto#3119]
Hi

I found some issue, when I have view of a particular region, e.g. national park, I would like to see what is the name of the park. Example:

On google maps:
![google maps](https://i.imgur.com/C6HkN0j.png)

On osm.org:
![osm.org](https://i.imgur.com/NadGuz9.png)

**Comment by kocio-pl** [comment]
It's not visible on every zoom level, but it's visible from z9 to z19:

https://www.openstreetmap.org/relation/6482172#map=9/45.5160/15.5196

There is z11-z12 where I suppose peaks and populated place names are eclipsing it. I don't see a quick solution, and the general one is not possible (it's not possible to always show all the elements), so I would close this ticket as not suitable for fixing.
