### ISSUE TITLE
leisure=sauna areas should be rendered

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#3137]
sauna got an icon in #3062, #3129
But an outline is missing

ref #3045 

example area
https://www.openstreetmap.org/way/558362650

**Comment by matkoniecz** [comment]
I am deeply worried about idea that everything should be shown as an area. I am not convinced that it is a good idea.

**Comment by kocio-pl** [comment]
This one is not that important in my opinion and we might leave it as it is. 

But there are some generic landuses which are popular and important, yet they have no visual representation. I appreciate a lot @polarbearing effort to review and coordinate the design phase. That doesn't mean every landuse/object type should get the outline, but some of them really should.

**Comment by matkoniecz** [comment]
> every landuse/object type should get the outline

I agree, that is not feasible.

> some of them really should

I will try to present my view and discuss it (in better location that this one, I probably should not post hopelessly broad opinion here), hopefully we will manage to improve the map :)

> This one is not that important in my opinion and we might leave it as it is.

Yes, I think that I will close it.
