### ISSUE TITLE
Add icon for shop=houseware

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3141]
https://wiki.openstreetmap.org/wiki/Tag:shop=houseware
6.6k uses

Mentioned in #1406 and #2347.

Kitchenware is probably the easiest thing to depict as an icon although we need to be careful that it's not too similar to `amenity=restaurant` (spoon and fork), `amenity=cafe` (teacup and saucer), `amenity=bar` (wineglass), `amenity=pub` (pintglass), `shop=tea` (teapot) or `shop=butcher` (meat cleaver).

A sideview of a bowl on top of a plate might work, or a whisk/spoon/spatula with a bowl or pan.

**Comment by kocio-pl** [comment]
I like 1.

**Comment by lakedistrictOSM** [comment]
I also like 1. Maybe the spoon could be made slightly thicker, if space allows. Is the pot lid at 50% opacity or is it just a bit blurry?

**Comment by Tomasz-W** [comment]
shop=houseware v2:

![shop houseware](https://user-images.githubusercontent.com/25656654/37840403-3e7e3b96-2ebd-11e8-92a7-174bbc5d3eb3.png)

Doesn't it reminds some kind of little cake? If you are satisfied with this shpe, I'll upload it to Gist.

**Comment by lakedistrictOSM** [comment]
A cake with handles?

I still quite like the idea of 1, maybe replace the pot with a [simple bowl shape](https://thenounproject.com/search/?q=bowl&i=227252). (Although I haven't been able to design anything that's better)

**Comment by kocio-pl** [comment]
You can upload it, maybe I will try to tinker with it a bit. It reminds me rather [Osmic version of ferry terminal](https://github.com/gmgeo/osmic/blob/master/transport/ferry-14.svg), but the context and lack of waves will make it not important.

Simple kettle icon examples:
- https://www.shutterstock.com/pl/image-vector/teapot-kettle-vector-icon-500288269
- https://www.iconfinder.com/icons/112314/cooking_eating_hot_water_kettle_kitchen_utensils_raw_restaurant_simple_icon#size=512
- https://www.iconfinder.com/icons/479928/kettle_pot_tea_kettle_teakettle_teapot_icon#size=512

**Comment by Tomasz-W** [comment]
Here you are:   https://gist.github.com/Tomasz-W/c7d59972170e01fcf61ac1bdd4a15f55

I think kettle is too much connected to the tea, a pot is more universal.

**Comment by dieterdreist** [comment]
>
> I think kettle is too much connected to the tea, a pot is more universal.
>


the pot is fine, but the additional spoon was useful too.

**Comment by turnsole80** [comment]
1 is good

**Comment by gpsvisualizer** [comment]
I think it needs the spoon for sure.  Undecided on whether the pot needs a lid.

**Comment by AgusQui** [comment]
Maybe change the spoon for a fork so it does not look like a store that sells soup?

**Comment by gpsvisualizer** [comment]
That's an idea.  The only problem is that with limited pixels, the fork gets very wide and starts looking like Neptune's trident. :)

![housewares2-14](https://user-images.githubusercontent.com/8356259/38478311-e578f02e-3b6c-11e8-92c4-4cc27dda8a76.png) (14px)

![housewares2-42](https://user-images.githubusercontent.com/8356259/38478310-e553bfe8-3b6c-11e8-896d-588826d4dd27.png) (42 px)

I think I prefer the spoon.

**Comment by gpsvisualizer** [comment]
How about we add a knife?
![houseware4-14](https://user-images.githubusercontent.com/8356259/38479012-6a75eef4-3b71-11e8-9b58-275c8a297a72.png) (14px)

![houseware4-42](https://user-images.githubusercontent.com/8356259/38479013-6a8efcf0-3b71-11e8-8133-f1f0d6d97567.png) (42px)

**Comment by kocio-pl** [comment]
I like this design - it's easy to recognize "kitchen bits and pieces" instead of cooking place for example. I would only add a space between pot and a lid.
