### ISSUE TITLE
Poor selection of labels on low zoom levels

### ISSUE THREAD

**Issue by Rovastar** [gravitystorm/openstreetmap-carto#315]
One of the things that I have noticed for some time is the rendering on extreme zoomed out levels level 2-5. I know we really look at these levels but if you do it just looks crazy madness.

I'll take Europe as an example

http://www.openstreetmap.org/#map=3/47.16/32.87

Now that level 3 I would expect to see names for this level for countries, large ones on the map but instead tiny places/countries are.

What happens:
UK is not displayed but Isle of Man and Jersey are.
France is not displayed but Andorra and Monaco are.
Netherlands, Italy and Spain are not displayed but the capitals of these countries are.and Malta, Gibraltar displayed.
This to name but a few.

Frankly it just looks stupid and makes the map look amateurish.

Any ideas how to make this better?
I am thinking that we could look at way area size and do something with this. Looking for large countries and displaying those first but I am not sure if I could get this to work as......

And at level 4 we have different but equally confusing issues.

http://www.openstreetmap.org/#map=4/50.46/11.69

Are are a few highlights
UK displays abbreviation for countries, I know that CYM is Wales but it is just confusing...
Spain is not displayed again but regions like EX are as is the capital.
Turkey's name is displayed but so are regions 1-50 (to whatever).
Most of eastern Europe; Poland, lativa, etc are not displayed but the region abbreviations are.
Belgium has 3 names displayed?!
and many more.

My thoughts for this are it is likely to do with the tagging of admin boundary (wrong levels,etc) and the data. But we could have clearer display for countries versus the admin boundaries/regions. Maybe a different clearer/different colour line size for the country versus states and the text could be different colour/style too. Again I am thinking way area could be helpful here.

I understand to countries like the USA need to have regions/states displayed for a vast country and it would make no sense not rendering them. I am do understand this no easy solution and there will be edge cases no matter that we think logically should be displayed but are not but I think must be able to improve on current situation.

and level 5 

http://www.openstreetmap.org/#map=5/50.121/9.580

has less but still confusing problems, I struggle to know where places are. Too many regions (IMHO) not enough capitals cities (only a few displayed)

Are we just rendering and/or editing boundaries 'wrong'?

Let me know your thoughts people......

**Comment by mkoniecz** [comment]
There are still problems, but issues mentioned here are now fixed.

Except 

>  Belgium has 3 names displayed?!

but it is a tagging problem, it is a single label - see http://www.openstreetmap.org/relation/52411#map=8/50.536/4.398.
