### ISSUE TITLE
Render landuse=landfarm + crop=rice as wetland

### ISSUE THREAD

**Issue by alarije** [gravitystorm/openstreetmap-carto#3166]
### Expected behavior
A rice field (landuse=farmland, crop=rice) is a flooded field, like a wetland or marsh, not a solid soil like most other types of farmlands. The current rendering (a solid brown color) suggest that is a solid soil (ie. can be walked though on foot).

### Actual behavior
I think a more appropiate rendering would be the combination of the current rendering of landuse=farmland and natural=wetland, ie, a solid brown background overlaid with dashed lines.

### Links and screenshots illustrating the problem
![capture](https://user-images.githubusercontent.com/30260970/38304441-ca3d5aa4-3809-11e8-8f9a-e8218f4bf26b.png)
At the left a natural wetland, at the right a rice field. The rice field is a flooded soil same as the wetland.

**Comment by kocio-pl** [comment]
Sounds clever, however I'm not a rice/farmland specialist and I'd like to hear other voices too.

Please add the link to the place you have shown.

**Comment by alarije** [comment]
Sample areas:

https://www.openstreetmap.org/#map=13/43.5726/4.4344 (some areas uses produce instead crop)
https://www.openstreetmap.org/#map=13/37.0898/-6.2588 

This area used landuse=orchad, crop=rice, natural=wetland: combines the rendering of orchad + wetland, appears to be tagged for the renderer

https://www.openstreetmap.org/#map=13/39.2598/-0.3519

This is a rice field (Wikipedia):

https://upload.wikimedia.org/wikipedia/commons/e/e8/Rice_fields_in_Namwon.jpg

**Comment by alarije** [comment]
I didn't know about the "upland rice". Researching on the Internet, it appears that upland rice it's about 12% of all rice (20 million ha of 170 million ha total) , so I don't know what should be the most appropiate tagging. 

Maybe we shouldn't change anything in the renderer and only change the wiki page to indicate that if it's a (flooded) rice field, it should be tagged also with natural=wetland or something like that. Or what you suggest, take the flooded rice as default, and add a new tag for upland rice.

The fact is that there are two types of soil (hard and flooded) and I think they should be represented differently.

**Comment by kocio-pl** [comment]
Thanks for the information! So please update the wiki or discuss new tag, but it's not a rendering problem, so I will close it now.
