### ISSUE TITLE
Layer 0 should cover layer -1

### ISSUE THREAD

**Issue by bmallet** [gravitystorm/openstreetmap-carto#3173]
When there is an area with layer=0, this one should cover an object at layer=-1 in order to hide the -1 object.

This trouble can be seen in Paris for an underground canal which should not be visible under a park, example :
![canal st-martin paris](https://user-images.githubusercontent.com/3845614/38604690-738d0b06-3d71-11e8-8492-ec348d5e396a.png)
- the canal is a tunnel, correct data entered (layer = -1 and tunnel = yes), cf. https://www.openstreetmap.org/way/30438764)
- above this, there is a park (https://www.openstreetmap.org/way/15275096)
but the rendering of leisure=park doesn't cover the layer -1, would be better to not see the canal.

Example of what should be : under the "Place Darno Maffini" (highway=pedestrian, https://www.openstreetmap.org/way/114002999, south part on the screenshot), the canal is not visible.

**Comment by dieterdreist** [comment]
IMHO it is a misconception that tunnels have to be rendered below other
things because they are below in the real world. This would often lead to
them not being visible at all, or having big gaps where obstructed by other
fills. Usually in technical drawings you draw hidden objects (behind
something) with a different line style like dashed, but on top of the rest,
in order to make them visible. The problem in our case is IMHO the white
fill. I would suggest to use dashed casing and not fill at all for
underground waterways,

**Comment by matthijsmelissen** [comment]
> When there is an area with layer=0, this one should cover an object at layer=-1 in order to hide the -1 object.

No, this is not true in general. If we implement what you say, highway tunnels under grassfields would be invisible, and I don't think that's desirable.

We could decide to hide underground canals in general, or change the rendering, but the solution you propose is not an option.

**Comment by dieterdreist** [comment]
I agree with the OP that there is an issue, although the suggested solution does not work. I propose to remove the filling and raise the dashed casing above the areas (including the highway area).

**Comment by kocio-pl** [comment]
Would you like to prepare a code for testing?

**Comment by dieterdreist** [comment]
actually yes, but it will take me some time because I don’t have the environment set up, and don’t have a lot of spare time

**Comment by kocio-pl** [comment]
Given that we have no deadline for that and there are no other people expressing the will to do it, it's OK for me if you do it when you will be ready. If you will need some assistance, just write.

**Comment by bmallet** [comment]
Someone else would like to have the underground canal visible this way : https://www.openstreetmap.org/note/1567091
Would it be possible to "remove the filling and raise the dashed casing above the areas (including the highway area)" ? Would be nice.
