### ISSUE TITLE
Add icon for leisure=bird_hide

### ISSUE THREAD

**Issue by Hjart** [gravitystorm/openstreetmap-carto#3175]
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dbird_hide

~2700 uses so far, but people appears to tag these things in a variety of other ways (primarily as view point) to make them render, as well as name them 'Bird hide' or 'Bird watching tower'.

JOSM has used https://wiki.openstreetmap.org/wiki/File:Binocs-both.svg as an icon since 2016

**Comment by turnsole80** [comment]
There is also the more generic `leisure=wildlife_hide` as well, which has a couple of hundred uses.

**Comment by kocio-pl** [comment]
Any idea how to visualize it? We're showing hunting stand, which is partially similar, but has different overall goal.

**Comment by Hjart** [comment]
The birdwatchers primary tool is his binoculars. Would it make sense to create a head with binoculars peering out over a box or screen?

**Comment by polarbearing** [comment]
We need to distinguish them from [planespotters](http://www.planespotters.net), however, who are a different species. So, some reference to birds is needed.

**Comment by Hjart** [comment]
How about something like https://commons.wikimedia.org/wiki/File:2008-07-25_Geese_over_01.svg (easily recognizable as a bird) then? I guess visualizing both a bird and binoculars (or telescope) in the same icon is stretching it a bit too much?

**Comment by kocio-pl** [comment]
How would it look like in 14px?

**Comment by polarbearing** [comment]
For consistency, the [hunting stand](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/hunting_stand.svg) icon visualises the facility, not the animal.

**Comment by lakedistrictOSM** [comment]
Just binoculars would probably work best. 

In England it's common for bird hides to have names so name=* should be rendered too. Icon and label in leisure-green?

> We need to distinguish them from planespotters, however, who are a different species. So, some reference to birds is needed.

I don't think we do. Is anyone actually mapping "planespotting hides"? The location should give context anyway - nature reserve vs airport etc

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Apr 2018, at 14:30, lakedistrictOSM <notifications@github.com> wrote:
> 
> We need to distinguish them from planespotters, however, who are a different species. So, some reference to birds is needed.
> 
> I don't think we do. Is anyone actually mapping "planespotting hides"?
> 


I agree planespotters won’t hide from airplanes, still I wonder why the term is so specific for birds, and not more generic for wildlife observation.

cheers,
Martin

**Comment by Hjart** [comment]
> I agree planespotters won’t hide from airplanes, still I wonder why the term is so specific for birds, and not more generic for wildlife observation.

I guess the reason is that at least in my part of the world, hides created for observation only almost exclusively target birds. In fact I'm not aware of any hides created for more generic purposes.

I agree though that it could make sense to have a more generic tag/term and if necessary fine tune using a wildlife=bird tag

**Comment by Tomasz-W** [comment]
Here you are, binoculars icon:

![leisure bird_hide](https://user-images.githubusercontent.com/25656654/38781125-225f1a76-40e1-11e8-9b0a-7fa8431617ef.png)

https://gist.github.com/Tomasz-W/3fd344781e0fdffb42e98221d06ee6be

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Apr 2018, at 19:02, Michael Andersen <notifications@github.com> wrote:
> 
> I guess the reason is that at least in my part of the world, hides created for observation only almost exclusively target birds


I was raising this because the only one I am aware of in my proximity is about a “pond ecosystem” and while the board features a lot of birds, there are also different kinds of animals like reptiles and frogs.
I’ve just discovered there is an unspecific version of this tag: https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dwildlife_hide

**Comment by polarbearing** [comment]
My point was that a binocular alone looks like man_made=binoculars, and does not indicate wildlife. 

My favourite with the proposals above is 'goose + binoculars', however the glasses should point towards the bird.

**Comment by kocio-pl** [comment]
There's only one such item:

https://www.openstreetmap.org/node/1804812609

and it still supports @lakedistrictOSM claim about the context, so we could use this icon for all such places in my opinion (there are [more similar tags](https://taginfo.openstreetmap.org/search?q=binoculars#values)).

**Comment by Hjart** [comment]
I think we should be cautious about confusing fixed binoculars (whether tagged tourism=, amenity= or whatever) with bird/wild hides (where people usually bring their own equipment).

So far I agree with  @polarbearing s pick of a favourite.

**Comment by polarbearing** [comment]
> I think we should be cautious about confusing fixed binoculars

Yes that is what I mean. My examples about planespotting or man_made was not about mapping/rendering them, but to show the purpose of the spot, to let the symbol speak for itself. The binoculars are just the instrument. 

@Tomasz-W - could you turn the instrument 180 deg in this example ![image](https://user-images.githubusercontent.com/8266355/38797221-21b3296e-415e-11e8-8afd-fc649ecf7abc.png) ?

**Comment by Tomasz-W** [comment]
@polarbearing 

* ![leisure bird_hide 1 1](https://user-images.githubusercontent.com/25656654/38800287-2fd7b330-4167-11e8-9c0e-69a375503457.png) (goose + binoculars)
* ![1](https://user-images.githubusercontent.com/25656654/38781125-225f1a76-40e1-11e8-9b0a-7fa8431617ef.png) (binoculars-only)

@dieterdreist An eye symbol is too 'wide' here. A certain tool symbol (binoculars) says much more.

I think it's obvious that 'binoculars-only' version is more readable. The question is do we really need a bird shape there? I think leisure-green binoculars would be enough.

**Comment by polarbearing** [comment]
favourite: ![image](https://user-images.githubusercontent.com/25656654/38800287-2fd7b330-4167-11e8-9c0e-69a375503457.png)

**Comment by Hjart** [comment]
Yes, a 'binoculars-only' certainly is more readable, but can we consider the fact that the areas in which bird hides are placed are usually not all that crammed with other info?
