### ISSUE TITLE
Render waterway with tunnel=flooded like tunnel=yes

### ISSUE THREAD

**Issue by flacombe** [gravitystorm/openstreetmap-carto#3179]
### Expected behavior
Ways with waterway=* + tunnel=flooded may be rendered like ways with waterway=* + tunnel=yes
I think canal in tunnels should be thinner on the map from zoom 16 to 19 than now. Colors may be inverted, with way in blue and casing in white or grey

### Actual behavior
Tag tunnel=flooded has no effect, tunnel=yes shows a really wide way with solid white and blue casing

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/216220208
https://www.openstreetmap.org/way/301303197

According to https://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dflooded description and review, tunnel=yes shouldn't be compatible with waterway=canal or waterway=river but since tunnel=flooded has just been introduced and it needs lot of time to carefully move tunnel=yes, render can remain the same.

Thanks in advance and best regards

**Comment by matkoniecz** [comment]
Sorry for disappointing you, especially as this issue is well written but this tag is used only 64 times worldwide.

Once usage grows (1000? 2000? uses) new issue should be opened (it may be just copy-paste of this one with note that tag is now widely used).

See https://taginfo.openstreetmap.org//search?q=tunnel%3Dflooded

**Comment by dieterdreist** [comment]
I believe in the case of tunnels we could render everything that is not
"no" as a tunnel. The main drawback is that it would render typos like
tunnel=eys "correctly", and that it could lead to tag fragmentation (people
might be encouraged to use strange tunnel values because they "work"). On
the other hand we do this with building and the vast majority is "yes",
although there is clear value in knowing the building typology

**Comment by matkoniecz** [comment]
@dieterdreist See also #727 (that is very similar, for irony bonus see who opened it)

**Comment by kocio-pl** [comment]
I think it depends on the object types.

1. Some types are easy to enumerate and may have very different meaning and look (for example `amenity=*`). This is when we need to decide and design rendering case by case.

2. There are some other, like `building=*` or `shop=*`, which might have thousands of legitimate values, but can be rendered similar by default and have only some specific values to be treated in a special way.

3. There are also some crossover types like `highway=*` or `waterway=*`, which are not that uniform (like `highway=bus_stop` or `waterway=dam`) and might look a bit different (like different road types), but sometimes it doesn't have to be different - I think `waterway=fish_pass` might be rendered just like stream, because there is a water visible on the ground (see #2895).

I think tunnels belong to the last category: they are all more or less similar and it's not that hard to render them in a sane way even if the subtype is specific.

**Comment by gustavecha** [comment]
FYI the map become more cluttered in some places
https://www.openstreetmap.org/#map=14/45.7001/6.7228

Especially with ways like this, despite mapped with recommended tagging
https://www.openstreetmap.org/way/544156199

**Comment by jeisenbe** [comment]
Usage has increased to 1485: https://taginfo.openstreetmap.org/tags/tunnel=flooded
Reopened.

**Comment by jeisenbe** [comment]
1355 uses on ways are with waterway tags which we render: https://overpass-turbo.eu/s/Mcc (count)

Features are still clustered in southern France and Europe in general, but there are uses in many countries, so it seems it will be accepted by mappers, and would be worth rendering identical to `tunnel=yes` on waterways.

Link to overpass download of all ways, with map: https://overpass-turbo.eu/s/Mcd

**Comment by imagico** [comment]
Looking at the current use i think it would be advisable to start by not rendering waterway=canal + tunnel=flooded at all and then think about how to suitably render all the different hydropower infrastructure features together to give a harmonic picture and useful feedback to mappers.

If we render waterway=canal + tunnel=flooded like normal waterway tunnels but not render the other related tags - in particular penstocks etc. possibly taking into account location and usage tags - that has a high likeliness of incentivizing wrong tagging - as potentially already does that we render waterway=canal + tunnel=flooded like a normal surface canal right now.

Also related to #3354 by the way.

**Comment by jeisenbe** [comment]
> Start by not rendering `waterway=canal` + `tunnel=flooded` at all

Just this, or also render  `waterway=river/stream` + `tunnel=flooded` same as  `waterway=river/stream` + `tunnel=yes` at the same time?

**Comment by imagico** [comment]
I have not seen significant use of tunnel=flooded on natural waterways at a quick look.

**Comment by flacombe** [comment]
Hi
It makes me happy to see this uses reopened

> Looking at the current use i think it would be advisable to start by not rendering waterway=canal + tunnel=flooded at all and then think about how to suitably render all the different hydropower infrastructure features together to give a harmonic picture and useful feedback to mappers.

Currently there is indeed a problem with situations like here
https://www.openstreetmap.org/#map=19/42.94872/-0.22580
Underground canal is visible on the map and not the overground pipeline going downhill from "Vanne de tête" building.
However I'd be in favour of a thin line, possibly dashed to show the watercourse instead of nothing.
usage=headrace tunnels are often as huge as a car could go in.

Otherwise, it may be possible to render overground penstocks as valuable landmarks. It will need another issue to deal with this.
location=overground is put on them when visible
https://www.openstreetmap.org/way/549908931

> I have not seen significant use of tunnel=flooded on natural waterways at a quick look.
Seems legit, tunnel=flooded is mainly intended to describe man made waterways

**Comment by jeisenbe** [comment]
> may be possible to render overground penstocks as valuable landmarks. It will need another issue to deal with this.

Yes, it would be good to open an issue about rendering `waterway=pressurised` - also related to rendering `man_made=pipeline`

**Comment by flacombe** [comment]
I think #3180 is suitable for that, even if it is closed currently.

**Comment by jragusa** [comment]
The main problem of tunnel=flooded concerns their large extension which may create confusion with streams/rivers and clutter some areas, independently of the rendering of the remaining hydropower infrastructure.

**Comment by flacombe** [comment]
I don't get your point @jragusa 
Currently underground waterways are confused with overground waterways since tunnel=flooded isn't rendered

**Comment by jeisenbe** [comment]
@jragusa or @flacombe, would either of you have time to submit a PR which would remove the rendering of waterways with `tunnel=flooded` for now? 

Later we can consider if there should be a special tunnel rendering for these features, after `man_made=pipeline` and `waterway=pressurised` are handled.

**Comment by sedot42** [comment]
An example where this leads to confusing rendering: https://www.openstreetmap.org/note/2028602

**Comment by jragusa** [comment]
@jeisenbe Do you still remove this feature or render it as a tunnel such as in #3400 ?

**Comment by jeisenbe** [comment]
> remove this feature

I think that would still be the plan for now: see https://github.com/gravitystorm/openstreetmap-carto/issues/3179#issuecomment-529864020

Once the rendering for man_made=pipeline is established, we could then consider if there are some `waterway=pressurised` and `tunnel=flooded` features which should be rendered.

**Comment by SonnyLidarDTM** [comment]
Please have a look at how _waterway=pressurised+usage=penstock_ as well as _waterway=canal+usage=headrace_ are of [a](https://de.wikipedia.org/wiki/Kraftwerksgruppe_Kaprun) are rendered in Austrians national map by dashed blue lines
https://maps.bev.gv.at/#/center/12.7283,47.1984

I think rendering in high zoom levels in Carto would be a good for understanding the hydro system of hydropower plants which are supplied by underground water canals and pressurized pipelines.

**Comment by imagico** [comment]
Please always provide links to the features in question in OSM when using concrete examples.

Please don't discuss new issues in comments to closed old ones.  We have plenty of waterway related issues open at the moment (like #3180, #3354, #4405) - if your suggestion does not fit any of those please open a new one.
