### ISSUE TITLE
Add rendering for emergency=phone

### ISSUE THREAD

**Issue by mmd-osm** [gravitystorm/openstreetmap-carto#318]
JOSM validator complains about amenity=emergency_phone being deprecated and auto-corrects it to emergency=phone when using the "Fix" button. However, the latter is not rendered by the carto style, thus all emergency phones disappeared from the map in some areas [1] recently.

I'd suggest to also include emergency=phone with the same render rule as amenity=emergency_phone in the carto style.

[1] Example for a recent mass update turning amenity=emergency_phone into emergency=phone: http://www.openstreetmap.org/changeset/19082658

**Comment by k1wiosm** [comment]
Is this going to be done anytime soon?

**Comment by pnorman** [comment]
As indicated above, it requires a database reload before it can be considered.

**Comment by mkoniecz** [comment]
@k1wiosm see also https://github.com/gravitystorm/openstreetmap-carto/issues/1286

**Comment by PolyglotOpenstreetmap** [comment]
Maybe we should start double tagging them, like we have to do with public_transport for the coming 20 years.

**Comment by maxxer** [comment]
`emergency=defibrillator` are getting widely diffused in Italy and in Europe lately, I think they would be very useful on the map.

**Comment by mkoniecz** [comment]
@maxxer This is offtopic in this issue. Please comment in existing issue about emergency=defibrillator or maybe create new if there is no issue on this topic.

**Comment by SomeoneElseOSM** [comment]
To be fair to @maxxer , they were sent here by a rather terse answer at https://help.openstreetmap.org/questions/41537/why-aed-defibrillators-are-not-displayed-on-maps and the root cause for the problem described here *is* explained above at https://github.com/gravitystorm/openstreetmap-carto/issues/318#issuecomment-66907947 .

**Comment by nebulon42** [comment]
See also #1286 and #1243 for details on the problem and possible solutions.
