### ISSUE TITLE
Better render names with an hyphen

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#3181]
Have this node as an example https://www.openstreetmap.org/node/3474947606 with the name as `São João del-Rei`

From zoom level 15 to 9 we have this:
![15](https://user-images.githubusercontent.com/982338/39016876-135bd022-43f8-11e8-8269-4f6358ac11a4.png)![14](https://user-images.githubusercontent.com/982338/39016875-13387f6e-43f8-11e8-9c58-3881eb3062d5.png)![13](https://user-images.githubusercontent.com/982338/39016874-1311835a-43f8-11e8-9253-0b72d83fe6d6.png)![12](https://user-images.githubusercontent.com/982338/39016872-12eef588-43f8-11e8-9ef8-776271580186.png)![11](https://user-images.githubusercontent.com/982338/39016871-12ccd142-43f8-11e8-85a7-4cb71dfb9e32.png)![10](https://user-images.githubusercontent.com/982338/39016870-12aacdc2-43f8-11e8-9a7c-97e337c1b046.png)![9](https://user-images.githubusercontent.com/982338/39016868-127e652a-43f8-11e8-94b3-32d470482935.png)

The name is being split at the `del-Rei` hyphen, while it most probably should not be (the renderer should consider it as a single word and not as a line-wrapping symbol).

For example, instead having this
```
São João del-
     Rei
```
_(due to the hyphen and the current rendering (above), it could be misinterpreted as `São João delRei`)_

we could have it split like this:
```
São João
del-Rei
```

**Comment by matthijsmelissen** [comment]
Thanks for reporting. Unfortunately I dont think this is something we have control over.

**Comment by naoliv** [comment]
Isn't there something that chooses where the phrase is split?
It can't be random (so some rule or some kind of logic exists to decide this)

**Comment by kocio-pl** [comment]
It's controlled by Mapnik, which this style uses as the rendering engine. You can report the problem there: https://github.com/mapnik/mapnik/issues

**Comment by naoliv** [comment]
Ah... right. Thanks!

**Comment by sommerluk** [comment]
The [responsible code](https://github.com/gravitystorm/openstreetmap-carto/blob/529e3f69718ff21de5a069f6d4cc086b152a6185/placenames.mss#L271) is:

```CartoCSS
text-wrap-width: 45; // 4.5 em
```

That means: If a line is gets longer than 45 pt, than Mapnik tries to do a line wrap afterwards. Apparently, there are two different kind of line wrap in Mapnik:
- The [`text-wrap-character`](http://mapnik.org/mapnik-reference/#3.0.20/text-wrap-character) property defines at which characters a  line wrap can be done. Default is: space character only. The [`text-repeat-wrap-character`](http://mapnik.org/mapnik-reference/#3.0.20/text-repeat-wrap-character) defines what happens with this character. By default it is removed. (That means, a space character is removed where a line break happens.) openstreetmap-carto uses currently the default settings of Mapnik.
- Apparently, after `U+002D HYPHEN-MINUS` line wraps are also allowed. I did not find any Mapnik property to fine-tune this behaviour.

The screenshot that you have posted shows – in my opinion – two independent problems:

1. A line wrap is allowed after `U+002D HYPHEN-MINUS`. Indeed I agree that it would be better for cartographic purposes when there was no line wrap after hyphen. This would also avoid some confusion. Possible solutions:

   a. Substitute `U+002D HYPHEN-MINUS` by `U+2011 NON-BREAKING HYPHEN`, which is meant to be visually an identical glyph, but which does not allow a line wrap. I’ve verified that Mapnik indeed does not make a line wrap at `U+2011 NON-BREAKING HYPHEN`. The substitution could be done within openstreetmap-carto in the SQL query.

   b. Mapnik support for customizing hyphen line wrap. This would be more elegant than a substitution in the SQL query. That means open a ticket at Mapnik’s issue tracker. If they decide to implement it and after a new Mapnik version is released and later packaged for Linux distributions, after that we could make use of it in openstreetmap-carto.

2. The line length is not always well balanced for multi-line labels. Imagine that the name of this village would be `São João del Rei`, without any hyphen. The rendering would be
```
São João del
     Rei
```
Also here, it would be better to have
```
São João del
     Rei
```
instead. This would require a line-breaking algorithm a little bit similar to the one that is used in TeX: Not simply consider the length of the current line and break everything that’s too long, but consider the consequences for the following lines as well, to get the best possible overall harmony. (Well, given that the labels in cartography a much shorter than entire book paragraphs typically done in TeX, the algorithm could maybe be much more simple than TeX’s algorithm.) There’s nothing we can do about that in openstreetmap-carto. This would have to be implemented in Mapnik…

**Comment by sommerluk** [comment]
Edited wrong formatting in my previous comment.

**Comment by sommerluk** [comment]
After taking a look at [the comment](https://github.com/mapnik/mapnik/issues/3885#issuecomment-386432449) from @talaj I think we have to leave the current behaviour “as is”.

Mapnik behaves conforming to the Unicode Line Break Algorithm (provided by ICU BreatIterator). As apparently they use a default locale for the BreatInterator, the behaviour is “untailored”. The algorithm is quite sophisticated and provides good results overall – not only for text in Latin script, but also for Asian scripts and complex scripts. This is great, and I do not want to sacrifice this for better rendering of names with a hyphen.

I understand that well the argument of this ticket, but I think the price we would have to pay is too high.
