### ISSUE TITLE
Add icon for amenity=bureau_de_change

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3185]
https://wiki.openstreetmap.org/wiki/Tag:amenity=bureau_de_change
9.8k uses

Maybe something similar to amenity=bank but with two different note designs? Or note and coins? 

I've had a go at a few designs but haven't produced anything suitable yet.

**Comment by Tomasz-W** [comment]
Icon proposals:
* ![amenity bureau_de_change](https://user-images.githubusercontent.com/25656654/39094603-2db185b6-4632-11e8-9aa4-b7c244cc267a.png) (4 currencies)
* ![amenity bureau_de_change2](https://user-images.githubusercontent.com/25656654/39094645-3221760a-4633-11e8-9a92-0af5179376e6.png) (dollar + euro)
* ![amenity bureau_de_change3](https://user-images.githubusercontent.com/25656654/39094648-354e24a4-4633-11e8-856d-6f0072900afc.png) (dollar + pound)

**Comment by kocio-pl** [comment]
Just for the record - there is a universal ["currency" symbol](https://en.wikipedia.org/wiki/Currency_sign_(typography)) (¤), but it's impractical, because it's not used or even known in the real life.

It might be hard to design because of limited space and complex idea. What about two halves of a banknote, maybe with arrows between them?

**Comment by lakedistrictOSM** [comment]
@Tomasz-W "4 currencies" is a bit too detailed but one of the "dollar +" designs might work, maybe the Euro one since more countries use the Euro than the Pound. 

I've only ever seen the "universal currency" symbol used as an asterisk and wouldn't know what it was if you hadn't said @kocio-pl. The two banknotes idea sounds good.

**Comment by Tomasz-W** [comment]
@kocio-pl @lakedistrictOSM 

> What about two halves of a banknote, maybe with arrows between them?

It would be too detailed and not intuitive. I've tried to add an arrows to 'dollar + euro' design, but it was not readable. Another option is to move these signs to the corners, so they will look like some "S.E." a little bit less.

![amenity bureau_de_change2](https://user-images.githubusercontent.com/25656654/39526005-dd5579bc-4e1d-11e8-97f1-ffec6724adf3.png)

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/b438cd0bd7305fec2c29b6bdc766e48f

**Comment by jragusa** [comment]
https://www.openstreetmap.org/node/2140012378
![bureau_de_change](https://user-images.githubusercontent.com/9897203/42277832-fc4834fc-7f98-11e8-8771-264bc664bac3.png)

**Comment by Tomasz-W** [comment]
I think this icon would be better with arrows symbolising an exchange:
![amenity bureau_de_change2](https://user-images.githubusercontent.com/25656654/42282239-2590a472-7fa6-11e8-967c-402f42b35599.png)

added to Gist link: https://gist.github.com/Tomasz-W/b438cd0bd7305fec2c29b6bdc766e48f

**Comment by Adamant36** [comment]
https://thenounproject.com/search/?q=exchange&i=712667

https://thenounproject.com/search/?q=exchange&i=1588829

https://thenounproject.com/search/?q=money%20exchange

**Comment by jragusa** [comment]
with the arrows:
![bureau_de_change 2](https://user-images.githubusercontent.com/9897203/42284636-6b9df706-7fad-11e8-9b7c-fa29a59e386d.png)
This version looks good to me

**Comment by jragusa** [comment]
@Tomasz-W could you try to correct the icon according to the [comment](https://github.com/gravitystorm/openstreetmap-carto/pull/3301#issuecomment-404896042) of @kocio-pl ?
