### ISSUE TITLE
Add icon for shop=bookmaker

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3186]
https://wiki.openstreetmap.org/wiki/Tag:shop=bookmaker
6.5k uses

@SomeoneElseOSM icon: https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/symbols/shop_bookmaker.p.16.png

Or maybe something combining luck/gambling and a ticket?: ![bookmaker02png](https://user-images.githubusercontent.com/20193716/39085944-7c98280c-4582-11e8-8bb7-f4b9082c757d.png)

**Comment by IVAN-RSM** [comment]
I would put an icon of a roulette with a horse in the background?

**Comment by lakedistrictOSM** [comment]
> I would put an icon of a roulette with a horse in the background?

A roulette would work for [amenity=casino](https://wiki.openstreetmap.org/wiki/Tag:amenity=casino) (4.8k uses) but I'm not so sure for a bookmakers. 

Bookmakers are generally about predicting scores/winners so maybe...

- some sort of score with question marks ?-?
- winner's podium https://www.shareicon.net/sports-winners-winner-podium-olympic-644286
- rosette/medal/trophy?

**Comment by IVAN-RSM** [comment]
I do not know there, but in Spain many bookmakers have a little roulette among sports bets of all kinds

**Comment by kocio-pl** [comment]
What about just four-leaf clover?

**Comment by eehpcm** [comment]
I suspect the commonest bets accepted in most countries are on horse racing.

Problem is, I think, any suitable icon would be too complex to display at a standard size.  A jockey wearing the distinctive hat, and holding a whip (in countries where a whip is still legal) astride a horse, is far too complex.  Maybe a horse's head by a winning post is feasible, but probably not.

Got it.  A burning banknote or a banknote being dropped down a drain.  They're equally good ways of throwing your money away.

**Comment by eehpcm** [comment]
Dice represent gambling, but casino rather than bookmaker.  I don't frequent bookmakers, but I've never heard of one with dice.  Pile of chips even more so (never heard of a bookmaker with a roulette table).  Pile of money suggests bank.

Stylized bookmaker?  What do they look like?  Maybe [this guy](https://en.wikipedia.org/wiki/John_McCririck)?  But he was a racing commentator, not a bookmaker.  And deliberately dressed unlike anyone else.

**Comment by dieterdreist** [comment]
2018-04-30 18:39 GMT+02:00 eehpcm <notifications@github.com>:

> Pile of money suggests bank.
>



they put a "B" (like Bitcoin or betting) on the coins, so you know it can't
be a bank ;-)

**Comment by Tomasz-W** [comment]
I went to some bookmakers webpages to get some inspiration. I noticed that there is "1 X 2" on top of every table. I transform it into an icon.
Is it intuitive? Is it readable enough?

![shop bookmaker](https://user-images.githubusercontent.com/25656654/39527865-daa99144-4e22-11e8-875b-c814ac91bbe3.png)

**Comment by lakedistrictOSM** [comment]
Or as bets are written in the form 2/1 how about something like **2/1**

**Comment by lakedistrictOSM** [comment]
@Tomasz-W Do you want to try designing another icon proposal for this? Maybe something based on my design, the 4 leaf clover suggested by kocio-pl or a ticket with a bet like "2/1".

**Comment by Tomasz-W** [comment]
@lakedistrictOSM As I remember, I've tried some designs with 4-leaf clover, but it didn't go well.

I think we should choose proper icon out of these 2 proposals:
1) ![1](https://user-images.githubusercontent.com/20193716/39085944-7c98280c-4582-11e8-8bb7-f4b9082c757d.png) (@lakedistrictOSM )
2) ![2](https://user-images.githubusercontent.com/25656654/39527865-daa99144-4e22-11e8-875b-c814ac91bbe3.png) (@Tomasz-W)

**Comment by kocio-pl** [comment]
1 is much better, but what about 4-leaf clover I asked before? Could you test it?

**Comment by Tomasz-W** [comment]
@kocio-pl 

> I've tried some designs with 4-leaf clover, but it didn't go well.

**Comment by kocio-pl** [comment]
I see, so I vote for 1 and dices for casino (so they be different).

**Comment by Tomasz-W** [comment]
@lakedistrictOSM Can you publish Gist link with your design? 

Is there anybody interested in making PR for this feature?

**Comment by meased** [comment]
I like icon 1.

**Comment by lakedistrictOSM** [comment]
Gist: https://gist.github.com/lakedistrictOSM/32004edd44e3225ca4ccef43bd91d857

**Comment by Tomasz-W** [comment]
@lakedistrictOSM I've checked the file, and there are some problems (the code is longer than usual). To use any icon, we must have it in "clean version". To do it, you have follow these steps in Inkscape:

* if some black elements are hiden under white elements, mark these shapes by clicking them with "Shift" pressed, an then go to menu Path -> Difference
* unite all elements by clicking them with "Shift" pressed, and then go to menu Path -> Union
* save the file as "Plain SVG"

**Comment by Tomasz-W** [comment]
@lakedistrictOSM When I saw a code longer than usual, I though you skipped one of the steps. I don't have enough knowledge to locate what is the reason of this longer code, but if you did all these steps, icon seem to be ok, I think, so no problem :)

**Comment by kocio-pl** [comment]
What about `shop=lottery`? It is as popular as this one:

![taghistory 50](https://user-images.githubusercontent.com/5439713/46251626-447cdd00-c458-11e8-9874-068acaae5561.png)

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dlottery

**Comment by eehpcm** [comment]
@kocio-pl 

> What about shop=lottery?

That surprises me.  In my town there is one bookmaker and 6 or more places selling lottery tickets.  

However, the bookmaker is exclusively a bookmaker and does no other type of business whilst all of the places selling lottery tickets do so as a sideline.  There is a newsagent that also happens to sell lottery tickets.  There is a supermarket that also happens to sell lottery tickets.  There are a couple of convenience stores that also happen to sell lottery tickets.

You can see where I'm going with this.  The bookmaker is solely a bookmaker and ought to be tagged as such.  The supermarket is primarily a supermarket and ought to be tagged as such.  The convenience stores are primarily convenience stores and ought to be tagged as such.

Is it so very different in other parts of the world that they have shops dedicated to selling lottery tickets?  Or are these shop=lottery tags nodes placed within buildings that are other types of shop?   If the latter then with current rendering technology it's going to be a toss-up which gets rendered.  I suppose it depends if you're desperate to buy groceries or desperate to buy a lottery ticket as to which you'd prefer rendered.  I've bought a lot of groceries over the years but never once bought a lottery ticket (or made a bet at a bookmaker).

**Comment by kocio-pl** [comment]
It's quite easy - just check the wiki page:

> A shop of which the main or only purpose is the sale of lottery tickets. 

>  In many other countries, lottery tickets are not bought in dedicated lottery shops, but for instance in shop=newsagent or shop=kiosk, then use lottery=yes instead.

**Comment by dieterdreist** [comment]
sent from a phone

> On 30. Sep 2018, at 02:56, eehpcm <notifications@github.com> wrote:
> 
> However, the bookmaker is exclusively a bookmaker and does no other type of business whilst all of the places selling lottery tickets do so as a sideline. There is a newsagent that also happens to sell lottery tickets. There is a supermarket that also happens to sell lottery tickets. There are a couple of convenience stores that also happen to sell lottery tickets.


same situation in Italy and Germany, lottery is not a dedicated shop type here, but is an item you can buy at other shops

**Comment by matkoniecz** [comment]
@lakedistrictOSM 

> Or maybe something combining luck/gambling and a ticket?

What is the source of this icon? Is it something that you made or is it case of "found on the internet"? What is its copyright status?

**Comment by lakedistrictOSM** [comment]
I made the icon myself in Inkscape, with the shape in the middle being adapted from one on Wiki (copyright free). It was only intended as a draft to hopefully inspire something better but it ended up being used! I'd still like to see a four leaf clover design if anyone wants to have a go!

**Comment by matkoniecz** [comment]
Thanks for info! I noticed that it was nowhere explicitly specified who is the author, so I wanted to confirm that everything is OK.
