### ISSUE TITLE
Render names of building:part

### ISSUE THREAD

**Issue by DeusFigendi** [gravitystorm/openstreetmap-carto#3188]
I'm just having a german discussion [here](https://www.openstreetmap.org/note/1293463#map=18/52.03824/8.49377) about tagging building parts as buildings to get the names of the parts displayed  in OSM-carto because names of building:part which ain't buildings are not rendered.

Well I think it's right, the names of building:part should be rendered so I'd like to suggest this.
Maybe at a more detailed zoom level but buildings maybe smaller or lighter but the buildings name but it should be rendered I'd say.

**Comment by kocio-pl** [comment]
I'm not sure if this is good idea. Could you show some examples of building:part name which make sense without the outline?

**Comment by DeusFigendi** [comment]
Yes of coarse,
my example was [the university of Bielefeld](https://www.openstreetmap.org/way/582358481#map=17/52.03779/8.49493). You can see the university and all "around" letters, in the east "A" and going north-western B-C-D-E (and F) and on the south side S-T-U (V) W. Very south-eastern there is "J".
Well this letters are the **names** of building-parts because the whole thing is **one building**. But the names are only displayed/rendered because the building:part s are tagged as buildings too, but this is semantically wrong. To have the names of the bulding party displayed is the reason why [Heros](https://www.openstreetmap.org/user/Heros) tagged them this way he/she told me.

This is my example.

I **could** also imagine castles or the like with building:part s named "west wing" or the like but I'd guess it's not very common to give (somehow official/documented) names to building parts. I estimate this maybe on administrative buildings or huge, somehow open/public buildings.

**Comment by kocio-pl** [comment]
Aren't they rather a `ref` than `name`?

**Comment by DeusFigendi** [comment]
Hmmm that's a very valid question.
To be honest: I don't know but I don't think so. I **think** `name` is the correct key here. But I will ask for other opinions.

**Comment by michaelletzgus** [comment]
I'm just testing the 'ref' with building part A.
I thing 'ref' is semantically OK because the name of the whole building, including the parts, is "University".
The different parts have more specific refs.

This scheme will work until a reason for a different name occurs, for example "Bielefeld University" and "University of applied sciences" in the same building.

So I would prefer this scheme for *:part objects:

1. Render name if present
2. Render ref if present but no name

Or: Introduce "*:part:name"

**Comment by dktue** [comment]
I think rendering of building-parts is a good idea; consider the following example:

![image](https://user-images.githubusercontent.com/2878623/43061183-8b11fd98-8e54-11e8-8059-5764420afe72.png)
https://www.openstreetmap.org/relation/5011450
https://www.openstreetmap.org/way/610116329
https://www.openstreetmap.org/way/343686293
https://www.openstreetmap.org/way/343686294
https://www.openstreetmap.org/way/343686295

**Comment by dieterdreist** [comment]
2018-07-23 8:46 GMT+02:00 dktue <notifications@github.com>:

> I think rendering of building-parts is a good idea; consider the following
> example:
>
> [image: image]
> <https://user-images.githubusercontent.com/2878623/43061183-8b11fd98-8e54-11e8-8059-5764420afe72.png>
> https://www.openstreetmap.org/relation/5011450
> https://www.openstreetmap.org/way/610116329
> https://www.openstreetmap.org/way/343686293
> https://www.openstreetmap.org/way/343686294
> https://www.openstreetmap.org/way/343686295
>
> —
>


IMHO in this case it is a mapping error, these are not building parts but
buildings (I happen to know the situation quite well personally), which
happen to be connected via overpasses. Generally I agree that rendering
names for building parts does make a lot of sense in some cases (those
where the mapper divided the building into logical parts according to the
function / structure and these parts are known under distinct names, and
less often in cases where the division was put solely with rendering of 3D
volumes in mind)

**Comment by sabas** [comment]
Another example https://www.openstreetmap.org/relation/6040462

**Comment by cwmke** [comment]
This comes up with universities and hospitals the most for me. I also believe the names should be displayed with building:part tags. If they have an amenity they already show but hospitals for example only have the one hospital tag and different chunks have different names.

An example building from my city is below. There is one large building complex with 2 hospitals and several sections that won't render such as the Center For Advanced Care and the Cancer Center.

![screenshot from 2019-01-16 10-13-02](https://user-images.githubusercontent.com/1923967/51262224-8eda8900-1977-11e9-98a6-2c6b4c611821.png)

**Comment by kocio-pl** [comment]
I believe in this case building:part name is not needed, all these parts are healthcare objects probably and should be tagged like that.

**Comment by cwmke** [comment]
Good point @kocio-pl although the Pavilion section still would not display a name in that instance. I believe it's more of a resting place and connector. Not really healthcare related.

**Comment by kocio-pl** [comment]
Maybe it is. I'd like to see some more examples where it's clear that:
- name is a proper tagging (instead of ref)
- building:part is a proper tagging (instead of building and instead of some POIs, like hospital clinic)

**Comment by cwmke** [comment]
I looked around and I've changed my mind. I can't think of or find any instance around me that really needs building:part name to render as they can normally be properly tagged with something that displays it. The only place it's really an issue is with the non hospital section previously mentioned and universities in my area as department= doesn't currently render. But that's a separate issue.

One question I have is that buildings with names and no additional tags display the name so why shouldn't building:part= with a name do the same? A name wouldn't be added unless it is a place with an identifiable name.

**Comment by dieterdreist** [comment]
building:part names are for building parts that have a distinct name, simple like this. Functions and users inside the buildings should go on their own objects and might have different names.

**Comment by kocio-pl** [comment]
Sure, but how much of them are there with proper name?

Out of 820 576 only 15 896 has a name tag and I wonder how many of them are really properly named as parts of the building and something else:

https://taginfo.openstreetmap.org/keys/building%3Apart#combinations

**Comment by Phidica** [comment]
I support rendering the names. I've found it's sometimes much more appropriate to put a name on a building:part when the whole building is operated by and named for one entity (say, a library) but some parts of it are older or specially built and have specific names that the entity uses in public communication. Making it a separate building and setting a tag like "operator" is potentially an option, but visually there is no indication of this tag either.

**Comment by cwmke** [comment]
I have another example where building:part with a name makes sense.  [Park Lafayette Towers](https://www.openstreetmap.org/way/404573624) is a single apartment building with 2 towers and a shorter space in between. The towers are named 'North Tower' and 'South Tower'. These names are displayed on the exterior of the building.

**Comment by polarbearing** [comment]
The hospital example above fulfils the OSM criteria for separate, connected buildings. I.e., if you tear down one of the clinic buildings, the rest would stand alone.

**Comment by dieterdreist** [comment]
sent from a phone

> On 31. Mar 2019, at 11:11, polarbearing <notifications@github.com> wrote:
> 
> The hospital example above fulfils the OSM criteria for separate, connected buildings. I.e., if you tear down one of the clinic buildings, the rest would stand alone.


where do you have this from? AFAIK it was never a criterion for building vs building:part in OpenStreetMap and apart from this, it doesn’t make sense.
You can always tear down a part of a building and have another one still standing. There are also clearly different buildings which share a wall (literally), e.g. some medieval buildings, and while you could not construct a building like this nowadays (in many jurisdictions), they do exist, and you could not tear one building completely down and have the other one remaining standing.

Cheers, Martin

**Comment by Adamant36** [comment]
> There are also clearly different buildings which share a wall (literally), e.g. some medieval buildings, and while you could not construct a building like this nowadays (in many jurisdictions), they do exist, and you could not tear one building completely down and have the other one remaining standing.

A lot of shopping centers in America are like that. They seem like one building, but the stores are actually in separate buildings that either share a wall or have an invisible to the outside world hallway between them. So one store can be destroyed and rebuilt if need be, without it affecting the other. They did that with a Sears in the mall near where I live recently.

**Comment by jeisenbe** [comment]
I'm not in favor of this idea. The tag building:part is often used for 3D modeling of the building, by showing what parts of the building have a different number of levels or different roof style. This often does not match with named "wings" or sections of a building. In addition, many named parts of large buildings are interior rooms, rather than readily identifiable "parts" of the building from a structural perspective. I don't think it would be reasonable to render the names of internal corridors and rooms in this 2D map style. Finally, many of the examples shown so far could have been mapped either as separate buildings (which can share walls, as seen in row houses / terraced housing and many old city centres) or as separate POIs.

**Comment by dieterdreist** [comment]
Am Di., 10. Sept. 2019 um 04:33 Uhr schrieb jeisenbe <
notifications@github.com>:

> I'm not in favor of this idea. The tag building:part is often used for 3D
> modeling of the building, by showing what parts of the building have a
> different number of levels or different roof style. This often does not
> match with named "wings" or sections of a building.
>

I don't see an issue here: if there is no name for the building:part that
applies to the OSM object then it shouldn't have a name tagged.



> In addition, many named parts of large buildings are interior rooms,
> rather than readily identifiable "parts" of the building from a structural
> perspective. I don't think it would be reasonable to render the names of
> internal corridors and rooms in this 2D map style.
>

depends on the zoom. You can make it depending on the size (or pixel size),
so that only things which matter at the given scale will have their name
render. A room can be an identifiable part from a structural perspective,
and it certainly is if you see "structure" not as load bearing thing but
regarding the division of space.

**Comment by jeisenbe** [comment]
"A room can be an identifiable part from a structural perspective ... if you see "structure" not as load bearing thing but regarding the division of space."

Should rooms be tagged as `building:part`? There is also a more specific tag `indoor=room` used over 55k times on ways and relations: https://wiki.openstreetmap.org/wiki/Tag:indoor%3Droom

If we render names of `building:part` but not names of `indoor=room` this may encourage mappers to use building:part inappropriately. 

Recall that the initial issue is that some mappers are (mis-)_"tagging building parts as buildings to get the names of the parts displayed in OSM-carto because names of building:part which ain't buildings are not rendered."_ - so it would not be good to create a new problem.

I'm not sure that even z20 is appropriate for rendering `indoor=room` features. At the equator a room needs to be 15 meters wide for a 100 pixel wide text label to fit at z20. 

(And we only currently render to z19 in the main deployment of this map style on Openstreetmap.org, where 100 pixels = 30 meters at the equator.)

**Comment by jeisenbe** [comment]
Currently 17,600 of 971,000 building:part features have a `name` tag: about 1.7%

**Comment by dieterdreist** [comment]
Am Mi., 11. Sept. 2019 um 13:28 Uhr schrieb jeisenbe <
notifications@github.com>:

> Should rooms be tagged as building:part? There is also a more specific
> tag indoor=room used over 55k times on ways and relations:
> https://wiki.openstreetmap.org/wiki/Tag:indoor%3Droom
>
>

generally the "building:part" tags are about "gross" building volumes,
while rooms are "net" building volumes (inner spaces), so the tag is not
suitable, I agree.



> If we render names of building:part but not names of indoor=room this may
> encourage mappers to use building:part inappropriately.
>

if we do not render building:part names some people will be encouraged to
map them as buildings. Rooms are typically smaller than building parts, and
more importantly, tend to overlap significantly (levels). For room labels
to make sense, we would have to render rooms in the first place. To render
rooms, we would have to produce horizontal sections of the building
(levels, ground plans). IMHO rooms are a different topic and we should not
sidetrack the discussion about building parts names to one about room
names.


> Recall that the initial issue is that some mappers are (mis-)*"tagging
> building parts as buildings to get the names of the parts displayed in
> OSM-carto because names of building:part which ain't buildings are not
> rendered."* - so it would not be good to create a new problem.
>

Rooms and building parts are too different to be susceptible to this
problem, IMHO.



> I'm not sure that even z20 is appropriate for rendering indoor=room
> features. At the equator a room needs to be 15 meters wide for a 100 pixel
> wide text label to fit at z20.
>


agreed

**Comment by jeisenbe** [comment]
> Rooms and building parts are too different to be susceptible to this problem

No tag is immune from tagging for the renderer. ;-)

In this case, the `description=` of building:part is _"To mark part of building, which has attributes, different from such ones at other parts"_, and the main wiki text says _"A way with the tag building:part=* describes a part of a building where some building attributes or the building function are different from the rest of the building."_

A "name=" is an attribute, and many rooms have special functions, so this could be seen as justification for mapping any named section of a building, including rooms, as `building:part=`. Perhaps the wiki page should be edited to clarify when indoor=room or indoor=corridor is appropriate instead.

**Comment by dieterdreist** [comment]
Am Mi., 11. Sept. 2019 um 15:01 Uhr schrieb jeisenbe <
notifications@github.com>:

> A "name=" is an attribute, and many rooms have special functions, so this
> could be seen as justification for mapping any named section of a building,
> including rooms, as building:part=. Perhaps the wiki page should be
> edited to clarify when indoor=room or indoor=corridor is appropriate
> instead.



I agree and have added something to the wiki

**Comment by jeisenbe** [comment]
Closing for reasons mentioned above (https://github.com/gravitystorm/openstreetmap-carto/issues/3188#issuecomment-529742627 and https://github.com/gravitystorm/openstreetmap-carto/issues/3188#issuecomment-530339025): we do not render the names of `indoor=room` features, and rendering `building:part` names without `indoor=room` names could lead to mistagging. 

Such features and building:part could be rendered together if z20 and perhaps z21 become routinely used in this style.
