### ISSUE TITLE
historic=castle z-index/opacity

### ISSUE THREAD

**Issue by eehpcm** [gravitystorm/openstreetmap-carto#3190]
A little while ago I changed a historic=castle from a node to an area.  It's a castle with about half of the curtain wall remaining.  I essentially connected what was left with out-of-band information as to where the missing bits used to be (which is what the wiki seems to imply I should do).

There is a problem where some visible features are inside the boundary or straddle the boundary.  Most notably, landuse=grass.  Most features (trees, benches, statues, etc) show above the shading of the castle area.  Grass, kitchen gardens and orchards do not, and this becomes apparent because they straddle where the curtain wall used to be (part inside the old bailiwick, part outside it).  In one place, the curtain wall was demolished so the owners could have a better view of the river, and created a grassed bank that straddled where the wall used to be.

So would it be possible to alter the z-index to put castle shading below grass/orchard/garden shading?  That would create a new problem because it would also require that the boundary be visible as a line (possibly dotted or chained).  Or change the opacity so where there is grass/orchard/garden inside the bailiwick its a grey/green mix?  As it stands I have to choose between using a node so certain features show up or using an area so I get the outline of the castle where sections of castle wall are missing.

[Cardigan Castle](https://www.openstreetmap.org/way/568794249) (yes, there's still a lot I have to fix up).

Is this feasible or is it a stupid request?  And if feasible, is it actually worth the effort involved given everything else on your to-do list?

**Comment by eehpcm** [comment]
> Could you explain it in more simple words with some images as a hint, probably?

Take a look at [Cardigan Castle](https://www.openstreetmap.org/way/568794249).  You can see some grass between the South East Tower and the Stables, bordered by the road called "Strand" (without the definite article one might expect).

Now look at the [actual extent of the grassed area](https://www.openstreetmap.org/way/558556565).  Most of the grass has vanished underneath castle.  It would be nice to be able to see the actual extent of both.

A similar thing happens with buildings such as Castle Green House and East Wing, because they're the same shade as historic=castle, but at least there are building outlines and labels to clarify matters.

Is that enough of a hint?  :)

**Comment by kocio-pl** [comment]
As far as I can tell, it's misguided tagging of a castle. The area of a castle does not necessary mean it has to be a building - and in this case it is not. I follow school example in such cases: school is the whole area, but building is only where the actual buildings (with walls, roofs etc) are located.

**Comment by kocio-pl** [comment]
I think ruins and demolished buildings are just a hard case to tag. 

Looking at the aerial background I thought that this was just a court inside the walls, but if this was a big building all over than I don't know how to tag it - how it looked like in the past or rather how does it look like today. 

I would probably choose current state, since history can be long and the castles can be rearranged many times in different times.

**Comment by SomeoneElseOSM** [comment]
I'm guessing that https://www.openstreetmap.org/way/568794249 probably shouldn't be "building=yes" here - https://map.atownsend.org.uk/maps/map/map.html#zoom=18&lat=52.08163&lon=-4.661052 is confused by that too.  When I looked at historic=castle usage a significant number weren't buildings (and weren't tagged as such).  See for exampe https://map.atownsend.org.uk/maps/map/map.html#zoom=17&lat=53.231089&lon=-1.29826 .

**Comment by eehpcm** [comment]
> I think ruins and demolished buildings are just a hard case to tag.

Indeed.

> Looking at the aerial background I thought that this was just a court inside the walls, but if this was a big building all over than I don't know how to tag it - how it looked like in the past or rather how does it look like today.

Well, it originally consisted of the Great Tower and a curtain wall (with its own towers) around it.  Then in modern times somebody built Castle Green House adjoining the Great Tower, and later added the East Wing and various other buildings inside what was the bailiwick.  Some original buildings, such as stables, back when the castle was used defensively were demolished or re-purposed (those buildings weren't themselves defensive but a necessary adjunct to living inside a castle).

>I would probably choose current state, since history can be long and the castles can be rearranged many times in different times.

I've tried to show the current state.  I've only mapped curtain walls that are still standing.  But I used historic=castle to map the extent of the original outer defensive wall, as I think the wiki implies I should (but I could be wrong about that).

However, back to my original point.  Assume a castle in perfect condition.  It has a continuous outer wall, and that is used as the boundary for defensive=castle.  There are no modern buildings inside to confuse the issue.  Part of the ground inside the castle wall is grass, and is mapped as such.  Nothing contentious here.  Except the grass doesn't show up, and that is all I was really asking for.  I can show most other things that happen to be within the castle wall, but I can't show the grass.  Which may matter if the castle is a tourist attraction, as this one is.

**Comment by eehpcm** [comment]
> I'm guessing that https://www.openstreetmap.org/way/568794249 probably shouldn't be "building=yes" 

You're right.  I'm not sure how that crept in.  I'll remove it and see what happens.

Then again, technically it is a building, since somebody built it.  But technically, it's also man_made.  And, technically, it's also natural (if a beaver lodge is natural then anything man makes is natural too).  But yes, as OSM understands it, it's not a building.  It will be interesting to see if removing it makes things better or worse.

**Comment by kocio-pl** [comment]
There's a never ending problem with priorities of landcover, buildings and other layers:

- https://wiki.openstreetmap.org/wiki/Standard_tile_layer#Rendering_order
- #688

**Comment by kocio-pl** [comment]
It looks better now and makes more sense - if you tag the walls alone, it means that the building is not there... So I'm closing it as a tagging problem.

**Comment by eehpcm** [comment]
> It looks better now and makes more sense

Not shown up for me yet, but I'll take your word for it.

Yep, not a tagging problem but a PEBKAC error.  Thanks to SomeoneElseOSM for spotting it.

**Comment by kocio-pl** [comment]
![screenshot-2018-4-23 linia cardigan castle 568794249 openstreetmap](https://user-images.githubusercontent.com/5439713/39142295-8541fb0a-472a-11e8-86c8-3893312265c7.png)

**Comment by eehpcm** [comment]
Yep, looks better.  Thanks for the screenshot.

Just one thing...

It doesn't show the outline of the castle any more.  Any chance of doing that somehow?  It would be kinda nice to have something like that.   Otherwise there are just some disconnected objects where once an entire castle was.  Again there's the discoverability/verifiability issue.  But a dotted line or something would be nice.  Or am I making another PEBCAK error?

**Comment by kocio-pl** [comment]
I don't think it makes sense, but if you do, just go to #3045.

**Comment by dieterdreist** [comment]
2018-04-23 18:47 GMT+02:00 eehpcm <notifications@github.com>:

> I'm guessing that https://www.openstreetmap.org/way/568794249 probably
> shouldn't be "building=yes"
>
> You're right. I'm not sure how that crept in. I'll remove it and see what
> happens.
>
> Then again, technically it is a building, since somebody built it.
>


no, technically this is not a building, it is a structure, composed of
several buildings and an enclosing wall.
