### ISSUE TITLE
Office + shop/amenity makes an icon very small

### ISSUE THREAD

**Issue by Zverik** [gravitystorm/openstreetmap-carto#3195]
Office + shop/amenity makes an icon very small

See here: https://www.openstreetmap.org/node/2979269234#map=19/55.82968/37.30825

You can find a similar shop without an `office` tag nearby, its icon is normal.

**Comment by kocio-pl** [comment]
Could you test if #3194 fixes this problem?

**Comment by kocio-pl** [comment]
You can always export relatively small areas directly from OSM.org website - it's a useful trick:

https://www.openstreetmap.org/export

**Comment by andrzej-r** [comment]
Didn't work very well. How do I import an .osm file into the database? Previously I always used .pbf files.

**Comment by kocio-pl** [comment]
Exactly the same as PBF, osm2pgsql can read both formats.

**Comment by andrzej-r** [comment]
The fix seems to work fine. Zoom 19-17:
![error2_z19](https://user-images.githubusercontent.com/587630/39376972-6e03e628-4a4b-11e8-98b9-8d45cc24f6cb.png)
![error2_z18](https://user-images.githubusercontent.com/587630/39376975-6fc06036-4a4b-11e8-96cd-ad3fd7195469.png)
![error2_z17](https://user-images.githubusercontent.com/587630/39376977-725065d0-4a4b-11e8-987e-46c148813882.png)

**Comment by Zverik** [comment]
Thank you @andrzej-r for testing this!
