### ISSUE TITLE
Cartography of address labels : too much at level 17/18?

### ISSUE THREAD

**Issue by brycenesbitt** [gravitystorm/openstreetmap-carto#320]
Have a look at:
http://www.openstreetmap.org/#map=17/37.87853/-122.27021&layers=N

The address labels are very prominent.  Could these be dialed down a bit, perhaps appearing in lighter font, or better yet not at all at zoom 16/17/18?  
The address labels are super important for searching of course, and even when finding a specific place, but at these zoom levels perhaps they demand more attention than they are worth.

**Comment by math1985** [comment]
I'm not sure if anything more than #1209 can be done about this.

**Comment by pnorman** [comment]
> I'm not sure if anything more than #1209 can be done about this.

yes - a better `min-distance`

**Comment by math1985** [comment]
> yes - a better min-distance

I'm not sure if a smaller min-distance is really necessary. The map looks really crowded with addresses, but I don't really see two addresses that are individually to close together. Do you have an example where this would help?

**Comment by pnorman** [comment]
![image](https://cloud.githubusercontent.com/assets/1190866/5894199/58f162f0-a4b4-11e4-85cb-fce06d367f3d.png)
![image](https://cloud.githubusercontent.com/assets/1190866/5894210/8e22a57e-a4b4-11e4-85ec-ed8743920209.png)
Both from http://www.openstreetmap.org/#map=17/49.14125/-122.84453 at different zooms.

Vertically it feels squeezed too
![image](https://cloud.githubusercontent.com/assets/1190866/5894225/e5515dc2-a4b4-11e4-9fa3-9e1b275cf925.png)
