### ISSUE TITLE
Syriac font rendering

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#3206]
The Syriac script has various variants:
- Eastern Syriac
- Western Syriac
- Estrangela Syriac

As far as I understand, _Estrangela Syriac_ is rather of historic interest. And for today’s usage, we have more native speaker of languages written in _Eastern Syriac_ than for _Western Syriac_ (but I may be wrong here).

Technically, we have the same problem as with Han unification (see #2208 for details): The script variant cannot be determined from the Unicode text. Our current code for Syriac is:
```
                "Noto Sans Syriac Eastern Regular",
                "Noto Sans Syriac Estrangela Regular",
                "Noto Sans Syriac Western Regular",
```
All these three fonts cover exactly the same set of Unicode Scalar Values (≈ code points).
The code defaults to _Eastern Syriac_, which I think is reasonable. If the font for _Eastern_ is installed, the others are never used. But I don’t like the code formatting so much. For CJK, we default to Japanese and do not have a fallback. Shouldn’t we eliminate _Estrangela_ and _Western_ here also?

cc @pnorman This is sort of a spin-off from #3184

**Comment by matthijsmelissen** [comment]
Agree with removing Estrangela and Western based on your description.
