### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#3209]
Perhaps we should add a config file for the line endings and stuff

http://editorconfig.org/

Ref #3200
Ref #3197

**Comment by kocio-pl** [comment]
This is not the solution, I think. Actually Atom trims trailing spaces by default (one can switch it off) and that's why it makes it harder to collaborate - it does it in the background, hence the next commit will contain new code mixed with removing spaces.

**Comment by HolgerJeromin** [comment]
No. That is exactly the point.
It (editors which has support for that file) wont do that if there is a .editorconfig file in the project.

**Comment by kocio-pl** [comment]
OK, now I see! Could you prepare the PR?

**Comment by matthijsmelissen** [comment]
Agree this looks like a good idea. @HolgerJeromin do you know how to prepare such a file?
