### ISSUE TITLE
Add icon for amenity=casino

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3210]
Quite popular feature (4,8k uses) without any rendering at the moment.
https://wiki.openstreetmap.org/wiki/Tag:amenity=casino

Potential icon could be used also for leisure=adult_gaming_centre (2,1k uses).
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dadult_gaming_centre

Icon proposals:
* ![1](https://user-images.githubusercontent.com/20193716/39085944-7c98280c-4582-11e8-8bb7-f4b9082c757d.png) (@lakedistrictOSM)
* ![amenity casino](https://user-images.githubusercontent.com/25656654/39531018-839d883a-4e2a-11e8-859a-e236e51d1402.png) (@Tomasz-W)

**Comment by meased** [comment]
I have been wanting an icon for this for a while. Here are my icon suggestions:

- ![dice](https://user-images.githubusercontent.com/14190496/39598730-1919f644-4f09-11e8-94d9-840b9acc79a1.png)
- ![dice_pair](https://user-images.githubusercontent.com/14190496/39598736-1c069e3e-4f09-11e8-9538-68e578cf7201.png)

**Comment by lakedistrictOSM** [comment]
Nice designs @meased! 

Related to #3186 where there's some more ideas being discussed.

**Comment by Tomasz-W** [comment]
I'm not sure if 'dice-only' design will be readable enough out of context. I mean that we know it's a casino icon because of issue title, but for map users it could be just a square with dots. What do you think?

**Comment by meased** [comment]
The way I see it our options are:

1. Dice/pair of dice
    - I think 2 or 3 dots would be best
        - 1 and 4 are too generic
        - 5 and 6 are too crowded
    - A single dice (die?) would look less crowded, but double dice may be more recognizable (look like they are being thrown)
2. Card suite
    - Hearts/diamonds are out
    - Clubs may work, but look similar to a tree
    - Spades may be the best option here?
3. Dice/card suite combo
    - Good in theory, but at less than 14x14, I think card suites will look terrible

I don't see how a ticket relates to a casino at all.

Slight tweak on the above icon (non-45 angle on the back die, bigger dots, rounded corners, two dots on front die to reduce crowding):
![dice_double](https://user-images.githubusercontent.com/14190496/39605248-2f6dd1de-4f1f-11e8-8cf5-a3e925659e4a.png)

**Comment by lakedistrictOSM** [comment]
I think that a single symbol would be clearest. A roulette wheel, four leaf clover or casino chip (coin) might work too.

> I don't see how a ticket relates to a casino at all.

That was intended for `shop=bookmaker`

**Comment by Tomasz-W** [comment]
Proposed icons

1) ![1](https://user-images.githubusercontent.com/20193716/39085944-7c98280c-4582-11e8-8bb7-f4b9082c757d.png) (@lakedistrictOSM )
2) ![2](https://user-images.githubusercontent.com/25656654/39531018-839d883a-4e2a-11e8-859a-e236e51d1402.png) (@Tomasz-W)
3) ![3](https://user-images.githubusercontent.com/14190496/39598730-1919f644-4f09-11e8-94d9-840b9acc79a1.png) (@meased )
4) ![4](https://user-images.githubusercontent.com/14190496/39598736-1c069e3e-4f09-11e8-9538-68e578cf7201.png) (@meased )

Can we choose which one do we prefer?

**Comment by matthijsmelissen** [comment]
@ccamara No, we take no ethical stance and display the world as it is.

**Comment by ccamara** [comment]
> No, we take no ethical stance and display the world as it is.

By your words I have to assume that the only reasons for not displaying `amenity=brothel` is because nobody has created an icon for that. :cry: It's a pity, then.

**Comment by IVAN-RSM** [comment]
I think the ccamara's comment is correct, OSM also performs a social function, since its map also has a social responsibility.

**Comment by kocio-pl** [comment]
I was trying to render `shop=erotic` once, but that didn't catch:

https://github.com/gravitystorm/openstreetmap-carto/pull/1602

**Comment by dieterdreist** [comment]
sent from a phone

> On 29. Jun 2018, at 13:28, Matthijs Melissen <notifications@github.com> wrote:
> 
> @ccamara No, we take no ethical stance and display the world as it is.


I’d rather say we do not take enough issue with casinos to omit them. There are other tags that are not rendered, although numbers could justify it, e.g. amenity=brothel
shop=erotic etc.
There is also a policy not to show some safe spaces to protect the inhabitants/users.

**Comment by lakedistrictOSM** [comment]
2 or 4 look the best.

Re the social/ethical comments - we also show pubs, bars, alcohol shops, tobacconists and other places which could be deemed "unhealthy" but like gambling, they can be safe with responsibility and moderation. There's no need to hide them.

**Comment by dieterdreist** [comment]
for brothels there are not even tags to state for which gender they are, i.e. the information is useless for women because most brothels are for men

**Comment by yopaseopor** [comment]
So...

- >The reason it was rejected was lack of instances in the database, not that we don’t want to render erotic shops in general. 

(We don't show brothels because there aren't many. Tag info says more than 2000. Casinos are about 4000).

-also because

- > for brothels there are not even tags to state for which gender they are, i.e. the information is useless for women because most brothels are for men

but...

- > we take no ethical stance and display the world as it is.

WTF?

Girls, What do you think about that?

**Comment by matkoniecz** [comment]
> for brothels there are not even tags to state for which gender they are, i.e. the information is useless for women because most brothels are for men

Please, can we avoid offtopic here? Discussing state of brothel tagging is certainly an offtopic in discussion about adding a casino icon.

**Comment by yopaseopor** [comment]
> Please, can we avoid offtopic here? Discussing state of brothel tagging is certainly an offtopic in discussion about adding a casino icon.

For me it is the same thing: some icons are rendered and some others no. Why? We are talking about OSMCarto, the door to Openstreetmap for the big public.  If we have to show the reality show the reality to all people. 
We are talking about amenities with "social impact". Casino is one of them.

**Comment by matkoniecz** [comment]
> For me it is the same thing: some icons are rendered and some others no. Why?

1) #1630 Guidelines for adding new features may be of interest for you (it ended without clear conclusion but it provides some insights)

2) Without someone making a pull request icon will be certainly not rendered.

**Comment by Tomasz-W** [comment]
So proposal No. 2 (clover + dice) has one more vote than No. 4 (two dices), but I think we can all agree to @kocio-pl argument, that would be good to make casino and bookmaker icons different to each other, and use clover only in bookmaker icon.
I left a final decision to @kocio-pl

**Comment by Tomasz-W** [comment]
@meased Can you upload Gist link with clean SVG file? Maybe you are interested in making a PR?

**Comment by meased** [comment]
I'll do a PR, just need a little time...
