### ISSUE TITLE
Electric poles are rendered but telephone poles are not

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3215]
Electric poles are rendered but telephone poles are not.
It is not fair.
https://wiki.openstreetmap.org/wiki/Talk:WikiProject_Telecoms#Telephone_poles_rendered.3F

**Comment by kocio-pl** [comment]
Currently there are only 64 of them:

https://taginfo.openstreetmap.org/tags/telecom=pole

I don't think they should be rendered until we're pretty sure that it's the way the community accepts as standard for tagging them.

**Comment by jidanni** [comment]
I did not ask you to render telecom=pole.
I think you should follow the [recommended tag](https://wiki.openstreetmap.org/wiki/WikiProject_Telecoms#Telephone_Poles).

**Comment by kocio-pl** [comment]
While `communication=pole` is much better in that respect (2 587 uses), it lacks a wiki page, so please start with completing it.

**Comment by jidanni** [comment]
OK I mentioned your comment [there](https://wiki.openstreetmap.org/wiki/Talk:WikiProject_Telecoms#Telephone_poles_rendered.3F).

**Comment by sommerluk** [comment]
Rendering telephone pole without rendering the telephone line is cartographically ugly. communication=line is below 2000 usages. Furthermore, rendering communication=line would require a stable way to distinguish overland communication lines (on poles) from underground or underwater communication lines, because the latter we won’t render in a general map.

> Electric poles are rendered but telephone poles are not.
> It is not fair.

I do not follow this argument. Electric poles are usually bigger than communication poles, which makes them better landmarks, which might be a reason to treat them differently.

Even if usage numbers would be higher for this feature and tagging style would be stable, we would have to discuss if we want this in a general map at all (and how to render it differently from power lines). Maybe only at the highest zoom level…

We will see if the situation improves in the future. In the mean time I tent to close this issue.

**Comment by jidanni** [comment]
In rural areas being able to locate and distinguish one is at electric pole #123 would be just as important a lifesaver as distinguishing one is at telephone pole #123. Also if one rams ones car into one, the effect is the same, electric pole or telephone pole...

**Comment by jidanni** [comment]
A city person wouldn't understand. But in rural areas regular spaced numbered utility poles beat infrequent addresses and mileposts, simply a pure gold landmark reference, be it for reporting emergencies or other uses.

**Comment by gustavecha** [comment]
I second the need of rendering poles.
Nevertheless, there is work to be done on telecom=* key first
See proposals like https://wiki.openstreetmap.org/wiki/Proposed_features/Telecom_local_loop intended to make telecom=* more useful and meaningful than communication=*

**Comment by dieterdreist** [comment]
sent from a phone

> On 5. May 2018, at 08:28, Lukas Sommer <notifications@github.com> wrote:
> 
> Furthermore, rendering communication=line would require a stable way to distinguish overland communication lines (on poles) from underground or underwater communication lines,


fortunately the tagging is already clear, it only has to be applied (location=*)

**Comment by matkoniecz** [comment]
Is there any widely used, stable tagging scheme for that feature? Without that it is not viable to even consider rendering.

**Comment by matkoniecz** [comment]
Closing for now without prejudice to a a new issue once clear tagging scheme is established and widely used.

**Comment by jidanni** [comment]
> in rural areas regular spaced numbered utility poles beat infrequent addresses and mileposts, simply a pure gold landmark reference, be it for reporting emergencies or other uses.

Real life example: Often in the middle of the night I have to tell the
police "the (hunters') gunfire is coming from the (anonymous) road at [electric pole 61](https://www.openstreetmap.org/node/4778301537).
Just wait at that junction and eventually they will have to come
out because it is a dead end road."

I am able to tell them electric pole 61 because I can see the electric
pole rendered on the map, and then I can use Query Feature on the OSM
website right panel to get the name of the pole.

However, for
-telephone poles #3215
-street lamps #3277
-milestones #2577

even though they also have labels on them very useful for coordinating
emergency responses, alas as they are hidden on the map, the user cannot
see where to Query Feature. So even though looking across the valley he
can see where the criminals / chemical spill / etc. is, if he wishes to
be able to tell the police what pole number that is at, he has no other
choice to go over there in person to have a look. Putting himself in the
line of fire / danger.

Sure, for city slickers, bars and snack shops are all the craze, not to be cluttered by ho-hum utility poles.  But when you are talking about rural areas, these boring items are the only "game in the book" (only things on the ground), and (being able to refer to them) could be lifesavers.

**Comment by matkoniecz** [comment]
> Closing for now without prejudice to a a new issue once clear tagging scheme is established and widely used.
