### ISSUE TITLE
Please do not put highway numbers exactly on overpasses or junctions

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3219]
Why does the program often insist on putting highway numbers exactly on top of
overpasses?
![1](https://user-images.githubusercontent.com/1230959/39678846-f7e9f31e-51c6-11e8-9cd8-a33982357690.jpg)

Please have it notice that this is an overpass, and put it very clearly to
the right or left etc.

All it is doing is increasing the confusion as to which road is which.

Sure, we should know that the road on top is the road it is talking
about. But OK we are not that smart. So please still move them to the
side. Yes we should zoom in and out to get a different view. Problem
solved. But then again we are not that smart.
https://www.openstreetmap.org/#map=15/24.8489/121.2010

**Comment by sommerluk** [comment]
As far as I know, this is technically not possible with our current rendering software stack.

**Comment by kocio-pl** [comment]
Furthermore I have no problem sorting the things out, because shield colors are different.

**Comment by jidanni** [comment]
What if one day, the shield colors are the same?

I don't know of any other paper, or on-line map that ever has done this. Nor any cartographer.

I don't think that closing the bug will help get this solved.

**Comment by kocio-pl** [comment]
The best thing to help is to write the code that could solve it while not introducing some other problems. If you know how to do it, just please try, because we don't.

"What if" is not the problem to solve. If someone will make the shield colors uniform, she will have to deal with this issue - but only then.

**Comment by matthijsmelissen** [comment]
> I don't know of any other paper, or on-line map that ever has done this. Nor any cartographer.

Google and Bing also render shields on top of overpasses:

<img width="161" alt="screen shot 2018-05-07 at 14 07 45" src="https://user-images.githubusercontent.com/5251909/39701076-12faa35e-5200-11e8-860d-18e59f7e3476.png">
<img width="90" alt="screen shot 2018-05-07 at 14 04 54" src="https://user-images.githubusercontent.com/5251909/39701077-131db8ee-5200-11e8-9d92-2c0f39d8d4da.png">

> If you know how to do it, just please try, because we don't.

Exactly this. If you have an idea for a solution, feel free to.

**Comment by kocio-pl** [comment]
> I don't think that closing the bug will help get this solved.

I don't think that leaving bug open will help anything too. Bug tracker is just a tool to manage problems, open status is not a magic wand.

There are no guarantees to solve anything "eventually", there are rather big chances that it will just clutter the space. I am digging in the old tickets from time to time, so having such issues open really makes it harder to discover problems that can be solved.

**Comment by jidanni** [comment]
Also even if the only problem is shield colors, one day Provincial Highway 7 will cross Provincial Highway 8. If you can manage not putting a 7 or an 8 smack in the middle of a flat intersection, then the same should be possible in three dimensions. Or just as a rule don't put them smack in the middle of any bridge.

**Comment by kocio-pl** [comment]
Still we see no solution and adding "what ifs" is not helping anything.

Do you have any code to solve it or even a hint how to code it?

**Comment by jidanni** [comment]
Basic solution:

while(haven't reached end of road yet){
   x+=500 meters;
   if(on a bridge){do nothing}else{place marker}.
}

Or use

   if(on a short bridge){...}

**Comment by kocio-pl** [comment]
We use SQL + CartoCSS here. You need to think in terms of selecting database values that mean "short bridge" for a start. Next thing is to look how the shields are placed in https://github.com/gravitystorm/openstreetmap-carto/blob/master/roads.mss.

**Comment by jidanni** [comment]
SELECT bridge WHERE (SELECT bridge.length > 100 meters) etc.
Also all this thinking needs to be done in meters before you hit the
roads.mss style files.

**Comment by kocio-pl** [comment]
In case of this style, especially roads, you have to debug, not simply write code:
1. look at the road.mss code to find which variables are used for placing shields
2. find the proper layer and code for selecting these data
3. modify it
4. test if this change didn't introduce any other problems

It's not given that you will succeed, but this is a way to go.

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. May 2018, at 14:41, kocio-pl <notifications@github.com> wrote:
> 
> Still we see no solution and adding "what ifs" is not helping anything.


first render invisible shields on intersections, then render the actual shields.

**Comment by jidanni** [comment]
I was thinking, I have never seen a marker rendered underneath a  bridge or even partly underneath a bridge.  Therefore perhaps add a pseudo bridge on top of a bridge then run the marker rendering algorithm and then remove the pseudo bridge.  I will look at those files later.

**Comment by kocio-pl** [comment]
Great. If you want to understand overall design of this style and test it a bit, it's good to start with these links:

- https://wiki.openstreetmap.org/wiki/Standard_tile_layer
- https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by jidanni** [comment]
I am sorry. I must maintain my role as just the bug reporter. All I can respectfully leave you with is a link,
https://www.google.com/search?q=common+cartographic+mistakes .

**Comment by matkoniecz** [comment]
Unfortunately I also expect that given technical limitations of this style it is unfixable. It would be great to see a PR fixing this (assuming that it is not introducing other worse cartographic or significant performance issues).

But unfortunately I would not expect this to be possible in general.

One thing that may help is #951 that would solve also other shield-related issues. Stopgap solutions lke not rendering shields in bridges may or may not help.

**Comment by jidanni** [comment]
![X0](https://user-images.githubusercontent.com/1230959/62425704-bb38d580-b70e-11e9-8c89-90baa9efbe7f.jpg)

Here https://www.openstreetmap.org/#map=15/41.7697/-86.7312
to make it worse, it seems to be part of a single letter bigger road
system ("I", "M") when it is in fact on par with {"IL" "SR" "IN"} but
with just one letter. A problem that would go away when #508 is completed.)

Anyway if one is going to place a number in an ambiguous place, make
sure it is the bigger item's number, else it will make it seem the
bigger road must be called the smaller's number. (When making a map we
can ignore creeks, tiny road underpasses when placing a number, so the
reader will assume this is also the case.)
