### ISSUE TITLE
Admin names disappear upon zooming

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3222]
See those purple words along the coast?
https://www.openstreetmap.org/#map=16/24.0661/121.6170
Let's zoom in to see what they say.
But upon zooming, they disappear.

**Comment by kocio-pl** [comment]
These are names of admin areas. Zooming will not help because a label size is fixed:

https://www.openstreetmap.org/#map=19/24.06911/121.61590

**Comment by jidanni** [comment]
OK but please give a more consistent user experience.
Gone at 15.
There at 16
Gone at 17.
Gone at 18.
There at 19.

**Comment by kocio-pl** [comment]
Labels on lines are placed more freely than on nodes or areas. I think we can control only the spacing.

**Comment by matkoniecz** [comment]
I think that it is nearly impossible to ensure that names on admin lines will stay in the same place on zooming in.

It is also not terrible as font-size stays the same.

**Comment by matkoniecz** [comment]
I think I will close it as unfixable, though PR are welcomed.
