### ISSUE TITLE
Gates are too prominent

### ISSUE THREAD

**Issue by bitnapper** [gravitystorm/openstreetmap-carto#323]
Gates in fences are often much to present on the map. In my region I mapped several fences with smaller gates in it and they are very annoying on smaller zoom levels. I thing it would be better not to render them in zoom-levels lower than 18.
Same with information boards. I've mapped plenty of them and I believe all those small info-board belong into the osm database but rendering them on zoom-level lower than 18 seems also to much.

For example see this area: http://www.openstreetmap.org/#map=16/51.7123/10.5129

**Comment by kocio-pl** [comment]
Maybe we should render gates much later when tagged on some types of way (like private access and service roads)?
