### ISSUE TITLE
Does not render tiles on history mode in mobile

### ISSUE THREAD

**Issue by smaprs** [gravitystorm/openstreetmap-carto#3237]
### Expected behavior  
Render standard OSM tiles normally on mobile (cellular android) on history mode.    
  
### Actual behavior  
Renders only some standard OSM tiles, but blank tiles for the rest, on mobile, on history mode:  
like in openstreetmap.org/history#map...  
They got truncated at half screen more or less.  
Also it shows not well the changeset frames in the area, it shows just as a thiny trace, not as an area.  
So can't chose a changeset to verify.  
It happens only on mobile and on history mode.  
When disabled history mode, rendering returns to normal.  
Some other fellow mappers have reported same problem.
  
### Links and screenshots illustrating the problem  
![photo_2018-05-15_08-44-02](https://user-images.githubusercontent.com/29050750/40054830-88cb0386-581c-11e8-913c-308285352e0a.jpg)

**Comment by matthijsmelissen** [comment]
This is the repository for tile rendering, while the issue you report is an issue with the website. Could you report this at https://github.com/openstreetmap/openstreetmap-website/issues instead?

Good issue by the way, I am also running into it.

**Comment by kocio-pl** [comment]
I will close this issue, since it really belongs to the deployment team, not the style itself (hence "invalid", but only in this context).
