### ISSUE TITLE
Divider removed at zoom level 17, but names only cleaned up at 16

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3239]
Starting with zoom level 18,

![df2](https://user-images.githubusercontent.com/1230959/40153927-973fcc50-59be-11e8-91a6-6d0fb55af53b.jpg)

You remove the divider at 17,

![df1](https://user-images.githubusercontent.com/1230959/40153928-97743904-59be-11e8-92b0-786db786327b.jpg)

But finally get around to cleaning up the doubled name still left there only at zoom 16,

![df3](https://user-images.githubusercontent.com/1230959/40153926-970ba24a-59be-11e8-8f28-83eb7c0b41cc.jpg)

[I hope](https://www.openstreetmap.org/#map=16/24.1337/120.6583)...

**Comment by pnorman** [comment]
We don't render a divider - at all the zooms, two lines are rendered, both with casings. When they get close enough, the casings are hidden behind the other road.

For the labels, it's another case of multiple nearby linestrings with similar names like in #497 and related issues.
