### ISSUE TITLE
61 19: tighten upside down toggle tolerances in Transport layer

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3240]
Maybe there could be some way to avoid such nearby swings...
![df4](https://user-images.githubusercontent.com/1230959/40154282-38d7beb4-59c0-11e8-99b8-a66d792415fc.jpg)
https://www.openstreetmap.org/#map=17/24.16785/120.70487&layers=T
@gravitystorm I don't know if this is the right place to report this.

**Comment by pnorman** [comment]
This is the issue tracker for OpenStreetMap Carto, not the transport layer, or any other layer on osm.org.

**Comment by jidanni** [comment]
@pnorman what is the discovery path, from OSM.ORG, to find out where to file a Transport Layer bug?

The user starts in the lower right corner,  "Tiles courtesy of ..."

Then what is the complete path?

One cannot blame users.

**Comment by pnorman** [comment]
> @pnorman what is the discovery path, from OSM.ORG, to find out where to file a Transport Layer bug?
> 
> The user starts in the lower right corner, "Tiles courtesy of ..."
> 
> Then what is the complete path?
> 
> One cannot blame users.

I'm not blaming you, I'm just informing you that this isn't the right place to report an issue with map styles other than OpenStreetMap Carto. For Transport Layer, you need to contact [Thunderforest](https://www.thunderforest.com/).

**Comment by jidanni** [comment]
OK I will send
```
To: support@thunderforest.com
Subject: No clear path on how to report Transport layer rendering bugs
```
