### ISSUE TITLE
Inner island relation doesnt render properly (water)

### ISSUE THREAD

**Issue by james2432** [gravitystorm/openstreetmap-carto#3243]
### Expected behavior
Cut out the polygon in the water polygon
### Actual behavior
Renders water as if relation wasn't there
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/relation/8316862#map=13/49.4411/-94.1010
Is the big island relation(over 2000 nodes needs a multi-polygon for place=island)
![image](https://user-images.githubusercontent.com/498547/40361550-b65167c0-5d97-11e8-9027-d68b3ae51eb8.png)

Which is set to inner in:
(warning big and may lag browser):
https://www.openstreetmap.org/relation/1414848

**Comment by imagico** [comment]
You have a relation (https://www.openstreetmap.org/relation/8316862) as member of a multipolygon (https://www.openstreetmap.org/relation/1414848) which is universally not supported in OSM.  You need to add the outer member ways of the island relation as inner members of the lake relation.

**Comment by james2432** [comment]
Thanks, fixed.
