### ISSUE TITLE
Why is area-barriers rendering so different from line-barriers rendering?

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#3250]
Our current `project.mml` has very different SQL queries for the layers with id “area-barriers” and “line-barriers”:

| area-barriers | line-barriers|
| ------------- |-------------|
| Has not `historic=citywalls`      | Has `historic=citywalls`  |
| Has everything with a `barrier` key      | Has only elements with a `barrier` key  who’s value is whitelisted | 

Therefore, closed ways with barrier=block (which is not in our whitelist) without further tags are not rendered like https://www.openstreetmap.org/way/350624000#map=19/43.63777/10.42239 shows. But if combined with another tag that is recognized as are, like landuse=grass, the barrier is rendered like https://www.openstreetmap.org/way/337388805#map=19/51.22629/6.65681 shows. I think that’s not consistent…

**Comment by dieterdreist** [comment]
sent from a phone

> On 28. May 2018, at 20:50, Lukas Sommer <notifications@github.com> wrote:
> 
> Our current project.mml has very different SQL queries for the layers with id “area-barriers” and “line-barriers”:
> 
> area-barriers	line-barriers
> Has not historic=citywalls	Has historic=citywalls
> Has everything with a barrier key	Has only elements with a barrier key who’s value is whitelisted


just in case it is not clear to everyone, there is also another tag for citywalls, barrier=city_wall

**Comment by jeisenbe** [comment]
Closed by PR #3745
