### ISSUE TITLE
Spring icon invisible under waterway=river

### ISSUE THREAD

**Issue by polarbearing** [gravitystorm/openstreetmap-carto#3253]
The spring icon was recently refurbished as a blue ring with a white halo #3189.

Unfortunately this was not tested when surrounded with a body of water, which is a common case for a spring. Example: [Big Spring Missouri](https://www.openstreetmap.org/#map=19/36.95184/-90.99300),  mapped as a node in a body of water. The old 'S' icon was visible, see example in [comment](3189#issuecomment-390004949). The new one is not:
![204155](https://user-images.githubusercontent.com/8266355/40260580-b57bbe2a-5afb-11e8-8032-1aad2a4a5e7c.png)

The ring is defined slightly darker than water colour and has a halo, so it is not clear to me why it is completely invisible. I had done some analysis so far (from #3189):

> The SVG is constructed atypically compared to other icons. It seems to have no artboard size, thus git shows the icon in a large transparent square, opening with Illustrator presents it on an A4 sheet, partially hanging over the border.
> It has 3 grouped paths being concentric rings. One is the blue ring (# 7abcec), the others are white (# ffffff). One of the white rings sits behind the blue and is thicker, thus constructs the 'halo'. The function of the third ring is unclear since it is thinner and behind the blue.
> The SVG contains some 'transform' operations which apparently just shift the rings onto each other and could be avoided if they were drawn in the right place already.
> 
> All new icons I have analysed so far use fill while the stroke is empty. This SVG is the opposite.
> 
> Typically we have the icon black and define the colour in carto.
> 
> The ring (# 7abcec) is darker than water (@water-color defined as # aad3df)
> 
> IIRC, the order of the 'id:' elements in the 'Layer:' section in the project.mml defines the painting order? If so, 'water-areas' are painted earlier than 'springs' which are earlier than 'water-lines'.
> 
> This explains why a river line is painted over the ring, but I don't understand why the white rings disappear over a water area?
> 
> Finally I'd have the style for the spring rather in the water.mss with the natural things, while water-features.mss mostly has the man-made barrieres etc.

**Comment by polarbearing** [comment]
I haven't understood the reason yet. The icon is supposedly painted above the water layer, so I don't understand why both the darker blue and the white halo remain invisible. Or my analysis is wrong.

**Comment by polarbearing** [comment]
Things were getting more mysterious. There are examples, where the icon is rendered when surrounded (or on the border of) natural=water, and some where not. 

The reason however is simple: the icon is covered by the waterway=river line, which is typical for larger springs. When attached to a stream on the other hand, the icon is wider than the stream line. 
Parts of the icon appear from z16 or lower when the river line becomes thinner. 

Shown:
https://www.openstreetmap.org/node/1678238492 (not connected to a way)
https://www.openstreetmap.org/node/2006105431 (not connected to a way)
https://www.openstreetmap.org/node/1889250060 (on the boundary of natural=water)
https://www.openstreetmap.org/node/5228692718 (attached to a stream)

These examples reveal another oddity: within a lake, the spring icon _appears to have a blue middle dot_. This however is the blue from the lake looking through the transparent centre of the icon. 

Not shown:
https://www.openstreetmap.org/node/1563919839 (attached to a river)
https://www.openstreetmap.org/node/3141264012 (attached to a river)
https://www.openstreetmap.org/node/5442671644 (attached to a river)
https://www.openstreetmap.org/node/5591150537 (attached to a river)
https://www.openstreetmap.org/node/3195263763 (attached to a river)
https://www.openstreetmap.org/node/256435736 (attached to a river)

Just on a river, no water body around:
https://www.openstreetmap.org/node/4971116279
https://www.openstreetmap.org/node/947900034

Queries: 
[spring within natural=water](http://overpass-turbo.eu/s/zcy) about 300
[within waterway=riverbank](http://overpass-turbo.eu/s/zcE) 64
[spring on river](http://overpass-turbo.eu/s/zcG) works only on bbox

So, to conclude, the easiest solution would be to **give up the rendering under waterways** and move the icon layer above them...

**Comment by Penegal** [comment]
> So, to conclude, the easiest solution would be to give up the rendering under waterways and move the icon layer above them...

Beware that the spring layer was added below the waterways on purpose, to make the last interrupt the spring outline and suggest that the water outputs from the spring. What you are describing here seems merely a size problem between the river way width and the spring icon size. Typically, springs output a stream and not directly a river, and that shows no such problem AFAIK, so changing the fundamental design of the icon for this issue, which _seems_ a corner case to me, sounds overkill.

Please note that I took part in the new spring rendering, so I cannot affirm that this answer is objective enough.

**Comment by Penegal** [comment]
_Corner case_ was not the right term here; I meant that the case of a river outgoing from a spring is a reduced subset of all springs, and, therefore, should not be the sole reason to trash the new design, which works for a vast majority of cases.

**Comment by polarbearing** [comment]
> Typically, springs output a stream and not directly a river

Small springs output a stream, big springs output a river. 13 cubic meters per second from Big Spring in Missouri fail the OSM definition of jumping over a stream. Something that works on the majority of small cases but fails on the prominent ones is a bug for me. 

During my search above I have found plenty cases where the spring is not connected to a waterway at all, so to expect that the waterway is part of the icon message is inconsistent. I know it was intentional, but as it leads to inconsistency, I suggest to drop it. 

I'd also like to close the transparent middle of the icon as it leads to another inconsistency. Filling with blue creates a nice circular 'wave ripple' effect, you can study that on springs in water bodies that are not covered by a river.

**Comment by Penegal** [comment]
> I'd also like to close the transparent middle of the icon as it leads to another inconsistency. Filling with blue creates a nice circular 'wave ripple' effect, you can study that on springs in water bodies that are not covered by a river.

This design was rejected because of risk of confusion with other water features, which could ultimately lead to mistagging.

**Comment by kocio-pl** [comment]
I think this ticket could be closed, since implementing #3461 would resolve also this problem:

![_mimirc](https://user-images.githubusercontent.com/5439713/47247539-9fc14000-d404-11e8-922f-a0ec1bf461d0.png)
![epsvrlfa](https://user-images.githubusercontent.com/5439713/47247538-9e901300-d404-11e8-915e-b166bd510bd2.png)

**Comment by polarbearing** [comment]
Well, but close it at the time the other one _is_ implemented, not because it _will be_ implemented.

**Comment by jeisenbe** [comment]
Fixed by #3738
