### ISSUE TITLE
Label and icon placement on areas sometimes in one of the corners instead of of the middle

### ISSUE THREAD

**Issue by dobratzp** [gravitystorm/openstreetmap-carto#3261]
### Expected behavior
Label and icon placed inside area.

### Actual behavior
Label and icon placed at one of the vertices of the area

### Links and screenshots illustrating the problem

OSM Objects:
[Willamette Dental Group](https://www.openstreetmap.org/way/344850686) 👎
[Fehrenbacher Hof](https://www.openstreetmap.org/way/293248333) 👍
[Goose Hollow Inn](https://www.openstreetmap.org/way/469547323) 👍

standard OSM rendering:
![187526](https://user-images.githubusercontent.com/4961910/41122769-71d0e294-6a51-11e8-934b-71465d992032.png)![187526](https://user-images.githubusercontent.com/4961910/41123328-23886db2-6a53-11e8-97f9-e60b604f02b3.png)

humanitarian OSM rendering:
![187526_hot](https://user-images.githubusercontent.com/4961910/41122929-edaa781c-6a51-11e8-9fa1-fabe80dd390a.png)![187526_hot](https://user-images.githubusercontent.com/4961910/41123342-2ea5be0c-6a53-11e8-9bb3-34a9c18b4b9e.png)

This example uses an amenity=dentist, but I have seen this same issue with many different types of POIs.  The majority of the time, the label and icon are placed correctly as in the above amenity=pub and amenity=cafe.  Looking at the humanitarian rendering, it looks like the label and icon are placed correctly, but the housenumber is also rendered but at the same vertex as in the standard rendering.

**Comment by kocio-pl** [comment]
This is well known Mapnik error (see #1465), which will be fixed on OSMF servers once it will be updated:

https://github.com/openstreetmap/chef/issues/155
