### ISSUE TITLE
Render barrier

### ISSUE THREAD

**Issue by IVAN-RSM** [gravitystorm/openstreetmap-carto#3262]
Render fences, walls and all barriers on top of highway=pedestrian, area=yes...

**Comment by Tomasz-W** [comment]
One of the most annoying issues of the Osm-carto for me...
It was closed in https://github.com/gravitystorm/openstreetmap-carto/issues/528, but there is still a hope - see https://github.com/gravitystorm/openstreetmap-carto/pull/3075#issuecomment-392311740

**Comment by kocio-pl** [comment]
It's a duplicate of #528, so I will close it, please discuss the problem there.
