### ISSUE TITLE
Add icon for amenity=boat_rental

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3263]
https://wiki.openstreetmap.org/wiki/Tag:amenity=boat_rental (1,8k uses)
It may be useful, especially for summer season :)

Icon proposal:
![amenity boat_rental](https://user-images.githubusercontent.com/25656654/41200593-babc9504-6ca7-11e8-9513-2d36eaf8b24b.png)

**Comment by kocio-pl** [comment]
It sounds and looks good too for me.

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/17191bd5781d2d015f556ba42f824cf3

@james2432 maybe you are interested in write a PR for this feature?

**Comment by james2432** [comment]
Sure
