### ISSUE TITLE
Add border color around park areas to differentiate them

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3264]
I think there should be a border around park areas to differentiate them from other areas with the same color near by, like other parks. As at this point if there if two parks are next to each other there is no way to tell where one park stops and the other starts. Although it might not be a huge issues normally, it is made much worse by the lack of a clear definition on what constitutes a park  so many grassy leisure areas etc with the same color are right next to each other and can't be told apart.  For the color I propose the same color used by the border on protected areas. I think its like a dark green. This should also be to complement the fill area color and not to replace it.

**Comment by Tomasz-W** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/3045 and https://github.com/gravitystorm/openstreetmap-carto/issues/3045#issuecomment-370219059

I would also like to see parks with outlines, but I think they should have different colour than protected areas, and they should be light green to match park area fill.

**Comment by matkoniecz** [comment]
Can you give an example of correctly tagged location where it would be useful?

**Comment by Tomasz-W** [comment]
@matkoniecz 
Parks "overwritten" by certain landcover tags, examples:
https://www.openstreetmap.org/way/23003645
https://www.openstreetmap.org/way/23003645
https://www.openstreetmap.org/way/180360395

In situations like above, it would be a lot easier to recognize a park size with an outline.

**Comment by polarbearing** [comment]
In both examples above (one is a dup) the park is visually very recognisable to me on the map. Adding an outline sounds interesting, however the 'park' tag is also used of lots of small green areas in towns, so the outline would clutter the map.

I'd prefer to wait until we have implemented the planned outlines for accommodation and museum, and experiment afterwards.

**Comment by Adamant36** [comment]
Here are some more examples, where parks are next to each other and its impossible to tell where one ends and the other starts. I could see a border adding clutter in places like @polarbearing talks about. Maybe it would't be as that much of an issue if the border color was subtle though. 

https://www.openstreetmap.org/#map=16/38.6818/-121.1679

https://www.openstreetmap.org/#map=13/37.9076/-122.2506

https://www.openstreetmap.org/#map=16/36.6249/-121.9160

https://www.openstreetmap.org/#map=13/37.6266/-122.0186

https://www.openstreetmap.org/#map=14/37.4527/-121.8571

**Comment by Adamant36** [comment]
Any chance we could revisit this? It doesn't seem like the planned outline coordination is going to happen anytime soon and its still a major issue. There's no reason we couldn't give parks the same outline as protected areas (maybe we could use it as the same outline for all "parkish" boundaries to unify them), or if not go with some other option.

**Comment by Tomasz-W** [comment]
I consider `leisure=park` as half landcover-like feature (a group of unspecyfied plants) and half cultural-like feature ("park" it's a kind of status which cities give to an unusual good green areas), so I surely would like to see some test renderings of an outline and potential new `#9DF2AC` shade for them (see: https://www.openstreetmap.org/user/Tomasz_W/diary/45047).

**Comment by Adamant36** [comment]
@tomasz-W, the color and boundary sounds like a good idea. I'm not a big fan of the current color myself. Plus I've heard a lot of criticism about it in other places besides here. So, it could use some improvement. 

As far as the issues go, they seem to be a lot more work then this one and they have all stalled out. Plus, there's no particular reason why they should be prioritized over this one that I can see anyway. Like, I wouldn't put any of them higher on a list of rendering importance. They are all about the same. To me, its more about what's actually doable or not. If we have one easy issue that  can be solved in a fair amount of time or three extremely complicated issues that will take a lot of time to accomplish, id go with the easy quick issue. 

If I've learned something from being involved in this over the last couple of years its that there's a natural inclination to put of the harder stuff for the more low hanging fruit and there's always low hanging fruit. So the harder stuff never ends up getting done. There's nothing wrong with that, but it does make prioritizing more difficult. 

There's a few complicated issues I've been wanting to do for a while now, but there's always new icons to add or something else simple to do. Its the attraction of the quick easy win I guess. That being said, I'll go over the other issues when I have some time and see if any of them can get done. I'd still like to work on this one in the mean time though. There's no reason not to.

**Comment by Tomasz-W** [comment]
@Adamant36 If you would start to do a code for this issue, please notice that park colour is connected with some elements by 'darken' option (e.g. leisure-green is based on current park colour, it should be saved and replaced by a RGB code then)

**Comment by jeisenbe** [comment]
I would be happy to see a different color for pitches and leisure. Pitches
are quite shocking on certain backgrounds. Didn’t we change the social
amenities color for that reason?

**Comment by Adamant36** [comment]
Id support that. Maybe sports centers (complexes?) also. I guess they should all be dealt with together in a meta issue or something if they are all going to be changed at the same time. Although, id say id say "color" issues are different then if parks should have border around them or not. The park can be whatever color you want to make it, but it wouldn't solve the problem this issue wants to deal with, telling parks that are next to each other apart.

**Comment by Tomasz-W** [comment]
I've made some ameteur tests in Photoshop and I propose to change leisure fill colour to 20% lighten of proposed park colour `#9DF2AC`. I consider current both of them too blueaish instead of greenish. I don't have any problem with current pitches colour, so I woulnd't change it.

**Comment by Adamant36** [comment]
@HolgerJeromin, good spot. It didn't get tested very much in the original PR from what I remember. You might want to open a new issue for it.

**Comment by Tomasz-W** [comment]
@HolgerJeromin https://github.com/gravitystorm/openstreetmap-carto/issues/3045 is a more proper ticket to discuss amenity outlines ;)

**Comment by jeisenbe** [comment]
It was recommended to decline this suggestion in https://github.com/gravitystorm/openstreetmap-carto/pull/4555#issue-1245520424 

We generally only render an outline for areas which are named and likely to be next to an identical area which also has a name, for example `landuse=residential`, `landuse=retail`, `landuse=allotments`, `amenity=school`

The only example location from above where a outline would be useful is https://www.openstreetmap.org/#map=17/38.68166/-121.16902 where there really are 2 directly adjacent `leisure=park` features with different names. However this is quite rare, all the other examples above have either been changed to a protected area boundary in the meantime or are not directly adjacent to another park, so the outline is not useful. 

We do not render an outline for `leisure=garden`, `leisure=golf_course` or `landuse=cemetery`, though we do for `leisure=recreation_ground` now, since it was changed to be lighter than `leisure=park`.

I recommend closing this and also changing `leisure=recreation_ground` back to the prior rendering for consistency.
