### ISSUE TITLE
Highway under construction in tunnel renders on top of buildings

### ISSUE THREAD

**Issue by jarikirma** [gravitystorm/openstreetmap-carto#3265]
### Expected behavior

highway=construction
construction=secondary
tunnel=building_passage (or plain yes)

should render differently when it is running through (or under) buildings.

### Actual behavior

Seen on openstreetmap.org: such a highway renders over buildings, even those at higher layers. At the same time, it is not rendered on top of areas like highway=pedestrian.

### Links and screenshots illustrating the problem

![image](https://user-images.githubusercontent.com/1022328/41497853-e4576f42-7166-11e8-859e-53097033e5e6.png)

Seen at https://www.openstreetmap.org/#map=19/60.17524/24.80590

**Comment by polarbearing** [comment]
Apparently a problem with _construction_. A finished motorway under a building renders correctly with tunnel casing, e.g. https://www.openstreetmap.org/#map=19/52.47526/13.30652

The ped area covering everything is a separate problem, an probably an open ticket here.

**Comment by pnorman** [comment]
I believe this is unrelated to buildings and I don't think we change style for tunnels on highway=construction at all.

**Comment by jarikirma** [comment]
I'm just wondering how to work around the issue as a map editor. This street has been a public transport street under a building complex for ages, being rebuilt for years, and not in use for a good while to the future, although it does reincarnate eventually. From the perspective of traffic routing it doesn't have any significance at this point. Should it be labelled something like was=highway to hide it for now?

Running a construction over a residential building (which is, BTW, is couple dozen meters above the tunnel level) obscures the map quite significantly.

**Comment by polarbearing** [comment]
Do we have other examples how tunnels under construction are rendered? 
They should at least have the dashed casing.

**Comment by matkoniecz** [comment]
> Highway under construction in tunnel renders on top of buildings

Any road renders on top of any buildings, it seems that this report is rather about missing special for road under construction that is tagged with tunnel tag.

**Comment by matkoniecz** [comment]
What seems to be reported as #761

**Comment by polarbearing** [comment]
So this issue can be closed, and #761 should be fixed?

**Comment by matkoniecz** [comment]
Yes.

Thanks for a well prepared bug report - unfortunately this issue is already known and tracked as #761, so I am closing this report.
