### ISSUE TITLE
Colors of old mapnik

### ISSUE THREAD

**Issue by archboy87** [gravitystorm/openstreetmap-carto#3269]
Where can I find the color codes of forests and farmland from the ["old mapnik" style](http://bl.ocks.org/tyrasd/raw/6164696/)?

Sorry for asking something at a place where only proposal should be.

**Comment by imagico** [comment]
You can find the code of the old Mapnik XML style this style is derived from through the link from the README:

https://trac.openstreetmap.org/browser/subversion/applications/rendering/mapnik

**Comment by archboy87** [comment]
@imagico: Haven't you once created a color comparison old vs new?

**Comment by imagico** [comment]
I am not aware of such a comparison overall.

The current style for landcover coloring also does not use constant colors any more, they vary between zoom levels for z<13.

**Comment by kocio-pl** [comment]
There's also mirror of the old code on GitHub:

https://github.com/openstreetmap/mapnik-stylesheets
