### ISSUE TITLE
Render watchtower like an observation tower

### ISSUE THREAD

**Issue by naoliv** [gravitystorm/openstreetmap-carto#3275]
Could we have the `man_made=tower` + ` tower:type=watchtower` objects rendered like a `tower:type=observation` tower, please?

There was a suggestion here https://github.com/gravitystorm/openstreetmap-carto/pull/2671#issuecomment-377665578 but right now they are being rendered as some kind of unknown type:

For example, https://www.openstreetmap.org/node/4306889882
![](https://user-images.githubusercontent.com/982338/41744367-f4fe68d4-7579-11e8-8933-22aa328dfa9b.png)

While having this would be nicer and more realistic:
![](https://user-images.githubusercontent.com/982338/41744479-39450cf0-757a-11e8-974e-212ff5b2d399.png)

**Comment by kocio-pl** [comment]
This is prepared in the second step - see #3158.

**Comment by naoliv** [comment]
Ah... I didn't see #3158 
Thanks!
