### ISSUE TITLE
regression: service access restriction covers motorway fill

### ISSUE THREAD

**Issue by giggls** [gravitystorm/openstreetmap-carto#3279]
### Expected behavior
as rendered up to v4.11.0

### Actual behavior
as rendered from v4.12.0
### Links and screenshots illustrating the problem
Starting from v4.12.0 (at least, I did not use git bisect) service way fill seems to be rendered above motorway. Attached are two files illustrating this behavior.
v4.11.0:
![test-construction-v4 11 0](https://user-images.githubusercontent.com/7996314/41922361-35cd5e94-7965-11e8-854b-a7caaf32f46b.png)
v4.12.0
![test-construction-v4 12 0](https://user-images.githubusercontent.com/7996314/41922382-453ad906-7965-11e8-8156-048d31053b17.png)

Service way is right above the "H" from "Dreieck Hochrhein" exit name.

**Comment by sommerluk** [comment]
Rendering in v4.12.0 at scale factor 5:
![screenshot 1](https://user-images.githubusercontent.com/6830724/41952405-2f31d646-79bf-11e8-8b7d-3332824b53fb.png)

The service road’s fill is rendered correctly below the motorway link’s fill. The service road’s access restriction (`.access::fill`) is rendered incorrectly above the motorway link’s fill. This is indeed a regression in #2640. The attachment within which the road fills were rendered was called `::fill` before, but in #2640 it has been renamed, while `.access::fill` remained unchanged.

**Comment by sommerluk** [comment]
Closing as the commit that had introduced this regression has been reverted. (I’ll take this into account when doing a new PR for unpaved roads.)

Thanks for the report!
