### ISSUE TITLE
Add special icon for shop=massage

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3287]
https://wiki.openstreetmap.org/wiki/Tag:shop=massage
8k uses

Icon could be a massage table? I haven't been able to design anything intuitive enough for this.

**Comment by Tomasz-W** [comment]
Icon proposal:

![shop massage](https://user-images.githubusercontent.com/25656654/42266110-c15d014c-7f75-11e8-88b7-b183e7fcef08.png)

**Comment by lakedistrictOSM** [comment]
That's not too bad actually. My icon designs involving people all looked like they were straight out the Kama Sutra!

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/f5964c0215475bffa4649eb1531dd564

As this isn't a place where you go to buy some goods, but for leisure service, I think it should be in leisure-green.
