### ISSUE TITLE
Add  special icon for shop=paint

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3288]
https://wiki.openstreetmap.org/wiki/Tag:shop=paint
7.6k uses

Icon could be a paint brush or a roller?
https://thenounproject.com/search/?q=paintbrush&i=105797
https://thenounproject.com/search/?q=paintbrush&i=466004
https://thenounproject.com/search/?q=paintbrush&i=273917

**Comment by Tomasz-W** [comment]
Icon proposals:
* ![shop paint brush](https://user-images.githubusercontent.com/25656654/42269320-233b1054-7f7e-11e8-9cf7-a66cae0a5cf7.png) (roller brush)
* ![shop paint pail](https://user-images.githubusercontent.com/25656654/42269584-d3384bc0-7f7e-11e8-992e-ff426973d62b.png) (paint pail)

**Comment by jragusa** [comment]
I vote for 1

**Comment by turnsole80** [comment]
1, and it works well for AU/NZ

**Comment by dktue** [comment]
vote for 1

**Comment by HALCONDEORO** [comment]
vote for 1

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/245e2151c51541d6265f540bc490eafe
