### ISSUE TITLE
Add  special icon for shop=fabric

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3289]
https://wiki.openstreetmap.org/wiki/Tag:shop=fabric
7.5k uses

No idea what the icon would look like. I don't think a roll of fabric would work. Any ideas @Tomasz-W?

**Comment by Adamant36** [comment]
I was just looking for an icon for that last night. Theres some good examples on Noun Project https://thenounproject.com/search/?q=fabric

Also for shop=sewing if you want to create an issue for it to https://thenounproject.com/search/?q=sewing

https://thenounproject.com/search/?q=sewing%20machine

**Comment by Tomasz-W** [comment]
Icon proposal:
![shop fabric](https://user-images.githubusercontent.com/25656654/42270886-31ea791a-7f82-11e8-9a86-316779ee83b8.png) (polka dot pattern)

I'm worried that it looks more like a carpet (we could use it for `shop=carpet`). I'll try to make a more folded version later (like this: https://cdn2.iconfinder.com/data/icons/industry-3/512/textile-2-512.png), maybe it will be better.

For `shop=sewing` I propose to use icon proposed for `craft=tailor`.
See: https://github.com/gravitystorm/openstreetmap-carto/issues/1697#issuecomment-365560281
https://gist.github.com/Tomasz-W/7227fe37f9e4a7e945a977023af84b25

There was a proposition to use violet version of this icon for `shop=tailor`.

**Comment by lakedistrictOSM** [comment]
The sewing machine icon should be saved for `shop/craft=tailor`. We can design a new icon (probably a needle and thread or cotton reel) for `shop=sewing` (805) / `shop=haberdashery` (290) when there's more uses.

**Comment by Adamant36** [comment]
I kind of like idea of something like a button with a needle through it and some string for the tailor. Their are of touch up people then seamstresses.

**Comment by Tomasz-W** [comment]
`shop=fabric`:
* ![shop fabric s](https://user-images.githubusercontent.com/25656654/42292054-0ad7f426-7fd0-11e8-8ef2-bf47b5f0a25e.png) (single roll)
* ![shop fabric](https://user-images.githubusercontent.com/25656654/42291533-94476dda-7fcc-11e8-8e82-bd9952f20b11.png) (double roll)

`shop=carpet`:
* ![shop carpet](https://user-images.githubusercontent.com/25656654/42291809-66fd6904-7fce-11e8-9264-bc44ea4e27f5.png) (no-pattern)
* ![shop carpet](https://user-images.githubusercontent.com/25656654/42291930-2eb7d1f0-7fcf-11e8-8df1-71fa1a9d72c5.png) (zigzag pattern)

`shop=sewing`:
* ![shop sewing nici](https://user-images.githubusercontent.com/25656654/42292812-888391fa-7fd5-11e8-80df-9774f4b9db7a.png) (needle + thread)
* ![shop sewing guzik](https://user-images.githubusercontent.com/25656654/42292804-71bf928e-7fd5-11e8-8485-ad68e64366d1.png) (needle + button)

**Comment by meased** [comment]
The fabric icon looks like paper clips, the carpet icon doesn't really look like anything to me, the sewing icons are good...

However, I don't feel every shop needs a special icon, just the popular or very prominent ones. A violet dot is perfectly fine for shops such as these. I feel the same way about craft rendering, it would be nice if they were rendered, but dots are fine, no need to make a thousand icons.

**Comment by lakedistrictOSM** [comment]
> The fabric icon looks like paper clips, the carpet icon doesn't really look like anything to me, the sewing icons are good...

I suggest that the proposed `shop=sewing` icon (needle + thread) is used for both `shop=fabric` and `shop=sewing/haberdashery` since it's the best icon design.

> However, I don't feel every shop needs a special icon, just the popular or very prominent ones. 

These recent issues are just about finding icons for the most popular ones, generally above 6k uses.

> A violet dot is perfectly fine for shops such as these. I feel the same way about craft rendering, it would be nice if they were rendered, but dots are fine, no need to make a thousand icons.

I'm happy for similar shops to share the same icon. I'm not keen on introducing more dots unless they have a unique colour (like shop and office do).

**Comment by dktue** [comment]
Vote for needle+button

**Comment by Tomasz-W** [comment]
Gist links:
* fabric rolls: https://gist.github.com/Tomasz-W/24baa83bbed6e1b56b6d86c54d56579f
* carpets: https://gist.github.com/Tomasz-W/760905dbf57ecf04faf6a527fd9e3397
* sewing: https://gist.github.com/Tomasz-W/1ebdcaec21c3974853710fe9e5695358

**Comment by Tomasz-W** [comment]
I would like to establish output of discussion here. Which icons do you want for which shops, and which ones we should skip?

**Comment by dktue** [comment]
I would vote for needle+button for shop=sewig and I don't have an opinion on the icons for shop=carpet and shop=fabric.

**Comment by lakedistrictOSM** [comment]
I vote for needle + thread for both fabric and sewing/haberdashery, since it's the clearest icon and both shops are similar.

**Comment by Tomasz-W** [comment]
@kocio-pl Is shop=fabric similar enough to shop=sewing to use the same icon for both? What do you think about it?

**Comment by lakedistrictOSM** [comment]
Needlecraft shops:
`shop=fabric` (7.6k uses)
`shop=sewing` (858 uses)
`shop=haberdashery` (295 uses)
`shop=wool` (143 uses)

Nearly 9k collectively 

A new issue can be opened to discuss `shop=carpet`.

**Comment by polarbearing** [comment]
needle + thread is fine for shop=sewing.
(button is more comprehensive but misunderstood as a smiley)

I'd rather not render shop=haberdashery due to the similarity to shop=sewing (even the wiki says so) to discourage tag fragmentation. 

For fabric, the needle+something icons appear unsuitable to me as it fails to show the main article. 
I like the roll icons but understand the resemblance to paper clips. Maybe, instead of two rolls, we could have a roll with one more turn?

**Comment by Tomasz-W** [comment]
* `shop=fabric` icon proposals with cotton pattern

1) ![shop fabric 1](https://user-images.githubusercontent.com/25656654/44658611-bac59400-aa01-11e8-8d5d-9ce886308457.png)
2) ![shop fabric 2](https://user-images.githubusercontent.com/25656654/44658613-bac59400-aa01-11e8-979e-cb11028fcfc9.png)
3) ![shop fabric 3](https://user-images.githubusercontent.com/25656654/44658614-bac59400-aa01-11e8-9167-92ad24e35223.png)

* for `shop=carpet` I don't have any better idea than proposed earlier:
1) ![shop carpet](https://user-images.githubusercontent.com/25656654/42291809-66fd6904-7fce-11e8-9264-bc44ea4e27f5.png) (no-pattern)
2) ![shop carpet](https://user-images.githubusercontent.com/25656654/42304972-24787ffa-8029-11e8-9872-27517db572ee.png) (zigzag pattern)

**Comment by lakedistrictOSM** [comment]
We should probably check with the tagging list which of sewing or haberdashery should be supported. (And maybe someone could do a mass edit to change them all, since the wiki definitions are almost identical)

I still prefer needle + thread, and it's worth remembering we use icons that aren't always what a shop mainly sells, eg a cake for confectionery and chocolate shops. What's important is that the icons are easily understood and are give some idea about what a shop sells - in this case something to do with sewing.

**Comment by polarbearing** [comment]
New shop=fabric icon 1 is very convincing from my perspective :-) . The upper part has a weaving which makes clear that it is not stationary (paperclip). Even better than my idea with the extra loop. 
No 2 and 3 look more like fences than fabric.

For the carpet, I don't understand the object on the right, maybe it is supposed to be the core the carpet is rolled on, but not intuitive for me. 
What about a square that has fringes on all four sides? Just a flat carpet, not rolled.

**Comment by Tomasz-W** [comment]
@polarbearing Flat carpet version: 

![shop carpet2](https://user-images.githubusercontent.com/25656654/44680015-def29680-aa3c-11e8-9728-c617378bda35.png)

**Comment by polarbearing** [comment]
some square versions:
![square_carpet1](https://user-images.githubusercontent.com/8266355/44685039-c9846900-aa4a-11e8-96b9-0b72be002dc9.png)
![square_carpet](https://user-images.githubusercontent.com/8266355/44685087-e1f48380-aa4a-11e8-911b-72d84ee52ccb.png)

**Comment by Tomasz-W** [comment]
For me, it looks like processor icon.

**Comment by dktue** [comment]
looks definitely like a CPU or a chip in general, too @Tomasz-W, @polarbearing

**Comment by polarbearing** [comment]
I understand, yes. Focussing on the topic of this issue, can we agree on 'New shop=fabric icon 1' with the webbing? And the needle/thread one for sewing, leaving lesser used tagging for later decision?

**Comment by Tomasz-W** [comment]
Gist links:

* `shop=fabric` https://gist.github.com/Tomasz-W/24baa83bbed6e1b56b6d86c54d56579f
* `shop=sewing` https://gist.github.com/Tomasz-W/1ebdcaec21c3974853710fe9e5695358

**Comment by dktue** [comment]
I like the pattern-version for `shop=fabric` and the one with the button for `shop=sewing` from your last post @tmcw !

**Comment by dktue** [comment]
Your flat-carpet version looks good, too @Tomasz-W !

**Comment by Tomasz-W** [comment]
Here is a SVG file if someone would like to test it: 

https://gist.github.com/Tomasz-W/760905dbf57ecf04faf6a527fd9e3397

**Comment by Adamant36** [comment]
shop sewing (needle + thread)
![shop sewing needle thread](https://user-images.githubusercontent.com/30259065/48907524-96b8f980-ee1c-11e8-9012-db331b9b7d56.png)
shop sewing (needle + button)
![shop sewing needle button](https://user-images.githubusercontent.com/30259065/48907549-a46e7f00-ee1c-11e8-8430-f1e7b68f5b7b.png)
shop fabric (pattern)
![shop fabric pattern](https://user-images.githubusercontent.com/30259065/48907575-b51ef500-ee1c-11e8-953c-c290c87ea2c2.png)
shop fabric (1 roll)
![shop fabric 1 roll](https://user-images.githubusercontent.com/30259065/48907589-bfd98a00-ee1c-11e8-9b3b-124f0e7a72a2.png)
carpet (zigzag)
![carpet zigzag](https://user-images.githubusercontent.com/30259065/48907602-cec03c80-ee1c-11e8-840d-c3d185240def.png)
carpet (no-pattern)
![carpet no-pattern](https://user-images.githubusercontent.com/30259065/48907625-db449500-ee1c-11e8-9408-fc6420f12c62.png)
carpet (flat)
![carpet flat](https://user-images.githubusercontent.com/30259065/48907637-e697c080-ee1c-11e8-948c-7a2bd9e557f3.png)

**Comment by kocio-pl** [comment]
My votes are:
- shop sewing (needle + thread)
- shop fabric (1 roll)
- carpet (flat)

**Comment by Tomasz-W** [comment]
* sewing -> needle + thread
* fabric -> I'll provide pattern-only icon, because rolls are not intuitive imo

@Adamant36 I think something went wrong with carpets icons (https://gist.github.com/Tomasz-W/760905dbf57ecf04faf6a527fd9e3397) , there was a space between rolled and unrolled parts of it, and on the test renderings they seem to be joined together.

**Comment by Tomasz-W** [comment]
`shop=fabric` (pattern-only):

![shop fabric 1](https://user-images.githubusercontent.com/25656654/48949891-d0335700-ef39-11e8-9030-22684ffb193b.png)

Gist link: https://gist.github.com/Tomasz-W/24baa83bbed6e1b56b6d86c54d56579f

**Comment by polarbearing** [comment]
I somehow liked the pattern+roll no 1 from Aug 27, but I can also agree with today's pattern-only.

**Comment by dktue** [comment]
pattern-only works fine for me. 👍

**Comment by Tomasz-W** [comment]
@Adamant36 There was an error in carpet icon, but I fixed it. Can you test zig-zag version for shop=carpet once more? https://gist.github.com/Tomasz-W/760905dbf57ecf04faf6a527fd9e3397#file-shop-carpet-zigzag-svg
