### ISSUE TITLE
Add icon for shop=trade (and potentially shop=wholesale)

### ISSUE THREAD

**Issue by lakedistrictOSM** [gravitystorm/openstreetmap-carto#3291]
https://wiki.openstreetmap.org/wiki/Tag:shop=trade
6.7k uses

Probably something involving pallets or maybe a fork lift truck. Could share an icon with [shop=wholesale](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwholesale) (1.3k uses).

1 ![trade01png](https://user-images.githubusercontent.com/20193716/42230224-514dae46-7ee0-11e8-9d93-0bcfc0ef7151.png)

**Comment by Tomasz-W** [comment]
I think it's too "wide" tag for specific icon. I would left dot-rendering only.

**Comment by Adamant36** [comment]
@Tomasz-W maybe not in combination with its sub tags

trade=building_supplies: 1263, could be a stack of wood pallets 
trade=plumbing: 176, probably not worth as icon showing yet
trade=timber: 122, could have same icon as building_supplies or just stay a dot for now
trade=agricultural_supplies: 380, a bag of seeds or a rake maybe
trade=tiles: 89, not worth showing yet and can keep as dot
trade=windows: 14, not worth showing yet

Building supplies seems way worth having an icon. There's a lot of Home Depots and Lowe's out there. It might encourage mappers to add the sub tag on the ones that don't have it. Agricultural stores also. Some good examples of possible icons for both on Noun Project. The rest can probably just wait and stay as dots until their numbers increase.

**Comment by Tomasz-W** [comment]
Icon proposals:
* ![shop trade2](https://user-images.githubusercontent.com/25656654/42308392-b4fe382e-8035-11e8-9fff-e81db8e87b34.png) (3 boxes)
* ![shop trade](https://user-images.githubusercontent.com/25656654/42308214-3bc39ca6-8035-11e8-88c6-1bbd9dc96a90.png) (4 boxes)

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/79e6deb43381777ed666e8911c240743

**Comment by kocio-pl** [comment]
I would use 3 boxes.

**Comment by lakedistrictOSM** [comment]
Gist link for 1: https://gist.github.com/lakedistrictOSM/05cedcc617964fd06fe5e629cc172629

**Comment by Tomasz-W** [comment]
@lakedistrictOSM I would prefer my version, because it's more pixel alligned and it has adhesive tape shapes making the squares to look more like a boxes.

**Comment by lakedistrictOSM** [comment]
@Tomasz-W I like the detail on your version but it looks a bit blurry to me. In any case it should be 3 boxes, since 4 boxes is too solid.
