### ISSUE TITLE
Outline of some River Thames islands not being rendered

### ISSUE THREAD

**Issue by martenjj** [gravitystorm/openstreetmap-carto#3294]
For the last few weeks, some islands in the River Thames (GB) are not being rendered correctly:  the features on the islands are rendered, and forest/wood landuse on the island, but not the island land area itself.  See the screen shot below, from https://www.openstreetmap.org/#map=17/51.39881/-0.41554

I did make some edits around this island (using iD) a few weeks ago, but did not need to touch the island boundary or the river relation it is part of (2110237).

There seem to be islands missing in this relation (2110237) and upstream of it (28938, 2001806). However, 2006294 further upstream and 308126 downstream are rendered correctly.

The tags of the relations appear to be identical for the working and non-working sections of the river, and correct according to https://wiki.openstreetmap.org/wiki/Tag:waterway%3Driverbank (natural=water water=river).  That wiki page says that the multipolygon should not be tagged with natural=water, but both 308126 and 2006294 have these tags and they are rendered correctly.

### Expected behavior

Island land areas are rendered in the same way as any other land area

### Actual behavior

Island land areas are not rendered

### Links and screenshots illustrating the problem
![image](https://user-images.githubusercontent.com/10631760/42370191-0066d856-8104-11e8-94a8-8614bb3b5543.png)

**Comment by imagico** [comment]
That's a classic old style Multipolygon,

https://www.openstreetmap.org/way/157812282

is a water area covering all the islands and is rendered as such.  Remove the tags from this way and you should be fine.

Side note:  Name tags for rivers belong to the waterway and not to the riverbank polygon.

**Comment by sommerluk** [comment]
Thanks for a well-written bug report! You have added the IDs of the ways and relations you’ve talked about – that’s good!

The responsible changeset that introduced the problem @imagico  talked about is https://www.openstreetmap.org/changeset/60110356 which added

key | value
-- | --
name | River Thames
natural | water
water | river

directly to the way which is wrong because not all of the polygon is actually water: The islands within it are not. The way is part of a multipolygon relation which represents the water yet correctly. I’ve fixed the data in https://www.openstreetmap.org/changeset/60461985

**Comment by dieterdreist** [comment]
2018-07-06 11:42 GMT+02:00 Christoph Hormann <notifications@github.com>:

> Side note: Name tags for rivers belong to the waterway and not to the
> riverbank polygon.



agreed they should also go on the (linear) waterway, but why not on the
polygon? The wiki says on the riverbank polygon a name=* is fine. Is there
a problem with putting the river name on the riverarea?

**Comment by imagico** [comment]
@dieterdreist - this is a discussion to be held elsewhere - i am just communicating what is common practice and only about 14 percent of all riverbank polygons have a name tag and not all of them are actually river names.  Most of them are just tagging for the renderer to place labels.

**Comment by dieterdreist** [comment]
sent from a phone

> On 6. Jul 2018, at 13:14, Christoph Hormann <notifications@github.com> wrote:
> 
> @dieterdreist - this is a discussion to be held elsewhere - i am just communicating what is common practice and only about 14 percent of all riverbank polygons have a name tag
> 


14% usage is not so few that it would justify the removal of names that actually apply to the feature, at most you could state it is less common.


> and not all of them are actually river names. 
> 


I did not check this thoroughly, but of course if the name is wrong it should be corrected, as always.

**Comment by martenjj** [comment]
Many thanks for the clarification.  I knew about the need for proper tagging and consistency for riverbank relations, but was confused by, e.g. way 26600620 (the outer of relation 308126) being tagged with natural=water;water=river but rendering properly.  This could just be tile caching.

I'm going to look at the wiki page again, because the instructions (section "How to map") are not totally clear and should strongly emphasise that the outer ways should not be tagged.  (and it also says "do *not* tag parent relations with natural=water" which is wrong according to the above comments).

**Comment by dieterdreist** [comment]
sent from a phone

> On 6. Jul 2018, at 18:43, Jonathan Marten <notifications@github.com> wrote:
> 
> (and it also says "do not tag parent relations with natural=water" which is wrong according to the above comments).


IMHO there is no clear right or wrong for natural=water in this context, together with waterway=riverbank it seems to be redundant though. As Christoph suggested this could be discussed on the tagging ml.

**Comment by sommerluk** [comment]
> was confused by, e.g. way [26600620](https://www.openstreetmap.org/way/26600620#map=16/51.3948/-0.3285) (the outer of relation [308126](https://www.openstreetmap.org/relation/308126#map=17/51.39417/-0.33029)) being tagged with natural=water;water=river but rendering properly. This could just be tile caching.

Indeed in this case the islands seem to be rendered. (As it makes yet 13 days since the last data change for the river water area, I suppose that’s _not_ a tile caching issue.) I would expect that the island isn’t visible (wrong tagging should be visualized by broken rendering result). And I have no idea why this behaves inconsistently here…

**Comment by mboeringa** [comment]
@martenjj and @sommerluk: there were still some major issues with the MP relation of the water body, and the river Thames waterway line relation. I have now corrected both of them. 

The islands in this part of the Thames should re-appear soon now.
