### ISSUE TITLE
Please add name rendering for landuse=religious

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#3322]
We have rendering of landuse since #2751
I moved the poi data from the building in the outline of https://www.openstreetmap.org/way/611970939
This is a parish centre.
Many current `name` I checked should be moved to `operator` however this would probably be done if the name is rendered.

**Comment by antifa-ev** [comment]
Especially in the Americas people map churchyards as building, because landuse=religious is not getting rendered. +1

**Comment by kocio-pl** [comment]
I also did not add symbol rendering IIRC, so maybe this might be needed too.

Does anyone want to try to create the proper code and test it - maybe one of you would like to try? We still have too many coders and a lot of tasks/issues to do.

**Comment by dieterdreist** [comment]
sent from a phone

> On 1. Aug 2018, at 14:52, antifa-ev <notifications@github.com> wrote:
> 
> Especially in the Americas people map churchyards as building, because landuse=religious is not getting rendered. +1


there is amenity=graveyard that is rendered. landuse=cemetery is also rendered but I agree it doesn’t fit for churchyards.

**Comment by kocio-pl** [comment]
Anybody willing to make the code and test it a bit?
