### ISSUE TITLE
v4.12.0

### ISSUE THREAD

**Issue by NKAmapper** [gravitystorm/openstreetmap-carto#3324]
Are the new features in v4.12.0 supposed to be rendered by now (except the surface tag)?
I cannot find rendering for any of those features (towers, quarter, brown shelter, etc).

**Comment by imagico** [comment]
No, you can follow the issues on openstreetmap/chef for that:

https://github.com/openstreetmap/chef/issues/168
https://github.com/openstreetmap/chef/issues/170
https://github.com/openstreetmap/chef/issues/172

**Comment by NKAmapper** [comment]
Thanks!

**Comment by kocio-pl** [comment]
That's probably because infrastructure is changing recently and admins are busy:

https://blog.openstreetmap.org/2018/07/25/server-moves-imperial-equinix/
