### ISSUE TITLE
Move manors to higher zoom level

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3325]
Curently both `historic=manor` and `historic=castle` are rendered from z15. It makes them too prominent and looking more important than they actually are. Examples:

manors:
https://www.openstreetmap.org/way/273470884#map=15/52.3669/16.9812
https://www.openstreetmap.org/way/273470883#map=15/52.3737/16.8508
https://www.openstreetmap.org/way/238038057#map=15/52.4118/16.9404
https://www.openstreetmap.org/node/5355328416#map=15/53.0894/16.1363
castles:
https://www.openstreetmap.org/relation/1483520#map=15/52.4077/16.9189
https://www.openstreetmap.org/way/274284937#map=15/52.9427/17.3060
https://www.openstreetmap.org/way/525949706#map=15/52.5731/17.0071

I propose to move them to z16 like eg. forts. Those buildings was the most important thing in cities hundreds of years ago. Now they are jus one of a tourist attractions, so they shouldn't be that prominent. 

I would consider moving an `amenity=townhall` to z15 instead.

**Comment by matkoniecz** [comment]
From quick look it seems a good idea for manors but I am not sure about castles that are typically major tourism attractions.

**Comment by kocio-pl** [comment]
The problem is also at the tagging level, I guess. What I'd like to show from z15 are all the castles, manors etc. which are big and standalone, no matter what is their exact type. Some of them which are part of a city might be better tagged as just `building=palace` for example. 

In this case tagging is not suitable for rendering good maps (not only in this style) and I'm not quite sure how to redefine it to be more useful.

**Comment by kocio-pl** [comment]
On the other hand this is not specialized map for tourism, so while I like seeing important castles and manors from z15+ very much, showing all of them from z16+ is not a serious omission and would reduce clutter in places like this:

https://www.openstreetmap.org/#map=15/49.5979/11.0109

**Comment by matkoniecz** [comment]
@kocio-pl Have you encountered case where correctly tagged castles are problematic?

From OP

https://www.openstreetmap.org/relation/1483520#map=15/52.4077/16.9189 - for me looks OK
https://www.openstreetmap.org/way/274284937#map=15/52.9427/17.3060 - looks OK
https://www.openstreetmap.org/way/525949706#map=15/52.5731/17.0071 - I opened https://www.openstreetmap.org/note/1476434

**Comment by kocio-pl** [comment]
Some castles located in the big cities don't pose a visual problem for me, even if not all of them are too important probably (assuming that they are not mistagged):

https://www.openstreetmap.org/query?lat=52.2472&lon=21.0164#map=15/52.2426/21.0244
https://www.openstreetmap.org/#map=15/51.5014/-0.1397
https://www.openstreetmap.org/node/3611368951#map=15/48.8522/2.3415
https://www.openstreetmap.org/#map=15/35.6842/139.7301

These manors also make clutter (and I'm also not sure how should they be tagged really):
https://www.openstreetmap.org/#map=15/55.7493/37.5924

so I second @matkoniecz opinion to only change rendering of all manors and not the other castles and palaces. We can do this not waiting for tagging changes and clarification. I still plan to make a general discussion about it a year after they has been introduced in OSM Carto (around April 2019) anyway.

**Comment by dieterdreist** [comment]
sent from a phone

> On 3. Aug 2018, at 13:19, kocio-pl <notifications@github.com> wrote:
> 
> Some of them which are part of a city might be better tagged as just building=palace for example.


When we speak about castles, this is not about a building alone, usually it is about a bigger structure consisting of several buildings, maybe a ditch, walls, towers, gardens / yards, etc. Similarly for palaces in cities.

**Comment by kocio-pl** [comment]
Anyone willing to make the code? Looks like there's an agreement what to do.

**Comment by matthijsmelissen** [comment]
Thanks for this PR!

**Comment by kocio-pl** [comment]
Castles are still not finished, maybe some more tuning will be needed.

I was thinking about manors as a countryside objects, so I wanted to show them earlier, but I've found quite a lot of them in cities, especially in Moscow:

![screenshot_2018-09-19 openstreetmap](https://user-images.githubusercontent.com/5439713/45751947-40f58480-bc14-11e8-9b20-b7221c427a46.png)

Maybe I was right and they should be tagged as "stately", but it's safer to not assume too much.
