### ISSUE TITLE
Change gastronomy objects colour to orange

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3329]
This ticket is to discuss some old @kocio-pl's proposal with changing rendering of gastronomy objects from brown to orange (it was proposed as part of PR https://github.com/gravitystorm/openstreetmap-carto/pull/2824#issuecomment-328521710 then, but forgotten without discussion or merging later)

@kocio-pl's test rendering with #c64803
![1](https://user-images.githubusercontent.com/5439713/30275522-e66ca422-9701-11e7-936d-4931d1612f82.png)

**Comment by kocio-pl** [comment]
I liked brown+red (#8c0000) more, but it was not fully convincing for me:

![brown+red](https://user-images.githubusercontent.com/5439713/30282173-cbb4f086-9714-11e7-8c51-d4a4efe461cd.png)

**Comment by Tomasz-W** [comment]
When you type a "gastronomy" in Google Images and look fastly before page will become fully loaded (photos are showed as a solid color pictures then), most of them are different shades of orange, see: https://www.google.pl/search?q=gastronomy&client=opera&hs=xSL&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiagtXxotjcAhXGaFAKHWUQAusQ_AUICigB&biw=1920&bih=981 . I think this colour is quite intuitive and ok for a gastronomy.
As there is a plan to change healthcare objects to red (https://github.com/gravitystorm/openstreetmap-carto/issues/2938), I think we should stay with brown/ orange for gastronomy.

**Comment by kocio-pl** [comment]
Maybe some other shade of orange would be better - who knows, it needs testing.

**Comment by polarbearing** [comment]
What restaurant signs are you talking about? Traffic signs, guide-posts?

**Comment by Tomasz-W** [comment]
Here is some compilation of well-known fast food restaurants logos:

http://cdn6.whiskeyriff.com/wp-content/uploads/fast-food-logos-e1358373184340.jpg

Every single one contains red or orange (as I know, it's not a coincidence, it's related to human psychology and marketing). I would like to see a test rendering with light-orange shade from McDonalds/ Burger King logo.

**Comment by polarbearing** [comment]
I find myself puzzled that we start making cartographic colouring decisions based on the brands of individual companies. What is next, landuse=industrial in Siemens blue?

Further, I would not call these fast food facilities restaurants. 

I am still happy with tourism+amenity-brown for these things, restaurants, museums and alike (except those repair services ;-)

**Comment by Adamant36** [comment]
@polarbearing, I think you confuse catography with iconography a bit. Although me and @Tomasz-W might be taking a more iconographic approach here, it still might have merit as the color brown isnt any more grounded in the real world then what we propose and like he says, theres psychology behind it. If not, what better way do you think there is for coming up with colors for those things? Obviously sticking to the old color is an option to if nothing else, but its not like theres any harm in testing a new one.

**Comment by kocio-pl** [comment]
I believe we should treat all gastronomy objects as one category and change the color only here:

https://github.com/gravitystorm/openstreetmap-carto/blob/3e0d7a0083a63aed85116fac451ab8aaf6daf9de/amenity-points.mss#L12

**Comment by polarbearing** [comment]
>  the color brown isnt any more grounded in the real world

It is more grounded: brown is used both in Europe and the [US](https://mutcd.fhwa.dot.gov/services/publications/fhwaop02084/) and many more places [worldwide](https://en.wikipedia.org/wiki/Traffic_sign) on traffic signs for recreational / tourism / museum destinations. That was the initial reason for using brown in this style.

**Comment by Adamant36** [comment]
@polarbearing except we are talking about gastronomy objects, not traffic signs, and I was saying in relation to that. Restaurants aren't exclusively for tourists and I wouldn't consider them a recreational thing necessarily either. So....I think what I said originally still stands.

**Comment by polarbearing** [comment]
recreation: "activity done for enjoyment when one is not working" (Oxford), thus until you are the chef, the restaurant is for recreation.

**Comment by dieterdreist** [comment]
sent from a phone

> On 14. Aug 2018, at 14:15, polarbearing <notifications@github.com> wrote:
> 
> recreation: "activity done for enjoyment when one is not working" (Oxford), thus until you are the chef, the restaurant is for recreation.
> 


we do not eat for enjoyment (alone), one has to eat, and restaurants are one of the possibilities to cater for this need

**Comment by meased** [comment]
I don't really have a problem with the current brown rendering. However, I also don't have a problem with splitting amenities into edible vs. non edible categories and coloring them differently.

I think @Adamant36 is right about going more towards yellow. Here is #c17303:
![gastro](https://user-images.githubusercontent.com/14190496/44128068-9a12e5fc-9ff5-11e8-888f-cd612c81e733.png)

**Comment by kocio-pl** [comment]
It's too light and it's harder for me to read the labels.

**Comment by Adamant36** [comment]
@meased can you test #cc6600 and like #ff9900?

**Comment by meased** [comment]
#cc6600
![cc6600](https://user-images.githubusercontent.com/14190496/44130782-fb4e9132-a003-11e8-849e-7d1d0fb839fc.png)

#ff9900
![ff9900](https://user-images.githubusercontent.com/14190496/44130783-fddf8f1e-a003-11e8-9ac8-56bfd9a88be2.png)

**Comment by meased** [comment]
The problem with going darker is that it is not very distinct from brown.
![9c7906](https://user-images.githubusercontent.com/14190496/44131025-24248c50-a005-11e8-81a5-5586d83143a3.png)

**Comment by kocio-pl** [comment]
#ff9900 is even harder to read (much too light)
#cc6600 looks the best for me - not as red-intensive as #c64803 while still perfectly readable

**Comment by Tomasz-W** [comment]
I vote for #cc6600

**Comment by Tomasz-W** [comment]
@meased Are you willing to make a PR for this issue?

**Comment by matkoniecz** [comment]
I am not sure it is worth doing. None of proposed changes seems to be improvement, at least to me.

**Comment by trigpoint** [comment]
@dieterdreist Whilst we do not eat purely for enjoyment, going to a restaurant is 100% for enjoyment. Nobody eat at a restaurant out of necessity.

**Comment by kocio-pl** [comment]
We have the whole gastronomy category, not only restaurants. Enjoyment might be first aim of amusement park, but for gastronomy first aim is eating/drinking, but there may be other aims too. And yes, I've been eating in restaurant only because I wanted to eat something (especially in journey).

**Comment by dieterdreist** [comment]
sent from a phone

> On 25. Aug 2018, at 10:29, trigpoint <notifications@github.com> wrote:
> 
> @dieterdreist Whilst we do not eat purely for enjoyment, going to a restaurant is 100% for enjoyment. Nobody eat at a restaurant out of necessity.


Perceived the whole whitecollar class is going to lunch in a restaurant every single day.

**Comment by Adamant36** [comment]
@trigpoint I eat at a restaurant out of necessity. Its the only place to eat within a few hour commute and I don't like packing a lunch because it always seem to end up either on my lap or all over the inside of my bag. Plus I tend to forget it on my way out in the morning anyway. I generally hate the food I eat at the restaurant though and the service sucks. Plus its expensive. So its not for enjoyment. there are exceptions.

**Comment by jengelh** [comment]
The new orange for gastronomy does not work too well IMO when they're located on a social campus (which is now also orange-ish rather than the yellow it used to have).
![orange](https://user-images.githubusercontent.com/8861948/45928703-3acf1300-bf48-11e8-8b96-b66cfe63e99e.png)

**Comment by Tomasz-W** [comment]
@jengelh We are working on that. See: https://github.com/gravitystorm/openstreetmap-carto/issues/1991#issuecomment-423797757
