### ISSUE TITLE
Render access=military as access=private

### ISSUE THREAD

**Issue by Penegal** [gravitystorm/openstreetmap-carto#3332]
### Expected behavior
Render `access=military` as `access=private` in order to highlight the fact that these ways are not generally accessible.

### Actual behavior
Rendered as usual, not highlighting the restriction.

I can take care of this, but, first, is this suggestion relevant?

**Comment by matkoniecz** [comment]
Can you link to the OSM wiki page documenting access=military?

**Comment by Penegal** [comment]
It seems there is none; should I create it or is this condition enough to decline the suggestion?

**Comment by kocio-pl** [comment]
The best thing is always to document usage of tags so the people know what's really available.

**Comment by matkoniecz** [comment]
> should I create it

I would strongly discussing it first on tagging mailing list - I think that access=private is preferable.

**Comment by kocio-pl** [comment]
Until the discussion gives some conclusions, I think we can close it, as this is not a rendering stage. It can be reopened later if there will be a need to discuss rendering it.
