### ISSUE TITLE
Add rendering for water slides (attraction=water_slide)

### ISSUE THREAD

**Issue by johsin18** [gravitystorm/openstreetmap-carto#3335]
### Expected behavior

Should be rendered as a path (blueish?) and an appropriate icon if mapped as a way.
Should be rendered as just the icon if mapped as a node.
The icon could be a man on a sloping line.

### Actual behavior

Not rendered at all.

### Links and screenshots illustrating the problem

Tag description:
https://wiki.openstreetmap.org/wiki/Tag:attraction%3Dwater_slide
It "suggests" to make it waterway=stream in addition, to force it being rendered, but is that a valid approach?

Example occurrence:
https://www.openstreetmap.org/#map=19/47.52249/7.56949

**Comment by kocio-pl** [comment]
I guess it should be rendered the same as a stream, but with the dark blue outline (to show similarity to swimming pool). I would probably not render nodes and icons.

Would you like to try make the code? We lack coders, so it's best to try on your own.

**Comment by matthijsmelissen** [comment]
I think this is too specific for our general purpose map.

**Comment by kocio-pl** [comment]
With generic water-like rendering I don't see the problem. It would look like swimming pool extension and won't create problem anywhere else.

**Comment by HolgerJeromin** [comment]
Our waterpark icon is similar, isnt it?

**Comment by BertMule** [comment]
Currently I have an area with 
```
area=yes
attraction=water_slide
name=water jump
tourism=attraction
```
Only the name is displayed.
I wish the icon to be displayed.

In general: please **at least** display icons in such cases.
This is so frustrating.
