### ISSUE TITLE
Name rendering issue for natural=water

### ISSUE THREAD

**Issue by Grillmannen** [gravitystorm/openstreetmap-carto#3337]
This lake has its name rendered far from its actual location: https://www.openstreetmap.org/relation/2380597

The name renders here: https://www.openstreetmap.org/relation/2380597#map=11/59.6570/12.3830

The phenomenon has been noted in other places, but I can't find any examples right now.

**Comment by kocio-pl** [comment]
This is the Mapnik error, not a style problem. It has been resolved in the code and is being currently resolved for OSM.org website by deploying new Mapnik packages, however it may take few more days. See #1465.

**Comment by kocio-pl** [comment]
This is actual rendering directly from current data and style version:

![eeq_myy](https://user-images.githubusercontent.com/5439713/43996493-f6a130e6-9dc3-11e8-8cf6-498df399f464.png)
