### ISSUE TITLE
Boundaries rendered where none exist

### ISSUE THREAD

**Issue by DENelson83** [gravitystorm/openstreetmap-carto#3338]
### Actual behavior
It seems the latest release of OSM-Carto is drawing boundaries where none exist.  If you look at the link below, it shows boundaries that do not correspond to any existing map data.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=16/49.6612/-124.9206&layers=D

**Comment by kocio-pl** [comment]
Thanks for reporting, but it looks like an old data caching issue - I have seen the problem, but after refreshing I see no additional lines:

![screenshot_2018-08-12 openstreetmap](https://user-images.githubusercontent.com/5439713/43996445-0ec0e6f4-9dc3-11e8-8406-12ba51439f80.png)

**Comment by DENelson83** [comment]
Well, refresh it again, because I am still seeing it after refreshing it myself several times.

**Comment by kocio-pl** [comment]
I still think it's data issue and refreshing doesn't tell which data version is current, so I have exported it and rendered locally - there's something strange really, but I guess problem is with data, not style:

![ytpffzfk](https://user-images.githubusercontent.com/5439713/43996584-4bceda3a-9dc6-11e8-9978-e1431f60f981.png)

**Comment by DENelson83** [comment]
Well, the problem seems to have fixed itself.  Thank you for at least noticing it.

**Comment by matkoniecz** [comment]
Turned out to be an upstream bug https://github.com/openstreetmap/osm2pgsql/issues/1394

https://lists.openstreetmap.org/pipermail/dev/2021-February/031048.html

> The error happens when there is a boundary relation containing exactly
> two ways forming a closed ring and the ways are oriented against each
> other. So they both have the same first and last nodes. The bug does
> not appear when the last node of one of the ways is the first node of
> the other. (Most likely the bug will also happen if there are four
> ways of which two create one ring and two another etc.)

> It is also possible to fix at least some of these cases by simply
> turning around one of the member ways. You can do this without the
> software having been updated. Just take care that turning around the
> way doesn't create other problems.

Once new osm2pgsql is deployed on OSM servers this bug will also disappear as boundaries are edited in general.
