### ISSUE TITLE
seamark:type=wall and barrier=dolphin not being rendered 

### ISSUE THREAD

**Issue by troelsarvin** [gravitystorm/openstreetmap-carto#3339]
I have recently edited the following area: https://www.openstreetmap.org/#map=19/55.64313/12.55271
The area includes a barrier in the water, used to guide ships properly into a lock. Previously, the barrier was tagged as a breakwater, but that was not reflecting reality, see http://troels.arvin.dk/osm/evidence/sluse_vand-ting/

After discussions in the regional mailing list and in commit comments, I have now tagged the barrier as sections with seamark:type=wall + barrier=cable_barrier[1] and sections with barrier=dolphin.
However, now nothing is redered at the default OSM map.

### Expected behavior
A series of barriers in the water should be rendered.

### Actual behavior
Nothing is rendered.

Note 1:
I'm not 100% certain that barrier=cable_barrier is actually valid, because the OSM wiki states that the barrier tag "only covers on-the-ground barriers". So this comes down to a definition of "on-the-ground". However, I thought that adding barrier=cable_barrier should not harm. In this case, I think, that carto should render a barrier (even if I had not added barrier=cable_barrier), solely because of the existance of seamark:type=wall.

**Comment by polarbearing** [comment]
barrier=cable_barrier used 223x
barrier=dolphin used 0x and is probably problematic tagging, since the dolphin is not the physical form of the barrier. 

As for seamark tags, the general style here is probably not the right place to render, there are maps specialised in this area, e.g. [openseamap](http://openseamap.org).

**Comment by troelsarvin** [comment]
I don't understand polarbearing's comment:

- What does "used 223x" mean?
- For barrier=dolphin: Does this mean that I should have marked a (narrow) area and tagged the area as "barrier=dolphin"?

**Comment by dieterdreist** [comment]
sent from a phone

> On 12. Aug 2018, at 18:04, Troels Arvin <notifications@github.com> wrote:
> 
> I don't understand polarbearing's comment:
> 
> What does "used 223x" mean?
> For barrier=dolphin: Does this mean that I should have marked a (narrow) area and tagged the area as "barrier=dolphin"?



you should discuss tagging related questions on the tagging ml, this is the issue tracker for the main rendering style.
I agree barrier=dolphin, in the context of the established other values for the “barrier” key, suggests a dolphin is the barrier, which is likely nonsense.

Used 223 times on the whole planet means that it is not established and will likely not be rendered at the moment

**Comment by polarbearing** [comment]
@troelsarvin, you are not doing anything wrong. 

"barrier=dolphin used 0x" - according to [Taginfo](https://taginfo.openstreetmap.org/tags/barrier=dolphin) it does not exist in the database. This is the first reference people discussing the style here look to see how relevant the tag is to others. It is updated over night, so in case you have added some today it will be counted tomorrow. Still, a special-interest feature is unlikely to be rendered in the general style here.

The tagging problem is that for the key barrier=* the values are the physical structure, such as block or wall, not the animal they are trying to restrain.

**Comment by mikini** [comment]
@polarbearing the tagging issue was discussed on [talk-dk](https://lists.openstreetmap.org/pipermail/talk-dk/2018-August/005096.html) but I think there are multiple confusions involved both there and here.

1) Specific types of man-made sea structures exists that are referred to as "dolphin", it has nothing to do with a marine animal.

Refer to:

 * https://en.m.wikipedia.org/wiki/Dolphin_(structure)
 * https://www.engineeringcivil.com/what-is-the-difference-between-breasting-dolphin-and-mooring-dolphin.html
 * http://nsccme.com/solutions/marine-works/dolphin-structures/
 * https://oceanandairtechnology.wordpress.com/2013/05/11/dolphins-mooring-breasting-berthing/

2) @troelsarvin neither used the talk-dk suggested, albeit proposed status but rather commonly used ([8712 uses](https://taginfo.openstreetmap.org/tags/man_made=dolphin)), [man_made=dolphin](https://wiki.openstreetmap.org/wiki/Proposed_features/Dolphin) tag or the more established [seamark:mooring:category=dolphin](https://wiki.openstreetmap.org/wiki/Seamarks/Moorings#Categories) ([20895 uses](https://taginfo.openstreetmap.org/tags/seamark:mooring:category=dolphin), [example](https://www.openstreetmap.org/node/4637137001)) tag. Instead he made [a first use](https://www.openstreetmap.org/way/616147454) (still [0 uses](https://taginfo.openstreetmap.org/tags/barrier=dolphin)) of the term in a [barrier](https://wiki.openstreetmap.org/wiki/Key:barrier) tag.

To me the barrier use also seem misguided as I can't imagine any definition of  "on-the-ground barriers" in a 2d geo context that includes objects separated from landmass by water.

Whether man_made=dolphin or select seamark: objects like mooring:category=dolphin should be rendered in Carto is more of a political question. In my apparent stance I'd lean towards that objects in coastal vicincity like mooring structures is a good guidance for mappers.

**Comment by polarbearing** [comment]
Thanks @mikini for the clarifications. So barrier=dolphin was poorly chosen as first it is not a barrier but a mooring point, and second established tagging exists. 

For seamark:*=* tags I still recommend not to render them in this style, as they are special interest and have their place in _openseamap_. Once such seamarks are significant structures that are perceived by the general audience, they should be tagged with appropriate man_made=* values (in addition), and could be rendered. We do render _man_made=pier_, so why not _man_made=dolphin_.

**Comment by kocio-pl** [comment]
Wiki page should be filled with de facto meaning, and then it can be rendered IMO, since it's quite popular.

**Comment by polarbearing** [comment]
@kocio-pl - why the barrier label, when it is about man_made=dolphin ?
Probably we should have two new tickets, 
* man_made=dolphin (8k+), which could be rendered as a symbol in the same colour as man_made=pier, maybe a dot, triangle or square.
* barrier=cable_barrier if the 223x are important enough, added as value to the linear barriers that render as a line.

**Comment by troelsarvin** [comment]
Cases 3343 and 3344 were spawned from this case, per the suggestion from @polarbearing
Consequently, this case will be closed now.
