### ISSUE TITLE
man_made=dolphin should be rendered

### ISSUE THREAD

**Issue by troelsarvin** [gravitystorm/openstreetmap-carto#3343]
I have recently edited the following area: [https://www.openstreetmap.org/#map=19/55.64313/12.55271](https://www.openstreetmap.org/#map=19/55.64313/12.55271)
The area includes a structure in the water, used to guide ships properly into a lock. Previously, the structure were tagged as a breakwater, but that was not reflecting reality, see fotos at [http://troels.arvin.dk/osm/evidence/sluse_vand-ting/](http://troels.arvin.dk/osm/evidence/sluse_vand-ting/)

After discussions in the regional mailing list, commit comments, and github discussions, I have now tagged parts of the structure as sections with man_made=dolphin (and material=wood).

However, now nothing is redered at the default OSM map.

I suggest that man_made=dolphin be rendered like man_made=pier. In case 3339 (which this case was spawned from), @polarbearing has a more detailed suggestion.

**Comment by polarbearing** [comment]
Fine. May I suggest do clean your post from all references to barriers, which is confusing in this case, and focus on the man_made dolphins? As I understand, these are mooring points, and not barriers?

**Comment by troelsarvin** [comment]
@polarbearing : The post has been updated, removing use of the word "barrier".

**Comment by polarbearing** [comment]
It seems we currently do not render man_made=pier on a node, which is used 5.6k.
On the other hand, man_made=dolphin is used predominately on nodes (8.7k, just 26 ways).

Thus we should fix this on-the-go, pier rendering on nodes and making dolphins the same. 

pier on a line is currently rendered ```line-width: 0.5; line-color: @land-color; line-cap: square;```, thus my suggestion would be to have a square 0.5 for the nodes.

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Aug 2018, at 12:04, polarbearing <notifications@github.com> wrote:
> 
> It seems we currently do not render man_made=pier on a node, which is used 5.6k.


seems correct. We also don’t render highway=motorway on a node, do we? 
-1 to supporting piers as nodes

**Comment by polarbearing** [comment]
We do render supermarkets on a node, which are larger than a small pier.

**Comment by polarbearing** [comment]
Thanks, the architectural perspective is convincing. The wiki definition already excluded nodes, that has been emphasized now as a tagging mistake. 

Thus the code for the dolphin needs to be different. What about the light grey colour from 'parking' for the pier+dolphin?

**Comment by Tomasz-W** [comment]
What about rendering it in the same way as bollards?
