### ISSUE TITLE
seamark:type=wall should be rendered

### ISSUE THREAD

**Issue by troelsarvin** [gravitystorm/openstreetmap-carto#3344]
I have recently edited the following area: [https://www.openstreetmap.org/#map=19/55.64313/12.55271](https://www.openstreetmap.org/#map=19/55.64313/12.55271)
The area includes a barrier in the water, used to guide ships properly into a lock. Previously, the barrier was tagged as a breakwater, but that was not reflecting reality, see fotos at [http://troels.arvin.dk/osm/evidence/sluse_vand-ting/](http://troels.arvin.dk/osm/evidence/sluse_vand-ting/)

After discussions in the regional mailing list, and in commit comments, I have now tagged parts of the barrier as sections with

 - barrier=cable_barrier [1], combined with
 - seamark:type=wall

However, now nothing is redered at the default OSM map.

I suggest that seamark:type=wall be rendered like a line. In case 3339 (which this case was spawned from), @polarbearing has a more detailed suggestion.

Note 1:
I'm not 100% certain that barrier=cable_barrier is actually valid, because the OSM wiki states that the barrier tag "only covers on-the-ground barriers". So this comes down to a definition of "on-the-ground". However, I thought that adding barrier=cable_barrier should not harm. In this case, I think, that carto should render a barrier (even if I had not added barrier=cable_barrier), solely because of the existance of seamark:type=wall.

**Comment by polarbearing** [comment]
I did not find the phrase "on-the-ground" on [this wiki page](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcable_barrier)? 

Personally I see no difference (for tagging purposes) between the cable mounted on posts or floatation devices (and probably anchored to the sea-ground). You might discuss that on the tagging list to clarify the definition. , or just use it this way. tagging list.

I don't see a need to consider the seamark:*=* tag, just rendering the barrier value as a line should be fine.

**Comment by Adamant36** [comment]
I kind of agree with polarbearing on this. Its technically on the ground, just under the water. So maybe it should be just mapped as a plain barrier line and have layer=-1 on it, like for other covered features. Especially since seamark:type=wall only has 38 uses according to Taginfo.

**Comment by matkoniecz** [comment]
> OSM wiki states that the barrier tag "only covers on-the-ground barriers"

Note that while useful OSM wiki is frequently wrong - especially in cases where it attempts to describe how specific keys are used. Feel free to check whatever given info makes sense and change it in cases where OSM wiki and real editing mismatch.

In more controversial or complicated cases it is a good idea to mention it on tagging mailing list, in very controversial situation it makes sense to do it before editing wiki.

--------

I am opposed to rendering extremely rare tags - and with 38 usages worldwide ( https://taginfo.openstreetmap.org/tags/seamark%3Atype=wall ) I suspect that more time was spend on discussing this issue than on mapping them.

--------

In addition I am highly opposed to seamark:*=* tagging scheme that tends to duplicate normal tagging.

--------

barrier=cable_barrier seems to be much better candidate for rendering, though I would wait until usage grows a bit ( https://taginfo.openstreetmap.org/tags/barrier=cable_barrier - 227 worldwide is quite low ).

**Comment by Tomasz-W** [comment]
@kocio-pl As this tag has extremely low usage (38) and tagging it is not clear, I propose to close this issue.
