### ISSUE TITLE
waterway=stream with location=underground should render differently

### ISSUE THREAD

**Issue by WinterB1860** [gravitystorm/openstreetmap-carto#3349]
At the moment streams render the same no matter if their location is set to be underground. While it is useful to know the flow of water it would mislead you on where the water is accessible.

On topographic maps they make the distinction with a dashed/dotted line. I believe mimicking this with a similar style would be sufficient in allowing map readers to recognize where it's an above ground stream and where it is underground and inaccessible.

**Comment by kocio-pl** [comment]
Do you mean something like stream in the tunnel?: 

https://www.openstreetmap.org/way/175350836

**Comment by WinterB1860** [comment]
Kocio-pl

More like if a stream naturally ends into the ground but the waterflow is known to keep going down a path until it re-appears again. In areas without much development to have man-made tunnels it would be useful to know where the water sources are, and where they lead.

In more urban environments where there is a dedicated tunnel for the stream itself beyond just going below the city I believe similar markings would probably be useful albeit rarely needed

**Comment by Tomasz-W** [comment]
I think that correctly tagged examples from post above should be `waterway=stream` + `tunnel=yes` or `tunnel=culvert`, and these combinations are rendered differently at the moment.

**Comment by matkoniecz** [comment]
tunnel tagging is supported and AFAIK is standard, correct tagging.

**Comment by WinterB1860** [comment]
Using tunnel=yes on a natural underground water flow would be applying an incorrect tag as it would not have a man-made tunnel or necessarily even have a natural tunnel/cave to be found. All the documentation for that sort of feature where there's no tunnel recommends the location=underground tag.

If tunnel=yes for waterways render differently to show it's underground then I would assume the generic and more applicable location=underground tag should render the same/similar

**Comment by imagico** [comment]
Natural underground water flow that is not a tunneled section of a river or stream is rarely practically verifiable and rarely continuous free surface flow.  And in the few exceptions there is no consensus this should be mapped with waterway=stream/waterway=river and if it is it does not make much sense to render it in a general purpose map.

**Comment by WinterB1860** [comment]
I believe that even semi-accurate topographic approximations about the flow and underground status of sections of waterways would be useful for a general purpose map if you're hiking in the woods and come across a change in the landscape where the previously designated section should be marked above ground, as many of the designations from topographic maps in rural areas are not updated as frequently as other areas where there is more affordability in keeping up to date on the status of a feature or have higher quality aerial photos. Knowing that it is known that water flows through that area as a waterway path means they can assume that the old approximated information is meant to be what they discovered/verified, as well as prepares you for a potential obstacle/resource when traversing the wild.

Looking at the wiki they only really describe waterways in caves or natural pressurized siphons, neither of which seem to fit other types of natural underground flow. (with the waterway=pressurized tag not rendering at all)


Even if there is no consensus on how these specific sort of paths should be rendered, I believe that with the location=underground tag to indicate a generic underground status on rendered waterways that it would be more informative to render as a generic single dotted line indication unless specified (eg tunnel/culvert.). If you believe that it would not be useful information to have to render then it would have to just stop rendering sections with the tag entirely, or have landcover areas render over them in priority due to location=underground indicating they should be below as they currently render the same as normal waterway=stream paths.

I initially assumed with how encouraging the wiki was about for using the location=underground tag that when mapping my local town's area they wouldn't show up much like the waterway=brook tag, and when they did I assumed the landcover areas would render over them; however, if we should change how it renders I believe the most informative method would be best, as there are similar methods for more definitive features already.

**Comment by jeisenbe** [comment]
@imagico, should we stop rendering waterways with `location=underground`, or continue to ignore this tag?

**Comment by imagico** [comment]
I would like to see examples of cases of natural underground water flow that is not a tunneled section of a river or stream where this is mapped in a correct form and not just as an abstract virtual connection between above ground start and end points.

**Comment by jeisenbe** [comment]
I think it's very unlikely we will find many examples mapped like that.

Assuming that almost all of the examples are going to be abstract or
virtual connections, how should we handle this?

Render as a normal stream/river, or not render?

**Comment by imagico** [comment]
I don't think we should add special consideration for a tagging that is not currently used correctly - even if that special consideration is not rendering it at all.

But i would like to give @WinterB1860 the opportunity to point to some examples - since the suggestion is made to render this in a distinct form it seems likely that they had in mind something that would be useful to render and that is certainly not an abstract strait point-to-point connection.

**Comment by jeisenbe** [comment]
I checked overpass-turbo: 

- Rivers: [79 ways](https://overpass-turbo.eu/s/M6I) with  `waterway=river` + `location=underground` without `tunnel` or `man_made`. There are 114 with `tunnel` or `man_made=pipeline`. Most (44) have only 2 nodes. Many are in Japan, imported from "National-Land Numerical Information (River) 2006, MLIT Japan", eg: [way 680546332](https://www.openstreetmap.org/way/680546332) and [way 83414929](https://www.openstreetmap.org/way/83414929)
Full query: https://overpass-turbo.eu/s/M6R

- Streams: [460 ways](https://overpass-turbo.eu/s/M6T) with `waterway=stream` (+ `location=underground` and not `tunnel` or `man_made`). The main concentrations are eastern Canada (some with source "NRCan-CanVec-7.0") and Japan, though there are a few clusters in Spain, France and Germany, and a few qanats in North Africa (which should be waterway=canal with tunnel=yes?) 

Examples: [way 26219994](https://www.openstreetmap.org/way/26219994), [way 432752495](https://www.openstreetmap.org/way/432752495) and [way 541642501 ](https://www.openstreetmap.org/way/541642501)

- Canal: 93 ways - https://overpass-turbo.eu/s/M6X

JOSM does not currently support this tagging, and I believe it's not supported by iD either.

**Comment by imagico** [comment]
Thanks.  While there are a few places where this seems sensible tagging most of this is just wrong.  I would definitely say better to keep the current rendering (show these like normal streams) than to explicitly not show them and there is way too little consistent use of this tagging to warrant rendering in a distinct form.
