### ISSUE TITLE
Render bus guideways underneath highway bridges

### ISSUE THREAD

**Issue by BjornRasmussen** [gravitystorm/openstreetmap-carto#3359]
Bus guideways currently render above highway bridges creating confusing and incorrect rendering.
![map 11](https://user-images.githubusercontent.com/37753777/44499670-f273bb00-a652-11e8-9818-709554e999f9.png)
https://www.openstreetmap.org/way/381661497

**Comment by kocio-pl** [comment]
We need coders willing to look at this. Would you like to try?

**Comment by HolgerJeromin** [comment]
Dupe of #2489

**Comment by jeisenbe** [comment]
Closed as duplicate of #2489, please discuss further there.
