### ISSUE TITLE
Pixel aligning some icons

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3362]
Some of icons which I have designed at the beginning of my activity here, was not pixel-aligned, but we have added them anyway. Now I fixed them and reuploaded to Gist. 
I also propose to make a line in `amenity=atm` icon thinner to make it less prominent.

_(Current icon on the left, fixed icon(s) on the right)_

* `historic=wayside_shrine`
![historic wayside_shrine0](https://user-images.githubusercontent.com/25656654/44543385-b2bed900-a70f-11e8-840f-004271ba7811.png) ![historic wayside_shrine](https://user-images.githubusercontent.com/25656654/44543384-b2bed900-a70f-11e8-9045-ec36135e9bbd.png) 
Gist: https://gist.github.com/Tomasz-W/e237875a860653546d553cacd4d8afbd
* `amenity=bbq`
![amenity bbq0](https://user-images.githubusercontent.com/25656654/44543383-b2264280-a70f-11e8-8706-8a4a5f929ae3.png) ![amenity bbq](https://user-images.githubusercontent.com/25656654/44543382-b2264280-a70f-11e8-8b6b-7fdb61e18e40.png)
Gist: https://gist.github.com/Tomasz-W/4ff000df11e004abf24d5e77f5b8db62
* `information=audioguide`
![information audioguide0](https://user-images.githubusercontent.com/25656654/44543387-b2bed900-a70f-11e8-8863-8af3901c33dc.png) ![information audioguide](https://user-images.githubusercontent.com/25656654/44543386-b2bed900-a70f-11e8-9f70-1817306d737a.png)
Gist: https://gist.github.com/Tomasz-W/c1b01647b8979e88b14d3dee6fcb3138
* `information=board` [I prefer thin version]
![information board0](https://user-images.githubusercontent.com/25656654/44543389-b2bed900-a70f-11e8-974e-22caaea0cdf1.png) ![information board3](https://user-images.githubusercontent.com/25656654/44544135-b5bac900-a711-11e8-9a83-9d663c3565cf.png) ![information board2](https://user-images.githubusercontent.com/25656654/44543390-b3576f80-a70f-11e8-9981-c3914208d8c9.png)
Gist: https://gist.github.com/Tomasz-W/d6f962425fbc8ec05b54a696e7eaee66
* `information=map`
![information map0](https://user-images.githubusercontent.com/25656654/44543392-b3576f80-a70f-11e8-8039-3117d35f221a.png) ![information map](https://user-images.githubusercontent.com/25656654/44543391-b3576f80-a70f-11e8-845a-0b1a93f264f1.png)
Gist: https://gist.github.com/Tomasz-W/1e8f2e4a59069ddee99db53ac1a5c1dc
* `shop=ticket`
![shop ticket0](https://user-images.githubusercontent.com/25656654/44543394-b3f00600-a70f-11e8-8a67-25043a573f5e.png) ![shop ticket](https://user-images.githubusercontent.com/25656654/44543393-b3576f80-a70f-11e8-9d60-4fd9c17a0db3.png)
Gist: https://gist.github.com/Tomasz-W/b18eee2375829d1fa2e97f40fd855968
* `tower:type=bell_tower`
![tower_type bell_tower0](https://user-images.githubusercontent.com/25656654/44543396-b3f00600-a70f-11e8-8807-57e71b92ec4a.png) ![tower_type bell_tower](https://user-images.githubusercontent.com/25656654/44543395-b3f00600-a70f-11e8-829b-1ac9ad3b18f3.png)
Gist: https://gist.github.com/Tomasz-W/18d5cac547924610245808723dd61319

* `amenity=atm`
![amenity atm0](https://user-images.githubusercontent.com/25656654/44545297-f9fb9880-a714-11e8-8f2c-525fc06becfe.png) ![amenity atm](https://user-images.githubusercontent.com/25656654/44545303-fe27b600-a714-11e8-9a7f-242137c3b340.png)
Gist: https://gist.github.com/Tomasz-W/bcb011d2e8785553241f63121adf307d

**Comment by meased** [comment]
:+1: 

Other icons in need of alignment that have been on my radar are:

- `tourism=motel`
- `amenity=car_rental`
- `amenity=bicycle_rental`
- `shop=car_repair`
- `shop=car`
- `amenity=car_wash`

**Comment by Tomasz-W** [comment]
@meased I've checked icons which you have mentioned, most of them was mostly pixel-aligned (it's impossible to do a full pixel-aligning, because it's not a Minecraft ;) ). As hotel icon was not pixel aligned, and other accomodation types has copied bed shape from this icon, I fixed them all:

* `tourism=apartament`
![apartament](https://user-images.githubusercontent.com/25656654/44617870-b10a2800-a86b-11e8-8aaa-0292a0562bae.png) ![pobrany plik apartament](https://user-images.githubusercontent.com/25656654/44617872-b6677280-a86b-11e8-8b5e-ab27ea48dc0b.png)
* `tourism=guest_house`
![guest house](https://user-images.githubusercontent.com/25656654/44617876-c4b58e80-a86b-11e8-918e-26b1dbf49b38.png) ![pobrany plik guest house](https://user-images.githubusercontent.com/25656654/44617878-c8e1ac00-a86b-11e8-9ded-b8c741e5d9b8.png)
* `tourism=hostel`
![hostel](https://user-images.githubusercontent.com/25656654/44617881-d4cd6e00-a86b-11e8-8ea4-558e7d1aa676.png) ![pobrany plik hostel](https://user-images.githubusercontent.com/25656654/44617884-d9922200-a86b-11e8-92f8-a7af50f7b62f.png)
* `tourism=hotel`
![hotel](https://user-images.githubusercontent.com/25656654/44617887-e4e54d80-a86b-11e8-8df1-f7706d4962ab.png) ![pobrany plik hotel](https://user-images.githubusercontent.com/25656654/44617888-e7e03e00-a86b-11e8-98cd-60c519853810.png)
* `tourism=motel`
![motel](https://user-images.githubusercontent.com/25656654/44617895-f6c6f080-a86b-11e8-8159-935633e6dab3.png) ![clean svg tourism motel](https://user-images.githubusercontent.com/25656654/44617896-fa5a7780-a86b-11e8-98ce-60d6ac41d449.png)

Gist link: https://gist.github.com/Tomasz-W/7b26018d9224f3c53b033e28a568a724

@kocio-pl Do you agree that pixel aligned version of all icons are better? Which one of `information=board` do you prefer?

@Adamant36 It's would be rather easy PR to do, because it's only icon files change. Would you like to take care of it?

**Comment by lakedistrictOSM** [comment]
@Tomasz-W The thin version of the info board is better.

**Comment by kocio-pl** [comment]
I also like the thin version of the info board. I would like to see rendering especially of wayside_shrine and atm to know the difference. It's good to remember that post box has the same slot shape, so maybe it should be tweaked too.

**Comment by Adamant36** [comment]
Sure. I'll do it after the other PRs I'm working on get done and the icons get figured out.

**Comment by Tomasz-W** [comment]
@kocio-pl Post box hava a similar slot shape (round corners), but it's a 1px wide, so difference between proposed atm icon (with sharp corners) would be unvisible in this part.

**Comment by kocio-pl** [comment]
I prefer clear symbol (which sometimes is not 1:1 to reality) than trying to be correct but too complex and not clear.

**Comment by meased** [comment]
Agree with @kocio-pl. Icons are symbolic, not miniature depictions of real life.

**Comment by Tomasz-W** [comment]
@kocio-pl What do you think about current `amenity=atm` zoom level (17)? I think it's too early for such a small feature, and it should be moved higher, maybe even to only z19, but as I don't have payment card I might be wrong.

**Comment by kocio-pl** [comment]
I agree. It has nothing to do with payment card, it's about showing things according to their size:

https://www.openstreetmap.org/user/kocio/diary/44852

**Comment by kocio-pl** [comment]
What are your arguments and (more important) what's your proposition?

**Comment by Adamant36** [comment]
@Tomasz-W, is this ready to go? Good job btw. The new icons look way better.

**Comment by polarbearing** [comment]
Good effort! Should we consider #3393 here already (cleaning metadata)?
