### ISSUE TITLE
power=generator + generator:source=wind should be rendered (I guess..)?

### ISSUE THREAD

**Issue by spithost** [gravitystorm/openstreetmap-carto#3363]
In the Netherlands there are quite some wind-generators placed with their base in the water and are "thus" an obstruction for sailors, comparable to dams and piers. 

I use (parts) of this project to render OSM-data on a tileserver to produce watercharts and miss the bases of these wind-generators. The piers and dams etc are defined in water-features.mss, the wind-generators are not.

As I'm just a user of (parts) of this project, I'm not sure what to add where and how... 
Maybe not only an .mss-file has to be changed but also one or more queries in project.mml?

**Comment by polarbearing** [comment]
amenity-points.mss has 
```
[feature = 'power_generator']['generator:source' = 'wind'],
  [feature = 'power_generator'][power_source = 'wind'] {
    [zoom >= 15] {
marker-file: url('symbols/power_wind.svg'); etc
```

**Comment by Tomasz-W** [comment]
It's already renderd: https://www.openstreetmap.org/node/3264516667
Please close the issue.
