### ISSUE TITLE
Add icon for highway=stop

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3366]
I did a search and didn't see an issue for it already. It could rendered like barriers on roads. As a node with a little stop sign icon. I see at is a temporary "social" barrier. There are currently 453,026 uses of it.

**Comment by kocio-pl** [comment]
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop

I'm not sure that road signs are good idea here, even on z19+, because they are too small and road-related. Could you explain what do you mean with "social" barrier and why it would be useful on the map?

**Comment by Adamant36** [comment]
Yeah I was thinking that. I was hopping at least the nodes behind roads would work. It might be to much if its that and stop signs etc though. But it would be cool if adding the icon coupd incuraged mapping them though. Since it seems like they arent mapped nearly as much as they could be. It might be good to incurage them being mapped more for routing to. I dont know if they are factored in for routing times in any apps, but they might be. So the more the better. 

By social barrier I just mean something that temporarily impedes forward movement along a route, but isnt a physical barrier like a gate or speed hump. Its more of a socially agreed on one instead.

Are most road related things generally not added? Because I was thinking of also doing an issue for traffic_calming=bump/hump.

**Comment by kocio-pl** [comment]
This is not a road style, even less car style and I don't think we should push it any further. Road code is already the biggest part of OSM Carto, if I remember correctly. Probably the only big thing left, which is worth rendering in my opinion, is #110.

**Comment by polarbearing** [comment]
OSM data contain many tags that are useful for different purposed than rendering a map. The stop positions are evaluated by routers and navigation systems.

**Comment by matkoniecz** [comment]
Stop signs are something used by routers and may be displayed in highly specialized styles or in editors.

I am pretty sure that displaying this kind of data in general purpose map is not feasible, especially in map displayed as static images.
