### ISSUE TITLE
Add icon for made_made=surveillance

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3367]
I suggest we add an icon for man_made=surveillance. It currently has 65 ,440 uses. There was not issue already created for it that I could find. Although it is mentioned in issues #2556 and #1519.

**Comment by kocio-pl** [comment]
The same problem for me as with road signs - they are too small. Moreover there are special maps to show them:

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurveillance#Rendering

**Comment by Adamant36** [comment]
Hhmm I could see that. I guess it would depend on the of camera mount. camera:mount=pole has 12,313 uses and camera:mount=mast has 103. Those where the types I was thinking of. They make up obstacles sometimes. I guess I could of been more specific in my request.

**Comment by kocio-pl** [comment]
This is why I suggested rendering street lamps just like bollards, see https://github.com/gravitystorm/openstreetmap-carto/issues/3277#issuecomment-401120975. I think we might render all such objects this way.

**Comment by Adamant36** [comment]
I agree with your suggestion there about street lamps. Maybe it can be revived somehow and this can be added to it, along with other similar objects.

**Comment by Tomasz-W** [comment]
On the one hand icon is too much for such a small and not important object, and on the other hand rendering it as a dot would be not understandable. I wouldn't add any rendering for this feature.

**Comment by Adamant36** [comment]
@Tomasz-W, look at pictures of CCTV camera polls on Google images. Some of them are the size of street lamps or signal polls. They are bigger then bollards and those are rendered.

**Comment by polarbearing** [comment]
Agree with @dieterdreist - looking from the other end, we render ```barrier_bollard, barrier_block, barrier_log``` with the same small grey dot. Including lamp posts and cameras the same as a block or a log makes the barriers meaningless.

**Comment by Adamant36** [comment]
@polarbearing, they are still barriers though. You cant drive through them. Also, I dont know about other places, but where I live a lot of lamp posts are in the middle of the sidewalk and have to maneuvered around. Which makes them barriers. Not to mention some light poles are the wooden minor power pole type. There is even mixed use ones that are both power poles and light poles. It seems inconsistent to render the power poles as a geographical feature but not light poles when they are essentially the same thing visually/spatially in the real world.

**Comment by polarbearing** [comment]
Any object can be an obstacle. A bench, a waste bin, an advertising column, though we should keep them separate from barriers, that are there for this purpose only. If you render street lamps, they should be distinguishable from bollards, other wise you just clutter the map with grey dots. 

For the intentional obstacles: When you had just lightweight bollards in the past to enforce that you should not drive a cycleway with the car (by the penalty of damaging your own vehicle), you get now more and more massive concrete barriers added to pedestrian areas etc, to massively prevent attackers to intentionally run over the people there. 

Thus, please don't throw barriers (on the way or loose) and other infrastructure into the same soup.

**Comment by Tomasz-W** [comment]
I think this issue can be closed as kind of 'wontfix', because:
* any object-shape-like icon would be too prominent for such a small and not so common-useful feature
* any universal icon (dot/ square etc.) won't be saying that is a cctv camera

**Comment by Adamant36** [comment]
Might as well. It seems like it was died on arrival anyway. At least it saves someone else from suggesting it later on though if nothing else.

**Comment by Tomasz-W** [comment]
@kocio-pl Please close this issue for the reasons above, and also because even user who opened the issue admitted that it might be too problematic.
