### ISSUE TITLE
Render leisure=amusement_arcade

### ISSUE THREAD

**Issue by meased** [gravitystorm/openstreetmap-carto#3371]
[1082 uses](https://taginfo.openstreetmap.org/tags/leisure=amusement_arcade#map)

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Damusement_arcade

Generally a fairly large venue that is not currently rendered.

Rendering ideas (I suppose it would probably be green):

- Just a dot + text
- Space invader monster (vary it to avoid copyright issues?)
![spaceinvader](https://user-images.githubusercontent.com/14190496/44863623-7b31be80-ac32-11e8-81b0-939a2ae4c76c.png)

**Comment by kocio-pl** [comment]
Nice! :smile:  Could you show 14 px version of it?

![taghistory 31](https://user-images.githubusercontent.com/5439713/44864878-05a10f00-ac81-11e8-83e2-491d731821eb.png)

**Comment by HolgerJeromin** [comment]
I dont think the monster (even pacman) would work for normal users

**Comment by polarbearing** [comment]
Do you say we are not normal?  :-)

**Comment by dieterdreist** [comment]
sent from a phone

> On 30. Aug 2018, at 20:30, meased <notifications@github.com> wrote:
> 
> is this recognizable to non-nerds?


IMHO yes, spaceinvaders are common knowledge :)
pac man seems more friendly than a „monster“.

**Comment by meased** [comment]
A "pixelated monster" _could_ be somewhat generic, but pac man is obviously a direct reference to the PacMan™ franchise and is most definitely heavily copyrighted and unusable for us.

**Comment by Tomasz-W** [comment]
As these places are full of non-display machines, I think that proposed symbol may be confusing, because it's closely related to video games. 

https://www.google.pl/search?q=amusement+arcade&client=opera&hs=Rji&source=lnms&tbm=isch&sa=X&ved=0ahUKEwipj7-tppndAhUJ1ywKHZQrDOMQ_AUICygC&biw=1920&bih=977

I can try with arcade/ toy-grab machine icon or pinball icon. What do you think?

**Comment by Tomasz-W** [comment]
@dieterdreist Images in link which I've added proves that sometimes (maybe even usually) there could be lack of display-machines in these centres.

**Comment by meased** [comment]
An icon should symbolically represent a class. It does not have to be an actual representation of the exact types of machines preset at a venue. It just has to give the average map reader the impression that the venue is an arcade.

That being said, I'm okay with other icon designs, but I think some of them may be difficult (or impossible) to fit into 14x14.

> there could be lack of display-machines in these centres

The trend seems to be that as home consoles have gotten so good, arcades focus more on physical games. It is still quite common to use antiquated objects as icons (phone icons are often rotary phones, the save icon on a computer is still a floppy disk).

**Comment by polarbearing** [comment]
I agree with Tomasz-W that a mechanical machine might be more representative, among them pinball or a one-armed bandit ("fruit machine") might be the most classical. Pinball might be easier in 14sq.
