### ISSUE TITLE
Render amenity=vehicle_inspection

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3378]
This is a growing tag closing to 2k limit and has a wiki page. I think that icon should be brown and contain car, probably with a seal of approval.

https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dvehicle_inspection

![taghistory 38](https://user-images.githubusercontent.com/5439713/44955142-ea1b4b80-aeae-11e8-9a4a-c4da67b32fb7.png)

**Comment by kocio-pl** [comment]
And what about magnifying glass instead?

**Comment by Tomasz-W** [comment]
I don't think it would match this tag, because a magnifying glass is a symbol of searching for something, while vehicle inspection stations are about checking certain vehicle parts from the list.

Gist link: https://gist.github.com/Tomasz-W/b75ee9d6fa76bc9c238dab76f4136f72

**Comment by kocio-pl** [comment]
Well, that's why it's called inspection - they're looking for possible problems according to the list, so both symbols are good for me and one might just look better than the other one.
