### ISSUE TITLE
Shape files not rendering? Land appears as water.

### ISSUE THREAD

**Issue by joaojoyce** [gravitystorm/openstreetmap-carto#3379]
Not sure if this is an openstreetmap-carto problem or a mapnik problem. Can you please help me out?

### Expected behavior
Land should appear as land-color (#f2efe9) but it's showing as water (#aad3df) Please see image [1]

### Actual behavior
Some or all land is appearing as water color. Please see image [2]. It looks like mapnik is not rendering the shape files but I'm not sure if that's the case. Shape files were downloaded with the scripts/get-shapefiles.py script.

Map is being rendered with the following python script:

``````
#!/usr/bin/python
from mapnik import *
m = Map(6000,3000)

load_map(m, "/mnt/openstreetmap-db/openstreetmap-carto/mapnik.xml")
bbox=(Box2d(-1018220.0424,4678930.2578,-1015162.5613,4680559.3220))
m.zoom_to_box(bbox)

render_to_file(m,'world.png', 'png')
print("rendered image to world.png")

``````
Carto: Version 1.1.0
Mapnik: Version 3.1.0

I've followed the instructions for importing the data with osm2pgsql. The data used was a full planet from geofabrik (from the individual continent files, merged with osmosis).

### Links and screenshots illustrating the problem
[1] ![screen shot 2018-09-03 at 01 06 41](https://user-images.githubusercontent.com/5451182/44962273-a7408e80-af15-11e8-9f9d-9d42a9320177.jpg)

[2] ![world](https://user-images.githubusercontent.com/5451182/44962264-7f512b00-af15-11e8-8fc8-2427199d87fb.png)

**Comment by kocio-pl** [comment]
Could you try with Kosmtik and http://download.geofabrik.de/europe/portugal-latest.osm.pbf for direct comparison? I did it and it works properly. I also use Mapnik 3.0.20, 3.1.0 is not finished yet.

**Comment by mosrosem** [comment]
As @kocio-pl said, Kosmtik works. https://github.com/kosmtik/kosmtik, and I also recommend using the v3.0.x branches, which are more stable.

**Comment by joaojoyce** [comment]
Tried to clean up and install mapnik and python-mapnik from the 3.0.x branch. Still no luck.

Here is the generated mapnik.xml (zip compressed as required by GitHub).

Can you confirm, by looking at the pictures, that this is an issue with the shape files and not with the database import? I've tried to clean the mapnik.xml and remove any postgreSQL datasource and my 
images are all blue. No shapes found.

Sorry about all the questioning, just spent 31 hours importing the data to postgres. I'm just hoping everything is ok on that side....
[mapnik.xml.zip](https://github.com/gravitystorm/openstreetmap-carto/files/2344908/mapnik.xml.zip)

**Comment by kocio-pl** [comment]
This looks like something with data, not style, but I have downloaded new shapes yesterday and this was still OK, so I don't know where exactly the problem is.
