### ISSUE TITLE
OSM doesnt show me characters on the first level

### ISSUE THREAD

**Issue by esamrui** [gravitystorm/openstreetmap-carto#3380]
### Expected behavior
My OSM is using Chinese characters, i have uploaded Taiwan map . After configure OSM to use Chinese characters i see themin correct way so, it is not my issue but .....

### Actual behavior
Characters are being used and load ok, but when i see the map in the first zoom, i don't see the name of country or regions ( I see the typical square as when you don't use correct characters ). If i zoom until street level i'm able to see street name in Chinese without problem.

### Possible Solution
I think the problem is coming form render configuration , something about zoom  or load but i have just started to work with render and I'm a little bit lose :) .

**Comment by sommerluk** [comment]
Could you post a screenshot?

Are you using the website at openstreetmap.org or a an app on your smartphone that is based on OSM?

**Comment by HolgerJeromin** [comment]
Probably http://help.openstreetmap.org is the better place.

**Comment by dieterdreist** [comment]
sent from a phone

> On 4. Sep 2018, at 17:07, esamrui <notifications@github.com> wrote:
> 
> i don't see the name of country or regions ( I see the typical square as when you don't use correct characters ). If i zoom until street level i'm able to see street name in Chinese without problem.


I guess you are missing a font, country names is a different font than street names.

**Comment by SomeoneElseOSM** [comment]
Does https://switch2osm.org/manually-building-a-tile-server-18-04-lts/ help?  There's a section in there about which fonts you might want to install.  The actual fonts may vary depending on the OS you're using.

**Comment by kocio-pl** [comment]
Did you look at this section of our installation guide?

https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#fonts
