### ISSUE TITLE
Add rendering for landuse=school

### ISSUE THREAD

**Issue by Khomille** [gravitystorm/openstreetmap-carto#3381]
Hello, I'm new here...

Here is my suggestion:

amenity=school is widely used to tag areas with a school and its outbuildings (gym, refectory, pitches, parking...) and areas where multiple schools share the same ground (often a [elementary school and a kindergarten](https://www.openstreetmap.org/#map=18/48.94171/2.36784), or a [high school with a junior high school](https://www.openstreetmap.org/#map=19/42.38742/-71.08703). As someone before me explained very well in #774:

> fellow mappers use it as a substitute for landuse, because it renders nicely in a yellowish color

This is problematic because the database lists too many schools: one for each actual facility and one more for the schools ground. 

This was in 2014 and @matthijsmelissen suggested that landuse=education should be rendered like amenity=school. landuse=education is rare ([used 489 times](https://taginfo.openstreetmap.org/tags/landuse=education)) but landuse=school is common ([used 5113 times](https://taginfo.openstreetmap.org/tags/landuse=school#overview)).

So could we render landuse=school just like amenity=school, with yellow color and the name? It would incite mappers to properly use amenity=school.

The french rendering of OSM already renders landuse=school : http://tile.openstreetmap.fr/?zoom=18&lat=48.94174&lon=2.36781&layers=B000000FFFFFF

**Comment by HolgerJeromin** [comment]
This should get a wiki page and perhaps a short notice on tagging ML.

But this is a very good suggestion, my [hometown needs](https://www.openstreetmap.org/way/118272694#map=17/51.88388/8.50306) this. too.

**Comment by polarbearing** [comment]
There is just a proposal https://wiki.openstreetmap.org/wiki/Proposed_features/landuse%3Dschool

**Comment by Adamant36** [comment]
What's the advantage of this over amenity=school as an area, which is already rendered?

**Comment by dieterdreist** [comment]
sent from a phone

> On 5. Sep 2018, at 18:07, Camille <notifications@github.com> wrote:
> 
> So could we render landuse=school just like amenity=school, with yellow color and the name? It would incite mappers to properly use amenity=school.


amenity=school on the school grounds (basically what the landuse school tag would be for) IS proper usage of the tag. The individual buildings within the school grounds should not get additional amenity school tags.

**Comment by polarbearing** [comment]
The proposers claim it would help in situations where more than one school share a common campus. Still I believe that this campus is an amenity=school.

**Comment by Khomille** [comment]
> dieterdreist wrote:
> amenity=school on the school grounds (basically what the landuse school tag would be for) IS proper usage of the tag. The individual buildings within the school grounds should not get additional amenity school tags.

No it is not. I'm talking about situations where the grounds are shared by different schools. Take [this example](https://www.openstreetmap.org/#map=18/48.94177/2.36799) near Paris:

- [one building](https://www.openstreetmap.org/way/63993798) is an elementary school called "École élémentaire Roland Madigou"
- [one building](https://www.openstreetmap.org/way/63992485) is another elementary school called "École élémentaire Andrez Diez"
- [one building](https://www.openstreetmap.org/way/63985690) is a kindergarten called "École maternelle Saint Léger"

Each school has a [ref number](https://wiki.openstreetmap.org/wiki/FR:Key:ref:UAI) in the french [National Directory of Schools](https://fr.wikipedia.org/wiki/R%C3%A9pertoire_national_des_%C3%A9tablissements). They all belong to the "[groupe scolaire Diez-Madigou](https://www.openstreetmap.org/way/619185410)" and share a common campus. There are 3 schools and the campus ground is not one of them, nor a 4th school. 

This is a very common situation in France where we have "[groupes scolaires](https://fr.wikipedia.org/wiki/Groupe_scolaire)" (kindergarten + elementary school) and "[cités scolaires](https://fr.wikipedia.org/wiki/Cit%C3%A9_scolaire)" (junior high school + high school). [The french wiki advises](https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dschool#Groupes_scolaires) to tag the campus with landuse=school but few mappers actually do it because they want the campus to be rendered in yellow.

![French wiki example for tagging a groupe scolaire](https://wiki.openstreetmap.org/w/images/6/6e/Groupe_scolaire_exemple.svg)

**Comment by kocio-pl** [comment]
I know also such cases in Poland, but I have not looked at the documentation until now. On the English page we have section https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dschool#Landuse:

> Tagging an area with amenity=school is the established way to tag the campus. Thus a landuse tag is typically not needed. There are some landuse=school tags in the database, please make sure they also carry the amenity tag. 

So I think we should start with discussing on Tagging list and updating documentation accordingly.

**Comment by dieterdreist** [comment]
sent from a phone

> On 6. Sep 2018, at 12:04, polarbearing <notifications@github.com> wrote:
> 
> The proposers claim it would help in situations where more than one school share a common campus. Still I believe that this campus is an amenity=school


could also be more than one school (even overlapping), but it isn’t an argument for landuse, which is just redundant

**Comment by dieterdreist** [comment]
sent from a phone

> On 6. Sep 2018, at 16:52, Camille <notifications@github.com> wrote:
> 
> Each school has a ref number in the french National Directory of Schools. They all belong to the "groupe scolaire Diez-Madigou" and share a common campus. There are 3 schools and the campus ground is not one of them, nor a 4th school.


you should include the campus grounds in the schools it is part of, this way you will have 3 schools

**Comment by jragusa** [comment]
An equivalent tagging scheme should be those applied to universities. We tag the surface with `amenity=university` and each units with `faculty=*`or `department=*`.

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Sep 2018, at 15:26, Jérémy Ragusa <notifications@github.com> wrote:
> 
> An equivalent tagging scheme should be those applied to universities. We tag the surface with amenity=university and each units with faculty=*or department=*.


this is a completely different situation, like it would be with one school and different specializations. The case that was reported here was about 3 different schools on the same campus (different buildings but common grounds). There is no problem with this.

**Comment by matkoniecz** [comment]
@Khomille 

> > On the English page we have section https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dschool#Landuse:

> > Tagging an area with amenity=school is the established way to tag the campus. Thus a landuse tag is typically not needed. There are some landuse=school tags in the database, please make sure they also carry the amenity tag. 

> So I think we should start with discussing on Tagging list and updating documentation accordingly.

Are you interested in updating English wiki and or starting discussion on tagging mailing list?

**Comment by kocio-pl** [comment]
While the usage is raising and quite right:

![taghistory 10](https://user-images.githubusercontent.com/5439713/47250831-3d2e6b00-d429-11e8-9aef-1ba334ebecaa.png)

we need some work on the documentation side which is not happening now. I will close this ticket now, but once there are related changes in the wiki it can be reopened.

**Comment by matkoniecz** [comment]
Usage is worrying a bit, especially huge sudden jumps indicating that most of use is from imports/mechanical edits.

**Comment by jdhoek** [comment]
I've started a thread on the tagging-ML on the subject `landuse=school`:

https://lists.openstreetmap.org/pipermail/tagging/2019-April/044350.html

@Khomille Could you have a look?

**Comment by polarbearing** [comment]
According to taginfo, there are 4937 schools combined with landuse=*, that is most likely most of the 5301 landuse=school. The combination for the latter is not show. 

My suspicion is that this is the result of the mech edit shown in the graph, someone trying to push the value by adding the landuse tag to the amenity.

**Comment by jdhoek** [comment]
@polarbearing A lot of that in Poland it seems. [The Polish wiki page](https://wiki.openstreetmap.org/wiki/Pl:Tag:amenity%3Dschool#landuse.3Dschool) seems to mention adding `amenity=school` to those specifically, but does not advocate removing `landuse=school`.

It would be interesting to learn what those two seemingly automated edits were meant to do.
