### ISSUE TITLE
Apron color in aerodromes is too prominent

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3385]
The airport apron is the area of an airport where park (for loading, unloading, refueling etc). Aprons are generally not open to the public, and are not features of interest on a general map style.  They are similar in use to aeroway=taxiway and amenity=parking, therefore it should be rendered in a similar way. 

But the tag aeroway=apron is currently rendered in a rather bright purple color, in contrast to the dark gray of taxiways and runways. The labels are more prominent than those of the terminal buildings.

I would recommend changing aprons to render in a light to mid-gray tone, similar to taxiways or private parking lots. 

Wikipedia article with definition: [https://en.wikipedia.org/wiki/Airport_apron](https://en.wikipedia.org/wiki/Airport_apron)
OSM Wiki article: [https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dapron](https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dapron)
Example of current rendering at Munich International Airport: [https://www.openstreetmap.org/#map=16/48.3526/11.7877](https://www.openstreetmap.org/#map=16/48.3526/11.7877)

![11342](https://user-images.githubusercontent.com/42757252/45362599-36cdf780-b610-11e8-8d5e-14526eedf2dd.png)

(Edit: fixed link to Munich airport, mentioned label prominence issue, added image)

**Comment by matthijsmelissen** [comment]
Yes, sounds like a good idea.

Could you create a pull request? It might be enough to change this line here: https://github.com/gravitystorm/openstreetmap-carto/blob/8343cc3358dbc8481fdf0ef42aaf13daac3708e8/landcover.mss#L31

**Comment by Tomasz-W** [comment]
I propose to render them the same as aeroways.

**Comment by dieterdreist** [comment]
for reference, this is the Munich airport:
https://www.openstreetmap.org/#map=16/48.3526/11.7877

I agree that a less saturated color might work better, and that it should
not be the same color as used for the taxiways and runways

**Comment by kocio-pl** [comment]
Maybe generic parking color would be OK? There will be no "P" and it should be clear from the context that they are related to the aircrafts, not cars for example.

**Comment by polarbearing** [comment]
Parking colour sounds plausible. The Munich example shows labels on the aprons ("Ramp 2"), which needs to change colour accordingly. What is the light grey behind the aprons? Is that the ```aerodrome``` colour? We would need to see how it contrasts.

**Comment by jeisenbe** [comment]
Yes, the light gray "aerodrome" color (transportation-area: #e9e7e2;) will usually be the background around the taxiways and apron, unless the aerodrome is still only marked as a node. I like the idea of unifying the rendering with parking (@parking:#eeeeee). However, the two colors are very close. I suspect this is already a problem for distinguishing surface parking lots within airports and train station areas.

Parking has a darker outline:  @parking-outline: saturate(darken(@parking, 40%), 20%);
I'd think it would be better to leave this out, in theory, because the other airport features do not have outlines and this would distinguish the apron from parking lots in the airport area (in addition to the lack of the parking icon).

I notice that osm-cart-alternative-colors (Imagico's fork) had #dedeee for transportation areas including aerodromes; this is a bluer and darker gray than our #e9e7e2. Changing transportation-area to #e9e7e2 would make this area a little more distinctive against the background land color, and would also make it possible to use #eeeeee for apron.

**Comment by kocio-pl** [comment]
Interesting ideas. Would you like to make some renderings testing these propositions?

**Comment by jeisenbe** [comment]
Should the apron name label still be rendered? It's hard to think of a typical use case. Pilots need a specialized map style (and probably should stick with commercial charts). Perhaps we can stop rendering the name of the apron? 

I couldn't find where the label size and color is specified in the current style, where should I look?

I'd love to make a PR myself and show some examples, but would I need to download all of the software to render the style on my PC? I have a very slow and unreliable internet connection.

**Comment by polarbearing** [comment]
> Should the apron name label be rendered? It's hard to think of a typical use case. Pilots need a specialized map style (and probably should stick with commercial charts).

It's not just pilots (though maybe spots pilots might use some OSM data?). As small devices are nowadays allowed during takeoff/landing it's fun to follow the plane taxiing around as a passenger.

**Comment by kocio-pl** [comment]
Initial rendering with just the color change. For me it looks nice and I have no problem with seeing the difference between it and car parking - the context is different and apron lacks the outline. Showing name is OK too and does not disturb me (we also show runway names and it works for me). Anybody wanting to make a PR and take care of more testing and (maybe) tuning?

[Warsaw Chopin Airport](https://www.openstreetmap.org/#map=13/52.1633/20.9605)

z13

Before
![ja6q9vk](https://user-images.githubusercontent.com/5439713/45840530-720aad80-bd17-11e8-9347-c2689e480d2d.png)

After
![les ntm4](https://user-images.githubusercontent.com/5439713/45840449-412a7880-bd17-11e8-9ba6-4c05fb2196a6.png)

z15
Before
![ejtzcsnq](https://user-images.githubusercontent.com/5439713/45840425-2fe16c00-bd17-11e8-98b2-dfb8407c8d64.png)

After
![z2rx67x2](https://user-images.githubusercontent.com/5439713/45840430-3243c600-bd17-11e8-8257-149ff1d33348.png)

z16
Before
![qkqpv0nr](https://user-images.githubusercontent.com/5439713/45840318-e6911c80-bd16-11e8-8648-b0ab7bbf4028.png)

After
![ah0v502m](https://user-images.githubusercontent.com/5439713/45840304-ded17800-bd16-11e8-8ab1-8cc0ba9b48a1.png)

**Comment by kocio-pl** [comment]
I guess some very light mix of parking and runway could work. It might be similar to pedestrian way or area, but again - the context is much different.

**Comment by Tomasz-W** [comment]
I'm good with parking-colour fill. I think we should avoid adding unnecessary new shades of gray, especially when having in mind https://github.com/gravitystorm/openstreetmap-carto/issues/2086

**Comment by kocio-pl** [comment]
I don't understand - why do you think anything would be wrong with another shade and how it relates to a traffic calming?

**Comment by polarbearing** [comment]
I'd guess he was referring to the dreaded word 'area:highway' in that issue. 

I'm happy enough with parking colour. Effectively, the apron _is_ the parking position for the aircrafts. As we don't render a P icon, it is still distinguishable.

**Comment by Adamant36** [comment]
I think it was in reference to the fact that we need a grayish color for that issue that isn't the parking color. Whereas, this one could be the parking-color fill just fine.

**Comment by Tomasz-W** [comment]
My mind set is "the less shades the better". We have to balance between distinguishing different types of landcover and keeping the map simple. In this case parking colour fill seems to be ok for most of participants, so I don't see a need for ading any new shade.

How it relates to traffic calming islands: if we have eg. 3 shades of grey area fillings on map, each one is distinguishable from the other and recognasible, but if we would have 10 shades of grey, some of them could be too close to each other and may be confusing. Of course is a hyperbole, but I think it shows good what I mean. Anyway, we all know that 50 shades of gray is bad thing in any meaning ;)

**Comment by dieterdreist** [comment]
to my eyes, this modification effectively removes the airport from the rendering or at least significantly reduces prominence. What is the reasoning for de-emphasizing airports on this style, aren’t they generally main features?

**Comment by kocio-pl** [comment]
This case is like all well mapped areas - see #2896. When the airport is tagged with only its area and not grass, etc, it will be better visible. There might be however airports with just a node, not area - the question is how would it look like (I guess apron would be hardly visible) and if we want it or not.

This way or another more testing is needed.

**Comment by kocio-pl** [comment]
OK, I see. Still I'm curious how it would look like, I'm very test driven... :wink:

**Comment by jeisenbe** [comment]
I actually wish the airport name label would stay visible for 1 or 2 zoom
levels higher. It would also be nice if the Terminal building labels could
render at a lower zoom level. I think this depends on the size of the
terminal building now. So there is often a zoom level or two with no
airport label and no Terminal label.

**Comment by kocio-pl** [comment]
It all needs some testing. These are not complicated things, but one doesn't know if it works until it can be seen. So I'm still looking for somebody who will actually make these tests, I'm not focused enough on this problem.

**Comment by dieterdreist** [comment]
sent from a phone

> On 21. Sep 2018, at 16:25, polarbearing <notifications@github.com> wrote:
> 
> I would consider the apron as a less important feature of an airport. It is visually dominated and characterized by the runway and the taxiway system, which still remains strong.


I agree for the runway but would not emphasize the taxiway system without including the aprons. If we’re talking about visual impact, the tower, car parks, hangars are usually dominant as well.

The aprons are useful for understanding the airport: runway, taxiway+apron, buildings (gates).

**Comment by jeisenbe** [comment]
I’m working on downloading Docker. Ive got 7 MB out of 523 MB after 9
hours; maybe the connection will be better tomorrow.

**Comment by kocio-pl** [comment]
It was surprising for me that parking color for apron is so popular and I agree it's much better than current violet filling.

However I want to ask what do you think about 40% mix of aeroway-fill and parking - it's similar to taxiways (and rightly so, as this is the same area) and at the same time does not look so blank and empty as pure parking color:

![3c50kdrd](https://user-images.githubusercontent.com/5439713/46115822-28c7cb80-c1f9-11e8-98bd-1f38e870e820.png)
![unlpfmy](https://user-images.githubusercontent.com/5439713/46115823-29606200-c1f9-11e8-8dc0-39fc4628a30c.png)
![0nj5yddf](https://user-images.githubusercontent.com/5439713/46115824-2a918f00-c1f9-11e8-9db1-a82b36227808.png)

**Comment by dieterdreist** [comment]
sent from a phone

> On 27. Sep 2018, at 02:04, kocio-pl <notifications@github.com> wrote:
> 
> However I want to ask what do you think about 40% mix of aeroway-fill and parking - it's similar to taxiways (and rightly so, as this is the same area) and at the same time does not look so blank and empty as pure parking color:


yes, better than parking color

**Comment by Tomasz-W** [comment]
@kocio-pl Please upload 30% version (I mean lighter than the current one) to compare. I think that in one "level" lighter version it would be still darker than bare ground, but less prominent.

**Comment by kocio-pl** [comment]
40% mix

original

![cqns1q 9](https://user-images.githubusercontent.com/5439713/46146919-45e5b400-c264-11e8-8a6c-82956b1ae779.png)

1% lighter

![stv1c2io](https://user-images.githubusercontent.com/5439713/46146924-48480e00-c264-11e8-97a7-e2c4943561ff.png)

2% lighter

![z5yx bq8](https://user-images.githubusercontent.com/5439713/46146927-49793b00-c264-11e8-937b-d730aa44373c.png)

**Comment by Tomasz-W** [comment]
40% mix works the best

**Comment by polarbearing** [comment]
Happy enough with those lightened runway colours. Better than the old purple definitely.

**Comment by kocio-pl** [comment]
It's #DADAE0.
