### ISSUE TITLE
Render tower:type=communication (always)

### ISSUE THREAD

**Issue by jaakkoh** [gravitystorm/openstreetmap-carto#339]
This relates (at least in part) to Issue https://github.com/gravitystorm/openstreetmap-carto/issues/181. In fact, my comment to it explains to whole thing - just wanted to open a separate issue for this in case as rendering of man_made=tower could mean different things, too:

"if there's a tower:type=communication in conjunction with man_made=mast then that icon is shown in OSM Mapnik (example: http://www.openstreetmap.org/node/2666366790).

I think this same rendering should happen when using man_made=tower (with tower:type=communication), which currently doesn't (http://www.openstreetmap.org/node/2489765793)."

**Comment by matkoniecz** [comment]
@math1985 

https://github.com/gravitystorm/openstreetmap-carto/pull/1366#issuecomment-81683325

> I have asked the Dutch community to change their tagging scheme.

Is there any result? Or is the tagging situation still at state that makes data unusable?

**Comment by math1985** [comment]
> Is there any result? Or is the tagging situation still at state that makes data unusable? 

No result yet, I made a new call to the Dutch community.

**Comment by martinum4** [comment]
so, any results jet? what makes the rendering of tower:type=communication (or man_made=tower if you don't want to render the other one) impossible?

**Comment by nighto** [comment]
Hello!

 

You have a new message, please read <http://blog.josehernandez.info/noon.php?o>

 

nighto@nighto.net

**Comment by PontiacCZ** [comment]
Still no change? `man_made=mast, tower:type=communication` apparently used to be rendered, [The Wiki](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtower) shows us which icon was used for this object. Most likely someone just made a mistake when editing the stylesheets. What does take so long to fix it?

There is a `man_made=tower, tower:type=communication` tagged on a [single node here](http://www.openstreetmap.org/node/4491833599) but it's not rendered.

Less important [masts](http://www.openstreetmap.org/node/574338445) get rendered without problems.

**Comment by kocio-pl** [comment]
@math1985 Are you still trying to discuss or is it time to decide? The PR should be rather easy to make.

**Comment by boothym** [comment]
This really needs to be sorted out. It's insane that a tag with 35,000 uses gets rendered (even though they might not be used for communication), but the tower:type=communication tag is ignored. 

If there's a problem with incorrect tagging in one country that's a data problem and no reason not to render the tag elsewhere.

**Comment by kocio-pl** [comment]
One problem is deciding, the other is purely technical - does `tower:type=*` tag need database reload and what notation should be used in `project.mml` and in `amenity-points.mss` (colon is not typical part of tag)?

There's also very similar tag, which should be rendered the same way, probably on z16+, since it's for large structure - `man_made=communications_tower` ([almost 4k uses](http://taginfo.openstreetmap.org/tags/man_made=communications_tower)).

**Comment by Tomasz-W** [comment]
I think this issue shoud be closed and further discussion should move to #2556.
