### ISSUE TITLE
Add rendering for leisure=fishing

### ISSUE THREAD

**Issue by IgorEliezer** [gravitystorm/openstreetmap-carto#3390]
"Fish & Pay" (`leisure=fishing`) is a leisure facility for fishing as entertainment. People normally pay an entrance fee or by catch weight. It's similar to `landuse=recreation_ground` but with man-made or natural pounds.

I suggest using the same pattern for `landuse_recreation_ground` and [this](https://commons.wikimedia.org/wiki/File:MUTCD_RS-063.svg) as icon.

Links:
* Wiki: https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfishing
* Taginfo: https://taginfo.openstreetmap.org/tags/leisure=fishing
* Tag count: 5 026, more than beach_resort, outdoor_seating and bird_hide.
* Examples: [w607102421](https://www.openstreetmap.org/way/607102421) and  [w544102360](https://www.openstreetmap.org/way/544102360)
* Search: https://www.google.com/search?q=Fish+%26+Pay

**Comment by Adamant36** [comment]
Good idea. The page says its still a draft though. So that might be an issue. Plus, half are mapped as points. So if it is render, it would be good to have an icon for it.

**Comment by Adamant36** [comment]
Its not a bad icon. We cant use anything related to Google Maps though because its copyrighted. So we will have to see if someone is willing to create an icon. The draft thing needs to be resolved to though. I think thats more important then if we have an icon for it or not at this point.

**Comment by IgorEliezer** [comment]
> We cant use anything related to Google Maps though because its copyrighted.

The icon is from Wikimedia Commons (https://commons.wikimedia.org/wiki/File:MUTCD_RS-063.svg), which happens to look like Google Maps'. :)

**Comment by Tomasz-W** [comment]
Icon proposals:

1. ![leisure fishing fish hook](https://user-images.githubusercontent.com/25656654/45585402-f4dcd400-b8e3-11e8-86bf-322a0e155212.png)
2. ![leisure fishing fish only](https://user-images.githubusercontent.com/25656654/45585351-433da300-b8e3-11e8-9b52-b2d145644c35.png)
3. ![leisure fishing fish hook above](https://user-images.githubusercontent.com/25656654/45585440-86e4dc80-b8e4-11e8-879b-a924048a33f4.png)
4. ![leisure fishing fish hook above](https://user-images.githubusercontent.com/25656654/45585456-cb707800-b8e4-11e8-8f54-fdb1875368b3.png)

**Comment by IgorEliezer** [comment]
I like 4 the most, for the hook close to fish mouth depicts better the "fishing" idea and resembles more the fishing sign, IMO. 3 seems a bit stacked, but still does. :+1:

**Comment by Adamant36** [comment]
@dieterdreist, can you give your opinion on why this shouldn't be rendered please? And can someone explain what the advantages of rendering this versus fishing=yes is or why the draft status doesn't matter to rendering it or not? Thanks.

**Comment by IgorEliezer** [comment]
> And can someone explain what the advantages of rendering this versus fishing=yes is

From what I understood reading the wiki and what I've found while mapping:
* [`fishing=yes|no|customers|private|etc`](https://wiki.openstreetmap.org/wiki/Key:fishing) is about access control of a water body.
* [`leisure=fishing`](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfishing) is about a facility which may contain pounds (`natural=water+water=pond+fishing=customers`), buildings, shelters etc.

**Comment by Adamant36** [comment]
@IgorEliezer HHmmm OK. Makes sense. The fact that it is a draft makes it seem like it still wasn't decided on though. Although, I still do see a use for this being rendered. My question would be if it is also mapped in places like beaches or sides of rivers where people might fish, but there is also other uses. If its only used for exclusive fishing landuses I'm fine with that. There should be a key for places like that though. I almost think a point like there is for tourist viewpoints would be better then mapping it as an area. 

Perhaps you could address the concerns raised  by Dieterdreist on the wiki page. I think he makes some valid points against it. Although, I don't know why he didn't bring them up here instead.

**Comment by dieterdreist** [comment]
sent from a phone

> On 16. Sep 2018, at 02:45, Adamant36 <notifications@github.com> wrote:
> 
> @dieterdreist, can you give your opinion on why this shouldn't be rendered please?


I am not generally opposed to rendering fishing facilities, but I think the tag is not chosen well. „fishing“ is an activity, not a facility or place. For leisure we use places, not activities.

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/58cdeee87a3e4f767d699955bd1caa35

**Comment by Adamant36** [comment]
@IgorEliezer, have you done any research on how the tag is actually used or figure out the wiki issue yet? I did a review of places tagged leisure=fishing in America and it seemed to really the gambit. There was a lot of points on the sides of lakes, beachs, and piers tagged with it. Only a few fit the discription of the tag you gave. I was planning on doing the PR for it, but id like it to be figured out first, or if not, the issue should be closed as wont add.  I think rendering it over things like beaches or piers is problematic, even if it is misstagging. Which really isnt even clear. So maybe the issue should be closed anyway.

**Comment by Adamant36** [comment]
I did some tests on it. I did similar rendering to the swimming area pr where it doesn't have a fill color. I think it looks cool and gives an opportunity to render some unique places. Its also has had a pretty meteoric rise in usage, as can be seen by the chart. its currently at 5,068 uses and seems to be going up very steadily. So I think its worth doing a PR for. Since both the usage numbers and need for it are clearly there. Whatever the exact issue with what does or doesn't qualify will probably be worked out over time and its not other tags that are currently rendered don't suffer from some miss-usage.  
![fishing chart](https://user-images.githubusercontent.com/30259065/46931521-59cd3c00-d000-11e8-9143-ff7e6cecbe89.png)
Nodes at z18
![fishing node 1 z18](https://user-images.githubusercontent.com/30259065/46931534-6fdafc80-d000-11e8-96f1-d0c034254330.png)
![fishing node 2 z18](https://user-images.githubusercontent.com/30259065/46931535-70739300-d000-11e8-8385-918164823ec5.png)
ways at z18
![fishing way 1 z18 probably wrongly tagged](https://user-images.githubusercontent.com/30259065/46931540-7bc6be80-d000-11e8-8118-746643965fd5.png)
![fishing way 2 z18](https://user-images.githubusercontent.com/30259065/46931546-81bc9f80-d000-11e8-9ff0-df531367a64a.png)

I think the first way one is miss-tagged, or maybe both as the page says it doesn't apply to areas, but I like how it looks on piers as it gives them it an extra usage context and a leisure insinuation that normal ones that just have boats attached to them don't).

**Comment by IgorEliezer** [comment]
@Adamant36:
> have you done any research on how the tag is actually used or figure out the wiki issue yet?

As to how the tag is used, outside my country, no. Doing a plain query with `"leisure"="fishing"` will bring, like you said, mixed results. At least 1/3 of occurrences are leisure=fishing used directly in lakes and pounds, which I consider miss-tagging probably due to bad documentation on the wiki.

Querying `way["leisure"="fishing"][!"natural"]` (`!natural` is to exclude lakes) brings better results that fit the criteria I gave. See examples below.

Even with laconic documentation, for me the ["leisure=" key](https://wiki.openstreetmap.org/wiki/Key:leisure) implies a facility or area with some kind of man-made structures and equipment, not just a spot in a water body, while "fishing=" would mean whether fishing is allowed or not.

Examples that fit in my criteria:

England:
https://www.openstreetmap.org/way/72241981
https://www.openstreetmap.org/way/242986416
https://www.openstreetmap.org/way/415311118

Germany:
https://www.openstreetmap.org/way/269516459
https://www.openstreetmap.org/way/24897251
https://www.openstreetmap.org/way/27410781

Brazil:
https://www.openstreetmap.org/way/262553727
https://www.openstreetmap.org/way/517951568
https://www.openstreetmap.org/way/198198187

All in all, please no hurry, and I much appreciate your testings. :+1:

**Comment by HolgerJeromin** [comment]
We should not hide tagging errors but make them visible...

**Comment by Adamant36** [comment]
@HolgerJeromin, I totally agree. That's why I think it might be worth rendering despite the tagging issues. As it would potentially give mappers a chance to fix them. Along with maybe drawing them into creating a better definition of the tag on the wiki.

**Comment by IgorEliezer** [comment]
@Adamant36, it seems we'll have a release this Friday. Is it a good idea to try the new feature?

**Comment by kocio-pl** [comment]
23.11 is a month from now, see #3476... :smile:

**Comment by IgorEliezer** [comment]
> 23.11 is a month from now, see #3476...

Oops, sorry. I mistook a month ahead Friday with this Friday. Thanks for pointing out. :+1:

**Comment by Adamant36** [comment]
@IgorEliezer, I'll be sure to do something on it before then.
