### ISSUE TITLE
Duplicated exit numbers on motorways shouldn't be rendered

### ISSUE THREAD

**Issue by DavidBelmares** [gravitystorm/openstreetmap-carto#3403]
### Expected behavior
Single number rendered per exit on a motorway
### Actual behavior
It does make sense that exits have their appropriate number ref tag, but I think that only one of them should be rendered. Having two of the same numbers close to each other on the same highway is not very clean. See what I mean: https://imgur.com/a/yL4JroP

As you can see, exit numbers 18A, 12A, 11, and 10 are rendered twice on the map (which again, makes sense due to them being labeled in both directions).

While the ref tags should be kept on both nodes of each pair, I think only one should be rendered.

**Comment by kocio-pl** [comment]
Thanks for reporting the problem. 

> While the ref tags should be kept on both nodes of each pair, I think only one should be rendered.

However the question is - which one?

**Comment by polarbearing** [comment]
You can include images in your post just by dragging them into the comment box, I did it for yours here:
![](https://i.imgur.com/PkO5e4Z.png)

There is one exit per directional carriageway, thus the number correctly represent reality. Why would you want to change that?

**Comment by DavidBelmares** [comment]
Yes, I understand that there are two separate exits, but perhaps at a certain zoom level (when the two numbers become close enough to each other), then one exit number could be rendered halfway between the two?

**Comment by kocio-pl** [comment]
At the scale you have shown they all are barely visible, so I don't see the need, while at the higher level it's probably better to show real positions. Overall this would be hardly needed in my opinion.

**Comment by polarbearing** [comment]
The example appears to be from z13, and the exits are far enough from each other to render separately. When I zoom further out in my area, the labels for the same exit number start to block each other, so that only one remains visible. So I think there is nothing to do here. 
This is similar to the two carriageways just melting together when zooming out, IIRC there is no extra code for that.

**Comment by kocio-pl** [comment]
I also think that current state of things is OK, so I'm gonna close it now. We would have strange effect when trying to make an average: for exits like 10 or 11 it would be placed on the crossing of roads, which would be false for both of them and it would make the crossing look special.

Thanks for the idea though!
