### ISSUE TITLE
Building-related rendering-bug

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3404]
https://www.openstreetmap.org/#map=19/48.51930/9.04988
![image](https://user-images.githubusercontent.com/2878623/45806558-abb0c980-bcc1-11e8-8d10-e8a4b26a1795.png)

https://www.openstreetmap.org/#map=18/48.51920/9.05026
![image](https://user-images.githubusercontent.com/2878623/45806539-9fc50780-bcc1-11e8-9d97-e101cafef020.png)

Building looks different on Z=18 and Z=19

**Comment by sommerluk** [comment]
This was a cache problem. The old tiles where cached and not updated. Accessing it now gives me the same rendering on both z18 and z19. Therefore closing this issue. Thanks anyway for the report.

**Comment by dktue** [comment]
For me the rendering is still the same -- are there any known issues regarding tile-caching that still affect this?

**Comment by kocio-pl** [comment]
Definitely very old caching. Look at the castle icon location - it's made with the old Mapnik. Also this is how z19 looks like with current master on my machine:

![pesams3i](https://user-images.githubusercontent.com/5439713/45815423-e40fd200-bcd8-11e8-8fd7-0ca313dbb22a.png)

**Comment by kocio-pl** [comment]
Check it now. I just requested manual refresh:

https://b.tile.openstreetmap.org/19/275323/181113.png/dirty

and it looks like it was re-rendered now. :smile:
