### ISSUE TITLE
Render power plants area

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3405]
Example where rendering the area would be helpful for `power=plant`
https://www.openstreetmap.org/way/164454445
![image](https://user-images.githubusercontent.com/2878623/45817399-fab92780-bcde-11e8-866a-62b82eac0790.png)

**Comment by kocio-pl** [comment]
Hm, 42% of them have `landuse=industrial` included:

https://taginfo.openstreetmap.org/tags/power=plant#combinations

According to wiki using it is "recommended if not already inside a bigger landuse=industrial, else optional":

https://wiki.openstreetmap.org/wiki/Tag%3Apower%3Dplant

**Comment by kocio-pl** [comment]
I guess if landuse for this exact object is optional, then we don't have to expect people will add it (no need to do act as a quality assurance), so we can safely add such rendering - even safer than with #3376, which was just a reality check. 

Would you like to try?

**Comment by matkoniecz** [comment]
> I guess if landuse for this exact object is optional

Why? I think in this case landuse is missing so not rendering landuse is OK.

From what I remember that was reasoning behind showing just name - so power plants with larger landuse=industrial will have their names rendered, and power plants not within landuse=industrial will be visible as data issue.

**Comment by kocio-pl** [comment]
But there's no data issue - it is explicitly allowed as a valid tagging on wiki.

**Comment by dktue** [comment]
@kocio-pl That's the point: Either we declare it a data issue and correct it in the wiki or we render it implicitly.

**Comment by kocio-pl** [comment]
You can discuss it on a Tagging list to make sure.

**Comment by Adamant36** [comment]
It seems weird and inconsistent to have substations rendered as areas but not power plants. I would expect them to be extremely similar in mapping philosophy and only a small amount of them are tagged with landuse. So its clearly not required in that case. I don't see why it wouldn't transfer over to power plants.

**Comment by matkoniecz** [comment]
> But there's no data issue - it is explicitly allowed as a valid tagging on wiki.

Are you sure? My reading of

> recommended if not already inside a bigger landuse=industrial, else optional 

is that

- inside larger landuse=industrial adding landuse=industrial is optional (rendering is OK in this case)
- if not inside landuse=industrial then landuse=industrial is recommended (not rendering area and encouraging to add landuse=industrial is also OK in this case)

**Comment by kocio-pl** [comment]
Yes, I see no data issue here, because "recommended" is not "required".

**Comment by matkoniecz** [comment]
Wiki typically describes things this way, to avoid confusion in rare examples. There may be a rare example of power plant that is not in industrial area (because it is left operating as a tourism attraction or is a military installation).

Also, many people complain when wiki dictates tagging rather than recommends.

I will change wiki a bit to clarify (if someone disagress - please start tagging discussion on tagging mailing list or Wiki).

**Comment by kocio-pl** [comment]
Thanks Mateusz! But that means that current rendering is proper and the ticket can be closed.

**Comment by matkoniecz** [comment]
I am closing, but feel free to start tagging dicussion if someone thinks that wiki is wrong or that encouraging to add landuse=industrial is a wrong idea.

**Comment by dieterdreist** [comment]
@matkoniecz I don’t understand why it was closed, the discussion about landuse has nothing to do with rendering this feature for areas.

**Comment by HolgerJeromin** [comment]
Just as a reference: #1836 was the PR with the decision to only render a name and not a fill or outline to suggest adding a `landuse=industrial`.

**Comment by kocio-pl** [comment]
Thanks for providing link.

>I would expect that power=plant would be anyway tagged as landuse=industrial.
>Rendering area (like landuse=industrial) hides that some data is missing

That was the same assumption that it's incomplete without landuse, but was not backed by Wiki definition, so this time we're more scrupulous.

**Comment by matkoniecz** [comment]
> Would we remove the rendering of area features from military airports because there will be landuse=military?

No, but military airports (tagged with for example military=airfield) should not be rendered as landuse=military without that landuse specified.

**Comment by dieterdreist** [comment]
sent from a phone

> On 22. Sep 2018, at 06:59, Mateusz Konieczny <notifications@github.com> wrote:
> 
> military airports (tagged with for example military=airfield) should not be rendered as landuse=military without that landuse specified.


why? Are there military airfields with different landuse?

**Comment by matkoniecz** [comment]
Because it may make less obvious that land use tagging is missing.

**Comment by Tomasz-W** [comment]
If smaller `power=substation` areas are filled, why bigger `power=plant` areas aren't in any way?

**Comment by Adamant36** [comment]
@Tomasz-W, I brought that up also. It doesn't make any sense to render substations but not power plants. There's no good reason not to render them either.

**Comment by jeisenbe** [comment]
Reopened: it doesn't make sense to render power=substation areas (and currently power=station, a synonym of power=plant) but not power=plant. 

Also, we should not render the text label based on the size of the area without any representation of the area. (Larger power=plant areas get larger labels, at earlier zoom levels). This is fixed by rendering the area.

**Comment by Adamant36** [comment]
Slightly off topic, but rendering for power=station should still be removed IMO. Rendering power=plant would be great though.
