### ISSUE TITLE
Collapse/Uncollapse directions on a single route

### ISSUE THREAD

**Issue by DavidBelmares** [gravitystorm/openstreetmap-carto#3406]
I think to help clean up navigation on OSM, it would be nice to have it so that a sequence of directions for staying on a single path (maybe not in terms of ways, but in terms of name) could collapse into one step for viewing longer trips with other routes, for example. See below, where it gives detailed steps on where to turn or stay right/left, etc. The user should have the option to collapse it all into one step if he/she wishes, into something like "Turn onto Los Gatos Creek Trail and continue for 13km" for example.

### Links and screenshots illustrating the issue
![](https://i.imgur.com/TNFAVQT.png)

**Comment by kocio-pl** [comment]
Thanks for reporting it! However this project is only about styling default map and has nothing to do with rendering routing hints. I think you should report it here:

https://github.com/openstreetmap/openstreetmap-website/issues

**Comment by polarbearing** [comment]
Probably it should be reported to the specific routing engine, there are a couple of them linked on the OSM website, unfortunately which one is cut off in the screenshot.

**Comment by kocio-pl** [comment]
I guess routing engines are not responsible for the way the route is presented, but you need to ask to really know how it works.
