### ISSUE TITLE
carto execution causes "TypeError: Cannot read property 'hasOwnProperty' of undefined"

### ISSUE THREAD

**Issue by bjornjm** [gravitystorm/openstreetmap-carto#3409]
### Expected behavior
Build style.xml through the command carto project.mml > style.xml

### Actual behavior
Program crashes due to TypeError problems
/usr/lib/nodejs/carto/lib/carto/tree/reference.js:19
    if (mapnik_reference.version.hasOwnProperty(version)) {
                                 ^

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Object.ref.setVersion (/usr/lib/nodejs/carto/lib/carto/tree/reference.js:19:34)
    at /usr/lib/nodejs/carto/lib/carto/tree/reference.js:209:5
    at Object.<anonymous> (/usr/lib/nodejs/carto/lib/carto/tree/reference.js:213:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

### Links and screenshots illustrating the problem

Version: openstreetmap-carto-4.14.0

I followed the guide "Build Your Own OpenStreetMap Tile Server on Ubuntu 16.04"
and got to the step when I should build the style.xml file:

carto project.mml > style.xml

In large the guide matched the instructions found in the provided INSTALL.md

I started to read the referenced code but concluded that I am not familiar with the programming language or the structure of the system so I gave up and search for help. I did not find much relevant to carto (even though a lot of hits for the generic problem). Hopefully there is some obvious detail missing...

system: Ubuntu 18.04

uname -a: Linux ultra 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

/Björn

**Comment by kocio-pl** [comment]
Hi, Björn,

Which Carto CSS version do you use?

**Comment by bjornjm** [comment]
Hmmm, I thought that was 4.14.0 since that was the version  name in the filename
but now when I go back I am not sure how I got to that archive. Probably the file in the guide was missing and I search for the latest/stable... But perhaps I went wrong.
Should I clone the git and build from there?

**Comment by kocio-pl** [comment]
I was asking about carto tool, not this style. This might be confusing: Carto CSS is a tool for compiling different styles and OpenStreetMap Carto is this style, which is being compiled.

What is the output of:

`carto -v`

**Comment by kocio-pl** [comment]
You need much newer version of Carto CSS - currently we depend on >= 0.18.0:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#additional-deployment-dependencies

0.9.5 is very old, like 5 years:

https://www.npmjs.com/package/carto

I use the one that is automatically installed with Kosmtik, but you can use the instructions from switch2osm:

```bash
sudo npm install -g carto
```
see:
https://switch2osm.org/manually-building-a-tile-server-18-04-lts/

**Comment by plqplq** [comment]
I'm still getting the same error as the OP with the latest versions

I did 

    sudo apt install npm nodejs
    sudo npm install -g carto

this shows:

    carto@1.2.0

Then 
    carto -v

Returns that same error (can't paste it sadly but same as OPs post)

    apt-show-versions node-carto

returns node-carto:all/bionic 0.9.5-2 uptodate

So why do I have 0.9.5-2 when I've just updated it ? 

Sorry if this is a linux noob error, I'm ok on windows :)
