### ISSUE TITLE
Layer not respected in attraction=water_slide

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3413]
The `layer`-tag is not respected in water-slides:
![image](https://user-images.githubusercontent.com/2878623/45948622-049d9c00-bff9-11e8-9f87-4b1ffaa28de8.png)

https://www.openstreetmap.org/way/603108779
https://www.openstreetmap.org/way/603108778

**Comment by kocio-pl** [comment]
Related to #3346.

@johsin18 Would you like to inspect this problem?

**Comment by johsin18** [comment]
I will try, but I have to set up my testing environment again first.

**Comment by johsin18** [comment]
Better like this?
![screenshot_20180929_145458](https://user-images.githubusercontent.com/3518185/46246058-326b5200-c3f8-11e8-9e36-7a6a9ddfcdcb.png)
![screenshot_20180929_145544](https://user-images.githubusercontent.com/3518185/46246059-38f9c980-c3f8-11e8-8417-273133ab5c83.png)
