### ISSUE TITLE
Remote connection to the PreviewServer with docker-compose up kosmtik

### ISSUE THREAD

**Issue by d3netxer** [gravitystorm/openstreetmap-carto#3415]
I followed the Quickstart instructions in the Docker Readme file on an Ubuntu 16.04 instance in AWS. The security group rules allow all traffic. After running ```docker-compose up kosmtik``` Everything seemed to be in order, here is the end of the output:

```
kosmtik_1  | Waiting for PostgreSQL to be running
kosmtik_1  | PostgreSQL running
kosmtik_1  |
kosmtik_1  | Starting get-shapefiles.py...
kosmtik_1  | ...script completed.
kosmtik_1  |
kosmtik_1  | [Core] Loading config from .kosmtik-config.yml
kosmtik_1  | [Core] Loading plugin from ../plugins/base-exporters/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/hash/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/local-config/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/datasource-loader/index.js
kosmtik_1  | [Core] Loading plugin from kosmtik-overpass-layer
kosmtik_1  | [Core] Loading plugin from kosmtik-fetch-remote
kosmtik_1  | [Core] Loading plugin from kosmtik-overlay
kosmtik_1  | [Core] Loading plugin from kosmtik-open-in-josm
kosmtik_1  | [Core] Loading plugin from kosmtik-map-compare
kosmtik_1  | [Core] Loading plugin from kosmtik-osm-data-overlay
kosmtik_1  | [Core] Loading plugin from kosmtik-mapnik-reference
kosmtik_1  | [Core] Loading plugin from kosmtik-geojson-overlay
kosmtik_1  | [Core] Loading project from project.mml
kosmtik_1  | [Core] PreviewServer started, you can browse http://0.0.0.0:6789
kosmtik_1  | [Core] Creating metatiles cache dir tmp/openstreetmap-carto/meta
kosmtik_1  | [Core] Deleting previous metatiles tmp/openstreetmap-carto/meta
kosmtik_1  | [Core] Created vector cache dir tmp/openstreetmap-carto/vector
kosmtik_1  | [Local Config] Unable to load local config from /openstreetmap-carto/localconfig.js
kosmtik_1  | [Error: File not found: /openstreetmap-carto/localconfig.js]
kosmtik_1  | [Fetch Remote] Done.
kosmtik_1  | [Core] Generating Mapnik XML…
kosmtik_1  | [Core] Using mapnik version 3.0.20
kosmtik_1  | [Core] Loading map…
kosmtik_1  | [Core] Map ready
kosmtik_1  | [Core] Loading map…
kosmtik_1  | [Core] Map ready
```

### Expected behavior
connect to my server from a distant location (http://MyServerIP:6789), and view the preview server

### Actual behavior
I went to the server address (http://MyServerIP:6789), and it displayed "This site can't be reached"

**Comment by ImreSamu** [comment]
imho:  this is a security restiction.

1. for a good security the SSH tunneling is the best
* https://blog.trackets.com/2014/05/17/ssh-tunnel-local-and-remote-port-forwarding-explained-with-examples.html


2.  not recomended / not secure :  you can open the port by modifying the port settings in the `docker-compose.yml` 
https://github.com/gravitystorm/openstreetmap-carto/blob/master/docker-compose.yml#L13

from
```yaml
    ports:
      - "127.0.0.1:6789:6789"
```

to
```yaml
    ports:
      - "6789:6789"
```

**Comment by kocio-pl** [comment]
Thanks for the report, however this is installation specific problem, not a problem with this style, so I will close it now.

**Comment by SomeoneElseOSM** [comment]
> Thanks for the report, however this is installation specific problem, not a problem with this style, so I will close it now.

It's something that really ought to be in the Docker Readme though - I wouldn't assume that everyone following these instructions is aware that this is even an option.

**Comment by d3netxer** [comment]
Thank you very much @ImreSamu. This worked for me and was very helpful!

**Comment by kocio-pl** [comment]
You have used different environment, from security point of view it's better to not allow reading this port from another machine.

**Comment by matthijsmelissen** [comment]
It seems my Docker-based installation somehow stopped working for me :(. I cannot connect to the PreviewServer anymore, even though I'm running Docker on my local machine.

In the output from Docker it shows:

> [Core] PreviewServer started, you can browse http://0.0.0.0:6789

Despite this, on http://0.0.0.0:6789 (and http://localhost:6789) I get the message "This site can’t be reached".

I'm using Docker for Mac OS, if it matters.

Does anybody have any idea how I could fix this?

**Comment by jeisenbe** [comment]
Have you already quit and restarted docker? I occasionally have to do this.

**Comment by matthijsmelissen** [comment]
> Have you already quit and restarted docker?

Yes, I have.

**Comment by jeisenbe** [comment]
Did you also restart the OS?

What browser are you using?

Changing branches didn’t help?

What messages are you getting in terminal?

**Comment by matthijsmelissen** [comment]
I reset docker now, which solved the problem (Preferences-Reset-Reset to factory defaults).

I had restarted the OS already, and changing branches did not help. No unexpected messages in Terminal. Anyway it's solved now.

**Comment by jeisenbe** [comment]
Weird! Glad it’s fixed

**Comment by HolgerJeromin** [comment]
The ip address `0.0.0.0` is special.
Assuming you have a network with `192.168.1.x` range. You have a loopback device with `127.0.0.1`, too.
If a program opens a webserver on the IP address `127.0.0.1` it will be reachable only from the same host. 
But if a program listen on `0.0.0.0` it will be available from everywhere, but you cannot connect to `0.0.0.0`, but the corresponding `127.0.0.1` (localhost) or `192.168.1.42` for example.
