### ISSUE TITLE
Start rendering of landuse=logging

### ISSUE THREAD

**Issue by ghost07tula** [gravitystorm/openstreetmap-carto#3416]
Hi all,

Right now we don't render landuse=logging, however this tag is widely used: see https://taginfo.openstreetmap.org/tags/?key=landuse&value=logging#overview

The bad thing here is that not rendering this tag leads some beginner mappers to use incorrect tags instead, like natural=heath/scrub/grassland. It is a good example of mapping for render, for instance take a look at this place: https://www.openstreetmap.org/#map=13/55.7753/38.0176 here we have heath in some areas and grassland in others. I personally visited this place on the bike, and can confirm that all these greenish areas should be mapped like landuse=logging + logging=clearcutting + start_date=?. 

So I think it makes sense to discuss how we should render it. Any ideas are welcome.

**Comment by kocio-pl** [comment]
Hi,

Thanks for the report, but this problem has been already discussed on #2531 and has been rejected as a forest life-cycle problem, so please look and discuss there. I will close this ticket as a duplicate.
