### ISSUE TITLE
Tunnel renders above buildings

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3417]
### Expected behavior
Tunnel renders under buildings
### Actual behavior
Tunnel renders above buildings
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=19/48.51839/9.04460
![image](https://user-images.githubusercontent.com/2878623/46135832-6b63c500-c246-11e8-8bed-a7eff9fe16ac.png)

**Comment by matthijsmelissen** [comment]
> Tunnel renders under buildings

Is that really the expected behaviour? In that case, small tunnels under big buildings would be invisible.

See for example also #529.

**Comment by matthijsmelissen** [comment]
See https://www.openstreetmap.org/#map=17/49.61100/6.13263 for a case where it is probably desirable that the tunnel is rendered on top of the buildings.

**Comment by dktue** [comment]
Good point @matthijsmelissen -- I'm looking forward to the discussion that might take place here! :-)

**Comment by RAytoun** [comment]
An easy way is to remove the road fill (or make the colour fill transparent and less less prominent) and let it render at the same layer as the buildings. That way the outlines and colour of the buildings will show with the pecked casing of the road in the tunnel showing through. This would also solve the problem that exists further to the right https://www.openstreetmap.org/#map=19/49.61133/6.12955 where the aqua tunnel takes on far more prominence than it deserves. But applying this as a general rule for tunnels would also affect the pedestrian footways inside buildings https://www.openstreetmap.org/#map=19/49.61101/6.13117 where prominence is desired.

**Comment by matkoniecz** [comment]
This is a complicated decision and it was considered desirable to render tunnels over ground features - see for example #3265 #3025 #1609 #623 #1911 and my own report in #250 :)

I will close it as a duplicate for now. Proposal to change it should consider reasons why it is considered preferable (for start - building passages would be invisible with tunnels rendered under buildings).
