### ISSUE TITLE
Dots in cyrillic "і" letters are lost

### ISSUE THREAD

**Issue by Vort** [gravitystorm/openstreetmap-carto#3418]
Lowercase letter "і" should have a dot rendered.
For reference look at [Dotted I (Cyrillic)](https://en.wikipedia.org/wiki/Dotted_I_(Cyrillic)) article at Wikipedia.

Screenshot:
![iss](https://user-images.githubusercontent.com/1242858/46137611-ac61d680-c252-11e8-9afc-63217f303cdc.png)
Location: [50.0048, 36.2297](https://www.openstreetmap.org/#map=16/50.0048/36.2297).

**Comment by matthijsmelissen** [comment]
Wikipedia says: "Even when the lowercase form is present without any other diacritic, the dot is not always rendered in historic texts (the same historically applied to the Roman letters i and j). Some modern texts and font styles, except for cursive styles, still discard the "soft" dot on the lowercase letter because the text is readable without it."

I have no opinion on it myself.

**Comment by sommerluk** [comment]
The corresponding Unicode code point for “і” is `U+0456 CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I`. And at the place you pointed out, in the OSM database, the `name` values indeed use this code point. So the OSM data itself seem to be correct.

The font family we are using for rendering is Noto. There is a [ticket about adding a dot to this character](https://github.com/googlei18n/noto-fonts/issues/1051) on Noto’s issue tracker. Noto ships currently two glyphs for `U+0456 CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I`: One _with_ a dot, the other one _without_ a dot. I’m not sure which are the conditions that trigger one or the other rendering. (It doesn’t show up in the `locl` lookup table, but in some other lookup tables.) As I don’t know well the Cyrillic script, I haven’t a clear idea about, but I would suggest you subscribe to the Noto issue mentioned above.

**Comment by matthijsmelissen** [comment]
Thanks for investigating, @sommerluk!

As this seems to be an upstream issue in the font, I'm going to close the issue on our side. Hopefully a solution will be find on the Noto side!
