### ISSUE TITLE
operator tag on ATM rendered only if name tag is also present

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#3419]
### Expected behavior

operator tag is rendered on ATMs

### Actual behavior

According to https://forum.openstreetmap.org/viewtopic.php?pid=717818#p717818 operator tag on atm is rendered only with name tag present

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/node/4804767422 (operator tag not rendered)

https://www.openstreetmap.org/node/935796695 (operator tag is rendered because name tag is present)

**Comment by kocio-pl** [comment]
What can be a source of this problem?

**Comment by matkoniecz** [comment]
Filtering where only objects with `name=*` are selected would be my first guess (for example in SQL).

**Comment by jeisenbe** [comment]
I have checked, and this bug does not appear to be present. The code in project.mml and amenity-points.mss is appropriate, and test renderings with `amenity=atm` + `operator=atm_operator` show the rendering as expected. This issue appears to be resolved now.
