### ISSUE TITLE
Docker fails to download shapefiles

### ISSUE THREAD

**Issue by janosrusiczki** [gravitystorm/openstreetmap-carto#3423]
### Expected behavior

After typing `sudo docker-compose up kosmtik` the kosmtik server should come up and I should be able to browse the tiles.

### Actual behavior

While the docker container launches I get the following error:

```
kosmtik_1  | Starting get-shapefiles.py...
kosmtik_1  | 1-1. Downloading 'world_boundaries'...
kosmtik_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
kosmtik_1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file data/world_boundaries-spherical.tgz: 
kosmtik_1  | Warning: Permission denied
```
And kosmtik is not displaying any tiles.

**Comment by ImreSamu** [comment]
> Starting get-**shapefiles**.py...

Can you give more informations ?
* linux, docker, docker-compose version - or any important things 
* What is your UID?  


see
_"The **shapefile data** that is downloaded is owned by the user with UID 1000. If you have another default user id on your system, consider changing the line USER 1000 in the file Dockerfile."_

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md#test-rendering

**Comment by janosrusiczki** [comment]
> What is your UID?
This was the problem, my UID was 1001. Thank you.
