### ISSUE TITLE
Don't even make isolated smaller houses' numbers disappear

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3429]
In
https://www.openstreetmap.org/?mlat=24.18169&mlon=120.86527&zoom=15#map=19/24.18156/120.86529
the house number (1-3) disappears if the house is too small. And one needs to use the humanitarian layer to see it.

Wouldn't it be better judgement to only make it disappear if there are other houses crowding it out?

Making smaller house numbers disappear adversely affects the isolated rural poor during rescue operations.

**Comment by kocio-pl** [comment]
Thanks for reporting. It's however not about isolation, because it's perfectly visible when not eclipsed by storage tanks, so I will close it now:

https://www.openstreetmap.org/?mlat=24.18169&mlon=120.86527&zoom=15#map=17/24.18105/120.86530
