### ISSUE TITLE
Dividing lines between residential areas

### ISSUE THREAD

**Issue by FTno** [gravitystorm/openstreetmap-carto#3433]
On the screenshot of the standard map  (https://www.openstreetmap.org/#map=19/59.72246/10.25500) there are residential areas (landuse=residential) located right next to each other,
and a dividing line appears between them.
I think it's wrong to display dividing lines between residential areas. Just looks bad and can't see any reason why.

![dividing_lines](https://user-images.githubusercontent.com/16176811/46569973-49acc100-c95d-11e8-9a9b-3b9cff86dc6c.png)

**Comment by FTno** [comment]
I have seen such dividing lines several places on the map, and they have seemed to me to be arbitrary. Someone have drawn a residential area and later another area has been drawn next to it and so forth. Those areas can of course just be merged, but that could mean a lot of work.

Since I now understand that this is an intentional behaviour and in some cases serves a purpose  (like in the two example links above), I close this issue.

**Comment by Adamant36** [comment]
Feel free to merge them. I don't think anyone will mind. There's a lot of places in California where I had to do that and I haven't gotten any hateful messages about it yet (fingers crossed). I think a lot of it has to with do with bad imports. It can be a lot of work to deal with and it sucks having to clean up other people's bad mapping, but I think it will ultimately make the map better. Good luck ;)

**Comment by polarbearing** [comment]
If there is a reason to draw the residential areas separately, that should be recognisable. I know some locations where the residential areas have names, so I'd like to see the boundary of that named area.
