### ISSUE TITLE
Relationship boundaries are rendered twice

### ISSUE THREAD

**Issue by Circeus** [gravitystorm/openstreetmap-carto#344]
From the code in admin.mss, I can't figure out why, but (as far as I can tell) boundary relationships will be rendered regardless of the tagging on the member ways. Since tagging ways separately with boundary tags will *also* cause these to be rendered, in many instances you'll get ways that render as boundaries twice. The result is that it is essentially impossible to have meaningful boundary relationships without making it impossible to have consistent rendering between ways with identical tags. 

For a simple example:  http://www.openstreetmap.org/#map=17/33.81944/-118.16976

The issue is not limited to the interaction of way tags and relationships, since a way that belongs to multiple boundary relationships will still suffer the same problem. Is there any way to limit the rendering at the way level (i.e. check for boundary tags OR membership in a boundary=administrative relationship) rather than rendering from both sides?

**Comment by math1985** [comment]
Solved by #1107 some time ago.
