### ISSUE TITLE
Update some icons

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3449]
There are disussions about updating some of icons, but as they are going on in closed tickets. I'm opening new one for doing it properly.

* `amenity=restaurant`(https://github.com/gravitystorm/openstreetmap-carto/pull/3430):
![](https://user-images.githubusercontent.com/25656654/46673489-2fcbe200-cbda-11e8-8dc4-e9471e02cbdc.png) (fork + spoon)
![amenity restaurant](https://user-images.githubusercontent.com/25656654/46916163-23b79a00-cfb7-11e8-8b42-6eeda3ca95b9.png) (fork + knife)

(current one: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/restaurant.svg)

* `man=made=storage_tank/ silo`(https://github.com/gravitystorm/openstreetmap-carto/issues/588):
![](https://user-images.githubusercontent.com/25656654/45743526-80b07200-bbfc-11e8-8cc5-3bc5e157ec40.png)

(current one: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/man_made/storage_tank.svg)

* `amenity=arts_centre` (https://github.com/gravitystorm/openstreetmap-carto/pull/3401):
![](https://user-images.githubusercontent.com/25656654/46671848-2a6c9880-cbd6-11e8-900d-6ad4f4dacbc7.png) (palette + note v1)
![](https://user-images.githubusercontent.com/25656654/46671849-2a6c9880-cbd6-11e8-9577-67e08c9ffa9d.png) (palette + note v2)
![amenity arts_centre4](https://user-images.githubusercontent.com/25656654/46916188-67120880-cfb7-11e8-871a-ea609eb4d81a.png) (note + paint brush)

(current one: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/art.svg)

**Comment by kocio-pl** [comment]
Regarding arts_centre - What about white mask (from theater) combined with palette instead of a note?

**Comment by Tomasz-W** [comment]
@kocio-pl I've tried and it didn't work, but I've made palette + note with bigger outline. 

![amenity arts_centre2](https://user-images.githubusercontent.com/25656654/47154632-21b94800-d2e3-11e8-8632-d1810816c2ae.png)

What do you think?

**Comment by kocio-pl** [comment]
Yes, I think it might work, I just need some real rendering to make sure.

**Comment by Tomasz-W** [comment]
Gist link for all icons: https://gist.github.com/Tomasz-W/4ebcb87699e6442d696f9c06ce16c31f

@Adamant36 Can you test them?

**Comment by kocio-pl** [comment]
Great!

I would choose standard fork+knife for restaurants, fork+spoon might be useful in the future for some food-related objects.

**Comment by jeisenbe** [comment]
FYI, in Asia it is common to use spoons, and sometimes there are forks
available, but knives are very rarely used by customers at restaurants.

Fork+Knife is very European / Western

But Google uses 🍴 for restaurants, so I suppose everyone understands this
icon.

**Comment by kocio-pl** [comment]
Thanks for the comment, good to have someone having expertise with Eastern cultures! I would stay with spoon then to have some balance. We use a lot of Western conventions in OSM Carto and current symbol is well known already, so it will be just mirrored.

**Comment by Jez-C** [comment]
Now carto uses the palette on two icons, I disagree with using it on a third. 

I think of arts centres providing teaching (dance/theatre/music/painting) and live performance, so agree with having a combined icon - I suggest a combination of half theatre mask + paint brush?

**Comment by Tomasz-W** [comment]
I prefer "fork + knife" version, but it's not so important thing for me, so I'll be ok also with "fork + spoon"

@Jez-C Shop palette is in _shop-violet_, gallery palette is in _amenity-brown_, and palette in arts centre would be only half-visible, so all of them would be easy distinguishable from each other. I've been trying with "mask + brush" and it didn't work.

**Comment by matkoniecz** [comment]
> I assume new icons will still cover up addresses. #3435

As it is obvious from the title this change is not intended to affect adresses.

**Comment by Adamant36** [comment]
@Tomasz-W, should the icon for arts centre be applied to art shops and galleries also or just arts centre? I don't think art shops would have music, but galleries might.

**Comment by Tomasz-W** [comment]
In the topic about small changes of the icons: don't you think that `historic=wayside_shine` should be moved to _amenity-brown_? It usually has religious or/ and cultural values, so filling it with _man-made-grey_ is a little bit like a visual reduction of these values. @kocio-pl @Adamant36 ?

**Comment by kocio-pl** [comment]
Sorry, I don't follow current discussions, but I thought that objects that are not directly usable and are mainly orientation points should be not brown. I believe most shrines are not "usable" (in a meaning of "interaction"), just like crosses.

**Comment by Adamant36** [comment]
@Tomasz-W, thanks. Uuumm I don't know about historic=wayside_shrine being amenity-brown or not. I don't have a good definition of what an amenity is (maybe its a European term?). Let alone what qualifies as man made or not. 

I do think if we mix tags with colors from different tags to much it will make things way over complicated in the code though due to the way variables work.

**Comment by kocio-pl** [comment]
Arts centre looks good with a note, storage tanks are still recognizable for me and spoon version is nice too (knife is great and for the Western culture map I would choose it, but we try to consider other parts of the world if possible).

**Comment by geostonemarten** [comment]
> I prefer "fork + knife" version, but it's not so important thing for me, so I'll be ok also with "fork + spoon"
> 
> @Jez-C Shop palette is in _shop-violet_, gallery palette is in _amenity-brown_, and palette in arts centre would be only half-visible, so all of them would be easy distinguishable from each other. I've been trying with "mask + brush" and it didn't work.

And why not hand or chopsticks ;-)

**Comment by Adamant36** [comment]
@Tomasz-W, are you good with the updated icons/fork and spoon?
