### ISSUE TITLE
Add amenity=internet_cafe icon

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3451]
Since this is quite popular amenity (it has 5090 uses now), which is not "cafe" (there is special key for real cafe and other objects, for which it's not a primary property - `internet_access`), I would add the icon like brown `@`symbol, which is typical Internet-related sign.

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dinternet_cafe

![taghistory 64](https://user-images.githubusercontent.com/5439713/46990699-e19b6f00-d102-11e8-8109-075b4c1ff335.png)

**Comment by jeisenbe** [comment]
I've just got kosmtik running, so I could do some testing renderings now! 

I'm looking for a good SVG image file for the @ symbol, but the ones I've found are not sized the same as our 14 pixel SVGs. Is there a good application I can use for resizing and editing SVGs?

**Comment by kocio-pl** [comment]
Great! I was about to ask you how is it going. :smile: 

I, and probably many other people, do SVG editing using multi platform application Inkscape (distributed under open source license).

**Comment by jeisenbe** [comment]
I haven't been able to find a download an Inkscape package for MacOSX 10.13.16 (High Sierra). It looks like there is a "Homebrew" option but I'm not sure about trying that yet.

@Tomasz-W, could you make an @ "at" symbol icon for this issue?

(I'm also having trouble finding internet cafes! I thought there were 4 in the Azores, but they are located at the same place as several amenity=bank, so didn't render. I'm trying Lebanon now. Is there a good tool for downloading just a small area of a city, rather than a whole country?)

**Comment by kocio-pl** [comment]
Isn't this package proper for you?

https://inkscape.org/release/0.92.2/mac-os-x/

Finding and exporting small area is rather easy:

1. Go to https://taginfo.openstreetmap.org/tags/amenity=internet_cafe
2. Click Overpass turbo
3. Set the area you want to try
4. Click "Run/Execute" (or whatever English version might be...) - if there are no objects just check another area
5. Click on the object you want to render
6. When seeing data on the standard OSM.org page click Export on top and then click Export button (or "Overpass API" link if there are any problems)

This will let you download `map.osm` file which you can import the same as PBF files.

I also try to zoom in/out an object on the map, so the proper zoom+position appears in the URL. Then I copy it from URL (something like `18/52.25436/21.03768`) and paste it in the Kosmtik URL (like `http://127.0.0.1:6789/openstreetmap-carto/#18/52.25436/21.03768`), so I don't loose the time to find it and render a lot of tiles along the way.

Did it help you?

**Comment by jeisenbe** [comment]
Thanks for the link to inkscape! The one I found was broken. It's a
big file so it may take me a couple of days; hopefully @Tomasz-W will
make one sooner.

I previously tried to import a data.osm file with "docker-compose up
import" but I got this error:

"Osm2pgsql failed due to ERROR: Open failed for 'data.osm.pbf': No
such file or directory"

So I thought I had to have a file in the format data.osm.pbf to use
the command "docker-compose up import".

Do I need to edit the file docker-startup.sh to look for data.osm or
map.osm instead of data.osm.pbf?

Or is there a different command to import a databalse from data.osm
instead of .pbf?

I think I can download osmosis and use that to change .osm files to
.pbf, so I might try that instead?

**Comment by polarbearing** [comment]
inkscape is on macports as well:
```
# port search inkscape
inkscape @0.92.3 (graphics, gnome)
    This is the current stable release version of Inkscape.
inkscape-app @0.92_1 (aqua, graphics)
    Inkscape.app application bundle
```

**Comment by Adamant36** [comment]
@jeisenbe, why not just go to Geofabrics website and download a .pbf file? A lot of them are really small and its alot easier then trying to convert something into one. Then you just put in the osm directory, rename it data.osm.pbf, and do the docker up import thing.

**Comment by jeisenbe** [comment]
@Adamant36, I’ve been doing this; I’ve got Lebanon, Liechtenstein, Andorra,
the Azores and the Faroes so far, but some new features are still hard to
find, eg Internet cafe. So I’m trying Osmosis now

**Comment by Adamant36** [comment]
Thats good. Did you try OverPass Turbo? It should tell you where they are.

**Comment by Tomasz-W** [comment]
@jeisenbe Here you go: https://gist.github.com/Tomasz-W/1acbd56a526463b3d38fcc82c8028551. Good luck with test renderings and (I believe) PR :)

**Comment by Adamant36** [comment]
@Tomasz-W, you should try coding sometime. It can be kind of fun ;)

**Comment by jeisenbe** [comment]
@Tomasz-W, I tried the icon.

It looks nice when I open the svg in a browser, but I can’t get it to
render.

If I copy and rename an existing icon it works fine.

I also tried using this symbol to replace the clinic/doctors icon in the
file, and it disappeared too.

**Comment by Tomasz-W** [comment]
@jeisenbe For more technical help ask @kocio-pl or @Adamant36

**Comment by kocio-pl** [comment]
@jeisenbe From what you've described, you probably just added a styling code into `amenity-points.mss` file (just remember to add both icon styling and label styling - they are in separate sections), but did not add the proper code into `project.mml` in few sections (called data layers), where the data is selected from the database for styling. This is a technical requirement to have sane performance with that many objects we render, reading all the data at once would kill the servers, so it creates burden for coders, but is important.

I suggest to look another similar amenity there and do it the same (4 layers if I remember correctly - line object, node object, line text and node text). This way you don't have to learn SQL. For example you might look at some earlier PR code, like #3434.

I hope this is more clear now, if you need further assistance, you're welcome to write about it.

**Comment by jeisenbe** [comment]
Thank you. I did make that mistake at first, but I had already made the
changes to project.mss and I was able to get an icon and label to render by
copying an existing svg, but I couldn’t get the new svg file to render.

But now my computer has crashed and won’t restart; it may be a hardware
problem. Maybe it’s just easier for someone else, who knows what they are
doing, to take this over.

Joseph

**Comment by kocio-pl** [comment]
Sorry to hear that. In case you will be able to run it again, you might just push your code changes to your OSM Carto fork, so I can just see it.

**Comment by jeisenbe** [comment]
I’ll try that

**Comment by jeisenbe** [comment]
I tried again on a different computer, and I tried cloning [my repository](https://github.com/jeisenbe/openstreetmap-carto/tree/internet-cafe) again and using that. The text name label is still rendering, but not the icon. Here are a couple examples from the Azores, all with the same name but different locations. I guess it is a chain of internet cafes?

1. Espaçio TIC  z18
![espaco-tic-z18](https://user-images.githubusercontent.com/42757252/47218839-06843080-d3e8-11e8-995e-3d2f7d6ae310.png)

2. Espaçio TIC z19
![espaco-tic-z19](https://user-images.githubusercontent.com/42757252/47218847-0edc6b80-d3e8-11e8-972c-85df16d82319.png)

3. Espaçio TIC z21
![espaco-tic-z21](https://user-images.githubusercontent.com/42757252/47218857-169c1000-d3e8-11e8-9f35-ef92ec78b946.png)

But if I change the icon file it works! I copied cafe.svg and renamed it internet_cafe.svg, and now I get a brown coffee cup:

1. Espaçio TIC  z18
![espaco-z18-cup](https://user-images.githubusercontent.com/42757252/47218870-1e5bb480-d3e8-11e8-9314-9c875e7585f1.png)

2. Espaçio TIC z19
![espaco-z19-cup](https://user-images.githubusercontent.com/42757252/47218878-287db300-d3e8-11e8-9bc5-9fed63ef8b49.png)

3. Espaçio TIC z21
![espaco-z21-cup](https://user-images.githubusercontent.com/42757252/47218890-316e8480-d3e8-11e8-9018-602967bebe5a.png)

This is the source of the svg file that won't render for me:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:osb="http://www.openswatchbook.org/uri/2009/osb"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   viewBox="0 0 14 14"
   height="14"
   width="14"
   id="svg109"
   version="1.1">
  <metadata
     id="metadata115">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
     id="defs113">
    <linearGradient
       osb:paint="solid"
       id="linearGradient831">
      <stop
         id="stop829"
         offset="0"
         style="stop-color:#ffffff;stop-opacity:1;" />
    </linearGradient>
  </defs>
  <text
     transform="scale(1.0078887,0.99217305)"
     id="text824"
     y="10.949527"
     x="-0.81406456"
     style="font-style:normal;font-weight:normal;font-size:15.01984596px;line-height:1.25;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.37549618"
     xml:space="preserve"><tspan
       style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;line-height:1;font-family:Arial;-inkscape-font-specification:Arial;stroke-width:0.37549618"
       y="10.949527"
       x="-0.81406456"
       id="tspan822">@</tspan></text>
</svg>

**Comment by Adamant36** [comment]
@jeisenbe, I can give it a try tomorrow. There might be a chance its something to do with the icon though. There's been a couple of them that didn't display correctly for whatever reason.

**Comment by jragusa** [comment]
@jeisenbe, it's seem that your svg file is broken. Try to download it from the "Download zip" button in the link provided by @Tomasz-W

**Comment by Adamant36** [comment]
@jeisenbe, you might want to the code for the text rendering down one column to line 739 also. It seems like a more appropriate place to put it. I wouldn't put an internet cafe in the same category as a courthouse or prison.

**Comment by Tomasz-W** [comment]
@jeisenbe I've updated (cleaned) icon file: https://gist.github.com/Tomasz-W/1acbd56a526463b3d38fcc82c8028551. Please try it now.

**Comment by jeisenbe** [comment]
1) @Adamant36, thank you for the suggestion. I was having trouble understanding the current categorization. The lists of amenities in the project.mml file also appear to be almost randomly ordered.

2) I found out how to render from .osm files. This code can be used change the expected database file when you import the database with Docker, as suggested in the Docker.md file. So now I can download .osm files from the main openstreetmap.org page, or export files from the JOSM editor; very useful!

```
OSM2PGSQL_DATAFILE=file_name.osm \
docker-compose up import 
```

3) @Tomasz-W, thank you! Here's what it looks like now:

  1. Icon only; label is blocked by shop to the south, at z17
![internet_cafe-z17](https://user-images.githubusercontent.com/42757252/47248215-c488d800-d443-11e8-9db8-a4fe663f6687.png)

  2.  Internet Cafe icon and label, at z18
![internet_cafe-z18](https://user-images.githubusercontent.com/42757252/47248220-ceaad680-d443-11e8-84cc-4bae858d1d9a.png)

  3.  Second location, at z19
![internet_cafe-z19](https://user-images.githubusercontent.com/42757252/47248217-c94d8c00-d443-11e8-8683-ce121ef8e5e3.png)

  3.   Third location, at z21
![internet_cafe-z21](https://user-images.githubusercontent.com/42757252/47248321-88a24280-d444-11e8-96be-9cf403608557.png)

Should I do a PR, or do we need more test renderings first?

**Comment by kocio-pl** [comment]
For me it's simple enough case that does not need more testing. Just make sure to show one example of node + label and second one of way + label - such two examples cover most of the problems the code of typical shop/amenity could have.

I also think that `file_name.osm` might be simply renamed into `.pbf` and it would be imported anyway, because `osm2pgsql` does not check if the extension matches file format. :smile:

**Comment by jeisenbe** [comment]
I didn't find many mapped as closed ways, but here is one in an underground mall in Stuttgart, Germany:
https://www.openstreetmap.org/way/436919789

Rendering at z19:
![internet-germany](https://user-images.githubusercontent.com/42757252/47254063-5968f100-d497-11e8-9698-5c9e44ed495d.png)
