### ISSUE TITLE
amenity=car_pooling is not rendered

### ISSUE THREAD

**Issue by Phyks** [gravitystorm/openstreetmap-carto#3456]
Hi,

### Expected behavior

It seems that the [`amenity=car_pooling`](https://wiki.openstreetmap.org/wiki/Tag:amenity=car%20pooling?uselang=fr) tag is not rendered in the openstreetmap-carto style.

### Actual behavior

There should be an icon for these amenities, so that they get rendered. This is especially important since some of them are not attached to a matching parking spot (because there is no dedicated parking area, it might just be a station) so that they are very difficult to spot in OSM data.

A possible icon (not sure if it matches requirements for OpenStreetMap-Carto, this is just an idea) could be
![car_pooling](https://user-images.githubusercontent.com/3856586/47097516-ddba3a80-d231-11e8-9485-0e307d27691c.png)
(SVG file is available at https://framadrop.org/r/tT_0dtYt1A#CAChQdbls5kaa7DozpHdWNMVej1bomZYShqEllsmSNQ=)

### Links and screenshots illustrating the problem

Here are a few examples:

* A `car_pooling` on a parking area: https://www.openstreetmap.org/node/5908242169
![capture d ecran 2018-10-17 a 17 28 14](https://user-images.githubusercontent.com/3856586/47097613-0d694280-d232-11e8-820e-41e42514d3c8.png)

* A `car_pooling` spot in front of a train station: https://www.openstreetmap.org/node/5948749485
![capture d ecran 2018-10-17 a 17 28 55](https://user-images.githubusercontent.com/3856586/47097644-22de6c80-d232-11e8-9bff-6f202d06263a.png)

* A `car_pooling` spot which is just a station (similar to bus station, note that OSM data lacks some small way on the side here): https://www.openstreetmap.org/node/5981485462
![capture d ecran 2018-10-17 a 17 29 26](https://user-images.githubusercontent.com/3856586/47097730-4acdd000-d232-11e8-95bb-ccdfb79e8490.png)

Thanks!

**Comment by kocio-pl** [comment]
This tag is very fresh and did not seem to be widely used yet. I think this is too soon for a rendering and propose to close this ticket without taking any action:

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_pooling

![taghistory 5](https://user-images.githubusercontent.com/5439713/47112402-7fec1980-d256-11e8-9d8b-7136b2acf6c2.png)

**Comment by polarbearing** [comment]
In addition, the proposed icon looks just like a family car to me, in particular with the kid in the back seat. Nobody wearing seatbelts ;-)

**Comment by kocio-pl** [comment]
I will close it now due to general concerns, but anybody is welcome to get back once the usage is more solid. Finding a proper icon is also possible in the meantime.

**Comment by Phyks** [comment]
> In addition, the proposed icon looks just like a family car to me, in particular with the kid in the back seat. Nobody wearing seatbelts ;-)

Indeed, I missed this interpretation of this icon… I just tried to stack extra passengers in the car :) I think the "child" in the back should actually have the same size as the rest of the passengers, probably.

> This tag is very fresh and did not seem to be widely used yet. I think this is too soon for a rendering and propose to close this ticket without taking any action

Ok, that makes sense. I'll wait for this tag to be more widely used.

**Comment by Bibi56** [comment]
358 now: https://taginfo.openstreetmap.org/tags/amenity=car_pooling
If rendered, more people will add the information

**Comment by Adamant36** [comment]
That's still way under the number usually required for rendering. Most of the time it takes like 2000 or so and its still not a guarantee. Do you know if iD Editor or JOSM supports it? If not, having them add it might help it along.

**Comment by Phyks** [comment]
> Do you know if iD Editor or JOSM supports it?

iD editor does support it. JOSM does not seem to support it at the moment though :/

**Comment by Bibi56** [comment]
[Ticket](https://josm.openstreetmap.de/ticket/17780#ticket) for JOSM created.

**Comment by Adamant36** [comment]
Hhhmmm, bummer. You should open an issue with them to add support for it.

**Comment by Bibi56** [comment]
@Adamant36 I don't know what you want to say as I said I created a ticket there. Which is already fixed.
With over 2,000 places available in an Open Data set for France, we can reach a decent amount of data so that you can render it ;-).

**Comment by Adamant36** [comment]
I just didn't see your message above mine. It happens sometimes when replying on the phone. Just so you know, I don't render things. That's left up to the Collaborators. I just provide mostly needless comments about things ;)

**Comment by benoit-dd** [comment]
Time to reopen?
The ticket in JOSM has been resolved in 2019.

Over 1800 cases of `amenity=car_pooling`, and a lot more of `amenity=parking + carpool=designated` that should probably be better with only `amenity=car_pooling`.
For example in France only : over 1000 `amenity=parking + carpool=designated` (and I suspect taht people use  `amenity=parking + carpool=designated` mainly because it is rendered.

I think only `amenity=car_pooling` should have a specific render as `amenity=parking + carpool=designated` is probably also used for "normal" parking with a specific area for carpooling.

`amenity=parking_space + carpool=yes/designated` is not used so far, but might also be considered
