### ISSUE TITLE
Bridge relation outline

### ISSUE THREAD

**Issue by JitGub** [gravitystorm/openstreetmap-carto#3465]
Bridge relation outline

### Expected behavior
Render bridge outline between way under and way across.

### Actual behavior
Way under is between bridge outline and way across.

### Links and screenshots illustrating the problem
Relation: 8360247 
https://www.openstreetmap.org/#map=19/57.38136/10.50715

![bridge](https://user-images.githubusercontent.com/22381619/47255160-efd3ed00-d46c-11e8-835b-43417e196440.PNG)

**Comment by polarbearing** [comment]
I doubt that it has anything to do with the relation. It's just the order of painting the bridge footprint first. Probably already reported.

**Comment by matkoniecz** [comment]
It is rendering of man_made=bridge area, relation is utterly ignored.

**Comment by matkoniecz** [comment]
It sounds like "man_made=bridge ignores layers" in #3203

**Comment by matkoniecz** [comment]
See linked issue for more detail. Situation is not ideal but there is no good idea how it should be improved.

Even if bridges should hide everything below (what will make map worse in some places and better in other, it should be analysed whatever overall effect is positive), they're are serious technical issues hope it should be implemented (road layer is already very complex so I would not recommend it as a good starting point for getting involved with improving map style).
