### ISSUE TITLE
please render aerialway=mixed_lift

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#347]
There are not many mixed_lifts, but they are important for a ski resort.

One example:
http://www.openstreetmap.org/way/46732281#map=17/47.22377/10.12568

Photo of such a aerialway:: http://www.skiresort.de/typo3temp/pics/8ef692a525.jpg 
I do not care if cable_car.png, chair_lift.png or a new icon is used.

**Comment by matkoniecz** [comment]
It is now used 31 times (including example) and still there was no RfC/vote.

**Comment by Gazer75** [comment]
Please fix this rendering. It is a valid type of aerialway so why not render like the t-bar, chair and platter?

**Comment by taphil** [comment]
I also vote to render mixed_lift aerialway, especially since it is described as proper value of the key 'aerialway' in OSM wiki: http://wiki.openstreetmap.org/wiki/Aerialway

**Comment by nebulon42** [comment]
We don't need a different rendering, but since people are missing it on the map we should reconsider this.
