### ISSUE TITLE
Error installing carto [globalMiddleware.push(...middlewares)]

### ISSUE THREAD

**Issue by alsaleem00** [gravitystorm/openstreetmap-carto#3477]
I am trying to install openstreetmap-carto for use with switch2osm.
I followed instructions in this page [this](https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/) page.
The instructions from link above 

> sudo apt install npm nodejs-legacy
> sudo npm install -g carto
> carto -v

The last command gave error 

> /usr/local/lib/node_modules/carto/node_modules/yargs/lib/command.js:22
>     globalMiddleware.push(...middlewares)
>                           ^^^
> 
> SyntaxError: Unexpected token ...
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/carto/node_modules/yargs/lib/argsert.js:2:17)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)

The up arrows are pointing to the three dots near middlewares
Am I missing some modules/files (installation instruction)?

Thanks.

**Comment by alsaleem00** [comment]
I am installing on Ubuntu 16.04 VM. node.js version 4.2.6.
Linux ubuntu-vm 4.15.0-38-generic #41~16.04.1-Ubuntu x86_64.

Thanks.

**Comment by alsaleem00** [comment]
Will upgrading node.js solve it?

**Comment by alsaleem00** [comment]
Does this have to do with this SO [this](https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread)

**Comment by alsaleem00** [comment]
I upgraded node.js to 8.12.0 and now works ok.

**Comment by matkoniecz** [comment]
Great, thanks for reporting back!

**Comment by kmilind29** [comment]
I am still get the same error, for the steps followed with same Linux version and Node js version. How to resolved it?

**Comment by kocio-pl** [comment]
Did you try our Docker installation?

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by alsaleem00** [comment]
did you upgrade node.j ? The error was caused by the ... (spread operator) not being implemented in earlier version of node.js 
Please follow the the right step in [this ](https://www.hostingadvice.com/how-to/update-node-js-latest-version/) link.
