### ISSUE TITLE
Tree row should appear at the same zoom level as single trees

### ISSUE THREAD

**Issue by sb12** [gravitystorm/openstreetmap-carto#3484]
### Expected behavior
Same zoom level for tree and tree row as they describe the same thing just on different levels of detail. 

### Actual behavior
Tree rows appear at zoom 16, while single trees only appear on zoom 18+

### Links and screenshots illustrating the problem
[Trees and tree rows on zoom 16](https://www.openstreetmap.org/#map=16/49.02495/8.44738)
[Only tree rows on zoom 17](https://www.openstreetmap.org/#map=17/49.02495/8.44738)

**Comment by polarbearing** [comment]
Fine, the same is true for zoom levels, they describe the same thing just on different levels of detail.

Tree rows are larger entities than single trees, so I don't see a problem.

**Comment by kocio-pl** [comment]
I also think that the present rendering is correct, so I will close it now. Thanks for the report anyway!
