### ISSUE TITLE
Add rendering for leisure=dance

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3495]
This year `leisure=dance` scheme has reached 2k uses limit and is raising fast - now it's 3 701. Some icon would be nice and probably not too hard even on 14 px matrix (like dynamic green man with a note), but even generic green dot might be OK.

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Ddance

![taghistory 22](https://user-images.githubusercontent.com/5439713/47958328-953ca400-dfc9-11e8-98e6-92815ce40028.png)

**Comment by dieterdreist** [comment]
does not seem to be a tag that makes sense, if you look at the whole system of tags. „Are we going to the dance tonight?“ Is „dance“ a place? Is leisure a good key for this? Does it exclude professional dancing? 
Why is this not called something like dance_venue or dance_hall, if that is what is intended?

**Comment by kocio-pl** [comment]
I guess there is no separate tag for professional dancing, just as we have no other tags than `amenity=police`, even if this is not the "amenity" yo can use as a (security) service but some internal police objects.

The definition talks a bout dance venues (also about dance style as a subtag):

> This tag and its supplementary tags are used for purpose-built dance venues (dance halls) and other venues which offer social dancing or participation dancing as a leisure activity on a regular basis. Usually, in dance halls, there is live music and dance types vary (waltz, tango, jive etc.). These places are meant just for dancing and they are not nightclubs or restaurants although there is usually serving beverages.

**Comment by Tomasz-W** [comment]
I would use a _leisure-green_ dot here, because as e.g. ballroom dances and breakdance are totally different from each other, it would be hard to design an icon matching all dance styles.

**Comment by kocio-pl** [comment]
Ok, so that would be closely related to #3368.

**Comment by imagico** [comment]
Indeed, closed by #4996.  Thanks.
