### ISSUE TITLE
Stop smoothing leisure=track as line as it results in very bad rendering in some cases

### ISSUE THREAD

**Issue by mboeringa** [gravitystorm/openstreetmap-carto#3499]
### Expected behavior
leisure=track should be rendered "as-is", how it is digitized, not smoothed

### Actual behavior
Lines of tracks are being smoothed, as the pull request introducing their rendering included smoothing, see line 2964 in this commit:
https://github.com/gravitystorm/openstreetmap-carto/pull/3443/commits/98d723c40873f7c3c46f5b28a72dfaadf285f01d

### Links and screenshots illustrating the problem
![afbeelding](https://user-images.githubusercontent.com/7635726/48087249-1d57bf00-e1ff-11e8-9746-d1ed9548cfdb.png)

Note that in this case, the "tracks" are wrongly tagged, in fact, after inspection of the location, I have concluded these are pitches. I have re-tagged them as such. Primarily affected objects seem to be very ancient, many from before 2010, when leisure=pitch apparently wasn't yet documented, and people tagged them track instead.

Anyway, back to the issue: smoothing falsely suggests detail that isn't there, I would advocate to avoid smoothing on all objects, so as to truly represent them as they were digitized. Most other objects aren't smoothed either, so I think it an anomaly.

**Comment by kocio-pl** [comment]
I suspected that something is wrong... Do you know which part of the code makes this problem?

**Comment by matthijsmelissen** [comment]
Oops! Can you submit a PR fixing it?

**Comment by Adamant36** [comment]
@mboeringa, the code for tracks as lines was based on the code for water slides. Do you think they have the same problem also?

**Comment by kocio-pl** [comment]
It's worth checking how it works without smoothing.

**Comment by Adamant36** [comment]
@sommerluk, that's what I'm thinking. If they aren't smoothed in real life, they shouldn't be rendered that way. I guess some testing for both without smoothing needs to be done. Although, I agree its probably better to get rid of it in both instances to avoid the feedback loop issue.

**Comment by daganzdaanda** [comment]
Yes, attraction=water_slide is also smoothed, see https://www.openstreetmap.org/way/110688957
![ws](https://user-images.githubusercontent.com/7693297/48213614-80239480-e37e-11e8-8711-ad457275bf2e.png)

That way is a wide water_slide mapped as area, so it should get area=yes. But waterslides with area=yes are not rendered yet (see https://www.openstreetmap.org/way/401026322)
![ws-area](https://user-images.githubusercontent.com/7693297/48213656-9cbfcc80-e37e-11e8-938b-69b55421e16d.png)

**Comment by polarbearing** [comment]
While I see the code line ```line-smooth: 1;``` I am struggling to understand its effect?

**Comment by Adamant36** [comment]
@polarbearing, here's a test for you with line-smooth: 1 and line-smooth: 0 to compare. To me it seems like the only difference is that line-smooth: 0 has the extra random dark green lines around the outside line. Its debatable if that extra information is useful or wanted though. As it looks kind of janky. Even if its technically more "correct."

Also, here is the official description for what it does "Smooths out geometry angles. 0 indicates no smoothing is applied. 1 indicates that it is fully smoothed. Values greater than 1 produce wild, looping geometries. It is suggested to use a range between 0-1 for this value."

Line-smooth 0 at z19
![track line-smooth 0 z19](https://user-images.githubusercontent.com/30259065/48308911-c31e6d00-e522-11e8-95b6-4ef67653be1c.png)

line smooth 1 at z19
![track line-smooth 1 z19](https://user-images.githubusercontent.com/30259065/48308912-cdd90200-e522-11e8-8236-39edef8a48e3.png)

Some other random ones over the recommended number (I.E. to much smoothing)

line-smooth 3 at z19
![track line-smooth 3 z19](https://user-images.githubusercontent.com/30259065/48308917-eb0dd080-e522-11e8-9555-1924678c564d.png)
line-smooth 6 at z19
![track line smooth 6 z19](https://user-images.githubusercontent.com/30259065/48308922-07aa0880-e523-11e8-9f6c-310a65ac020a.png)
line-smooth 100 at z19 (not a track id want to try to run around)
![track line-smooth 100](https://user-images.githubusercontent.com/30259065/48308928-1395ca80-e523-11e8-9bbf-8d11d50cce31.png)

**Comment by polarbearing** [comment]
Thanks a lot! 
So it looks like kind of anti-aliasing to me. 

As any node/way representation of a curved track is an approximation to reality, I see nothing wrong with the anti-aliasing, i.e. the smoothing parameter set usefully to 1.

**Comment by jeisenbe** [comment]
Smoothing is a bad idea for this style at the highest zoom levels, because
mappers should be able to see if a road or other linear feature is mapped
with enough nodes or not.

But it would probably be fine at mid-zoom levels, where the exact geometry
is not visible, even without smoothing.

**Comment by matkoniecz** [comment]
Smoothing should not be ever done as it distorts mapped geometry - what is bad both in cases where it improves appearance and makes it worse.

**Comment by Adamant36** [comment]
@matkoniecz, just so you know I wasn't doing test renderings over the limit to suggest it should be done that way. It was just to help illustrate exactly what it was doing. While a map with the numbers jacked up on everything might be interesting to look at, its obviously not functional. 

For instance, I was fooling around with a map for a while there that replaced all the patterns and icons with Nicolas Cage faces. It might have been hilarious to look at, but it was completely unusable outside of a good laugh and teaching me more about coding. 

Anyway, on topic I'll probably do more test renderings at higher zoom levels to see how much of a difference it really makes. I'm not really sure what the utility of mappers being able to tell if a liner feature is mapped with enough nodes at a higher zoom level is, let alone how they would know if said feature even needs more nodes from a distance like that, but I'm still willing to test things out more.

**Comment by kocio-pl** [comment]
Original report shows that smoothing can work really bad and I have seen no example of smoothing improving rendering, so I would just remove this option.

**Comment by kocio-pl** [comment]
I would argue that sometimes data manipulation gives better map experience, but it's always better to avoid it when there's no need.

**Comment by polarbearing** [comment]
I had not seen the ground truth for the example in the OP, thus I was assuming the smoothing 
function was doing some anti-aliasing on strange edge pixels, as I thought seeing on the smoothing=0 
renderings later.

 From the discussion I assume however that the original tracks above were mapped as rectangles, and 
the mapnik smoothing is some mis-named curve interpolation function between fixed points.

If it is the latter, I'd be strongly against it, in general. I would hate to map an octogonal house 
and find it interpolated to a circle.

The documentation in mapnik just seems to define that 'smooth' means 'smooth', which is poor.

**Comment by daganzdaanda** [comment]
> From the discussion I assume however that the original tracks above were mapped as rectangles, and
the mapnik smoothing is some mis-named curve interpolation function between fixed points.

Yes exactly. Look at https://overpass-turbo.eu/s/DFj to find tracks without area=yes. Very often these are 100m running tracks on school sports grounds, mapped as a closed way. The rectangles turn into random weird rubber bands.

> It is not changing what should be done, but the fundamental problem with smoothing is not that map looks worse, but fact that it distorts data.

Agree. I'll open an issue for waterslides as well.

**Comment by mboeringa** [comment]
> From the discussion I assume however that the original tracks above were mapped as rectangles, and the mapnik smoothing is some mis-named curve interpolation function between fixed points.

Yes, these were rectangles in their originally digitized form, and I have kept that, as, as I discovered looking at the location at aerial imagery, these turned out to be leisure=pitch features, not tracks. 

I re-tagged them accordingly, which resolved the rendering issues for these specific features, but of course doesn't solve the styling issue.

**Comment by daganzdaanda** [comment]
[Documentation on line-smooth](https://cartocss.readthedocs.io/en/latest/mapnik_api.html#id57):

> line-smooth
> Type: float
> 
> Default Value: 0 (No smoothing.) Range: 0-1 Smooths out geometry angles. 0 is no smoothing, 1 is fully smoothed. Values greater than 1 will produce wild, looping geometries.

That explains the weird spirograph effects above. I'm still against smoothing anything in this style, but I'm curious what a value of .1 or .2 would do to a rectangle...

**Comment by jeisenbe** [comment]
Smoothing and simplification might help with dashed lines at mid and low
zoom levels, where the precise geometry cannot be shown. We already use
simplification for borders at low zoom levels. It could help reduce
rendering artifacts due to the dashed pattern on intermittent streams,
footpaths and cycle paths at mid-zoom; the dashed pattern already obscured
the precise geometry.

But I agree that it should never be used at high zoom, or on features like
sidewalks which can have sharp angles in the real world.

**Comment by StyXman** [comment]
Any news on this? For the moment, I would patch removing those lines and continue the discussion on whether add or not smoothing later.

**Comment by matkoniecz** [comment]
> Any news on this?

There is https://github.com/gravitystorm/openstreetmap-carto/pull/3547 but you are probably aware of it :)
