### ISSUE TITLE
Lighten gray color for man-made icons

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3500]
Related to #1587

Some have complained that hunting stands are too prominent with the current man-made icon color, #555555. Tall towers and cranes in cities can also appear rather too prominent at zoom level 14, where they are one of the only icons shown. It is suggested to change to a slightly lighter gray.

***Hunting Shelter, z19***
![shelter-z19-555](https://user-images.githubusercontent.com/42757252/48138182-1310f000-e2e7-11e8-835d-ecabff7dae47.png)

**Honolulu, z14** - 4 towers
https://www.openstreetmap.org/#map=14/21.3049/202.1434
![honolulu-z14-555](https://user-images.githubusercontent.com/42757252/48135627-ca563880-e2e0-11e8-8520-5def12d3b420.png)

**Hunting Shelters** https://www.openstreetmap.org/#map=16/47.8931/16.1289
![shelters-z16-555](https://user-images.githubusercontent.com/42757252/48137119-b280b380-e2e4-11e8-8165-bea04d9392f3.png)

**Ala-Wai Park** - stadium lights
https://www.openstreetmap.org/#map=18/21.28711/202.17081
![alawai-z18-555](https://user-images.githubusercontent.com/42757252/48135822-5e280480-e2e1-11e8-804e-1f9662901e4c.png)

**Diamond Head Lighthouse***
https://www.openstreetmap.org/#map=15/21.2574/202.1878
![diamond-z15-555](https://user-images.githubusercontent.com/42757252/48136224-72b8cc80-e2e2-11e8-841f-34ba03288dae.png)

**Mauna Kea Telescopes**
![maunakea-z16](https://user-images.githubusercontent.com/42757252/48135949-c1199b80-e2e1-11e8-9375-c6b07e1aed58.png)

**Comment by jeisenbe** [comment]
Three lighter gray options. I like option 3 best (#777777)

**Honolulu, z14** - 4 towers
https://www.openstreetmap.org/#map=14/21.3049/202.1434
1) Original, #555=555555
![honolulu-z14-555](https://user-images.githubusercontent.com/42757252/48135627-ca563880-e2e0-11e8-8520-5def12d3b420.png)

2) Slightly lighter #666666
![honolulu-z14-666666](https://user-images.githubusercontent.com/42757252/48135636-d3dfa080-e2e0-11e8-9c05-1cb36bbd7e2b.png)

3) Lighter gray, lucky #777777
![honolulu-z14-777](https://user-images.githubusercontent.com/42757252/48135642-d80bbe00-e2e0-11e8-8f1f-fd144a44e768.png)

4) Even lighter #888888
![honolulu-z14-888](https://user-images.githubusercontent.com/42757252/48135852-75ff8880-e2e1-11e8-96a9-fc312c7bad4e.png)


**Ala-Wai Park** - stadium lights
https://www.openstreetmap.org/#map=18/21.28711/202.17081
1) #555555
![alawai-z18-555](https://user-images.githubusercontent.com/42757252/48135822-5e280480-e2e1-11e8-804e-1f9662901e4c.png)

2) #666666
![alawai-z18-666666](https://user-images.githubusercontent.com/42757252/48135835-6aac5d00-e2e1-11e8-8f10-b5c48e001309.png)

3) #777777
![alawai-z18-777](https://user-images.githubusercontent.com/42757252/48135849-74ce5b80-e2e1-11e8-8896-3e081b4049ef.png)

4) #888888
![alawai-z18-888](https://user-images.githubusercontent.com/42757252/48135859-7ac43c80-e2e1-11e8-9cd1-1d95ecbc79c2.png)


**Diamond Head Lighthouse***
https://www.openstreetmap.org/#map=15/21.2574/202.1878
1) #555555
![diamond-z15-555](https://user-images.githubusercontent.com/42757252/48136224-72b8cc80-e2e2-11e8-841f-34ba03288dae.png)

2) #666666
![diamond-z15-666666](https://user-images.githubusercontent.com/42757252/48135915-a21b0980-e2e1-11e8-892e-4c7d061c96ac.png)

3) #777777
![diamond-z15-777](https://user-images.githubusercontent.com/42757252/48136503-27eb8480-e2e3-11e8-9a79-07ed68ea13db.png)

4) #888888
![diamond-z15-888](https://user-images.githubusercontent.com/42757252/48135905-9d565580-e2e1-11e8-8d5d-0658ccec98df.png)

**Mauna Kea Telescopes**
1) #555555
Stop me if you've seen this one before...
![maunakea-z16](https://user-images.githubusercontent.com/42757252/48135949-c1199b80-e2e1-11e8-9375-c6b07e1aed58.png)

2) #666666
![maunakea-z16-666666](https://user-images.githubusercontent.com/42757252/48135961-cbd43080-e2e1-11e8-81df-42e094676fdd.png)

3) #777777
![maunakea-z16-777](https://user-images.githubusercontent.com/42757252/48135970-d1ca1180-e2e1-11e8-9f8b-fcfd4cb97fe5.png)

4) #888888
![maunakea-z16-888](https://user-images.githubusercontent.com/42757252/48136044-ff16bf80-e2e1-11e8-924e-3be3a7c74980.png)


**Hunting Shelters** https://www.openstreetmap.org/#map=16/47.8931/16.1289
1) #555555
![shelters-z16-555](https://user-images.githubusercontent.com/42757252/48137119-b280b380-e2e4-11e8-8165-bea04d9392f3.png)

2) #666666
![shelters-z16-666](https://user-images.githubusercontent.com/42757252/48137125-b57ba400-e2e4-11e8-8adb-d6cb6555fd96.png)

3) #777777
![shelters-z16-777](https://user-images.githubusercontent.com/42757252/48137151-be6c7580-e2e4-11e8-9275-d85ea649036b.png)

4) #888888
![shelters-z16-888](https://user-images.githubusercontent.com/42757252/48137139-b9a7c180-e2e4-11e8-9779-9e7d9b4b5985.png)

Here's a hunting shelter in a patch of forest (from the same area as above):
1) 555
![shelter-z19-555](https://user-images.githubusercontent.com/42757252/48138182-1310f000-e2e7-11e8-835d-ecabff7dae47.png)

2) 666
![shelter-z19-666666](https://user-images.githubusercontent.com/42757252/48137870-51f27600-e2e6-11e8-9036-ea0e4b1ef60f.png)

3) 777
![shelter-z19-777](https://user-images.githubusercontent.com/42757252/48137857-4dc65880-e2e6-11e8-8caa-ca53ebd368a5.png)

4) 888
![shelter-z19-888](https://user-images.githubusercontent.com/42757252/48138175-0f7d6900-e2e7-11e8-9472-b8b37b21bd20.png)

**Comment by kocio-pl** [comment]
I like 777 the most.

**Comment by kocio-pl** [comment]
Are you sure you can recognize this color from black?

**Comment by Tomasz-W** [comment]
I don't have a problem with current man-mage-grey shade, so I wouldn't change anything. But if you need to, I wouln't go any lighter than a `#666666`

**Comment by Adamant36** [comment]
I like #666666. Its better then the current color. Also, I agree with @Tomasz-W about not going any lighter than that. Maybe #777777 which looks good on the telescopes but not other things. #888888 is going to light though.

**Comment by cepesko** [comment]
thanks, jeisenbe, for showing the different examples. For me it's not a matter of having problems rather than wanting to see a map where color saturation fits together and results in a harmonic style.
POIs with little relevance (and height) like hunting_stands should blend in with the other features. and not be overly outstanding. Therefore #666666 or even #777777 would be my favourite for these.
Towers and antennas could keep a stronger gray, maybe in the future depending on their height-tag if too many inner-city roof communication antennas show up.

**Comment by kocio-pl** [comment]
Roof top towers (with `location=roof` or  `location=rooftop`), including broadcasting towers are not rendered at all.

**Comment by Adamant36** [comment]
Btw, there is an issue which I plan to do a PR for eventually that would make smaller items like benches be rendered in man made grey. So if its to light of a grey color it might make smaller poi's like those harder to see. Especially in residential areas. I suggest either making two different man made grey colors based on size of thing being rendered, or test benches etc in the new grey color to make sure they arent harder to see. That being said, it might be worth waiting for that issue to get done before this one is dealt with.

**Comment by jeisenbe** [comment]
I agree that 888888 is too light. 777777 is fine in most places, but it may be too light over train tracks and other very dark areas. For example, this crane in Milan is right over main line tracks, which have a very dark gray outline.

Would 666666 work?

Train station with crane over tracks in Milan
Current z14, #555555
![z14milano](https://user-images.githubusercontent.com/42757252/48203458-e9b99800-e3aa-11e8-8fce-aa82848f9bf7.png)
Current z15
![z15milano](https://user-images.githubusercontent.com/42757252/48203462-eb835b80-e3aa-11e8-86d1-41b4b24cb9eb.png)
Current z16
![z16milano](https://user-images.githubusercontent.com/42757252/48203467-ecb48880-e3aa-11e8-980f-b447367c799e.png)

z14 666666
![z14milano-666](https://user-images.githubusercontent.com/42757252/48203429-d1e21400-e3aa-11e8-80eb-e047697a7290.png)
z15 666666
![z15milano-666](https://user-images.githubusercontent.com/42757252/48203431-d3134100-e3aa-11e8-8b09-a007d09af6ff.png)
z16 666666
![z16milano-666](https://user-images.githubusercontent.com/42757252/48203084-e5d94600-e3a9-11e8-8204-4d314296faea.png)

z14 777777
![z14milano-777](https://user-images.githubusercontent.com/42757252/48203072-dd810b00-e3a9-11e8-8ee6-32aab9b6d41e.png)
z15 777777
![z15milano-777](https://user-images.githubusercontent.com/42757252/48203075-df4ace80-e3a9-11e8-8651-e38c9097061f.png)

**Port of Venice z17**
Current 555
![z17venice](https://user-images.githubusercontent.com/42757252/48203154-102b0380-e3aa-11e8-84cd-7f20541b9096.png)
666666
![z16venice-666](https://user-images.githubusercontent.com/42757252/48203138-01445100-e3aa-11e8-8de2-73240586c642.png)
777777
![z16venice-777](https://user-images.githubusercontent.com/42757252/48203146-0903f580-e3aa-11e8-99fa-f956c19468f0.png)

**Singapore z14**
Current 555
![z14singapore-future](https://user-images.githubusercontent.com/42757252/48203166-17521180-e3aa-11e8-987f-84d7e6490266.png)
666666
![z14singapore-666](https://user-images.githubusercontent.com/42757252/48203169-191bd500-e3aa-11e8-8100-eb5a32bc1432.png)
777777
![z14signapore-777](https://user-images.githubusercontent.com/42757252/48203172-1d47f280-e3aa-11e8-9035-8589dfa7d15b.png)

**Blauer Kran, Germany, z16**
Current 555
![z16blauer](https://user-images.githubusercontent.com/42757252/48203190-2f299580-e3aa-11e8-98f9-d0e5328d1c4f.png)
666666
![z16blauer-666](https://user-images.githubusercontent.com/42757252/48203206-36e93a00-e3aa-11e8-8603-4e6812e1c7ca.png)
777777
![z16blauer-777](https://user-images.githubusercontent.com/42757252/48203193-305ac280-e3aa-11e8-8edd-5c7ab4550085.png)

**Comment by Tomasz-W** [comment]
> I noticed that wayside crosses and man_made=cross are rendered as #000000
> (black) instead of man-made icon gray.
> 
> Also wind power generator icons are black

I'm sure we would left black icons for religion map elements, but the thing to consider is to:
* use `black `also for other things, but then we shoud describe which groups should it include (to have a clear rule for the future)
or
* move all `black `non-religious icons to `man-made-grey`

Actually black power generators and cranes fits for me. What about including all naturally tall man-made objects in `black `category? It would include towers, power generators and cranes. I think it would be reasonable as we moved/ added many new things to `man-made-grey` recently. What do you think?

**Comment by jeisenbe** [comment]
I think the cranes looked too dark with the black renderings (those I
showed with the png), so I would move wind turbines to man-made-gray.

I can understand about using black for place_of_worship and wayside
shrines/crosses.

**Comment by cepesko** [comment]
In general it's a good idea to try to categorize different types of POIs depending on their tagging as man-made, place of worship (...) with one same colour.
However it's well-known that these tagging schemes developed over time and POIs often don't fit in their categories (e.g. wayside_cross = historic vs. place of_worship vs. man_made).
Therefore trying to strongly keep a consistency with tagging categories sometimes doesn't represent real categories. 
Example 1: The "amenity" hunting_stand is an amenity for a very limited number of persons, mostly just one, its owner. Aditionally it's not a landmark like the bell_tower of a church. I would therefore give it a light grey.
Example 2: A lighthouse is a big solitary landmark and would get a stronger man_made_grey since more people use it for orientation.
Example 3: A wind_generator very often is part of a wind_farm and, although it is tall, shouldn't dominate the map and would get a lighter man_made_grey.
Importance should play the most important role and change saturation of color.

Category colors shouldn't depend on the tagging but the function of the item.
In issue #3483 there's the idea to change the color of shelters at bus stops to public-transport-blue, which I support as it's part of the transport infrastructure.

etc.

Yes, wind turbines, cranes and hunting stands to man-made-gray would be a

**Comment by Tomasz-W** [comment]
As sometimes some _man-made-grey_ feature looks _black_ (like religious), I think that going down with `#666666` might be an improvement.

**Comment by Adamant36** [comment]
I vote for #666666.

**Comment by jeisenbe** [comment]
I will try #666666 in the open PR #3516

**Comment by geostonemarten** [comment]
why not add halo ? or specific color contrast on grey element same as railway???

This problem exist for all point and we need change color regulary in case of contrast with sub elements lines or polygones

**Comment by kocio-pl** [comment]
Resolved by #3516.
