### ISSUE TITLE
Non-uniform name label color for man_made features

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3510]
### Expected behavior

All man_made features with icons in man-made-icon color (currently #555, dark gray) should have a name label in a matching color.

I would suggest darkening the man-made-icon color 10% or 15%

### Actual behavior

Some man_made features have black text for the name label, others use man-made-icon gray:
The text appears to be lighter than the corresponding icon when man-made-icon is used, but darker than the icon when black is used.

**Gray labels and icon (man-made-icon):**
man_made = lighthouse, windmill, hunting_stand, bunker
historic = wayside_shrine

**Black labels with gray icon:**
man_made = tower, mast, communications_tower, water_tower, chimney

**Religious items with black icon and text**
man_made = cross
historic = wayside cross
- these can be considered a separate category
- I think we can leave these with black text and a black icon, as with place_of_worship (which actually has a very dark black-blue label)

**Wastewater and Water Plants**
- These are still in the same code as other man-made icons, but are rendered with the landcover name label code, as seen below in the test images (both a point and polygon are shown for each)
- I recommend removing the redundant code

### Links and screenshots illustrating the problem
Test images with current master:
Towers, shrines, bunkers, wastewater
![tower-shrine-bunker-before](https://user-images.githubusercontent.com/42757252/48452597-29411380-e7f3-11e8-80e8-09d5c5b57f9f.png)

Windmill, Stand, Wind Turbine, Lighthouse, Water Tower
![towers-windmill-stand-before](https://user-images.githubusercontent.com/42757252/48452599-2b0ad700-e7f3-11e8-8720-d9d45d263181.png)

Samphire tower, Dover England
https://www.openstreetmap.org/?mlat=51.1056&mlon=1.275&zoom=17
![samphire-tower-z17-black](https://user-images.githubusercontent.com/42757252/48452621-4aa1ff80-e7f3-11e8-8956-87d2726cf637.png)

Diamond Head Lighthouse, Honolulu
https://www.openstreetmap.org/?mlat=21.256944&mlon=-157.809444&zoom=17
![](https://user-images.githubusercontent.com/42757252/48302781-5fa53700-e544-11e8-99d5-3f69683d8fbc.png)

**Comment by jeisenbe** [comment]
I believe man-made-icon 15% darkened looks the best, but 10% could also work.

_Test area 1:_
Current rendering, z17
![tower-labels-1-before](https://user-images.githubusercontent.com/42757252/48453015-0152af80-e7f5-11e8-89dc-b5bf078c9712.png)
Man-made-icon 10% darker (except wayside cross)
![tower-labels-10darker](https://user-images.githubusercontent.com/42757252/48453021-0879bd80-e7f5-11e8-980d-7b46ef476793.png)
Man-made-icon 15% darker (except wayside cross)
![tower-labels1-15darker](https://user-images.githubusercontent.com/42757252/48453037-192a3380-e7f5-11e8-9709-c1bb91e77403.png)

_Test area 2:_
Current
![tower-labels-2-before](https://user-images.githubusercontent.com/42757252/48453067-3959f280-e7f5-11e8-8093-3c292c27526b.png)
10% Darkened
![tower-labels-10darker-2](https://user-images.githubusercontent.com/42757252/48453086-4971d200-e7f5-11e8-8e88-92ebc84cde24.png)
15% Darkened
![tower-labels-2-15darker](https://user-images.githubusercontent.com/42757252/48453089-4d9def80-e7f5-11e8-955d-d074b1c48d09.png)

_Samphire tower:_
Current
![](https://user-images.githubusercontent.com/42757252/48452621-4aa1ff80-e7f3-11e8-8956-87d2726cf637.png)
10%
![samphire-darken10](https://user-images.githubusercontent.com/42757252/48453124-6d351800-e7f5-11e8-9c4f-a94655633799.png)
15%
![samphire-darken15](https://user-images.githubusercontent.com/42757252/48453128-71613580-e7f5-11e8-98c4-a765aa9d9829.png)
man-made-icon (0% darker):
![samphire-tower-gray](https://user-images.githubusercontent.com/42757252/48453154-8e960400-e7f5-11e8-8e82-aabb6e84bd45.png)

_WRC and WKYS towers in Washington, DC_
Current black
![wrc-wkys-black](https://user-images.githubusercontent.com/42757252/48453202-b1281d00-e7f5-11e8-85dc-232627d4722d.png)
10%
![wrc-wkys-darken10](https://user-images.githubusercontent.com/42757252/48453201-b1281d00-e7f5-11e8-825e-0352f437a665.png)
15%
![wrc-wkys-darken15](https://user-images.githubusercontent.com/42757252/48453193-aa99a580-e7f5-11e8-8918-78380f7fd2f7.png)
man-made-icon gray
![wrc-wkys-gray](https://user-images.githubusercontent.com/42757252/48453205-b2f1e080-e7f5-11e8-93e3-ec306fd9495c.png)

_WDCU in Washington, DC_
Current black
![wdcu-black](https://user-images.githubusercontent.com/42757252/48453287-0cf2a600-e7f6-11e8-86e5-d21cfe1233e1.png)
10%
![wdcu-darken10](https://user-images.githubusercontent.com/42757252/48453283-095f1f00-e7f6-11e8-98f5-344b4814c03d.png)
15%
![wdcu-darken-15](https://user-images.githubusercontent.com/42757252/48453278-06fcc500-e7f6-11e8-87db-07b2492e2e22.png)
man-made-icon gray
![wdcu-gray](https://user-images.githubusercontent.com/42757252/48453281-082df200-e7f6-11e8-98f7-c9cfd99a63c1.png)

_Diamond Head Lighthouse, Hawaii_
man-made-gray (current rendering):
![diamond-head-gray](https://user-images.githubusercontent.com/42757252/48454560-fdc22700-e7fa-11e8-8310-df49b9bac6e8.png)
10% darker
![diamond-head-darken10](https://user-images.githubusercontent.com/42757252/48454255-edf61300-e7f9-11e8-80bb-6acaa7b0ca06.png)
15% darker
![diamond-head-darken15](https://user-images.githubusercontent.com/42757252/48454256-edf61300-e7f9-11e8-8fb5-a84bebb7f56b.png)
Black
![diamond-head-black](https://user-images.githubusercontent.com/42757252/48454253-ecc4e600-e7f9-11e8-8d6d-a452a7212ef6.png)

**Comment by jeisenbe** [comment]
I've also noticed that the text-dy for lighthouses is 16, versus 10 to 12 for most others. I would like to reduce it to 12:
Before (text-dy-16)
![](https://user-images.githubusercontent.com/42757252/48454256-edf61300-e7f9-11e8-8fb5-a84bebb7f56b.png)
After (text-dy-12)
![lighthouse text-dy-12](https://user-images.githubusercontent.com/42757252/48454604-34983d00-e7fb-11e8-81d1-a1921a831961.png)

**Comment by daganzdaanda** [comment]
IIRC, text-dy was first tested with a string like ÉÉÉÉÉÉÉÉÉÉÉ. Also IIRC, we found later that there were problems with other languages that use a lot of diacritics stacked on top of each other. That's why we have such large text-dy with most icons. 
I would love to see icons and text closer to each other, but I think we do have to find a way around the potential problem in other scripts. Maybe there's a way to align the top of the label to the bottom of the icon or vice-versa (I'm assuming right now it's using the baseline or the x-height?)

**Comment by jeisenbe** [comment]
Thank you for the suggestion, I've tested with ÉÉÉÉÉ now, and an emoji symbol. 

Before
![lighthouse before](https://user-images.githubusercontent.com/42757252/48487429-94c1ca00-e861-11e8-82e7-1d088a0e3d58.png)

After
![lighthouse after](https://user-images.githubusercontent.com/42757252/48487447-9c816e80-e861-11e8-86f9-84073305c255.png)

I believe text-dy 12 will work for the lighthouse icon. 
10 to 12 is used for most other similar icons. A few use text-dy 13, but none use 14, 15 or 16 except for the lighthouse.

**Comment by Adamant36** [comment]
It would be good if stuff like that was as uniform as possible so more features can be combined in the code. As it there's a lot of fragmentation there. Id bet making a lot of this type of stuff more uniform wouldn't make a huge difference in how they are rendered either.
