### ISSUE TITLE
bring the Canada label down

### ISSUE THREAD

**Issue by brandoncote** [gravitystorm/openstreetmap-carto#3524]
issue: the Canada label is placed in the middle of the northernmost admin division of canada (also the least populated admin division)

suggestion: the population distribution of a country should have some pull/influence over the country label's position

**Comment by kocio-pl** [comment]
This style is not controlling positions of labels, it's done by Mapnik (the cartographic "engine" we use). It tries to find the biggest area of a polygon and if possible pull it toward so called centroid. You can read more about it here: https://github.com/mapnik/mapnik/pull/3811.

**Comment by pnorman** [comment]
This is not doable in any reasonable way without special casing.
