### ISSUE TITLE
Test more admin border colors

### ISSUE THREAD

**Issue by vholten** [gravitystorm/openstreetmap-carto#3526]
In #3489 @kocio-pl discussed changing the color of admin borders, and tested the look of dark violet borders. He mentioned two other possibilities: 
1. Gray with a green tint, used by the German fork and @imagico's fork
2. Plain gray, tested by @kocio-pl in #2695

I prefer to avoid anything involving violet for the borders, see also @Tomasz-W's comment https://github.com/gravitystorm/openstreetmap-carto/issues/3489#issuecomment-439676660
Here I test the results of the other two options, specifically:
1. The German-style gray with a green tint `#50705a`, with a slightly darker `#445f4d` for low zooms (z<8)
2. Plain gray `#646464` which is a desaturated version of the German-style color, with a slightly darker `#555555` for low zooms (z<8), which is the same color that @kocio-pl tested in #2695.

In addition, I feel that two other changes are beneficial:
* With gray or almost gray borders, the country labels would be shown in black and therefore in the same style as city labels. To distinguish country labels from the city labels I've made them bold.
* The second change is related to the line width of level 2 (international) borders. This line width jumps from 2 to 6 pixels between zoom 9 and 10, and I have made the change more gradual (see graph).

![linewidth](https://user-images.githubusercontent.com/5209216/48960640-8b75e300-ef6e-11e8-9f3e-3371295489df.png)

z4 before
![z4osm](https://user-images.githubusercontent.com/5209216/48960919-04763a00-ef71-11e8-8349-34cabfda8c83.png)

z4 German-style color
![z4ger](https://user-images.githubusercontent.com/5209216/48960927-12c45600-ef71-11e8-9c00-a10559be3d84.png)

z4 gray
![z4gray](https://user-images.githubusercontent.com/5209216/48960932-17890a00-ef71-11e8-9194-cc5a8a9fb91b.png)

z6 before
![z6osm](https://user-images.githubusercontent.com/5209216/48960945-3f786d80-ef71-11e8-9692-1ee515ec8efc.png)

z6 German-style color
![z6ger](https://user-images.githubusercontent.com/5209216/48960948-43a48b00-ef71-11e8-9bb6-433fb7d5ae5d.png)

z6 gray
![z6gray](https://user-images.githubusercontent.com/5209216/48960950-47d0a880-ef71-11e8-891c-1d50388f503b.png)

z8 before
![z8osm](https://user-images.githubusercontent.com/5209216/48960953-4c955c80-ef71-11e8-9741-5a72adfbb0c4.png)

z8 German-style color
![z8ger](https://user-images.githubusercontent.com/5209216/48960954-5028e380-ef71-11e8-92c8-e7e5f9633375.png)

z8 gray
![z8gray](https://user-images.githubusercontent.com/5209216/48960959-5323d400-ef71-11e8-99af-f10609a6a86d.png)

z10 before
![z10osm](https://user-images.githubusercontent.com/5209216/48960960-57e88800-ef71-11e8-970b-3c9073482049.png)

z10 German-style color
![z10ger](https://user-images.githubusercontent.com/5209216/48960961-5c14a580-ef71-11e8-8898-82634c6b5242.png)

z10 gray
![z10gray](https://user-images.githubusercontent.com/5209216/48960962-5fa82c80-ef71-11e8-8d8c-bb48a92ecbe0.png)

z13 before
![z13osm](https://user-images.githubusercontent.com/5209216/48960965-62a31d00-ef71-11e8-8b7c-dc478279b928.png)

z13 German-style color
![z13ger](https://user-images.githubusercontent.com/5209216/48960968-6636a400-ef71-11e8-9102-5074abe41c72.png)

z13 gray
![z13gray](https://user-images.githubusercontent.com/5209216/48960969-6898fe00-ef71-11e8-995a-13f61da843f7.png)

**Comment by kocio-pl** [comment]
Thanks a lot for such careful testing of this version!

I like the idea of grey borders, I also agree with making countries names bold. The color is less disturbing than violet and (dark) green, while this is still possible to distinguish city names form country and state names. It also gives a map subtle visual dynamic.

It sounds good to change the width of borders more smooth, but in practice I like bold grey borders on z10 more than new ones (with tuned width).

**Comment by jeisenbe** [comment]
I like the slightly greenish gray borders aka German style. They look gray
at first glance , but the hint of green helps distinguish the borders from
other gray lines on the map.

Re “in practice I like bold grey borders on z10 more than new ones”

Perhaps the transition can happen sooner.
Eg admin_level=2 borders could be 2.5 wide at z7, 3.5 at z8, 4.5 at z9, and
5.5 at z10?

**Comment by kocio-pl** [comment]
@vholten Could you give a link so I could test both versions? Visually I like grey more, but maybe we need some tint to make it easier to recognize. Maybe just a mix between these two versions would work. However I feel we're pretty close to the proper rendering of borders now. I like the idea of making them a bit darker on low zooms, we can tune it too.

> Perhaps the transition can happen sooner.

Maybe you're right, it's worth checking.

**Comment by Tomasz-W** [comment]
@vholten Looks very promising (both dark-green and gery), can you provide some high-zoom examples, espesially of dark-green borders crossing with protected area boundaries and gray borders crossing with power lines?

Examples of a places to test:
https://www.openstreetmap.org/#map=16/52.2837/20.3812
https://www.openstreetmap.org//#map=14/52.2336/20.5584

**Comment by jeisenbe** [comment]
It would also be good to see some boundaries that follow rivers, and some
that have track roads on the border or closely parallel.

**Comment by jeisenbe** [comment]
This issue was more of a [WIP] PR - which continued in PRs #3666 and #3716. There is a previous issue #3489 "Change the colors of admin borders" so this issue can be closed as a duplicate
