### ISSUE TITLE
Add dedicated icon for memorial benches

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3527]
Continuation of unfinished https://github.com/gravitystorm/openstreetmap-carto/pull/3356.

As memorial benches has partly simple amenity character and partly memorial character, both `bench` and `memorial` icon don't show their character properly.

Proposal is to render combination of `amenity=bench` + `historic=memorial` by dedicated icon in _amenity-brown_:

![memorial bench](https://user-images.githubusercontent.com/25656654/48966398-18ea1f00-efd1-11e8-9b98-d0ea186f3e70.png)

Gist link: https://gist.github.com/Tomasz-W/9ad756936dab43da9383c6586551e2e0

This change was actually approved in https://github.com/gravitystorm/openstreetmap-carto/issues/3088 but there was some technical dificulties in a bigger PR back then, so I'm opening this ticket to not forgot about this remaining part. 

@jragusa I'm mentioning you as you were an author of original memorial subtags PR.

**Comment by jragusa** [comment]
I tried again to resolve this problem but it does not work :/ With the code below, it leaves the generic memorial icon

```
  [feature = 'historic_memorial'][zoom >= 17] {
    [feature = 'amenity_bench'] {
      marker-file: url('symbols/historic/memorial_bench.svg');
      marker-fill: @memorials;
      marker-placement: interior;
      marker-clip: false;
    }
  }
```
I have also tried adding bench in dedicated `amenity_` section in `project.mml` and add condition as following:

```
  CASE 
    WHEN historic IN ('memorial')
      AND amenity IN ('bench')
      THEN 'yes' ELSE 'no' 
  END AS memorial_bench,
```
```
  [feature = 'historic_memorial'][zoom >= 17] {
    [memorial_bench = 'yes'] {
      marker-file: url('symbols/historic/memorial_bench.svg');
      marker-fill: @memorials;
      marker-placement: interior;
      marker-clip: false;
    }
  }
```
But it leaves the generic `bench` icon.

The best answer would be to have `historic = memorial` + `memorial = bench`

**Comment by polarbearing** [comment]
please fix typo in title

**Comment by Adamant36** [comment]
@jragusa, do we know what the number of memorial benches tagged are out there? TagInfo says there's 59 uses of memorial=bench. I couldn't find any information on the combination of historic=memorial + amenity=bench though. But memorial benches aren't listed on either of their wiki pages. 

It might worth asking in the tagging mailing list, or the memorial discussion page, and closing this issue until its actually decided whats best to use.

**Comment by jeisenbe** [comment]
The combination `amenity=bench` + `historic=memorial` is only [used 220 times](http://overpass-turbo.eu/s/M5i). This does not require a unique icon at this time. I'm closing this issue for now.
