### ISSUE TITLE
Make @placenames-light colour darker

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3537]
Current @_placenames-light_ colour is a `#777777` which is quite light one.

It causes some problems with admin areas labels visibility. Examples:

* unintuive districts names lost in grey resideltial areas (paradoxially, when you zoom it out, it looks much better):
https://www.openstreetmap.org/#map=14/50.0353/22.0072
https://www.openstreetmap.org/#map=14/54.3477/18.6205
* neighbourhoods names lost in well-mapped-area
https://www.openstreetmap.org/#map=15/52.3856/16.9564
* main village less prominent than its sub-villages:
https://www.openstreetmap.org//#map=15/52.4734/20.4740

I propose to change it to `#555555`

**Comment by Adamant36** [comment]
#555555

Gdansk before
![placenames gdansk before](https://user-images.githubusercontent.com/30259065/50371989-9a09e700-057a-11e9-848a-b40a0aba9a74.png)
Gdansk after
![placenames gdansk after](https://user-images.githubusercontent.com/30259065/50371993-b0b03e00-057a-11e9-8d59-e7f2a8dcd005.png)
Poznan before
![poznan before](https://user-images.githubusercontent.com/30259065/50371998-c0c81d80-057a-11e9-9230-952e917852ae.png)
Poznan after z14
![poznan after z14](https://user-images.githubusercontent.com/30259065/50372003-d76e7480-057a-11e9-981a-ca02925eca15.png)
Poznan after z16
![poznan after z16](https://user-images.githubusercontent.com/30259065/50372005-e48b6380-057a-11e9-98b0-caab8aa3cd2d.png)
Looks good to me.

**Comment by Tomasz-W** [comment]
@Adamant36 As cities, streets etc. names are dark black, I think we could use even a minimally darker shade here, can you try with `#4c4c4c`?

**Comment by Adamant36** [comment]
Here you go. I actually thought of 3c3c3c for some reason and I think its the best. Followed by 404040.
#4d4d4d Rzeszow
![4d4d4d rzeszow](https://user-images.githubusercontent.com/30259065/50378531-42569480-05e9-11e9-8ce3-ada06f4aee01.png)
#404040 Rzeszow (slightly better)
![404040 rzeszow slightly better](https://user-images.githubusercontent.com/30259065/50378532-4e425680-05e9-11e9-80f0-16b28a540e9e.png)
3c3c3c Rzeszow (best)
![3c3c3c rzeszow best](https://user-images.githubusercontent.com/30259065/50378534-569a9180-05e9-11e9-95d1-d5a1a714dfe9.png)

**Comment by Tomasz-W** [comment]
@Adamant36 If you see some difference between `#3c3c3c` and `#404040` you propably have some 'placebo' effect ;) , because it's only 1% of difference between them (first one is H:0, S:0, L:24 and second one H:0, S:0, L:25). `#4d4d4d` is also good and ok for me, so you can post more test renderings of different locations here or test it more on you own and choose the best one for PR also on your own.

**Comment by Adamant36** [comment]
@Tomasz-W, it might be that, or eye strain from all this squinting at hardly noticeable things I've been doing lately. Whatever it is, I'm fine with whatever color you think is best and round numbers are always better ;) 

I'm also happy to do more tests though. I just wish Poland loaded faster. Its way to detailed.

**Comment by kocio-pl** [comment]
The difference between these shades is really small even when I do a switch-a-tab comparison in my browser (which is more rigorous than it will be in the real life), so I'm fine with any of that.

**Comment by kocio-pl** [comment]
@matthijsmelissen Since you have rejected ticket implementing it (#3590) do you think this issue ticket should stay open for possibly better implementation or it is not doable and it should be closed too?

**Comment by jeisenbe** [comment]
> If there is a solution, I suspect it will include a more general rework of the place labels

In that case, I will close this issue, since it is a quite specific request to make the placename-light color darker, which was rejected in #3590 (I agree with @matthijsmelissen on this). 

If there are ideas to rework the place labels more generally, that can be discussed in a new issue.
