### ISSUE TITLE
hedge rendered on top of a bridge

### ISSUE THREAD

**Issue by bdxd111** [gravitystorm/openstreetmap-carto#3546]
https://www.openstreetmap.org/#map=19/51.57790/5.09033

In the above situation there is a bridge with a hedge crossing it underneath. The hedge, tagged with `barrier=hedge` and `area=yes` is rendered on top of the bridge. I would expect the bridge to be drawn on top of the hedge like it does with other land areas. I dont know if this is intentional due to the `barrier` tag? 

### Links and screenshots illustrating the problem
![hedge-bridge](https://user-images.githubusercontent.com/14345606/49333241-6e1ec580-f5bb-11e8-9208-6864b13f341e.PNG)

**Comment by matkoniecz** [comment]
The same issue as #3203. 

It is partially effect of that it was significantly simpler to implement it this way and partially because alternatives - transparency or completely not displaying features under bridge is not better than the current solution.
