### ISSUE TITLE
Render name of railway station with suffix "역" in Korea region.

### ISSUE THREAD

**Issue by wodndb** [gravitystorm/openstreetmap-carto#3549]
Koreans are familiar to spell name of railway station with a "-역(station)" and station name with "-역" is convention of web maps in South Korea. However, almost of station names in OSM has no word 'station' or similar words(except building names). and also, official Korean name of station has no "-역(station)". 

So I survey Korean railway station name for OSM contributors.
(https://docs.google.com/spreadsheets/d/16o5ub9mjA2henfT0obZJ4HWukPS78QEHAjzDHn4pjkQ/edit#gid=871323506)

80 percent of people who participated the survey want to put the suffix "역" to name of railway station. I questioned about this to OSM forum. (https://forum.openstreetmap.org/viewtopic.php?id=64609) and I get a response that name is only name and Mapnik or other rendererers could be programmed to add this suffix at the end of the name when rendering Korean names stations.

Can openstreetmap-carto render name of railway station with the suffix "역"?

**Comment by kocio-pl** [comment]
I'm not sure how it should be handled. Technical question first - how could we detect which stations should we apply it to?

**Comment by wodndb** [comment]
I try hard to read the source code here but I can't fully understand.

If this renderer can check Hangul Syllables which is set in unicode block(U+AC00–U+D7AF), we can detect station. Hangul is only used in South and North Korea. Yanbian Korean Autonomous Prefecture and Changbai Korean Autonomous County also use hangul but they mainly use Chinese character.

**Comment by kocio-pl** [comment]
I have the idea that maybe we could compare if `name:ko` value is the same as in `name` tag? I guess this would both avoid false positives and make tagging more complete.

**Comment by jragusa** [comment]
The [wiki](https://wiki.openstreetmap.org/wiki/Names) says for `name` tag: "The common default name". So I suppose you can add the suffix "-역" in the name tag and leave as it in the `official_name` tag.

**Comment by wodndb** [comment]
@kocio-pl You're right. I should make more detail condition to detect station.

**Comment by wodndb** [comment]
@jragusa official_name tag is for country name.

**Comment by kocio-pl** [comment]
I believe that is for everything that has official name.

**Comment by wodndb** [comment]
@kocio-pl @jragusa I will ask this to OSM forum and community. Thanks.

**Comment by polarbearing** [comment]
The style shows cartographically that it is a station, by picking the appropriate symbol. Thus adding such suffix I would consider redundant.
