### ISSUE TITLE
Beach pattern doesn't render in some areas

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#3554]
beaches should render with a sand pattern.

some beaches aren't rendering with a sand pattern. 

https://www.openstreetmap.org/#map=17/37.77149/-122.51049 (location 1)
![beach location 1](https://user-images.githubusercontent.com/30259065/49689917-55437200-fadd-11e8-9db0-f717426f18e8.png)

https://www.openstreetmap.org/#map=17/37.80577/-122.46216 (location 2)
![beach location 2](https://user-images.githubusercontent.com/30259065/49689922-612f3400-fadd-11e8-8d0c-51d9e2973cb1.png)

I don't what the deal is. The tagging doesn't seem to be any different then the other beaches in the area. Which render properly. If it was a tagging issue though id think it wouldn't render at all, not just leave pattern out. It might be something to do with the latest version of the map. I'm pretty sure I had looked around that area before it came out and I didn't notice the problem back then. 

(after looking around more, it seems to be a common problem along the California coast. While some beaches render fine. A lot of them don't)

**Comment by meased** [comment]
The sand pattern is only rendered when tagged with `surface=sand`. This is consistent with other beaches in the area.

**Comment by Adamant36** [comment]
Not according to this in the landcover file 
   
```
 [natural = 'beach'],
    [natural = 'shoal'] {
      [surface = 'sand'] {
        polygon-pattern-file: url('symbols/beach.png');
        polygon-pattern-alignment: global;
```
Otherwise, it should be called sand.png instead of beach.png

**Comment by kocio-pl** [comment]
As far as I know @meased is right. The name could be improved (maybe `grain.ong`).

Anyway it could be good if you provide links to both beach rendering examples.

**Comment by Adamant36** [comment]
How come it has the code to be rendered with a pattern in the landcover file and also a picture of it rendered with the pattern on the wiki then? 

There's links to after examples in my original message. I don't have any before renderings unfortunately. Maybe I just spaced it and it was never rendered with a pattern, but I'm sure I would have noticed it and the evidence in the code and on the wiki makes me think otherwise. Unless the code and wiki is wrong. Which is possible.

**Comment by jeisenbe** [comment]
In the western USA it is common to think of beaches as sandy

But in Britain many named beaches are covered in pebbles or cobbles.

In some places soft-bottom coastlines with silt and clay (ie mud) are also
called beaches.

So there needs to be a surface tag used with beach to specify sand,
pebbles, mud etc.

**Comment by kocio-pl** [comment]
Some wiki review might be good, I believe. Most probably this is not a rendering problem.

**Comment by Adamant36** [comment]
It seems there's a PR from 2015 about rendering beaches without patterns #1990. My bad. I'm not crazy, I swear. I guess someone should update the wiki at least. 

@jeisenbe, I know not all beaches are sandy, but why render it in yellow then? Since mud etc isn't yellow.  Seems like it should be a neutral color and rely on the patterns instead, if it can be any color in real life.
