### ISSUE TITLE
Render emergency=control_centre

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3556]
Emergency Control Centers (the place you reach when you call 112 in Europe) should be rendered.

**Tagging:** ```emergency=control_centre```

Icon suggestion
----
![image](https://user-images.githubusercontent.com/2878623/49696140-ad45ab80-fba5-11e8-9b27-322355d41ac5.png)

**Comment by HolgerJeromin** [comment]
Thanks for your suggestion
But we have only about 220 objects, no wiki page. Far too early to render imo

https://taginfo.openstreetmap.org/tags/emergency=control_centre#overview

**Comment by dktue** [comment]
It's due to the nature of this tag that there won't be many ever. Those are not ambulance stations but control centers that are responsible for vast areas.

**Comment by kocio-pl** [comment]
Their nature is also that they are not directly usable by physical presence, it's a phone service. In fact this is kind of office, so maybe this would work. The icon needs to be much smaller than your example anyway, we use 14 px matrix which makes many icons look bad.

**Comment by matkoniecz** [comment]
Combined lack of documentation and extremely low usage disqualifies it.

https://duckduckgo.com/?q=emergency%3Dcontrol_centre+osm+wiki&t=canonical&ia=web
https://taginfo.openstreetmap.org/tags/emergency=control_centre
https://wiki.openstreetmap.org/w/index.php?search=emergency%3Dcontrol_centre&title=Special:Search&go=Go

**Comment by dktue** [comment]
@kocio-pl : I tried with paint, but I'm not very skilled. 😬 

![image](https://user-images.githubusercontent.com/2878623/49698239-564dcf80-fbc1-11e8-97c8-b466242b5bc3.png)

**Comment by matkoniecz** [comment]
Please comment here once it is documented somewhere on the OSM Wiki what it is.

**Comment by polarbearing** [comment]
The icon could be for any call centre, there is nothing emergency-specific.
