### ISSUE TITLE
Render service=emergency_access thinner

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#3557]
```highway=service``` and ```service=emergency_access``` should be rendered thinner like ```highway=service``` and ```service=driveway``` are already.

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/tags/service=emergency_access has decent use

**Comment by kocio-pl** [comment]
It's also documented and steady growing. What about other `service=*` values, could someone review them?

https://taginfo.openstreetmap.org/keys/service#values

https://wiki.openstreetmap.org/wiki/Tag%3Aservice%3Demergency_access

![taghistory 32](https://user-images.githubusercontent.com/5439713/49700801-cf5e1e80-fbe3-11e8-84a3-7c3255293159.png)

**Comment by dieterdreist** [comment]
sent from a phone

> On 9. Dec 2018, at 18:15, Mateusz Konieczny <notifications@github.com> wrote:
> 
> https://taginfo.openstreetmap.org/tags/service=emergency_access has decent use


is it another way to say “driveway” in a case where there is a sign “emergency access” (e.g. Feuerwehrzufahrt in Germany)? Seems so...

**Comment by dktue** [comment]
@dieterdreist : In my opinion ```driveway``` may be occupied by residents while ```emergency_access``` must never by occupied by anybody.

**Comment by polarbearing** [comment]
I see no reason why the emergency access should be treated as a minor service road. 
Only larger objects would have a signposted emergency access road, thus it would be a major service road.

**Comment by dktue** [comment]
@polarbearing : Here's an example

https://www.openstreetmap.org/#map=19/48.52646/9.06252
![image](https://user-images.githubusercontent.com/2878623/49734601-0fc1a900-fc85-11e8-9dd7-ebad33dd9f64.png)

**Comment by matkoniecz** [comment]
@polarbearing Can you give an example of service=emergency_access that should not be treated as a minor driveway?

**Comment by polarbearing** [comment]
I take dktue's example above. An emergency access must logically be reachable from the main road, thus it is a tagging error to have it sitting isolated north of the building.

**Comment by dieterdreist** [comment]
Am Mo., 10. Dez. 2018 um 14:53 Uhr schrieb polarbearing <
notifications@github.com>:

> I take dktue's example above. An emergency access must logically be
> reachable from the main road, thus it is a tagging error to have it sitting
> isolated north of the building.
>

I agree with the tagging error assessment, this way:
https://www.openstreetmap.org/way/233295884
has the emergency access tag, hence all ways from the main road to this way
must also get it, currently they don't:
e.g. https://www.openstreetmap.org/way/233295883

**Comment by matkoniecz** [comment]
If Wiki is clearly wrong - just edit it.

If discussion is needed - ask on OSM Wiki talk page or on tagging mailing list.

**Comment by SilentSpike** [comment]
I've had some confusion with this tag in the past and I've considered proposing that it should be rendered differently, but wasn't sure what to suggest.

I've personally only encountered it [here](https://www.openstreetmap.org/way/423231780). The relevant [wiki page for fire paths](https://wiki.openstreetmap.org/wiki/Fire_Path) suggests use of the `service=emergency_access` tagging for those which look like the second image shown. It just so happens that image was taken in this city and the fire paths around here all look exactly like that (including the one I've linked).

Now, to me looking at that on the ground that's clearly not a highway you would ever use. However, on the map rendering this isn't obvious and it looks like any other service road which could lead someone to thinking their is a connection there that they can take.

**Comment by polarbearing** [comment]
@SilentSpike - these are different things. 
emergency_access is a situation where a service road, that can be used normally, must not be blocked e.g. by parking on it, because firefighters would need it to get close to a building with a high density of people living/working in it. 
The fire_path on the first and second wiki pictures are situations where only emergency vehicles might pass (thus restricted access).

**Comment by polarbearing** [comment]
As we have not found reasons why service=emergency_access should be considered 'minor' and rendered thinner, I propose to close the issue.

**Comment by matkoniecz** [comment]
> An emergency access must logically be reachable from the main road, thus it is a tagging error to have it sitting isolated north of the building.

It may be worth documenting at https://wiki.openstreetmap.org/wiki/Tag:service%3Demergency_access (and if https://github.com/gravitystorm/openstreetmap-carto/issues/3557#issuecomment-445809205 is correct then it also should be documented).

Closing for now, please comment if it turns out that correctly tagged service=emergency_access may branch out from hiway=service + service=driveway.
