### ISSUE TITLE
Move station=subway later

### ISSUE THREAD

**Issue by jragusa** [gravitystorm/openstreetmap-carto#3559]
### Expected behavior
Move `railway=station` + `station=subway` to z14 as well as `railway=tram_stop` (#3541)

### Actual behavior
Similar render than others `railway=station`

### Links and screenshots illustrating the problem
`z12`
before
![subway_before_z12](https://user-images.githubusercontent.com/9897203/49745742-f24e0880-fc9f-11e8-8127-e5e91b776319.png)
after
![subway_after_z12](https://user-images.githubusercontent.com/9897203/49745749-f67a2600-fc9f-11e8-9032-bc3e90cd4324.png)

`z13`
before
![subway_before_z13](https://user-images.githubusercontent.com/9897203/49745767-00038e00-fca0-11e8-8c22-79e991e54650.png)
master
![subway_master_z13](https://user-images.githubusercontent.com/9897203/49746425-7785ed00-fca1-11e8-9b30-be3476f2812b.png)
after
![subway_after_z13](https://user-images.githubusercontent.com/9897203/49745805-16114e80-fca0-11e8-89c8-ba80dab8f38e.png)

`z14` (no changes)
before
![subway_before_z14](https://user-images.githubusercontent.com/9897203/49745918-540e7280-fca0-11e8-87bb-a4f19a68aa10.png)
after
![subway_after_z14](https://user-images.githubusercontent.com/9897203/49745895-48bb4700-fca0-11e8-8d82-4c3f2722a78b.png)

**Comment by kocio-pl** [comment]
I thought it's not even worth separate issue ticket, just PR - unless you wanted something more fancy. :smile:

**Comment by jragusa** [comment]
Yes you're right, this what happens when you want to be too careful :)
