### ISSUE TITLE
Don't render "highway"=* + "area"="yes"

### ISSUE THREAD

**Issue by BjornRasmussen** [gravitystorm/openstreetmap-carto#3564]
The current rendering of `highway=*` + `area=yes` encourages people to map `area:highway=*` features as `highway=*` with `area=yes`, which is incorrect.  To fix this, `highway=*` + `area=yes` should no longer be rendered.  According to taginfo, there are 298,745 features tagged like this.

Examples: 
* https://www.openstreetmap.org/way/194428842
* https://www.openstreetmap.org/way/183205906
* https://www.openstreetmap.org/way/386587077
* https://www.openstreetmap.org/way/416470385
. . . and 298,741 others.

**Comment by kocio-pl** [comment]
Hi, please make the title of this ticket to be more precise.

Related to #180.

**Comment by HolgerJeromin** [comment]
Remapping this areas with linear ways seems not a really good idea:
https://www.openstreetmap.org/way/83148575#map=18/50.77707/6.07978
https://www.openstreetmap.org/way/32348177#map=19/50.77695/6.07982

But many of them have linear ways already:
https://www.openstreetmap.org/relation/905098#map=18/50.77597/6.08390 (and others south of this)

**Comment by matkoniecz** [comment]
Certainly not all highway=values are rendered for areas.

Can you list highway values that should be never rendered as areas and currently are referred as areas?

**Comment by aceman444** [comment]
highway+area=yes and highway:area seem to mean different things, so why should highway+area=yes not be rendered? Also highway:area is only an unapproved proposal on the wiki, so there is no reason to somehow base any decisions on it.

Also, in your examples, https://www.openstreetmap.org/way/194428842 actually looks like correct use of highway+area, it is not just the 2D shape of a single road. Also https://www.openstreetmap.org/way/386587077 looks questionable, I haven't looked at aerial imagery of the place.

**Comment by Adamant36** [comment]
I agree with aceman444 that any decision of rendering shouldn't be based on highway:area. Although they are both highway tags, it doesn't mean the use of one is related to the other. As they have different meanings and different use cases. At least, they should. Even if they didn't though, its not like they are or should be mutually exclusive.

**Comment by mboeringa** [comment]
> I agree with aceman444 that any decision of rendering shouldn't be based on **highway:area**. Although they are both highway tags, it doesn't mean the use of one is related to the other. As they have different meanings and different use cases. At least, they should. Even if they didn't though, its not like they are or should be mutually exclusive. There's nothing in the highway:area proposal that says it supersedes highway+area=yes. At least not that I could find.

The tag is **area:highway=x**, not _highway:area_, but you probably meant to write that ;-) :

https://wiki.openstreetmap.org/wiki/Proposed_features/area:highway

**Comment by Tomasz-W** [comment]
I would really like to choose one of the schemes for highway areas and go with it. 

Current situation is crazy: we have allowed but not documented scheme with "area=yes" which is still consequently added by one users (because it's rendered) and consequently reverted by second ones (because in opionion of some this tag is wrong) at the other hand we have second scheme of area:highway= which is simpler and documented, but as it's not rendered it's less popular.

https://wiki.openstreetmap.org/wiki/Tag:area:highway%3Dfootway

**Comment by kocio-pl** [comment]
In general I'm skeptic if we can stay with just one scheme. The days when OSM meant just adding new different are gone, now we have to deal with multiple schemes and balance when to use them.

**Comment by Tomasz-W** [comment]
`The two schemes have different meanings`

Can you describe meaning of both schemes and show the difference between them?

**Comment by polarbearing** [comment]
Yes.

```area:highway=*``` is proposed to describe the non-routable, detailed shape of a (typically linear) highway. It has some inconsistencies, e.g. some people map area:highway=emergency, where they mean to describe road areas that are painted with white hatching that should be avoided in normal traffic flow, but have nothing to do with emergencies. The tag requires the linear routable direction of the highway mapped as lines with highway=*. Mapping such area:highway is comparable to mapping riverbanks in addition to the linear river flow. 

```area=yes + highway=*``` describes an area on which the dedicated traffic can route omnidirectional. There are strong voices that argue that routing engines should consider those omnidirectional objects in addition to nodes+edges in classical graph theory; thus no linear highway lines would be required within.

**Comment by matkoniecz** [comment]
I am closing it as it is starting to degenerate into tagging dicussion and it is already partially implemented.

Certainly not all highway=values are rendered for areas.

Please open new issue that lists highway values that should be never rendered as areas and currently are rendered as areas (or open it for a just single higway value that is rendered for areas and should be never rendered for areas).

**Comment by matkoniecz** [comment]
In short "To fix this, highway=* + area=yes should no longer be rendered." is not a good solution. Some highway=* + area=yes are completely fine and not rendering them is not desirable (highway=pedestrian + area=yes for pedestrian squares is an example).

If there is some higway value that is rendered for areas and should be never rendered for areas - please open a new issue.

**Comment by Adamant36** [comment]
@mboeringa, yes that's what I meant. Thinks for the correction ;)

As far as the discussion goes, I've seen a few map apps render highway=* + area=yes. I haven't seen any render the other tag though. I think the rendering of the highway=* + area=yes is partly due to the fact that this map does, which works as a feedback loop for people to map things that way. So, while area=yes might not be documented or whatever it would be bad to base a rendering decision on that. Since its clearly in semi widespread use. Whatever the wiki details are.

**Comment by BjornRasmussen** [comment]
OsmAnd is currently the only software that renders `area:highway`. Anyway, I now know that there is a difference between `area:highway` and `highway` + `area=yes`.
