### ISSUE TITLE
Undocumented link roads should not render

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3566]
### Expected behavior
We previously rejected a request to render the undocumented tag residential_link. Similarly, unclassified_link, service_link and other undocumented "link" highways should not render. See #1280

### Actual behavior
All highway=xxx_link are currently being rendered the same as highway=xxx

Currently all highway=xxx_link are being rendered as highway=xxx, including residential_link, service_link and road_link. These features are also rendered above more important roads. 

This is a test area I created in JOSM, where I noticed the problem. Each of the small curving roads is a link (Left: road_link, bottom: residential_link, right: unclassified_link)

![links-master](https://user-images.githubusercontent.com/42757252/49942065-9c8b9180-ff27-11e8-8901-563ef3336224.png)

The current SQL query in project.mml for roads-casing and road-fill is:

```
            (CASE WHEN substr(feature, length(feature)-4, 5) = '_link' THEN substr(feature, 0, length(feature)-4) ELSE feature END) AS feature,
```

The result is that all highway_xxx_link are selected as highway_xxx, and currently render.

### Links and screenshots illustrating the problem

Test area showing all highway features and links being rendered. Each of the connecting, diagonal "highways" is in the form highway=xxx_link; eg highway=cycleway_link, highway=construction_link

![links2-master](https://user-images.githubusercontent.com/42757252/49942093-b0cf8e80-ff27-11e8-96ac-42947479b185.png)

**Comment by kocio-pl** [comment]
What do you think about just completing wiki documentation instead of removing rendering?

**Comment by jeisenbe** [comment]
This  is just a bug, not a proper rendering. The features were not added intentionally, so they render on top of other roads. And there certainly should not be a rendering for highway=cycleway_link, highway=construction_link and the others at the top of the image.

Previously it was noted that residential_link was only used 56 times, and service_link was used 0 times (in 2015 I believe). 

I suspect the numbers are still quite low, because links are supposed to use the classification of the highest road linked, so anything under tertiary_link is questionable. 

If anyone is in favor of properly rendering unclassified_link, residential_link or service_link, this should be discussed in #1280 or a new issue, I believe?

**Comment by matkoniecz** [comment]
Thanks for catching this!
