### ISSUE TITLE
Distinguish different cranes types

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3573]
Follow up for https://github.com/gravitystorm/openstreetmap-carto/issues/3478 and https://github.com/gravitystorm/openstreetmap-carto/pull/3501. Distinguish different cranes types to show people better what they can expect in certain place.

* `man_made=crane` + `crane:type=portal_crane`:
![](https://user-images.githubusercontent.com/25656654/47601256-31651a80-d9ce-11e8-8050-c997a67dd9ca.png)
* `man_made=crane` +` crane:type=floor-mounted_crane`:
![](https://user-images.githubusercontent.com/25656654/47602005-9d4c8080-d9d8-11e8-8bd1-bedc3bea63f5.png)  or  ![](https://user-images.githubusercontent.com/25656654/47602069-9114f300-d9d9-11e8-8b68-50c63a4f707c.png) (generic icon)
* `man_made=crane` + `crane:type=travel_lift` and `crane:type=gantry`:
![](https://user-images.githubusercontent.com/25656654/47601758-88222280-d9d5-11e8-9c98-c231d61e2a16.png)

Gist link: https://gist.github.com/Tomasz-W/ed6c01e147616e786faff2690fcce686

**Comment by matthijsmelissen** [comment]
This is going in too much detail for this stylesheet. Icons are meant to be pictograms, and do not need to be a literal depiction of the object in question.

**Comment by Adamant36** [comment]
@matthijsmelissen, you know that could apply to 99% of the icons being used right? For me its less about adding a  "literal depiction of the object" and more about incentivising sub tagging by giving the sub tags their own icons. Which I think this accomplishes. 

Also, I would venture that in a lot of cases people don't even know a sub tag exists or look it up on the wiki without it having unique icons. Personally, I wouldn't know about a lot of the sub-tags if there wasn't "to much detail" on the map by them having icons (different types of tourist information mediums comes to mind).

**Comment by sommerluk** [comment]
Let me add to what @matthijsmelissen said that the subtypes have all lower usage than 1000.

Closing as per @matthijsmelissen

**Comment by Adamant36** [comment]
@Sommerluck, crane:type=gantry has 864 uses. Alone I doubt that the extra 136 uses to get it to 1000 really matters, but since its being combined with crane:type=travel_lift which has 327 uses its over 1000. So I'll probably do a PR on it anyway even if this issue is closed. For good measure I'll add crane:type=portal_crane to it also since it has 991 uses. You and @matthijsmelissen can feel free to split hairs over the missing 9 uses in that case.
