### ISSUE TITLE
Mixed-up colours in new hospital icon (OSM Carto v4.18.0)

### ISSUE THREAD

**Issue by SelfishSeahorse** [gravitystorm/openstreetmap-carto#3587]
Hi,

it's a minor thing, but (one of) the hospital/healthcare symbol(s) usually is a red cross on white background, not a white cross on red background. The latter is the flag of Switzerland. 🇨🇭 (Other common hospital/healthcare symbols are a white H on blue background or the Rod of Asclepius (⚕).

**Comment by kocio-pl** [comment]
This is designed to be a cross-shaped hole in the red circle, which is not the same as in Switzerland flag (no more than red dot is similar to Japanese flag).

What colors do you think are mixed up? Could you give the link and a screenshot to show the problem?

**Comment by kocio-pl** [comment]
If I understand you, this ticket can be safely closed now, so I'll do it. If you need to discuss it further, just write here.
