### ISSUE TITLE
type=boundary, boundary=region: polygon versus line issue

### ISSUE THREAD

**Issue by mboeringa** [gravitystorm/openstreetmap-carto#3588]
### Expected behavior
**type=boundary, boundary=region, natural=mountain_range** tagged features imported as polygons.

### Actual behavior
I currently see osm2pgsql importing relations tagged as **type=boundary, boundary=region, natural=mountain_range** as line elements in the **planet_osm_line** table when using **openstreetmap-carto.style** and **openstreetmap-carto.lua** as style and tag transform script in the osm2pgsql command line statement, while I would expect these features to be imported as polygons in the **planet_osm_polygon** table. 

A prominent example is the entire Alps ending up as line strings in the planet_osm_line table, see screenshot.

Is this something that can be configured in the **openstreetmap-carto.lua** script, so as to have these imported as polygons, or is this an osm2pgsql issue? I looked over the lua script, but it is not really clear to me how to go about this, if possible.

Note that this issue is not so much about the **natural=mountain_range** tag, but rather I would expect any relation tagged with **type=boundary, boundary=region** to end up in the **planet_osm_polygon** table instead of **planet_osm_line**.

### Links and screenshots illustrating the problem
![afbeelding](https://user-images.githubusercontent.com/7635726/50372560-d49e6e80-05d0-11e9-8846-8260d7355cf9.png)

**Comment by mboeringa** [comment]
Hmm... I think I found the issue: the import was based on a Geofabrik "France" extract. Of course the French Alps are only a small part of the entire alpine region. It appears the Geofabrik extract only contains a part of the necessary relation members to build the polygon, see the screenshot. Hence the failure to build a proper polygon of this feature. 

![afbeelding](https://user-images.githubusercontent.com/7635726/50372804-7031de00-05d5-11e9-8047-6c732b31f89e.png)

**Comment by mboeringa** [comment]
I am currently going through a rather slow import of Europe. When that finishes with the Alps as polygons in the planet_osm_polygon table, I will close the issue.

**Comment by kocio-pl** [comment]
How did it go?

**Comment by mboeringa** [comment]
@kocio-pl : I am closing the issue. Took a bit longer to answer this, as I unfortunately had to restart my computer during the second import, requiring a third import attempt that now finished successfully. As anticipated, the Alps boundary relation imported fine as Polygon as part of the Geofabrik Europe extract, see screenshot:

![afbeelding](https://user-images.githubusercontent.com/7635726/50490721-edfb4c80-0a0e-11e9-9d5e-42972baeb13b.png)
