### ISSUE TITLE
Add rendering for leisure=track bridges

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3592]
We have leisure=track lines rendered, but there is no special rendering of them in combination with bridge=*.

Example place where it causes a problem:
https://www.openstreetmap.org/way/327635778

Adding bridge rendering would make this toboggan route more understandable.

**Comment by matkoniecz** [comment]
I started a new thread on tagging mailing list as result of reviewing related tagging: https://lists.openstreetmap.org/pipermail/tagging/2018-December/041618.html

**Comment by Adamant36** [comment]
@matkoniecz Although I doubt it, there might be other cases of tracks with bridges besides summer toboggans. Did you happen to do an Overpass query or anything to find out? I'm not sure its worth rendering if there are, but it might be worth checking anyway.

**Comment by matkoniecz** [comment]
280 globally without filtering out attraction=summer_toboggan http://overpass-turbo.eu/s/FtS

187 globally after filtering out http://overpass-turbo.eu/s/FtT

And many of them are clearly or almost certainly wrong: https://www.openstreetmap.org/changeset/66578888#map=16/1.2704/-70.2094&layers=N (fixed), https://www.openstreetmap.org/changeset/66578984#map=17/40.20070/-6.40566&layers=N (fixed), https://www.openstreetmap.org/note/1659541 , https://www.openstreetmap.org/note/1659545 and https://www.openstreetmap.org/way/135954930 (tagging for renderer)

**Comment by matkoniecz** [comment]
So I would classify it as "not worth doing".

I would have doubts with accepting ready PR due to increase in code complexity.

**Comment by jeisenbe** [comment]
It looks like the plan was to close this issue since it mainly affects `attraction=summer_toboggan`, but this feature isn't a `leisure=track` but more similar to roller coasters. Generally race tracks for cycling, running and dog or horse racing do not have bridges, so it would be quite rare for this to be useful. Closed.
