### ISSUE TITLE
healthcare=laboratory has no icon just a dot

### ISSUE THREAD

**Issue by 532910** [gravitystorm/openstreetmap-carto#3594]
Bad:
![bad](https://user-images.githubusercontent.com/14617699/50407653-ee1c0200-07ec-11e9-8f36-d0fdb38f79b8.png)

Good:
![good](https://user-images.githubusercontent.com/14617699/50407654-eeb49880-07ec-11e9-86ed-44c7850be594.png)

**Comment by polarbearing** [comment]
If you consider this style bad, why do you use it?

**Comment by Tomasz-W** [comment]
As we have a lot of things to show in OSM-Carto, we have to show some of them in simplest and less prominent possible way (e.g. by dots for healtcare and office objects or squares for public transport stops). If we would use dedicated icons for all features, map propably would look like this:

![](https://mhscattalk.com/wp-content/uploads/2017/05/791px-Plain-MMs-Pile.jpg)

**Comment by matkoniecz** [comment]
I changed the title to make this issue fixable. If some other tags should be rendered with icon - open an issue for them.

I considered closing this as `declined` and opening new one for just laboratory, but this version should be less confusing.

**Comment by thep** [comment]
> healthcare=laboratory has over a thousand uses and it could be something like a beaker (the container. Not the Sesame Street character). So that's a possibility at least.

I asked medical lab people and they said a microscope should represent their work best. A beaker or a flask could still be read as a chemical lab instead.

**Comment by Adamant36** [comment]
A side view of a microscope probably wouldn't be to hard of an icon to make. It would probably be easier to tell its a lab 
icon compared to a beaker also.

**Comment by jeisenbe** [comment]
Note that we cannot render anything tagged under the `healthcare=*` key until the next database reload. This could happen sooner rather than later, but someone will need to submit a PR which adds `healthcare=*` as a polygon key in the `openstreetmap-carto.lua` file. See #3611

**Comment by Adamant36** [comment]
> Note that we cannot render anything tagged under the healthcare=* key until the next database reload. This could happen sooner rather than later, but someone will need to submit a PR which adds healthcare=* as a polygon key in the openstreetmap-carto.lua file.

Hopefully done correctly in PR #4005

**Comment by imagico** [comment]
This issue in the current form is invalidated by #3731.  We should either close it or the issue opener should re-formulate it to adding rendering of healthcare=laboratory, see also #4402.

**Comment by jeisenbe** [comment]
Closing since the original concern is no longer valid
