### ISSUE TITLE
highway=motorway_junction labels should change color based on ways present

### ISSUE THREAD

**Issue by Roadsguy** [gravitystorm/openstreetmap-carto#3595]
Currently, name and ref labels on motorway_junction nodes always render with motorway colors. This looks odd on trunk roads with numbered exits:

![](https://i.imgur.com/QeGSiA6.png)

(Even in the U.S, I'm unaware of any numbered exits on roads mapped as primary or lower, so that shouldn't be an issue.) A simple solution could be creating a trunk_junction tag and rendering it, but this would require changing many tags. It seems like it would be easier to have the color of the label change to that of the highest priority way at the node. An ideal priority chain could be "motorway, trunk, primary, secondary, motorway_link, trunk_link, primary_link." This way the above pictured example would render with trunk colors, as would Exit 39 shown below:

![](https://i.imgur.com/BREBW5Q.png)

A trunk road splitting into two motorway_link ways with a numbered exit would be colored trunk. A trunk road becoming a motorway at a numbered exit would be colored motorway.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_junction mentions that it is perfectly fine to use them on `trunk` and `primary` where applicable and I see no value in creating new `trunk_exit1 tags.

Though at least for me current coloring is not really looking bad.

**Comment by jeisenbe** [comment]
Does anyone else think they need to change color to match the roads?

I believe it is technically feasible to adjust the rendering based on the
classification of the intersecting roads, but the SQL query might be a bit
complex.

**Comment by boothym** [comment]
The motorway_junction colour is a dark red which doesn't really match either motorway or trunk - and since the tag can be used on both I don't think there needs to be any colour change.

**Comment by pnorman** [comment]
I also don't see an issue with the current colour.
