### ISSUE TITLE
Add rendering for roller_coaster

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#3596]
The track should be mapped with [roller_coaster=track](https://wiki.openstreetmap.org/wiki/Tag:roller_coaster%3Dtrack). An example is [this](https://www.openstreetmap.org/way/209771601) and there are even more next door. A narrow black line should be drawn on the map. At the moment, unfortunately, many use railway=* to get the track  rendered. On the [Key:attraction](https://wiki.openstreetmap.org/wiki/Key:attraction)-page this is expressly disapproved (_Do not tag them as any railway!_). Since the track is meandering the name should not be placed here.
For the [attraction](https://wiki.openstreetmap.org/wiki/Tag:attraction%3Droller_coaster), another node or area should be drawn on which the name stands. The name should be added in black. You could also add tourism=attraction, but that would be too much importance to the roller coaster.

**Comment by kocio-pl** [comment]
I guess for this rare type of objects it's enough for rendering with 920 uses:

https://wiki.openstreetmap.org/wiki/Tag%3Aroller_coaster%3Dtrack

![taghistory 35](https://user-images.githubusercontent.com/5439713/50449738-71427280-0929-11e9-9249-9c00c7647eee.png)

**Comment by matthijsmelissen** [comment]
I think this is quite specialized, and I'm not sure about rendering it on a general purpose map.

**Comment by Adamant36** [comment]
@matthijsmelissen, personally id disagree. They aren't any specialized then other similar things like racing tracks or water slides that are already rendered. Also, they can take up fairly large areas, where you can't go under or around them safety reasons. So without rendering them your essentially advocating for large blank spots, that look like places people can go when they aren't.

**Comment by pkoby** [comment]
> On the [Key:attraction](https://wiki.openstreetmap.org/wiki/Key:attraction)-page this is expressly disapproved (_Do not tag them as any railway!_).

The https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dtheme_park#Related_tags page lists railway=narrow_gauge as what is to be used until railway=roller_coaster is a thing. So I guess one of those pages should change (probably this one?).

**Comment by HolgerJeromin** [comment]
They are quiet big and good for orientation.
A full mapped theme park would look empty without a rendering.

**Comment by polarbearing** [comment]
Summer toboggan #3436 and Rollercoaster #3596 should be considered together. The carriageway could be rails, an ice or a water channel, for which all the same kind of line can be rendered.

Question is if we need an icon, and how the ground is rendered where the carriageway is built on.

**Comment by matkoniecz** [comment]
I would consider rendering track with one of railway styles. In the ideal world it would not be shown on general purpose map but unfortunately tagging for renderer is extremely popular here.

Unfortunately, it seems that choice is between "render roller coaster track" and "render roller coaster track mistagged as railway".

**Comment by meased** [comment]
We already render `railway=miniature`, and a roller coaster track pretty much is a miniature railway.

**Comment by jeisenbe** [comment]
> it seems that choice is between "render roller coaster track" and "render
roller coaster track mistagged as railway".

True. And roller coasters should not be rendered so early as railways. The
mistagged examples look very strange at mid-zoom levels.

**Comment by filips123** [comment]
@meased 

> Do not tag them as any railway!

As you said, a roller coaster track pretty much is a miniature railway. So you could just render `roller_coaster=track` similar to `railway=miniature`.

**Comment by jeisenbe** [comment]
I've looked into the use of [attraction=roller_coaster](https://wiki.openstreetmap.org/wiki/Tag:attraction%3Droller_coaster) and [roller_coaster=track](https://wiki.openstreetmap.org/wiki/Proposed_features/key:roller_coaster) in the context of deciding what tags to import as polygons during the next database reload. Both tags are frequently used to tag the tracks of roller coasters. Attraction=roller_coaster is mapped as an unclosed way 1,572 times (8-April-2019) and roller_coaster=track has 1483 uses on unclosed ways, so the two methods of tagging are about equally popular. 

For rendering the track there is no problem about the database, because ways are imported as linestrings by default. If we want to render the label of the attraction based on polygons, this would require a change, however.

I would recommend that @geozeisig reopen the proposal process for [roller_coaster=track](https://wiki.openstreetmap.org/wiki/Proposed_features/key:roller_coaster) with a RFC (request for comments) on the tagging mailing list, and then get it voted on. Then we might need to wait till roller_coaster=track is clearly the more popular choice (assuming that this is accepted by the community)

**Comment by jeisenbe** [comment]
I'd support using the same rendering at `railway=miniature` since both features are usually tourist attraction railways which loop around in a small area. That tag renders at z15 currently, but it's possible that roller coasters should not render until z16. This would need testing.

However, as I mentioned above, we should clarify if `roller_coaster=track` is the preferred mapping method for this feature, rather than using `attraction=roller_coaster` on the tracks.

**Comment by jeisenbe** [comment]
Now 2/3rds of ways are double-tagged with roller_coaster=track + `attraction=roller_coaster` - [2062 ways](http://overpass-turbo.eu/s/NYv) compared to 2800 unclosed ways for both tags individually. I'm not sure why they are being double-tagged in this way, @geozeisig do you know?

**Comment by geozeisig** [comment]
I can not explain it either. The wiki is clear. Now I asked a couple of people why they do it that way.
If roller_coaster=track not rendered I understand that railway=* is added. When the topic is solved we will have to revise the data again.

**Comment by geozeisig** [comment]
There are now more than 3,500 applications
![taghistory](https://user-images.githubusercontent.com/17127509/84351472-bdd04b00-abbb-11ea-82bf-6b66692ca9ae.png)

**Comment by DaveF63** [comment]
@geozeisig And that's only the correctly tagged ones. There are many falsely tagged as railway=miniature to force the rendering.

**Comment by Adamant36** [comment]
> @geozeisig And that's only the correctly tagged ones. There are many falsely tagged as railway=* to force the rendering.

There's 87 instances of `attraction=roller_coaster + railway=miniature`. Which isn't to many, but it would still help if they were tagged correctly and there's probably more out there without the attraction tag.

**Comment by Adamant36** [comment]
Hhhmmm, thanks. Roller_coaster=track is the clear favorite there and 5,166 uses should be enough to justify rendering it.

**Comment by spookypeanut** [comment]
I just noticed that a rollercoaster I added is not getting rendered, and that brought me here. Looks like the consensus is that it should be rendered, but doesn't look like it got any further (please correct me if either of these are not the case). I'm a bit of a dev (but have never looked into osm code), so I might consider figuring out how to create a PR for this if I get time

**Comment by mxxcon** [comment]
> I support the rendering of this feature. They are contained within specific areas so no overlapping with other 'general purpose' features. Miniature railways & waterslides, of similar size & locations are already rendered. Using the same render as railway=miniature way seems appropriate, but with a 'bridge' style edging to indicate it is elevated.

Apologies if I'm misunderstanding what you said but there are situations where a rollercoaster is not an exclusive feature at a given location. I know of rollercoasters that have food vendors and other attractions and features below the tracks. Additionally I know of a location that's building a rollercoaster intertwined with a log flume ride.

**Comment by DaveF63** [comment]
"'general purpose'"

**Comment by arminkollascheck** [comment]
Still not included? Why does the change to render roller coasters takes so long?

**Comment by pnorman** [comment]
> Still not included? Why does the change to render roller coasters takes so long?

There is no change that has been proposed - this is a feature request that no one has submitted a PR for.

**Comment by Nekzuris** [comment]
Any update?

**Comment by Roeliooo** [comment]
Hi Friends. What is the status of [roller_coaster=track](https://wiki.openstreetmap.org/wiki/Tag:roller_coaster%3Dtrack). Don't see it on the OSM map yet. Thanks.

**Comment by imagico** [comment]
#4666 has been merged but we have not made a release since then so the change is not yet visible in the map.
