### ISSUE TITLE
healthcare=rehabilitation on areas not rendered

### ISSUE THREAD

**Issue by geowas-github** [gravitystorm/openstreetmap-carto#3606]
Areas (closed ways) tagged healthcare=rehabilitation are not rendered.

https://www.openstreetmap.org/way/551730150
https://www.openstreetmap.org/way/644404595

However, there is a health care dot if the tag is on a building. 

https://www.openstreetmap.org/way/127701228

**Comment by Adamant36** [comment]
Where would healthcare=rehabilitation be tag on something as a way thats not a building? Can you provide a location of an example?

**Comment by geowas-github** [comment]
I added examples above. You were to fast ;)

In Germany there are rehabilitation centres which can be as big as hospitals (several buildings, parks, helicopter landing sites, etc. included).

**Comment by kocio-pl** [comment]
We have more problems with some areas rendered only with buildings. Looks like some areas are not imported into database when not using any of the popular tags.

**Comment by jeisenbe** [comment]
Do'h, I just opened a duplicate issue! The problem is that 'healthcare' is not in openstreetmap-carto.lua as a polygon

**Comment by kocio-pl** [comment]
I will close this one now as your ticket is more general.
