### ISSUE TITLE
healthcare=nurse not rendered at all

### ISSUE THREAD

**Issue by deuzeffe** [gravitystorm/openstreetmap-carto#3609]
Hello,

Thx for the work done on rendering for healthcare tag scheme. Very appreciate.

One question: healtcare=nurse is not rendered. Is it intended, forgotten or just a bug ?
For example, here: https://www.openstreetmap.org/#map=19/45.79709/1.13787 (on n°34). On an other hand, maybe I didn't tagged correctly the POI.. Feel free to show me the right way :)

Thx for your answer, whatever it is.

PS : sorry for my bad and straightforward english. As you guess, I'm not a english language native...

**Comment by kocio-pl** [comment]
Hi, thanks for the report!

This tag is not documented currently and has very low usage, so it's unlikely at the moment:

https://wiki.openstreetmap.org/wiki/Key:healthcare

![taghistory 37](https://user-images.githubusercontent.com/5439713/50531019-42ccbf00-0b04-11e9-8a5b-234a14fd5f76.png)

Somebody should complete the wiki and add more such objects to the OSM database.

**Comment by deuzeffe** [comment]
Oh, I see, you're right, of course! 

Mainly used in France (according to https://overpass-turbo.eu/s/EQ1), probably because a tuto about healthcare tagging (https://wiki.openstreetmap.org/wiki/FR:Comment_cartographier_un_(sant%C3%A9) ) to tag nurse's offices. An other wiki page to write ^^

PS: thx for `features` label and adding in the road map ;)

Have a nice 2018's end & 2019's beginning!

**Comment by kocio-pl** [comment]
I will close this issue now for the reasons explained above, but feel free to come back when the usage will be much higher and there will be wiki page for this. Technically it should be easy fix then.

**Comment by jeisenbe** [comment]
This tag is now used 1429 times, after an import or organized activity last year, and contiued usage in the past couple of years. https://taginfo.openstreetmap.org/tags/healthcare=nurse#chronology

<img width="953" alt="Screen Shot 2021-09-18 at 22 28 00" src="https://user-images.githubusercontent.com/42757252/133916538-8de02017-a3fc-4a0c-97c8-5f8617719725.png">

However geographically the usage is quite limited, mostly in France, and a few regions in other countries:
<img width="700" alt="Screen Shot 2021-09-18 at 22 27 36" src="https://user-images.githubusercontent.com/42757252/133916531-3f3fa338-7424-4819-af5b-549e254de3a6.png">
:

I’m not convinced this feature is well established enough for rendering yet.
