### ISSUE TITLE
Adding rendering for emergency=assembly_point

### ISSUE THREAD

**Issue by wilmaed** [gravitystorm/openstreetmap-carto#3632]
Emergency Assembly Points are designated places where people have to wait in the event of a fire or other emergency (flood, tornado, earthquake, tsunami, ...):

https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dassembly_point

Usage:  8374 entries
https://taginfo.openstreetmap.org/tags/emergency=assembly_point

For example this SVG Image (2 colors: red and transparency):
https://github.com/wilmaed/foo/blob/master/yassembly.svg

14x14px:
![yassembly22](https://user-images.githubusercontent.com/31799538/50989989-27ed4800-1511-11e9-8c10-79772d03eb90.png)

Example:
![school](https://user-images.githubusercontent.com/31799538/50990734-2755b100-1513-11e9-80f7-10c94aa7c295.png)

Maybe different colors for different types:
assembly_point:tsunami
assembly_point:fire
assembly_point:flood
assembly_point:tornado
assembly_point:earthquake

**Comment by kocio-pl** [comment]
I would render it on z19+ and I guess one color for all of them is enough. This icon looks OK for me.

![taghistory 41](https://user-images.githubusercontent.com/5439713/50994088-9931f880-151b-11e9-99c5-6ec39390bf8d.png)

**Comment by HolgerJeromin** [comment]
The icon does not work for me. :-(

**Comment by jeisenbe** [comment]
Perhaps thinner arrows would help? Maybe only 3 instead of 4?

**Comment by polarbearing** [comment]
The 4 arrows is what I'd remember from such signs (though they are diagonal, search 'assembly point symbol').

Anyway I'd be against rendering, and not at all in emergency colour. These points are of relevance in relation to a particular building. Thus there might be different points for different buildings in proximity, or even different points for different parts/populations in the same building. The general map cannot show such relations.

**Comment by Adamant36** [comment]
> different points for different parts/populations in the same building. 

Probably not for something like a:tsunami. Everyone is going to run to higher ground no matter population they are a member of. Its also, not as building dependent as something like a fire or a tornado. I agree that other then those tags, except maybe earthquakes. its to specific a tag. It would be worth rendering once the sub tags get more usage though and the icons can be specific. As it is assembly_point:tsunami=yes only has 7 usages. Or conversely assembly_point:fire=yes could just be left out of it.

**Comment by polarbearing** [comment]
There are different purposes for such points. One is to seek refuge (your tsunami example), another is to count heads (like in a fire in a school/company) to see if somebody is missing (muster/assembling point). 
The tag appears to be badly designed in this differentiation, together with the suspicious import I'd suggest to reject for now. 

I also found the suspicious import, it is in Taiwan, and all I probed are shelter-functions of public buildings in a case of emergency. The tag emergency=assembly_point is not well chosen for those. About 5000 nodes and 670 polygons: https://overpass-turbo.eu/s/Fu5
Example:

```
    addr:country=TW
    addr:full=嘉義縣水上鄉水上村正義路141號
    building=office
    description=水上鄉公所三樓
    emergency=assembly_point
    emergency:amenity=social_facility
    emergency:shelter_type=水災
    emergency:social_facility=shelter
    emergency:social_facility:association_villages=鄉公所附近村民；無收容所之村
    emergency:social_facility:for=displaced_people
    emergency:social_facility:id=1781
    emergency:social_facility:source=內政部消防署
    evacuation_center=yes
    name=水上鄉公所
    office=government
```

**Comment by polarbearing** [comment]
https://www.openstreetmap.org/changeset/49214137 has one of the discussions about the import, I left a comment there.

**Comment by matkoniecz** [comment]
I am planning to close this issue as declined for reasons mentioned two and three comments so and because

**Comment by matkoniecz** [comment]
If someone thinks that my arguments can be contradicted or has good arguments why it should be rendered despite problems that I mentioned- this is the best moment to mention them.

**Comment by polarbearing** [comment]
In favour of closing.

**Comment by matkoniecz** [comment]
I am closing, though if anyone has good counterarguments - please comment (especially if you are visiting github rarely and missed discussion), issues can be easily reopened.

one additional problem is that proposed icons, especially

![50990734-2755b100-1513-11e9-80f7-10c94aa7c295](https://user-images.githubusercontent.com/899988/51750512-93f3b280-20b2-11e9-86af-7d547f7adec4.png)

for me look like gunsight or a military target what would lead to rather unwelcomed confusion.

**Comment by Adamant36** [comment]
> for me look like gunsight or a military target what would lead to rather unwelcomed confusion.

Probably not a good icon to have in the middle of a school. At least here in America.
