### ISSUE TITLE
Question: What tags does OSM-Carto use to render boundary=national_park relations in its own rendering?

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#3633]
To check - `boundary=national_park` relations that are split into several ways:
What is the tag requirement to get it to them to render both the boundary line/label when zoomed in & the green fill at low zoom levels:

Is `area=yes` required?

Are `outer` roles required if there is no `inner`?

Is there a rule to render them at different zoom levels depending on area?

Is it the same for other area such as `boundary=protected` & `leisure=nature_reserve`?

**Comment by matkoniecz** [comment]
> Is there a rule to render them at different zoom levels depending on area?

Yes.

For other questions - is this attempt to check how things should be tagged? 

In this case I would not tag for specific rendering but rather follow established tagging rules. Good start is to use power of great JOSM validator - load affected area or object and run validator. It is likely to report many issues, including ones causing wrong rendering.

JOSM validator is not foolproof but it is quite good (and JOSM developers are great at fixing reported problems).

In case that correctly tagged national park is not rendered - please report this specific problem.

**Comment by matkoniecz** [comment]
> Is area=yes required?

It should not be required.

**Comment by DaveF63** [comment]
> For other questions - is this attempt to check how things should be tagged?

No. To be clear, my questions were specifically relating to which tags OSM-Carto uses to render solely in  its rendering. I've amended the title to clarify.

> Yes.

Thanks, that helps me understand.

**Comment by gpsvisualizer** [comment]
Speaking of national parks and such, does anyone know why parts of Gifford Pinchot National Forest are intermittently rendering as if they were natural=wood? https://www.openstreetmap.org/#map=16/46.7264/-121.8517

**Comment by jeisenbe** [comment]
Have you checked the data? Most likely that section of the National Forest
is also tagged with landuse=forest or natural=wood. These tags might be on
the relation or a multipolygon, if you don’t seem them on an OSM way

**Comment by DaveF63** [comment]
Well, someone removed a forest tag a couple of weeks ago, & there's been a hiccup in the render server, so it might be delayed. 
However, I'm surprised it renders at all. Is this it's actual boundary?
http://tools.geofabrik.de/osmi/?view=geometry&lon=-2.33890&lat=51.37624&zoom=9

Also, you may want to check out this:
http://ra.osmsurround.org/analyzeMap?relationId=8162013

**Comment by gpsvisualizer** [comment]
> However, I'm surprised it renders at all. Is this it's actual boundary?
> http://tools.geofabrik.de/osmi/?view=areas&lon=-122.39784&lat=46.63525&zoom=12&opacity=1.00

That's part of it, yes.  And the "touching rings" are exactly as they should be.  We have a lot of checkerboard land ownership in this part of the world.

I guess it _is_ just "hiccups," but I've never seen such a persistent case of them!

**Comment by jeisenbe** [comment]
Closing, it looks like @DaveF63 had questions answered, but please comment if anything else was missed.
