### ISSUE TITLE
Barrier Icons

### ISSUE THREAD

**Issue by wilmaed** [gravitystorm/openstreetmap-carto#3638]
I am aware of #3635

So if anyone find my barrier icons (for nodes) useful, use it for whatever you want.

------------------------------------------------------------------

barrier=kissing_gate
SVG:
https://github.com/wilmaed/foo/blob/master/kissing.svg
14px:
![kissing2](https://user-images.githubusercontent.com/31799538/51072055-f1bbdf80-165a-11e9-9347-3d7306a45b0e.png)

------------------------------------------------------------------

barrier=turnstile
SVG:
https://github.com/wilmaed/foo/blob/master/drehkreuz.svg
14px:
![drehkreuz2](https://user-images.githubusercontent.com/31799538/51071700-b10d9780-1655-11e9-9a66-dd1908f519dd.png)

------------------------------------------------------------------
barrier=swing_gate
SVG:
https://github.com/wilmaed/foo/blob/master/swing_gate.svg
14px:
![swing_gate2](https://user-images.githubusercontent.com/31799538/51079554-44cc7b80-16c9-11e9-8db5-0770be3dbeb8.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dswing_gate
Usage: 21426 Entries
https://taginfo.openstreetmap.org/tags/barrier=swing_gate

------------------------------------------------------------------

barrier=hampshire_gate
SVG:
https://github.com/wilmaed/foo/blob/master/hampshire_gate.svg
14px:
![hampshire_gate2](https://user-images.githubusercontent.com/31799538/51073138-b3c7b700-166c-11e9-9404-5c08af944705.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier=hampshire_gate
Usage: 3259 Entries
https://taginfo.openstreetmap.org/tags/barrier=hampshire_gate

------------------------------------------------------------------

barrier=bump_gate
SVG:
https://github.com/wilmaed/foo/blob/master/bump_gate.svg
14px:
![bump_gate2](https://user-images.githubusercontent.com/31799538/51077850-39b72280-16ac-11e9-802b-a8359462b9f4.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbump_gate
Usage: 2138 Entries
https://taginfo.openstreetmap.org/tags/barrier=bump_gate

------------------------------------------------------------------

barrier=full-height_turnstile
SVG:
https://github.com/wilmaed/foo/blob/master/full.svg
14px:
![full2](https://user-images.githubusercontent.com/31799538/51072415-9a207280-1660-11e9-9a9d-d9315d716033.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dfull-height_turnstile
Usage: 855 Entries (very low, but nevertheless an important info, because entry usually only with ticket)
https://taginfo.openstreetmap.org/tags/barrier=full-height_turnstile

------------------------------------------------------------------

barrier=log
SVG:
https://github.com/wilmaed/foo/blob/master/log2.svg

14px:
![log2](https://user-images.githubusercontent.com/31799538/51078529-830c6f80-16b6-11e9-87aa-515fee5d3834.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlog

------------------------------------------------------------------

barrier=sally_port
SVG:
https://github.com/wilmaed/foo/blob/master/sally_port.svg

14px:
![sally_port2](https://user-images.githubusercontent.com/31799538/51079525-e2737b00-16c8-11e9-8e02-f1ccd2748ee2.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dsally_port

------------------------------------------------------------------

barrier=cycle_barrier
SVG:
https://github.com/wilmaed/foo/blob/master/cycle.svg
14px:
![cycle2](https://user-images.githubusercontent.com/31799538/51080048-a5ad8100-16d4-11e9-8539-cbf81d19b4ee.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcycle_barrier

------------------------------------------------------------------

barrier=chain
SVG:
https://github.com/wilmaed/foo/blob/master/chain.svg
14px:
![chain2](https://user-images.githubusercontent.com/31799538/51080199-79dfca80-16d7-11e9-8e37-65cb1b6c8e06.png)

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dchain

**Comment by Adamant36** [comment]
Weren't most of these already proposed in the original issue and rejected for the ones currently being used? 

Is there anything actually wrong with the ones we went with or are these just being provided for the sake of redundancy?

**Comment by wilmaed** [comment]
>sake of redundancy?

sorry, your are right.

**Comment by jajajaneeneenee** [comment]
Only one comment: your icon for a swing_gate is indeed a lift_gate ... or it looks very much like a lift_gate. (It's also often a case of wrong tagging ...). The symbols for these two kinds of barriers should be distinguishable in a clear way.
