### ISSUE TITLE
Airport icon is coverd by suburb name in some zoom levels

### ISSUE THREAD

**Issue by HT43-bqxFqB** [gravitystorm/openstreetmap-carto#3640]
### Expected behavior

Airport icon should be visible from zoom level 11-13.

### Actual behavior

Airport icon is covered by train station name? I do not know if this is a wanted behaviour or a bug. Too be save, I post it here.

### Links and screenshots illustrating the problem

![screenshot at 2019-01-13 22 17 13](https://user-images.githubusercontent.com/7846818/51090862-8cf7a680-177a-11e9-9173-493ba8af3663.png)
![screenshot at 2019-01-13 22 17 38](https://user-images.githubusercontent.com/7846818/51090863-8f5a0080-177a-11e9-9e9d-59f5f84299bd.png)
![screenshot at 2019-01-13 22 20 37](https://user-images.githubusercontent.com/7846818/51090864-9123c400-177a-11e9-93c4-0bc742bd5db4.png)

**Comment by matthijsmelissen** [comment]
Thanks for reporting. It is in fact not the name of the railway station you see, but the name of the district (place=suburb). Then it is the question if we should prefer district names or airport icons. I think the current behaviour of preferring district names is fine, given that there also exist a large number if minor airports.

**Comment by matkoniecz** [comment]
It there any popular tag that allows to distinguish major airports from minor ones?

In latest discussion on this topic `iata` and `icao` tags were found to allow distinguishing extremely minor ones, but maybe something new appeared.

Otherwise it will be necessary to probably reject this one.

**Comment by jeisenbe** [comment]
There are 3 different tags. Some airports still have “type=“, but the two
newer options are “aerodrome=“ and “aerodrome:type=“.

Probably there needs to be a proposal and an effort to make sure all the
major international airports are tagged consistently, so we can show
airstrips and private club airfield differently than public commercial
airports.
