### ISSUE TITLE
Alternative for comp-op="darken"

### ISSUE THREAD

**Issue by Klaus-Tockloth** [gravitystorm/openstreetmap-carto#3653]
The current style (4.19) uses the feature 'comp-op="darken"' three times:

```
<Style name="admin-low-zoom" filter-mode="first" comp-op="darken" opacity="0.4">
<Style name="admin-mid-zoom" filter-mode="first" comp-op="darken" opacity="0.5">
<Style name="admin-high-zoom" filter-mode="first" comp-op="darken" opacity="0.5">
```

Question: Is there an alternative to achieve a similar result?

Background: "comp-op" prevents mapnik/carto to create a svg file with "proper" vector data. 
Instead a svg file with an (huge) embedded png map (base64 encoded) will be created. Same problem for pdf.

**Comment by kocio-pl** [comment]
I have heard complaints about SVG export at least 2 times on forum and on help.osm.org, I would be happy if this problem could be fixed. Anybody interested in fixing this?

**Comment by imagico** [comment]
To my knowledge the only other way to get consistent rendering of admin boundaries with semi-transparency is by preprocessing the data.  This is a workable approach but not necessarily a desirable one here.

**Comment by sommerluk** [comment]
Does https://github.com/mapnik/mapnik/pull/4012 help here? Is part of the newest Mapnik release 3.0.22…

**Comment by talaj** [comment]
It seems like comp-op is only available in Cairo SVG surface for SVG version >= 1.2, see https://github.com/behdad/cairo/commit/5336cf5a984cdeb4d4887cd3c643a3e051aca338. Since Mapnik outputs SVG with `version="1.1"`, I think this is the culprit.

On the other hand PDF with `comp-op="darken"` should be rendered correctly. I tried that with Mapnik 3.0.x and Cairo 1.15.

**Comment by talaj** [comment]
Yes, SVG 1.1 is the default standard for Cairo SVG Surface. How I could overlook that  :angry:!

https://github.com/behdad/cairo/blob/7a923b1ff5bf3e2b79ce4f2fe14d352faef5bccb/src/cairo-svg-surface.c#L276

**Comment by talaj** [comment]
Is this ancient script still being used for expert to PDF and SVG?
https://trac.openstreetmap.org/browser/sites/tile.openstreetmap.org/cgi-bin/export

If yes, to allow `comp-op` in SVG, this has to be put after line 120 of the script:
```python
surface.restrict_to_version(cairo.SVG_VERSION_1_2)
```

Or is it somewhere in git?

**Comment by kocio-pl** [comment]
Thanks for investigating the issue!

OSM website has its own repository, I guess this is where the export might be coded or called from:

https://github.com/openstreetmap/openstreetmap-website

**Comment by talaj** [comment]
The website redirects to `/cgi-bin/export`, but I cannot find the export script in that repository:
https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/export_controller.rb#L23

**Comment by kocio-pl** [comment]
Hm, I am not sure where people get vector exports from, since by default it's just .osm file format. I opened a ticket here: https://github.com/openstreetmap/operations/issues/270.

**Comment by tomhughes** [comment]
This is https://github.com/mapnik/mapnik/issues/3749 which has a PR opened today in https://github.com/mapnik/mapnik/pull/4029.

**Comment by tomhughes** [comment]
The script is https://github.com/openstreetmap/chef/blob/master/cookbooks/tile/templates/default/export.erb by the way, and as we're actually creating the surface ourselves in python I guess we can fix this in the script by setting the version on the surface?

**Comment by talaj** [comment]
Yes @tomhughes, Ubuntu Bionic has python-cairo 1.16.2, so we can just call `surface.restrict_to_version(cairo.SVG_VERSION_1_2)` there.

**Comment by tomhughes** [comment]
Fixed in https://github.com/openstreetmap/chef/commit/d95ea7972cf4c002e5443bb3163952abc9adb72f.

**Comment by kocio-pl** [comment]
Nice! When this change will became operational and how to make a simple test if this really works?

**Comment by tomhughes** [comment]
It already is, and I already tested it.

**Comment by kocio-pl** [comment]
So can we just safely close this ticket now? Because as I understand the reporter, his aim was to allow vector exports, not a code change in itself.

**Comment by talaj** [comment]
Also PDF seems OK to me now.

**Comment by kocio-pl** [comment]
Oh, I was thinking about "Export" button on top, while this function is available from "Share" button on the right... It's a small usability glitch for me. However both PDF and SVG work for me, so I'm closing it now. If there will be further problems to discuss, it can be reopened.

Thanks, guys!
