### ISSUE TITLE
Missing fonts after following INSTALL.md

### ISSUE THREAD

**Issue by Phyks** [gravitystorm/openstreetmap-carto#3655]
Hi,

I followed https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#installation-on-ubuntudebian (on Ubuntu bionic) and was expecting the required fonts to be installed. However, when running Kosmtik, I get the following warnings:

```
Mapnik LOG> 2019-01-23 14:15:36: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-0'
Mapnik LOG> 2019-01-23 14:15:36: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-0'
Mapnik LOG> 2019-01-23 14:15:36: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-0'
Mapnik LOG> 2019-01-23 14:15:36: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-0'
```

It seems there are two issues with the fonts:

* First, `ttf-unifont` package does not seem to provide a `Medium` font, from looking at [the files within the package](https://packages.ubuntu.com/bionic/all/ttf-unifont/filelist). Is the `unifont Medium` font supposed to be provided by this package?

* Second, Noto Emoji is not packaged nor installed, which was already discussed in https://github.com/gravitystorm/openstreetmap-carto/issues/2379. However, there seems to be now a package for Ubuntu (starting from bionic / 18.04 LTS) called [`fonts-noto-color-emoji`](https://packages.ubuntu.com/bionic/fonts-noto-color-emoji) which provides the font. Still, the font is named "Noto Color Emoji" and not "Noto Emoji", so simply installing the package is not enough. Same seems to be available in Debian, but only in `testing` for now. Would it be worth mentionning this in the `INSTALL.md` (and eventually use the "Color" font)?

Best,

**Comment by Adamant36** [comment]
A better description would be good. When I first started using Mapnik, I didn't know the warnings about fonts where normal and that it would load without them. So it would be good if there was at least a mention of the fact that the warnings are normal and don't effect anything.
