### ISSUE TITLE
Duplicated city names

### ISSUE THREAD

**Issue by Phyks** [gravitystorm/openstreetmap-carto#3664]
Hi,

I'm not exactly sure what is happening but it seems some city names are duplicated in https://www.openstreetmap.org/#map=13/48.8078/2.3047.

### Expected behavior

I would expect "Montrouge", "Arcueil" or "Cachan" to only appear once.

### Actual behavior

They appear twice, in different gray scale (lighter one being city subdivision colors normally, but these cities have no subdivisions I think).

### Links and screenshots illustrating the problem

![screenshot_2019-01-31 openstreetmap](https://user-images.githubusercontent.com/3856586/52055651-44a0fc80-2560-11e9-9a65-0cd66e918197.png)

From https://www.openstreetmap.org/#map=13/48.8078/2.3047

Thanks!

EDIT: After a bit of looking around, it is probably coming from https://www.openstreetmap.org/relation/37026 which is included due to `landuse=residential` and https://www.openstreetmap.org/node/26692584 which is included due to `place=town`.

**Comment by imagico** [comment]
That is due to multiple features being tagged `name=Montrouge` etc.:

https://www.openstreetmap.org/node/26692584
https://www.openstreetmap.org/relation/37026

The latter is rendered with a label because it is tagged landuse=residential.

**Comment by Phyks** [comment]
Indeed. However, it seems to be frequent to have such multiple items with same name.

Looking around "Puy de Dome" in France (probably biased), I found four typical cases:

1. Same as above, with a duplicate from the place name.
2. Apartments complex names, such as https://www.openstreetmap.org/way/396613093.
3. Halting site for travelling people (which could be catched separately with `residential=halting_site` I think) such as https://www.openstreetmap.org/way/531944145
4. Squares, such as https://www.openstreetmap.org/way/420591082. The name is also duplicated in a separate node here, https://www.openstreetmap.org/node/4205554289. I would however probably not have tagged this one this way.

(2) seems to be actually the blocking point in favor of rendering `landuse=residential`. Not sure it could be catched otherwise. Maybe `landuse=residential` could be filtered on polygon area?

**Comment by matkoniecz** [comment]
> Indeed. However, it seems to be frequent to have such multiple items with same name.

Can you give example of place where this is a correct tagging?

> Same as above, with a duplicate from the place name.

I would expect that such cases are victims of wrong data, not of a wrong map style.

> Apartments complex names, such as https://www.openstreetmap.org/way/396613093.

Rendering apartment complex names is desirable, I see nothing wrong with it.

> Halting site for travelling people (which could be catched separately with residential=halting_site I think) such as https://www.openstreetmap.org/way/531944145

Is anything wrong with showing this name?

> Squares, such as https://www.openstreetmap.org/way/420591082. The name is also duplicated in a separate node here, https://www.openstreetmap.org/node/4205554289. I would however probably not have tagged this one this way.

https://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element - this is a clearly incorrect data and one of functions of this style is to show incorrect data as a clearly incorrect. I edited this case to reduce duplication.

**Comment by matkoniecz** [comment]
I think that main problem here is incorrect tagging - is https://www.openstreetmap.org/node/26692584 really a separate town? And either this place can has clearly defined boundaries and should be tagged on area or it has no clearly defined boundaries and should be tagged as a node.

I see no good reason to tag it both as a point and as an area.

**Comment by Phyks** [comment]
So, there are two items: the node, which is the city center (`place=town`) and the polygon (`boundary=administrative`). Both have the same name and represent the same city. The boundaries of the city are defined by the `boundary=administrative` relation (and can be well defined). Then, probably the `place=town` could be put on the area itself.

This could be bad tagging. However, this seems to happen quite a lot around there, and I'm not super up to date on tagging boundaries and towns, so I'm not really for updating anything in this area myself without some extra background knowledge.

I sent [a message on talk-fr](https://lists.openstreetmap.org/pipermail/talk-fr/2019-February/091600.html) (in French) to have more background on this tagging scheme.

**Comment by matkoniecz** [comment]
> I sent [a message on talk-fr](https://lists.openstreetmap.org/pipermail/talk-fr/2019-February/091600.html) (in French) to have more background on this tagging scheme.

What is their opinion about current tagging? Is there any convincing argument against https://github.com/gravitystorm/openstreetmap-carto/issues/3664#issuecomment-459841020 ?

**Comment by Phyks** [comment]
Hi,

I did not get a lot of feedback yet. Part of the answers was that OSM is iterative and that this is expected that the landuse would not be well refined, which is true. However, the real issue here is that the landuse is tagged on the same object as the boundary=administrative, thus sharing the same name. I did not get feedback on whether this would be a valid tagging scheme or not.

From openstreetmap-carto side, a potential fix could eventually be to ignore landuse=residential with names if they also have a boundary tag. 

For the record, I did some checks around Paris and found 30 such landuse so far:

```
           name           |   landuse
--------------------------+-------------
 Quartier Châtillon       | residential
 Paris 16e Arrondissement | residential
 Juvisy-sur-Orge          | residential
 Malakoff                 | residential
 Montrouge                | residential
 Cachan                   | residential
 Arcueil                  | residential
 Gentilly                 | residential
 Le Kremlin-Bicêtre       | residential
 Paris 15e Arrondissement | residential
 Paris 14e Arrondissement | residential
 Paris 7e Arrondissement  | residential
 Paris 13e Arrondissement | residential
 Paris 6e Arrondissement  | residential
 Paris 1er Arrondissement | residential
 Paris 5e Arrondissement  | residential
 Paris 4e Arrondissement  | residential
 Paris 3e Arrondissement  | residential
 Ivry-sur-Seine           | residential
 Paris 11e Arrondissement | residential
 Paris 20e Arrondissement | residential
 Paris 12e Arrondissement | residential
 Paris 17e Arrondissement | residential
 Paris 8e Arrondissement  | residential
 Clichy                   | residential
 Paris 9e Arrondissement  | residential
 Paris 2e Arrondissement  | residential
 Paris 10e Arrondissement | residential
 Paris 18e Arrondissement | residential
 Paris 19e Arrondissement | residential
```

Best,

**Comment by matkoniecz** [comment]
> However, the real issue here is that the landuse is tagged on the same object as the boundary=administrative, thus sharing the same name.

I am highly convinced that it is clearly a bad idea, if someone thinks otherwise I would be happy to discuss it on tagging mailing list (please create a new thread and let me know).

**Comment by jeisenbe** [comment]
> landuse is tagged on the same object as the boundary=administrative

I agree that this is a bad idea. Two unrelated features should not share
the same OSM geometry.

A boundary=administrative is a defined by the local government and can
change at any time. Landuse tags describe the human use of the land. It is
very rare that these would be exactly the same area. Usually a residential
area is larger or smaller than the administrative boundary

**Comment by matkoniecz** [comment]
I opened https://josm.openstreetmap.de/ticket/17305#ticket asking JOSM to start complaining about this tagging.

I am convinced that it is a tagging issue and not something wrong with the renderer. As such, I'm closing this issue.

**Comment by Phyks** [comment]
I agree on this, thanks!

**Comment by matkoniecz** [comment]
> I opened josm.openstreetmap.de/ticket/17305#ticket asking JOSM to start complaining about this tagging.

JOSM developers just added this warning - see https://josm.openstreetmap.de/ticket/17305#comment:6

I opened equivalent iD issue at https://github.com/openstreetmap/iD/issues/6011
