### ISSUE TITLE
Swimming pool as building

### ISSUE THREAD

**Issue by TastyComputer** [gravitystorm/openstreetmap-carto#3665]
I noticed that the pool name font differs depending on whether it is a building or a node. In my opinion it should be with the same look.
![ld9zoa38uxcb](https://user-images.githubusercontent.com/47242403/52128323-ebef6380-2634-11e9-9cd5-f70faa4658af.png)
Police: https://www.openstreetmap.org/way/173574304
Szczecin: https://www.openstreetmap.org/node/2439409194

**Comment by imagico** [comment]
The one on the left is a building label - if a feature is tagged `building=*` + `name=*` the name is assumed to apply to the building.  This is intended behavior.

The correct mapping here is mapping the pool separately from the building - see https://wiki.openstreetmap.org/wiki/Tag:leisure=swimming_pool.  Indoor pools should also be tagged `location=indoor` and possibly `level=*`
