### ISSUE TITLE
add rendering for parking hgv / truck and bus

### ISSUE THREAD

**Issue by JLZIMMERMANN** [gravitystorm/openstreetmap-carto#3667]
### Expected behavior
Give a specific pictogramm for amenity=truck_parking / hgv_parking and amenity=bus_parking

### Actual behavior
Nothing happens when the map displays only the letter P

### Links and screenshots illustrating the problem
Example of truck_parking  https://www.openstreetmap.org/way/642915676#map=18/48.61622/2.62593
https://www.aprr.fr/fr/services-sur-aires/cote-vehicule/parking-securise#
https://www.google.com/maps/place/Centre+routier+R%C3%A9au/@48.6161241,2.6259264,474m/data=!3m1!1e3!4m5!3m4!1s0x47e5fca5cef5693f:0xf81ee23e486f5a26!8m2!3d48.6147637!4d2.6288609

**Comment by Adamant36** [comment]
I'm pretty sure is already highway=services for truck stops and things related to it.

Also, I don't think amenity=bus_parking is a good tag as it doesn't fit the definition of "For describing useful and important facilities for visitors and residents." Places where buses are parked are usually private, fenced off, areas that the general public can't go. Unless your talking a "bus depot." Which already has a transportation related tag for. 

Its more appropriate to tag places where buses park as amenity=parking with access=private. Which I'm sure is how its done 99% of the time. Or are you going to have an amenity tag on the same object as another amenity tag? That wouldn't work.

**Comment by matkoniecz** [comment]
https://taginfo.openstreetmap.org/tags/amenity=truck_parking - used 4 times worldwide

https://taginfo.openstreetmap.org/tags/amenity=bus_parking - used 24 times worldwide

Discussing new tags is happening on OSM Wiki, tagging mailing list and similar places, not here.
