### ISSUE TITLE
Render amenity=tuition

### ISSUE THREAD

**Issue by fiuncho** [gravitystorm/openstreetmap-carto#3673]
amenity:tuition doesn't render anything on the map, not even a simple point. There are at this moment very few nodes with this tag, but it has a wiki page and there are no alternative tag for this kind of node.

Some examples below:

https://www.openstreetmap.org/node/6239863364
https://www.openstreetmap.org/node/5877104942

**Comment by polarbearing** [comment]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtuition
used 9x

**Comment by kocio-pl** [comment]
Thanks for reporting it, but the usage is much too low currently for the rendering here, so I will close it now.
