### ISSUE TITLE
How to style a amenity point depending on what surface it's placed on?

### ISSUE THREAD

**Issue by spithost** [gravitystorm/openstreetmap-carto#3684]
I'd like to style wind-generators different on a tileserver, depending on what surface they are placed on. As I create basemaps for sailing, with a tileserver, I'd like to be style the features power_generator to be larger and/or have a different symbol depending if they are on water instead of on land.
### Expected behavior
**Different** styling of power_generator depending on if they are on land or on water. 
So that they can be made more visible on water-surfaces when using the generated tiles as a basis for navigation on the water.
### Actual behavior
Using the standard .mss for amenity points, they are VERY small on the tiles I produce (zoom-factor 16). 
That's quite ok for the land-surfaces but on the watersurfaces, it would be nice if they would be larger (i.e. more visible on the maps).

**Comment by pnorman** [comment]
For the same reasons that we can't style differently in urban and rural areas, this can't be done within our current infrastructure.

In a differently designed style you could load the water data into the database and do a spatial query to determine if something is in water or not, but that's not something we do.
