### ISSUE TITLE
Car_repair's label is brown

### ISSUE THREAD

**Issue by hugobqd** [gravitystorm/openstreetmap-carto#3687]
Shops are supposed to have a purple icon and text label. But on car_repair, the text is brown.

<img width="312" alt="capture d ecran 2019-02-19 a 16 45 09" src="https://user-images.githubusercontent.com/35178/53027782-e59b1d00-3465-11e9-807d-a76ce0ffce05.png">

(Other example : the southernmost garage in OSM : https://www.openstreetmap.org/way/329705189)

**Comment by matthijsmelissen** [comment]
See also .#2658.
