### ISSUE TITLE
render man_made=watermill

### ISSUE THREAD

**Issue by fiuncho** [gravitystorm/openstreetmap-carto#3692]
I have been mapping some watermills and I realized it doesn't render in carto. However I've found that carto renders windmills and windmills numbers are not much higher, according to taginfo.

In what follows I post some examples:

Watermills:
https://www.openstreetmap.org/node/5338734755
https://www.openstreetmap.org/way/672532693

Windmills:
https://www.openstreetmap.org/node/527858702#map=19/51.48548/4.46008
https://www.openstreetmap.org/way/146213769

**Comment by kocio-pl** [comment]
Looks sane for me, but we need an icon for that.

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwatermill

![taghistory 48](https://user-images.githubusercontent.com/5439713/53292707-ed8cf100-37c6-11e9-89ab-508a9c94ed09.png)

**Comment by wilmaed** [comment]
> 
> 
>we need an icon for that.
> 

like that?

https://github.com/wilmaed/foo/blob/master/watermill14.svg

![mill14](https://user-images.githubusercontent.com/31799538/53298354-f1535e80-382c-11e9-92e7-759945628f0d.png)

**Comment by Adamant36** [comment]
Looks like a gear getting oil on it or something. 

Here's a link to Noun Project with a few icons that might be worth trying

https://thenounproject.com/search/?q=watermill

**Comment by wilmaed** [comment]
https://github.com/wilmaed/foo/blob/master/mill4.svg
![mill14_](https://user-images.githubusercontent.com/31799538/53298947-c7059f00-3834-11e9-9b16-be3c93f8d452.png)


https://github.com/wilmaed/foo/blob/master/mill5.svg
![mill14__](https://user-images.githubusercontent.com/31799538/53299130-e56c9a00-3836-11e9-9057-2b63cdb75974.png)

**Comment by wilmaed** [comment]
Clipped and resized ID-Editor Icon:
https://github.com/wilmaed/foo/blob/master/mill6.svg

![watermill-15](https://user-images.githubusercontent.com/31799538/53300161-b6a8f080-3843-11e9-972a-843b8c8726a0.png)

**Comment by imagico** [comment]
I suggest to close this as declined - the tag is apparently equally used for

* former watermill buildings without any actual watermill structure being still present
* disused watermills with preserved structure
* operational watermills

with no established tagging to differentiate between those.  That makes any rendering kind of problematic i think.

I would rather like to see power=generator + generator:source=hydro being rendered.

**Comment by jeisenbe** [comment]
Closing as declined due to reasons in the above comment: this tag is used for historic, disused watermills, history watermill buildings which are now re-purposed for some other use, as well as a few operational watermills. This makes it difficult to provide a rendering which matches the use of the tag. Note that closing this issue was also recommended in https://github.com/gravitystorm/openstreetmap-carto/pull/4555#issue-1245520424
