### ISSUE TITLE
free-standing notice board

### ISSUE THREAD

**Issue by eehpcm** [gravitystorm/openstreetmap-carto#3693]
I mapped a free-standing notice board (not attached to a wall) on a node with tourism=information + information=board + board_type=notice + direction = 295 + operator = foo

To avoid doubt, this is a free-standing notice board: 
![cilgerran_notice_board](https://user-images.githubusercontent.com/3224921/53294079-62b4f200-37d8-11e9-9f61-4e6ec9a69545.jpg)

### Expected behavior

I expect it to render, as have other notice boards I've mapped which are mounted on the walls of buildings (mapped as a node on the closed way of the building).

### Actual behavior

Nothing is rendered.

### Links and screenshots illustrating the problem

[Notice board that renders](https://www.openstreetmap.org/node/5995858595)

[Notice board that does not render](https://www.openstreetmap.org/node/6298288417)

**Comment by Adamant36** [comment]
Probably because the other icons close to it are higher in rendering priority. So they block it from displaying. That's my guess at least.

**Comment by kocio-pl** [comment]
Exactly, this is visible on z20, so I will close this ticket:

![screenshot_2019-02-24 openstreetmap carto kosmtik](https://user-images.githubusercontent.com/5439713/53294500-afa0c480-37e8-11e9-9843-309348c57ba8.png)
