### ISSUE TITLE
Landuse=grass is not rendered at z9 and below

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3696]
### Expected behavior
It should be apparent if a region has landcover tagging or if the landcover is still not mapped at z7 to z9

### Actual behavior
Areas with landuse=grass, such as the Netherlands and northern Belgium, look gray (unmapped) at z9 and below, but are clearly fully mapped when seen at mid and high zooms

### Links and screenshots illustrating the problem
Utrecht, z10
https://www.openstreetmap.org/#map=10/52.0331/4.7859
![z10-utrecht-rotterdam-farmland](https://user-images.githubusercontent.com/42757252/53300254-4d42d500-3877-11e9-8ec5-6e726150b2f9.png)

z9
https://www.openstreetmap.org/#map=9/52.0322/4.7873
![z9-utretch-to-rotterdam](https://user-images.githubusercontent.com/42757252/53300282-bfb3b500-3877-11e9-80a9-da0ae18791e0.png)

**Comment by matkoniecz** [comment]
Related to #3273

**Comment by matkoniecz** [comment]
Looks related to #3273 #1566 and result of #2874

**Comment by jeisenbe** [comment]
> Looks related to #3273 #1566 and result of #2874

That's my initial thought. The extracts of these parts of the Netherlands have too much data for me to render them on my laptop, but perhaps someone else can check?

**Comment by jeisenbe** [comment]
@vholten discovered that the problem is with areas tagged landuse=grass, which was not rendered below z10. I've changed the title and description of this issue.
