### ISSUE TITLE
Add rendering for leisure=water_park

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [gravitystorm/openstreetmap-carto#370]
Map: http://www.openstreetmap.org/#map=17/-22.98075/-43.48637

To the south of the parking lot there is a water park, represented by a polygon (id=263566033) with leisure=water_park and name=Rio Water Planet.  There is also a node (id=2692030832) with the same tags.  None of them are being rendered in OSM slippy map.  If you enable "Map data" you can see its outline.

I've already checked for cache issues, etc.  The parking lot and the neighbouring club belong to the same changeset and both are being rendered, thus this is not a cache issue.

Thanks.

**Comment by math1985** [comment]
Fixed by #725.
