### ISSUE TITLE
Rendering private amenity=place_of_worship grey

### ISSUE THREAD

**Issue by wilmaed** [gravitystorm/openstreetmap-carto#3702]
Tag combination:

```
access=private
amenity=place_of_worship
```

### Expected behavior
grey icon

### Actual behavior
black icon

### Links and screenshots illustrating the problem

Chapelle d'Aubigné  (next Cathédrale Notre-Dame):
https://www.openstreetmap.org/way/365724597

北辰神社
https://www.openstreetmap.org/way/334119445

**Comment by jeisenbe** [comment]
Is this correct tagging? A search about Chapelle d'Aubigné finds a page
that says “La chapelle d'Aubigné accueillera des expositions temporaires
dans le cadre de l'Historial Jeanne d'Arc, dont l'inauguration est prévue
pour février 2015”
In English: “The chapel of Aubigné will host temporary exhibitions as part
of the Historial Jeanne d'Arc, whose inauguration is scheduled for February
2015”

http://www.patrimoine-religieux.fr/eglises_edifices/76-Seine-Maritime/76540-Rouen/158136-ChapelledAubigne(chapelledelensemblearchiepiscopal)

This suggests that it is not private.

I also think that places of worship are mainly useful as orientation
landmarks, for most use cases. A temple or sanctuary might be closed to the
public, yet it will probably be a significant local landmark. Mormon (LDS)
temples would be a good example; they are not open to the public but are
visually prominent.

**Comment by wilmaed** [comment]
> mainly useful as orientation landmarks, for most use cases.

my personal use case: may I visit and/or pray

**Comment by jeisenbe** [comment]
I think we should decline this request. Since `amenity=place_of_worship` icons are currently black and `man_made` icons are gray, rendering `amenity=place_of_worship` + `access=private` in gray would be confusing. Transparency would have the same problem. And as mentioned above, places of worship are often orientation landmarks, even when not open to the general public (e.g. mormon temples, private monasteries),  so it's not a problem to render private places of worship.

**Comment by imagico** [comment]
Agreed.  amenity=place_of_worship + access=private is not listed as a combination by taginfo which means there are less than 1000 cases of this.  It has so far not been demonstrated that this tag combination is used consistently in a meaningful way.  It seems that many of the places tagged this way are (historic) church buildings with no regular public access and no regular church services.  The verifiability of declaring such amenity=place_of_worship is questionable, in particular in religions/denominations that do not have an institution of formal consecration of places of worship.
