### ISSUE TITLE
Update to a new Mapnik and Kosmtik versions

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#3717]
### Expected behavior
After upgrade to newest Kosmtik version from git master (see https://github.com/kosmtik/kosmtik/issues/295) rendering should not change.

### Actual behavior
There are some warnings and the rendering is broken.

### Links and screenshots illustrating the problem

Example warnings:

> Warning: landcover.mss:608:6 Styles do not match layer selector #landcover-low-zoom.
> Warning: landcover.mss:608:6 Styles do not match layer selector #landcover.

Luxembourg - after:

![YRC5B9M2](https://user-images.githubusercontent.com/5439713/54367863-69b28000-4673-11e9-859a-dcc9fc3afd05.png)

**Comment by kocio-pl** [comment]
This change is needed to finally merge long awaited https://github.com/gravitystorm/openstreetmap-carto/pull/3399.

**Comment by pnorman** [comment]
If we require a new mapnik version we should be doing that in a major release

**Comment by matthijsmelissen** [comment]
> After upgrade to newest Mapnik version from git master 

It's either master or the latest (version) tag, it cannot be both :)

Does OSMF Operations already run the latest version? Logistically it would probably be easier if they bump their version first, before we release a version requiring the new Mapnik.

**Comment by sommerluk** [comment]
On my local machine, it renders correctly. But I have deleted all .index files for the shapefiles. I suspect these files make problems because there is a version missmatch between the Mapnik version that generates the index files (either the downloaded index files or these you might re-create locally using your distribution's Mapnik package) and the node-mapnik version used by Kosmtik. If you delete the index files, does it render correctly?

**Comment by kocio-pl** [comment]
I have upgraded my system to Ubuntu 19.04 and the whole environment is not working, currently I have:

$ node -v
v10.15.2

$ npm -v
5.8.0

Maybe I will try to downgrade them to a node v8.10.0 and npm 3.5.2, [as before](https://github.com/kosmtik/kosmtik/issues/295#issuecomment-473094860).

**Comment by sommerluk** [comment]
> Does OSMF Operations already run the latest version?

Yes, [operation is yet running Carto 1.2.0](https://github.com/gravitystorm/openstreetmap-carto/pull/3399#issuecomment-520025952).

**Comment by sommerluk** [comment]
> There are some warnings

This is a consequence of a change in CartoCSS which outputs now much more warnings than before, but still generates the very same XML result. Its consequences for openstreetmap-carto have been discussed in #3183 and it has been considered a non-issue.

**Comment by sommerluk** [comment]
Closing as we use higher Mapnik and Kosmtik versions now.
