### ISSUE TITLE
Rescale z_order and treat links the same as base type

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#3719]
Currently all orders are divisible by 10. The z_order would be easier to work with if all current orders were divided by 10.

At the same time, we should make highway=X and highway=X_link have the same z_order, then add link status to the order by in the queries.

**Comment by sommerluk** [comment]
> we should make highway=X and highway=X_link have the same z_order, then add link status to the order by in the queries.

What would be the advantage of this change?

**Comment by pnorman** [comment]
> What would be the advantage of this change?

Without an increase in query complexity it gives us more flexibility, cleaner z_order selection, and is clearer as why the values are different. It allows foo and foo_link to be treated the same which right now is not true.

**Comment by jeisenbe** [comment]
This has to be done at the time of database reload, correct?

**Comment by pnorman** [comment]
> This has to be done at the time of database reload, correct?

Yes

**Comment by jeisenbe** [comment]
> The z_order would be easier to work with if all current orders were divided by 10.

I could still do this in #4055, though it will require changing more values, since the `construction=` values need 18 unique numbers. 

Is that worthwhile?

**Comment by pnorman** [comment]
Thinking about this, it's not going to work with our peculiar ordering of links between high-class roads and low-class roads.

-----

> I could still do this in #4055, though it will require changing more values, since the `construction=` values need 18 unique numbers.
> 
> Is that worthwhile?

No.
