### ISSUE TITLE
Add rendering for man_made=bunker_silo

### ISSUE THREAD

**Issue by MrPlumbum** [gravitystorm/openstreetmap-carto#372]
Please create a rendering for the approved tag man_made=bunker_silo ([Wiki documentation](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbunker_silo)). For those mapped as polygon I would propose a rendering as a grey area with a highlighted (dark grey) frame.

Now there are several hundreds mapped, but I would approximate that the number will increase to several tens of thousands.

*[Example 1](http://www.openstreetmap.org/#map=19/52.54447/10.11723&layers=D)
*[Example 2](http://www.openstreetmap.org/#map=17/40.37568/-104.51033&layers=D)

Thanks

**Comment by matkoniecz** [comment]
Also, such objects are not highly important, I think that rendering them is not the best idea.

**Comment by MrPlumbum** [comment]
I like the rendering-style proposed by daganzdaanda: "with a similar colour to farmyard, a bit darker". 

There should be a rendering because in the areas covered with a bunker_silo is nothing else.

**Comment by kocio-pl** [comment]
10 775 cases already and they do use some space, so I think it's time to rethink the issue.

**Comment by jeisenbe** [comment]
I looked into this. I can't think of a good rendering. 

They are not buildings (no roof, only 3 walls), and they are not really similar to farmyards, so we should not use the same color as a building or farmyard. 

They are rectangular, and building-sized, not like a whole farmyard area. 

Most do not have any `barrier=wall` features added for the 3 sides with walls, though this could be used and is already rendered. 

So, besides the walls, we would be rendering the area of the floor, which might be covered with agricultural products or sillage. I'm not sure that anything besides the walls is of interest for a general-purpose map. 

Does anyone have other ideas about rendering this in a reasonable way, or can we close the issue?

**Comment by jeisenbe** [comment]
I have no ideas about how to render these in a good way, except to map and render the walls that surround them on 3 sides. They should usually be inside a landuse=farmyard or landuse=farmland area which we can also render. So I will close this for now, but if someone has a great idea about how to render these, it can be reopened.
