### ISSUE TITLE
Ghost boundary line crossing suburb

### ISSUE THREAD

**Issue by IgorEliezer** [gravitystorm/openstreetmap-carto#3721]
### Expected behavior
Draw the dotted line only where the suburb boundaries actually are drawn.

### Actual behavior
There's a dotted line crossing the suburb where there is none.

### Links and screenshots illustrating the problem

![image](https://user-images.githubusercontent.com/4673289/54497705-ad5bf280-48dc-11e9-9fe4-4eebda0248b9.png)

Relation: https://www.openstreetmap.org/relation/7733930

The relation is made of two ways ([539829080](https://www.openstreetmap.org/way/539829080
) and [539829079](https://www.openstreetmap.org/way/539829079)), both as `outer` role. It seems that only 1st, 2nd and the last nodes of the 2nd way are taken in account and a straight boundary line is drawn between 2nd and last nodes.

There are also these bordering relations: https://www.openstreetmap.org/relation/7733929 and https://www.openstreetmap.org/relation/7733931. I analyzed all 3 relations manually, in JOSM and OSM Relation Analyzer, they all make a perfect loop and have the correct roles (only `outer`). I've found nothing out of extraordinary.

http://ra.osmsurround.org/analyzeRelation?relationId=7733930&_noCache=on
http://ra.osmsurround.org/analyzeRelation?relationId=7733929&_noCache=on
http://ra.osmsurround.org/analyzeRelation?relationId=7733931&_noCache=on

I have plans to improve and clean the area to fix overlapping landuses and parallel ways but I preferred to report the issue before proceeding.

**Comment by matkoniecz** [comment]
Thanks for reporting! Many issues with map style remain unknown to us because nobody reported them, so thanks for a very thorough report!

This looks like outdated rendering or small data corruption on rendering servers. Editing affected objects usually clears such issues.

Unfortunately, this would be a not a bug in map style but some problem with updating data on OSM servers.

It may be even not a bug but a hardware issue.

Overall, I am pretty sure that it is not fixable by improving map style.

Let us know if this line persists after editing in this area.

**Comment by IgorEliezer** [comment]
@matkoniecz:
> Let us know if this line persists after editing in this area.

The problem vanished after I changed the boundary.

![map](https://user-images.githubusercontent.com/4673289/54871464-e4c21780-4d92-11e9-8360-e7525fa1db18.png)

Feel free to close the issue if ok.

**Comment by matkoniecz** [comment]
Turned out to be an upstream bug https://github.com/openstreetmap/osm2pgsql/issues/1394

> The error happens when there is a boundary relation containing exactly
> two ways forming a closed ring and the ways are oriented against each
> other. So they both have the same first and last nodes. The bug does
> not appear when the last node of one of the ways is the first node of
> the other. (Most likely the bug will also happen if there are four
> ways of which two create one ring and two another etc.)

> It is also possible to fix at least some of these cases by simply
> turning around one of the member ways. You can do this without the
> software having been updated. Just take care that turning around the
> way doesn't create other problems.

Once new osm2pgsql is deployed on OSM servers this bug will also disappear as boundaries are edited in general.

**Comment by mmd-osm** [comment]
I checked all type=boundary relations having two ways that are sharing the same first and last node via an Overpass query. Currently, we have 4839 such relations, which amounts to 0.7% of all type=boundary relations. Query is available on my osm wiki page.
