### ISSUE TITLE
Country names next to boundaries should disappear after state names after county names... when zooming out

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3723]
There are four countries in
https://www.openstreetmap.org/#map=10/49.1166/87.6819
but how can students tell which?

**Comment by matkoniecz** [comment]
>  but how can students tell which?

By zooming out to see label for entire country or by zooming in to see labels on the border line

**Comment by jidanni** [comment]
OK, I zoomed way way out, found the country names, but by the time I zoomed back in, I mixed them up in my head. Plus what do I need to do for assistive technology? Use a red marker on my computer screen?
[Here](https://www.openstreetmap.org/#map=17/24.22232/120.83322) we see even the tiniest local borders feature names. Why not international borders that might be hazardous to cross if you are the wrong nationality?

**Comment by jidanni** [comment]
All I know is Google doesn't make them disappear until one zooms much farther out.

**Comment by jidanni** [comment]
Ah ha, I have the solution!

Instead of showing

- **all** area names down to zoom level 16, then have them **all** disappear starting at zoom level 15,

How about something like

- Show township names down to zoom level X, county names down to level
  X-2, county names down to level X-4, state names down to level X-6,
  country names down to level X-8... you get the idea!

**Comment by jidanni** [comment]
Also hand in hand would be: OK, I have reached the zoom level where it is time to remove the [country, state, etc.] name. Well this is the same level where I should now put that [country, state, etc.] name in the big white area in the middle of that [country, state, etc.]'s region currently on the map.

**Comment by jidanni** [comment]
Returning to our original map,
OK we have lost our names below zoom level 16.
Let's see how low we have to go to recover them again.
At zoom level 5 both Mongolia and Kazakhstan's centers enter our screen,
so we see their names.

Finally at zoom level 3 Russia's center, and hence name, enters our
screen.

At zoom level two, all country names disappear. Fair enough.

Alas, #3725 .

**Comment by sommerluk** [comment]
> There are four countries in https://www.openstreetmap.org/#map=10/49.1166/87.6819 but how can students tell which?

> All I know is Google doesn't make them disappear until one zooms much farther out.

When looking at Google Maps at the same position and zoom level you have indicated, I do not see any country labels!

> Instead of the current behavior of showing all area names down to zoom level 16, then have them all disappear starting at zoom level 15,

This isn't the current behavior. The current behavior is starting and stopping country label rendering based on the size of the country.

> How about something like Show township names down to zoom level X, county names down to level X-2, county names down to level X-4, state names down to level X-6, country names down to level X-8... you get the idea!

That would result in a terrible rendering. Having the same zoom level threesholds for Russia and Vatican City (both are countries) would not scale well at all. And as you might have noticed, yet currently county names show up later than country names.

> but how can students tell which?

This was the original issue you mentioned. It is intentional that country names disappear when the country becomes so big that it covers likely the hole screen. Otherwise you would have to render always country names on all zoom levels. It's not desirable to have for example Russia's country names on all tiles at z19. It would be quite confusing when you are looking at Moscow at z19 seeing “Russia” always on your screen. That's a more important that the issue you have described here, so closing at “won't fix”.

**Comment by jeisenbe** [comment]
This is the relevant code for the main country labels (at the center
of the polygon) from `placenames.mss` :
```
.country {
  [zoom >= 3][zoom < 5][way_pixels > 1000],
  [zoom >= 5][way_pixels < 360000] {
```
This means that all countries that are **larger** than 1000 square
pixels (eg 10 x 100 pixels) are shown from z3 to z5.

From z5 all countries are shown, no matter the size, as long as they
are **smaller** than 360,000 pixels (eg 360 x 1000; about half the
screen. This has been the case for a long time.

It would be possible to show the labels one zoom level later by
changing this value, but then the country label would sometimes shown
even when none of the borders of the country were visible. I'm not
sure that this is useful or necessary.

For states and provinces (admin_level 4) the code is:
```
.state {
  [zoom >= 5][zoom < 7][way_pixels > 3000],
  [zoom >= 7][way_pixels > 3000][way_pixels < 196000] {
```
So states are only shown when they are larger than 3000 pixels but
less than 196,000 pixels in area; this means they are shown for 4 zoom
levels, which most country labels are shown for at least 5 zoom levels
(excepting huge countries like Russian, Canada, China, and the USA)

From `admin.mss` we have:

```
#admin-text[zoom >= 11][way_pixels >= 48000] {
  [admin_level = '1'][way_pixels >= 360000],
  [admin_level = '2'][way_pixels >= 360000],
  [admin_level = '3'][way_pixels >= 196000],
  [admin_level = '4'][way_pixels >= 196000],
  [zoom >= 12][admin_level = '5'],
```

So from z11 we now shown the country name along the border, if the
country takes up less than 360,000 pixels.

Previously the labels along the borders were only shown at z16 and
above. I submitted the PR which caused them to be shown sooner. Admin
level 2 (country) labels could actually been shown along the borders
as soon as z9, but I decided not to make such a large change all at
once.

Do others think it would be helpful if the border labels for countries
were shown as early as z9?

**Comment by jeisenbe** [comment]
Ah, now I've checked the area, and I see that the border labels are not yet shown on z11 to z15. While PR #3677 has been merged since Feb 15th, the rendering has not been updated because the change has not taken affect on the server. 

z11 China-Russia-Mongolia border
![z11-china-russia-mongolia](https://user-images.githubusercontent.com/42757252/54863414-aaa14780-4d8b-11e9-985f-94222715f1d0.png)

Still, I could see a benefit to considering showing the border text labels at z9 for admin_level=2

**Comment by jidanni** [comment]
Here is the current situation for stundents trying to figure out what
countries they are looking at upon the Malaysia (M) - Brunei (B)
border. "X" means the county name is completly absent from the screen
in any form.

 M B [19](https://www.openstreetmap.org/#map=19/4.58533/114.07599)
 M B [18](https://www.openstreetmap.org/#map=18/4.58533/114.07599)
 M B [17](https://www.openstreetmap.org/#map=17/4.58533/114.07599)
 X B [16](https://www.openstreetmap.org/#map=16/4.58533/114.07599)
 X X [15](https://www.openstreetmap.org/#map=15/4.58533/114.07599)
 X X [14](https://www.openstreetmap.org/#map=14/4.58533/114.07599)
 X X [13](https://www.openstreetmap.org/#map=13/4.58533/114.07599)
 X X [12](https://www.openstreetmap.org/#map=12/4.58533/114.07599)
 X X [11](https://www.openstreetmap.org/#map=11/4.58533/114.07599)
 X B [10](https://www.openstreetmap.org/#map=10/4.58533/114.07599)
 X B [9](https://www.openstreetmap.org/#map=9/4.58533/114.07599)
 X B [8](https://www.openstreetmap.org/#map=8/4.58533/114.07599)
 M B [7](https://www.openstreetmap.org/#map=7/4.58533/114.07599)
 M B [6](https://www.openstreetmap.org/#map=6/4.58533/114.07599)
 M B [5](https://www.openstreetmap.org/#map=5/4.58533/114.07599)
 M X [4](https://www.openstreetmap.org/#map=4/4.58533/114.07599)
 M X [3](https://www.openstreetmap.org/#map=3/4.58533/114.07599)
 X X [2](https://www.openstreetmap.org/#map=2/4.58533/114.07599)
 X X [1](https://www.openstreetmap.org/#map=1/4.58533/114.07599)
