### ISSUE TITLE
platforms ways on route=ferry relations rendered identically to route ways

### ISSUE THREAD

**Issue by tpikonen** [gravitystorm/openstreetmap-carto#3726]
All ways which are part of route=ferry relation are now rendered with a blue dashed line and a route name label. This makes ways which have a 'platform' role, like ferry terminals look funny, for example [here](https://www.openstreetmap.org/#map=19/60.16734/24.98012):
![ferry-platform](https://user-images.githubusercontent.com/3215/54863380-8c6a2600-4d50-11e9-9549-8f437a8e3489.png)

Ways in a route=ferry relation should be rendered like above only when they have no role, or for legacy routes, when they have 'forward' or 'backward' roles.

**Comment by jeisenbe** [comment]
Should the terminal actually be included in the route relation?

The wiki page for relation:route says that a ferry route is:

"The route a ferry takes from terminal to terminal. Please make sure to add at least one node per tile (zoom level 12), better at least one every few km, so offline editors catch it with bbox requests."

The wiki page for route=ferry (https://wiki.openstreetmap.org/wiki/Tag:route=ferry) says:

"Draw a way way from one ferry terminal to another and add route=ferry and name=*."

and

"The ferry route should start and end at a ferry terminal"

This sounds like the route should only include the actual path of the ferry, not the terminal building?

**Comment by tpikonen** [comment]
route=ferry is used (also) for bus-like public transport ferries in cities. These routes are tagged with the same conventions as other public transport modes and include members with platform and possibly stop roles.

**Comment by jeisenbe** [comment]
How many relations which are tagged with route=ferry  include the terminals
in the relation?

Would you have the time to document this usage in the wiki?

Perhaps it should also be discussed on the Tagging mailing list to confirm
that it is the best way to tag these ferry routes.

**Comment by matkoniecz** [comment]
For me it looks like a tagging mistake, I would check is it actually desirable tagging method.

Is JOSM validator or Osmose complaining about such tagging?

**Comment by tpikonen** [comment]
> For me it looks like a tagging mistake,

No, this tagging is widely used, and in fact the only sensible way to tag this kind of ferry routes (unless there is a tag other than route=ferry for public transport ferry routes, which there is not).

The wiki documentation for public transport is a disaster area (I like the [Refined public transport](https://wiki.openstreetmap.org/wiki/Proposed_features/Refined_Public_Transport) tagging scheme, but also that page is rather poorly written) but ferries are are explicitly mentioned also in the [main public transport page](https://wiki.openstreetmap.org/wiki/Public_transport#Ferries)).

Please see [this](https://overpass-turbo.eu/s/Hgy) Overpass query to find platform member ways of route=ferry relations. There are results at least in Netherlands, Germany and Finland.

**Comment by imagico** [comment]
I think the solution is quite simple:  We stop rendering route=ferry on relations.  The dominating tagging of route=ferry is on ways as a locally verifiable way to indicate:  _Along this route public ship based transport occurs on a regular basis_.  Route relations for ferries are something very different and not an alternative way to map the same thing.  Treating both the same way as we do now is misleading.  It is a bit like tram tracks vs. tram routes - except that a ferry route is of course not physically manifested.

This would also avoid the current double labeling of ferry routes like here:

https://www.openstreetmap.org/way/130362686#map=13/53.9560/8.5664

**Comment by tpikonen** [comment]
> I think the solution is quite simple: We stop rendering route=ferry on relations.

This is probably the simplest solution. The alternative would be to filter out ferry ways based on their role in route=ferry relations, but apparently there is no relation role filtering made in any of the SQL queries in project.mml.

Public transport routes are not rendered in openstreetmap-carto anyway, so this is in line with other transit modes.

See my PR for a simple implementation.

**Comment by Marc-marc-marc** [comment]
if ferry route should not display in openstreetmap-carto anymore, there is no rational too keep it rendered if the route use a way but not if it use a relation (with a relation, the way member don't duplicate the tag of the relation, so it'll also not be rendered anymore)
