### ISSUE TITLE
v4.21 release

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#3736]
I'd like to get out a v4.21 release for a branch point for schema changes, and to get the pointonsurface stuff out.

Are there any other *ready to merge* PRs that we should get in before release?

**Comment by imagico** [comment]
I have merged a number of things that were ready a few days back so i think we would be fine for a release now.

**Comment by jeisenbe** [comment]
I'm fine with doing the release now. The PRs that are currently open can wait till the next month.

**Comment by pnorman** [comment]
If someone else can test and handle the release process that would be good. I'm busy with a move that includes my computer.

**Comment by pnorman** [comment]
Just noting that this is on my to-do list, and my development machine is still in its shipping box.

**Comment by pnorman** [comment]
Done, and created the `schema_changes` branch. As a reminder for maintainers, when tagging a new release it's your responsibility to merge it to this branch

> If there are any long-running development branches check them out and merge the new release with git merge $NEW_RELEASE

**Comment by jeisenbe** [comment]
I wish I had mentioned that #3759 should have been fixed before this release (All shop text labels are no longer being displayed after #3712). I've submitted #3760 with the fix.

It would also be nice to fix #3765 which is also caused by #3712 but it's not as noticeable.

**Comment by pnorman** [comment]
These sound like big enough bugs to release a v4.21.1

**Comment by kocio-pl** [comment]
Another big enough regression problem: #3765.

**Comment by kocio-pl** [comment]
Yet another regression bug: #3780.

**Comment by pnorman** [comment]
I've tagged v4.21.1 somewhat belatedly. Do we think there's enough stuff for v4.22.0 soon? If so I'll hold off the v4.21.1 announcement.

**Comment by jeisenbe** [comment]
It looks like no new bugs have been discovered in the past couple of months. Do we have enough for v4.22.0 or should v4.21.1 be released soon?

**Comment by pnorman** [comment]
I'd go for v4.22.0 after reviewing PRs

**Comment by jeisenbe** [comment]
Close in favor of v4.22.0
