### ISSUE TITLE
Consider rendering winter sports pistes

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3740]
### Winter sports (Skiing, Snow Boarding, Sledding, etc)

Currently winter sports pistes, areas uses for skiing, snowboarding and related snow sports are tagged as  [piste:type](https://wiki.openstreetmap.org/wiki/Key:piste:type), mainly [piste:type=downhill](https://wiki.openstreetmap.org/wiki/Tag:piste:type%3Ddownhill) and [piste:type=nordic](https://wiki.openstreetmap.org/wiki/Tag:piste:type%3Dnordic). These tags are used almost 90k and 70k times respectively. 

Most ski and snowboarding areas are in rural areas where few other features are mapped, however, there may be ski lifts and track or service roads and paths that are mapped in the area which are currently rendered.

While these are specialized features, they are similar to golf=* tags in that there are few other features shown in the same area. Also, piste:type=downhill is currently rendered by the French style at [openstreetmap.fr](https://www.openstreetmap.fr), as are golf features. 

However, unlikely golf courses, pistes are winter-only features in most areas, which means that there may be more difficulties in deciding on an appropriate rendering which will work globally. They are also mapped as linear features most frequently, rather than as areas. 

There are also a number of different types of pistes, beyond downhill skiing/snowboarding and nordic (cross-country) skiing, and the different types may require different renderings. 

As a start, we could consider rendering downhill and nordic pistes in a [similar style](https://github.com/cquest/osmfr-cartocss/tree/master/sports.mss) to openstreetmap.fr, with a line along the way in a color that corresponds with the type of piste, and a text name label along the line. We could also add a oneway arrow where appropriate. 

Please comment if you are interested in this issue. I'd also appreciate if others could share some screenshots from the other map styles which currently render these features, for comparison.

**Comment by polarbearing** [comment]
IIRC, there are specialized maps to show that. If you render ski routes, then with the same logic you'd need to render hiking and biking routes. There are all special maps for that. I see no need on a general style.

**Comment by jeisenbe** [comment]
We render bicycle paths and hiking paths.

A closer analogy would be golf=hole, which is not yet rendered (it also
requires database changes) but has been proposed.

Skiing pistes are somewhat similar, except that they are seasonal in most
places.

**Comment by polarbearing** [comment]
I said routes, not paths. 

Skiing: https://slopes.waymarkedtrails.org/#?map=14!47.1667!10.1699
Hiking: https://hiking.waymarkedtrails.org/#?map=13!47.3807!10.3517
Cycling: https://cycling.waymarkedtrails.org/#?map=14!47.8196!10.8951
Mountainbiking: https://mtb.waymarkedtrails.org/#?map=14!47.2949!11.4002
Inline Skating: https://skating.waymarkedtrails.org/#?map=13!47.3492!8.6879
Horse riding: https://riding.waymarkedtrails.org/#?map=12!51.7996!-0.567

**Comment by HolgerJeromin** [comment]
There are so many Winter features to render. 
http://opensnowmap.org/?zoom=15&lat=46.967&lon=10.9923&layers=snowbase&marker=false

This is nothing for a general style as it is even invisible 3/4 of the time of the year. Most of the downhill pistes are meadow the rest of the year with (already rendered) infrastructure like pylons on top.

**Comment by matkoniecz** [comment]
Even waymarkedtrails is not rendering all with one style. mapy.cz also has a separate style for ski trails/pistes.

I think that it is OK to keep it not rendered in a general style.

**Comment by jragusa** [comment]
I'm against to show winter sports pistes because :
1/ [http://opensnowmap.org/](http://opensnowmap.org/) is your friend if you need information,
2/ some pistes use roads/tracks in winter so their rendering will probably blur the latter and,
3/ it will clutter some area.

**Comment by polarbearing** [comment]
Proposing to close.

**Comment by imagico** [comment]
Closing because the general opinion seems to be that

* this is too specialized for a general purpose style
* there are existing specialized map styles that cover this
* most pistes are seasonal and rendering them would be confusing and misleading during summer.
