### ISSUE TITLE
Consider rendering ref numbers for campsite=camp_pitch

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3741]
### Should we render tent pitch locations within a campsite?

- Currently amenity=campsite is rendered. Campsites often after numbered and signed pitch locations, where a tent can be pitched or a camper trailer can be parked. These are not usually considered addresses so they are not rendered. 

- This situation is somewhat like that with to allotments=plot, which is a reference number that is useful for routing and orientation, but not an official address. We could render the "ref=*" tag for camp_site=camp_pitch at high zoom levels. 

- But this will require changing the lua transformations file to import closed ways tagged camp_site=camp_pitch as a polygon feature

- [camp_site=camp_pitch](https://wiki.openstreetmap.org/wiki/Proposed_features/camp_site_pitch) is used 6932 according to [taginfo](https://taginfo.openstreetmap.org/tags/camp_site=camp_pitch) but unfortunately there is no list of combinations. 

- I downloaded all features mapped as nodes or ways and tagged camp_site=camp_pitch + ref=* and found 3,012 features with both tags. None of the features had an "addr:unit" tag, only 29 had an addr:housenumber. There were 145 camp_site=camp_pitch with a name, mostly a number or "campsite <number>". 

This suggest there is enough use of this tag to be considered for rendering, and "ref=*" is the correct field to render. 

However, it should be better documented first, and a database reload would need to take place if we want to support mapping as a closed way.

**Comment by Adamant36** [comment]
This would helpful in getting people to stop using the name tag on camp_site=camp_pitch in places where it should be the ref #. 

Btw, I'm not sure if your aware but you can do a tag count query in OverPassTurbo by doing something like 

```
out:csv(::count)][timeout:250];

nwr["name"="Kathmandu"]["shop"="outdoor"];
  
out count;
```
And just modifying it for whatever tags you want a count for.

**Comment by jeisenbe** [comment]
Note that the `camp_site=camp_pitch` was not approved: https://wiki.openstreetmap.org/wiki/Proposed_features/camp_site_pitch

Some users would prefer using `tourism=camp_pitch`, others would like an entirely new tag

**Comment by jeisenbe** [comment]
The tag camp_site=camp_pitch was deprecated and now tourism=camp_pitch is the approved tag fo this feature, and is now the most common tagging, used 7000 times, while camp_site=camp_pitch has decreased to 4500 uses and camp_site=pitch is down to 0. So I am closing this issue, but we can consider rendering the ref for tourism=camp_pitch, which won't require waiting for database load.
