### ISSUE TITLE
Hide underground power lines

### ISSUE THREAD

**Issue by Tomasz-W** [gravitystorm/openstreetmap-carto#3746]
Rendering underground power lines in the same way as above-ground ones leads to map messing in some places. Another thing is that they are not useful for most of the map users.

Example places where it causes visual mess:
https://www.openstreetmap.org/way/364533289
https://www.openstreetmap.org/way/127968407
https://www.openstreetmap.org/way/638878098
https://www.openstreetmap.org/way/638878097

Related to https://github.com/gravitystorm/openstreetmap-carto/issues/3506

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Tag:power=line?uselang=en-US has

> High-voltage power lines used for power transmission, supported by towers/pylons, or in some places or situations, by poles Edit or translate this description. 

and

> Use power=cable with location=underground for undergound or underwater power cables

Is there a reason to suspect that OSM Wiki is wrong?

**Comment by seb-1204** [comment]
I wonder if they can be actually verified without information that is access limited/restricted. They are by definition not really visible, maybe there are markers on the road/building?

**Comment by famo** [comment]
@Tomasz-W those are tagging errors, quote from the wiki:

> A **power=line** is carried on power=towers, but may be supported by poles, especially on lines in the subtransmission grid, that connects the main grids with the distribution grid. ...

and

> Use **power=cable** with location=underground for underground or underwater power cables. ...

In short there are no underground power lines, only power cables...

The layer tag, I believe, is also wrong (probably resulting from the wrong power tagging).
