### ISSUE TITLE
Set “cache-features: true” in project.mml?

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#3756]
Set `cache-features: true` in project.mml?

The option `cache-features: true` makes Mapnik cache SQL results between attachments within the same layer.

Currently, we do not use it. Would it be for performance reasons a good idea to enable it on all layers that have attachments?

Mapnik does not use  `cache-features: true` because of [possible memory issues](https://github.com/mapnik/mapnik/issues/657), but memory issues [does not seem to be likely](https://github.com/mapnik/mapnik/issues/3977#issuecomment-417923243).

**Comment by pnorman** [comment]
This is probably a good idea, but needs testing
