### ISSUE TITLE
Elevation / height no longer rendered for peaks, alpine huts, waterfalls etc.

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3765]
## Expected behavior
- Peaks, volcanoes, saddles, alpine huts, and guideposts were previously displayed with their name and their elevation in meters when this was tagged as `ele=*`
- The height of a waterfall was added to the name as well

## Actual behavior
- Currently the elevation and height are no longer rendered, due to changes in `project.mml` in PR #3712

## Test renderings illustrating the problem

Current rendering of Mt Everest with master branch
![z16-everest-current](https://user-images.githubusercontent.com/42757252/56727120-fda35b80-678a-11e9-9fca-2b69ad51fbaa.png)

Rendering with commit 712afb87f8c7d506437cedb5273cea9fa367f524 (immediately before PR 3712) and same data
![z16-everest-before-ele-shown](https://user-images.githubusercontent.com/42757252/56727142-0a27b400-678b-11e9-895d-4bcd2e46c0d6.png)

Test area current
![z19-test-height-ele-current](https://user-images.githubusercontent.com/42757252/56727309-5ffc5c00-678b-11e9-8b22-43becb5aba23.png)

Before 
![z19-ele-height-before](https://user-images.githubusercontent.com/42757252/56727301-5d016b80-678b-11e9-8303-3db188701bc3.png)

**Comment by matkoniecz** [comment]
Thanks for catching this!

**Comment by jeisenbe** [comment]
I've tried to fix this, but I can't figure out how to reformat the SQL correctly. 

Previously this was in the main SQL select for the `text-point` layer:

```
            CONCAT(
                name,
                CASE WHEN name IS NOT NULL AND (elevation IS NOT NULL OR height IS NOT NULL) THEN E'\n' ELSE NULL END,
                CASE WHEN elevation IS NOT NULL THEN CONCAT(REPLACE(ROUND(elevation)::TEXT, '-', U&'\2212'), U&'\00A0', 'm') ELSE NULL END,
                CASE WHEN height IS NOT NULL THEN CONCAT(ROUND(height)::TEXT, U&'\00A0', 'm') ELSE NULL END
            ) AS name,
            CASE
              WHEN "natural" IN ('peak', 'volcano', 'saddle') THEN elevation
              WHEN "waterway" IN ('waterfall') THEN height
              ELSE NULL
            END AS score,
```

And this was in the subselect:

```
                CASE
                  WHEN "natural" IN ('peak', 'volcano', 'saddle')
                    OR tourism = 'alpine_hut' OR (tourism = 'information' AND tags->'information' = 'guidepost')
                    OR amenity = 'shelter' THEN
                    CASE
                      WHEN tags->'ele' ~ '^-?\d{1,4}(\.\d+)?$' THEN (tags->'ele')::NUMERIC
                      ELSE NULL
                    END
                  ELSE NULL
                END AS elevation,
                CASE
                  WHEN "waterway" IN ('waterfall') THEN
                    CASE
                      WHEN tags->'height' ~ '^\d{1,3}(\.\d+)?( m)?$' THEN (SUBSTRING(tags->'height', '^(\d{1,3}(\.\d+)?)( m)?$'))::NUMERIC
                      ELSE NULL
                    END
                  ELSE NULL
                END AS height,
```

Note that we would need to change the "height" column for waterfalls into "elevation" or something like "int_height" since man_made=tower is also selected with "height" in the `amenity-points` layer.

I've tried to insert these lines back into the new `id: amenity-points` layer, but I get errors.

Perhaps @pnorman has time to look into this one?
