### ISSUE TITLE
Lifecycle prefix rendering.

### ISSUE THREAD

**Issue by Otavva** [gravitystorm/openstreetmap-carto#3769]
I thought tags with lifecycle prefix are render on the map. But they don't. Will they do or not? In my case I want to map abandoned and ruined bridge. But with the abandoned: prefix this bridge isn't rendered. Actually all of the building or roads with lifecycle prefix should be renderd because without this the prefixes will useless. Thank you.

P.S. I sayed why this bridge should to be rendered in [this](https://wiki.openstreetmap.org/wiki/Talk:Lifecycle_prefix#Lifecycle_prefix_rendering) message.

**Comment by matkoniecz** [comment]
AFAIK currently unused standing buildings should be tagged as `building=*`, not as `abandoned:building`.

Is there any case where rendering `abandoned:highway` would make sense? For example road turned into pedestrian road (making its previous function abandoned) should be tagged as `highway=pedestrian`, abandoned major road now used as cycleway can and should be tagged as `highway=cycleway` that is rendered.

> this message.

This message mentions destroyed bridge. Such objects should be present in OSM only in cases where it is likely that other mappers would mistakenly map them as existing - because something is still visible on aerial images or it was destroyed recently.

But OpenStreetMap is not place to map history.

**Comment by Adamant36** [comment]
"Is there any case where rendering abandoned:highway"

Something like what's here maybe. You have to go to edit to see it. Its been there that way for like ten years, and its not a bike path or anything. It just sits there. It actually bugs me quit a lot. Both that's its not rendered with the abandoned tag on it and that they never just turned into a bike path. Maybe it's to small or something. I'm sure there's other examples. 

https://www.openstreetmap.org/#map=19/40.68112/-122.36748

**Comment by Adamant36** [comment]
Oh yeah duh, like here in Government Camp. You have a whole small town, or at least what use to be with abandoned roads. 

https://www.openstreetmap.org/#map=16/40.6914/-122.3897

There's also this spot. 
https://www.openstreetmap.org/#map=18/40.68191/-122.35065

They shouldn't be tagged as track roads.

**Comment by Otavva** [comment]
@matkoniecz
And this bridge is mapped as existing! As I say in the wiki talk it'll be a mistake if I just delete it. But maybe you right that OSM is'nt place for a history. And buildings are should mapped as `building=ruins`. In this case I'm agree with you. So we need something like `bridge=ruined` for brdiges. But in this case we should to make new tag for roads and for railways. Something like '*=ruins' or '*=unused'. But I think tagging is not a problem. But the rendering is.

P.S. Why we have lifecycle prefixes in this case? After reading the wiki I understand that this feature already applied but it isn't rendered yet. It is at least strange.

**Comment by Otavva** [comment]
Here this bridge is.
https://www.openstreetmap.org/way/36931535#map=16/48.6340/39.5151

**Comment by HolgerJeromin** [comment]
> Here this bridge is. https://www.openstreetmap.org/way/36931535#map=16/48.6340/39.5151

Right now I see v11 of this way which is tagged:
````
bridge=yes
construction=primary
highway=primary
````
Which is rendered fine (but the tagging can not be right).
In v10 it was: `demolished:highway=primary`

IMO such a thing could have a line with `demolished:highway=primary`. 
If it is really significant it should get another osm element around it with [man_made=bridge](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dbridge) which would be rendered.
Logic behind the rendering: There is no usable highway, but a bridge by itself.

**Comment by HolgerJeromin** [comment]
The Government Camp could be mapped as highway=service (and perhaps access=no/private).

**Comment by Otavva** [comment]
@HolgerJeromin 
The previous version was my bad tagging. Your's idea is better than just delete it so I find the answer for the brige. **But anyway question about lifecycle prefix stay opened.**

**Comment by aceman444** [comment]
@Otavva 
No v10 with demolished:highway=primary made sense if you wanted a demolished (non-working) road.
Now in v11 with highway=primary it is a normal working road that can be passed by any vehicle. The construction=primary tag is ignored if highway=construction isn't used. But you say it is no construction, so that tagging would also be bad.

**Comment by HolgerJeromin** [comment]
> But anyway question about lifecycle prefix stay opened.

Not really. IMO the idea behind the prefix was to explicit "hide" the information for the normal data consumer, as the feature is not in a normal usable state.

> Of course I'll map it like bridge but I can't map it like ruined bridge.

You can. But why to you want to show an unusable pile of stones (worst state of a ruined bridge) in a generic map? :-)

**Comment by matkoniecz** [comment]
In general, it is preferable to have issues about specific things so I will review objects mentioned here and open a new issues similar to #2030 "Render disused:railway=rail like railway=disused"

**Comment by matkoniecz** [comment]
Unused buildings: `building=*` tagging is covering them, so there is no need to render anything new.

Ruined bridges: `ruined:man_made=bridge` is probably a way to tag them, but I think that ruined bridges are out of scope for a general purpose map.

`abandoned:highway` would conflict with rendering current road state. For example road turned into pedestrian road (making its previous function abandoned) should be tagged as `highway=pedestrian`, abandoned major road now used as cycleway can and should be tagged as `highway=cycleway` that is rendered. Also, in cases like this I am dubious whatever even should be tagged `abandoned:highway`

**Comment by Otavva** [comment]
But how can I map dead end of the highway?

Honestly, I agree that lifecycle prefix is bad idea and it is have no need to be rendered. So maybe should we raise the issue about deleting of this thing? Of course this question for wiki. This prefixes makes really many troubles and mistakes, because people (and me too) are thinking that them are aproved and fully workable. But they are not.

**Comment by HolgerJeromin** [comment]
> This prefixes makes really many troubles and mistakes, because people (and me too) are thinking that them are aproved and fully workable. 

They are IMO fully workable in their scope. If there are buildings I know are removed, but are visible on Bing image it is better to leave the outline way with a prefix `destroyed:building`. An alternative would be to add only a `note` on the way. 
Otherwise the next remote mapper will add the buildings again.

**Comment by Otavva** [comment]
Ok. I think this conversation moves from rendering theme to the osm wiki. Thank you all for the your opinion! :)
