### ISSUE TITLE
Checkpoints icon rendering.

### ISSUE THREAD

**Issue by Otavva** [gravitystorm/openstreetmap-carto#3770]
I think we should have the icon for `military=checkpoint` tag because it will be more informative. Of course in Europe no any border control, but in the post-soviet contryes (of course countries that isn't part EC) there are many border checkpoints. And, of course, many other countries of the world are have them. They are controlled by military.

Next case is checkpoints in the war area. They are placed on the roads and military check your documents every time when you ride on this road. If you use OSM and there is no one icon on the road you'll be surprised when you see the checkpoint. But we need safe maps!
 
I wrote the [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Advanced_checkpoints) for a new tag `checkpoint=border` for checkpoints placed on the border and a new tag `checkpoint=war` for checkpoints in the war area. I think them should use different icons, because they are controlled by different military parts. War checkpoints are controlled by a military but border checkpoints are controlled by border guards.

I didn't draw any icon because I'm not the best painter. But if no one draws the icons, I will.

Thank you, for your time.

**Comment by jeisenbe** [comment]
1) military=checkpoint is used over 3000 times, slowly increasing over the past 6 years, but it has never been formally proposed or defined. The current wiki page is very short: https://wiki.openstreetmap.org/wiki/Tag:military%3Dcheckpoint

Before we could consider rendering this, someone needs to research how the tag is currently used around the world. Is it used at borders, in conflict areas, at the entrances to military bases or landuse? You can use JOSM or Overpass-turbo.eu to download the current nodes and check how they are actually used. I suspect many of them will be entrances to military facilities, based on the wiki description, not border points or conflict zone checkpoints. 

We might be able to render this in a similar style to one of the other barrier features, if it is used in a consistent way.

2) If you would like to get your proposal for a new tag approved, please read the page about the [proposal process](https://wiki.openstreetmap.org/wiki/Proposal_process), then discuss your proposal on the [Tagging mailing list](https://lists.openstreetmap.org/listinfo/tagging).  

In this style we try to show tags that are already clearly defined, accepted and used by the community. Getting your tags approved will not guarantee that they will be rendered, but it will make it more likely that other people will use them.

**Comment by Otavva** [comment]
> someone needs to research how the tag is currently used around the world.

Ok. I'll do this.

And sorry for I was hurried about proposing rendering of the not approved tags.

**Comment by Otavva** [comment]
I have checked this tag on the Overpass Turbo. This tag is mostly used by areas and nodes. But there is one big problem - this tag is used not only by military checkpoints. They used it for many civil checkpoints in the industrial area. And not only on them. So maybe now the rendering for this tag is useless, becouse it is uncontrollable. People use it as them want. So I close this issue because we shoudl make this tag more standartized at first. Thank you!
