### ISSUE TITLE
Multipolygon relations still require area=yes tags, but should be implicit

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#3776]
### Expected behavior
If you add highway=pedestrian to a multipolygon relation it should be clear that this is about an area and should not require an additional area=yes tag
### Actual behavior
It doesn't render the feature at all, if area=yes is missing
### Links and screenshots illustrating the problem
An example is here: https://www.openstreetmap.org/way/244270393

![Screen Shot 2019-05-06 at 14 13 41](https://user-images.githubusercontent.com/581288/57224274-3227da80-7009-11e9-9afe-df44e43c3f12.png)

**Comment by mboeringa** [comment]
That multipolygon relation is broken, it has a self intersection according to JOSM, as the example display you added already shows if you look closely above the patch of grass.

Screenshots from JOSM, especially see the second zoomed in image:

![afbeelding](https://user-images.githubusercontent.com/7635726/57244814-8e0a5780-7039-11e9-8d4d-03649b8fe311.png)

![afbeelding](https://user-images.githubusercontent.com/7635726/57244851-a5e1db80-7039-11e9-9920-0e3bbe098036.png)

**Comment by matkoniecz** [comment]
The issue you've identified is regarding a tagging issue and not something wrong with the renderer. As such, I'm closing this issue.

In general it is a good idea, especially for multipolygons, to run JOSM validator to check whatever data is correct.

**Comment by matkoniecz** [comment]
Migrated to https://www.openstreetmap.org/note/1769553 as an OSM data issue

**Comment by matkoniecz** [comment]
@mboeringa Thanks for a check!
