### ISSUE TITLE
Fountain base is rendered above text

### ISSUE THREAD

**Issue by pietervdvn** [gravitystorm/openstreetmap-carto#3777]
### Expected behavior

The text should be rendered above the fountains (or the blue dot should be visible too)

### Actual behavior

Text is rendered under the bigger, cyan dots.

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/#map=17/50.84393/4.35660

![Screenshot_2019-05-08_16-36-17](https://user-images.githubusercontent.com/1466478/57383728-96849e80-71af-11e9-8e91-adf02e68aa66.png)

**Comment by imagico** [comment]
Thanks - this is already covered by #1934.
