### ISSUE TITLE
Feature request: Introduce more granular layers

### ISSUE THREAD

**Issue by Klaus-Tockloth** [gravitystorm/openstreetmap-carto#3783]
I very often use the osm-carto layer feature to avoid the rendering of a complete feature group (e.g. admin borders, nature reserve borders, highway shields, tourism borders, area texts, ...). A very useful concept. But sometimes it is impossible to avoid a feature. Often this is unwanted text. Something like this:
 
<img width="600" alt="Bildschirmfoto 2019-05-19 um 10 35 06" src="https://user-images.githubusercontent.com/5493128/57979752-744a1680-7a22-11e9-80ef-b9cd0f683e85.png">

https://www.openstreetmap.org/#map=14/54.8713/8.3170
 
Unwanted labels: NSG Ratumbecken, NSG Baakdeel-Ratum/Sylt

Feature request: Allow more control over the label rendering by introducing more granular layers.

**Comment by imagico** [comment]
I am not quite sure about the nature of your request.  If you want the ability to turn off specific map elements on the map on osm.org - this is kind of the wrong place for such a request.

If you would like the different label types to be separated into different layers so you can more easily turn them on and off when rendering the map yourself - that would in principle be possible but it would put constraints on label prioritization (you can't do cross-layer prioritization in Mapnik).  I don't think we would want to do that.  This would especially mean you could not use a way_area criterion for the starting zoom level without getting randomly disappearing labels as you zoom in.

**Comment by StyXman** [comment]
The only solution you have left it to hunt the specific part of the style that renders those labels and remove it or comment it out. Extra points if you also modify the SQL statements and remove the references to the data needed for rendering them. I think this is typical of forks.

**Comment by Klaus-Tockloth** [comment]
> I am not quite sure about the nature of your request. If you want the ability to turn off specific map elements on the map on osm.org - this is kind of the wrong place for such a request.

No, that isn't what I want. The map on openstreetmap.org should not be affected.

> If you would like the different label types to be separated into different layers so you can more easily turn them on and off when rendering the map yourself ...

That's exactly the feature request. More layers for more control. An example makes it perhaps a bit clearer. My service renders a map based on the default osm-carto style but hides some features:
```
HideLayers: admin-low-zoom,admin-mid-zoom,admin-high-zoom,admin-text,nature-reserve-boundaries,nature-reserve-text
```

**Comment by Adamant36** [comment]
"That's exactly the feature request. More layers for more control." 

That was something I had thrown around the idea of awhile back, but it never seemed to take off for some reason. Maybe rendering speed issues. It would help the code be better organized if there were more layers though in my opinion.

**Comment by jeisenbe** [comment]
I think this request cannot be filled, because rendering performance is worse with more layers, and code complexity increases. Greatly increasing the number of layers would make it more difficult to maintain the style. So I recommend closing this issue.

**Comment by imagico** [comment]
I agree.

The main considerations for the layer structure should IMO be

* cartographic goals and quality
* rendering efficiency
* code maintainability

Disabling certain features in the style does not necessarily require them to be implemented in separate layers.  Mss modifications or script based processing of project.mml to modify the style are perfectly doable and it would be possible to support this further by introducing SQL coding conventions that simplify scripted modifications.

For the specific case of this issue modifying this

https://github.com/gravitystorm/openstreetmap-carto/blob/fcf1892e5b6f025010f8d8e34aa991082a97b27c/amenity-points.mss#L2255-L2298

would be the solution.
