### ISSUE TITLE
Bicycle map the rcn_ref symbol numbers are missing "3 digits"

### ISSUE THREAD

**Issue by Jakkajakka** [gravitystorm/openstreetmap-carto#3793]
### Expected behavior
Bicycle map the rcn_ref symbol numbers "3 digits" are missing
### Actual behavior
the symbol in circle is blanc
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=14/51.0761/5.6181&layers=CN

**Comment by Nakaner** [comment]
This is the bug tracker and source code repository of the map style "OSM Carto", not the Cycle Map provided by Thunderforest you are complaining about. That map style is proprietary.

**Comment by Jakkajakka** [comment]
I try to find Thunderforest forum? thx
