### ISSUE TITLE
Render wetland=saltmarsh with a fill color

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3799]
- Unlike most wetlands, wetland=saltmarsh has only a pattern with no fill
- This is the same situation as with wetland=mangrove and wetland=reedbed; all 3 features currently have no fill, because when we used land polygons the ocean and water fill colors were rendered below landcover, and these features can be found outside of the coastline or over water areas.
- There are issues for the two other features requesting a color fill rendering: #2013 and #2025
- This new issue is created so that all 3 features can have a color fill added, now that the oceans and water areas are rendered above `landcover`
- Now, if wetland=saltmarsh is drawn outside of the coastline it will continue to have a blue, ocean color fill; the fill color would only be seen when the feature is over land. 
- It is suggested that wetland=saltmarsh could have the same color as wetland=marsh, or a similar color

**Comment by jeisenbe** [comment]
# Test renderings - Delaware

## Before: current rendering of saltmarsh without fill color
z14 Delaware seashore - saltmarsh at center (park and residential fill shows), wetland=marsh with fill on left
![z14-delaware-seashore-marsh-before](https://user-images.githubusercontent.com/42757252/59104335-4ba3a580-896c-11e9-9754-369514ffcf4a.png)

14 Salt marsh islands on right and upper left
![z14-burton-island-marsh-before](https://user-images.githubusercontent.com/42757252/59104337-4cd4d280-896c-11e9-80fa-8c48ee0cf1c9.png)

z14 - Salt marsh on left, Dodd marsh on right is wetland=marsh
![z14-dodd-marsh-saltmarsh-before](https://user-images.githubusercontent.com/42757252/59104338-4d6d6900-896c-11e9-9c8a-903c63f5392e.png)

## Test 1: Saltmarsh with `@grass` fill - `#cdebb0`
- same as wetland=marsh, wetland=fen and wetland=wet_meadow

z14 @grass - Delaware seashore - saltmarsh at center (park and residential fill shows), wetland=marsh with fill on left
![z14-delaware-seashore-saltmarsh-grass-fill-after](https://user-images.githubusercontent.com/42757252/59104508-b7860e00-896c-11e9-92fc-19f8a13a99cb.png)

z14 @grass - Salt marsh islands on right and upper left
![z14-burton-island-saltmarsh-after](https://user-images.githubusercontent.com/42757252/59104525-c371d000-896c-11e9-9962-e4ec5b5ad76e.png)

z14 @grass - Salt marsh on left, Dodd marsh on right is wetland=marsh
![z14-dodd-marsh-saltmarsh-after-grass-fill](https://user-images.githubusercontent.com/42757252/59104533-c8368400-896c-11e9-92f6-a43078a5a872.png)

## Test 2: Saltmarsh with `@campsite` fill - `#def6c0`

z14 Delaware seashore - saltmarsh at center (park and residential fill shows), wetland=marsh with fill on left
![z14-delaware-seashore-saltmarsh-campsite-color](https://user-images.githubusercontent.com/42757252/59104548-d1bfec00-896c-11e9-870e-8db3f323249c.png)

14 Salt marsh islands on right and upper left
![z14-burton-island-saltmarsh-campsite-fill](https://user-images.githubusercontent.com/42757252/59104629-003dc700-896d-11e9-89d2-028c4e4e28bb.png)

z14 - Salt marsh on left, Dodd marsh on right is wetland=marsh
![z14-dodd-marsh-saltmarsh-campsite-fill](https://user-images.githubusercontent.com/42757252/59104645-09c72f00-896d-11e9-861a-fec319742f45.png)

**Comment by jeisenbe** [comment]
## Zeeland, Netherlands saltmarshes

A. Large salt marsh with many large tidal channels
https://www.openstreetmap.org/#map=13/51.3590/4.1393

B. 2 small salt marshes: one over sea water, one over land in database
https://www.openstreetmap.org/#map=15/51.4552/3.6555

### 0) Before
A. z13
![z13-verdronken-saltmarsh-before](https://user-images.githubusercontent.com/42757252/59107448-9e349000-8973-11e9-8f55-74be3298231d.png)

B. z15
![z15-slufter-saltmarshes-zeeland-before](https://user-images.githubusercontent.com/42757252/59107456-a12f8080-8973-11e9-8aaf-2af2c27060cc.png)

### 1) Saltmarsh with `@grass` fill - `#cdebb0`
A. z13
![z13-verdronken-saltmarsh-grass-fill](https://user-images.githubusercontent.com/42757252/59107471-a987bb80-8973-11e9-9685-ba1b1f8ddf03.png)

B. z15
![z15-slufter-saltmarsh-grass-fill](https://user-images.githubusercontent.com/42757252/59107489-b86e6e00-8973-11e9-92fc-22b3af6231c0.png)

### 2) Saltmarsh with `@campsite` fill - `#def6c0`
A. z13
![z13-verdronken-saltmarsh-campsite-fill](https://user-images.githubusercontent.com/42757252/59107517-c91ee400-8973-11e9-9ab5-176065da9d18.png)

B. z15
![z15-slufter-saltmarsh-campsite-fill](https://user-images.githubusercontent.com/42757252/59107568-e81d7600-8973-11e9-95e7-a7376b49ef9c.png)

**Comment by jeisenbe** [comment]
As @imagico [suggested](https://github.com/gravitystorm/openstreetmap-carto/issues/2025#issuecomment-500160666) in #2025 here are test renderings of saltmarsh with `@grass` fill - `#cdebb0` plus a dot pattern suggestive of saltwater. 

### 0) Current rendering for comparison:

A. Salt marsh (left) and marsh (right)
https://www.openstreetmap.org/#map=13/51.3590/4.1393
![z13-schelde-saltmarsh-vs-marsh-before](https://user-images.githubusercontent.com/42757252/59547057-71840800-8f73-11e9-8b97-30587b95653a.png)

B. Small salt marshes: one over sea water, one over land in database
https://www.openstreetmap.org/#map=15/51.4552/3.6555
![z15-slufter-saltmarshes-zeeland-before](https://user-images.githubusercontent.com/42757252/59107456-a12f8080-8973-11e9-8aaf-2af2c27060cc.png)

C. Saltmarsh (left) next to marsh (center), mouth of the Eel river, California
![z14-eel-river-saltmarsh-marsh-before](https://user-images.githubusercontent.com/42757252/59547054-629d5580-8f73-11e9-8a03-401ca67492f5.png)


### 1) Saltmarsh with dense dot pattern and `@grass` fill - `#cdebb0`
- This dot pattern is copied from the saltwater pattern in the alt-colors style (water_salt.svg), changed to white
- However, it may be too dense, covering up too much of the grass color

A. 
![z13-schelde-saltmarsh-vs-marsh-dots1](https://user-images.githubusercontent.com/42757252/59547076-b90a9400-8f73-11e9-9039-178420ac4216.png)

B. 
![z15-slufter-saltmarsh-dots1](https://user-images.githubusercontent.com/42757252/59547077-bb6cee00-8f73-11e9-88d7-9e7b23d1f1fb.png)

C.
![z14-eel-river-marsh-saltmarsh-dot1](https://user-images.githubusercontent.com/42757252/59547079-c162cf00-8f73-11e9-951f-109aab53ebf0.png) 


### 2) Saltmarsh with looser dot pattern and `@grass` fill - `#cdebb0`
- This pattern uses slightly smaller dots, 5 pixels apart on average
-From [http://www.imagico.de/map/jsdotpattern.php#x,128,jdp68152;g,5,32,32;rx,25,2,32,32;rx,25,2,32,32;rx,25,2,32,32;rd,0,0,0,dot,0.125,10,9,0,jdp48264,ffffff,cdebb0;]( http://www.imagico.de/map/jsdotpattern.php)

A. 
![z13-schelde-saltmarsh-dots2](https://user-images.githubusercontent.com/42757252/59547086-d93a5300-8f73-11e9-9ed6-de7cec9f1c4e.png)

B. 
![z15-slufter-saltmarsh-dots2](https://user-images.githubusercontent.com/42757252/59547090-e8210580-8f73-11e9-99d9-066e89684bf2.png)

C.
![z14-eel-river-marsh-saltmarsh-dot2](https://user-images.githubusercontent.com/42757252/59547096-fb33d580-8f73-11e9-89d9-5a732225d8d4.png)

I believe this second pattern works well.

**Comment by jragusa** [comment]
Why not replacing blue lines by white lines or even a mix of both lines ?

**Comment by jeisenbe** [comment]
The same wetland pattern (with the blue horizontal lines and green
vegetation symbols) is used over land and over water, so that pattern needs
to match the other wetland pattern styles.

We could use white dashes on the green fill pattern instead of dots, but I
think that dots suggest salt more clearly than short lines.
