### ISSUE TITLE
Avoid rendering cross on La Luz del Mundo temples

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#3800]
Like Jehovah’s Witnesses (#1079), [La Luz del Mundo](https://en.wikipedia.org/wiki/La_Luz_del_Mundo) (LLDM) is a Christian denomination that avoids using the cross as a symbol. An [Aaron’s rod](https://en.wikipedia.org/wiki/Aaron's_rod) could be appropriate, since it tops some of their temples, but it seems like a generic place-of-worship icon would be sufficient. LLDM temples are tagged `denomination=la_luz_del_mundo`.

### Expected behavior

🛐

### Actual behavior

✝️

### Links and screenshots illustrating the problem

![lldm](https://user-images.githubusercontent.com/1231218/59163095-c675d900-8ab0-11e9-9563-b62d932e3ca3.png)

**Comment by imagico** [comment]
Two uses of this tag:

https://taginfo.openstreetmap.org/tags/denomination=la_luz_del_mundo

and no documentation.  I think in particular in case of religious denominations it is essential that there is a documentation of the tag allowing a non-member of the religion to determine if a certain place of worship belongs to it or not.  Otherwise i would essentially be a non-verifiable tag.  Unfortunately this is not the case for any denomination value at the moment.

**Comment by 1ec5** [comment]
> Two uses of this tag:

I went through OSM cleaning up tags like `denomination=La Luz del Mundo` just before opening this issue, so now there are [21 uses](https://overpass-turbo.eu/s/JNR), which will show up in taginfo before long.

> I think in particular in case of religious denominations it is essential that there is a documentation of the tag allowing a non-member of the religion to determine if a certain place of worship belongs to it or not. Otherwise i would essentially be a non-verifiable tag.

I started [a wiki page](https://wiki.openstreetmap.org/wiki/Tag:denomination%3Dla_luz_del_mundo) with tips for distinguishing an LLDM temple from another church that happens to be named similarly. For places of worship, verifying the denomination sometimes entails entering the worship space or perusing a church bulletin. But for LLDM temples, street-level imagery is often enough to tag verifiably.

**Comment by imagico** [comment]
Thanks.

One of the reasons i stressed documentation of denomination tags is that i think maybe the best approach is to render religion=christian without denomination with a generic place of worship symbol and only render a list of established denomination tags that represent branches of christianity that use the cross as a symbol with the cross.  This would support mappers in specifying the denomination - which however is only a good idea if the denominations rendered are properly documented so there is proper guidance how to correctly tag this.

**Comment by 1ec5** [comment]
Documenting denominations in more detail would be a good idea, but I’m not sure where to start. Most denominations aren’t quite as identifiable through physical characteristics. What I usually look for is some indication in the name or an explicit reference to a denomination or church hierarchy in the church’s signage or signposted website. But that’s probably my American bias: in the U.S., the denomination is very often indicated in the church name, or otherwise the church is nondenominational or deemphasizes their affiliation. Also, in the U.S., it’s reasonable to make assumptions like “Catholic” meaning `roman_catholic`, which is true the vast majority of the time.

Conservatively applying the cross icon only when the `denomination` tag calls for it could make the cross much less common on the map. It would avoid misrepresenting poorly tagged LLDM temples and JW kingdom halls, but I’m not sure whether that’s the right balance, considering that the two non-cross-using denominations we know of have relatively consistent naming conventions.

**Comment by Adamant36** [comment]
> Documenting denominations in more detail would be a good idea, but I’m not sure where to start.

I wonder if this is something we could start using the name index to improve the mapping and documentation of. Religious organizations are like brands, and we already have entries for social centers. So I don't see why religions wouldn't qualify also.

**Comment by SK53** [comment]
@Adamant36 I think this may require more care than is possible with the current brand approach. Many distinct denominations have similar names. For instance I've seen confusion between Christ-catholics and catholic churches in CH; the various aspects of the Free Church of Scotland are informative; as are the differences between the various branches of Quakerism in the US. The Welsh Calvinist Methodist Church is not particularly Calvinist, nor Methodist, but a Presbyterian church, as indeed its Welsh name, Eglwys Bresbyteraidd Cymru, and its modern English name indicate.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/Tag%3Adenomination%3Dla_luz_del_mundo

> LLDM does not use the Christian cross; therefore, renderers should avoid symbolizing LLDM temples with the cross

It would be useful to link to something confirming that cross is not merely usually unused but also unwanted/disliked as a symbol.

Wikipedia has

>  It does not use crosses or religious images in its worship services.

but nothing that indicates that using cross symbol to mark their temples would be actually offensive

**Comment by jeisenbe** [comment]
I find it a little confusing to avoid using the standard cross symbol for any place_of_worship with `religion=christian`, because of a certain `denomination=` tag.

**Comment by jeisenbe** [comment]
`denomination=mormon` (LDS) also don't use the cross, but claim to be `religion=christian`. We could render all three denominations with the generic `place_of_worship` symbol, or reconsider rendering `denomination=jehovahs_witness` in a different way which implies that it is a not `religion=christian`.
