### ISSUE TITLE
Request: display toy libraries

### ISSUE THREAD

**Issue by ChameleonScales** [gravitystorm/openstreetmap-carto#3803]
Toy libraries have been recently implemented in ID as amenity=toy_library and so far 129 of them have been added on openstreetmap worldwide (mostly in France). I plan to help spread the word so more get added but it would be great if they showed up with their icon and name on openstreetmap.org for starters.
Toy stores and book libraries are already displayed so I think it makes sense to include toy libraries as well.

**Comment by jeisenbe** [comment]
Usually we like to see an amenity tag with over 2000 uses and increasing adoption by different mappers in a wide variety of places prior to adding rendering for a new tag.

It's also important that the tag be fully documented on the wiki.

I'd recommend finishing the proposal page at https://wiki.openstreetmap.org/wiki/Proposed_features/toy_library and sending a message to the tagging list with an RFC - see the page https://wiki.openstreetmap.org/wiki/Proposal_process - then in 2 weeks you can request a vote to approve the tag, as well as the other tags that you've suggested on that page. 

After that, the tag should be documented at https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoy_library - it's also possible to make this page without going through a proposal process, but I think it might be helpful to discuss the additional tags and get more people interested in mapping these features. 

Then, after the tag becomes more widely used, we can consider rendering it here.

**Comment by matkoniecz** [comment]
> Toy libraries have been recently implemented in ID as amenity=toy_library

I recommend checking is it implemented/already requested for [JOSM](http://josm.openstreetmap.de/), [Vespucci](https://github.com/simonpoole/beautified-JOSM-preset) and other editors.

**Comment by matkoniecz** [comment]
Closing for now, can be reopened later once usage increases (note that not all popular tags are rendered)
