### ISSUE TITLE
Highway Begin and End point automatic rendering

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3806]
Long term wishlist item:

All highways have [metal Begin and End signs](https://www.google.com/search?q=US+1+Mile+Marker+0&tbm=isch). Even if run of the mill milestones are not rendered, some though should be given to how to automatically render these important endpoints based on the underlying [direction](https://wiki.openstreetmap.org/wiki/Forward_%26_backward,_left_%26_right#Identifying_the_direction_of_a_.27way.27) in the database. Else who is to know where the "beginning of highway 32" or the "end of highway 47" are?

[Manually adding](https://www.openstreetmap.org/node/4898623221) them is not systematic.

Also consider e.g., "P" [shaped](https://en.wikipedia.org/wiki/Talk:Polygonal_chain#The_letter_%22P%22) roads:

Allow us to take this road 46 as example. Things start out [innocently enough](https://www.openstreetmap.org/?mlat=24.19233&mlon=120.83941#map=17/24.19233/120.83941). The highway department has a Begin sign there and the road heads east.

But let's look at the [junction in the middle of the P](https://www.openstreetmap.org/?mlat=24.19284&mlon=120.85671#map=19/24.19284/120.85671) where the road loops back upon itself and ends.

Any automatic placement of a [中 46 END] marker on the map must still make it clear to the user that the road first goes east, then loops around, finally heading back south and hitting itself in the middle (where the highway department has indeed put an "End" sign.)

Therefore simply attaching an End point marker at that tri-point would be ambiguous.

**Comment by jeisenbe** [comment]
I'm not sure that this would be helpful. As you mentioned, highways often end at a junction with another highway, and sometimes this can be ambiguous. And the `ref=*` of highways is already rendered in a repeated fashion along the line of the highway, so the approximate start and end points are usually apparent, especially when zooming in.

Are there any relevant examples of other map styles which render these end points?

**Comment by jidanni** [comment]
OK, fine. As long as it agrees with https://wiki.openstreetmap.org/wiki/Good_practice#Map_what.27s_on_the_ground .
