### ISSUE TITLE
OSM text quality much worse than Google's

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3813]
OSM text quality dangerously low.

https://www.openstreetmap.org/#map=19/24.15109/120.69722

![pp](https://user-images.githubusercontent.com/1230959/59970554-c2ab8180-959b-11e9-8daf-696c272dc736.jpg)

**Comment by sommerluk** [comment]
Hm, I don’t know how you scale the images, but in general this style is deployed as raster pictures, which obviously do not look good when upscaled by a non-integer factor like 2,22 as you are using.

The original screenshot from OSM without scaling:
![Openstreetmap](https://user-images.githubusercontent.com/6830724/59972741-1d38e380-9584-11e9-99b3-8ccabac2ce4f.png)

**Comment by polarbearing** [comment]
First, I see no 'danger' here. It would help not to use yellow press jargon in reporting issues. 

The google example is written in a grey tone, while OSM uses black. The anti-aliasing algorithms might be a bit different, or just the fonts having different line width; but as @sommerluk said, it has to be judged at the 100% scaling, which looks clear to me.

**Comment by HolgerJeromin** [comment]
Another possibility for differences. Google uses vector tiles which can render better with anti aliasing or even retina displays.

**Comment by matkoniecz** [comment]
>  OSM text quality

Is it also problematic when viewing images at 100%?

**Comment by Adamant36** [comment]
I have a 1920x1080 and things look a tad fuzzy and off for me. Including fences which have always looked sorta jagged and pixelated. Even while viewing images at 100%. I don't have the same issues on my 4K TV though. There lines, text, and also colors look much more vivid and less pixelated. It's something I've been wondering about for a while now. More then likely it's a monitor issue or something to do with the specific type of monitor I'm using. I figured 1920x1080 would be a good enough resolution to not cause fuzziness. Apparently it's not. So, any actual issues with text quality if there are any could just be the monitor it's being viewed on.

**Comment by mmelissen** [comment]
This is likely caused by the fact that we do not provide 2x (retina) tiles on openstreetmap.org. That would also explain why the problem only occurs on some screens.

You can find a deployment of this style with 2x tiles here: https://osm.rrze.fau.de/testhd.html Is there still a quality difference between these tiles and Google?

**Comment by matthijsmelissen** [comment]
This is likely caused by the fact that we do not provide 2x (retina) tiles on openstreetmap.org. That would also explain why the problem only occurs on some screens.

You can find a deployment of this style with 2x tiles here: https://osm.rrze.fau.de/testhd.html Is there still a quality difference between these tiles and Google?

**Comment by jidanni** [comment]
Problem 1 is that older users will have to hit CTRL++... to read street names often anyway.

Problem 2 is even on https://osm.rrze.fau.de/testhd.html , each time one zooms the mouse wheel, the names momentarily become readable, but then are re-rendered smaller.

If I zoom https://osm.rrze.fau.de/testhd.html finally the names become comfortably readable, but there is no URL to compare the same place on OSM.org, nor can I go to Taiwan to try how placenames look there. P.S., I'm using HDMI-1 connected primary 1920x1080+0+0 and GitHub at 125% zoom while I type this.

**Comment by jidanni** [comment]
And I cannot hit CTRL+++ on  https://osm.rrze.fau.de/testhd.html because it just hits the zoom button on the map. 
OK comparing https://www.openstreetmap.org/#map=19/49.57475/11.02909
we indeed see https://osm.rrze.fau.de/testhd.html is better!:
![27581-2](https://user-images.githubusercontent.com/1230959/60892144-371b3b80-a291-11e9-8378-71efa581b4cd.jpg)

**Comment by matkoniecz** [comment]
There is no example of scaling broken for untransformed images. And this style with 2x tiles appears to work fine.

So problem is not in style itself.
