### ISSUE TITLE
Yes there is room for labels on opposite sides of close pairs

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3814]
Let's say on the map item 1 is visible on the right, and nearby item 2 is visible on the left.

Why can't item 1's name be placed to the right of item 1,
and item 2's name be placed to the left of item 2?

Wouldn't that be better than just randomly, or non-randomly, only
showing one name?

Same not only for E/W item pairs, but also N/S, and NE/SW etc. item pairs.

In each case there is plenty of room for both names, all you have to do
would be intelligently place their names "close to their points, but
away from other points". Simply use a "magnetism algorithm," where we
are more attracted to our point, but at the same time repelled from
the other point(s). Voila!

Case in point, the current state of the pair of bridges at
https://www.openstreetmap.org/way/696526916 , which at one time had a
different issue, #3805.

**Comment by systemed** [comment]
> Simply use a "magnetism algorithm,"

New text placement algorithms are not something openstreetmap-carto can implement and should be suggested over on https://github.com/mapnik/mapnik . If it's a matter of "simply" I'm sure they'll be delighted to receive your patch.

**Comment by jidanni** [comment]
OK done.
