### ISSUE TITLE
Truncated road name or ref at metatile boundaries

### ISSUE THREAD

**Issue by kymckay** [gravitystorm/openstreetmap-carto#3820]
### Expected behavior

Not exhibiting this partial ref rendering or name duplication on Rosemount Viaduct (screenshot below is the easiest way to see what I mean).

[Here's a link to the coordinates where this occurs](https://www.openstreetmap.org/#map=19/57.14840/-2.10918).

### Links and screenshots illustrating the problem

![image](https://user-images.githubusercontent.com/5459452/60896550-73817400-a25e-11e9-8523-2316415345fc.png)

**Comment by LucFreitas** [comment]
Same here (z12, z13 and z14):
https://www.openstreetmap.org/?mlat=-19.9733&mlon=-43.1373#map=14/-19.9733/-43.1373

**Comment by Sjord** [comment]
The problem seems to show itself on the edge of two tiles. This issue seems similar to [mapnik issue #889](https://github.com/mapnik/mapnik/issues/889): Name label is cut between two tiles. I don't think it is a problem with the stylesheets of openstreetmap-carto. It looks like a problem with the renderer.

**Comment by jeisenbe** [comment]
Suggestions in the linked Mapnik issue:

"You can change tile buffer size and set shield symbolizer's clip="false".
And you also can set avoid-edges="true"."

@pnorman any thoughts about these ideas? 

Tile buffer size is set by the rendering servers, not at here, correct?

**Comment by pnorman** [comment]
> Tile buffer size is set by the rendering servers, not at here, correct?

It might be - our definition is the same as here, and I think cut-off labels are infrequent enough that we don't want to increase it for what will be a marginal decrease.

**Comment by pnorman** [comment]
We make an effort to avoid these problems by various means (buffer, etc) but they're impossible to get rid of completely. I'm going to close this, as we'll always have some cut-off labels.
