### ISSUE TITLE
bridges with tag railway=abandoned aren't rendered

### ISSUE THREAD

**Issue by olefs** [gravitystorm/openstreetmap-carto#3821]
### Expected behavior

Bridges tagged with railway=abandoned should be rendered, even if the route of the abandoned railway isn't rendered. [You can't see the bridge here ;) ](https://www.openstreetmap.org/#map=18/47.28535/11.40115)

### Actual behavior

The bridge just dosn't appear in osm-carto (picture below). In contrast, e.g. wanderreitkarte is rendering the bridge.

### Links and screenshots illustrating the problem

OSM - the bridge isn't rendered
![osm](https://user-images.githubusercontent.com/37802906/61189414-82688c00-a68d-11e9-91fb-de3e93dab68f.png)

wanderreitkarte reders the bridge (marked with red arrow)
![wanderreitkarte](https://user-images.githubusercontent.com/37802906/61189413-82688c00-a68d-11e9-9602-582d78796833.png)

Line: Hungerburgbahn (25318264)
![tags](https://user-images.githubusercontent.com/37802906/61189415-82688c00-a68d-11e9-8539-f068d8a67df7.png)

**Comment by polarbearing** [comment]
See #542, abandoned railways are not rendered, consequently no bridges as well. If another style renders them, they have a different purpose. 

Anyway, if the bridge construction is still there, it can be mapped as man_made=bridge, and that will be rendered here.

**Comment by matkoniecz** [comment]
Closing as this feature is not mapped.

> Anyway, if the bridge construction is still there, it can be mapped as man_made=bridge, and that will be rendered here.

Note that `railway=abandoned bridge=yes` may mean that either

- railway and bridge is gone without trace (IMHO in that case mapping it in OSM is generally undesirable, except rare cases where object is still visible on outdated aerial images)
- railway is gone, bridge is preserved

so rendering it is not desirable, see #542 for more
