### ISSUE TITLE
amenity=toilets Rendered in faded style when access=public

### ISSUE THREAD

**Issue by gecho111** [gravitystorm/openstreetmap-carto#3823]
Expect that it would be rendered in the standard style.

Appears faded as it would if access were set to no.

example:  https://www.openstreetmap.org/#map=19/50.43463/-104.61656
 vs    https://www.openstreetmap.org/#map=19/50.43379/-104.58717

**Comment by matkoniecz** [comment]
Using `access=yes` (if explicit tagging is needed) is preferable. `access=public` is an undesirable duplicate that should not be supported without really, really good reason.

https://taginfo.openstreetmap.org/tags/access=public#combinations has some minor use - but note https://taginfo.openstreetmap.org/keys/access#values

Is `access=public` maybe encouraged to be replaced by `access=yes` in JOSM or other decent validator? Is there maybe request to introduce such validator rule rejected for reasons that are still applicable?

**Comment by gecho111** [comment]
Validator rules might be helpful to reduce non-preferred tagging / deprecated usage.  If I had created that amenity I would have just omitted access.  I figured I should bring the issue up rather than just delete the tag.

**Comment by HolgerJeromin** [comment]
"access=public" was only ever documented for toilets. Not sure if this is still the case and is useful to support.

**Comment by matkoniecz** [comment]
I found https://github.com/openstreetmap/iD/issues/2280 and https://josm.openstreetmap.de/ticket/10007

**Comment by jeisenbe** [comment]
Reviewing the links above, both JOSM and iD added this as an option for a couple features at one point, but this has now been fixed and usage of access=public is no longer increasing, while access=yes is used over 20 times more often and is increasing steadily.  

While the meaning of access=public is fairly clear, one of the goals of this style is to prevent tag fragmentation, when new tags are invented which mean the same thing as established tags. So I don't think we need to support access=public as a synonym for access=yes in this style.

**Comment by matkoniecz** [comment]
I will close it as it is not a problem in map style but in map data.

Independently, I will try to either run a bot edit replacing `access=public` by `access=yes` or at least add such action to validator(s).
