### ISSUE TITLE
leisure=fitness_station not rendered if line instead of node

### ISSUE THREAD

**Issue by MaestroGlanz** [gravitystorm/openstreetmap-carto#3824]
### Expected behavior
If there is a fitness station like horizontal bars, which can be like 5m wide, or a stairs, which is also used as a fitness station, there should be a fitness station symbol halfway the line. This should also be on relations (i.e. group of poles for jumping) in the center of the area of the bounding box of the relation.

### Actual behavior
The symbol appears only on fitness stations represented by a node.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/note/1812034#map=19/48.88582/9.20060
on the left, where there is the six way crossing with the Alt-Württemberg-Allee, there is an obstacle course. This is not rendered. 
In the middle, next to the single waste basket, there are horizontal bars.

https://www.openstreetmap.org/#map=19/49.60921/11.03231
In the middle, there is a station, which is not rendered.

https://www.openstreetmap.org/#map=18/49.60752/11.03794
In the middle, there are three stations, which are not rendered.

**Comment by matkoniecz** [comment]
Note that https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfitness_station describes mapping on unclosed ways as a bad idea, so it would be preferable to discuss first is this tagging is OK (personally I think that `amenity=bicycle_parking` or `leisure=fitness_station` and similar should not be mapped as a unclosed line and I am willing to discuss on OSM Wiki or tagging mailing list)

> This should also be on relations (i.e. group of poles for jumping) in the center of the area of the bounding box of the relation

Multipolygons should be already supported (assuming that areas are supported), other relations (like site relation) are bad idea for mapping this feature and implementation would anyway need to happen in other project (`osm2pgsql`) - see more detail in https://github.com/gravitystorm/openstreetmap-carto/issues/1678

**Comment by jeisenbe** [comment]
I agree that the first step would be asking on the wiki talk page https://wiki.openstreetmap.org/wiki/Talk:Tag:leisure%3Dfitness_station or the Tagging mailing list if it's appropriate to map these features as linear ways. Currently this is not suggested as an option. 

Right now, there are [over 7000 unclosed ways](https://overpass-turbo.eu/s/LMB), but only [107 closed ways](https://overpass-turbo.eu/s/LMC), which suggests this way of mapping is not widely used. See: 
```
 [out:csv(::count)][timeout:60];
 (
   way["leisure"="fitness_station"](if:!is_closed());
 );
 out count;
```

**Comment by jeisenbe** [comment]
I'm planning to close this issue, because mapping these features as lines instead of a node or area does not seem to be widely used or documented.
