### ISSUE TITLE
Use native highway shields

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3835]
Here we see freely licensed symbols are already available
https://en.wikipedia.org/wiki/LaPorte_County,_Indiana#Major_highways

This would eliminate the current "LETTER[S] NUMBER[S]" numbering, which
is a purely OSM invention*,
https://www.openstreetmap.org/#map=12/41.1010/-84.9940
thus finally making the map reflect what is on the ground.
(Indeed here we even see "SR" and "IN" being used interchangeably:
https://www.openstreetmap.org/#map=15/41.5595/-86.8993 )

*"LETTERS NUMBERS" is not what is on the pole.

**Comment by jidanni** [comment]
#508 Duplicate.

**Comment by 1ec5** [comment]
> (Indeed here we even see "SR" and "IN" being used interchangeably:

I’m a little late to this, but for what it’s worth, [here’s some backstory](https://forum.openstreetmap.org/viewtopic.php?pid=751214#p751214) as to why both “SR” and “IN” have been used in Indiana. In my opinion, “SR” has a better claim to the on-the-ground rule, but the graphical shields in #508 would be ideal, if for nothing else than the fact that people like me can stop nitpicking about which prefix to use in `ref`s. 😅
