### ISSUE TITLE
Width of tree_row is less than barrier=hedge at z16

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3845]
### Expected behavior
The width of a tree_row should be wider than a barrier=hedge at all zoom levels, and it should be possible to distinguish the two features easily

### Actual behavior
At z16, `tree_row` is 2.5 pixels wide, while `barrier=hedge` is 3 pixels wide
At z17 and lower zoom levels, `tree_row` is much wider (5 pixels -> 10px -> 15px ext) while barrier=hedge remains at 3 pixels

### Links and screenshots illustrating the problem
z16
![z16-hedge-vs-treerow-before](https://user-images.githubusercontent.com/42757252/63497214-4c28f280-c4fe-11e9-8f42-53e6ce92b235.png)

z17
![z17-hedge-vs-treerow-before](https://user-images.githubusercontent.com/42757252/63497227-4fbc7980-c4fe-11e9-9260-7545a7d3e4ec.png)

z18
![z18-hedge-vs-treerow-before](https://user-images.githubusercontent.com/42757252/63497264-619e1c80-c4fe-11e9-9c49-58f1fa32e65f.png)

**Comment by imagico** [comment]
Note since #2789 tree and tree row rendering has been left in a fairly inconsistent state.

**Comment by imagico** [comment]
See also #1753 for considerations on rendering tree rows and hedges.
