### ISSUE TITLE
Too early and inconsistent initial zoom level for natural area patterns

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3862]
### Expected behavior
- Similar patterns, like scree/shingle and bare_rock, should appear at the same zoom level. 
- This should be consistent with other natural area patterns, like woodland etc.
- The generic wetland pattern can appear sooner (since there is no fill color for this feature), but specific wetland types should appear at the same time as other natural area patterns.

### Actual behavior
- Most patterns appear at z13, but a few appear as early as z5
- `natural=bare_rock` <s>and `natural=sand`</s>* patterns start at z5, but the similar features `natural=scree` and `natural=shingle` are not shown until z13
- Very few natural landcover areas are large enough for patterns to be shown this early; most that are visible are poorly-mapped dessert areas, where a few mappers have created huge polygons which don't accurately represent the actual areas of rock or sand. 

### Recommended solution
- Show all natural area patterns at z13 and higher, except for generic wetland pattern (and military overlay)
- Landuse patterns might be better at z14, but this is a minor problem

*(The `natural=sand` pattern was removed by #3855)

**Comment by jeisenbe** [comment]
The first step to fixing this was #3855, which took a surprisingly large amount of time and discussion, but is now merged.

Next: have bare rock appear at the same zoom level as shingle and scree

**Comment by jeisenbe** [comment]
Also see #4071, specifically about the issues with showing wetland pattern at low zoom.

**Comment by kocio-pl** [comment]
> Similar patterns, like scree/shingle and bare_rock, should appear at the same zoom level.

This sounds OK for me.

> This should be consistent with other natural area patterns, like woodland etc.

While big green areas are quite clear as vegetation, pure brownish colors are not even remotely that recognizable and they all have much more delicate patterns than woodland for example (or even bushes), so this does not work for me (but that should be discussed in #4072 of course).
