### ISSUE TITLE
Nodes with leisure=sports_centre have no icon or name rendered

### ISSUE THREAD

**Issue by camelCaseSucks** [gravitystorm/openstreetmap-carto#3868]
Any node tagged as leisure=sports_centre is currently rendered as just an address. There is no icon or name.

examples:
https://www.openstreetmap.org/node/2174921622
https://www.openstreetmap.org/node/4029273583

**Comment by jeisenbe** [comment]
This style currently renders a name label and fill color for areas tagged with `leisure=sports_centre`. However, I see that currently there are over 42,000 nodes with this tag, over 23% of tagged features. 

Two possibilities: 
1) Render a generic marker (round dot) and text label for nodes, and continue to render just the name label for areas. 

2) Add a specific icon for both nodes and areas. 

It may be difficult to find a generic icon which will work for all kinds of sports centres. Maps.me uses a "running person" icon, but this could be confused with running-specific venues. OsmAnd uses a person with outstretched arms. 

But both of these options could make it more difficult to adjust the sports_centre color in the future.

In the past, `sports_centre` and `stadium` were rendered in the light yellow-green societal_amenities color, then this was changed to the current very light green `@leisure` which is also used for some other recreation features, created by lightening the `park` color.

However as @imagico has mentioned, it's not ideal to use green for non-vegetation related features. We also have many features in different shades of green currently, and it would be helpful to reduce these by changing `@stadium` to a different color, perhaps yellow or light orange again. Also, `@leisure` is too light compared to other area features, which leads to problems with contrast.

Adding an icon or a dot would complicate these color changes, by limiting the options which would work well.

**Comment by Prince-Kassad** [comment]
Even having just a name with no icon would be an improvement over the status quo.

The real problem is a tagging issue - leisure=sports_centre is a catch-all for various sport-related amenities that have very little in common, from swimming halls over bowling centers up to horse stables. It will be very difficult to come up with an icon unless we add sport= to the database so we can have different rendering based on sport tagged.

**Comment by jeisenbe** [comment]
`sport=` is already available for adjusting the rendering of features such as `leisure=sports_centre` and `leisure=pitch` - see closed PR  #3651 for example, but also for issues with rendering different icons with each sport; there are currently [113 documented values](https://wiki.openstreetmap.org/wiki/Key:sport).

**Comment by jeisenbe** [comment]
It appears that this feature used to have a text label when mapped as a node, but this was unintentionally removed. See #3876 and PR #3878
