### ISSUE TITLE
Render barrier=wicket_gate

### ISSUE THREAD

**Issue by jaffroy62** [gravitystorm/openstreetmap-carto#3875]
### Expected behavior

I suggest to render barrier=wicket_gate which is mostly used on nodes of paths or footways to illustrate this kind of barrier. The expexted rendering should be discreet. It should be less prominent than barrier=gate

<img width="302" alt="image" src="https://user-images.githubusercontent.com/42764343/64472646-13298880-d162-11e9-93b0-365668ebce39.png">

### Actual behavior

not rendered at the moment

### Links and screenshots illustrating the problem

wiki: https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwicket_gate

**Comment by jeisenbe** [comment]
Currently used [334 times](https://taginfo.openstreetmap.org/tags/?key=barrier&value=wicket_gate), compared to over 1,800,000 `barrier=gate` - so it's the 56th most common value of `barrier`.

It appears to be used for 2 different things:

"A wicket gate is a pedestrian door or gate, particularly one built into a larger door or into a wall or fence near a larger gate. It may also be a stand-alone gate that provides convenient secondary access, for example to the rear of a walled park or garden":

![](https://wiki.openstreetmap.org/wiki/File:Blue_Anchor_level_crossing_-_wicket_gate.jpg)

Consider the rarity of this tag, we might be able to render it the same as a `barrier=gate` but a unique icon is probably not appropriate yet. There are several more common values of `barrier=*` which are not yet supported by this style.

**Comment by pnorman** [comment]
With 334 uses I'd rather not render it.

**Comment by jeisenbe** [comment]
Two more common, similar tags for entrances for foot usage only (probably? They are undocumented):

https://taginfo.openstreetmap.org/tags/barrier=door - used 4 185 times
https://taginfo.openstreetmap.org/tags/barrier=footgate - used 530 times

But they are both quite rare compared to `barrier=gate` which is also commonly used for gates on footways.

**Comment by jeisenbe** [comment]
Closing for now due to low usage and unclear distinction from more common tags like `barrier=gate`, `barrier=door`,  and `barrier=footgate`. This issue can be reopened if the situation changes.
