### ISSUE TITLE
Schools and kindergartens mapped as a node not shown anymore.

### ISSUE THREAD

**Issue by A67-A67** [gravitystorm/openstreetmap-carto#3876]
Since a few days schools and kindergartens that have been mapped on a node are not shown anymore. This seems to be a bug [issue 3868](https://github.com/gravitystorm/openstreetmap-carto/issues/3868). 

Schools are often mapped as an area that contains the entire school area, but in a case of multiple schools sharing a building or a school and a library in the same building building mapping them on a node makes more sense.

### Expected behavior
The name of the school or kindergarten is shown in a dark-yellow italic font, like until a few days ago.

### Actual behavior
The housenumber is shown instead of the name.

### Links and screenshots illustrating the problem

- [A kindergarten shown as a house number](https://www.openstreetmap.org/node/4575567969)
- [A school shown as a house number](https://www.openstreetmap.org/node/5693493497)

For both the name used to be rendered by OSM-carto. This problem is also being discussed on the [Dutch forum](https://forum.openstreetmap.org/viewtopic.php?id=67300), in a discussion that started with [issue 3860](https://github.com/gravitystorm/openstreetmap-carto/issues/3860).

**Comment by imagico** [comment]
I have not checked but from a quick look it seems like #3764 removed rendering of this and other POI types by requiring a non-NULL way_pixels value.

**Comment by jeisenbe** [comment]
Thank you, it's correct that #3764 created this, since `way_pixels = null` is not considered `<= 768,000`. I've got a PR to fix it.

**Comment by jeisenbe** [comment]
I notice that `place=island` and `place=islet` on nodes have not been rendered since PR #1444 in commit 6cd5b3c9d3388270f1d2bf58c98c5aef7b3e2e01 "Do not render island/islet name when way_pixels is big" in on Sat Mar 21, 2015 - but this appears to have been unintentional? @sommerluk? 
I will also restore the rendering for these two features when mapped as nodes at >z16/z17, if there's no objection.

**Comment by sommerluk** [comment]
I'm sorry for inconvenience, indeed this was unintentional.
