### ISSUE TITLE
Add rendering for playground=sandpit

### ISSUE THREAD

**Issue by carstenhag** [gravitystorm/openstreetmap-carto#3884]
### Expected behavior

Sandpit area renders a bright brownish area

### Actual behavior

It doesn't show up at all.

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/edit#map=19/48.27879/10.97427

https://www.openstreetmap.org/way/721297176

**Comment by matkoniecz** [comment]
Closing due to no reply to

> Do you have a different idea for rendering these features?

I am not fundamentally opposed to idea of rendering this structure but I am very, very, very dubious about adding yet another new icon and even more dubious that there is some reasonable area rendering.

And missing sandpits are not a major issue.
