### ISSUE TITLE
Add rendering for playground=structure

### ISSUE THREAD

**Issue by carstenhag** [gravitystorm/openstreetmap-carto#3885]
### Expected behavior

Structures get rendered. They should not be transparent.

### Actual behavior

"Structure" playgrounds don't get rendered :(

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/way/721297178  
https://www.openstreetmap.org/way/721297179

**Comment by carstenhag** [comment]
Well, to me it would make sense to at least show "something". I'm not sure if 20 icons on one playground are the best way.

Nothing being shown just seems wrong.

**Comment by jeisenbe** [comment]
Normally a playground is tagged with `leisure=playground`. The two examples above, https://www.openstreetmap.org/way/721297178 and https://www.openstreetmap.org/way/721297179, only have `playground=structure`, but that tag is not meant to be used without a surrounding area tagged with `leisure=playground` - or you can add `leisure=playground` to the same object as `playground=structure`, if that's the whole extent of the playground. 

See https://wiki.openstreetmap.org/wiki/Tag:playground=structure - note: 
"useful combination: leisure=playground for the area around the devices"

**Comment by carstenhag** [comment]
Well... https://www.openstreetmap.org/way/315040636 is the surrounding area with `leisure=playground`. I don't know what you are wanting to tell me :)

**Comment by jeisenbe** [comment]
Sorry, I misinterpreted your comment about "it would make sense to at least show something". 

Do you have a thought about a way that these features could be shown, besides using different icons for each type?

**Comment by polarbearing** [comment]
While leisure=playground is indeed a useful combination for the surroundings of a device in most cases, in reality you have sometimes stray devices e.g. in a park, without defining a playground. A swing here, a springy there.

**Comment by matkoniecz** [comment]
> in reality you have sometimes stray devices e.g. in a park, without defining a playground. A swing here, a springy there.

In my tagging, and also in my experience such places can be treated and mapped as a very small playgrounds. Is it something that is considered as poor tagging/incorrect?

**Comment by polarbearing** [comment]
I would not consider that a suitable solution. If I ask a query tool, how many playgrounds are in this area, the number would be significantly inflated by such 'micro-playgrounds'. Further, they have not a verifiable boundary. This probably needs further discussion and documentation.

**Comment by jeisenbe** [comment]
>  they have not a verifiable boundary.

In that case mapping as a node is a good solution.

**Comment by jeisenbe** [comment]
I think we should probably close this issue, since #3161 attempted to render playground equipment but it was not possible to find 14 pixel icons that could work for all the features or a generic playground icon that did not look like a see-saw. However, if someone has new ideas about how to render these features in an appropriate way, we could reconsider.

**Comment by polarbearing** [comment]
Happy enough to close, it is a case for a specialized map.
