### ISSUE TITLE
Render police area and name

### ISSUE THREAD

**Issue by geozeisig** [gravitystorm/openstreetmap-carto#3892]
### Expected behavior
Render [police ](https://wiki.openstreetmap.org/wiki/Key:police) area and name **without** an icon. There are e.g. police=barracks, police=car_pound, police=naval_base ... The color should be the same as `amenity=police`.
### Actual behavior
It is currently not displayed. [Example ](https://www.openstreetmap.org/way/5095457/history)
### What could be a problem
There is a approved [proposal ](https://wiki.openstreetmap.org/wiki/Proposed_features/tag:Police) from this year that had huge approval. But there are not many applications yet. In the past, `landuse=comercial` or `amenity=police` was used.  When the key is rendered we can rework this.

**Comment by jeisenbe** [comment]
The key `police=` has been used less than 2000 times overall, and the most common value is still `police=traffic_police`, used 983 times, which was not part of the proposal. 

Tags like `police=barracks`, `police=car_pound`, `police=naval_base` have only been used a dozen times each, or less: https://taginfo.openstreetmap.org/keys/?key=police#values

I believe we will need to wait until these tags are more firmly established before rendering them.

Also, different features might require a different rendering. For example, a `police=barracks` is a type of residential facility, while a `car_pound` is more similar to a private parking lot, and a `naval_base` is similar to a police station, and `police=office` might be rendered like `office=*`

**Comment by jeisenbe** [comment]
We would also need to consider adding `police=*` as a polygon key in the lua file, so it will not be possible to render features that are only tagged with `police=*` until after the next database reload, which will probably be at least several months from now. However, we could now discuss if the key should be added to the schema changes at that time.

**Comment by kocio-pl** [comment]
In fact it is possible to use most of the keys in v4.x (except the ones filtered by lua script, of course) through `hstore` values and we do use it, for example `icao=*` and `iata=*` values. 

It might make sense to move them into real values one day, it might be one of the goals of database reload.

**Comment by jeisenbe** [comment]
There is no problem with using new tags and keys for features which
already have a main feature tag which is imported properly as a
polygon. But the `police=*` key is supposed to be used alone, on areas
as well as nodes. An area tagged `police=barracks` would not be
imported properly as a polygon and therefore will not be rendered,
unless the lua file is changed and the database reloaded. This was the
same issue with adding rendering for `healthcare=*` features which are
not tagged as `amenity=*` or `building=*`.

**Comment by jeisenbe** [comment]
Features such as police=barracks, police=car_pound, police=naval_base, and police=office are still used less than 200 times overall, so for now I will close this issue. When use of these tags has risen and become firmly established around the globe we can reopen this issue and consider adding `police=*` as a polygon key during a future database reload.
