### ISSUE TITLE
Burmese word order

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#392]
I got a somewhat belated comment that Burmese words are out of order with the font changes.

The example I'm looking at is http://www.openstreetmap.org/node/26576173

**Comment by matkoniecz** [comment]
reopening per discussion starting on https://github.com/gravitystorm/openstreetmap-carto/issues/1313#issuecomment-76483078

**Comment by lminko** [comment]
+1

**Comment by gravitystorm** [comment]
I can confirm this is fixed with mapnik 3 / harfbuzz, you can see the results on my Transport layer

http://www.openstreetmap.org/#map=11/21.9838/96.3899&layers=T

**Comment by math1985** [comment]
As Mapnik 3 now has been rolled out, this should have been solved on openstreetmap.org.
