### ISSUE TITLE
Part of query is not restricted by bounding box

### ISSUE THREAD

**Issue by nexces** [gravitystorm/openstreetmap-carto#3937]
WHERE conditions on line:
https://github.com/gravitystorm/openstreetmap-carto/blob/05dc392c9b828814b3ce741e8b5ad397b934b4f5/project.mml#L2100

are different than on line:
https://github.com/gravitystorm/openstreetmap-carto/blob/05dc392c9b828814b3ce741e8b5ad397b934b4f5/project.mml#L2090

which causes sequential table scan (long execution) and collecting unwanted data

**Comment by jeisenbe** [comment]
Thank you for reporting this problem, @nexces. Would you have the time to submit a PR which would fix it?

**Comment by nexces** [comment]
@jeisenbe PR ready

**Comment by jeisenbe** [comment]
Thank you for the PR!

If you are interested in helping further, we have a number of open issues. See the labels "[good first issue](https://github.com/gravitystorm/openstreetmap-carto/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)" and "[help wanted](https://github.com/gravitystorm/openstreetmap-carto/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)" in particular.

**Comment by jeisenbe** [comment]
For reference, I caused this bug in PR #3898
