### ISSUE TITLE
Hudson Bay label placement incorrect

### ISSUE THREAD

**Issue by KeeganI** [gravitystorm/openstreetmap-carto#3943]
Sorry if this is not the correct place to put this, I am super new. I recently made a osm server and imported the data using osm2pgsql. I noticed my Hudson Bay label is not in the correct location:
![image](https://user-images.githubusercontent.com/31942031/67324166-62910180-f4e1-11e9-9859-a58057c3b341.png)

How do I go about simply hiding/removing this label on my local server?

**Comment by pnorman** [comment]
Where did you import data for?

**Comment by KeeganI** [comment]
> Where did you import data for?

I imported the data from the latest osm.pbf planet file

**Comment by jeisenbe** [comment]
Was the planet.osm.pbf file downloaded in the last few days? Has it been
modified?

The Hudson Bay label should be based on this relation, which was last
edited 12 days ago:
https://www.openstreetmap.org/relation/9441240#map=4/60.99/-79.76

I suspect this is a data problem which is not yet visible on
openstreetmap.org because the low-zoom tiles are only updated about once a
month.

**Comment by jeisenbe** [comment]
The Hudson Bay multipolygon relation has 13,440 ways as members! I can't retrieve it's history on openstreetmap.org - too big. Can someone with an unlimited internet connection try to download this monster and check it out?

**Comment by KeeganI** [comment]
> Was the planet.osm.pbf file downloaded in the last few days? Has it been modified? The Hudson Bay label should be based on this relation, which was last edited 12 days ago: https://www.openstreetmap.org/relation/9441240#map=4/60.99/-79.76 I suspect this is a data problem which is not yet visible on openstreetmap.org because the low-zoom tiles are only updated about once a month.

@jeisenbe  I used a world file from a month ago and 4.22. I had the issue with the hudson bay and an issue with the labeling of Canada and the United States. I recently re did the import with a world file from this week and 4.23. Canada and the United States is fixed but Hudson Bay still has the placement issue.

**Comment by jeisenbe** [comment]
In this case I think I've fixed the data in the main OpenStreetMap database, so you should be able to update your planet.osm.pbf file with the latest diff, using Osmosis. See https://wiki.openstreetmap.org/wiki/Planet.osm/diffs and https://wiki.openstreetmap.org/wiki/Osmosis
It's best to edit the database directly if something is mapped incorrectly, and you are able to fix it.

In the future, if you find data that you want to remove from your local copy of the database only, you can  create a change set file and apply it to with Osmosis (see [examples](https://wiki.openstreetmap.org/wiki/Osmosis#Example_usage)), if the data in OpenStreetMap is not wrong.

You can also remove rendering for all features at a certain zoom level by editing the relevant `.mss` file - for example, if you don't want `natural=bay` features displayed at low zoom levels, you could edit `openstreetmap-carto/water.mss` to change this line:

https://github.com/gravitystorm/openstreetmap-carto/blob/da4d48dca316e8813c4e8b32922eda08f63e0bba/water.mss#L337

(I would recommend creating a new branch with git first: `git checkout -b my-branch` - this will make it easy keep your `master` branch up-to-date with this repository)

for example try:
```
  [feature = 'natural_bay'][zoom >= 10],
```
This would rendering bays only at z10 and higher zoom levels

Or more generally you could edit this line to stop rendering all water area labels at low zoom:
https://github.com/gravitystorm/openstreetmap-carto/blob/da4d48dca316e8813c4e8b32922eda08f63e0bba/water.mss#L342
Change to z4 and higher only:
``` 
    [zoom >= 4][way_pixels > 3000][way_pixels <= 768000],
```

This is all a bit off topic for this repository, but I hope it helps you find a solution that works for your user case. 

For further help about setting up a server or editing the map style, try the OSM-dev mailing list: https://lists.openstreetmap.org/listinfo/dev

If you encounter general problems you can try the Talk mailing list: https://lists.openstreetmap.org/listinfo/talk

Or the forums: https://forum.openstreetmap.org for example [Rendering maps](https://forum.openstreetmap.org/viewforum.php?id=100) and  [Development](https://forum.openstreetmap.org/viewforum.php?id=13)
