### ISSUE TITLE
Label for vending_machine=parking_ticket uses uncommon value selection

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#3946]
### Actual behavior

The label for the vending machine on the map is sourced from the operator=* tag even though a name=* tag is present.

### Expected behavior

Do prefer name= over operator=. This is also how OsmAnd+ and JOSM do it by default.

### Links and screenshots illustrating the problem

https://osm.org/node/4329279576

**Comment by jeisenbe** [comment]
It's uncommon for ticket machines to have an individual name. 
According to taginfo 33% of `amenity=vending_machine` features have an `operator=*` tag but only 9% have a `name=*` tag.

The wiki page mentions `operator=` but not `name=` - https://wiki.openstreetmap.org/wiki/Tag:amenity=vending_machine

Most of the `name=*` tags seem to not actually be a specific name of a certain vending machine. I tried this search for [named vending_machine nodes in Wales](https://overpass-turbo.eu/s/NoZ). The 2 features found were named "School of Electronic Engineering", "School of Computer Science", "St Gwladys Car Park", "Coke", "Drinks and Snacks", "Drinks", "Snacks", "Amazon Locker", "Pit Stop", "Graham Hardinges" and "Photo-Me". Only the last 3 might be commonly-used names. 

The operator tags for these same features were: "Bangor University" x2, "Campus Catering", "Caerphilly County Borough Council", and "Amazon" - only the last is really helpful. 

Searching for all in Wales with `operator=` finds a few more useful examples, including: "Transport for Wales", "Knolton Farmhouse Cheese", "4CG", and "Newport Bus", but many more unhelpful operators: "Ceredigion Council", "Pembrokeshire Coast National Park Authority", "Pembrokeshire County Council", "Conwy Council".

The example given above, [node 4329279576](https://osm.org/node/4329279576), has the name "Neues Rathaus 1 - Außenstellplätze" which seems to mean "New Town Hall 1 - outdoor parking spaces". 

In contrast, the operator is "Stadt Göttingen", meaning "Göttingen City", which makes sense, though rendering this is not very useful. 

It would make the most sense to stop rendering the operator tag for vending machines.

**Comment by jeisenbe** [comment]
Looking at some more data from England, it looks like the `operator=` label might be useful for rendering `parcel_pickup` vending machines (e.g. Amazon lockers).

The `public_transport_ticket` features also have sensible `operator=*` values, but usually the operator is obvious from the context. Only at major stations, where there might be more than one operator, would this information be helpful.

The operator of parking_ticket machines seems to never be helpful.

The `name=` tags are usually descriptions, duplicate the operator, or duplicate the name of the parking lot or the bus stop / train station, or the street. I'd hoped that the Amazon lockers might at least have unique names, but they are rarely tagged properly.

**Comment by jragusa** [comment]
I agree to remove `operator` label from `parking_tickets` but not for `public_transport_ticket` especially in multi-modal platforms where you can find both train and coach from different companies

**Comment by matkoniecz** [comment]
I would expect that removal label for `parking_tickets` may overall improve map.

Rendering `name` seems weird, a place where individual ticket machines have names is highly unusual.
