### ISSUE TITLE
Render cycleway over road

### ISSUE THREAD

**Issue by hugobqd** [gravitystorm/openstreetmap-carto#3956]
When a cycleway is along a road, it must be visible and not under

<img width="685" alt="Capture d’écran 2019-10-28 à 14 51 52" src="https://user-images.githubusercontent.com/35178/67684125-e2601580-f992-11e9-942a-accb057f2e0e.png">

https://www.openstreetmap.org/#map=18/45.92572/-1.33133

**Comment by jeisenbe** [comment]
This is difficult to fix. At mid zoom levels, say z14, if the cycleway is rendered above the road fill it could get quite confusing, since the cycleway would appear to be in the middle of the road, even if we made the road rendering much narrower.

**Comment by tomass** [comment]
This requires a cartographic generalisation operation of "displacement" which is a pre-processing (actually all real cartography needs heavy pre-processing).
OSM-Carto has restrictions on pre-processing therefore it is impossible to do this.

**Comment by matkoniecz** [comment]
Unfortunately, rendering footway and/or cycleway over roads will cause even worse rendering problems.

**Comment by matkoniecz** [comment]
I am marking is at wontfix, as it is something that on ideal map would be handled better, but we are unable to do this here given various limitations.
