### ISSUE TITLE
Name rendered twice on power/building

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#3963]
Observed:
The name of building (way 737365087) is rendered twice.
https://osm.org/#map=19/51.54569/9.76438

Expected: just one label should be enough.

**Comment by jeisenbe** [comment]
This building is also tagged as a `power=generator` which gets `text-dy: 10`, so the building name is being displayed at the center, and the power generator name (which is the same) is displayed just below.

The `text-dy` is necessary for wind generators, which are displayed with an icon, but should not be used for other types of generators. 

I caused this bug in #3515, sorry.
