### ISSUE TITLE
Remove icon for shop=ice_cream as a duplicate of amenity=ice_cream

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3970]
### Expected behavior
- [`amenity=ice_cream`](https://wiki.openstreetmap.org/wiki/Tag:amenity=ice_cream) is the "de facto" tag for places which mainly serve ice cream or frozen yogurt to eat on the premises or take away, and is currently rendered with an ice cream cone icon. Mappers should be given feedback that this is the most common method of mapping such features

### Actual behavior
- We render the same icon (but in a different color) for [`shop=ice_cream`](https://wiki.openstreetmap.org/wiki/Tag:shop=ice_cream), which has less than 1/10th as much usage.

**Taginfo comparison:** https://taginfo.openstreetmap.org/compare/amenity=ice_cream/shop=ice_cream
27 027 ` amenity=ice_cream`  features
vs
2 293 `shop=ice_cream` features

**Taghistory:** 
- Usage of `shop=ice_cream` has hardly increased in the past 3 years, while `amenity=ice_cream` tripled (9k to 27k)
![ice-cream-shop-vs-amenity-taghistory](https://user-images.githubusercontent.com/42757252/68587144-af0ca300-04c9-11ea-990c-3cd3b9ee65fd.png)

See discussion on Tagging mailing list:
https://lists.openstreetmap.org/pipermail/tagging/2019-November/049155.html

Icon (same shape for both tags, but color is set to `@shop-icon` or `@amenity-brown`
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/ice_cream.svg

### Solution
- Remove the SVG icon from shop=ice_cream. This feature would still be rendered as a standard shop "dot".

**Comment by matkoniecz** [comment]
https://josm.openstreetmap.de/ticket/9125 is related (" shop=ice_cream should be detected and fixed to amenity=ice_cream ") wontfixed in 2016 (when popularity of this two tags was significantly closer and before my edit to OSM Wiki that removed claim that this two tags discribe different features).
