### ISSUE TITLE
Admin_level=9/10 boundaries are too similar to disused railways and paths

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#3971]
### Expected behavior
- Administrative boundaries (`boundary=administrative`) should not be similar to on-the-ground features
- All rendered `admin_level=*` values should be clearly distinct

### Actual behavior
- `railway=disused` features are very similar to `boundary=administrative` + `admin_level=9` or `admin_level=10` (which have the same rendering)
- Hat tip to @Tomasz-W for noticing this in https://github.com/gravitystorm/openstreetmap-carto/issues/2872#issuecomment-449655031
- The widely-spaced, dotted gray line also might be mistaken for a type of `highway=path` or `=footway` with `access=no` or  under construction

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=17/52.37805/16.90282
![z17-railway-disused-border-9-10-17:52 37805:16 90282](https://user-images.githubusercontent.com/42757252/68637071-e36f7600-0540-11ea-9f67-d89a1f2d03ce.png)

https://www.openstreetmap.org/#map=18/52.37779/16.83689
![18:52 37779:16 83689-border-9-vs-disused-rail](https://user-images.githubusercontent.com/42757252/68637080-e8342a00-0540-11ea-8b76-d31daaaa9442.png)

https://www.openstreetmap.org/#map=18/52.37546/16.83968
![18:52 37546:16 83968-admin_level-9-10-vs-railway-disused](https://user-images.githubusercontent.com/42757252/68637113-fa15cd00-0540-11ea-85e9-975641f88d92.png)

**Comment by jeisenbe** [comment]
Anyone have a good example of an under-construction or `access=private` path next to one of these? I thought I had seen one yesterday in another issue but can't find it now.

**Comment by kocio-pl** [comment]
I guess we could add wide ending of the lines, since this is common rendering of borders on different maps and we're gonna use this only for pipelines probably (and even then it would be double line - see from the https://github.com/gravitystorm/openstreetmap-carto/issues/640#issuecomment-530789947).

I'm not suggesting just adding it to the al9 (and al7, since this is the same as al6 IIRC), but rather add this as another tool in our toolset.

**Comment by newtestaccount4949** [comment]
Also, level 6 looks a lot like tracks (see https://www.openstreetmap.org/#map=15/55.7010/-4.3341)

**Comment by HolgerJeromin** [comment]
screenshot for linked map area:
![image](https://user-images.githubusercontent.com/2410353/70212585-d3aa1280-1737-11ea-9c6f-2e8295bc299b.png)

**Comment by jeisenbe** [comment]
Fixed by #4100, I believe
