### ISSUE TITLE
Docker install documentation

### ISSUE THREAD

**Issue by chivi94** [gravitystorm/openstreetmap-carto#3978]
I had some problems with the file "DOCKER.md", to adapt the docker option to my own, and it was because of the entrypoint of the dockerfile.
### Expected behavior

To set up the server i would like to only execute the command "docker-compose up", without specifying the command execution mode
### Actual behavior

Now, it's neccesary to execute docker-compose up with import or run, like this:
- docker-compose run service [run|import]

### Links and screenshots illustrating the problem
------

**Comment by jeisenbe** [comment]
@chivi94 is this issue no longer a problem for you?
