### ISSUE TITLE
Visualise name for amenity=social_facillity

### ISSUE THREAD

**Issue by AllroadsNL** [gravitystorm/openstreetmap-carto#3987]
[amenity=social_facillity](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dsocial_facility)

People, family, friend, contacts, often visit these amenity.
A quick look on the map must shown these facilities, ohh, there.

Name is not showing.
I am in contact with the organisation, because of the name is more of a description.
![benaming](https://user-images.githubusercontent.com/8817345/70541068-a362d980-1b66-11ea-9e2d-06f083be163d.JPG)

**Comment by polarbearing** [comment]
node: https://www.openstreetmap.org/node/2719177187/history
building: https://www.openstreetmap.org/way/266363157

The name for social facilities are typically rendered in this style. 

If it fails in your particular case, we'd need to check the reasons. Often icons or labels are blocked by other features. 
The tile is clean, it was re-rendered 13:33 after your 12:44 edit. 
The name is quite long, thus the label would be bulky. Is the town and the region really part of the name?
The facility is tagged on a separate node; if the facility uses the full building you might consider tagging the building instead.

**Comment by AllroadsNL** [comment]
In the Netherlands, we have a import of buildings and adressnode. In the Netherlands all mostly all adresses are there, so you can route to them. A group is still updating data.
We agreed together the best way  is to merged the company to adressnodes.
First I took out the one  " ,"  in the name.
Then both ", ".
Shorten the name, then immediately it is  visuallised after a few minutes.
![zorgkantoor](https://user-images.githubusercontent.com/8817345/70628749-04eb7c80-1c29-11ea-9fb9-b77e1d1e7aa0.JPG)


Made it a little longer. It works too.
![longer name](https://user-images.githubusercontent.com/8817345/70629217-eafe6980-1c29-11ea-95bb-28eb4388be2a.JPG)

Then a extra word with a space. It works too. The words in a different order then, the first problem example. 4 lines of text.
![longer name same line](https://user-images.githubusercontent.com/8817345/70629983-19307900-1c2b-11ea-9085-7966519d8c3d.JPG)

The problem example, order of words again. It fails.
![conflict again](https://user-images.githubusercontent.com/8817345/70630923-a88a5c00-1c2c-11ea-82f8-7a42f077237e.JPG)
Maybe a fifth lines is needed for the words.
then maybe in conflict with the bicycle parking visualisation.

I will set it back to a working name.

**Comment by polarbearing** [comment]
In general, it is not such a good idea to change the data a lot to test rendering, or to adjust the length of a name to appearance in one particular renderer. 

In your particular case, you appear to have duplicate nodes for the same object, maybe they even block each other:
https://www.openstreetmap.org/node/2719177187/history
https://www.openstreetmap.org/node/7048982927/history

**Comment by AllroadsNL** [comment]
Thanks, for finding that one, saved now only the original node .
