### ISSUE TITLE
amenity=festival grounds not yet rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#3990]
https://www.openstreetmap.org/way/747470467 was rendered last month, but not anymore this month.

**Comment by jeisenbe** [comment]
This feature was previously tagged as a leisure=recreation_ground.

The tag amenity=festival_grounds has not yet been rendered by this style.

**Comment by jidanni** [comment]
> This feature was previously tagged as a leisure=recreation_ground. The tag amenity=festival_grounds has not yet been rendered by this style.

OK. But I apparently made that change following [your advice](https://wiki.openstreetmap.org/wiki/Talk:Good_practice#Don.27t_map_temporary_events_and_temporary_features). Please give me some new advice. Thanks.

**Comment by jeisenbe** [comment]
This is not the appropriate place to discuss how things should be tagged, but I will say that amenity=festival_grounds seems to be the best option for https://www.openstreetmap.org/way/747470467 even though it is not a very common tag yet. It might be good to discuss with the community if this tag should also be used for showgrounds / fairgrounds, because there are a number of those features.

**Comment by jeisenbe** [comment]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfestival_grounds is documented as a "proposed" tag, used 135 times. 

Similar tags:
amenity=music_venue - 359 uses
leisure=festival_grounds - 13
leisure=music_venue - 61
amenity=concert_hall - 214
amenity=showground - 6 
recreation_ground=showground - 25 
landuse=fairground - 62
leisure=fairground - 12

This could be rendered the same as landuse=commercial or leisure_stadium, but probably needs to become more common first, unless we want to render all music features like amenity=music_venue and amentiy=concert_hall at the same time and in the same style.

**Comment by pnorman** [comment]
> probably needs to become more common first

Yes, with 135 uses we wouldn't render it but instead need to wait for the tagging to develop and it to be more common.
