### ISSUE TITLE
Representing public_transport=platform nodes

### ISSUE THREAD

**Issue by Robot8A** [gravitystorm/openstreetmap-carto#3994]
I suggest a representation of public_transport=platform nodes when they don't have and old scheme railway station or bus stop tag. This can be important for representing other transportation modes stops such as shared taxis.

The suggestion for the icon is a public transport stop pole similar as the bus stop emoji (https://emojipedia.org/bus-stop/)

Thanks in advance

**Comment by jeisenbe** [comment]
Bus stops, tram stops and train stations are represented in this style for features tagged with `highway=bus_stop`, `railway=station`, `railway=halt` and `railway=tram_stop`, in addition to `amenity=ferry_terminal`, `amenity=bus_station`, `aerialway=station` and `amenity=taxi`.

We previously declined rendering `public_transport=platform` in issue #311 - but I will address the comment about "share_taxi=yes".

While `public_transport=platform` + `share_taxi=yes` has been used [6000 times](https://taginfo.openstreetmap.org/tags/?key=public_transport&value=platform#combinations), this combination has not been documented. The page [Key:share_taxi](https://wiki.openstreetmap.org/w/index.php?title=Key:share_taxi&redirect=no) is redirected to Key:psv, and it's not clear how this tag is different than minibus, taxi and bus. It's also not documented to combine this tag (or bus=yes, minibus=yes, taxi=yes etc) with `public_transport=platform` - this was not part of the public_transport proposal. 

Also, only [207 nodes (overpass link)](http://overpass-turbo.eu/s/PjW) have `share_taxi=yes` + `public_transport=platform` but without `highway=bus_stop` or `tram=yes` or `trolleybus=yes` or `bus=yes` - so only a small number of features cannot currently be tagged with a tag which this style already renders. Most of the featuers are in central Europe and eastern Europe - I was not aware that there are such public service vehicles in these countries 

 I just rode on a vehicle that might be described as a [share taxi](https://en.wikipedia.org/wiki/Share_taxi), here in Indonesia, to get home from a remote village: it was a pickup truck with room to sit or stand up in the back, traveling back and forth on a new, one-lane rough road with an irregular schedule. The only fixed stops are at the beginning and end, and we call these (and other minibuses with semi-fixed routes) a "taxi" here in eastern Indoneisa. But is this how the tag is being used in Germany and Russia, or is it for some other type of taxi?

**Comment by Robot8A** [comment]
Right now I am living in Turkey for some time, where https://en.wikipedia.org/wiki/Dolmu%C5%9F are quite popular, and in some cities the main mode of transportation. In the city where I'm living they are usually Ford Transit vans (~8-10 people fit in there) that have fixed stops in busier areas and you hail and ride on less busy streets. In the street the stops have distinctive signage with a big D and the destinations the share taxis serve.
I've seen it mapped on OSM as a taxi rank as well as a bus stop, so it would be nice to set a common tagging for this mean of transportation. As far as I am aware, similar transportation methods exist in other parts of the world (https://en.wikipedia.org/wiki/Share_taxi).

**Comment by jeisenbe** [comment]
Those look like minibuses, and they are a bit larger than the usual "angkutan kota" aka "angkot" vehicles here in Indonesia which are the main form of public transportation in most towns (other than motorcycle taxis). Is there any reason they should not be considered a type of bus?

**Comment by kocio-pl** [comment]
There are many types of public transport - this might be not a complete list, but it's good starting point:

https://en.wikipedia.org/wiki/Template:Public_transport

Some means of public transport is currently rendered in this style, while some others are not, even if the general idea of public transport platform is quite clear, no matter what vehicles (single- or multimodal) stop there and if we know the distinction between share taxi and taxi or if guided bus/minibus/trolleybus is a kind of bus or not.

**Comment by jeisenbe** [comment]
> Some means of public transport are currently rendered in this style while some others are not

Could you provide an example of a type of public transit which is cannot be rendered in this style through the use of established tags?

**Comment by kocio-pl** [comment]
Unfortunately I couldn't, that's why I posted a link to the list of the different public transport to check what they might be. However if we don't consider trolleybus to be a bus, then it is an example of such case.

**Comment by jeisenbe** [comment]
There are only [400 nodes](http://overpass-turbo.eu/?q=LyoKVGhpcyBoYcSGYmVlbiBnxI1lcmF0ZWQgYnkgdGhlIG92xJJwxIlzLXR1cmJvIHdpemFyZC7EgsSdxJ9yaWdpbmFsIHNlxLBjaMSsxIk6CsOiwoDCnGFtxI1pdHk9cmVzdGHEqGFudMWIwp0KKi8KW291dDpqc29uXVt0acWMxaLFpDI1XTsKLy_Ej8SUxJ1yIMWSc3VsdHMKKAogIMW2IHF1xJLEmsSjcnQgZm9yOiDFiMWKxYxuxY7FkMW9xZXFl8WZxZvGhSBub2RlWyJ0cm9sbGV5YnVzIj0iecWTIsWqInB1YmxpY1_GqsWYc3DGk3TGtMa7bMSUxpJybca5xqjEhGdod2F5IiHGtcaxc1_FlG9wx5AixJNpbMeVx5fHmceKx4zGk8ePxrrHo8elx5bHmMa1xZTElGnFqMehx67HpsexIsSIxoDHocWLxY3Fj8e6x5vHncWVxazHtsetYcekx7nHqMeDbciEx5_GucW0xobIk8aGKcW0xohwxLfFmcW8xZPFv8aBCsWvxJjGpXnFtD7FtMihc2tlxL1xdDs&c=BArR-6-aXC) with public_transport=platform + trolleybus=yes but that lack another tag which is currently rendered, like as a train station, tram stop or bus stop.

And most of those have bus=yes or train=yes or tram=yes, suggesting that one of those tags should be added - only 74 features lack these: http://overpass-turbo.eu/s/PAX

In contrast, there are over 8000 features tagged with public_transport=platform and both trolleybus=yes + highway=bus_stop, suggesting that this is the almost universal way of mapping these features. So I would feel confident recommending using highway=bus_stop for trolleybuses as well as for buses powered by petrol, diesel, natural gas, fuel cells or batteries.

**Comment by kocio-pl** [comment]
In the case of trolleybus I would rather check if theese are really multimodal stops or just simply tagging for rendering, which sounds probable to me.

The list of all public transport types should be evaluated too, sooner or later.

**Comment by jeisenbe** [comment]
`highway=bus_stop` isn't tagging for the renderer, it's by far the most common way to tag bus stops, whether they are powered by overhead wires, batteries or fossil fuels, as shown above. 

Currently there are over 2.5 million highway=bus_stop nodes but only 1 million public_transport=platform  + bus=yes or trolleybus=yes. There are actually more public_transport=platform + highway=bus_stop combinations (1.25 million), probably because adding bus=yes / trolleybus=yes was not part of the public_transport proposal and isn't needed if highway=bus_stop is used.

https://taginfo.openstreetmap.org/tags/public_transport=platform#combinations 
https://taginfo.openstreetmap.org/tags/trolleybus=yes#combinations
https://taginfo.openstreetmap.org/tags/highway=bus_stop

**Comment by jeisenbe** [comment]
Closing: As mentioned in the discussion above, currently all public_transport=platform nodes can also be tagged with one of the more common tags which we render due to past community consensus: highway=bus_stop, railway=station, railway=halt and railway=tram_stop. Also see previous discussion in #311 about rendering public_transport tags.

**Comment by kocio-pl** [comment]
The problem with using `highway=bus_stop + trolleybus=yes` we're no longer sure if this is just a trolleybus stop or multimodal bus+trolleybus stop (which is clear with `public_transport=platform + bus=yes/no + trolleybus=yes/no`). This way we're promoting less precise description of reality (just to make it visible on the map).

And we're still only talking about just one type (trolleybus), no other transportation was even checked.

**Comment by jeisenbe** [comment]
The bus service itself will be mapped as a route relation with `route=bus` or `route=trolleybus`, and the bus stops should be members of this relation, so this should make it clear whether or not a particular stop is serviced by trolleybuses, regular buses, or both. It isn't necessary to add a tag to the stop node: https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dtrolleybus
