### ISSUE TITLE
forest disappears at zoom level 17 and only zoom level 17

### ISSUE THREAD

**Issue by ferdinand0101** [gravitystorm/openstreetmap-carto#3996]
### Expected behavior
It doesn't disappear
### Actual behavior
It does
### Links and screenshots illustrating the problem
https://youtu.be/HDUbhehu-Y4

**Comment by ferdinand0101** [comment]
also unlike another issu which coplains about a simmelar thing this fores has been edited 5 days ago which should be long enough for it to render

**Comment by jeisenbe** [comment]
Thank you for the report, @ferdinand0101. 

Would it be possible to link directly to the rendered location like `https://www.openstreetmap.org/#map=<coordinates>`? This will make it possible to check the object tags directly and test the area for problems.

Usually when a feature is visible at all zoom levels except one, there is not a problem with this stylesheet but a temporary issue with one of the renderering servers that are used to provide the tiles on openstreetmap.org.

**Comment by manfredbrandl** [comment]
The problem is still there at https://www.openstreetmap.org/#map=17/51.38167/7.06039

**Comment by matkoniecz** [comment]
> The problem is still there at https://www.openstreetmap.org/#map=17/51.38167/7.06039

As expected, it is no longer present. It was either data or database issue, not a map style issue.

In such cases it is a good idea to load area in JOSM and run validator. It usually turns out to be a broken multipolygon or a similar issue, in remaining cases fixing invalid data triggers a database update.

**Comment by HolgerJeromin** [comment]
Perhaps fixed three days ago:
https://github.com/openstreetmap/operations/issues/350#issuecomment-573445928

**Comment by matkoniecz** [comment]
Yes, it is likely that report by @tbertels located the root cause.
