### ISSUE TITLE
containers are up , got error about gis 

### ISSUE THREAD

**Issue by do-d1** [gravitystorm/openstreetmap-carto#3997]
![image](https://user-images.githubusercontent.com/14095078/71781005-5988da00-2fd2-11ea-8b68-d4f878584c75.png)

this are the only DB's in 2 containers :  kosmtik:v1 , db:v1

![image](https://user-images.githubusercontent.com/14095078/71781024-8806b500-2fd2-11ea-8156-de33e23e9461.png)

any suggestions ?

**Comment by jeisenbe** [comment]
From the screenshot the error message displayed by Kosmtik:

```
 Postgis Plugin FATAL:database "gis" does not exist Connection string "dbname-gis  connect_timeout=4" encountered during parsing of layer 'landcover-low-zoom' in Layer
```

Looks like the you have Debian 10.7-1.pgdg90+1

What were the steps that you followed before encountering this error? 

Have you tried our [instructions for using Docker](https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md) instead?

**Comment by do-d1** [comment]
actually its running as a docker

**Comment by jeisenbe** [comment]
Could you describe your system set-up and the steps you followed that led to this error message?

**Comment by do-d1** [comment]
today i started over , new vm , cloned the repo and followed the:
[Quick start](https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md#quick-start)
`docker-compose up import`
had a small issue [#3999](https://github.com/gravitystorm/openstreetmap-carto/issues/3999)
then `docker-compose up kosmtik`

`Attaching to openstreetmapcarto_kosmtik_1
kosmtik_1  | Waiting for PostgreSQL to be running
kosmtik_1  | PostgreSQL running
kosmtik_1  |
kosmtik_1  | Starting get-shapefiles.py...
kosmtik_1  | 1-1. Downloading 'simplified-water-polygons-split-3857'...
kosmtik_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
kosmtik_1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
kosmtik_1  | Warning: data/simplified-water-polygons-split-3857.zip: No such file or
kosmtik_1  | Warning: directory
  0 22.7M    0 16384    0     0  25883      0  0:15:21 --:--:--  0:15:21 25883
kosmtik_1  | curl: (23) Failed writing body (0 != 16384)
kosmtik_1  |
kosmtik_1  |
kosmtik_1  |    'curl' error: download failed.
kosmtik_1  |
kosmtik_1  | cp: cannot create regular file '.kosmtik-config.yml': Permission denied
kosmtik_1  | [Core] No usable config file found in .kosmtik-config.yml
kosmtik_1  | [Core] Loading plugin from ../plugins/base-exporters/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/hash/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/local-config/index.js
kosmtik_1  | [Core] Loading plugin from ../plugins/datasource-loader/index.js
kosmtik_1  | [Core] Loading project from project.mml
kosmtik_1  | [Core] PreviewServer started, you can browse http://0.0.0.0:6789
`


cp: cannot create regular file '.kosmtik-config.yml': Permission denied

**Comment by Adamant36** [comment]
> cp: cannot create regular file '.kosmtik-config.yml': Permission denied

Did you trying doing it with sudo (`sudo docker-compose up kosmtik`)? If you don't it usually gives a file permission denied error. Even if your a Superuser.

**Comment by jeisenbe** [comment]
Did the rendering test work when you checked http://0.0.0.0:6789 in your browser?

**Comment by do-d1** [comment]
> Did you trying doing it with sudo (sudo docker-compose up kosmtik)? If you don't it usually gives a file permission denied error. Even if your a Superuser.

i cloned it to \root\openstreetmap-carto
and run it as root  sudo -i 

> Did the rendering test work when you checked http://0.0.0.0:6789 in your browser?

no i get a blank page 
ERR_CONNECTION_REFUSED


i will try to move the folder to user home directory and run from there

**Comment by HolgerJeromin** [comment]
> Did the rendering test work when you checked http://0.0.0.0:6789 in your browser?

0.0.0.0 is the alias for "listen on all devices". 
You have to tell the browser to use http://127.0.0.1:6789
if you are on the same machine

**Comment by jeisenbe** [comment]
Thank you for the correction. I usually go directly to localhost:6789 - e.g. localhost:6789/openstreetmap-carto/#6/-4.000/139.000 - with the 3 numbers representing #<Zoom Level> / <lattitude> / <longitude>

**Comment by jeisenbe** [comment]
> i will try to move the folder to user home directory and run from there

Good idea.

"OpenStreetMap Carto repository needs to be a directory that is shared between your host system and the Docker virtual machine. Home directories are shared by default; if your repository is in another place you need to add this to the Docker sharing list (e.g. macOS: Docker Preferences > File Sharing; Windows: Docker Settings > Shared Drives)." - but it's easiest to just have it as a home directory.

Re: `get-shapefiles.py` - if you have not yet downloaded the shapefiles, this script needs to run with a good internet connection. You will end up downloading about a gigabyte of data, mainly the ocean shapefiles mentioned at INSTALL.md

You can also download them manually at the following paths. They should be in a folder named "data" under the openstreetmap-carto directory (so `/openstreetmap-carto/data/` ) to prevent them being re-downloaded by the shapefiles.py script. 

* [`simplified_water_polygons.shp`](https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip) (updated daily)
* [`ne_110m_admin_0_boundary_lines_land.shp`](http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip)
* [`water_polygons.shp`](https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip) (updated daily)
* [`icesheet_polygons.shp`](https://osmdata.openstreetmap.de/download/antarctica-icesheet-polygons-3857.zip)
* [`icesheet_outlines.shp`](https://osmdata.openstreetmap.de/download/antarctica-icesheet-outlines-3857.zip)

**Comment by jeisenbe** [comment]
@do-d1 is this problem now solved?

**Comment by jeisenbe** [comment]
I assume the original issue is resolved, but if not, this issue can be reopened.
