### ISSUE TITLE
natural=spring blocks place node labels

### ISSUE THREAD

**Issue by Prince-Kassad** [gravitystorm/openstreetmap-carto#4011]
Example illustrating the problem: https://www.openstreetmap.org/#map=15/49.6064/8.1085&layers=N

natural=spring has priority over place node labels. As a result, the label for this village gets blocked by the spring at z14 and thus does not render. It gets rendered again at z13 when we stop rendering natural=spring. 

We definitely should not render natural=spring in such a way that it can block place node labels, even if it is uncommon for place nodes and springs to be close together like this.

Related to #3461

**Comment by imagico** [comment]
Separate layer for springs was introduced in #3189.

Related also to #3274.

**Comment by jeisenbe** [comment]
Springs are now back above water lines, so we could move them back to amenity-points, or move the springs layer after placenames.

**Comment by tilmanb** [comment]
> [...] move the springs layer after placenames.

This seems reasonable.
