### ISSUE TITLE
Text labels of man_made=bridge are shown too soon for short or narrow bridges

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#4019]
Related to #3979

### Expected behavior
- The text labels of man_made=bridge areas should generally be shorter than the longest dimension of the bridge, in most cases
- Common bridge names in languages which use an alphabetic script may be expected to include words about 10 characters long, which equals to about 50 pixels
- Many shorter bridges and viaducts are only 10 times longer than they are wide, therefore the bridge label can be shown at about 50*5= 250 way_pixels
- Most other area features, which are usually not so thin, are only labeled with their names at 3000 way_pixels: assuming an average length to width ratio of 2:1 for random landcover and landuse polygons, this is about 80 by 40 pixels.

### Actual behavior
- The way_pixels limit for man_made=bridge text lables is only 62.5 pixels, one zoom level sooner than suggested by the calculation above.
- While this is fine for long bridges (more than 30 times length vs width) or bridges with short name (no words longer than 6 characters), it shows the text label too soon for shorter bridges, or mid-length bridges with long names

### Suggested change
- Adjust way_pixels limit to 250 (1 zoom level later than current) or 187.5 (2 zoom levels sooner than other features)
- This will still show the bridge name almost 2 zoom level sooner than most area features, but not quite so soon as now.

### Examples:
Short (1 block long: 60 to 120 meters) road and pedestrian bridges in Chicago are already shown at z15, but the text label is usually significantly longer than the bridge itself:
![chicago-bridges](https://user-images.githubusercontent.com/42757252/73586484-3d089080-44f1-11ea-8541-6b7dcaf75ba5.png)

At z16 the bridge outline is barely visible. The text label is still as long as the bridge, but it looks reasonable:

![bridges-chicago-z16](https://user-images.githubusercontent.com/42757252/73586817-17ca5100-44f6-11ea-8594-42ca9e8f980b.png)

z17 shows the extent of the bridges clearly, for comparison:
![bridge-chicago-z17](https://user-images.githubusercontent.com/42757252/73586820-1e58c880-44f6-11ea-83a3-cb9b267a14e2.png)

**Comment by jeisenbe** [comment]
@matkoniecz what are your thoughts about this issue?

**Comment by matkoniecz** [comment]
I am not disputing that there is something to be tweaked.  From what I remember code was not tested with tiny named footway bridges. 

But I would dispute

> The text labels of man_made=bridge areas should generally be shorter than the longest dimension of the bridge, in most cases

In many cases label on maps is much bigger than named feature, I see no reason to make exception for bridges. Brisbane label is 500km long at https://www.openstreetmap.org/#map=4/-28.54/130.78

Bridges labels are also larger than their area in https://www.openstreetmap.org/#map=14/50.0425/19.9541 and it was actually tested and rendering is reasonable here.


> Short (1 block long: 60 to 120 meters) road and pedestrian bridges in Chicago are already shown at z15, but the text label is usually significantly longer than the bridge itself:

I am unable to judge is it reasonable rendering this case.

**Comment by Prince-Kassad** [comment]
The bridge name rendering would probably look a lot more pleasant if the name labels could be rotated according to the orientation of the bridge like road names. As it is now, bridges that go from north to south have a very awful name rendering, and they can render as early as z12 in some places when we only start rendering road names starting from z13.

**Comment by jeisenbe** [comment]
> As it is now, bridges that go from north to south have a very awful name rendering, and they can render as early as z12 in some places when we only start rendering road names starting from z13.

At mid zoom levels we could have the label follow the way (the outline of the bridge), towards the center, but this would not center the label perfectly. And at high zoom levels this would be confusing. 

I believe it's possible to transform a rectangle into a linear way in postgis, but this might be slow. Anyone know the code to do this, and want to test it?

**Comment by jeisenbe** [comment]
Here's the screenshot of https://www.openstreetmap.org/#map=14/50.0425/19.9541 Krakow, mentioned above as where it was tested:

<img width="614" alt="krakow-screenshot-before-z14" src="https://user-images.githubusercontent.com/42757252/76219919-ed3c8800-6259-11ea-8f75-38b4cd17d9f0.png">

Loading just the river and bridges, we see that 7 out of 10 have the name rendered, but the 3 smallest in this image don't show, with the 62.5 pixel limit:

<img width="614" alt="krakow-before-62 5-z14" src="https://user-images.githubusercontent.com/42757252/76219053-8cf91680-6258-11ea-94a2-1250d86cbc89.png">

Increasing the limit to 125 removes 3 more of the narrower/shorter bridge labels. The 4 largest remain: Would this be acceptable?

<img width="614" alt="krakow-after-125-z14" src="https://user-images.githubusercontent.com/42757252/76218589-d301aa80-6257-11ea-936c-b0322d000ed7.png">

A limit of 187.5 would only show the 2 largest bridges at z14, though most will show at z15 still:
<img width="614" alt="krakow-after-187 5-z14" src="https://user-images.githubusercontent.com/42757252/76219398-21fc0f80-6259-11ea-8bba-feca947d385d.png">


Here's Chicago now at z15 - with lots of bridge labels:
![chicago-bridges](https://user-images.githubusercontent.com/42757252/73586484-3d089080-44f1-11ea-8541-6b7dcaf75ba5.png)

With 125 way_pixel limit:
<img width="601" alt="chicago-after-125-z15" src="https://user-images.githubusercontent.com/42757252/76219543-553e9e80-6259-11ea-8236-5d135c19e6ce.png">

With 187.5 limit no bridges are shown::
<img width="601" alt="chicago-after-187 5-z15" src="https://user-images.githubusercontent.com/42757252/76219563-5c65ac80-6259-11ea-87ad-1c04d0eb53f4.png">

(They all show at z16 still, even the small pedestrian bridges:)
<img width="601" alt="chicago-after-125-z16" src="https://user-images.githubusercontent.com/42757252/76219910-e9a90100-6259-11ea-8b65-70a98bb0fef4.png">

**Comment by jeisenbe** [comment]
Another issue is seen with several bridges are close together:

The label of one bridge can block others nearby:
<img width="614" alt="hauptbahnbrucke-z15" src="https://user-images.githubusercontent.com/42757252/76221964-3a6e2900-625d-11ea-8195-6af53905d569.png">

When the bridges are close and oriented vertically, the labels can cross two bridges:
<img width="301" alt="hauptbahnbrucke-z16" src="https://user-images.githubusercontent.com/42757252/76221589-a9974d80-625c-11ea-997b-98dd59cdec3e.png">

**Comment by matkoniecz** [comment]
> Increasing the limit to 125 removes 3 more of the narrower/shorter bridge labels. The 4 largest remain: Would this be acceptable?

In this specific case label removal makes situation worse, but maybe improvement in other places balances it.
