### ISSUE TITLE
Icon for information=tactile_model does not fit

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#4021]
Aachen Dom has a tactile model of the building in front of it. Definitive no map.

https://www.openstreetmap.org/node/1272915553

https://www.mapillary.com/app/?focus=photo&pKey=orzv9Fvog8CL6uPeO4UCTQ

![image](https://user-images.githubusercontent.com/2410353/73833891-07261d80-480b-11ea-842c-f2a91b317661.png)

ref #3437 
cc @Tomasz-W

**Comment by jeisenbe** [comment]
Do you suggest removing the rendering for information=tactile_model, or is there another existing icon which would work better?

**Comment by dktue** [comment]
Isn't a tactile model a specific type of (3D) map?

**Comment by HolgerJeromin** [comment]
I don't think a person who creates [building models](https://en.wikipedia.org/wiki/Building_model) would say they are creating a map.

**Comment by polarbearing** [comment]
Maybe an icon illustrating a finger towards a structure?

**Comment by dktue** [comment]
Right, if there's a single building then it seem conterintuitive to call it a map.

I though of this one:
![metal-model-tuebingen](https://user-images.githubusercontent.com/2878623/74840309-0f13b080-5327-11ea-8fde-95400de1c70e.jpg)

**Comment by jeisenbe** [comment]
OK, options: 

1) remove the icon rendering for information=tactile_model
2) switch to another existing "information" icon

I don't think this feature is common enough to create a unique icon.

**Comment by HolgerJeromin** [comment]
I would be OK to fallback to an "i".
