### ISSUE TITLE
traffic_calming:island not rendered when they are areas, not nodes?

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4027]
Are https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland#Rendering rendered when they are areas, not nodes? https://www.openstreetmap.org/way/771115231

**Comment by jeisenbe** [comment]
The tag `traffic_calming=island` is not rendered by this style, whether mapped as a node or an area.

**Comment by Adamant36** [comment]
Related to #2086 maybe.
