### ISSUE TITLE
Should we release another version before schema changes?

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4031]
I've gone through PRs with approved reviews, which included #3952, a decently large visual change. Normally I'd like to split that up from the schema changes and release v4.26.0, but I'm not sure we have enough changes ready to be able to do that. Most of the open PRs [have no reviews](https://github.com/gravitystorm/openstreetmap-carto/pulls?q=is%3Apr+is%3Aopen+not+review%3Anone) or have [changes requested](https://github.com/gravitystorm/openstreetmap-carto/pulls?q=is%3Apr+is%3Aopen+review%3Achanges-requested).

Thoughts?

**Comment by jeisenbe** [comment]
I am ok with either option.

**Comment by imagico** [comment]
I see no real problem with having significant cartographic changes together with the schema change.

**Comment by pnorman** [comment]
Question discussed, closing issue.
