### ISSUE TITLE
research_institute at heart of coronavirus scandal not rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4036]
https://www.openstreetmap.org/way/766090654
https://wiki.openstreetmap.org/wiki/Tag:amenity=research%20institute

**Comment by imagico** [comment]
Please don't use a sensationalist title in attempting to lobby for rendering tags.

Duplicate of #2077 - if you see reason to reopen that based on changed tagging practice please comment there.

**Comment by polarbearing** [comment]
Besides, the virus is not a 'scandal', which is defined as an action "morally or legally wrong and causing general public outrage" - a disease has no moral.
