### ISSUE TITLE
Postgis Plugin: ERROR:  column "name" does not exist

### ISSUE THREAD

**Issue by nanoficator** [gravitystorm/openstreetmap-carto#4039]
Hey everybody!

I have the next error when I try to render tiles at zoom level from 5 to 9 (at the another zoom level everything is OK):

`Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist`

I try with this command (example for zoom level 5):

`render_list --num-threads=32 --socket=/var/run/renderd/renderd.sock --all --max-zoom=5 --min-zoom=5 --tile-dir=/opt/osmdata/osm/tiles/`

All logs of renderd.service:

`Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 5, number 1
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 6, number 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 7, number 3
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 8, number 4
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 9, number 5
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 10, number 6
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 11, number 7
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 12, number 8
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 13, number 9
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 14, number 10
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 15, number 11
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 16, number 12
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 17, number 13
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 18, number 14
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 19, number 15
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 20, number 16
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 21, number 17
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 22, number 18
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 23, number 19
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 26, number 20
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 27, number 21
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 28, number 22
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 29, number 23
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 30, number 24
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 31, number 25
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 32, number 26
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 33, number 27
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 34, number 28
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 35, number 29
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 36, number 30
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 37, number 31
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(5) xml(default), z(5), x(0), y(0), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(6) xml(default), z(5), x(0), y(8), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 0-7 0-7, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 0-7 8-15, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(7) xml(default), z(5), x(0), y(16), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 0 8 -> -20037508.342800|0.000000 -10018754.171400|10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 0 0 -> -20037508.342800|10018754.171400 -10018754.171400|20037508.342800 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(8) xml(default), z(5), x(0), y(24), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(9) xml(default), z(5), x(8), y(0), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 0-7 16-23, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 0-7 24-31, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 0 16 -> -20037508.342800|-10018754.171400 -10018754.171400|0.000000 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(10) xml(default), z(5), x(8), y(8), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 0 24 -> -20037508.342800|-20037508.342800 -10018754.171400|-10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 8-15 0-7, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(11) xml(default), z(5), x(8), y(16), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 8 0 -> -10018754.171400|10018754.171400 0.000000|20037508.342800 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 8-15 8-15, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 8 8 -> -10018754.171400|0.000000 0.000000|10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 8-15 16-23, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(12) xml(default), z(5), x(8), y(24), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 8 16 -> -10018754.171400|-10018754.171400 0.000000|0.000000 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming connection, fd 38, number 32
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 8-15 24-31, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 8 24 -> -10018754.171400|-20037508.342800 0.000000|-10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(13) xml(default), z(5), x(16), y(0), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 16-23 0-7, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(14) xml(default), z(5), x(16), y(8), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 16 0 -> 0.000000|10018754.171400 10018754.171400|20037508.342800 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(16) xml(default), z(5), x(16), y(24), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 16-23 8-15, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(17) xml(default), z(5), x(24), y(0), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 16 8 -> 0.000000|0.000000 10018754.171400|10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(19) xml(default), z(5), x(24), y(8), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 16-23 24-31, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 15
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 24-31 0-7, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 10, fd 15 closed, now 31 left
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 16 24 -> 0.000000|-20037508.342800 10018754.171400|-10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 24-31 8-15, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 24 0 -> 10018754.171400|10018754.171400 20037508.342800|20037508.342800 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(18) xml(default), z(5), x(24), y(24), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 24 8 -> 10018754.171400|0.000000 20037508.342800|10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(20) xml(default), z(5), x(24), y(16), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 21
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 15, fd 21 closed, now 30 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 24-31 24-31, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 23
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 24-31 16-23, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 16, fd 23 closed, now 29 left
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 24 24 -> 10018754.171400|-20037508.342800 20037508.342800|-10018754.171400 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 24 16 -> 10018754.171400|-10018754.171400 20037508.342800|0.000000 to a 8 x 8 tile
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 27
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 17, fd 27 closed, now 28 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 29
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 18, fd 29 closed, now 27 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 31
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 19, fd 31 closed, now 26 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 33
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 20, fd 33 closed, now 25 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 35
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 21, fd 35 closed, now 24 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 37
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 22, fd 37 closed, now 23 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 22
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 15, fd 22 closed, now 22 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 28
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 16, fd 28 closed, now 21 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 32
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 17, fd 32 closed, now 20 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 36
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 18, fd 36 closed, now 19 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 26
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 15, fd 26 closed, now 18 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 34
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 16, fd 34 closed, now 17 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 30
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Connection 15, fd 30 closed, now 16 left
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got incoming request with protocol version 2
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: Got command RenderBulk fd(38) xml(default), z(5), x(16), y(16), mime(image/png), options()
Feb 21 14:10:49 OSRM renderd[9970]: DEBUG: START TILE default 5 16-23 16-23, new metatile
Feb 21 14:10:49 OSRM renderd[9970]: Rendering projected coordinates 5 16 16 -> 0.000000|-10018754.171400 10018754.171400|0.000000 to a 8 x 8 tile
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 0-7 8-15
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 0-7 24-31
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 0-7 8-15 in 0.072 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/0/8) with protocol version 2 to fd 6
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 0-7 24-31 in 0.074 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/0/24) with protocol version 2 to fd 8
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 8-15 24-31
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 0-7 0-7
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 8-15 24-31 in 0.081 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/8/24) with protocol version 2 to fd 12
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 24-31 24-31
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 0-7 0-7 in 0.083 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/0/0) with protocol version 2 to fd 5
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 24-31 24-31 in 0.084 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/24/24) with protocol version 2 to fd 18
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 16-23 8-15
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 16-23 8-15 in 0.087 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/16/8) with protocol version 2 to fd 14
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 0-7 16-23
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 16-23 16-23
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 8-15 0-7
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 8-15 8-15
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 0-7 16-23 in 0.092 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/0/16) with protocol version 2 to fd 7
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 16-23 16-23 in 0.092 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/16/16) with protocol version 2 to fd 38
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 8-15 0-7 in 0.094 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/8/0) with protocol version 2 to fd 9
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 8-15 8-15 in 0.096 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/8/8) with protocol version 2 to fd 10
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 24-31 16-23
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 24-31 8-15
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 24-31 0-7
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 16-23 0-7
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 24-31 16-23 in 0.100 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/24/16) with protocol version 2 to fd 20
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 8-15 16-23
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 24-31 8-15 in 0.101 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/24/8) with protocol version 2 to fd 19
Feb 21 14:10:50 OSRM renderd[9970]: ERROR: failed to render TILE default 5 16-23 24-31
Feb 21 14:10:50 OSRM renderd[9970]:    reason: Postgis Plugin: ERROR:  column "name" does not exist
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 8-15 16-23 in 0.103 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/8/16) with protocol version 2 to fd 11
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 16-23 24-31 in 0.105 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/16/24) with protocol version 2 to fd 16
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 24-31 0-7 in 0.106 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/24/0) with protocol version 2 to fd 17
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: DONE TILE default 5 16-23 0-7 in 0.108 seconds
Feb 21 14:10:50 OSRM renderd[9970]: DEBUG: Sending render cmd(4 default 5/16/0) with protocol version 2 to fd 13
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 6
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 1, fd 6 closed, now 15 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 8
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 2, fd 8 closed, now 14 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 12
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 5, fd 12 closed, now 13 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 5
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 0, fd 5 closed, now 12 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 18
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 8, fd 18 closed, now 11 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 14
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 5, fd 14 closed, now 10 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 7
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 0, fd 7 closed, now 9 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 38
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 8, fd 38 closed, now 8 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 9
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 0, fd 9 closed, now 7 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 10
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 0, fd 10 closed, now 6 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 20
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 5, fd 20 closed, now 5 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 19
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 4, fd 19 closed, now 4 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 11
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 0, fd 11 closed, now 3 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 16
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 1, fd 16 closed, now 2 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 17
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 1, fd 17 closed, now 1 left
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Failed to read cmd on fd 13
Feb 21 14:11:00 OSRM renderd[9970]: DEBUG: Connection 0, fd 13 closed, now 0 left`

My nano /usr/local/etc/renderd.conf

```
[renderd]
socketname=/var/run/renderd/renderd.sock
num_threads=32
tile_dir=/opt/osmdata/osm/tiles
stats_file=/var/run/renderd/renderd.stats

[mapnik]
plugins_dir=/usr/lib/mapnik/3.0/input
font_dir=/usr/share/fonts/truetype
font_dir_recurse=1

[default]
URI=/
TILEDIR=/opt/osmdata/osm/tiles
XML=/opt/osmdata/osm/styles/openstreetmap-carto/style.xml
HOST=tile.openstreetmap.debian
TILESIZE=256
```

/opt/osmdata/osm/styles/openstreetmap-carto/style.xml was got by command:

`carto project.mml > style.xml`

where project.mml from [here](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml)

What's the reason? What am I doing wrong?

**Comment by pnorman** [comment]
What version of osm-carto are you using, and what version of mapnik?

**Comment by nanoficator** [comment]
> What version of osm-carto are you using, and what version of mapnik?

Carto version:
```
root@OSRM:~# carto -v
carto 0.16.3 (Carto map stylesheet compiler)
```
And Mapnik version:
```
root@OSRM:~# mapnik-config -v
3.0.12
```

**Comment by pnorman** [comment]
osm-carto requires cartocss 0.18.0 or later

**Comment by nanoficator** [comment]
> osm-carto requires cartocss 0.18.0 or later

I should have read the documentation more carefully....
Thanks a lot! Now version is 1.2.0 and it works :)
