### ISSUE TITLE
Move MSS files to their own directory

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4041]
We now have about 50 items in the root directory of the project, which is becoming unwieldy. 17 of these are MSS files.

I propose moving all the MSS files to their own directory. I'm not sure if symbols should move to that directory too. I would keep project.mml where it is.

The only con to this is that most PRs would need rebasing, so we should try to get as many merged as are ready.

If we do this, I'd like to do it before we tag 5.0.0.

**Comment by jeisenbe** [comment]
I don't have strong feelings about this change.

I am happy to rebase my own PRs if necessary. 

From what I can tell, none of the other old open PRs are likely to be updated or fixed soon

**Comment by jeisenbe** [comment]
Ok, I've tried this, and now I agree that it would be helpful. This will make it easy to search the new directory just for the `.mss` files contents. 

But what should we name the new folder?

**Comment by StyXman** [comment]
> But what should we name the new folder?

`mss`? `style`?

**Comment by HolgerJeromin** [comment]
Another candidate would be a docs directory and docker (which has a file in `scripts`, too). 
But both are not so important than the mss files...
