### ISSUE TITLE
river tunnel under a river is shown split

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#405]
http://www.openstreetmap.org/way/75255454 (river tunnel) is below (layer=-1) 
http://www.openstreetmap.org/way/3567099 (river)

as the riverbed is mapped the "crossing" is rendered strange:
http://www.openstreetmap.org/#map=19/49.01623/8.30446

**Comment by matkoniecz** [comment]
![selection_004](https://cloud.githubusercontent.com/assets/899988/16228291/7bee40a2-37b6-11e6-80fa-25a36417901a.png)
image from the linked example

**Comment by imagico** [comment]
I think this is solved since we stopped rendering waterway lines over water areas.
