### ISSUE TITLE
man_made=observatory is not rendered

### ISSUE THREAD

**Issue by dktue** [gravitystorm/openstreetmap-carto#4065]
I tagged an [observatory](https://www.openstreetmap.org/#map=19/47.26821/11.38077) but it's not being rendered (area and name-label).
![image](https://user-images.githubusercontent.com/2878623/76199439-29d39980-61f0-11ea-8ca3-ad7ffd7ba03f.png)

Are there any suggestions how we could render that?

**Comment by jeisenbe** [comment]
The `man_made=telescope` feature is rendered here already: (https://www.openstreetmap.org/node/7279177665)

I looked into the tag `man_made=observatory` when we added the rendering of `man_made=telescope`, but unfortunately it is used for a number of unrelated things:

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dobservatory
"An observatory is a location used for observing terrestrial or celestial events. Astronomy, meteorology, geophysical, oceanography and volcanology are examples of disciplines for which observatories have been constructed."

A volcano or ocean observatory is quite different than an astronomical observatory, and a meteorological observatory may only be a man_made=monitoring_station  or radar tower. 

While there is observatory:type=* for specificity, this has only been used a few hundred times.

**Comment by geozeisig** [comment]
The `man_made=observatory` is used for the institution usually a building, while `man_made=telescope` is used for the instrument itself.

**Comment by jeisenbe** [comment]
> The man_made=observatory is used for the institution usually a building, while man_made=telescope is used for the instrument itself.

In theory, but a large percentage of man_made=observatory features are not astronomical.

Right now the subtag `observatory:type` is used a little over 700 times, and the most common value is `astronomical` with about 500 uses. Most uses are in central Europe: https://taginfo.openstreetmap.org/keys/?key=observatory%3Atype#map - also note that over 100 are tagged with telescope:type, suggesting this tag is used on man_made=telescope as well as man_made=observatory - there is some confusion.

I don't think this feature is currently common enough and fully established to be supported by this style.

Note that there is also `amenity=research_institute` which could overlap with astronomical and other scientific observatories, though that tag is more vague and less common. (See #2077)

For now I will close this issue, but if this tag becomes more common and more clearly defined, we can consider re-opening it later.
