### ISSUE TITLE
Move shapefiles into database

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4089]
After having [some issues](https://github.com/gravitystorm/openstreetmap-carto/issues/4046#issuecomment-600801800) with shapefiles, sahapeindex, and differing Mapnik versions I'm wondering if we should move our shapefiles into the database. I already have code that will do this, including updating the resulting tables without downtime.

## Advantages
- Allows use of non-system Mapnik (e.g. with Kosmtik) without performance problems
- Necessary for vector tiles
- Would allow us to remove the ocean layers
- Keeps all data needed for rendering in one place

## Disadvantages
- Requires ogr2ogr
- Additional code (but already written code)

I don't know what performance differences there are. I suspect PostgreSQL is more efficient at its queries than shapefiles can be, but have no data either way.

**Comment by jeisenbe** [comment]
I assume this would require v6.0.0 since the software requirements are changing? 

Would it require a database reload?

Re: "Would allow us to remove the ocean layers" - How would this work? Would they be rendered as part of `water-areas` or a new single layer?

**Comment by pnorman** [comment]
> I assume this would require v6.0.0 since the software requirements are changing?

I don't think it has to. Versions mean what we want them to, and I could go either way on this.

> Would it require a database reload?

No.

> Re: "Would allow us to remove the ocean layers" - How would this work? Would they be rendered as part of `water-areas` or a new single layer?

As part of water-areas, which would be a UNION ALL between the osm2pgsql water and the ocean shapefiles.

**Comment by imagico** [comment]
One question would be if there are any database performance issues related to replacing several hundred megabytes of data in the postgis database on a daily basis.

The ogr2ogr/shp2pgsql dependency could be avoided by having the coastline process offer a pgsql dump in addition to the shapefiles.  Technically this is not a big thing but of course it would need to be implemented none the less.

**Comment by pnorman** [comment]
> One question would be if there are any database performance issues related to replacing several hundred megabytes of data in the postgis database on a daily basis.

I don't see any reason to expect it to cause a problem. It's a small quantity compared to the DB.

> The ogr2ogr/shp2pgsql dependency could be avoided by having the coastline process offer a pgsql dump in addition to the shapefiles. Technically this is not a big thing but of course it would need to be implemented none the less.

My only concern about ogr2ogr is that PostgreSQL 12 requires a recent version, and it's easy to get a setup where you have PG12 but not a recent ogr2ogr.

**Comment by gravitystorm** [comment]
>     * Necessary for vector tiles

This isn't entirely accurate. It's possible to generate vector tiles using shapefiles, via e.g. tilelive-bridge or tessera. It's only necessary if st_asmvt has already been confirmed as the only option. 

However, there are other things (like controlling attributes appearing in the vector tiles) that this makes easier, even with tilelive-bridge, so I would say "helpful for" rather than "necessary for".

> My only concern about ogr2ogr is that PostgreSQL 12 requires a recent version

Does `shp2pgsql` have the same problem? It appears to have a significantly simpler output that might have a better range of compatible versions.

**Comment by pnorman** [comment]
> This isn't entirely accurate. It's possible to generate vector tiles using shapefiles, via e.g. tilelive-bridge or tessera. It's only necessary if st_asmvt has already been confirmed as the only option.
> 
> However, there are other things (like controlling attributes appearing in the vector tiles) that this makes easier, even with tilelive-bridge, so I would say "helpful for" rather than "necessary for".

It's technically possible to produce a layer from shapefiles using mapnik, but then you're stuck having an ocean layer, a low-zoom ocean layer, and a water layer.

> Does `shp2pgsql` have the same problem? It appears to have a significantly simpler output that might have a better range of compatible versions.

shp2pgsql's output options are fairly limited. Whenever I've tried it in the past I ran into something I couldn't do with it, but could with ogr2ogr.

To be clear, all versions of Ubuntu, Debian, and any other OS I'm aware of come with ogr2ogr which works.
