### ISSUE TITLE
Beneficial to have the function for language selection available in Lua Script?

### ISSUE THREAD

**Issue by galewis2** [gravitystorm/openstreetmap-carto#4091]
Would it be beneficial to have the ability to select language for tags be easily available in the openstreetmap-carto base repository?

All that's needed is something like in the appropriate places:
`
different_name = nil # or "name:en"
 if different_name then
    if keyvalues[different_name] and keyvalues["name"] then
        if keyvalues["name"] ~= keyvalues[different_name] then
            keyvalues["name"] = keyvalues["name"].."\n("..keyvalues[different_name]..")"
        end
    end
end
`

Or is it preferred to keep this repo tidy? I see this as an often requested thing so I can see either way

**Comment by jeisenbe** [comment]
Related to #3870 - @pnorman, do you know if this suggestion is feasible and desirable?

**Comment by imagico** [comment]
See also #803.

**Comment by galewis2** [comment]
For example I have in lua:
```
function filter_tags_node (keyvalues, numberofkeys)
    if keyvalues["name:en"] and keyvalues["name"] then
        if keyvalues["name"] ~= keyvalues["name:en"] then
            keyvalues["name"] = keyvalues["name"].."\n("..keyvalues["name:en"]..")"
        end
    end
    return filter_tags_generic(keyvalues)
end
```
It would make sense to make this language agnostic. Working on a quick import now to demo, I will upload snapshots when it's complete

**Comment by galewis2** [comment]
![image](https://user-images.githubusercontent.com/62433564/77769636-7b668b80-701a-11ea-956a-b515d35d86e3.png)

Idea was extended upon from https://www.openstreetmap.org/user/demonshreder/diary/43956

**Comment by pnorman** [comment]
If we want to put it into the Lua file then it should be enabled by a global variable to switch it on.

I'd rather do the language conversion at generation time than when loading. Doing it when loading rules out rendering multiple languages from the one DB.

**Comment by pnorman** [comment]
> I'd rather do the language conversion at generation time than when loading. Doing it when loading rules out rendering multiple languages from the one DB.

I'm going to close it for this reason. I'd like an easier solution to changing the rendered language for forks and other deployments, but I don't think it can involve setting the language at import time.
