### ISSUE TITLE
Evaluate use of PostgreSQL JIT

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4095]
In https://github.com/openstreetmap/operations/issues/386 I encountered a problem with one of Mapnik's `LIMIT 0` queries having a high cost and use of the JIT being planned, causing the query to take a second to execute.

My development setup is not normal, so this needs testing to see if it reproduces in smaller extracts with Kosmtik, and I haven't done testing with renderd to see if it impacts a production setup.

**Comment by pnorman** [comment]
I ran benchmarks on pre-rendering zoom 0 to zoom 12, and jit off came out ahead.

Zoom 5-9 were faster with jit, but 10-12 were slower, and they're a lot more common.

**Comment by mboeringa** [comment]
Do you have any figures for this as well to share? Would be interesting to get some feeling for the actual difference.

**Comment by pnorman** [comment]
> Do you have any figures for this as well to share?

Unfortunately I don't have the raw data anymore. I think jit saved about 10 minutes for z0-z10 (out of about 120) and cost about 50 for z11-z12 (out of about 360).

It's not like the difference in development where Mapnik was issuing some queries that took 1s instead of 1ms and it was making it take ages to reload the style, but it is noticeable. 

If I get the time I'd like to see where the differences are, and run a z13-z19 workload against it. I'm extrapolating from the z0-z12 results and I feel that's safe, but I don't have a feeling for *why* it's slower.

**Comment by jeisenbe** [comment]
Is this a setting that can be turned on and off easily? 

For example, could the openstreetmap.org servers use JIT to render z0 to z9 once a month, and then switch off JIT to render z10-z19 in real time for the rest of the month?

**Comment by pnorman** [comment]
> Is this a setting that can be turned on and off easily?
> 
> For example, could the openstreetmap.org servers use JIT to render z0 to z9 once a month, and then switch off JIT to render z10-z19 in real time for the rest of the month?

This would require a renderd restart, so isn't worth it.
