### ISSUE TITLE
Render amenity=driving_school as an area

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4101]
Where I live [driving schools](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddriving_school) are massive, taking up [acres](https://www.openstreetmap.org/way/786810354) and [acres](https://www.openstreetmap.org/way/523323050).
Alas they are not even given the treatment of a parking lot, which they
98% resemble on the ground.
Instead all they get is a .
Yup, a dot.

**Comment by polarbearing** [comment]
Could somebody please change the title to "Render amenity=driving_school as an area", I think that is what jidanni means.

**Comment by polarbearing** [comment]
While the wiki page about amenity=driving_school is a bit sparse, I assume it has the perspective of mapping the school as understood as a building or shop, comprising an office and a seminar room for the theoretical lessons, and a stationary driving simulator.  After that, most business of a driving school is actually lessons in real traffic. 

The examples jidanni gives above are the training parcours for the first use of a moving vehicle, apparently. I do not see them resembling to 98% a parking lot. 

Where I live, they are typically not part of a driving school, but a separate facility, maybe the school can book time slots there. 

Similar facilities are traffic schools for children, and parcours for driver safety training. I wonder how they are tagged.

**Comment by jidanni** [comment]
OK, in some parts of the world, even for adults,
driving practice is to be done on massive closed parking lot / race courses.
In other parts of the world, the school only consists of one building,
https://github.com/openstreetmap/iD/issues/7497
and practice takes place right on real city streets. Etc.

**Comment by pnorman** [comment]
@jidanni Please avoid [unconstructive criticism](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CODE_OF_CONDUCT.md#values) and [inflammatory remarks](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CODE_OF_CONDUCT.md#summary). Messages and issue titles like the ones from you here do not help lead to a productive respectful discussion.

**Comment by polarbearing** [comment]
jidanni's simultaneous iD ticket (proposing that driving schools are not in buildings) was just declined. 

From a tag usage of 18628, 14681 are used on a node, 3875 on a way. 
2312 are used in conjunction with building=*, this is probably the majority of the ways. 

I conclude that most mappers mean the indoor facilities of a driving school. 
Thus I see no need to find an area fill for the indoor facility, and propose to decline. 

For the outdoor facility, I see that as a tagging problem, which needs to be discussed, e.g. in the proposal cited above or on the tagging list.

**Comment by imagico** [comment]
> From a tag usage of 18628, 14681 are used on a node, 3875 on a way.
2312 are used in conjunction with building=*, this is probably the majority of the ways.

Yes, the tag is predominantly used for indoor facilities.  There is neither indication that the same tag is widely used for outdoor driver training areas nor would it make much sense to use the same tag for such.

Suggest to close this unless anyone has substantial objections.

**Comment by simonpoole** [comment]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddriver_training would likely be the correct (not very popular) tag BTW

**Comment by jidanni** [comment]
(OK, but that would cause such facilities to go from being just a dot, to disappearing completely. It would be best to wait for it to be rendered before using it.)

**Comment by polarbearing** [comment]
As pointed out by jeisenbe in another issue, feel free to tag the commercial landuse of such feature. And tag correctly, you are not only tagging to get a feature rendered in Carto.

**Comment by SteveLz** [comment]
Driving schools do not always exist in the same form around the world. In East Asia, a training ground is usually included. Although `amenity=driver_training` is used now, strictly speaking, this is only a part of the driving school and cannot represent the entire driving school. Therefore, it is necessary to render the driving school by area.

**Comment by tyrasd** [comment]
I agree with @SteveLz: Driving schools which have dedicated additional facilities outside of their "building" should be mapped as an area including all respective features, just like how regular schools are mapped: the `amenity=driving_school` should encompass the whole site of the driving school. Individual features, such as the `building` and/or `driver_training` can then be mapped individually inside of its perimeter (similar how sports facilities, school yards, playgrounds and school buildings are mapped). Sure, in Europe it is uncommon to see such large driving schools, but that doesn't mean that they don't exist.
