### ISSUE TITLE
Render populated place without a name

### ISSUE THREAD

**Issue by hiddewie** [gravitystorm/openstreetmap-carto#4115]
Corresponding PR #4120.

### Expected behavior

In many areas of the world small villages have no name or an unknown name. These villages are tagged with `place` but without a `name`. These places should be rendered and be visible on the map, preferably with a small icon (a dot, a house?).

In addition to roads, showing villages makes the map more structured. I would expect that the villaged would be rendered from zoom 12 onwards (maybe depending on the.

### Actual behavior

Nothing is rendered.

At the moment, the only way view a meaningful map in those areas is to make sure every village has a mapped `landuse=residential`, and view the map at high zoom levels.

### Links and screenshots illustrating the problem

Overpass turbo link with some of these issues in Nigeria: https://overpass-turbo.eu/s/SFG

Render of the map (normally)

![image](https://user-images.githubusercontent.com/1073881/79003069-16e71880-7b52-11ea-8fd6-f23d13d83350.png)

Overpass interface, showing the missing villages

![image](https://user-images.githubusercontent.com/1073881/79002941-d4254080-7b51-11ea-8edc-09c0c8c5c012.png)

Distribution of items tagged with `place`: https://taginfo.openstreetmap.org/keys/place#values

**Comment by polarbearing** [comment]
The place key is defined as "Used to indicate that a particular location is known by a particular name". Thus the name is required in my perspective. A place without a name is a tagging mistake. 
If a village is unnamed, it would be just defined by its landuses, typically residential and farmyard.

**Comment by imagico** [comment]
I don't think there is agreement among mappers about the identity of populated places independent of their name.  The question if a certain building belongs to a certain place is usually inherently tied to the name.

The vast majority of populated places mapped without names seems to be in areas where remote mapping dominates compared to on-the-ground mapping.  It seems likely that these are predominantly not places without a name but either no distinct identity places at all or named places. Even in Africa such mapping practice seems rare in areas where local on-the-ground mapping is common.

If there is agreement among mappers on what constitutes a populated place independent of a name i would not be opposed to depict it in addition to the label (though that could be tricky cartographically).  But i don't see this being the case right now.

**Comment by hiddewie** [comment]
Interesting. The wiki seems to denote a place as *Used to indicate that a particular location is known by a particular name, to indicate what sort of "place" it is. *

However, that contradicts itself as a particular location may be known, but have no name, yet must be indicated what sort of place it is.

(I also see that the tag `name=*` is marked as required on a place)

This would indeed make missing names a tagging mistake, but removing all `place=*` without names would greatly harm humanitarian help in such areas.

Ref: https://wiki.openstreetmap.org/wiki/Key:place

**Comment by polarbearing** [comment]
I would not see any need to remove unnamed places, rather it should be an invitation to find the name eventually, sooner or later. 
This is unrelated to rendering. OSM allows me to tag a building as a node, if I don't know the outline yet, but it is not rendered here either.

**Comment by Adamant36** [comment]
> This is unrelated to rendering. OSM allows me to tag a building as a node, if I don't know the outline yet, but it is not rendered here either.

It's not a given that all places would have names that could be found eventually like it is for all buildings to have outlines that could someday be mapped though.

**Comment by polarbearing** [comment]
Why is it less likely to find a name? E.g. by going there and asking?

**Comment by jeisenbe** [comment]
I agree with the above comments: 

1) Most settlements do have a name, and if the name if missing this is usually because the area has been mapped via aerial imagery only, without local mappers or survey of the area.

The lack of rendering for the villages is a hint that the settlements still need to be mapped in that area, by survey or local knowledge.

2) It is usually not possible to guess which areas are named or not, if you have not visited the area. The size of settlements which are named seperately is determined by the culture and history of the local area, and a mapper from another region who is adding place= tags based on aerial imagery will often be mistaken.

For example, in my home-town region of the western United States, it is common for many rural settlements to have no name, since local people use the name of the nearest town to include many other small settlements. Often groups of houses will be separated by more than a kilometer but will share the same name.

In contrast, here in the mountains of New Guinea, the local people have names for very small settlements. Based on aerial imagery, prior to visiting areas in person, I guessed that one medium-sized area would share the same name, based on aerial imagery. But in fact, each small cluster of houses has it's own name, even if it is only separated from the next by 100 meters.

**Comment by Adamant36** [comment]
> Why is it less likely to find a name? E.g. by going there and asking?

Kind of for the reasons stated by @jeisenbe. Realistically your not going to hike to every little to find out the name. Nor should have to or would someone there even know the name if you did.  I'd guess with some places it's just historical and would take some major research to find. I don't think "I don't know the name right now, but someone might or might not figure it out in the future by going on a hike or digging through their locally libraries historical database" should block rendering.

**Comment by pnorman** [comment]
This would mean adding a symbol to places at high zooms. Does anyone have a suggestion on what symbols would work?

**Comment by hiddewie** [comment]
I think a filled, solid dot would be enough. If there was a larger use case, then an icon of a house would be better, but that might be mistaken for some amenity.

**Comment by jeisenbe** [comment]
A dot alone is already used for many different types of POIs, in different colors at high zoom levels. Dark gray dots are used for bollards and similar barriers.

The circled dot or an empty circle would be a possibility, but it might be hard to interpret if there is no name.

**Comment by sommerluk** [comment]
In my practical on-the-ground experience in West Africa I would say most villages have names. An all towns and cities have names. There exists however a considerable number of hamlets and isolated dwellings, that indeed have no name at all, especially when located in less developed regions. In general, I would say having no name is rather limited to rather small populated places.

**Comment by hiddewie** [comment]
I created a PR which should solve this issue for me. I chose a circle (simple SVG) of small size and with a light placename color `#777777`. This looks very well next to existing placenames. Nothing changes for the places that have a name.

Some renderings with the new style is also added.

Feedback is welcome on #4120.

**Comment by hiddewie** [comment]
Posted this question to the OSM tagging mailing list, as this may be a more conceptual tagging discussion than I had originally imagined.

**Comment by hiddewie** [comment]
Until there is concensus about the use case for places without names, this issue (rendering of said nodes) may be closed. I will also close the PR.
