### ISSUE TITLE
Road doesn't update rendering for months

### ISSUE THREAD

**Issue by AntMadeira** [gravitystorm/openstreetmap-carto#4140]
Hi there.
Although most of the elements I map or correct are updated regularly, for example, a road that I've changed from tertiary to secondary a week ago is correctly displayed on the map now, there's one road next to me that was changed many years ago from primary to secondary which remains as primary on the map, no matter the zoom level.
Is this an issue with the renderer or some mapping error that I'm not aware of?

This is the example:
https://www.openstreetmap.org/way/38460996/history
https://www.openstreetmap.org/#map=14/39.7514/-8.8453

![screen1](https://i.imgur.com/QrPTkbK.png)

Regards.

**Comment by polarbearing** [comment]
Could the reason be the route relation
https://www.openstreetmap.org/relation/6158793/history#map=15/39.7448/-8.8447
in which the old and the new segments of the EN 242 are members, and which carries a highway=primary tag itself?
I noted some double-labelling of the old segment, 'Estrada Nacional 242' from the relation, and 'Estrada da Marinha Grande' from the way, alternating.

Does a route relation need a highway tag?

**Comment by AntMadeira** [comment]
Nice catch, polarbearing!
This relation was created 4 years ago, and I searched for the problem (almost) everywhere and didn't notice that detail.
I'll inform if the render doesn't update in the next few days, but I think that's exactly it. ;)

Thank you very much!

**Comment by polarbearing** [comment]
The road turned yellow already, since you took the highway tag off the relation. 
However the old road is still a member of the EN 242 relation (see the extra loop when watching it on the OSM website). 
Would you be able to remove it from the relation in iD, or should I help in JOSM?

You might consider closing this issue since it turned out to be a tagging problem.

**Comment by AntMadeira** [comment]
I can confirm it's already yellow. 

Sorry for the off topic: I thought about removing the old road from the relation, and I know how to do it, but I couldn't find any documentation on the wiki pages on how to proceed with these cases. Do we really have to remove the old parts of a referenced road from a road relation?

**Comment by polarbearing** [comment]
Yes, but we are getting off-topic here, please find my response in 
https://www.openstreetmap.org/changeset/84645139
