### ISSUE TITLE
Failed CI/Syntax

### ISSUE THREAD

**Issue by jeisenbe** [gravitystorm/openstreetmap-carto#4142]
See https://github.com/gravitystorm/openstreetmap-carto/actions/runs/99555421

 ```
Set up xmllint 4s
   Run sudo apt-get install -qq --no-install-recommends libxml2-utils
   E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/libx/libxml2/libxml2-    utils_2.9.10+dfsg-2+ubuntu18.04.1+deb.sury.org+1_amd64.deb  404  Not Found [IP: 91.189.95.83 80]
   E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
##[error]Process completed with exit code 100.
```

This did not affect the rendering, and I don't see any changes in the code that could have caused this. Is there some problem with the linked server at ppa.launchpad.net perhaps?

**Comment by StyXman** [comment]
There is a new version, its trying to install `+1` and available is `+3`. I wonder two things:

* Maybe `apt update` should be run prior to package installation.
* Why are we using an external ppa for `libxml`? The one in the distro (I assume Ubuntu) is not enough?

**Comment by pnorman** [comment]
> * Why are we using an external ppa for `libxml`? The one in the distro (I assume Ubuntu) is not enough?

We're not specifying an external PPA, that seems to be coming from https://github.com/actions/virtual-environments/blob/ubuntu18/20200430.1/images/linux/Ubuntu1804-README.md
