### ISSUE TITLE
Add PASSWORD to get-external-data.py

### ISSUE THREAD

**Issue by zaa76** [gravitystorm/openstreetmap-carto#4144]
...
parser.add_argument("-P", "--password", action="store", help="Override database user password")
...
 psycopg2.connect(database=database,
                             host=host, port=port,  user=user, password=password) 
...
if password is not None:
                        ogrpg = ogrpg + " password={}".format(password)
...

**Comment by jacekkow** [comment]
I'd say that the password option was deliberately omitted as command line is usually visible for other system users (including a password that would be passed this way):

> Avoid passing secrets between processes from the command line, whenever possible. Command-line processes may be visible to other users (using the ps command) or captured by security audit events. To help protect secrets, consider using environment variables, STDIN, or other mechanisms supported by the target process.

Excerpt from [GitHub Actions documentation](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

Use `PGPASSWORD` environment variable instead:
```
PGPASSWORD="password-to-postgres" ./scripts/get-external-data.py -H ...
```

**Comment by pnorman** [comment]
Are you running into scenarios you can't handle with PGPASSWORD or a .pgpass file?

**Comment by pnorman** [comment]
Closing, never got an answer from the reporter.
