### ISSUE TITLE
Not rendering Devanagari on ways

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#415]
This arose during work on #414 

http://www.openstreetmap.org/way/27287354#map=16/30.0584/78.5094
![image](https://f.cloud.github.com/assets/1190866/2418588/5c108afe-ab47-11e3-96aa-6fcada2f884c.png)

Tags include ``name=गंगा``

**Comment by matkoniecz** [comment]
Is it also fixed by Mapnik 3 like #392?

**Comment by pnorman** [comment]
presuming fixed, have no where to verify right now.
