### ISSUE TITLE
Add rendering for deforestation areas (man_made=clearcut)

### ISSUE THREAD

**Issue by GunSmoker** [gravitystorm/openstreetmap-carto#4159]
Currently man_made=clearcut is not shown.

For example, OsmAnd renders these areas as stumps/stubs. See attached image.

![Screenshot_2020-06-10-16-20-24](https://user-images.githubusercontent.com/3242603/84273429-5375c700-ab37-11ea-93a4-83a8a3cce42a.png)

Adding natural=scrub is an option when deforestation area starts to regrow, but it looks wrong when such area has only grass and stumps.

![DSC01036](https://user-images.githubusercontent.com/3242603/84273617-8d46cd80-ab37-11ea-97eb-3ec88d9f9cc0.JPG)

**Comment by GunSmoker** [comment]
@jeisenbe I am not familiar on how this work technically. But it isn't it the same issue with scrubs in forests? Or swamps inside scrubs/forests? After all, if there is a conflict, nothing stops one from fixing it or creating a different layout?

Is there a way to check how much man_made=clearcut overlaps with other areas?

**Comment by Adamant36** [comment]
> Is there a way to check how much man_made=clearcut overlaps with other areas?

I'm not sure if it's exactly what your looking for, but you can do an OverPassTurbo query to find objects that are inside of other objects. The first tag is the larger area and the rest is the tag for the smaller area inside of it. 

http://overpass-turbo.eu/s/V3r

**Comment by matkoniecz** [comment]
Case such as https://user-images.githubusercontent.com/3242603/84273617-8d46cd80-ab37-11ea-97eb-3ec88d9f9cc0.JPG can be mapped by editing forest area to not include it.

Mapping it would not take more effort than mapping `man_made=clearcut`.

> A 10 year old man_made=clearcut could already have 5 meter tall trees in some climates, though it would likely remain distinguishable from the taller surrounding trees.

+1

If you want to map that forest was cut down and is not existing in this area? Edit forest area to exclude this.

> Adding natural=scrub is an option when deforestation area starts to regrow

Is later an option.

**Comment by matkoniecz** [comment]
> But it isn't it the same issue with scrubs in forests?

I such cases scrubs are usually not mapped.

> Or swamps inside scrubs/forests?

This is solved by wetland styling selected in way that works well when overlaid on typical surroundings.

**Comment by Adamant36** [comment]
>  Adding natural=scrub is an option when deforestation area starts to regrow

Isn't there sort of a difference traditionally between a scrub plant and a tree planting that is in the process of growing? I would imagine they are technically different things and I wonder how someone could tell the difference from a satellite photo alone.

**Comment by matkoniecz** [comment]
It is not a very big issue, as (at least in some climates) initially it will be combination of small trees and scrub plants.

> I wonder how someone could tell them apart from a satellite photo alone.

Yes, mapping solely from aerials/satellite images has its limitations.

**Comment by GunSmoker** [comment]
@matkoniecz Perhaps, I was not clear. man_made=clearcut is already excluded. 

The issue is that blank space does not represent what is there, while stumps pattern (as is in OsmAnd app) is a clear indication what you can expect from this area: it is not a clearing in the forest.

**Comment by GunSmoker** [comment]
BTW,

> A 10 year old man_made=clearcut could already have 5 meter tall trees in some climates, though it would likely remain distinguishable from the taller surrounding trees.

Many of landuse=farmland in my area are natural=scrub already (e.g. abandoned). However, it does not mean that I should map unmapped farmland as scrub, thinking "oh, it will probably be scrub here in 10 years or so anyway". WHEN farmland becames scrub - only then can one edit tags to reflect that.

It is the same for natural=scrub growing into natural=wood. You map area as natural=scrub, and if/when it grows into forest - only then you change tags to natural=wood.

Why it should not be the same for clearcut? Yes, it MAY be forest in 15 years, but it also may be not. If man_made=clearcut will grow into something different - then change the tags for this area. But if it did not grow - leave tags out, let it render as clearcut.

**Comment by matkoniecz** [comment]
> while stumps pattern (as is in OsmAnd app) is a clear indication what you can expect from this area: it is not a clearing in the forest.

The problem is that clearcut may be field of stumps, but it may be also a construction site, field, scrubs, small trees etc

see https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dclearcut

> former landuse=forest or natural=wood areas, where most or all trees are uniformly cut down (...) If there is vegetation present, add a suitable tag such as natural=scrub for bushes, shrubs and very small trees (transitional scrub) or landuse=meadow for grasses and herbs (transitional meadow). See vegetation for more options. 

(if real usage is different the this page should be changed)

**Comment by GunSmoker** [comment]
@matkoniecz Why is this a problem? AFAIK, OSM follows "map what's on the ground" principle, and you should not map historic events and historic features. Which means if clearcut is occupied with something else - you should map this "something" instead.

**Comment by jeisenbe** [comment]
> If clearcut is occupied with something else - you should map this "something" instead.

Right. You can map the grass or shrubs with an appropriate tag. There might be a few months (especially if the clear-cut happens before winter or before dry season) when there is no vegetation, but generally within 9 to 12 months there will be grass or small bushes growing.

I don't think rendering the presence of tree stumps is relevant for a general-use map audience.

**Comment by jeisenbe** [comment]
Note that `landuse=logging` is a more common tag for areas where trees have been cut (though ti is somewhat less specific in theory): https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dlogging 

Since neither `man_made=clearcut` or `landuse=logging` are clearly established as the preferred tag, and the actual vegetation of the area can be mapped with landuse=meadow or natural=scrub (or natural=heath), I recommend closing this issue for now.

In the future if one of the two tags `man_made=clearcut` or `landuse=logging` become well-defined and clearly established, we might consider this issue again, though I'm inclined to think that this information is not relevant for a general-use map based on the current mapping practices.

**Comment by GunSmoker** [comment]
OK, but I just want to note that rendering clearcuts as suggested above does not create any issues in OsmAnd.
