### ISSUE TITLE
Telephone mounted on wall not getting rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4162]
Telephone on wall not getting rendered:
https://www.openstreetmap.org/node/7620863051

Telephone in booth getting rendered.
https://www.openstreetmap.org/node/5549120589

Well if the telephone is mounted on a wall, what
makes more sense than making it a node on that wall?

**Comment by polarbearing** [comment]
I don't think we have a rule here about booth or not, or wall or not. This appears simply as a matter of the first example being blocked by the other icon and label. 
Thus it is among the dozens of simple blocking issues that you already reported here. 
Proposing to close.

**Comment by jidanni** [comment]
OK, I'll make a note on https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dtelephone .

**Comment by polarbearing** [comment]
In OSM Carto, is is the general case that two icons cannot be rendered in the same place, i.e. one blocks the other. It is pointless to annotate this behaviour in the wiki at any feature that could have an icon.

**Comment by jidanni** [comment]
I would argue that just like sesame seeds in a porridge, they all find
ways to slightly move over so they all can be accommodated on the top.
If it is a building edge that is the problem, a break in the wall can
be made (keeping the background color constant though.) Otherwise
e.g., a town with 10000 buildings and only one public phone will have
this important amenity gobbled up and gone. Same with a rural area with only
one building and one phone, or drinking fountain, etc. important (or
not so important to some people on some days) amenities.

If they really need to move over too far, then little stalks / arrows
can be added, as is the common cartographic practice.

**Comment by jidanni** [comment]
Also, the only thing that's going to load up with the map with too many items in a too-small small area would be some automated editing. We human mappers couldn't even put too many things in small places in the editor anyways.

**Comment by jidanni** [comment]
#4163
