### ISSUE TITLE
Add extender arrows for rich cartographic detail in dense places

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4163]
![P_20200616_161152_vHDR_On_1](https://user-images.githubusercontent.com/1230959/84751628-5c5f1080-afef-11ea-85e3-f9afc8819666.jpg)
With extender arrows, rich cartographic detail in dense areas would now be possible.

Here we even see how multiple floors in one building could be treated with a shared extender arrow:
![P_20200616_160956_vHDR_On_1_1](https://user-images.githubusercontent.com/1230959/84751856-a2b46f80-afef-11ea-92ed-c0eac846f437.jpg)

Not only points of interest, but also regular street names could also be facilitated  in areas of high road density:
![P_20200616_161250_vHDR_On_1](https://user-images.githubusercontent.com/1230959/84752200-063e9d00-aff0-11ea-8c35-1aae31c60b21.jpg)

**Comment by jidanni** [comment]
The algorithm could be simple: simply sweep around in 360 degrees looking for gaps. Do this with a wider and wider radius. Now compare all the gaps we found and simply choose the largest one to fill in our object name and then add the extender arrow pointing to the object!
 if more than one object then simply compute the space is needed for two objects etc.

**Comment by jidanni** [comment]
The example images I have posted above all relevant to City centers of small villages and towns. 

In large cities with kilometers in kilometers of dense information, I'm afraid the above is not possible.

So the algorithm will need some safety checks.  Give up if needing to go beyond 300 meters etc.

**Comment by imagico** [comment]
This is not feasible for a real time updated tiled map at this time.

I am also not aware of any current tiled maps that practically use fully automated methods for that - this is a very hard task technically.  Even basic labeling with alternative positions is hard to do in a tiled map and often done rather suboptimally - this would add a whole additional level of complexity to that.  Examples of this being tried would be most welcome.

**Comment by jidanni** [comment]
The examples are in the images I posted.

They are not necessarily generated by hand editing...

**Comment by jidanni** [comment]
This was intended as a long-term wish list item.

There is no worry that editors could feeling too many points of interest that could not be placed on the maps. The only worry is automatic editors. This is because within JOSM or iD one couldn't stuff too many points in anyway without noticing the crowding.

**Comment by HolgerJeromin** [comment]
We use mapnik as a rendering engine. 
This software has to support this feature. 
If not, this wish list item could never be fullfilled.

It would be right overthere in https://github.com/mapnik/mapnik but they have 550+ open items. I am not sure if they want to have such an long-term wish list item in there issue tracker.

**Comment by imagico** [comment]
The examples you showed are from a classical non-tiled, non-interactive not real time updated map and show plenty of evidence of manual label and symbol placement.

**Comment by jidanni** [comment]
Tiles could be updated and cached upon closing edits, not later upon browsing requests.

**Comment by HolgerJeromin** [comment]
> Tiles could be updated and cached upon closing edits, not later upon browsing requests.

This would would change nothing concerning this issue (and result in horrible performance).
This is an operational idea not an idea for this repository.

**Comment by Adamant36** [comment]
IMO the solution is rendering POIs at z20. Doing so would solve a lot of these types of issues that keep popping up.
