### ISSUE TITLE
Roundabout name is not displayed because it's too long

### ISSUE THREAD

**Issue by maro-21** [gravitystorm/openstreetmap-carto#4166]
Example 1:
https://www.openstreetmap.org/way/190721339
![example1](https://user-images.githubusercontent.com/57260466/84955031-d0381080-b0f6-11ea-94d5-ea598387b1df.png)

This roundabout had to be split due to bus routes, so if it was in one piece, it would probably be rendered correctly.

But it's a general issue with street names, not only roundabouts.

Example 2:
[327856867](https://www.openstreetmap.org/way/327856867) + [312911913](https://www.openstreetmap.org/way/312911913) + [312911914](https://www.openstreetmap.org/way/312911914) + [22769131](https://www.openstreetmap.org/way/22769131)
![example2](https://user-images.githubusercontent.com/57260466/84955163-0aa1ad80-b0f7-11ea-9012-b5522b7ddaeb.png)

This is one street in four pieces but had to be split because of different tags. There is enough space for the street name so it should be rendered.

### Actual behavior
The name of a street is not displayed if the street is in small pieces.

### Expected behavior
Display street names regardless split street. If connected ways have the same name, treat them as one feature and display the name.

**Comment by polarbearing** [comment]
IIRC there is another issue where (shorter) names are shown too frequently because the roads are split. 
If we had a method to join road segments with the same name+classification, this would fix both.

**Comment by polarbearing** [comment]
Related to #951 (Segmented roads lead to too high or too low density of shields and names). 
Probably duplicate, as no name is a special case of too low density.

**Comment by jeisenbe** [comment]
Thank you for reporting this issue, @maro-21. As mentioned above, this problem was already reported in #951. Please continue the discussion there.
