### ISSUE TITLE
Road shield blocks highway=mini_roundabout

### ISSUE THREAD

**Issue by Prince-Kassad** [gravitystorm/openstreetmap-carto#4167]
Example illustrating the problem:

https://www.openstreetmap.org/#map=19/49.15015/7.77923&layers=N

highway=mini_roundabout should have priority over everything else since it's a road feature, yet the road shield can block it.

![mini_roundabout](https://user-images.githubusercontent.com/48839736/85235015-f7058800-b411-11ea-8dec-1f688213c3c2.png)

**Comment by imagico** [comment]
Yes, mini roundabouts are rendered as low priority blocking POIs.

A possible solution would be to rendering this in a non-blocking fashion immediately after the roads layers.  Would need to be tested for feasibility though.

Another option - which i think i'd kind of favor - would be to render them like `highway=turning_circle`, maybe with a minor design variation to indicate the difference in tagging - see

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dturning_circle
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmini_roundabout

Physically these are very similar and the difference largely comes from context - which is visible in the map.

**Comment by jeisenbe** [comment]
Re: "render them like highway=turning_circle, maybe with a minor design variation to indicate the difference in tagging"

I agree with this idea. Physically they are nearly identical to turning circles, so including a minor design variation seems not strictly necessary, though if it's possible to render a small circular gray dot in the center that could look nice.
