### ISSUE TITLE
rendering of mimics and concealed items

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4173]
If A [mimics](https://wiki.openstreetmap.org/wiki/Key:mimics) B, then rendering it as A is not entirely correct, nor is rendering it as B. So maybe render A on top of a transparent B, etc.

So for e.g., a [cell tower mimicking a water tank](https://wiki.openstreetmap.org/wiki/File:Phony_water_tank_real_cell_tower.jpg) perhaps render it as a hollow/transparent water tank, with a cell tower inside/overprinted.

We also [read](https://wiki.openstreetmap.org/wiki/Key:mimics) about
> …when communications infrastructure is hidden within an existing structure that serves the function it appears to, i.e., cellphone technology enclosed within an existing church steeple does not mimic the steeple and should be tagged with tower:construction=concealed.

Well in this case we could render both items side by side. That would be correct for the steeple, but not entirely correct for the cell tower. So maybe use a *semi*-transparent steeple enclosing a cell tower in this case. (Sure, one might say well we only map what is on the ground, and not things we can't see. But the map would be much less valuable that way... And just like when fog lifts, or a fence is removed, there the item is behind it.)

Yes, our tags aren't big enough to fit inside each other currently. I'm just saying some thought needs to be done about how to deal with mimics and concealed items.

**Comment by polarbearing** [comment]
```mimics``` is used 66 times so far, thus there is no need to discuss such fancy ideas for a couple of years. 

Further, a communication tower should be rendered as a communication tower, regardless what it mimics. I find the additional information about mimicking interesting, but unsuitable for the general style. 

Proposing to decline.

**Comment by jidanni** [comment]
Well if people _see_ a water tank, but the map shows a communication tower, then they will "correct" the map to show a water tank.

So at least an asterisk should appear next to a mimicked object.

**Comment by pnorman** [comment]
> `mimics` is used 66 times so far, thus there is no need to discuss such fancy ideas for a couple of years.

Yes, we're not going to add code for something that occurs so infrequently.

**Comment by jidanni** [comment]
Ah, that is because most people don't possess the _X-ray eyes_ to detect the mimics!
