### ISSUE TITLE
Render incline on roads

### ISSUE THREAD

**Issue by j47996** [gravitystorm/openstreetmap-carto#4180]
Ordnance Survey (UK) maps mark inclines with a chevron pointing uphill for 14% - 20%, double for 20% +

**Comment by polarbearing** [comment]
Can you explain how that is mapped, how often, and how the percentage is measured in OSM?

**Comment by HolgerJeromin** [comment]
https://wiki.openstreetmap.org/wiki/Key:incline

https://taginfo.openstreetmap.org/keys/incline

**Comment by jeisenbe** [comment]
The key "incline=*" has been used 600k times, but 80% are the value "up" or "down", which does not specify how steep of an incline is involved. 

The next most common value is "0%" with 22k uses, followed by "10%" with 12k uses, "15%" with 6k and "20%" with 4k. There are about 50k which have a non-zero numerical value with a %:  https://taginfo.openstreetmap.org/keys/incline#values

Of those with `incline=10%`, there are 4897 ways with `highway=path`, `=footway`, `=cycleway`, `=steps` or `=bridleway`: https://overpass-turbo.eu/s/VVY - so over 1/3rd are types of paths: https://overpass-turbo.eu/s/VVZ

And there are 4135 `highway=track` with incline=10% - which are also rendered in a similar manner, in this style (https://overpass-turbo.eu/s/VW0).

So if we focused on paths and tracks, we might find 30k or more features which could have a rendering based on incline >9% (or perhaps >6%?).

Would that be worth considering?

**Comment by mboeringa** [comment]
> So if we focused on paths and tracks, we might find 30k or more features which could have a rendering based on incline >9% (or perhaps >6%?).

Nice analysis, but I think it is not logical to focus on paths and tracks. A lot of paths in mountain regions will have incline >10% and are only accessible on foot, which everyone knows and is therefor largely non-information.

This information is most useful for roads accessible by car, to know if e.g. a heavily loaded truck will encounter a non passible road with an incline to steep to take.

So instead of paths and tracks, I would render this stuff on roads of type "unclassified" up to "primary" or possibly "trunk" (motorway should always be accessible to any type of motorized vehicle, so rendering it there isn't useful).

**Comment by jragusa** [comment]
I'm following @mboeringa to render them only on roads where you can found dedicated traffic signs in several European countries (for example: https://fr.wikipedia.org/wiki/Panneau_de_signalisation_de_descente_dangereuse_en_France#/media/Fichier:France_road_sign_A16.svg).

At least in France and Switzerland, these traffic signs are present when slope exceeds 10% (4% for motorways and trunks in France) and possibly less in Germany.

**Comment by j47996** [comment]
Just roads would suit me.

**Comment by jeisenbe** [comment]
Looking at highway=motorway/trunk/primary/secondary/tertiary/unclassified/residential, there are 2691 features with incline=10%, and there are 495 highway=service with this value: so this information is more common on paths and tracks. 

There might be 15k or 20k roads (excluding tracks) with` incline >= 10%` - is that common enough to be worth rendering?

As a bike rider I'm much more interested in the incline of roads compared to when I'm driving a car. If one is driving a HGV or bus you would want to avoid roads with steep inclines, but in personal motor vehicles it is not so significant.

**Comment by polarbearing** [comment]
The last argument by @jeisenbe is an important point: we are a general interest map, and should not focus on one particular traffic class. There are other maps and routers that do that. 
Cyclemap already renders contour lines (from a different source), routers can avoid roads which are unsuitable for a particular vehicle type. 
If we'd start rendering incline, we would also need to render maxheight and maxwidth, which are even more critical to decide if a road is passable. 
We should focus on general-interest symbols on roads, such as access and surface.

**Comment by imagico** [comment]
We have had the discussion on if it is even possible to render both road surface type and access restriction at the same time in this style (#3399/ #4137).  Adding yet another subclassification of roads seems out of the question.

Therefore closing this as very unlikely to gather sufficient support or a viable styling idea.
