### ISSUE TITLE
Rendering healtcare tags wihtout icon with a generic one (dot)

### ISSUE THREAD

**Issue by deuzeffe** [gravitystorm/openstreetmap-carto#4183]
Hello,

Could all healthcare tags without a dedicated icon have a red dot, like shops without an icon have a purple dot?

Thank you for whatever the answer is.

**Comment by HolgerJeromin** [comment]
I think the amount of valid healthcare tags is be a smaller that shop tags.
Look at the very long tail of values at
https://taginfo.openstreetmap.org/keys/healthcare#values
only 25 tags are used by more than 100 objects in the database.

**Comment by imagico** [comment]
We don't want to introduce a new catchall for healthcare tags while we are trying to get rid of it for shops in #3730.

Regarding healthcare tag rendering - see #1981, #3731.

Rendering specific broadly accepted healthcare tags is of course a possibility - you should open new, distinct issues for such.
