### ISSUE TITLE
Support amenity=research_institute

### ISSUE THREAD

**Issue by Simon0Harms** [gravitystorm/openstreetmap-carto#4185]
### Expected behavior
Show the (Short) Name of a  Research Institute
### Actual behavior
You have to bypass by using e.g. landuse.
### Links and screenshots illustrating the problem
Was discussed here (german):
https://forum.openstreetmap.org/viewtopic.php?pid=796166#p796166

**Comment by imagico** [comment]
Duplicate of #2077.
