### ISSUE TITLE
get-external-data.py

### ISSUE THREAD

**Issue by corcrea** [gravitystorm/openstreetmap-carto#4186]
### Expected behavior
Hello,

I'm stuck at the style file stage, some data has been inserted in the database. I don't know what to do. Thank you in advance.

PS: this is my first github ticket, sorry if I forgot important information.

### Actual behavior
![image](https://user-images.githubusercontent.com/69316403/89553922-73abc480-d80e-11ea-945e-a1a39d4f5054.png)

**Comment by pnorman** [comment]
Does the ogr2ogr command given on line 3 of the output work when run by itself?

**Comment by corcrea** [comment]
![image](https://user-images.githubusercontent.com/69316403/89619241-ed36c780-d88d-11ea-85e4-2f27d15579d3.png)

The command is executed via the renderaccount user.
I followed the tutorial available at https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/.

Thanking you in advance, we thank you in advance.

**Comment by corcrea** [comment]
![image](https://user-images.githubusercontent.com/69316403/89619504-54ed1280-d88e-11ea-8776-86679494dff7.png)
 result of the same command with the option "skipfailures".

**Comment by pnorman** [comment]
Your system has managed to get an ogr2ogr version that doesn't work with the postgresql you're connecting to. What does ogr2ogr --version report?

**Comment by corcrea** [comment]
Hello,
I've given up trying to find a solution to this problem.
So I switched back to a version 11 of postgresql that doesn't cause a problem.
I followed this tutorial: 
https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/

Thanking you,
Sincerely
