### ISSUE TITLE
Give highway=bus_stop priority over amenity=shelter

### ISSUE THREAD

**Issue by maro-21** [gravitystorm/openstreetmap-carto#4188]
I think bus stop's names and `highway=bus_stop` should have priority over `amenity=shelter`.
For me the bus stop or the name of a bus stop is more important than a shelter.

I've recently changed public transport shelter's tagging from `building=yes` to `amenity=shelter`+`shelter_type=public_transport` and the name of the stop stopped rendering. On lower zooms there isn't a bus stop icon at all.

Currently shelters render at zooms 16-19 but I don't think they're so important features to do it so.

### Examples
![osm carto amenity shelter building](https://user-images.githubusercontent.com/57260466/90066627-47041b00-dcee-11ea-977d-28d19c0bb20e.png) ![osm carto amenity shelter building 2](https://user-images.githubusercontent.com/57260466/90066639-4a97a200-dcee-11ea-9546-7d4cadf0af4a.png)
![OSM Carto bus stop priority](https://user-images.githubusercontent.com/57260466/90066710-613df900-dcee-11ea-8d8a-9bea94f07bc3.png)

https://www.openstreetmap.org/node/1701715493
https://www.openstreetmap.org/node/1701723143

### Current behavior
The amenity=shelter has priority over highway=bus_stop.

### Expected behavior
Render highway=bus_stop over amenity=shelter.

**Comment by Adamant36** [comment]
This is kind of a duplicate of #2431 and #3483. From what I remember a possible solution besides tweaking the rendering levels was floated in #3124. Although, it never went anywhere. It's not clear that changing rendering levels would help any. So, this might be a good candidate for z20 if it ever happens. I guess shelters could stop being rendered if tagged with shelter_type=public_transport, but that seems like an odd solution. I imagine people would want to know which bus stops have shelters when they are looking at the map.

**Comment by matkoniecz** [comment]
Very similar to #4179

**Comment by jeisenbe** [comment]
Thank you @maro-21 - this issue is a duplicate of #2431 but it is a good idea. \

This whole issue of prioritization is also discussed more generally in #3880 where it is suggested that priority should be related to initial zoom level (though in this case both icons are first rendered at z16)

**Comment by jeisenbe** [comment]
Please discuss further at #2431
