### ISSUE TITLE
Add rendering for amenity=waste_disposal

### ISSUE THREAD

**Issue by NikolasHuan** [gravitystorm/openstreetmap-carto#419]
Popular tag is not rendered on the map.
 Please add this tag.

http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_disposal

**Comment by matkoniecz** [comment]
I think that it should not be rendered. At least in Poland for medium sized/volume waste each residential building has its associated amenity=waste_disposal.

**Comment by kocio-pl** [comment]
But that buildings could have the icon - at least at z=max. I also think garages could have their own icon on highest zoom level.

**Comment by matkoniecz** [comment]
Main problem is not fitting icons for next feature appearing everywhere (though it may also be a problem), but that such icons would not provide any useful information.

Maybe situation is different in other countries.

**Comment by kocio-pl** [comment]
I think on micromapping level (and I take it cautiously only as z=max for now to test the idea) I'd like to know what given building is for - just like we see multi-storey parking buildings with a "P" icon on top on the middle zoom level.

**Comment by dieterdreist** [comment]
2015-03-15 13:14 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> At least in Poland for medium sized/volume waste each residential building
> has its associated amenity=waste_disposal.



can this generally be used or is it for the residents of the building only?
If it's the latter this tag doesn't apply I think.
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_disposal

**Comment by matkoniecz** [comment]
> If it's the latter this tag doesn't apply I think.

The latter. Current definition is not making clear is it applicable what is making it even worse - my initial impression was that it intends to map private waste collection points (where waste is picked up by garbage trucks). Also, that is how this tag seems to be used (other usage in Poland also indicates mistagging and using it instead of amenity=waste_basket).

**Comment by dieterdreist** [comment]
2015-03-16 10:45 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> my initial impression was that it intends to map private waste collection
> points



this is in the amenity namespace, so generally "Covering an assortment of
community facilities including toilets, telephones, banks, pharmacies and
schools." (from the amenity key definition) -> private objects are out.
OK, to be fair, our wiki has become sort of a bible, you can also find
another short definition on the same page (green box on the right: "For
describing useful and important facilities for visitors and residents.") ->
private objects are in.
http://wiki.openstreetmap.org/wiki/Key:amenity

**Comment by kocio-pl** [comment]
@dieterdreist You're right and also:
1. We already show private parkings.
2. We are not sure what are the status of this tag (public or private).

I think at z>=19 it's good to see what's around (the same with garages or power substations, but we don't have special icons yet) and at this level it wouldn't be intrusive at all, even for visitors, so it seems to me like a safe choice.

**Comment by matkoniecz** [comment]
Given that it is not even clear how this tag is supposed to be used I propose o not render this tag.

**Comment by math1985** [comment]
> Given that it is not even clear how this tag is supposed to be used I propose o not render this tag.

A couple of months ago, I have clarified the wiki for all garbage related items. Is there something still unclear about the purpose of this tag?

I'd be in favour of rendering the tag, but only on the highest zoom levels - if only for preventing mistagging.

Blocks of flats often have these objects. 
Other picture: http://denhaagfm.nl/wp-content/uploads/2013/11/ORAC-2.jpg
Note that these are meant for household garbage bags, not icelolly-sticks of passerbys.
Maybe I should replace the picture in the wiki.

**Comment by matkoniecz** [comment]
Mostly http://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dwaste_disposal#confusing (initially I thought that it obviously includes completely private locked-up collection points but for example in this thread some people expected private collection points to be excluded).

**Comment by matkoniecz** [comment]
Also, I still think that even at the highest zoom level it will clutter map too much for such low-importance object. See for example http://overpass-turbo.eu/s/ePU

![selection_002](https://cloud.githubusercontent.com/assets/899988/13574426/59c97328-e484-11e5-80d7-18f06e63d93e.png)

**Comment by math1985** [comment]
I see what you mean. Does it differ from garbage bins?

**Comment by matkoniecz** [comment]
Yes, it is waste basket on the bottom of garbage chute and a waste basket for some dry recyclables (paper, plastic, metal). It is behind doors, accessible for residents and garbageman.

https://www.google.pl/maps/@50.0798803,19.8855599,3a,43.8y,222.83h,86.08t/data=!3m6!1e1!3m4!1sV8NqSWeRRx0FZ_ffqdh-GQ!2e0!7i13312!8i6656?hl=en

![selection_003](https://cloud.githubusercontent.com/assets/899988/13575057/2ddcf610-e487-11e5-84d8-d842494a15c3.png)

It gets worse in some places with every single house having its own space for garbage - see for example https://www.google.pl/maps/@50.1037354,19.9413231,3a,75y,26.39h,81.24t/data=!3m6!1e1!3m4!1s3gc8NsjBE1ba0XYHgQJvRw!2e0!7i13312!8i6656?hl=en

![selection_004](https://cloud.githubusercontent.com/assets/899988/13575137/84eaf466-e487-11e5-9ad7-f1f3f614a1d6.png)

I guess that it strongly depends on local tradition but at least in Poland it would introduce massive amount of things that are completely unnoticed and unimportant - as it this kind of infrastructure that nobody notices till it is working properly.

IIRC from reading tagging mailing list for example in rural Japan there is typically one bigger collection point for multiple houses so for local/specialistic maps it may make sense to render this object - but here I am pretty sure that it would be a poor idea.

**Comment by kocio-pl** [comment]
The question is how worse is this than garbage bins we already have on z19?

**Comment by Tomasz-W** [comment]
@matkoniecz I'm not sure is the first example a correct tagging. As we don't map steps, bicycle stands, elevators etc. inside buildings, I'm not sure about mapping waste disposal nodes if they are hidden behind doors inside residential building. 
The second one in very rare, I think. Why would somebody map someone's private little waste disposal place?  (if you have examples of massive amount of amenity=waste_disposal in some single-family houses district, please paste it here)

For example: this is one of polish block-housing districts, and as you can see, there is not that much of waste disposals. It won't make map cluttered.
https://overpass-turbo.eu/map.html?Q=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A“amenity%3Dwaste_disposal”%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20%2F%2F%20query%20part%20for%3A%20“amenity%3Dwaste_disposal”%0A%20%20node%5B"amenity"%3D"waste_disposal"%5D(52.37444640263532%2C16.933107376098633%2C52.39875308009566%2C16.994175910949707)%3B%0A%20%20way%5B"amenity"%3D"waste_disposal"%5D(52.37444640263532%2C16.933107376098633%2C52.39875308009566%2C16.994175910949707)%3B%0A%20%20relation%5B"amenity"%3D"waste_disposal"%5D(52.37444640263532%2C16.933107376098633%2C52.39875308009566%2C16.994175910949707)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20body%3B%0A>%3B%0Aout%20skel%20qt%3B
I would like to see other examples in different conditions - tenement houses districts, single-family houses districts etc.

**Comment by matkoniecz** [comment]
> we don't map steps, bicycle stands, elevators etc. inside buildings

Since when? Not mapping building passages like http://www.openstreetmap.org/?mlat=50.08150&mlon=19.88193#map=19/50.08150/19.88193 would be weird. 

There is also no good reason to not map bicycle parkings that are under roof (or in their own building). There is even tag to specify that bicycle parking is in the building (bicycle_parking = building https://wiki.openstreetmap.org/wiki/Key:bicycle_parking ).

>  Why would somebody map someone's private little waste disposal place?

For similar reasons as people map sometimes every single tree in park, map roads as areas (area:highway) or try to map every single bicycle parking in the city (together with its properties). Reasons include [completionism](https://en.wiktionary.org/wiki/completionism), interest in a given feature or to make further mapping easier (tagging it explicitly notes what is in a given building - for example I mapped man_made=street_cabinet in some places to make mapping and interpretation of aerial images easier).

**Comment by Tomasz-W** [comment]
> Not mapping building passages like http://www.openstreetmap.org/?mlat=50.08150&mlon=19.88193#map=19/50.08150/19.88193 would be weird.

It's completly different thing than thing I mentioned. Of cource we map building passages, but do we map building corridors as footways?

> There is also no good reason to not map bicycle parkings that are under roof (or in their own building). 

It's also different thing. These are separate buildings, which only function is to be a bicycle parking. Your example was presenting a waste disposal nodes inside bigger, residential building.

> For similar reasons as people map sometimes every single tree in a park, map roads as areas (area:highway), map every single barrier=gate, including ones on footways to private homes, or try to map every single bicycle parking in the city (together with its properties)

Yes, that's true, but you still didn't give me an example of massive-mapped waste disposals, one by one, side by side, so in case of amenity=waste_disposal it's still just your theory.

**Comment by matkoniecz** [comment]
> do we map building corridors as footways?

In some places people do that - http://www.openstreetmap.org/#map=19/50.06758/19.94689

**Comment by matkoniecz** [comment]
>  in case of amenity=waste_disposal it's still just your theory

Map style should not really on "we will display feature and hope that nobody will map all instance of it".

**Comment by l29ah** [comment]
On Tue, Jul 25, 2017 at 04:04:45PM +0000, Mateusz Konieczny wrote:
> >  in case of amenity=waste_disposal it's still just your theory
> 
> Map style should not really on "we will display feature and hope that nobody will map all instance of it".

Somehow you don't argue this way against building entrances, benches, trees, shops and bus stations. It is unreasonable to ignore any kind of accepted OSM amenities just because it might someday clutter some view of some area, and it's the tag placing policy to be discussed (in the OSM wiki?) rather than rendering style to avoid trivial/useless instances of the tag. Several tag descriptions already note when an item shouldn't be placed, and it apparently works.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by matkoniecz** [comment]
> Somehow you don't argue this way against (...) benches, trees, shops and bus stations.

In all cases where I made/tested PRs with this changes I tested how it will work also in area with high density of this kind features. In cases where I commented on issues I also considered (among other issues) rendering in high density areas.

> building entrances

I may not remember correctly but IIRC I never did anything related to rendering that feature.

**Comment by Tomasz-W** [comment]
@kocio-pl Could you make a test rendering with this icon:

![amenity waste_disposal2](https://user-images.githubusercontent.com/25656654/32142363-7710fd3e-bc96-11e7-9366-c006d5c36cf9.png)
14x14:
![amenity waste_disposal](https://user-images.githubusercontent.com/25656654/32142365-7b945806-bc96-11e7-97c0-6cf5828bd02b.png)

**Comment by kocio-pl** [comment]
It's not recognizable for me at 14 px. I think wheels and a space under the cover should be bigger. 

It may be still better to make it even smaller than 14 px, because it's solid shape and can easily take too much attention.

**Comment by matkoniecz** [comment]
In case of somebody making pr - please, test it also in high density stress and consider not rendering private waste_disposal

**Comment by Tomasz-W** [comment]
I changed it due to @kocio-pl notices. I think it's all what we could get from big wheelbin shape. Another option is a container icon, but I have no idea how to transform it to a vector 
https://static.turbosquid.com/Preview/2014/05/27__02_06_46/1.jpg3b98edec-403f-421b-bc30-35029a66bafdOriginal.jpg

![amenity waste_disposal2](https://user-images.githubusercontent.com/25656654/32143267-189ae556-bca7-11e7-93f8-54f689865234.png)

![amenity waste_disposal](https://user-images.githubusercontent.com/25656654/32143258-019d731e-bca7-11e7-847f-c92244a7c7b6.png)

**Comment by kocio-pl** [comment]
The wheels are still hard to recognize.

Conversion from big JPG makes no sense (especially because this image has perspective), its easier to design one yourself and test only on 14 px to avoid impressions from big version.

**Comment by kocio-pl** [comment]
What if we reuse waste_basket icon, but render it earlier? This would not make it too heavy and still clear IMO, since they are similar, the main difference is the size. We use such solution with clinic/doctors and it seems to be working.

**Comment by kocio-pl** [comment]
Definition says:

> They may be in the street, but they are not primarily for use by passing pedestrians. 

So maybe they should be rendered with gamma, like private parking - what do you think about it?

My intuition is that z18+ could be enough (earlier than small bins, but not much earlier).

**Comment by Tomasz-W** [comment]
Well, not all of waste disposals are closed for pedestrians. Often it's a couple of wheelbins just standing somewhere on a footway.
Gamma rendering here is not a perfect solution, but any solution would be better than not rendering it at all. I would like to see a test rendering to know how it works.

**Comment by dieterdreist** [comment]
2015-03-15 13:14 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> I think that it should not be rendered. At least in Poland for medium
> sized/volume waste each residential building has its associated
> amenity=waste_disposal.
>


are you sure these are "amenity" things then? Are they publicly
accessible/usable? If not I don't think an amenity tag would apply.

**Comment by matkoniecz** [comment]
> Are they publicly accessible/usable?

No. That is why I mentioned access=private

> If not I don't think an amenity tag would apply.

It is the first time that I heard this claim. Note that keys are not always really fitting - highway=footway for start. amenity=prison/parking may be without access to general public and are still tagged with amenity key.

amenity=toilets are rare case that is restricted to ones with public access, but it is not result of using amenity key.

**Comment by dieterdreist** [comment]
2017-11-02 14:49 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> If not I don't think an amenity tag would apply.
>
> It is the first time that I heard this claim. Note that keys are not
> always really fitting - highway=footway for start. amenity=prison/parking
> may be without access to general public and are still tagged with amenity
> key.
>
> amenity=toilets are rare case that is restricted to ones with public
> access, but it is not result of using amenity key.
>

IMHO the toilets example is not a rare case but is a similar, typical
example. You can also look at amenity=shower (only public showers),
amenity=drinking_water (not your private water tap), amenity=waste_basket
(not your private bin in your garden), amenity=bbq (not your private BBQ),
amenity=telephone, amenity=table, amenity=shelter, amenity=clock (publicly
visible), amenity=baking_oven, amenity=bar (commercial establishment), etc.

**Comment by dieterdreist** [comment]
the [key description](https://wiki.openstreetmap.org/wiki/Key:amenity)
says: Covering an assortment of *community* facilities

**Comment by dieterdreist** [comment]
the [key description](https://wiki.openstreetmap.org/wiki/Key:amenity) says: Covering an assortment of *community* facilities

**Comment by matkoniecz** [comment]
In this case this object is used by community (shared between 20 flats) but no general public.

**Comment by dieterdreist** [comment]
2017-11-02 15:10 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> In this case this object is used by community (shared between 20 flats)
> but no general public.
>


That's not how I would interpret "community" in this context

**Comment by matkoniecz** [comment]
> That's not how I would interpret "community" in this context

Then lets continue at http://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dwaste_disposal#confusing

**Comment by kocio-pl** [comment]
I think we could also use this kind of shape (the license is incompatible in this case):

https://www.flaticon.com/free-icon/garbage-container_32244

**Comment by Tomasz-W** [comment]
It may be confusing - waste disposals are usually a large or medium containers, and this shape shows little trash bin.

**Comment by kocio-pl** [comment]
It's a medium size street container - hence a wheel to make it move easier. I have similar at the front of my office. There are also other possible medium size shapes, but it needs to be tested on 14 px anyway.
