### ISSUE TITLE
Transit Platform does not render the same way as Tram Platform

### ISSUE THREAD

**Issue by Shrinks99** [gravitystorm/openstreetmap-carto#4196]
### Expected behavior
I used the transit platform tag to denote the fact that this station has both buses and streetcars on the same platform whereas the platform across from it only serves streetcars.  Both of these are marked `public_transport=platform` however the [standard transit transit platform](https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dplatform) doesn't render at all.

### Actual behavior
The tram platform renders, there is no object on the map for the transit platform

### Links and screenshots illustrating the problem
![Annotation 2020-08-25 223636](https://user-images.githubusercontent.com/5672810/91249833-9ce0b600-e725-11ea-9e30-e23b44eb9404.png)
Both the general purpose "transit platform" (serving busses and streetcars at this station) and the streetcar only "tram platform" across from it in the editor

![Annotation 2020-08-25 223727](https://user-images.githubusercontent.com/5672810/91249903-c00b6580-e725-11ea-9577-ceb0fe354270.png)
Only the tram platform is displayed on the map.

**Comment by jeisenbe** [comment]
Thank you for your report.

The tag `public_transport=platform` is not rendered.

That was requested way back in issue #435 (so this issue is a duplicate). But rendering was declined last year. Please review the discussion there, if interested.
