### ISSUE TITLE
Hedge areas don't get properly rendered

### ISSUE THREAD

**Issue by Robot8A** [gravitystorm/openstreetmap-carto#4200]
### Expected behavior
It renders as an area

### Actual behavior
It renders the outline

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/617503194

**Comment by imagico** [comment]
For the background of this matter see #3844, in particular https://github.com/gravitystorm/openstreetmap-carto/pull/3844#issuecomment-583848782 and https://github.com/gravitystorm/openstreetmap-carto/issues/4111#issuecomment-609390320.

As written there:

> there are two options i consider to have the chance to reach consensus here:

> * remove rendering of barrier=hedge due to the lack of clear and universally agreed on semantics in use.
> * interpret barrier=hedge as implying a polygon and as a landcover tag when tagged on a polygon.

> If you want to reformulate this issue to pursue either of these options i would support that. It would still be subject to a 
> discussion of the merits of such a change of course.

**Comment by matkoniecz** [comment]
Closing as it adds nothing new to what was discussed in issues linked by @imagico 

Maybe it would make sense to change behavior, but it would be necessary to start from reviewing all what was discussed already.
