### ISSUE TITLE
Thickness of power lines

### ISSUE THREAD

**Issue by jengelh** [gravitystorm/openstreetmap-carto#4209]
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=17/51.11511/14.21586
![43813](https://user-images.githubusercontent.com/8861948/94321428-c9d7f100-ff8f-11ea-97e6-bb82939171d0.png)

### Actual behavior
There is a group of three power lines;
the left one, way 60417684, is rendered "normal", has tag cables=6 and no associated relation
the center one, way 60417689, is rendered somewhat thicker, has tag cables=12 and relation
the right one, way 59025951, is rendered "normal", has tag cables=6 and relation

I could not find an indication in the carto code what would cause this center line to be emphasized. `git grep -e cables` does not yield a match, so the tag is probably not the cause. But it's the only one that stands out.. hm

### Expected behavior
Probably have all three lines the same thickness.

**Comment by pnorman** [comment]
The thicker one is rendered multiple times because it is part of a route relation with power=line. Just like a type=route route=road relation should not have highway=motorway on it, a type=route route=power should not have power=line on it.
