### ISSUE TITLE
Incorrect symbol in legend for access=destination

### ISSUE THREAD

**Issue by limes11** [gravitystorm/openstreetmap-carto#4211]
Hi all, 

access=destination is clearly rendered with grey circles on the way for hw=residential/unclassified etc. This is not reflected in the legend, where the symbol looks similar to the one for private but in a different color.

As someone suffering under mild colorblindness, I find it impossible to tell whether access=destination is rendered on highway=path/footway. I can see no difference. 

I propose to change the legend accordingly. 

(As a matter of fact, I will be happy with dropping the rendering of access=destination altogether for the simple fact that this tag is wrong in at least 90% of the cases when it's used.)

**Comment by HolgerJeromin** [comment]
This repository does not provide a legend itself
See #1928 for a bit of context

**Comment by jeisenbe** [comment]
@limes11 thank you for noticing this problem. 

I believe you are referring to this page: https://www.openstreetmap.org/key

At this moment it shows this for some of the roads and paths:

<img width="234" alt="legend-lines" src="https://user-images.githubusercontent.com/42757252/94512809-e499a800-01d1-11eb-9206-09e026d06207.png">

It is quite out of date, but it is not maintained in this repository. 

There is a more complete and up-to-date list of symbols on the wiki: 

https://wiki.openstreetmap.org/wiki/Standard_tile_layer/Key

Including the current access rendering:

https://wiki.openstreetmap.org/wiki/LinesTab#Miscellaneous_roads
<img width="779" alt="Screen Shot 2020-09-28 at 21 32 46" src="https://user-images.githubusercontent.com/42757252/94512919-2aef0700-01d2-11eb-9eb7-fe6db5157248.png">

I believe you will need to open an issue at https://github.com/openstreetmap/openstreetmap-website to fix the “key” link on openstreetmap.org

**Comment by limes11** [comment]
Alright, thanks a lot for pointing out where to ask for help!
