### ISSUE TITLE
Accessibility validation: Text must exceed CCR threshold

### ISSUE THREAD

**Issue by monicacarlino** [gravitystorm/openstreetmap-carto#4213]
### Expected behavior

The contrast of the two links on the map is compliant to color contrast analysis and wcag 2.1.

### Actual behavior

a: 'Report a problem' Violation 339 CCR of 3.6, adjust foreground and background colors to exceed 4.5. 
a: 'OpenStreetMap' Violation 341 CCR of 3.6, adjust foreground and background colors to exceed 4.5.

### Links and screenshots illustrating the problem

![low-contrast](https://user-images.githubusercontent.com/7782700/94565712-d5fecf80-0269-11eb-8c71-ebc317378599.gif)

**Comment by pnorman** [comment]
This is the issue tracker for OpenStreetMap Carto, the map style. We are not responsible for the text you have highlighted, that is up to the webpage which is adding the text.
