### ISSUE TITLE
Hide specific building names

### ISSUE THREAD

**Issue by ivansieder** [gravitystorm/openstreetmap-carto#4215]
We try to hide i.e. hotels, chalets,... on a map and have therefore removed them from the SQL query. But for some reason there seems to be a fallback to the 'name' tag. Is there any way to remove that from the project.mml? or is there a better approach to hide those kind of properties?

Tried searching the net and closed github issues, but wasnt't able to find anything suitable to this. Thank you in advance!

**Comment by Adamant36** [comment]
If you remove the code for them from the amenity points file that should stop their names from rendering. Since that's where it's handled.

**Comment by ivansieder** [comment]
#building-text was causing the issue. setting it to na empty string resolved the issue. Thank you!
