### ISSUE TITLE
Avoid rendering cross on Iglesia ni Cristo places of worship

### ISSUE THREAD

**Issue by ianlopez1115** [gravitystorm/openstreetmap-carto#4225]
Similar to Jehovah’s Witnesses (#1079) and La Luz del Mundo (#3800), Iglesia ni Cristo is a Christian denomination that avoids using the cross as a symbol. A generic place-of-worship icon can be used in lieu of a emblem specific to the said denomination.
### Expected behavior
🛐

### Actual behavior
✝️

### Links and screenshots illustrating the problem
![image](https://user-images.githubusercontent.com/1140532/96368691-d95dea80-1187-11eb-8480-662e5c3c5bb4.png)

**Comment by jeisenbe** [comment]
The church website seems to confirm that the symbol of a cross is not used on Iglesia ni Cristo buildings or in public worship services: https://www.pasugo.com.ph/on-using-the-cross-and-graven-images-for-worship/

However, I have not yet been able to confirm that Iglesia ni Cristo would consider the use of the cross as a map symbol to be inappropriate for their chapels and cathedrals. It’s not mentioned on the Wikipedia article on this religion, for example.

Can someone confirm this?

Also, does Iglesia ni Cristo consider themselves a separate religion from Catholicism or Protestant Christianity? If so, that would be a point in favor of using a different symbol.

**Comment by ianlopez1115** [comment]
>However, I have not yet been able to confirm that Iglesia ni Cristo would consider the use of the cross as a map symbol to be inappropriate for their chapels and cathedrals

One OSM contributor who is part of the said church raised this [note](https://www.openstreetmap.org/note/992185) in May 2017 mentioning that "[INC does] not carry the cross symbol in our chapels and it is against [their] doctrines". I'll be linking this discussion to the said note (and also this [note](https://www.openstreetmap.org/note/2389359) which raised a similar query) so that they and possibly other INC members who are also OSM contributors can participate here.
