### ISSUE TITLE
Missing a database user credentials in the style.xml file

### ISSUE THREAD

**Issue by duszek94** [gravitystorm/openstreetmap-carto#4233]
Hello

I want to generate a **style.xml** file for the OSM server, which would contain database credentials in the `<Datasource></Datasource>` sections

I've modified a **project.mml** file like below:

> "osm2pgsql": {
>        ...
>       "user": "example",
>       "password": "example"
> }

but after executing this command:
`carto project.mml > style.xml`
provided username and password are not attached 

In result, the **renderd** service has no access to the database and is unable to load a profile. Here are the errors:
> Postgis Plugin: fe_sendauth: no password supplied
> Received request for map layer 'default' which failed to load

My version of the **openstreetmap-carto** package is 2.41.0

How could I fix that? Thank you in advance for your help

**Comment by imagico** [comment]
OSM-Carto uses a YAML mml file in all recent versions - your quote is from JSON.  Adding user and password info to the corresponding section of the YAML:

https://github.com/gravitystorm/openstreetmap-carto/blob/b10aef3866bacf387581b8fea4eec265010b0d14/project.mml#L27-L32

should work.  Use of old versions as you indicate (2.41.0 is from 2016) is not supported and i don't even know if that is compatible with current versions of carto and mapnik.
