### ISSUE TITLE
add rendering for man_made=observatory

### ISSUE THREAD

**Issue by tamkto** [gravitystorm/openstreetmap-carto#4234]
an observatory is typically a building or an area that contains one or more telescopes or monitoring stations and auxiliary buildings. currently only individual telescopes are rendered. it would be nice to have a name of an observatory itself rendered as well (maybe even taking precedence over individual telescopes/stations at lower zoom levels).
https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dobservatory
(some observatories are also marked with landuse=observatory, but this is deprecated)

examples:
https://www.openstreetmap.org/#map=15/28.7587/-17.8878
https://www.openstreetmap.org/#map=14/19.8234/-155.4702

**Comment by jeisenbe** [comment]
@tamkto thank you for mentioning this.

There is a previous issue requesting the same new rendering: https://github.com/gravitystorm/openstreetmap-carto/issues/4065

**Comment by tamkto** [comment]
@jeisenbe yes, exactly, thanks for pointing that issue out.
I think that the best solution would be to render just the name tag of a man_made=observatory object if it exists, it would greatly help in the examples above and I cannot think of a situation where it would be problematic.

**Comment by jeisenbe** [comment]
Re: "I am still not sure why landuse=observatory has been deprecated in favour of a man_made tag: man_made=observatory is basically a landuse thing”

That’s a good point. It appears that it was only marked as discouraged in November 2019, without discussion: https://wiki.openstreetmap.org/w/index.php?title=Tag:landuse%3Dobservatory&diff=prev&oldid=1919298

Perhaps ask about this on the Tagging mailing list: https://lists.openstreetmap.org/listinfo/tagging

Until there is a consensus about the best way to tag and map these features, I don’t think we can render them, as previously mentioned in #4065, so I will close this as a duplicate. Discussion can continue on #4065 if there is a change in the status of this tag.
