### ISSUE TITLE
"magic bullet" exists=no, to prevent rendering

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4237]
Like #542, maybe there should be a "magic bullet" exists=no,
that would keep a feature off the map.

You see, [an item that no longer exists](https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/demolished#This_tag_very_important_as_an_aid_to_locate_existing_features) but that connects existing items, thus allowing the latter to make sense, needs some way to exist in the database, but without being rendered.

Sure, for various features, various tag combinations might cause them not to be rendered. But there should also be one "magic bullet".

**Comment by jeisenbe** [comment]
One of the primary goals of this map style is to provide consistent feedback to mappers. A tag which means “don’t render this” would be quite confusing to mappers, and not very helpful to map users, so we would not use such a tag to influence rendering.

See https://wiki.openstreetmap.org/wiki/Comparison_of_life_cycle_concepts for a discussion of the tagging issues, and https://wiki.openstreetmap.org/wiki/Lifecycle_prefix for alternative ways to map features which do not yet exist or no longer exist.

**Comment by jidanni** [comment]
Ah, removed:power=line ! That was simple! Thanks!
