### ISSUE TITLE
Render abandoned:building=*

### ISSUE THREAD

**Issue by wielandb** [gravitystorm/openstreetmap-carto#4238]
### Expected behavior

A building that I tag with the lifecycle-prefix `abandoned` should still be on the map after re-rendering.

### Actual behavior

A building tagged with `abandoned` disappears from the map. 

### Further explanation and argumentation

I absolutely see the arguments made in #2551 and before that rendering abandoned waste baskets and other obsolete things bloats the map. 
My main problem why I am opening this issue is that the standard rendering for a building is an accurate representation, even if it is abandoned. Where I live, there are lots of abandoned industrial buildings, and when I tag them as abandoned, they disappear from the map. So now, where in reality are massive amounts of huge buildings, there are just huge empty spaces on the map, wich is just not a representation of reality. And simply _not removing_ a building wich is facutally there does not bloat the map.

**Comment by HolgerJeromin** [comment]
`abandoned` prefix on building tag seems fishy. 
A shop or office can be abandoned, but IMO no osm building. The feature (which is described by `building` tag) is still there.

**Comment by imagico** [comment]
* abandoned:building: 123k uses, [undocumented](https://wiki.openstreetmap.org/wiki/Key:abandoned:)
* building=ruins: 94k uses, [documented](https://wiki.openstreetmap.org/wiki/Tag:building%3Druins)
* building=* + ruins=yes: 48k uses, [documented](https://wiki.openstreetmap.org/wiki/Key:ruins)
* building=* + abandoned=yes: 20k uses, [documented](https://wiki.openstreetmap.org/wiki/Key:abandoned)
* disused:building: 16k uses, [undocumented](https://wiki.openstreetmap.org/wiki/Key:disused:)
* building=* + disused=yes: 13k uses, [documented](https://wiki.openstreetmap.org/wiki/Tag:disused%3Dyes)

In principle i would support the rendering of abandoned buildings in a state of serious decay in a distinct rendering and the rendering of disused buildings without serious decay like normal buildings.

But we do not have a clear consensus on tagging among mappers apparently.  The use of `abandoned:building` - while it seems to be the most widespread tag - is currently undocumented and as @HolgerJeromin says its exact meaning is not intuitively clear.  Drawing a clear line between `abandoned:building` and `disused:building` is also missing, the generic explanation for the prefix is not really that helpful for the specific case of buildings.

**Comment by jeisenbe** [comment]
There is not clear consensus about whether `building=*` + `abandoned=yes` is prefered, or `abandoned:building=*`, and the situation for `building=*` + `disused=yes` vs `disused:building=*` is even less in favor of the namespaced version. 

See previous general discussion at #2124 as well.

I don’t think we should support the tag `abandoned:building` until it is clearly defined and there is clear consensus that this method of tagging is preferrable to adding `abandoned=yes`.

It will also be difficult to find a rendering style for ruins and abandonded buildings. See previous efforts to define a different rendering for “minor buildings” at #3679 - We would need a clear idea of how to distinguish these features from other buildings.
