### ISSUE TITLE
Label placement within some area shapes obviously suboptimal

### ISSUE THREAD

**Issue by atorger** [gravitystorm/openstreetmap-carto#4243]
The text labels for lakes etc should be placed either in the center, or a bit off-center to allow the appropriate text size.

In the lake "Garacken" in the screenshot a plain vertical/horizontal centering works well as the shape of the lake is as it is. In the lake "Abborrtjärnen" however, the label is by being forced to be in the vertical center forced to be made smaller than it would be if just lifted a bit off center.

![image](https://user-images.githubusercontent.com/13962807/97854225-7593ff80-1cf9-11eb-9ce5-0926b235babc.png)

Here is the same lake from an official government map, showing a better position of the label.
![image](https://user-images.githubusercontent.com/13962807/97854671-14b8f700-1cfa-11eb-82a1-fb06012ad794.png)

**Comment by imagico** [comment]
Thanks for the report - but this is already covered in #3857.
