### ISSUE TITLE
scripts/get-external-data.py fails because ne_110m_admin_0_boundary_lines_land.zip has moved

### ISSUE THREAD

**Issue by SomeoneElseOSM** [gravitystorm/openstreetmap-carto#4249]
(this is on Debian 11 testing)

```
scripts/get-external-data.pyINFO:root:Checking table simplified_water_polygons
INFO:root:Checking table water_polygons
INFO:root:Checking table icesheet_polygons
INFO:root:Checking table icesheet_outlines
INFO:root:Checking table ne_110m_admin_0_boundary_lines_land
Traceback (most recent call last):
  File "scripts/get-external-data.py", line 258, in <module>
    main()
  File "scripts/get-external-data.py", line 206, in main
    download.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
```

It's odd that that URL returns 500 there.  A "wget" on the same URL gets a 500 too as opposed to a 302; but a browser download follows a redirect to https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip .

Obviously one "fix" would be to change the URL in "get_external_data.yml", but is it actually possible to get "get_external_data.py" to follow the redirect in the same way that a browser does?

**Comment by pnorman** [comment]
We do follow redirects, but naturalearthdata.com is broken, opened https://github.com/nvkelso/natural-earth-vector/issues/434 to cover it. 

I prefer the cannonical URL we're currently using that is linked from the web pages, but obviously it doesn't work so needs changing to the redirected URL.

Working on a PR to change it.

**Comment by SomeoneElseOSM** [comment]
Since the resolution at https://github.com/nvkelso/natural-earth-vector/issues/434 this works for me without any script changes.  I've just run through https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/ "soup to nuts" on a new VM and it worked without problems.

**Comment by terminaldweller** [comment]
The current link in the `external-data.yml` is not working.
If i curl it:<br/>
```bash
curl http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
```
I get this:<br/>
```html
<html>
<head>
<meta name="robots" content="noarchive" />
<meta name="googlebot" content="nosnippet" />
</head>
<h3>Error. Page cannot be displayed. Please contact your service provider for more details.  (21)</h3>
</div>

</body>
</html>
```

**Comment by walxo** [comment]
https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip

**Comment by SomeoneElseOSM** [comment]
@walxo Are you trying to report a current problem or are just linking to a location in Natural Earth's CDN where the request that "get-external-data.py" will redirect to?

Scripts that don't handle redirects well will struggle, but get-external-data.py worked when I last tried it a couple of weeks ago.
