### ISSUE TITLE
Australian Pictorial Shields

### ISSUE THREAD

**Issue by OppositeAd2996** [gravitystorm/openstreetmap-carto#4255]
Hello 

Greetings from Australia. Shields are needed for us as well as simple numbers isn't enough. I know that most of the country uses the British Alphanumeric System. However, the entire country doesn't have a unified system so it gets messy here.

Currently, I've raised the issue up on the OSM reddit page. You can see the difference [here](https://www.reddit.com/r/openstreetmap/comments/k0374x/making_shields_come_onto_openstreetmaps/) where I've put the difference. Furthermore, these shields aren't copyrighted so we can use them. 

There isn't much shielded routes left these days except in WA, QLD and VIC (which is starting to phase out these routes)

Thanks,

**Comment by jeisenbe** [comment]
Hello @OppositeAd2996 - this has already been requested in issue #508 

Please continue any new observations or discussion in that issue. Unfortunately, you will see that #596 must be solved first, and that depends on #4112

**Comment by OppositeAd2996** [comment]
Okay, I'll do that

**Comment by kennykb** [comment]
Please also open an issue at https://github.com/kennykb/osm-shields/ so that the idea doesn't get lost from that thread of development, either.

**Comment by OppositeAd2996** [comment]
Thanks,

**Comment by ZeLonewolf** [comment]
Hi @OppositeAd2996, we are very close to having support for highway shields in the openstreetmap-americana project (we are awaiting an imminent release of OpenMapTiles 3.13), and we would welcome contributions of Australian pictoral shields to that project.
Feel free to post an issue at https://github.com/ZeLonewolf/openstreetmap-americana
