### ISSUE TITLE
define value for leaf_type for Arecaceae, or use family key.

### ISSUE THREAD

**Issue by mfrasca** [gravitystorm/openstreetmap-carto#4256]
I'm drawing a `natural=tree`, and it's a palm tree.  Now the problem is that palm trees belong to a very complex family and I know that even most botanists who don't specialize in that family won't go any further in the identification than "Arecaceae sp.", that is to say "it's a palm tree".  Resulting situation?  I have a tree, I know it's a palm, I have no species, no genus, and I could tag it as `family=Arecaceae`, but who's going to notice?

The [wiki page for `natural=tree`](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree) says what icon is used to represent a tree node, based on the value of the key `type`, but it also says that tagging non relations with `type` is deprecated, and that [`leaf_type`](https://wiki.openstreetmap.org/wiki/Key:leaf_type) should be used instead.

But: `leaf_type` does not mention palm trees.

In February 2019 I posed the question in the [talk for that page](https://wiki.openstreetmap.org/wiki/Talk:Key:leaf_type), and nobody commented.

Palm trees can be described as broad leaved, but that would not anticipate what we're going to see on location.  Like you go to Cannes and you see orange trees?

Can we include some value for `leaf_type` that would be specific to palm trees?

The other option would be to add a `family` key, which would be only relevant for palm trees.  Not a good idea in my opinion.

An other option, apparently used in Cannes (check Node: 5995522981), is to tag palm trees as `genus=Areca`, which has two disadvantages: it is not honoured by the renderer; it is possibly not even true. (I've asked the author about it.)

**Comment by mfrasca** [comment]
apparently there's almost 5200 objects which would benefit this addition.
5049 palm; 101 palms; 34 palmtree and 8 more.

**Comment by imagico** [comment]
This is not the place for tagging discussion. I am sorry that your comment on the talk page for `leaf_type` did not receive an answer.  But you already indicated the prudent answer yourself - palm trees are formally broad-leaved trees.  A better place as a starting point might be the documentation of `natural=tree`:

https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree

or the tagging mailing list.  The consensus way to tag the biological family of a tree is `taxon` (https://wiki.openstreetmap.org/wiki/Key:taxon) `genus` is for the genus of a plant - and palms belong to multiple different genera (see https://en.wikipedia.org/wiki/List_of_Arecaceae_genera).

If your suggestion is to render `taxon` or `genus` on trees - we currently do not render any distinction on `natural=tree` and by far the most common supplementary tags for those are `leaf_type` (2.4M) and `leaf_cycle` (1.4M).  That means we will certainly not differentiate rendering of palm trees based on species/genus/taxon without also differentiating leaf_type/leaf_cycle.

In principle I could envision a differentiated rendering of trees based on leaf_type/leaf_cycle and further differentiating out palm trees - if there is a consistently used tagging for those (which could be a list of values for species/genus/taxon).  So if you want you can re-frame your issue in that direction.

**Comment by matkoniecz** [comment]
>  I am sorry that your comment on the talk page for leaf_type did not receive an answer.

If you want more answers to tagging questions I recommend tagging mailing list. Telegram OSM channel, Discord OSM channel etc may also be useful alternatives if someone wants some answers.

I am closing this issue as it is not a place for tagging discussion.
