### ISSUE TITLE
Render busway=opposite_lane

### ISSUE THREAD

**Issue by c933103** [gravitystorm/openstreetmap-carto#4264]
busway=oppsite_lane is frequently used together with tags like oneway=yes, which indicate for a one-lane road there is another lane that goes the opposite way but that lane can only be used by buses. Currently, OSM Carto only render the one way tag, making the road being shown as unidirectional, but does not provide any visual indication that buses are allowed in another way, making it somewhat confusing for users trying to plan routes for buses. Please consider improving the rendering to show the existence of a bus lane in opposite direction.

**Comment by jeisenbe** [comment]
@c933103 thank you for opening this issue. Do you have an idea of how this could be rendered?

Currently this map style does not show a specialized rendering for any of the `busway=` or `cycleway=` tags, which are used to specify that a certain lane in a roadway is dedicated to use by bicycles or buses. 

It would be difficult for us to show all of these details for buses, especially since there would be equal reasons to add rendering for the `cycleway` tags, which might be found on the same street segments.

There are also existing speciality maps which focus on these details, including the Transport map and OPNVKarte on Openstreetmap.org and I believe in most cases map users would be better served by using a map style which shows all bus-related tags and infrastructure.

**Comment by matkoniecz** [comment]
> Do you have an idea of how this could be rendered?

And in way that would not make it easy to confuse with regular `oneway` and `oneway:bicycle=no`

> It would be difficult for us to show all of these details for buses, especially since there would be equal reasons to add rendering for the cycleway tags, which might be found on the same street segments.

+1

> making it somewhat confusing for users trying to plan routes for buses

I would strongly suggest to not use general-purpose rendering for something so specialized. For example https://github.com/dabreegster/abstreet is likely to be far better fit.

Also, is it theoretical issue or real use case? If real use case - where it is happening? (I ask as in places familiar to me people planning routes for buses work with people who decide on busway placement and have strong influence on that).

**Comment by c933103** [comment]
> > Do you have an idea of how this could be rendered?
> 
> And in way that would not make it easy to confuse with regular `oneway` and `oneway:bicycle=no`
> 

How is oneway:bicycle=no currently rendered? 

> > It would be difficult for us to show all of these details for buses, especially since there would be equal reasons to add rendering for the cycleway tags, which might be found on the same street segments.
> 
> +1
> 
> > making it somewhat confusing for users trying to plan routes for buses
> 
> I would strongly suggest to not use general-purpose rendering for something so specialized. For example https://github.com/dabreegster/abstreet is likely to be far better fit.
> 
> Also, is it theoretical issue or real use case? If real use case - where it is happening? (I ask as in places familiar to me people planning routes for buses work with people who decide on busway placement and have strong influence on that).
> 
> 
> 
In my city, while the transportation department is responsible for both the decision of drawing bus lane and overseeing the bus route arrangement, individual bus companies also have their separate planning division, and in addition to that, local councilors, as well as public member, would also often be involved in or even proposing routes actively to the bus companies and transportarion departments, where maps would be used in the process.
In addition, other than regular bus companies providing urban bus services, there are also smaller bus companies that provide shuttle bus services, tour bus services, intercity coaches, paratransit, or even individually operated minibuses that they all could use bus lanes but need to design and drive the routes by themselves

**Comment by matkoniecz** [comment]
> How is oneway:bicycle=no currently rendered?

They are not.

**Comment by matkoniecz** [comment]
I am very dubious is it feasible to render it.

I would leave it for full-blown renderers of lane tagging like https://github.com/dabreegster/abstreet#ab-street or specialized rendering for narrow application.

**Comment by jeisenbe** [comment]
Closing because there is no feasible way to render this in our map style, and there are speciality map styles which are focused on public transport which could do a much better job of this. (e.g. https://wiki.openstreetmap.org/wiki/Transport_Map and https://wiki.openstreetmap.org/wiki/ÖPNVKarte)
