### ISSUE TITLE
Render tunnel=yes and covered=yes on highway=raceway

### ISSUE THREAD

**Issue by SuperFlomm** [gravitystorm/openstreetmap-carto#4269]
### Expected behavior
Tunnels rendered similar to tunnels on regular roads.
### Actual behavior
Tunnels are not rendered and are therefore indistinguishable from raceways without tunnels.
### Links illustrating the problem
https://www.openstreetmap.org/way/176695255
https://www.openstreetmap.org/way/397149462
https://www.openstreetmap.org/way/712371562
https://www.openstreetmap.org/way/175563701

**Comment by imagico** [comment]
highway=raceway + tunnel=yes: 118 uses.
highway=raceway + covered=yes: 84 uses.

**Comment by matkoniecz** [comment]
Duplicate of display tunnels and bridges for highway=raceway #1688
