### ISSUE TITLE
Public transport shelter should not be labeled with elevation

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#4270]
### Expected behavior

A bus shelter tagged `amenity=shelter` `building=yes` `shelter_type=public_transport` should be rendered as an ordinary building with or without an `ele` tag.

### Actual behavior

The `ele` tag causes the bus shelter to be rendered like an alpine hut, labeled with a 🌧️ and an elevation. For example, [this way](https://www.openstreetmap.org/way/851972354) was added as part of a building import that included elevations and heights for every building. The bus shelter is useful for avoiding the rain, but the elevation is not particularly interesting for a 2D renderer. (It might be useful for a 3D renderer.)

### Links and screenshots illustrating the problem

[![vta](https://user-images.githubusercontent.com/1231218/102858779-ae8a4f80-43df-11eb-98db-815fa5e5c28e.png)](https://www.openstreetmap.org/way/851972354)

/ref #3382

**Comment by imagico** [comment]
Thanks for the report.  There seem to be a few misconceptions here:

* The shown rendering is not the rendering for alpine huts - alpine huts are rendered like this: https://www.openstreetmap.org/#map=17/46.50142/8.05286
* The addition of the `ele` tag does not change the rendering beyond displaying the elevation in the label in addition to the name (or alone if no name is tagged).
* The rendering of the building is completely independent of the shelter and ele tagging.

I think this issue could still make sense in the following versions:

* propose to not render ele on `amenity=shelter` + `shelter_type=public_transport` - that makes quite a lot of sense IMO.
* propose not to render `shelter_type=public_transport` with a symbol - i don't think that is a good idea because those shelters (whether they qualify as building or not) are fairly useful to map users.
* propose to render `shelter_type=public_transport` with a symbol distinct from ordinary `amenity=shelter`.  That in principle makes sense IMO but would depend on a suitable symbol of course.

**Comment by polarbearing** [comment]
I'd prefer "_render shelter_type=public_transport with a symbol distinct from ordinary amenity=shelter_" as well as "_not render ele on amenity=shelter + shelter_type=public_transport_".

**Comment by polarbearing** [comment]
Quick mockup: side-view of a back wall with a tilted roof, supposed to be transport-blue. Do we need the raindrops?
![shelter-pt1](https://user-images.githubusercontent.com/8266355/102889803-96f0ac80-445b-11eb-9f6b-ec7cc2781607.png)

**Comment by 1ec5** [comment]
Thank you for clearing up my misunderstanding. Indeed, I meant to suggest omitting the elevation from `shelter_type=public_transport`, but a distinct icon would be even better. The mockup makes sense to me; hopefully it would be intuitive regardless of which side of the road the shelter is on.

**Comment by imagico** [comment]
Ok, i changed the title to reflect the idea or removing the elevation label - that is non-controversial and a good first issue for new developers.  Differentiated rendering of different shelter_type values is more tricky to do in an intuitive fashion.

**Comment by GoutamVerma** [comment]
hey @imagico i would like to work on it .it will be going to be first contribution

**Comment by GoutamVerma** [comment]
will you guys help me

**Comment by imagico** [comment]
Sure - general instructions how to get started with this style can be found on

https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md
https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md

With any specific questions on how to fix this issue just ask.

**Comment by jeisenbe** [comment]
@GoutamVerma there is a fairly detailed explanation about how to do a PR and test changes at https://github.com/gravitystorm/openstreetmap-carto/issues/2291#issuecomment-753247982 - and the following comment.

**Comment by GoutamVerma** [comment]
hey @jeisenbe and @imagico i'm done with the setup. will you please tell me how to fix this issues .where i need to make changes in project.mml .

**Comment by jeisenbe** [comment]
This line adds the elevation for the name of all tpes of `amenity=shelter`: 

https://github.com/gravitystorm/openstreetmap-carto/blob/e77163edaaf1c2fcd9c35d6967e38c108312c8d6/project.mml#L1470

If you simply want to not render the ele=* when there is a `shelter_type=public_transport` tag on the same feature, you could add `AND shelter_type IS NOT public_transport`, I believe. 

But you might also want to consider what other shelter_type values should or should not have the elevation rendered. Perhaps this is also not needed for a `picnic_shelter`, for example. 

In that case you could add `AND shelter_type NOT IN (public_transport, picnic_shelter)`

**Comment by GoutamVerma** [comment]
hey @imagico and @jeisenbe. I made a pull request against this issue please review and accept this . Thank you

**Comment by imagico** [comment]
@jeisenbe already mentioned where the change needs to be made.  For additional context - the label shelters and other POIs are labeled with is defined by

https://github.com/gravitystorm/openstreetmap-carto/blob/e77163edaaf1c2fcd9c35d6967e38c108312c8d6/project.mml#L1463-L1477

That is a very complex expression combining both elevation values for peaks and shelters and height values for other features.  You can simply ignore most of it and modify the condition for shelters as @jeisenbe explained.  Make sure you get the braces right, that needs to be:

`OR (amenity = 'shelter' AND tags->shelter_type NOT IN (public_transport, picnic_shelter))`

**Comment by jdhoek** [comment]
> Quick mockup: side-view of a back wall with a tilted roof, supposed to be transport-blue. Do we need the raindrops?
> ![shelter-pt1](https://user-images.githubusercontent.com/8266355/102889803-96f0ac80-445b-11eb-9f6b-ec7cc2781607.png)

Nice! That's how I would expect to see them too. This is how these show up on Dutch government maps for street furniture:

![Screenshot from 2021-02-02 12-13-21](https://user-images.githubusercontent.com/683699/106592811-42f3e000-6550-11eb-8e26-5ec4bd2f4656.png)

That shape seems like it would convey the meaning of a bus/tram stop shelter quite well.
