### ISSUE TITLE
Render local ethnic names for Chinese autonomous divisions

### ISSUE THREAD

**Issue by Artoria2e5** [gravitystorm/openstreetmap-carto#4276]
### Background
China has [autonomous ethnic divisions](https://en.wikipedia.org/wiki/Autonomous_administrative_divisions_of_China) at many levels, from the largest province-like "autonomous regions" to smaller autonomous prefactures. It is common for these divisions to have place names deriving from ethnic languages, and to have government road signs indicating such names.

OSM should print some of these names on the default map, especially for large cities.

### Expected & actual behavior
* A view of Inner Mongolia, such as [6/42.343/111.683](https://www.openstreetmap.org#map=6/42.343/111.683), should not only show 呼和浩特市 for Hohhot, but also the local writing of ᠬᠥᠬᠡᠬᠣᠲᠠ.
* A view of Lahsa, [relation 2745046](https://www.openstreetmap.org/relation/2745046), should also show its Tibetan name ལྷ་ས་གྲོང་ཁྱེར་. 

Both currently only show the phonetic translation in Chinese. Since Lhasa has a `name` with the native name, it appears that Carto is only taking `name:zh`.

### Suggestions
* It might be helpful to have a tag recording the additional langs to render on boundary-type relations.
* Some significant places in Mongolia already have an additional traditional mongolian script render despite a lack of equivalent information in OSM, cf. [relation 270051](https://www.openstreetmap.org/relation/270051). Whatever magic is used there will be relevant for processing the mongolian information here.
* I expect this issue to be relevant in other autonomous divisions around the world with recongized regional languages.

**Comment by pnorman** [comment]
We do not use the name:zh tag. World-wide we render the name in the local language - the `name` tag. There is no special treatment for specific scripts or regions.

For Lhasa, there is no label rendered for the object you linked. There is a label from Lhasa City which is from https://www.openstreetmap.org/node/31219396 and has `name=拉萨市`.

**Comment by Artoria2e5** [comment]
What's the explanation for ᠳᠠᠯᠠᠨᠵᠠᠳᠠᠭᠠᠳ rendering in though? It's only in a name:mn-mong entry. See https://www.openstreetmap.org/node/297231370#map=12/43.5604/104.4236

**Comment by mboeringa** [comment]
> What's the explanation for ᠳᠠᠯᠠᠨᠵᠠᠳᠠᠭᠠᠳ rendering in though? It's only in a name:mn-mong entry. See https://www.openstreetmap.org/node/297231370#map=12/43.5604/104.4236

That wasn't the case 2 days ago. If you look at the editing history, you can see that someone removed the Mongolian addition to the `name` tag, and inserted it in the `name:mn-mong` tag:

**Comment by Artoria2e5** [comment]
Judging from the multilingual names page, China is supposed to have the local names. The current situation is probably an oversight by the community -- we are overwelmingly Han Chinese after all. I tweaked the description on the page a bit to just be a bit more specific.

The partial consensus I can gather from the telegram group is quite positive. I mean, what can you expect from outlaws who break rules about keeping geographic information secret every day anyways...
