### ISSUE TITLE
Render healthcare=centre

### ISSUE THREAD

**Issue by jpds** [gravitystorm/openstreetmap-carto#4282]
This should be rendered by default on the standard map as people are using it to mark places that are COVID-19 testing sites/vaccination centres, for example:

- https://www.openstreetmap.org/node/8174601071
- https://www.openstreetmap.org/node/8237571422
- https://www.openstreetmap.org/node/8298155594

**Comment by imagico** [comment]
Thanks for the suggestion, given however we just had the discussion on tagging pointing out this tag is used for a very broad and unspecific spectrum of facilities:

https://lists.openstreetmap.org/pipermail/tagging/2021-January/058254.html
https://wiki.openstreetmap.org/wiki/Tag%3Ahealthcare%3Dcentre

I would suggest to decline this request.

Rendering more specific tags indication public vaccination opportunities (`healthcare:speciality=vaccination`, 
`vaccination=*`, `healthcare=vaccination_centre`) are a different matter.  So far they are used almost exclusively in Germany however and tend to not have access tags despite being not open to the public in general (you need an appointment and you can only get that under very specific circumstances, i.e. age and profession).  IMO this is at the moment something for speciality maps and not for a global general purpose map like this.

**Comment by jeisenbe** [comment]
I agree with @imagico about the problems with healthcare=centre, which I realized after searching how the tag is used in India (the main area), France, and England, in addition to here in the USA. Basically it is used for anything healthcare-related which has the word “center” in the name, or in India even for other features which vary from regional hospitals to village health posts without any doctor or nurse available. Rendering this would be similar to rendering healthcare=yes (when used as a primary feature tag).

(It should also be mentioned that there is a proposal to tag vaccination centres as `healthcare=vaccination_centre` currentling in the voting phase of the proposal process, and it will probably be approved in a few days: https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:healthcare%3Dvaccination_centre)

**Comment by jpds** [comment]
That's great for vaccination centres, but I don't believe that we have anything for actual testing centres, such as https://www.openstreetmap.org/node/8298155594

**Comment by imagico** [comment]
There does not seem to be an established tagging for that - `healthcare:speciality=covid19` is undocumented, has only 77 uses and is semantically ambiguous (diagnosis vs. treatment).

**Comment by imagico** [comment]
Closing as per discussion above.  If consensus among mappers develops on a semantically clear tagging and such is being used more broadly the matter can be revisited.

**Comment by jeisenbe** [comment]
Re: testing sites - tagging discussion is off-topic here, but please see the relevant discussions on the Tagging list about that: 

https://lists.openstreetmap.org/pipermail/tagging/2021-January/057868.html - question about how to tag
https://lists.openstreetmap.org/pipermail/tagging/2021-January/058358.html - suggestion to use healthcare=sample_collection instead of healthcare=laboratory
