### ISSUE TITLE
Rendering of highway=turning_circle suboptimal

### ISSUE THREAD

**Issue by pigsonthewing** [gravitystorm/openstreetmap-carto#4286]
### Expected behavior

Turning circles (`highway=turning_circle`) should be rendered according to their `diameter=*` value

### Actual behavior

Turning circles appear to be rendered at a default (and small) size, regardless of the diameter=* value

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/node/16267961

https://www.openstreetmap.org/node/73757045

https://www.openstreetmap.org/node/58806357

**Comment by imagico** [comment]
For a well readable map turning circles need to be drawn in a size relative to the drawing width of the road (which they are - see https://github.com/gravitystorm/openstreetmap-carto/blob/master/style/roads.mss#L2435)

Regarding drawing of roads in actual ground width (and then consequently rendering turning circles in their actual diameter) - we have rejected that in #1290 - could revisit that of course.

**Comment by pnorman** [comment]
Closing for the reasons above.
