### ISSUE TITLE
Error "fe_sendauth no password supplied" due to missing password argument in scripts/get-external-data.py

### ISSUE THREAD

**Issue by ukalpa** [gravitystorm/openstreetmap-carto#4287]
### Expected behavior
There is no PostgreSQL "password" option for "./scripts/get-external-data.py" 

### Actual behavior
When I execute the command

`./scripts/get-external-data.py -d osm -H localhost -U postgres`

returns the below error:
![Screen Shot 2021-01-16 at 10 13 44 PM](https://user-images.githubusercontent.com/4927815/104808020-354c1400-5848-11eb-8b2c-3a9bfe81c054.png)

### I solved by adding the following codes but not sure if it is the correct solution:

<img width="895" alt="Screen Shot 2021-01-16 at 10 22 38 PM" src="https://user-images.githubusercontent.com/4927815/104808195-6d078b80-5849-11eb-8ba5-eaa2918bc963.png">

<img width="738" alt="Screen Shot 2021-01-16 at 10 15 57 PM" src="https://user-images.githubusercontent.com/4927815/104808093-d935bf80-5848-11eb-8a25-5dad6d50ca68.png">

<img width="658" alt="Screen Shot 2021-01-16 at 10 17 36 PM" src="https://user-images.githubusercontent.com/4927815/104808102-ddfa7380-5848-11eb-8c26-44d0b763dc77.png">

Then, can execute successfully by adding -P option.

**Comment by pnorman** [comment]
Fixed in #4265

Best practices would be to put the password in a `.pgpass` file or use environment variables, but the command line is now an option.
