### ISSUE TITLE
scripts/get-external-data.py fails with no such column: area_of_use_auth_name on ne_110m_admin_0_boundary_lines_land.shp

### ISSUE THREAD

**Issue by bib1963** [gravitystorm/openstreetmap-carto#4290]
### Links and screenshots illustrating the problem
Following instructions, I get to scripts/get-external-data.py, which eventually fails with:

INFO:root:Checking table simplified_water_polygons
INFO:root:Checking table water_polygons
INFO:root:Checking table icesheet_polygons
INFO:root:Checking table icesheet_outlines
INFO:root:Checking table ne_110m_admin_0_boundary_lines_land
CRITICAL:root:ogr2ogr returned 1 with layer ne_110m_admin_0_boundary_lines_land
CRITICAL:root:Command line was ogr2ogr -f PostgreSQL -lco GEOMETRY_NAME=way -lco SPATIAL_INDEX=FALSE -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=YES -nln loading.ne_110m_admin_0_boundary_lines_land --config SHAPE_ENCODING WINDOWS-1252 -explodecollections -t_srs EPSG:3857 PG:dbname=gis data/ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp
CRITICAL:root:Output was

Traceback (most recent call last):
  File "scripts/get-external-data.py", line 243, in main
    subprocess.check_output(ogrcommand, stderr=subprocess.PIPE, universal_newlines=True)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ogr2ogr', '-f', 'PostgreSQL', '-lco', 'GEOMETRY_NAME=way', '-lco', 'SPATIAL_INDEX=FALSE', '-lco', 'EXTRACT_SCHEMA_FROM_LAYER_NAME=YES', '-nln', 'loading.ne_110m_admin_0_boundary_lines_land', '--config', 'SHAPE_ENCODING', 'WINDOWS-1252', '-explodecollections', '-t_srs', 'EPSG:3857', 'PG:dbname=gis', 'data/ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/get-external-data.py", line 258, in <module>
    main()
  File "scripts/get-external-data.py", line 249, in main
    raise RuntimeError("ogr2ogr error when loading table {}".format(name))
RuntimeError: ogr2ogr error when loading table ne_110m_admin_0_boundary_lines_land

If I run ogr2ogr directly, I get:

osm@ns2 ~/openstreetmap-carto$ ogr2ogr -f PostgreSQL -lco GEOMETRY_NAME=way -lco SPATIAL_INDEX=FALSE -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=YES -nln loading.ne_110m_admin_0_boundary_lines_land --config SHAPE_ENCODING WINDOWS-1252 -explodecollections -t_srs EPSG:3857 PG:dbname=gis data/ne_110m_admin_0_boundary_lines_land/ne_110m_admin_0_boundary_lines_land.shp
ERROR 1: PROJ: proj_create_from_database: SQLite error on SELECT name, coordinate_system_auth_name, coordinate_system_code, geodetic_crs_auth_name, geodetic_crs_code, conversion_auth_name, conversion_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM projected_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name
ERROR 1: Failed to process SRS definition: EPSG:3857

All this with master head on 20210123 and the latest OSM data from geofabrik.

This happens with both GB & Andorra data.

**Comment by bib1963** [comment]
Ugh... column area_of_use_auth_name is not available in proj 7.2, but does seem to be available in 7.1.1.

**Comment by pnorman** [comment]
It sounds like you've got a bug in your ogr2ogr installation.

**Comment by jeisenbe** [comment]
This happened to me on an older branch (water-color before merge with master), but I did not have the problem on the current master branch.

**Comment by pnorman** [comment]
This looks like an ogr bug, and not something we can fix.
