### ISSUE TITLE
scripts/get-external-data.py does not recognise data already downloaded

### ISSUE THREAD

**Issue by bib1963** [gravitystorm/openstreetmap-carto#4291]
### Links and screenshots illustrating the problem
This script goes away and downloads a number of files. Some of these are very large, takes time, and eats into internet data allocation.

It should be a lot smarter, preserving the source archive, checking a crc, and checking if it requires to be updated.

**Comment by pnorman** [comment]
The script uses conditional gets to only download if the files are updated. What files are you not observing this for?

**Comment by bib1963** [comment]
On Saturday, 23 January 2021 16:22:16 GMT Paul Norman wrote:
> The script uses conditional gets to only download if the files are updated. What files are you not observing this for?


Ugh... I think this may be a user error. Retrying it now, it does not fetch the files. Previously, it did appear to - it's hard not to notice the downloading of 700MB.
I think this can be closed as raised in error. If I find out why this happened, I'll re-raise.
