### ISSUE TITLE
Releasing 5.3.0

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4293]
It's been a long time since 5.2.0, and I'd like to release 5.3.0 this weekend. All approved PRs are merged, the ones which are not draft and don't have changes requested are

- #4204 
- #4204

The notes for this release will need to cover new deployment instructions for
- external data now in database, and
- new indexes, if #4204 is accepted

**Comment by jeisenbe** [comment]
Thank you for working on this @pnorman. 

#4127 is not approved yet, it still needs to be reviewed cartographically, if you are interested. But this is not urgent.

#4128 needs a consensus call. I know that’s no fun, but we have to make a decision someday.

#4292 - I wish I could review this, but it seems like the performance benefits won’t be seen unless a full planet database is used, or at least a very large database like all of Europe, correct? My system now has 16 GB of RAM, so I believe this is insufficient for the task.

**Comment by pnorman** [comment]
Done.

**Comment by pnorman** [comment]
We need to release a 5.3.1 with a fix for #4305 and #4306.
