### ISSUE TITLE
Missing translation for location point

### ISSUE THREAD

**Issue by eehpcm** [gravitystorm/openstreetmap-carto#4298]
### Expected behavior

Turn on location.  Touch centre point.  Get position/accuracy.

### Actual behavior

Turn on location.  Touch centre point.  Get missing translation error.

**Comment by jeisenbe** [comment]
This does not sound like a problem which is caused by this stylesheet, OpenStreetMap Carto, which is only a style for rendering (raster) map tiles.

Is this issue related to behavior on openstreetmap.org, or perhaps on a mobile device app?

**Comment by eehpcm** [comment]
@jeisenbe 

> This does not sound like a problem which is caused by this stylesheet, OpenStreetMap Carto, which is only a style for rendering (raster) map tiles.

I couldn't find a more obvious place to mention the problem.  Which is probably me losing the plot again.  If you can point me at the correct place I'll take it there.

> Is this issue related to behavior on openstreetmap.org,

Yep.  Location button.

**Comment by jeisenbe** [comment]
Please see https://github.com/openstreetmap/openstreetmap-website/issues to report general issues with the openstreetmap.org website (in most cases).

**Comment by eehpcm** [comment]
@jeisenbe 

Thanks for the pointer.
