### ISSUE TITLE
performance problem with rendering

### ISSUE THREAD

**Issue by andreassteiner97** [gravitystorm/openstreetmap-carto#4299]
Some time ago I searched for a new style for my OSM maps. When I found this style and implemented it sucessfully into my docker I was really happy because this map looks so much better than the old style I used before: [https://github.com/openstreetmap/mapnik-stylesheets](https://github.com/openstreetmap/mapnik-stylesheets)

Importing the OSM data into the postgis database worked as expected. When it comes to rendering the performance is not really good. The majority of the tiles take longer than 600 seconds to be renderd --> timeout. 

My machine is a Centos7 Server with 32GB RAM, 16 Cores and a lot of hdd space. On this server I run multible Docker-Containers: 
- Postgresql-Postgis 
- Mapproxy (with Mapnik) --> for rendering the tiles
- Mapcache --> for caching the tiles

I searched through multible issues with performance problems, searched through multible forums. changed the postgresql config multible times, added all indicies I found but nothing helped.  

As good as the card looks, i can't use this style because the performance of the seeding is so bad.

**Comment by StyXman** [comment]
> a lot of hdd space

The best boost you're going to get it from an SSD instead. I have 4 cores, 8GiB of RAM and I can render 8x8 metatiles in less than 10s. Also, make sure all indexes were created (see ìndexes.sql`). Also, render in metatiles, 8x8 was a good compromise for me.

**Comment by andreassteiner97** [comment]
But why is it so much slower than my old style .. example: 

seeded 24467984 tiles, now at z18 x143468 y92832
seeded 1529252 metatiles (24468032 total tiles, 24468032 non-empty tiles) in 722185.5 seconds at 33.9 tiles/sec (33.9 non-empty tiles/sec)

--> arround 2 Metatiles per second.

**Comment by StyXman** [comment]
Last time the XML version of this style was updated was some 8 years ago. Since then, this style has become way more complex, I think, rendering many many more stuff than then. I think it's reasonable it takes more time.

**Comment by andreassteiner97** [comment]
Good point. In fact is is much more faster with configuring 8x8 or 16x16 metatiles not 4x4. Thanks for the hint. 😀
