### ISSUE TITLE
Download script errors on first run

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#43]
When running with no previous files downloaded the errors

```
Warning: Illegal date format for -z, --timecond (and not a file name).
Warning: Disabling time condition. See curl_getdate(3) for valid date syntax.
```

are generated.

**Comment by kocio-pl** [comment]
We could use conditional expressions for all "curl -z" instances, starting with:

```sh
echo "dowloading world_boundaries..."
if [ -f "data/world_boundaries-spherical.tgz" ]; then
  curl -z "data/world_boundaries-spherical.tgz" -L -o "data/world_boundaries-spherical.tgz" "http://planet.openstreetmap.org/historical-shapefiles/world_boundaries-spherical.tgz"; 
else
  curl -L -o "data/world_boundaries-spherical.tgz" "http://planet.openstreetmap.org/historical-shapefiles/world_boundaries-spherical.tgz"
fi
```

We just need to know if it's worth fixing at all (this is a minor issue) and if we want more readability (simple syntax like the above code) or we want to use variables to make the code more compact and versatile?

**Comment by pnorman** [comment]
I'm wondering about completely rewriting it, because there are also problems with differences between `unzip` versions.

**Comment by kocio-pl** [comment]
Do you still plan to do that or it's better to patch it like I said?

BTW: it's the oldest open issue we have... :8ball:

**Comment by Ircama** [comment]
PR https://github.com/gravitystorm/openstreetmap-carto/pull/2137 should already address this.
