### ISSUE TITLE
Loading external data fails

### ISSUE THREAD

**Issue by tomhughes** [gravitystorm/openstreetmap-carto#4304]
### Expected behavior

Loading external data works.

### Actual behavior

Loading external data fails:

```
Traceback (most recent call last):
  File "/srv/tile.openstreetmap.org/styles/default/scripts/get-external-data.py", line 280, in <module>
    main()
  File "/srv/tile.openstreetmap.org/styles/default/scripts/get-external-data.py", line 219, in main
    download.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://www.naturalearthdata.com/http/www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
```

In fact it appears that naturalearthdata.com has been taken offline and now points at an unrelated site.

**Comment by pnorman** [comment]
Opened https://github.com/nvkelso/natural-earth-vector/issues/470 upstream

**Comment by nvkelso** [comment]
The https link works fine and is recommended:

- https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip

(note `https` and `http//www` above)

Still investigating upstream why this happened. Will update https://github.com/nvkelso/natural-earth-vector/issues/470.

**Comment by nvkelso** [comment]
The http:// link should be operational again now, too.
