### ISSUE TITLE
Need some way to get a list of external data tables

### ISSUE THREAD

**Issue by tomhughes** [gravitystorm/openstreetmap-carto#4305]
In order that the production deployment can set permissions correctly it needs to be able to get a list of the external data tables so that it can grant select permission on them.

**Comment by pnorman** [comment]
You can get a list from [external-data.yml](https://github.com/gravitystorm/openstreetmap-carto/blob/master/external-data.yml) but I think the script needs to do any permission setting or you'll have trouble between table updates and when you set permissions.

**Comment by tomhughes** [comment]
Well I'm doing it wall from chef and having it run the script and then immediately update the permissions before restarting renderd but having the script set permissions would work as well.

The model we're using in production is that osm2pgsql and the external data load run by chef run as user `tile` which has read and write access while renderd runs as `www-data` which only has read access.
