### ISSUE TITLE
Make historic=citywalls less conspicuous

### ISSUE THREAD

**Issue by michalfabik** [gravitystorm/openstreetmap-carto#4308]
### Expected behavior  
According to my understanding of https://wiki.openstreetmap.org/wiki/Tag:historic%3Dcitywalls and https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcity_wall, a good use case of the two tags would be to use `historic=citywalls` to map an area of a historical city centre that was once surrounded by walls, of which some parts may still be standing. These standing parts would then be tagged with `barrier=city_wall`. This way, it would be possible to map a particular part of a city as an area of special interest with features typical for historical fortified walled cities (such as e.g. architecture that stands out against areas outside the walls, narrower streets, denser street networks etc.), and to have actual physical walls stand out.

### Actual behavior  
`historic=citywalls` is rendered the same way as `barrier=city_wall`, making it look as though the whole area is surrounded by a fully preserved physical wall.  
  
### Links and screenshots illustrating the problem  
Historical fortified city surrounded by `historic=citywalls`:  
https://www.openstreetmap.org/relation/11741687  
  
See relation members of the above. The whole relation is rendered the same way even though some members are tagged with `barrier=city_wall` and some aren't.

**Comment by jeisenbe** [comment]
As mentioned on the linked wiki page: "A citywall is a fortification used to defend a city or settlement from potential aggressors.” This tag is also used for “existing city walls that are ruined, maybe with only foundations remaining”.

However, it is not normally used to map things which no longer exist (see https://wiki.openstreetmap.org/wiki/Good_practice#Don.27t_map_historic_events_and_historic_features).

There are no other cases where historyc=citywalls is used with type=multipolygon to map the entire area of a historic walled town. When mapped as an area, normally this tag is used to map the actual shape of the existing wall (though it is much more common to map the centreline of the wall instead). You can see all examples which are mapped as type=multipolygon areas here: https://overpass-turbo.eu/s/12YQ

**Comment by michalfabik** [comment]
Oh, I stand corrected. I suppose we could use some sort of a `historic=walled_city` or something to mark the whole area regardless of whether the walls are preserved or not. Anyway, this is beyond the scope of this "bug" so I'm closing this.
