### ISSUE TITLE
document that indexes are required in indexes.sql

### ISSUE THREAD

**Issue by stephankn** [gravitystorm/openstreetmap-carto#4309]
code to generate index and `indexes.sql` state that indexes are optional.

Release notes of 5.3.0 hint, that they are now required:

> - The recommended indexes are now required. Attempting to render without
>   them will result in abysmal performance. 

https://github.com/gravitystorm/openstreetmap-carto/blob/e77163edaaf1c2fcd9c35d6967e38c108312c8d6/scripts/indexes.py#L57

Please confirm, that indexes are no longer optional and change the comment to avoid confusion.

**Comment by jeisenbe** [comment]
@pnorman can we confirm that the indexes are still optional for rendering small areas, but strongly recommend or required for rendering the Planet or a large area (e.g. a continent)?

**Comment by pnorman** [comment]
They're required as documented at https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#custom-indexes. The indexes.sql documentation comment needs updating.
