### ISSUE TITLE
Smart users place objects a safe distance from roads

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4314]
### Zoom level 18
Smart users place objects a safe distance from roads:
![20210201T154107](https://user-images.githubusercontent.com/1230959/106428652-4893ec00-64a4-11eb-8a70-a174008af4e7.jpg)
Non-smart users don't, and these are the consequences:
![20210201T154136](https://user-images.githubusercontent.com/1230959/106428647-47fb5580-64a4-11eb-950d-9d4bed7e698b.jpg)
Yup, 90% obscured.
### Zoom level 19
Ah, finally, there it is,
![20210201T154201](https://user-images.githubusercontent.com/1230959/106428643-4598fb80-64a4-11eb-8d17-1f0681a41541.jpg)

Moral of story: smart users place items a safe distance (five meters+?) from roads, no matter how safe they might look when editing. Also if one day the road gets thicker, (via reclassification by an person editing it, or even via a stylesheet change) you will be safer. 
Yes, maybe in some countries the police will stop one from building too close to roads, so the ~~bug~~ issue never occurs there.

Sure, you might say "stop using _wireframe_ in iD".
But we never were:

![20210201T162655](https://user-images.githubusercontent.com/1230959/106433005-88f66880-64aa-11eb-8386-184f44063bf6.jpg)

**Comment by imagico** [comment]
Is there any request regarding this style in here or is this just some mapping advice?

**Comment by tomass** [comment]
Smart users capture object data as it actually is on the ground and then **displace** needed objects as much as required for each scale.

Non smart users try to do **displacement** in data which will never work as displacement will depend on scale and symbolisation of objects (f.e. width of roads) from which you will want to displace your "important" object.

**Comment by jidanni** [comment]
Well all I know is for editors, even with background imagery turned off, what looks deceivingly great in the editor, needs several double checks (editing for the renderer), to make sure will not in fact end up looking like a muffin run over by a bulldozer. That's all I know.

**Comment by pnorman** [comment]
Closing as off-topic.

@jidanni please review the [code of conduct](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CODE_OF_CONDUCT.md), in particular the avoiding destructive behavior section which covers staying on topic, unconstructive criticism, and snarking.

**Comment by jeisenbe** [comment]
I think the root of this issue is the same as #3925 - highway=tertiary features near the equator are often quite narrow, so the current rendering is too wide at z18.

This can be solved either by rendering highway=tertiary more narrowly, perhaps in concert with changing the color to light yellow and shifting the other highway classes toward red (and motorways to magenta), or by adjusting feature width based on lattitude - which is more complicated.

**Comment by jidanni** [comment]
I think it's quite interesting that this actually turns out to be a North versus South, Rich vs. poor.... Where Editors in the north countries Assume that things will look the same in the middle countries Dot-dot-dot and it all turns out to be a Mathematical problem do the curvature of the Earth! Sorry, today I'm using voice input to type this.
