### ISSUE TITLE
globe view support

### ISSUE THREAD

**Issue by 532910** [gravitystorm/openstreetmap-carto#4315]
Please add globe view support, the same as Google Maps does it:
![image](https://user-images.githubusercontent.com/14617699/106433661-8f241f00-6481-11eb-8bc7-295600e49037.png)

**Comment by imagico** [comment]
This request is off-topic here, this is a map style development and design project, how this map style is displayed to the user (i.e. the map display UI) is not our concern.  You can do so classically in Leaflet or Openlayers but there are also open source 3D display systems like CesiumJS.

**Comment by lectrician1** [comment]
See https://github.com/openstreetmap/openstreetmap-website/issues/2604 !
