### ISSUE TITLE
[name != null] not working, maybe [name != ''] neither.

### ISSUE THREAD

**Issue by StyXman** [gravitystorm/openstreetmap-carto#4318]
I just spent a great part of my afternoon trying to filter out peaks that don't have names. Here's the original code:

```javascript
  [feature = 'natural_peak'][zoom >= 11] {
    marker-file: url('symbols/natural/peak.svg');
    marker-fill: @landform-color;
    marker-clip: false;
  }
```

Here's mine:

```javascript
  [feature = 'natural_peak'][zoom >= 11][name != ''] {
    marker-file: url('symbols/natural/peak.svg');
    marker-fill: @landform-color;
    marker-clip: false;
  }
```
This doesn't work at all. The reason I report this here and not (yet) in mapnik/mapnik#1 is because the code already has this:

```javascript
  [feature = 'waterway_waterfall'] {
    [zoom >= 13][height > 20],
    [zoom >= 14][height > 10],
    [zoom >= 15][name != null],
    [zoom >= 16] {
      marker-file: url('symbols/waterfall.svg');
      marker-clip: false;
      marker-fill: @water-text;
    }
  }
```

This doesn't work either. To test this, just go to https://www.openstreetmap.org/node/5208301194#map=15/44.1560/5.0473 and see the nameless waterfall render in ZL 15. Also ZLs 13, 14 and 16.

Not sure what should we do about this, except go complain to `mapnik`.

**Comment by StyXman** [comment]
I just noticed the MapnikXML generated by `carto-css`:

```xml
    <Rule>
      <MaxScaleDenominator>400000</MaxScaleDenominator>
      <Filter><![CDATA[([feature] = 'waterway_waterfall') and ([height] > 20) and ([name] != null)]]></Filter>
      <MarkersSymbolizer clip="false" file="symbols/waterfall.svg" fill="#5a5aa1" width="16" />
    </Rule>
    <Rule>
      <MaxScaleDenominator>400000</MaxScaleDenominator>
      <Filter><![CDATA[([feature] = 'waterway_waterfall') and ([height] > 20)]]></Filter>
      <MarkersSymbolizer clip="false" file="symbols/waterfall.svg" fill="#5a5aa1" width="16" />
    </Rule>
    <Rule>
      <MaxScaleDenominator>400000</MaxScaleDenominator>
      <Filter><![CDATA[([feature] = 'waterway_waterfall') and ([height] > 10) and ([name] != null)]]></Filter>
      <MarkersSymbolizer clip="false" file="symbols/waterfall.svg" fill="#5a5aa1" width="16" />
    </Rule>
    <Rule>
      <MaxScaleDenominator>400000</MaxScaleDenominator>
      <Filter><![CDATA[([feature] = 'waterway_waterfall') and ([height] > 10)]]></Filter>
      <MarkersSymbolizer clip="false" file="symbols/waterfall.svg" fill="#5a5aa1" width="16" />
    </Rule>
    <Rule>
      <MaxScaleDenominator>25000</MaxScaleDenominator>
      <Filter><![CDATA[([feature] = 'waterway_waterfall') and ([name] != null)]]></Filter>
      <MarkersSymbolizer clip="false" file="symbols/waterfall.svg" fill="#5a5aa1" width="16" />
    </Rule>
```

I looks weird, but should not be the reason for this bug.

**Comment by kennykb** [comment]
'name != null' isn't the right thing in SQL - null ls not equal to anything, including itself.

Try 'name is not null'

**Comment by imagico** [comment]
The `name` column in the amenity-points layer in OSM-Carto is never `NULL` - because of

https://github.com/gravitystorm/openstreetmap-carto/blob/42a6baf41a6e8f7020ff005a18e2f63e75a97d1b/project.mml#L1463-L1477

https://www.postgresql.org/docs/9.1/functions-string.html

"NULL arguments are ignored."

@kennykb - We are talking about MSS code, not SQL.

**Comment by imagico** [comment]
@StyXman - does this solve your problem?

**Comment by StyXman** [comment]
@imagico `[name != '']` still doesn't work. I highly suspect `mapnik`. I'm going to close this here, but at least there's a link to the mapnik repo.
