### ISSUE TITLE
External-data.yml is missing

### ISSUE THREAD

**Issue by zsoooc** [gravitystorm/openstreetmap-carto#4325]
Hi!

I downloaded the latest version of openstreetmap-carto and tried to run get-external-data.py. It says: "No such file or directory: 'external-data.yml'. It seems that this file is missing.

Do you have any suggestions how to fix it?

**Comment by pnorman** [comment]
What exact commands did you run?

**Comment by zsoooc** [comment]
I've followed this tutorial: https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/#create-the-data-folder

git clone https://github.com/gravitystorm/openstreetmap-carto.git
cd openstreetmap-carto
cd scripts/get-shapefiles.py

It seems that this tutorial is a little bit outdated: the get-shapefiles.py is missing, so I tried to run:
./get-external-data.py

**Comment by pnorman** [comment]
Our installation instructions are at [INSTALL.md](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md) which call for you to run `scripts/get-external-data.py`. If you run it without `external-data.yml` in the current directory you'll need to specify a path, see the `--help`.

If you've got issues when following that tutorial, you'll need to take it up with the maintainers of the tutorial.

**Comment by HolgerJeromin** [comment]
ping @Ircama

**Comment by Ircama** [comment]
> ping @Ircama

Thanks for pinging. Yes, that tutorial is partially outdated at the moment, sorry for this. I'll try to find some time during this month to perform all the needed tests and do the corrections.

**Comment by Ircama** [comment]
FYI, I updated the mentioned tutorial.
