### ISSUE TITLE
Rendering of natural=couloir

### ISSUE THREAD

**Issue by hungerburg** [gravitystorm/openstreetmap-carto#4326]
A proposal is in draft for arête's cousin, the couloir - https://wiki.openstreetmap.org/wiki/Proposed_features/couloir_2 - Not the proponent myself, I see good chances for it to get approval. Unlike a spine, couloirs are always steep in the direction of the way. There a V like shape should work very well and make them easy to tell apart from spines. Rendering those will make maps more readable and bring a little bit of life into bare_rock deserts ;) Usage is currently low, no idea how rendering will affect that. I do not see how it could be misused.

**Comment by hungerburg** [comment]
No hurry. Its cousin, arete, already shows up. I understand, it cannot be retropacked with that feature. And, of course, ridge (the sibling of arete) is much more common. Gonna wait for how the proposal does. Whether or not that gets approved, I dont expect the number to explode. There are not so many famous couloirs.

**Comment by imagico** [comment]
Closing as there is so far no significant use hence no evidence if the tag is consistently used  and broadly supported by mappers nor is there any definitive documentation what the tag is being used for.

**Comment by hungerburg** [comment]
I share the concern about the weasel words in the proposal, they did not make sense to me either. As someone who thinks to know the subject matter, I did not care so much. The most famous couloir in my country, the Pallavicini Rinne is also mapped as a place=locality for a lack of other means, to get it on the carto map. Taginfo count may be misleading, but not by much.
