### ISSUE TITLE
Cursive Cyrillic fonts should be avoided

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#4327]
Some Cyrillic (Russian) names are displayed in cursive characters.
This makes them difficult to read and a reason for errors even by someone knowing Cyrillic.
For example, Замошское болото display resembles Замошское болоmо, with a "t" written like a sort of m which is in fact a cursive "t".
Cursive Cyrillic fonts should be avoided.
[map image link](https://www.openstreetmap.org/?mlat=58.7998&mlon=31.3344#map=13/58.7997/31.3344)

**Comment by imagico** [comment]
Seems to be a bug in the font used, not an issue with italic fonts in Cyrillic in general:

https://mc.bbbike.org/mc/?lon=31.3344&lat=58.7998&zoom=13&num=2&mt0=sputnik-map&mt1=mapnik

**Comment by batyrmastyr** [comment]
> Cursive Cyrillic fonts should be avoided.

I have a better suggestion: let’s remove from the output all latin chars that resemble cyrillic ones. Just about 2/3 of all latin alphabet.😏

**Comment by a-pirard** [comment]
On 09/02/2021 10.06, Christoph Hormann wrote:
>
> Seems to be a bug in the font used, not an issue with italic fonts in
> Cyrillic in general:
>
> https://mc.bbbike.org/mc/?lon=31.3344&lat=58.7998&zoom=13&num=2&mt0=sputnik-map&mt1=mapnik
>
Not a bug in a font. According to my findings, *some* fonts use *by
design* italics to represent cursive script and others don't. The latter
should be used.

All the best,

André.

**Comment by imagico** [comment]
After some research to make sense of the cryptic remarks:  The term you are looking for is *oblique*.  We use Noto Sans Italic for the labels in question which is using Russian cursive (https://en.wikipedia.org/wiki/Russian_cursive) - which is what you seem to dislike.  The problem seems to be somewhat similar to #2380.

It seems to me this is mostly a matter of taste in font style.  Requirements to change something would IMO be:

* that there is consensus in the community that an oblique font is more desirable than an italic/cursive font.
* that there is a suitable font available for that.

**Comment by a-pirard** [comment]
On 09/02/2021 15.00, Christoph Hormann wrote:
>
> ...
>
> It seems to me this is mostly a matter of taste in font style.
> Requirements to change something would IMO be:
>
>   * that there is consensus in the community that an oblique font is
>     more desirable than an italic/cursive font.
>   * that there is a suitable font available for that.
>
My message is not cryptic at all
<https://github.com/gravitystorm/openstreetmap-carto/issues/4327>, but
as one has to know what English is when speaking of it, one has to know
what Cyrillic and cursive Cyrillic are for this point.
And it is not a matter of taste.

Let's have a short lesson.

Cyrillic is mind boggling because some of its very Latin lookalike
letters like Р means in fact R and Н means N etc.
They write Россия for Russia (and СССР for Soyuz Sovetskikh
Sotsialisticheskikh Respublik).
But where the problem is getting really more intricate is when they
write Russian not the normal, printed way but in the cursive way, which
is the way they write it by hand.
Latin letter I is normally written И but is written a sort of "u" in
cursive script.
Letter D is normally Д but a sort of "g" in cursive.
Letter L is normally Л but a sort of "i" in cursive.
Letter T is normally Т but a sort of "m" in cursive.
Etc.
More readable table <https://fr.wikipedia.org/wiki/Cursive_cyrillique>
on French Wikipédia.
I say "sort of" because/,/ although I can type those letters in
Thunderbird with a Russian keyboard and use Arial font displaying in
italic the Latin-lookalike cursive character I speak of, the odds are
high that they will be mangled when you read them, and I used the Latin
characters.
It is *NOT* a question of italic/oblique style difficult to read even in
English (like #2380
<https://github.com/gravitystorm/openstreetmap-carto/issues/2380> says)
but it is because *all* the Cyrillic cursive fonts display those cursive
letters in a way that falsely looks like Latin ones.
So my point is not at all a matter of esthetics like in #2380
<https://github.com/gravitystorm/openstreetmap-carto/issues/2380> but of
mistaking a character for another.

In the map I referred to the name is Замошское болото, that is
Zamoshskoye boloto,
but the way it's written in cursive makes it very risky to be
transliterated as "bolomo".
Other examples are even more striking.

Some fonts display Russian italics as cursive and some don't.
Arial and Noto Sans do, but Comic Sans MS, Dejavu Sans, Freemono and
Latin Modern Sans and more do not, just to pick some at random.
So, it's just a matter of not using italic or of using a font that does
not display cursive.

Obviously, regarding a consensus, you would get meaningless opinions
from people not knowing Cyrillic or cursive.
The best example is that someone who made a OSM Feature Proposal
regarding languages and who stated in it that Bulgaria uses another
alphabet than Russia.
They use the same Cyrillic (see on OSM), but the guy had come across
maps showing names in cursive script (see on OSM too for italics) and he
thought that it was another alphabet.
And those understanding Cyrillic and cursive best, Cyrillic natives,
will not understand the problems that foreigners have to understand the
way they write Russian by hand.

It is those blunders that I suggest to avoid simply.

**Comment by hungerburg** [comment]
Looks like an unfortunate choice by the designers of the Noto font. For the italic/oblique style they tried to mimic handwriting, their italic T looks like a latin m - https://fonts.google.com/specimen/Noto+Sans?query=noto&preview.text_type=custom&preview.text=%D0%B1%D0%BE%D0%BB%D0%BE%D1%82%D0%BE

Of course, italic/oblique is NOT handwriting, and if even natives can be tricked, Noto is harmful. Not sure about that, there is no regular letter, that looks like a latin m, so there should be no confusion possible?

Other fonts, e.g Roboto https://fonts.google.com/specimen/Roboto?preview.text_type=custom&preview.text=%D0%B1%D0%BE%D0%BB%D0%BE%D1%82%D0%BE do not suffer from that.

Here a font closer to handwriting - https://fonts.google.com/specimen/Pacifico?preview.text_type=custom&preview.text=%D0%B1%D0%BE%D0%BB%D0%BE%D1%82%D0%BE - beware, there another detail changed…

**Comment by a-pirard** [comment]
On 13/02/2021 22.43, hungerburg wrote
    
    Looks
      like an unfortunate choice by the designers of the Noto font. For
      the italic/oblique style they tried to mimic handwriting, their
      italic T looks like a latin m ...
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gravitystorm/openstreetmap-carto/issues/4327#issuecomment-778682227",
"url": "https://github.com/gravitystorm/openstreetmap-carto/issues/4327#issuecomment-778682227",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    Italic "т" (lowercase) does.
    Not only Noto. I wrote:
    Some fonts display Russian italics as
      cursive and some don't.
      Arial and Noto Sans do, but Comic Sans MS, Dejavu Sans,
      Freemono and
      Latin Modern Sans and more do not, just to pick some at random.
      So, it's just a matter of not using italic or of using a font that
      does
      not display cursive.
    That's a few I examined randomly and the ubiquitous Arial does, and
    more...
    Century Schoolbook L, Opensymbol, Times New Roman, Trebuchet MB,
    Ubuntu, ... also do, to limit my search to some non exotic ones.
    It looks like a partially followed convention.
    It might (I don't know) stem from the fact that Russian does not use
    italic and that they used it for cursive. But what was alright when
    only Russian was written with some font has become wrong in a mixed
    language environment like OSM.

**Comment by hungerburg** [comment]
As I see this, the very question is, can this choice of so many font designers, an unfortunate for sure, but as you stress, very widely followed, cause any harm. There should be a storm of anger flowing at the distributors (google. microsoft, ITC etc.), reaching far beyond openstreetmap, if the confusion was widespread, shouldn't it? Can you give some evidence?

But as you said, perhaps they created the italic variants just for sake of completeness, and nobody uses them, outside of openstreetmap - Can this be true? Can you give some evidence?

PS: The Pacifico font has Russian sounding names on the designers list and they also changed at least the (latin letter) B, but it is not regular nor italic, it has no styles at all, it is mimicking handwriting, no more, no less.

**Comment by sommerluk** [comment]
See https://en.wikipedia.org/w/index.php?title=Cyrillic_script&oldid=1105582917#Italic_and_cursive_forms for an explanation.

In short: In Cyrillic typography, it is normal that the italic forms differs on some characters quite a lot from the regular form. And: The exact form of the italic characters are different between regions and/or languages (Russian, Bulgarian, Serbian…).

Noto, the font we are using, supports all these variants in parallel and therefore implements correctly the Cyrillic typography.

So, there is nothing to do here: The rendering is an accepted variant.

Chosing different rendering variants based on language and/or region (as said above, Noto supports all of them), we would have to find a solution for #2208
