### ISSUE TITLE
Add render support for tailings ponds.

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4328]
Tailings ponds are currently tagged `reservoir_type=tailings`, along with `natural=water`+`water=reservoir` **or** `landuse=reservoir`.  A [recently approved proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Tailings_pond) has approved the tag `man_made=tailings_pond`.

As a contaminated body of liquid or slurry, tailings ponds should not render as an ordinary water feature, and instead should have styling that suggests its hazardous composition.

See also:
https://github.com/openstreetmap/iD/issues/8347

**Comment by pnorman** [comment]
With 23 uses it would be premature to render this tag.

**Comment by tastrax** [comment]
There are however over 2500 reservoir_type=tailings which will progressively changed to the new tailings_pond

https://overpass-turbo.eu/s/1qa1
