### ISSUE TITLE
scripts/get_external_data.py cannot download ne_110m_admin_0_boundary_lines_land.zip

### ISSUE THREAD

**Issue by akb21** [gravitystorm/openstreetmap-carto#4333]
https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip is down again.

**Comment by pnorman** [comment]
Works for me. Can you provide details when you say it's down?

**Comment by akb21** [comment]
Now work for me too... But I tried two different network and proxies then ,and it didn't work. Maybe I forgot the great firewall. I'm 
 really sorry.
