### ISSUE TITLE
landuse=railway vs railway=platform

### ISSUE THREAD

**Issue by UncleOwen** [gravitystorm/openstreetmap-carto#4336]
### Expected behavior
railway=platform should be visible even if landuse=railway obscures it.

### Actual behavior
railway=platform is invisible if landuse=railway is present on another area

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/relation/6090975
https://www.openstreetmap.org/way/398260941

**Comment by HolgerJeromin** [comment]
The painters algorithm should have taken care of that. Small objects are painted later than larger ones.

[This platform](https://www.openstreetmap.org/way/178307894) is similar tagged and rendered. Perhaps the multipolygon is cause problems here...

**Comment by sun-geo** [comment]
Seems duplicate of #4008
