### ISSUE TITLE
render fixme=* with a question mark

### ISSUE THREAD

**Issue by Marc-marc-marc** [gravitystorm/openstreetmap-carto#4348]
since the purpose of the style is to give feedback to the contributors, I suggest to display the icon of a question mark for objects either on all objects with a fixme or on objects that are not rendered otherwise.
This will make these problems visible instead of expecting the user to run an editor that can warn them of the proximity of that object (which is not the case by default in iD or josm, as long as the individual object is not selected)

**Comment by polarbearing** [comment]
Well, this style has several uses. Mapper feedback is one if them. 
I'd prefer to show fixmes in a way they can be switched off, like the Notes layer, or the developer's switch in OsmAnd.

**Comment by imagico** [comment]
Being understandable and supportive for mappers is one of our goals.  But allowing mappers to paint question marks in the map by adding fixme tags does not serve this goal not is it compatible with our other goals.

This is the task for QA tools and specialized map overlays.

**Comment by polarbearing** [comment]
In addition, not all FIXMEs are solvable immediately. 
E.g. when I spot a newly constructed house, I'll map the estimated outline from the street perspective, and leave a fixme. 
Once we have fresh aerial imagery a year later, I'd be able to refine the geometry and remove the fixme. 
The question mark all the year would not help.
