### ISSUE TITLE
Add rendering for barrier=ship

### ISSUE THREAD

**Issue by kolgza** [gravitystorm/openstreetmap-carto#4355]
### Expected behavior
All large maritime obstructions should be rendered
### Actual behavior
Instances of `barrier=ship` are not rendered
### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/922435652
![image](https://user-images.githubusercontent.com/46303203/112706300-c1e30600-8e79-11eb-93ab-c66f0277b91a.png)

**Comment by kolgza** [comment]
I originally closed this just for the sake of not creating too much noise, but I've seen at least one person be for actually rendering this.

I'm not sure if I should reopen it.

**Comment by aceman444** [comment]
Is that ship permanent there? Also, the barrier=ship value does not seem agreed on and documented on the wiki. But maybe OSM carto style could still render generically any unknown values of 'barrier' to shown some barrier is at the spot.

**Comment by HolgerJeromin** [comment]
> But maybe OSM carto style could still render generically any unknown values of 'barrier' to shown some barrier is at the spot.

This was removed in #1986 five years ago

**Comment by polarbearing** [comment]
The Ever Given was afloat again around lunchtime on Monday, the example above has been deleted since.  

Waterway obstacles are probably an issue for the openSeaMap, not here.

**Comment by aceman444** [comment]
OK, it is also questionable whether to map such transient objects (lasting a few days) into OSM. Data consumers hardly notice them.
