### ISSUE TITLE
Render directions of individual lanes on a road

### ISSUE THREAD

**Issue by kolgza** [gravitystorm/openstreetmap-carto#4356]
### Description
At high zoom levels, arrows could be used to represent the lanes of a road, along with the directions of each of those lanes. This would serve to better utilize the [`lanes=*`](https://wiki.openstreetmap.org/wiki/Lanes) tag, as well as the [`change:`](https://wiki.openstreetmap.org/wiki/Key:change) prefix. This would address #4264, which was closed partly because there was no proposed solution for rendering bus lanes.
### Mockup
![carto individual lanes mockup](https://user-images.githubusercontent.com/46303203/113048827-f2c08500-9170-11eb-8e6d-3a9b8e605b5f.png)

**Comment by polarbearing** [comment]
```turn:lanes``` are well used by routers in shown in navigation, and I think there are specialised visualisation tools for checking them outside editors.
The mockup shows only examples with 3 arrows in total, and not the typical situation with 4 or more turn lanes _per direction_. 
Thus it would not fit into the typical width we render roads with.

**Comment by kolgza** [comment]
It seems that fundamental changes to how Carto functions would be needed to add this superfluous feature. This is probably even less feasible than #180.
