### ISSUE TITLE
Railway tunnels look almost the same as the open portion

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4359]
Here there is two railroad tunnel entrances, and one highway tunnel entrance. 
![20210405T100958](https://user-images.githubusercontent.com/1230959/113529856-309d2d80-95f7-11eb-97aa-dde0b8e4794b.jpg)
Compared to the highway tunnel, the railway tunnel looks almost the same as the open portion.
Also its entrance is not clearly marked.
https://www.openstreetmap.org/#map=18/24.21651/121.68910

**Comment by polarbearing** [comment]
Any constructive idea how it should look like?

The tunnel entrance is not marked for the highway either, it's just the rounded end of the open highway line. 

Railway looks clearly different for me for the open and tunneled part. First is black/white with casing, second is dashed black without white and without casing. 

I don't know if mapnik would support symbols at the end of lines?

**Comment by pnorman** [comment]
> I don't know if mapnik would support symbols at the end of lines?

This wouldn't work since the tunnel ways could be split, resulting in multiple lines.

**Comment by polarbearing** [comment]
Indeed. So unless the OP has no better idea, I propose to close.

**Comment by jidanni** [comment]
Just do the same thing you do for highways:
- Make it that much lighter.
- And add the arc at the boundary.

It is important to know where a tunnel begins.
https://en.wikipedia.org/wiki/Hualien_train_derailment
https://www.google.com/search?q=Hualien+train+derailment&tbm=isch

**Comment by jidanni** [comment]
Ah, no wonder, you are currently using "railroad in road" symbol!!
https://www.topozone.com/topographic-map-legend-symbols/

**Comment by manfredbrandl** [comment]
The arc as in Wikipedia is too big but a smaller arc my be a good idea for me.

**Comment by polarbearing** [comment]
I have some doubts that this wikipedia template is meant for automatic map rendering. 
Do you have a proposal how to solve the problem mentioned by @pnorman that the tunnel way in OSM might consist of multiple segments, and thus the end of each segment would trigger additional entrances?

**Comment by jidanni** [comment]
> ... multiple segments

Well all I know is whatever problem affects / is solved / for highways, it should also affect / be solved for railroads.

So just use one kind of rendering machinery for both, under the hood.

**Comment by manfredbrandl** [comment]
> The arc as in Wikipedia is too big but a smaller arc my be a good idea for me.

I have changes my opion: We cannot show the tunnel entrance with small railroads. I suggest closing this issue.

**Comment by jidanni** [comment]
All we got in Taiwan are Narrow Gauge small railroads but they act just like real railroads do in other countries. There was a big accident with 50 people killed just last week.

**Comment by jidanni** [comment]
https://en.m.wikipedia.org/wiki/Narrow-gauge_railways_in_Asia

**Comment by jidanni** [comment]
So again, one cannot use a North American or European view of other people's railroads. What might be a small railroad in your country might be a big railroad in my country.

**Comment by polarbearing** [comment]
> There was a big accident

Could you please refrain from linking news about accidents to carto style issues. I cannot see a causality that these incidents were avoidable with a changed carto style. 

Besides the unsolved issue of multiple segments, another issue is that multiple rails might go through the same tunnel pipe. This is probably not renderable without separate tagging.

**Comment by pnorman** [comment]
> Indeed. So unless the OP has no better idea, I propose to close.

No implementable ideas have been forthcoming. If someone does have an idea, they can open a draft PR and we can discuss it there.

Please remember that the [code of conduct applies here](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CODE_OF_CONDUCT.md), and in particular

> - Avoid destructive behavior:
>   - Derailing: stay on topic; if you want to talk about something else, start a new conversation.
>   - Unconstructive criticism: don't merely decry the current state of affairs; offer—or at least solicit—suggestions as to how things may be improved.
>   - Snarking (pithy, unproductive, sniping comments)
>   - Discussing potentially offensive or sensitive issues unless directly technically relevant; this all too often leads to unnecessary >conflict.
>   - Microaggressions: brief and commonplace verbal, behavioral and environmental indignities that communicate hostile, derogatory or negative slights and insults to a person or group.
