### ISSUE TITLE
Render `◊` icon on HOV Lanes

### ISSUE THREAD

**Issue by kolgza** [gravitystorm/openstreetmap-carto#4363]
### Expected behavior
At high zoom levels, highways tagged with `hov=designated` should be reflected in the rendering using the `◊` symbol which is associated with HOV restrictions.

### Actual behavior

HOV lanes are rendered the same as all other motorways.

### Links and screenshots illustrating the problem

How HOV lanes are currently rendered:
![image](https://user-images.githubusercontent.com/46303203/113897499-ed7ac000-9798-11eb-9c98-18190075cfa3.png)

Common road sign indicating HOV status ([source](https://openclipart.org/detail/174216/hov-2+-only)):
![image](https://user-images.githubusercontent.com/46303203/113897590-03888080-9799-11eb-95e6-13a5a270c7c4.png)

**Comment by polarbearing** [comment]
As already discussed in #4356, this style does not render any lanes. 

Unfortunately you did not give the geographical link to the example screenshot. Apparently the words "Restricted Lane" are a description and not the name of the road, thus this is a tagging error. 

Indeed asking Nominatim, such mistagged lanes are found in Pittsburgh, for example.

**Comment by kolgza** [comment]
> As already discussed in #4356, this style does not render any lanes.

"HOV lane" is a misleading term. I should have specified that I meant *separate ways* that are tagged with `hov=designated`.

> Unfortunately you did not give the geographical link to the example screenshot. 

My mistake: https://www.openstreetmap.org/way/92641578#map=15/40.4802/-80.0062

**Comment by polarbearing** [comment]
Also for ways, this style renders access restrictions only coarsely. It also does not render any PSV priorities. They are important for routing/navigating, but imho not on a general map style.

**Comment by kolgza** [comment]
I should of added a render.

![bitmap](https://user-images.githubusercontent.com/46303203/113915334-a8608900-97ac-11eb-9754-d543c3df8945.png)


I meant doing something extremely simple, like this.

**Comment by matkoniecz** [comment]
That would strongly encourage mismapping HOV lanes as a separate carriageways.
