### ISSUE TITLE
The way "shop=agrarian" are displayed

### ISSUE THREAD

**Issue by Asteliks** [gravitystorm/openstreetmap-carto#4369]
### Expected behavior
Having at least the name of the POI displayed on the map

### Actual behavior
For some reason agrarian shops are displayed only as dots on the map. There is no icon and name. 

### Links and screenshots illustrating the problem
See this for reference: https://www.openstreetmap.org/node/2706322467

**Comment by imagico** [comment]
We have a catchall for shops (see #3730) to be displayed with dot and label, In your example only a dot shows up because there is no space for the label.  See

https://www.openstreetmap.org/node/2320967610

for how it looks like with label.

Request to render a distinct symbol would be valid but note #3635.

**Comment by simonpoole** [comment]
I normally take the position that tags are mostly opaque alphanumeric values that can contain any nonsense and if it doesn't fit, who cares. However shop=agrarian could likely win the award of the most egregiously misnamed thing in OSM, so I think we should refrain from actively promoting it, particularly when there are actually well named alternatives.

**Comment by Asteliks** [comment]
> I normally take the position that tags are mostly opaque alphanumeric values that can contain any nonsense and if it doesn't fit, who cares. However shop=agrarian could likely win the award of the most egregiously misnamed thing in OSM, so I think we should refrain from actively promoting it, particularly when there are actually well named alternatives.

@simonpoole could you suggest how to improve tagging in the example presented in this issue?

**Comment by Asteliks** [comment]
> We have a catchall for shops (see #3730) to be displayed with dot and label, In your example only a dot shows up because there is no space for the label

@imagico should I understand that the name is too long? If so that is quite painful as other nodes do not share this problem:
- https://www.openstreetmap.org/node/5259891400
- https://www.openstreetmap.org/node/7114815091

**Comment by imagico** [comment]
No, in your example the name collides with the atm symbol at z19 due to #3880.

**Comment by matkoniecz** [comment]
Closing as it is general, not specific to agrarian and not really fixable.
