### ISSUE TITLE
Consider rendering forest fill under any other landuse

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#4371]
There are forest symbols, designed for being visible over `landuse=residential` and other land use.

But in some cases also green fill is displayed on top of mapped landuse (when forest area is smaller than competing areas)

### Expected behavior
Green forest fill is rendered below `landuse=residential` (and other) while symbols still are rendered above.

### Actual behavior
Sometimes green fill obscures landues

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/way/711432832#map=19/41.67983/-88.55266

`landuse=residential` being marked:

![screen02](https://user-images.githubusercontent.com/899988/114627278-4eccf280-9cb5-11eb-9007-7be77230a203.png)
![screen04](https://user-images.githubusercontent.com/899988/114627279-4ffe1f80-9cb5-11eb-81e1-508468930380.png)

**Comment by ZeLonewolf** [comment]
It is common to have minor areas of wood/forest on top of `landuse=residential` areas.  In those cases, I think the current behavior works well.

**Comment by cliffordsnow** [comment]
I like how the current rendering works. If nothing else, the basemap look nicer when we render wood/forest on top of landuse.

**Comment by talllguy** [comment]
Old but relevant issues about these overlaps #888 and #1136. The size of the area matters. I personally have mapped a lot of `landuse=residential` to the property/subdivision boundary based on the admin_level wiki. It is common to have tree areas inside these residential areas. I think the green trees should show on top of the grey residential fill in those cases.

**Comment by matkoniecz** [comment]
> I like how the current rendering works. If nothing else, the basemap look nicer when we render wood/forest on top of landuse.

That is also potential solution, if that proposed change would be rejected I will be at least able to demonstrate that fix was considered and rejected as worse than problem once someone complains again :)

AKA everything is more complicate than expected

**Comment by imagico** [comment]
I would be against removing wood/forest from the size based drawing order of the landcover layer.  As @talllguy said having smaller wood areas show up within a residential area is important for proper mapper feedback.  Yes, we have the pattern overlay, but that would not really be a proper display of the wooded area in such a case - and confusing in comparison to other small grained landcover mapping within a residential area like grass/garden.

I think the sized based drawing order plus the separate pattern overlay is the best way to be explicit about overlaps in mapping in a generic and comprehensible form.

**Comment by matkoniecz** [comment]
heh, that was quick
