### ISSUE TITLE
Roads display filter and color edition

### ISSUE THREAD

**Issue by jugurthab** [gravitystorm/openstreetmap-carto#4378]
Hi,
I'm new to OSM, I need some help to :

- Change all roads colors to color #3f3354 for all zoom levels.
- Display only roads (without buildings, water or green lands) for all zoom levels.

I have tried to change the colors in style/style.mss :
@tertiary-fill:  #3f3354 ;
@residential-fill:  #3f3354 ;
@service-fill: @residential-fill;
@living-street-fill:  #3f3354 ;
....
....
....
@bridge-casing: #3f3354;

 however, I still have roads which did not change : 

![Capture d’écran de 2021-04-19 22-15-25](https://user-images.githubusercontent.com/39241012/115297682-c6d76480-a15c-11eb-827c-f2140db874d7.png)

Thanks a lot.

**Comment by StyXman** [comment]
It's a shame there's not really a place to ask this kind of questions. The closest I know is https://discord.com/channels/413070382636072960/607265062322700308

The missing ones are `motorway`, `trunk`, `primary` and `secondary` and their `_link`s. A fuller list is in https://github.com/gravitystorm/openstreetmap-carto/blob/master/style/road-colors-generated.mss

**Comment by imagico** [comment]
> Change all roads colors to color #3f3354 for all zoom levels.

@StyXman already pointed you to road-colors-generated.mss which defines most of the road colors.  There are also still some inlined colors in roads.mss in the code.

> Display only roads (without buildings, water or green lands) for all zoom levels.

You just need to disable all the non-roads layers of the style.  Consider though that this style is exceptionally complex in road rendering compared to other styles.  If you just want to render all roads in plain uniform coloring a simpler map styles (some links can be found on the README) might be a better choice.

**Comment by jugurthab** [comment]
Thanks for all, it works.
