### ISSUE TITLE
Wrong order of rendering primary and tertiary roads

### ISSUE THREAD

**Issue by Dimitar5555** [gravitystorm/openstreetmap-carto#4379]
### Expected behavior
The tertiary road should be rendered below the the primary road.
### Actual behavior
The tertiary road is rendered above the primary road
### Links and screenshots illustrating the problem
![image](https://user-images.githubusercontent.com/19364673/115363544-3b48ec80-a1cb-11eb-94af-6a93012006a2.png)
https://www.openstreetmap.org/#map=19/42.69077/23.33843

**Comment by imagico** [comment]
This is just a wrong use of the layer tag on

https://www.openstreetmap.org/way/19790358
https://www.openstreetmap.org/way/431859927

Quoting from the [layer tag wiki page](https://wiki.openstreetmap.org/wiki/Key:layer):

_Layer is not suitable to define vertical relationships of adjoining, nearby or distant elements or areas_

Remove the `layer=1` from the above segments (where it is wrong - you could add an incline or embankment tag if applicable) and you should be fine.
