### ISSUE TITLE
Text for subway stations makes map too busy at z=14

### ISSUE THREAD

**Issue by kolgza** [gravitystorm/openstreetmap-carto#4389]
### Expected behavior
For `station=subway`, the station icon renders at z>=14, while the station text renders at z>=15.

### Actual behavior
In areas with a high density of subway stations, the text rendering obscures features to a degree where the map becomes unreadable.

### Links and screenshots illustrating the problem
The city centers of Chicago IL, New York City NY, and Philadelphia PA at z=14:
![image](https://user-images.githubusercontent.com/46303203/116095319-4b9f1280-a676-11eb-8254-ecd7ee91bfd8.png)
![image](https://user-images.githubusercontent.com/46303203/116097367-15fb2900-a678-11eb-8e82-36dbcbeb11eb.png)
![image](https://user-images.githubusercontent.com/46303203/116095227-39bd6f80-a676-11eb-9884-50e5ae02b01f.png)

**Comment by imagico** [comment]
So the suggestion as i read it is to move the starting zoom level for subway station labels from z14 to z15.

Currently we have as far as i can see:

type | symbol start | label start
------|-----------------|---------
railway=station|z12|z14
railway=halt|z13|z15
railway=station, station=subway|z14|z14
railway=tram_stop|z14|z16
highway=bus_stop|z16|z17

Seems a sensible suggestion to me.
