### ISSUE TITLE
Change rendering of landuse=forest

### ISSUE THREAD

**Issue by hungerburg** [gravitystorm/openstreetmap-carto#4393]
### Expected behavior

One of the arguments in the recent proposal down-vote of deprecating landuse=forest in favour of natural=wood was, that forest does not always equate wood. Indeed, in the early days, the recommended rendering for forest was plain green colour. Only where there are actually trees on the ground, the pattern was meant to appear, in places that where additionally tagged "natural=wood". OSM Carto should only show the trees pattern, where there are actually trees on the ground.

### Actual behavior

OSM-Carto shows forestry managed areas, that may be wastelands, scrub, scree, heath, etc. just the same as woodlands.

### Links and screenshots illustrating the problem

Well, as in fact, people map forests when they see woods, there are no samples ;) In the area of my local knowledge, I found https://www.openstreetmap.org/way/129169253 where forest overlaps scrub - You bet, what management the forestry does there? The once intended semantics seems were already lost in 2011, so OSM-Carto has the lever, to remind people of the distinction, that seem so essential and finally map all the missing woods!

**Comment by imagico** [comment]
That topic has been discussed many times already - the only common denominator in all the different ideas of what various tags related to woodland mapping in OSM mean is that both `natural=wood` and `landuse=forest` indicate _here are trees_ and nothing beyond.  In other words: [Approach 6](https://wiki.openstreetmap.org/wiki/Forest).  Almost all OSM data users interpret the tags this way and there is not even remotely a majority among mappers following a different interpretation in their work.  Based on this we have removed different rendering of the two tags a long time ago.  See https://github.com/gravitystorm/openstreetmap-carto/pull/1242#issue-27582318 and https://github.com/gravitystorm/openstreetmap-carto/issues/647#issuecomment-52816195

Suggestion to close this as declined - if we want to introduce more differentiated rendering of woodland i would suggest to introduce rendering of leaf_cycle which is used consistently and documents a meaningful distinction.

**Comment by pnorman** [comment]
> the only common denominator in all the different ideas of what various tags related to woodland mapping in OSM mean is that both `natural=wood` and `landuse=forest` indicate _here are trees_ and nothing beyond.

Yes. This is how we interpret it along with almost everyone else consuming OSM data.

**Comment by hungerburg** [comment]
I'd had wished for this to stay open a bit longer, as "the community" has decided (see proposal page), **not a least on the grounds of this distinction**, to keep the difference alive -- as a reminder, a "Rute ins Fenster". I'd have even gone so far, as to suggest to render "landuse=forest" in brown colour!

PS: one of the votes mentioned "leaf_cycle and leaf_type" as "unscientific" - I have yet to read up on this subject.

**Comment by imagico** [comment]
And just to be clear - in the proposal process you refer to the participants have just failed to reach consensus on the proposal, they have not positively decided on anything.

Anyway we are in general not making rendering decisions based on what some people in a proposal page on the wiki or in some forum discussion agree that mappers should do but based on what mappers actually do and what we can observe of that in the database.
