### ISSUE TITLE
Italic (cursive) text for regions and parks doesn't work for some scripts

### ISSUE THREAD

**Issue by soshial** [gravitystorm/openstreetmap-carto#4398]
### Expected behavior
For [Armenian](https://www.openstreetmap.org/#map=9/40.6349/45.1044) and [Georgian](https://www.openstreetmap.org/#map=10/42.5612/45.3722) script regions and parks should be italic, but they are not.

### Links and screenshots illustrating the problem
Because of this it is hard to discern cities from regions. Have a look at the screenshot (green are italic: correct; red are not italic but should be):
![Screenshot_20210503_071308](https://user-images.githubusercontent.com/100644/116838413-52320a80-abdf-11eb-9060-6041b6cfd520.png)

**Comment by pnorman** [comment]
Italics are only available for the base font, not the other scripts.
For a considerable number of labels this style will make no difference to the regular style.

https://github.com/gravitystorm/openstreetmap-carto/blob/a2077c0c8d40fb7f6d308b4ca4e8941d4c8b699a/style/fonts.mss#L189-L190

If Noto changes this, we can consider what other scripts italics would work for.
