### ISSUE TITLE
scripts/get-shapefiles.py fails to download ne_110m_admin_0_boundary_lines_land

### ISSUE THREAD

**Issue by vishantsolanki** [gravitystorm/openstreetmap-carto#4399]
### Expected behavior

failed to download 'ne_110m_admin_0_boundary_lines_land' while creating docker image 

http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip it's look down please help to check 

### Links and screenshots illustrating the problem

![image](https://user-images.githubusercontent.com/80324161/116867583-1886f100-ac2b-11eb-97ed-948c98e9de7e.png)

**Comment by moees** [comment]
I have the same problem, the link is down. Is there any other source where I can download it ?

**Comment by pitdicker** [comment]
Fixed by https://github.com/gravitystorm/openstreetmap-carto/pull/4466.
