### ISSUE TITLE
amenity=bench not shown for ways

### ISSUE THREAD

**Issue by joshinils** [gravitystorm/openstreetmap-carto#4407]
### Expected behavior
An icon of a bench is shown somewhere for they way. At least for ways with only two nodes or non-closed ways.

### Actual behavior
Nothing is shown

### Links and screenshots illustrating the problem
https://overpass-turbo.eu/s/17tq
https://www.openstreetmap.org/way/652957857
https://www.openstreetmap.org/way/915702622
https://www.openstreetmap.org/way/486570472
https://www.openstreetmap.org/way/829981829

**Comment by joshinils** [comment]
I would think this is wrong, since the wiki says "may be used on ways".
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbench

**Comment by imagico** [comment]
Duplicate of #2711.

**Comment by joshinils** [comment]
alright, i could not find that one.
