### ISSUE TITLE
capital vs. admin_centre

### ISSUE THREAD

**Issue by AntMadeira** [gravitystorm/openstreetmap-carto#4408]
Hi there.

This is not really an issue, but rather a doubt I have about the rendering of capitals and admin_centres, since the wiki is not very helpful on this.
1) A city which is a state capital with capital=4 will render differently than a city which is just a city?
2) What about a city which is admin_centre of a relation with admin_level=4? Is it rendered the same way as a city which is not an admin_centre?
3) In a given country, if admin_level=X always corresponds to capital=X, what's the use of the tag capital=*?

Regards.

**Comment by imagico** [comment]
Answers to the questions:

1. no, capital=4 affects the scoring of places so such places might be rendered earlier and with higher priority than others but the styling is identical.
2. role admin_centre on boundary relations is currently ignored (it is not supported by osm2pgsql so this is not an osm-carto issue).
3. already answered by 2.

See also #2365.
