### ISSUE TITLE
Dark theme variant

### ISSUE THREAD

**Issue by vanillajonathan** [gravitystorm/openstreetmap-carto#4412]
Create a dark theme variant. This could be useful when using a device in dark mode or at evening/night time.

**Comment by imagico** [comment]
I think this is out of scope for this style - we try to produce one cartographic design, not a set of several, that would spread our resources too thin and we would end up producing several mediocre designs rather than a single decent one.

What we try to do is making this style easily adaptable, there is room for improvement in that field w.r.t. colors - we still have plenty of colors inline in the code somewhere that could be organized more systematically for easy adjustment.

**Comment by HolgerJeromin** [comment]
Ref for a nice  filter hack:  https://github.com/openstreetmap/openstreetmap-website/issues/2332#issuecomment-727266980

**Comment by vanillajonathan** [comment]
I didn't propose several alternative styles, just a dark addition to the existing bright one.

This could perhaps done algorithmically by generating the colors by subtracting lightness from the base bright color and adding lightness to the base dark color.

Something like:

```py
from enum import Enum

BASE_LIGHT_LIGHTNESS = 100
BASE_DARK_LIGHTNESS = 0

class ColorVariant(Enum):
    LIGHT = 1
    DARK = 2

def generate_color(hue: int, saturation: int, color_variant: ColorVariant) -> (int, int, int):
    """Generate a color.

    Generate a color in HSL format given a hue, saturation and color variant.

    Args:
        hue -- The hue for the color to generate.
        saturation: The saturation for the color to generate.
        color_variant: The variant of the color to generate.

    Returns:
        A triplet representing a color in HSL format.

    Raises:
        ValueError -- On invalid color variant.
    """
    lightness = 0
    if color_variant is ColorVariant.LIGHT:
        lightness = BASE_LIGHT_LIGHTNESS
        lightness -= 50
    elif color_variant is ColorVariant.DARK:
        lightness = BASE_DARK_LIGHTNESS
        lightness += 50
    else:
        raise ValueError("Unknown color variant")
    return (hue, saturation, lightness)
```

**Comment by matkoniecz** [comment]
Are you interested in actually making and deploying such map style? In such case feel free to file issues about things that would make it easier.

But what is attempted here is complicated enough without adding expectations that colour-swapped map style would be ALSO usable.

**Comment by vanillajonathan** [comment]
I would hope to see it depoyed on the official OpenStreetMap tile server with a `-dark` suffix on the filename.

    https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
    https://{s}.tile.openstreetmap.org/{z}/{x}/{y}-dark.png

I think that an algorithm (such as the one I provided above in my previous post) could be used to generate both light and dark themes. The color hue is inputted to the algorithm which then outputs a color with lightness (and possibly saturation) adjusted depending on the theme variant.

**Comment by imagico** [comment]
Closing as we agree this is out of scope for this project.  If you want to develop a fork/add-on for this style that changes the color palette used to something with dark area fills and brighter lines/symbols - using either some algorithm or manually - and need some changes in this style to facilitate this being technically easier such suggestions are welcome.

Also relevant in that context would be http://blog.imagico.de/managing-patterns/
