### ISSUE TITLE
landuse=greenery not rendered

### ISSUE THREAD

**Issue by owiecc** [gravitystorm/openstreetmap-carto#4414]
[Tag:landuse=greenery](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dgreenery) is a catch-all tag for defining decorative green elements. It is preferred to use more specific tags but often these do not reflect the actual use (e.g. non-flowering plants). I suggest that we just render `landuse=greenery` green. 

Currently this tag is not rendered at all.

**Comment by imagico** [comment]
I am not sure what the reasoning is behind the suggestion of this issue to render landuse=greenery.

The tag is used very rarely considering its semantic scope (~8300 uses), almost all of these uses are from a small area in the Netherlands, probably an import.  The tag clearly has no broader support from mappers and documentation on the wiki clearly discourages its use.

**Comment by matkoniecz** [comment]
Closing per @imagico 

See also https://taginfo.openstreetmap.org/tags/landuse=greenery#chronology - it is basically entirely from import, partially reverted, no actual use after that...
