### ISSUE TITLE
Tamil supplement character support

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#4415]
It might be a good idea to add NotoSansTamilSupplement to the font list. This font seems to support some Tamil characters that are not supported by NotoSansTamil.

Reference: https://github.com/googlefonts/noto-fonts/issues/1532#issuecomment-647930501

**Comment by kocio-pl** [comment]
Could you show the example places where this could help?

**Comment by pnorman** [comment]
Closing as we'd need some example places to test - if we got them, we could look at adding it.
