### ISSUE TITLE
landuse=forest relation partialy rendered when shared members with leisure=park relation

### ISSUE THREAD

**Issue by Aury88** [gravitystorm/openstreetmap-carto#4427]
### Expected behavior
The landuse=forest  should be rendered over the leisure=park area in relations

### Actual behavior
when the landuse=forest multipoligon relation shares members with leisure=park relation the park is rendered and only the tree symbols in the landuse=forest area but not the dark green color filler

### Links and screenshots illustrating the problem
![Villa Borromeo](https://user-images.githubusercontent.com/3192478/123059912-89b47a80-d40a-11eb-9b88-5a37fc42e168.png)

In the left (not rendered) the forest multipoligon relation sharing members with the leisure=park multipoligon relation, on the right an equivalent forest multipoligon relation that does not share members with the leisure=park relation

park area: https://www.openstreetmap.org/#map=18/45.62890/9.31993
rendered relation: https://www.openstreetmap.org/relation/3098373
non rendered relation: https://www.openstreetmap.org/relation/3098376

**Comment by HolgerJeromin** [comment]
mapnik uses the "painters algorithm" here.
First the largest fill (forest) are drawn. On top the smaller ones (park).
And after that the tree symbols.

**Comment by Aury88** [comment]
so is this a correct behavior?

**Comment by Aury88** [comment]
not an issue
