### ISSUE TITLE
Render highway=proposed again

### ISSUE THREAD

**Issue by richlv** [gravitystorm/openstreetmap-carto#4434]
### Expected behavior

highway=proposed is rendered (in some shaded, lighter colour or such).

### Actual behavior

It's not rendered anymore.

### Links and screenshots illustrating the problem

#1654 removed highway=proposed rendering, mentioning the concerns that all kinds of not-really-feasible "proposals" were being mapped.
In most cases, though, those proposed highways would be very useful to render, as they are coming from official planning documents.
Additionally, not rendering them increases data rot, where there's little motivation to clean up proposals in map data.

This is also something other map providers do, and users do like that - for example: https://twitter.com/kasparsskincs/status/1410953346693935104 .
Mappers would benefit, as they could map streets as proposed, allowing easier transitioning to construction, then to the final tagging.

Other provider review:
* Google maps - shows proposed ways as existing.
* Apple maps - shows proposed ways as existing.
* Balticmaps - shows proposed ways with dashed lines.

**Comment by richlv** [comment]
Example from another mapping provider: dashed lines represent proposed highways.

![image](https://user-images.githubusercontent.com/112888/124283188-4e295700-db54-11eb-99d8-c77a815b52b6.png)

**Comment by richlv** [comment]
What about some people mapping really vague ideas?
Same as with people mapping pretend railways, or railways that existed 100 years ago...
Communities can clarify guidelines on what makes sense as "proposed".

From a data purist point of view, it can seem good not to render proposed highways - but from "selling OSM" point of view, we're losing.

**Comment by imagico** [comment]
It seems nothing of substance has changed since #1654/#1663 and i don't see any new arguments on the matter either.

It is clearly consensus among mappers that proposed roads - for any meaning of proposed - typically are not [verifiable](https://wiki.openstreetmap.org/wiki/Verifiability).  Looking at the data supports this.

**Comment by matkoniecz** [comment]
> Mappers would benefit, as they could map streets as proposed

Not rendering `highway=proposed` does not block their mapping.

> Google maps - shows proposed ways as existing.

No idea why it would be considered as worth emulating, showing nonexisting way as existing does not seem to be a good idea.

Likely Google has simply wrong data in your area (in my region it occasionally even routes along nonexisting roads).
