### ISSUE TITLE
rendering error

### ISSUE THREAD

**Issue by j47996** [gravitystorm/openstreetmap-carto#4437]
### Expected behavior
All "wood" area rendered.

### Actual behavior
Parts of wood not rendered. Possibly influenced by adjacent cliff?
Z-level dependent.  Appears at 16, not 15.

### Links and screenshots illustrating the problem

https://www.openstreetmap.org/#map=16/50.7134/-1.4516
compare with
https://www.openstreetmap.org/#map=15/50.7134/-1.4516

**Comment by imagico** [comment]
That's not a style issue, that is just different age of the rendered tiles served by the tile servers resulting in inconsistencies at the tile edges.

Triggering a re-rendering using the `/dirty` option solves this.
