### ISSUE TITLE
peak/amenity point order not working?

### ISSUE THREAD

**Issue by StyXman** [gravitystorm/openstreetmap-carto#4439]
The OSM project file has a computed field for determining peak order here:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L1542

This same query is used for labeling here:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L2038

I found a case where I think it shows what I'm otherwise experiencing in my fork: order seems not to be used. In this link, we can see an unlabeled peak, close to a nameless but labeled one.

https://www.openstreetmap.org/?mlat=43.9697&mlon=7.6338#map=13/43.9697/7.6338

if we zoom in once, the label appears, and shows that the peak is higher that the nameless:

https://www.openstreetmap.org/?mlat=43.9697&mlon=7.6338#map=14/43.9697/7.6338

What I tried to do was to add some score to other points so they have precedence over others, like city gates, castles, forts and more, like this:

```sql
              CASE
                -- local: these are shown before mountain peaks or saddles; keep score above 9000
                WHEN tags->'sport' IN ('climbing') THEN 10000 -- higher than anything
                WHEN man_made='cross' THEN 9900
                -- important things that are not necessarily at peaks, but that we want to render before other stuff
                WHEN historic IN ('city_gate', 'castle', 'fort') THEN 9800
                WHEN "natural" IN ('peak', 'volcano', 'saddle') THEN
                  CASE
                    WHEN tags->'ele' ~ '^-?\d{1,4}(\.\d+)?$' THEN (tags->'ele')::NUMERIC
                  END
                WHEN waterway IN ('waterfall') THEN
                  CASE
                    WHEN tags->'height' ~ '^\d{1,3}(\.\d+)?( m)?$' THEN (SUBSTRING(tags->'height', '^(\d{1,3}(\.\d+)?)( m)?$'))::NUMERIC
                  END
              END AS score,
```

For instance, this doesn't make this city gate render before the man made tower that I guess it's on top of it:

https://www.openstreetmap.org/way/89316698

Any ideas?

**Comment by StyXman** [comment]
I forgot to mention: I ran the query by hand and effectively it's ordered, maybe mapnik is using another (dis)order?

**Comment by imagico** [comment]
I think in your case example the 1556m peak label to the southwest is blocking the 1551m peak label at z13.  See the following with the z14 label pasted into a z13 screenshot to show the dimensions.

![peaks](https://imagico.de/files/carto_peak.png)

What would be worth considering for peaks is to try placing ele only and/or name only labels for peaks after (non-successfully) trying to place a name + ele label - cases like this might be less confusing that way.

**Comment by StyXman** [comment]
> try placing ele only and/or name only labels for peaks after (non-successfully) trying to place a name + ele label

but for that you need either support from the renderer or a more complex query that dupes the elements, one with the long label and another without, right?

> the 1556m peak label to the southwest is blocking the 1551m peak label at z13

OK, I'll try to find another example, or close this one and move the discussion to the forum.

**Comment by StyXman** [comment]
Ok, I can't find an example, and the tower/city gate dichotomy is actually originated because the polygon is tagged as both w/o `tower=defensive`. I guess this is a non issue. Closing.

**Comment by imagico** [comment]
> but for that you need either support from the renderer or a more complex query that dupes the elements, one with the long label and another without, right?

Yes, you need to duplicate the features with something like:

```
SELECT
    ...
  FROM
    (WITH pois AS (SELECT ...)
    SELECT
        ...,
        ... AS name,
        1 as priority
      FROM pois
    UNION ALL
    SELECT
        ...,
        ... AS name,
        2 as priority
      FROM pois) AS _
  ORDER BY
    ...,
    priority
```
