### ISSUE TITLE
Don't render track roads at z13 or z14

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#4440]
Their rendering tends to get kind of wacky at those zoom levels. Especially when there are multiple track roads mapped in the same area or if they are curved. I don't think they need to be rendered at z13 or z14 anyway. Since a lot of them are either private or not generally drivable (I'd be interested to know how many are tagged with surface=asphalt or similar. Whatever the number, they aren't major roads). 

Z13
![Trackroads Z13](https://user-images.githubusercontent.com/30259065/126028049-caf1442f-822b-4e9b-9719-9cd5a04ec6f6.png)

Z14
![Trackroads Z14](https://user-images.githubusercontent.com/30259065/126028056-9b7a474e-d761-412d-98b1-c61b7cb7551f.png)

**Comment by imagico** [comment]
Related to #3798 and #765, clashes with #1591.

Keep in mind that in terms of road rendering systematics removing highway=track from z13/14 would require removing cycleway/footway as well - which in turn would render the map even more useless for non-motorized navigation in non-urban contexts than it is right now (after in particular #747 and #3467) - see also https://github.com/gravitystorm/openstreetmap-carto/issues/3808#issuecomment-503034693.

A workable way of rendering tracks and paths at z13/14 has been shown in http://blog.imagico.de/drawing-the-lines/.

**Comment by imagico** [comment]
And please always provide links to your sample locations.

**Comment by Adamant36** [comment]
>And please always provide links to your sample locations.

https://www.openstreetmap.org/#map=13/40.1038/-122.3933

**Comment by Adamant36** [comment]
> Keep in mind that in terms of road rendering systematics removing highway=track from z13/14 would require removing cycleway/footway as well

That might not be a bad thing at z13. Paths and service roads aren't rendered at that level either. Footways aren't any more important then service roads. Also, I think it's a bad premise to call not rendering them at z13 useless. It's not like people can't just zoom in one more level to see footways if they need to. No one is checking out the details of footway at that level anyway. 

> A workable way of rendering tracks and paths at z13/14 has been shown in http://blog.imagico.de/drawing-the-lines/.

I had thought of that, but it's pretty unlikely anyone is going to write the code for it or deal with the other stuff that they would have to for it to merged. Whereas, there's a good chance someone will just change a zoom level. Which takes almost nothing.

**Comment by lectrician1** [comment]
I would be for removing footways at Z14 and Z13. They look pretty weird and are not necessary as they are in Chicago here: https://www.openstreetmap.org/#map=14/41.8737/-87.6136

**Comment by jeisenbe** [comment]
Re: "a lot of them are either private or not generally drivable”

The definition of highway=track does not include that access is private, or that they are not accessible to ordinary passenger vehicles. These are roads mainly used for forestry, agriculture, ranching, or sometimes recreation. 

Rural areas have track roads stretching for many kilometers. If they are not shown on z13 and z14 it will not be possible to see the road network in those places. 

E.g. https://www.openstreetmap.org/#map=13/52.2741/5.8799
<img width="744" alt="Screen Shot 2021-09-19 at 00 01 02" src="https://user-images.githubusercontent.com/42757252/133918644-7cacbd83-6080-4895-be8c-781709ee924a.png">

https://www.openstreetmap.org/#map=13/20.7347/-156.3797
<img width="744" alt="Screen Shot 2021-09-19 at 00 06 52" src="https://user-images.githubusercontent.com/42757252/133918758-4ed11ca9-ca8f-4400-9bb3-3f833caaf800.png">

**Comment by Adamant36** [comment]
> The definition of highway=track does not include that access is private, or that they are not accessible to ordinary passenger vehicles. These are roads mainly used for forestry, agriculture, ranching, or sometimes recreation.

Sure, it's not in the definition, but that's just the nature of the roads. A good portion of "forestry, agriculture, ranching" roads are private whatever OSMs definition of a track road is. Recreation roads not so much, but it would still be worth making an exception in render ones that are not so boldly (if at all). 

> Rural areas have track roads stretching for many kilometers. If they are not shown on z13 and z14 it will not be possible to see the road network in those places.

In a good portion of the cases they are blocked at their entrances by barriers though and can't (or shouldn't be) driven down by 99% of the people who are viewing the style. In no way are such roads part of the road network either. Nor does that change just because of how far the track road goes for.

**Comment by Adamant36** [comment]
Another example of where the rendering is bad at z13. It really shouldn't look like there's large gabs in the track roads when they don't exist in real life. 

https://www.openstreetmap.org/#map=13/39.1250/-122.2290

![Track roads z13](https://user-images.githubusercontent.com/30259065/135701900-ad377d75-67c7-459f-86c1-b9b8168a3c5e.png)
