### ISSUE TITLE
visual distinction between different types of raceways

### ISSUE THREAD

**Issue by sevku** [gravitystorm/openstreetmap-carto#4462]
It would be nice to have a visual distinction between different types of raceways. I'm especially thinking of sport=motor vs sport=rc_car:

![image](https://user-images.githubusercontent.com/23403917/132484386-e73ba3d2-3e2b-4c3e-a7e3-73840aab3f82.png)

left is rc and right is motor, it would be nice to have a distinction between them. Even if just that the lines for the rc cars isn't as wide

**Comment by imagico** [comment]
`highway=raceway` has 32k uses, 12.6k in combination with `sport=motor`.

`sport=rc_car` has a total use number on ways of 661 - the majority of them not in combination with `highway=raceway` (`leisure=track` being the most common primary tag, `leisure=pitch` and `leisure=sports_centre` also being common).

The [wiki page](https://wiki.openstreetmap.org/wiki/Tag:sport%3Drc_car) for the tag has been [changed last year](https://wiki.openstreetmap.org/w/index.php?title=Tag%3Asport%3Drc_car&type=revision&diff=2054956&oldid=1924172) from suggesting `leisure=track` to suggesting `highway=raceway` by a user with only two edits on the wiki.

If you ask me - tagging wise tagging am rc car track as `highway=raceway` makes as much sense as tagging a model airplane flying area as `aeroway=aerodrome`.  But that is kind of an off topic discussion here.

Related to #844.

**Comment by sevku** [comment]
@imagico Indeed I thinking the same: is there really any sense in mapping the rc track in its detail. It wasn't me who mapped that. An I guess I might change it from a track to an area. It just makes more sense.

Though I think it would still be nice to have a distinction between car race and motorbikes. but for now, the issue I had is probably resolved.

**Comment by sevku** [comment]
![image](https://user-images.githubusercontent.com/23403917/132495027-a72a367e-32db-4949-a1d6-4a38941e9c5b.png)
A lot better I think thanks.
