### ISSUE TITLE
[suggestion] golf course colors - recent change - color for putting greens should be more green

### ISSUE THREAD

**Issue by boxer4** [gravitystorm/openstreetmap-carto#4479]
### Expected behavior
Putting greens should be brighter green as it usually has the best quality grass on a golf course.

### Actual behavior
The recent change in default colors for the default layer has a more blue-ish hue for putting greens, making them somewhat look like water hazards which is something that golfers actively try to avoid.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=19/40.45731/-104.97406

**Comment by boxer4** [comment]
Sorry about erroneous report.  It decided to post when I pressed enter by mistake.  Now I need to figure out how to change the title.

Anyway there was a recent change to the renderer for the default OSM tiles where golf course colors changed.  It wasn't a big issue except that putting greens look a bit too blue and sort of look like water hazards.  Just a suggestion to perhaps change the color a bit more green so that water hazards and putting greens are a bit more distinct.  Saving this for now so people are aware that I'm not talking about an accidental emoji title...

**Comment by HolgerJeromin** [comment]
ref golf implementing PR #4381

**Comment by jeisenbe** [comment]
This is a request to change the `pitch` color, which is also used for golf greens, I believe, similar to prior issue #1190 which was closed a that time by #2363 in 2016 which made the pitch color lighter but not much less blue - unfortunately that PR also made the pitch border line a little too prominent. We discussed using the old `@golf_course` color for pitches in issue #3517

**Comment by jeisenbe** [comment]
But be aware that some users have complained that the current color choices are too low contrast overall: #3647 - and we don’t have an overall consensus on color design - #2270

**Comment by boxer4** [comment]
Thanks, looks like others share my sentiment and this is actually a duplicate issue.  No problem either way, I don't even golf but just noticed it when drawing the putting greens especially when zoomed out, it's hard to tell the difference between a water hazard or putting green.

Yes color limitations is something, perhaps something to consider - it's not necessarily that all golf courses are well mowed except for fairways, tee boxes, and greens; and to some extent rough, but the rest of the course tends to be unplayable scrub/trees and out of bounds anyway, and you can add some red->brown into those regions and not be too far off.

But carry on, I don't even play golf, just was a bit alarmed drawing golf hole ways straight into a water hazard (until you look at it real close!)
