### ISSUE TITLE
render natural=desert

### ISSUE THREAD

**Issue by abdullahO2** [gravitystorm/openstreetmap-carto#4488]
Make rendering of areas tagged with:
**natural=desert** + **surface=sand**
(natural=desert is not currently rendered)
Like areas tagged with:
**natural=sand**
![image](https://user-images.githubusercontent.com/61907628/138880143-6e4b8a68-5f7a-4cb1-bb01-5b22901d1b51.png)

**Comment by imagico** [comment]
Closing as we previously deliberately removed rendering of natural=desert and the tag is generally considered poorly defined and non-verifiable.  Further development of tagging arid region physical geography, specifically dunes and dune-fields, would definitely be desirable and if established could be considered for rendering here.
