### ISSUE TITLE
Render club= in general

### ISSUE THREAD

**Issue by Fizzie41** [gravitystorm/openstreetmap-carto#4489]
This is the same sort of issue as "Render club=scout" #4199, but I thought a different suggestion should possibly be done as a separate issue? If it would be better kept together, could somebody please combine the two?

Similar to the scout issue discussed, I have been mapping the new club=cadet tag, which naturally doesn't render, so I've been thinking about possible solutions.

As mentioned previously, there are ~35000 uses of club=*, including ~16000 club=sport which do sort of render, depending on just how they are tagged (e.g. leisure=sport_centre).

So there are 19k "other" clubs, but there aren't a "lot" of any single one.

So, instead of a host of individual icons, which will never happen, how about rendering them all together as club=*, using something similar to the iD icon of two hands shaking e.g. 
https://www.openstreetmap.org/edit#map=21/-26.87855/152.10275 
or:
![image](https://user-images.githubusercontent.com/35707521/141058644-e13fc38a-22cb-4f83-995d-1938f271bcce.png)
(Please excuse the size!)

Yes, it would be very small to make out what you're looking at, but as long as there was something there, that said, as per my example, "Blackbutt Lions Club" that would achieve the desired effect of showing where & what that Club is!

Would that work?

Thanks,
Graeme

**Comment by polarbearing** [comment]
The problem with club=* is its inconsistent usage combined with its indifferent heterogenous meaning. There are sports clubs, socially oriented associations, and in Germany I found a lot of associations that have the legal form of 'eingetragener Verein' (e.V., registered association) that have a completely different purpose than what you understand as a club, but are tagged as such. 

As a geo database, we want to show the physical elements, not the legal construct. 

For the physical location, there are rendered tagging schemes such as amenity=community_centre + community_centre=club_home for the place where people meet, office=* for the headquarter, or as you mentioned the leisure=* tags. 

For the icon example, please remember we have 14 square pixels for the icon, thus such details would not work.

**Comment by imagico** [comment]
Thanks for the suggestion.

@polarbearing already explained some of the points that speak against it.  For future reference - from my perspective the core issues with this idea are:

* We do not - with very few exceptions - render keys, we render tags.  This stems from our goal to support mappers in consistent tagging.  Rendering a catch-all for all values with a certain key does not do that.
* The tags using the club=* key are both in documentation and in practical use extremely broad - they overlap with a lot of more broadly used tags many of which we already render.
* The most common value club=sport for example is used for both places where sports are actually performed (for which the more common tag is leisure=sports_centre) and for places where sports are managed/organized (i.e. a club office - for which, as @polarbearing mentioned, there are also other tags).  Having a unified rendering for both is not really helpful for the map user.
* As already mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/4257#issuecomment-739060607 rendering facilities open to the public (like clubs whose activities are open to the public) and private ones (members-only clubs) in a common design is questionable regarding map usefulness.
* When selecting and designing symbols the practical ability of the target map users to identify the feature class and to distinguish it from other features rendered is key.  The symbol of shaking/holding hands has very different connotations in different cultures and differentiation from how we render [amenity=community_centre](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcommunity_centre) is not clear at all IMO.

I suggest to open issues for rendering specific values if that seems to be useful w.r.t. the goals of this style.  We already have #4199 for club=scout.
