### ISSUE TITLE
Diacritics in a particular vilage label are rendered at wrong places

### ISSUE THREAD

**Issue by LEdoian** [gravitystorm/openstreetmap-carto#4490]
The name of the Czech village "Břežany II" is rendered with the carons over 'e' and 'a' instead of 'r' and 'z'. This happens both on the label for the village and for border of its area. Also, similar issues are found on several other layers featured at [osm.org](https://osm.org). The name seems to be written in correct UTF-8 (the roman 'II' is written using U+2161, rather than two i's).

The village is here: https://www.openstreetmap.org/relation/441243#map=13/50.0865/14.7830

The wrong renderings:
![image](https://user-images.githubusercontent.com/3229356/141488484-75887317-590a-4399-80ea-0cc261d31a02.png)
![image](https://user-images.githubusercontent.com/3229356/141488524-17aad9e5-f2cd-495f-925f-55a4986044aa.png)

For some reason, the bus stop in the village has correct rendering:
![image](https://user-images.githubusercontent.com/3229356/141489908-aa0dc7f4-d779-4399-87ca-e35520437376.png)

I don't think I've seen such misrendering for any other place.

(Also, I am not sure whether this belongs here or to the operations bug tracker. The [wiki](https://wiki.openstreetmap.org/wiki/Standard_tile_layer) says that it belongs rather to the operations' repo, but that issue tracker doesn't seem to me as being map/rendering related.)

**Comment by sommerluk** [comment]
The default font is Noto Sans. U+2161 is not part of Noto Sans.

I suspect that because of the missing U+2161 in Noto Sans, Mapnik falls back to the next font that has Latin characters and also U+2161 which maybe is Noto Sans CJK who's Latin characters are borrowed from Source Sans (instead of Noto Sans), and Source Sans has no support for these diacritics. But that's just raw guess…

**Comment by imagico** [comment]
I can't reproduce the problem with my local test environment and it also seems to be non-universal in deployments of the style and derivatives of it, see:

http://tools.geofabrik.de/mc/#13/50.0956/14.8041&num=4&mt0=geofabrik-basic-pastel&mt1=geofabrik-basic-colour&mt2=geofabrik&mt3=geofabrik-topo

https://mc.bbbike.org/mc/?lon=14.807683&lat=50.091859&zoom=13&num=4&mt0=mapnik-bw&mt1=mapnik&mt2=osm-ch-standard&mt3=mapnik-german

I would assume it is a problem of the specific versions of the fonts used - and deployments which show the error differ from those which don't in that regard.  If that is the case this is nothing we can solve here.  Identifying the exact cause would require someone with a test environment that shows the error.

**Comment by sa1phx** [comment]
Hello, it looks like problem with rendering in some zoom level: 

![image](https://user-images.githubusercontent.com/100022554/159019410-3471626a-90e5-4d0d-9c5b-01379638e891.png)

**Comment by LEdoian** [comment]
Another instance is at Třeboň. Here the name of the town is OK, but the part "Třeboň II" is again written using the character for roman numeral, and the diacritics get misplaced.
<https://www.openstreetmap.org/node/1599164419#map=14/49.0058/14.7880>
![image](https://user-images.githubusercontent.com/3229356/160218346-fcab81a6-1459-4288-b2ea-1ad4a411b4d5.png)

@sa1phx I feel like that is a different issue, since for both Břežany and Třeboň it happens consistently across zoom levels, as long as the label contains Unicode roman numeral character (the bus stop at Břežany seems to have two I's in the name, I can select them independently in node detail). I do not know, what the issue for Žilinská Lehota is, but it renders correctly for me at osm.org ([link](https://www.openstreetmap.org/#map=12/49.2211/18.6182)).

I now think that this issue is related to the Unicode roman numerals. I am not confident enough to change the issue title though.

**Comment by pnorman** [comment]
Is this rendering correct?
![image](https://user-images.githubusercontent.com/1190866/178681181-c43757e4-366b-45c1-ab5c-179f952171d4.png)

Rendered with fonts-noto packages of 20201225-1

**Comment by LEdoian** [comment]
On 13. 07. 22 9:58, Paul Norman wrote:
> Is this rendering correct?
> ![image](https://user-images.githubusercontent.com/1190866/178681181-c43757e4-366b-45c1-ab5c-179f952171d4.png)

No, the carons should only be above 'r' and 'z', not the vowels 'e' and 
'a'. The vowels should be rendered exactly as in English.

(Also, even if the carons would be placed above vowels (which they can't 
in Czech) they would be above the letters, not intersecting any part of 
the letter. So the rendering is wrong even in that sense, but that is 
not this issue.)

**Comment by pnorman** [comment]
My system has the same version of fonts-noto as the OSMF tileservers, so this involves more than just font versions. I'm using Kosmtik with node-mapnik as a binary blob, so I'm not sure of all the versions.

I believe I'm using system fontconfig, which is 2.13.1-4.2 on my Debian box, and the OSMF servers are using 2.13.1-2ubuntu3 but will move to 2.13.1-4.2ubuntu5 with the upcoming OS upgrades. Although fontconfig has been an issue in the past with rendering differences, I don't see it as being a cause here.

Maybe a harfbuzz difference?

I tried updating the rendering DB to change 'Břežany Ⅱ' to 'Břežany' and got the correct diacratics

![image](https://user-images.githubusercontent.com/1190866/178693890-45aded98-fb3f-4523-b29c-6680c2e82eb2.png)

I have a few things to try
- [ ] Move to a local copy of noto with the same version
- [ ] Update local noto to the latest from github
- [ ] A fontconfig virtual font

I'm not very optimistic we can fix this, and it might be an upstream issue.

**Comment by pnorman** [comment]
Also worth noting is that lots of systems will get the roman numeral wrong. As an example, my console displays a box for it, and I use fonts with decent unicode support.

**Comment by sommerluk** [comment]
> The default font is Noto Sans. U+2161 is not part of Noto Sans.
> 
> I suspect that because of the missing U+2161 in Noto Sans, Mapnik falls back to the next font that has Latin characters and also U+2161 which maybe is Noto Sans CJK who's Latin characters are borrowed from Source Sans (instead of Noto Sans), and Source Sans has no support for these diacritics. But that's just raw guess…

I've tested this now and indeed this the actual problem.

Furthermore: U+2161 in supported by Noto Sans Symbols. Our current font list is:
- "Noto Sans Regular",
- "Noto Sans CJK JP Regular",
- […]
- "Noto Sans Symbols Regular",

Because Noto Symbols has a lower priority, Noto Sans CJK is preferred as the first font that supports all symbols, but Noto Sans CJK has the above described issues.

I'm not sure if reordering the font list (putting Noto Sans CJK at a lower priority) would solve this issue or not. If it would solve it, we would have to verify if this has side-effects…

> For some reason, the bus stop in the village has correct rendering

This is because the bus stop label does not has the U+2161 ROMAN NUMERAL TWO, but instead two times the U+0049 LATIN CAPITAL LETTER I.

**Comment by pnorman** [comment]
> I'm not sure if reordering the font list (putting Noto Sans CJK at a lower priority) would solve this issue or not. If it would solve it, we would have to verify if this has side-effects…

I think we should. For Arabic we state

> The Arabic fonts are placed behind Sans fonts
because they might re-define some commonly used signs like parenthesis or
quotation marks, and the arabic design should not overwrite the standard design.

This applies to CJK as well.
