### ISSUE TITLE
Feature request: Use a 3D globe instead of a 2D (I'm guessing a mercator) projection of the globe

### ISSUE THREAD

**Issue by K4LCIFER** [gravitystorm/openstreetmap-carto#4495]
Full zoom out looks like this currently:
![image](https://user-images.githubusercontent.com/7829231/143725977-e704b55a-999c-4571-ba59-54b89160feaa.png)
Google Maps does the following which I think is much better:
![image](https://user-images.githubusercontent.com/7829231/143725985-c052826b-4d03-4b07-87fd-5bb692671b86.png)

**Comment by imagico** [comment]
This is about the map display and navigation interface so out of scope for this project.

We should of course encourage changes that make this style more projection agnostic - allowing style users to render in projections other than mercator (including but not limited to perspective projections like used by google at low zoom levels) without the need for larger adjustments.

**Comment by lectrician1** [comment]
This was also asked on this issue: https://github.com/openstreetmap/openstreetmap-website/issues/2604

**Comment by lectrician1** [comment]
and this one: #4315
