### ISSUE TITLE
Render of `waterway=drain`+`bridge=*` like a `highway=*` 

### ISSUE THREAD

**Issue by LaoshuBaby** [gravitystorm/openstreetmap-carto#4500]
### Expected behavior

Drains that is on aqueduct should at least be coloured blue as the water color

### Actual behavior

Carto treated it like a highway, it was coloured white

##### Current

![图片](https://user-images.githubusercontent.com/42690037/144581164-889a499d-ec11-475c-8e36-dabc6bb1d2e5.png)
[Link: way936489491 in GB](https://www.openstreetmap.org/way/936489491)

##### Current

![图片](https://user-images.githubusercontent.com/42690037/144581318-2ecb3134-5fb2-4dd7-861a-28ff9ae6c284.png)
[Link: in CN](https://www.openstreetmap.org/#map=16/36.6705/118.4377)

**Comment by imagico** [comment]
This seems to be a bug introduced in #2594 by moving the water line styling before the bridge styling for minor waterways.

**Comment by danieldegroot2** [comment]
_Duplicate of #3497._

**Comment by imagico** [comment]
Good point, we missed that.
