### ISSUE TITLE
Use another symbol for the LDS places of whorship

### ISSUE THREAD

**Issue by Xevib** [gravitystorm/openstreetmap-carto#4502]
### Expected behavior
- The temples and churches of LDS (aka mormon) should appear with the symbol of the Moroni angel or the Christus
### Actual behavior
- The LDS (aka mormon) temples and churches appear with the symbol of a crucifix. 
#### Church
[Link to OSM](https://www.openstreetmap.org/node/5327615553)
![imatge](https://user-images.githubusercontent.com/2422305/145229528-9e18067b-3eed-48b7-8ad5-665d04d3bd19.png)

#### Madrid temple
[Link to OSM](https://www.openstreetmap.org/way/145953136)
![imatge](https://user-images.githubusercontent.com/2422305/145229425-8d499234-4bfb-4f35-aceb-6b78a1af8d48.png)

#### Additional information
- [Wikipedia article about symbolism on the LDS church](https://en.wikipedia.org/wiki/Symbolism_in_The_Church_of_Jesus_Christ_of_Latter-day_Saints) (specially the Guidelines part)

**Comment by Xevib** [comment]
Seems the issue is here https://github.com/gravitystorm/openstreetmap-carto/blob/master/style/amenity-points.mss#L611

**Comment by imagico** [comment]
See also #3800, #4225.

The two examples shown use `denomination=latter_day_saints` - which has 426 uses -  `denomination=mormon` has 7131 uses.  So tagging seems to be somewhat disputed here.  Regarding the problem in general - See the suggestion in https://github.com/gravitystorm/openstreetmap-carto/issues/3800#issuecomment-500248866.

**Comment by Xevib** [comment]
@imagico Yes, there are multiple denomination values , if the change is done it have to applied to the two values.The LDS church does not refer itself using the term mormon.

**Comment by imagico** [comment]
As a general principle we want to avoid supporting the proliferation of tags so we try not to interpret tagging on which there is no consensus among mappers.  In this case my suggestion from https://github.com/gravitystorm/openstreetmap-carto/issues/3800#issuecomment-500248866 would avoid this problem by positively rendering only christian denominations which use the cross with the cross symbol and rendering all others (and plain religion=christian) with a generic place of worship symbol.

I don't think there is going to be consensus for rendering individual denominations with distinct symbols because this would quickly lead to an exorbitant growth in the number of symbols.

**Comment by 1ec5** [comment]
> positively rendering only christian denominations which use the cross with the cross symbol and rendering all others (and plain religion=christian) with a generic place of worship symbol

For sure, this conservative approach has the benefit of avoiding having to hard-code exceptions that don’t use the cross, but the downside would be having to hard-code each of the non-exceptions, the Christian denominations that do use the cross. There are simply too many to list, many of them with too few locations in reality to ever consider special-casing in software. It’d be similar to the challenge of developing icons for individual denominations. I would expect the non-cross-using denominations to be a much more manageable set, even if we were to accommodate both `mormon` and `latter_day_saints`.

Some renderers have avoided having to hard-code denominations at all by using a generic icon for all places of worship, regardless of religion or denomination. But that’s an editorial decision that may disappoint some members of the community, given the effort that has gone into developing religious icons for this project over the years.
