### ISSUE TITLE
Problem with get-external-data.py

### ISSUE THREAD

**Issue by bpg-software** [gravitystorm/openstreetmap-carto#4504]
Hi,
probably is my fault, but I have a problem with get-external-data and I was unable to solve it.
My goal is to create a OSM server using a Linux box with Ubuntu 16.04. I am following a guide of  [switch2osm](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-16-04-2-lts/).

My problem in is step:
scripts/get-external-data.py
I receive error:
	Traceback (most recent call last):
	  File "scripts/get-external-data.py", line 29, in <module>
	    import psycopg2
	ImportError: No module named 'psycopg2'

but if I run "pip2 list" I receive:
psycopg2                  2.6.1
psycopg2-binary           2.8.6

and with "python --version" I receive
Python 2.7.12

I already tried to install python-psycopg2 with apt-get and psycopg2-binary using pip or pip2 but I have the same error.

Someone have some suggestions?

Thanks a lot

**Comment by mmd-osm** [comment]
FYI: Other issues on Ubuntu 16.04 reported by same user: https://github.com/switch2osm/switch2osm.github.io/issues/177

It should be noted that both Ubuntu 16.04 and Python 2 are no longer supported. get-external-data.py requires Python 3.

-> Suggesting to close this issue.

**Comment by pnorman** [comment]
> I already tried to install python-psycopg2 with apt-get and psycopg2-binary using pip or pip2 but I have the same error.

You need to install the [Dependencies](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#dependencies) which include Python 3 with the psycopg2, yaml, and requests libraries (`python3-psycopg2` `python3-yaml` `python3-requests` packages on Debian-derived systems)

**Comment by bpg-software** [comment]
I asked my question twice because I didn't know if the problem was in my device, in documentation or in openstreetmap-carto.
Now I solved my problems with get-external-data with the command
`update-alternatives --install /usr/bin/python python /usr/bin/python3 1`

In this way python3 has become the default. After I installed python3-psycopg2 with apt.

Thanks a lot

**Comment by SomeoneElseOSM** [comment]
> It should be noted that both Ubuntu 16.04 and Python 2 are no longer supported. get-external-data.py requires Python 3.

If that's the case then it might make sense to update https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md to say something other than "On Ubuntu 16.04..." to reflect what the actual situation is.  I've no idea if the Python 3 issue mentioned is the only roadblock or whether there are also other dependencies elsewhere.

https://switch2osm.org/serving-tiles/manually-building-a-tile-server-16-04-2-lts/ says things like "It’s recommended to use one of the newer links, but if you absolutely still need a server based upon 16.04..."

**Comment by mmd-osm** [comment]
> "It’s recommended to use one of the newer links, but if you absolutely still need a server based upon 16.04."

Maybe change it to read "Ubuntu 16.04 has reached end of standard support in April 2021.".  See https://wiki.ubuntu.com/Releases
