### ISSUE TITLE
Gates that open on the left vs. right, etc.

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4507]
Perhaps think ahead for future rendering for
https://wiki.openstreetmap.org/wiki/Talk:Tag:barrier%3Dgate#Gates_that_open_on_the_left.2C_right.2C_middle.2C_etc.
Yes, even though there are not such tags yet.

**Comment by imagico** [comment]
There is not even a suggested mapping method yet, let alone a practical use of such a method in the field.  So i am going to close this.
