### ISSUE TITLE
SVG support error: <enable-background> attribute is not supported

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4508]
When doing some unrelated dev work I got the message

```
Mapnik LOG> 2021-12-30 01:01:21: SVG support error: <enable-background> attribute is not supported
```

We should not have unsupported features in our SVGs, and CI should automatically check for this.

**Comment by imagico** [comment]
#4457 is supposed to take care of that.

**Comment by HolgerJeromin** [comment]
Could be now closed?
