### ISSUE TITLE
Render boundary=border_zone

### ISSUE THREAD

**Issue by kuba-medrek** [gravitystorm/openstreetmap-carto#4509]
Hello
I'd like to ask if you are considering rendering recently accepted proposal: Tag: boundary=border_zone.

[Proposal page](https://wiki.openstreetmap.org/wiki/Proposed_features/boundary=border_zone)

I believe that such areas should be rendered - although there are few of them, they are extremely important for map users.

**Comment by pnorman** [comment]
With only 20 uses, there's not enough usage for us to consider it yet.

**Comment by kuba-medrek** [comment]
In most countries there will be 0 or 1 usage, so this tag will never be popular as the other tags.

**Comment by mboeringa** [comment]
> I'd like to ask if you are considering rendering recently accepted proposal: Tag: boundary=border_zone.
> 
> [Proposal page](https://wiki.openstreetmap.org/wiki/Proposed_features/boundary=border_zone)
> 
> I believe that such areas should be rendered - although there are few of them, they are extremely important for map users.

I also think the proposal page of the Wiki needs some adjustments. E.g., the word "border zone" implies the zone is an area, yet one of the first examples given on the page links to a line type object without area:
https://www.openstreetmap.org/relation/1439255

I also think that for consistency with other "boundary" types, the double tagging:

**type=boundary
boundary=border_zone**

put on a closed relation should be mandatory.
