### ISSUE TITLE
Render amenity=boat_storage

### ISSUE THREAD

**Issue by Cj-Malone** [gravitystorm/openstreetmap-carto#4514]
### Expected behavior

Render [amenity=boat_storage](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dboat_storage)

### Actual behavior

Not currently rendered. I've just had a conversation with a user miss mapping them as `amenity=parking` to get them rendered.

### Links and screenshots illustrating the problem

[w406439510](https://www.openstreetmap.org/way/406439510)

It's got a wiki page, and almost 4k uses. I image a lot more are miss mapped as car parking to force rendering.

**Comment by imagico** [comment]
Thanks for the suggestion.  Mostly tagged on polygons, more than half of them in combination with building tags, those largely from a compact mapping activity 10 years ago in the midwest US - see for example:

https://www.openstreetmap.org/way/142263053
https://www.openstreetmap.org/way/141749598

Overall the mapping seems mostly consistent, rarely with additional tags (including name tag), some access=private.  Tag use is so far concentrated on Europe and North America.

**Comment by Cj-Malone** [comment]
Interesting, I hadn't used it `building`. I think `operator` could be a useful tag too, but obviously tagged a lot less.

**Comment by Cj-Malone** [comment]
Just checked, and OsmAnd renders it. It's just a dot with 2 boats in the centre. I don't know if you look for prior art when adding new renderings.

**Comment by boothym** [comment]
There is also https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dboatyard which is used slightly more often and seems very similar (with the addition of constructing and repairing in the wiki description).

**Comment by imagico** [comment]
Good point, there is definitely overlap between those two tags in practical use.  `waterway=boatyard` at a quick look seems broader in use both semantically and in global distribution.

**Comment by jeisenbe** [comment]
Declining this request for now since `waterwy=boatyard` overlaps in usage and is also common. We can revisit this decision in the future if a preferred method of tagging, with a clear definition, develops later.

**Comment by BertMule** [comment]
Boatyard is NOT rendered either.

Also, the full tag is: waterway=boatyard. My intention is NOT a [waterway.](url)
It is even described as "A place for constructing, repairing and storing vessels OUT of the water."

Current example: [Kanaaldijk](https://www.openstreetmap.org/#map=19/51.87071/4.23629).
