### ISSUE TITLE
kosmtik container can not be build

### ISSUE THREAD

**Issue by astronautchen** [gravitystorm/openstreetmap-carto#4515]
### Expected behavior
kosmtik container can be used normal

### Actual behavior
when  i run `docker-compose up kosmtik`,it will show something wrong,
like below image;so i edit dockerfile to delete some package which name with fonts character,
but it not successful;how can i use kosmtik successfully;

### Links and screenshots illustrating the problem

![image](https://user-images.githubusercontent.com/51189069/154385964-b94c10b4-8fd9-4c1f-8655-d6b01e62540a.png)

**Comment by kocio-pl** [comment]
I've just tested and it works as expected, so I close this ticket as invalid. Please recheck it and comment here if something is still wrong.
