### ISSUE TITLE
Tile downloads with newer Android System Webview implementations fail

### ISSUE THREAD

**Issue by woheller69** [gravitystorm/openstreetmap-carto#4523]
### Expected behavior
OpenStreetMap tiles should load
### Actual behavior
Tiles are not loaded
### Links and screenshots illustrating the problem

Install Android System WebView 99.0.4844.58
Try to load (tested with Jelly Browser which uses WebView):
https://tile.openstreetmap.de/7/63/42.png
-> this works
Now change ".de" to ".org" 
-> "[Access denied. See https://operations.osmfoundation.org/policies/tiles/)"
Switch to an older WebView Implementation (tested with 88.0.4342.152)
-> this works

The browser uses a valid HTTP User-Agent, so why is it getting blocked?

My RadarWeather app which uses WebView also does not work anymore.
https://github.com/woheller69/weather
woheller69/weather#54
Switching to ".de" solves the problem for the moment but is not satisfying.

**Comment by imagico** [comment]
Off-topic here - has nothing to do with the style.

**Comment by woheller69** [comment]
Thanks!
Moved to openstreetmap/operations#601
