### ISSUE TITLE
Intermittent waterways on bridges rendered in white

### ISSUE THREAD

**Issue by zaizone** [gravitystorm/openstreetmap-carto#4531]
### Expected behavior
Intermittent waterways on bridges (like aqueducts) should be rendered in dashed blue.

### Actual behavior
When the tags `bridge=*` and `intermittent=yes` are associated, linear elements are rendered in white like an actual road.

### Links and screenshots illustrating the problem
Please check [l'Aqueduc de Castries](https://www.openstreetmap.org/way/27515227) rendered as below
![map(3)](https://user-images.githubusercontent.com/4717626/162711391-70d7cc1f-7f79-4f47-bd9c-3166d0013c88.png)
Various examples can be found here : [https://overpass-turbo.eu/s/1hzm](https://overpass-turbo.eu/s/1hzm)

**Comment by danieldegroot2** [comment]
_Duplicate of #3497._
