### ISSUE TITLE
Please render landuse=flowerbed

### ISSUE THREAD

**Issue by RedAuburn** [gravitystorm/openstreetmap-carto#4564]
landuse=flowerbed was approved as a proposal a while ago, and currently has 31,700 uses as an area (143 uses as a node).

This would improve things like flower gardens, which currently look empty.

usage is increasing rapidly:
<img width="1082" alt="Screenshot 2022-06-03 at 17 59 51" src="https://user-images.githubusercontent.com/26939824/171911468-723a02f2-2213-4633-bb2f-d9f628bc590e.png">

**Comment by imagico** [comment]
See #4251.

We have consensus that this would be good to add - provided that a suitable design for rendering can be developed (the PR unfortunately was abandoned and not further developed).  A few ideas were provided in the mentioned PR.  Essentially just needs some work in visual design and testing.

**Comment by jeisenbe** [comment]
I agree that with >31k uses this is common enough to render, if a good style can be designed. This may require re-considering the rendering of similar features like `leisure=garden`.

**Comment by bgo-eiu** [comment]
Something that comes to mind would be something that is the same color or very similar as a meadow, but with little flower insets across it, like how woods have little trees in them

**Comment by imagico** [comment]
Any design experiments and studies would be highly welcome.  When using patterns keep in mind though that flower beds are often rather small and using coarse patterns with large pictorial symbols does not typically work well for small geometries.  Using a relatively fine grained structure pattern might work better.  The most obvious idea would be to use a more generic and weak structure pattern for leisure=garden while using something more specific and possibly heavier in some way hinting at flowers for landuse=flowerbed.

**Comment by hungerburg** [comment]
I took the chance, made two screenshots and fired up the Gimp, see below: Base is orchard, because, regular patterns signify human efforts. Using yellow and red dots at 45° may still show a bit of irregularity, if not noise. Result looks a moiré, like orchard does to me, but I am having difficulties with fine details on screen on many occasions.

![Flowerbed](https://user-images.githubusercontent.com/586972/172954315-60f36d9f-b963-481d-9120-60f35db838e1.png)

**Comment by imagico** [comment]
Yes, thanks, this is the kind of experiment i had in mind.

A colored pattern is an obvious choice for something like a flower bed.  But as you can probably see this kind of small multi-color detail, especially in complementary colors (red-green), can be problematic for reading.  And the pattern as you show it is coarser than that for leisure=garden - which would be non-ideal considering that flower beds are typically features within a garden, i.e. they tend to be smaller scale than coarser categorizations like garden or park.

Some ideas what you (or anyone else who would like to work on this) could try:

* vary the pattern, maybe try also an irregular one
* try less sharply pixel aligned symbols
* try less harshly complementary colors
* use a base color that matches grass/garden (which is most likely a better fit than orchard - see also https://github.com/gravitystorm/openstreetmap-carto/pull/4251#issuecomment-731243102)

**Comment by jeisenbe** [comment]
> maybe try also an irregular one

I thought we were trying to use regularly repeating patterns for cultivated / man-made vegetation? E.g. something like https://github.com/imagico/osm-carto-alternative-colors/blob/master/symbols/patterns/garden.png for garden in alt-colors style, but with dots closer together for this feature. 

> try less harshly complementary colors

For example yellow pattern on green fill, without the red, perhaps?

> use a base color that matches grass/garden

Agreed. Flower beds will have non-woody low-growing plants in most cases, which is similar to grass / meadow / grassland, while orchards have trees in most cases.

**Comment by imagico** [comment]
> I thought we were trying to use regularly repeating patterns for cultivated / man-made vegetation?

My suggestion was not meant to indicate that i would necessarily prefer an irregular pattern - just that it would be worth trying.

As far as cultivated vs. natural features is concerned - we use regular patterns mostly for features were a large scale regular structure is common in reality and having something similar in the pattern can help intuitive recognition.  Like for orchards, plant nursery, garden and allotments.  OTOH we use random patterns for many features which can be both natural and shaped and intensely maintained by humans.  And flower beds often do not have internally a regular arrangement and they might not even be maintained beyond yearly mowing and the original seeding of flowers.  So it is not necessarily helpful to use a regular pattern.  But as said i would be fine with a regular pattern, just not tied to it if something irregular works better for some reason and is well recognizable and harmonically fits into the style.

> For example yellow pattern on green fill, without the red, perhaps?

A single color might work but it might also make it less recognizable to indicate a flower bed.  It would also be possible to try moving more towards orange.

**Comment by jeisenbe** [comment]
> A single color might work but it might also make it less recognizable to indicate a flower bed. It would also be possible to try moving more towards orange.

So yellow + orange, or white + yellow perhaps?

**Comment by imagico** [comment]
All worth trying i think.  I have not tested any color combinations.  Staying a bit away from the complementary contrast green-red is likely to be advisable.  Also red is used for footway lines - hence it could affect readability of those closeby.

**Comment by hungerburg** [comment]
To be honest, I have no idea about the rendering of patterns in OSM-Carto. The roundabout has about 128 pixels in size at zoom 19. It is the biggest of flowerbeds in the samples I looked at. Still, here another sample, taking up some of the thoughts from above.

![flowebed2](https://user-images.githubusercontent.com/586972/173162860-109802d0-046c-41a2-bef5-2870b62f1ca1.png)

First, I wanted the top view of a rose (Planansicht, we call it here). Soon I learned, at 8×8 this is not going to work out. So I switched for a side view of the flower. This is just manual placement of pixels in a grid.

I like the idea of using white. Yellow does very bad, when scaled to non-integer. (I have to scale most websites to be able to read. I never scale openstreetmap though. Does that even work? Yes, when doing ctrl+) The bitmap above is much more clear on 200%.

**Comment by hungerburg** [comment]
Another take, a bit more sophisticated. I did draw an ornamental flower, a mix of two classics, the Lotus and the Lily. Then processed that to a pattern on http://www.imagico.de/map/jsdotpattern.php#x,256,jdp23956;g,20,32,32;rx,250,2,32,32;rd,0,0,0,custom,1,6,4,0,jdp5218,ef2929,fce94f; and pasted the result into a mockup.

![Flowerbed](https://user-images.githubusercontent.com/586972/174081089-5e140a9d-8811-4083-a281-95a551c77a67.png)

``` svg
<svg width="3.2mm" height="2mm" viewBox="0 0 16 10" version="1.1" xmlns="http://www.w3.org/2000/svg">
<path d="M10,4 C11,3 10,1 8,0 C6,1 5,3 6,4 C4,2 2,2 0,2 C0,6 2,10 8,10 C14,10 16,6 16,2 C14,2 12,2 10,4 M8,8.4 C12,9 14,6 15,3 C12,4 9,6 8,8 C7,6 4,4 1,3 C2,6 4,9 8,8.4 M8,6 C10,5 10,3 8,2 C6,3 6,5 8,6" fill-rule="evenodd"/>
</svg>
```

The selection of inks on jsdotpattern is a bit limited. The path got added, because of a mention above. Usually, people do not trample through flowerbeds ;)

**Comment by imagico** [comment]
This seems to be moving away from what would be a suitable design for this style.  The grass green background color is pretty much set for landuse=flowerbed because for the map user this is semantically very close to a (unmown, tall) grass area.  And as said above in https://github.com/gravitystorm/openstreetmap-carto/issues/4564#issuecomment-1149637098 large pictorial symbols will likely not work well for features like this which are often mapped in a fine grained manner leading to small polygons in display being drawn with the pattern.

A number of examples of symbol geometry/color combinations that seem to work reasonably well

https://imagico.de/map/jsdotpattern.php#x,128,jdp87556;gs,8,32,32;rd,1,0,0,dot,0.125,4,4,0,jdp67976,ffffff,cdebb0;
https://imagico.de/map/jsdotpattern.php#x,128,jdp92665;gs,8,32,32;rd,1,0,0,dot,0.15,4,4,0,jdp18105,ffb72d,cdebb0;
https://imagico.de/map/jsdotpattern.php#x,128,jdp92665;gs,8,32,32;rd,1,0,0,dot,0.175,4,4,0,jdp26245,ffead1,cdebb0;
https://imagico.de/map/jsdotpattern.php#x,128,jdp92665;gs,8,32,32;rd,1,0,0,dot,0.15,4,4,0,jdp26573,fff5d1,cdebb0;

Since jsdotpattern so far does not support multiple symbol colors you will need to edit the pattern SVGs if you want to have multiple different colors combined.

**Comment by hungerburg** [comment]
You are right. Flowerbeds are usually small. Looking at my paintings above, the one to the right, below "Birkenweg" should do quite fine even with no yellow background. Perhaps a simple POI icon, much like amenity=shelter, in the centre of the area marked as a flowerbed is good enough?

**Comment by imagico** [comment]
I don't think a point symbol or a single symbol pattern like suggested for sport pitches is a good idea here.  The mapping convention for flower beds - like for most other landcover tags - is that areas can be split to facilitate either the ease of work for the mapper or to indicate some minor differences in characteristics (like type of flowers).  Showing a single symbol for every polygon geometry would work against that well established convention.

It would also be prone to be confused with a single plant being mapped and rendered (like natural=plant).

I think you were on a good way with the previous design tests, just needs some more tests and tuning to fit into the design context of this style (in particular with the rendering of leisure=garden - which, if needed, you could modify for this to work).

**Comment by hungerburg** [comment]
For me, the simple dotted pattern looks too much like a meadow, rather than a flowerbed. Perhaps, OSM-Carto uses understatement to correct for overstatement by mappers. I guess, this is beyond my level of selflessness.

**Comment by imagico** [comment]
Well - meadows with many flowers and a flowerbed are often quite similar in appearance.  There are even flowerbed designs that attempt to mimic specifically the assortment of flowers you might find on a meadow in certain settings.

If mappers would make a clearer distinctions of these things (in particular of the different areas we render with grass color) based on semantics of use rather than physical appearance we could consider changing our rendering to reflect that better.  But as discussed many times this is not the case on a global level.  Hence our vegetation rendering is largely based on physical distinction and in that domain the difference between grass and flowerbed in rendering is going to have to be fairly small.

That said - you can work on the pattern weight to make it well defined - and as said you should to make it more defined than the more generic garden pattern.  And if you use a multi-color pattern that would also make the rendering fairly distinct for sure.

**Comment by BertMule** [comment]
Ran into this problem (again, probably).
Changed an object from inappropriate 'grass' into flowerbed, only to result  in disappearance altogether.

It's disappointing that though we agree there should be something, this topic is already left behind for a whole year.
I'd rather see a tag removed, than that it is effectively useless.

There are a lot more of them.
I would say that every accepted tag (no too many please) should also be rendered (at least on some map).

**Comment by imagico** [comment]
As indicated above this has been on a good way in terms of design development and just needs a bit more work to be put into it.

**Comment by daganzdaanda** [comment]
I played around with the pattern generator (very cool tool btw!)

The combination of various small symbols could be a way to go:
https://imagico.de/map/jsdotpattern.php#x,128,jdp47287;g,8,32,32;rx,25,2,32,32;rx,25,2,32,32;rx,25,2,32,32;rx,25,2,32,32;rx,250,2,32,32;rx,250,2,32,32;rx,250,2,32,32;rd,0,0,0,+dash%20diagonal2+dash%20diagonal2%20thin+dash%20diagonal1+dot,0.15,10,9,0,jdp4495,b02784,cdebb0;

Of course, many flowerbeds are planted very straight, so I made something more regular using a "tree star" symbol with random rotation:
https://imagico.de/map/jsdotpattern.php#x,128,jdp34242;gv,14,32,32;rd,1,1,1,tree%20star%202b,0.75,8,8,0,jdp64090,ec9d9d,cdebb0;

The "tree star" and "marsh" symbols seem to get along well:
https://imagico.de/map/jsdotpattern.php#x,128,jdp11668;gv,16,32,32;rd,1,1,0,tree%20star%202+marsh+tree%20star%202a+tree%20star%202b,0.8,4,4,0,jdp53114,ceb0eb,cdebb0;

Finding a good colour for the symbols is difficult... It should not make the flowerbed stand out so much that nothing else gets noticed anymore. But it should still have enough contrast to be recognizable.

Maybe green on green could still be ok with the right symbol(s)?
https://imagico.de/map/jsdotpattern.php#x,128,jdp34242;gv,14,32,32;rd,1,1,1,tree%20star%202b,0.75,8,8,0,jdp79201,9bb87f,cdebb0

**Comment by daganzdaanda** [comment]
Here's a flower-like symbol I made in inkscape
https://gist.github.com/daganzdaanda/47c3369bc4bf520a66b950b3a581fba3
Is it possible to test something like that with the pattern generator tool?

**Comment by hungerburg** [comment]
I made some small efforts for a rendering of flowerbeds. The design constraints of OSM Carto and my artistic ambitions just do not meet: Flowerbeds hurt the eye, sometimes they even stink, so map representation must as well, in my mind. Yet Carto wants to please the eye ;) And very successful at that - it is an exceptionally well designed map, honestly!

On a related term: Gardening departments here stock what were flowerbeds with "Blumenwiesen" (flowery meadows) instead and put up sings explaining their doings, referring to insect welfare e.g, perhaps anticipating complaints by people wanting to get a black eye from looking at French style flowerbeds. For those an irregular jsdotpattern might do well, in my view. Yet, it looks like there is no tagging for them? The natural=meadow tag is marked deprecated, but the landuse=meadow page also shows flowers, not just grasses, but the agricultural meadows it is used to map all are operated on short turn-over, where flowers cannot persist.

**Comment by imagico** [comment]
@daganzdaanda - i added a number of five-leaf flower symbols.  Your tests look promising but please keep in mind the design context of this with [plant_nursery](https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=landuse&value=plant_nursery) and [orchard](https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=landuse&value=orchard) regarding weight and coarseness of patterns.  Avoiding the use of non-green colors would be a nice possibility if it can be made to look somewhat intuitive.

Also could take some cues for what we did for [golf=rough](https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=golf&value=rough).  This is different because it only has to work in a specific context of course.

**Comment by daganzdaanda** [comment]
Thanks for the update with flower-like symbols! I'll see what I can get with these. 

> Avoiding the use of non-green colors would be a nice possibility if it can be made to look somewhat intuitive.

Yeah. Introducing a new contrasty colour for a symbol just for flowerbeds would be too much.

**Comment by daganzdaanda** [comment]
How about something like this:
https://imagico.de/map/jsdotpattern.php#x,128,jdp8256;gs,14,32,32;rd,1,1,0,flower1b+flower1+flower3+flower3b,0.75,8,8,0,jdp73332,9bb87f,cdebb0;
It's green flower-stars on green, quite straight, but some variation through the 3 different symbols used.

**Comment by daganzdaanda** [comment]
https://imagico.de/map/jsdotpattern.php#x,128,jdp34088;gv,20,32,32;rd,1,1,0,flower1b+flower1+flower3+flower3b,0.75,4,4,0,jdp76446,9bb87f,cdebb0;
A rotated triangular pattern, with a bit more distance between the symbols.

**Comment by daganzdaanda** [comment]
https://imagico.de/map/jsdotpattern.php#x,128,jdp8256;gs,14,32,32;rd,1,1,0,flower1b+flower1+flower3+flower3b,0.75,8,8,0,jdp73332,9bb87f,cdebb0
Largers symbols and a silvery grey colour... White just doesn't work for me, grey is a bit better. But green makes you think of plants and would make the interpretation easier. 

Maybe we need some more flower symbols 😁 like here:
https://imagico.de/map/jsdotpattern.php#x,128,jdp34236;gv,20,32,32;rd,1,1,0,flower1b+flower1+flower3+flower3b+flower2b+flower2,1,4,4,0,jdp77461,9bb87f,cdebb0;
This looks good IMHO!

The same with more "fat" flowers and less thin ones:
https://imagico.de/map/jsdotpattern.php#x,128,jdp34236;gv,20,32,32;rd,1,1,0,flower1b+flower2b+flower2,1,4,4,0,jdp57554,9bb87f,cdebb0;

**Comment by daganzdaanda** [comment]
Last one for now, tighter, more randomized and with smaller symbols again:
https://imagico.de/map/jsdotpattern.php#x,128,jdp47147;gv,14,32,32;s,jdp23875;j,jdp3763;j,jdp11669;j,jdp76799;j,jdp24479;s,jdp53222;s,jdp64106;rx,25,2,32,32;s,jdp51681;s,jdp96416;s,jdp60347;s,jdp17994;rx,250,2,32,32;rd,1,1,0,flower1b+flower1+flower3+flower3b+flower2b+flower2,0.75,4,4,0,jdp54145,9bb87f,cdebb0;

**Comment by imagico** [comment]
As said already - you need to look at the design context to determine what works and what does not.

Look at it in combination with other colors and patterns in the style and see if it fits in harmonically.  To me dark green stars on a brighter green background look quite a lot like trees - Norwegian style tree symbols like i showed [here](https://imagico.de/blog/en/differentiated-rendering-of-woodland-in-maps/).

If you are thinking about a regular pattern it might be a good idea to try one with no vertical or horizontal symmetry - like

https://imagico.de/map/jsdotpattern.php#x,128,jdp53521;gv,12,32,32;tr;rd,0,0,0,flower3b,0.9,5,5,0,jdp99947,eef6c0,cdebb0;

**Comment by daganzdaanda** [comment]
> To me dark green stars on a brighter green background look quite a lot like trees

Yes, I also noticed that. (And I read your blog about trees, but didn't remember the Norwegian example) 
I would be willing to accept a dark-on-light green for flowers, if the symbols can be read and deciphered well enough. But for that, they will have to be big, and so maybe overwhelm the rest of the map.

Your last example actually works juuuust well enough for me, too. The contrast is really at the edge, though... My monitor is quite decent, but I can barely see the stars. Which means, it's definitely not too strong. 

I made a variant of your idea just with a little bit larger and more spaced symbols:
https://imagico.de/map/jsdotpattern.php#x,128,jdp62563;gv,15,32,32;tr;rd,1,1,0,flower3b,1,5,5,0,jdp95598,eef6c0,cdebb0;

The same with a slightly stronger symbol
https://imagico.de/map/jsdotpattern.php#x,128,jdp62563;gv,15,32,32;tr;rd,1,1,0,flower1b,1,5,5,0,jdp63610,eef6c0,cdebb0;

Here's one with multiple symbols (I like how it adds a bit of randomness)
https://imagico.de/map/jsdotpattern.php#x,128,jdp62563;gv,15,32,32;tr;rd,1,1,0,flower3b+flower2b+flower1b,1,5,5,0,jdp98061,eef6c0,cdebb0;

Even wider spacing and a different symbol with slightly changed colour
https://imagico.de/map/jsdotpattern.php#x,128,jdp15972;gv,22,32,32;tr;rd,1,1,0,flower1,1,4,4,0,jdp6570,f7ffb8,cdebb0;
Here it may be too wide spacing, the chances are that very small flowerbeds will only have one or two symbols on them.

So this is a bit tighter again, adding a random rotation to the symbol for giggles 
https://imagico.de/map/jsdotpattern.php#x,128,jdp79837;gv,20,32,32;tr;ts;rd,1,1,1,flower1,1,4,4,0,jdp53324,f7ffb8,cdebb0;

And this is still a bit tighter with two smaller symbols
https://imagico.de/map/jsdotpattern.php#x,128,jdp21279;gv,18,32,32;tr;ts;rd,1,1,0,flower3b+flower2b,0.9,4,4,0,jdp37072,f7ffb8,cdebb0;

Even tighter, with a single fullsize symbol 
https://imagico.de/map/jsdotpattern.php#x,128,jdp40777;gv,14,32,32;tr;rd,1,1,0,flower1,1,4,4,0,jdp46768,f7ffb8,cdebb0;

**Comment by imagico** [comment]
> The colour from the last variations kind of works with simple dots too

Keep in mind this would be fairly similar to the allotments pattern.

**Comment by daganzdaanda** [comment]
argh, of course... we really do render a ton of stuff!
https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=landuse&value=allotments
I like the flowers better anyway 😄

**Comment by winnux8** [comment]
Bringing this up again as it seems to be a huge issue and people even tend to tag flowerbeds as grass or gardens just for the renderer ;)

**Comment by gdabski** [comment]
I'd argue that flowerbeds meet the definition of `garden`, i.e. a _distinguishable planned space, usually outdoors, set aside for the display, cultivation, and enjoyment of plants_ ;)

**Comment by hungerburg** [comment]
A garden IMHO intrinsically can be stepped inside - I at least do not enjoy it by looking at it from the outside. Especially when the cherries are ripe.

Recently I pondered this very subject. Carto will never use a blunt rendering as my previous suggestion. Ideas brought forward until now: Needs to be regular, needs to be green. How about https://imagico.de/map/jsdotpattern.php#x,256,jdp80301;gv,20,32,32;rd,0,0,0,ring8,1,5,11,0,jdp71042,4e9a06,cdebb0; - the rings are the flower blossoms, regular grid, rotated so not to be too boring. Anything too similar? Fine tune to your hearts desire!
