### ISSUE TITLE
Maintainer decisions and autonomy

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#4574]
I don't want to continue a general discussion on a specific PR, so I'll move this over here:

> I see much bigger problem there - looks like community is very clear what it wants and you are not going to listen. Who do you think you represent here with these wishes or this is just a personal preference you would like to have? I think this is very important question. Just calling something serious issue does not make one.

This is a really unfair question to ask of another maintainer. Maintainers don't "represent" particular groups of people - there's no electorate to represent. There are no elections to win. 

Maintainers are all appointed individually based on their own skills and experience. And different maintainers bring different skills and experiences to the team.

So every decision a maintainer makes is a personal decision. Of course these can be based on personal preferences, but also on what they hear from other people, and what other people's priorities are - it's a collaborative project after all. But that doesn't mean that if one group of people really really really want something that a maintainer must therefore acquiesce, against their own judgement. It's always down to the maintainer to make their own decisions.

"Who do you think you represent here" is a dreadful thing to say.

**Comment by pnorman** [comment]
Closing as there's nothing directly actionable here. If there are future questions by people who don't understand the role of open source maintainers, we can point them at the above text.
