### ISSUE TITLE
Fence separating 2 pedestrian areas not visible

### ISSUE THREAD

**Issue by p2s** [gravitystorm/openstreetmap-carto#4577]
Hello, I hope I'm at the right place for that kind of issue :) 

### Expected behavior
If a fence separate 2 pedestrian areas it should be easily visible

### Actual behavior
I have 2 areas (highway = pedestrian), I created a path for the fence, sharing the areas points, but we cannot see the fence :
![image](https://user-images.githubusercontent.com/453590/175574355-d1e5ebcb-e34e-451c-8d14-827ac25697bb.png)

I guess the gray of the fence and of the pedestrian area are the same.

### Links and screenshots illustrating the problem
https://www.openstreetmap.org/#map=19/50.63176/3.08591
The fence : https://www.openstreetmap.org/way/1073087796
A picture of the fence
![image](https://user-images.githubusercontent.com/453590/175573940-a2db0de5-938a-4cec-8316-d6d5abbd59a1.png)

**Comment by imagico** [comment]
Thanks for the report, this is an already known problem - see  #528.

Unfortunately there is no really good solution for this that does not either have serious negative side effects or is awfully complicated and inefficient to implement within our current technical framework.  We have #3281 still open (meaning we have not rejected that idea) - but we also have no consensus that we would like to go that route (see #3872).
