### ISSUE TITLE
Inquiry from the OSMF on ideas how they might help the project

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#4581]
An OSMF board member has approached the OSM-Carto maintainers and indicated an interest from the OSMF to help this project and was asking for ideas how to do so.  No details on what such help might look like were given and the board member indicated a reluctance to bring this matter up for public discussion themselves here, however they also indicated it is fine to have a public discussion here and gather input from the OSM-Carto developers in a broader sense this way.

Although this is a bit of a weird inquiry i feel it is important to communicate this to the project and its contributors. OSM-Carto is an open cooperation and that means anything that helps a contributor of the project in some way in their OSM-Carto work is potentially also of help for the project as a whole.  And i generally like to see as much of this project and its communication as possible to be in public and on public record.

This issue is meant to inform the OSM-Carto contributors about this inquiry and provide a place for them to present and discuss ideas and suggestions along these lines.  Given the unspecific nature of the inquiry i do not envision this to result in a formal answer to be developed but for what is suggested and discussed here to serve as an informal answer.  That means this is more intended to provide a place to collect some ideas and suggestions and less to discuss their merit.

Because a topic like this bears the strong risk of conversations getting sidetracked I like to remind everyone to keep the discussion here strictly on topic.  To make sure the discussion on this issue serves the described purpose i intend to make generous use of the github function to mark messages as off-topic if necessary.  Should anything discussed here inspire anyone to move discussion to matters not directly related to this issue please open a new issue instead (if the matter is still about OSM-Carto) or move it to a different venue.

**Comment by imagico** [comment]
Since no one else has commented anything on this and i don't want a certainly well meaning inquiry to go unanswered here a few points that come to my mind regarding what the OSMF could do to support this project.

I deliberately keep this brief, a lot more could be said on each of these regarding both why this is important and about the historical and present day context of the matter.

* Develop and show an interest in and appreciation for map design work in the OSM-Community in general (and of course in particular also openly cooperative map design specifically).  AFAIK this inquiry is the first time in the ten years history of the project that an OSMF representative on the political/decision making level has expressed any interest in the project and something tells me that this is not caused by you suddenly out of the blue realizing how important and valuable map style design is for OpenStreetMap... :wink: To be clear: On the technical level OSMF operations have always been genuinely supportive of the project.  This suggestion more applies to the political level.  In general it is extremely rare for the OSMF to even acknowledge that there is such a thing as map design work in the OSM community and - to put it bluntly - that maps do not just happen to come out of map rendering software.  This manifests in various forms, but in particular is also visible in money spending habits:  While the OSMF has over the years probably spent several 100k Euros on software development i don't think a single Euro was ever spent on map style design.  When financing development of software specifically for map rendering the OSMF has AFAIK never consulted with map designers regarding their needs.
* Support more diversity in map styles with goals similar to OSM-Carto.  This might sound like a weird suggestion how to help OSM-Carto but the project has been burdened since its beginning ten years ago by the fact that there is no other map style in existence with even broadly a similar purpose and scope as OSM-Carto.  That changing would be highly beneficial both for OSM-Carto and for the OSM community in general.
* Develop and publicly communicate a clear strategy w.r.t. the OSMFs use of OSM-Carto and the interest of the company in using/running other map styles and supporting other map design projects (be that with goals similar to OSM-Carto or not).  The OSMF has for quite some time indicated [an interest to bootstrap new map design projects](https://wiki.osmfoundation.org/wiki/Operations/Minutes/2022-03-10) but has - despite [inquiries](https://github.com/openstreetmap/operations/issues/565#issuecomment-906225445) in [that regard](https://github.com/openstreetmap/operations/issues/565#issuecomment-1074498514) so far not communicated in public what long term intentions are behind these endeavours, what goals these are meant to serve and how these plans relate to the OSMFs use of OSM-Carto.
* Publicly acknowledge the use of OSM-Carto by the OSMF.  Our license does not require that but it is noticable that [the OSMF tile usage policy](https://operations.osmfoundation.org/policies/tiles/) does not even link to OSM-Carto or suggest tile users to credit OSM-Carto.  The OSM website for the other map layers credit the style with "Tiles style by ..."/"Tiles courtesy of ..." but for OSM-Carto it does not.  This communicates a certain message the OSMF might like to reconsider.

**Comment by ZeLonewolf** [comment]
> Develop and show an interest in and appreciation for map design work in the OSM-Community in general

I think this is a good idea, but it's unclear what actionable steps the OSMF could take to accomplish it.  Though perhaps taking lofty ideas and figuring out how to implement them is exactly the purview of a global foundation to sort out.

> Support more diversity in map styles with goals similar to OSM-Carto

This is an interesting suggestion.  It's also not quite clear (to me) what's meant by this, but I would interpret it as "support other map styles that are global, general-purpose and are intended to provide mapper feedback".  It's a good suggestion on its face, but it seems like there is little motivation for community members to start projects with this goal.  I find that contributors that wish to start new map styles generally do so in order to satisfy a regional or functional (specific, rather than general) need.  The only map style I'm aware of that have goals "similar to osm-carto" as your [alternative colors style](https://github.com/imagico/osm-carto-alternative-colors).  If you're proposing that the OSMF support ac-style in some way (probably this means rendering and hosting it) then say so.  Without specific candidate styles that the OSMF might support, it's not really an actionable suggestion.

The latter two suggestions - a strategy for the use of osm-carto and other map styles and/or design projects, and public attribution, seem like directly actionable proposals that are reasonable and appropriate for the OSMF to take on and I concur.

**Comment by pnorman** [comment]
Figuring out how to support tile layers on the OSM site which are only regional would help. I don't know what the UI would look like since the assumption that layers are global is baked into a lot of the site UI.

There's styles (e.g. SomeoneElses' british-focused style) which capture regional differences (e.g. PRoW) that a global style will never. Supporting them will reduce the pressure for OpenStreetMap Carto to be something it isn't. It would also get more people involved in writing OSM styles, which means more ideas out there.

**Comment by imagico** [comment]
> There's styles (e.g. SomeoneElses' british-focused style) which capture regional differences (e.g. PRoW) that a global style will never. Supporting them will reduce the pressure for OpenStreetMap Carto to be something it isn't. It would also get more people involved in writing OSM styles, which means more ideas out there.

Yes, more diversity in open source map styles and more activity in that field and more awareness of its value in general would be helpful, exactly for the reasons you mention.  I deliberately did not include that in my list of suggestions because the OSMF becoming active here in a targeted form would likely do more harm than good.  Any form of targeted support in that domain would be subject to the inherent cultural bias in the OSMF and would most likely be following the [Matthew principle](https://en.wikipedia.org/w/index.php?title=Matthew_principle), i.e. would target already successful projects and neglect struggling and emergent ones and thereby decrease diversity rather than increase it.

If the OSMF board wants to throw money at the problem (my suggestions were specifically for other forms of support, money was only mentioned to illustrate also quantitatively the low significance map design has for the OSMF in general so far) i have two suggestions which i have both made in the past already:

* Act as a neutral infrastructure provider for map design projects.  Probably the most useful infrastructure the OSMF could provide for map design projects in general would be providing and operating rendering infrastructure for such projects for a public deployment of their map.  The key here would be neutrality, i.e. provide this to projects without a selection from people with influence in the OSMF (which would inevitably project the cultural bias of the organization).  If the OSMF would provide this without discrimination to people with the sustained interest and talent to work on map design that would allow such people (which are rare to find and motivate in the OSM community in general) to concentrate on what they are good at (map design) without having to double as a sysadmin and fundraising specialist for most of their time.
* Strategically invest in map rendering technology that (a) scales well with map design sophistication and cartographic ambition, (b) is suitable for open cooperative projects like OSM-Carto and (c) is designed and developed specifically for the needs of the map designer rather than the liking and convenience of the software developer.  I have pointed out that this is a strategic imperative for the OSM-Community on several occasions (like [here](http://blog.imagico.de/on-the-discussion-on-osmf-supported-vector-tiles-maps/), [here](http://blog.imagico.de/why-it-is-essential-for-the-openstreetmap-community-to-actively-pursue-map-design-innovation/) and  [here](http://blog.imagico.de/openstreetmap-carto-an-update-on-the-project/)).  While this is in total quite definitely beyond the current financial abilities of the OSMF, it is definitely something where the OSMF could contribute to.

**Comment by imagico** [comment]
Closing this as the main purposes of opening the issue was to inform the OSM-Carto developers of the inquiry and give them the opportunity to share their thoughts.  And both of these goals have been served.

It is a bit unfortunate that there were not more diverse suggestions made but i understand that because this inquiry is somewhat weird and unusual and lacks context many are likely unsure what to make of it.

Anyway - the ideas i have sketched should provide quite a few starting points to anyone in the OSMF who would like to support OSM-Carto in some form.  If there is need for further explanations or discussion don't hesitate to comment and we can reopen this.

**Comment by sommerluk** [comment]
I'm a little late to answer. However: I think maybe OSMF could help get https://github.com/openstreetmap/operations/issues/565 done.
