### ISSUE TITLE
Historic ruins not rendered

### ISSUE THREAD

**Issue by freddie1729** [gravitystorm/openstreetmap-carto#4585]
### Expected behavior

Historic ruins should show up on the map

### Actual behavior

Historic ruins are hidden

### Links and screenshots illustrating the problem

The ruins [here](https://www.openstreetmap.org/#map=16/50.9972/-4.5271), for example, are a historic monument which you may want to visit, so it would make sense to see them rendered.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/13642255/177188097-84743487-9cef-4e52-ace8-34b3e780a975.png">

**Comment by imagico** [comment]
Thanks for the report - that subject is already covered by #331.
