### ISSUE TITLE
Releasing v5.5.0

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4588]
It's been a long time since a release. I'd like to put out v5.5.0 this weekend.

There are no [PRs approved and awaiting merging](https://github.com/gravitystorm/openstreetmap-carto/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+sort%3Aupdated-asc+review%3Aapproved). Of the [unreviewed PRs](https://github.com/gravitystorm/openstreetmap-carto/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+review%3Anone+sort%3Aupdated-asc) I think the candidates are ~~#4587~~, #3750, and #4448 as fairly simple ones. I'm not worried about stuff like Travis removal (#4582) because it has no impact on what we release, just internal processes.

**Comment by pnorman** [comment]
This is likely to be the last 5.x release with #4431 ready for review

**Comment by Indieberrie** [comment]
I have a PR in the making, hopefully it will be out by the end of the weekend!

**Comment by pnorman** [comment]
Released,

**Comment by HolgerJeromin** [comment]
Is there a changelog (as we had in the past)?

**Comment by pnorman** [comment]
Yes, changelog.md has the changelog.
