### ISSUE TITLE
Add label for tourism=viewpoint

### ISSUE THREAD

**Issue by 1ec5** [gravitystorm/openstreetmap-carto#459]
[This observation deck](http://www.openstreetmap.org/way/91292276) is tagged `tourism=viewpoint`. The stylesheet applies an ![asterisk](https://raw.githubusercontent.com/gravitystorm/openstreetmap-carto/master/symbols/view_point.p.16.png) icon but ignores the `name` tag. When the viewpoint sits atop a landmark building, it’s important to render a label because the viewpoint will obscure any label for the building as a whole.

For now, the workaround is to tag the observation deck as a less specific `tourism=attraction`, as with the [Sears Tower](http://www.openstreetmap.org/node/2311635030).

**Comment by matkoniecz** [comment]
It is still not rendered on closed ways.
