### ISSUE TITLE
get-external-data.py leaves file in root directory of project

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4590]
When run with `--cache`, `get-external-data.py` creates files like `water-polygons-split-3857.zip` and `water-polygons-split-3857.zip.lastmod` in the root directory of the project.

These files should be in the data directory and ignored by git.

**Comment by Indieberrie** [comment]
I'm working on it as part of other things that I'm adding to that script. I was thinking of moving it to data directory. Is it ok place for them?
