### ISSUE TITLE
Barrier=gate is too prominent after recent changes

### ISSUE THREAD

**Issue by Ancymonek** [gravitystorm/openstreetmap-carto#4599]
### Expected behavior
Objects tagged with barrier=gate are not so prominent on the map. 

### Actual behavior
Currently, its black color (#000000) dominates everything else around and gathers unnecessary focus on this (honestly - not so important) object. It may have something to do with cleaning SVG commit: https://github.com/gravitystorm/openstreetmap-carto/pull/4457 .

### Links and screenshots illustrating the problem
Zoom 17 - screenshot:
![obraz](https://user-images.githubusercontent.com/16021640/178336064-4433fe51-3e06-4e9a-adf2-edd10e22465c.png)
https://www.openstreetmap.org/#map=17/52.14917/20.82287

Old vs new rendering:
![obraz](https://user-images.githubusercontent.com/16021640/178337367-023f1fc0-70c3-47b8-b6ae-07b5a39e8de2.png)

Previously:
![obraz](https://user-images.githubusercontent.com/16021640/178337694-62ed2244-2722-4c1a-835f-88d632028404.png)

Now:
![obraz](https://user-images.githubusercontent.com/16021640/178337788-9dff2508-b569-4efe-9e94-ac254b7079bc.png)

**Comment by docentYT** [comment]
Yep. The new icon looks weird. Anyone opened a map of any major city with the new icons before the commit?
