### ISSUE TITLE
Should we vendor fonts?

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4602]
Out of #4490 I investigated the versions of the fonts we use, and what systems have
Most Debian-derived systems have Noto fonts from 2020. Since then, there have been [updates to noto](https://github.com/notofonts/noto-fonts#recent-updates), with bug fixes, including bold support diacritics in NotoNaskhArabic.

Even if we got Debian to update the fonts-noto package today, it wouldn't be in a Ubuntu LTS release until 2024, and wouldn't be in backports until late 2022

Vendoring the fonts would involve writing a script that copies them from the noto-fonts repo into a ./fonts directory, and adding `font-directory: url('fonts');` to fonts.mss

This would add an estimated 18MB for all NotoSans Regular fonts[^1], 5.5MB for NotoSans bold[^2], 52MB for hanazono, and 14MB for unifont.

Advantages

1. Style users get up to date fonts without needing to manually install unpackaged stuff
2. We can get rid of fallback fonts, since we will control the fonts included
3. We can get rid of missing font warnings, which will also allow strict mode loading of the XML
4. We would remove significant deployment to deployment variations in text rendering that we currently have (e.g. people testing #4490)

Disadvantages
1. Repo size goes up by about 90MB
2. We're vendoring third-party content rather then relying on build systems and packaging
3. We have to keep the vendored fonts up to date with a script

[^1]: `find noto-fonts/unhinted/ -name 'NotoSans*-Regular.ttf' -type f | xargs du -hc --apparent-size`
[^2]: `find noto-fonts/unhinted/ -name 'NotoSans*-Bold.ttf' -type f | xargs du -hc --apparent-size`

**Comment by HolgerJeromin** [comment]
> Repo size goes up by about 90MB

Could this be included in `scripts/get-external-data.py` ?

**Comment by pnorman** [comment]
> Could this be included in `scripts/get-external-data.py` ?

It's not external data that changes, so I would be against that.

**Comment by imagico** [comment]
I would also like to consider the option for pulling in the fonts with a script on the user side.  It would be a significant volume of data and having that in the repo would mean every contributor would locally store a complete history of the font files (which would likely quickly grow to several hundred megabytes).  And as i see it there is not really a gain in having the fonts in the repo per se.

IMO it should be a separate script that downloads a certain version of the fonts (verified by us to work) as necessary (when the fonts are locally missing or outdated).
