### ISSUE TITLE
Render selected multipolygons filled

### ISSUE THREAD

**Issue by Sinuhe20** [gravitystorm/openstreetmap-carto#4608]
### Expected behavior
Selected multipolygons should be filled

### Actual behavior
Selected multipolygons are not filled

### Links and screenshots illustrating the problem
Two temple sites with almost the same attributes, the one as way (Luxor) is filled, the other as multipolygon (Karnak) not:

- https://www.openstreetmap.org/way/1079039494 (filled)
- https://www.openstreetmap.org/relation/14358790 (not filled)

Overpass turbo renders multipolygons correctly filled:

https://overpass-turbo.eu/s/1kaj

And it seems not be related to the complexity of the outline:

https://www.openstreetmap.org/relation/2017780 (also not filled)

**Comment by imagico** [comment]
This is the wrong issue tracker for this kind of concern - we are developing the style of the background map tiles, not the interactive features of the OSM website.  The OSM website is maintained on https://github.com/openstreetmap/openstreetmap-website.
