### ISSUE TITLE
Syriac language not showing in catro

### ISSUE THREAD

**Issue by Rawwoi** [gravitystorm/openstreetmap-carto#4610]
### Expected behavior

Syriac language showing in carto (it was working before for years, it stop showing in the last days)

### Actual behavior

Syriac language showing as "▯▯▯▯"...

### Links and screenshots illustrating the problem      

screenshot before and after: https://i.ibb.co/SQq0xCz/image.png      

one of the examples:     
https://www.openstreetmap.org/node/1972159484

**Comment by imagico** [comment]
Thanks for the report.

https://mc.bbbike.org/mc/?lon=43.122217&lat=36.491356&zoom=15&num=3&mt0=cyclosm&mt1=mapnik&mt2=mapnik-german

Since there have not been any changes to the font lists this could be deployment specific (see #4490, #4602).

All the labels that show this problem i could see are cases where the name tag contains a compound labeling string rather than a single name.  Do you have any cases where the problem occurs with a plain Syriac name in the name tag?

**Comment by mmd-osm** [comment]
This might be a side effect of upgrading tile servers to Ubuntu 22.04 along with this change: https://github.com/openstreetmap/chef/commit/6c1eca2b583b258a9086693997b033d24378aae1

https://github.com/openstreetmap/operations would be a good place to report this issue.

**Comment by pnorman** [comment]
I get this on Debian, and it's fixed by #4606 so it's either a font issue or a font ordering issue as opposed to a mapnik, harfbuzz, or fontconfig issue.

**Comment by sommerluk** [comment]
Noto Sans Syriac had three styles, each as a separate font file, in the past. We used one of these three font files.

[These three font files in the meantime have been merged into one single file.](https://github.com/notofonts/syriac/issues/10#issuecomment-1160919180) Therefore, the old font name does not work any more when updating the Noto fonts to a newer version.

However, [Noto plans to separate the three styles again into three separate font files](https://github.com/notofonts/syriac/issues/13#issuecomment-1160919240) in the future.

**Comment by pnorman** [comment]
> Noto Sans Syriac had three styles, each as a separate font file, in the past. We used one of these three font files.
> 
> [These three font files in the meantime have been merged into one single file.](https://github.com/notofonts/syriac/issues/10#issuecomment-1160919180) Therefore, the old font name does not work any more when updating the Noto fonts to a newer version.

I don't think this matters for this particular issue, since the fonts shouldn't be different between 20.04 and 22.04 according to the package information. It does matter with #4606, since we'll have to make changes when Noto separates the styles again.
