### ISSUE TITLE
Router help lines create weird shapes and gaps on squares

### ISSUE THREAD

**Issue by Eevee97** [gravitystorm/openstreetmap-carto#4612]
### Expected behavior

When I'll talk about "router help lines" I'm talking about paths created to help routing services recognise paths inside areas/squares. Router help lines (`highway=pedestrian`) on squares (`highway=pedestrian`, `area=yes`) should not change how the squares are rendered.

### Actual behavior

Routing help lines create some weird looking maps at the moment. They are mapped to help routing services recognise paths inside an area/square. Currently, if these lines end at the edge of the square, it creates weid shapes outside the square (round shape of road end). If there is a cycle way inside a square, it is not rendered if there is a router help line.

These paths aren't paths that need top be rendered, if they are inside squares. They could of course be mapped as footways, but many mappers seem to agree that the paths inside a square have to have the same tags as the area has. And this creates all these road ends that are seen on the map.

### Links and screenshots illustrating the problem

I've circled the weird points with black lines:

![Näyttökuva (500) – kopio](https://user-images.githubusercontent.com/104729336/179841435-bf667a1b-e831-4615-84d0-47a3c3982fca.png)
![Näyttökuva (501)](https://user-images.githubusercontent.com/104729336/179842170-cd6f31c6-e486-4643-a941-1c3c69667066.png)

**Comment by pnorman** [comment]
Leaving aside the tagging question, I don't think this is possible to change. It would involve changing the end-cap settings which would impact all highway ways, and even then I don't think it would work.

**Comment by danieldegroot2** [comment]
> Currently, if these lines end at the edge of the square, it creates weid shapes outside the square (round shape of road end)

Also, for this part, see https://github.com/gravitystorm/openstreetmap-carto/issues/4499#issuecomment-985443694

**Comment by pnorman** [comment]
For the same reasons as https://github.com/gravitystorm/openstreetmap-carto/issues/4499#issuecomment-1193253101, I'm going to close this.

Fixing it would be impractical, and any of the possible fixes would cause breaks elsewhere.
