### ISSUE TITLE
Drop rendering of name labels on information boards

### ISSUE THREAD

**Issue by ZeLonewolf** [gravitystorm/openstreetmap-carto#4619]
Currently, features of type `information=board` will render with an icon and label, for example:

![image](https://user-images.githubusercontent.com/3254090/180586195-4ce4de79-5c48-4f6c-a726-15b3474ac5d1.png)
Location: https://www.openstreetmap.org/#map=19/41.44931/-71.39906

At this location, the feature:
https://www.openstreetmap.org/node/9779113378
is tagged with a name that corresponds to the title of the information board, which seems like an interesting/questionable but not unreasonable practice.  The title of the information board is supported by a link to a photograph of the object in the object's tags.

I propose that `name` no longer be rendered for information boards.  The rendering of `name` on these features adds visual clutter and encourages the adding of possibly questionable values into the `name` tag for the purpose of rendering.

**Comment by 1ec5** [comment]
> a name that corresponds to the title of the information board, which seems like an interesting/questionable but not unreasonable practice.

[A recent tagging mailing list discussion](https://lists.openstreetmap.org/pipermail/tagging/2021-November/062798.html) seemed to coalesce around either `name` or `board:title` for capturing the sign’s title. It may well be that the labeling here motivates mappers to tag the title in the first place.

Would labels for `memorial=plaque` also be removed? As in example above, parks of a historic or botanical character tend to have a dense collection of information boards, plaques, and markers that aren’t notable in their own right. However, markers can be more remarkable [in an urban environment](https://www.openstreetmap.org/node/6452840446), where they may even serve as stops in a walking route.

**Comment by bgo-eiu** [comment]
I'm inclined to agree with this, but I think part of the issue at hand is that the existing tagging scheme doesn't do much to convey the degree of significance a sign name has, and what type of information is included. A welcome sign seems like a more welcome labelled map feature than a label on every sign reminding passers by of local trespassing ordinances or where to put their dogs' poop. Even in situations where having a sign label display would be desirable, the actual sign text can be idiosyncratic or erroneous in a way that street signs are less likely to be. For example, welcome signs bearing the name of a neighborhood other than the one the sign is in planted by property developers trying to attract transplants to unfashionable parts of the city, overly verbose government-installed signs that bear the name of several municipal agencies before getting to the point, signs for industrial parks that read like signs for amusement parks, or place name signs that have de facto been replaced with a rather rude/childish pun that vandals arrived at a consensus on.

If labels are going to be rendered for information boards, I think the criteria should be very discerning, i.e. only specific types of them would display, which would have to be tagged in some way to indicate this.

**Comment by pnorman** [comment]
> A welcome sign seems like a more welcome labelled map feature than a label on every sign reminding passers by of local trespassing ordinances or where to put their dogs' poop.

We render tourism information signs that are boards - most signs would not be like this.

I looked at local usage and the most frequent names globaly, and agree with removing name rendering from information boards.
