### ISSUE TITLE
Planning v5.6.0 release

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4625]
It'll be four weeks since v5.5.0 in a week or so, so I'd like to give some thought to what we can get into v5.6.0.

The list of [unreviewed PRs](https://github.com/gravitystorm/openstreetmap-carto/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+review%3Anone+sort%3Aupdated-asc) is up to 12. 8/12 of those are mine, so I need other people to review. Reviews can and should be done by non-maintainers too.

Several of the PRs have no tie-in with the release sechedule since they're technical improvements with no deployment considerations (#4623, #4622, #4614, ~~#4611~~). Still, it would be nice to get them off the open list.

#4616 and #4606 are fairly simple cartographically, so I hope there's only technical questions that could hold them up. #4607 is a bigger change and might need some discussion.

**Comment by imagico** [comment]
I try to have a look at every PR but i want to test changes properly so things like #4616 take some more time.

Personally i think more important than a regular release schedule (which is obviously nice to give development work a clear structure) is to get movement on the bigger design changes that have a strong impact on other issues and solutions to those.  This currently means mostly #3399/#4137, #4128 and #3670.

**Comment by mboeringa** [comment]
@pnorman 

Correct me if I am wrong, but maybe it is good to note that https://github.com/gravitystorm/openstreetmap-carto/pull/4471 is probably out of scope in the list of [unriewed PRs](https://github.com/gravitystorm/openstreetmap-carto/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+review%3Anone+sort%3Aupdated-asc) you linked, as [you justly noted](https://github.com/gravitystorm/openstreetmap-carto/pull/4471#issuecomment-1176532112) that it is likely superseded by the work on https://github.com/gravitystorm/openstreetmap-carto/pull/4431 for the flex backend support that I guess you intend for v6.0. Maybe closing https://github.com/gravitystorm/openstreetmap-carto/pull/4471 in favor of the upcoming flex backend support is in order?

And so is https://github.com/gravitystorm/openstreetmap-carto/pull/4431 then as well.

**Comment by pnorman** [comment]
Yes, I expect flex to take more time than is reasonable for the upcoming release. I don't see #4471 as out of scope

**Comment by pnorman** [comment]
Released
