### ISSUE TITLE
Command recommended in INSTALL.md to disable JIT fails.

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#4627]
Command recommended in INSTALL.md to disable JIT fails.

### Expected behavior

INSTALL.md recommends a command for disabling JIT, which works.

### Actual behavior

INSTALL.md recommends

```psql -d gis -c 'ALTER SYSTEM SET jit=off; SELECT pg_reload_conf();'```

to disable JIT. However, this fails with the following error message:

```ERROR:  ALTER SYSTEM cannot run inside a transaction block```

**Comment by pnorman** [comment]
I guess this needs to be done as two `-c` commands
