### ISSUE TITLE
Aramaic name shown as bunch of rectangles

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#4636]
https://www.openstreetmap.org/node/2710911176/history#map=19/31.77633/35.23074

#3184 may be related

`name=ܕܝܪܐ ܕܡܪܝ ܪܩܘܣ`

![screen23](https://user-images.githubusercontent.com/899988/182687478-f71d2ba3-a3cb-42c1-a70e-aa270364a1bc.png)

**Comment by pnorman** [comment]
Works for me - do you get this locally with master? It's likely something that's fixed with the v5.6.0 font changes

![image](https://user-images.githubusercontent.com/1190866/182688384-ee49a369-b935-430c-a87a-d63b3ed279c4.png)

**Comment by matkoniecz** [comment]
not checked, I just tested it online

> It's likely something that's fixed with the v5.6.0 font changes

really unlucky timing then, I was checking something in Jerusalem
