### ISSUE TITLE
Big water bodies disappeared on z0-z4

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#4638]
### Expected behavior
Big water bodies like lakes should be visible from low zoom levels.

### Actual behavior
Lakes are visible only from z5.

### Screenshots with links illustrating the problem
Lake Victoria - older style version (z4)
![Screenshot 2022-08-07 at 01-56-01 OpenStreetMap Carto — Kosmtik](https://user-images.githubusercontent.com/5439713/183269473-212e00d9-c5ac-482b-9b0c-85683e1bd825.png)

Lake Victoria - current rendering on OSMF (z4)
![Screenshot 2022-08-07 at 01-56-11 OpenStreetMap Carto — Kosmtik](https://user-images.githubusercontent.com/5439713/183269481-aa9d9b6a-c9cf-4622-896e-02038d1c92f5.png)

**Comment by ZeLonewolf** [comment]
Goodbye, [Great Lakes](https://www.openstreetmap.org/#map=4/52.72/-83.58):

![image](https://user-images.githubusercontent.com/3254090/184026471-a9845f4b-9d3e-4396-b1e0-a164a95301a1.png)

**Comment by ZeLonewolf** [comment]
Appears to be introduced in #3750
