### ISSUE TITLE
Render aeroway=aircraft_crossing

### ISSUE THREAD

**Issue by DianAgesson** [gravitystorm/openstreetmap-carto#4652]
Hello,

I would like to propose that the map begin rendering the tag [aeroway=aircraft_crossing.](https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Daircraft_crossing)

The tag allows for mappers to indicate where a road or path intersects with an aeroway. The most famous examples are the Gilbratar airport which is bisected by a major highway, but these rare situations are important in the local area for routing/route planning purposes.

The tag was [approved ](https://wiki.openstreetmap.org/wiki/Proposed_features/Aircraft_crossing) and since then has been implemented by the community around the world. As these crossings are not common, [the overall numbers are not high](https://taginfo.openstreetmap.org/tags/aeroway%3Daircraft_crossing), but have been applied to nearly every example I can find.

The proposal also included a possible [icon.](https://wiki.openstreetmap.org/wiki/File:Airside_crossing_example_icon.svg) for these crossings, adapted from the "level crossing" icon.

Dian

![50px-Airside_crossing_example_icon svg](https://user-images.githubusercontent.com/99240595/185265958-46a5e498-2405-41a7-8958-912bc27ea638.png)

**Comment by imagico** [comment]
41 uses, unclear semantics (from the way it is used it is not clear if this is just a superfluous explicit tagging of intersections between an aeroway=runway or aeroway=taxiway and a highway=* or something else).  

In any case i would be against adding another static POI symbol rendering of a line feature intersection like we already do for fords and mountain passes.  It significantly obscures a part of the line rendering that is particularly important for reading.

**Comment by DianAgesson** [comment]
Hello,

> 41 uses, unclear semantics (from the way it is used it is not clear if this is just a superfluous explicit tagging of intersections between an aeroway=runway or aeroway=taxiway and a highway=* or something else).

The tag is not only used for intersections, but for situations where a “level crossing” feature exists to facilitate aircraft movements. This includes where aircraft fly closely overhead.

It also explicitly excludes service roads within airports that are used by ground crew, instead being exclusively for situations where “normal” traffic is interrupted. The tagging is necessary for the same reasons as railway crossings: they are points where routing is affected.

> In any case i would be against adding another static POI symbol rendering of a line feature intersection like we already do for fords and mountain passes. It significantly obscures a part of the line rendering that is particularly important for reading.

My belief is that the scope of this tag will prevent it saturating the map. It should be much less intrusive than a railway level crossing.

**Comment by imagico** [comment]
Keep in mind that we render tags as they are actually used, not as someone thinks they should be used.

**Comment by jeisenbe** [comment]
Only 41 uses,This tag is too rare to be shown with a symbol as suggested. 
Note that some are private service roads which cross taxiways, e.g. https://overpass-turbo.eu/s/1mY6 -  unfortunately the suggestion "explicitly excludes service roads within airports that are used by ground crew” has not always been followed.
