### ISSUE TITLE
oneway not shown on aeroway=taxiway

### ISSUE THREAD

**Issue by phd0** [gravitystorm/openstreetmap-carto#4659]
### Expected behavior
like a secondary road, show the OneWay arrow on the yellow taxiway. 
actually, arrow not shown 

### Screenshots with links illustrating the problem
https://www.openstreetmap.org/#map=17/48.72891/2.34357
![image](https://user-images.githubusercontent.com/1939211/185865536-aac9d609-21ce-4442-a263-0b53679fd1c6.png)

![image](https://user-images.githubusercontent.com/1939211/185865357-fc6cd8c5-6e6e-4712-afbe-4b345d90b2ca.png)

**Comment by imagico** [comment]
There are about 550 combinations of `aeroway=taxiway` with `oneway=yes`.  Combination is not documented.

**Comment by jeisenbe** [comment]
I do not believe this information would be useful on a general-purpose map. As mentioned above it is only used in about 0.2% of taxiways, so I recommend declining this request.
