### ISSUE TITLE
Barrier=chain is rendered as ways but should be mapped as nodes

### ISSUE THREAD

**Issue by Adamant36** [gravitystorm/openstreetmap-carto#4673]
Related to #4654. The title is self explanatory. According to @pnorman barrier=chain is barrier=chain is currently rendered as a normal way like barrier=fence or barrier=guard_rail, but according to the wiki they are supposed to mapped as nodes. The usage numbers also support that, with only 4,943 out of 29,410 uses currently mapped as ways instead of nodes.

**Comment by imagico** [comment]
As formulated this issue is off-topic on this tracker, we are not concerned with how mappers should map things.

If you want to suggest rendering nodes tagged `barrier=chain` with a point symbol or otherwise or not rendering ways tagged with way with a line signature please change accordingly, otherwise this should be closed.

**Comment by Adamant36** [comment]
>We are not concerned with how mappers should map things. 

Huh? "This style has multiple purposes: It's an important feedback mechanism for mappers to validate their edits and helps to prevent unfavorable fragmentation of tag use." How exactly does the style "prevent unfavorable fragmentation of tag use" except by partly being concerned with how mappers should map things? I can also point to a ton of issues in the meantime where you've made comments directly to that effect. For instance https://github.com/gravitystorm/openstreetmap-carto/pull/4604#issuecomment-1184810167 pretty clearly discourages people not mapping things through "centrally organized campaigns and massive organized and mechanical editing efforts." There's also PRs like #971 and the various issues that revolved around the mapping/rendering of large water bodies. Both of those relate to how mappers should map things. Not to mention all the discussions about the rendering of name and ref tags and if rendering either in certain situations encourages bad tagging practices. So your claim that such discussions are off-topic or otherwise not the trackers concern is just bizarre. 

> If you want to suggest rendering nodes tagged barrier=chain with a point symbol or otherwise or not rendering ways tagged with way with a line signature please change accordingly

Sorry, I thought it was implied that I was suggesting barrier=chain should rendered as a point symbol instead of a line signature. I guess I should have made it more explicit. My bad. Anyway, I see now that #4409 suggests rendering barrier=chain on nodes and I don't really feel like getting into a protracted meta discussion about what the concerns of the tracker are in the meantime. So I'm going to close this as a duplicate and save the line signature thing for another time. Thanks though 👍

**Comment by imagico** [comment]
For more detailed explanation in case my brief comment was difficult to understand:

The issue title requests rendering to be adjusted to how chain barriers _should_ be mapped - which according to the initial comment is decided by the wiki.  We have a long standing tradition to not base our rendering decisions on what some perceived authority (for example someone editing the wiki or some editor preset developer or someone doing organized edits) says, but to base it primarily on the de facto practice of local mappers deciding themselves what to map and how to map it.  Based on that the request of #4409 is reasonable - and dropping rendering of a line signature for ways with that tag could be as well, i have not looked at this enough to form a qualified opinion though.

And that is perfectly in line with most past decisions in this project (and in the cases where it is not this is usually reflected in the connected discussion).  If anyone has difficulties understanding that for any particular decision then please just ask (but do so without implying that you already know that the decisions are arbitrary and without a basis in reason).

Feel free to open an issue or PR for removing line rendering for `barrier=chain` if you think that is a good idea - it is the barrier value with the lowest volume use on ways that is currently rendered with a line signature.

**Comment by Adamant36** [comment]
"anyone has difficulties understanding that for any particular decision then please just ask (but do so without implying that you already know that the decisions are arbitrary and without a basis in reason)."

BTW, I wasn't implying that the decisions are arbitrary or without a basis in reason. You haven't done a good job in this issue and a lot of others at conveying what exactly your making decisions based on. But that's not me though. I can guarantee that if I picked any other maintainer at random that they could give a clear, concise explanation of what their process of deciding something is from the start. No insult, but for some reason you seem to be unable to that in most of issues I've seen. At least not without some prodding like in this issue. Your second comment was perfectly fine and understandable. The first one? Not so much. I don't know if a language or education issue, but a lot of people who contribute to this (including myself) often have a hard time parsing out exactly what your getting at.

Personally, I'm just a random internet pleb. I don't have a PhD in engineering or anything fancy like that. For that matter I couldn't even read or write passed a third grade level until I was like 25 (which wasn't that long ago). So I'm never going to be able to magically decipher your one sentence explanations. Blame it on my stunted intelligence level compared to yours or whatever, but I'm not intentionally being malicious or bad faithed with my responses. I just genuinely don't understand what your on about a lot of the time. And it seems like your put off sometimes when I ask for clarification. 

I know I've gone off about the meta discussions before. I don't think those are helpful either, but there has to be a good medium somewhere between turning something into a completely pointless meta discussion and responding with something so short and concise that its just as unhelpful at moving things forward.
