### ISSUE TITLE
get-font.sh failed to find unzip when using Docker

### ISSUE THREAD

**Issue by ibicdlcod** [gravitystorm/openstreetmap-carto#4677]
importing data using `docker-compose up import`
### Actual behavior
import_1   | scripts/get-fonts.sh: 127: scripts/get-fonts.sh: unzip: not found
openstreetmap-carto_import_1 exited with code 127
### Screenshots with links illustrating the problem
![Screenshot from 2022-09-05 19-19-58](https://user-images.githubusercontent.com/1089754/188437224-dad64aa3-4d82-40ca-9c6b-28c5ec225f2b.png)

**Comment by Woazboat** [comment]
The `unzip` package needs to be added here https://github.com/gravitystorm/openstreetmap-carto/blob/master/Dockerfile.import#L13-L15

**Comment by nighto** [comment]
Created a small PR with the fix proposed by @Woazboat
