### ISSUE TITLE
Render man_made=works + product=furniture

### ISSUE THREAD

**Issue by Almorca** [gravitystorm/openstreetmap-carto#4680]
I think that man_made=works + product=furniture should be render like shop=furniture.

**Comment by HolgerJeromin** [comment]
We render no icon for any industrial/man_made thing. 
If you can buy a sofa there it should have a `shop=furniture` at the correct position.

**Comment by imagico** [comment]
`man_made=works` + `product=furniture` have 232 uses in combination.  And we quite definitely don't want to render shops and factories of things identically.  If there are places where furniture is both made and sold then they can be double tagged as such.

I would suggest we close this.

**Comment by pnorman** [comment]
Insufficient usage for a dedicated icon, and reusing the furniture shop would lead to confusion.
