### ISSUE TITLE
Theme park outline not rendering correctly over highway areas

### ISSUE THREAD

**Issue by wmisener** [gravitystorm/openstreetmap-carto#4682]
### Expected behavior
Theme park (`tourism=theme_park`) and zoo (`tourism=zoo`) outlines should render on top of everything else, since they define a sort of boundary. This would be similar to how protected area outlines currently render.

### Actual behavior
Theme park outlines appear to render below highways, but above other objects like buildings and piers, leaving to an undesirable broken outline. This is especially noticeable under pedestrian areas (`highway=footway`+`area=yes`), but appears to be true for all `highway=*`, whether they are mapped as ways or areas.

### Screenshots with links illustrating the problem
<img width="745" alt="Screen Shot 2022-09-11 at 11 11 50 AM" src="https://user-images.githubusercontent.com/58491489/189542673-a3904292-32e8-4cb8-8282-195d0142202f.png">

https://www.openstreetmap.org/way/173532595, Pacific Park, Santa Monica, CA, USA

<img width="522" alt="Screen Shot 2022-09-11 at 11 13 15 AM" src="https://user-images.githubusercontent.com/58491489/189542745-a33178d9-6a2f-4d9d-b2a3-7bb5d81b57fa.png">

https://www.openstreetmap.org/#map=19/33.80960/-117.91858, Disneyland, Anaheim, CA, USA

<img width="530" alt="Screen Shot 2022-09-11 at 11 17 33 AM" src="https://user-images.githubusercontent.com/58491489/189542988-8fbf5233-dc56-4365-b26c-8220b9d5f2f4.png">

https://www.openstreetmap.org/#map=19/33.80960/-117.91858, Universal Studios, Los Angeles, CA, USA

Compare:
<img width="754" alt="Screen Shot 2022-09-11 at 11 21 45 AM" src="https://user-images.githubusercontent.com/58491489/189543068-e5b18443-283b-44e3-9c47-679fc48cc6d9.png">

https://www.openstreetmap.org/#map=19/33.80960/-117.91858, Circle X Ranch, Thousand Oaks, CA, USA

Notice how the protected area boundary goes on top of the roadways. I find this desirable behavior, though it's been proposed to change it in #4127, due to rendering issues with closely parallel boundaries (#3685)

**Comment by imagico** [comment]
This is in principle easy to fix by moving the `tourism-boundary` layer above the road layers.

Note however your examples also illustrate how problematic this kind of rendering is and how severely it affects map readability, in particular in cases where the outline of a theme park/zoo intersects something like a pedestrian area.

**Comment by wmisener** [comment]
I'm not sure I understand, by "how problematic this kind of rendering is" do you mean the current rendering, with the boundary under the pedestrian areas, or my suggestion, which would put the boundary above the pedestrian areas? If you mean the suggestion, could you clarify how you see the posted examples, which are all of the current rendering, illustrating this? Or, do you mean the style of rendering boundaries with a line and casing in general?

I see these examples as depicting how the current rendering of these boundaries underneath the pedestrian areas is very bad for map readability. Especially the first one at Pacific Park, which is how I noticed it in the first place. It's not clear to me whether your comment is in support of or in opposition to the suggested change, or about a broader stylistic question.

**Comment by imagico** [comment]
> do you mean the current rendering, with the boundary under the pedestrian areas, or my suggestion, which would put the boundary above the pedestrian areas?

Sorry if i was unclear - i was referring to the design concept for rendering these features in general, independent of the position in the layer stack.

If you take that design as a given your suggestion is perfectly fine.
