### ISSUE TITLE
When address range too near

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4688]
One used to seeing two numbers,
![Screenshot_20220915-065203_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190387106-02935974-67f4-4869-9a4c-b18d7684ee22.jpg)
has a hard time guessing what only one number means, ![Screenshot_20220915-064903_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190386723-98e00d23-15de-4798-b91f-81574f6bb3f9.jpg)
geo:43.1515316,-79.3596095?z=23

**Comment by jidanni** [comment]
Perhaps as these are roomy farm fields some more leniency could be allowed.

**Comment by sommerluk** [comment]
We render point feature labels at their real position to give correct feedback to mappers.
