### ISSUE TITLE
Render International boundary markers

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4696]
International boundary markers are important, often far and few between, and worth being rendered.
https://www.openstreetmap.org/node/1194944921

**Comment by jidanni** [comment]
Also, they are the true facts on the ground. And indeed often reveal that the lines we see on Openstreetmap are perhaps several meters away from where they really should be. 

I don't propose dragging those lines to where the boundary markers are. But I'd at least like to see where the boundary markers are on the map.

**Comment by imagico** [comment]
The linked feature has two relevant tags: `historic=boundary_stone` and `man_made=survey_point`.  For survey points we have #2271.  If you want to render `historic=boundary_stone` please change the issue accordingly.  Note `historic=boundary_stone` semantically overlaps with `boundary=marker`.

**Comment by jidanni** [comment]
(See also [pic](https://commons.m.wikimedia.org/wiki/File:19940720skmbnd.jpg), [map](https://www.openstreetmap.org/node/331783182), [trip](https://www.jidanni.org/geo/us_can1994/index.html).)

Anyways what I'm requesting shouldn't have anything to do with history, historical value etc. Even if an international boundary was just agreed upon last Thursday, markers should still be rendered if they are indeed the ground truth!

Also we don't want any Tom Dick and Harry's steel survey nail in a sidewalk to necessarily be rendered though. (Even if they're emblazoned with the local Mosquito Abatement Commission's official seal.)

Here we see the middle of an international bridge between the United States and Canada... (one moment please)

**Comment by jidanni** [comment]
Exhibit A, the Peace Bridge at Buffalo, New York / Fort Erie, Ontario. 
![Screenshot_20220925-083231_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192143655-16787e95-1923-4301-a758-f094112d502e.jpg)
The rendered coarse "middle of the river" border is several truck-lengths away from the pair of plaques on either side of the road, and three flags, US, UN,  and Canadaian.

Alas they all might as well just be trash cans, because they're not going to get rendered. 

No offense to trash cans, well, you get my point: there's a ton of stuff up there, affixed with each nation's great seals and signatures, but you never know it looking at the map!

**Comment by imagico** [comment]
We can only render what is mapped and tagged in OSM in a consistent fashion and that does not seem to be the case for boundary markers on international boundaries at the moment.  Hence i am closing this.
