### ISSUE TITLE
Drydock: only name gets rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4704]
![Screenshot_20221002-193601_Brave - Beta.jpg](https://user-images.githubusercontent.com/1230959/193481466-34c36b5e-9620-4898-aa33-bd53aa503e32.jpg)![Screenshot_20221002-193851_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193481471-5c01e8b0-2899-4f2d-9874-b2654ad056ef.jpg)![Screenshot_20221002-193913_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193481474-f98b365e-338d-4452-abca-ea6ae52e9c3e.jpg)
The dry dock is not rendered, only the name is, which ends up floating in the river. Not too 'dry' after all.

**Comment by tjur0** [comment]
This is not a drydock, this is: https://www.openstreetmap.org/way/256493808
Use man_made pier like this: https://www.openstreetmap.org/way/295356902
