### ISSUE TITLE
Rendering of sports entities

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4705]
As ever, its very frustrating to have drawn very common, socially important, entities like sports clubs and don't see any result.

Typically this is as a point on a building, or perhaps added to an address, often within a sports centre.
One can debate what is the best way. I prefer to separate the two.

While editing one might at least see some general icon and the name.

And then the proof of the pudding: nope. No name, no icon.

Arbitrary [example ](https://www.openstreetmap.org/#map=17/52.17529/4.48302) with several centres, pitches and clubs, tagged in different ways.

This seems an issue that is already years old. 

It is not about entities that have some legal name of 'club', but just **sports** clubs. 

Now the workaround is to add the name to the sports centre, which may come down to the same thing, but is not really correct.
People may also add the name to a pitch.

At least I am tired of having to find workarounds for very obvious expected, but not actual behaviour, or having done work for nothing.

I would expect the name and possibly a dedicated sports icon.

Related to this are my expectations:
- Sports centres: name, which may be different from one or more contained clubs.
- Sports pitches: dedicated icons.

**Comment by sommerluk** [comment]
Your description of what exactly the problem is, is somewhat unclear. The sports center in your example is https://www.openstreetmap.org/way/10068738#map=16/52.1759/4.4839. This feature actually _is_ rendered:
![grafik](https://user-images.githubusercontent.com/6830724/193599923-662e0baf-0ee3-4d86-b2dd-1bc8e47ed104.png)

**Comment by HolgerJeromin** [comment]
Please adjust your words. 
At least I interprete your "As ever, its very frustrating" (from the last 5 issues from you)  as "your work sucks".

**Comment by BertMule** [comment]
Please also note the other centres to the south-west, and that I am speaking about the combination of **three** entities:
- club=sport
- leisure=pitch
- leisure=sports_centre

**Comment by jeisenbe** [comment]
`leisure=pitch` and `leisure=sports_centre` are already rendered. 

`club=sport` is not rendered, nor any other value of `club=*` - there was some discussion about this in issue #4489

Are you requesting a rendering for `club=sport`? 

The only `club=sport` features in your example location are 3 nodes such as this one, inside of a building which is also inside of a larger `leisure=sports_centre` area, for example: https://www.openstreetmap.org/node/10072887943

**Comment by fizwidget** [comment]
> People may also add the name to a pitch.

I’ve just seen an example of this (a pitch bearing the name of a club that happens to use it). I fixed it by moving the club’s name & details to a separate club=sport node.

Of course, I then discovered that it no longer renders at all in Carto. I strongly suspect this is why the club name was added to the pitch in the first place. 

So it seems Carto’s current behaviour here is encouraging “tagging for the renderer” :/

**Comment by imagico** [comment]
Please always provide links to examples you discuss.

I mostly concur with your observation.  The reasons why we currently don't render `club=sport` are given in https://github.com/gravitystorm/openstreetmap-carto/issues/4489#issuecomment-965022103.  We have an open issue about not rendering `name` on `leisure=pitch` any more (#4210).

Without knowing your specific example i cannot say if `leisure=sports_centre` would be a viable tagging here (and if the club's name is actually a valid name for that or if it is the operator) - but that is a discussion for a different place anyway.
