### ISSUE TITLE
Names of defensive_works sometimes not displayed

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4708]
At the city of [Naarden ](https://www.openstreetmap.org/#map=16/52.2949/5.1648) there are a lot of defensive_works, like bastions and ravelins.  Names are often not displayed. 

Some observations
- While editing, making them an area at first seemed to help, though others already resulted in problems. But even rendering of the first category did not actually work.
- There are some simple ravelins that are displayed with a name. They are unconnected islands with singular land-use. 
- The ID-editor does not well support defensive_works.

So what is going on?

**Comment by imagico** [comment]
We don't render `defensive_works=*` tags.  If you see something being rendered in the map in some way that has nothing to do with `defensive_works=*` tags.

https://wiki.openstreetmap.org/wiki/Key:defensive_works

704 uses in total, 661 of these in Europe, very uneven distribution of mapping (https://taginfo.geofabrik.de/europe/keys/defensive_works#map)

Most common value is `defensive_works=bastion` with 300 uses.

Closing as the question is answered as far as it pertains to this style.  And we most likely do not want to render `defensive_works=*` tags at this time.

**Comment by BertMule** [comment]
Request to render the name.
Just the name...
