### ISSUE TITLE
Animal enclosures ways not mapped.

### ISSUE THREAD

**Issue by EvanCarroll** [gravitystorm/openstreetmap-carto#4718]
### Expected behavior
They show.

### Actual behavior
They do not show.

### Screenshots with links illustrating the problem
Looking up the Houston Zoo way 51816626

![Screenshot_2022-10-22_21-35-57](https://user-images.githubusercontent.com/19922/197370454-3b1da450-7666-4c6a-afe4-052366d93542.png)

I moved the POI animal enclosures to ways, they only show when you hit Edit and use the OpenStreetMap standard.

![Screenshot_2022-10-22_21-37-18](https://user-images.githubusercontent.com/19922/197370497-89f1839c-528b-4b4e-8e22-994262772bdc.png)

**Comment by jeisenbe** [comment]
These enclosures appear to be tagged `attraction=animal` e.g. https://www.openstreetmap.org/way/1105075701 - a request to render `attraction=animal` is already open in issue #3775 so I will close this as a duplicate.
