### ISSUE TITLE
Quarter only rendered as point?

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4722]
Despite issue #798 stated to be solved, I am still puzzled whether it totally works.

Currently I do get rendering as a point.  But only at lesser zoom levels (bigger scales), which caused confusion at first.

As an area it did not turn up. In my understanding from documentation it should.

Both forms are still present in [Jeugddorp ](https://www.openstreetmap.org/#map=18/51.81250/4.70205).

I also experimented with boundaries. I don't think it turned up. But it is not what I want to start with.

Thanks.

**Comment by danieldegroot2** [comment]
For minor places, [only nodes are rendered](https://github.com/gravitystorm/openstreetmap-carto/blob/aa35c89ec5fa0ae0413d0fb597164c8c5d2c997e/project.mml#L1342) on Carto (other renderers may differ).
(In `SELECT` above, [`"way"`](https://github.com/gravitystorm/openstreetmap-carto/blob/aa35c89ec5fa0ae0413d0fb597164c8c5d2c997e/project.mml#L1339) is the term which is continuously used when getting an object's geometry, or its coordinates in case of a point.)

As mentioned on the [wiki page for `place=quarter`](https://wiki.openstreetmap.org/wiki/Tag:place=quarter), nodes are easier for rendering and routing purposes as
- they require less complicated calculations for finding their (center) position.
- it's easier to have all the relevant tags (i.e. international names) on just the node.

(the section "Used on these elements" on the wiki only indicates what are valid ways to map, not what is rendered by anyone. When hovering over the icons, you'll also see a hover text "may be used on ..." or "should not be used on ..." for each of them.)

See also https://github.com/gravitystorm/openstreetmap-carto/issues/103#issuecomment-646213745 and below. Sidenote: label placement for small areas is [not optimal](https://github.com/gravitystorm/openstreetmap-carto/issues/3857) currently.

**Comment by BertMule** [comment]
So in fact they ARE only rendered as point.
I will remove the one on area.
Thanks for the clarification.

I wish definition of tags was aligned with rendering, at least in Carto.
So if it is applicable for both a point and an area, then it is also rendered on both .
If a tag is defined, then it is paired with some rendering, even if it is just generic.
That would prevent endless confusion, questions, discussions, and frustration.

**Comment by joshinils** [comment]
What about place-areas that have no label-node? What about `place=neighborhood|city_block|plot` which may be very small?
I don't understand why mapping it as a place does not render the name, opposed to a named `landuse=*` where it does.
