### ISSUE TITLE
rendering of openstreetmap-carto is slow

### ISSUE THREAD

**Issue by a14stoner** [gravitystorm/openstreetmap-carto#4737]
Hello I have a question!

Is it known that the rendering of tiles from this repo is much slower than from the repo https://github.com/openstreetmap/mapnik-stylesheets ? Switched to this repo some time ago and the rendering is much slower than in the older repo. 

If someone says otherwise please comment so we can talk together.

**Comment by HolgerJeromin** [comment]
Did you adjusted the sql index?
Did you deactivated JIT?
See https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#disable-jit for both

**Comment by a14stoner** [comment]
I took the default indexes from this repo. 
i disabled jit for now and retry rendering. 

thanks in advance

**Comment by a14stoner** [comment]
@HolgerJeromin i cant tell you how happy i am. it renders fast now. i dont know why i did not see the configuration hint for that....... thanks a million....
