### ISSUE TITLE
barrier=planter 

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#4751]
### Expected behaviour

To render a symbol representing a barrier=planter. 
https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dplanter
https://taginfo.openstreetmap.org/search?q=barrier%3Dplanter+

### Actual behaviour

It doesn't.

-----

This style of traffic restriction is on the increase in Britain (& around the world?), particularly in the urban environment. 

I'm aware long discussions can be had over the specific symbols used to represent barriers, but I think it would be fine to use a simple black square.

**Comment by imagico** [comment]
`barrier=planter`: 2.1k uses
`man_made=planter`: 7.9k uses
~500 use both.

It could be worth researching how many of the 2.1k are actually barrier nodes on highway=* and how many are just a less popular synonym for `man_made=planter`.

**Comment by imagico** [comment]
> It could be worth researching how many of the 2.1k are actually barrier nodes on highway=* and how many are just a less popular synonym for man_made=planter.

Looking at tag use a bit further it seems clear that `barrier=planter` is used just as much for standalone planters as it is for nodes on `highway=*` compared to `man_made=planter`.  Given the much wider use of `man_made=planter` overall i think it would be preferable to render that.

I think there are ways to render `man_made=planter` in a distinct way at z18/z19 that communicates _vegetation enclosed by a wall like linear barrier_ - which is what most planters essentially are.  Some care would need to be taken for the symbol used not to be mistaken as a mapped geometry.

I suggest we close this in favor of #4868.
