### ISSUE TITLE
Rendering of hazard=hole

### ISSUE THREAD

**Issue by troelsarvin** [gravitystorm/openstreetmap-carto#4759]
In #4483 general rending of hazards was rejected, because it seems boundry=hazard usage is somewhat inconsistent and fluffy.

However, I propose a more specific type of hazard be rendered: **[hazard=hole](https://wiki.openstreetmap.org/wiki/Tag%3Ahazard%3Dhole)**

My reasoning is that use of this type of hazard is so specific that it's less likely to be inconsistently used. Also, I believe there is value in highlighting this type of hazard. I came across such a case recently: http://troels.arvin.dk/osm/topics/hole_in_ground_in_tyrkey/

**Comment by imagico** [comment]
178 uses, wiki page is very non-specific w.r.t. verifiable characteristics.

Most uses seem to be mapping of potholes with a node on `highway=*`.  The rest is mostly in combination with one of:

* `natural=cave_entrance` (which we render)
* `natural=cliff` on ways (which we render)
* `natural=sinkhole` - see #2414
* `man_made = manhole` - see #4353

**Comment by pnorman** [comment]
Insufficient usage to add a rendering for.
