### ISSUE TITLE
Some airport terminal names not rendered

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4768]
I don't see the name of
https://www.openstreetmap.org/way/9847872
rendered. But I do for
https://www.openstreetmap.org/way/303149554 .

**Comment by HolgerJeromin** [comment]
The name of the railway=station https://www.openstreetmap.org/node/4653352237 is rendered so the name of the building (has nothing to do with a terminal) has not enough space.


Colliding names should be no new topic for you, shouldn't it? #4688, #4578, #4150

**Comment by jidanni** [comment]
I see. Well at least the [other terminal](https://zh.wikipedia.org/wiki/zh:%E8%87%BA%E7%81%A3%E6%A1%83%E5%9C%92%E5%9C%8B%E9%9A%9B%E6%A9%9F%E5%A0%B4%E7%AC%AC%E4%B8%80%E8%88%AA%E5%BB%88?uselang=en) is still named, though only at highest zoom level,
https://www.openstreetmap.org/way/9847873
because luckily it doesn't have it's subway stop in the center.

**Comment by imagico** [comment]
Closing as duplicate for other issues in this generic form (like @HolgerJeromin pointed out).

Specific suggestions how to address this particular collision problem are welcome - but are difficult as long as the more fundamental problems are not addressed (like #3880).

**Comment by jidanni** [comment]
Hmmm, maybe items with Wikipedia articles linked should win over those that don't.
I.e., some Mom and Pops Diner shouldn't knock some Jefferson Memorial off the map.
