### ISSUE TITLE
How to change the font-size of road names

### ISSUE THREAD

**Issue by muellercornelius** [gravitystorm/openstreetmap-carto#4776]
It is not a real bug. I think I am just doing it wrong. I am running my own tileserver and I want to increase the font size of my road names.

Thats why I changed those lines:
https://github.com/gravitystorm/openstreetmap-carto/blob/6591d7b97ce34395d8e214d25329c50742bce044/style/roads.mss#L3756-L3791

to have bigger text sizes in the higher zoom steps:
```
     [zoom >= 14] {
      text-size: 9;
    }
    [zoom >= 15] {
      text-size: 10;
    }
    [zoom >= 17] {
      text-size:  20;
    }
    [zoom >= 19] {
      text-size: 30;
    }
```
on zoom level 17 the names are really big. So it seems to work. But on zoom level 18 and above they are a lot smaller again....

Am I doing something wrong or miss something?

Zoom Level 17: 
![image](https://user-images.githubusercontent.com/26606825/217651131-b04653b3-872f-41dd-96eb-689428f944fa.png)

Zoom Level 18:
![image](https://user-images.githubusercontent.com/26606825/217651237-12df0df8-8e12-4009-a448-12f249b7561f.png)

If someone please could point me in the right direction. That would be awesome. Thank you very much.

**Comment by imagico** [comment]
The sample renderings shown are at different resolution.  It is expected that a rendering at z18 at lower resolution leads to a smaller font size relative to the rendering pixel size than at z17 at higher resolution.

In case that is not clear:  Font sizes in Mapnik are specified relative to nominal map scale or zoom level, not relative to the rendering pixel size.  See also #3657.
