### ISSUE TITLE
River label renders on top of bridge

### ISSUE THREAD

**Issue by packi** [gravitystorm/openstreetmap-carto#478]
Example:
![screen shot 2014-04-16 at 1 23 20 pm](https://cloud.githubusercontent.com/assets/493734/2719063/485e9fc8-c55a-11e3-8b89-f1c65e1ae1de.png)

Bridge: http://www.openstreetmap.org/way/8147286
Waterway: http://www.openstreetmap.org/way/27600092

**Comment by alfmarcua** [comment]
A partial humble solution to this issue could be to have a phantom label for bridges that displaced river labels. In particular, it could be achieved by giving a label style with opacity 0 to the bridges whenever their own label it is not displayed.
