### ISSUE TITLE
Fill for unclassified miniroundabouts missing

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4781]
Mini-roundabout fill colours are defined in https://github.com/gravitystorm/openstreetmap-carto/blob/f066b0b6a376c97f890904498ab745d7405b9c0c/style/roads.mss#L3134-L3140

This does not include highway=unclassified, resulting in a blue dot instead of one that matches the casing.

![image](https://user-images.githubusercontent.com/1190866/221345837-086e46ab-af61-4bad-9037-87cc4c9a0c14.png)

The node in question is https://www.openstreetmap.org/node/253329433, but a data change on osm.org means it no longer shows the problem.

**Comment by imagico** [comment]
Tertiary is wrong as well:

![tertiary](https://imagico.de/files/carto_turning_circles_17_40.png)

**Comment by imagico** [comment]
See also https://github.com/gravitystorm/openstreetmap-carto/issues/4380#issuecomment-823224885
