### ISSUE TITLE
Large park with name... somewhere

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4785]
We see this [large park](https://www.openstreetmap.org/way/450179501), but what is its name?
We look up and down but can't seem to find it.
We need to execute a [query](https://www.openstreetmap.org/query?lat=37.5892&lon=-122.3231) to finally find out:
[Coyote Point Recreation Area](https://en.wikipedia.org/wiki/Coyote_Point_Recreation_Area).

**Comment by sommerluk** [comment]
Closing. Works for me.

**Comment by jidanni** [comment]
I can see it only at zoom level 14. No other zoom levels.
https://www.openstreetmap.org/#map=14/37.5885/-122.3240
