### ISSUE TITLE
View Database Data And Structure

### ISSUE THREAD

**Issue by littlTom** [gravitystorm/openstreetmap-carto#4793]
![image](https://user-images.githubusercontent.com/118588293/226537052-41fd36af-8410-42b4-8a10-d68ced7371aa.png)
I load the load map stylesheet and map data into the database by osm2pgsql. I want to plot an ER diagram of the database but I don't know how to view database data and structure. Could you give me some advice? Thanks a lot!

**Comment by pnorman** [comment]
An ER diagram is unlikely to be useful as a rendering database has no relationships between different tables. Regardless, any tool that can work on PostgreSQL DBs should work fine. I don't have any particular recommendations, and doing so is really outside the scope of OSM Carto
