### ISSUE TITLE
Why is node golf=hole being rendered the same as golf=pin?

### ISSUE THREAD

**Issue by DaveF63** [gravitystorm/openstreetmap-carto#4804]
Hi
Why is node golf=hole being rendered the same as golf=pin?

https://www.openstreetmap.org/node/7674311131

golf=hole should only be used on a way.

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgolf_course#Features_within_a_golf_course

This rendering should be removed to discourage golf=hole being used as a node.

**Comment by imagico** [comment]
This is probably based on the original implementation in the french style:

https://github.com/cquest/osmfr-cartocss/blob/9a7543eaee34fbb551e45550f3a14a7473639b17/sports.mss#L50

`golf=hole` is indeed practically not used on nodes (https://taginfo.openstreetmap.org/tags/golf=hole#overview) - so this should be changed.
