### ISSUE TITLE
Please render museum areas

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4805]
Currently museum-areas are not distinctive.

Example is this large area (2 separate parts)  covering railroad tracks and buildings.
https://www.openstreetmap.org/#map=18/52.15961/4.44358

It would clarifying to have a different colour to set it apart from non related areas and objects.

**Comment by HolgerJeromin** [comment]
thanks for the report.
this is already covered by #2704

**Comment by BertMule** [comment]
Thanks, I had not found that.
I hope that will go forward, it has not for a while.
