### ISSUE TITLE
Rendering artifact on leisure=marina

### ISSUE THREAD

**Issue by lest69** [gravitystorm/openstreetmap-carto#481]
I just noticed there's a small artifact on the rendering of leisure=marina. It's on every marina area I checked in my region, and appears to always be on the westernmost node of the area.
![capture](https://cloud.githubusercontent.com/assets/6880533/2724577/18530f28-c5a3-11e3-8e7c-a7785a7692b5.PNG)
There are a number of marinas around [here](http://www.openstreetmap.org/#map=16/48.4258/-123.3840) if you want to inspect them further.

**Comment by matkoniecz** [comment]
https://github.com/mapnik/mapnik/issues/2851 is a new mapnik ticket about "Predictable offsetting on polygons"

> 2834 introduces a problematic back compatibility problem for cartographers using line-offset on polygons because it will potentially flip the side of the polygon that the offset occurs on.

> This may be a serious blocker for people upgrading to Mapnik 3.0.0.

> Let's brainstorm solutions...

**Comment by math1985** [comment]
This should be fixed upstream: https://github.com/mapnik/mapnik/pull/2904

Thanks @springmeyer!

**Comment by matkoniecz** [comment]
Also, thanks @flippmoke!

**Comment by matkoniecz** [comment]
Is it also covering rendering border only on one element of multipolygon like at http://www.openstreetmap.org/?mlat=51.5386&mlon=-0.1576#map=12/51.5386/-0.1576 ?

![selection_001](https://cloud.githubusercontent.com/assets/899988/8717513/98e6ed16-2b9c-11e5-9cfd-4535e03c03ba.png)

**Comment by math1985** [comment]
Never noticed that - @springmeyer has this been solved or is it worth reporting?

**Comment by pnorman** [comment]
Confirming fixed

**Comment by math1985** [comment]
This should have been fixed now on openstreetmap.org as Mapnik 3 has now been rolled out. Note that some tiles might not have been updated yet.

**Comment by SomeoneElseOSM** [comment]
#1237 , which was the same problem as this, is certainly fixed in the standard style now it's on MApnik 3.
