### ISSUE TITLE
Request to render highway=residential & area=yes

### ISSUE THREAD

**Issue by Drahflow** [gravitystorm/openstreetmap-carto#4811]
### Expected behavior

The same arguments for highway=service & area=yes objects also apply for highway=residential & area=yes. Thus ways with highway=residential & area=yes should be rendered as residential-street-textured areas.

I checked a few instances of this tag combination around the lat/lon of the one linked below, in all cases they were not mis-mapped areas of essential linear ways, but square-like areas across which vehicles could drive omnidirectionally.

### Actual behavior

Such objects are invisible.

### Screenshots with links illustrating the problem

![residential-area-carto](https://user-images.githubusercontent.com/609223/235651243-b70a0077-76fe-4225-9cf2-4d827ade2a59.png)
https://overpass-turbo.eu/s/1usa

vs.

![residential-area-bing](https://user-images.githubusercontent.com/609223/235651270-aee8fa53-17d7-470f-a29c-609b4271be7a.png)
https://www.bing.com/maps?q=hannover+map&FORM=HDRSC6&cp=52.282895%7E10.612627&lvl=19.0&style=h

**Comment by imagico** [comment]
Would revert #4096 - see #3995 for a lengthy discussion of this.  See also  #3985, #4637.

Please bring up any _new_ arguments on the matter here.

**Comment by Drahflow** [comment]
In somer other issues (e.g. https://github.com/gravitystorm/openstreetmap-carto/issues/3995#issuecomment-575946162 , and thus a few years back), it is claimed that no guidance exists on the wiki. I derived my understanding from this section:
https://wiki.openstreetmap.org/wiki/Key:area:highway
> [area](https://wiki.openstreetmap.org/wiki/Key:area)=[yes](https://wiki.openstreetmap.org/wiki/Tag:area%3Dyes) on a [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=* describes a routable highway area on which the dedicated traffic can route omnidirectionally; i.e. from any point along the edge to any other. This is typical for pedestrian areas, or service areas where vehicles drive without prescribed lanes. The rationale is that routing engines should consider those omnidirectional objects in addition to nodes and edges in classical graph theory; thus no linear highway lines would be required within. However, as of 2019, [OpenTripPlanner](https://wiki.openstreetmap.org/wiki/OpenTripPlanner) is the only OSM-based router that supports routing over areas. It does so by computing a visibility graph over the area. [[1]](https://github.com/osmlab/osm-planning/issues/17)

**Comment by Drahflow** [comment]
Another argument: What would otherwise be the correct way to map https://en.wikipedia.org/wiki/Shared_space ? (And I think some of the examples I found in Germany so far were attempts at implementing it.)

**Comment by imagico** [comment]
Changes in actual use of `highway=residential` on polygons or in mapper consensus on what this means since #4096 would be the main reason for revisiting the decision.  But i don't see any indications for that so far.  I also would not assume that the shown example is by mapper consensus considered a valid use of `highway=residential` on polygons.  If it is it would be important to have documentation of that.

**Comment by pnorman** [comment]
I would be against rendering it, for the reasons matkoniecz mentions, and were previously established in t he linked issues. I don't see that anything has changed since then.
