### ISSUE TITLE
Playhouse not rendered in park

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4816]
Here is an example of inconsistent behaviour in a park.
- Playhouse is not rendered.
- While playground and picknick-table are.

https://www.openstreetmap.org/#map=19/52.16277/4.47963

**Comment by HolgerJeromin** [comment]
I asume you mean this node:
https://www.openstreetmap.org/node/10905248295

`playground=playhouse`
We discussed playgruond equipment in: #3161

**Comment by BertMule** [comment]
Indeed.

I had not found the other issue/pull-request.
See my remark there.

**Comment by imagico** [comment]
Closing this as the specific request to selectively render `playground=playhouse` is not going to find support here.

#3161 was closed with the decision not to render playground details.  We could revisit that decision in light of how widely these are meanwhile mapped (https://taginfo.openstreetmap.org/keys/playground#overview) and how meaningful these can be for a significant part of our target users base (kids and families with kids) and that we have an increasing interest in developing the high zoom levels (#4661).

For this to actually have a chance (in particular in light of #3635) a concrete and viable design concept would be needed.  Just dumping a number of additional POI symbols into the system - like #3161 attempted - is not likely going to find approval.  What is necessary here is some solid, holistic design work with outside-the-box thinking (compare for example also #844).  Anyone who wants to work on that should feel welcome to open a new issue.  And for those who want to contribute but do not have the design skills - working on #3880 would help a lot here as well.

**Comment by BertMule** [comment]
For clarity. I don't suggest to distinguish and depict all sorts of playing-objects. That's too much detail.
Just that both a playground (area) and any play-object (point) are depicted. 
The latter in a generic  way. That's how I interpreted it to start with. 
And I thought to have seen it that way. Has that changed?

**Comment by imagico** [comment]
We are rendering (and have rendered since version 1.0) `leisure=playground` on points and polygons:

https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=leisure&value=playground
https://imagico.de/map/styleinfo/#style=osmcv1&section=tags&key=leisure&value=playground

We have never rendered any `playground=*` features so far.
