### ISSUE TITLE
Render turn restrictions

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4829]
### Expected behavior
https://wiki.openstreetmap.org/wiki/Relation:restriction are important. Users need to know that they won't be able to turn where they think they can, and thus should turn earlier.
### Actual behavior
Not rendered.
### Screenshots with links illustrating the problem
https://www.openstreetmap.org/node/4416898149
![20230611T070155](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/485c8ccf-78c0-4d94-bb1c-db35574b32b6)
We only see the restriction in the Cycle layer.

**Comment by imagico** [comment]
> We only see the restriction in the Cycle layer.

No.  There are two `no_u_turn` restrictions involving the node in question here and none of them is in any way visualized by any of the layers on osm.org.

It would be necessary to provide suggestions how you'd want the style to visualize what type of turn restrictions.  Any pointers to maps doing that would be useful as well.  But keep in mind that a technique for us to use would have to work both for left side and right side traffic.

**Comment by jidanni** [comment]
Indeed, Cycle layer was rendering one-way https://www.openstreetmap.org/way/430276497 !

**Comment by pnorman** [comment]
I'm not aware of any maps which render turn restrictions. JOSM can show them, but not in a way that makes it obvious what movements they're applying to.

I'm going to close this for three reasons

1. It is not normal to show turn restrictions on a map, and there are no other examples we can look at for inspiration.
2. Looking at turn restriction editors, it's really too much information to display, particularly when we look at intersections with multiple left or right turn directions.
3. Any visualization is likely to involve via nodes, which we do not have access to for technical reasons.
