### ISSUE TITLE
amenity=lounger

### ISSUE THREAD

**Issue by hungerburg** [gravitystorm/openstreetmap-carto#4830]
Recently I notice that a lounger, that I mapped has turned into a bench - not on location, but in the data. My suspicion, loungers do not render. So here a try. I am afraid it looks a bit like a shoe? Maybe someone else can do better. It is a first idea. Feel free to do whatever!

![lounger](https://github.com/gravitystorm/openstreetmap-carto/assets/586972/50944342-ef13-42d5-a64b-27117a9eff83)

**Comment by pnorman** [comment]
Duplicate of #4469. Please check existing issues before opening a new one.

**Comment by hungerburg** [comment]
Sorry, I just read the bold print **"Your search did not match any code"** in the centre of the result of the search. Did not realize that in the side column there hide 2 hits. Please update the search form.

**Comment by imagico** [comment]
That is an issue with the github UI, nothing we can do anything about here.
