### ISSUE TITLE
Landfill at some zoom levels, golf course at others

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4831]
I'm not sure if I discovered something new here, but...
https://www.openstreetmap.org/?mlat=42.1121&mlon=-87.8160#map=14/42.1121/-87.8160

### Expected behavior

Probably all golf course for all zoom levels.

### Actual behavior

13. Lake Land Fill
14. Lake Land Fill
15. Willowhill Golf Course
16. Willowhill Golf Course
17. Willowhill Golf Course

### Screenshots with links illustrating the problem

![20230618T073641](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/8967cea9-b4a4-46c3-b26b-2fce25812945) 
![20230618T082223](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/158c2e92-6896-4220-8a19-1fe1e536d212)

Yes, this is the edge case of concentric items.

**Comment by imagico** [comment]
Same as written in https://github.com/gravitystorm/openstreetmap-carto/issues/4828#issuecomment-1583242932 applies:

> We currently render point symbols with priority over point labels independent of the starting zoom level.  That could be reconsidered but that would depend on solving #3880.

Closing because of that.
