### ISSUE TITLE
Bridge hurts road at end

### ISSUE THREAD

**Issue by jidanni** [gravitystorm/openstreetmap-carto#4843]
The location is [GPS 42.112740 N 87.739419 W] https://www.openstreetmap.org/?mlat=42.1127404&mlon=-87.7394188#map=20/42.1127404/-87.7394188

![Screenshot_20230718_074826_All-In-One Offline Maps.jpg](https://github.com/gravitystorm/openstreetmap-carto/assets/1230959/664d5dd5-a7ea-4aca-868b-b048572f2911)

True, the user should start the bridge a little bit after the corner. But in cases that the user doesn't, the rendering still should show the bridge starting after the corner not in the middle of the corner. Don't you think?

I mean if I make a right turn onto a bridge the bridge doesn't start in the middle of the road, it starts after I make the turn, how far after I make the turn, let's say 0 m after I make the turn.

Then there's the worrisome case of bridges that really do land in the middle of roads. But there would certainly be some ramps to connect it so there's little worry about such cases.

**Comment by imagico** [comment]
The rendering here shows exactly what is mapped (i.e. a bridge starting in the middle of another road) and this rendering result is as intended.  This is even [prominently documented to not be valid mapping](https://wiki.openstreetmap.org/wiki/Key:bridge).

Some other map styles might try to do mind reading of mappers (like: here the mapper probably intended to map something different so we show it as if they had actually done so) - but this is not compatible with our goals.

(Side note: this does not mean that the mapper mind reading idea would be easy to implement in cases like this.  You have tons of geometric configurations to consider here.  Practically i doubt any map style has actually attempted something like that)

**Comment by jidanni** [comment]
I'm worried about cases where a river has two roads on either side and no banks but just steep walls. Crossing the river or several bridges, you might say once each city block. Like an "H".

There is no land under the bridge, and there is no empty space under the roads. And there is no margins anywhere too do anything about it.

**Comment by imagico** [comment]
This is not a rendering question but a mapping question.  None the less quickly:

If you have two 8m wide roads next to a 12m wide river and a bridge connecting the roads across the river that would be mapped with two ways tagged `highway=*` at a distance of `12m+2*4m=20m` and the bridge would be a way of a length of 12m tagged `highway=*` + `bridge=yes` connected to the two roads with shorter ways tagged `highway=*` without a bridge tag of a length of 4m.

**Comment by jidanni** [comment]
Hmmm, wish there was a old army base, on a different planet, where we could set up, and link to demonstrations of each of these concepts, all without harming the (real) map.
