### ISSUE TITLE
Render living_street=yes

### ISSUE THREAD

**Issue by tjur0** [gravitystorm/openstreetmap-carto#4847]
### Expected behavior
Any fill type road classification should get the living_street fill color if it has `living_street=yes`.

Highway=tertiary
https://www.openstreetmap.org/way/1193317625
https://www.openstreetmap.org/way/6967557

Highway=service
https://www.openstreetmap.org/way/158749637
https://www.openstreetmap.org/way/643505376

### Actual behavior
`living_street=yes` is not rendered

### Screenshots with links illustrating the problem
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/52704747/bc4d66fc-8506-4956-af42-83a0e77c490f)

**Comment by pnorman** [comment]
This was considered and rejected in #3514. See also https://github.com/cyclosm/cyclosm-cartocss-style/issues/146. Closing as duplicate.
