### ISSUE TITLE
Chinese font support

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#486]
Continuing the work in #414, I'm looking at CJK fonts. Because Han unification makes this more complicated than other fonts, I'm looking at Chinese first.

The following unicode fonts appear to be packaged on ubuntu 12.04, and serves as a preliminary list

* fonts-arphic-ukai - "AR PL UKai" Chinese Unicode TrueType font collection Kaiti style
* fonts-arphic-uming - "AR PL UMing" Chinese Unicode TrueType font collection Mingti style
* ttf-wqy-microhei - A droid derived Sans-Seri style CJK font
* ttf-wqy-zenhei - "WenQuanYi Zen Hei" A Hei-Ti Style (sans-serif) Chinese font

**Comment by mxa** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/issues/2204#issuecomment-230020607
