### ISSUE TITLE
Shape files download failed

### ISSUE THREAD

**Issue by Cactustory** [gravitystorm/openstreetmap-carto#4879]
Hello,
I did everything step by step correctly with https://switch2osm.org/serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts/ but when I tried to download shapefiles I ran into this problem.
root@srv94600149:~/src/openstreetmap-carto# sudo -u _renderd scripts/get-external-data.py
INFO:root:Starting load of external data into database
INFO:root:Checking table simplified_water_polygons
INFO:root:  Table simplified_water_polygons did not require updating
INFO:root:Checking table water_polygons
Killed
It kills the process and the folder is empty.
I checked logs and one of the errors is: An error occurred while loading the map layer 's2o': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist

**Comment by pnorman** [comment]
It looks like it was OOM killed. What do your system logs say for why it was killed?

**Comment by Cactustory** [comment]
Yes, you are right. It was because of a lack of RAM, that I fixed it with the swap.
