### ISSUE TITLE
Stream tunnel under a swimming pool rendered incorrectly

### ISSUE THREAD

**Issue by LoremoCH** [gravitystorm/openstreetmap-carto#488]
At Rheinau in Switzerland (http://www.openstreetmap.org/#map=18/47.63811/8.59941) two stream tunnels are exactly under a swimming pool. But on the map the where renderet as they would be on top of it.

It is possible to change that?

**Comment by mkoniecz** [comment]
I am not sure is it bad. Rendering tunnels below features that are above them would make tunnels invisible in fully mapped areas.

**Comment by kocio-pl** [comment]
I see no easy fix for this.

**Comment by pnorman** [comment]
> I see no easy fix for this.

My only thoughts are making the casing alternating `@land-colour` and blue dashes.

**Comment by HolgerJeromin** [comment]
Just to provide a screenshot for the future:
![image](https://cloud.githubusercontent.com/assets/2410353/21239624/f9aab5de-c307-11e6-9390-c1882b0ad304.png)

**Comment by nebulon42** [comment]
I think we have to reject the request of the OP. It would be desirable to have the tunnel covered by the pool in this case. But this would be undesirable in a lot of other cases. The vanishing dashes are not ideal and can be improved. @pnorman's idea is the right solution for this.

**Comment by pnorman** [comment]
Fixed in #2594
