### ISSUE TITLE
Zoom 17 + 18 correct, Zoom 19 has a superior last letter

### ISSUE THREAD

**Issue by JuergenAuer** [gravitystorm/openstreetmap-carto#4883]
Hi,

I've changed a name of an object.

### Expected behavior

Zoom 17 and 18 are correct. "37. Schule (Grundschule)".

### Actual behavior

Zoom 19: The last "e" is like a (html) sup - element. Current Chrome + FF (Desktop), same with Chrome mobile and Samsung mobile.

Links + Screenshots:

Zoom 18 - perfect:

https://www.openstreetmap.org/#map=18/52.52105/13.43858

![2023-10-12 OSM-perfect-18](https://github.com/gravitystorm/openstreetmap-carto/assets/65248690/3cd17439-2240-4926-95a3-94078ec2739c)

Zoom 19 - wrong last letter and missing ")"

https://www.openstreetmap.org/#map=19/52.52133/13.43893

![2023-10-12 OSM-Bug-19](https://github.com/gravitystorm/openstreetmap-carto/assets/65248690/a4e0505b-183b-49bd-a36b-e026d8d6ce8e)

Looks like a bug.

**Comment by swedneck** [comment]
this isn't a bug, just a tile that didn't have time to update. Try looking at the map again now, it looks fine to me.
i think you were a bit too eager to see your changes, give the tiles a bit more time to update in the future

**Comment by JuergenAuer** [comment]
The change is two days old. And my desktop may have a wrong cache. But mobile - first tested today, 21:15, not on Tuesday.

**Comment by swedneck** [comment]
hm, okay that's weirder then, but still it shows up just fine on my end so it's not a carto issue at least, *possibly* an issue with the osm.org deployment but more likely your caches just need to be cleared so the device gets the new tiles.

**Comment by imagico** [comment]
I cannot reproduce the observation but this is quite definitely not a style problem.  The issue is at a z19 tile boundary, hence likely a problem related to delayed updates in rendering:

![tile 1](https://tile.openstreetmap.org/19/281715/171939.png)
![tile 2](https://tile.openstreetmap.org/19/281716/171939.png)
