### ISSUE TITLE
Proposal for OSM Carto rendering template for new icons

### ISSUE THREAD

**Issue by santasa99** [gravitystorm/openstreetmap-carto#4888]
**Proposal**
I would like to propose two new icons for carto rendering. It concerns three Tag pages and their respective tags:

I created icons for Tag pages {{tag|historic|stećak_necropolis}} and {{tag|historic|stećak}} with the icon File:Stecak icon osm 16.svg and {{tag|tower:type|clock}} with File:Clock-tower.svg

first for tags:

historic=stećak_necropolis
historic=stećak

and second one for:

tower:type=clock

Why
We lack icons that can properly illustrate these specific features.

Icons
![Stecak_icon_osm_16 svg](https://github.com/gravitystorm/openstreetmap-carto/assets/46263947/aea7d62b-2f6e-4826-8bb1-8053632c9a0a) ![16px-Stecak_icon_osm_16 svg](https://github.com/gravitystorm/openstreetmap-carto/assets/46263947/54a24612-e754-45a3-b46f-1b5d4b77cec9) Tag:historic=stećak necropolis [https://wiki.openstreetmap.org/wiki/Tag:historic%3Dste%C4%87ak_necropolis] and Tag:historic=stećak [https://wiki.openstreetmap.org/wiki/Tag:historic%3Dste%C4%87ak]
![Clock-tower svg](https://github.com/gravitystorm/openstreetmap-carto/assets/46263947/398ffcce-e831-4aa9-94bd-dfa3407fe851) ![16px-Clock-tower svg](https://github.com/gravitystorm/openstreetmap-carto/assets/46263947/65c8b9b5-3593-465b-9e0e-10d954e1f54b) Tag:tower:type=clock [https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dclock]

Please, don't laugh at this, I am completely new here. :-)

**Comment by pnorman** [comment]
Normally these should be two different issues.

To add a rendering of something, there needs to be enough general adoption. There are 2 [historic](https://taginfo.openstreetmap.org/keys/historic)=stećak and 450 clock.

Additionally, neither icon will work at 14x14, which is what we use.

**Comment by imagico** [comment]
Thanks for the suggestions.  Sketches like you made are valuable and fine as a start but are better placed on the OSM wiki. For actual use here we would be looking for something in line with our [style guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines).

Like @pnorman said - the tags you are proposing are all for the moment not in broad enough use to mandate rendering.  For reference:

`historic=stećak_necropolis`
https://wiki.openstreetmap.org/wiki/Tag:historic%3Dste%C4%87ak_necropolis
16 uses

`historic=stećak`
https://wiki.openstreetmap.org/wiki/Tag:historic%3Dste%C4%87ak
2 uses

`tower:type=clock`
https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dclock
450 uses
if rendered symbol should be consistent with that of [tower:type=bell_tower](https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dbell_tower)

Like for `tower:type=bell_tower` there is the problem of competing concepts of mapping/tagging the clock/bell vs. mapping as a secondary tag to the built structure supporting it - for clocks the standalone `amenity=clock` is much more widespread - see #3577.  For bells the opposite is the case (see https://wiki.openstreetmap.org/wiki/Proposal:Bell) - though in reality, standalone bells are widespread in some parts of the world (like certain christian traditions).  Documenting where `tower:type=clock` is used vs. where `amenity=clock` is used would be helpful for this.

It would definitively be good if we'd have more comprehensive rendering of historic features in the map (which depends a bit on broadly and consistently used taggings for those of course).  But these two tags are not really the point to start with here.

Side note (off-topic here though) - it has been long standing informal convention to avoid using non-ASCII characters in classifying tag values.  While this is not a firm requirement (neither here nor elsewhere) this is definitely something to consider when inventing new tags.  But this just as a hint here - this is a discussion for a different place.

I am closing this as none of the tags suggested currently would find consensus support to be added in this style.

**Comment by imagico** [comment]
Sure.
