### ISSUE TITLE
Restricting road types used for shield placement

### ISSUE THREAD

**Issue by dch0ph** [gravitystorm/openstreetmap-carto#4897]
### Expected behavior

Road name shields should be in "boring" bits of the map.

### Actual behavior

Shields can be placed on any road segment, This seems to have the effect of increased likelihood of shields appearing in busy parts of the map with multiple short segments.

### Screenshots with links illustrating the problem

[From area](https://www.openstreetmap.org/#map=14/54.6522/-1.4820)

Shields placed here, obscuring detail
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/20069699/73fcaf97-0483-4348-921b-b1f929bfcb3f)

![image](https://github.com/gravitystorm/openstreetmap-carto/assets/20069699/ed29dcb6-8858-4868-8762-cf4506aa2c22)

It's unclear to me why mapnik fails to place a shield on the boring stretch between roundabouts (here at Z14)
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/20069699/44caf9b8-c560-43f8-aa0b-69e6f78a4f71)

A solution to the primary issue would be to exclude ways with `junction=roundabout` and `junction=circular`. It doesn't make sense to allow shields here. 

You could make a similar argument to exclude `bridge=*`. But in contrast to junctions, bridges can be long, and so at higher zoom levels shields might improve information quality rather than obscure.

I don't understand shield placement well enough to encourage shield placement in long stretches.

**Comment by imagico** [comment]
Related issues: #951, #4401.

**Comment by dch0ph** [comment]
Thanks for linking related issues. It looks like shield placement is a general nightmare.

I'm experimenting with "AND junction IS NULL", which seems a simple way to remove some of worst placements.

**Comment by dch0ph** [comment]
I'm closing this issue, effectively folding into #951.

 "AND junction IS NULL" would be a logical addition, since you don't want shields on junctions, but in practice it has made little observable difference in experiments. Mapnik just loves putting shields on junction flares.
