### ISSUE TITLE
Render Tag:protect_class=22

### ISSUE THREAD

**Issue by Elme122** [gravitystorm/openstreetmap-carto#4903]
### Expected behavior

`Tag:protect_class=22`, for cultural and historical heritage areas or objects, hasn't been rendered yet, whilst other `Key:protect_class`, mainly nature reserves, have been rendered.

### Actual behavior

No render.

**Comment by HolgerJeromin** [comment]
see #4542 for discussions about this tag.

**Comment by imagico** [comment]
Discussion on #4542 indicated consensus not to render this tagging.  Therefore i am closing this issue.  If you have information on changed mapping practice that warrants a re-evaluation please provide it.
