### ISSUE TITLE
Don't render house numbers for `amenity=car_sharing`

### ISSUE THREAD

**Issue by dreua** [gravitystorm/openstreetmap-carto#4912]
### Expected behavior

It has been decided to not render car sharing (#1891) so I'd expect it to not render anything.

### Actual behavior
amenity=car_sharing with an address shows up as a house number on the street. This is expected to be the address of a building close by so it is very unlikely to add any value and much more likely to cause confusion. In any case it looks bad.

### Screenshots with links illustrating the problem
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/15114715/0abe3c7f-577c-4509-b2da-4061dc6cfb60)

https://www.openstreetmap.org/node/9141226027

We have quite a few of those in Mainz: https://overpass-turbo.eu/s/1EmC

**Comment by HolgerJeromin** [comment]
Perhaps this information should be a `ref` instead of an `addr:housenumber`. Not sure about this...

**Comment by dch0ph** [comment]
Yes, this seems a misuse of `addr:housenumber`. It's not a question of whether `amenity=car_sharing` is rendered (it isn't). Basically any node with `addr:housenumber` will show up with an "address". 

This doesn't seem to be a ref number, just a duplication of the closest genuine address onto another feature (which would be poor/incorrect tagging). Or perhaps this is the way these sites are labelled locally?

**Comment by HolgerJeromin** [comment]
Same with postboxes (at least in Germany):
![image](https://github.com/gravitystorm/openstreetmap-carto/assets/2410353/7b7ec111-5f77-497f-b0a7-9e1de21ffd72)

https://upload.wikimedia.org/wikipedia/commons/a/a6/12-04-21-wildparkstrasze-ebw-by-RalfR-11.jpg

**Comment by dreua** [comment]
Thanks for the input, I'll check whether we can fix that by tagging differently.
