### ISSUE TITLE
Render amenity=bicycle_wash

### ISSUE THREAD

**Issue by mcliquid** [gravitystorm/openstreetmap-carto#4916]
### Request
Today the proposal for `amenity=bicycle_wash` was accepted. In this context, I would also like to request the acceptance of this tag in the main OpenStreetMap style. The use of the tag will remain low, as there will never be a bike wash station on every street corner, but the icon is already prepared and linked here, so it would be a good thing to find it on the map.

### Links
OSM Wiki: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_wash
Proposed Icon: https://wiki.openstreetmap.org/wiki/File:Bicycle_wash.svg
PR in iD tagging scheme: https://github.com/openstreetmap/id-tagging-schema/pull/1032

**Comment by pnorman** [comment]
With <100 uses we will not be rendering at this time. I did not evaluate the proposed icon or tagging for suitability.

**Comment by imagico** [comment]
The use of `amenity=bicycle_wash` is currently insufficient to assess adoption by mappers and consistency in use.  This is not only a matter of absolute use numbers, it is also a matter of long term stability of use, regional distribution and number of mappers using it.

For context: `service:bicycle:cleaning=yes` is used about ten times as often and has been in active use by mappers for much longer - as secondary tag to tags in much wider use that we largely already render - `shop=bicycle`, `amenity=bicycle_rental`, `amenity=bicycle_repair_station`.

**Comment by Cyberlima** [comment]
> The use of `amenity=bicycle_wash` is currently insufficient to assess adoption by mappers and consistency in use. This is not only a matter of absolute use numbers, it is also a matter of long term stability of use, regional distribution and number of mappers using it.
> 
> For context: `service:bicycle:cleaning=yes` is used about ten times as often and has been in active use by mappers for much longer - as secondary tag to tags in much wider use that we largely already render - `shop=bicycle`, `amenity=bicycle_rental`, `amenity=bicycle_repair_station`.

I comprehend the argument, but there are places that are only for  wash the bicycle, besides the shops. its however very rare
