### ISSUE TITLE
Unexplained non rendering of meadow

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4934]
There is a sudden gap in the rendering of meadows here:
https://www.openstreetmap.org/#map=18/52.09470/4.48719 

I can't explain it, when inspecting tags, and comparing it to adjacent comparable parts.
It appears at various zoom-levels and in various web-browsers.
I have not found it elsewhere yet.

Any explanation, or a bug?

**Comment by imagico** [comment]
That is just broken data: https://www.openstreetmap.org/way/95708477 is an invalid geometry.

As a general rule:  If other map styles show the same behavior it is typically not a style problem.

**Comment by BertMule** [comment]
Than I have to thank the editor.
I was not able to see what was changed, and what was the problem.

You are right about styles, but as said, I could not explain it.
