### ISSUE TITLE
why Tag:highway=milestone can't be displayed？

### ISSUE THREAD

**Issue by MyeongSaeHo** [gravitystorm/openstreetmap-carto#4935]
### Actual behavior
As the title suggests
### Screenshots with links illustrating the problem
![Uploading IMG_20240219_141751.jpg…]()

**Comment by HolgerJeromin** [comment]
Discussion happened in #2577

**Comment by imagico** [comment]
Closing as duplicate, please bring up any new arguments and ideas in #2577.

See also #3605.
