### ISSUE TITLE
Rendering of emergency=landing_site

### ISSUE THREAD

**Issue by hungerburg** [gravitystorm/openstreetmap-carto#4938]
### Expected behavior

Something rendered

### Actual behavior

Nothing rendered

### Screenshots with links illustrating the problem

None.

### Deliberations

There is quite some use of the tag. Locations quite prominent on the ground, e.g. the letter H marked by rocks/stones e.g., they have to be observable from the air. With a bit of local knowledge can be told apart from helipads. Perhaps render same as helipads, perhaps oblique in order to tell them apart?

**Comment by imagico** [comment]
About 4k uses, half of which are from an import in Poland.

I don't have the impression there is consensus on a delineation between `aeroway=helipad` and `emergency=landing_site`.  Documentation seems deliberately vague.  If there is consensus that for some verifiable helicopter landing sites `aeroway=helipad` is not a suitable tagging the criteria for this should be documented.  If and when that happens we can think about if to show that.

**Comment by mboeringa** [comment]
Maybe a nice feature to add to the new [OpenAirportMap](https://community.openstreetmap.org/t/announcement-openairportmap/8675) announced on the OpenStreetMap Community Forum instead?

**Comment by hungerburg** [comment]
> Maybe a nice feature to add to the new [OpenAirportMap](https://community.openstreetmap.org/t/announcement-openairportmap/8675) …

Just looked there in the area of my local knowledge - this map does not show all the helipads that are registered with the regulators, especially it misses all the places where OSM contributors placed a helipad, where there is just an emergency landing site instead ;) 

What prompted me to file this issue was when gardening OSM data: A mapillary or what its called task urged users to turn helipad nodes into helipad areas - and I noticed that an helipad area was created, where there is not helipad. So I placed a landing site node over the "H" on the aerial, which prompted a note "Cannot be both, which one to keep" - and emergency one by third party intervention.

If you ask me: For OSM, it is the same ;) And both should render the same ;)

**Comment by imagico** [comment]
> If you ask me: For OSM, it is the same ;) And both should render the same ;)

As a principle we try not to support the creation of new synonyms for established tags.

I am going to close this for the moment - if and when the tag becomes clearly differentiated from `aeroway=helipad` in use we can revisit.
