### ISSUE TITLE
Render ways with highway=busway

### ISSUE THREAD

**Issue by jeffbblair** [gravitystorm/openstreetmap-carto#4942]
Highway=busway is used for roads that only buses can travel on. 

Currently these ways are not rendered. Since they are a subtype of highway, they seemingly should be.

**Comment by HolgerJeromin** [comment]
Thanks for your suggestion. Please search for existing items for your idea:
#4226

**Comment by imagico** [comment]
Closing as duplicate - please bring up any new thoughts on the matter in #4226.
