### ISSUE TITLE
Please render emergency=water_rescue

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4953]
Used emergency=water_rescue. 
Tried both on a point and on a building. Neither was rendered.
An 'emergency' is an extra good reason.

Example: [KNRM](https://www.openstreetmap.org/#map=19/52.10201/4.26720).

**Comment by imagico** [comment]
Thanks for the suggestion.

`emergency=water_rescue` has 538 uses at this time. - See https://wiki.openstreetmap.org/wiki/Tag:emergency%3Dwater_rescue.  There is more generic `amenity=rescue_station` with 640 uses as well.

See #3629 - we still do not have a viable design for rendering `emergency=life_ring` - which has 9700 uses.  #3688 was abandoned without issues being solved.  

`emergency=water_rescue` and `emergency=lifeguard` have quite clearly changed substantially in their semantic scope quite recently with `emergency=water_rescue_station` and `emergency=lifeguard_base` having gone out of fashion around 2021.

Suggest to close this as

* not viable to consider before #3629, in particular rendering `emergency=life_ring` or having a generally agreed on concept for displaying water related emergency infrastructure (for which #3629 would be the place to discuss).
* lack of a well established semantic delineation between the different tags in use.

**Comment by pnorman** [comment]
Besides the above, there's also a low number of uses.

**Comment by BertMule** [comment]
I did not mean this as a means to find rescue in an emergency, as also mentioned in #3629.
(Which seems a different issue, and not solved anyway.)
My motive was at the occasion of visiting such a station, searching for it on the map, and correcting it afterwards.

As often, it is frustrating to model objects, to find they are not visible at all.
Then, what's the point?
