### ISSUE TITLE
Please add a separate rendering for DRY reedbeds

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4959]
I have been modelling DRY reed-beds, which are used for harvesting the reeds. These can be quite homogenous reed-beds, visually the same as wet ones, but explicitly dry. Paths or tracks may run through them.
For instance: [Rengerspole](https://www.openstreetmap.org/#map=18/53.11576/5.88304)

I replaced inappropriate scrub by reedbed, but this is not what I want, because of the wet aspect.

It creates these problems.
- They seem misleadingly wet and inaccessible.
- Paths or tracks (on dry land) drawn through it are badly visible, because of the blue stripes.

As far a I know there no good alternative for [reedbed](https://wiki.openstreetmap.org/wiki/Tag:wetland%3Dreedbed).
I considered at least these variations: [wetland](https://wiki.openstreetmap.org/wiki/Key:wetland).

My proposal is to just leave the blue stripes out in a separate pattern.

I also mentioned this at the related [non-transparent color](https://github.com/gravitystorm/openstreetmap-carto/issues/2013).

Also see [add color fill](https://github.com/gravitystorm/openstreetmap-carto/pull/3807) and [rendering over water and over land](https://github.com/gravitystorm/openstreetmap-carto/issues/3854).

**Comment by imagico** [comment]
I have difficulties seeing how this is an actionable request.  

You seem to want us to render 

https://www.openstreetmap.org/relation/17539307

differently from other areas tagged `natural=wetland` + `wetland=reedbed` because it is a _dry reed-bed_ (by some definition of that term).  But there is nothing in the tagging here that differentiates it from other reed-beds that would allow us to base a differentiated rendering on.

**Comment by BertMule** [comment]
OK, of course it would need a different tag.
Jokingly: natural=dryland + dryland=reedbed.

I am not aware that something like this exists, with the desired result.

**Comment by imagico** [comment]
Well - if no established tagging exists then this is not the right place to discuss the matter at this time.  You should discuss tagging options with other mappers and work on establishing a tagging concept.  Generally speaking reeds growing on not water saturated ground are probably partly mapped with `natural=grassland`, partly with `natural=scrub`, the latter in particular for perennial types of reed like giant reed.

Closing as this is not a matter for this issue tracker without an established tagging existing.  This needs to be discussed on the mapping level.

**Comment by BertMule** [comment]
I understand this is not rendering, but should go a level deeper first: tags. Followed by rendering.

The point is exactly that inappropriate tags like scrub, or maybe grass, are used.
