### ISSUE TITLE
Please make quay visible

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4961]
A quay is actually not rendered, and invisible. 
For instance in this national park they are deliberately created for recreation, along with piers.
For example  [here](https://www.openstreetmap.org/#map=19/53.11536/5.88654). The quay is just invisible.

Several times I have created a recreation_ground along the quay (or pier) . 
But it would help if they were recognisable by themselves.

So the request is to create a simple rendering by some line.

**Comment by imagico** [comment]
This is not an actionable request, there is no tagging specified that could be interpreted, the link provided goes vaguely to an area and it is unclear what is mapped there that should be shown differently in the map.

Therefore closing it.

Please put some more effort before opening an issue into:

* evaluating if what you would like to see is something that OSM-Carto can reasonably provide under [the goals we have](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CARTOGRAPHY.md).
* formulating the issue in a way that allows OSM-Carto developers to determine what your concern is without searching and guessing.  This means in particular following the instructions [here](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#reporting-issues).

**Comment by BertMule** [comment]
I think I was clear enough.
The quay can be modelled (tagged), but is not rendered. 

Just look at the centre of the example, in any editor.
Please put some more effort into evaluating an issue.

The only thing I would like is to see is a distinct line.
Like some thick line of an arbitrary colour.

**Comment by jeisenbe** [comment]
I believe you are asking for a rendering for man_made=pier such as https://www.openstreetmap.org/way/261848660#map=18/53.11518/5.88668 in your example location. 

This is already rendered as a line in land color. 

Perhaps you did not realize this is a rendering, since it is the same color as untagged land. But it is rendered, otherwise this area would be the uniform blue water color

![image](https://github.com/gravitystorm/openstreetmap-carto/assets/42757252/57e75014-5e45-48c8-a381-1c938c6b1e09)

**Comment by HolgerJeromin** [comment]
> I think I was clear enough.

> Please put some more effort into evaluating an issue.

I think the spare time of style developers is better invested in developing the style (discussing, experimenting, coding) than loading some area and guessing what your problem with the current rending is.

* In the best case they lost a few minutes (when they got the guess right). 
* In the worst case they are discussing and thinking about features you had no problems with.
