### ISSUE TITLE
Please scale ditches depending on zoom level

### ISSUE THREAD

**Issue by BertMule** [gravitystorm/openstreetmap-carto#4963]
Ditch is a convenient way to quickly model, by just drawing a line. I even wish I had discovered it earlier.
In reality the  modelled water may vary in width from 1 to several meters, which of course is not taken into account.

But they seem to always be rendered the same way, independent of scale.
That looks a bit awkward.
It is desirable that would they also scale up a bit in width.

Here's an [example](https://www.openstreetmap.org/#map=19/53.11463/5.88781).
Compare rendering at various zoom levels and the underlying reality in edit.

**Comment by imagico** [comment]
Please specify what exactly you want rendered based on what tagging.  In the linked to map area there does not seem to be a `waterway=ditch` with a `width` tag - hence no data that allows us to conclude the actual width of the feature in question.  Related to #3354.

Closing as this is not actionable as is.  If you want to suggest ground unit rendering of `waterway=ditch` based on `width` tagging please re-formulate the issue accordingly.  But note that ground unit rendering in general was rejected in #1290 so weighty arguments would be needed to re-visit that decision.

**Comment by BertMule** [comment]
I was not aware of a width property for ditches, which is not standard. 
And as far as I understand, it wouldn't be used anyway.

It would make sense to take that into account.

It was not what I meant. My idea was to make an assumption about width, say 2 meters, and scale accordingly.

The same thing applies to canals. I noted those being used as wider 'ditches'. Trying that myself, I wasn't satisfied, for the same reason as with ditches, not scaling in a usable way.

So coming back at the width-property. That would be the most deterministic way. 
Apart from drawing areas for every ditch or canal, which is a lot more work I want to avoid.
