### ISSUE TITLE
Rendering for healthcare=blood_donation

### ISSUE THREAD

**Issue by MortalEngineXXII** [gravitystorm/openstreetmap-carto#4972]
This tag is not displayed in OSM Carto, I think it should be displayed at least as a dot or other generalized mark. This issue was discussed almost [four years ago](https://github.com/gravitystorm/openstreetmap-carto/issues/4222), perhaps its relevance has changed since then. The tag is currently used [1895 times](https://taginfo.openstreetmap.org/tags/healthcare=blood_donation#overview)

**Comment by imagico** [comment]
Duplicate of #4222 - please add any relevant new information on tag use there.
