### ISSUE TITLE
Addresses of building:part are not shown

### ISSUE THREAD

**Issue by alnzrv** [gravitystorm/openstreetmap-carto#4974]
Addresses of the large building are not shown on the map:
https://www.openstreetmap.org/#map=18/44.81439/20.42977

The building:
https://www.openstreetmap.org/way/1257524525

This building contains multiple building:part with the addresses, for example:
https://www.openstreetmap.org/way/516512490
https://www.openstreetmap.org/way/516512489

![image](https://github.com/gravitystorm/openstreetmap-carto/assets/7187657/5c40f5fd-db8d-4ada-9745-b2473ebdc700)

**Comment by imagico** [comment]
Rendering of `building:part` is covered in #1857, rendering of house-numbers on non-building polygons in #1746.
