### ISSUE TITLE
calling scripts/get-external-data.py get timeout

### ISSUE THREAD

**Issue by beckietech** [gravitystorm/openstreetmap-carto#4989]
### Expected behavior
sudo -u _renderd scripts/get-external-data.py
This process involves a sizable download and may take some time - not much will appear on the screen when it is running. Some data will go directly into the database, and some will go into a “data” directory below “openstreetmap-carto”.
### Actual behavior
INFO:root:Starting load of external data into database
INFO:root:Checking table simplified_water_polygons
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb3a524c0d0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='osmdata.openstreetmap.de', port=443): Max retries exceeded with url: /download/simplified-water-polygons-split-3857.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3a524c0d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 449, in <module>
    main()
  File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 336, in main
    download = d.download(
  File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 193, in download
    response = self._download(url, headers)
  File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 159, in _download
    response = self.session.get(url, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)--2024-07-03 12:12:25--  https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip
正在查找主機 osmdata.openstreetmap.de (osmdata.openstreetmap.de)... 116.203.99.53
正在連接 osmdata.openstreetmap.de (osmdata.openstreetmap.de)|116.203.99.53|:443... 失敗: 連線超過時間。
準備重試。

--2024-07-03 12:14:44--  (嘗試第  2 次)  https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip
正在連接 osmdata.openstreetmap.de (osmdata.openstreetmap.de)|116.203.99.53|:443... 
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='osmdata.openstreetmap.de', port=443): Max retries exceeded with url: /download/simplified-water-polygons-split-3857.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3a524c0d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

I also tried to wget some links:
wget https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip

and I also get timout error:

Please tell me what am I doing wrong? Thanks,

**Comment by pnorman** [comment]
> ### Expected behavior
> sudo -u _renderd scripts/get-external-data.py This process involves a sizable download and may take some time - not much will appear on the screen when it is running. Some data will go directly into the database, and some will go into a “data” directory below “openstreetmap-carto”.
> 
> ### Actual behavior
> INFO:root:Starting load of external data into database INFO:root:Checking table simplified_water_polygons Traceback (most recent call last): File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn conn = connection.create_connection( File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection raise err File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection sock.connect(sa) TimeoutError: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen httplib_response = self._make_request( File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request self._validate_conn(conn) File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn conn.connect() File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect conn = self._new_conn() File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb3a524c0d0>: Failed to establish a new connection: [Errno 110] Connection timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send resp = conn.urlopen( File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen retries = retries.increment( File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='osmdata.openstreetmap.de', port=443): Max retries exceeded with url: /download/simplified-water-polygons-split-3857.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3a524c0d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 449, in main() File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 336, in main download = d.download( File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 193, in download response = self._download(url, headers) File "/home/bill/openstreetmap-carto-master/scripts/get-external-data.py", line 159, in _download response = self.session.get(url, headers=headers) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get return self.request('GET', url, **kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send raise ConnectionError(e, request=request)--2024-07-03 12:12:25-- https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip 正在查找主機 osmdata.openstreetmap.de (osmdata.openstreetmap.de)... 116.203.99.53 正在連接 osmdata.openstreetmap.de (osmdata.openstreetmap.de)|116.203.99.53|:443... 失敗: 連線超過時間。 準備重試。
> 
> --2024-07-03 12:14:44-- (嘗試第 2 次) https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip 正在連接 osmdata.openstreetmap.de (osmdata.openstreetmap.de)|116.203.99.53|:443... requests.exceptions.ConnectionError: HTTPSConnectionPool(host='osmdata.openstreetmap.de', port=443): Max retries exceeded with url: /download/simplified-water-polygons-split-3857.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3a524c0d0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> 
> I also tried to wget some links: wget https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip
> 
> and I also get timout error:
> 
> Please tell me what am I doing wrong? Thanks,

You have a network issue somewhere between you and osmdata.openstreetmap.de. This is not something we can fix and you will have to discuss it with your network admin.
