### ISSUE TITLE
Rendering Man Made

### ISSUE THREAD

**Issue by KillerKingSolo** [gravitystorm/openstreetmap-carto#5000]
[man_made](http://wiki.openstreetmap.org/wiki/Key:man_made) Does not render on OSM or other programs without being in the edit mode. This would be very useful for stuff like [mineshaft](http://wiki.openstreetmap.org/wiki/Tag:man_made=mineshaft), [adit](http://wiki.openstreetmap.org/wiki/Tag:man_made=adit), [storage_tank](http://wiki.openstreetmap.org/wiki/Tag:man_made=storage_tank), [tower](http://wiki.openstreetmap.org/wiki/Tag:man_made=tower), and other [man_made](http://wiki.openstreetmap.org/wiki/Key:man_made) stuff. I know of some places that don’t actually renter the man_made stuff and I can’t save it as a waypoint or anything like that on Organic Maps because it’s not rendering so I have to make my own waypoint and not have the actual name save place of the man_made location.

Examples:
https://www.openstreetmap.org/#map=19/34.35652/-117.74442
https://www.openstreetmap.org/#map=19/34.36081/-117.74441

![image](https://github.com/user-attachments/assets/b3e745fe-1e42-42d1-b75d-324b57954742)
![image](https://github.com/user-attachments/assets/692e0b95-c7cd-4828-9d54-644e81ba2155)
![image](https://github.com/user-attachments/assets/f963fdfb-cee0-43f9-91bc-79f0cb3e9ce7)
![image](https://github.com/user-attachments/assets/7baa78f3-091f-4cfb-b52a-a6b03a374883)

**Comment by HolgerJeromin** [comment]
We decide rendering per `key=value` and not per `key=*` (with exception `building=`, `shop=`).
See existing discussion #3704, #4868, #4149, #3967

**Comment by imagico** [comment]
As far as rendering any and all values of man_made=* in a uniform design - we quite definitely don't want to do that, we render tags, not keys - with very few specific exceptions (buildings, shops, offices)

Apart from that

* `man_made=storage_tank` and `man_made=tower` we render (see [here](https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=man_made&value=storage_tank) and [here](https://imagico.de/map/styleinfo/#style=osmcarto&section=tags&key=man_made&value=tower))
* for `man_made=adit` we have #3704.
* `man_made=mineshaft` was mentioned in #3704, it competes with `historic=mineshaft`, about 40 percent of `man_made=mineshaft` have `disused=yes`/`abandoned=yes` so operational status is not a consistent distinction between the two tags.

I am closing this - as duplicate for `man_made=adit`, as invalid for `man_made=storage_tank` and `man_made=tower` and as wontfix for a catch-all on `man_made=*`.  `man_made=mineshaft` can be looked at if the tagging practice becomes more consistent, possibly together with `man_made=adit` and other mining related tags - see https://github.com/gravitystorm/openstreetmap-carto/issues/3704#issuecomment-517826560.

@HolgerJeromin - as far as open issues on `man_made=*` are concerned - there is in particular also #3494 and #1224.  The latter IMO being one of the most serious gaps in our style as far as POIs are concerned.  Help on this and any of the other open issues mentioned would be welcome.

**Comment by KillerKingSolo** [comment]
But why can't I see it on open street map. I have to be in edit mode to see it. I can't view it in non-edit mode.

**Comment by imagico** [comment]
The two locations you linked to have features tagged `man_made=adit` - which, as explained, we currently do not render, we already have a distinct open issue for that (#3704).
