### ISSUE TITLE
Display of the tracks in the "standard view" or at least in the "traffic map"

### ISSUE THREAD

**Issue by OpenGreenStreet** [gravitystorm/openstreetmap-carto#5002]
I may have asked a similar question before. As a rail traveler, I am always annoyed that the tracks at the platforms of stations are not visible in OSM. This would be very helpful when planning journeys.

I would be very pleased if in future the tracks were displayed in the "Standard view" or at least in the "Traffic map". In principle, the data is available via the "Platform edge" parameter.

### Screenshots
![20240811-151734](https://github.com/user-attachments/assets/c62e03a1-093e-4603-b147-041b8c253494)
![20240811-151639](https://github.com/user-attachments/assets/889f7c72-6c19-4eda-9782-f2fb243af24f)
![20240811-151617](https://github.com/user-attachments/assets/163d617d-475c-4104-84a1-923a5f7ec29c)

**Comment by imagico** [comment]
This seems redundant to #3271/#4662/#4886.

Please always provide links to the areas/features you use as examples.

Closing as duplicate.  Please provide any new relevant information on the mentioned issues.  There has also been a pull request (#4800) - but so far this is missing information on the de facto mapping practice of the various numbering system and ways to map them to assess what kind of rendering might be suitable for us.
