### ISSUE TITLE
New statement regarding the OSMF's plans of using OSM-Carto

### ISSUE THREAD

**Issue by imagico** [gravitystorm/openstreetmap-carto#5003]
As many of you know the OpenStreetMap Foundation has for a long time maintained strategic ambiguity regarding the future plans for their use of this style.

I therefore wanted to make everyone aware of a new public statement by Andrew Hain (member of the OSMF EWG) which seems to mark a departure from that strategic ambiguity.  [Here](https://community.openstreetmap.org/t/busways-not-rendered-on-main-openstreetmap-carto-for-years-prs-are-ready-but-not-accepted/6193/16) he writes:

> Paul Norman is developing a vector tile-based system to replace Mapnik based rendering, which will make OSM-Carto obsolete as well.

Now i don't want to over-interpret this - the desire to stop using OSM-Carto has been present in the OSMF for many years and has been articulated publicly in various forms.  But this is the first time (AFAIK) that a representative of the OSMF has stated in public a definitive plan to functionally replace OSM-Carto in the OSMF portfolio of services with a commercially developed client side rendered style.

This does not directly affect us.  This is purely an informational post to make developers and users of OSM-Carto aware of this development.  OSM-Carto is an independent project with no formal or economic connections to the OSMF.  I also like to emphasize again that at no point have the OSM-Carto maintainers as a group been consulted or communicated with by the OSMF about their plans of using or ceasing to use OSM-Carto.

**Comment by hungerburg** [comment]
I'd say this quote only echoes what has been written 6 years ago here https://blog.systemed.net/post/15 - who would not want that?

**Comment by imagico** [comment]
You will have to ask the OSMF what their ideas and plans are motivated by.

The presence of strong special interests in and around the OSMF regarding the OSMF's map hosting and regarding the default map displayed on osm.org has indeed been a constant for many years.  But so has - at least so far - the strategic ambiguity in the OSMF's official position there.  That potentially changing is the news i wanted to point out.  Discussing the _what_ and _why_ of their plans beyond OSM-Carto is out of scope here.

**Comment by imagico** [comment]
Closing as this was an informational message and not an actionable issue.
