### ISSUE TITLE
Arrow from oneway steps renders even when steps are not visible (under pedestrian area)

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#5008]
### Expected behavior
If the steps are not visible, because they are underground and there is an pedestrian area mapped on top, I would not expect the one-way arrows to show

### Actual behavior
The arrows are visible.

### Screenshots with links illustrating the problem
https://www.openstreetmap.org/way/55829461
![image](https://github.com/user-attachments/assets/f6f42d69-916f-4b8a-9fb2-62e073dcc9ab)

If you scroll a bit to the west, you will hit on Marienplatz which made me notice the arrows first:
![image](https://github.com/user-attachments/assets/eb0d1c53-6599-4086-9543-4ee6b2b61333)

Probably related to #3614, but that was merged in 2019 and I wonder if I really did not look closely at this area since then...

**Comment by imagico** [comment]
I think this is covered by #529 and #706.

This is not a problem specific to steps, this concerns all kinds of road/path tunnels and both oneway arrows and name labels.

Closing as duplicate.
