### ISSUE TITLE
barrier=gate sometimes renders incorrectly as highway/ford.svg

### ISSUE THREAD

**Issue by FriederHannenheim** [gravitystorm/openstreetmap-carto#5018]
### Expected behavior
barrier=gate renders as the gate symbol
### Actual behavior
this symbol is rendered
![image](https://github.com/user-attachments/assets/3e313de7-426e-48ce-97ed-0ddde7f5085f)

### Screenshots with links illustrating the problem
https://www.openstreetmap.org/node/12211219426
![image](https://github.com/user-attachments/assets/82928a63-e364-49b0-b70c-2f61684c1e4b)

**Comment by FriederHannenheim** [comment]
aah. I seem to have tagged the foot path as ford=yes. Sorry

**Comment by imagico** [comment]
For context: We have an open issue (#4000) for moving rendering of ford=yes to a different, ideally non-blocking design so it would not interfere with barrier rendering in such cases.  This is a good example how such a change would be beneficial for mapper feedback.
