### ISSUE TITLE
Render amenity=lounge

### ISSUE THREAD

**Issue by okainov** [gravitystorm/openstreetmap-carto#5019]
There is `amenity=lounge` tag for tagging lounges e.g. in airports. However it's not rendered today, could this be possible rendered? Thanks! 

See https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlounge

### Expected behavior

`amenity=lounge` should appear on the map. Minimal icon IMO can be a purple dot 
![image](https://github.com/user-attachments/assets/1fdfe5a4-4058-4a10-bf84-4e9b8efd0da9) or purple couch (from `shop=furniture` which is very unlikely to be in the vicinity, so there is no chance for visual collision) 
![image](https://github.com/user-attachments/assets/8f55cba4-1513-4d50-bd38-1505d5b5e957)

Motivation for couch - lounge is used as place to relax between flights and it's often depicted as such (maybe also with table and drink), so it's quite recognize-able.

See example of multiple lounges in FRA airports in Overpass https://overpass-turbo.eu/s/1ShG

**Comment by imagico** [comment]
Thanks for the suggestion.  

`amenity=lounge` has 162 uses.  Scope of use is fairly wide, essentially all kinds of facilities that are advertised locally as a _lounge_.  It is not limited to airports or public transport in general.  There does not appear to be an established tagging to distinguish between public facilities, facilities open to any paying customer and closed clubs for members only.

Rendering like shops would be confusing, especially for the members only facilities.

Right now this does not seem to be widely established tagging and the scope of the tag seems very broad.  If, at some point, we'd want to render this a distinction between the different classes of access would be essential for a useful depiction.

**Comment by imagico** [comment]
Closing for reasons mentioned (lack of broader use and unconstrained scope of tag currently).
