### ISSUE TITLE
files svg

### ISSUE THREAD

**Issue by Geoscope19** [gravitystorm/openstreetmap-carto#5026]
Hello,
I have uploaded svg files, especially "mangrove" but the pictograms do not display at my place. I have like an empty file. How can I use them (in qgis).
Thank you

**Comment by imagico** [comment]
I have no idea about the nature of the problem described here.  Note that this project has nothing to do with QGis, we are a map style based on Carto and Mapnik.

If you think your problem is relevant here please describe in detail:

* what you are trying to do.
* the exact steps you do to accomplish that.
* what you expect the result to be.
* what the result actually is.

If this is difficult to do in English you can do so also in your native language.

**Comment by Geoscope19** [comment]
Bonjour,

J'ai téléchargé le svg "mangrove". 
Dans un premier temps, j'ai juste essayé de l'utiliser avec Qgis pour restituer une carte avec un fond open street map vectoriel. Le motif n'apparaissant pas, je l'ai ouvert avec Notepad++, pensant que je pourrais débloquer le rendu du contour et du remplissage (méthode trouvée ici : https://portailsig.org/content/ajouter-et-personnaliser-des-symboles-svg-depuis-qgis.html). Or votre fichier n'a pas du tout la même structure. Comme je ne suis pas du tout informaticienne, j'ai voulu ouvrir le fichier avec illustrator pour comprendre, et celui-ci ne comporte apparemment aucun objet. Même constat en ouvrant avec Gimp (cf. capture d'écran).
Mon souhait est de pouvoir a minima utiliser le motif de vos svg tels qu'ils apparaissent dans votre github, au mieux pouvoir éventuellement jouer avec les couleur et épaisseur des contour et du remplissage sous qgis.

Merci pour votre boulot, et merci de me permettre d'écrire en français :-)
![mangrove_sous_gimp](https://github.com/user-attachments/assets/579060e8-bf7d-43e1-8c04-ae2a52816e4b)

**Comment by imagico** [comment]
I suppose the SVG you are talking about here is

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/generating_patterns/mangrove.svg

That opens just fine in GIMP for me.  The more suitable tool for editing our SVGs would be Inkscape though.  Note these pattern SVGs use some SVG features that are not understood by all programs reading SVGs.  There is a script in jsdotpattern:

https://github.com/imagico/jsdotpattern/blob/master/svg_pattern.sh

for flattening these to a more broadly compatible SVG with Inkscape.  But that is essentially just a demonstration, not really designed for ease of use.

The AC-Style has the SVG patterns in a form pre-processed this way - but they are not identical design-wise and they are a different license:

https://github.com/imagico/osm-carto-alternative-colors/blob/master/symbols/patterns/mangrove.svg

Concrete use of our SVGs in QGis is really out of scope of this issue tracker.

**Comment by Geoscope19** [comment]
Je vous remercie.
J'ai ouvert votre svg avec Inscape, j'ai bien la texture. Je l'ai enregistré sous "svg optimisé", j'ai ajouté 
` fill="param(fill) #000" stroke="param(outline) #000" stroke-width="param(outline-width) 0.1"
fill-rule="evenodd" clip-rule="evenodd" ` après '<Path' et ça marche :-)
Merci beaucoup
![mangrove1](https://github.com/user-attachments/assets/0c42bbd6-a182-4dd8-b38a-6629007d79af)
