### ISSUE TITLE
Expire tiles after update

### ISSUE THREAD

**Issue by kirill150399** [gravitystorm/openstreetmap-carto#5034]
Hello! I can't find the functionality of expiring tiles when updating data in flex mode. Is it really not there or am I just not looking hard enough?

**Comment by imagico** [comment]
We are not covering actual tile server operation in this repository, we are just developing the style.  But the move to the flex backend should not require changes about that (although there are additional options for tile expiry AFAIK).

The place to go regarding operation of a tile server is https://switch2osm.org/serving-tiles/.  For specifics about osm2pgsql operation see https://osm2pgsql.org/doc/manual.html.
