### ISSUE TITLE
public_transport=platform is not rendered

### ISSUE THREAD

**Issue by jc86035** [gravitystorm/openstreetmap-carto#504]
[public_transport=platform] is not rendered on the map. Could this be fixed with

public_transport=platform with tags
- railway=yes,
- light_rail=yes,
- monorail=yes,
- subway=yes,
- tram=yes, or
- funicular=yes
  = rendered same as railway=platform;

with tags
- bus=yes, or
- share_taxi=yes
  = rendered same as highway=platform;
  etc.

**Comment by jojo4u** [comment]
could the duplicate label be added?
