### ISSUE TITLE
No labels for railway=(rail, subway, light_rail, ...; platform), public_transport=platform

### ISSUE THREAD

**Issue by jc86035** [gravitystorm/openstreetmap-carto#505]
Could labels be added back for railways and platforms? They seem to have been removed sometime in the last few months.

[edit] I was thinking about <code>railway=platform</code> and <code>public_transport=platform</code> with <code>railway</code>/<code>subway</code>/etc.<code>=yes</code>, not <code>highway=platform</code> and <code>public_transport=platform</code> with <code>bus</code>/etc.<code>=yes</code>. Bus and share taxi platforms should probably be treated separately and usually don't need labels.

On the other hand, would it be good if ref=\* was used for the label of the platform if there is no name=*?

**Comment by donaldrnoble** [comment]
Platform `name` is currently rendered for platforms `railway=platform` additionally tagged as `area=yes` but not for simple lines
