### ISSUE TITLE
Add rendering for amenity=community_centre

### ISSUE THREAD

**Issue by nhsavage** [gravitystorm/openstreetmap-carto#506]
These are potentially very useful to people, so it possible, could these please be rendered? Thank you.

http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtownhall
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcommunity_centre

**Comment by math1985** [comment]
Removed townhall from this issue, duplicate with #77.

**Comment by polarbearing** [comment]
Many community_centres have a campus around the building. That should render, e.g. in "educational" yellow like kindergarten/school.

**Comment by dieterdreist** [comment]
2015-06-01 13:13 GMT+02:00 polarbearing <notifications@github.com>:

> Many community_centres have a campus around the building. That should
> render, e.g. in "educational" yellow like kindergarten/school.




This is very likely depending on the cultural setting, but I haven't found
an indice to associate community centres with "education" from reading the
wiki:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcommunity_centre
and I also wouldn't have thought about education from my personal
expectations (at least not as "main" field).

I believe they are more places for celebrations, and maybe for some forms
of politics (public participation etc.)

**Comment by kocio-pl** [comment]
I think we should have an icon for it (like two people talking or sitting at the table) and at least render the name for the area. Does it sound reasonable?

**Comment by polarbearing** [comment]
Name and icon certainly helps. Area fill helps further to show dimensions. 

@dieterdreist - I did not mean a community_centre is always educational, I just compared it. Might have better said amenity-yellow, though I know there is some debate about limiting its use. 

I have seen some family of multi-generation oriented centres here, i.e. social meeting places.

**Comment by kocio-pl** [comment]
My drafts of the icon:
1) ![community_centre-14-2](https://cloud.githubusercontent.com/assets/5439713/8946061/88317be4-358d-11e5-900f-15b6d7027a7f.png)
2) ![community_centre-14-5](https://cloud.githubusercontent.com/assets/5439713/8946066/95a0214a-358d-11e5-8378-f7b3ad88ccdd.png)
3) ![community_centre-14-7](https://cloud.githubusercontent.com/assets/5439713/8946068/9c4c3920-358d-11e5-9647-00fed37eaf46.png)
4) ![community_centre-14-10](https://cloud.githubusercontent.com/assets/5439713/8946077/af3f5f9e-358d-11e5-8d35-6b578d5d52f1.png)

**Comment by pnorman** [comment]
I like 5, but looks a bit shelter-like

**Comment by polarbearing** [comment]
> looks a bit shelter-like

Yes the indication of a roof is misleading. I have mapped plenty such places which have a building on a campus, for those the icon would often sit outdoors. 

I like "standing with joined arms" as in 4, indicating a cooperative activity, which is not always at a table (as in 1+2).

The boundary could eventually be shown as outline, see also #1624.

**Comment by kocio-pl** [comment]
Updated versions of 4 (more enthusiastic cooperation I guess :smile: ) and 5:
6) ![community_centre-14-16](https://cloud.githubusercontent.com/assets/5439713/8958513/8480f6d2-3605-11e5-9252-ebb29d386948.png)
7) ![community_centre-14-17](https://cloud.githubusercontent.com/assets/5439713/8958601/1de3ba80-3606-11e5-9362-5b45efc698fd.png)

**Comment by polarbearing** [comment]
Good. Three people joining hands are probably too much for our icon size?

**Comment by kocio-pl** [comment]
It's possible, but only 10 might work:
8) ![community_centre-14-19](https://cloud.githubusercontent.com/assets/5439713/8959247/0ad7188e-360a-11e5-8ce0-f59676f7158f.png)
9) ![community_centre-14-23](https://cloud.githubusercontent.com/assets/5439713/8959295/469da8a6-360a-11e5-8014-2af91854493e.png)
10) ![community_centre-14-25](https://cloud.githubusercontent.com/assets/5439713/8959389/dc44760a-360a-11e5-90fe-5a5e41e71992.png)

**Comment by daganzdaanda** [comment]
I prefer number 6. For me, 7 looks a bit like hiking, 10 is getting too abstract.
Would 6 look too unsharp if you made the stick figures fatter?
I don't mind the roof, the Humanitarian Style icon is OK, too.

**Comment by nhsavage** [comment]
I also don't mind the roof. I guess the challenge is that we all have different experiences of what this type of place is like, but I would see this as a building of some sort. If that would be confusing in some cases, I think my preference would be 6.

**Comment by kocio-pl** [comment]
11) ![community_centre-14-27](https://cloud.githubusercontent.com/assets/5439713/8968761/97533088-363f-11e5-8fce-7154c4b29b2c.png)
12) ![community_centre-14-29](https://cloud.githubusercontent.com/assets/5439713/8968836/121816ee-3640-11e5-81a2-6756921d2768.png)

**Comment by kocio-pl** [comment]
Field test (6, 7, 11, 12):
![community_centre-thin-happy](https://cloud.githubusercontent.com/assets/5439713/9254488/13751dc0-41e4-11e5-9326-533d20b717ef.png)
![community_centre-thin](https://cloud.githubusercontent.com/assets/5439713/9254556/6e85c444-41e4-11e5-881b-33ad08120940.png)
![community_centre-big-happy](https://cloud.githubusercontent.com/assets/5439713/9254688/2fbd5d16-41e5-11e5-96f4-117197fc0f1f.png)
![community_centre-big](https://cloud.githubusercontent.com/assets/5439713/9254832/e64fa9d0-41e5-11e5-92a0-e271fda1ce76.png)

I would choose 6.

**Comment by pnorman** [comment]
When I first saw the images, without the above discussion, I thought they were washrooms.

**Comment by kocio-pl** [comment]
You're right, 7 and 12 are resembling standard toilet/washroom icons. I took the idea from Humanitarian style AFAIR, but somebody didn't like the roof and this is the outcome.

My original idea was something like 1 or 2 and I like them still, but people like 6 more, which in my opinion is different enough (no separation - quite the reverse =} ).

**Comment by tilmanb** [comment]
I think example 3 represents the "community" aspect in a good way.

**Comment by kocio-pl** [comment]
For me 3 looks more like a radiation warning, because details are too small and lack the context (in the original car sharing icon the context was clear).

**Comment by kocio-pl** [comment]
Light yellow background ("societal amenities") is now introduced by #2981.
