### ISSUE TITLE
Should landcover be ordered by z_order?

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/openstreetmap-carto#53]
At the moment the query orders by both z_order and way_area. Ordering by area makes sure small polygons end up on top (where there's no holes in a larger polygon). I guess z_order will help if the features are on separate layers, since there's no fine control over landcover ordering required.

But is this necessary? Are overlapping features with different z_orders - and the larger one on top - either common or wanted?

**Comment by fgregg** [comment]
Here's another example: Big buildings above a large underground railway platform in Chicago:

https://www.openstreetmap.org/#map=19/41.87848/-87.63955

**Comment by math1985** [comment]
In fact I think it's an example of #688. Neither buildings nor railway platforms are rendered by the landcover layer.

**Comment by math1985** [comment]
Given that we haven't seen any usecase for ordering landcover by z_order in 2 years time, I will close this. Ordering of railway platforms etc. will still be considered, but these are not landcover.

**Comment by math1985** [comment]
Now I look at this issue again, I see that my statement does not correspond to my action. I thought the current situation was that z_order (or layer) is not taken into account, but in fact it is. I still think it would be better not to take it into account, so the correct action, I think, would be to remove the layer column from the ORDER BY.

**Comment by kocio-pl** [comment]
Low zoom ordering has been removed in #2740, is it enough for us and the issue can be closed or we want to remove more of it?

**Comment by math1985** [comment]
I think we also want to remove the z_order from the regular landuse query.
