### ISSUE TITLE
Add label and area rendering for amenity=recycling

### ISSUE THREAD

**Issue by mippzon** [gravitystorm/openstreetmap-carto#535]
When mapping recycling centers with the following tags:
amenity = recycling
area = yes
name = [name]

the name and the area is not rendered on the openstreetmap default map.

Example here: https://www.openstreetmap.org/#map=17/55.55867/12.94345

**Comment by kocio-pl** [comment]
What about this issue? I guess the area is still not rendered - it should be probably the same as landuse=industrial and I don't think we need area=yes for this (closed polygon should be enough).

**Comment by matkoniecz** [comment]
I am not convinced that rendering even more areas is beneficial at this point. As label is already rendered I propose to close this issue and do not render area for this feature.

**Comment by kocio-pl** [comment]
I guess this is genuine industrial type, just tagged in a separate way, so I don't think it is really adding new area type, rather adding another instance of the same general type.

**Comment by matkoniecz** [comment]
> I guess this is genuine industrial type, just tagged in a separate way

So it would be anyway displayed after tagging as landuse=industrial.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 19.09.2015 um 11:34 schrieb kocio-pl <notifications@github.com>:
> 
> I guess this is genuine industrial type, just tagged in a separate way, so I don't think it is really adding new area type, rather adding another instance of the same general type.
> 


I agree general industrial rendering would possibly work

**Comment by matkoniecz** [comment]
> I agree general industrial rendering would possibly work

Is there real case where it would make sense to render amenity=recycling as industrial and where it landuse=industrial should not be used anyway for that area?

And even if cases like that exist - it would be probably confusing to render something like landuse=industrial in places where landuse=industrial would be incorrect.

**Comment by kocio-pl** [comment]
In a current state some of them will be tagged as industrial and some of them won't, which makes sense only if we're not sure if they are really industrial all the time - otherwise it's introducing tag inflation and visual chaos. So: are there any amenity=recycling area which are not really "industrial"?
