### ISSUE TITLE
Add rendering for tourism=wilderness_hut

### ISSUE THREAD

**Issue by bohwaz** [gravitystorm/openstreetmap-carto#540]
tourism=wilderness_hut points are not displayed.

There is an icon here:  http://wiki.openstreetmap.org/wiki/File:Wilderness_hut_blue_stove_p32.svg

**Comment by matkoniecz** [comment]
Would it be a good idea to render them exactly like tourism=alpine_hut?

>  Example icon: http://osm-icons.org/images/6/6f/30042.svg

is not really recognisable for me (though in my region such places are extremely rare and none are mapped).

**Comment by bohwaz** [comment]
No not really a good idea, as alpine huts often offer food, and have a 
cost, as wilderness huts like in New Zealand are often remote, are not 
staffed, offer no food or service and are sometimes free or cheap. Alpine 
huts are more like hotels I think.

**Comment by kocio-pl** [comment]
So maybe something close to shelter (or just shelter icon) would be good - for example shelter with the floor line? I'm not sure hoe the proposed icon would look at 14x14 px size.

**Comment by nebulon42** [comment]
This is now rendered, but this issue wasn't closed then.
