### ISSUE TITLE
paths and tracks renderings are indistinguishable

### ISSUE THREAD

**Issue by a-pirard** [gravitystorm/openstreetmap-carto#547]
Initial text on old tracker ticket   https://trac.openstreetmap.org/ticket/5163::
The rendering of highway=path and highway=track is barely distinguishable.
For example, many huge width highway=residential continue to an extra thin =track and then invisibly change to a =path.
Just like on my National Geographic maps, I suppose that highway=track should be drawn with a distinguishable width something like half that of residential highways.

your reply: I don't think path and track are barely distinguishable.

my reply: Yes they are.
Look at this part of the OSM map

![stockis-which](https://cloud.githubusercontent.com/assets/7649889/3034733/29cb8478-e07a-11e3-9366-2b852da13889.jpg)

and ask anyone, including yourself, which is the path and which is the track where vehicles can pass.
In case of doubt, look at the key:
![track-1ab8881461027c46960a65123f176022](https://cloud.githubusercontent.com/assets/7649889/3035150/5051b8fa-e085-11e3-8f80-11fde5c3fde7.png)  Track
![footway-10e2ffa7697210623f36a18829831ec6](https://cloud.githubusercontent.com/assets/7649889/3035160/b6d80e12-e085-11e3-94e8-84efc79d1bd3.png)  Footway 
Just like any sensible rendering like the IGN map shown below, the key makes tracks very distinguishable from foot, and more important, although I still maintain that tracks should be wider on the OSM map, as in reality.
But look carefully, <b>the map does not correspond to the key at all !!!</b>
<b>It even looks like the opposite</b>: smaller red dashes south is the track and longer black north is the path !!!
So that my request could also be stated "make the map like the key (and reality)" ;-)

 This is @ http://www.openstreetmap.org/way/281165129#map=18/50.52934/5.81330&layers=D

![stockis osm marked](https://cloud.githubusercontent.com/assets/7649889/3035273/de63304e-e088-11e3-970f-4478520fa4af.png)

Look at Le Stockis : residential -> track -> path transitions in the circles where they meet.
The tracks go to a meadow and uphill through the forest.
Compare with the following IGN map.

![stockis ign-1](https://cloud.githubusercontent.com/assets/7649889/3035283/2880cd4e-e089-11e3-912b-d9edfa978f9e.png)

Isn't it obvious on this IGN map which are tracks and which are paths? Even without a key.
The main hint of the importance of a way is its width, also dashes.
The color means little obvious, but they're fine to follow similar roads when the beginning is grasped.
And visibility when the roads are thin is best achieved with black on any background.

I made a bit of painting to simulate the difference:

![stockis osm new](https://cloud.githubusercontent.com/assets/7649889/3035288/496a45ee-e089-11e3-94c9-71745d7ca5a2.png)

Isn't that is a more pleasant map to look at and grasp? !!!
And consequently much more pleasurable for the OSMers to map !!!

Please note that I don't claim I reached the optimal aesthetics: I just focused on visibility and differentiating what can be used by vehicle and which by foot(/bike) only.  The paths also need some touch up for visibility.

**Comment by mkoniecz** [comment]
@a-pirard Heavily increasing strength of highway=track would make map worse.

Main problem is that highway=path missing from legend.

**Comment by a-pirard** [comment]
It's not a question of "how heavier" a track strength but, as the title says, "distinguishable".
A track must be distinguished from a path without closeup looking, and not only when it's next to it.
The track must be understandably represented as larger, as vehicle vs foot.
The legend must not be necessary to distinguish but to tell what the already distinguished elements mean.
Other maps have been presented as doing that nicely and it doesn't matter if OSM is "a little less heavier" as long as the goal is fully met.

**Comment by mkoniecz** [comment]
I am not sure what is causing differences, but "track must be distinguished from a path without closeup looking" for me was always doable.

**Comment by kocio-pl** [comment]
They are somehat close, but I was also always able to tell which is which.

**Comment by nebulon42** [comment]
Sometimes this is tricky, I agree. Maybe having longer dashes on track while keeping everything else unchanged might help?

**Comment by a-pirard** [comment]
The confusion between tracks and paths is obvious from my pictures and I stopped mapping them because I disliked making fuzzy maps.
Before filing this bug I asked several persons which is a track or a path and they couldn't tell.
Everyone agrees, including the other maps and the persons who render OSM.org.
You may well have no problem but is it a reason to fight against an obvious improvement for those ho have one, instead of being constructive and maybe say "my taste is like/a bit lighter/darker than this other map".
It's like saying "you should stop improving cars because I don't have one".

**Comment by kocio-pl** [comment]
I think making track wider would do the trick, since almost all the roads are wide and footway/path are thin, and that reflects the common fact in reality (vehicles need more space than pedestrians) - that would be nice visual hint.

**Comment by vincentdephily** [comment]
+1 for making tracks wider, as they are always (?) wide enough for a tracktor, as opposed to paths.

In addition to this, it isn't rare for a highway=unclassified/residential to turn into a highway=track without any physical change, just because the rest of the road is only of use to farmers.
