### ISSUE TITLE
Use reduced landcover for low-zoom

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#553]
Currently the landcover layer is essentially

```sql
SELECT ... 
  FROM planet_osm_polygon 
  WHERE <is feature from A> OR <is feature from B>
  ORDER BY z_order,way_area
```
With the corresponding MSS
```css
#landcover
  [feature = A1][zoom >= 10] {
    ...
  }
  [feature = A2][zoom >= 10] {
    ...
  }
  <...>

  [feature = B1][zoom >= 10] {
    ...
  }
  [feature = B2][zoom >= 10] {
    ...
  }
  <...>
}
```

Aside from the complexity of the attachments SQL, there is a disadvantage here. For low-zoom queries every feature has to be returned, even if most of them will be filtered out.

Is there a reasonable way around this?

I was thinking perhaps

```css
[zoom >= 10][zoom<14]#landcover-A,
[zoom>=14]#landcover-all, {
  <...>
}
```
but I'm not sure if it'd work, if it'd balloon the XML, etc. Thoughts?
Edit: early submit, updating

**Comment by mkoniecz** [comment]
Is there a strong performance improvement?

> #landcover-A
> #landcover-all

has an unfortunate result of increasing complexity of map style.

**Comment by pnorman** [comment]
> Is there a strong performance improvement?

I would expect so. The details would depend implementation bout it would definitely result in less features being returned from the DB server. The XML would be larger, but I'd expect that to be less significant.

**Comment by math1985** [comment]
> The details would depend implementation bout it would definitely result in less features being returned from the DB server. 

I still don't think I understand it. Why can we not use `Max'/`MinScaleDenominator' from `mapnik.osm', for example?

**Comment by pnorman** [comment]
> I still don't think I understand it. Why can we not use `Max`/`MinScaleDenominator` from `mapnik.osm`, for example, to prevent returning too many features?

We're not rendering OSM files, we're rendering from PostGIS.

The only ways to adjust how much data is being returned is to change the query. `Max`/`MinScaleDenominator` or `minzoom`/`maxzoom` for vector tiles both are all or nothing - the only adjustment that can be made on them is to query the layer or not.

**Comment by math1985** [comment]
This has been implemented in the meanwhile.
