### ISSUE TITLE
service=driveway not rendered in zoom 13-15

### ISSUE THREAD

**Issue by Klumbumbus** [gravitystorm/openstreetmap-carto#561]
highway=service service=driveway is not rendered in zoom levels 13-15. All other highway=\* are rendered until level 13 (even highway=path). This results in disconnected streets.
Example: http://www.openstreetmap.org/?mlat=50.6925&mlon=12.8393#map=16/50.6925/12.8393 (this is zoom16, zoom out once)

**Comment by sommerluk** [comment]
Would it be an option simply start rendering footpathes later (=at higher zoom levels only)?

**Comment by math1985** [comment]
No, not really. In the countryside footpaths at z15 are really necessary.
