### ISSUE TITLE
Linear barriers: way too intense at z16, z17

### ISSUE THREAD

**Issue by achadwick** [gravitystorm/openstreetmap-carto#582]
Linear barriers are rendered too heavily at lower zooms, specifically z16 and 17. This can lead to patchiness in residential areas where users have mapped garden walls compared to neighbouring residential areas where they haven't. The inconsistency being rendered is actually there in the data of course, but the rather strong visual weight given to walls makes the inconsistency look more important than it actually warrants. Example:

http://www.openstreetmap.org/#map=16/51.7643/-1.2634

(This is perhaps a harsh example because the walls may be double-struck there. There are nearby garden-walled areas which are single-struck)

This could be addressed by reducing the visual weight of walls/fences at the lower zooms where walls are of less relevance than serviceways and pedestrian cut-throughs.

Please could the rendering of barrier=wall, possibly other linear barriers too, be modified such that:
- at z16, they are almost imperceptible or absent;
- at z17, they have 33% of the weight they have at z19,
- at z18, they have 66% of the weight they have at z19,
- at z19, they have their existing weight?

Or of course any other sensible increment.

Rationale: linear barriers are mostly of use as landmarks for map users, and are of more relevance to walkers and recreational/park cyclists. They're also linear features which are easily confused with paths and trails. Making them almost invisible at z16 (which is a motorist's final destination or half a cyclist's short journey) is appropriate because these uses are mostly constrained by available roads and paths.

Conversely, walkers/wheelchair users/parents with kids would benefit hugely from having lots of extra detail when they zoom in to z18 or z19 and walls/fences are much more relevant to their usage patterns. Higher zooms make everything wide apart and more readily distinguishable, so the ease of confusion is less of a problem.

Last time I looked, there wasn't any great consensus or will to change the tagging of private garden walls to something which doesn't render.

**Comment by mkoniecz** [comment]
As @Rovastar noted in #582 linear barriers are now more noticeable than buildings with new colours.

http://www.openstreetmap.org/way/132701201#map=17/52.91187/-1.48218

![selection_001](https://cloud.githubusercontent.com/assets/899988/5685421/4cb29fda-983a-11e4-886b-efb8765a0c1b.png)

**Comment by Rovastar** [comment]
Aha didn't spot this thread. Personally I think it has only become more a problem recently. I did look over the past few weeks....

**Comment by kocio-pl** [comment]
Another dense area:
https://www.openstreetmap.org/#map=16/52.2185/0.1061

I believe this is just proper tagging (maybe adding residential gardens would make it more bearable visually) and some places just look like this. Or somebody would still like to improve it? If not, I would close this ticket.

**Comment by boothym** [comment]
>Another dense area: https://www.openstreetmap.org/#map=16/52.2185/0.1061

I think that's actually improper tagging as the fences are double tagged. It seems the location in the OP has been cleaned up since this issue was posted.

It looks fine in an area like this: https://www.openstreetmap.org/#map=16/55.9347/-3.1940 (though it would be nice to get trees back on z17 as a lot of them have been mapped in Edinburgh)

**Comment by kocio-pl** [comment]
> though it would be nice to get trees back on z17 as a lot of them have been mapped in Edinburgh

In my opinion there's no chance, exactly because there's too many of them tagged already and they are small scale features - well mapped places seem to be single-tree-dots haunted. If you want to see trees on lower zoom levels, you need to draw the natural=wood, tree line or something like this.

I'm not sure if original proposition is good and tend to accept that some areas just look like this (I mean double tagging should not influence rendering, isn't it?) and making barriers paler is not necessary. Is anybody willing to test it?

**Comment by polarbearing** [comment]
I agree to leave as is. There are two cases, barrier around small private properties, but on the other hand around large areas like theme parks etc. It would be odd to see the barrier only when zooming onto a small corner of that park. Would also produce inconsistent results with the outlines (museum, accommodation etc) in the pipeline.

**Comment by kocio-pl** [comment]
This is also what I was thinking about. So I close it now, if anybody wants to show it can be tuned without such side effects, please make some test renderings to show it.
