### ISSUE TITLE
Suggestion for man_made=storage_tank

### ISSUE THREAD

**Issue by JoshuaGore8** [gravitystorm/openstreetmap-carto#588]
The below is my suggestion for rendering the feature man_made=storage_tank in main OSM layer:
![storage_tank](https://cloud.githubusercontent.com/assets/7251556/3138970/8cf7fad6-e8bd-11e3-9186-3bd72d96b0d2.png)

**Comment by simonpoole** [comment]
Sorry for adding to this and essentially reopening. Fhe current numbers for storage_tank use are

145 900 man_made storage_tank
vs
12 762 building storage_tank

(this is likely due to presets). IMHO rendering the former would make sense (but not necessarily anything differnt than for building=storage_tank).

**Comment by jojo4u** [comment]
This is man_made instead of building. Man_made is also used for silo, water_tower, gasometer and reservoir_covered. The [feature page](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dstorage_tank) is now in good shape and usage is now 153 467 : 13 560.

**Comment by ThomasA** [comment]
Simply *not* rendering `man_made=storage_tank` (and `man_made=silo` as well, for example) seems like almost the worst solution of all. At least the tanks and silos I am thinking of are often quite prominent features on the ground. They often stand out much clearer from the landscape than surrounding buildings and not rendering them at all when they are actually tagged seems like a mistake.
If no consensus can be reached on the actual appearance, how about simply rendering them with the same signature as `building=industrial`? At least they show up on the map then.

**Comment by ThomasA** [comment]
To elaborate a bit: These are examples of the silos and storage tanks that I think it is a problem not to render:
![Silo](https://imageservice.nordjyske.dk/images/nordjyske.story/2012_05_15/1b016c1e-d89f-4343-b57a-a3fde3cd4d4e.jpg)
![Storage tanks](http://scm.dk/sites/default/files/oversigtsbillede_oliehavnen.jpg)

**Comment by math1985** [comment]
Shouldn't they be tagged as building=yes in addition? At least the first one seems to be a building.

We can fix it on our side, but I don't think we should expect all other renderings to follow suit.

**Comment by kocio-pl** [comment]
The question is not only how to render such polygons (143 941), but also how to render nodes (56 091)?

**Comment by ThomasA** [comment]
Combining it with `building=yes` would seem an easy fix, but [the documentation](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dstorage_tank) says:

> A storage tank is not a building, so do not include a building=yes tag.

[The documentation for `man_made=silo`](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsilo) does not mention such a restriction, but only specifically mentions combining it with `building:material`. I guess that could be used in my silo example (top image) to tag that they are made of concrete.
I still think the very visible oil storage tanks in my bottom image ought to be rendered on maps when they are such easily recognisable features. See also the note about this in [the documentation for `man_made=silo`](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsilo):

> Silos are landmarks which lend themselves to navigating. Most silos are easy to discern from other structures by the layperson.

**Comment by matkoniecz** [comment]
See https://wiki.openstreetmap.org/wiki/Talk:Tag:man_made%3Dstorage_tank#building.3Dyes_.3F for discussion on wiki.

**Comment by matkoniecz** [comment]
> 145 900 man_made storage_tank
> vs
> 12 762 building storage_tank

Note that according to https://taginfo.openstreetmap.org/tags/man_made=storage_tank#combinations about half of man_made=storage_tank is tagged also as building=* (building=yes, building=industrial, building=storage_tank).

**Comment by SomeoneElseOSM** [comment]
Whether a storage tank is a building or not is probably a question for the tagging list (and likely won't get resolved there), but what's the objection to rendering a man_made=storage_tank that someone has decided to add without a building tag?

**Comment by ThomasA** [comment]
Reading the thread of this issue, I get the impression that there was no consensus on what it should actually look like?

**Comment by matkoniecz** [comment]
>  what's the objection to rendering a man_made=storage_tank that someone has decided to add without a building tag

It is a strong voice in a discussion how this feature should be tagged (to be fair, not rendering it without a building tag is a also a voice in discussion, though a bit less significant). This style has significant influence and encourages editors and other data consumers to follow.

It also means that style is again made a bit more complex.

**Comment by meased** [comment]
The ideas in #2532 may help solve the rendering issue if everyone is acceptable to a storage_tank being a "minor building". Doesn't help with the tagging issue however.

**Comment by dieterdreist** [comment]
sent from a phone

> On 26. Oct 2017, at 12:41, SomeoneElseOSM <notifications@github.com> wrote:
> 
> Whether a storage tank is a building or not is probably a question for the tagging list (and likely won't get resolved there), but what's the objection to rendering a man_made=storage_tank that someone has decided to add without a building tag?


it’s really not that easy to say what is a building, e.g. German and English definitions seem to diverge: English: for human occupancy, German: accessible by humans and for the protection/storage of people, animals or things.
In OSM we have traditionally included a lot in building=* what you can also see by the fact that there is no generic non-building structure tag (significant ones are either in man made or in building or both).

Storage tank is a functional description, in Germany it could be a building or not, according to size and structure, not sure for other countries. The tanks in the photos would be ok to be tagged with the building tag imho.

**Comment by kocio-pl** [comment]
I think that something generic (derived from water tower) could be good on some z17+ probably:
1) ![silo-3](https://user-images.githubusercontent.com/5439713/37553212-dd7d1306-29c3-11e8-9947-ad662257d7d2.png)

I guess this could be used for both `man_made=storage_tank` and `man_made=silo`, since the difference is the definition what they contain (general "bulk material" for silo and more specific "liquids, compressed gases" for storage tank).

**Comment by HolgerJeromin** [comment]
I dont know any storage tank which is not on the ground

**Comment by kocio-pl** [comment]
Do you have an idea how could it be depicted?

**Comment by SomeoneElseOSM** [comment]
@HolgerJeromin raised storage tags (for feed, diesel, etc) on farms are fairly common on farms round me.  A quick image search finds a few similar examples such as http://www.frugal-living-freedom.com/images/bulkfueltanks.jpg .

**Comment by HolgerJeromin** [comment]
Google image search for storage tanks are all/most ground based.

**Comment by Tomasz-W** [comment]
What about this shape?:

![man_made storage_tank](https://user-images.githubusercontent.com/25656654/37558876-7b9653e8-2a1b-11e8-94c4-3ff599f2054b.png)

**Comment by Tomasz-W** [comment]
Gist link: https://gist.github.com/Tomasz-W/4ebcb87699e6442d696f9c06ce16c31f

**Comment by Adamant36** [comment]
I was thinking that myself and I think @polarbearing has a similar opinion. Id be willing to do tests etc on a better icon if need be.

**Comment by Tomasz-W** [comment]
2. ![man_made storage_tank2](https://user-images.githubusercontent.com/25656654/45743524-8017db80-bbfc-11e8-84e8-eca3c3e7500b.png)
3. ![man_made storage_tank3](https://user-images.githubusercontent.com/25656654/45743526-80b07200-bbfc-11e8-8cc5-3bc5e157ec40.png)

**Comment by polarbearing** [comment]
> I think @polarbearing has a similar opinion

Oh, mind-reading. Shoud I wear a tin hat? :-)
But indeed, No 3 is more pleasant. Could we try the fat one with 50% transparent fill representing the content?

**Comment by Tomasz-W** [comment]
![man_made storage_tank3](https://user-images.githubusercontent.com/25656654/45754875-24aa1580-bc1d-11e8-9d75-192a4d9f549a.png)   (50% fill)

https://gist.github.com/Tomasz-W/4ebcb87699e6442d696f9c06ce16c31f

**Comment by meased** [comment]
I like 3.

**Comment by sommerluk** [comment]
Looks a little bit like a stein (glass for beer) for me.

New icons should be monochrome. I know we have still some very few non-monochrome icons currently in openstreetmap-carto, but ideally we would get rid of them also.

**Comment by polarbearing** [comment]
The 50% one is not bad, thanks for trying, but indeed could be taken for a drink. Thus No 3 is it.

**Comment by IgorEliezer** [comment]
May I suggest a silo icon?
![image](https://user-images.githubusercontent.com/4673289/45779219-db63c100-bc30-11e8-874e-0e1a803e21b1.png)
_(quickly made on Paint.NET)_

**Comment by kocio-pl** [comment]
@IgorEliezer Thanks for your sketch, but we need to test icons on 14 px matrix to know how would they really look like.

**Comment by Tomasz-W** [comment]
Just for the note: there is replacement of `symbols/man_made/storage_tank.svg` file needed with 'v3' file from this Gist link: https://gist.github.com/Tomasz-W/4ebcb87699e6442d696f9c06ce16c31f

**Comment by jidanni** [comment]
I assume the new tank symbols will still cover up addresses. https://github.com/gravitystorm/openstreetmap-carto/issues/3435

**Comment by jidanni** [comment]
Please remove the side hose from the storage tank icon:

I would recommend not using the current
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/man_made/storage_tank.svg
for water storage tanks.

It 100% resembles a gas pump
https://www.google.com/search?q=gas+pump&tbm=isch

Only gas pumps have a tube (hose) attached to the side.

So either establish an independent icon for water tanks, or remove the hose... thanks!

**Comment by matkoniecz** [comment]
If you think that something should be changed - please open a new issue.

Comments in old issues will be almost certainly missed.

**Comment by Adamant36** [comment]
> Please remove the side hose from the storage tank icon

I'm pretty sure its not suppose to be a hose. I think it's the ladder that is on the side of most storage tanks.

**Comment by jidanni** [comment]
Oh, that is for immense storage tanks.
I say there are many more storage tanks on farms
and roofs of buildings, holding water 3, 5, 10, 20, 40 metric tons,
without ladders. As ladders are brought to the site when needed and not
left rusting attached to each tank.
None of these tanks have ladders:
https://www.openstreetmap.org/#map=19/24.18840/120.87404
So please use a more general failure-proof symbol. Thanks.

**Comment by jidanni** [comment]
Also one notes in the (iD) editor reasonable tank symbols are used. The user only discovers months later that he has actually filled the hills with "gas pumps". Furthermore, those tanks with ladders are always *much fatter than taller*. Nope, I'm sorry, the current tall tank icon with a "hose" at its side is certainly a gasoline pump.

**Comment by pnorman** [comment]
> If you think that something should be changed - please open a new issue.
> 
> Comments in old issues will be almost certainly missed.
