### ISSUE TITLE
Add rendering for amenity=bicycle_parking

### ISSUE THREAD

**Issue by Grillmannen** [gravitystorm/openstreetmap-carto#591]
Please add rendering for amenity=bicycle_parking, both nodes and areas. The icon could be the same as car parking but with a small bicycle underneath, like the JOSM "rendering".

If i remember correctly, these used to render. Areas like these look very empty with no bicycle parking rendering: http://www.openstreetmap.org/#map=19/55.86100/12.91229 .

Also, there are about 96 000 uses in the database.

**Comment by nebulon42** [comment]
FYI there is now an icon available: ![parking-bicycle-18](https://cloud.githubusercontent.com/assets/3531092/6541460/718b678c-c4d2-11e4-945c-1bc7849a23e6.png)
[nebulon42/osmic/parking-bicycle-18.svg](https://github.com/nebulon42/osmic/blob/master/transport/parking-bicycle-18.svg)

**Comment by mboeringa** [comment]
I just hope people aren't going to "tag for the renderer" with this one in the Netherlands... With +20 Million bikes or so, and about every tree, lamp- or sign pole in cities used as "bicycle_parking" around here, I could see this icon going "viral" ;-)

**Comment by Grillmannen** [comment]
That kind of usage is not the kind that is normally called "tag for the renderer"... Actually, the opposite would be true. If people would avoid tagging bicycle_parkings because the map would be congested with icons, that would be mapping for the renderer, and that is a renderer problem.

**Comment by mboeringa** [comment]
> Actually, the opposite would be true. If people would avoid tagging bicycle_parkings because the map would be congested with icons, ***that would be*** **mapping** ***for the renderer***

You are right... ;)

**Comment by mkoniecz** [comment]
> I just hope people aren't going to "tag for the renderer" with this one in the Netherlands... With +20 Million bikes or so, and about every tree, lamp- or sign pole in cities used as "bicycle_parking" around here, I could see this icon going "viral" ;-)

see http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking 

> The term ‘bicycle parking’ refers to any parking space designed for bicycles, where one can leave a pedal cycle unattended in reasonable security.

Though on http://wiki.openstreetmap.org/wiki/Key:bicycle_parking there is bicycle_parking=informal but even this is restricted to "Notably large or well-used railings, fences, or other street furniture(...)".

**Comment by matkoniecz** [comment]
I was thinking a bit about this topic during making #1364 - and my opinion is that amenity=parking and amenity=bicycle_parking of the same size have the same importance.

In most places large bicycle parking is highly unusual while giant car parkings are nothing special what is probably resulting in "all bicycle parkings are unimportant".

Also, with current rendering tiny and small parings are too prominent.

**Comment by brycenesbitt** [comment]
Bicycles can be parked almost anywhere (to poles, parking meters).  There are huge numbers of bicycle parking stands in dense areas.  Both reasons argue against rendering bicycle parking.

More rare features that one must actually hunt for I feel should be rendered:
https://github.com/gravitystorm/openstreetmap-carto/pull/1353
The rarity makes them valuable to have a map.

----
If carto had a way to dynamically set the zoom level, this would be different.  The only bicycle parking area in 100 miles, along with the only drinking fountain, probably should render at z17.  But on a college campus with hundreds of marked racks, it's hard to argue for rendering at all.

**Comment by mvl22** [comment]
> Bicycles can be parked almost anywhere (to poles, parking meters).

Then those can be marked on the map as a pole or parking meter.

My concern is about large areas of cycle parking and purely treating it as equivalent to car parking. I cannot see any logical reason why OSM should consider cycle parking less important than car parking. Either both area-based things should be shown, or neither.

There is currently cycle parking here, but you would not know it:
http://osm.org/go/0EQHxcvZL?m=
yet the adjacent *car* parking area is given prominence in yellow.

See my picture above showing the size of this area.

**Comment by kocio-pl** [comment]
> Bicycles can be parked almost anywhere (to poles, parking meters). There are huge numbers of bicycle parking stands in dense areas. 

As a city cyclist I can say that (at least in Warsaw) it's even _more_ true regarding cars: =} 

1. They can be parked almost anywhere (grass, sidewalks, by the sides of road) - and they really do, so I tag such common places according to reality, no matter if there is "P" sign.

2. There are much more such cars "stands" (official or not) than you can find poles or barriers around.

**Comment by Grillmannen** [comment]
The kind of illegal parking @kocio-pl  is talking about is the reason why it's strange to talk about bicycle parking at poles and parking meters. At least in Sweden the parking behaviour kocio-pl is describing would quickly lead to hefty parking tickets (in the area of 50-100 euros), and I guess this differs from country to country. When I was in Rome I noticed that people parked anywhere they could fit in a car, with no regard to parking signs. I guess in some countries the parking tickets are either to cheap or there are simply too few people patrolling the streets.

Of course when we're talking about tagging bicycle parkings we're talking about bike stands, and not just everywhere one might or might not put a bike without having it towed. Just as we do not mark every part of the street amenity=parking

If I were cycling in Warsaw I wouldn't dare put the bike anywhere since I wouldn't know about the local rules for bicycle parking. I'd put it in a bike stand because then I would feel certain it would not be removed by authorities.

@mvl22  describes it well.
