### ISSUE TITLE
Render the "toll" tag

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#593]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/3313). It needs more discussion as it is not clear whether a fix is needed or not.

"As requested in #2597 for osmarender, I think that Mapnik should render tolled roads in some way that is easily distinguishable from non-tolled roads. This would be really useful when planning routes. As an example, can you tell which one of these Spanish motorways is tolled? http://www.openstreetmap.org/?lat=40.3303&lon=-3.7898&zoom=13&layers=M (hint: it's the R-5, although you can't tell from the map).

A few suggestions over the possible rendering:

* Some kind of icon inside the identifier or alongside/below it, like a currency sign or some traffic signal like  http://commons.wikimedia.org/wiki/File:Spain_traffic_signal_r200.svg 

* A darker shade of the color used for a non-tolled road of the same category. It is important that the algorithm be generic because non-motorways can be tolled too (some bridges, tunnels, etc. on trunk/regional roads are tolled). This is more or less what Google does and I consider it a quite good approach:  http://maps.google.es/?ie=UTF8&ll=40.32888,-3.800068&spn=0.09239,0.222816&z=13 

* A different color altogether. This is what Bing does, and is not a bad approach, but it would require creating a new color scheme for all roads that did not conflict with the existing one:  http://www.bing.com/maps/?v=2&cp=40.327756177544124~-3.8051634729476973&lvl=13&sty=r 

* Some other visual identification like stripes, dots, whatever "

**Comment by matkoniecz** [comment]
> A darker shade of the color used for a non-tolled road of the same category. (...) This is more or less what Google does and I consider it a quite good approach

Can somebody show me roads of the same class displayed in Google differently as result of difference in toll status? Either it was mistake, it changed or it is not covering all countries.

According to my checks Google is displaying all motorways as orange and it is unrelated to toll status. I checked in Poland (there are both free and tolled motorways), London with its congestion charge and M6 Toll vs M6 in UK.

> A different color altogether. This is what Bing does

Bing is also not displaying a separate color for tolled roads, but it displays area covered by London Congestion Charge.

**Comment by math1985** [comment]
Google Maps used to render toll roads differently, but they don't do so anymore.

![Example](http://europeandcis.undp.org/blog/wp-content/uploads/2013/01/Lodz.jpg)

For example, Poznań-Golina (halfway Poznań and Łodż) is a toll road, but Golina-Łodź was (at the time of this map) no toll road.

The difference is quite hard to see, which might be why Google got rid of it.

**Comment by pnorman** [comment]
MapQuest uses green for toll rodes
MapQuest.com
![image](https://cloud.githubusercontent.com/assets/1190866/7577801/770da88e-f801-11e4-9949-2c40c407dd50.png)

MapQuest Open
![image](https://cloud.githubusercontent.com/assets/1190866/7577810/8a1b1d3a-f801-11e4-84ad-7528586c45f9.png)

Bing uses teal, which is unique to them afaik
![image](https://cloud.githubusercontent.com/assets/1190866/7577908/d039d238-f802-11e4-9f3f-719d118bdccc.png)

I recall more examples in my paper maps, which are either green or purple. I can't recall any toll road stylings that do more than change the colour.

**Comment by matkoniecz** [comment]
@pnorman @math1985 Thanks!

MapQuest is funny - they are using at least three separate styles on one map, with toll=yes displayed only in one: see http://www.openstreetmap.org/#map=14/50.0706/19.7829&layers=Q (EW motorway is tolled, NS not) and http://www.openstreetmap.org/#map=12/52.6639/-1.8697&layers=Q with M6 and M6 toll.

**Comment by pnorman** [comment]
> MapQuest is funny - they are using at least three separate styles on one map

Ah yes, I should have been more explicit. The first one is MapQuest.com in North America, the second is the MQ Open North America style, which is different from the MQ Open style in the UK and in the EU. MapQuest.com outside North America is the same as MapQuest Open.

There is also the new [mq-carto-style-vector](https://github.com/MapQuest/mq-carto-style-vector) which is [solid green at low zooms](https://github.com/MapQuest/mq-carto-style-vector/blob/master/mq-carto-style.tm2/transportation.mss#L40-L49) 
![image](https://cloud.githubusercontent.com/assets/1190866/7581812/2ad84d1c-f83c-11e4-8964-a33d2922c37c.png) and a variable shade of green depending on zoom for higher zooms.

**Comment by matkoniecz** [comment]
After working for a long time on reworking roads - I see no good way to handle this and add even more information.

One of main problems is a huge amount of separately displayed road classes with significant resistance to merging styling (see reaction to displaying trunk and motorway in way that is not allowing immediate recognition of road type).

I am quite sceptic about whatever it is possible to show highway, access, bridge, tunnel, oneway, surface and toll tags at the same time and keep map usable and nicely looking.

Even current rendering of access is highly problematic.

**Comment by polarbearing** [comment]
I agree that we have now a lot of special tags on the roads, not only tolls, but speed limits, max height, turn lanes, etc. That is too much for the general map, and the advantage of OSM is that other views can be rendered from the data that have these parameters in focus.

**Comment by pnorman** [comment]
I'd like to render toll, but I've also come to the same opinion as matkoniecz.

All toll renderings that I have seen lose information on the classification of the road, unless it is conveyed in some other manner.

As an example, MQ Open has a different pattern for motorways, which is still seen with tolls

![image](https://cloud.githubusercontent.com/assets/1190866/9509110/c56cdd34-4c10-11e5-9204-cfe3a7c46069.png)

There is often an implicit assumption in styles that tolled roads are motorways, but this isn't true.

If someone does have a style that they think works, pull requests are welcome.

**Comment by imagico** [comment]
> There is often an implicit assumption in styles that tolled roads are motorways, but this isn't true.

According to taginfo of the 120k toll=yes >106k are motorway/motorway_link, the rest is probably nearly all bridges, tunnels and other stuff that is not even a highway.  So rendering toll only on motorways is a fairly good approximation.

**Comment by polarbearing** [comment]
What makes the toll issue even more difficult is that you can have tolls for particular classes of vehicles, only. For example, Germany has a free-flow motorway toll for HGV only. As the opposite, the Dublin city harbour motorway is mandatory and free for HGV, while passenger cars pay a hefty toll for a fast transit during peak hours into the city centre.

**Comment by BalooUriza** [comment]
On Wed, Aug 26, 2015 at 6:42 PM, Paul Norman <notifications@github.com>
wrote:

> I'd like to render toll, but I've also come to the same opinion as
> matkoniecz.
>
> All toll renderings that I have seen lose information on the
> classification of the road, unless it is conveyed in some other manner.
>
> As an example, MQ Open has a different pattern for motorways, which is
> still seen with tolls
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1190866/9509110/c56cdd34-4c10-11e5-9204-cfe3a7c46069.png>
>
North American maps tend to convey classification with patterns and line
weights as much as it does with colors.  That said, if we render tolls, we
should made an effort to render it on all highway types:  Toll cycleways
and paths are a thing that exist in at least central and eastern Kansas.
