### ISSUE TITLE
Long road names get cut off

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#594]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/3277). It needs more discussion as it is not clear how this should be implemented.

The original bug was as follows:
"Tile  http://b.tile.openstreetmap.org/18/119191/109411.png does not render its part of the name on way http://www.openstreetmap.org/browse/way/78331207

Thus, name gets half-rendered on zoom level 18, being rendered on tile  http://c.tile.openstreetmap.org/18/119192/109411.png but not on the other one."

Now it seems that the name get rendered on both tiles, but cut off on one of them.

**Comment by math1985** [comment]
I haven't seen this issue occurring for a while, is it still relevant?

**Comment by matkoniecz** [comment]
http://www.openstreetmap.org/?mlat=50.06103&mlon=19.92919#map=18/50.06008/19.92920

![selection_003](https://cloud.githubusercontent.com/assets/899988/10871038/c539e6b8-80db-11e5-9172-1ee8b28be3e7.png)

**Comment by kocio-pl** [comment]
This particular location looks good now. But i guess it's still old metatiles problem?

**Comment by nebulon42** [comment]
All the examples given in this issue seem to be ok. I think we should close it for now.
