### ISSUE TITLE
Confusing arrows when oneway construction overlaps oneway highway

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#597]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/5085). It needs more discussion as it is not clear how this should be implemented.

If a road overlaps with a construction road, and both roads are oneway but in opposite direction, it is not clear which arrows refer to which roads.
Example: https://trac.openstreetmap.org/raw-attachment/ticket/5085/oneway_arrows%20of%20construction%20highways.png

The original bug report suggests the following layering stack

    construction highway
    construction oneway arrows
    normal highway
    normal oneway arrows 

However, that would create a lot of overhead in the code.

We could also decide to drop rendering arrows on construction roads altogether, or to do nothing at all.

**Comment by matkoniecz** [comment]
> Drop one way arrows on under construction roads they are not even built yet.

I think that it would be a good idea.

**Comment by nebulon42** [comment]
When we are talking about not rendering oneway arrows on certain road types like construction it would be beneficial to discuss on which types arrows should be omitted. Oneway arrows are also rendered on e.g. footways and possibly on steps although none are tagged that way currently.

Do we want that? I initially thought about omitting construction, footway, path, pedestrian, platform, steps although I see some issues with e.g. bike designated access. So maybe still include footway, path?

**Comment by matkoniecz** [comment]
path - oneway bicycle routes are nothing weird.

true footways - in my city there is a bizarre case of sidewalk with allowed bicycle traffic (highway=footway, bicycle=yes), oneway on each side of the road. I am not entirely sure is it worth showing oneway arrows in cases like that. There are also extremely limited cases of truly oneway footways (entrance only, exit only footways) like at http://www.openstreetmap.org/?mlat=50.05516&mlon=19.85401#map=19/50.05516/19.85401 There are also some oneway mountain routes like http://www.openstreetmap.org/#map=19/49.21884/20.02714

pedestrian - many highway=pedestrian allow limited traffic (for example delivery during limited hours) that is oneway. Though given that significant majority of traffic there is not oneway...

**Comment by nebulon42** [comment]
Thanks for clarifying, I will only omit construction, platform and steps for now.

**Comment by matkoniecz** [comment]
platform - I am unsure whatever we are rendering arrows there. Anyway, oneway footway through platform would be rendered anyway.

steps - there are about 800 cases of oneway=yes on steps - see http://taginfo.openstreetmap.org/tags/highway=steps#combinations and http://overpass-turbo.eu/s/bxk

It s not much, but I would prefer to keep this rendering (to keep it consistent with highway=footway, to make debugging of routing problems easier. it is also nice to cover also this rare cases)

Among known to me real cases - oneway trail in Slovenský raj - http://www.openstreetmap.org/way/273254101#map=18/48.93684/20.36541

**Comment by matkoniecz** [comment]
So I would propose to omit oneways solely for construction and platform.

**Comment by nebulon42** [comment]
I've tested with platform and oneway arrows were not rendered.
