### ISSUE TITLE
thematically related landcover types should use the same hue

### ISSUE THREAD

**Issue by ian29** [gravitystorm/openstreetmap-carto#60]
I'm thinking that features like parks, grasslands, wood, forest, pitch, etc could share a consistent hue and be differentiated only by their lightness and/or saturation. lowest hanging fruit seem to be land cover types, but i wonder where else this could help clean up the map + create a more organized palette. 

Definitely a version 3 ticket.

**Comment by math1985** [comment]
This issue is too general to be useful at the moment, especially given that the landuse colors have gotten a lot of attention. I will close this, but more specific issues are welcome.
