### ISSUE TITLE
Oneway arrows in print

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#606]
Oneway arrows are visibly chunky when in print

![image](https://cloud.githubusercontent.com/assets/1190866/3210200/a2917e34-eea9-11e3-9c6e-9d6d31207335.png)

![image](https://cloud.githubusercontent.com/assets/1190866/3210202/c3edfdd2-eea9-11e3-9c46-810ce2677e88.png)

**Comment by pnorman** [comment]
One potential solution would be to have sub-integer steps for making up the arrow.

**Comment by nebulon42** [comment]
Wouldn't it be necessary to seriously inflate the code to have a good result? But didn't know that this is even possible.
