### ISSUE TITLE
Further lightning retail landuse

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#614]
One option presented in #599 was to de-colour the retail landuse farther and adjust the hue of commercial and industrial father into the blue, with values something like

```cartocss
@residential: #E1E1E1;      // Lch(89,0,0)
@residential-line: #B9B9B9; // Lch(75,0,0)
@retail: #F4DAD6;           // Lch(89,10,30)
@retail-line: #DFADA7;      // Lch(75,20,30)
@commercial: #F0DAE5;       // Lch(89,10,345)
@commercial-line: #D8ADC3;  // Lch(75,20,345)
@industrial: #E2DDF0;       // Lch(89,10,300)
@industrial-line: #BCB4D8;  // Lch(75,20,300)
@railway: @industrial;
@railway-line: @industrial-line;
```

This results in 
![image](https://cloud.githubusercontent.com/assets/1190866/3212471/e2af305a-ef5e-11e3-9b62-b6c971430817.png)

Industrial on the left, commercial in the middle, retail on the right.

Current deployed is
![image](https://cloud.githubusercontent.com/assets/1190866/3225023/601878de-f046-11e3-9aa7-218e81d1a7f1.png)

Another idea was to use blue for commercial, as blue was considered for ``office=*``.

Do we want to do any of these?

**Comment by math1985** [comment]
@pnorman Is this issue still open?

**Comment by pnorman** [comment]
I'm okay with leaving the colours as is, but others had suggested the change

**Comment by math1985** [comment]
I think the consensus is currently that further lightening the colours is not possible without them becoming too similar. I will close the issue for now, but if anyone has a concrete proposal we can reopen it again.
