### ISSUE TITLE
unify the symbol file names to a standard scheme

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#630]
Is there a wish to unify the symbol file names to a standard scheme (before adding more files as #277)?
Right now they are a bit random, i would propose 
key_value.size.png
For example
shop_hairdresser.16.png
or
amenity_parking.16.png
or
amenity_parking_private.16.png
I could make a pull request if no one with more knowledge is faster.

The landuse / background images (as cemetery_jewish.18.png) could have a prefix or another directory.

**Comment by kocio-pl** [comment]
Resolved by https://github.com/gravitystorm/openstreetmap-carto/pull/2451.
