### ISSUE TITLE
Tertiary roads more dominant than secondary on z10

### ISSUE THREAD

**Issue by katpatuka** [gravitystorm/openstreetmap-carto#631]
On z10, tertiary roads (rendered gray) are somehow more dominant than secondary roads - see for example the secondary between Otlukbeli and Demirözü here: https://www.openstreetmap.org/#map=10/40.0363/39.9044.

**Comment by matkoniecz** [comment]
Preview of early version of new road style - that should solve too low visibility of secondary.

![tertiary vs secondary - see 631 master-_new-road-style-z16-with-purple-pedestrians 10 12 300px master - new-road-style-z16-with-purple-pedestrians](https://cloud.githubusercontent.com/assets/899988/8502710/97beec5a-21b4-11e5-8139-fb3c913b33bf.png)
