### ISSUE TITLE
Icons: SVG and PNG, minimizing blur.

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#632]
I have a branch with a SVG icon for Parking, and it's showing what was a theoretical concern is one in practice

![image](https://cloud.githubusercontent.com/assets/1190866/3280619/e5069a44-f46f-11e3-8f44-0de080a6b631.png)
(Current master left, branch right, 1600%)

A properly done bitmap is clearer than a vector graphic, when at the resolution of the bitmap. This can seen here with the lower horizontal bar of the P having 3 pixels on the non-transparent version.

Are there techniques that we can use to minimize this? How did @samanpwbb handle PNG conversions in Maki?

The relevant SVG is

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 100 100">
<path fill="none" stroke-width="14" stroke="#0092da" d="M 7,100 L 7,7 50,7 A 23,23 0 0,1 50,53 L 7,53" />
</svg>
```
and MSS is

```css
    marker-file: url('symbols/parking.svg');
    marker-placement: interior;
    marker-height: 12;
```

**Comment by math1985** [comment]
This is implemented by #1165. Closing the current issue.
