### ISSUE TITLE
landuse=greenfield should not be rendered like landuse=construction

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#648]
It is not the best idea to render these two in exactly the same way. These two are related but not enough to justify exactly the same rendering. 

Heavy color for landuse=construction is a good one, landuse=greenfield may use similar but lighter.

**Comment by Matthias84** [comment]
I suggest to reintroduce an appropriate rendering of greenfield as it's has same growth like brownfield or construction:
![Screenshot_2019-07-26 osm tag history](https://user-images.githubusercontent.com/217511/61927820-87271d00-af76-11e9-9240-af2213232dc1.png)
It's also featured at JOSM and ID editors and landcover is an important topic for a map, esp. on lower zoom levels.

**Comment by matkoniecz** [comment]
Tags are not rendered based on popularity alone. From what I see it was also not removed due to low popularity, but for other reasons.

Has anything changed since it was removed? Or are you disagreeing with reasons for removing it?

**Comment by Matthias84** [comment]
5 yrs ago the author pointed out, that color style was bad and might not easy to find a good styling for a legal (read: non physical) state. But this is more related to the tag discussion itself but not it's rendering.

I suggest to reintroduce this feature, using a coloring similar to natural=scrub as it is in use and mappers seem to distinguish between a area that is scheduled for construction and ones that are under construction or demolishion.
