### ISSUE TITLE
Cross-project icon repository?

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#659]
There are quite a number of projects using the same icons as we do (or icons derived from common svg files). Do we want to maintain the icons ourselves, or do we want to contribute to a cross-project icon database?

Projects using 'our' icons include [Potlatch 2](https://github.com/openstreetmap/potlatch2/tree/master/resources/icons), [OsmAnd](https://github.com/osmandapp/OsmAnd-resources/tree/master/icons),  [NavIt](http://sourceforge.net/p/navit/code/HEAD/tree/trunk/navit/navit/xpm/), [openstreetmap-de](http://svn.openstreetmap.org/applications/rendering/mapnik-german/symbols/), and [openstreetmap-fr](https://github.com/cquest/osmfr-cartocss/tree/master/symbols). The [original set](http://www.sjjb.co.uk/mapicons/downloads) has been extended by various parties, see [here](https://github.com/openstreetmap/map-icons/tree/master/svg-twotone), [here](https://github.com/twain47/Open-SVG-Map-Icons), [here](http://osm-icons.org/wiki/Main_Page), and [here](http://wiki.openstreetmap.org/wiki/Project_of_the_week/2010/Jul_25). As such, development on the icons is highly fragmentized.

Reasons for using a cross-project repository:
- Projects can more easily profit from development icons in other projects 
- Consistent use of icons between projects

Reasons not to use a cross-project repository:
- Added complexity
- It is easier to make icons that only look good in one particular size, and different projects might require different sizes
- The original icons have a dark background, which leaves less space for the icon itself

A good candidate for a central repository would be https://github.com/twain47/Open-SVG-Map-Icons.

**Comment by math1985** [comment]
@nebulon42 I still think it would be nice to see have some more consistency between the different projects. I guess the best way to go forward would be to write pull requests for Osmand and openstreetmap-website with the icons that have been rolled out. Would you like to do that or shall I do that?

**Comment by nebulon42** [comment]
I agree that more consistency in terms of icons would be good. But I'm not sure if it is still too early to attempt that? I wanted to reach a certain state in this repository first (i.e. all current icons replaced by SVG) before expanding work to other repositories. But if you want to try, I guess it doesn't hurt to attempt it.

**Comment by math1985** [comment]
The advantage of reaching out to OsmAnd and openstreetmap-website earlier might be that we might get more people on board helping with the conversion. But I'm fine with waiting too.

**Comment by nebulon42** [comment]
I see your point. I guess I should still focus on getting some icons done, but if you want to go ahead I'm happy to provide support where appropriate.
Just for clarification: Which icons does openstreetmap-website use? Or do you mean -de / -fr / -hot?

**Comment by math1985** [comment]
> Which icons does openstreetmap-website use?

They are used when viewing a changeset. [Example](www.openstreetmap.org/changeset/28497160), see bar left.

**Comment by nebulon42** [comment]
Ok, I missed that. Yes, I think this is a great starting point.
