### ISSUE TITLE
Gap between water and sea

### ISSUE THREAD

**Issue by sabas** [gravitystorm/openstreetmap-carto#671]
There's a small white line between a polygon tagged natural=water and the 'sea', see for example the Venetian Lagoon
https://www.openstreetmap.org/#map=17/45.33119/12.34303

**Comment by mkoniecz** [comment]
It seems that it is not happening anymore.

**Comment by sabas** [comment]
@mkoniecz see this tile https://b.tile.openstreetmap.org/18/140060/93956.png

**Comment by math1985** [comment]
It appears we have no good way to solve this, see #1275.
