### ISSUE TITLE
military=danger_area looks like building on z10 and is agressive pink at z11

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#684]
https://www.openstreetmap.org/way/234810192#map=10/54.4057/19.4012

Something between z10 and z11 style would be better - neither eyesore pink nor nearly invisible grey.

Also, pink is used for retail, commercial, supermarkets and tourism attraction. 

Current z11 style:
![przechwytywanie](https://cloud.githubusercontent.com/assets/899988/3439532/7dea123a-00e7-11e4-9ef3-8389ebecc184.PNG)

Current z10 style:
![przechwytywanie](https://cloud.githubusercontent.com/assets/899988/3439538/98d91ea6-00e7-11e4-9945-5407c8a25759.PNG)

Currently used style for [landuse=military; military=barracks] that IMHO would work as military=danger_area and for its current purpose is too strong:
![przechwytywanie](https://cloud.githubusercontent.com/assets/899988/3439558/2a5dc638-00e8-11e4-9eb3-04d764c9af73.PNG)

**Comment by math1985** [comment]
Do you think we need to keep both military=danger_area and landuse=military? We could consider using the current landuse=military rendering (red stripes) for both. Most military training grounds are likely danger areas in one way or another, and military areas probably shouldn't be entered even if they are not danger areas.

**Comment by matkoniecz** [comment]
> Do you think we need to keep both military=danger_area and landuse=military? We could consider using the current landuse=military rendering (red stripes) for both.

Seems to be a good idea - I will run test on it. But in that case it may be possible to do not handle this tag. 

Wiki has info that adding also landuse=military is mandatory what makes sense, but it is done in about half of military=danger_area. But even 50% of object is less than 500 object worldwide - see http://overpass-turbo.eu/s/gJi

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 10 giu 2016, alle ore 00:26, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> Do you think we need to keep both military=danger_area and landuse=military? We could consider using the current landuse=military rendering (red stripes) for both.
> 
> Seems to be a good idea - I will run test on it. But in that case it may be possible to do not handle this tag.
> 


what about military danger areas on water? A danger area for military reasons doesn't necessarily imply that the area is currently used for military purposes, or does it? Couldn't this also be used for legacy dangers?

**Comment by matkoniecz** [comment]
lets continue at http://wiki.openstreetmap.org/wiki/Talk:Tag:landuse%3Dmilitary#Add_explicit_note_that_it_covers_also_legacy_dangers

**Comment by matkoniecz** [comment]
From checking it seems that many of military=danger_area without landuse=military is used for tagging for renderer for dangers unrelated to military (see for obvious example at http://www.openstreetmap.org/changeset/40111293#map=19/38.99369/-77.08746).

![selection_007](https://cloud.githubusercontent.com/assets/899988/16169978/286a667a-3542-11e6-9fcc-b2943e90203e.png)

**Comment by mboeringa** [comment]
Well, you justly removed that one... I don't think this type of severe mis-usage should be any guide to decisions regarding style development.

**Comment by matkoniecz** [comment]
It was merely the most obvious one, so absurd that I changed it without verification on the ground.

But from my check most of *military*=danger_area that has no military=landuse is unrelated to military.

**Comment by kocio-pl** [comment]
Danger symbol is now moved to SVG and it should be easier to test different background color ideas by changing this line (possibly also adding [opacity](https://github.com/gravitystorm/openstreetmap-carto/pull/2739#issuecomment-321997520)):

https://github.com/gravitystorm/openstreetmap-carto/blob/79bc74d35ad3aad59b67ea2948fa7f758ae883c9/landcover.mss#L45

**Comment by kocio-pl** [comment]
Effectively closed by #3057 - see https://github.com/gravitystorm/openstreetmap-carto/pull/3057#issuecomment-364930316.
