### ISSUE TITLE
Render huge military areas on earlier zoom levels

### ISSUE THREAD

**Issue by HolgerJeromin** [gravitystorm/openstreetmap-carto#686]
Should we render http://www.openstreetmap.org/way/35876652 and http://www.openstreetmap.org/way/31427818 earlier than zoom 10? Moved discussion from #420

**Comment by matkoniecz** [comment]
Even better examples: http://www.openstreetmap.org/#map=10/51.2641/-1.8539 http://www.openstreetmap.org/?mlat=47.0350&mlon=-122.5621#map=10/47.0350/-122.5621

**Comment by kocio-pl** [comment]
Makes sense for me. I guess we could show earlier also industrial areas (like quarry) if they are big enough, because some of them are really huge and make important part of the landscape.
