### ISSUE TITLE
Add rendering for amenity=fountain

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#705]
Hi,

I'd like to know what is the current state of affairs with the fountain rendering?

We have reasonable proposition to fix this issue (https://github.com/gravitystorm/openstreetmap-carto/pull/47) - there is the code and even the icon (https://github.com/Rovastar/openstreetmap-carto/blob/e5320dbd98981fdeb1944771d54d6984b4bf4b73/symbols/fountain.png). I know the original reporter mixed too many things in one basket, but this one should be easy to pick up and merge - almost no-brainer.

So what are technical - or maybe other - obstacles keeping this issue unresolved and what should be done to fix it? I want to help if it's needed and possible.

**Comment by nebulon42** [comment]
Possible icon for fountain: ![fountain-18](https://cloud.githubusercontent.com/assets/3531092/6652543/942545c4-ca72-11e4-805e-e1e70419de35.png)
[nebulon42/osmic/outdoor/fountain-18.svg](https://github.com/nebulon42/osmic/blob/master/outdoor/fountain-18.svg)

**Comment by kocio-pl** [comment]
I would expect more symmetry (possibly with 4 or 6 water streams instead of just 2), since the fountains are mostly big, decorative objects. This one I would recognize as a small water "fountains" for drinking or washing hands.

**Comment by mboeringa** [comment]
One warning here: often, people tag each and every fountain in a fountain group. This may mean dozens of "fountains" in a very small area. Prime examples are the fountains in the basin near Palais de Chaillot in Paris, and the famous "Fountains of Bellagio" in Las Vegas.

You won't be able to render this with an icon on any but the highest zoom... and even on Z19, it is likely icons may overlap, unless using routines to avoid collisions.

**Comment by nebulon42** [comment]
I just wanted to notify this thread that there is a possible icon available. I didn't imply anything about feasibility or such and I also didn't intend to propose a PR.

**Comment by matkoniecz** [comment]
>  it is likely icons may overlap, unless using routines to avoid collisions

In this style all labels and icons have enabled collision detection and no overlap is allowed.

**Comment by mboeringa** [comment]
> In this style all labels and icons have enabled collision detection and no overlap is allowed.

Good. Still, cartographically, it may not lead to the nicest results if multiple icons are displayed close to each other, even if they do not overlap. At least something to consider and possibly try out with the example locations I pointed out, where this potential problem is likely to surface.

**Comment by dieterdreist** [comment]
> Am 14.03.2015 um 21:14 schrieb mboeringa <notifications@github.com>:
> 
> Good. Still, cartographically, it may not lead to the nicest results if multiple icons are displayed close to each other, even if they do not overlap. At least something to consider and possibly try out with the example locations I pointed out, where this potential problem is likely to surface


In my view fountains can consist of several sub objects emitting or channeling water, but it would still remain one fountain with one name, architect etc. and should be one object amenity=fountain 

Having many of them close together is either a tagging problem or a very particular situation 

Cheers 
Martin

**Comment by mboeringa** [comment]
> In my view fountains can consist of several sub objects emitting or channeling water, but it would still remain one fountain with one name, architect etc. and should be one object amenity=fountain Having many of them close together is either a tagging problem or a very particular situation

I basically agree. Yet there is the tagging practice, which often contradicts logic... Here is the example from my OSM Renderer for ArcGIS. Each saturated blue dot in the lake in the lower right corner is a node tagged with **amenity = fountain**. I think this practice is more widespread.

You may be able to dodge this problem by setting a wide "collision spacing" or so, preventing any other icons appearing, at the small risk of missing some other icons in other fountains nearby.

![amenity_fountain_palais_de_chaillot_paris](https://cloud.githubusercontent.com/assets/7635726/6653422/b5608472-ca92-11e4-8fb4-17792971b6fb.jpg)

**Comment by kocio-pl** [comment]
So we may act like this:
1. Render all the nodes as blue dots
2. Render all the areas as nice icon in the middle (https://github.com/gravitystorm/openstreetmap-carto/pull/1384#issuecomment-80792078)

If such detailed tagging - for each nozzle - is a common practice, we should respect it and use the robustness principle ("be liberal in what you receive and be conservative in what you send"). That way we'll be always on the safe side and blue point is still better than nothing at all. It may be tricky to tell what tagging scheme should be used to know when we would draw a point (just a nozzle) or a full icon (the architectural object), because fountain can also have the form of one nozzle. Maybe if we want to be sure this node is more than "just a nozzle" we should expect "amenity=fountain + fountain=architectural_object/real_fountain/..." scheme?

But when we have the area, we know it's not about the nozzles anymore and this is fountain in the broader sense - an architectural object. There is another problem however - should we render the water on the whole area? I guess not, because it'd be also too far and we can stay on the safe side: if one knows there is a water it can add that later (as a basin or something alike), but the fountain may be disused, but probably there's the edge to tag as a wall, so we still have the idea of how big it is.

And the other aspect: fountains are often known to be in the form of a statue or other specific art form - how should we treat such cases? What comes first - a form or a function - or maybe we need a special icon for that case?

**Comment by mboeringa** [comment]
I think area / ways tagged with **amenity = fountain**, just need a label added based on the name tag. In most cases, if the fountain is big and historic / prominent enough, there will be some name associated with it. See the "Basin du Dragon" in the previous image I posted here in this issue tracker.

Of course, a name label by itself doesn't tell you for sure if it is a fountain or not, but in most cases, if of interest to tourists, like for example the "Trevi fountains" in Rome, you will know the name and the fact that it is a fountain beforehand, and just need to know *where* it is... the label will suffice to tell you, no icon needed.

**Comment by dieterdreist** [comment]
> Am 15.03.2015 um 03:35 schrieb kocio-pl <notifications@github.com>:
> 
> Maybe if we want to be sure this node is more than "just a nozzle" we should expect "amenity=fountain + fountain=architectural_object/real_fountain/..." scheme?


I think there are very few extra tags typically on fountains. I would request a name (and render that name) rather than strange architectural object tags (all fountains can be considered architectural objects). Still I believe that putting an amenity fountain tag on each nozzle is not the way this tag generally works, maybe we can come up with a more specific tag for those rather than declare the "naked" fountain tag lost because of them?

cheers 
Martin

**Comment by dieterdreist** [comment]
> Am 15.03.2015 um 03:35 schrieb kocio-pl <notifications@github.com>:
> 
> And the other aspect: fountains are often known to be in the form of a statue or other specific art form - how should we treat such cases? What comes first - a form or a function - or maybe we need a special icon for that case?


I would see the sculpture as part of the fountain and give priority to   the latter

**Comment by kocio-pl** [comment]
> Still I believe that putting an amenity fountain tag on each nozzle is not the way this tag generally works, maybe we can come up with a more specific tag for those rather than declare the "naked" fountain tag lost because of them?

If we think current tagging practice is simply broken and refuse to respect it, everything would be much easier - we would render nice icon by default even for the nodes, and make it a blue dot only in case of nodes tagged as "amenity=fountain + fountain=nozzle".

**Comment by mboeringa** [comment]
> **If we think current tagging practice is simply broken and refuse to respect it**, everything would be much easier - we would render nice icon by default even for the nodes, and make it a blue dot only in case of nodes tagged as "amenity=fountain + fountain=nozzle".

I think we all agree that this practice isn't the best, but this type of tagging issues is often a consequence developing knowledge and experience.

Currently, **fountain = x** does not seem to be documented on the Wiki (and only 43 uses in TagInfo), and is probably not supported in the defaults of the editing tools like JOSM either. It neither is in the database, so your proposition will not work at this moment in time.

**Comment by kocio-pl** [comment]
So which route should we take:
1. Useful, but not perfect (nodes only as the dots, icons for the area)?
2. Perfect, but hard (try to make fountain=x "alive" somehow)?

Of course we can take 1. for now and hope for 2. in the future, because it's still better than no fountain rendering.

**Comment by mboeringa** [comment]
Another thing to think about: sometimes, it is difficult to distinguish between what represent a "nozzle", and what a "fountain". Look at the image below of Versailles near the red arrow. The blueish dot's are actually "nozzles/fountains", intermingled with a tree row along a path. I surely couldn't tell what is the nozzle or fountain here (unless each has it's own name, in which case every dot probably represents an individual fountain). But an icon on each "nozzle/fountain" here, may not be the best...

![versailles_fountain_line](https://cloud.githubusercontent.com/assets/7635726/6656341/e50c58ec-cb26-11e4-9e16-babd141507c3.jpg)

It is this location in reality:

**Comment by kocio-pl** [comment]
Nozzle is just a water pipe end - no statues, cups or whatever. On the picture I see the real fountain and I have no doubt about it, so I would render the real icon here, not the dot. Of course only from some zoom level, so we may use safe z for which we still use the dot instead of the icon.

**Comment by mboeringa** [comment]
Looking at Z19 of the same location in Versailles, it seems only Z19 will do for rendering icons:

http://www.openstreetmap.org/#map=19/48.80724/2.12194

At Z18, the icons are already likely to be conflicting / colliding.

**Comment by kocio-pl** [comment]
So we have no other (safe) choice. If somebody will come with a better idea we can change it, but now I would make it a regular icon for nodes with z>=19 and for areas, otherwise it should be just a dot.

**Comment by mboeringa** [comment]
Agree (if an icon is desired)

**Comment by kocio-pl** [comment]
At least it's just highly recommended IMHO. =}

**Comment by dieterdreist** [comment]
2015-03-15 14:46 GMT+01:00 kocio-pl <notifications@github.com>:

> If we think current tagging practice is simply broken and refuse to
> respect it, everything would be much easier - we would render nice icon by
> default even for the nodes, and make it a blue dot only in case of nodes
> tagged as "amenity=fountain + fountain=nozzle".





We should not tag fountains and parts of fountains with the same tag IMHO.
I suggest to use a different tag for nozzles, like amenity=fountain_nozzle
or man_made=fountain_nozzle or maybe even waterway=fountain_nozzle.
Subtagging is fine for subsets of an object, not for different kind of
objects.

**Comment by dieterdreist** [comment]
What is the state here? Are pull requests useful or is there already one? I came across a nice garden this weekend with some very impressive fountains: 
http://www.openstreetmap.org/relation/4863600#map=18/42.42494/12.15439
The rendered map is a really bad representation of the data here. Am I expected to add natural=water to them?
This is what we are talking about: 
http://en.wikipedia.org/wiki/Villa_Lante

**Comment by math1985** [comment]
>  http://en.wikipedia.org/wiki/Villa_Lante

Wiki says:

> [Fountain] applies to nodes and areas although most fountains should be tagged as nodes representing the location of the fountain sitting within an area of natural=water 

I think indeed that it should be tagged as natural=water.

**Comment by dieterdreist** [comment]
> Am 05.05.2015 um 13:13 schrieb math1985 <notifications@github.com>:
> 
> I think indeed that it should be tagged as natural=water.
> 

I'll micromap the 4 basins then in this case, still it would be nice to have   the name of the fountain rendered

**Comment by jojo4u** [comment]
Some summary: 
* amenity=fountain should relate to the whole thing (e.g. to name it)
* amenity=fountain for every nozzle does not work out

Natural=water plus amenity=fountain as node comes from the misconception (http://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dfountain) that there is only one source of water. There is no water= tag fitting a fountain since there is already amenity=fountain. The closest is reflecting_pool which states "undisturbed by fountain jets". [Wiki] (http://wiki.openstreetmap.org/wiki/Proposed_features/Water_details)

Best solution: Refine definition amenity=fountain as the whole fountain including the nozzles and the water basin. Invent a new tag for nozzles. Micromapped areas have  active mappers which are able to retag in case there was excessive nozzle-mapping.

**Comment by dieterdreist** [comment]
2015-05-29 12:39 GMT+02:00 jojo4u <notifications@github.com>:

> Refine definition amenity=fountain as the whole fountain including the
> nozzles and the water basin.



+1, in case the object has a name ("foo fountain") we should have one
object amenity=fountain with this name, and use different tags for the
parts of it.

**Comment by kocio-pl** [comment]
So probably:
1) amenity=fountain should be rendered with a name and the specific icon for the whole area it covers (or just a point),
2) basins included should be tagged just as a water=*,
3) individual nozzles (tagged like amenity=nozzle) should be rendered with a blue dot.

Does it make sense?

**Comment by math1985** [comment]
If the entire water basin should be covered, how do we tag fountains like this?

http://i.ytimg.com/vi/1fye2MrXlxM/maxresdefault.jpg

**Comment by kocio-pl** [comment]
I think this is a point fountain (or maybe just a nozzle if smaller) inside wider water area. We left it to the mappers to tell what is the scope of the fountain.

**Comment by dieterdreist** [comment]
> Am 29.05.2015 um 14:00 schrieb kocio-pl <notifications@github.com>:
> 
> So probably:
> 1) amenity=fountain should be rendered with a name and the specific icon for the whole area it covers (or just a point),
> 


from my own rendering experience I suggest to render just a name and no icon

> 
> 3) individual nozzles (tagged like amenity=nozzle) should be rendered with a blue dot.
> 


this is not an established tag AFAIK and I'd contest it on a semantic level and neither would it integrate well with the tagging scheme in general

This should be discussed on tagging ML

**Comment by dieterdreist** [comment]
> Am 29.05.2015 um 14:10 schrieb kocio-pl <notifications@github.com>:
> 
> We left it to the mappers to tell what is the scope of the fountain


+1, for sure we won't tag the whole lake as a fountain

**Comment by kocio-pl** [comment]
> from my own rendering experience I suggest to render just a name and no icon

From my experience probably most are just decorative points in park with no name. The whole discussion took place because we wanted to also include some big fountain areas, where there's a need for separate tagging individual nozzles and the fountain as the whole.

In my proposition (I will ask about it on tagging list) both (very different) types can have sane, even if not the best, rendering. What's your experience then and with small fountains with no name then?

**Comment by dieterdreist** [comment]
> Am 30.05.2015 um 12:43 schrieb kocio-pl <notifications@github.com>:
> 
> What's your experience then and with small fountains with no name then?

my experience was that either fountains prevented other, subjectively more important features from rendering (high priority), or they popped up and re-disappeared in a random way (lower priority), because the symbol and text together occupied too much space and because of a lot of fountains in the area, a few big  important and many small ones.

fountains without a name are typically so small that many people not even notice them when passing in the street. There are lots of very impressive, famous and large fountains around here, with rich decorations, often sculptural qualities, and famous names. 

most famous ones include 
http://en.wikipedia.org/wiki/Fontana_dei_Quattro_Fiumi
http://en.wikipedia.org/wiki/Trevi_Fountain
http://en.wikipedia.org/wiki/Quattro_Fontane
(last one difficult to render nicely)

These would be nice to show up very early (maybe z15 or 16), the qualifier could be tourism=attraction

Fontana di Trevi used to show up at z16, currently it's z18 which seems too late:

http://www.openstreetmap.org/#map=18/41.90076/12.48326

Typically if the fountain has no name it is also less important.

Visualizing (mapping) single nozzles makes sense in different settings like bigger water areas, like here:
http://www.pland.de/wp-content/uploads/2010/08/Plan°D-Wasserspiel-Eingangsbereich-Eschborn-Plaza.jpg
http://www.freizeitpark-welt.de/freizeitparks/plopsaland/fotos/tanzende_fontaenen.jpg
or less recent
http://footage.framepool.com/shotimg/qf/415755974-apollo-brunnen-quadriga-versailles-schlosspark.jpg

cheers 
Martin

**Comment by kocio-pl** [comment]
So your hometown is probably different from mine - there are not such big fountains, and those "small" are not to be seen passing the streets, because they are important landmarks in parks, like:
- [named one in Ogród Saski](http://www.openstreetmap.org/way/72833745)
- [not named one near Pałac Kultury](http://www.openstreetmap.org/node/2306370568)
- [another not named - it's tagged as a sculpture, because I was not sure how to treat something not being just a nozzle](http://www.openstreetmap.org/node/3384271665)
- [one more not named in the local park](http://www.openstreetmap.org/node/1289106373)

They are very typical here in Warsaw. What would you do with them? How would you change/extend my proposition for tagging and rendering to work in a sane way for both cases?

**Comment by dieterdreist** [comment]
2015-05-31 22:54 GMT+02:00 kocio-pl <notifications@github.com>:

> So your hometown is probably different from mine - there are not such big
> fountains, and those "small" are not to be seen passing the streets,
> because they are important landmarks in parks, like:
>
>    - named one in Ogród Saski <http://www.openstreetmap.org/way/72833745>
>    - not named one near Pałac Kultury
>    <http://www.openstreetmap.org/node/2306370568>
>    - another not named - it's tagged as a sculpture, because I was not
>    sure how to treat something not being just a nozzle
>    <http://www.openstreetmap.org/node/3384271665>
>    - one more not named in the local park
>    <http://www.openstreetmap.org/node/1289106373>
>
> They are very typical here in Warsaw. What would you do with them? How
> would you change/extend my proposition for tagging and rendering to work in
> a sane way for both cases?
>



First of all, I would question if those fountains that contain sculptural
artwork really are not named. Typically they should be. They would also
have a known architect or artist normally. Maybe, but I am not sure about
this, if they are from socialist times, they might not be traceable back to
a single artist but to a collective. I believe you could use the name of
this collective for the artist / architect.
Of course there will still remain some fountains that indeed do not have
names, or where we cannot find the names for now. Rendering the names for
those with names will already be some kind of filter and will give us more
probability that prominent fountains are rendered, for those without names
I see 2-3 main alternatives:

1. render an icon and accept that it will "break" the map for areas with a
lot of fountains.

2. do not render an icon. This will encourage mappers to search the names
of prominent fountains that are yet untagged, but it will also leave some
fountains unrendered which would likely be rendered if you decided manually
for every fountain.

3. decide on additional keys or tags that will determine if an icon is
rendered or not, e.g. in absence of a name.

**Comment by math1985** [comment]
I haven't followed the entire discussion (it would be a day job) - is there any chance this is eventually going to lead to a pull request?

**Comment by kocio-pl** [comment]
@math1985 We're not ready for PR, but the conclusions are very close IMO, because we talk about the sane compromise between rendering big and small fountains.

**Comment by kocio-pl** [comment]
@dieterdreist I have checked the sculpture and you were right - the name and the artist are known, so I updated the tagging here. 

It is interesting that it's not so typical for a small fountain - [the water goes through nozzles at the bottom of the sculpture, not only form the sculpture itself](http://www.zoliborzanie.pl/wp-content/uploads/2011/08/alina_gora_2.jpg). It ensures me we need some additional tagging for the nozzles, the lights and any other micro scale devices that can be used with the fountain. 

I think it's an important conclusion, because this would allow us be micromapping-friendly from the start. That would be nice side effect of such a late decision to render the fountains.

## Tagging and rendering guide

I guess we could render the points with a name (if available) + the icon, and probably the area with just a name. That way we shouldn't break too much and give the mappers more flexibility with what do they consider to be a fountain, since it showed they can come in wide variety of forms and sizes.

If the nozzles inside the big fountains are tagged as fountains, they could be retagged probably, but we need the new tag then for nozzle - maybe just water=nozzle (amenity=nozzle was clearly rejected), but the other tags for elements used there (such as lights) could be crafted too. 

Nozzles should be always rendered as blue dots, since they can be quite small. 

## Rendering details

I will try to make a mockup to test the idea. I would start with full icons from z>=17, just like many smaller POIs. The name for the points should be in water-like color and with typical size and style. Embassy and bus stop could be the right templates here.

Name for the areas should be the same color and text style, but the size should be dependent on the way_area. I don't know from what zoom level should they be visible and what size/way_area function should we use, because I had no time to look at big fountains yet. 

Nozzle zoom level have to be higher than 17 - for small fountains z19 would be better than z18. We don't have this tag yet, but it's better to know it beforehand.

What zoom levels or other general hints do you suggest? We will tweak it after all, so it does not have to be right from the start.

**Comment by jojo4u** [comment]
@Kocio-pl, any progress in the mockup? Since nozzle is part of a fountain let's use the namespace: fountain:nozzle=yes for the nozzle.

**Comment by kocio-pl** [comment]
Not yet, I have some other things, but I still remember and plan to do it. This tagging sounds reasonable - I still think it should be first proposed on Tagging list, but I expect no problems with accepting it.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 18.07.2015 um 22:20 schrieb kocio-pl <notifications@github.com>:
> 
> This tagging sounds reasonable - I still think it should be first proposed on Tagging list, but I expect no problems with accepting it.
> 

+1

**Comment by kocio-pl** [comment]
Sorry for such a long delay, but here is the first batch of local mockups. Right now I'm looking for the right color, because water-text is too pale and transportation-text is too strong (and I don't want the fountains to resemble transportation facilities). Any suggestions?

![fountain-pkin-water](https://cloud.githubusercontent.com/assets/5439713/9290642/e0f940c0-439a-11e5-8ac9-c7f5ee958099.png)
![fountain-pkin-transportation](https://cloud.githubusercontent.com/assets/5439713/9290647/ed7b4e9c-439a-11e5-85cd-f368b1f406a1.png)

![fountain-saski-water](https://cloud.githubusercontent.com/assets/5439713/9290644/e655aafe-439a-11e5-920f-69a5d4828b62.png)
![fountain-saski-transportation](https://cloud.githubusercontent.com/assets/5439713/9290648/f996d570-439a-11e5-8743-83e7591e1567.png)

![fountain-alina-water](https://cloud.githubusercontent.com/assets/5439713/9290645/e8b89e3c-439a-11e5-9b34-3e12ff4d41ec.png)
![fountain-alina-transportation](https://cloud.githubusercontent.com/assets/5439713/9290653/00bd0e96-439b-11e5-90ec-f40d1864fde1.png)

**Comment by jojo4u** [comment]
This is not closed, only the icon was added, no area rendering.

Example:  http://www.openstreetmap.org/#map=19/48.77501/9.17879&layers=N / http://www.openstreetmap.org/way/100055576

**Comment by HolgerJeromin** [comment]
Note that not every fountain has a water area:
https://de.m.wikipedia.org/wiki/Kugelbrunnen_(Aachen)
has iirc not even a small water surface.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 31.10.2015 um 14:43 schrieb Holger Jeromin <notifications@github.com>:
> 
> Note that not every fountain has a water area:
> https://de.m.wikipedia.org/wiki/Kugelbrunnen_(Aachen)
> has iirc not even a small water surface.


for me it renders fine:
http://www.openstreetmap.org/#map=17/50.77535/6.09181
http://www.openstreetmap.org/#map=18/50.77535/6.09181

**Comment by kocio-pl** [comment]
> This is not closed, only the icon was added, no area rendering.

By design - the fountain can be an area but not filled with water. One can add the basin easily (as it is done now) and it doesn't break, while removing water it would be hard (new tags for fountain should be coined and database reload would be needed). If we know the fountain area we should have it tagged, no matter if there's a water inside or not.

> for me it renders fine:

I guess @HolgerJeromin was not complaining but trying to explain why the fountain area is not filled with water.

There can be some problems on z17, where the icon has small water circle included (as a context for a dot), however it should be discussed in more details on https://github.com/gravitystorm/openstreetmap-carto/issues/1934, as this is a specific subcase of rendering.

**Comment by HolgerJeromin** [comment]
> I guess @HolgerJeromin was not complaining... 

You are right. Thanks for explaining.

**Comment by jojo4u** [comment]
So how should be tag the water area? If water area equals the fountain area according to  http://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element the best would be a property of amenity=fountain. If the water area is smaller it should be still marked as a part of the fountain. So like building:part something like fountain:part=basin.

**Comment by kocio-pl** [comment]
Fountain can have many parts: nozzle (one or more) seems to be essential, water basin is very common, some artwork is also a common part, but there can be some lights (even in the basin) also - I'm not aware of any other common part. @matkoniecz said he has an idea related to mapping big/complex fountains and I hope he will reveal it some day :) ... I think now it's time to define it as a whole, not just a basin, because it will be harder to make the parts tagging coherent later. 

Do you have an idea how should we tag all the fountain parts?

**Comment by dieterdreist** [comment]
sent from a phone

> Am 03.11.2015 um 03:48 schrieb kocio-pl <notifications@github.com>:
> 
> Do you have an idea how should we tag all the fountain parts?
> 


I'd use the same tags we use otherwise without the fountain. E.g. in Rome there is a famous fountain with an ancient egyptian obelisk on top, I don't see the need to say it's a fountain part, you can see this because it's inside the fountain perimeter. (btw, current rendering puts a blue circle atop the obelisk icon, it's on Piazza Navona)

cheers 
Martin

**Comment by kocio-pl** [comment]
For osm-carto that could be enough (given we agree how to tag individual nozzles), but it's better if the tagging scheme is more flexible - for example for making 3D models too or selectively hiding some elements (like fountain lights, but not the street lights).

**Comment by dieterdreist** [comment]
2015-11-03 10:07 GMT+01:00 kocio-pl <notifications@github.com>:

> For osm-carto that could be enough (given we agree how to tag individual
> nozzles), but it's better if the tagging scheme is more flexible - for
> example for making 3D models too or selectively hiding some elements (like
> fountain lights, but not the street lights).



yes, some features like fountain lights (or maybe more general: underwater
lights) could make sense, taggingwise. Others, which are also sometimes
integral part of fountains, like obelisks, shouldn't get a fountain-obelisk
tag (IMHO). They're obelisks in the fountain, there's nothing more special
to them.

If we want to go on discussing this, we should do it in the B Ark (sorry,
meant tagging-list).

**Comment by kocio-pl** [comment]
I have already started this topic 2 months ago, but nobody replied:

https://lists.openstreetmap.org/pipermail/tagging/2015-September/026349.html
