### ISSUE TITLE
landuse=basin with basin=detention

### ISSUE THREAD

**Issue by merkato** [gravitystorm/openstreetmap-carto#709]
As in http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dbasin landuse=basin + basin=detention should be used for tagging of dry basins for stormwater. 

Proposal for rendering:
![polder_bukow_propozycja_small](https://cloud.githubusercontent.com/assets/847295/3536592/ac0a3dce-0813-11e4-9980-c2b3fb4e6899.png)

**Comment by matkoniecz** [comment]
If that is still something that should be fixed - is anybody aware about OSM elements that would be a good examples of situation?

**Comment by jragusa** [comment]
According to the wiki definition and since #3104, we can render the subtag basin as intermittent water body as figured in the first post.

**Comment by matkoniecz** [comment]
@jragusa Can you provide any example of OSM element (way/relation)?

**Comment by jragusa** [comment]
Initially, I thought it was only related to storm events and hence to some countries (U.S.) but actually we also find this feature in Europe. They are built to store water during important rainfall and hence prevent large river flooding. They are also frequently found along major highways.

An example here near Annecy (https://www.openstreetmap.org/#map=18/45.92946/6.12063) where you can find 2 basins with the correct tags (https://www.openstreetmap.org/way/529090226 and https://www.openstreetmap.org/way/529090223).

Look at the aerial photograph to compare: https://www.geoportail.gouv.fr/carte?c=6.121392731642797,45.929393524870136&z=18&l0=ORTHOIMAGERY.ORTHOPHOTOS::GEOPORTAIL:OGC:WMTS(1)&l1=GEOGRAPHICALGRIDSYSTEMS.MAPS::GEOPORTAIL:OGC:WMTS(0)&permalink=yes

The upper one contains some water while the lower one is empty

**Comment by jragusa** [comment]
@matkoniecz 
same location with intermittent pattern:
https://www.openstreetmap.org/#map=18/45.92935/6.12104
![basin_retention](https://user-images.githubusercontent.com/9897203/40747064-828fa6ec-645c-11e8-921a-575fccd25d24.png)

**Comment by jragusa** [comment]
@matkoniecz and @kocio-pl Are you agree to apply intermittent water body pattern to the `basin=retention`, `basin=detention` and `basin=infiltration` tags ?

**Comment by kocio-pl** [comment]
Reading Wikipedia articles and short description on OSM wiki I understand that basin=retention is called wet pond, because it does not loose water, so I would leave it as it is. But `basin=detention` and `basin=infiltration` are meant to loose water over time, so it makes sense to me to render them as intermittent.
