### ISSUE TITLE
Do we want casings around water at low zooms?

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#71]
I believe it is possible to join water features in a way that would allow us to put a casing around them without lines where they are broken into smaller areas (e.g. long rivers).

I think it would perform okay on higher zooms.

Would this be cartographically desirable?

**Comment by kocio-pl** [comment]
The water examples from given locations are still not too visible.

**Comment by math1985** [comment]
Agree.
