### ISSUE TITLE
Administrative boundaries not being rendered for closed ways

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#713]
See here for an example:

http://www.openstreetmap.org/?lat=37.88179412484169&lon=-122.3072612285614&zoom=18

The way representing the boundary for the city of Albany, which is being rendered by Mapnik, has a small gap, while the adjacent city of Berkeley boundary is closed. When I close the gap, Albany's borders disappear from the map. It appears that non-closed ways and closed ways that are part of relations are being rendered, but closed ways without relations are not.

See https://trac.openstreetmap.org/ticket/4667.

**Comment by kocio-pl** [comment]
Looks like it's working now.

**Comment by jeisenbe** [comment]
Should we stop rendering the border lines from unclosed ways (lines)?
