### ISSUE TITLE
Add rendering for highway=emergency_access_point

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#715]
The tag highway=emergency_access_point should be rendered as icon.

See also https://trac.openstreetmap.org/ticket/1174.

**Comment by pnorman** [comment]
After this time without any progress on *how* to render this feature, I'm going to close this issue out.

**Comment by daganzdaanda** [comment]
I had not seen this yet, but I think we should consider icons for most "emergency=*" objects.

There is ISO 7010 for emergency symbols, see here: https://de.wikipedia.org/wiki/Rettungszeichen
For emergency access points, I've seen the white cross on green, like this: https://de.wikipedia.org/wiki/Datei:Anfahrpunkt_für_Rettungsfahrzeuge_HP_108_Alter_Lorscher_Weg_102_1235.jpg

There seems to be a simpler version of https://en.wikipedia.org/wiki/File:ISO_7010_E007.svg for meeting points, with a single dot in the middle of the arrows.

At the moment, we try to get all icons to work without a box. It would be a bit confusing with a simple cross -- we would need a new colour (dark green?) and hope that nobody reads it as pharmacy. Apart from the first-aid cross, the symbols could work without their box -- except that 14px is *really* small...
