### ISSUE TITLE
Add rendering for man_made=wastewater_plant

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#717]
The tag man_made=wastewater_plant should be rendered as icon and/or landuse.

See also https://trac.openstreetmap.org/ticket/1830.

**Comment by KaiRo-at** [comment]
I think it just should be rendered the same as landuse=landfill, at least for now. Both have to do with waste management.

**Comment by HolgerJeromin** [comment]
Perhaps render it the same as industrial (and its name).

**Comment by matkoniecz** [comment]
Maybe show labels in landuse=industrial style.

I would expect that man_made=wastewater_plant area would be anyway tagged as landuse=industrial. Are there cases of correctly tagged places where rendering man_made=wastewater_plant like landuse=industrial would improve situation?

(the same case as power=plant - see https://github.com/gravitystorm/openstreetmap-carto/pull/1836#issuecomment-140301385)

**Comment by HolgerJeromin** [comment]
I thought about it, too, but the landuse is not documented in the Wiki. 
I have no problem with this solution, but wiki should be adapted. 
Right now I cannot check how many of the 32 245 ways have no industrial.

**Comment by matkoniecz** [comment]
> landuse is not documented in the Wiki

I am pretty sure that landuse=industrial is documented. Also, way with man_made=wastewater_plant may be without landuse industrial and still be fully inside larger landuse=industrial.

>  Right now I cannot check how many of the 32 245 ways have no industrial. 

This is easy - see http://taginfo.openstreetmap.org/tags/man_made=wastewater_plant#combinations (it is 1 in 10).

**Comment by HolgerJeromin** [comment]
Sorry, I meant the text and info box of the wastewater article does not mention that landuse is useful to add. It did for power plant.

**Comment by aceman444** [comment]
So 1 in 10 meaning only 1 has any landuse set. That means wasterwater_plant should be rendered by itself, not relying on the landuse tag.

**Comment by SomeoneElseOSM** [comment]
Quite often a man_made=wastewater_plant is a named part of a differently-named landuse=industrial area.  I suspect that part of the reason why the landuse=industrial combination is as high as it is is in order to get a name to render.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 08.10.2015 um 11:30 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> I am pretty sure that landuse=industrial is documented. Also, way with man_made=wastewater_plant may be without landuse industrial and still be fully inside larger landuse=industrial.


it could also be a very small plant and not merit any landuse =industrial tag at all

**Comment by matkoniecz** [comment]
> it could also be a very small plant and not merit any landuse =industrial tag at all

Can you give an example (preferably with photo) where landuse=industrial should not be mapped and rendering it as area like landuse=industrial would be a good idea? I encountered extremely small and even in that cases landuse=industrial would be desirable.

**Comment by dieterdreist** [comment]
2015-10-09 10:17 GMT+02:00 Mateusz Konieczny <notifications@github.com>:

> Can you give an example (preferably with photo) where landuse=industrial
> should not be mapped and rendering it as area like landuse=industrial would
> be a good idea? I encountered extremely small and even in that cases
> landuse=industrial would be desirable.



You can check these results (not all of them are non-industrial, but I am
sure you agree that a lot are):
https://www.google.com/search?q=household+waste+water+plant&safe=off&tbm=isch&tbo=u&source=univ&sa=X&ved=0CCkQsARqFQoTCN-q9dzXvMgCFUTHFAodolEFcQ&biw=1873&bih=978

**Comment by matkoniecz** [comment]
In this cases I think that rendering such areas like landuse=industrial would not be a good idea.

**Comment by HolgerJeromin** [comment]
do we need such small private wastewater plant in the rendering? I am not sure. 

So perhaps rendering the name is an idea:
On industrial plants it will suggest a additional landuse=industrial and a private one in a garden has probably no name, so it does no harm.

**Comment by jojo4u** [comment]
I added to the wiki: 
> If the plant is not inside an already tagged area of {{tag|landuse|industrial}} and if it serves many households also add {{tag|landuse|industrial}}.

http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwastewater_plant

**Comment by HolgerJeromin** [comment]
We should apply the same logic to water_works.
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_works
I added the same text to the water_works wiki and the german translations of both articles.
Perhaps this github ticket could be adjusted to support both tags.

**Comment by Tomasz-W** [comment]
More than 2 years passed. What are your opinions now? 
IMO rendering wastewater_plant and water_works just like landuse=industrial is the best solution here.

**Comment by matkoniecz** [comment]
I am not aware of any case where landuse=industrial should not be mapped and rendering it as area like landuse=industrial would be a good idea, so I would prefer rejecting this idea.

**Comment by dieterdreist** [comment]
2018-02-25 13:13 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> I am not aware of any case where landuse=industrial should not be mapped
> and rendering it as area like landuse=industrial would be a good idea, so I
> would prefer rejecting this idea.
>

I don't believe it is a good idea to encourage people using "landuse" for
features. Usually, "landuse" is about the use of land, i.e. it is a
property and can be split or combined arbitrarily (as needed / suitable for
the combination with features) and would not get a name. If someone has
their villa on the site of a waste water plant (to give a stupid example,
more realistic cases are any kind of different landuse within the
facility), it should be possible to assign them a different landuse without
modifying the area of the plant.

**Comment by moermann** [comment]
WWTPs may get rendered the same like landuse=industrial, but they should not be tagged like this! Same applies for man_made=water_works.

Especially in North America the often contain huge surface reservoirs, which are clearly not industrial.

**Comment by HolgerJeromin** [comment]
> Especially in North America the often contain huge surface reservoirs, which are clearly not industrial.

Can you give us an example? osm object?

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Jun 2018, at 15:34, moermann <notifications@github.com> wrote:
> 
> Especially in North America the often contain huge surface reservoirs, which are clearly not industrial.


industrial is defined as production and storage, reservoirs would fit into this (I’m also reluctant to use industrial for these, but the discussion should be held elsewhere, not in the style issue tracker)
