### ISSUE TITLE
Add rendering for elevators

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#720]
Elevators should be rendered as icon.

See also https://trac.openstreetmap.org/ticket/3545.

**Comment by k1wiosm** [comment]
This would be nice. Any idea when will this be added?

**Comment by math1985** [comment]
The problem is that some elevators are very important (the public elevators in Lisbon and Luxembourg come to mind), but others are totally irrelevant for a general purpose map (elevators inside small offices for example). We currently have no way to distinguish them.

@k1wiosm Did you have any particular elevator in mind?

**Comment by k1wiosm** [comment]
I was thinking about a public elevator in this university (http://www.openstreetmap.org/#map=19/32.77629/-117.07330).

Definitely, only public elevators shoud be shown on the map. Are there really elevators inside small offices mapped on OSM?

**Comment by mkoniecz** [comment]
@k1wiosm Certainly some people will start mapping anything that is rendered. Includinh indoor elevators in any high building.

**Comment by pnorman** [comment]
I'm uncertain on this. Elevators would be more useful if we rendered elevation via hillshading and/or contour lines.

**Comment by kocio-pl** [comment]
Elevators are important on viaducts, subway/train stations or underground footway passages and other transportation-related places, even without other ground elevation context. I would be very happy to see them there as I draw a lot of footways and it's not always clear how are they linked between the levels.

But I don't know how to easily recognize which one elevator is important public amenity and which one is private or useful only in the building context. For example train station elevator is of course a not-that-interesting building feature to get to the x floor, but it works mainly as the important link between footway and the platform in a journey planning (be it with heavy luggage, on wheelchair or with a bicycle), so it is useful in a broader context than the building itself. 

I also remember people with physical disabilities needs them also in places like townhalls, shopping centers, so I tend to think it would be good to know they are there.

**Comment by RAytoun** [comment]
@kocio-pl You have raised an important strong case for showing elevators as a means for the physically disabled to plan their way through towns even if it includes shop and office elevators. By showing a visual difference to the rendered symbols it will highlight which elevators are a part of a route through the town and which are specific to a building.

**Comment by kocio-pl** [comment]
Maybe we need to sort them out by the access=* tag (just like we do for public/private parkings). I think all the public places and some semi-public (like shopping centers, which are open to the public even if privately-owned) should have the elevators visible.

**Comment by kocio-pl** [comment]
My proposition for elevator icon (10 px):
1) ![elevator-10-5](https://cloud.githubusercontent.com/assets/5439713/8397199/6f5503b6-1dc3-11e5-8638-a05924695847.png)

**Comment by mboeringa** [comment]
> My proposition for elevator icon (10 px):

Looks fine

**Comment by kocio-pl** [comment]
Field test shows it's too small, so I made a [12 px draft](https://github.com/gravitystorm/openstreetmap-carto/commit/4b54c26ba504cac7b99f8d6e5959b0f6d5f5bc49):
![elevator-12-z19](https://cloud.githubusercontent.com/assets/5439713/8397622/9f40d33e-1dd2-11e5-8bb3-e16cb2902424.png)
![elevator12-z19-tarasy](https://cloud.githubusercontent.com/assets/5439713/8397624/a4d6c0d8-1dd2-11e5-82cc-d08823b0cf1f.png)

Notes of the current state:

1. Icons are shown from z18 and name should be visible from z19, however I couldn't find elevator with name in Warsaw, so this is still not tested.

2. I'm still not sure if they should be maybe 14px, because there's so much visual distractions in the first example and I guess that may be the issue in many other places (footways with casing or other things in dense places).

3. Private part not implemented - I have to check how it's made in cases like parkings.

4. Generally I copy-pasted the bus stop styling and I'm even more overwhelmed with project.yaml than when dealing with shops. Let me know if something should be done different here or in  amenity-points.mss.

**Comment by mboeringa** [comment]
> Icons are shown from z18 and name should be visible from z19, however I couldn't find elevator with name in Warsaw, so this is still not tested.

I doubt you need to render any name labels for this feature, unless you intend to render any indoor elevator with its name / ref number also... In the rare case an elevator is a historic relic and tourism attraction, like the Santa Justa elevator in Lisbon Portugal (http://www.openstreetmap.org/way/115238861), it will have been tagged as such, and show up anyway.

**Comment by kocio-pl** [comment]
Sure, [fixed it](https://github.com/kocio-pl/openstreetmap-carto/commit/7ebe93b44665f9c9d585f6fef9ef234eb96deb6c), so at least 1. is clear now.

**Comment by kocio-pl** [comment]
Could somebody help me please - I don't quite get what is the problem with this syntax:

```yaml
  [feature = 'highway_elevator'][zoom >= 18] {
    [access = ''],
    [access = 'public'],
    [access = 'yes'] {
      marker-file: url('symbols/elevator-12.svg');
      marker-fill: @transportation-icon;
      marker-placement: interior;
    }
  }
```

I took these access values from a parking feature. I guess the problem is with [access = ''], which is probably essential, because most of public elevators won't have any access tag.

On the other hand private elevators are a minority, like [this one](http://www.openstreetmap.org/node/3059612121) in Berlin, so maybe we can not try to hide them.

**Comment by matkoniecz** [comment]
@kocio-pl What is happening? What you expected? What and how went wrong?

**Comment by kocio-pl** [comment]
When the code looks like this:

```yaml
  [feature = 'highway_elevator'][zoom >= 18] {
      marker-file: url('symbols/elevator-12.svg');
      marker-fill: @transportation-icon;
      marker-placement: interior;
  }
```

the elevator icon is visible within specified range (all elevators on z18+), but with the access restrictions added, it disappears completely.

**Comment by pnorman** [comment]
The problem is `[access = '']`. Checking for null has been annoying within carto, but I believe is now possible.

https://github.com/mapbox/carto/issues/75#issuecomment-11861115 indicates `[field=null]` works

mapbox/carto#227 is somewhat related, but not what you want here

**Comment by HolgerJeromin** [comment]
Access = public is imo only defined for toilets. All other features should use only the value  yes

**Comment by kocio-pl** [comment]
OK, PR is ready, thanks for all the help!

But both comments suggest this part of code meant for visually "hide" any non-public parking places is flawed:

```yaml
    [access != ''][access != 'public'][access != 'yes'] {
      marker-opacity: 0.33;
    }
```

and instead should look like:

```yaml
    [access != null][access != 'yes'] {
      marker-opacity: 0.33;
    }
```

Am I right?

**Comment by pnorman** [comment]
> But both comments suggest this part of code meant for visually "hide" any non-public parking places is flawed:
> 
> ```mss
    [access != ''][access != 'public'][access != 'yes'] {
      marker-opacity: 0.33;
    }
```
> 
> and instead should look like:
> 
> ```mss
    [access != null][access != 'yes'] {
      marker-opacity: 0.33;
    }
```
> 
> Am I right?

Maybe. For some layers (e.g. landuse), null is turned into '' in the SQL - see #1614 for details. This should be changed to check in mss.
