### ISSUE TITLE
Scale shield width more intelligently

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#726]
We currently based shield width off of `char_length(ref)`, statistics about the most common characters, and a day worth of staring at shields.

This is, obviously, not ideal. A much better solution would be to use the pixel width of the rendered text, but mapnik/mapnik#2020 prevents that. In spite of this, we really want some way to deal with varying shield text widths because there is some significant variation between ref pixel width at the same `char_length` when comparing refs from concurrent US interstates with lots of `;`, `I`, `` `, and`1`` characters and other refs (e.g. Mexico routes) with much wider characters.

A better solution would be to compute some relative string length in Postgres and use it to select a more appropriate shield.

IRC dump

```
02:30 < pnorman> I'm trying to hack around a limitation in the rendering software I'm using. I need the length of a string in pixels. Currently I'm using char_length(ref) and some statistics about the characters commonly used in ref at different lengths to get pixel sizes. Obviously I can't get an exact measure out of postgresql, but can anyone think of a measure that results in better results for ref's of 'llll' and 'MMMM'
02:32 < pnorman> I *suppose* I could split the string into characters, get a nasty CASE statement to convert them to something relative, and sum them back up
02:32 < Berge> pnorman: You hvae to do this in postgres, and not in the application?
02:32 < Berge> have, even
02:33 < peerce> string in pixels?  ummmmm.
02:33 < Berge> A string has no information about how it should be rendered.
02:35 < pnorman> Berge: yes, in postgres
02:36 < Berge> pnorman: You could write a function in plperl or something with specific information about the application's rendering of the strings.
02:36 < pnorman> Obviously I'm not going to be able to do this perfectly, but given that the existing deployed solution relies entirely on char_length to pick the appropriate background size, *anything* better is an improvement
02:36 < Berge> But it'd be a gross hack.
02:41 < RhodiumToad> set up a string of "narrow" and "wide" characters, assume everything else is in between, and use a combination of the three possible counts?
02:42 < RhodiumToad> the hack way would be something like this
02:45 < RhodiumToad> char_length(regexp_replace(regexp_replace(str, '([^l.,!])', '\1\1', 'g'), '([MmWw]{2})', 'm\1', 'g'))
02:45 < RhodiumToad> first [] is characters to consider "narrow", second is "wide"
02:47 < pnorman> RhodiumToad: That's what I was thinking about in essence, but your way is simpler than what I was looking at
```

I'm liking the regex replace solution over what I was thinking which was 

``` sql
SELECT 
    SUM(
      CASE rc 
        WHEN 'l' THEN 1
        WHEN 'M' THEN 3
        ELSE 2
      END)
  FROM (SELECT unnest(string_to_array(ref,NULL)) AS rc, ctid, ... FROM ...) AS ref_chars
  GROUP BY ctid;
```

The `unnest`/`GROUP BY` works, but is a bit annoying, particularly if there's any other GROUP BYs going on in the same query.

Thoughts?

**Comment by matkoniecz** [comment]
I am not sure is it really doable - such case statement should include not only ASCII but also characters from other alphabets - for example Japanase https://github.com/gravitystorm/openstreetmap-carto/issues/294#issuecomment-31812803

Or maybe "not in ASCII, therefore wide character" would work?

**Comment by pnorman** [comment]
Closing as good enough, and better would be really hard.

**Comment by pnorman** [comment]
It's worth noting that we're better than when I opened the issue originally since we split on ; so no one label is as wide anymore.
