### ISSUE TITLE
Add area rendering for historic=archaeological_site

### ISSUE THREAD

**Issue by sabas** [gravitystorm/openstreetmap-carto#732]
Currently (https://github.com/gravitystorm/openstreetmap-carto/blob/d40f6b919453ae69cbd91c17b7c002c83c2ff275/amenity-points.mss#L296) is rendered only as a point, but it's used also to mark areas (8939 occurrences as area and 220 as relation). Is it possible to add some color fill?
To make it show I saw being often used tourism=attraction

**Comment by mkoniecz** [comment]
Can you propose how it would be rendered?

**Comment by sabas** [comment]
A lighter version of the color used for important buildings?
Also a similar color could be applied to tourism=attraction. ( #1063 )

**Comment by mkoniecz** [comment]
It would make it confusing, it would look like a building.

**Comment by matkoniecz** [comment]
@sabas Where it would improve map? Can you give examples? Preferably - both screenshot and link to location on map.

I was unable to find places where it would not be solved by #1257

**Comment by sabas** [comment]
http://overpass-turbo.eu/s/b8y I tag a typical megalith of Sardinia island as an area when possible 
http://www.openstreetmap.org/way/146036992#map=17/40.06051/8.73277 (this is a well - hole in the ground with stairs) the enclosing site is http://www.openstreetmap.org/way/146021538 . The archaeological area could be tagged as an attraction possibly, but my doubt is, would #1257 force mapping tourism=attraction for each site? Or could be added in the rule [tourism=attraction],[historic=archaeological_site] ?

**Comment by matkoniecz** [comment]
> The archaeological area could be tagged as an attraction possibly, but my doubt is, would #1257 force mapping tourism=attraction for each site?

I am hoping that all or nearly all archaeological sites worth displaying as areas are worth displaying because these places are tourism attractions. In that case it would be enough to solve #1257 without inventing additional rendering.

**Comment by imagico** [comment]
Looking at a few world famous archaeological sites i have to say rendering the whole site in uniform color or with a boundary outline will not really improve that much:

http://www.openstreetmap.org/#map=16/27.3237/68.1332
http://www.openstreetmap.org/#map=18/35.29822/25.16244
http://www.openstreetmap.org/#map=17/39.95838/26.23999

Developing and establishing a good tagging system for archaeological remains would probably be a good idea but in general OSM mappers are more often outdoor and nature people than history buffs.

**Comment by polarbearing** [comment]
Another case for an outline.

**Comment by mboeringa** [comment]
> I am hoping that all or nearly all archaeological sites worth displaying as areas are worth displaying because these places are tourism attractions. In that case it would be enough to solve #1257 without inventing additional rendering.

I can assure you this is not always the case, because I render both **tourism=attraction** and **historic=archaeological_site** as boundary outlines. There are major historic hill forts and such tagged as **historic=archaeological_site**, but not necessarily as tourism attraction.

Reviewing and rendering hundreds of maps from all over the globe up to now using my renderer, this is quite clear.

*It is true though*, that if you actually want to limit the number of displayed archaeological sites to keep things manageable (which may not be a bad thing), then using the **tourism=attraction** as your sole means of displaying them, will probably weed out a lot of the lesser archaeological features. E.g. in England, I have seen dozens of underground mine shafts being tagged as **historic=archaeological_site**, where the only signs of such - mainly horizontal - shafts were their entrances and, surprisingly visible on aerial photos, vertical ventilation shafts dispersed along the length of the horizontal underground shafts.

> Another case for an outline.

\+1

**Comment by dan980** [comment]
This would be a great improvement in Italy, where archaeological sites are widespread. Some sites are pretty big, in this case the icon is misleading and does not give any information about the boundaries. Ironically, a cultivated field is much clearer.

**Comment by Tomasz-W** [comment]
I think giving archeological sites areas a fill or outline is a bad idea and may be confusing. In most cases they don't have a physical borders (it's often a grass areas with group of stones on it). If it's a building or a walls, it should be mapped additionally as a building or a walls, then it works propetly.

**Comment by kocio-pl** [comment]
I think we need colors/outlines for some more generic types of areas, so I would not focus on this. Maybe if we have some system for mainstream areas (like museum/culture) it might have sense to revive it and share the rendering, but for now it seems too specific, so I'm closing it now.

**Comment by SomeoneElseOSM** [comment]
> I think giving archeological sites areas a fill or outline is a bad idea and may be confusing

True (even without outlines).  When I added an area rendering for them elsewhere I eventually went with a very pale pink - see [here](https://map.atownsend.org.uk/maps/map/map.html#zoom=21&lat=53.2612251&lon=-1.202608) for an example (that's the western edge of [this](https://www.openstreetmap.org/way/123387963).  That said, some sort of area delineation makes sense, see for example [here](https://map.atownsend.org.uk/maps/map/map.html#zoom=19&lat=52.317245&lon=-7.587007).
