### ISSUE TITLE
Display both name and house number for houses that have both

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#735]
The Mapnik rendering layer should display both the name and the housenumber of buildings. Right now, the housenumber suppresses the display of the name. I think a smaller font than is usual for the name label would be appropriate.

See also https://trac.openstreetmap.org/ticket/2240.

**Comment by math1985** [comment]
* Do we want this?
* If so, is there any way to accomplish this?

**Comment by lest69** [comment]
It would be nice, but I'm not sure there's a way to do it without either hopelessly cluttering the map or having most of them not render due to conflicts between each other.

**Comment by balrog-kun** [comment]
With a little SQL conditional it should be well possible, you can append the house number after the name I guess.  I don't remember what method there was available in mapnik (if any) to change the font and font size midway through a label.

**Comment by balrog-kun** [comment]
Looks like https://github.com/mapnik/mapnik/wiki/TextSymbolizer#formats example does just that.

**Comment by pnorman** [comment]
If we want to do this SQL has the advantage that it would allow the housenumber and housename layers to be combined, and the disadvantage that we can't style it any differently.

**Comment by HolgerJeromin** [comment]
We have `addr:housename`, `addr:housenumber` and `name`. We should not confuse them :-)
This issue was about `addr:housenumber` and `name`. 
There is a JOSM Style that renderes both separated with a `|`. So a Walmart with Housenumber 4 is displayed as `4|Walmart`
Osmand renders `Wallmart (4)` in this case. Which is a little bit confusing, too.
