### ISSUE TITLE
House numbers nor names are rendered if long name is given

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#737]
The house number is not rendered for this building. I think (but don't know) the reason is as follows:

- name and addr:housenumber are given, so Mapnik chooses to render name
- name is too long to fit in the area of the building
- name is not rendered therefore

In this case Mapnik should choose to render the house number instead as it fits within the building's area and the name doesn't. Otherwise Mapnik should prefer the buildings name as it does on zoom=18 where the name fits within the building.
The described error only exists for zoom=17.

See also https://trac.openstreetmap.org/ticket/2127.

**Comment by math1985** [comment]
I think the reason for this is that the building in the original request has both an icon and a housenumber. I don't think we can or want to render both, so I will close this issue.

**Comment by mkoniecz** [comment]
In this case neither was displayed, as style decided to display name instead of number.
But name was too long and therefore it collided with other labels. Author of 2127 suggested to display house number in case like this, what seems to be a good idea.

**Comment by math1985** [comment]
> In this case neither was displayed, as style decided to display name instead of number.
But name was too long and therefore it collided with other labels.

I think in that case the current system still renders the house number? Do you have an example of this happening?

**Comment by lest69** [comment]
>>In this case neither was displayed, as style decided to display name instead of number.
>>But name was too long and therefore it collided with other labels.

>I think in that case the current system still renders the house number?

Yes it does. It took a bit of looking around to find an example, [but here's one](http://www.openstreetmap.org/way/223925762#map=19/48.45587/-123.49823). At z19, the name "The Back Nine" is rendered for all 9 houses. If you zoom out to z18, three of the names experience conflicts and the house number "2600" is rendered instead. Other similar occurrences can also be found just to the southwest at "Tara on Deville" and "The Deville".

**Comment by mkoniecz** [comment]
Thanks @lest69! So either original reporter was mistaken or this was fixed since reporting.
