### ISSUE TITLE
Country names not well-rendered in Mapnik

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#741]
In most parts of the world, country names (administrative boundaries of level 2) are not rendered with sufficient prominence to be clear to someone who does not already know the map, except at the lowest zoom levels (and sometimes not even then). Basically, the country name is only clearly the most prominent thing if there is nothing else labelled in the area, because so many other things are granted equivalent or greater typographical prominence.

For instance, see Central America (zoom=8). At that link and zoom level you'll see parts of Guatemala, Belize, El Salvador, and Honduras (maybe Nicaragua and Mexico depending on screen size). But unless you already know the map, it's not clear which is which because none of those names show up at all despite having many national administrative boundaries in-frame. Zoom out once, same story. Zoom out a second time (to zoom=6) and the country names are there, but unless you know them already and/or are intimately familiar with Mapnik rendering conventions, you won't see them; Belmopan (city) is much more prominent than Belize, and Tegucigalpa (also city) is much more prominent than Honduras, and all the country names blend in with the province names. One more level out and the country names are somewhat easier to pick out but are still significantly competing with the province names. In this area, it's not until you zoom out to zoom=4 that the country names are clear.

The situation is similar in many other parts of the world that have relatively small and/or well-mapped countries, including western Africa, most of South America, and all of Europe; in the Caribbean there are several countries where zoom=6 is the only level their names ever appear at.

I'll propose two fixes:

- the easy temporary fix: when they're rendered at all, render admin_level=2 names not only in non-italic but actually in a larger font size than currently (and possibly bolded as well).
- the harder but more important fix: choose whether to render the admin_level=2 names based not only on zoom level but also on the size of the administrative boundary (ideally enclosed area, but perimeter length or even number of nodes in the boundary might make a sufficiently reasonable proxy). Nobody needs to see "United States of America" rendered at anything further zoomed than zoom=5, probably, but St. Kitts and Nevis should probably have its name rendered all the way in to zoom=10 or 11. Certainly the country name should appear, and prominently, on the zoom=8 map of Central America that I linked above. 

See also https://trac.openstreetmap.org/ticket/4709

**Comment by matkoniecz** [comment]
> For instance, see Central America (zoom=8). At that link and zoom level you'll see parts of Guatemala, Belize, El Salvador, and Honduras (maybe Nicaragua and Mexico depending on screen size). But unless you already know the map, it's not clear which is which because none of those names show up at all despite having many national administrative boundaries in-frame.

fixed - see http://www.openstreetmap.org/#map=8/14.701/-88.434

> Zoom out once, same story. Zoom out a second time (to zoom=6) and the country names are there, but unless you know them already and/or are intimately familiar with Mapnik rendering conventions, you won't see them; Belmopan (city) is much more prominent than Belize, and Tegucigalpa (also city) is much more prominent than Honduras, and all the country names blend in with the province names. One more level out and the country names are somewhat easier to pick out but are still significantly competing with the province names. In this area, it's not until you zoom out to zoom=4 that the country names are clear.

also fixed

Overall, fixed in great #1989 by @nebulon42 (and maybe also earlier changes).

Low zoom still have problems but it should be covered in separate (maybe new) issues.
