### ISSUE TITLE
Add rendering for historic=castle

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#744]
Castles are important landmarks, so I think we should render them. See also https://trac.openstreetmap.org/ticket/2247.

**Comment by matkoniecz** [comment]
Note, I am no longer considering rendering it as a special building to be a good idea.

historic=castle tagging scheme is a poor tagging scheme and IMHO should not be supported.

**Comment by abdeldjalil09** [comment]
> Note, I am no longer considering rendering it as a special building to be a good idea.

How about castles tagged as nodes (11 016 uses) and castles without building=* (16 143) ?

**Comment by dieterdreist** [comment]
sent from a phone

> On 6 Jan 2017, at 03:23, aceman444 <notifications@github.com> wrote:
> 
> Because historic=castle may be the whole area of the fortification/palace grounds and is comprised of multiple buildings



+1, a medieval castle is usually composed of several buildings and often several rings of walls, even the small ones.

**Comment by kocio-pl** [comment]
[building=castle](http://taginfo.openstreetmap.org/tags/building=castle) would be of use, we can also render historic=castle+building=*, when the tagging is choosen. For castle area however or nodes we can find different rendering ideas.

School example:
- school on mode is currently rendered with a name with special color
- area tagged with amenity=school has special color and a name with special color
- building tagged with amenity=school is like any other buildings, but shows a name (I don't remember the color)

It doesn't mean it's how we want it to be in the future, it's just a starting point for further ideas for castle rendering.

**Comment by dieterdreist** [comment]
sent from a phone

> On 6 Jan 2017, at 23:37, kocio-pl <notifications@github.com> wrote:
> 
> For castle area however or nodes we can find different rendering ideas.


render a name from z15 and maybe an icon, z17

**Comment by kocio-pl** [comment]
This icon might be good as default symbol for a castle:
https://github.com/gmgeo/osmic/blob/master/tourism/castle-fortress-14.svg

I guess Tagging discussion is needed and Wiki changes for a start. This can take a long time before it'll be a standard of tagging, and we can use this time to design rendering strategy for all the cases (node, building, area), no matter what tagging scheme will be chosen in the end.

**Comment by wolfbert** [comment]
@dieterdreist +1

> render a name from z15 

Currently, `historic=castle` + `name=*` is not rendered, which causes mappers to put the `name` tag on the buildings instead of the castle grounds where it belongs. At the very least, give mappers the chance to map the grounds by rendering the name.

**Comment by jojo4u** [comment]
There is discussion about historic=castle tagging on german forum (https://forum.openstreetmap.org/viewtopic.php?id=57896). People agree that the tag as area means the whole ensemble. This would include the courtyards and even some modern-day additions like a kiosk. Buildings or ruins have to be tagged separately.

A technical question arised if there are no surroundings and the sole building is tagged as multipolygon because of a courtyard (example: https://www.openstreetmap.org/relation/22988). Is putting historic=castle on the outer way of the building multipolygon a good idea technically? Because multipolygon rules allow it but I'm unsure whether the new lua branch would support it.

**Comment by mboeringa** [comment]
> A technical question arised if there are no surroundings and the sole building is tagged as multipolygon because of a courtyard (example: https://www.openstreetmap.org/relation/22988). Is putting historic=castle on the outer way of the building multipolygon a good idea technically?

I see little reason to change the tagging in your example, and no need to add the **historic=castle** tag to the outer of the MP. Everybody understands the courtyard of the castle belongs to the castle in this example.

I would certainly be undesirable to add both **historic=castle** and **building=yes** on the outer as well as the MP. Depending on the renderer, you would end up with two buildings stacked on top of each other, with the building derived from the outer blocking the view of the inner court, as it won't have one.

**Comment by jojo4u** [comment]
For me it's not about understanding but good tagging. Currently the courtyard is excluded from the castle area. 

>It would certainly be undesirable to add both historic=castle and building=yes on the outer as well as the MP. 

The building tag would stay on the MP.

The

**Comment by mboeringa** [comment]
> For me it's not about understanding but good tagging. Currently the courtyard is excluded from the castle area.

This is just one interpretation, I don't think you can really say that either way is good or bad in this particular example, or that people would not generally understand the courtyard is not part of the castle.

Undoubtedly, this has been discussed at length in the German forums, but unless you are planning to calculate metrics on castle sizes including courtyards, I still see very little reason this tagging would need changing.

As to a specific argument in favor of maintaining the current tagging: if some style would like to emphasize castle _buildings_ by use of a specific color instead of using a "castle" POI, only putting the tag on the outer would not allow this or at least make it much more elaborate to accomplish.

I am not saying that your suggestion is bad here, I just want to illustrate with the above example that either way has consequences for the potential cartography. It is up to you to make the choice for the tagging, and than accept the possible outcome of the cartography in your favorite OpenStreetMap style.

**Comment by jojo4u** [comment]
Castle _buildings_ undoubtedly need further tagging development. For example by documenting building=castle mentioned above with already 1400 uses.

**Comment by wolfbert** [comment]
@mboeringa 

> but unless you are planning to calculate metrics on castle sizes including courtyards

That's exactely the point. Every database object must make sense when queried individually. I.e. when someone asks for castle areas (to draw a map, calculate average area, or whatever), the object returned must represent that part of observable reality - the castle area doen't have a hole. Same by the way with schools, where the school yard gets excluded from the school grounds.

As for putting the tag on the outer ring, I don't like it either, but it saves a duplicate polygon and it is valid according to joto. This only occurs for single, stand-alone buildings without surroundings.

**Comment by mboeringa** [comment]
> That's exactely the point. **_Every database object must make sense when queried individually._** I.e. when someone asks for castle areas (to draw a map, calculate average area, or whatever), the object returned must represent that part of observable reality - the castle area doesn't have a hole.

This is still only one possible interpretation / definition. I also think that, while I applaud consistent tagging and concise Wiki definitions of real world objects in OSM, I think with the current state of OSM, your ambitions as voiced in the bold quote are sky high. There is still a massive amount of inconsistencies all over the OSM database and Wiki.

Based on the experience of developing my own renderer, I also know that the number of possible - _and often totally unexpected_ - exceptions to certain Wike "rules" is just enormous. There is always an edge case defying a certain rule.

Again: I am not against your tagging suggestion. _Go ahead and tag it like that if you want to!_ It is OSM after all. I am just saying there are a lot more nuances to all of this than many people think.

**Comment by a3nm** [comment]
Regarding this issue, here is an example of a castle which is currently not rendered at all http://www.openstreetmap.org/way/211046305. The "castle" is a kind of open area with ruins; currently only the individual buildings inside the castle area are rendered, which is a bit confusing.

**Comment by mboeringa** [comment]
> Regarding this issue, here is an example of a castle which is currently not rendered at all http://www.openstreetmap.org/way/211046305. The "castle" is a kind of open area with ruins; currently only the individual buildings inside the castle area are rendered, which is a bit confusing.

I assume the outline drawn represents either a reinforced wall, or embankment or so? If so, you can use a couple of things to make it visible:

- Use **[historic=citywalls](http://wiki.openstreetmap.org/wiki/Tag:historic%3Dcitywalls)** or the equivalent **barrier=city_wall** (there is also **[wall=castle_wall](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwall)**, but I don't think that one is rendered yet by Carto)
- Use **[barrier=wall](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dwall)** or **[barrier=retaining_wall](http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dretaining_wall)** (if the wall is holding back higher ground)
- Use **[man_made=embankment](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dembankment)** if the feature is on higher ground like an embankment, but no walls are there

All of these are rendered if I am right.

**Comment by a3nm** [comment]
Thanks for the explanations! I don't think there are walls, so
man_made=embankment looks like the best choice. I added it, but it
doesn't appear to render, though. :/

-- 
Antoine Amarilli

**Comment by mboeringa** [comment]
> Thanks for the explanations! I don't think there are walls, so man_made=embankment looks like the best choice. I added it, but it doesn't appear to render, though. :/

It will if you don't use the tag on a closed way. Yes, I understand this is not what is expected. But if you draw a separate way unclosed, it will show up. And of course, the castle complex has an entrance, so that would be a suitable place to start drawing.

Looking at the imagery in iD, I do also think it likely a barrier=retaining_wall tag would be suitable. It seems enclosed by one. Likely, this also only renders as an unclosed way.

**Comment by dieterdreist** [comment]
sent from a phone

> On 17. Apr 2017, at 19:54, mboeringa <notifications@github.com> wrote:
> 
> I assume the outline drawn represents either a reinforced wall, or embankment or so? If so, you can use a couple of things to make it visible


yes, but this will only render those objects, not the castle or castle ruins (name!)

**Comment by a3nm** [comment]
Thanks for explaining! I fixed things following what you suggested, and
now at least the embankement renders. This isn't perfect (what is inside
still appears as a forest) but it's better than nothing.

Thanks again!

Best,

-- 
Antoine Amarilli

**Comment by mboeringa** [comment]
> I fixed things following what you suggested, and now at least the embankement renders.

OK, great that this helped you out. Of course, the topic about adding rendering for castles is still open and may see future changes.

**Comment by hubgitti** [comment]
According to the OSM Wiki, the outline of a castle should be mapped as historic=castle, having the name and other taggings on it:
https://wiki.openstreetmap.org/wiki/Tag:historic%3Dcastle#How_to_map
https://wiki.openstreetmap.org/wiki/DE:Tag:historic=castle#Wie_mappen.3F

When doing so, nothing is rendered on openstreetmap.org. To my opinion the current situation is unacceptable.

**Comment by kocio-pl** [comment]
Would you like to try preparing the code or move this idea forward in some other way? I don't think it's gonna be done if nobody will step up to do it. It sounds like a strong motivation for me that you can't accept current state of things.

We should decide which type needs rendering (we're finally ready to select subtypes) and in which way (icons, minimum zoom level etc). Some icons that might be helpful are here:

https://github.com/gmgeo/osmic

**Comment by SomeoneElseOSM** [comment]
Just to chuck in another rendering option, here's what I went for for various "historic" areas in another map style:

https://map.atownsend.org.uk/maps/map/map.html#zoom=18&lat=53.007133&lon=-0.624572

(that's https://www.openstreetmap.org/way/371069082 in OSM BTW)

**Comment by hubgitti** [comment]
I would suggest to have the name and an icon at the castle node or area. I think no extra colouring or other fancy stuff is needed. I'm not a developer, so I cannot contribute here, sorry. I mapped a few castles at OSM, I "repaired" some of them: I turned single castles mapped as multiple ones (tagging for the renderer because name of buildings are shown?) into single ones by using a surrounding extra way - as described in the wiki. With the result: They are lost on openstreetmap.org now.

What would you suggest here, how could I contribute to get castles rendered?

And yes, to my opinion, the situation _is unacceptable_! I'm not saying that in an angry way, it is just like I think the current situation is.

**Comment by kocio-pl** [comment]
Sure, it's OK that you say what you need. It would just help if you be more precise - which castle type with which icon from which zoom level?

**Comment by dieterdreist** [comment]
2018-01-30 7:55 GMT+01:00 kocio-pl <notifications@github.com>:

> Sure, it's OK that you say what you need. It would just help if you be
> more precise - which castle type with which icon from which zoom level?
>


I would render the name label for every castle_type, z17+
The more prominent ones from z15 with icon and z16 with additional label.
Loooking at taginfo, the values for the second category can be these:
stately
defensive
fortress
palace
kremlin
defensive;stately
castrum
shiro
citadel
fortification
chateau
water_castle

**Comment by kocio-pl** [comment]
We still need more specific decisions to prepare the code.

> The more prominent ones from z15 with icon and z16 with additional label.

How would we select these (which tag or set of tags for example)?

> Loooking at taginfo, the values for the second category can be these:

Tags are not the problem, the icons are. So - which icons would we use and which types would they depict (of course there might be more types depicted by the same icon, just like we do with some shops for example)?

**Comment by hubgitti** [comment]
I saw that currently many things are rendered starting with z16, so I would  also use z16 for the castles. To my opinion there is no need to have dependencies on the "importance" of the castles.

I was looking at the icons also, but I have the impression that they all look quite "European". I was trying to draw a new one using "inkscape", I'll continue trying during the weekend.

**Comment by hubgitti** [comment]
I tried some icons, they don't look so different to the ones as your examples provided in https://github.com/gmgeo/osmic (mine are  a little more ugly :-) )

I would suggest row 10, colum 10, the one with the "mixed roofs" on the two towers. The mixed roofs "soften" the icon a little to make it more compatible to the different versions of castles.

I checked the web for fortified buildings, they don't look so dramatically different on the globe.

**Comment by kocio-pl** [comment]
So you suggest to use just one icon for all the types? I guess we can use more of them to show their slightly  different meaning.

**Comment by kocio-pl** [comment]
Initial proposition:

https://github.com/gmgeo/osmic/blob/master/tourism/castle-defensive-14.svg
generic castle:
- no subtype

https://github.com/gmgeo/osmic/blob/master/tourism/castle-fortress-14.svg
fortified castle:
- castle_type | defensive
- castle_type | fortress
- castle_type | castrum
- castle_type | shiro
- castle_type | kremlin

https://github.com/gmgeo/osmic/blob/master/tourism/castle-manor-14.svg
manor house (châteaux)
- castle_type | manor

https://github.com/gmgeo/osmic/blob/master/tourism/castle-stately-14.svg
stately home
- castle_type | stately

https://github.com/gmgeo/osmic/blob/master/tourism/castle-palace-14.svg
palace
- castle_type | palace

Notes:
1. `castle-defensive-14.svg` is great to show ambiguity, just like two trees in the forest, but maybe  `castle_type=defensive` could be shown this way too.
2. Palace icon is oriental, we could use stately icon instead, as it's more neutral and maybe there's no need to differentiate these types. I guess also manor doesn't need special icon and should be depicted by the same icon.
3. In my city there's a lot of palaces ("A palace is a grand prestigious residence of aristocracy, mostly built in a town or city."), but they are sometimes indistinguishable from other houses, just more elegant, so it might be overwhelming.

What do you think?

**Comment by Tomasz-W** [comment]
* Manor icon doesn't reminds me manor at all
* Palace icon looks more like a mosque
* Rest of icons are good

**Comment by hubgitti** [comment]
I would suggest to use just one icon. After the renderer will display castles, things can be refined in later versions. Hopefully some castle experts will contribute after the first most simple version will appear on openstreetmap.org

I updated the german wiki:
https://wiki.openstreetmap.org/wiki/DE:Tag:historic=castle#Wie_mappen.3F

to explain the tagging in greater detail.

I also went through this thread again:
https://forum.openstreetmap.org/viewtopic.php?id=57896

**Comment by Tomasz-W** [comment]
My icon proposals:
* Manor
![historic manor2](https://user-images.githubusercontent.com/25656654/35778393-f5284a28-09bd-11e8-822b-69eeeb945eca.png)
14x14: ![historic manor](https://user-images.githubusercontent.com/25656654/35778395-fccd8c98-09bd-11e8-9711-58f47f5c402f.png)

* Palace
![historic palace2](https://user-images.githubusercontent.com/25656654/35778397-06b4cef6-09be-11e8-953d-99499a97708f.png)
14x14: ![historic palace](https://user-images.githubusercontent.com/25656654/35778401-0efaf932-09be-11e8-9f7d-c04cc24fe6ab.png)

**Comment by kocio-pl** [comment]
Manor icon is interesting, but just doesn't work for me at 14 px and a palace icon doesn't work for me at all.

**Comment by Tomasz-W** [comment]
@kocio-pl I unterstand. I'm putting Gist, in case of someone want to tune up this icons.
https://gist.github.com/Tomasz-W/16c57c0722b36d2302012b1a724a7a47
https://gist.github.com/Tomasz-W/b73795cc1421919591ba221b33c1454a

**Comment by hubgitti** [comment]
Did you also have a look here?:
https://wiki.openstreetmap.org/wiki/Key:castle_type

**Comment by Tomasz-W** [comment]
Another try for palace - windows instead of columns:
![historic palace okna 2](https://user-images.githubusercontent.com/25656654/35801617-474bdaa4-0a6d-11e8-8bc6-3ab1bbebde5b.png)

![historic palace okna](https://user-images.githubusercontent.com/25656654/35801616-47337216-0a6d-11e8-8491-3e031f099202.png)

**Comment by kocio-pl** [comment]
Better on z14 than scaled up version, but still not too clear for me. 

BTW: do you try to align the lines with the pixel matrix?

**Comment by polarbearing** [comment]
There is some discussion on [talk-de](https://lists.openstreetmap.org/pipermail/talk-de/2018-March/114673.html) that the less-used historic=fort was merged before the more-used historic=castle was ready. There is fear that this might lead to retagging for the renderer. 

Consequently, this issue here should be accelerated, maybe with an interim solution.

**Comment by kocio-pl** [comment]
I see. I think this is quite close to being ready (I have some new ideas to test soon, but it's just about tuning visual differences in Osmic shapes), so I wouldn't worry about that.

**Comment by Tomasz-W** [comment]
* next palace/ stately icon proposal (includes gate and 3-part roof)
![historic palace okna](https://user-images.githubusercontent.com/25656654/36933736-98412cfe-1ede-11e8-969f-81df4c9d0b6c.png)
* manor icon tuned up a little bit
![historic manor](https://user-images.githubusercontent.com/25656654/36933814-95728a80-1edf-11e8-95b2-e5226b9016d0.png)

**Comment by kocio-pl** [comment]
I like this version of manor shape and I'd like to test how it looks on the map. 

Palace/stately icon is good in general, but I get lost with readability details like windows and connected roofs - I'm struggling to recognize it as a building.

**Comment by polarbearing** [comment]
+1 manor shape

**Comment by Tomasz-W** [comment]
Gist links:
* manor (-> it should be used also for `historic=manor` - this tag is allowed by OSM Wiki, and it has 3,9k uses)
https://gist.github.com/Tomasz-W/7950f86fef9c57e41cd125b2b70f5edd
* palace/ stately (I've made windows bigger and roofs sharper)
![historic palace okna](https://user-images.githubusercontent.com/25656654/36937289-6e0e4dbc-1f11-11e8-83f0-7b036b550923.png)
https://gist.github.com/Tomasz-W/25c553437720cd4181264f9b54ea4382

**Comment by MaestroGlanz** [comment]
+1 manor

**Comment by playerEric1** [comment]
Can different icons for different castle types be added?
