### ISSUE TITLE
Add rendering for amenity=marketplace

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#751]
It would be nice to get rendering for “amenity=marketplace” with an icon and its name.

Some facts:

– 22 827 objects with “amenity=marketplace” in the database

– Wiki says to use it only an areas, not on nodes. But taginfo say that nearly 50% of the usage is on nodes (and the other 50% on areas).

– Is often used together with “building=yes” (20% of total usage) and “landuse=retail” (10% of total usage)

**Comment by kocio-pl** [comment]
I think if it's a regular market place, it doesn't have any other important objects which could be in conflict, so the exact opening times should be tagged with opening hours tag, like we do with shops - this is a social agreement to expect it to be working/present in some days/hours/times and not in the others, but the most important thing is where they are located.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 22.08.2015 um 17:32 schrieb kocio-pl <notifications@github.com>:
> 
> I think if it's a regular market place, it doesn't have any other important objects which could be in conflict, so the exact opening times should be tagged with opening hours tag, like we do with shops


there are both cases: markets that close (no access, shops closed) and markets which are typically public squares and open all the time but where the shops/booths close
or leave.
On the marketplace object I'd use opening hours only in the first case, otherwise service_times might be more appropriate. For individual stands / shops we would still tag opening hours as usual.

cheers 
Martin

**Comment by abdeldjalil09** [comment]
Still no change ?

**Comment by kocio-pl** [comment]
As far as I can see, the discussion reached no conclusion yet. Any ideas how to get there?

**Comment by abdeldjalil09** [comment]
Maps.me has this icon : 
https://github.com/mapsme/omim/blob/e646b270bd68d0c27adac5ed712682cf1500b68c/data/styles/clear/style-night/symbols/marketplace-l.svg

**Comment by sommerluk** [comment]
Rendering could be with an icon and name for both, points and areas. And for areas additionally same area rendering like for retail.

The icon could look like one of these:

2:
![screenshot 2](https://user-images.githubusercontent.com/6830724/31151344-95a01308-a886-11e7-88c2-af71cab9ccf2.png)
This one is maybe nicer.

3:
![screenshot 3](https://user-images.githubusercontent.com/6830724/31151345-95ae5da0-a886-11e7-91ba-4de6ebd455bd.png)
This one works maybe better when there is noise in the background.

Amenity colour or shop colour?

**Comment by kocio-pl** [comment]
I guess 2 (the solid one) fits better our icon style. Shop color should be more informative, since we use brown for many different things.

**Comment by sommerluk** [comment]
Some more icon versions:

4:
![m4](https://user-images.githubusercontent.com/6830724/31312421-2fc40aba-abb2-11e7-8d26-a8afd19ef73d.png)

5:
![m5](https://user-images.githubusercontent.com/6830724/31312423-34938a98-abb2-11e7-83ff-76b12066ddaf.png)

I tend to use number 5 it is both
- solid
- closed shape that works well on noisy background

About zoom level: Supermarket starts at z16 with its own icon, most other shops start at z17 with a dot, and at z18 with their own icons. I tend to start with marketplace also at z17, but directly with the icon.

**Comment by kocio-pl** [comment]
Interesting place to test: http://www.openstreetmap.org/way/27303588

**Comment by sommerluk** [comment]
![screenshot 14](https://user-images.githubusercontent.com/6830724/31582291-2d60750c-b16f-11e7-8b0f-652b50c04067.png)
![screenshot 15](https://user-images.githubusercontent.com/6830724/31582292-2dbd7c70-b16f-11e7-8ff6-3f0158d72669.png)
![screenshot 16](https://user-images.githubusercontent.com/6830724/31582293-2e03593e-b16f-11e7-9e05-814a38147c04.png)
![screenshot 17](https://user-images.githubusercontent.com/6830724/31582294-2e510198-b16f-11e7-80bf-4b65888bf271.png)
![screenshot 18](https://user-images.githubusercontent.com/6830724/31582295-2e9a7f26-b16f-11e7-94fa-05a8976ceee2.png)
![screenshot 19](https://user-images.githubusercontent.com/6830724/31582296-2ee2f9a4-b16f-11e7-8390-4d83e137d15c.png)

**Comment by math1985** [comment]
The wiki says: `The traditional market square is a city square where traders set up stalls and buyers browse the merchandise.`

I suppose that includes nearly all market squares that have a weekly market. Do we really want to render them all?

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Oct 2017, at 14:09, Matthijs Melissen <notifications@github.com> wrote:
> 
> I suppose that includes nearly all market squares that have a weekly market. Do we really want to render them all?


why not, they are usually very significant for the settlement

**Comment by kocio-pl** [comment]
> I suppose that includes market squares that have a weekly market but without fixed amenities. That includes market squares in most European cities. Do we really want to render them all?

My local experience is that most of the time this is only their historical role. Today they tend to be just regular city square with shops around, not booths inside.

**Comment by sommerluk** [comment]
I would say that these cases should _not be tagged_ with `amenity=marketplace`.

In West Africa, this tagging refers normally to a real marketplace currently in usage. It exists also in almost all bigger towns, aside of supermarkets. And in most villages, it is even the only place where you can buy food, so it’s often at a central place in the village and an important place for the life of the village.
