### ISSUE TITLE
Add rendering for historic=monument

### ISSUE THREAD

**Issue by mrwojo** [gravitystorm/openstreetmap-carto#758]
An icon and name should do (as with its cousin historic=memorial). There's already a CC0 icon for it at http://www.sjjb.co.uk/mapicons/ which is the icon osm.org's browse page uses for this tag.

historic=monument has about 30k uses.

This may reveal some latent weirdness in tagging... like how every stone in Stonehenge is marked historic=monument.

**Comment by nebulon42** [comment]
I can offer this ([nebulon42/osmic/monument-16.svg](https://github.com/nebulon42/osmic/blob/master/tourism/monument-16.svg)) as icon if it is decided to be rendered.

**Comment by kocio-pl** [comment]
I like this icon - of course I wait for a subtags support (wall-mounted memorial is very different from a big memorial monument - see the examples of its variety: https://en.wikipedia.org/wiki/Memorial#Examples_of_notable_memorials ), but we need it for many landmarks.

**Comment by kocio-pl** [comment]
@nebulon42: Whatever happened to this icon? Long time no hear... =}

**Comment by nebulon42** [comment]
I never intended to do a PR here, because first it has to be clear if it should be rendered or not and I'd like to avoid another #1304 where in the PR discussion it became clear that there is no support for additional rendering. The icon is available, feel free to use it.

**Comment by kocio-pl** [comment]
Hm, because historic=monument looks like designed especially for buildings, which are visible on the map anyway (even with the name), this icon is optional, but I think it would do no harm. Probably we need a visual before/after test to know.
