### ISSUE TITLE
Add rendering for amenity=clinic

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#763]
Jóhannes Birgir Jensson reports on the talk mailinglist:

"Also worrying that amenity=clinic still isn't displayed with the cross like pharmacy and others, in many rural places this is the only healthcare around.
http://www.openstreetmap.org/node/2303511227"

**Comment by kocio-pl** [comment]
Let it be like this - or maybe the same as the hospital or the same as the amenity=doctors? I'm not sure what are key difference between such objects and having the clinics visible is probably even more important than rendering "doctors".

**Comment by Stalfur** [comment]
Amenity=doctors is now rendered. As most clinics have doctors (but not all) it seems like a easy and acceptable solution

**Comment by kocio-pl** [comment]
So what icon shape do we choose:
1. Hospital cross without the circle.
2. Doctors bag.
3. hospital cross (maybe the same as in hospital)?

According to english Wikipedia clinic may be small local facility, but "[s]ome clinics grow to be institutions as large as major hospitals, or become associated with a hospital or medical school, while retaining the name 'clinic.'"
[ https://en.wikipedia.org/wiki/Clinic ]

So this can be different objects in reality (small/medium/large, independent/part of hospital), hence the difficulty with finding the right symbol.

**Comment by Stalfur** [comment]
I for one would like to see 1. Hospital ross without circle

In my area the clinic has general doctors (who refer cases onwards to specialists if needed) and nurses, while also being responsible for infant checkups and inoculation. I would only go to a hospital for a major thing.

I believe the same situation is in other less developed areas where access to a hospital is even more ardous.

**Comment by kocio-pl** [comment]
I still have no clear preference for symbol, but I think that it should be rendered form z>=16 (simply because hospital is z>=15 and doctors is z>=17).

**Comment by kocio-pl** [comment]
I made the simple cross icon at last (baby steps with Inkscape), but I don't know how should I publish it now, because GitHub doesn't accept SVG ("Unfortunately, we don't support that file type. Try again with a PNG, GIF, or JPG."). What should I do now?

**Comment by matkoniecz** [comment]
Are you trying to edit repository using online editor? 

I would recommend using git client (for starting with git I used https://try.github.io/levels/1/challenges/1 and http://git-scm.com/book/en/v1/Getting-Started )

But it is possible to add SVG file using online editor.

I [did](https://github.com/matkoniecz/svg_test/tree/master) this by creating a new file named test.svg and copying svg gile contents there (it is just text).

**Comment by kocio-pl** [comment]
Thanks! Git is my tool of the month to learn (also for work) and I will read both git getting started guides anyway to understand it better, but is there a simple path to update my personal fork ( https://github.com/kocio-pl/openstreetmap-carto ) to latest osm-carto version and work with it? 

I made this fork exactly for creating my own osm-carto patches, just because one of the guides told me to do so, but I stuck at rendering too big data set. Now I'm trying to resume this and playing with icons is additional reason to.

**Comment by kocio-pl** [comment]
That's what it is =} :

https://github.com/kocio-pl/openstreetmap-carto/blob/master/symbols/clinic.16.svg

**Comment by matkoniecz** [comment]
@kocio-pl One small thing for future: it is better to make new branches for new features. This way it is possible to work on more than one thing at the time (for example - more than one pull requests at the same time). It also makes much easier to update your fork.

> we need some simple, task-oriented guides and tools for a start.

Yes, it would be great to have something like that.

**Comment by pnorman** [comment]
https://guides.github.com/introduction/flow/ is a reasonable introduction to the github workflow we approximately use

**Comment by kocio-pl** [comment]
Here is my PR regarding rendering icon and the area tagged as amenity=clinic:

https://github.com/gravitystorm/openstreetmap-carto/pull/1474

As I said, I think this icon should be seen from z>=16, otherwise it's just like the hospital.

**Comment by kocio-pl** [comment]
Once I got deeper into OSM icon designing, I have another idea - nothing very surprising, but I'm pretty sure it's better than a cross without a circle: ![clinic-14-3](https://cloud.githubusercontent.com/assets/5439713/7508322/d1257e54-f47e-11e4-8630-04f945a63d10.png) - what do you think about it?
