### ISSUE TITLE
Add rendering for amenity=townhall

### ISSUE THREAD

**Issue by skorasaurus** [gravitystorm/openstreetmap-carto#77]
It'd be nice to see [amenity=townhall](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtownhall) rendered and it is important enough that it should be included in the default map. (likely at a z17,z18 zoom). 

It's an active tag, used 45,000+ times, and a relatively uncontroversial tag. 

Not sure if I'll have time to get around to proposal a style for it in a pull req, but a note to self just in case. 

If you need an icon for the node objects of it, you could use the one found in [HDM-cartoCSS](https://github.com/hotosm/HDM-CartoCSS/tree/master/icons) (the svg for the icon is within the _maki.svg)

**Comment by math1985** [comment]
@nebulon42 Do you have any suggestion for an icon? SJJB has http://www.sjjb.co.uk/mapicons/png/amenity_town_hall.p.16.png, which is not very clear.

**Comment by nebulon42** [comment]
I will look into it. (cross-ref https://github.com/nebulon42/osmic/issues/5)

**Comment by kocio-pl** [comment]
Maybe a house icon with a simple clock tower?

**Comment by nebulon42** [comment]
There is now a first version of town hall ([town-hall-16.svg](https://github.com/nebulon42/osmic/blob/master/administration/town-hall-16.svg)) alongside with an icon for government facilities ([government-16.svg](https://github.com/nebulon42/osmic/blob/master/administration/government-16.svg)).

town hall: ![town-hall-16](https://cloud.githubusercontent.com/assets/3531092/5816806/01890436-a0a5-11e4-8cad-31f72166e5fb.png)
government: ![government-16](https://cloud.githubusercontent.com/assets/3531092/5816810/07d0a5ec-a0a5-11e4-80a2-3c6359af42b0.png)

**Comment by kocio-pl** [comment]
Nice and consistent - the flag is clear enough symbol for me.
