### ISSUE TITLE
Add rendering for hotel areas

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#775]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/3179):

http://www.openstreetmap.org/?lat=28.38634&lon=-81.50292&zoom=17&layers=M Here the hotels are not rendered as areas, while the landuse areas are. Perhaps a grayish pink (cross between residential and commercial) would be best.

**Comment by matkoniecz** [comment]
> I'm also skeptical if there's room in the colour space for a new colour.

I am pretty sure that additional color at high zoom is a bad idea.

Also - for small hotels there would not be any benefit, large complexes would be anyway tagged with already rendered landuse=commercial.

I recommend rejecting this proposal.

**Comment by polarbearing** [comment]
Outline would be useful, also for other touristic features, see summary in #1624.

**Comment by kocio-pl** [comment]
I guess we're out of colors for areas (and we should probably also rethink some already used - for example: what the hospital and school have in common, which social facility like orphanage does not have?). 

Borders are the only hope for now, however it'd be good to think beforehand about the system for colors/styles. We can combine them with some icons (hotel already has it's own) to have more precise information - border style and color would be for more general categories, so we wouldn't need too much of them.

**Comment by DaveF63** [comment]
There are plenty more hues. There was a website (can't find a link atm) that showed how slight changes in colour appearance were easily delectable by the human eye. 

>I am pretty sure that additional color at high zoom is a bad idea.
I'm unsure why it's a bad idea. Hospitals & schools etc are rendered why stop there?  Why not add entities such as hotels & pubs? How will it harm the rendering?

**Comment by matkoniecz** [comment]
I fixed inconsistent widths at z10 and z11 and tweaked glow. master will be merged in after new release that should happen soon so it may be preferable to wait with updating test server.

**Comment by polarbearing** [comment]
> plenty more hues ... easily delectable by the human eye

While you might be able to see the difference between hue A and B when you contrast them, it is a different issue to recognise one when you don't see the other. 

> border style and color would be for more general categories

Yes. Accommodation-blue, tourism-brown, educational-social-medical-yellow.

**Comment by kocio-pl** [comment]
What about embassy area [like this](http://www.openstreetmap.org/way/212337223)?

**Comment by polarbearing** [comment]
Embassy would be another case for an outline. Question is whether it has currently the correct colour, would amenity-brown be a better fit for embassy than transportation-blue? Updated table in #1624.

**Comment by dieterdreist** [comment]
2015-08-31 13:49 GMT+02:00 polarbearing <notifications@github.com>:

> Embassy would be another case for an outline. Question is whether it has
> currently the correct colour, would amenity-brown be a better fit for
> embassy than transportation-blue? Updated table in #1624
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1624>.
>


maybe something in administrative boundary color?

**Comment by matkoniecz** [comment]
>>   I am pretty sure that additional color at high zoom is a bad idea.

> I'm unsure why it's a bad idea. Hospitals & schools etc are rendered. Why stop there? Why not add entities such as hotels & pubs? How will it harm the rendering?

Because it is impossible to display everything. Even JOSM editing style is not displaying all tags. At this moment this style so many things that unifying display or even removing features results in greater improvement than adding more features.

> There are plenty more hues. There was a website (can't find a link atm) that showed how slight changes in colour appearance were easily delectable by the human eye.

Map should be readable. Using various brown-yellow colours for hospitals, schools, hotels, pubs etc and expecting people to be able to recognize this features would not result in a readable map.



At this moment we should stop. Rendering all areas (hotels, embassies, police stations, biergartens, restaurants, etc etc) - by outline or area rendering is simply impossible (assuming that one want map that is prettier than JOSM editing style).

**Comment by crse** [comment]
This issue is still relevant, as some hotels might have tons of buildings, and a single node does not give a clear picture a full scale of hotel facility.
