### ISSUE TITLE
Render tourism=zoo as half transparent overlay

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#778]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/3962):

Rendering tourism=zoo as half transparent "overlay" (like nature reserves are rendered currently) would be better. Currently landuse and nature areas are drawn over zoo area and in places where the entire zoo area is covered with landuse/natural areas there is no way to say that this area is a zoo area.

Example (not jet covered fully with landuse tags but the area covered with forest shows the problem): http://www.openstreetmap.org/?lat=59.42285&lon=24.66418&zoom=15&layers=M

**Comment by pnorman** [comment]
![image](https://cloud.githubusercontent.com/assets/1190866/7672103/15c0fc22-fc9b-11e4-8893-f2db66d6fa55.png)
![image](https://cloud.githubusercontent.com/assets/1190866/7672098/02cfb162-fc9b-11e4-89cc-e3034fa47be6.png)

Overall happy with the improvements
