### ISSUE TITLE
Incorrect labelling of multipolygon relation

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#779]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/4099):

Someone seems to be rather over-enthusiastically grouping together all the residential areas in Cambridge into multipolygon relations. I'm not convinced this is helpful. However, there is a rendering artefact which makes this particularly unpleasant. The name of one of (the many) outer elements is being picked up and rendered widely across the whole of the area which the relation covers (possibly it is in the middle of any anonymous outers which are also part of the relation, not sure).

The name chosen seems to be pretty random. It comes from this small way, "The Orangery".

http://www.openstreetmap.org/browse/way/43491617

You can then see this insignificant "The Orangery" caption rendered repeatedly all over Cambridge where it is completely irrelevant. For example:

http://www.openstreetmap.org/?lat=52.197111&lon=0.103013&zoom=18&layers=M

and

http://www.openstreetmap.org/?lat=52.190617&lon=0.129325&zoom=18&layers=M

It doesn't seem right to render the name of one element of a multipolygon relation arbitrarily on others.

I think the relation concerned is this one: http://www.openstreetmap.org/browse/relation/1823059 but it could be this one, I'm not certain: http://www.openstreetmap.org/browse/relation/1825599

I will contact the author directly about the undesirability of this relation in principle, but I think the way the name is being rendered is a bug in any case.

**Comment by rasher** [comment]
Copying from the original report in trac, this *is* a problem for actual use. [Comment by rasmusv](https://trac.openstreetmap.org/ticket/4099#comment:2):

*****

I think that the original reporters problems have been resolved in OSM, however I've observed something similar in Denmark. 

I have created the multipolygon 1933205 [1], which covers the municapality of Samsø (Samsø Kommune) - a big island with approximately 16 islets. The multipolygon is given a name tag which should preferably apply only to the complete multipolygon and not all of the 17 parts of the multipolygon [2] as it is now. The problem with the existing method of rendering is that you cannot see the names of the islets, but instead they are wrongly called "Samsø Kommune".

\[1]: http://www.openstreetmap.org/browse/relation/1933205
\[2]: http://www.openstreetmap.org/?lat=55.8944&lon=10.6519&zoom=14&layers=M

**Comment by math1985** [comment]
This is a different problem, this issue is about the name of an outer element being rendered rather than the name of the multipolygon. Could you open a new issue for this?
