### ISSUE TITLE
Add rendering for landuse=greenhouse_horticulture

### ISSUE THREAD

**Issue by mfornasa** [gravitystorm/openstreetmap-carto#78]
It seems that landuse=greenhouse_horticulture is not rendered.
[http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dgreenhouse_horticulture]

See example at: http://www.openstreetmap.org/?lat=45.41466&lon=11.01812&zoom=17&layers=M

**Comment by matkoniecz** [comment]
If it would be rendered I think that it should be displayed exactly like landuse=farmland. It is different than a typical field, but not different enough to make YA landuse colour reasonable. Also, in fully mapped area greenhouses will be mapped.
