### ISSUE TITLE
Add area rendering tourism = chalet

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#786]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/4854):

Areas which are tagged as "tourism = chalet" do not get rendered, I would propose these are rendered the same as campsites etc.

**Comment by matkoniecz** [comment]
I think that there is no space for rendering even more features as areas, therefore I propose to reject this proposal.

**Comment by polarbearing** [comment]
Added to the table in #1624 - another case for potential outline rendering.
