### ISSUE TITLE
Render name for barrier=gate objects

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#790]
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/3943):

I think it would be worthwhile to render the name=* tag for barrier=gate objects, as these are often important landmarks. See the discussion on the tagging@ list for further discussion:  http://thread.gmane.org/gmane.comp.gis.openstreetmap.tagging/8155

Thanks to XAPI, the database shows that as of 2011-07-29, 3,129 out of 221,793 (1.4%) barrier=gate nodes have a name, so this certainly won't overwhelm the map with new names.

I'm not a style designer, but I'd suggest the name should only show at zoom levels 15 and above.

**Comment by matkoniecz** [comment]
see also #152 proposing doing this for historic=gate

**Comment by math1985** [comment]
Gates are usually unlabelled, and if they are labelled, it is typically with the name of the amenity they give access to. Therefore I think there's currently no point in rendering gate names, so I will close this issue.

**Comment by dieterdreist** [comment]
2015-03-22 1:43 GMT+01:00 math1985 <notifications@github.com>:

> Gates are usually unlabelled, and if they are labelled, it is typically
> with the name of the amenity they give access to. Therefore I think there's
> currently no point in rendering gate names, so I will close this issue.



As soon as there several gates (and not just emergency exits or similar),
they will typically have names or refs (numbers / letters). Think of big
factories for instance. Around here, this is also typical for the beach,
e.g. http://www.openstreetmap.org/node/2775382249
