### ISSUE TITLE
Add rendering for leisure=ice_rink

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#796]
Some leisure objects are not rendered, such as:
- leisure=ice_rink  (https://trac.openstreetmap.org/ticket/3482)
- leisure=dog_park (https://trac.openstreetmap.org/ticket/2482)

**Comment by matkoniecz** [comment]
dog_park is covered by #341

**Comment by jragusa** [comment]
https://www.openstreetmap.org/way/381191895

Pitch colour:
![ice_rink_pitch](https://user-images.githubusercontent.com/9897203/40277761-dee93da8-5c24-11e8-8e80-50e9203fdf42.png)

Glacier colour:
![ice_rink_glacier](https://user-images.githubusercontent.com/9897203/40277767-ee25f3ec-5c24-11e8-9cdf-5a2da8eff6e2.png)

However, I still have a problem to render name from landcover.mss

**Comment by jragusa** [comment]
Thank you very much @matkoniecz 

I didn't know this feature to find code in the project. This helped me a lot

With name rendered
https://www.openstreetmap.org/way/87188308
![ice_rink_name](https://user-images.githubusercontent.com/9897203/40574110-29a2c556-60cd-11e8-8f8a-163a3d40c749.png)

**Comment by HolgerJeromin** [comment]
Many ice rinks in germany are buildings:
https://www.openstreetmap.org/way/33498620

I have no preference what to do with them, but this should be considered.

**Comment by jragusa** [comment]
The rendering is the same than both `building=*` and `leisure=sports_centre`: they are basically rendered as building (area and label). The new rendering is only available for outdoor ice_rink

**Comment by Tomasz-W** [comment]
@jragusa Are you going to make a PR for this issue?

**Comment by jragusa** [comment]
@Tomasz-W done :)
