### ISSUE TITLE
Add label for amenity=car_sharing

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#800]
amenity=car_sharing is currently rendered with icon, but without label. In bigger places there are multiple operators, so rendering the name or operator value would be nice.

See also https://trac.openstreetmap.org/ticket/3526.

**Comment by nebulon42** [comment]
Is there a consensus yet? I'd like to fix #857, but I don't know how the label should be displayed.

**Comment by sb12** [comment]
This has been solved by #1452.

**Comment by math1985** [comment]
Thanks for pointing out.
