### ISSUE TITLE
Remove barrier catch-all

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#818]
We have at the moment a catch-all rendering for barriers: all barrier=* lines, with the exception of barrier=hedge, are currently rendered as a gray line.

We probably want to get rid of this catch-all, just like we got rid of the other catch-all's.

Question is what we want to include. In particular, I wonder whether should render barriers that are typically tagged as node also as lines. For example, barrier=block, barrier=style, barrier=bollard, and barrier=gate are usually tagged as node, but sometimes also as way.

**Comment by HolgerJeromin** [comment]
closed by #1986

**Comment by math1985** [comment]
Thanks.
