### ISSUE TITLE
Distinguish deciduous and coniferous forests

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#822]
At the moment, we don't distinguish deciduous and coniferous forests. Distinguishing them in rendering might improve the map.

See https://trac.openstreetmap.org/ticket/1526.

**Comment by matkoniecz** [comment]
see https://github.com/gravitystorm/openstreetmap-carto/pull/1242#issuecomment-126958042 for ideas and partial implementation how this data may be displayed

**Comment by BushmanK** [comment]
I made several sample patterns using current pattern used for natural=wood.

leaf_type=needleleaved no leaf_cycle
![needleleaved](https://habrastorage.org/files/bc6/fba/7c5/bc6fba7c5bcf4f1eb684c4cafc103ddf.png)

leaf_type=broadleaved no leaf_cycle
![broadleaved](https://habrastorage.org/files/4a9/241/392/4a9241392ed14f18bb947cb831f8b57c.png)

leaf_type=broadleaved leaf_cycle=deciduous
![broadleaved deciduous](https://habrastorage.org/files/6e4/2aa/918/6e42aa918bed495fb2eac710cd720a0b.png)

For leaf_cycle=evergreen, leaf_cycle=semi_evergreen,  leaf_cycle=semi_deciduous I suggest using pattern with fully filled tree outlines, but any other ideas are welcome, for sure.

So, basically, for unknown life cycle outline should be empty; for trees, looking differently through the year - half-filled, for trees, not changing or barely changing its appearance - fully filled.

While not all needle-leaved plants have similar conic shape as fir or cypress (mature pine, for example), in majority of cases, this shape is associated with them pretty well. So, I believe, using conic and rounded canopy outline is legitimate way to show broadleaved and needleleaved trees.

Actually, I have no  idea how to show leafless plants - hard to imagine unified symbol for them, they are too different.

**Comment by d1g** [comment]
> It doesn't sound like the tagging is fully settled out. Worth noting: we have wood in the database, but not leaftype.

Things changed since 2014, probably it's time to review (now 420K leaf_cycle objects vs 366K instances of the deprecated wood)

http://taginfo.openstreetmap.org/compare/wood/leaf_cycle

**Comment by HolgerJeromin** [comment]
We are waiting here for #1504

**Comment by kocio-pl** [comment]
As the leaf_type rendering is progressing nicely, we can get back to discussion about leaf_cycle. Note however that there can be as much as 6 of them (including unknown) for 3 types of leaf (broadleaved, needleleaved and unknown): 

https://wiki.openstreetmap.org/wiki/Key:leaf_cycle

**Comment by sommerluk** [comment]
Note that the wikipedia links for semi_evergreen and semi_deciduous point to the _same_ wikipedia page, so the question is what’s the real difference? Furthermore, eaven both together are much less used than the other values:

deciduous 80.36%
evergreen 11.38%
mixed 5.02%
semi_deciduous 2.35%
semi_evergreen 0.52%

So maybe semi_deciduous and semi_evergreen can be rendered either both the same way, or even not at all…

**Comment by kocio-pl** [comment]
I would render semi_x the same as x. The symbols are too small to fit too many information in them, so that would be good enough for me.

**Comment by imagico** [comment]
@sommerluk - you should not give too much on basic numbers and value lists that are often just copied from Wikipedia (which in contrast to OSM loves the idea of closed classification systems).  It is always important to also see if use of a tag is actually consistent with the documented meaning (and if - as you mentioned - there is even a clearly documented and verifiable meaning) and with the situation on the ground (like with leaf_type=leafless where this is clearly not the case).

Rendering certain values will always endorse these values in comparison to other possible values.  There is for example also the term `brevideciduous` with a much clearer botanical meaning.
