### ISSUE TITLE
Add rendering for attraction=summer_toboggan

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#825]
It would be great to have ways with attraction=summer_toboggan rendered. Right now, most of them a additionally tagged with railway=narrow_gauge etc - which is a clear case of "tagging for the renderer". Having the proper tag rendered would solve certainly this problem.

I think we could even keep the rendering the same as railway=narrow_gauge.

See also https://trac.openstreetmap.org/ticket/4935.

**Comment by pnorman** [comment]
After this time without any progress or interest, I'm going to close this issue.
