### ISSUE TITLE
Render bridge_name

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#828]
We should render lock_name and bridge_name for the name of locks and bridges, respectively.

See also https://trac.openstreetmap.org/ticket/3223.

**Comment by matkoniecz** [comment]
Changed it to request rendering bridge_name, lock name is covered by #157

**Comment by math1985** [comment]
I'm not sure that this is no longer necessary now we render man_made=bridge.

**Comment by matkoniecz** [comment]
> I'm not sure that this is no longer necessary now we render man_made=bridge.

Why it would be still necessary? Names of bridges are now rendered and therefore this workaround is no longer necessary.

What would be the pint of rendering name of bridge on the road? Especially as roads on bridges may have their own names, different from name of the bridge.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 28.08.2015 um 20:40 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Why it would be still necessary? Names of bridges are now rendered and therefore this workaround is no longer necessary.
> 
> What would be the pint of rendering name of bridge on the road? Especially as roads on bridges may have their own names, different from name of the bridge.
> 


+1, bridge_name always was a strange workaround due to the fact that bridges for a very long time had been mapped only implicitly

**Comment by jojo4u** [comment]
Yes, we have man_made=bridge now, rendering the bridge name on the highway should be unnecessary.

**Comment by math1985** [comment]
Closing per @matkoniecz.
