### ISSUE TITLE
Add rendering for multistory parking icons

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#839]
Multistories should be rendered with a P and roof.

See also https://trac.openstreetmap.org/ticket/3470.

**Comment by mkoniecz** [comment]
I see no good reason for special rendering in this case. Also, how it is tagged?

**Comment by polarbearing** [comment]
Just for the records, it is tagged, and used:
"amenity=parking" + 
"parking={ surface 500k | multi-storey 19k | underground 21k | rooftop 518 | sheds 252 | carports 1k | garage_boxes 2k }"

**Comment by geozeisig** [comment]
Please insert a symbol for `amenity=parking` + `parking=multi-storey`.
It could look like this:
![parkhaussymbol](https://user-images.githubusercontent.com/17127509/48670114-66b6e100-eb12-11e8-95f9-e30bc032fe38.jpg)

[https://gist.github.com/geozeisig/df5c02ed2484ee52f13f994d26bc2912](https://gist.github.com/geozeisig/df5c02ed2484ee52f13f994d26bc2912)

**Comment by jeisenbe** [comment]
I don’t believe this is needed.

Parking structures are buildings, and the rendered building outline
provides more information than a unique symbol.

**Comment by Adamant36** [comment]
I agree with @jeisenbe. Also, how are people going to know its multi-storey and not covered parking instead going by your icon? 

On the plus side, it has 31,680 uses and seems to be increasing at a pretty steady pace. Using an icon would also help differentiate multi-storey from covered or underground parking. 
![taghistory 6](https://user-images.githubusercontent.com/30259065/48686413-b6c49080-eb70-11e8-928c-6fc3f9c7a0ec.png)

**Comment by polarbearing** [comment]
Maybe multi-storey could get some repetitive element. Either a double roof, two horizontal lines under the P, or one below and one above (compare tourism=apartment)

**Comment by Adamant36** [comment]
I was thinking something like a double or single arrow on top for multi-storey, a flat line on top for covered, and double or single arrow on the bottom for underground.

**Comment by jeisenbe** [comment]
Covered parking can also have the roof areas tagged with building=roof, no?
There is an open PR to render this lighter than standard buildings. Perhaps
this is enough; the type of building or roof or absence of a building will
show if it is surface parking, covered parking, or a structure.

**Comment by kocio-pl** [comment]
Since the people are discussing the issue, I reopen this ticket.

**Comment by Adamant36** [comment]
@jeisenbe, actually it appears there is different parking tags for covered parking. Including parking=sheds, parking=carports, and parking=garage_boxes. There's also a recommendation of using building=carport instead of parking=carports. Who knows how much any of those tags are used. I always just go with building=roof. Id imagine that's what most people do. I know in America we don't make a distinction between the different types.

**Comment by jragusa** [comment]
With #3599, parking_entrance of multi-storey parking will be rendered. Does it still necessary to render differently `parking=multi-storey` ? Moreover, the "P" icon is displayed on top of a building in contrast to `parking=surface`, and `parking=underground` will be hidden with #3600.

**Comment by Tomasz-W** [comment]
@jragusa I think thet mentioned PR resolves this issue.
