### ISSUE TITLE
Render ref for leisure=pitch

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#845]
It would be good to see ref tags rendered as badges for leisure=pitch objects.

If the object also has a name tag, then the badge and name are rendered on top of each other. This may also be a problem when (or if) sport icons are rendered too, then you could potentially have to render a name, a sport icon, and a ref badge for the one pitch.

See also https://trac.openstreetmap.org/ticket/3214.

**Comment by andrewharvey** [comment]
What if the feature has no name? I was thinking just appending the name with the ref in parthenthesis.

**Comment by math1985** [comment]
Only 0.5% of the pitches has a ref. The function of this ref differs a lot from place to place: sometimes it is ref within the sports club, sometimes municipal ref, etc. At this point it doesn't make sense to implement this, so I'll close this issue.
