### ISSUE TITLE
Increase zoomlevel for private amenity=recycling

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#847]
In the German speaking countries every apartment building has it's own containers for recycling plastic, paper,but only people living in those apartments are allowed to use them. They are mapped according to the description on the wiki page with access=private added to them.

problem is, mapnik still renders them even at zoom level 16, which totaly clutters the map. example:  http://osm.org/go/0JhJfqRx

Suggestions for fine tuning the rendering of this tag: 1) amenity=recyling + access+private should only be rendered at zoom level 18 and higher and transparency of the symbol should be set to 50% (like it is done with amenity=parking if set to private). at zoom level 17 or lower, it shouldn't be rendered at all. 2) amenity=recyling + access+permissive should only be rendered at zoom level 17 and higher and transparency of the symbol should be set to 50% (like it is done with amenity=parking if set to permissive ). at zoom level 16 or lower, it shouldn't be rendered at all. 3) amenity=recyling + access+public (or no restriction) should be rendered without transparency and at zoom level 16. (basically as it is now)

See also https://trac.openstreetmap.org/ticket/3575.

**Comment by kocio-pl** [comment]
I think [rendering them lighter](https://github.com/gravitystorm/openstreetmap-carto/issues/1012) may be better.

**Comment by matkoniecz** [comment]
Zoom was increased also for public, maybe increasing it even more for private ones is still a good idea.

**Comment by kocio-pl** [comment]
I think about something different: amenity=recycling can be large/important (recycling_type=centre) or small/less important (recycling_type=container), which is IMO exact analogy to amenity=waste_disposal (it's just that some trashes are segregated and some other aren't). I realize we need a database reload, but it makes sense for me to:
- Have recycling_type=centre earlier (z>=17 as of now or maybe even z>=16).
- Push recycling_type=container later (lack of recycling_type=* should be treated the same by default), probably to z>=18 or even z>=19, no matter if they are public or private.
- For amenity=waste_disposal use the same rules as for recycling container (the icon could be just bigger than for amenity=waste_basket).

I wanted to open new issue for that, but maybe there's no need for it and we can continue here?

**Comment by HolgerJeromin** [comment]
I hope many centres are mapped as an area, so probably we do not need the new tag in the db, but could use way area.

**Comment by kocio-pl** [comment]
I also thought about it, but both can be mapped as an area (containers can be under roof or in a kind of shed), so this would not work.

**Comment by HolgerJeromin** [comment]
But even a shed or something like that would be smaller than a typical (or at least important) centre. So IMO your suggestions from https://github.com/gravitystorm/openstreetmap-carto/issues/847#issuecomment-127776632 would still work.

**Comment by matkoniecz** [comment]
> or node (center area border could be not known)

Rendering them as not prominent as they deserve encourages more detailed rendering (as an area) so it is OK.

**Comment by kocio-pl** [comment]
I don't like those workarounds, but I also don't want to loose the energy to get into details too deep, especially before we have interesting database entries available and we can test different approach. The most important things for me are:
- there are bigger and smaller/local recycling points and we should reflect their importance (by choosing proper zoom level)
- small/local recycling points are in fact the same as waste disposals and we should reflect it (by using the same rendering rules)
- private/public difference is better reflected by using opacity than by tuning zoom level (just like we don't do it for private highways or private buildings)

**Comment by kocio-pl** [comment]
The current numbers for amenity=recycling are:
- recycling_type=centre - 11 419
- recycling_type=container - 106 157

I guess it's now ready to finally deploy https://github.com/gravitystorm/openstreetmap-carto/issues/847#issuecomment-127776632. This will make z17 less cluttered and soon we can have also amenity=waste_disposal on z18+ (see #419).

**Comment by HolgerJeromin** [comment]
More important than the number itself: [60.49%](https://taginfo.openstreetmap.org/tags/?key=amenity&value=recycling#combinations) of all recycling objects have added type.

**Comment by kocio-pl** [comment]
I think it's even easier: only "centre" should be visible on z17 (as currently), we don't have to check any other type - they all will fall into z18/19 by default, so lack of type doesn't bother us.
