### ISSUE TITLE
Add rendering for natural=cliff node

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#849]
Nodes tagged with natural=cliff should be rendered.

See also https://trac.openstreetmap.org/ticket/3770.

**Comment by matkoniecz** [comment]
http://wiki.openstreetmap.org/wiki/Tag:natural%3Dcliff after http://wiki.openstreetmap.org/wiki/Proposed_features/cliff_clarification now has definition 

> Nodes tagged natural=cliff mean rock spires. One common and simple sign is an upright isosceles triangle.

**Comment by dieterdreist** [comment]
> Am 15.03.2015 um 13:17 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Nodes tagged natural=cliff mean rock spires. One common and simple sign is an upright isosceles triangle


what an unfortunate decision, just because this was voted doesn't make it make more sense. Why not natural=rock_spires ?

**Comment by matkoniecz** [comment]
There is http://wiki.openstreetmap.org/wiki/Proposed_features/natural%3Dspire

**Comment by dieterdreist** [comment]
2015-03-15 14:43 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> There is
> http://wiki.openstreetmap.org/wiki/Proposed_features/natural%3Dspire
>


thank you for pointing to this draft. Unfortunately the proposed value is
less explicit than what you (above) and he (in the description) did use
when writing about it. My suggestion remains natural=rock_spire.

**Comment by matkoniecz** [comment]
>  Nodes tagged natural=cliff mean rock spires. One common and simple sign is an upright isosceles triangle

Rock spires may be also tagged as areas with natural=bare_rock. Given that it is already rendered, tagging as area is superior and we already have problems with way too many icons I propose rejecting this proposal.
