### ISSUE TITLE
Change icon for railway=subway_entrance

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#851]
Subway entrances are currently rendered with an icon that seems to symbolize 'walking'. This needs to be changed.

[Example](http://www.openstreetmap.org/#map=19/40.41912/-3.69332)

See also https://trac.openstreetmap.org/ticket/3920.

**Comment by math1985** [comment]
@nebulon42 Do you have any suggestion for an alternative to this?

Would the letter M be well-known enough? Or something with stairs?

**Comment by pnorman** [comment]
> Would the letter M be well-known enough?

No - letter used is a regional thing.

**Comment by k-bx** [comment]
Yeah, "M" would be quite bad for Berlin, for example. They have two different subways one named with [blue "U"](http://en.wikipedia.org/wiki/Berlin_U-Bahn) and another with [green "S"](http://en.wikipedia.org/wiki/Berlin_S-Bahn).

I think proper upload of logos would be a good solution, it could be done as a small separate service that I could work at if you need help. It would have a database of icons for public transports per city and some discussion forums. What do you think?

**Comment by nebulon42** [comment]
I'd like to avoid letters as they are not universal. Something with stairs is preferrable.

@k-bx I'm not exactly sure what you are suggesting, but AFAIK regional renderings are out of scope for this style. Also public transport provider logos should be depicted at the station node or stop position and not at the entrances, even if those are often equipped with such logos.

**Comment by gravitystorm** [comment]
Using "proper logos" also has big problems - it means that everyone needs to learn what all the different logos mean in all the different cities. For this style we will be keeping generic symbols.

**Comment by dieterdreist** [comment]
> Am 01.05.2015 um 14:04 schrieb Andy Allan <notifications@github.com>:
> 
> Using "proper logos" also has big problems - it means that everyone needs to learn what all the different logos mean in all the different cities.


if you're using the public transport in a place  you'll know these logos for sure, and you'll be looking for them when searching a close by underground station.

**Comment by math1985** [comment]
Not only people on the ground use the map. If I hear about a terrorist attack in a metro station in Kuala Lumpur, I would like to be able to easily find that metro station on the map without having to know how metro symbols in Kuala Lumpur look like.

**Comment by k-bx** [comment]
@math1985 it should be quite obvious what is the sign of a metro by just observing a map:

https://i.imgur.com/06SwK5k.png
https://i.imgur.com/avpucsW.png
https://i.imgur.com/4UVTAkf.png

We can see Google has both solutions, for Kuala Lumpur it shows generic icon, while for Berlin and Kyiv it shows local one. Things like M-sign in Kyiv or S and U in Berlin are so common and recognizable there that for most users and use-cases it would rather feel that OSM-based app is broken or poorly-implemented if they don't see their sign rendered (and see generic blue icon instead).

**Comment by polarbearing** [comment]
It is an advantage of the carto style of the general OSM map that it is equal internationally. 
When looking on your google example for Kiev, the M letters could also be Museums to me, since I have never seen the local logos. 

Local styles can be rendered on other layers, see German style here with yellow-red motorways
http://www.openstreetmap.de/karte.html?zoom=15&lat=52.50855&lon=13.28096&layers=B000TT 
or French style with very local railway and metro icons (probably considering the operator tag to keep them local):
http://tile.openstreetmap.fr/?zoom=15&lat=48.87876&lon=2.36164&layers=B0000000FFFFFFF

**Comment by dieterdreist** [comment]
> Am 01.05.2015 um 06:05 schrieb Kostiantyn Rybnikov <notifications@github.com>:
> 
> They have two different subways one named with blue "U" and another with green "S".


FWIW, only the U are subways, the S are light rails.

**Comment by nebulon42** [comment]
Though one. Here is an idea: ![subway-entrance-14](https://cloud.githubusercontent.com/assets/3531092/7445317/e4b5ef22-f1ad-11e4-9804-54a4c1daca81.png)

This is how it might look on the map (http://www.openstreetmap.org/#map=18/48.19931/16.35228):
![subway_entrance](https://cloud.githubusercontent.com/assets/3531092/7445324/f34171ce-f1ad-11e4-8e35-3b0f3ef44a7b.png)

The symbol should be smaller. But how the stairs should be recognisable then I don't know. Also icon halos would be nice. Have I suggested that already? ;-)

**Comment by nebulon42** [comment]
Same configuration, smaller symbol:
![subway_entrance_smaller](https://cloud.githubusercontent.com/assets/3531092/7452960/59f80912-f264-11e4-882b-51610b84af53.png)

**Comment by math1985** [comment]
Would this symbol work for subway stations that are not underground? Or is railway=subway_entrance reserved for underground entrances?

**Comment by nebulon42** [comment]
The wiki is unspecific on that. In Vienna also overground "U-Bahn" station entrances are mapped that way (see http://www.openstreetmap.org/#map=19/48.21466/16.41409). All the subway stations I know at least require going down or up some stair or escalator to reach the platform.

Another question is if we want to maintain a special distinction over other entrances. Otherwise we could also use a generic entrance symbol.

**Comment by kocio-pl** [comment]
There are also underground entrances not connected with transportation (other than just crossing the big street =} ), but rather giving you the access to underground located shops. However the question is do we need to give them a special icon (AFAIK there's no special tagging scheme for it). These underground entrances can be more general - you can cross the street and visit underground shops, but you can eventually take there to the train platform.

And if we want to consider stair/escalator going up, we have a lot of [such viaducts](http://makieta.pl/h0-stacje-dworce/5306-faller-120110-wiadukt-pieszy-peronowy-neustadt-h0.html) leading from the train station to the platform in Poland (which can also be a pedestrian link between different part of city).
