### ISSUE TITLE
Add rendering for tourism=artwork

### ISSUE THREAD

**Issue by math1985** [gravitystorm/openstreetmap-carto#855]
The tag tourism=artwork should be rendered with icon.

See also https://trac.openstreetmap.org/ticket/4529.

**Comment by kocio-pl** [comment]
I guess the icon is worth showing even without the name - at least for such artwork types as sculpture, statue or a stone. In the parks for example they are the common landmarks, together with some buildings and fountains (that's why I have created this ticket: https://github.com/gravitystorm/openstreetmap-carto/issues/705).

**Comment by polarbearing** [comment]
Currently 37500 occurrences, most of them nodes, about 2500 on ways (e.g., on walls).

**Comment by kocio-pl** [comment]
I guess this is so broad category, that I would rather wait for database reload, so we could know [exact type](http://wiki.openstreetmap.org/wiki/Key:artwork_type) and join them with corresponding [memorial types](http://wiki.openstreetmap.org/wiki/Key:memorial). We could render them that way for example: 
- architecture - could be rendered like tourist attraction (with star)
- mural/painting - icon showing the general "picture" could be good - but probably it would be good to have something like this for art galleries too, although not the same 
- sculpture - maybe some famous shape (other than statue)
- statue - the same as memorial=statue (general "statue" shape could work)
- stone - probably very similar (or the same) to rocks and memorial=stone

It's hard for me to imagine the general "artwork" icon, but I can test some ideas. If this is accepted, we wouldn't have to wait for anything more.

**Comment by jojo4u** [comment]
I detailed some problems with tourism=attraction here: http://wiki.openstreetmap.org/wiki/Talk:Tag:tourism%3Dattraction

**Comment by kocio-pl** [comment]
What about something abstract like [this](https://www.iconfinder.com/icons/171221/basic_block_character_circle_construct_construction_design_draw_figure_form_frame_framework_logo_phigures_picture_card_shape_shapes_shares_square_stature_structure_triangle_icon)?

**Comment by d1g** [comment]
@kocio-pl yes, any icon will work. 

Even coloured dot (similar to shop=yes), tourism=artwork features are important landmarks at z17+ levels

**Comment by kocio-pl** [comment]
Looks like eclipsing shapes doesn't work with such a limited matrix - it's hardly recognizable: 
1) ![artwork-14-7](https://cloud.githubusercontent.com/assets/5439713/15969632/26d880b0-2f31-11e6-8c76-0135eb9da3f2.png)
but a simpler idea might work:
2)  ![artwork-14-1](https://cloud.githubusercontent.com/assets/5439713/15969622/1d85b474-2f31-11e6-86b9-d090bf9d8f01.png)

**Comment by Jotam** [comment]
I really like the general idea. But with the triangle at the bottom, it somehow reminds me of a vintage camera. Could the triangle be at the top again?

**Comment by kocio-pl** [comment]
Sure:
3) ![artwork-14-13](https://cloud.githubusercontent.com/assets/5439713/16804081/42c13c98-490a-11e6-91f4-def232029b70.png)

**Comment by daganzdaanda** [comment]
4) is a good icon. 
Without knowing it, I would not read it as "artwork", though. (Toy blocks = childcare would be my first guess). How do others interpret the three shapes?

Would a palette (like https://cdn0.iconfinder.com/data/icons/business-vector-tab-bar-icons/48/painter_palette-512.png ) be a good idea for all artworks? Or would we get complaints that a statue is not a painting...?

**Comment by kocio-pl** [comment]
IMO there is no sure solution, since it could also mean shop=art (in violet) or art gallery. I like abstract blocks as the artwork can be very different - like [sculpture, graffiti, stone, painting, logo, installation](http://taginfo.openstreetmap.org/keys/artwork#values)... However I don't exclude palette if we agree about other possible uses of this symbol.

**Comment by d1g** [comment]
I vote for no4. 

There no good icon for sculptures in any case. Having icon for "paintings" is possible, but:

http://taginfo.openstreetmap.org/keys/artwork_type#values:
sculpture 15 942 56.73%
statue 8 394 29.87%

Please make an "good enough" icon for these 2 first rather how to include special case rendering of 1.25% :)

**Comment by kocio-pl** [comment]
So maybe we could design general statue icon, to match just the majority of cases (since 15% is relatively unimportant)?

**Comment by Jotam** [comment]
How about something very simple and very abstract?
![artwork](https://cloud.githubusercontent.com/assets/15984044/17060955/84540cac-502c-11e6-9ae3-d7d7ceb07219.png)

**Comment by kocio-pl** [comment]
I don't know, but if you provide SVG link, I can test it visually at least.

**Comment by Jotam** [comment]
Sure. 
http://roeskamp.de/osm/artwork_01.svg

**Comment by Jotam** [comment]
And maybe also try this ![artwork](https://cloud.githubusercontent.com/assets/15984044/17069506/3ce017d2-5057-11e6-9c1f-fad4c8f50038.png)
http://roeskamp.de/osm/artwork_02.svg

**Comment by kocio-pl** [comment]
Thanks! For me it looks like it's visually much better, because spiral pattern is lighter than mine (even crowded z18 is OK), but I feel it's too abstract.

Warsaw, z18:
![krvbnqsn](https://cloud.githubusercontent.com/assets/5439713/17069554/6fc9f6d6-5057-11e6-869f-6dbb02de8b2d.png)
z19:
![blah0tdh](https://cloud.githubusercontent.com/assets/5439713/17069556/78ef90e0-5057-11e6-8d64-3380199d928a.png)

**Comment by kocio-pl** [comment]
Second pattern is too heavy IMO comparing to monument and museum icons:
![ulntte0a](https://cloud.githubusercontent.com/assets/5439713/17069763/9b553d96-5058-11e6-9b1e-b51b6fa3e166.png)
![6s4sqxqx](https://cloud.githubusercontent.com/assets/5439713/17069768/a3445a1e-5058-11e6-855e-63739708951c.png)

![tbjnlrlu](https://cloud.githubusercontent.com/assets/5439713/17069770/ab344cde-5058-11e6-9a8b-db270284f510.png)

**Comment by Jotam** [comment]
Unfortunately, you are right. In places that are "cramped" with artwork, it's way to heavy. The question is if this makes sense at all. Don't get me wrong - I absolutely agree with tourism=artwork being rendered. But maybe only at the lowest zoom level. I quite like the icon when it's a single instance, though.

**Comment by Jotam** [comment]
The spiral shaped icon works fine. The fact that it's lighter is a good thing. Is it really too abstract? Some other opinions would be great.

**Comment by kocio-pl** [comment]
What about [statue-like design](https://github.com/kocio-pl/openstreetmap-carto/blob/artwork/symbols/artwork-14.svg) (technically it's toilet+monument =} )? I like it. It's light, similar to info point lightness (small "i" letter), but it still resembles popular artwork type and works reasonably even in the worst case (crowded z17):

Saski Park (z17-z19):
![kcjs1udm](https://cloud.githubusercontent.com/assets/5439713/17070515/a44db6fe-505c-11e6-9864-a84f68fec73b.png)
![qxgdsldr](https://cloud.githubusercontent.com/assets/5439713/17070741/0023e68c-505e-11e6-9110-13a1b5a07e72.png)
![ibeamvua](https://cloud.githubusercontent.com/assets/5439713/17070782/3760fe28-505e-11e6-964c-89eb963607b0.png)

and Lazienki Park (z17-z19):
![8jbdxibi](https://cloud.githubusercontent.com/assets/5439713/17070628/4e88df2c-505d-11e6-8d3a-e34e331ff0cd.png)
![n4jwmurx](https://cloud.githubusercontent.com/assets/5439713/17070582/05c5c0f2-505d-11e6-82bd-a08a09080d2d.png)
![y6odp8hh](https://cloud.githubusercontent.com/assets/5439713/17070568/ee865f96-505c-11e6-8fb5-2322b949db8b.png)

If we have more artwork-crowded places we could show only named artworks from z17 and the rest (without name) from z18.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 22 lug 2016, alle ore 22:15, Jotam <notifications@github.com> ha scritto:
> 
> But maybe only at the lowest zoom level. I quite like the icon when it's a single instance, though.


we could watch out for the combination with attraction. Rendering artwork will make more sense when hstore is active and we can differentiate by type

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 22 lug 2016, alle ore 22:19, Jotam <notifications@github.com> ha scritto:
> 
> The spiral shaped icon works fine. The fact that it's lighter is a good thing. Is it really too abstract? Some other opinions would be great.


it's a bit too big, with 1 wind less it would be better I think. Generally it could work, but still e.g. in the case of a statue there is some discrepancy in the overall shape. 

I could imagine also a tiny square (which doesn't convey any shape because more evidently represents a point) and a label

**Comment by Jotam** [comment]
Brilliant idea to combine "toilet" and "monument". :-) However, I see two problems: one is that it resembles the memorial icon. Another is that this proposal focuses only on statues. It would not be a good representation of graffiti, paintings, etc.

**Comment by kocio-pl** [comment]
For me it looks like the Oscar statue and is substantially different than memorial icon (compare both types in Lazienki Park for example).

I also think [focus on ~85% of objects](https://github.com/gravitystorm/openstreetmap-carto/issues/855#issuecomment-233432295) is a fair trade for now. However when hstore will be available I think we could use spiral for all the other artwork types (~15%).

**Comment by daganzdaanda** [comment]
I like that statue icon! It's very understandable and not intrusive. Great way to recycle existing elements and still be different enough to avoid confusion. 

[Tag-Info at the moment:](http://taginfo.openstreetmap.org/keys/artwork_type#values) 
> sculpture   16 000   56.69%
> statue   8 433   29.88%
> 

[But from the wiki:](http://wiki.openstreetmap.org/wiki/Key:artwork_type) 
> A sculpture is a work made of stone, metal, ceramic, wood or other material. If the work represents people or animals, you should use artwork_type=statue instead.

So, ~70% of artwork_types are not statues. Sculptures are probably mostly abstract, and could use a more abstract icon, like the spiral.

What about making the spiral a bit smaller like @dieterdreist said? maybe 1,5 turns would already be enough, and could allow for thickening the line a bit?

Another idea would be to use the small pedestal from the "oscar statue" and put a small diamond shape and a circle on top of it. So its similar in size and shape (not so dense), but more abstract.

**Comment by Jotam** [comment]
I tried both your suggestions. Unfortunately, 1,5 turns don't work for the spiral. It's hardly a spiral any more. But 2,3 turns are fine. See here: http://roeskamp.de/osm/artwork_01-02.svg

I also liked your other idea with the diamond. I had started to think into the same direction already. :-) Is this like what you had in mind? http://roeskamp.de/osm/artwork_03.svg

**Comment by Jotam** [comment]
@kocio-pl Great idea to distinguish between different kinds of artwork. As I said, I like your statue icon for statues. If we could have something more abstract for everything else, that would be perfect.

**Comment by math1985** [comment]
We should really be careful not to overcrowd the map. At the given zoomlevels, I think the art works are not relevant enough compared to the other features, I'd recommend rendering from z18 on.

**Comment by dieterdreist** [comment]
I have also made some variations

**Comment by dieterdreist** [comment]
![artwork_1](https://cloud.githubusercontent.com/assets/581288/17078581/18c097fa-50f7-11e6-8989-8ae81b52af0a.png)

![artwork_2](https://cloud.githubusercontent.com/assets/581288/17078582/18c3e3ba-50f7-11e6-8d13-54de54b63f83.png)

![artwork_3](https://cloud.githubusercontent.com/assets/581288/17078583/18ca6474-50f7-11e6-89e0-08bda77cfcc5.png)

![artwork_4](https://cloud.githubusercontent.com/assets/581288/17078584/18ddeee0-50f7-11e6-91b2-9cb0137ac3b0.png)

![artwork_5](https://cloud.githubusercontent.com/assets/581288/17078585/18e4053c-50f7-11e6-88ff-98406e933df5.png)

![artwork_6](https://cloud.githubusercontent.com/assets/581288/17078586/18e671f0-50f7-11e6-91c9-d7bac911f43a.png)

![artwork_7](https://cloud.githubusercontent.com/assets/581288/17078587/1901ed04-50f7-11e6-9a2b-1f89b3619363.png)

**Comment by dieterdreist** [comment]
the svg have been rejected but are available

**Comment by kocio-pl** [comment]
I just put icons into code branch, probably also "gists" (loose code collections) are possible here?

I would try rendering with 5.

**Comment by dieterdreist** [comment]
2016-07-23 17:09 GMT+02:00 kocio-pl <notifications@github.com>:

> I would try rendering with 5.



+1, I would try 5 and 7, unfortunately don't have a working rendering stack
around at the moment...

**Comment by math1985** [comment]
I would like to see a rendering with 7.

1-5 are not recognizable enough to me (if anything, they'd represent a fire extinguisher to me).

**Comment by kocio-pl** [comment]
8) artwork_03
![owec1ett](https://cloud.githubusercontent.com/assets/5439713/17081438/d6ee32ee-5158-11e6-9a74-0dfb307d6676.png)
![q7ftfah0](https://cloud.githubusercontent.com/assets/5439713/17081439/dc6cb47a-5158-11e6-9bc1-6102243851b2.png)

9) 7-like diamond (10 px)
![46tn7stv](https://cloud.githubusercontent.com/assets/5439713/17081440/f27403a4-5158-11e6-971d-5e1cc563912e.png)
![ebwr0duw](https://cloud.githubusercontent.com/assets/5439713/17081442/f4e2dcfa-5158-11e6-84b3-8b088e2bb11a.png)

**Comment by Jotam** [comment]
After all these different suggestions, I think I prefer @daganzdaanda's idea with the pedestal, diamond, and circle. It's light enough on the map, concrete enough to symbolize a statue, and abstract enough to represent sculptures and other artworks. It seems to meet all our requirements so far.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 24 lug 2016, alle ore 10:02, Jotam <notifications@github.com> ha scritto:
> 
> It's light enough on the map, concrete enough to symbolize a statue, and abstract enough to represent sculptures and other artworks. It seems to meet all our requirements so far.


IMHO it's clearly a statue an not suitable for paintings, graffiti, landart, etc.

**Comment by kocio-pl** [comment]
I also like the simple and abstract diamond icon. It is as universal as the spiral, but I agree with @math1985 that the spiral may look like a fire equipment (I didn't make such connection myself, but in fact there's similar icon in JOSM) and diamond look more like a "gem" on game maps to me - which I feel is consistent with the idea of the "artwork" on the real map.

So for now I would like to use diamond as a general artwork icon from z18 (to not overcrowd z17, which seems like a land between mapping and micromapping world). After we have hstore available, I would also add statue icon only for statues (~30% of artworks) and show "special" artworks earlier, like z16 or z17  (when we have "tourist_attraction=yes" established as an alternative form for "tourism=attraction").

What do you think about that?
