### ISSUE TITLE
Add rendering for amenity=dojo

### ISSUE THREAD

**Issue by matthijsmelissen** [gravitystorm/openstreetmap-carto#856]
The tag amenity=dojo should be rendered with icon.

See also https://trac.openstreetmap.org/ticket/5005.

**Comment by PanderMusubi** [comment]
Meanwhile, this key has been used 2856. Often a dojo has fixed mats and has only specific usage for the training of martial arts. Reopen please this issue.

**Comment by matkoniecz** [comment]
Questions at https://wiki.openstreetmap.org/wiki/Talk:Tag:amenity=dojo remain unanswered.

**Comment by polarbearing** [comment]
[leisure=sports_hall](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dsports_hall) is getting increasingly tagged now for single halls that do not form a "centre". 

This will become a better rendering candidate than a specific unsuitable amenity tag for every kind of sport.

**Comment by HolgerJeromin** [comment]
>  Often a dojo has fixed mats and has only specific usage for the training of martial arts. Reopen please this issue.

There are "sport" [halls](https://www.openstreetmap.org/way/86111245) with parquet floor which are only used for dancing. I don't think we should add a special handling for "one" sport section.

**Comment by PanderMusubi** [comment]
IMHO: Hacker and coder dojos should be labelled as maker spaces, hacker spaces or something similar. A dojo is like a swimming pool. You can only do a certain amount of sports there (swimming, waterpolo, diving), but which sports is up to equipment and management (judo, aikido, karate).

So a dojo is indepent of which sport is being practiced. Mainly in Japan, there are dojos with different types of mats, fixed cotton mats, fixed plastic mats, one large fixed plastic mat or parquet. And the floor can "floating" on some special kind of shock absorbing foam. Not that I would like to tag these details, but I would like to give an insight in that a dojo is a specialized amenity, like a swimming pool e.g. World wide, there are many dojos which aren't tagged yet, and they outnumber so called coder dojos. Some dojo are even cultural heritage. There are also cases of multiple dojos in one building. That building could be a sports hall/centre. See also https://en.wikipedia.org/wiki/Nippon_Budokan Does that answer your questions?

**Comment by PanderMusubi** [comment]
Most dojos, it is prohibited to enter on shoes and the soft mats on the floor usually prevent usage of a dojo for dancing or other activities. (Dancing is often with shoes or needs a bit more stable floor.)

**Comment by HolgerJeromin** [comment]
I meant dancing halls as another example for sport centres with limited target sports (which probably needs no special rendering).

**Comment by polarbearing** [comment]
Nobody stops you from subtagging the leisure=sports_hall with sports_hall=[dojo|dancing_hall|...], we all agree that they are different. Though that is better described in a secondary tag.

**Comment by sashagra** [comment]
if there is no map icon can it render the name of dojo?
