### ISSUE TITLE
Add rendering for amenity=car_rental

### ISSUE THREAD

**Issue by moliha** [gravitystorm/openstreetmap-carto#857]
amenity = bicycle_rental is rendered ok
but -
amenity = car_rental is completely invisible - no icon - no name - nothing at any zoom level.

In my opinion, this is too bad to be left uncorrected for long...

**Comment by nebulon42** [comment]
New icon available: https://github.com/nebulon42/osmic/blob/master/transport/rental-car-16.svg
For a PR I would need to know how the label should be rendered (name/operator/brand).
