### ISSUE TITLE
Add rendering for amenity=biergarten areas

### ISSUE THREAD

**Issue by dieterdreist** [gravitystorm/openstreetmap-carto#858]
If amenity=biergarten is on an area this area should be highlighted (color fill and/or outline). Right now there is only an icon and the name.

**Comment by math1985** [comment]
Which colour would be appropriate?

**Comment by matkoniecz** [comment]
I think that it is impossible to continue increasing number of different landcovers.

Also number of different outlines is limited.

I propose to close this as this area is not critically important to render.
