### ISSUE TITLE
Add rendering for amenity=food_court

### ISSUE THREAD

**Issue by sommerluk** [gravitystorm/openstreetmap-carto#868]
Add rendering for amenity=food_court. Easiest possibility: Treat it exactly the same way like amenity=restaurant (same logic, same icon).

**Comment by nebulon42** [comment]
What would be the benefit of having a different icon? Wouldn't it be the case that all the different food providers in the food court were tagged? I'm not a big fan of "add a circle to make it look different" icons and I'm currently lacking ideas for other depictions.

**Comment by sommerluk** [comment]
@nebulon42 The benefit could be that you can have a node for the food court, and individual nodes for the individual food providers. And if rendered differently, you can find out quickly which one is the name of the food court as a hole.

However, I agree that this is a minor concern.

**Comment by nebulon42** [comment]
On the other hand, nearly all food_courts I found in Austria where tagged incorrectly (should have been restaurant or fast_food), so maybe using the same icon as restaurant might encourage incorrect tagging?

**Comment by sommerluk** [comment]
Good point.
