### ISSUE TITLE
Add label for amenity=ferry_terminal

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#869]
Name of ~~the route=ferry~~ and amenity=ferry_terminal should be visible. Currently only MapQuest does this on the main OSM page. Example:

https://www.openstreetmap.org/way/37930736
https://www.openstreetmap.org/node/33238753

**Comment by pnorman** [comment]
c.f. https://phabricator.wikimedia.org/T156205 and my problems identify terminal details
