### ISSUE TITLE
Add rendering for amenity=vehicle_inspection

### ISSUE THREAD

**Issue by tux2000** [gravitystorm/openstreetmap-carto#881]
It seems that currently this tag is not rendered neither as node nor as area. Its not heavily used yet but it definitively is in use.

**Comment by matkoniecz** [comment]
Used 512 times worldwide.

**Comment by dieterdreist** [comment]
> Am 15.03.2015 um 13:10 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Used 512 times worldwide.


this is based on a proposal in draft status and should not have been created as a tag definition page IMHO. The proposed tagging makes it incompatible with other tags like amenity=fuel
Could have been an attribute rather than a top level tag.
