### ISSUE TITLE
Add rendering for tourism=gallery

### ISSUE THREAD

**Issue by moliha** [gravitystorm/openstreetmap-carto#883]
In 'Map Features', tourism=gallery has this explanation:

Art galleries are a popular visitor attraction 

but no icon
worse: even if the gallery has been given a name, nothing is shown

So, even though galleries are popular attractions, they are invisible on the map.

**Comment by matkoniecz** [comment]
@math1985 

> They have overlap with shop=art and shop=museum, is the tag welldefined?

As @dieterdreist noted in http://wiki.openstreetmap.org/wiki/Proposed_features/Art_gallery#Voting - no.

>I think this is pointless, as there are already shop=art for galleries and tourism=museum for galleries which do not sell. Create a subtag for museums (e.g. museum:theme=art_gallery) if you want to tell that it is explicitly for art work. I also don't agree that those are "for tourists". Given all that, "gallery" is not clear at all, and tourism doesn't help either to define that it is an "art gallery"

Tag passed voting, fortunately usage is quite low. I think that it should not be rendered.

**Comment by math1985** [comment]
In England, there seems to be a stronger distinction between art galleries and museums than in continental Europe, so from that perspective I think the tag somehow makes sense.

But apart from that, we already have a huge amount of discussion in this repository, which is good but also makes it hard for the maintainers to follow (and participate) in everything. I really would not like to increase the amount of discussion even more, so I think we should not concern ourselves with tagging discussions here.

As far as I'm concerned, the people at the tagging mailing list have made a decision, so we shouldn't dismiss rendering this tag with the argument that it's bad tagging. Anyone who disagrees with the tagging scheme is free to re-open the discussion on the tagging mailing list.

**Comment by dieterdreist** [comment]
> Am 16.03.2015 um 19:22 schrieb math1985 <notifications@github.com>:
> 
> In England, there seems to be a stronger distinction between art galleries and museums than in continental Europe, so from that perspective I think the tag somehow makes sense.


yes, but it highly misleading because even in the English world (eg the U.S.) the term gallery refers to different kind of objects. Without the "art" the tag is ambiguous anyway, and tourism seems a bad choice for an object whose main purpose is preservation and education

**Comment by pnorman** [comment]
> As far as I'm concerned, the people at the tagging mailing list have made a decision, so we shouldn't dismiss rendering this tag with the argument that it's bad tagging. Anyone who disagrees with the tagging scheme is free to re-open the discussion on the tagging mailing list.

I've only ever considered the wiki a secondary source for tagging info - at best.

**Comment by kocio-pl** [comment]
This scheme is being currently discussed [on Tagging list](https://lists.openstreetmap.org/pipermail/tagging/2016-January/028265.html), if somebody is still interested in this topic.

> I've only ever considered the wiki a secondary source for tagging info - at best.

As far as I remember you tend to rely on the database content, but I find it very limited, since we would loose the meaning. Of course, we could find general, common sense meaning (like "museum", "gallery", "art" or "shop"), but we could not decide which is preferred, because in real life these objects can be expressed in many ways. Wiki is very useful tool to show the preferred scheme for given object, defining it's scope (database itself can't do it at all) and showing coherent "extensions" of the basic scheme (like "name", "operator" or "ref" - in db all these are just separate tags without connection to others).

**Comment by pnorman** [comment]
Given the relatively low usage, lack of PRs, and lack of interest I'm going to close this issue.

**Comment by Adamant36** [comment]
Looks like it has 4798 now and is fairly well defined. So it might be worth revisiting. If @Tomasz-W wants to come up with an icon for it, I would be willing to do the PR.

**Comment by Tomasz-W** [comment]
What about re-use of `amenity=arts_centre` icon in amenity-brown?

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/art.svg

**Comment by Tomasz-W** [comment]
@kocio-pl As it has almost 5k uses now, can we re-open this issue and try to add an icon for it?

**Comment by Adamant36** [comment]
@Tomasz-W, since its been re-opened do you want to come up with an icon or ahould we test the one for amenity=arts_centre in brown for it as your propose?

**Comment by Tomasz-W** [comment]
@Adamant36 re-use of amenity=arts_centre.
