### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by wikiro** [gravitystorm/openstreetmap-carto#886]
Ребят, подскажите пожалуйста, что я делаю не так, что с ресурсами? Пишет, что нет файла. Спасибо.
Dear Colleagues, could You please check if above files exists and are accessible on your resource.

wget http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
--2014-08-17 16:04:29--  http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
Распознаётся www.naturalearthdata.com... 66.147.242.194
Устанавливается соединение с www.naturalearthdata.com|66.147.242.194|:80... соединение установлено.
Запрос HTTP послан, ожидается ответ... 302 Moved Temporarily
Адрес: http://www.nacis.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip [переход]
--2014-08-17 16:04:30--  http://www.nacis.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
Распознаётся www.nacis.org... 23.235.213.250
Устанавливается соединение с www.nacis.org|23.235.213.250|:80... соединение установлено.
Запрос HTTP послан, ожидается ответ... 301 Moved Permanently
Адрес: http://nacis.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip [переход]
--2014-08-17 16:04:31--  http://nacis.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip
Распознаётся nacis.org... 23.235.213.250
Повторное использование соединения с www.nacis.org:80.
Запрос HTTP послан, ожидается ответ... 404 Not Found
2014-08-17 16:04:31 ОШИБКА 404: Not Found.

**Comment by robrackn** [comment]
The URL to the NaturalEarth 'ne_110m_admin_0_boundary_lines_land' shapefile no longer work. 
Are there any alternative download sites?

![script](https://user-images.githubusercontent.com/1779910/56385667-716ec280-61e5-11e9-92b5-d4b844dc6478.gif)

**Comment by nvkelso** [comment]
That’s fixed.

Alternative is to download from github.

**Comment by imagico** [comment]
Works fine here now.  There were problems yesterday so maybe some residual effects of this cause problems for you.  We could move to using https which is what is linked on the website now but the http URL seems to work.

You can see if the links on

https://www.naturalearthdata.com/downloads/110m-cultural-vectors/

work.

Alternatively - as mentioned on the dev mailing list - you can also get the shapefiles from 

https://github.com/nvkelso/natural-earth-vector/tree/v4.0.0/110m_cultural
