### ISSUE TITLE
Add rendering for names man_made=works

### ISSUE THREAD

**Issue by daganzdaanda** [gravitystorm/openstreetmap-carto#887]
Do you think it would be sensible to display the name of factories tagged with man_made=works? 
We already render landuse=industrial, so there may be some duplication of labels afterwards, but surely there are factories that don't sit on a named landuse, and then you just see a huge building with no indication as to what it is.

**Comment by HolgerJeromin** [comment]
Often we have a big landuse=industrial area with multiple man_made=works nodes inside because the mapper had no idea where the different companies are located inside. From the outside it is not easy to decide where one company ends and the next starts inside the landuse. 
IMO this is a valid transition tagging. 
But right now the works nodes are not rendered with a name, so you have no idea which company is there. (Only if there is a named parking :-)

**Comment by abdeldjalil09** [comment]
Please render this tag, in many industrial areas , we see his housenumbers instead of his names, we have ~90000 uses.

**Comment by kocio-pl** [comment]
Should be rather easy to do and it sounds to me like we have agreement here.

**Comment by nbcaldon** [comment]
This is similar to an issue we are having at the moment with industrial estates:
With multiple shops and amenities in a building, it is possible to show the names of the shops on the standard map by adding each shop as a node within the building. With industrial buildings, the nodes can be added in the same way, but the names of the nodes are not rendered. I propose that where a node is tagged with "industrial=" and "name=" the name should be rendered on the standard map. At present it does not seem to be possible to make the names of the companies visible if there are more than one in a building, unlike with shops where they can all be shown.
I am not sure whether this is a new issue or covered by the present one?

**Comment by HolgerJeromin** [comment]
@nbcaldon 
Only nodes with industrial= and name= is IMO not sufficient. man_made=works should be added and therefore this issue should cover your situation.

**Comment by nbcaldon** [comment]
@HolgerJeromin 
Thanks for your comment, but the name still does not render if I add "man-made=works".

**Comment by HolgerJeromin** [comment]
Yes. And that is why this github issue is still open.
