### ISSUE TITLE
Add rendering for amenity=doctors

### ISSUE THREAD

**Issue by CloCkWeRX** [gravitystorm/openstreetmap-carto#89]
Previously, a few people have been keen on seeing amenity:doctors or similar render:
* http://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddoctors
* http://wiki.openstreetmap.org/wiki/Proposed_features/Doctor
* http://wiki.openstreetmap.org/wiki/Proposed_features/Clinic_(Medical)
* http://wiki.openstreetmap.org/wiki/Proposed_features/GP_Surgery
* https://trac.openstreetmap.org/ticket/2309 (mapnik)
* https://trac.openstreetmap.org/ticket/4272 (mapnik)
* https://github.com/openstreetmap/mapnik-stylesheets/pull/8
* https://trac.openstreetmap.org/ticket/4741 (potlatch2)
* https://trac.openstreetmap.org/ticket/4599 (potlatch2)

There are renderings for dentists, and renderings for hospitals; arguably seeing a local GP is more relevant to more individuals who may be using OSM; than visiting a dentist.

Failing that, wontfixing this + the other 4 tickets would be worth doing to clean up the  number of open requests.

**Comment by teschi** [comment]
The current behavior also get's odd when you have an amenity=doctors with an address, the house-number will be displayed instead of each doctor, in my case leading to duplicated numbers that are rendered.

**Comment by nebulon42** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/pull/1041#issuecomment-67786406 for a perhaps clearer icon. I would have proposed it already, but there is #1041 and I didn't want to supercede it.

**Comment by math1985** [comment]
Resolved by #1201.
