### ISSUE TITLE
man_made=embankment is not rendered if it's a closed way

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#892]
man_made=embankment is rendered only when it's an open way, but not if it's a closed way. I think it should be visible in both cases, since sometimes embankment can be seen from all sides, not only as left/right edges - it also may be used to indicate there is a big "hole" in the ground.

**Comment by math1985** [comment]
Best solved with osm2pgsql lua file. Moved to corresponding milestone.

**Comment by kocio-pl** [comment]
Simple solution for now was adding area=no:

http://www.openstreetmap.org/way/296610960

The idea came from this object:

http://www.openstreetmap.org/way/219234636
