### ISSUE TITLE
own colour for each leisure type (sport)

### ISSUE THREAD

**Issue by Newbie07** [gravitystorm/openstreetmap-carto#919]
I have sports_centre with lots of different pitches and tracks and a stadium. But stadium and sport_centre have the same colour.
1. Please assign different colours to stadium and sport_centre
2. Additionally leisure=sports_centre and building=\* should be rendered differently than building=yes

Thanks

**Comment by oddityoverseer13** [comment]
One thing to note for this issue is some fields support multiple sports. Those can be tagged with either sport=multi or sport=sport1;sport2

**Comment by kocio-pl** [comment]
> a outline could work but might also interfere with barrier=fence.

They have an outline defined and it's lighter than barriers:
https://github.com/gravitystorm/openstreetmap-carto/blob/9d5795de44d6ea4c3545ed7e03c8e2d2d47e1d15/landcover.mss#L577-L580

**Comment by kocio-pl** [comment]
I don't think we have enough colors for this, so I will close it. Leisure/sport areas have light green currently and it's not so hard to distinguish them by icon and size most of the time, but it's not possible to use more colors for them. The more important thing is to know that light green is for leisure and sport in general.
