### ISSUE TITLE
addr:housenumber: render semi-colon separated values with comma as separator

### ISSUE THREAD

**Issue by Newbie07** [gravitystorm/openstreetmap-carto#920]
There are quite some objects with multiple values of addr:housenumber. They are often tagged with a comma as separator (and a white space afterwards) as it looks nice and it is mentioned on the wiki (https://wiki.openstreetmap.org/wiki/Addresses#Buildings_with_multiple_house_numbers).

On tagging@ was no objection to change the separator in favour of semi-colon. See http://thread.gmane.org/gmane.comp.gis.openstreetmap.tagging/18979

On point was mentioned though, that it would be nice if the renderer would change the separator into a comma and adding a white space afterwards.

Thanks

**Comment by mikedld** [comment]
Has anything changed since last time? If I'm counting it right, there're now ~103k `addr:housenumber` tags with commas and ~182k with semicolons.
