### ISSUE TITLE
gap in rendering when moving from a highway+railway to a highway+railway+bridge

### ISSUE THREAD

**Issue by matkoniecz** [gravitystorm/openstreetmap-carto#934]
http://www.openstreetmap.org/?mlat=59.33140&mlon=18.09368#map=19/59.33140/18.09368

Mentioned by Markus Lindholm on OSM-talk mailing list.

**Comment by pnorman** [comment]
We don't have a good picture of the issue, so I'm including this from #1993 

> ![bridge-road-tram](https://cloud.githubusercontent.com/assets/113756/11609651/91870d70-9b8c-11e5-890f-edc8de98e01a.png)

> This is the area of the example: https://www.openstreetmap.org/#map=19/51.04068/13.80249

**Comment by cm8** [comment]
> About the only way I can imagine to do this would be to detect bridges that touch non-bridges at their ends and render them with butt caps [..]

@pnorman: Have you thought about simply rendering highway=* bridge=yes twice?
- First time, we ignore layer tag + draw with round end caps.
- Second time, taking layer tag into account, draw butt caps only.

Caveat hit in very rare cases: If a tramway runs _under_ a bridge and its linestring is _directly_ under a split node of a bridge way made of multiple linestrings:  Then if these linestrings meet at a sharp angle, a small rendering artefact may occur, inverse to the problem fixed, putting the tramway for a small fraction ontop of the bridge.  It is very likely that this case is hit far less often than what we're trying to fix.

> > Could we use a butt endcap for bridge fills?
> No, because often bridges are split into multiple linestrings, and the join can be at an angle.

@gravitystorm In this case the rendering will be broken anyway: Round line caps miss a continued encasing stroke - unlike for the miter joints of one and the same linestring, the encasing will not magically connect when two separate linestrings meet (are split at) in a sharp angle. Example attached.

**Comment by gravitystorm** [comment]
> example uses id editor rendering, but carto does not behave different iirc

This is incorrect - it's best to use mapnik to demonstrate. For example, we don't use miter joints.

**Comment by cm8** [comment]
Yes, alright. I think the issue is clear to thread participants. As far as I can judge from the main map the behavior is the same for end point caps and this is also what we will have to deal with if a bridge way is split on the bridge.  What do you think about the suggestion to render end caps at layer 0 (or one layer below the one tagged) and then render with butt caps in the layer(s) currently rendered in?
