### ISSUE TITLE
Green rendering of leisure=track is confusing

### ISSUE THREAD

**Issue by vincentdephily** [gravitystorm/openstreetmap-carto#952]
Athletics tracks are currently rendered green (I guess the original idea was to use the same tint as sport pitches), which looks odd. The usual surface is compacted, or a special rubbery tarmac, red or black. Never grassy or green (that I've seen).

Not sure what color would suit best. Perhaps greyish-white, or a red that matches https://en.wikipedia.org/wiki/File:Athletics_track.jpg. See also issue #919.

**Comment by oddityoverseer13** [comment]
I've created [a discussion section](https://wiki.openstreetmap.org/wiki/Talk:Tag:leisure%3Dtrack) for discussing this further.
