### ISSUE TITLE
When label does not fit below icon, render label on top or side

### ISSUE THREAD

**Issue by kocio-pl** [gravitystorm/openstreetmap-carto#957]
In places, where there is a lot of icons and names to display, carto is performing quite bad, because it always try to render icon with text under it, and when there is not enough space, it simply hides them. However HOT does it better - it tries to move the names so they don't overlap and don't have to be hidden. 

Example - all 6 names instead of just 4 on the same zoom level (in the centre, top left corner of Francuska nad Walecznych crossing):

http://www.openstreetmap.org/#map=19/52.23517/21.05308
http://www.openstreetmap.org/#map=19/52.23517/21.05308&layers=H

**Comment by daganzdaanda** [comment]
Would it be a terrible idea to change the default position of icons from the top of the label to the left side? I know that it may look weird for right-to-left scripts, but for labels with a single line it could still be OK. And we would not have the problem that the icon looks lonely with too large text-dy.

What we have now (E for LTR, 3 for RTL):
```
  *          *               *        *        
EEEEE      EEEEE           33333    33333        
          EE EEEE                  33 3333        
```
What might work:
```
* EEEEE    * EEEEE        * 33333    *  33333       
             EE EEEE                   33 333        
```
Only the last example, RTL label with more that one line, might look bad if the first line is shorter than a later one. One could align the lable to the left, that would look good, but may be hard to read. We should ask Hebrew or Arabic speakers before doing something like that.

**Comment by daganzdaanda** [comment]
Actually, if it were possible to align RTL text to the right, it would probably be possible to change the default icon placement to the right, too?
And if it's not possible to have different alignment, then everything can be left-aligned, and there wouldn't be any problem with the icon distance. Reading RTL might still be a problem then.

**Comment by kocio-pl** [comment]
Back to business - I'll take a second chance on rendering at home:

@matkoniecz:

> I was working with a data for a single city obtained from Overpass API (Kraków) and it worked even in VM.

I would like to try Warsaw, but don't know how to do it - can you help me? Overpass-Turbo Wizard does not allow me to get naive "* in Warsaw". What are the exact steps to obtain a single city data then?

**Comment by matkoniecz** [comment]
@kocio-pl 

My method is described in point 1b in https://github.com/matkoniecz/bicycle_map_of_Krakow/blob/master/readme.txt 

Numbers specify limits of bounding box so it is necessary to adjust values to download a different city (osm file for Kraków and nearby areas is 216 MB).

I based this query on one of examples found on wiki.openstreetmap.org/wiki/Overpass_API (or maybe http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide ?).

**Comment by kocio-pl** [comment]
Thanks! I may try it if I want the most current data, but in the meanwhile I've found https://mapzen.com/metro-extracts/ with weekly data for key polish cities (including Warsaw and Cracow). However I was surprised that Cracow and nearby areas (Krakow_Poland) PBF file is only 15 MB. Why so big difference between your data and Metro?

**Comment by matkoniecz** [comment]
[PBF format](http://wiki.openstreetmap.org/wiki/PBF_Format) is more space efficient than .OSM (it is XML, famous for lack of space efficiency).

Note that Mapzen covers larger area, so this difference is even more significant.

Main benefit of downloading from Overpass is that I am frequently noticing problems in data. I may edit and within minutes (Overpass replication lag) it is possible to download a new version including my edit. It allows me to test rendering with a correct tagging.

**Comment by kocio-pl** [comment]
Metro OSM file is about 450 MB after bunzipping, so it may be true (they may use bigger box).

**Comment by kocio-pl** [comment]
At last I've made the test using @math1985 hint from https://github.com/gravitystorm/openstreetmap-carto/issues/957#issuecomment-55949424. Because unlike the HOT style we have many types of objects, [I applied those settings for shops and food/drink amenities for a start](https://github.com/kocio-pl/openstreetmap-carto/commit/d52633b66cd3c2724fb9381cbfc651cd6b412718).

### Simple retail area
before:
![labels-z19-shops-nieklanska-before](https://cloud.githubusercontent.com/assets/5439713/8390227/143f2c52-1c8a-11e5-8df1-92d5359bc04f.png) 
after:
![labels-z19-shops-nieklanska-after](https://cloud.githubusercontent.com/assets/5439713/8390229/1a25f146-1c8a-11e5-8d94-e6dbd6d8cd05.png)

### Complex retail area
before:
![labels-z19-shops-centralny-before](https://cloud.githubusercontent.com/assets/5439713/8390234/94568bce-1c8a-11e5-89fa-51fbabb97992.png)
after:
![labels-z19-shops-centralny-after](https://cloud.githubusercontent.com/assets/5439713/8390236/9f4d7fc4-1c8a-11e5-8aa6-c02e1d57babc.png)

### Complex amenity area
before:
![labels-z17-amenities-nowy-swiat-before](https://cloud.githubusercontent.com/assets/5439713/8390240/c96347bc-1c8a-11e5-9dbb-5ad55002674a.png)
after:
![labels-z17-amenities-nowy-swiat-after](https://cloud.githubusercontent.com/assets/5439713/8390242/cf3d7036-1c8a-11e5-8836-6ec41a4a1b3d.png)

**Comment by pnorman** [comment]
How do they compare for cut off labels at metatile boundaries?

**Comment by mboeringa** [comment]
@kocio-pl , while a good idea to ensure stuff gets labelled, this also means a lot more labels in already overcrowded map areas. From a cartographic point of view, I would therefore suggest not to swap this this labelling for the existing one, but use a two stage approach instead:

- Current labelling when zoomed out, preventing overcrowding of labels
- Switching to this new labelling only at the very highest zoom level(s). It is likely even only really appropriate on Z19 for features like shops and amenities like restaurants and pubs.

This way, you get the best of both worlds: a less crowded map when zoomed out (a bit), and stuff properly getting labelled when zoomed in.

**Comment by kocio-pl** [comment]
@mboeringa Thanks, you're right! HOT has much more subtle POI rendering so it works good there, but we have strong colors, so [I moved it to z19](https://github.com/kocio-pl/openstreetmap-carto/commit/d7719506a5f81571044c485b75587fd3336a2210) - this way it acts mainly as a substitute for higher zoom levels. First two examples are already on z19. For the eating amenities I could not spot any place where z19 would be still such a visible problem (the rendering is taken on z17), but they are common meeting places, so the name is even more important than for shops. Any other suggestions of improvement?

BTW: how should we avoid duplication of code here? Most of z>17 and z>19 sections are the same, except few labeling statements, and I'm not sure how to make it in the most elegant and readable way.

@pnorman I don't really understand your question (and the problem too, I guess), maybe somebody else could answer?

**Comment by matkoniecz** [comment]
@kocio-pl For start see https://www.mapbox.com/tilemill/docs/guides/metatiles/

**Comment by matkoniecz** [comment]
> For the eating amenities I could not spot any place where z19 would be still such a visible problem

http://www.openstreetmap.org/#map=19/50.06048/19.93860 http://www.openstreetmap.org/#map=19/50.06423/19.93783 ?

**Comment by kocio-pl** [comment]
I didn't say I can't find any problems with amenity labeling. =} Parts of the "Complex amenity area" example also has the labeling problem at z19, but I consider them (and your examples) to be fairly small compared to some shop areas - no need to render again, I guess.

I'm aware of what the metatiles are, but I don't understand what @pnorman asks about them here. What difference could make just relocating of some labels in this context?

**Comment by pnorman** [comment]
I have a strong preference for keeping z17-z19 consistent in rendering rules. 



> What difference could make just relocating of some labels in this context?

If the text placement is shifted in different ways in different metatiles for the same text, it will result in cut off labels.

**Comment by mboeringa** [comment]
> If the text placement is shifted in different ways in different metatiles for the same text, it will result in cut off labels.

How does HOT, or for that matter any other project using Mapnik and this type of more flexible labelling, solve this issue? It seems to me that this type of labelling by itself is quite normal.

> I have a strong preference for keeping z17-z19 consistent in rendering rules.

While I fully understand the difficulties of managing multiple types of rendering and render rules in a style like this one, I do think at some point cartographic output dictates that maintaining the same render rules across three zoom levels, may not be feasible... I can't tell if that is the case here, but three zoom levels is a pretty huge difference in terms of labelling options and label "space".

**Comment by kocio-pl** [comment]
> While I fully understand the difficulties of managing multiple types of rendering and render rules in a style like this one, I do think at some point cartographic output dictates that maintaining the same render rules across three zoom levels, may not be feasible... I can't tell if that is the case here, but three zoom levels is a pretty huge difference in terms of labelling options and label "space".

+1

My primary background in OSM is micromapping and I like the "mappers' map" concept very much, so I care more for showing the data we have than keeping the map surface clean (we have MapQuest Open for this already), so I for one would not object too loud for keeping the smart labeling in the whole POI range. 

But see how serious are people regarding to POI clutter - we even have the separate issue around just one of the rarest places, and the problem is spotted on just one of zoom levels ([Too many icons at z17?](https://github.com/gravitystorm/openstreetmap-carto/issues/1560))! It surprised me a lot that a single, visually moderate - IMO - problem can create such a strong response. So I try to play safe here. My ultimate goal is to let people see the basic properties of POIs (type and name) on the map. With smart labeling just on z19 my goal is reached and I see no need to create more clutter at lower zoom levels.

I just treat z19 as a special "last zoom level". If we will eventually get z20 rendering one day, I will check if we still need the smart labeling at all and would move it there, because that would be the last resort for people to see the named POIs on this map.

**Comment by pnorman** [comment]
> How does HOT, or for that matter any other project using Mapnik and this type of more flexible labelling, solve this issue? It seems to me that this type of labelling by itself is quite normal.

I don't know if or if not it will cause problems, which is why I asked. As for other stylesheets, I'm not aware of any which have as many point/center of area based labels.

> While I fully understand the difficulties of managing multiple types of rendering and render rules in a style like this one, I do think at some point cartographic output dictates that maintaining the same render rules across three zoom levels, may not be feasible... I can't tell if that is the case here, but three zoom levels is a pretty huge difference in terms of labelling options and label "space".

There's a few cartographic reasons. One is that you want to keep the map from having too many different overall appearances and feels, drawing emphasis to different features on different zoom levels.

Another reason particularly relevant for POIs is that choosing what **not** to render is an important cartographic choice, and deciding to render everything is often a cop-out to avoid saying no.

In this case, I don't see any reason why z17-z19 can't be the same for text-placements. I can't see anyone mentioning that text-placements has bad results on z17.

**Comment by pnorman** [comment]
We might need to increase the minimum distance between labels

![image](https://cloud.githubusercontent.com/assets/1190866/8402701/81b8126c-1df2-11e5-9bac-8a503b520e22.png)

Right now, all labels are below icons, so it's normally clear what they belong to. In the example above, it's not clear if Matras is the shop to the left or below.

![image](https://cloud.githubusercontent.com/assets/1190866/8402716/b96f3ad2-1df2-11e5-9a69-a2f3ef88ff3b.png)![image](https://cloud.githubusercontent.com/assets/1190866/8402724/d4dd6398-1df2-11e5-91ee-427278c97764.png)

The distance from the icon to text placed on the right seems inconsistent.

**Comment by gravitystorm** [comment]
> I just treat z19 as a special "last zoom level".

Be careful with this. One of the goals of the stylesheet is re-usabiilty, and even without making any changes, other people use these stylesheets on tileservers that have different zoom ranges available. Sometimes it stops at 18. Sometimes 22. So don't make too many assumptions based on what the 2 OSMF tileservers are doing - focus on the cartographic reasons to make a decision instead.

**Comment by kocio-pl** [comment]
@pnorman 

> Right now, all labels are below icons, so it's normally clear what they belong to. In the example above, it's not clear if Matras is the shop to the left or below.

It makes me think a bit longer, but then it's clear to me that it's always centred somehow, so Matras must belong to the POI below. People mark the POIs by hand, so in many cases it will be a useful hint.

> The distance from the icon to text placed on the right seems inconsistent. 

I guess the distance is measured from the whole icon box, not from the visible pixels, so most probably this might be a problem with different width of visible images.

@gravitystorm Thanks for bringing it on the table. As I said, this problem is secondary for me, so I will be happy in both cases of smart labeling (z>17 or z>19). 

We have conflicting values here: straight labeling is more clear, but we lose some important informations, while smart labeling is quite the opposite. Going to z>19 with smart labeling would be kind of practical compromise between those general rules. We can also make another practical compromise: let's check how many deployments of osm-carto do we know and how many levels do they use. If something changes in the future, we can tweak again. 

General rules are good thing, but there are always some practical limits and goals - I believe showing the names is one of very important goals for end users. How we should do this is a matter of weighting the importance of different rules and the costs.

**Comment by kocio-pl** [comment]
> Sometimes it stops at 18. Sometimes 22. 

Is it possible to start using variable called "zmax" maybe? Then we would apply smart labeling always at the very end of the zoom scale, no matter which one is used for given service.

**Comment by pnorman** [comment]
> focus on the cartographic reasons to make a decision instead

Circling back to this, is there a reason **not** to use `text-placements` on more than one zoom level?

**Comment by kocio-pl** [comment]
I [mentioned](https://github.com/gravitystorm/openstreetmap-carto/issues/957#issuecomment-116164342) one reason already: the fear of the clutter at some zoom levels, especially the entry one for such POIs (namely z17). I could not however say if it's "cartographic" or not.

**Comment by kocio-pl** [comment]
Is there still some interest in this solution or is it problematic?

**Comment by daganzdaanda** [comment]
I dislike the big text-dy gap that we need now. So I wouldn't mind changing all the labels to sit on one side (right?) of the icons. 
I don't think that an automated random placement left/right/below will work very well. It would need a lot of "padding" to make sure that it's always clear what is labeled. In the end, we would probably hide more POIs than necessary.

**Comment by kocio-pl** [comment]
There is no way to have consistent gap, because icon shape is within certain matrix (usually 14x14 px), but does not always touch the (bottom) border. Changing the side to some other fixed one does not help this problem, because some shapes are tall and don't touch the left/right border too. Or rather there is a way - we would have to change all the icons to touch given border - but those shapes would be then shifted from the centre and it is just a different problem which may be either better or worse.

I also believe that dynamic placing helps show more than with static placing - or at least not less.

**Comment by math1985** [comment]
I have experimented a bit with left/right placement, but the results were not really legible. With left/right placement, it became very unclear which labels were connected to which icons. Sorry, no screenshot anymore. I therefore think alternating bottom/left/right-labelling is not viable, so I'll close this ticket. Feel free to open a new ticket for other ideas, such as right-only labelling.
