### ISSUE TITLE
amenity=fuel with shop=kiosk is rendered as unknown shop in purple instead of fuel icon

### ISSUE THREAD

**Issue by HostedDinner** [gravitystorm/openstreetmap-carto#963]
Fuel stations which are also tagged with shop=kiosk (prob. also shop=convenience and shop=yes) are rendered as purple dot as unknown shop type. For example: http://osm.org/go/0DaQVor3r

**Comment by daganzdaanda** [comment]
> Perhaps a combined Icon would be best.
I don't think that the fuel pump and shopping cart would work combined. They need to be a certain size to be discernible.

I'd prefer that amenity=fuel overrules any shop value. So only show the nice new fuel pump.
If someone wants to know if there's a shop in a petrol station, it's still in the data and could be searched or displayed with specialized tools.

**Comment by Theodin** [comment]
I found an occurrence of this and wanted to post an issue but its already here so I am just adding my voice tot his bug report. btw, its noth the [buiding=yes tag](http://www.openstreetmap.org/way/126257025) but indeed the [shop=* tag](http://www.openstreetmap.org/node/293784400) which is causing this.
