### ISSUE TITLE
Font requirements

### ISSUE THREAD

**Issue by SomeoneElseOSM** [gravitystorm/openstreetmap-carto#999]
There's a doc

https://github.com/gravitystorm/openstreetmap-carto/blob/d778979732b8d775de77ff4c3b663ed25dc0b981/INSTALL.md

which describes which Ubuntu packages should be needed to install all required fonts.

However, when I ran "generate_tiles.py" (which seems to want all fonts in the stylesheet to be actually installed) recently, it complained about a number of them:

Mukti Narrow Bold
TSCu_Paranar Bold
TSCu_Paranar Italic
TSCu_Paranar Regular
Unifont Medium

Although the stylesheet isn't here, the source I suspect is:

https://github.com/gravitystorm/openstreetmap-carto/blob/1fe21083ae1d5b745c1b4120cf098056f248451e/style.mss

and that does still reference those.

Is the duplication (with different case) of "Unifont Medium" deliberate (perhaps for different OS support), and is the mapnik.xml resulting from a "carto" export even supposed to work out of the box with "generate_tiles.py"?

Are the "missing" fonts perhaps differently named or available from elsewhere in Ubuntu 14.04?

(for the avoidance of doubt note that I'm not exporting directly from TileMill; I know that has (other) issues).

**Comment by pnorman** [comment]
We've completely redone the fonts. Warnings are still generated, which is unfortunate, but what happens when fonts change names.
